### ISSUE TITLE
Hard limit on number of states in save should be removed

### ISSUE THREAD

**Issue by Jacob-Barhak** [holoviz/panel#1009]
When saving a holoviews object with more than 1000 states after combining all slider/listbox widget options, there is a hard limit set in the save command than raises a exception and prevents generating a plot. 
Here is an example of such an error message:
````
...
File "C:\Users\Work\Anaconda2\envs\dev\lib\site-packages\panel\io\embed.py", line 141, in embed_state
    len(cross_product))
RuntimeError: The cross product of different application states is too large to explore (N=1050), either reduce the number of options on the widgets or increase the max_states specified on static export.
````

First the error message can be improved to explain the user that the max_states is an option in the save command. However, there is no reason for this limit unless some memory / compute bound is reached. 

It does take a long time to generate files of this size, yet a warning and a progress bar may be a better approach rather than a placing a hard limit on the user that throws an exception. On the long term hard limits like number of columns on a spreadsheet become a problem. 

This issue is here to open this discussion and hopefully deprecate the max_states in future versions after turning it into a warning first rather than a hard stop.

**Comment by philippjfr** [comment]
We'll have to disagree about the definition of a hard limit here since it can be changed. If we change the error/warning we should also take care to say that `save` is only one case where this limit might have to be set.

The reason we added this was because we did not want users to think their export was broken and in the vast majority of cases I would recommend a user serves the app using bokeh server rather than exporting more than 1000 states. The decision was therefore made that if they cross this limit a user should be forced to think about what they are doing and make a deliberate decision to override this limit. Whatever we decide an improved error/warning message should explain the trade-offs.

One thing we should definitely do here is update the error message to be clearer, additionally we should do some of the following:

1) Change the error to a warning
2) Make the limit globally configurable on `pn.config`
3) Add a progress bar for `.save`

@jbednar thoughts?

**Comment by philippjfr** [comment]
>This issue is here to open this discussion and hopefully deprecate the max_states

Hard veto on me for deprecating `max_states` entirely, a user should absolutely be forced to consider what they are doing is appropriate if they run into this limit. Embedding is a nice feature but it has it's limits and a user should be made aware of those. If users decide that they understand the limitations and issues and still want to exceed it we should provide a way for them to override those limits permanently, e.g. in an rcfile that sets pn.config options.

**Comment by jbednar** [comment]
I also strongly reject the idea of removing max_states; it is there for a reason.  It is very easy to naively ask for embedding a state space larger than the number of atoms in the universe!  I agree that the configuration and messaging could be improved (though it already seemed pretty clear to me :-). 

I don't have a strong opinion about whether it should remain an error or whether it should simply warn that the maximum has been reached and embed no further states. I think where it really matters is on batch (unattended) operation such as generating HTML reports in CI systems.  Is it better that such a system generate partial output rather than none, or is it better that it be an error so that people realize that it's a problem?  I think I favor reporting that the max has been reached, as a warning, but not aborting, and instead embedding a smaller space.

**Comment by Jacob-Barhak** [comment]
Ok Philipp,  Ok James,

Your hard veto may go away once Moore's law continues. You see, computing
power was growing exponentially for many years and and peta byte
computation is not that uncommon as it was before. Moore's law may be
slowing down,  yet parallelization is easier now,  so compute is easier
overall.

We agree on warnings rather than a hard stop. And if you want to leave this
as as option rather than a hard coded number to initiate warming,  it also
makes sense. Although I like the idea of deprecating this parameter in the
future in a save and putting it in some options file that will update every
few releases when computing needs will change.

Just to give you an example from own experience. In my system I have 6
dimension options hard coded  when I designed it.  I am very sorry about
this limit now after a decade and had to bypass it in all sorts of ways.

Your design is better , yet you choose to limit yourself by stopping the
user. I gave the example of Microsoft doing the same thing when designing
spreadsheets. And after a decade or two it became a bad idea.

I suggest you let hardware and systems limit the user,  not your own
system.

And what you think as a large file today may become tiny a decade from now.

I noticed you are conservative with space. To put you into perspective,  I
currently generate ~24mb  124mb files with your system. And although I
would like those to be more compact,  it is worthwhile for me to have files
in that size if it means that the file is self contained and reproducible
and static in the sense of not needing to spin a server.

Recall that a static file is reproducible on its own while if I spin
server,  it depends on multiple versions which becomes a version control
issue. Recall our conversation on python versions stopped being supported.
In a few years from now I want to be able to see the results I produced
without needing to fight version issues of systems that are no longer
supported.  The best way to do it is through a static file  - not a server.
And my dimensions will probably grow in the next few years. And I am
already hitting your limits,  and you guys have the best solutions in the
market I know of.

If you want to improve file size, please see if it is possible to improve
the embedded code in the html. I wish I could help there,  yet the learning
is tough there. To be effective, I will see if I can help with adding a
progress bar and turn errors into warnings. I think we agree on this and
solve the current stop.

And to soften the hard vetos I suggest you look at 5G specs and their
predictions on how fast a large file such as an HD move can be downloaded?

My suggestion is not to limit the user in any way,  let other technology
limit the user. The more limitations you add,  the more you make developers
work,  and although we all want developers to be important and the center
of things,  it makes no economic sense. Disk space costs a few cents,
while developer time is much more expensive. So forcing a developer to
develop and maintain a server and deploy it makes much less economic sense
than embedding the server in a large file.

The real question is,  if it is possible to improve the embedded code. I
wish I knew the answer as this will begin optimal solution.

In any case,  your ability to handle multi dimensional data is unique and
should be promoted to support big data visualization.

            Jacob

**Comment by jbednar** [comment]
Technology can only change what the hard limit should be set to, not whether there should be one.  The limit is there to alert people to the fact that they are filling up their hard drive with a file that is very likely to be impractical for anyone to download and use. When people get this message, surely they can just increase the limit, so I don't see what the objection is. I'd be happy for there to be a value like None to indicate no limit, and then anyone who really wants files to be generated up to the limits of the hard drive and CPU time can do so. Meanwhile, the default limit serves to educate people about the very real consequences of trying to embed an enormous state space of plots into an HTML file.

**Comment by Jacob-Barhak** [comment]
Well James,

If you are trying to conserve used time,  then a warning is sufficient -
and we already agree there.

A progress bar will be much better indication to the user than a limiting
parameter. And it is not hard to do. I believe we agreed there as well.

The limiting parameters can stay to avoid breaking code of others,  yet not
be hard limits. Depreciation discussion may return in the future in case of
no need.

To be efficient,  I suggest we discuss if it is possible to parallelize the
file creation process in any way for users with big dara needs that do not
mind the large file sizes.  This way,  no one is harmed and new users will
get new opportunities.

Also,  it if it possible to reduce the size of the generated file anymore?

I know you are trying to keep things efficient, yet some of your potential
users have other needs. As far as I know,  you are the only visualization
tool set addressing high dimensional plots in python and offer a static
document. Might as well explore how to improve this capability.

If your users data can fit into a file,  you want to offer then the ability
to make it interactive without a specialized server. It really helps
reproducibility.


         Jacob

**Comment by Jacob-Barhak** [comment]
This issue is currently resolved by https://github.com/holoviz/panel/pull/1017  and by https://github.com/holoviz/panel/pull/1021 . The hard problem was resolved and therefore the issue should be closed. yet it is worthwhile to still discuss if it is at all possible to reduce the footprint of the large files somehow and make their construction more efficient.
