### ISSUE TITLE
Document best practices for profiling Panel apps

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1010]
## My Pain

You can do a lot of things in Panel and also create rather large applications. But right now there is really no documentation on how to identify bottle necks in your application.

Furthermore performance is one of the main considerations when comparing to the alternatives like Streamlit, Voila, Dash and JS Frameworks. Especially since low performance is one of the things that is a general comment in blog posts on Bokeh. And also because Voila looks very, very fast compared to the competitors according to what I have seen. In Voila moving a slider updates the charts instantanously. Thats not the case of Panel or any of the other competitors.

So being able to create performant Panel apps are very important.

I think it would be very helpfull to create to some documentation on how to best profile your Panel apps.

## Solution

Create documentation on profiling Panel apps to include in the Panel documentation. Maybe it's really just providing a few links to other resources. But I don't know yet as I have not tried this yet.

### Accept Criteria

- Easy to use
- Can identify bottlenecks both on server and client.

## Alternative Solutions

Alternatively someone could write a blog post or I could add something to the documentation of awesome-panel.org similar to https://awesome-panel.readthedocs.io/en/latest/vscode.html

**Comment by philippjfr** [comment]
The performance and debugging user guide covers profiling now: https://pyviz-dev.github.io/panel/user_guide/Performance_and_Debugging.html

If you see something missing from it please open a PR or issue for that specific thing.

**Comment by LinuxIsCool** [comment]
The above link is now 404 but you can find a collection of resources on performance here: https://panel.holoviz.org/how_to/index.html#test-and-debug
