### ISSUE TITLE
Document best practices for testing Panel Apps

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1011]
## My Pain

You can do a lot of things in Panel and also create rather large applications. But right now there is really no documentation on how to test your Panel applications.

I can see from the Panel code that there are some helper fixtures for example when testing the panes. And I'm also curious on thoughts on what to test.

It would be nice to have some documentation on how to test Panel apps. 

Maybe this is a part of a broader documentation on how to **architect, develop and test Panel apps**.

I'm using the reactive API with `param.Parameterized` classes. So thats where my personal interest primarely is.

## Solution

Add documentation on best practices for testing Panel Apps.

## Alternative Solutions

Someone could wrote a blog post. I could write something and add it to the documentation for awesome-panel.org similar to https://awesome-panel.readthedocs.io/en/latest/vscode.html

**Comment by philippjfr** [comment]
You contributed some great documentation on testing so I'll close.
