### ISSUE TITLE
pn.widgets.CrossSelector not working correctly anymore

### ISSUE THREAD

**Issue by SandervandenOord** [holoviz/panel#1016]
I updated to new versions and now my CrossSelector is not functioning correctly anymore:
After moving features from right to left or left to right, you can't see the selected features anymore.
See code below and image.

panel==0.8.0rc2.post1+ge4f5887
datashader==0.10.0.post2+g138b86c
holoviews==1.13.0a22.post2+g9549d8bae
hvplot==0.5.2.post15+g856ee5e
param==1.10.0a2
jupyterlab==1.2.4
pandas==1.0.0rc0

![image](https://user-images.githubusercontent.com/7305600/73162890-16acb480-40ef-11ea-9698-05dcece5e9e2.png)

Simplified code example:
```python
import panel as pn
pn.extension()
import param

FEATURE_LIST = ['a', 'b', 'c', 'd', 'e']

class WellExplorer(param.Parameterized):
    selected_features = param.ListSelector(
        default=['a', 'b'],
        objects=FEATURE_LIST,
    )

well_explorer = WellExplorer()

pn.Row(pn.Param(
    well_explorer.param['selected_features'],
    widgets={'selected_features': pn.widgets.CrossSelector}
))
```

**Comment by philippjfr** [comment]
This was fixed here: https://github.com/holoviz/panel/pull/999/files#diff-87b2e1e1f0c16af20b93933546abcce6R427
