### ISSUE TITLE
Make it much easier to provide progress/ activity to the user

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1039]
#### My Pain

I wan't to develop awesome analytics applications in Python. And I'm hoping Panel can provide this.

One pain i'm experiencing is that it **feels** slow compared to for example streamlit or applications developed in a JS framework. I've discovered that it is actually often a feeling. And the cause is that the other applications have a lot of progress/ activity reporting. They trick my brain and keep it activated.

In panel it's difficult to use the progress bar. You have to think about an architecture for how to use it when changing things in your page or running calculations.

I would like it to be very, very easy to report the progress and activity to the user

#### Solution

- Lower the friction of using the progressbar to report on server activity.
- Make it possible to report that the client/ front layout engine or similar is working as well.

I think the solution is to improve the functionality, improve the documentation and provide some great examples.

A simple solution is to provide a spinner that spins when ever there is activity in the front or backend and hides at other times.

#### Additional Context

In the gallery at awesome-panel.org I have experimented and created a ProgressBar extension that makes lowers the friction a bit. it can be used as inspiration.

Key elements

- "Activity Queue with progress value and message". I would like to enable multiple ques in the future.
- Can be used as function, context manager and annotation

![image](https://user-images.githubusercontent.com/42288570/73397229-5b993c80-42e3-11ea-9a6e-f0e9e9f7cff2.png)

**Comment by hyamanieu** [comment]
This could be closed as activity is shown in templates and there are now many widgets to indicate progress & activity.

**Comment by MarcSkovMadsen** [comment]
Thanks
