### ISSUE TITLE
Layout all plotting libraries the same

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1043]
#### My Pain

I want Panel to be awesome and easy to use. One small friction point is that the supported plotting libraries holoviews, altair and plotly are not layout in the same way.

The implication is more to learn and remember and that you have to spend time when changing or experimenting with your plotting library. And you are in doubt if choosing something else than Holoviews which seems the most supported/ polished is a good idea.

A layout example is shown below.

![image](https://user-images.githubusercontent.com/42288570/73422008-e1d77200-4327-11ea-88c7-92a91497f66d.png)

```python
import panel as pn
import altair as alt
import pandas as pd
import plotly.express as px
import hvplot.pandas


pn.extension("altair")
pn.extension("bokeh")
pn.extension("plotly")

data = {
    "x": list(range(1, 1000)),
    "y": list(range(1, 1000)),
}

dataframe = pd.DataFrame(data)


altair_plot = (
    alt.Chart(dataframe.reset_index())
    .mark_line()
    .encode(alt.Y("y", scale=alt.Scale(zero=False)), x="x")
    .properties(width="container", height=300,)
)
plotly_plot = px.line(dataframe, x="x", y="y", height=300)
plotly_plot.layout.autosize = True

hv_plot = dataframe.hvplot(x="x", y="y", height=300)
hv_plot = pn.pane.HoloViews(hv_plot, sizing_mode="stretch_width")

pn.Column(
    altair_plot, plotly_plot, hv_plot, sizing_mode="stretch_width", background="gray",
).servable()
```

#### Solution

Make the same margin around the plots. And preferably remove it if possible.

#### Additional Context

I know this is a tiny detail. But its details like this that creates friction and overhead. And uncertainty in whether Altair and Plotly are truly supported.

So it's not must have. But nice to have one day.

(I actually created this example because when I started out with Panel I had the feeling that Plotly was slow compared to Holoviews. And I did not know if the cause was Panel or Plotly. But this example does not support the feeling that Panel or Altair is slower than HoloViews).

**Comment by philippjfr** [comment]
I consider this out of scope to be honest, the amount of tweaking to get all plotting libraries is endless and an ever moving target.
