### ISSUE TITLE
Please increase the max size for image upload to Discourse

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1057]
#### My Pain

When I create a post in Discourse I often wan't to illustrate my idea, question or announcement using a video .gif because *a picture says more than a thousand words. And a .gif video even more*.

Right now the file size is constrained (<5 MB ?) and if I upload something around 5 MB the image is turned into a small thumbnail that cannot be seen.

Normally my videos are in the range 3-7 MB.

The result is that I have to spend a lot of time re-recording videos or editing them. And this is a slow and tedious process.

#### Solution

Increase file size to 7.5MB and never convert to thumbnail. If size/ storage is not a problem then increase to 15 MB. Then I (and others, I believe) would never have problems.

**Comment by philippjfr** [comment]
Bumped both image and upload sizes:

<img width="690" alt="Screen Shot 2020-02-01 at 2 52 37 PM" src="https://user-images.githubusercontent.com/1550771/73593272-89a89780-4502-11ea-90ed-88956facfe1c.png">

**Comment by philippjfr** [comment]
Please reopen if you have issues, as the description says I may have to bump the limit in apache as well.

**Comment by MarcSkovMadsen** [comment]
I tried uploading a 13 MB .gif. That did not work for some reason.

![image](https://user-images.githubusercontent.com/42288570/73602359-17bc6680-4573-11ea-9a09-25dcdcf6e091.png)

**Comment by MarcSkovMadsen** [comment]
I also uploaded a 5977KB file and that worked.
