### ISSUE TITLE
The param reference example contains warnings and some unexpected output

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1058]
I took a look at https://panel.holoviz.org/reference/panes/Param.html#panes-gallery-param

And I can see it contains warnings and some unexpected expected.

I've created the reference example originally. But when I see this I believe it has something to do with the way the static file is produced? So right now I don't know how to fix this?

@philippjfr ?

![image](https://user-images.githubusercontent.com/42288570/73587609-7a075f80-44be-11ea-875a-be51ebc86b8f.png)

**Comment by philippjfr** [comment]
We releases a dev release of param which finally starts enacting some of the major API cleanup we've been working towards and the docs are built against that. We simply need to update set_params to .param.set_params.
