### ISSUE TITLE
The Markdown pane does not handle indented docstrings well

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1062]
#### System Info

- Panel: 0.8.0
- Bokeh: 1.4.0
- Tornado 5.1.11
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### My Pain

I have a lot of semi-automated tests for awesome-panel.org where I manually inspect how things look.

In order not to repeat my self, my docstrings for the test are also output to the user as a checklist. But these does not look nice if I output them using the `pn.layout.pane`.

![image](https://user-images.githubusercontent.com/42288570/73602898-95847000-457b-11ea-9ddd-87928b8ab937.png)

More generally is that the Markdown pane after upgrade to Panel 0.8.0 supports code highlighting but indented markdown is report as an `err`.

I believe this should not happen as indented markdown is a common use case when defining multiline strings inside functions.

#### Reproducing Example

```python
import panel as pn


def view():
    output = """We test that

    - A "Header is shown"
    - The background is blue
    - The sizing_mode is "stretch_width" by default. DOES NOT WORK CURRENTLY
    """
    return pn.pane.Markdown(output)


view().servable()
```

![image](https://user-images.githubusercontent.com/42288570/73602940-1a6f8980-457c-11ea-8145-91defd0f3004.png)

**Comment by MarcSkovMadsen** [comment]
I tried to test the different combinations of indented text that I see.

As you can see the `output` and `output1` text is not formatted nicely.

```python
import panel as pn
from awesome_panel.express import Markdown
import textwrap

wrap = textwrap


def view():
    output = """We test that

    - A "Header is shown"
    - The background is blue
    - The sizing_mode is "stretch_width" by default. DOES NOT WORK CURRENTLY
    """

    output1 = """We test that

    - A "Header is shown"
    - The background is blue
    - The sizing_mode is "stretch_width" by default. DOES NOT WORK CURRENTLY

    ```python
    def my_func(a):
        a +=1
    ```
    """

    output2 = """
    We test that

    - A "Header is shown"
    - The background is blue
    - The sizing_mode is "stretch_width" by default. DOES NOT WORK CURRENTLY

    ```python
    def my_func(a):
        a +=1
    ```
    """

    output3 = """\
    We test that

    - A "Header is shown"
    - The background is blue
    - The sizing_mode is "stretch_width" by default. DOES NOT WORK CURRENTLY

    ```python
    def my_func(a):
        a +=1
    ```
    """
    return pn.Column(
        pn.pane.Markdown(output),
        pn.layout.Divider(),
        pn.pane.Markdown(output1),
        pn.layout.Divider(),
        pn.pane.Markdown(output2),
        pn.layout.Divider(),
        pn.pane.Markdown(output3),
    )


view().servable()
```

![image](https://user-images.githubusercontent.com/42288570/73603196-ce264880-457f-11ea-83cf-54687731ea0b.png)

**Comment by MarcSkovMadsen** [comment]
Maybe the solution is just to say the indented text in the form of `output` and `output1` is just not best practice and is not supported. 

If thats the decission then the above example could maybe in some form be added to the documentation at https://panel.holoviz.org/reference/panes/Markdown.html#panes-gallery-markdown

Add the same time it could be documented that Markdown now supports code highlighting.

**Comment by philippjfr** [comment]
Yes, the problem is your formatting in `output` and `output1`. It's not that it's not fully supported, in fact it's doing exactly what you'd expect, it's that you are not being consistent about the indentation, this is **standard** Markdown behavior. Maybe it's clearer why it's wrong when you print `output`:

```
We test that

    - A "Header is shown"
    - The background is blue
    - The sizing_mode is "stretch_width" by default. DOES NOT WORK CURRENTLY
```
