### ISSUE TITLE
Please support concept of Layout Extension

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1072]
This is a discussion (for now)

#### My Pain

I like to use the reactive api and compose my app from what I call reuseable components.

An example of a component is

```python
import param
import panel as pn

class MyComponent(param.Parameterized):
    value = param.Number()

    def view(self):
        return pn.Column(
            "# Component X",
            self
        )

MyComponent().view().servable()
```

![image](https://user-images.githubusercontent.com/42288570/73838259-90415280-4813-11ea-9094-924f8a675746.png)

My pain is really that the concept of component is something I have from JS/ Angular. It's not really something I see defined in the Panel documentation. 

Furthermore I don't think it's really supported because I would really like the user of the component to just instantiate my component as `component = MyComponent()` instead of `component = MyComponent().view()`. So I have tried to inherit from for example `Column` but I found out that it is buggy ([issue 1060](https://github.com/holoviz/panel/issues/1060)).

I don't think my component is a `pane` or `layout` as it does not satisfy the definitions. Maybe it's a `widget`. But I don't think so either. To me widgets are atomic. The components are larger and composed.

#### Solution

So my suggestion is

- Define a concept of component.
- Provide the functionality to define them
- Provide some documentation and examples.

**Comment by MarcSkovMadsen** [comment]
When constructing the *component* I might provide one or more *models* or *services* as Im layering my app into models, services, plots and components.

- The models are primarely *data models* with some methods for converting back and from string, dicts etc.
- The services provides ETL functionality and various business logic.
- I have a seperate plotting layer because this is usefull on its own and because I would be nice to be able to easily change between holoviews, plotly, altair libraries etc.

**Comment by jbednar** [comment]
This sounds like a good idea to me.  To me it seems like your component would be a layout, which is a composition of atomic elements or other layouts, right?  But I agree that we should have a straightforward way to define custom classes like that, with the class required to override only a single method to populate the layout.  @philippjfr ?

**Comment by MarcSkovMadsen** [comment]
Thanks @jbednar 

To me this is not a Layout because it's not for "wrapping external viewable items". But maybe it's just the *definition* below that should be more precious. I just need a commonly accepted language to express my self and discuss on github, in my code and its documentation, at awesome-panel.org etc. And to convey the architecture of my apps to colleagues.

To me the example is closer to a widget than a Pane or Layout. But I think it's something distinct ... it's a component :-).

--- 

From https://panel.holoviz.org/user_guide/Components.html

Panel provides a wide range of components for easily composing panels, apps, and dashboards both in the notebook and as standalone apps. The components can be broken down into three broad classes of objects:

- **Pane objects** allow wrapping external viewable items like Bokeh, Plotly, Vega, or HoloViews plots, so they can be embedded in a panel.
- **Widget objects** provide controls that can trigger Python or JavaScript events.
- **Panel layout objects** allow combining plots into a Row, Column, Tabs or a Grid.

**Comment by jbednar** [comment]
> To me this is not a Layout because it's not for "wrapping external viewable items". 

You mean, it is not a Pane?  I'm arguing for Layout, not Pane.

**Comment by MarcSkovMadsen** [comment]
I mean its not a Pane or a Layout. It's not a Layout because a for example the "component" above is not intended to "allow combining plots into a Row, Column, Tabs or a Grid".

**Comment by MarcSkovMadsen** [comment]
Haishori asks on Discourse how to create [self contained custom panels](https://discourse.holoviz.org/t/how-to-create-a-self-contained-custom-panel/985).

He needs the same as I do :-)

**Comment by MarcSkovMadsen** [comment]
This issue is also very much related to the project on Panel Extensions I've started. See https://discourse.holoviz.org/t/how-to-create-panel-extensions/980 and https://github.com/marcskovmadsen/panel-extensions-template.

**Comment by MarcSkovMadsen** [comment]
I would like to change this from a discussion to a feature request. 

Should we just change the labels? Or should we create a new Feature Request?

**Comment by MarcSkovMadsen** [comment]
One idea could be to add a mixing called `ExtensionMixin` when inheriting.

```python
class CustomComponent(pn.Column, pn.ExtensionMixin):
```

That could automatically 

- add new parameters to the `_rename` attribute
- make it possible to make the layout readonly for some use cases.
- solve other not yet identified issues.

**Comment by MarcSkovMadsen** [comment]
I now have a working example of a Layout Extension based on a `pn.Column`. 

![image](https://user-images.githubusercontent.com/42288570/88450235-c6b86b80-ce4d-11ea-9258-77a2e32851a9.png)

```python
"""The DataFramePlotter is an example of a Composable Extension for Panel

It was initially proposed by Haishiro and discussed in [Discourse 985]\
(https://discourse.holoviz.org/t/how-to-create-a-self-contained-custom-panel/985)
"""
import matplotlib.pyplot as plt
import pandas as pd
import panel as pn
import param
import seaborn as sns


class DataFramePlotter(pn.Column):
    """Extension Implementation"""
    column = param.Selector()

    def __init__(self, data, **params):
        # The _rename dict is used to keep track of Panel parameters to sync to Bokeh properties.
        # As column is not a property on the Bokeh model we should set it to None
        self._rename["column"] = None

        super().__init__(**params)

        self._plot_pane = pn.pane.Matplotlib(background="blue", sizing_mode="stretch_both")
        self[:] = [self.param.column, self._plot_pane]

        # Please note that the alternative of setting
        # @param.depends("column", watch=True)
        # on _update_plot_pane does not work.
        # See https://github.com/holoviz/panel/issues/1060
        self.param.watch(self._update_plot_pane, "column")

        columns = data.columns.values
        self.param.column.objects = columns
        # I need to set self.column to show a plot initially
        self.column = columns[0]

    # Make sure you don't use a function name already used by the Parent class.
    # For example _update_model is used by the Parent Class.
    def _update_plot_pane(self, _):
        # - I get exception if plt.close is below ax line. See https://github.com/holoviz/panel/issues/1482
        # - The plot does not change if I remove plot.close() fully.
        plt.close()

        ax = sns.distplot(df[self.column])
        self._plot_pane.object = ax.figure

if __name__.startswith("bokeh"):
    # Use the extension
    df = pd.DataFrame(data={"x": [1, 2, 3, 4, 5, 6, 7], "y": [1, 2, 2, 4, 5, 9, 7]})
    DataFramePlotter(df, width=300, height=300).servable()

```

**Comment by MarcSkovMadsen** [comment]
**Summary**

I can create Panel extensions that inherits from panes or layouts if I am careful. I have concrete examples working for `HTML`, `Markdown` and `Column`.

What I would like to know is

- Should I and others create Panel Extensions by inheriting in this way?

If yes

- Could and should we make it easier? How?

If no

- What should we do instead?

(Same questions for https://github.com/holoviz/panel/issues/1494 and https://github.com/holoviz/panel/issues/1483).

To me these questions are important to get answered because 1) My personal code base is growing and might need refactoring based on the answer 2) I am guiding users to best practices on discourse 3) I am describing best practices in the Awesome Panel Extensions Guide.

FYI. @philippjfr @jbednar

**Comment by MarcSkovMadsen** [comment]
I close this one as the `Viewer` component now supports the concept.
