### ISSUE TITLE
Warn if JupyterLab extension is not installed

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#1078]
Often users forget to install the JupyterLab extension and things appear to work but none of the comms work. We should probably add a message to warn about this which the JupyterLab extension will filter out before publishing.

**Comment by michaelaye** [comment]
There's none mentioned in the panel README? I'm asking because I find the panel.interact not working in JLab despite having the bokeh extension installed. is there another one that's missing? Works fine in the notebook.

**Comment by philippjfr** [comment]
Panel requires pyviz extension, not the bokeh extension:

```
jupyter labextension install @pyviz/jupuyterlab_pyviz
```

Adding it to the READMe makes sense to me as well. It's currently just on the homepage.

**Comment by michaelaye** [comment]
thanks. i can put it on the readme.

**Comment by philippjfr** [comment]
Awesome, thank you!

**Comment by philippjfr** [comment]
Since the JLab extension is now bundled into the `pyviz_comms` package it is no longer possible to forget to install it.
