### ISSUE TITLE
AttributeError: type object 'extension' has no attribute '_loaded'

### ISSUE THREAD

**Issue by bstadlbauer** [holoviz/panel#1094]
#### ALL software version info (this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

```
python=3.6
git+https://github.com/holoviz/panel@7c6b2cc1f98ed0158da6e4d9e0bf645876b42c42
holoviews==1.12.7
pyviz_comms==0.7.3
```

#### Description of expected behavior and the observed behavior
When calling `pn.extension(pn.extension(raw_css=[css]))` the error from the description happens.

#### Complete, minimal, self-contained example code that reproduces the issue

```sh
python -c 'import panel as pn; import holoviews as hv; hv.extension("bokeh"); pn.extension(raw_css=["foo"])'

```

#### Stack traceback and/or browser JavaScript console output
```sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/bstadlbauer/miniconda3/envs/panel-bug/lib/python3.6/site-packages/param/parameterized.py", line 2812, in __new__
    return inst.__call__(*args,**params)
  File "/Users/bstadlbauer/miniconda3/envs/panel-bug/lib/python3.6/site-packages/panel/config.py", line 288, in __call__
    if not hv.extension._loaded:
AttributeError: type object 'extension' has no attribute '_loaded'
```

**Comment by philippjfr** [comment]
Indeed sounds like a bug, but why call the extension twice like you're doing? Guess it's just for illustration purposes?
