### ISSUE TITLE
Add Panel to anaconda-community Site

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1104]
I think Panel should be added to the site

https://www.anaconda.com/anaconda-community/

next to Bokeh and HoloViews.

**Comment by MarcSkovMadsen** [comment]
One reason to add them is that Panel would appear more approved and supported. Making it easier to get it white listed as a technology in an enterprise.

In general it would also just inspire people to check out panel and help increase the adoption I think.

**Comment by jbednar** [comment]
I've requested that, but the website is currently being overhauled, so they may not be ready to make changes to older content.
