### ISSUE TITLE
Add perspective widget

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1107]
I discussed with @ceball that we should add support for [Perspective](https://perspective.finos.org/)

Perspective is a nice and very performent (I believe) widget for exploring large amounts of data and for streaming data. It's originally developed at JP Morgan.

It would enable providing advanced interactive exploration of large data sets and streaming data sets in a way thats highly customizable by the user.

![image](https://user-images.githubusercontent.com/42288570/74803929-fa132f00-52de-11ea-892f-9890f0620c86.png)

#### Additional Context

Perspective also has a high performent PerformanceManager that can run in Tornado and communicate large amounts of data incrementally between front end and back end using the Arrow format. Maybe it would actually perform better than Bokehs data transfer. Something to try out?

**Comment by MarcSkovMadsen** [comment]
As you can see just above I've created a request to support Panel in the Perspective Repo. Maybe this can lead to interest, ideas, support, code etc.

**Comment by timkpaine** [comment]
We'll continue discussion with @ceball on https://github.com/finos/perspective/issues/942

One thing we wanted to highlight (not specific to Perspective) is the complete duplication of libraries. Perspective is currently tethered to ipywidgets built on traitlets targeting voila, whereas panel has its own widgets and is built on param and bokeh server. In an ideal world, we wouldn't be writing the same libraries over and over again, requiring contributed libraries (e.g. perspective) to pick one or the other.

**Comment by jbednar** [comment]
Alas, that's at least partly our fault. We created Param in 2003, long before Traits and Traitlets and Bokeh Properties, but we were academics trying to publish papers, not software, so we didn't try to promote it much outside our group. In the interim it was reinvented several times, and is probably even today being reimplemented somewhere in the world.  

The good news is that in Bokeh 2.0 (due in the next few days!), everything should play nicely together, with Bokeh server working just fine with ipywidgets, and voila working just fine with Bokeh widgets. So I don't think the consequences of choosing one or the other should matter as much, very soon.

**Comment by ceball** [comment]
Yes, bokeh 2 + ipywidgets_bokeh is great! The standard ipywidgets plus various 'custom widgets' I tried seemed to work fine. Admittedly not perspective's ipywidget when I tried that briefly, but I only recently started with perspective and have so far only been able to build parts of it (the python and c++; the "javascript" side still fills me with fear...), so haven't been able to debug that yet.

I haven't had enough practical experience yet to say, but Philipp has previously pointed out the main downside of ipywidgets_bokeh is the additional javascript bundle size.

**Comment by jbednar** [comment]
> main downside of ipywidgets_bokeh is the additional javascript bundle size.

I _think_ that's only a downside for Bokeh users, as Voila users will encounter that bundle size already.   I'm not sure what the downsides are in the other direction, i.e. the cost for an ipywidgets user of incorporating something using Bokeh widgets.

**Comment by MarcSkovMadsen** [comment]
FYI.

I've started adding support for the `perspective-viewer` web component to Panel.

For more information see https://github.com/holoviz/panel/pull/1122#issuecomment-596169367

**Comment by MarcSkovMadsen** [comment]
Just for the record. The basic functionality for the `perspective-viewer` has been implemented and is working well. The things that I would expect not working are streaming and getting selected rows back. But the rest I would expect to work just fine.

![perspective](https://user-images.githubusercontent.com/42288570/77223084-ab64e900-6b59-11ea-91ca-facb7c79f76d.gif)

**Comment by MarcSkovMadsen** [comment]
FYI. I've added an example to the gallery at awesome-panel.org

![test_perspective](https://user-images.githubusercontent.com/42288570/82760051-74c57c00-9df1-11ea-9713-b3a5be3eba78.gif)

**Comment by MarcSkovMadsen** [comment]
In the dream scenario Panel would support the use cases demonstrated in this videos

https://www.youtube.com/watch?v=IO-HJsGdleE

**Comment by philippjfr** [comment]
Added in Panel 0.11

**Comment by dmquant** [comment]
I am using panel to manage my data catalogs and visualization. Just wondering is there any way to update the perspective data and configurations after data changes? I have tried .param.update(**kwargs), but it seems does not work.

**Comment by MarcSkovMadsen** [comment]
Hi @dmquant 

Try asking your question in the discourse forum. That is meant for user support. Thanks.
