### ISSUE TITLE
Enable filtering on DataFrame widget

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1108]
#### My Pain

I have a dataframe of 20.000 rows as output of my calculation. My users would like to explore this data.

I provide some aggregates and some plots but I can see that my users also want to explore the data in a table where they can sort and filter on some of the columns.

As far as I can see the `pn.widgets.DataFrame` does not enable filtering.

#### Solution

Implement functionality for filtering on the `pn.widgets.DataFrame`

#### Alternatives

Implement functionality for downloading datasets enabling my users to work with it in Excel.

My dataset is too large to be base64 encoded so I cannot use the workaround described here https://github.com/holoviz/panel/issues/839

There is a pull request for a FileDownload widget here https://github.com/holoviz/panel/pull/915. That would also be a  solution.

Regarding file download the best thing would to be able to deliver an url endpoint with search parameters for my users that they can connect to in excel and run a simple "refresh" when needed.

#### Additional Context

With the qgrid you can filter and sort https://github.com/quantopian/qgrid

With the perspective widget you can filter and sort https://perspective.finos.org/. There is a request to add this here https://github.com/holoviz/panel/issues/1107

**Comment by philippjfr** [comment]
Both `DataFrame` and `Tabulator` now have filtering APIs, it might be nice to make that possible on the UI side though.

**Comment by hyamanieu** [comment]
In the case of Tabulator, wouldn't it possible to simply enable `filterHeader` for all columns: http://tabulator.info/examples/4.9#filter-header ?

**Comment by philippjfr** [comment]
We now support Tabulator header filters too.
