### ISSUE TITLE
Enable a Panel app to serve or appear to serve a REST api

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1119]
#### My Pain

I would like to serve dynamically generated documents like text, csv, excel, json, images at url endpoints that include search parameters.

I would like to expose my functions, models, plots etc. as REST api endpoints with get, post, put, patch and delete methods.

I would the api endpoints to appear on the same url as my Panel app. I.e. the app at for example `example.com` and the api at `example.com/api`.

I would like the functionality to auto-generate Open API/ Swagger API documentation so that it is easy for developers to understand the api and easy to use with C#, Angular etc. as it can automatically generate the boiler plate code needed.

#### Solution

Enable panel to use to serve REST Api Endpoints.

#### Alternative Solution

Don't provide this a functionality as a part of Panel but instead provide some documentation to a best practice solution like Fast API, Django REST Api, Flask or similar. Or maybe a pointer to how the already running Tornado server can be used.

If this is the solution please also describe how to integrate this with the Panel app. I.e. that they are using the same url. Maybe Panel could just do the reverse proxying?

example.com/
example.com/api

One thing I would like described is really the integration with `param`. I.e. if I have `param.Parameterized` model. How to I extract the data? Do I use SqlAlchemy? Can I do that easily that easily? How do I serialize a `param.Parameterized` model? What about security? How would that work and can it integrate with Panel?

**Comment by MarcSkovMadsen** [comment]
@philippjfr . Just some words on your thoughts and how you would do this would be very valuable. Maybe me or some other user could try it out in our own apps, return the learnings and then one day this could be a part of Panel.

**Comment by philippjfr** [comment]
We have a contract in place that will require implementing this so this will happen in the near term.

**Comment by cisaacstern** [comment]
Assuming this enhancement is still pending, but just adding a +1 that this would be an incredible feature which I would definitely use. :smile:

If there's been any headway on this since the last post ~1 yr ago, I'd love to know where to find relevant details.

**Comment by philippjfr** [comment]
This is indeed implemented now but documentation is lacking. Also there are currently only two REST providers built on tranquilizer and serving param.Parameterized instances. If you could describe your use case that would be very helpful.

**Comment by cisaacstern** [comment]
Awesome, @philippjfr!

I have a Panel app in which the user selects a `.csv` file containing LiDAR topography data from a directory (with the `Date` parameter), and then sets `Resolution` and `Sigma` parameters to define a regularized and smoothed `numpy.ndarray` as output. This output array can then be downloaded with the `Download array` button:

<img width="1193" alt="Screen Shot 2021-02-12 at 11 46 55 AM" src="https://user-images.githubusercontent.com/62192187/107815304-0d0ce380-6d28-11eb-8512-953c715210a3.png">

I'd like to implement an endpoint that is functionally similar to querying shields.io for a last-commit badge:

> https://img.shields.io/github/last-commit/cisaacstern/lidar-nn?logo=github&amp&style=flat-square

...except that the API parameters are the same as those in the Panel app. So making a `GET` request to the following (hypothetical) url:

> https://my-api.my-domain.com/lidar-nn?date=70&res=250&sigma=1.20

...would return the same output as clicking the `Download array` button in the screenshot above.

If it's relevant, this specific work-in-progress ([repo here](https://github.com/cisaacstern/lidar-nn/blob/main/lidar-nn.py)) runs from a class that inherits from `param.Parameterized`.

The big-picture use case I imagine is providing stakeholders the ability to interact with each step in a multi-stage data transformation. Ultimately, the output of the current app, `lidar-nn`, will be ingested by additional downstream apps, hosted separately. I'd like for these downstream apps to be able to acquire their requisite input arrays by making a `GET` request to an API endpoint.

While I did previously explore the idea of developing all of this functionality into a single mega-app which wraps all of the necessary transformations, from both an intelligibility & maintainability standpoint, it feels much more manageable to discretize these processes into standalone applications, and have them query each-other.

Will be very interested in your thoughts. And please let me know if I've left out any important details or context.

**Comment by cisaacstern** [comment]
I'll add if/when I'm able to achieve this with your guidance, @philippjfr, I will gladly contribute a PR and/or discourse post etc. documenting how it's accomplished!

**Comment by MarcSkovMadsen** [comment]
I believe this can be closed since Panel 0.10 @philippjfr ?

https://blog.holoviz.org/panel_0.10.0.html#REST-APIs

**Comment by Julien76** [comment]
As per [https://blog.holoviz.org/panel_0.10.0.html#REST-APIs](https://blog.holoviz.org/panel_0.10.0.html#REST-APIs) serving a REST api only works when using:

```
 panel serve app.py --rest-provider tranquilizer
```

but it doesn't work for:

```
import panel as pn

from tranquilizer import tranquilize

select = pn.widgets.Select(options=['Cheddar', 'Mozarella', 'Parmeggiano'], value='Cheddar')

def update_cache(event):
    pn.state.cache['cheese'] = event.new

select.param.watch(update_cache, 'value')

@tranquilize()
def order():
    '''I'd like to buy some cheese!'''
    return f"I'm afraid we're fresh out of {pn.state.cache['cheese'].lower()}, sir."

pn.serve(
 select,
  rest_provider="tranquilizer"
)
```

and then executing (assuming the above code is in file named `app.py`):

```
python app.py
```

Will it be possible to add feature parity between `pn.serve()` and `panel server`?

**Comment by maximlt** [comment]
Hi @Julien76, could you please open a new issue?

**Comment by Vbook313** [comment]
> #### My Pain
> I would like to serve dynamically generated documents like text, csv, excel, json, images at url endpoints that include search parameters.
> 
> I would like to expose my functions, models, plots etc. as REST api endpoints with get, post, put, patch and delete methods.
> 
> I would the api endpoints to appear on the same url as my Panel app. I.e. the app at for example `example.com` and the api at `example.com/api`.
> 
> I would like the functionality to auto-generate Open API/ Swagger API documentation so that it is easy for developers to understand the api and easy to use with C#, Angular etc. as it can automatically generate the boiler plate code needed.
> 
> #### Solution
> Enable panel to use to serve REST Api Endpoints.
> 
> #### Alternative Solution
> Don't provide this a functionality as a part of Panel but instead provide some documentation to a best practice solution like Fast API, Django REST Api, Flask or similar. Or maybe a pointer to how the already running Tornado server can be used.
> 
> If this is the solution please also describe how to integrate this with the Panel app. I.e. that they are using the same url. Maybe Panel could just do the reverse proxying?
> 
> example.com/ example.com/api
> 
> One thing I would like described is really the integration with `param`. I.e. if I have `param.Parameterized` model. How to I extract the data? Do I use SqlAlchemy? Can I do that easily that easily? How do I serialize a `param.Parameterized` model? What about security? How would that work and can it integrate with Panel?
