### ISSUE TITLE
Enable adding javascript modules via pn.config.js_files or some alternative

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1124]
#### My Pain

I'm trying to add a `pn.pane.WebComponent` to Panel here https://github.com/holoviz/panel/issues/1120

I can see that often the user or developer of a component needs to import the js dependencies as modules as below

```html
<script type="module" src="https://unpkg.com/wired-slider@2.0.0/lib/wired-slider.js?module"></script>
```

Please note that module is in two places. It won't work without it. You will get errors in the browser console.

#### Solution

Extend `pn.config.js_files` or add `pn.config.js_module_files` functionality to support this use case.

**Comment by xavArtley** [comment]
I don't understand you request.
If you do 
```python
pn.extension(js_files = {"wired_slider": "https://unpkg.com/wired-slider@2.0.0/lib/wired-slider.js?module"}
```
It should already work

**Comment by mattpap** [comment]
> Ok I understand know the type "module" is important

Without it you won't be able to import it from the component and it would be just a global pile of JS and not an isolated module.

**Comment by xavArtley** [comment]
@mattpap the modification should be at bokeh level in Ressource class?

**Comment by mattpap** [comment]
> the modification should be at bokeh level in Ressource class?

We will definitively add support for modules to bokeh, but that will likely happen on top of PR https://github.com/bokeh/bokeh/pull/9614 and it would be useful to positively resolve issue https://github.com/bokeh/bokeh/issues/9731 by then. Though in the meantime panel could add intermediate support on its own. However, it's still preferred to bundle modules together, because of issues with interoperability between dependencies using different module systems, degradation of performance with many modules (especially without HTTP/2 being used) and support for legacy browsers which don't allow modules at all.

**Comment by MarcSkovMadsen** [comment]
Thanks.

My understanding of this stuff is limited though. I’m just trying to get it to Work.

**Comment by MarcSkovMadsen** [comment]
> 
> 
> > the modification should be at bokeh level in Ressource class?
> 
> We will definitively add support for modules to bokeh, but that will likely happen on top of PR [bokeh/bokeh#9614](https://github.com/bokeh/bokeh/pull/9614) and it would be useful to positively resolve issue [bokeh/bokeh#9731](https://github.com/bokeh/bokeh/issues/9731) by then. Though in the meantime panel could add intermediate support on its own. However, it's still preferred to bundle modules together, because of issues with interoperability between dependencies using different module systems, degradation of performance with many modules (especially without HTTP/2 being used) and support for legacy browsers which don't allow modules at all.

Hi @mattpap . I have also read those things but never experienced them. But I guess its because my use cases are relatively simple.

But I think there are two extreme use case to support.

1. Adhoc or simple use in a notebook.  A user has identified some module that can enable him to do something awesome. In this case he just needs to get the module in. He does not need to think about performance or other issues.
2. An advanced web application with many modules and other dependencies. Here the issues you mention would apply.

The above is something I believe ... not know for sure.
