### ISSUE TITLE
Periodic callback don't stop in Django

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#1125]
#### ALL software version info
Python	3.7.6
Panel	8.0
Bokeh	1.4.0
Django	3.0.3
Channels	2.4.0
Windows 10

#### Description of expected behavior and the observed behavior
I'm trying to create a Django site which have a widget with a periodic callback, so a plot is updated every 10 seconds. In principle I have combined two of your examples a [Django example](https://github.com/holoviz/panel/tree/master/examples/apps/django2) and a [periodic callback example](https://panel.holoviz.org/gallery/simple/random_number_generator.html).

I have got this work both with Django's `python manage.py runserver` and Panel's `panel serve panel_example.py`. But I have noticed that when I leave the site without stopping the periodic callback with the widget itself that it keeps running forever in Django, where Panel is running for ~30 seconds. Is there a way to get Django to work like Panel and only run for a small amount of time after a user leave the site?

I have very limited experience with Django and Bokeh interaction so it could be that I'm missing something very obvious or there are better alternatives to what I'm doing.

#### Complete, minimal, self-contained example code that reproduces the issue
See [periodic_example.zip](https://github.com/holoviz/panel/files/4277081/periodic_example.zip) with an example of the problem, I'm using the commands mentioned above to start Django or Panel. I'm printing the current time when the function with a periodical callback is called.

**Comment by Hoxbro** [comment]
I think it is a bug that PeriodicCallback is running "forever" with Django when the user closes the browser without pressing the stop button. 

I seems to be related to  `bokeh.io.curdoc.add_periodic_callback` in [PeriodicCallback](https://github.com/holoviz/panel/blob/master/panel/callbacks.py) which do not register when the user leaves the site.

**Comment by Hoxbro** [comment]
The problem stills is still here with newer versions of Panel (0.10.0a6) and Bokeh (2.1.0). [Updated code](https://github.com/holoviz/panel/files/4791693/periodic_example.zip).

I have screen recorded the problem to show the how Panel stops after 30 seconds of closing the browser and Django keeps running forever. I have attached the screen recordings [periodic_videos.zip](https://github.com/holoviz/panel/files/4791730/periodic_videos.zip) and converted them to Gif:

**Panel**
![panel](https://user-images.githubusercontent.com/19758978/84885303-24110e00-b093-11ea-9f65-825569f78474.gif)

**Django**
![django](https://user-images.githubusercontent.com/19758978/84885377-41de7300-b093-11ea-992f-e386624bd830.gif)

**Comment by philippjfr** [comment]
Sounds like the server cleanup handlers aren't correctly triggered when running via Django. It's likely we'll have to fix this upstream in Bokeh.

**Comment by Hoxbro** [comment]
Could see their had been some updates with periodic callbacks in #1507 so I tried to see if it had solved the problem. Unfortunately it did not solve it but then again it was a long shot. I was running version `0.10.0a17.post4+g844c883`.

Also looked into Bokeh´s Django implementation and found out I could register a window/tab closing with the function `WSConsumers.disconnect` in the file `bokeh.server.django.consumers.py`. I was not able to communicate between Django and Bokeh/Panel and communicate that the windows was closed, but maybe another one which has more experienced with that could be able to do it.

**Comment by Hoxbro** [comment]
I have fount out I can get the periodic callback to stop by changing the [following lines](https://github.com/bokeh/bokeh/blob/bf555e93d4d62b58e113d73c406bf0db8e2f4a34/bokeh/server/django/consumers.py#L231-L232) from:
```
    async def disconnect(self, close_code):
        pass
```

to:

```
    async def disconnect(self, close_code):
        self.connection.session.destroy()
```

Maybe this could be the solution to my problem? I have not a Bokeh development environment setup on my computer, so I have not ran any of their tests.

**Comment by philippjfr** [comment]
Ooh, yeah that seems like it would work. Maybe just submit a PR and we can discuss and further test it from there.

**Comment by Hoxbro** [comment]
Fixed upstream in https://github.com/bokeh/bokeh/pull/10578
