### ISSUE TITLE
Can not unlink axis in panel.Tabs

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/panel#1126]
#### ALL software version info
panel==0.8.0
holoviews==1.12.7
ubuntu 18.04
python 3.6.8

#### Description of expected behavior and the observed behavior
I need to render two different tabs with the same labels but different axis ranges. I would rather have a high level option rather than adding .options(axiswise=True) to every plot.

#### Complete, minimal, self-contained example code that reproduces the issue

```
a = pd.DataFrame(range(20))
b = pd.DataFrame(range(40))
pn.Tabs(b.hvplot.line(), a.hvplot.line(), linked_axis=False)

```

**Comment by philippjfr** [comment]
Thanks for the issue, however the `linked_axes` option exists on the HoloViews pane and works fine:

```python
a = pd.DataFrame(range(20))
b = pd.DataFrame(range(40))
pn.Tabs(pn.pane.HoloViews(b.hvplot.line(), linked_axes=False), a.hvplot.line())
```

**Comment by philippjfr** [comment]
The option cannot be on Tabs because Panel layout should be agnostic about the contents and linking of axes is specific to HoloViews.

**Comment by LinuxIsCool** [comment]
Thanks @philippjfr. Totally makes sense. It's nice to have the canon working example. Simple enough.

**Comment by philippjfr** [comment]
Let me know if you think it could be documented better, this does trip up people frequently.

**Comment by LinuxIsCool** [comment]
Sure, I'll take a look at docs and make a suggestion.

**Comment by LinuxIsCool** [comment]
I'm considering three locations to add the example that you posted.
1. /user_guide/customization -> Add section for Pane.HoloViews
2. /user_guide/links -> Add section at bottom on holoviews axis
3. Create new file /user_guide/holoviews

Any suggestions?

Are the html files auto-generated from the jupyter notebooks in /examples/user_guide?

Thanks!

**Comment by jbednar** [comment]
Yes, the HTML is auto-generated from the notebooks, so contributing to the docs only requires editing the notebooks and then clearing out any extra metadata Jupyter added to the notebooks. I'm not sure where this information should go, personally...
