### ISSUE TITLE
Functionality to convert WebComponent model to true Bokeh+Panel model

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1131]
#### My Pain

I've created the `WebComponent` and demonstrated how easy it is to use to create awesome plugins for Panel in Python only. See https://github.com/holoviz/panel/pull/1122

There are things that custom WebComponents do not support though (I belive)

- js linkin
- Advanced customization of the model in typescript.
- use a true Bokeh models.

#### Solution

Create functionality to convert a WebComponent to the Bokeh model .py+.ts and Panel .ts files.

This might be done using jinja templates or python f-string with a lot of loops and if statements.

#### Additional context

An example webcomponent is 

```python
class SearchInput(WiredBase):
    html = param.String('<wired-search-input></wired-search-input>')
    attributes_to_watch = param.Dict({"placeholder": "placeholder", "autocomplete": "autocomplete"})
    properties_to_watch = param.Dict({"value": "value"})
    events_to_watch=param.Dict({"input": None})

    def __init__(self, min_height=40, **params):
        super().__init__(min_height=min_height, **params)

    placeholder=param.String("Search Here")
    value = param.String()
    autocomplete=param.ObjectSelector("off", objects=["on", "off"])
```

The idea is to convert this configuration into 

- The **Pane .py model** file. It's primarely a matter of instantiating the model and reading which parameters it has besides the configuration `html`, ..., `events_to_watch` parameters and adding them to the model. These parameters can be identified as the parameters on the child WebComponent but not on the base/ parent WebComponent.
- The **Bokeh. py model** file. It's primarely a matter of converting the `param.String` types to bokehs `property.String` type etc.
- The **Bokeh .ts model** is more advanced. Its a matter of converting Bokeh .py properties to .ts properties and connecting a signal for each property. How the signal is connected depends on if it is an attribute, property or event to watch in the original Panel WebComponent.

**Comment by philippjfr** [comment]
I don't intend to implement anything beyond `ReactiveHTML` which should already address this use case.
