### ISSUE TITLE
Home page does not exist (404)

### ISSUE THREAD

**Issue by kripnerl** [holoviz/panel#1139]
Sorry if not writting to right issue list. 

#### ALL software version info
Not relevant. 

#### Description of expected behavior and the observed behavior
https://panel.holoviz.org/ should show sometihng else then 404. 

#### Complete, minimal, self-contained example code that reproduces the issue
https://panel.holoviz.org/

#### Screenshots or screencasts of the bug in action
Big 404

**Comment by philippjfr** [comment]
Thanks for catching this, fixed.

**Comment by Douchin-Julien** [comment]
Hi!

https://panel.holoviz.org/

is down again.

**Comment by philippjfr** [comment]
Thanks, fixed again. Seems like GitHub is reverting the CNAME configuration on every deployment, which is bizarre.

**Comment by Douchin-Julien** [comment]
thx
