### ISSUE TITLE
Should panel support "depends() on action" for param.Action?

### ISSUE THREAD

**Issue by ceball** [holoviz/panel#1149]
Using `@depends()`, should I be able to make a method depend on a `param.Action`'s callable being called via Panel, without having to alter the underlying callable myself? I.e. getting `@depends` on a button click in Panel, where the button click's action is some pre-existing function I don't want to modify. Or maybe even just to simplify depends() on a param.Action in Panel.

For example, "naive people" who haven't read the docs might write something like the below, hoping to have a plot update in response to a button click. Clicking the spinner (`one`) immediately updates the plot, whereas clicking the button (`two`) does not update the plot. 

![Peek 2020-03-13 09-36](https://user-images.githubusercontent.com/1929/76609328-22253500-650f-11ea-89ed-d9744bebc485.gif)

```
clicks = []
class A(param.Parameterized):
    one = param.Number(1, bounds=(0,10))
    two = param.Action(lambda x: clicks.append(x))
   
    @param.depends('one','two')
    def test(self):
        return hv.Curve(np.random.random((10,10)))

a = A()
pn.Row(a.param, a.test)
```
       
(Note: `watch=True` makes no difference.)

The way to achieve the desired behavior here is to have the `param.Action`'s callable do `x.param.trigger('two')` as well as whatever else it was doing before:

```
clicks = []
def update_clicks(x):
    clicks.append(x)
    x.param.trigger("two")

class A(param.Parameterized):
    one = param.Number(1, bounds=(0,10))
    two = param.Action(update_clicks)
   
    @param.depends('one','two')
    def test(self):
        return hv.Curve(np.random.random((10,10)))

a = A()
pn.Row(a.param, a.test)
```

That's no big deal, although it's a little bit more complicated for the user to understand.

However, if you have a pre-existing parameterized object (unrelated to panel), with a `param.Action` (or `param.Callable`) set to some pre-existing callable, you then can't just "panel" it - you have to modify the callable to do the trigger.

#### Describe the solution you'd like

I'm not sure I even want to be able to do this :)

At the param level, it doesn't make sense to have the `test()` method depend on the `two` parameter as written above in the first example, if what I actually mean is to depend on the `two` parameter's value being called. Usually with `@depends('x')`, you are declaring that there's a dependency on `x`'s value being set/changed - which for param.Action means switching one callable for another, not calling the callable.

Param _could_ support watching of a `param.Action`'s callable being called (e.g. by wrapping the callable when the value is set), but that's a different can of worms. (And if it did, you might be writing something like `@depends("two:actioned")` or whatever suspicious thing we previously invented there.)

Meanwhile, Panel currently at least knows that all you can do for a param.Action in the GUI is action it by clicking (you can't set/change the callable), so maybe it would be ok to have `panel.depends()` on a param.Action mean depending on it being called? Maybe not, though, because you could still change the callable _outside_ the GUI, which is what `depends()` presumably responds to at the moment.

#### Describe alternatives you've considered

There are already perfectly acceptable alternatives to achieve response to a button click in panel :) E.g. https://panel.holoviz.org/gallery/param/action_button.html#param-gallery-action-button.

#### Additional context

Setup for the code above:

```
import numpy as np
import panel as pn
import holoviews as hv
import param
pn.extension()
```

Versions:
* panel: 0.8.1
* bokeh: 1.4.0
* param: 1.9.3

**Comment by philippjfr** [comment]
We now have `param.Event` which behaves more sensibly when you want to depend on it.
