### ISSUE TITLE
Add template feature for serving multiple, individual apps with individual css styles.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1159]
#### My Pain

I'm serving a dictionary of apps using something similar to

```bash
APP_ROUTES = {
    "app1": app1,
    "app2": app2,
}
pn.serve(APP_ROUTES, port=14033, dev=True)
```

I started developing a custom `pn.Template` for one of my apps. This includes some custom css styling. So I added it to the template of the app.

But then the other apps started using the style as well.

After some confusion and debugging I found out that it was because I added the CSS styles using `pn.config.raw_css` and thus then they will be found in all apps.

#### Solution

Add a parameter to the `pn.Template` to specify which `css_files` and `raw_css` to include. I guess the same would hold for scripts, script modules and similar.

Alternatively mention this issue in the documentation and describe the solution. I guess the solution is to include any css and javascript directly in the custom template file.

**Comment by philippjfr** [comment]
pn.config now has per session state and each template also has a completely separate `.config`.

**Comment by hyamanieu** [comment]
@philippjfr , I just used `pn.config.raw_css.append(css)` within a single app of a multiple app panel server: it still leaks to my other apps.  I was using panel `0.12.0rc12` (latest). Is this coming to a later tag?

**Comment by philippjfr** [comment]
Can you post the full example you tried?

**Comment by hyamanieu** [comment]
You can re-close it...

Making a minimal working example for your inquiry, there is no leak. It may be within my larger project.

Still here's the MWE:
```python
import panel as pn
css = """
.bk.bk-btn:focus {
    box-shadow: 0 0 0 2px #f90;
    }


.bk.bk-btn.bk-btn-success {
  background: #eee;
  color: #666;
}
.bk.bk-btn.bk-btn-success.bk-active {
  background: #5cb85c;
  color: #fff;
}"""

def test1():
    pn.extension(raw_css = [css])
    
    return pn.Row(pn.widgets.Toggle(name='click me!', button_type='success'))
def test2():
    
    return pn.Row(pn.widgets.Toggle(name='click me!', button_type='success'))


APP_ROUTES = {
    "app1": test1,
    "app2": test2,
}
pn.serve(APP_ROUTES, port=14033, dev=True)
```

**Comment by philippjfr** [comment]
Appears to have been fixed.

**Comment by MarcSkovMadsen** [comment]
I was also surprised to experience this behavior the other day. So I can confirm.
