### ISSUE TITLE
non-clickable links

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [holoviz/panel#1162]
At the bottom of the page at https://panel.holoviz.org/, I see the following, which includes two non-clickable links:

> Once you’ve installed Panel, you can get your own copy of all the notebooks used to make this website:
> 
> panel examples
> cd panel-examples
> 
> And then you can launch Jupyter to explore them yourself using either Jupyter Notebook or JupyterLab:
> 
> jupyter notebook
> jupyter lab

**Comment by ceball** [comment]
I'm not sure which things you are expecting to be links. Or maybe I am a bit confused?

You _appear_ to be talking about commands that are meant to be run in a terminal. That isn't explicitly stated anywhere, so the docs could be improved in that regard. (Maybe you could suggest clearer phrasing, or open a pull request to make the change yourself?)

In case I have misinterpreted, could you maybe include a screenshot showing what you mean?

**Comment by jbednar** [comment]
Good point; I think it should explicitly say something like "you can run the following commands in your Conda or pip environment to get your own copy of ...".

**Comment by Phillip-M-Feldman** [comment]
It looks as though I did misunderstand the intent, and that nothing more
than a rewording is required.  I'm not sure that I'm sufficiently savvy to
make the pull request.

**Comment by ceball** [comment]
We value this kind of feedback (it's difficult to write clear documentation about something you do every day!), so if you are at all interested in making the change, we'll happily help. 

Here are the overall steps of what I think is the simplest way (I might be wrong!):

1. Fork the repository to your own GitHub account (it's a button in GitHub somewhere).
2. Make the wording change in the appropriate file via the online GitHub editor.
3. Follow the GitHub editor guidance to commit and then create a pull request.

There's probably not enough detail there to actually follow along, but it tells you the three main steps, and there should be GitHub documentation with details. (Step 1 might even happen for you automatically if you just try to edit the file online, I'm not sure.)

Also, the above is just one of several possible ways to do it. Others involve using free software to get your own copy of the repository on your computer.

Anyway, did you actually accomplish what you were trying to do? If not, there's a holoviz discourse forum where you can get usage help (there should be a link to it on the panel website).

**Comment by ceball** [comment]
The file itself: https://github.com/holoviz/panel/blob/master/doc/index.rst

Although having just found that myself, I see it's "rst" format. I forgot we still have those; they can be difficult to edit correctly :(

**Comment by ceball** [comment]
I went to get the discourse link, and in the process found you were sent here from there. Telling you to go back there doesn't seem very helpful 😂
