### ISSUE TITLE
Spinner shows Value/ Input not Spinner

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1172]
The current release of Panel is 0.9.2.

#### My Pain

I was setting up a new Panel project and would like to use the Spinner. I could not get it spinning. Instead the `value` is shown.

This is also happening in the reference gallery at https://panel.holoviz.org/reference/widgets/Spinner.html#widgets-gallery-spinner

![image](https://user-images.githubusercontent.com/42288570/77219459-3e8c2780-6b36-11ea-99b0-792065d201ae.png)

#### Solution

Fix it :-). Don't know how.

**Comment by MarcSkovMadsen** [comment]
My Mistake. Thought the Spinner was like a Progress.

**Comment by jbednar** [comment]
Right; Bokeh's name "spinner" for this widget is very confusing!
