### ISSUE TITLE
panel.holoviz.org is down

### ISSUE THREAD

**Issue by lrq3000** [holoviz/panel#1174]
panel.holoviz.org is down, it was working earlier today, but now there is a 404 error on the whole domain and all subpages.

**Comment by janosg** [comment]
Same problem here. Any time estimate on when it will be fixed?

**Comment by philippjfr** [comment]
It's bizarre GitHub keeps switching back the CNAME which brings it down.

**Comment by philippjfr** [comment]
Fixed now, but if anyone has any idea why GitHub would revert the CNAME configuration after a deployment that would be appreciated.

**Comment by ceball** [comment]
Not quite clear what is happening.

Travis writes a CNAME file with panel.holoviz.org in it (which I can see in
the gh-pages branch), but afterwards at
https://github.com/holoviz/panel/settings the custom domain is not
panel.holoviz.org, and you have to manually set it to that?

Or something else?

**Comment by philippjfr** [comment]
Semi-randomly it's resetting the domain and HTTPS setting in https://github.com/holoviz/panel/settings to panel.pyviz.org and HTTPs disabled when a new doc build is deployed from Travis.
