### ISSUE TITLE
Please support jupyter_themes

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1175]
#### My Pain

I like to work with dark themes because 

1) they look nice 
2) they put less strain on my eyes
3) its most often a requirement from the people I develop panel apps for.

If I change the theme of my Jupyter Notebook to something dark my Panel app is **not readable** because the text colors are blurry/ not sharp.

I'm using `jupyter_themes` to change the theme. And I've been using the `chesterish` theme.

#### Solution

- Must have: a generic dark theme for notebooks. 
- Nice to have: a dedicated theme for each of the jupyter_themes.

#### Code

In order to change jupyter theme you need to `conda install jupyterthemes` or `pip install jupyterthemes`

Lets take the following app

```python
import param
import panel as pn
import pandas as pd
import os
pn.extension()
pn.config.sizing_mode="stretch_width"

data = pd.DataFrame({
    "x": [1,]*10,
    "y": [2,]*10,
})

themes = [
    'default',
    'chesterish',
    'grade3',
    'gruvboxd',
    'gruvboxl',
    'monokai',
    'oceans16',
    'onedork',
    'solarizedd',
    'solarizedl',
]

class App(param.Parameterized):
    theme = param.ObjectSelector('default', themes)
    dataframe = param.DataFrame(data)
    action = param.Action()
    message = param.String()
    
    def __init__(self, **params):
        super().__init__(**params)
        self.action=self.change_theme
    
    def view(self):
        return pn.Column(
            pn.Param(self),
        )
    
    def change_theme(self, _):
        if self.theme=="default":
            cmd = "jt -r"
        else:
            cmd = f"jt -t {self.theme}"
        os.system(cmd)
        self.message=f"""
        Changed to {self.theme} **please 
        
        1) refresh the browser!**"
        2) clear all output
        3) run all cells
        """
        
App().view()
```

#### Default Theme

![image](https://user-images.githubusercontent.com/42288570/77242530-9e023a00-6bff-11ea-9c40-a17db09c7cf9.png)

#### Chesterish

![image](https://user-images.githubusercontent.com/42288570/77242544-cd18ab80-6bff-11ea-8797-b426a1b6fabb.png)

#### Grade3

![image](https://user-images.githubusercontent.com/42288570/77242564-00f3d100-6c00-11ea-9f32-57e681a8bb5b.png)

#### Gruvboxd

![image](https://user-images.githubusercontent.com/42288570/77242573-28e33480-6c00-11ea-8266-132c4a205275.png)

#### Gruvboxl

![image](https://user-images.githubusercontent.com/42288570/77242596-65af2b80-6c00-11ea-874e-5fff8930d5ad.png)

#### Monokai

![image](https://user-images.githubusercontent.com/42288570/77242604-811a3680-6c00-11ea-901d-45c395ede803.png)

#### Oceans16

![image](https://user-images.githubusercontent.com/42288570/77242619-9abb7e00-6c00-11ea-8e3d-0a2f03420c91.png)

#### OneDork

![image](https://user-images.githubusercontent.com/42288570/77242642-e53cfa80-6c00-11ea-850f-a51ec8d3985a.png)

#### Solarizedd

![image](https://user-images.githubusercontent.com/42288570/77242651-fd147e80-6c00-11ea-9921-7c59b29f8cd9.png)

#### Solarizedl

![image](https://user-images.githubusercontent.com/42288570/77242673-1d443d80-6c01-11ea-9297-a25c7586f65b.png)

**Comment by MarcSkovMadsen** [comment]
I see a related issue here https://github.com/holoviz/panel/issues/520

**Comment by MarcSkovMadsen** [comment]
#### Additional Context

I believe the CSS needed to make panel nice can be found in the CSS of the jupyter_themes. For example a DataFrame in the `chesterish` theme looks like

![image](https://user-images.githubusercontent.com/42288570/77243072-e4f32e00-6c05-11ea-88fb-77d6d9234ec6.png)

**Comment by philippjfr** [comment]
There's still a long tail to address here but we will support dark themes in Jupyter properly. Ensuring that each of the Jupyter themes works perfectly is out-of-scope however.
