### ISSUE TITLE
Remove panel.serve template dependency on panel.holoviz.org

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1176]
#### My Pain

When https://panel.holoviz.org/ is down (like now https://github.com/holoviz/panel/issues/1174)

![image](https://user-images.githubusercontent.com/42288570/77242819-0f8fb780-6c03-11ea-83a6-17cf1d22ca54.png)

the template used by panel.serve does not show the Panel logo

![image](https://user-images.githubusercontent.com/42288570/77242838-3221d080-6c03-11ea-8bd7-ea46cd67a931.png)

```html
<img src="http://panel.pyviz.org/_static/logo_stacked.png" width="120">
```

#### Solution

Change the link of the image to a more robust cdn.

**Comment by jbednar** [comment]
What if we changed the url to https://raw.githubusercontent.com/holoviz/panel/master/doc/_static/logo_stacked.png ?  Is github's uptime sufficient? If not I'm not sure where else to host the image that would be more reliable.

**Comment by mattpap** [comment]
I would just serve it as a static resource by `panel.serve()`. If the logo is small enough, it could be embedded as a data URL. Maybe those options were rejected earlier.
