### ISSUE TITLE
DataFrame pane does not render DataFrames with many columns nicely

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1177]
#### My Pain

I often have DataFrames with many columns I want to present, use and explore.

Currently this is not possible in Panel as it does not render them nicely

#### Solution

Fix it :-) Maybe using scrolling or something similar.

#### pn.pane.DataFrame

```python
import param
import panel as pn
import pandas as pd
import os
pn.extension()
pn.config.sizing_mode="stretch_width"

data = {}
for i in range(0,100):
    data[i]=["abc"]*100
dataframe = pd.DataFrame(data)
pn.pane.DataFrame(dataframe)
```

##### Notebook

![image](https://user-images.githubusercontent.com/42288570/77242992-e8d28080-6c04-11ea-9a1d-1a2763037b6a.png)

#### Server

![image](https://user-images.githubusercontent.com/42288570/77243003-0d2e5d00-6c05-11ea-80eb-fefeeacead80.png)

**Comment by MarcSkovMadsen** [comment]
Here is an example from todays work. Aarrghh :-)

![image](https://user-images.githubusercontent.com/42288570/77298983-0cbcc180-6cec-11ea-8e32-7cd0ce60a83e.png)

**Comment by lgonzalezsa** [comment]
A workaround I found is to do dataframe.to_html(); certainly the format is different but at least allow me to expose the dataframe.

**Comment by philippjfr** [comment]
Thanks to your recent changes this now behaves well.
