### ISSUE TITLE
DataFrame widget does not render DataFrames with many columns nicely

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1178]
#### My Pain

I often have dataframes with a large number of columns and maybe even dynamic columns that I want to show and explore in my Panel App.

Currently this is not possible in Panel as it does not render DataFrames with many columns nicely.

For example the DataFrame widget just cuts of the columns and does not provide scrolling.

#### Solution

Fix it :-) Maybe by providing horizontal scrolling.

#### Additional Context

FYI. @philippjfr 

As the DataFrame pane has similar problems https://github.com/holoviz/panel/issues/1177,  I think there is a **major issue** for Panel as it does not display DataFrames nicely. At least that is always my experience. 

And I think DataFrames is one of the must fundamental things you want to display in Panel. I think its one of the first things a new user of Panel would experience. And there is no work around I know of.

#### Code

```python
import param
import panel as pn
import pandas as pd
import os
pn.extension()
pn.config.sizing_mode="stretch_width"

data = {}
for i in range(0,100):
    data[i]=["abc"]*100
dataframe = pd.DataFrame(data)
pn.widgets.DataFrame(dataframe)
```

##### Notebook

![image](https://user-images.githubusercontent.com/42288570/77243055-b5dcbc80-6c05-11ea-9623-014dd0d6249d.png)

##### Server

![image](https://user-images.githubusercontent.com/42288570/77243087-1bc94400-6c06-11ea-9273-0e384bc43158.png)

**Comment by MarcSkovMadsen** [comment]
Here is an example from todays work. Aarrghh :-)

![image](https://user-images.githubusercontent.com/42288570/77298983-0cbcc180-6cec-11ea-8e32-7cd0ce60a83e.png)

**Comment by fm75** [comment]
Thanks for 
```python
pn.config.sizing_mode="stretch_width"
```
That fixed a problem that I was having. Maybe this should be default behavior for DataFrame.

**Comment by philippjfr** [comment]
The widget now correctly scrolls and has options to control this behavior.
