### ISSUE TITLE
Required packages not correctly listed with conda

### ISSUE THREAD

**Issue by hyamanieu** [holoviz/panel#1180]
I am posting an issue following my post on https://discourse.holoviz.org/t/unable-to-update-with-newest-panel-creating-a-new-environment-not-straightforward/330

As said, installing a version >0.7 of panel doesn't work straightforward. Conda doesn't say which packages are missing. It seems the solution lies in adding conda-forge channel, and this isn't documented.

**Comment by philippjfr** [comment]
I **think** I just fixed this with Panel 0.9.3. could you give that a go?

**Comment by hyamanieu** [comment]
Doing the following didn't raise any error:

`conda create -n panel093 -c pyviz panel=0.9.3 python=3.7`

I didn't do much more testing, but I could import panel. I guess that means the issue is solved.

**Comment by philippjfr** [comment]
Thanks for checking and thanks for reporting the typo!
