### ISSUE TITLE
Intermediate loading of widgets to implement loading screens

### ISSUE THREAD

**Issue by lrq3000** [holoviz/panel#1183]
My dashboard has to fetch some remote data and do some heavy calculations on first load. I am using a cache to avoid other users but the first to have to wait a long time. However, even for other users, there is a delay between the script start / access to the URL of the Bokeh server, and the display of Panel widgets (because I do other calculations that cannot be cached).

So, I had the idea to implement a simple loading screen, just to let the user know that something is going on in the background. Here is what I wrote:

```
# Show a loading screen until everything is prepared
loading_spinner = pnw.Progress()
loading_txt = pn.pane.Markdown('## Please wait while the dashboard is loading...')
loading_screen = pn.Row(pn.layout.HSpacer(),
       pn.Column(
           loading_txt,
           pn.Row(
               pn.layout.HSpacer(),
               loading_spinner,
               pn.layout.HSpacer()
           )
       ),
       pn.layout.HSpacer())
loading_screen.servable()
```

Then, later in my code, to hide the loading screen I can simply write:
```
loading_screen.clear()
```

Before loading the real dashboard.

However, it does not work, because it seems that Panel only displays after all calculations and widgets are loaded in memory.

Hence my question: is it possible to signal to Panel that we want to display an intermediate state of the widgets? This would be useful not only for drawing a loading screen, but also to dynamically update the dashboard, so this stone could kill multiple birds :-)

**Comment by philippjfr** [comment]
Ideally this would be something solved at the bokeh level, basically rendering some basic loading screen while the app is initialized. However maybe we can add some workaround at the Panel level while that is being worked on. It may for example be possible for Panel to provide a flag that tells your code whether it should return the loading animation or the actual contents of your app.

**Comment by philippjfr** [comment]
>This would be useful not only for drawing a loading screen, but also to dynamically update the dashboard, so this stone could kill multiple birds :-)

This latter thing should already be possible, once the app is initialized you can trigger some change in the beginning of your callback, then do some long-running computation and then update the dashboard again.

**Comment by mattpap** [comment]
> Ideally this would be something solved at the bokeh level, (...)

If this is to be handled via the JSON serialization protocol, then it must solved at bokeh level, due to how rendering works in web browsers. Between JSON objects being loaded, bokehjs objects constructed and finally rendered, nothing will appear on screen, because all those steps happen in one JS runtime task, and rendering happens only after everything else in a task finished computing. We will need to cooperatively split up that task into multiple to allow intermediate rendering. Otherwise one could use templates to store alternative content in place of a plot or dashboard, before the actual content is rendered (something like HTML's `<noscript>`).

**Comment by lrq3000** [comment]
Thank you very much guys for your fast replies!

Please let me clarify that what i mean by the loading screen is not when
the bokeh server is loading, that would be nice but it's fast enough and it
happens once so it's ok, but once my app starts (i have debug text printed
in the console to check that), any widget i set as .servable() before the
heavy computations won't display until all computations are done and the
full dashboard is loaded too. But I'm running a from an ipython notebook,
I'll check if that's the culprit.

In any case I'll try to make a minimal example to bettea explain what i had
in mind.

Le lun. 23 mars 2020 à 20:35, Mateusz Paprocki <notifications@github.com> a
écrit :

**Comment by lrq3000** [comment]
Re,

I tried to run the server from the .py file using Jupytext, but it didn't help, so that's really a limitation of the Bokeh server.

Here is a minimal example of what I had in mind:

```
import panel as pn
import panel.widgets as pnw
pn.extension()

# Show a loading screen until everything is prepared
loading_spinner = pnw.Progress()
loading_txt = pn.pane.Markdown('## Please wait while the dashboard is loading...')
loading_screen = pn.Row(pn.layout.HSpacer(),
       pn.Column(
           loading_txt,
           pn.Row(
               pn.layout.HSpacer(),
               loading_spinner,
               pn.layout.HSpacer()
           )
       ),
       pn.layout.HSpacer())
loading_screen.servable()

# Do some long computation
for i in range(int(1E8)):
    pass

# Hide the loading screen
loading_screen.clear()

# Show the final screen
pn.pane.Markdown('## Loading done!').servable()
```

I hoped the loading screen would load up before the computation and then it would get replaced by "Loading done!", but what happens when the user loads up the page is that all calculations are done and only after, only the text "Loading done!" is shown.

**Comment by lrq3000** [comment]
If this is a limitation in the Bokeh server, should I report the issue on their tracker instead?

**Comment by philippjfr** [comment]
There are now a number of ways to add loading screens. In particular all components have the `loading` parameter on all components which will display a spinner on top of it. You can easily create components with load enabled by default and hide the spinner with the `pn.state.on_load`. Examples [1](https://panel.holoviz.org/gallery/simple/loading_spinner.html#simple-gallery-loading-spinner) and [2](https://panel.holoviz.org/gallery/simple/defer_data_load.html).
