### ISSUE TITLE
Plot Title Warning

### ISSUE THREAD

**Issue by gioarma** [holoviz/panel#1184]
#### Software version info
holoviews 1.13.0
bokeh 2.0.0
JupyterLab 2.0.1

#### Example code

```python
import pandas as pd
import hvplot.pandas
pd.options.plotting.backend = 'holoviews'

df = pd.DataFrame(range(5))
df.plot(title = 'Test')
```
I get the plot, but also a warning: 

```
WARNING:param.OverlayPlot23109: title_format is deprecated. Please use title instead
```
although I'm using `title`, not `title_format`

**Comment by gioarma** [comment]
Sorry, this should be under holoviews

**Comment by MarcSkovMadsen** [comment]
I experience a similar problem when using the HoloViz tutorial. See https://github.com/holoviz/holoviz/issues/257
