### ISSUE TITLE
MultiChoice automatically sorted

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#1185]
Awesome sleek widget! One thing I found was that it was automatically sorted; is it possible to implement a sorted=True/False option?
`pn.widgets.MultiChoice(options=['b', 'c', 'a'], height=1000)`

![image](https://user-images.githubusercontent.com/15331990/77373308-f0de0d80-6d35-11ea-90ed-9ccf479ee558.png)

**Comment by philippjfr** [comment]
Thanks for the issue. It is not sorted at the HoloViews level so this is a bokeh issue.

**Comment by mzy2240** [comment]
Related to https://github.com/holoviz/panel/issues/4454
