### ISSUE TITLE
Fileselector widget: click on folder doesn't update the file list

### ISSUE THREAD

**Issue by kcpevey** [holoviz/panel#1186]
#### ALL software version info
panel 0.9.3  
  
#### Description of expected behavior and the observed behavior
When navigating the folders in the left hand side of the FileSelector widget, I can double click on a folder. This triggers the displayed directory string to be updated to the folder I just clicked on. However, the file list does not update. To update the file list, I have to click the "down" arrow.   
  
Reading through the docs, it seems this is expected behavior, but it doesn't feel natural to the user. So maybe this is a feature request instead of a bug report? It seems like this is just missing a param.depends that will trigger a file list update when the directory is changed.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension()

files = pn.widgets.FileSelector('~')
files
```

**Comment by philippjfr** [comment]
There is sadly no way to make this happen otherwise we would have done it when designing the widget. We do not have access to double click events.

**Comment by kcpevey** [comment]
Ah, that's true, a single click on the folder will populate the directory string. Anyhow, it seems like you could just put a watcher on the directory string to trigger an update of the file list. Are you avoiding that because if you *typed* in the directory string it would trigger with every letter typed?

**Comment by kcpevey** [comment]
I don't doubt you've thought this through already, I'm just curious :)

**Comment by philippjfr** [comment]
>Anyhow, it seems like you could just put a watcher on the directory string to trigger an update of the file list

No I'm avoiding this because it would mean you couldn't select folders (I realize the widget is called FileSelector but it also works for directories). It'd also be super easy to do accidentally which would be annoying.

**Comment by kcpevey** [comment]
Got it. Thanks!

**Comment by ahuang11** [comment]
Could the down arrow key be next to the >> buttons. With heavily nested directories, it feels a bit tedious to drag the mouse to the top right of the widget then back to the center left of the widget to select directory

**Comment by dwr-psandhu** [comment]
@philippjfr How about allowing the enter/return key instead of click to navigate to the folder ? Is that possible ?
