### ISSUE TITLE
Param value does not reflect widget. 

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/panel#1196]
#### ALL software version info
bokeh==2.0.0  
holoviews==1.13.1  
jupyterlab==2.0.1  
panel==0.9.3  

#### Description of expected behavior and the observed behavior

From panel/examples/reference/widgets/FloatSlider.ipynb:  

Moving the slider value does not change the param value. I feel like I am going crazy. Am I missing something obvious?

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

pn.extension()

float_slider = pn.widgets.FloatSlider(name='Float Slider', start=0, end=3.141, step=0.01, value=1.57)

float_slider

float_slider.value

```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/31582215/77692589-2cf6b580-6f64-11ea-97c7-adbc03d11bf6.png)

**Comment by philippjfr** [comment]
Do you have the jupyterlab extension installed?

**Comment by LinuxIsCool** [comment]
Thanks @philippjfr that was it.
