### ISSUE TITLE
Assertion error on widget.controls()

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/panel#1197]
## ALL software version info
bokeh==2.0.0
holoviews==1.13.1
jupyterlab==2.0.1
panel==0.9.3

#### Description of expected behavior and the observed behavior
From panel/examples/reference/widgets/FloatSlider.ipynb:

Render the controls panel for the float slider.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

pn.extension()

float_slider = pn.widgets.FloatSlider(name='Float Slider', start=0, end=3.141, step=0.01, value=1.57)

float_slider.controls()

```

#### Stack traceback and/or browser JavaScript console output
```
~/.virtualenvs/LTF/lib/python3.6/site-packages/param/parameterized.py in descendents(class_)
    161     printing the contents of an entire class hierarchy.
    162     """
--> 163     assert isinstance(class_,type)
    164     q = [class_]
    165     out = []
AssertionError: 
```

#### Screenshots or screencasts of the bug in action

![image](https://user-images.githubusercontent.com/31582215/77701581-e3ae6200-6f73-11ea-90d1-9b656aa62fed.png)

**Comment by philippjfr** [comment]
Can't reproduce this, what's your version of `param`?

**Comment by philippjfr** [comment]
This is still a bug Panel though, we clearly did not pin param strictly enough.

**Comment by LinuxIsCool** [comment]
param==1.9.2

**Comment by philippjfr** [comment]
Okay, yeah please try upgrading to 1.9.4, I'll bump the required version in the dependencies.

**Comment by LinuxIsCool** [comment]
I don't see 1.9.4 in releases, but installed 1.9.3 and it works. Thanks @philippjfr .
