### ISSUE TITLE
Selecting widget states to embed before exporting to html

### ISSUE THREAD

**Issue by poplarShift** [holoviz/panel#1198]
Currently for a panel app `p`, `p.embed()` embeds "some" of the widget states so that they can be viewed in a static html export. A worthwhile feature would be to be able to specify which values exactly to export for each widget. 
For the moment, this apparently requires modifying the widgets or Parameters directly.

**Comment by philippjfr** [comment]
This should be straightforward enough, it's just a question of how we specify it. The easiest would be a mapping from Widget class to the specific values you want to embed.
