### ISSUE TITLE
Add a docs section to the developer guide 

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#1202]
The HoloViz team has achieved a wonderful job at thoroughly documenting panel (and holoviews, geoviews, hvplot, datashader)! I find myself digging a lot in the docs when I want to learn something new or to solve an issue. This is a much better experience compared to having to Google everything and browse StackOverflow.

Yet, from time to time I find typos, broken links, missing pieces of information, or not very clear explanations (at least to me!). Some of these issues could be fixed by the community. The developer guide of panel, however, doesn't provide any information about how to tackle that. Since most of (all?) the docs is made of Jupyter Notebooks, it should be pretty easy for any user of panel (and holoviews, etc.) to update the docs, as I expect them to be familiar with notebooks. 

I intend this issue to serve as a basis for discussion about this topic. In the first place, would the HoloViz team be OK with adding a Docs Section to their developer guide? If so, what should it contain? I'd say that the less experienced developers (well, like me) should be given the full set of instructions. How to fork, commit, make a pull request could be linked to the GitHub docs. There are probably some specific things that are done by the current maintainers (cleaning the notebooks for instance) that should also be mentioned in the docs section.

If this ends up in effectively adding a docs section to the developer guide, this change could be deployed to the other holoviz websites. This could be taken into account during the discussion.

@MarcSkovMadsen I've seen that you've contributed quite a lot to the docs. Assuming you're not part of the HoloViz team, you might have some good comments to provide here!

**Comment by jbednar** [comment]
I'm glad you appreciate our docs and want to help! I'd suggest that we make a general developer-docs section on the holoviz.org site, and then each individual project can link to it.  We generally all develop multiple projects at once, so we'll be best set up to tell how to set up a general development environment, and then each library can explain any special things about developing that particular project (e.g. for Panel that the JS resources need to be rebuilt after changing the code).

**Comment by MarcSkovMadsen** [comment]
I would really, really like to know how to get an efficient developer workflow for docs. As far as I can see

- The installation takes +10 mins
- The build takes 30-60 mins depending on hard ware
- There is NO WAY to use sphinx-autobuild, i.e. no way to get an efficient workflow where you change a document (.md) and then see the changes 1-5 secs later.

**Comment by philippjfr** [comment]
The new Pixi based build tooling makes doc builds reproducible and simple.

**Comment by MarcSkovMadsen** [comment]
I dont Think its completed? The existing developer docs are not up to date with pixi. And how to contribute to and build docs is not described.

I for One dont know how to do it, and dont dont it because there is not step by step guide.

**Comment by philippjfr** [comment]
> The existing developer docs are not up to date with pixi. And how to contribute to and build docs is not described.

This isn't true. There just hasn't been a release with pixi yet.
