### ISSUE TITLE
what's wrong with my panel...

### ISSUE THREAD

**Issue by ShukriChiu** [holoviz/panel#1203]
![image](https://user-images.githubusercontent.com/5136543/78033589-2cfa1980-7399-11ea-83dc-36e5a3ea1477.png)

I have no idea why I can show singe panel widget but I can't show any panel pane.

I have installed all the libs and jupyter lab extension

**Comment by ShukriChiu** [comment]
plz close the issue, I didn't install @bokeh/jupyter_bokeh plugin in jupyterlab. Please add this information in the official tutorial, It's so hard to find out without any reminder.

**Comment by philippjfr** [comment]
Yes, definitely needs to be added where ever possible.
