### ISSUE TITLE
Altair + Panel Bug

### ISSUE THREAD

**Issue by ShukriChiu** [holoviz/panel#1204]
![image](https://user-images.githubusercontent.com/5136543/78067069-abba7b00-73c8-11ea-8282-2eecbb134330.png)

The example format is wrong. I think it's a vega compatible problem.

if I use alt.Chart.display() to display plot from Altair, the result is fine, however I can't dynamically update the plot by change the parameters.

**Comment by philippjfr** [comment]
Thanks, this was fixed in https://github.com/holoviz/panel/pull/1201. I'll push a new release asap.
