### ISSUE TITLE
Markdown widget broken

### ISSUE THREAD

**Issue by PeteFein** [holoviz/panel#1217]
#### ALL software version info
panel                       0.9.3
bokeh                       2.0.1
Python 3.8.2

#### Description of expected behavior and the observed behavior
Markdown widgets don't display

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.panel("#Broken")
```

**Comment by philippjfr** [comment]
Thanks, with bokeh 2.0.1 all custom models broke due to a change in the way they are loaded and bundled. I'll be releasing Panel 0.9.4 asap.

**Comment by PeteFein** [comment]
Wow, in a dot release? :-[ Thanks for fixing so quickly

**Comment by philippjfr** [comment]
v0.9.4 is now building.
