### ISSUE TITLE
django2 example does not render anything at http://localhost:8000/sliders/

### ISSUE THREAD

**Issue by veenapaddy** [holoviz/panel#1219]
Followed the example/readme @https://panel.holoviz.org/user_guide/Django_Apps.html and cloned your repo and ran after installing django, bokeh, channels etc. Versions below for what could be relevant.

`
bokeh             2.0.1
Django            3.0.5
holoviews         1.13.2
channels          2.4.0
panel             0.9.4
`

Running
`
python manage.py runserver
`
seems to fire up things ok, but i get a blank page when navigating to http://localhost:8000/sliders/. No clear error messages are displayed. No changes were made to git repo code.

**Comment by philippjfr** [comment]
Thanks for the issue, there's already some discussion on this in https://github.com/holoviz/panel/issues/1205 so I'll close.

**Comment by veenapaddy** [comment]
Got it. Thanks. Ill follow along #1205, just wasnt sure it was the same since i wasn't getting any error message.
