### ISSUE TITLE
Improve the style and functionality of `pn.widgets.DataFrame`

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1223]
#### My Pain

Displaying tables in my apps is essential. My users need them to be 

- readable and look beautiful.
- be fast and responsive - even with large amounts of data (10.000 - 100.000 rows).
- be functional (i.e. provide sort and filtering).

The current `pn.widgets.DataFrame` is far from that. See https://github.com/holoviz/panel/issues/1178, https://github.com/holoviz/panel/issues/1108 and https://github.com/holoviz/panel/issues/940

#### Solution

get inspiration from https://ghiscoding.github.io/angular-slickgrid-bs4-demo/#/basic and improve :-)

![slick-grid](https://user-images.githubusercontent.com/42288570/78322365-d21a1b00-756e-11ea-894c-e57c008ef561.gif)

#### Additional Context

As far as I understand the DataFrame is built on top of SlickGrid.

**Comment by philippjfr** [comment]
We've now built out Tabulator which addresses most of the stated requirements. Any other suggestions should be filed as specific requests to improve Tabulator.
