### ISSUE TITLE
expand and expand_button parameters of pn.Param do not work as stated in documentation

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1229]
#### System Info

Panel version 9.5

#### My Pain

When reading the documentation https://panel.holoviz.org/reference/panes/Param.html#panes-gallery-param

![image](https://user-images.githubusercontent.com/42288570/78455216-4226bf00-769d-11ea-9402-3d9ef4108e7c.png)

I read it as it you can use the `expand` parameter to set whether or not to enable expanding into child classes. But that is not how it works.

In fact the `expand` parameter seems to have no effect. Instead the `expand_button` should be set to False. 

This is not clear at all from the documentation.

#### Code Example

```python
import param

import panel as pn


class ColorPalette(param.Parameterized):
    primary = param.Color("#9c27b0")

RED = ColorPalette(primary="#f44336", name="Red")
BLUE = ColorPalette(primary="#2196f3", name="Blue")

class ColorScheme(param.Parameterized):
    primary = param.ObjectSelector(RED, objects=[RED, BLUE])

    def view(self):
        not_works1 = pn.Param(
            self,
            expand=False,
        )
        not_works2 = pn.Param(
            self,
            expand=False,
            expand_button=None,
        )
        works = pn.Param(
            self,
            expand_button=False,
        )
        return pn.Column(
            not_works1, not_works2, works
        )

app = ColorScheme().view().servable()
```

![image](https://user-images.githubusercontent.com/42288570/78455272-99c52a80-769d-11ea-8eae-2a3de103eb72.png)

#### Additional Context

I just wasted 40 minutes with frustration trying to figure out what the problem was in a complicated example that did not work due to this and another bug in Panel (I believe). Friction :-)

I actually created the documentation but as I remember it that part I got from some existing documentation.

**Comment by philippjfr** [comment]
Looks like this is a docs issue, seems like you didn't copy the docstrings correctly when you wrote the reference notebook 😉
