### ISSUE TITLE
plots in tabs -- hover text, zoom, move, and other plot manipulation tools only work in LAST tab

### ISSUE THREAD

**Issue by sbrar17** [holoviz/panel#1231]
#### ALL software version info
panel 0.80
Plotly 4.5.2
Pandas 1.0.1
Python 3.7.6

#### Description of problem and expected behavior
I created a web app that has a few tabs using the tabs widget; there are three line plots in a column on each tab. Each plot is made using the Plotly library and renders appropriately. The problem is that plot features like toggling legend items, hover text, and the other tools (zoom level, move) only work consistently on the plots in the last tab. Many/most of the these plot features (legend toggle) do not work in the other tabs. All plots are the same size and located in the same position on each tab. same behavior with Safari (13.0.5) and Chrome (80.0.3987) under MacOS (10.15.3). Same behavior in Windows 10 and Chrome.

#### Complete, minimal, self-contained example code that reproduces the issue
The web app is accessible here; it is a COVID-19 dashboard being used by healthcare providers to track the epidemiology of the pandemic:

http://3.215.121.30:8080/COV19v2

The tabs in question are located on the right side of the page. The plot manipulation tools for these plots in these tabs do not behave as expected except for the last tab titled: "Pop Adj Mort" (which stands for Population Adjusted Mortality). Would be really helpful for viewers to be able to toggle and zoom in all tabs.

**Comment by philippjfr** [comment]
Is this still true with the latest version of Panel? I suspect it is but it's worth checking. This also seems related to https://github.com/holoviz/panel/issues/804. Plotly seems to dislike tabs in various ways. Not clear whether this is an issue with Panel's plotly implementation, Bokeh's Tabs component or Plotly itself.

**Comment by rithwikjc** [comment]
I just ran into this same issue.
```
panel 0.9.5
plotly 4.6.0
```
And yes it's the same as #804. Was going to raise an issue, but glad to see its already reported. :)
