### ISSUE TITLE
panel.holoviz.org is down

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1240]
![image](https://user-images.githubusercontent.com/42288570/78670218-b64fa580-78dd-11ea-891c-4622e9e43499.png)

**Comment by MarcSkovMadsen** [comment]
And this is how holoviz.org looks

![image](https://user-images.githubusercontent.com/42288570/78670298-d2534700-78dd-11ea-9f7d-7de543e8013f.png)

**Comment by MarcSkovMadsen** [comment]
And this is hvplot

![image](https://user-images.githubusercontent.com/42288570/78670398-f878e700-78dd-11ea-851f-ecdfab36746f.png)

**Comment by philippjfr** [comment]
GitHub pages is down, we have no control over this.
