### ISSUE TITLE
FileDownload widget produces empty file for dataframe xlsx / does not work for BytesIO object

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1241]
#### Version

Panel 0.9.4

#### My Pain

The FileDownload widget produces empty `xlsx` files when clicking the button.

![image](https://user-images.githubusercontent.com/42288570/78681365-eeaab000-78ec-11ea-8991-6e6c1bffa981.png)

![image](https://user-images.githubusercontent.com/42288570/78681430-0124e980-78ed-11ea-8ebe-2801616fe843.png)

```python
import pandas as pd
import panel as pn
from io import BytesIO

data=pd.DataFrame({"a": [1]})

def get_file():
    output = BytesIO()
    writer = pd.ExcelWriter(output, engine='xlsxwriter')
    data.to_excel(writer, sheet_name="Data")
    writer.save()
    return output

file_download = pn.widgets.FileDownload(filename="data.xlsx", callback=get_file)
file_download
```

and there are no error messages in either the console or the jupyter server log.

#### Additional Context

But if you save the file manually it has contents

![image](https://user-images.githubusercontent.com/42288570/78685118-9924d200-78f1-11ea-86aa-e59872868bf8.png)

```python
with open("data_manual.xlsx", 'wb') as f:
    f.write(get_file().getvalue())
```

#### Solution

- Identify and fix bug
- or document how file download of Pandas XLSX files should be done.

**Comment by MarcSkovMadsen** [comment]
My guess would be that the mime type is not supported (yet).

![image](https://user-images.githubusercontent.com/42288570/78685761-7e9f2880-78f2-11ea-845d-bbe7e63699a3.png)

**Comment by MarcSkovMadsen** [comment]
According to https://filext.com/faq/office_mime_types.html the mime type should be

application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

**Comment by MarcSkovMadsen** [comment]
Having looked more at the code the problem is really that for non-string files the `read` method is used and for the `BytesIO` object created that is the empty string while the `getvalue` method is not.

![image](https://user-images.githubusercontent.com/42288570/78687243-44368b00-78f4-11ea-919f-b1bb2bbac524.png)


![image](https://user-images.githubusercontent.com/42288570/78687220-3da81380-78f4-11ea-87ff-cf1d8fdaa72e.png)

**Comment by MarcSkovMadsen** [comment]
#### Workaround

A workaround for now is to set `output.read=output.getvalue`

```python
import pandas as pd
import panel as pn
from io import BytesIO

data=pd.DataFrame({"a": [1]})

def get_file():
    output = BytesIO()
    writer = pd.ExcelWriter(output, engine='xlsxwriter')
    data.to_excel(writer, sheet_name="Data")
    writer.save()
    output.read=output.getvalue
    return output

file_download = pn.widgets.FileDownload(filename="data.xlsx", callback=get_file)
```

![image](https://user-images.githubusercontent.com/42288570/78687977-05550500-78f5-11ea-8ea4-4596bfbe5a6b.png)

**Comment by MarcSkovMadsen** [comment]
#### Solution

According to https://stackoverflow.com/questions/26879981/writing-then-reading-in-memory-bytes-bytesio-gives-a-blank-result I need to `seek` back to the beginning of the file after writing the initial in memory file

```python
import pandas as pd
import panel as pn
from io import BytesIO

data=pd.DataFrame({"a": [1]})

def get_file():
    output = BytesIO()
    writer = pd.ExcelWriter(output, engine='xlsxwriter')
    data.to_excel(writer, sheet_name="Data")
    writer.save()
    output.seek(0)
    return output

file_download = pn.widgets.FileDownload(filename="data.xlsx", callback=get_file)
file_download
```

It works 

![image](https://user-images.githubusercontent.com/42288570/78688947-194d3680-78f6-11ea-8214-2778cba86c29.png)

**Comment by philippjfr** [comment]
>According to https://stackoverflow.com/questions/26879981/writing-then-reading-in-memory-bytes-bytesio-gives-a-blank-result I need to seek back to the beginning of the file after writing the initial in memory file

This is definitely the correct fix.
