### ISSUE TITLE
Responsive plots generated in parameterized classes not resizing to window dimensions

### ISSUE THREAD

**Issue by mmorys** [holoviz/panel#1245]
This issue was first mentioned in Panel Discourse topic [Responsive plots generated in parameterized classes not resizing to window dimensions](https://discourse.holoviz.org/t/responsive-plots-generated-in-parameterized-classes-not-resizing-to-window-dimensions/453).

#### Software version info
python=3.7.7
bokeh=2.0.1
holoviews=1.13.2
panel=0.9.3
param=1.9.3

#### Description of expected behavior and the observed behavior
We expect holoviews objects that are initialized with `responsive=True` to adapt to size of the available window, even when a panel is passed a callable function. When a parameterized class has a "`view(self)`" function, and a panel is created with the callable, as in `pn.Column(obj.view)`, the holoviews objects created by `view` do not respond to window size. However, when a panel is created with the function return, as in `pn.Column(obj.view())`, the holoviews objects do respond to window size.

In the minimal example, a SimplePlot class creates a basic sinusoid with an adjustable amplitude. A PlotViewer class combines the SimplePlot objects into a single panel. A checkbox tied to the parameter link_y_axes is used to trigger the PlotViewer.view() method to change the plot y-labels for linking/unlinking the y-axes.

In the panel() method, two options are shown for plotting. The first (preferable because the full application needs to update datashaded plots) passes the view callable to the panel, and works properly other than resizing. The second passes the output of the view method and resizes, but does not react to the checkbox interaction.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import param, panel as pn, numpy as np, holoviews as hv
pn.extension()

num_plots = 2

# Class to create simple holoviews curve plot of a sinusoid
class SimplePlot(param.Parameterized):
    amplitude = param.Number(default=1.0, bounds=(0, 1))

    @param.depends('amplitude')
    def plot(self):
        points = [(0.1 * i, self.amplitude * np.sin(0.1 * i)) for i in range(100)]
        return hv.Curve(points).redim.range(y=(-1,1))

    def view(self, suffix=""):
        return hv.DynamicMap(self.plot).redim(y="y"+suffix).opts(responsive=True, ylabel='y', min_width=400, min_height=200)

# Class to combine multiple SimplePlot objects into a single panel
class PlotViewer(param.Parameterized):
    link_y_axes = param.Boolean(True)
    plot_list = param.List([], precedence=-1)
    num_plots = param.Integer(default=2, bounds=(1,None), precedence=-1)

    def __init__(self, **params):
        super().__init__(**params)
        self.plot_list = [SimplePlot() for i in range(self.num_plots)]

    # Whenever the link_y_axes checkbox is changed, replot the Column so that the
    # plot y-axis labels change and are linked/unlinked appropriately
    @param.depends('link_y_axes')
    def view(self):
        col = pn.Column(width_policy='max', height_policy='max')
        for i, plot in enumerate(self.plot_list):
            y_label_suffix = "" if self.link_y_axes else str(i)
            col.append(plot.view(y_label_suffix))
        return col

    def panel(self):
        plot_params = pn.Column(width_policy='fit')
        plot_params.append(pn.Param(self.param))
        plot_params.extend([pn.Param(plot.param) for plot in self.plot_list])

        # # Option 1: Dynamic sizing to window does not work, but plots update correctly
        # return pn.Row(self.view, plot_params, width_policy='max', height_policy='max')
        # # Option 2: Dynamic sizing works, but does not update plots
        return pn.Row(self.view(), plot_params, width_policy='max', height_policy='max')

viewer = PlotViewer(num_plots=num_plots)
viewer.panel().servable()
```

#### Screencast of the bug in action
![Axis_resizing_options](https://user-images.githubusercontent.com/10374345/78836140-7a8d0c80-79bf-11ea-822b-1b69c644138c.gif)

**Comment by nritsche** [comment]
I think I encountered the same bug in https://github.com/chime-experiment/bondia/issues/19 with

**Software version info**

python=3.8.0
bokeh=2.1.1
holoviews=1.13.2
panel=0.9.7
param=1.9.3

I noticed that the plot becomes responsive after the first time a param is changed and it looks like the same is true for the gif posted above.

**Comment by mmorys** [comment]
@nritsche I was able to find a workaround for the issue by embedding the `self.view` function inside a panel `GridSpec` element. I don't know why, but if the view function is added to a GridSpec it resizes dynamically. See below where the change was made.

```
import param, panel as pn, numpy as np, holoviews as hv
pn.extension()

num_plots = 2

# Class to create simple holoviews curve plot of a sinusoid
class SimplePlot(param.Parameterized):
    amplitude = param.Number(default=1.0, bounds=(0, 1))

    @param.depends('amplitude')
    def plot(self):
        points = [(0.1 * i, self.amplitude * np.sin(0.1 * i)) for i in range(100)]
        return hv.Curve(points).redim.range(y=(-1,1))

    def view(self, suffix=""):
        return hv.DynamicMap(self.plot).redim(y="y"+suffix).opts(responsive=True, ylabel='y', min_width=400, min_height=200)

# Class to combine multiple SimplePlot objects into a single panel
class PlotViewer(param.Parameterized):
    link_y_axes = param.Boolean(True)
    plot_list = param.List([], precedence=-1)
    num_plots = param.Integer(default=2, bounds=(1,None), precedence=-1)

    def __init__(self, **params):
        super().__init__(**params)
        self.plot_list = [SimplePlot() for i in range(self.num_plots)]

    # Whenever the link_y_axes checkbox is changed, replot the Column so that the
    # plot y-axis labels change and are linked/unlinked appropriately
    @param.depends('link_y_axes')
    def view(self):
        col = pn.Column(width_policy='max', height_policy='max')
        for i, plot in enumerate(self.plot_list):
            y_label_suffix = "" if self.link_y_axes else str(i)
            col.append(plot.view(y_label_suffix))
        return col

    def panel(self):
        plot_params = pn.Column(width_policy='fit')
        plot_params.append(pn.Param(self.param))
        plot_params.extend([pn.Param(plot.param) for plot in self.plot_list])

        # # Option 1: Dynamic sizing to window does not work, but plots update correctly
        #---------------- Change starts here ---------------------
        plot_out = pn.Row(pn.GridSpec(sizing_mode='stretch_both'), plot_params, sizing_mode='stretch_both')
        plot_out[0][0,0] = self.view
        return plot_out
        #---------------- Change ends here ---------------------
        # # Option 2: Dynamic sizing works, but does not update plots
        # return pn.Row(self.view(), plot_params, width_policy='max', height_policy='max')

viewer = PlotViewer(num_plots=num_plots)
viewer.panel().servable()

```

**Comment by teajaysee** [comment]
This still isn't fixed as far as I can tell? Any chart generated with a paramaterised function cannot be responsive, but as here suggested, editing the object in-place does work, though obviously not the recommended way of using Panel/Holoviews. Is there any likelihood this issue might be fixed some point? thanks

**Comment by philippjfr** [comment]
Sorry I never replied here, this is indeed pretty easy to work around. The thing you need to understand is that when you pass a dynamically updating method to a Panel layout it is treated just like any other object and is wrapped in a Panel component. This Panel component can declare options about the sizing behavior of the object. By calling `pn.panel(self.view, ...)` you can provide those options:

```python
    def panel(self):
        plot_params = pn.Column(width_policy='fit')
        plot_params.append(pn.Param(self.param))
        plot_params.extend([pn.Param(plot.param) for plot in self.plot_list])

        view = pn.panel(self.view, sizing_mode='stretch_both') # 
        return pn.Row(view, plot_params, sizing_mode='stretch_both')
```
