### ISSUE TITLE
Panel does not work in VS Code notebook experience

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1247]
#### My Pain

I'm a user of VS Code and would like to be able to use Panel in the VS Code notebook experience. But currently I cannot.

When running the below code in an integrated notebook

```python
import panel as pn
pn.extension()
pn.Column("# Hello Panel World")
```

I see

![image](https://user-images.githubusercontent.com/42288570/78865603-2f660e80-7a3e-11ea-8e1b-0257fb997b53.png)

I'm using Panel 0.9.4 and VS Code 1.43.2.

**Comment by mattpap** [comment]
It fails indeed on the last line, but given that panel works in the reference implementation of jupyter notebook and this errors seems to originate from vscode(-python?) (though with this quality of error reporting by vscode(-python?), it's hard to know for sure), then I would submit this to vscode-python's issue tracker. On a side note, bokeh works fine (at lest simple plotting capability).

**Comment by MarcSkovMadsen** [comment]
Thanks @mattpap . I created this issue on the request of @philippjfr . So I would like him to state if I should open an issue for VS Code also or instead?

**Comment by philippjfr** [comment]
Maybe it's an issue with our JS code so I'll debug first and then we can escalate to VSCode.

**Comment by philippjfr** [comment]
I believe this is working now, if not please reopen.
