### ISSUE TITLE
Edits to a dataframe via pn.ipywidget(pn.widgets.DataFrame(df)) are not reflected back to the dataframe

### ISSUE THREAD

**Issue by ceball** [holoviz/panel#1249]
#### ALL software version info

jupyterlab on linux, chromium 79.0.3945.130

```
$ conda list # abbreviated
# Name                    Version                   Build  Channel
bokeh                     2.0.1                      py_0    bokeh/label/dev
ipykernel                 5.2.0            py37h43977f1_1    conda-forge
ipython                   7.13.0           py37hc8dfbb8_2    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
ipywidgets_bokeh          1.0.0dev1                  py_0    bokeh/label/dev
jupyter_bokeh             2.0.0                      py_0    bokeh/label/dev
jupyter_client            6.1.2                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                2.1.0                      py_0    conda-forge
jupyterlab_server         1.1.0                      py_1    conda-forge
panel                     0.9.5                      py_0    pyviz/label/dev
param                     1.10.0a2                   py_0    pyviz/label/dev
python                    3.7.6           h8356626_5_cpython    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
```

```
$ jupyter labextension list
JupyterLab v2.1.0
Known labextensions:
   app dir: /home/sefkw/mc3/envs/hvdev/share/jupyter/lab
        @bokeh/jupyter_bokeh v2.0.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @pyviz/jupyterlab_pyviz v1.0.0  enabled  OK
```

#### Description of expected behavior and the observed behavior

When using `pn.ipywidget(pn.widgets.DataFrame(df))` (or `comms='ipywidgets'`), after editing a pandas dataframe the change is not reflected back to the original dataframe.

`pn.widgets.DataFrame(df)` alone (without `comms='ipywidgets') works fine.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import panel as pn
pn.extension()
df = pd.DataFrame([[1,2],[3,4]])
pn.ipywidget(pn.widgets.DataFrame(df))
```

Editing the dataframe does not affect df. Works fine without the `pn.ipywidget()` call.

#### Stack traceback and/or browser JavaScript console output

![Screenshot from 2020-04-09 15-36-17](https://user-images.githubusercontent.com/1929/78906937-e8950a80-7a77-11ea-940b-809dd336f7c4.png)

#### Screenshots or screencasts of the bug in action

![Peek 2020-04-09 15-40](https://user-images.githubusercontent.com/1929/78907386-88529880-7a78-11ea-8b6e-9331a9659bc0.gif)

**Comment by philippjfr** [comment]
Thanks, I can reproduce.

**Comment by ceball** [comment]
I might be wrong, but is this a problem with jupyter_bokeh rather than panel?

Here is an example that apparently works via `bokeh serve`,  but not in the notebook with jupyter_bokeh:

```python
from bokeh.models.widgets.tables import DataTable
from bokeh.models import ColumnDataSource, TableColumn
from bokeh.io import curdoc
import pandas as pd

df = pd.DataFrame([[1,2],[3,4]],columns=['x','y'])
ds = ColumnDataSource(df)
dt = DataTable(source=ds, sortable=True, editable=True,
               columns=[TableColumn(field="x",title="x"),
                        TableColumn(field="y",title="y")])

def on_data_change(attr, old, new):
    print('on_data_change')
    print('...attr: %s'%attr)
    print('...old: %s'%old)
    print('...new: %s'%new)

ds.on_change('data', on_data_change)

curdoc().add_root(dt)
```

I'm not hugely familiar with using bokeh (thanks to holoviz ;) ), so there could be problems with the above. But running it and editing the bottom right value in the table to 300 results in this being printed:

```
on_data_change
...attr: data
...old: {'index': array([0, 1]), 'x': array([1, 3]), 'y': array([  2, 300])}
...new: {'index': array([0, 1]), 'x': array([1, 3]), 'y': array([  2, 300])}
```

(don't know why old and new are the same, but the point is I get the updated value).

The above example in jupyter lab, with additional imports
```python
from bokeh.io import output_notebook
import bokeh.resources
output_notebook(resources=bokeh.resources.INLINE)
```

and last line replaced with

```python
import jupyter_bokeh as jbk
jbk.BokehModel(dt)
```

results in the following entry in the jupyter lab log:

```
on_data_change
...attr: data
...old: None
...new: None
```

**Comment by ceball** [comment]
I.e. `_sync_model` is not getting the data?

https://github.com/bokeh/jupyter_bokeh/blob/232733ef9cea84b562e26b9365a781941117c546/jupyter_bokeh/widgets.py#L104-L115

Seems to be confirmed by being missing from the message?

![Screenshot from 2020-04-26 16-43-42](https://user-images.githubusercontent.com/1929/80312435-1fd81b00-87dd-11ea-9360-3a57e75ab024.png)

**Comment by ceball** [comment]
@mattpap any chance you could give your opinion about the jupyter_bokeh example above? 

Does it look like an issue in jupyter_bokeh? If so I'll move over there, and focus my debugging on jupyter_bokeh.

Or is it not clear (i.e. I need to do more to determine/demonstrate)? 

Or is it expected jupyter_bokeh behavior (i.e. I need to improve my understanding)?

Thanks!

**Comment by philippjfr** [comment]
I suspect it's not listening to column patch events.

**Comment by ceball** [comment]
Thanks! Earlier this morning (before your comment) I'd got as far as not understanding when `_consume_patch` (below) should and would be called, but decided I would need to get and build `jupyter_bokeh` myself locally in order to understand how it all works (probably just with print statements, ha ha), but couldn't quite face the typescript & lab build process before work. However, your comment might be enough for me to go try that this evening...if you could just confirm what "it" is in "I suspect it's not listening to column patch events" above (i.e. you meant jupyter_bokeh, right?).

```typescript
export class BokehView extends DOMWidgetView {
  [...]
  constructor(options?: any) {
    [...]
    this.model.on("change:render_bundle", () => this.render())
    this.listenTo(this.model, "msg:custom", (content, buffers) => this._consume_patch(content, buffers))
  }
```
https://github.com/bokeh/jupyter_bokeh/blob/232733ef9cea84b562e26b9365a781941117c546/src/widgets.ts#L64 T

```typescript
  protected _consume_patch(content: {msg: "patch", payload?: Fragment}, buffers: DataView[]): void {
    if (this._document == null)
      return
    if (content.msg == "patch") {
      const {payload} = content
      this._receiver.consume(payload != null ? payload : buffers[0].buffer)
      const comm_msg = this._receiver.message
      if (comm_msg != null && keys(comm_msg.content).length > 0) {
        this._blocked = true
        try {
          this._document.apply_json_patch(comm_msg.content, comm_msg.buffers)
        } finally {
          this._blocked = false
        }
      }
    }
  }
}
```

**Comment by ceball** [comment]
```typescript
  protected _change_event(event: DocumentChangedEvent): void {
    const {ModelChangedEvent} = bk_require("document/events")
    if (!this._blocked && event instanceof ModelChangedEvent)
      this.send({event: "jsevent", id: event.model.id, new: event.new_, attr: event.attr, old: event.old})
  }
```
https://github.com/bokeh/jupyter_bokeh/blob/232733ef9cea84b562e26b9365a781941117c546/src/widgets.ts#L85-L89

On editing the data frame in lab, `event` here no values for `new_` and `old`, but it does have a "hint" containing a "patch" for the data frame. My hack for now is to take the hint and apply the patch (both concepts I've heard of before :)), replacing `event.new_` with the result. However, that is surely not the right way to do it (both in terms of the design and the performance) :) 

In order to fix properly, I need to start by going off and learning bokeh's event system before returning to jupyter_bokeh.

**Comment by philippjfr** [comment]
I fixed this in https://github.com/bokeh/jupyter_bokeh/pull/102
