### ISSUE TITLE
Update docs to be consistent on `value_throttled` and `callback_policy`

### ISSUE THREAD

**Issue by joelostblom** [holoviz/panel#1255]
From https://discourse.holoviz.org/t/how-to-throttle-values-on-mouseup/456/2

I thought `callback_policy` was deprecated, but if I look at the [documentation of IntRangeSlider](https://panel.holoviz.org/reference/widgets/IntRangeSlider.html), it is still there. However, in the [docs for RangeSlider](https://panel.holoviz.org/reference/widgets/RangeSlider.html), there is no `callback_policy` and instead there is `value_throttled` which is referencing `callback_throttle`, which in turn does not exist on this doc page but it does exist on the IntRangeSlider doc page where `value_throttled` does not exist.

Related to #1253

**Comment by joelostblom** [comment]
This doc update could also include clarifying what `value_throttled` actually does. The current docstring reads

> Tuple of upper and lower bounds of selected range where events are throttled by callback_throttle value.

To me this implied that throttling will only occur in the range specified in the tuple. However, the current behavior of the parameter is to toggle throttling for the entire range of the widget and set the initial value to what is specified in the tuple. And as @philippjfr [pointed out here](https://discourse.holoviz.org/t/how-to-throttle-values-on-mouseup/456/6?u=joelostblom), the throttling means that the widget fires on "mouseup", it seems like the reference to `callback_throttle` is obsolete, is that correct? If so, I would rewrite like this for clarity:

> Tuple of upper and lower bounds for the selected value range. In contrast to setting `value`, events are throttled so that they only update on mouseup rather than continuously. 

---

Personally, I think the most intuitive behavior would be to make `value_throttled` a boolean parameter and rely exclusively on `value` to specify the value range, and not have the user switch between using either `param.value` or `param.value_throttled`, but instead always be using `param.value` in `@pn.depends`. This would avoid confusion stemming from not realizing that you need to change both the initialization and the decoration to throttle a value.

This parameter name could be changed to `throttle_value` to avoid confusion with how they are named in bokeh and under the hood it could set the `param.value` attribute to the bokeh `value_throttled` valule, but the user would not have to change the name of the attribute they are using. So they code would look like:

```python
int_range_slider = pn.widgets.IntRangeSlider(end=10, throttled_value=True)

@pn.depends(int_range_slider.param.value, watch=True)
def print_slider_value(slider_value):
    return slider_value
```

There might be technical limitation that I am not aware of preventing this change, so simply view this as a suggestion of which syntax I think most clearly communicates the purpose of these parameters, and is simplest to understand and also use since it requires changes only in one place to switch between throttled and continuously updated widgets.

**Comment by philippjfr** [comment]
This has been resolved.
