### ISSUE TITLE
Set `value_throttled` on instantiation of widgets

### ISSUE THREAD

**Issue by joelostblom** [holoviz/panel#1256]
From https://discourse.holoviz.org/t/how-to-throttle-values-on-mouseup/456/3?u=joelostblom

This works (no value throttling):

```python
int_range_slider = pn.widgets.IntRangeSlider()

@pn.depends(int_range_slider.param.value, watch=True)
def print_slider_value(slider_value):
    return slider_value[0]

pn.Column(int_range_slider, print_slider_value)
```

To get throttling I tried changing `int_range_slider.param.value` to `int_range_slider.param.value_throttled`, but this raises `TypeError: 'NoneType' object is not subscriptable`. This can be fixed by specifying `value_throttled=(3, 4)` (or any number) when initializing the slider (although it was not needed to set `value=` when using `int_range_slider.param.value`).

```
-----
panel       0.9.5
param       1.9.3
sinfo       0.3.1
-----
IPython             6.5.0
jupyter_client      5.2.3
jupyter_core        4.6.3
jupyterlab          2.1.0
notebook            5.6.0
-----
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) [GCC 7.3.0]
Linux-5.6.2-arch1-2-x86_64-with-arch
4 logical CPU cores
-----
Session information updated at 2020-04-08 12:00
```

**Comment by philippjfr** [comment]
This has been addressed.
