### ISSUE TITLE
Dragging a slider widget sometimes updates `value` and `value_throttled` differently

### ISSUE THREAD

**Issue by joelostblom** [holoviz/panel#1258]
Again from https://discourse.holoviz.org/t/how-to-throttle-values-on-mouseup/456/10?u=joelostblom and with the same code and versions numbers as in #1256 and #1257.

Dragging the slider around, updates both `value` and `value_throttled` the same most of the times., but occasionally I come across strange behavior where they are updated differently, see the video below:

![image](https://discourse.holoviz.org/uploads/default/original/1X/7402e5f282dbbd0846c8469a9832eda3f7483483.gif)

**Comment by philippjfr** [comment]
Actually I'm not sure there's much we can do about this, the events may be processed in any order (or rather the order depends on what bokeh) so there's always one that will lag the other.

**Comment by joelostblom** [comment]
Hmm, does that mean that I need to worry about that the value passed on to the function might not be the value I am seeing on the slider?

**Comment by philippjfr** [comment]
Good point, didn't think about the example you posted properly. In the end they should always match, seemingly that's not the case so there's a bug somewhere.

**Comment by xavArtley** [comment]
I think the true test to see if there is a bug is this one:
```
int_range_slider = pn.widgets.IntRangeSlider(end=10, value=(7,9))

@pn.depends(int_range_slider.param.value_throttled)
def print_slider_value_throttled(throttled):
    return pn.pane.Str(throttled, width=500)

@pn.depends(int_range_slider.param.value)
def print_slider_value(value):
    return pn.pane.Str(value, width=500)

pn.Column(int_range_slider, print_slider_value_throttled, print_slider_value)
```

Since the value can be different in transient states we have to compare at the end of interactions
And I cannot produce incoherency

**Comment by philippjfr** [comment]
This was some issue with events getting dropped in the notebook which has since been resolved.
