### ISSUE TITLE
Add option to toggle throttled on widgets with interact and depends

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#1259]
#### Is your feature request related to a problem? Please describe.
I often want to use the `value_throttled` for my dashboard´s widgets and the only way to do it right now is the hard way by adding an explicit widget instance to `pn.interact` or `pn.depends`. 

#### Describe the solution you'd like
Either add a keyword like `throttled` to `pn.interact` and `pn.depends` or create a new function which use the `value_throttled` if it exist for the widget e.g. `pn.interact_throttled`.

#### Additional context
Here are examples of `pn.interact` and `pn.depends` with a `throttled` keyword:
![interact_example](https://user-images.githubusercontent.com/19758978/79048694-2e400780-7c1f-11ea-81ad-57a541e6a5f4.gif)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19758978/79048762-a3abd800-7c1f-11ea-9a6c-9bced12f8156.gif)

**Comment by Hoxbro** [comment]
I have got an working example of the feature request mentioned above by adding the keyword throttled to the functions `pn.interact` and `pn.depends`. I have changed the files panel/interact.py and panel/depends.py to get this to work. I also needed to change panel/widgets/sliders.py so it solves the issues mentioned in #1253 and #1256.  I have attached the [files](https://github.com/holoviz/panel/files/4470734/files.zip) changed.  Code used above: 

```
import panel as pn
pn.extension()

func = lambda x: x
pn.interact(func, x=1, throttled=True)
```

```
import panel as pn
pn.extension()

int_range_slider = pn.widgets.IntRangeSlider(end=10, value=(2, 10), value_throttled=(7, 9))

@pn.depends(int_range_slider, throttled=True)
def print_slider_value(slider_value):
    return slider_value

pn.Column(int_range_slider, print_slider_value)
```

**Comment by Hoxbro** [comment]
Any updates on this enhancement?

**Comment by philippjfr** [comment]
If there is any progress I'll record it here, if this is a priority for you I'd be happy to guide you through contributing a PR.
