### ISSUE TITLE
Importing panel not working

### ISSUE THREAD

**Issue by jpandeinge** [holoviz/panel#1265]
I installed panel using `conda install -c pyviz panel` on ubuntu 18.04.4 LTS as recommended on the official website [panel](https://panel.holoviz.org/getting_started/index.html). However, I keep getting an import error.

`import panel as pn`
here is a screenshot of the error i am getting.
![panel](https://user-images.githubusercontent.com/17166397/79119229-20f65a80-7d90-11ea-9fbe-dadf7937cf0c.png)

**Comment by philippjfr** [comment]
Thanks for the issue. You need a more recent version of Panel. Panel < 0.9  are not compatible with bokeh > 2.0.
