### ISSUE TITLE
Responsive Grid

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1268]
#### My Pain

I'm trying to create responsive single page applications. With the new Card and Accordion coming up the only `layout` component I'm really missing is a responsive Grid.

#### Solution

Something like 

- https://material.io/develop/web/components/layout-grid/ or
- https://purecss.io/grids/

#### Additional Context

The most important thing to decide in the design is how much detail the user can specify. Some css grid frameworks really lets you fine tune the grid for each individual device (mobile, tablet, desktop). Others just let you specify the number of columns (1,2,3..,12).

I can see there already are requests close to this

- https://github.com/holoviz/panel/issues/572
- https://discourse.holoviz.org/t/mobile-layouts/302

**Comment by MarcSkovMadsen** [comment]
There is a user asking for a responsive grid here https://discourse.holoviz.org/t/responsive-dashboard/945/3

**Comment by philippjfr** [comment]
You'll be able to roll your own with https://github.com/holoviz/panel/pull/1343

**Comment by MarcSkovMadsen** [comment]
I think 1343 together with a good example and recommendation of a grid framework that works great with panel would do the trick.

**Comment by philippjfr** [comment]
The [GridStack](https://panel.holoviz.org/reference/layouts/GridStack.html) component has now been around a while. Happy to see a new issue to allow size dependent grid specs though.
