### ISSUE TITLE
panel widgets.DateRangeSlider not working

### ISSUE THREAD

**Issue by khannaum** [holoviz/panel#1269]
I am from Pakistan
panel widgets.DateRangeSlider not working . Following is the code snap

```python
date_range_slider = pn.widgets.DateRangeSlider(
name=‘Date’,
start=cust_group_by_work_projected.ddate.min(), end=cust_group_by_work_projected.ddate.max(),
value=(cust_group_by_work_projected.ddate.min(), cust_group_by_work_projected.ddate.max())
)
pn.extension()
test_new=cust_group_by_work_projected.hvplot(y=‘Count’,x=‘complaint_type’ ,
groupby=[‘RBU’,‘complaint_type’,‘ddate’],legend=False)
pn.panel(test_new, widgets={‘ddate’: date_range_slider})
```

![image](https://user-images.githubusercontent.com/7712413/79222573-37c0ae00-7e71-11ea-8f6f-8fd3413641f5.png)

help required why daterangeslider not working
date range values not selected and resulted to None
ddate is None

**Comment by khannaum** [comment]
![image](https://user-images.githubusercontent.com/7712413/79222906-d51be200-7e71-11ea-8382-edebe63ab447.png)

**Comment by khannaum** [comment]
this is working

![image](https://user-images.githubusercontent.com/7712413/79227410-48752200-7e79-11ea-8cf8-11d1d5323be9.png)

**Comment by khannaum** [comment]
![image](https://user-images.githubusercontent.com/7712413/79227997-347df000-7e7a-11ea-8396-9be6b56a463b.png)

**Comment by philippjfr** [comment]
This is a usage question which I've addressed on Discourse.
