### ISSUE TITLE
Add Panel to the list of tools for a data scientist at https://www.anaconda.com/distribution/

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1278]
I believe Panel is awesome but under communicated.

One solution would be to add it to https://www.anaconda.com/distribution/

I would suggest adding the line

- Create awesome analytics app with [Panel](https://panel.holoviz.org/)

![image](https://user-images.githubusercontent.com/42288570/79540516-98760380-8088-11ea-8dfb-dff4b068c3bf.png)

**Comment by philippjfr** [comment]
Done 🥳
