### ISSUE TITLE
https://panel.holoviz.org/ is not secure

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1279]
![image](https://user-images.githubusercontent.com/42288570/79540746-f1459c00-8088-11ea-8cda-87365b753186.png)

**Comment by philippjfr** [comment]
Really not sure what's up:

![Screen Shot 2020-04-24 at 2 24 01 PM](https://user-images.githubusercontent.com/1550771/80212173-4ceac900-8637-11ea-98f2-3ea0a7591cc6.png)
