### ISSUE TITLE
Plotly panel resets layout on data update

### ISSUE THREAD

**Issue by Alexboiboi** [holoviz/panel#1291]
#### ALL software version info
panel==0.9.5
bokeh==2.0.1
param==1.9.3

#### Description of expected behavior and the observed behavior
Hi there,

I am using panel to display a plotly pane. It works quite nicely but as soon as want to update some trace parameters, the layout is reseted at its original view. According to the corresponding [discussion ](https://discourse.holoviz.org/t/plotly-panel-resets-layout-on-data-update/528) in the Holviz Discourse it appears to be a bug.

#### Complete, minimal, self-contained example code that reproduces the issue
In order to test the behaviour I am talking about, turn the 3d object with the mouse and then move the opacity slider.
```
import param
import panel as pn
import plotly.graph_objects as go
pn.extension('plotly')

class MyFig(param.Parameterized):
    opacity = param.Number(default=1, softbounds=(0,1))
    fig_pane = param.ClassSelector(class_=pn.pane.Plotly)
    
    @param.depends('opacity', watch=True)
    def update_opacity(self):
        self.fig_pane.object.data[0].update(opacity=self.opacity)
                              
    def view(self):
        return pn.Column(self.param.opacity, self.fig_pane)

plotly_fig = go.Figure(data=[
    go.Mesh3d(
        x=[0, 1, 2, 0], y=[0, 0, 1, 2], z=[0, 2, 0, 1],
        i=[0, 0, 0, 1], j=[1, 2, 3, 2], k=[2, 3, 1, 3],
    )
])
myfig = MyFig(fig_pane=pn.pane.Plotly(plotly_fig))
myfig.view()
```

#### Screenshots or screencasts of the bug in action
![gif1](https://user-images.githubusercontent.com/29252289/79912507-6ebf3280-8422-11ea-815d-09ad25190f3b.gif)

**Comment by ceball** [comment]
Still reproducible with panel 0.11.0a2 (bokeh 2.2.3, plotly 4.14.1, param 1.10.0).
