### ISSUE TITLE
python callback for ColumnDataSource

### ISSUE THREAD

**Issue by do6mt** [holoviz/panel#1293]
I would like to link different plots based on a selection in a plot (bokeh).

In bokeh there is a python callback for changed selctions in "columnDataSource"
**s1.selected.on_change('indices', callback)**, which does work as long as I'm running a bokeh server in Jupyter. As I understood up to now its not possible to run such an application over several Cells what I actually would like to do. I thought that panel could solve this issue.

Unfortunatly it seems as if there is no columDataSource in panel with a python callback that can be used!?

It would be great if there was a solution to use something like:

s1 = pn.ColumnDataSource(data = dict(x=x,y=y))
with a python callback
s1.selected.on_change('indices', callback)

Thank you so much! 
Martin

**Comment by nghenzi** [comment]
You can use the bokeh CDS un your panel app. The callback will be executed un the dame way that a single bokeh based app.

**Comment by MarcSkovMadsen** [comment]
Hi @nghenzi 

Do you have a link or an example? I would like to try that out.

Thanks.

**Comment by do6mt** [comment]
Hi @ nghenzi,
thanks for you reply! 
> You can use the bokeh CDS in your panel app. The callback will be executed in the same way that in a single bokeh based app.
I think this does not work. Using CDS inside a panel app does work, but mixing callbacks like: s1.selected.on_change('indices', callback)
s1.selected.js_on_change('indices', update_S2)
does not work and leads to the following Warning:
![warning](https://user-images.githubusercontent.com/22011289/80069995-8f7ea980-8542-11ea-9a1b-7ae764d71ea3.JPG)
java callback (s1.selected.js_on_change('indices', update_S2)) is executed 
python callback  (s1.selected.on_change('indices', callback)) does not work!

**Comment by nghenzi** [comment]
Uhs,,, I was answering for bokeh server only. Sorry for the misunderstanding !

**Comment by ceball** [comment]
@do6mt if you were to use holoviews, would what you want be possible? E.g. based on https://www.holoviews.org/user_guide/Linking_Plots.html

@philippjfr I probably triaged this wrong as I'm not sure I understand the question, and I'm confused by the milestones :)

**Comment by philippjfr** [comment]
Using callbacks on a Bokeh ColumnDataSource is now fully supported whether on notebook or server. When using it in the notebook you may also have to call `pn.io.push_notebook` to push the updates to the frontend. This helper function is introduced in https://github.com/holoviz/panel/pull/2447.
