### ISSUE TITLE
Propagate parameter 'disabled' to function 'embed'

### ISSUE THREAD

**Issue by JuliaS92** [holoviz/panel#1295]
Dear developers,

I am building a rather large app, of which I would like to send embedded .html-versions to non-programming collaborators. Since embedding calculates all combinations of interface elements I have to reduce the options. I would however still like to show which options will be available in the end. I was hoping to achieve this by disabling some of the widgets using the 'disabled' parameter. Unexpectedly the embedding function still rattles through all the possible combinations regardless whether they are even available in the end.

## Expected behaviour
I would like to only precalculate for the widget states, that are enabled and use the set value for all widgets with disabled=True.

## Alternatives
For many widgets it is possible to reduce the number of options easily. However, if I want to go down to a single default value different widgets would have to be used for some cases (e.g. TextInput or Select instead of IntSlider). Another alternative is to not include these widgets in the embedded app at all. Both options require a lot more programmatic effort than just setting a boolean value and also don't allow to show the originally intended output. Of course hosting the full app straight away is the other option, but I still feel like propagating the disabled parameter to the embedding function would be the expected behaviour.

## Minimal code example where I would expect only one state:
```python
import panel as pn
import time
select = pn.widgets.Select(options=[1,2,3], value=2, disabled=True)
@pn.depends(select.param.value)
def show_select(value):
    time.sleep(2)
    return "This was selected: {}".format(value)
app = pn.Row(select, show_select)
app.embed()
```

**Comment by philippjfr** [comment]
Yes, this makes sense. Any chance you could submit a PR to this effect, I think all that needs to happen is that you modify the `is_embeddaable` function inside `panel.io.embed.embed_state` to return False if the widget is disabled.

**Comment by JuliaS92** [comment]
Thank you for the quick reply! I can give it a try - will be my first community contribution.

**Comment by maximlt** [comment]
Hi @JuliaS92,

I did my first contribution recently here in panel. You can find some guidance in the Developer guide [here](https://panel.holoviz.org/developer_guide/index.html).

If you've never worked with Git before, I found this Gist to be quite useful: https://gist.github.com/Chaser324/ce0505fbed06b947d962

Good luck ;)
