### ISSUE TITLE
Blank webpage coming while running any Jupyter notebook from cmd using the panel serve command

### ISSUE THREAD

**Issue by naaybalodia** [holoviz/panel#1300]
When I create a panel dashboard and run it from Jupyter Notebook (using panel.extension()) it runs perfectly. 

But when I do panel.servable() and run the notebook from the command prompt using the panel serve command, I get blank webpages. In the command prompt, it shows 404 GET/static/extensions/panel/panel.min.js. I have attached the screenshot of the command prompt messages that I got.

I have also attached the panel.min.js file which I found while searching in the Anaconda folder. I can't understand what is the problem and why the blank webpage keeps coming on running any panel server from the command prompt. Please help. 

[SimplePanel.zip](https://github.com/holoviz/panel/files/4533939/SimplePanel.zip)

**Comment by xavArtley** [comment]
Try to update bokeh 2.0.2

Le sam. 25 avr. 2020 à 22:22, naaybalodia <notifications@github.com> a
écrit :

**Comment by naaybalodia** [comment]
Worked like a charm! No more blank webpages. Thank you.
