### ISSUE TITLE
Altair tooltip dates are offset or incorrect by minus one day when rendered using Panel

### ISSUE THREAD

**Issue by pybokeh** [holoviz/panel#1303]
Hello ran into a bizarre bug.  I successfully created a COVID-19 dashboard with hvplot line chart, hvplot tables, and plotly's choropleth map using reactive API.  I then created a another version where I am just replacing the hvplot line chart with Altair's line chart as I wanted to test Panel's ability to support 3 data visualization backends within the same app.

Everything is fine except the bizarre thing is, if the Altair chart is rendered with Panel, the dates that show up in the tooltip is incorrect.  By incorrect, I mean it is showing minus one day with respect to the correct date, in other words, offset or incorrect by minus one day.  To see if problem occurs outside of notebook environment, I created a standalone py script version, and the problem with the dates in the tooltip still occurred.

But if I render the Altair chart without Panel, the dates in the tooltip are correct.  I have very little web dev or javascript knowledge, so not sure what additional diagnostic information I can provide.

Here is my notebook [example](https://github.com/pybokeh/jupyter_notebooks/blob/master/panel/Altair_Dates_Tooltip_Problem.ipynb) that someone can try to reproduce the problem with.  I am on Ubuntu machine with panel version 0.9.5 and bokeh version 2.0.1.

Here is my pip freeze output:
altair==4.1.0
astroid==2.3.3
attrs==19.3.0
backcall==0.1.0
bokeh==2.0.1
colorcet==2.0.2
cycler==0.10.0
decorator==4.4.2
entrypoints==0.3
holoviews==1.13.2
hvplot==0.5.2
ipykernel==5.2.1
ipython==7.13.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.2.1
mccabe==0.6.1
numpy==1.18.2
packaging==20.3
pandas==1.0.3
panel==0.9.5
param==1.9.3
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.1
plotly==4.6.0
prompt-toolkit==3.0.5
ptyprocess==0.6.0
pyct==0.4.6
Pygments==2.6.1
pylint==2.4.4
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2019.3
pyviz-comms==0.7.4
PyYAML==5.3.1
pyzmq==19.0.0
retrying==1.3.3
scipy==1.4.1
seaborn==0.10.0
six==1.14.0
toolz==0.10.0
tornado==6.0.4
tqdm==4.45.0
traitlets==4.3.3
typing-extensions==3.7.4.2
vega-datasets==0.8.0
wcwidth==0.1.9
wrapt==1.11.2

EDIT: Provided a simple example to duplicate the problem.

**Comment by jbednar** [comment]
Timezone issues, maybe?

**Comment by pybokeh** [comment]
I apologize, I should've provided a more simplified example.  Here's an [example](https://github.com/pybokeh/jupyter_notebooks/blob/master/panel/Altair_Dates_Tooltip_Problem.ipynb) I came up with.

**Comment by pybokeh** [comment]
@jbednar No idea.  Raw data don't include time, just date.  Weird that the difference is being caused by whether or not the Altair chart is being rendered with Panel or not.

**Comment by ananis25** [comment]
I'm getting a similar error with using panel's `pane.Vega` renderer for altair plots in that the timestamp axis seems to have an arbitrary offset. Curiously, 

```py
# chart = altair chart

panel.vega.Vega(chart)  # inserts offset
panel.vega.Vega(chart.to_dict())  # works as expected
altair.Chart.from_json( chart.to_json() )  # inserts offset
```
The altair documentation indicates this is a browser related [issue](https://altair-viz.github.io/user_guide/times_and_dates.html#note-on-browser-compliance), which is weird because you'd expect all the renderers in the same browser tab to work similarly? But it is also not limited to panel. 

Using timezone aware columns for datetime in the pandas dataframe seems to give me consistent behavior across panel/altair and after (de)serialization.

**Comment by tonyfast** [comment]
closing, this as it seems out of our control. perhaps we can remind folks to use timezone aware columns in examples.
