### ISSUE TITLE
Hierarchical/Linked Selectors

### ISSUE THREAD

**Issue by sdc50** [holoviz/panel#1311]
I often find myself creating a chain of hierarchical `ObjectSelectors` and re-coding a lot of boiler plate code to make it work. It would be great if Panel could provide a better way of linking Selector widgets where the options of one depend on the value of another.

This is a typical case of linked selectors:

![Car Selector](https://user-images.githubusercontent.com/6454472/80629498-8b59fc80-8a18-11ea-95e7-cf548acbc615.gif)

**Code:**
<details>

```python
car_data = {
    'Subaru': {
        'Outback':['Base', 'Premium', 'Limited', 'Onyx Edition XT', 'Touring', 'Limited XT', 'Touring XT'],
        'Forester': ['Base', 'Premium', 'Sport', 'Limited', 'Touring'],
        'Ascent': ['Base', 'Premium', 'Limited', 'Touring'],
    },
    'Tesla': {
        'Model S': ['Base', 'Long Range', 'Performance'],
        'Model X': ['Base', 'Long Range', 'Performance'],
        'Model Y': ['Base', 'Long Range', 'Performance'],
    },
    'Audi': {
        'A3': ['Premium', 'Premium Plus', 'S line Premium'],
        'A4': ['40 Premium', '45 Premium', '40 Premium Plus', '45 Premium Plus', '40 Prestige', '45 Prestige'], 
    },
}

class CarSelector(param.Parameterized):
    make = param.ObjectSelector(objects=list(car_data.keys()))
    model = param.ObjectSelector()
    trim = param.ObjectSelector()
    
    def __init__(self, **params):
        super().__init__(**params)
        self.make = self.param.make.objects[0]
    
    @param.depends('make', watch=True)
    def update_model_objects(self):
        model_objects = list(car_data[self.make].keys())
        self.param.model.objects = model_objects
        self.model = model_objects[0]
        
    @param.depends('model', watch=True)
    def update_trim_objects(self):
        trim_objects = car_data[self.make][self.model]
        self.param.trim.objects = trim_objects
        self.trim = trim_objects[0]
    
    def panel(self):
        return pn.Param(self)

car_selector = CarSelector()
car_selector.panel()
```

</details>

I don't know what the best API for this would be, but maybe having some way to specify a parent in the ObjectSelector:

```python
    make = param.ObjectSelector(objects=car_data)
    model = param.ObjectSelector(objects=car_data, parent=make)
    trim = param.ObjectSelector(objects=car_data, parent=model)
```

**Comment by MarcSkovMadsen** [comment]
I recently saw the same problem.

Here is my first iteration on a solution. I provide it here for inspiration and to foster discussion.

```python
"""This module contains the FilterSelect widget which extends the
existing Select widget.

Use the FilterSelect widget if your Select.objects depends on some other selections.
"""
from typing import Callable, List, Optional, Union

import pandas as pd
import param


def auto_update_parameter_objects(  # pylint: disable=too-many-arguments
    app: param.Parameterized,
    parameter: str,
    filter_func: Union[Callable, List, pd.DataFrame],
    filter_parameters: List[str],
    key: Optional[str] = None,
    value: Optional[str] = None,
):
    """Adds automatic updating of the `app.param[parameter].objects` based on the values of the
    `filter_parameters`.

    One use case is an parameterized class with region and country ObjectSelector parameters.

    ```python
    OBJECT_ROWS = [
        {"country": "Denmark", "run": "First", "id": 1},
        {"country": "Germany", "run": "Second", "id": 2},
    ]


    class AppWithAutoUpdate(App):
        country = param.ObjectSelector(default="Denmark", objects=["Denmark", "Germany", "Sweden"])
        value = param.ObjectSelector()

        def __init__(self, **params):
            super().__init__(**params)

            auto_update_parameter_objects(
                app=self,
                parameter="value",
                filter_func=OBJECT_ROWS,
                filter_parameters=["country"],
                key="id",
                value="run",
            )

    app = AppWithAutoUpdate(country="Germany")
    ```

    Parameters
    ----------
    app : param.Parameterized
        A `param.Parameterized` class
    parameter : str
        The name an ObjectSelector parameter. For example "value"
    filter_func : Union[Callable, List, pd.DataFrame]
        - A callable on the form `def update_func(**params)` that takes values of the
        `filter_parameters` and the associated app values as input and updates
        `app.param[parameter].objects`
        - A List of dictionaries where each dictionary has the keys of filter_parameters, key and
        value
        - A DataFrame with columns containing the filter_parameters, key and value
    filter_parameters : List[str]
        A list of parameters in `app.param` that the objects depend on. For example ["country"]
    key : Optional[str], optional
        The name of the `value` key or column, by default None. For example "run"
    value : Optional[str], optional
        The name of the `name` key or columns, by default None. For example "id"

    Returns
        The watcher

    Raises
    ------
    ValueError
        If the filter_func is not a valid type
    """
    if isinstance(filter_func, list):
        update_func = create_update_func_from_rows(
            app=app, parameter=parameter, object_rows=filter_func, key=key, value=value
        )
    elif isinstance(filter_func, pd.DataFrame):
        update_func = create_update_func_from_dataframe(
            app=app, parameter=parameter, object_dataframe=filter_func, key=key, value=value
        )
    elif callable(filter_func):
        update_func = create_update_func(
            app=app, parameter=parameter, filter_func=filter_func, key=key, value=value
        )
    else:
        raise ValueError("The `filter_func` provided is not of a valid type")

    def update_callback(_=None):
        params = {param: getattr(app, param) for param in filter_parameters}
        update_func(**params)

    update_callback()

    return app.param.watch(fn=update_callback, parameter_names=filter_parameters)


def create_update_func_from_rows(
    app: param.Parameterized, parameter: str, object_rows, key, value, **params
) -> Callable:
    """
    Parameters
    ----------
    app : param.Parameterized
        A `param.Parameterized` class
    parameter : str
        The name an ObjectSelector parameter. For example "value"
    object_rows : List
        A List of dictionaries where each dictionary has the keys of filter_parameters, key and
        value
    key : Optional[str], optional
        The name of the `value` key, by default None
    value : Optional[str], optional
        The name of the `name` key, by default None

    Returns
    -------
    Callable
        A callable on the form `def update_func(**params)` that takes values of the
        `filter_parameters` and the associated app values as input and updates
        `app.param[parameter].objects`
    """
    filter_func = _create_filter_func_from_rows(object_rows=object_rows, key=key, value=value)

    return create_update_func(app, parameter, filter_func, **params)


def create_update_func_from_dataframe(
    app: param.Parameterized, parameter: str, object_dataframe, key, value, **params
) -> Callable:
    """
    Parameters
    ----------
    app : param.Parameterized
        A `param.Parameterized` class
    parameter : str
        The name an ObjectSelector parameter. For example "value"
    object_dataframe : pd.DataFrame
        A DataFrame with columns containing the filter_parameters, key and value
    key : Optional[str], optional
        The name of the `value` column, by default None
    value : Optional[str], optional
        The name of the `name` column, by default None

    Returns
    -------
    Callable
        A callable on the form `def update_func(**params)` that takes values of the
        `filter_parameters` and the associated app values as input and updates
        `app.param[parameter].objects`
    """
    object_rows = object_dataframe.to_dict(orient="records")

    filter_func = _create_filter_func_from_rows(object_rows=object_rows, key=key, value=value)

    return create_update_func(app, parameter, filter_func, **params)


def create_update_func(app: param.Parameterized, parameter: str, filter_func, **params):
    """[summary]

    Parameters
    ----------
    app : param.Parameterized
        A `param.Parameterized` class
    parameter : str
        The name an ObjectSelector parameter. For example "value"
    filter_func : [type]
        A callable on the form `def update_func(**params)` that takes values of the
        `filter_parameters` and the associated app values as input and updates
        `app.param[parameter].objects`

    Returns
    -------
    Callable
        A callable on the form `def update_func(**params)` that takes values of the
        `filter_parameters` and the associated app values as input and updates
        `app.param[parameter].objects`
    """

    def update_func(**params):
        if not filter_func:
            return

        objects_dict = filter_func(**params)
        objects = list(objects_dict.values())
        if app.param[parameter].objects != objects:
            # Needs individual updates
            # See https://github.com/holoviz/param/issues/398
            app.param[parameter].names = objects_dict
            app.param[parameter].objects = objects

        if not objects:
            app.param[parameter].default = None
            if app.param[parameter].allow_None:
                setattr(app, parameter, None)
            return

        if getattr(app, parameter) in objects:
            return

        value = objects[0]

        if app.param[parameter].default != value:
            app.param[parameter].default = value
        if getattr(app, parameter) != value and value:
            setattr(app, parameter, value)

    update_func(**params)
    return update_func


# region Utility Function


def _include_func(row, **params):
    if not params:
        return True
    return all(row[k] == v for k, v in params.items())


def _create_filter_func_from_rows(object_rows, key, value):
    def filter_func(**params):
        return {row[value]: row[key] for row in object_rows if _include_func(row, **params)}

    return filter_func


# endregion
```

**Comment by MarcSkovMadsen** [comment]
The reason this is important is that I compare this to Tableau where you drag and drop you widgets around and also setup relationships pretty quickly to explore and understand your data.

I do this all the time.

I believe it should be possible to create something very fast to use for Panel as well. So that Panel is actually also fast for prototyping and exploration.

**Comment by maximlt** [comment]
I believe this has been implemented with https://panel.holoviz.org/reference/widgets/NestedSelect.html.

**Comment by ahuang11** [comment]
It would be nice to link NestedSelect to param objects.
