### ISSUE TITLE
support latex rerender in widget labels

### ISSUE THREAD

**Issue by akhmerov** [holoviz/panel#1324]
#### Is your feature request related to a problem? Please describe.

When a a widget label is modified, it doesn't trigger latex rerender, therefore making panel incompatible with mathjax labels.

To observe the behavior, run and tweak the slider (taken from [this discourse thread](https://discourse.holoviz.org/t/latex-labels-in-a-holomap/613/2)):

```
from bokeh.models import Slider
from bokeh.io import show, output_notebook
output_notebook()

show(Slider(title=r'$\mu$', value=0, start=0, end=10))
```

![](https://discourse.holoviz.org/uploads/default/original/1X/8aeea8726b0a2abce485b4e88276fdb056e6662f.gif)

#### Describe the solution you'd like

Not exactly sure what's the relation between the holoviz stack and mathjax/katex, but for example mathjax rerender could be run on any label refresh.

**Comment by philippjfr** [comment]
Hopefully this will become possible as part of bokeh 2.5.0.

**Comment by akhmerov** [comment]
Amazing! Is there an issue or PR that I can track?

**Comment by philippjfr** [comment]
Looks like this wasn't actually on the radar yet but shouldn't be difficult to support. See https://github.com/bokeh/bokeh/issues/11355

**Comment by philippjfr** [comment]
This was implemented a while ago:

<img width="326" alt="Screen Shot 2023-02-17 at 20 13 23" src="https://user-images.githubusercontent.com/1550771/219765846-24380fa1-3904-4496-9965-5838e9c1333d.png">
