### ISSUE TITLE
Update DataFrame widget value immediately upon selection with cell SelectEditor

### ISSUE THREAD

**Issue by mmorys** [holoviz/panel#1325]
#### Is your feature request related to a problem? Please describe.
The DataFrame allows for cell values to be selected from a dropdown list as [documented here](https://panel.holoviz.org/reference/widgets/DataFrame.html). The frustrating issue is that the user is required to either hit 'Enter' on the keyboard, or click elsewhere in the table to confirm selection.

#### Describe the solution you'd like
 It would be more intuitive for the "value" parameter change event to fire immediately when the cell value is selected, and not require the user to hit enter or click elsewhere in the table. Hitting 'Enter' works, but if the user changes a cell value and doesn't do this, these changes may be lost.

#### Minimal example code
Minimal example has a watch set for the DataFrame widget "value" parameter. When the "value" changes (i.e. the user changes a cell in the table), the console prints out a line of text with a timestamp.
```
import panel as pn
import pandas as pd
import timeit
from bokeh.models.widgets.tables import SelectEditor

select_options = ['a','b','c']
select_editor = SelectEditor(options=select_options)
df = pd.DataFrame({'Letters':['a','b','c'], ' Numbers':[1,2,3]})

df_widget = pn.widgets.DataFrame(df, editors={'Letters': select_editor})
df_widget.param.watch(lambda value: print("Edited {}".format(timeit.default_timer())), 'value')
df_widget.servable()
```

#### Screen capture using example code
![Peek 2020-05-06 17-41](https://user-images.githubusercontent.com/10374345/81232374-c9c85c00-8fc2-11ea-8030-dcfca361e93e.gif)

**Comment by philippjfr** [comment]
Sorry no one ever replied here. This is definitely an issue in the implementation of the select editor in Bokeh and will have to be fixed there.

**Comment by philippjfr** [comment]
At this point we (Panel maintainers) will no longer put much effort into the classic DataTable and instead focus development on [Tabulator](https://panel.holoviz.org/reference/widgets/Tabulator.html). If you need this feature it should be raised as an issue in Bokeh.
