### ISSUE TITLE
pn.param mapping of boolean to toggle fails with param.depends

### ISSUE THREAD

**Issue by lvankouwen** [holoviz/panel#1331]
#### ALL software version info

I am working on the branch "static_serve" on the panel_dev conda environment. 
panel                     0.10.0a2.post9+g643033f           dev_0                 <develop>
param                    1.10.0a2                                      py_0                    pyviz/label/dev
parameterized       0.7.4                                            pyh9f0ad1d_0    conda-forge
(Windows, Chrome browser)

#### Description of expected behavior and the observed behavior

I expect the toggle and the checkbox to work in the same way when rendered via pn.param. However, only the checkbox seems attach the param.depends method to itself. 
No error message occurs. The method "change_toggle" is just never called. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import param


class BugTester(param.Parameterized):

    bool_toggle = param.Boolean(default=False, label='toggle')
    bool_checkbox = param.Boolean(default=False, label='checkbox')

    def __init__(self, **params):
        super().__init__(**params)

    def view(self):
        widgets = {
            'bool_toggle': pn.widgets.Toggle,
            'bool_checkbox': pn.widgets.Checkbox}
        return pn.Param(self.param, widgets=widgets)

    @param.depends('bool_toggle', watch=True)
    def change_toggle(self):
        print('toggle changed')

    @param.depends('bool_checkbox', watch=True)
    def change_checkbox(self):
        print('checkbox changed')


if __name__ == "__main__":
    bug = BugTester()
    pn.serve(bug.view(), port=5050)
```

**Comment by maximlt** [comment]
If you run `bug.bool_toggle = True` you should see that the callback `change_toggle` is executed. It means the parameter `bool_toggle` and the toggle widget are not synchronized.
