### ISSUE TITLE
Convert examples to use default templates

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#1340]
In https://github.com/holoviz/panel/pull/1277 we added support for default templates (currently a MaterialTemplate and a BootstrapTemplate). We should add some examples that use these themes or convert existing examples to use the themes.

**Comment by jbednar** [comment]
And preferably provide the same example with multiple themes, to show in a moderately complex example how the theming changes things.

**Comment by philippjfr** [comment]
This has been done for a while thanks to the great work of @MarcSkovMadsen.
