### ISSUE TITLE
Using Parameterized Class, DiscreteSlider's value does not update in UI when using pn.Row()/pn.Column()

### ISSUE THREAD

**Issue by pybokeh** [holoviz/panel#1351]
OS: Windows 10
Bokeh: 2.0.2
Panel: 0.95

**Problem:** When I move the slider, the chosen value does not update in the UI, it remains or stays at the default value (stays at "7").

**Example code to duplicate:**
```
import panel as pn
import param

class SalesExplorer(param.Parameterized):
    rm_period = param.Integer(7, bounds=(7, 90))

sales = SalesExplorer()

app = pn.Row(
               pn.Param(sales.param.rm_period, 
                   widgets={'rm_period': pn.widgets.DiscreteSlider(
                       name='Rolling Mean Period',
                       options=[7, 14, 30, 60, 90], value=7)
                   }
               )  
           )

app
```

The value returned from doing ```sales.rm_period``` is correct, it just doesn't update the value in the UI as you move the slider.  If I don't pass in the ```widgets=``` parameter, the UI updates the value fine.  But of course, I want the slider to only allow specific discrete values.

I also learned if you *don't* wrap the pn.Param object in pn.Row() or pn.Column(), the UI updates fine.  

For example:
```
discrete_slider = pn.Param(sales.param.rm_period, 
                               widgets={'rm_period': pn.widgets.DiscreteSlider(
                                   name='Rolling Mean Period',
                                   options=[7, 14, 30, 60, 90], value=7)
                               }
                           )

discrete_slider
```

This problem occurs both in notebook and in standalone mode.

**Expected outcome:**
When I move the discrete slider, the value that is displayed in the UI should update or show the chosen or correct value.

**Comment by xavArtley** [comment]
As a work around you can use :
```
app = pn.Column(
                pn.Param(sales.param.rm_period, 
                   widgets={'rm_period': pn.widgets.DiscreteSlider(
                       name='Rolling Mean Period',
                       options=[7, 14, 30, 60, 90], value=7)
                   }
               ).layout
           )
app
```

**Comment by pybokeh** [comment]
@xavArtley Thanks!  That worked.  With other slider types, I don't need to add the ```.layout```, just the discrete one that I know of so far.

**Comment by xavArtley** [comment]
Yes that's a bug. I just gave you a workaround.

**Comment by pybokeh** [comment]
Just wanted to report that I have upgraded my panel version to 0.10.1 and removed the above workaround and no longer have this issue.  Thanks for these recent updates.  They are awesome!
