### ISSUE TITLE
Add warning when Panel passed method/function with watch=True

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#1352]
Probably the most common confusion I see among Panel users is that they add `watch=True` to `param.depends` when they don't need to. Since this is pretty much never a sensible thing to do when passing a method or function to Panel, I'm considering whether we should just warn when a user gives a method/function which has watch=True on it to Panel.

**Comment by maximlt** [comment]
That's a great idea, it took me a while before I managed to understand that concept. When you see that `watch=True` option you just naturally want to use it because without it you may think the callback you set doesn't do anything at all. What made me click is when I read somewhere that `watch=True` was best suited for methods that have side effects. Do not hesitate to provide a rather long warning message that explains clearly why `watch=True` isn't needed when the method/function explicitly returns something.

**Comment by jbednar** [comment]
I think the underlying source of confusion here is that Param only actually implements a subset of what it lets you declare. E.g. you can declare a `default` and `bounds` for Parameters, and Param will respect and enforce those directly. , but it won't do anything with `soft_bounds` or `step`; those are just hints left around for a GUI to use if it supports them.  

`@depends` is used both ways; by default it merely records dependency information (which Panel can then inspect and use), but if you also say `watch=True` Param actively re-runs the method itself, independently of Panel. That makes sense for something only used for its side effects, but if it's returning a value, Param has nowhere to put the value.  Panel does know what to do with a return value (i.e. display it), so if you provide such a method to Panel, it doesn't make sense for Param to also be invoking that method when a Parameter on which it depends changes; Panel will already be doing that, and moreover will be doing something with the output, making it be called twice with one of the return values discarded (surely an error!).

So  at least as far as Param and Panel alone are concerned, it is difficult to see any middle ground; `watch=True` makes sense for side-effecty methods with no return value, and the default `watch=False` makes sense for methods Panel calls to update a display.

So I do think it makes sense for Panel to warn when given a method or function with `watch=True` dependencies; that's almost surely (always?) an error.
 
What's less clear to me is whether `watch=True` _ever_ has valid uses for methods returning a value, ignoring Panel.  At the Param level, are there any cases where we want Param to invoke the method and then discard the output?  It's hard to see why that would ever be desirable. If not presumably the warning or error should be at the Param level, not the Panel level.

**Comment by maximlt** [comment]
Thanks for having included that long warning message, it's gonna help a lot of people for sure!

**Comment by MarcSkovMadsen** [comment]
One thing is that I actually almost never user `depends` without `watch`.

The reason being that if you return layouts, panes or widgets from a function decorated with `depends` into for example a column it makes your application slow. The application works much better if you just update the `object` or other parameters of the `pane`, `layout` or `widget`.

I see a lot of these examples in the documentation but they gave me a lot of problems when I started using Panel.

I use `depends` with `watch` a lot though. But those functions do not return anything. They update the `object` of a `pn.pane.Holoviews` pane instead as an example.

**Comment by maximlt** [comment]
Have you identified why it makes your application slower?

**Comment by MarcSkovMadsen** [comment]
Removing and adding panel, layouts and widgets take more time than updating them.

I think it’s due to time for transferring data and laying things out.

**Comment by philippjfr** [comment]
Right, we should expand the API user guide with a section discussing the performance implications of the various approaches. Your suggestion of passing parameters to panes is already covered by https://github.com/holoviz/param/issues/363
