### ISSUE TITLE
ipywidgets on_click events don't work

### ISSUE THREAD

**Issue by ofirbit** [holoviz/panel#1363]
#### ALL software version info
jupyterlab==2.0.1
panel==0.9.5
jupyter-bokeh==2.0.1
bokeh==2.0.2
@pyviz/jupyterlab_pyviz v1.0.2
@jupyter-widgets/jupyterlab-manager v2.0.0

#### Description of expected behavior and the observed behavior
When we convert a Panel button object to be an `ipywidget` button, it's on_click events stop working.

#### Complete, minimal, self-contained example code that reproduces the issue

* This code will not print the `hello world` to the screen:
```
import panel as pn
import ipysheet

pn.extension(comms='ipywidgets')  # remove the "comms='ipywidgets'" and "hello world" will appear on click

button = pn.widgets.Button(name="click me")
def on_button_clicked(kkk):
    print('hello world')
button.on_click(on_button_clicked)
button
```

* Another way to reproduce the problem is with the `pn.ipywidget()` function:

```
import panel as pn
import ipysheet

pn.extension()

button = pn.widgets.Button(name="click me")
def on_button_clicked(kkk):
    print('hello world')
button.on_click(on_button_clicked)
pn.ipywidget(button)  # replace that with just `button` and "hello world" will appear on click
```

#### Screenshots or screencasts of the bug in action

* With `comms='ipywidgets'` the button does not react to clicks:
![image](https://user-images.githubusercontent.com/45560972/82350276-cf329700-9a03-11ea-9e2c-5fa54c19492f.png)

* Of course, with a normal Panel button, the "on_click" event works:
![image](https://user-images.githubusercontent.com/45560972/82350578-33edf180-9a04-11ea-873b-1cb8850669b6.png)

**Comment by philippjfr** [comment]
Thanks for the issue. This will be fixed by https://github.com/holoviz/panel/issues/1363.
