### ISSUE TITLE
Allow to set address with panel.serve

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1364]
#### My Pain

I'm working on a major refactor of awesome-panel.org where I would like to enable serving a set of Panel applications on individual urls.

- The main app should be served at `/` and not as today at `/app`.
- I would like to serve for the material theme builder at `/themebuilder`
- I would like to serve the awesome panel designer at `/designer`
- I would like to be able to serve more aps at `/app-name` in the future.

The only way I can achieve this is via `panel.serve` I believe. But as my application runs in a docker container I need to be able to set the `address` to `0.0.0.0`. This is currently not possible to do.

(I can set the port to 80 though. That is also needed for deployment to Azure).

#### Solution

Enable specifying the `address` when running `panel.serve`. 

The serving command would then be something like

```python
pn.serve(APP_ROUTES, address="0.0.0.0", port=80, dev=False, title="Awesome Panel")
```

**Comment by philippjfr** [comment]
I may be confused but I think the keyword you're looking for is `websocket_origin`.

**Comment by MarcSkovMadsen** [comment]
Setting address does it. It just not documented.

Problem solved.
