### ISSUE TITLE
Documentation demo for JavaScript jscallback function not working

### ISSUE THREAD

**Issue by nels** [holoviz/panel#1366]
The *Defining Javascript callbacks* section in the documentation [here](https://panel.holoviz.org/user_guide/Links.html) has example code for using **jscallback**:
```
value1 =   pn.widgets.Spinner(value=0, width=75)
operator = pn.widgets.Select(value='*', options=['*', '+'], width=50, align='center')
value2 =   pn.widgets.Spinner(value=0, width=75)
button =   pn.widgets.Button(name='=', width=50)
result =   pn.widgets.StaticText(value='0', width=50, align='center')

button.jscallback(clicks="""
if (op.value == '*') 
  result.text = (v1.value * v2.value).toString()
else
  result.text = (v1.value + v2.value).toString()
""", args={'op': operator, 'result': result, 'v1': value1, 'v2': value2})

pn.Row(value1, operator, value2, button, result)

```
I placed this code in a Notebook and also tried serving it as an app with
```
row = pn.Row(value1, operator, value2, button, result)
row.servable()
```
In both cases nothing happens when clicking on the equals sign that is supposed to perform the operation between the two arguments.
There are no browser console errors displayed.

The *Linking using custom JS code* section contains a **jslink** code example
```
markdown = pn.pane.Markdown("<b>Markdown display</b>", width=400)
text_input = pn.widgets.TextInput(value="Markdown display")

code = '''
    target.text = '<b>' + source.value + '</b>'
'''
link = text_input.jslink(markdown, code={'value': code})

pn.Row(text_input, markdown)
```
that does work as expected

**Environment**
Python 3.8
Firefox Developer 77 & Chromium 81

*Libs*
bokeh==2.0.2
panel==0.9.5

**Comment by philippjfr** [comment]
Thanks, the problem is that the clicks property was removed in bokeh 2.0 and now you have to add this callback using `js_on_click`.

**Comment by maximlt** [comment]
Should it be checked beforehand that the property exists and raise an error if not? As in:
https://github.com/holoviz/panel/blob/d71eb304c6d157207036e4316a857acaccae5987/panel/reactive.py#L451-L464

Also how do you deal with these kind of backwards incompatible changes in general? There's a least another button using 'clicks' with a `jscallback` in the docs [here](https://panel.holoviz.org/gallery/demos/VTKInteractive.html).

**Comment by philippjfr** [comment]
>Also how do you deal with these kind of backwards incompatible changes in general? There's a least another button using 'clicks' with a jscallback in the docs here.

We should really have put it in the release notes when we upgraded to Bokeh 2.0 but never did.

**Comment by maximlt** [comment]
How about falling back to `js_on_click` if someone writes `button.jscallback(clicks="...", args={...})`? This new method isn't really documented anywhere as of now so it could maybe be turned into a private one. Not sure it's such a good idea though, it just feels it's not abstracting much from bokeh at this point but maybe that's natural when one goes low level dealing with JS callbacks and stuff.
