### ISSUE TITLE
Suggestions for improving the website

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#1369]
Hi,

I've spent quite a lot of time on the website and I  wanted to suggest some potential improvements:
-  [ ] Change the color of the text in the search bar. It's green right now and is difficult to read.
![image](https://user-images.githubusercontent.com/35924738/82906036-effb6f00-9f64-11ea-8254-c16c2fa0547f.png)
- [ ] Move the search bar to a place where it's easier to find and make it bigger
![image](https://user-images.githubusercontent.com/35924738/82906886-36050280-9f66-11ea-82f1-eceee2f11fe5.png)
- [ ] Replace static images by GIFs on the index page to demonstrate the power of Panel and the kind of interactivity you can get (applies to the readme too)
![image](https://user-images.githubusercontent.com/35924738/82906949-47e6a580-9f66-11ea-8bc3-cfdd9fecd66c.png)
- [ ] Headers and sub-headers should be permalink for easier referencing to specific content in a page
![image](https://user-images.githubusercontent.com/35924738/82907179-8ed49b00-9f66-11ea-8bba-0a32916087c2.png)
- [ ] Headers and sub-headers should appear in a table of content always available to the user to more easily browse through the content of a page
- [ ] There should be a link to a **binder** environment on every notebook page
- [ ] The Reference Gallery should be above the Gallery in the table of content (I use it a lot more)
- [ ] The Reference Gallery should have a table of content at the top to quickly find a widget/layout/pane (it's pretty hard now, specially for the widgets, I usually search through the page)
- [ ] The first line describing a widget/layout/pane in the reference gallery should be highlighted in its own box. It's the most important piece of information of the page.
![image](https://user-images.githubusercontent.com/35924738/82907900-83ce3a80-9f67-11ea-9582-b1ede89c4016.png)
- [ ] The API reference manual isn't very useful as of now, clicking on a subpackage removes completely the API table of content which is then difficult to explore
![image](https://user-images.githubusercontent.com/35924738/82908489-57ff8480-9f68-11ea-8cd0-6eab26328757.png)
- [ ] It doesn't look very good when set to a small size (same as on mobile if I'm not mistaken)
![image](https://user-images.githubusercontent.com/35924738/82908651-9137f480-9f68-11ea-9b78-6cab3162054b.png)

These are just suggestions that I believe would make the website look better and easier to use. Feel free to make some more suggestions that I would then add to this list.

**Comment by maximlt** [comment]
As for the first item, I believe the font color in the search bar is set in the `sphing_holoviz_theme`. It could just be set to black.
https://github.com/pyviz-dev/sphinx_holoviz_theme/blob/b822647c6770d7c4d8231efb193edf2988342c82/sphinx_holoviz_theme/static/css/main.css_t#L2136

**Comment by maximlt** [comment]
The `Dask` documentation (the examples exactly) has a binder environment and each page suggests to run the associated notebook in JupyterLab, it works pretty well.
![image](https://user-images.githubusercontent.com/35924738/83258547-be79e200-a1b6-11ea-8fd4-831aa63744e1.png)

See that repo for more info: https://github.com/dask/dask-examples

**Comment by philippjfr** [comment]
I'd like to switch to the new theme used by Bokeh, which was designed with mobile viewing in mind. Adding a binder link to each page would also be nice.

**Comment by MarcSkovMadsen** [comment]
Will you keep the `green` color @philippjfr on the app bar and as the Panel color?

I actually like the green color. But maybe it would like it to be the very nice material green color. :-)

**Comment by maximlt** [comment]
Switching to the Bokeh theme would resolve many of my initial suggestions :)

**Comment by philippjfr** [comment]
Some of these suggestions definitely still apply but a lot has also already changed and the remainder is being tracked elsewhere.
