### ISSUE TITLE
Plotly charts no longer working on demo notebook

### ISSUE THREAD

**Issue by aalasafidler** [holoviz/panel#1370]
I'm trying to run the demo notebook provided at

https://mybinder.org/v2/gh/panel-demos/gapminder/master?urlpath=/gapminder.ipynb

All 3 plots (from holoviews, mpl, and altair) are running fine, but the Plotly chart simply doesn't show. (Similarly, plotly charts I had in other Bokeh projects have stopped working, returning instead the 

`Error: Model 'panel.models.plotly.PlotlyPlot' does not exist. This could be due to a widget or a custom model not being registered before first usage.`)

Can I get the package versions the demo notebook required to work, please?

What I'm currently running is
bokeh                     1.3.0                    pypi_0    pypi
holoviews                 1.12.7                   pypi_0    pypi
panel                     0.6.2                    pypi_0    pypi
plotly                    4.8.0                      py_0    plotly
tornado                   6.0.3            py37h1de35cc_3

**Comment by philippjfr** [comment]
Sorry we never replied here, this was almost certainly an issue with clashing versions of Bokeh and Panel and should be resolved with recent versions.
