### ISSUE TITLE
Enable disabling the FileDownloadWidget

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1371]
#### My Pain

I'm trying to use the FileDownload Widget in my application. Depending on the state of the application there might be a file to download or not. If there currently is nothing to download I would like to disable the FileDownload Widget.

As far as I can see this is not possible according to the documentation at https://panel.holoviz.org/reference/widgets/FileDownload.html. I've also tried instantiating the FileDownload Widget with `disabled=True` and this does not work.

##### Solution

Add `disabled` parameter to FileDownload and implement the associated functionality.

**Comment by maximlt** [comment]
This was added in #1306, you could checkout `master` and see whether it works as you expect.

**Comment by MarcSkovMadsen** [comment]
Closing this one then. Thanks @maximlt
