### ISSUE TITLE
Create JavaScript Callback API 

### ISSUE THREAD

**Issue by sdc50** [holoviz/panel#1372]
It would be nice to have some kind of JavaScript API to trigger Python functions/methods. For example if I create a widget I can register a callback with `widget.param.watch`. However, if I can't produce the desired interface with the existing widgets then I would resort to using an HTML element with custom markup. The problem is that I have no way of registering a callback on the HTML element. 

I would like to be able to do something like this:

```python
pn.pane.HTML('''
<div>
  <a onclick="panel_js_api.call_my_callback_here()">Click Me!</a>
</div>
''')

**Comment by MarcSkovMadsen** [comment]
Hi @sdc50 

This PR has a lot of overlap to your request and could be used to solve it https://github.com/holoviz/panel/pull/1252

**Comment by philippjfr** [comment]
This request is fully covered by the new `ReactiveHTML` component, specifically check out the Slideshow example in the user guide: https://pyviz-dev.github.io/panel/user_guide/Custom_Components.html#examples
