### ISSUE TITLE
Task status indicators

### ISSUE THREAD

**Issue by jlstevens** [holoviz/panel#1373]
Panel already has progress bars which are good for representing a progress level between zero and a hundred percent but it doesn't have task indicators.

To clarify what I mean by that, consider batch jobs on an HPC system (for instance) where you have N tasks that may have multiple different states (e.g pending, executing, completed). Unlike a progress bar, the granularity is discrete and defined by the number of tasks and you may want to have multiple colors to represent these different states.

There is going to be many ways of representing such data, but for now I am imagining a bar with N colored segments where the colors represent the states. If meaningful, the segments might be ordered by task number (or id) in which case you'll probably see a mix of colors along the bar. Alternatively, if the task identity is not important, you can group by status (if you only have two states, say 'executing' and 'completed' this would look a bit like a normal progress bar which jumps forwards every time a task completes)

**Comment by philippjfr** [comment]
Closing since there's been no further interest and this sounds quite specific.
