### ISSUE TITLE
Improve panel.Param alignment of inputs and actions in row

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1375]
#### My Pain

I think `panel.Param` is awesome. It makes it so easy layout parameters of `param.Pameterized` classes without having to spend a lot of time on it.

But for example when implementing the `DE:TE: Object Detection` app at awesome-panel.org I had to spend some time on find a workaround to align the below row.

![image](https://user-images.githubusercontent.com/42288570/83345934-7a9eee00-a318-11ea-8ade-61b83e2288b0.png)

#### Minimal Reproducing example

The problem is that using just one `panel.Param` as in the below code example looks like

![image](https://user-images.githubusercontent.com/42288570/83346004-306a3c80-a319-11ea-8a9b-79dee46cd036.png)

```python
import param
import panel as pn


class DETRApp(param.Parameterized):
    input_image_url = param.String("https://panel.holoviz.org/_static/logo_stacked.png", label="Input Image URL")
    run_detr = param.Action(label="Run DE:TR:")
    set_random_image = param.Action(label="Random Image")

    view = param.Parameter()

    def __init__(self, **params):
        params["view"] = self._get_view()
        super().__init__(**params)

    def _get_view(self):
        top_selections = pn.Row(
            pn.Param(
                self,
                parameters=["input_image_url", "run_detr", "set_random_image"],
                widgets={"set_random_image": {"button_type": "success"}},
                default_layout=pn.Row, show_name=False,
                width=900,
                )
        )
        app_view = pn.Column(
            top_selections,
        )
        return app_view

DETRApp().view.servable()
```

#### Solution

Improve the layout capabilities of `panel.Param` to align inputs with label with buttons.

#### Work Around

![image](https://user-images.githubusercontent.com/42288570/83345952-b2a63100-a318-11ea-8db6-6692c361979e.png)

```python
import param
import panel as pn


class DETRApp(param.Parameterized):
    input_image_url = param.String("https://panel.holoviz.org/_static/logo_stacked.png", label="Input Image URL")
    run_detr = param.Action(label="Run DE:TR:")
    set_random_image = param.Action(label="Random Image")

    view = param.Parameter()

    def __init__(self, **params):
        params["view"] = self._get_view()
        super().__init__(**params)

    def _get_view(self):
        top_selections = pn.Row(
            pn.Param(self, parameters=["input_image_url"], default_layout=pn.Row, show_name=False,),
            pn.Param(
                self,
                parameters=["run_detr", "set_random_image"],
                widgets={"set_random_image": {"button_type": "success"}},
                default_layout=pn.Row,
                show_name=False,
                width=300,
                margin=(14, 5, 5, 5),
                sizing_mode="fixed",
            ),
        )
        app_view = pn.Column(
            top_selections,
        )
        return app_view

DETRApp().view.servable()
```

**Comment by xavArtley** [comment]
Don't know if it will fit your need but you can use the align properties in your widgets:
class DETRApp(param.Parameterized):
    input_image_url = param.String("https://panel.holoviz.org/_static/logo_stacked.png", label="Input Image URL")
    run_detr = param.Action(label="Run DE:TR:")
    set_random_image = param.Action(label="Random Image")

    view = param.Parameter()

    def __init__(self, **params):
        params["view"] = self._get_view()
        super().__init__(**params)

    def _get_view(self):
        top_selections = pn.Row(
            pn.Param(
                self,
                parameters=["input_image_url", "run_detr", "set_random_image"],
                widgets={"set_random_image": {"button_type": "success", "align": "end"},
                         "run_detr": {"align": "end"}},
                default_layout=pn.Row, show_name=False,
                width=900,
                ),
            
        )
        app_view = pn.Column(
            top_selections,
        )
        return app_view

DETRApp().view.servable()

**Comment by philippjfr** [comment]
I do think it would make sense to special case buttons and automatically add `align='end'`.

**Comment by MarcSkovMadsen** [comment]
# Solution

Thanks @xavArtley . Your suggestion works perfectly


![image](https://user-images.githubusercontent.com/42288570/83376229-d4172380-a3d1-11ea-9c13-9cbc8044685a.png)

```python
import param
import panel as pn


class DETRApp(param.Parameterized):
    input_image_url = param.String("https://panel.holoviz.org/_static/logo_stacked.png", label="Input Image URL")
    run_detr = param.Action(label="Run DE:TR:")
    set_random_image = param.Action(label="Random Image")

    view = param.Parameter()

    def __init__(self, **params):
        params["view"] = self._get_view()
        super().__init__(**params)

    def _get_view(self):
        top_selections = pn.Row(
            pn.Param(
                self,
                parameters=["input_image_url", "run_detr", "set_random_image"],
                widgets={"set_random_image": {"button_type": "success", "align": "end"},
                         "run_detr": {"align": "end"}},
                default_layout=pn.Row, show_name=False,
                width=900,
                )
        )
        app_view = pn.Column(
            top_selections,
        )
        return app_view

DETRApp().view.servable()
```

**Comment by MarcSkovMadsen** [comment]
Regarding `align`. I think I know what the problem is. I've never really learned to use it.

The first time I tried to use it was with a `panel.Param` and `default_layout` as `nx2` Gridbox. And I could not get `align` working. I could not understand if `align` was about

- aligning the items of the layout.
- aligning the item self
- aligning horizontally
- aligning vertically.

I will have to study this closer to understand.
