### ISSUE TITLE
deck_gl_global_power_plants.html example does not work

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1380]
When I navigate to https://panel.holoviz.org/gallery/param/deck_gl_global_power_plants.html#param-gallery-deck-gl-global-power-plants the example does not work and there is an error message in the console.

![image](https://user-images.githubusercontent.com/42288570/83483355-ba91dc80-a4a2-11ea-8ed1-df4fad9bf1a8.png)

**Comment by jimleetjin** [comment]
@philippjfr  I believe this issue is back.

The map on the website is not loading.

<img width="1437" alt="Screenshot 2020-08-11 at 17 07 15" src="https://user-images.githubusercontent.com/67329480/89914320-24420b80-dbf5-11ea-9ece-d649fa748ae3.png">

**Comment by philippjfr** [comment]
Thanks, reopened. Seems like a new issue though.

**Comment by srcoulombe** [comment]
This is still an issue with v0.9.7 (using pydeck 0.6.1)

**Comment by philippjfr** [comment]
Panel 0.9.1 is old at this point. Current release is 0.11

**Comment by srcoulombe** [comment]
Right that's my bad, apologies. 
I checked using Panel 0.11 and the issue is still there.
