### ISSUE TITLE
stocks_plotly.html#apis-gallery-stocks-plotly  does not show the app

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1381]
Browser: Chrome

If I go to https://panel.holoviz.org/gallery/apis/stocks_plotly.html#apis-gallery-stocks-plotly the app is not shown.

![image](https://user-images.githubusercontent.com/42288570/83481982-72bd8600-a49f-11ea-8006-d332b1ed6527.png)

**Comment by philippjfr** [comment]
Turned out to be an outdated notebook that was deployed on our server. I'm updating the notebooks along with the release this time.
