### ISSUE TITLE
Cannot change 2 Button params simultaneously

### ISSUE THREAD

**Issue by ronif** [holoviz/panel#1382]
Hi! I'm having trouble changing the name and the style of a button in a callback:

```python
import panel as pn
pn.extension()

class Foo:
    def __init__(self):
        self.button = pn.widgets.Button(name='yes', button_type='success')
        self.button.on_click(self.on_click)
    
    def on_click(self, event):
        names = ['yes', 'no']
        types = ['success', 'danger']
        self.button.name = names[self.button.clicks % 2]
        self.button.button_type = types[self.button.clicks % 2]
    
    def view(self):
        return pn.panel(pn.Row(self.button))

x = Foo()
x.view()
```

If you comment out either `self.button.name = names[self.button.clicks % 2]` or ` self.button.button_type = types[self.button.clicks % 2]` then the other line works.

Am I doing something wrong?

#### Versions
python: 3.7
panel: 0.6.3
bokeh: 1.3.4
param: 1.91

**Comment by MarcSkovMadsen** [comment]
Hi @ronif . 

Could you try to see if you can reproduce on the latest version of panel?

Thanks

**Comment by philippjfr** [comment]
Yeah, this works fine using latest Panel (0.9.5). I'll close.
