### ISSUE TITLE
Tabs.html documentation does not show the use of closeable or dynamic

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1387]
Just reading https://panel.holoviz.org/reference/layouts/Tabs.html

And the `dynamic` and `closeable` sections do not actually use/ showcase that functionality.

Maybe its because it cannot in a static page? 

#### Solution

Either use/ showcase the functionality or mention that it cannot be demonstrated in the static page.

![image](https://user-images.githubusercontent.com/42288570/83961089-20f67080-a890-11ea-8d58-05d504a008f2.png)

**Comment by halilbay** [comment]
I'd like to work on this issue, if it is okay for you?

**Comment by philippjfr** [comment]
Would love to see it @halilbay!
