### ISSUE TITLE
How to use sqlalchemy or other ORM with panel?

### ISSUE THREAD

**Issue by atiAkizuki** [holoviz/panel#1393]
The first question is how to ensures that my SQLAlchemy sessions get properly closed/cleaned up so that objects aren't shared when multiple users use it?

**Comment by philippjfr** [comment]
@atiAkizuki Thanks for your question. This is really much more of a usage question rather than an issue so would you mind posting to our Discourse site: https://discourse.holoviz.org/ instead?
