### ISSUE TITLE
VTK models not register when using save function

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#1408]
With the latest vtk changes we can't save anymore the vtk panel

```python
import panel as pn
pn.extension('vtk')
vtk_pane = pn.pane.VTK('https://raw.githubusercontent.com/Kitware/vtk-js/master/Data/StanfordDragon.vtkjs',
                     sizing_mode='stretch_width', height=400, enable_keybindings=True, orientation_widget=True)
vtk_pane.save('vtk_save')
```

produce this error when we open the html file
![image](https://user-images.githubusercontent.com/18531147/84560414-1c283580-ad44-11ea-8669-5c40a9bdeb42.png)

**Comment by xavArtley** [comment]
Ok my bad it's because panel is download from unpkg and the version is 0.9.5

**Comment by philippjfr** [comment]
Wonder if we should upload JS bundles for dev releases and then disable the integrity checks.
