### ISSUE TITLE
VTK - Multiple vtkRenderer in a vtkRenderWindow, SetViewport , vtkViewport , are ignored and merged

### ISSUE THREAD

**Issue by GilShoshan94** [holoviz/panel#1413]
Hi,

I tried to use two vtkRenderer in a single vtkRenderWindow and to use SetViewport() to seperate my window into two areas with two active cameras. 
Since in the documentation of Panel it is only ask to pass a vtkRenderWindow, I thought it should work.
Now I am not sure since I don't really see how to retrieve both camera from the panel.pane object.

So is this a bug or is this a limitation of panel that a single pane cannot have more than one vtkRenderer (and one active camera) ?

(If this is not a bug, can we make this a feature request ?)

##### vtkViewport.SetViewport() :
"Specify the viewport for the Viewport to draw in the rendering window. Coordinates are expressed as (xmin,ymin,xmax,ymax), where each coordinate is 0 <= coordinate <= 1.0."

#### ALL software version info
- OS: Windows 10 Pro (64-bit) version 1909
- Python: 3.8.3
- Chrome: Version 83.0.4103.97 (Official Build) (64-bit)
- Panel: 0.9.5
- Bokeh: 2.0.1

##### Expected behavior:
Each vtkRenderer is render into its own space defined by SetViewport() in the vtkRenderWindow.
Also each camera are accessible from Panel to control (jslink, ...)
##### Observed behavior:
SetViewport() is ignored, both vtkRenderer are merged into the same space.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
# fmt: off
## The 3 followings line are a temp solution until I upgrate to bokeh 2.0.2 (now it 2.0.1) and won't be necessary later
from bokeh.settings import settings  # noqa isort:skip
settings.resources = 'cdn'  # noqa isort:skip
settings.resources = 'inline'  # noqa isort:skip
# fmt: on
import panel as pn
import vtk

# Create the arrow and the associated mapper and actor.
arrow = vtk.vtkArrowSource()
arrowMapper = vtk.vtkPolyDataMapper()
arrowMapper.SetInputConnection(arrow.GetOutputPort())
arrowActor = vtk.vtkActor()
arrowActor.SetPosition(-0.5, 0, 0)
arrowActor.SetMapper(arrowMapper)

# Create the sphere and the associated mapper and actor.
sphere = vtk.vtkSphereSource()
sphere.SetRadius(0.1)
sphereMapper = vtk.vtkPolyDataMapper()
sphereMapper.SetInputConnection(sphere.GetOutputPort())
sphereActor = vtk.vtkActor()
sphereActor.SetMapper(sphereMapper)


# Create two renderers and assign actors to them. A renderer renders into a
# viewport within the vtkRenderWindow. It is part or all of a window on the
# screen and it is responsible for drawing the actors it has.
# We can add the same actor to two different renderers;
# it is okay to add different actors to different renderers as well.
ren1 = vtk.vtkRenderer()
ren1.AddActor(arrowActor)
ren1.SetBackground(vtk.vtkNamedColors().GetColor3d("DarkSlateGray"))
ren1.SetViewport(0.0, 0.0, 0.5, 1.0)

ren2 = vtk.vtkRenderer()
ren2.AddActor(sphereActor)
ren2.SetBackground(vtk.vtkNamedColors().GetColor3d("LightSlateGray"))
ren2.SetViewport(0.0, 0.7, 0.3, 1.0)

# Set the cameras far enough
ren1.GetActiveCamera().SetPosition(0, 0, 3)
ren2.GetActiveCamera().SetPosition(0, 0, 2)


# Finally we create the render window which will show up on the screen.
# We add our two renderers into the render window using AddRenderer.
renderWindow = vtk.vtkRenderWindow()
renderWindow.AddRenderer(ren1)
renderWindow.AddRenderer(ren2)


# Test Panel
a = pn.pane.VTK(renderWindow)
a.show()

# Test VTK
# interactor = vtk.vtkRenderWindowInteractor()
# interactor.SetRenderWindow(renderWindow)
# renderWindow.Render()
# interactor.Start()
```

##### With Panel:
![image](https://user-images.githubusercontent.com/29143941/84646497-dd90a780-af0a-11ea-9915-a2fa0a501850.png)

##### With VTK:
![image](https://user-images.githubusercontent.com/29143941/84646578-fef19380-af0a-11ea-8156-3349e5448a1b.png)

**Comment by xavArtley** [comment]
In next panel version it's almost supported:
![image](https://user-images.githubusercontent.com/18531147/84652430-e635ad80-af0b-11ea-93ed-765165dcec9c.png)

There is a bug with the orientation widget, I'll try to find a way to correct it.

**Comment by GilShoshan94** [comment]
@xavArtley Awsome ! 
Will we be able to access/control each camera (of each viewport/render) too ?

**Comment by GilShoshan94** [comment]
@xavArtley Also, should I close this then?

**Comment by xavArtley** [comment]
I have never used multiple viewports so I don't know what can be done or not. I'm not sure about multiple independant camera

**Comment by xavArtley** [comment]
seems possible
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/18531147/84654621-cd2efb80-af0f-11ea-83b6-0c2897f24ded.gif)

**Comment by GilShoshan94** [comment]
@xavArtley Great ! 
And thank you for such a fast answer.
Should I open a feature request for access/control multiple independent cameras ?

**Comment by xavArtley** [comment]
This issue is fine to reference different problems with viewports
