### ISSUE TITLE
Plotly panel fails to render inside JupyterLab

### ISSUE THREAD

**Issue by LoriHarris** [holoviz/panel#1414]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
Windows 10
Panel  0.9.5
plotly  4.8.1
holoviews 1.13.2
bokeh  2.0.2                    
jupyter_bokeh  2.0.2    
JupyterLab v2.1.4
        @bokeh/jupyter_bokeh v2.0.2 enabled  ok
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
        @pyviz/jupyterlab_pyviz v1.0.4 enabled  ok
        jupyterlab-plotly v4.8.1 enabled  ok
        plotlywidget v4.8.1 enabled  ok        

#### Description of expected behavior and the observed behavior
Panel renders a preview inside JupyterLab, but Plotly and Mapbox component render blank as white space.

See below for white space when Mapbox plots are called.
![image](https://user-images.githubusercontent.com/43394481/84688756-dfa83580-af0d-11ea-9486-064fd99144ff.png)

Tabs with hv.plot components show properly:
![image](https://user-images.githubusercontent.com/43394481/84688827-fcdd0400-af0d-11ea-93b0-d49e93fa742b.png)

The plotly plots that should display render correctly when called ALONE:
![image](https://user-images.githubusercontent.com/43394481/84688878-0fefd400-af0e-11ea-8704-8129c4e8f991.png)

**Comment by philippjfr** [comment]
Thanks, could you do me a favor and look in your browsers Javascript console and see if there are any errors?

**Comment by LoriHarris** [comment]
@philippjfr Yes of course, thank you! 

The console output is different each time I restart the kernel.  This morning my first attempt gave me:

![image](https://user-images.githubusercontent.com/43394481/84770947-88a26f00-afa6-11ea-9ac7-93a02075fc6f.png)

The second time I ran it I got:
![image](https://user-images.githubusercontent.com/43394481/84771466-7bd24b00-afa7-11ea-834b-bcb5156a3d2b.png)

**Comment by philippjfr** [comment]
It looks like it's loading an old version of Bokeh in Javascript, I'm not quite sure how that could happen. I can only suggest that you clear all your notebooks and then refresh the page.

**Comment by LoriHarris** [comment]
Interestingly, if I change the order of the imports to the following:  
```python

import panel as pn
pn.extension('plotly')
import plotly.express as px
import pandas as pd
import hvplot.pandas
import os
from pathlib import Path
from dotenv import load_dotenv
```
The console output changes to:
![image](https://user-images.githubusercontent.com/43394481/84772640-3f075380-afa9-11ea-9cf8-a0ad2c72a98f.png)
And the notebook rendering changes from blank space to scrollable blank space:
![image](https://user-images.githubusercontent.com/43394481/84772741-5fcfa900-afa9-11ea-8c32-241eeb07e31f.png)

**Comment by LoriHarris** [comment]
And one more update - now using the following imports I got the same error in my console, but DID get a plotly output in my rendering:
```python
import jupyter_bokeh
import bokeh
import panel as pn
pn.extension('plotly')
import plotly.express as px
import pandas as pd
import hvplot.pandas
import os
from pathlib import Path
from dotenv import load_dotenv
```
![image](https://user-images.githubusercontent.com/43394481/84773168-061bae80-afaa-11ea-836d-53a22036dd88.png)

![image](https://user-images.githubusercontent.com/43394481/84773135-f9975600-afa9-11ea-9e23-1a5e184870d3.png)

**Comment by philippjfr** [comment]
You definitely shouldn't need `import jupyter_bokeh` for anything, also that `'send' of undefined` you're seeing is harmless (although I should still try to fix it). I suspect you just finally cleared old Bokeh out somehow and it should now work consistently. When upgrading bokeh versions I think an old notebook with an old version of bokeh can end up in your namespace and break things. I would suggest clearing all notebooks you have open in JupyterLab and then reloading the page, that should usually fix things.

**Comment by LoriHarris** [comment]
Thank you!  One more thing I've just noticed and would like to mention.  It does seem that the order of the imports was affecting things.  

My original order was as follows and consistently produces a blank rendering:
```python
import pandas as pd
import hvplot.pandas
import os
from pathlib import Path
from dotenv import load_dotenv
import panel as pn
pn.extension('plotly')
import plotly.express as px
```
My new order seems to be making the magic happen:
```python
import panel as pn
pn.extension('plotly')
import plotly.express as px
import pandas as pd
import hvplot.pandas
import os
from pathlib import Path
from dotenv import load_dotenv
```

**Comment by philippjfr** [comment]
Oh that's a good point, the problem is with this:

```python
import hvplot.pandas
```

This initializes the extension without loading Plotly, if you load Plotly after that it won't initialize correctly. We absolutely need a warning about this.

**Comment by LoriHarris** [comment]
Thank you so much!

**Comment by philippjfr** [comment]
Okay, I did my best here, in Panel 0.9.6 it will warn you if some extension could not be loaded and I've also addressed some asynchronous loading issues with the Plotly component.
