### ISSUE TITLE
Templates get stuck on DarkTheme in notebooks after they're set once.

### ISSUE THREAD

**Issue by kebowen730** [holoviz/panel#1417]
On Panel 0.9.5 while testing a new Template I ran into a bug related to DarkTheme.

 Ive been using the Template.ipynb notebook in the user_guide directiory to test my new template, and for some reason once I set a template with theme=DarkTheme , it always renders with DarkTheme even if I set it back to DefaultTheme, unless I restart the Kernel. This occurs with the new GoldenTemplate that I'm testing, as well as MaterialTemplate and BootstrapTemplate. This only occurs with DarkTheme, DefaultTheme is overridden when it's changed. It seems like an issue with the css sticking around, but I'm not sure what causes it or why it's only with DarkTheme.

To reproduce, in a notebook run:

```python
import panel as pn

bootstrap = pn.template.BootstrapTemplate(title='Bootstrap Template', theme=pn.template.DefaultTheme)

bootstrap.show
```

change it to this and run:

```python
import panel as pn

bootstrap = pn.template.BootstrapTemplate(title='Bootstrap Template', theme=pn.template.DarkTheme)

bootstrap.show
```

and then run again after reverting to the original codeblock, this can also be done using the second python cell in the Panel User Guide notebook I referenced above.

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/1479
