### ISSUE TITLE
MultiSelect Widget typing input fails sometimes

### ISSUE THREAD

**Issue by lastmeta** [holoviz/panel#1420]
#### ALL software version info
panel==0.9.4
bokeh==2.0.0
notebook==6.0.2

#### Description of expected behavior and the observed behavior
Typing in a multiselect widget should always set the widget.value to what is displayed on the widget. Sometimes it does not.

#### Complete, minimal, self-contained example code that reproduces the issue
```
import panel as pn
w = pn.widgets.MultiSelect(
  name='type ab'
  options=[
    'zoo',
    'whatever',
    'something',
    'nothing',
    'aaa', # does not show in the rendering (must scroll down)
    'abch',
    'abci',
    'bcj',])
```

#### Screenshots or screencasts of the bug in action

![image](https://user-images.githubusercontent.com/5642485/84954647-ffc52980-b0b2-11ea-8e72-25770e78d6e0.png)

This doesn't happen all the time, for example, typing zoo works fine. seems to happen if it has to scroll or something...

I don't know if this is a problem with panel or bokeh or if it is due to my version numbers being slightly old. (We choose to update to bokeh 2.0.0 because 2.0.2 caused a much bigger problem: no visual of panel gspec in notebook, but that besides the point.)

**Comment by philippjfr** [comment]
>no visual of panel gspec in notebook, but that besides the point.)

Seems like a pretty severe problem that I haven't heard about, could you file an issue?

**Comment by philippjfr** [comment]
This seems like an upstream issue with Bokeh.

**Comment by philippjfr** [comment]
I don't appear to be able to reproduce this anymore but if it does re-occur the issue should be filed with bokeh.
