### ISSUE TITLE
Pane updating broken in current py37 env

### ISSUE THREAD

**Issue by michaelaye** [holoviz/panel#1440]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
python 3.7.6
browser: Brave (Chromium)
OS: Kubuntu 20.04
notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
jupyterlab                2.1.4                      py_1    conda-forge
bokeh                     2.1.0            py37hc8dfbb8_0    conda-forge
panel                     0.9.5                      py_1    conda-forge

#### Description of expected behavior and the observed behavior

Changing of `object` attribute should update the pane, as instructed in "02_Building_Panels".
It does this, when I use the holoviz-tutorial conda env, but it doesn't when I try it in my up-to-date py37 env.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension()
title = pn.panel('## Earthquake Dashboard')
title   # to display the pane

title.object = '## The Most Powerful Earthquakes'   # this does not update the pane

```

#### Stack traceback and/or browser JavaScript console output
![image](https://user-images.githubusercontent.com/69774/85207965-e0641180-b2e9-11ea-809f-abf21cd6b6f7.png)

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/69774/85207978-fc67b300-b2e9-11ea-8748-8d1799a1a7b6.png)

**Comment by michaelaye** [comment]
just tried in Firefox and it's the same issue.

**Comment by philippjfr** [comment]
Oh this is a known issue. Bokeh 2.1 is not compatible with released panel. That's why I'm releasing panel 0.9.6 tonight.

**Comment by philippjfr** [comment]
Okay, I was a day late but it's released now :)

**Comment by michaelaye** [comment]
No worries, thanks for the release!

**Comment by michaelaye** [comment]
Incidentally, is there a “known issues” page for holoviz that peeps could just quickly look at that are targeted for fixes in the next release? Maybe a simple Gh issues filtr view would serve for that?

**Comment by jbednar** [comment]
Our new policy is to assign open bugs to the next scheduled release, which you can see by looking at the Github milestone for the next upcoming version.  However,  we have a lot of untriaged older issues not assigned to any milestone (trying to catch up on those on regular Monday meetings now!), and of course if we can't get to a particular issue it gets postponed to the following release.
