### ISSUE TITLE
Wrap layout combining pn.Row/pn.Column

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#1446]
Similar to hv.Layout().cols(2) but specialized for panel.

For example, can be specified like:
`pn.Wrap(cols=2)`
or
`pn.Wrap(max_width=300)`?

**Comment by philippjfr** [comment]
Isn't [GridBox](https://panel.holoviz.org/reference/layouts/GridBox.html) exactly that?

**Comment by philippjfr** [comment]
>pn.Wrap(max_width=300)?

This likely will never work, for many components there's no way to know ahead of time how wide they will be.
