### ISSUE TITLE
After upgrade to Panel 0.9.6 and Bokeh 2.1.0 my app becomes 20 times slower to layout

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1452]
OS: Win 10
Panel: 0.9.5 -> 0.9.6
Bokeh: 2.0.2 -> 2.1.0
Browser: Chrome

#### My Pain

I was trying to test out if I could upgrade to Panel 0.9.6 and Bokeh 2.1.0.

After the upgrade my app awesome-panel.org felt slow and sluggish when running locally. And my fan started working like crazy.

After some time I found it its **5-30 times slower to layout**.

FYI @philippjfr and @mattpap . I believe this is a **major issue**.

#### Reproduce

1. Install the awesome-panel.org repo as described in the README.
2. upgrade panel to 0.9.6 and bokeh to 2.1.0
3. run `python app.py`
4. open `localhost` in your browser
5. Navigate to the Yahoo Query app.

#### Yahoo Query app - Opening

Takes 1min 15 sec versus 5-10 secs before

![panel-096-bokeh210](https://user-images.githubusercontent.com/42288570/85356370-17ffd300-b50f-11ea-92a8-7ee448a1a235.gif)

#### Yahoo Query App - Resize

Takes + 2 min versus nothing noticeble before.

![panel-096-bokeh210-resize](https://user-images.githubusercontent.com/42288570/85356476-54333380-b50f-11ea-82df-e8333adb9663.gif)

#### Additional Context

I found out its not enough to downgrade Panel to 0.9.5 and Bokeh 2.1.0. I also need to delete my browser history+cache+cached files before I got the original speed back.

**Comment by philippjfr** [comment]
Suspect the layout optimizations in bokeh and the one in panel aren't interacting well. Will look at it today and then probably release 0.9.7 asap.

**Comment by mattpap** [comment]
>  I also need to delete my browser history+cache+cached files before I got the original speed back.

Removing cache should be sufficient. However, for testing I will recommend always running with devtools open, assuming it was configured to disable cache permanently (devtools > settings > network > disable cache (when devtools is open)).

**Comment by philippjfr** [comment]
The 0.9.7 release is now building: https://travis-ci.org/github/holoviz/panel/builds/701223667
