### ISSUE TITLE
Checkboxgroup doesn't render the widget name

### ISSUE THREAD

**Issue by kcpevey** [holoviz/panel#1457]
#### ALL software version info
Panel 0.10.0a6

#### Description of expected behavior and the observed behavior
Many (most?) of the panel widgets have a `name` field which displays as a title of the widget. However, the Checkboxgroup does not display the `name` as the title. If I'd like my checkboxgroup to have a title label, I have to construct it as a separate element. 

#### Complete, minimal, self-contained example code that reproduces the issue
From the docs (https://panel.holoviz.org/reference/widgets/CheckBoxGroup.html#widgets-gallery-checkboxgroup):
```
checkbox_group = pn.widgets.CheckBoxGroup(
    name='Checkbox Group', value=['Apple', 'Pear'], options=['Apple', 'Banana', 'Pear', 'Strawberry'],
    inline=True)

checkbox_group
```
Even though the `name` field is populated, it does not display above the widget. 

#### Stack traceback and/or browser JavaScript console output
No errors

#### Screenshots or screencasts of the bug in action
<img width="766" alt="Screen Shot 2020-06-24 at 3 07 34 PM" src="https://user-images.githubusercontent.com/15659110/85622455-779fd080-b62c-11ea-87e0-be085dd96b8b.png">

**Comment by maximlt** [comment]
Hi @kcpevey ,

You're right, and this is a known issue, see the complete list of widgets with and without a title here #1313.

Maybe @philippjfr  can hint us about what would be his way forward for these missing titles?

**Comment by philippjfr** [comment]
Thanks Kim! My only suggestions is that we basically have these widgets emit a layout of the widget along with some text. I'm going to close this issue, in favor of the catch-all issue that @maximlt pointed to.

**Comment by kcpevey** [comment]
Thanks! Apologies for the duplication!
