### ISSUE TITLE
Automatically display a spinner or ability to link a dynamic tab to other widgets while it's loading

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#1458]
More info:
https://discourse.holoviz.org/t/can-dynamic-tabs-trigger-progress-active-on-change-of-tab/859/2

**Comment by hyamanieu** [comment]
This can be closed @philippjfr as all elements now have the `loading` parameter.

**Comment by philippjfr** [comment]
I think we still want dynamic=True to default to showing a loading spinner, so I won't close quite yet.

**Comment by philippjfr** [comment]
>I think we still want dynamic=True to default to showing a loading spinner, so I won't close quite yet.

Actually I'm not sure we do, the time to render can be very variable and we don't want to cause annoying flicker by default.
