### ISSUE TITLE
HTML pane linked to ColorPicker widget does not respond live

### ISSUE THREAD

**Issue by mycarta** [holoviz/panel#1462]
#### ALL software version info
Machine: Mac OS 10.14.6
Browser: behaviour experienced with Jupyter Notebook using both Firefox and Chrome

These are the relevant packages in my current _holoviz-tutorial_ environment:
##### Name Version Build Channel
bokeh 2.0.2 py37_0
ipykernel 5.1.4 py37h39e3cac_0
jupyter_client 6.1.3 py_0
jupyter_core 4.6.3 py37_0
panel 0.9.5 py_0 pyviz
python 3.7.7 hf48f09d_4

The full environment is posted [here](https://discourse.holoviz.org/t/issues-with-the-holoviz-tutorial/891/3).

#### Description of expected behavior and the observed behavior

As per [Holoviz Discourse post](https://discourse.holoviz.org/t/colorpicker-functionality-different-from-that-shown-in-the-scipy-2019-tutorial/908/2?u=mycarta):

I am comparing the behaviour in my notebook against @jbednar 's video tutorials from Scipy 2019,  where the HTML pane linked to ColorPicker widget is demonstrated [in here](https://www.youtube.com/watch?v=7deGS4IPAQ0&feature=youtu.be&t=4124).
Since the current [03_Interlinked_Panels tutorial](https://holoviz.org/tutorial/Interlinked_Panels.html) has a RangeSlider example instead of the ColorPicker, I’ve just typed-up the example from the video in my notebook. It is copied below.

However, while in his demonstration the HTML pane updates on the fly as he moves around the picker, in my case it does not: it is only updated when I close the picker, see animated GIF below.

#### Complete, minimal, self-contained example code that reproduces the issue

```


    import panel as pn
    pn.extension()

    color_picker = pn.widgets.ColorPicker(value=’#ff0000’)
    color_picker

    html = pn.pane.HTML(’’, width=200, height=200, background=color_picker.value)
    color_picker.link(html, value=‘background’)
    html


```

#### Stack traceback and/or browser JavaScript console output
I am not sure if it is related but I get this warning in the terminal:
`IPKernelApp] WARNING | No such comm: hv-extension-comm`

#### Screenshots or screencasts of the bug in action
![ColorPicker](https://user-images.githubusercontent.com/7424763/86368882-f901ef00-bc3a-11ea-8c89-b7c6f3ef7df8.gif)

**Comment by xavArtley** [comment]
The actual behavior seems the one intended. 
The previous behavior for me was a bug of the webbrowser
the event connected is `change`:
https://github.com/bokeh/bokeh/blob/a68a6f8a3891fd669db7b954c3a5313d6b571012/bokehjs/src/lib/models/widgets/color_picker.ts#L28
From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/color :
> The change event is fired when the user dismisses the color picker

**Comment by philippjfr** [comment]
Thanks @xavArtley, I think we should replace the example in the user guide in that case.

**Comment by philippjfr** [comment]
The tutorial has been overhauled since and the behavior is indeed intended. If we want to argue to change the behavior that should be done in bokeh.
