### ISSUE TITLE
Please support concept of HTML Extension

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1483]
Panel: 0.9.7

#### Context

As you get into Panel one of the things you would like to do is to be able to refactor your code into small, reusable components. Maybe you want to use them your self, share with your colleagues or maybe even share with the Panel community.

I've started describing how to do this here https://github.com/marcskovmadsen/panel-extensions-template. A user also asks how to do this on Discourse https://discourse.holoviz.org/t/how-to-create-a-self-contained-custom-panel/985.

I would claim that one of the basic, reusable components you would like to create is created by inheriting from the `HTML` pane.

#### Code: param.watch - not working

 I would expect to be able to inherit from the `HTML` pane but it does not work.

![html-extension-not-working](https://user-images.githubusercontent.com/42288570/87845045-b0e1fe00-c8c3-11ea-9ce8-307788b67528.gif)

Steps
1. Run the code below with `panel serve`
2. Drag the slider and see that the page does not update

```python
import panel as pn
import param

def get_html(value):
    """Main functionality of Extension"""
    font_size = value
    alpha = 1-value/100
    green = int(value*255/100)
    return f"""
<div style="font-size: {font_size}px;color: rgba(0,{green},0,{alpha}">{value}</div>
"""

class HTMLExtension(pn.pane.HTML):
    """Extension Implementation"""
    value = param.Integer(default=30, bounds=(0,100))

    def __init__(self, **params):
        self._rename["value"]=None

        super().__init__(**params)
        self.param.watch(self._update, "value")
        self._update()

    def _update(self, _=None):
        self.object = get_html(self.value)
        print("update", self.object)


if __name__.startswith("bokeh"):
    # Create app
    extension = HTMLExtension(width=125, height=125)
    app = pn.Column(
        extension,
        extension.param.value,
        width=150,
    )
    # Serve the app
    app.servable()
```

I can see in the console that the `update` function is run. The HTML pane is just not updating in the browser.

### Example: @param.depends - not working

I would also expect this example to work. But it does not either.

```python
import panel as pn
import param

def get_html(value):
    """Main functionality of Extension"""
    font_size = value
    alpha = 1-value/100
    green = int(value*255/100)
    return f"""
<div style="font-size: {font_size}px;color: rgba(0,{green},0,{alpha}">{value}</div>
"""

class HTMLExtension(pn.pane.HTML):
    """Extension Implementation"""
    value = param.Integer(default=30, bounds=(0,100))

    def __init__(self, **params):
        self._rename["value"]=None

        super().__init__(**params)
        self._update()

    @param.depends("value", watch=True)
    def _update(self, _=None):
        self.object = get_html(self.value)
        print("update", self.object)


if __name__.startswith("bokeh"):
    # Create app
    extension = HTMLExtension(width=125, height=125)
    app = pn.Column(
        extension,
        extension.param.value,
        width=150,
    )
    # Serve the app
    app.servable()

    # Run panel serve 'examples\basic_static.py' in the command line
```

### Additional Context

I can get something working if I'm willing to instantiate and use the extension via `HTMLExtension().view` instead of `HTMLExtension()`. 

But I believe this is a wrong path to take (please argue against). I believe this is the wrong path because it is not what new developers of extensions and new users of Panel would expect. Normally you can just instantiate an object and use it.

If this is the preferred api in Panel for reusable extensions from existing Panel components, then that should be clearly stated somewhere and examples provided I would think. I has been something confusing to me and that I've been wondering about since starting to use Panel.

This example works

![html-extension](https://user-images.githubusercontent.com/42288570/87845180-75e0ca00-c8c5-11ea-9e3b-71658b500d4c.gif)

```
import panel as pn
import param

def get_html(value):
    """Main functionality of Extension"""
    font_size = value
    alpha = 1-value/100
    green = int(value*255/100)
    return f"""
<div style="font-size: {font_size}px;color: rgba(0,{green},0,{alpha}">{value}</div>
"""

class BasicExtension(param.Parameterized):
    """Extension Implementation"""
    value = param.Integer(default=30, bounds=(0,100))
    view = param.Parameter()

    def __init__(self, **params):
        super().__init__(**params)
        self.view = pn.pane.HTML(width=125, height=125)
        self._update()

    @param.depends("value", watch=True)
    def _update(self, *events):
        self.view.object = get_html(self.value)

if __name__.startswith("bokeh"):
    # Create app
    extension = BasicExtension()
    app = pn.Column(
        extension.view,
        extension.param.value,
        width=150,
    )
    # Serve the app
    app.servable()

    # Run panel serve 'examples\basic_static.py' in the command line
```

**Comment by MarcSkovMadsen** [comment]
### Fix: param.watch

I found out that the `_update` function override the `_update` function in the parent class. Just renaming it solved the issue.

import panel as pn
import param

def get_html(value):
    """Main functionality of Extension"""
    font_size = value
    alpha = 1-value/100
    green = int(value*255/100)
    return f"""
<div style="font-size: {font_size}px;color: rgba(0,{green},0,{alpha}">{value}</div>
"""

class HTMLExtension(pn.pane.HTML):
    """Extension Implementation"""
    value = param.Integer(default=30, bounds=(0,100))

    def __init__(self, **params):
        self._rename["value"]=None

        super().__init__(**params)
        self.param.watch(self._update_object, "value")
        self._update_object()

    def _update_object(self, _=None):
        # Note:
        # Don't name the function `_update` as this will override a function in the base class
        self.object = get_html(self.value)
        print("update", self.object)


if __name__.startswith("bokeh"):
    # Create app
    extension = HTMLExtension(width=125, height=125)
    app = pn.Column(
        extension,
        extension.param.value,
        width=150,
    )
    # Serve the app
    app.servable()

    # Run panel serve 'examples\basic_static.py' in the command line
```

**Comment by MarcSkovMadsen** [comment]
### Fix @param.depends example

Renaming the `_update` function and changing its signature also fixed this example

```python
import panel as pn
import param

def get_html(value):
    """Main functionality of Extension"""
    font_size = value
    alpha = 1-value/100
    green = int(value*255/100)
    return f"""
<div style="font-size: {font_size}px;color: rgba(0,{green},0,{alpha}">{value}</div>
"""

class HTMLExtension(pn.pane.HTML):
    """Extension Implementation"""
    value = param.Integer(default=30, bounds=(0,100))

    def __init__(self, **params):
        self._rename["value"]=None

        super().__init__(**params)
        self._update_object()

    @param.depends("value", watch=True)
    def _update_object(self, *events):
        # Note:
        # Don't name the function `_update` as this will override a function in the base class
        self.object = get_html(self.value)
        print("update", self.object)


if __name__.startswith("bokeh"):
    # Create app
    extension = HTMLExtension(width=125, height=125)
    app = pn.Column(
        extension,
        extension.param.value,
        width=150,
    )
    # Serve the app
    app.servable()

    # Run panel serve 'examples\basic_static.py' in the command line
```

**Comment by MarcSkovMadsen** [comment]
### Summary

- I can get `HTML extensions` working.
    - The problem was that I overrode the function `_update` in the Parent Class
- I would like to know if it is expected that Panel users inherit from the `HTML` pane and other Panel Components
- Would like to suggest rename the `_update` function to something more specific such as `_update_bokeh_model` to lower the friction of using Panel.

**Comment by MarcSkovMadsen** [comment]
I've updated the above because for some reason all the `HTML` inheritance examples do not work for me now.

I've tried reinstalling Panel/ Bokeh (still 0.9.7/ 2.1.1). It does not change anything.

**Comment by MarcSkovMadsen** [comment]
Argghh :-) `_update` and `_update_object` (and `_update_model` and `_update_pane`) are functions of the parent `HTML` pane that I should not override.

This code works

```python
"""The DynamicNumber is an example of a HTML Extension for Panel"""
import panel as pn
import param

class DynamicNumber(pn.pane.HTML):
    """Extension Implementation"""
    value = param.Integer(default=30, bounds=(0,100))

    # In order to not be selected by the `pn.panel` selection process
    # Cf. https://github.com/holoviz/panel/issues/1494#issuecomment-663219654
    priority = 0

    def __init__(self, **params):
        # The _rename dict is used to keep track of Panel parameters to sync to Bokeh properties.
        # As value is not a property on the Bokeh model we should set it to None
        self._rename["value"]=None

        super().__init__(**params)
        self._update_object_from_parameters()

    # Don't name the function
    # `_update`, `_update_object`, `_update_model` or `_update_pane`
    # as this will override a function in the parent class.
    @param.depends("value", watch=True)
    def _update_object_from_parameters(self, *events):
        self.object = self._get_html(self.value)

    def _get_html(self, value):
        """Main functionality of Extension"""
        font_size = value
        alpha = 1-value/100
        green = int(value*255/100)
        return f"""
    <div style="font-size: {font_size}px;color: rgba(0,{green},0,{alpha}">{value}</div>
    """


if __name__.startswith("bokeh"):
    # Create app
    extension = DynamicNumber(width=125, height=125)
    app = pn.Column(
        extension,
        extension.param.value,
        width=150,
    )
    # Serve the app
    app.servable()
```

**Comment by philippjfr** [comment]
Should use `ReactiveHTML` for this, e.g.:

```
class Text(pn.reactive.ReactiveHTML):
    
    color = param.Color(default='red')
    
    font_size = param.Integer(default=12)
    
    value = param.String(default='0.1')
    
    _child_config = {'value': 'literal'}
    
    _template = '<div id="test" style="font-size: ${font_size}px; color: ${color}">${value}</div>'

text = Text(font_size=20)
pn.Row(text.controls(), text)
```
