### ISSUE TITLE
widgets.DataFrame ability to get sorting and order changed by user

### ISSUE THREAD

**Issue by ItamarShDev** [holoviz/panel#1486]
#### Is your feature request related to a problem? Please describe.
Currently, i see no way of knowing that the user interacted with DataFrame without changing any value

#### Describe the solution you'd like
2 options:
1. `selected_dataframe` to represent the viewed column order and row sort
1. Add new params for that

#### Describe alternatives you've considered
Any grid/table library

**Comment by philippjfr** [comment]
I think I misunderstood your original request. We can absolutely expose the sortable/reorderable option in Bokeh but Bokeh does not actually allow accessing the reordered data. This would be a request for Bokeh.

**Comment by ItamarShDev** [comment]
Can we at least listen on sorting event?
I need to know the event happens basically

**Comment by philippjfr** [comment]
Afaik you'd have to file a feature request with bokeh for both features. Would be happy to be proved wrong though.

**Comment by philippjfr** [comment]
The new [Tabulator](https://panel.holoviz.org/reference/widgets/Tabulator.html) widget will make the current sorting order available to the user starting in the 0.12 release.
