### ISSUE TITLE
Ability to style DataFrame cells

### ISSUE THREAD

**Issue by ItamarShDev** [holoviz/panel#1487]
#### Is your feature request related to a problem? Please describe.
Currently, i see no way of styling cells without JavaScript

#### Describe the solution you'd like
a new  cell_formatter functional parameter

#### Describe alternatives you've considered
Any grid/table library

**Comment by philippjfr** [comment]
The `Tabulator ` styling API makes it possible to style a Table: https://panel.holoviz.org/reference/widgets/Tabulator.html#styling
