### ISSUE TITLE
Inconsistencies in param.Integer with slow callbacks 

### ISSUE THREAD

**Issue by ptocca** [holoviz/panel#1490]
#### Environment
Ubuntu 18.04, Firefox 78.0.2
bokeh                     2.1.1 
jupyter-bokeh             2.0.3
notebook                  6.0.3
panel                     0.9.7
param                     1.9.3

#### Description of expected behavior and the observed behavior
If the callback associated with a param.Integer is slow, the UI and the model get out-of-sync, when dragging. 
More precisely, the IntSlider shows a value, but the param.Integer associated with it has another value.    
I attach a screencast showing the issue. I drag the handle and, after the UI settles, the value of the slider (882) is not the value of the parameter (586).

![Peek 2020-07-21 15-11](https://user-images.githubusercontent.com/12876344/88065646-c6c21e00-cb64-11ea-8066-c34882a622b4.gif)

This should be pretty basic functionality. As it is, it's unusable.    
Am I missing something? Is there a way to have updates only on mouse-up (if possible, by default)?

Thanks

**Comment by MarcSkovMadsen** [comment]
@philippjfr . You added this to the already release 0.9.7 milestone?

**Comment by philippjfr** [comment]
Thanks.
