### ISSUE TITLE
serving static dirs --- missing argument

### ISSUE THREAD

**Issue by nghenzi** [holoviz/panel#1491]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

# Name                    Version                   Build  Channel
panel                     0.10.0a16.post5+gc028511           dev_0    <develop>

#### Description of expected behavior and the observed behavior

I am serving some javascript static files with the static-dirs option in a panel dev environment.   It appears an error of missing argument.

![image](https://user-images.githubusercontent.com/46707985/88198341-fb43e180-cc19-11ea-86fa-6d4e14bada0e.png)

After that I was looking for the error and I believe that the errors is in the line 104 of panel/command/serve.py. 

There it should be "patterns += get_static_routes(static_dirs) " instead of "patterns += get_static_routes()". 

After I corrected that, I had to change the directory path of the line 103 in the same file. I hardcoded it to the location of the dist folder.  

I think the error appears in this pull request 

#1472 Fix issues with requirejs and templates

**Comment by philippjfr** [comment]
Thanks, clearly a bug. A PR would be very welcome.

**Comment by nghenzi** [comment]
done. I think it's ok, but I don't have much experience on this.

**Comment by philippjfr** [comment]
Thanks again!
