### ISSUE TITLE
Button click event does not respond

### ISSUE THREAD

**Issue by aboutyy** [holoviz/panel#1527]
Hi, there! 
The button click event does not work in jupyter lab. I tried the official button.ipynb and the action_button.ipynb, the code went well, but the button click event just does not respond.

#### ALL software version info
panel 0.9.7
jupyter 1.0.0
jupyterlab 2.2.2
hovovies 1.13.3
bokeh 2.1.1
jupyter-client 6.1.6
jupyter-console 6.1.0
jupyter-contrib-nbextensions 0.5.1
jupyter-nbextensions-configurator 0.4.1
pyvista 0.25.3
pyviz-comms 0.7.4
#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

import panel as pn
pn.extension()
button = pn.widgets.Button(name='Click me', button_type='primary')
button
button.clicks
#### Stack traceback and/or browser JavaScript console output

#### Screenshots or screencasts of the bug in action

**Comment by philippjfr** [comment]
Have you installed the JupyterLab extension?

```
jupyter labextension install @pyviz/jupyterlab_pyviz
```

**Comment by aboutyy** [comment]
> Have you installed the JupyterLab extension?
> 
> ```
> jupyter labextension install @pyviz/jupyterlab_pyviz
> ```

yes, i installed the extension. The lib is installed in ubuntu 16.04 OS. I guess it may conflicts with other libs, because it works fine in a new computer with windows os.

**Comment by aboutyy** [comment]
Plus: the select Drop down box event is also not responding. Do i have to offer other info?

**Comment by philippjfr** [comment]
Sorry for the late response, any errors in the Javascript console would be helpful.

**Comment by MarcSkovMadsen** [comment]
Hi @aboutyy 

Just the simple question: Is it `button.click  you expect to see changes to? In a notebook?

Because from that you will only get a static, fixed value.

You need to use `button.param.clicks` in a notebook?

Could you maybe provide some screenshots or even better a `.gif` video of what you are trying to do?

**Comment by aboutyy** [comment]
> Sorry for the late response, any errors in the Javascript console would be helpful.



> Hi @aboutyy
> 
> Just the simple question: Is it `button.click you expect to see changes to? In a notebook?
> 
> Because from that you will only get a static, fixed value.
> 
> You need to use `button.param.clicks` in a notebook?
> 
> Could you maybe provide some screenshots or even better a `.gif` video of what you are trying to do?

Thank you for your reply.

I just tried the official example in pannel-examples/reference/widgets/button.ipnb. The button click just did not response to the click event. 

In the gif, i clicked the button several times, but the click event always showed clicked 0
![button click no response](https://user-images.githubusercontent.com/7921194/91001272-d6b69d00-e5fd-11ea-9541-8db1d4510248.gif)

.

**Comment by MarcSkovMadsen** [comment]
That should definately work.

**Comment by aboutyy** [comment]
> That should definately work.

It worked in a new computer, I don't know if it confilicts with other lib or version.

**Comment by MarcSkovMadsen** [comment]
Notebooks are unstable i believe. Yesterday i spent a lot of time on and issue. When i copy pasted the code to a new cell it worked.

**Comment by fhinojosa** [comment]
I'm having the same issue. I'm working through the tutorial, so I have the same code as aboutyy. The widgets appear, and seem to be working. I can select a date with the date picker, etc... But I can't seem to get the button event code to work?

**Comment by philippjfr** [comment]
Oh right, my assumption was that we were basically talking about all widgets not working and button was just the first thing you tried but it sounds like at least in your case it's explicitly the button @fhinojosa?

**Comment by fhinojosa** [comment]
Argh. I may have inadvertently lied. It looks like the javascript and html parts of the widget are working. So I can select something with a datePicker, and the datePicker field changes. But, as I just noticed, the date_picker.value in the next cell is not changing?

**Comment by fhinojosa** [comment]
I created a fresh environment and was able to get the button to work. So my bad. Thanks for the help.

**Comment by aboutyy** [comment]
> I created a fresh environment and was able to get the button to work. So my bad. Thanks for the help.

Could you please list the old environment libs, may be we can find something in common to pick out the confilict lib?

**Comment by aboutyy** [comment]
> Notebooks are unstable i believe. Yesterday i spent a lot of time on an issue. When i copy pasted the code to a new cell it worked.

I tried in a new note book and pasted the example code, still not working. Strange

**Comment by fhinojosa** [comment]
I'm afraid, while I was able to get a simple, separate, working example working. I'm still not able to get the downloaded examples to work. I'm not getting any errors, and, the components appear, and update within themselves, but it doesn't appear that the widgets are able to update anything outside of themselves. I hope that makes sense. I'm really excited about the library, and am anxious to study the code examples to learn how to use it.

**Comment by fhinojosa** [comment]
I was able to get the examples working using conda and exactly following the instructions located at https://panel.holoviz.org.

**Comment by philippjfr** [comment]
Going to close since this wasn't consistently reproducible, please reopen if you can reproduce still.
