### ISSUE TITLE
When trying to use tabulator.info javascript in Notebook I get Javascript error adding output!

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1529]
#### My Pain

I have wrapped the tabulator.info grid into a new Panel widget. It works great on the server. Now I'm trying to get it working in the Notebook.

It does not work. The tabulator grid is not shown. My Hypothesis is that the tabulator javascript module does not load. It's defined like this

![image](https://user-images.githubusercontent.com/42288570/90327641-08908980-df96-11ea-93d3-f80442b20638.png)

If I try to load it directly in the notebook via

```python
import panel as pn
pn.config.js_files["tabulator"]="https://unpkg.com/tabulator-tables@4.7.2/dist/js/tabulator.min.js"
pn.extension()
```

I get a 'Javascript error adding output!' and `Error: Mismatched anonymous define() module: ..' error.

![image](https://user-images.githubusercontent.com/42288570/90327673-7c329680-df96-11ea-99b4-33787e4281d7.png)

I would like 1) To know how to solve this 2) Have a better error message describing the cause and solution.

**Comment by philippjfr** [comment]
So I've had to develop some custom workaround for custom JS to load correctly in the classic notebook where requirejs is used to load modules. In addition to the `__javascript__`` variable I also define a requirejs based configuration on Panel model classes, e.g. take a look at the Plotly configuration:

```python
    __javascript__ = [
        'https://code.jquery.com/jquery-3.4.1.min.js',
        'https://cdn.plot.ly/plotly-latest.min.js'
    ]

    __js_skip__ = {'Plotly': __javascript__[1:]}

    __js_require__ = {
        'paths': {
            'plotly': 'https://cdn.plot.ly/plotly-latest.min'
        },
        'exports': {'plotly': 'Plotly'}
    }
```

Here the ``__js_require__`` configuration gets used in the classic notebook instead to avoid the errors you are seeing.

**Comment by MarcSkovMadsen** [comment]
I tried this one without luck

![image](https://user-images.githubusercontent.com/42288570/90342882-00733100-e00c-11ea-8758-80c48a2fe5b6.png)

![image](https://user-images.githubusercontent.com/42288570/90342886-0bc65c80-e00c-11ea-8687-83f8601c973b.png)

Will try to understand what it does and if I need to do something else.

**Comment by philippjfr** [comment]
Try to strip off the .js extension from the `js_require` definition.

**Comment by MarcSkovMadsen** [comment]
It did not change anything. But I found something else that works using requirejs directly in the `.ts` code. I will itereate a bit on that and get back with the solution.

**Comment by MarcSkovMadsen** [comment]
I've tried this without luck

![image](https://user-images.githubusercontent.com/42288570/90355726-8499d880-e04d-11ea-80c4-75664eb2ada8.png)

**Comment by MarcSkovMadsen** [comment]
I've tried this variant without luck

![image](https://user-images.githubusercontent.com/42288570/90355849-e0fcf800-e04d-11ea-8199-0ccf841a4df7.png)

**Comment by MarcSkovMadsen** [comment]
As the requirejs work in notebook I will just stick to that for now.

There is also a little bit of information on the Tabulator package regarding loading the package and using `require`. See http://tabulator.info/docs/4.7/install

![image](https://user-images.githubusercontent.com/42288570/90355948-33d6af80-e04e-11ea-9b77-5cdfeb43e8e6.png)

**Comment by MarcSkovMadsen** [comment]
This also works in a code cell

```html
%%html
<script>
requirejs.config(
    {paths: { 'tabulator': ['https://unpkg.com/tabulator-tables@4.7.2/dist/js/tabulator.min']},}
);
if(!window.Tabulator) {
    require(['tabulator'],function(tabulator) {window.Tabulator=tabulator;});
}
</script>
```

**Comment by MarcSkovMadsen** [comment]
FYI. @philippjfr 

I will close this one for two reasons 1) I've find a workaround in the notebook 2) There is a PR on adding Tabulator to Panel. So it will be solved there.
