### ISSUE TITLE
Nested ipywidget containers not working?

### ISSUE THREAD

**Issue by ceball** [holoviz/panel#1549]
If I have e.g. an `ipywidgets.HBox` in an `ipywidgets.VBox`, I get no visible output in panel.

Maybe this is just a usage error, in which case I'll be happy to add something to the docs :)

#### ALL software version info

```
bokeh                     2.2.0                      py_0    bokeh/label/dev
ipywidgets                7.5.1                      py_0    conda-forge
ipywidgets_bokeh          1.0.2                      py_0    bokeh/label/dev
jupyterlab                2.2.6                      py_0    conda-forge
panel                     0.10.0a23                  py_0    pyviz/label/dev
```

Chromium 83.0.4103.116

#### Description of expected behavior and the observed behavior

Expected something like the "two rows" layout below (ipywidgets in jupyter lab):

![Screenshot from 2020-08-25 21-54-45](https://user-images.githubusercontent.com/1929/91227449-6e131180-e71e-11ea-8591-a97ea4446b31.png)

But got "nothing" (ipywidgets in panel):

![Screenshot from 2020-08-25 21-57-57](https://user-images.githubusercontent.com/1929/91227471-7408f280-e71e-11ea-99e0-a3d6e21296a2.png)

#### Complete, minimal, self-contained example code that reproduces the issue

test.py:
```
import panel as pn
pn.extension()

import ipywidgets as ipw

hello1 = ipw.Label("hello1")
world1 = ipw.Label("world1")

hello2 = ipw.Label("hello2")
world2 = ipw.Label("world2")

layout = ipw.VBox([
    ipw.HBox([hello1,world1]),
    ipw.HBox([hello2,world2])
])

#layout = ipw.HBox([hello1,world1])

pn.panel(layout).servable()
```

Run as `python -m panel serve test.py`

If I just have one `HBox` (i.e. uncommenting the second `layout` above), I get the result I expected for that case:

![Screenshot from 2020-08-25 21-56-46](https://user-images.githubusercontent.com/1929/91227465-723f2f00-e71e-11ea-84e6-3a758ad79ffe.png)

**Comment by philippjfr** [comment]
I can definitely reproduce, the extra strange part is if I launch it from a notebook with `.show()` it does work.

**Comment by philippjfr** [comment]
I've narrowed it down, it seems like bokeh can't correctly measure the size of the nested boxes and so gives them 0 width and height. Seems like something that will have to be fixed in `ipywidgets_bokeh`.

**Comment by philippjfr** [comment]
Works okay when setting sizing mode or width/height. Should also be fixed by bokeh layout changes so I'll close.
