### ISSUE TITLE
Panel fails to compare versions on the holoviews 

### ISSUE THREAD

**Issue by tonyfast** [holoviz/panel#1554]
#### Description of expected behavior and the observed behavior

On https://github.com/holoviz/holoviews/pull/4517, appveyor is unable to compare versions in the holoviews tests using distutils comparison. 

#### Complete, minimal, self-contained example code that reproduces the issue

https://ci.appveyor.com/project/holoviz-developers/holoviews/builds/34892678#L2911

**Comment by MarcSkovMadsen** [comment]
@philippjfr should this not be moved to the HoloViews repo? Can you do it?

**Comment by philippjfr** [comment]
Thanks @tonyfast and @MarcSkovMadsen. This was resolved I believe, closing.
