### ISSUE TITLE
FileInput widget is limited by the size of the tornado `max_buffer_size1

### ISSUE THREAD

**Issue by kcpevey** [holoviz/panel#1559]
The tornado client has a [default max buffer size of 100MB](https://github.com/tornadoweb/tornado/blob/c3c263de0a7b627af4ea3b729a32acd2ddd99d38/tornado/simple_httpclient.py#L120) . This limits the files that are loaded into the FileInput widget. 

The buffer size can be increased by setting this size on the bokeh server: 
from bokeh.server.server import Server
`server = Server( ... , websocket_max_message_size=1000000000,)`

This should be documented in the FileInput docs page.

**Comment by okz** [comment]
for jupyter notebooks apps, the server is started with jupyter. 

For a 1GB support, ``jupyter_notebook_config.py`` can be updated with: 

```
c.NotebookApp.tornado_settings = {"websocket_max_message_size": 1024 * 1024 * 1024}
```

**Comment by okz** [comment]
there is a workaround at:  https://github.com/holoviz/panel/issues/1559

**Comment by okz** [comment]
No :S .. To many windows..

Was supposed to add this to https://discourse.holoviz.org/t/panel-widgets-fileinput-maximum-file-size/916/3

Thanks for letting me know

**Comment by philippjfr** [comment]
@okz think you could make a PR mentioning this in the FileInput docs?

**Comment by okz** [comment]
Sure..will give it a go sometime next week.

**Comment by Coderambling** [comment]
Update: in the imminent 1.5 release, Panel offers the FileDropper widget, which supports large files.

https://holoviz-dev.github.io/panel/reference/widgets/FileDropper.html
