### ISSUE TITLE
FileDownload fails with panel serve in release 0.9.7: downloads same data over and over

### ISSUE THREAD

**Issue by matsvandecavey** [holoviz/panel#1560]
#### Description of expected behavior and the observed behavior
When serving a notebook, the FileDownload widget repeatedly saves that same data it saved the first time the button was pushed.
In earlier version 0.9.5 this was an issue in the notebook as well, and after updating to 0.9.7 I was relieved to see it solved.

Try serving the notebook in https://panel.holoviz.org/gallery/param/download_upload_csv.html 1 [fileDownload-tutorial.ipynb (8.8 KB) ] and generate +1 datasets. It will download the same data over and over. See figures: generated data with 4 samples, but saves old data from first download.

![image](https://user-images.githubusercontent.com/2987662/91993287-79c19200-ed35-11ea-9be9-b9dfa64e027b.png)

![image](https://user-images.githubusercontent.com/2987662/91993212-6282a480-ed35-11ea-9fb2-eb5809f2e295.png)

**Comment by philippjfr** [comment]
Cannot reproduce with latest Panel, please reopen if the issue persists.
