### ISSUE TITLE
Create an "Show the Community!" or "Share with the community!" section on Discourse

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1563]
In order for the community to share knowledge and learn what can be done and is done with HoloViz including Panel it would be nice if there was a "Show the community!" section on Discourse that nudged users to share what they do.

We could all learn from that I believe.

Bokeh and Streamlit both have it. And I believe it's a valuable resource.

**Comment by philippjfr** [comment]
Added a category here: https://discourse.holoviz.org/c/showcase/. Suggestions for improving the section welcome.
