### ISSUE TITLE
Incorrect documentation in reference guide of TextInput

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1564]
The value is **not** nescessarily a *Parsed datetime value* :-)

![image](https://user-images.githubusercontent.com/42288570/92319825-9e12bc80-f01c-11ea-8d4f-11ebc0251fb9.png)

https://panel.holoviz.org/reference/widgets/TextInput.html#widgets-gallery-textinput

**Comment by halilbay** [comment]
I'd like work on this issue, if it is okay for you?

**Comment by philippjfr** [comment]
@halilbay That would be appreciated.
