### ISSUE TITLE
A new widget with the same class name as an existing widget is not possible

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1591]
I am trying to create new widgets for Panel based on Fast, Material, Wired etc.

I've asked if they should have "new" names like FastButton or just be called "Button". The feedback was to call them "Button".

![image](https://user-images.githubusercontent.com/42288570/93555563-8faa9600-f976-11ea-89c0-51fef3d0fe7c.png)

But the below example shows it will not work for some unknown reason.

## Use Existing Class Name does not work!

```python
from panel.widgets import Button as _PnButton
import param

class Button(_PnButton):
    _name = param.String()

    _rename = {**_PnButton._rename, "name": None, "_name": "label"}

    def __init__(self, **params):
        super().__init__(**params)

        self._update_name()

    @param.depends("name")
    def _update_name(self, *_):
        print("update name")
        self._name = "allo " + self.name

Button(name="world").servable()
```

![image](https://user-images.githubusercontent.com/42288570/93555613-c2ed2500-f976-11ea-8267-27fe7756ebd0.png)

## Using new class name works

But if I change the class name it works!

```python
from panel.widgets import Button as _PnButton
import param

class NewButton(_PnButton):
    _name = param.String()

    _rename = {**_PnButton._rename, "name": None, "_name": "label"}

    def __init__(self, **params):
        super().__init__(**params)

        self._update_name()

    @param.depends("name")
    def _update_name(self, *_):
        print("update name")
        self._name = "allo " + self.name

NewButton(name="world").servable()
```

![image](https://user-images.githubusercontent.com/42288570/93555697-08115700-f977-11ea-85a7-35a1c2798957.png)

##### Additional Context

To me this does not make sense and I don't understand how it can happen. Is it Python, Panel or Bokeh that is causing this? My guess is it is actually a Python inheritance thing. I've tried to google without finding anything useful.

FYI. @jbednar

**Comment by jbednar** [comment]
That's not good!  @philippjfr, I'm the one who suggested that if Marc was setting up a whole set of alternative implementations for objects we already have, it's probably easiest to manage if they have the same names but are in a different module, so that a user can easily switch between `from panel.widgets import Button` to `from fast import Button`. Is there a registry based on the unqualified class name somewhere?

**Comment by philippjfr** [comment]
I'm really not understanding which part here doesn't work. Why are you overriding `name` with `_name`? You're trying to add a prefix to parameter name? This works just fine:

```python
from panel.widgets import Button as _PnButton

import param

class Button(_PnButton):

    _rename = {**_PnButton._rename, "name": "label"}

Button(name="world").servable()
```

**Comment by philippjfr** [comment]
@MarcSkovMadsen gentle ping as I'd like to resolve this before 0.10.0.

**Comment by MarcSkovMadsen** [comment]
Hi @philippjfr 

As you write I had a use case where I needed to add a prefix to the name value when shown on the Button.

I cannot find that use case any more as my code has been refactored.

You are welcome to close this one.

But at least even though you think the way I'm using the api is hard to understand it should be technically possible to do. But I guess its an edge case and there are more important things to fix. 🙂
