### ISSUE TITLE
Enable uploading mp4 videos to Discourse

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1593]
Video is a powerful media for communication. I use it often. 

But on the HoloViz Discourse Forum I can only upload .gif videos which requires an extra and time consuming conversion step. Furthermore the quality gets reduced and the user cannot stop and replay parts of the video.

## Solution

Enable support for uploading .mp4 videos.

## Additional Context

They've added that support to the Bokeh Discourse. See https://discourse.bokeh.org/t/allowed-media/4810

**Comment by philippjfr** [comment]
Done.
