### ISSUE TITLE
Improve Index Page

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1601]
The current Index page looks like

![panel_index](https://user-images.githubusercontent.com/42288570/94188411-a0449a00-fea9-11ea-9290-e2ab9d8109c0.jpg)

It's is nice to have an index page. But is as bare bones as it can be and does not communicate very well that some awesome analytics apps will reveal themselves when you click the links. Furthermore it is not documented if and how the layout of the template can be adjusted for example to the organisations branding.

Some suggestions for basic improvements could be

- Document how to fine tune the existing template.
    - Replace image
    - Change fonts and colors
- Document how to create a custom template.
    - Provide one or more examples.

BI Tools like Tableau provides more information including meta data and information in the form of a Gallery

![image](https://cdnl.tblsft.com/sites/default/files/pages/server_dashboard_overview_3x3_0.png)

I can see that for my personal and work use cases I need something like a gallery which includes links to the application, an image of it, link to documentation, instructional videos, code etc. And it should be searchable. Maybe someday it would even be nice to mark an application as favorite or know which are the most popular dashboards or how often they are opened.

![image](https://user-images.githubusercontent.com/42288570/94188711-121ce380-feaa-11ea-80e4-d64d05e74e3c.png)

You can try it here https://awesome-panel.org/gallery

In order to define this I've defined some models like Application and Author.

I see this as a move towards defining a model of what a Site, Application/ Page etc. is. I have something here https://github.com/MarcSkovMadsen/awesome-panel-extensions/tree/master/awesome_panel_extensions/models/resource.

One solution could be to create a gallery very similar to the Gallery I've created but maybe using Bootstrap or https://shoelace.style/ which is more in line with the style of Bokeh/ Panel.

Over time this could be extended to a Gallery Template for each of the frameworks that Panel provides Template for (Vanilla, Material, ...).

**Comment by Jhsmit** [comment]
+1 for documenting how to change that, for sure in the future for my app I want to customize the Index page. 
For my use case probaly it will be more text heavy rather than a gallery, with links/logos for funding agencies, documentation, publications etc

**Comment by MarcSkovMadsen** [comment]
Right now you have to create your own using https://panel.holoviz.org/user_guide/Templates.html. 

That is powerful. But takes time.

**Comment by philippjfr** [comment]
Your new index page is already a huge improvement so I'll close.
