### ISSUE TITLE
Install of development version errors (panel.js version does not match panel version)

### ISSUE THREAD

**Issue by ltalirz** [holoviz/panel#1604]
### Is your feature request related to a problem? Please describe.
Installing a development version of panel, e.g. using

```
pip install https://github.com/holoviz/panel/archive/b151ae6ebeafbc9ab9cc6e5e4974cc9899766a4b.zip
```

fails with:
```
    File "setup.py", line 233, in <module>
      % (js_version, version))
  ValueError: panel.js version (0.10.0-a27) does not match panel version (None). Cannot build release.
```

In order to be able to add panel development versions as dependencies in a project I've commented out this guard in the setup.py
https://github.com/holoviz/panel/blob/b151ae6ebeafbc9ab9cc6e5e4974cc9899766a4b/setup.py#L230-L233
and I'm wondering whether it is really needed?

#### Describe the solution you'd like
One could either skip the guard if the panel version is `None` or one could try to make sure that the panel development versions actually have version numbers just like panel.js seems to have.

**Comment by philippjfr** [comment]
I'm happy to skip if panel version is `None` but really this shouldn't happen. Basically this guard is there to avoid ever building a package without a valid panel dev version also being built and uploaded to NPM, so I'm -1 on disabling it entirely.

**Comment by philippjfr** [comment]
Oh just read this part:

>pip install https://github.com/holoviz/panel/archive/b151ae6ebeafbc9ab9cc6e5e4974cc9899766a4b.zip

This is not a supported way of working with Panel. Either install dev versions from test.pypi.org or directly from the your local checkout. I'll skip the check on None anyway though.

**Comment by ltalirz** [comment]
Thanks @philippjfr !

> This is not a supported way of working with Panel. Either install dev versions from test.pypi.org or directly from the your local checkout.

Just to understand: is there a particular reason not to do this, e.g. when one needs a feature that is not yet released on test.pypi.org?
For me it seemed to work just fine after commenting out the guard.

**Comment by philippjfr** [comment]
>Just to understand: is there a particular reason not to do this, e.g. when one needs a feature that is not yet released on test.pypi.org?

If it's working for you then it's fine I suppose, the reason why this is technically supported is precisely because the versioning does not work in this scenario.
