### ISSUE TITLE
Enable using different Templates with Panel using specific, non-global resources - LINK TO CODE INCLUDED.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1606]
If you use the global configuration `pn.config` for your templates you will include the same
css and js files in all templates. 

This is **problematic** if you want different templates,
like for example a light template, a dark template, a bootstrap template, a material
template, a template with Plotly Plots, and template without Plotly plots etc.

I experience this at awesome-panel.org and professionally. I can see that the repository https://github.com/paulopes/panel-components has created a lot of code to handle this problem.

#### Solution

Add functionality to only use specific extensions, raw_css, css_files and js_files in a Template.

Please note that it should also be able to use Bokeh/ Panel extensions like `awesome-panel-extensions` with this functionality.

#### Additional Context

I've created code to solve this in the context of `panel-components`. I believe it's worth reviewing if this code could be included in Panel. I would be willing to do a PR if I get the proper support to get it included. The PR comes with a lot of tests.

See https://github.com/paulopes/panel-components/pull/10 including the files changed https://github.com/paulopes/panel-components/pull/10/files

![image](https://user-images.githubusercontent.com/42288570/94994739-f1cfe180-0599-11eb-978b-ecb4ba3b8aa4.png)

@philippjfr . I would like to know if this is something for Panel, Bokeh or not at all. Thanks.

**Comment by MarcSkovMadsen** [comment]
The TemporaryResources context manager is work in progress. I have not used it in practice in the `components.py` file of the `panel-components` project. But I plan to.

The one thing I don't know is if there could be problems with `thread safety`.

**Comment by MarcSkovMadsen** [comment]
FYI. @bryevdv . Maybe this is actually something that should be solved in Bokeh or this code be added to Bokeh?

**Comment by Jhsmit** [comment]
Does this allow ause case then users change Themes (ie switch between dark/light) from within the GUI?

**Comment by MarcSkovMadsen** [comment]
It depends on how you would like to do it.

#### 1. Some .js Frameworks just supports this.

Some frameworks provide this out of the box. You are using the same .css and .js for all themes. An example is Fast where you can checkout light/ dark theme changes here https://awesome-panel.org/gallery. Another is Shoelace.style.

![image](https://user-images.githubusercontent.com/42288570/95098077-853a1b80-072e-11eb-8eb1-44fd32b5162d.png)

#### 2. Using query parameters and a page refresh

In Panel you can use the url or query parameters before you load the page to determine the template. For example yourdomain.com/?theme=dark. You can use that to choose a dark .css style. Or a light style theme. 

This is currently a hassle to do in Panel because if you use `pn.config.css_files` to include stylesheets in your template then they will be included in every page no matter the url or query parameters. 

The TemporaryResources context manager can be used to solve this problem. 

The TemporaryResources context manager solves more and all problems (I believe) as it does not use any of the .js or .css coming from the global `pn.extension` or `pn.config` values.

Please note that switching the theme requires either a refresh or that you replace the css. For example if you have raw_css in a `pn.pane.HTML`. Then you can do it. 

The one thing I have not figured out yet is how to replace the theme of your Bokeh, Holoviews, Plotly, Altair, DeckGl and ECharts plots without a refresh.

**Comment by philippjfr** [comment]
This is now supported, `pn.config` is no longer global and each template also has its own `.config`.
