### ISSUE TITLE
Describe why and how to serve static assets from a src_folder

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1607]
I can see that there is a lot of functionality to copy and serve assets from a source folder (defaults to www).

I would like to know why and how to best use this.

#### Solution

Add description with examples to README.

**Comment by philippjfr** [comment]
Honestly not quite sure what this is referring to.

**Comment by MarcSkovMadsen** [comment]
Ahh. Wrong repository. Should be in paulopes repository.
