### ISSUE TITLE
Plot doesn't respond to widget changes in Param.ipynb

### ISSUE THREAD

**Issue by jbednar** [holoviz/panel#1618]
For:

param=1.9.3 or 1.10.0a5.post9+gf68fffc (master)
panel=0.9.7 or 0.10.0a28 

The last example in user_guide/Param.ipynb shows a plot that updates when the Radius slider is dragged, but fails to update when the N slider is dragged (notice N=8 but a triangle is shown):

![image](https://user-images.githubusercontent.com/1695496/95616756-f24ff880-0a2f-11eb-96bb-ff868f7a204c.png)

There are dependencies declared on `n`, so this is either a bug in the notebook or in how Panel and Param are handling the dependencies.

**Comment by jbednar** [comment]
Also, the previous cell doesn't respond even to radius being dragged, after the whole notebook is run using Run All, which I suspect is a notebook-level interaction rather than a bug in Panel or Param. Still something worth cleaning up, though.

**Comment by nghenzi** [comment]
I think i am seeing the same thing in https://discourse.holoviz.org/t/difference-between-bokeh-and-panel-button/1287/2 
The callbacks are triggered in the python side, but not in js side when using the notebook. Then the plots are not updated. 
If you use .show or .servable it works

**Comment by jbednar** [comment]
Oh, that's helpful! I can confirm; yes, adding `.show()` does make it respond to `n`.
