### ISSUE TITLE
DataFrame pane height does not work

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1640]
I'm using panel 0.9.7.

I was trying to help a user on Discourse https://discourse.holoviz.org/t/save-filtered-df-example-how-to-return-the-size-of-the-df-also/1315/4. In the example I created I saw that setting the  `pn.pane.DataFrame` height does not work.

Below is a minimum reproducible example. I would have expected the height of the table to be 300px (The area with blue background).

![image](https://user-images.githubusercontent.com/42288570/96328410-f5a43f00-1042-11eb-93a2-6dfbe3c6b163.png)

```python
import panel as pn
import param

from bokeh.sampledata.autompg import autompg

pn.pane.DataFrame(autompg, height=300, width=700, background="blue").servable()
```

**Comment by kcpevey** [comment]
Just tested this on 0.9.7 and it does obey the `height` parameter inside of jupyter, but NOT when served via `.show()`

**Comment by philippjfr** [comment]
This is how the Bokeh layout engine works, if you need to fix the height you need to put the object into a container of the desired height, e.g. in this case:

```python
pn.Column(pn.pane.DataFrame(autompg, height=300, width=700, background="blue"), height=300, scroll=True).show()
```
