### ISSUE TITLE
ImportError: 'NumericInput' from 'bokeh.models.widgets.inputs'

### ISSUE THREAD

**Issue by epifanio** [holoviz/panel#1648]
### ALL software version info 

* OS Linux ubuntu 20.04
* panel git master
* bokeh git master
* system python 3.8

#### Description of expected behavior and the observed behavior
 I got an import error when attempting to use `panel` from git master

```
cannot import name 'NumericInput' from 'bokeh.models.widgets.inputs' 
```

I didn't get the error above when running a "pip-installed"  version of `panel` 

#### Complete, minimal, self-contained example code that reproduces the issue

From the panel src code [panel/widgets/input.py", line 16](https://github.com/holoviz/panel/blob/master/panel/widgets/input.py#L16): 

```python
from bokeh.models.widgets import (
    CheckboxGroup as _BkCheckboxGroup, ColorPicker as _BkColorPicker,
    DatePicker as _BkDatePicker, Div as _BkDiv, TextInput as _BkTextInput,
    PasswordInput as _BkPasswordInput, Spinner as _BkSpinner,
    FileInput as _BkFileInput, TextAreaInput as _BkTextAreaInput,
    NumericInput as _BkNumericInput)
```

#### Stack traceback and/or browser JavaScript console output
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-c97eef64abaa> in <module>
----> 1 from bokeh.models.widgets.inputs import NumericInput

ImportError: cannot import name 'NumericInput' from 'bokeh.models.widgets.inputs' (/usr/local/lib/python3.8/dist-packages/bokeh/models/widgets/inputs.py)
```

**Comment by xavArtley** [comment]
you have to update your version of bokeh>=2.2 to work with panel master

**Comment by xavArtley** [comment]
I reopen bokeh version is pinned to >=2.0.0 in setup.py

**Comment by epifanio** [comment]
Hi. thanks for the comment - I had bokeh master installed, but it was masked from the previously pip installed version - manually removing it (`pip uninstall bokeh`) fixed the import issue.

**Comment by MarcSkovMadsen** [comment]
Hi @epifanio . Can this one be closed then?

**Comment by epifanio** [comment]
Yes, closing it. Thanks!
