### ISSUE TITLE
Custom Template CSS is lower priority than other CSS

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1663]
I'm working on the MaterialTemplate and would like to set the drawer background color. But I'm not able to because the `material-components-web.min.css` is higher in priority.

![image](https://user-images.githubusercontent.com/42288570/96670601-049b3200-1360-11eb-87fb-b692aa132f2b.png)

#### Solution

Reorder the order of the .css files.

#### Additional Context

- I don't know how to do it.
- I will find a workaround for now.

**Comment by MarcSkovMadsen** [comment]
I figured out where it is

![image](https://user-images.githubusercontent.com/42288570/96670964-0285a300-1361-11eb-89a3-f702c67850cd.png)

Would it be ok to switch these across all templates and verify that they are still ok @philippjfr ? Then I will do it ASAP.

**Comment by philippjfr** [comment]
Reopen if this isn't totally done.
