### ISSUE TITLE
Panel show not working in chrome

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#1666]
![image](https://user-images.githubusercontent.com/18531147/96686273-9b76e700-137e-11eb-9904-6da02e2f8b31.png)

MRE:
```python
import panel as pn
pn.extension()

pn.widgets.FloatSlider().show()
```

tested on linux and windows 10

**Comment by xavArtley** [comment]
however if i make the example servable and I use panel cli it works correctly
![Uploading image.png…]()

**Comment by xavArtley** [comment]
I can reproduce this error from this commit https://github.com/holoviz/panel/commit/3824d7b782bf4e95bdac71670f6fa6c67373cc72

so I suppose it's linked to this one https://github.com/holoviz/panel/commit/3961571aecf125e642bdfd092e99189a18ba551d
but I can't build it

**Comment by philippjfr** [comment]
I think this was an issue with bokeh 2.2.2, could you try upgrading 2.2.3?

**Comment by xavArtley** [comment]
Already tested with bokeh 2.2.1, 2.2.2 and 2.2.3

**Comment by philippjfr** [comment]
Hmm odd, I had the same issue but wasn't able to reproduce after upgrading to 2.2.3. will have to try again.

**Comment by xavArtley** [comment]
I succed to make it works using bokeh origin/branch-2.3

**Comment by philippjfr** [comment]
Hmm, I actually pip installed it. Wonder if it's something about the conda packages.

**Comment by xavArtley** [comment]
I never use conda

**Comment by xavArtley** [comment]
using
pip install bokeh==2.3.0.dev2
it works

**Comment by philippjfr** [comment]
Really don't understand why this varies with Bokeh version, but I've now restored the old behavior in #1678 so that should fix it.
