### ISSUE TITLE
Out of date "latest dev tag" badge

### ISSUE THREAD

**Issue by ceball** [holoviz/panel#1667]
The latest dev tag shows up as a9 for me, when it's actually a36.

![Screenshot from 2020-10-21 10-54-55](https://user-images.githubusercontent.com/1929/96704410-f3681a80-138b-11eb-8427-a33a779deac1.png)

For me the badge is coming from:

https://camo.githubusercontent.com/f2daa1613407a52b882ab748da9230803888215e/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f7461672f686f6c6f76697a2f70616e656c2e7376673f6c6162656c3d74616726636f6c6f72423d313163636262

Is that happening for everyone? If so, anyone know what to do about it?

If I go make a new badge at shields.io, it is showing the right info (just in case it was something to do with version ordering)...

<img alt="GitHub tag (latest by date)" src="https://img.shields.io/github/v/tag/holoviz/panel?color=11ccbb">

**Comment by Hoxbro** [comment]
Just to add to out of date badges, the second build status has not been updated for two years.

![2020-10-21 14_16_41](https://user-images.githubusercontent.com/19758978/96718359-30daa100-13a8-11eb-8d6a-46b853ead2f7.png)
![2020-10-21 14_16_55](https://user-images.githubusercontent.com/19758978/96718365-320bce00-13a8-11eb-85f3-a605f93e5feb.png)

**Comment by ceball** [comment]
> The URL used for the badge is https://img.shields.io/github/tag/holoviz/panel.svg?label=tag&colorB=11ccbb but if i change it to https://img.shields.io/github/v/tag/holoviz/panel.svg?color=11ccbb I get the correct one.

Ah, interesting: https://img.shields.io/github/tag/holoviz/panel.svg?label=tag&colorB=11ccbb ends up as https://img.shields.io/github/v/tag/holoviz/panel.svg?colorB=11ccbb&label=tag&sort=semver - `sort=semver` is the problem.

Seems like just updating the badge should do it then. @Hoxbro do you want to make that PR? Otherwise I'm happy to do it.

> maybe it is related to lightweight and annotated tags in git?

I think they are all annotated tags

**Comment by Hoxbro** [comment]
You´re right. When i added /v/  before tag it works as expected.
 
https://img.shields.io/github/v/tag/holoviz/panel.svg?label=tag&colorB=11ccbb

**Comment by ceball** [comment]
Thanks @Hoxbro
