### ISSUE TITLE
Issues in DEV Documentation as of 20201021 17:07

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1673]
I just skimmed trough the documentation before the launch. I see some issues

#### Issue 1

Progess is both under Indicators and Widgets.

![image](https://user-images.githubusercontent.com/42288570/96739442-144a6300-13c0-11eb-90ec-63524309dd2d.png)

#### Issue 2

Wrong image for Boolean Status

![image](https://user-images.githubusercontent.com/42288570/96739517-27f5c980-13c0-11eb-9654-77fd6e6c8de4.png)

#### Issue 3

The expansion button is outside the card at https://pyviz-dev.github.io/panel/reference/layouts/Card.html#layouts-gallery-card

![image](https://user-images.githubusercontent.com/42288570/96739750-6ab7a180-13c0-11eb-8b27-afa3106a468c.png)

In more places than the image shows.

#### Issue 4

The bokeh example should be working in the notebook because its using jslinks. But it is not.

https://pyviz-dev.github.io/panel/reference/panes/Bokeh.html#panes-gallery-bokeh

![bokeh_not_working](https://user-images.githubusercontent.com/42288570/96740487-2c6eb200-13c1-11eb-9674-1bdb4898bc34.gif)

**Comment by MarcSkovMadsen** [comment]
# Issue 5

Nothing shown in the bottom of the VTK guide https://pyviz-dev.github.io/panel/reference/panes/VTK.html#panes-gallery-vtk

![image](https://user-images.githubusercontent.com/42288570/96743588-7311db80-13c4-11eb-98f1-90f69f7b649f.png)

**Comment by MarcSkovMadsen** [comment]
### Issue 6

The JS linking in the plotly-link example is not working https://pyviz-dev.github.io/panel/gallery/links/plotly_link.html#links-gallery-plotly-link.

![plotly_link](https://user-images.githubusercontent.com/42288570/96744535-72c61000-13c5-11eb-9073-6dc6b0e02516.gif)

**Comment by MarcSkovMadsen** [comment]
### Issue 7

The vega-heatmap-link examply is not showing/ working.

https://pyviz-dev.github.io/panel/gallery/links/vega_heatmap_link.html#links-gallery-vega-heatmap-link

And there are warnings in the console.

![image](https://user-images.githubusercontent.com/42288570/96744942-d8b29780-13c5-11eb-9731-95dad7ddd8a3.png)

**Comment by Hoxbro** [comment]
# Issue 8
Sample video in gallery does not work anymore. 

https://panel.holoviz.org/reference/panes/Video.html#panes-gallery-video

![image](https://user-images.githubusercontent.com/19758978/96766623-a90e8a00-13db-11eb-8874-3f8e3921bbb6.png)

**Comment by philippjfr** [comment]
Still seeing some weirdness with the VTK one, everything else seems to have been addressed. @xavArtley Any idea what's going on there?

**Comment by xavArtley** [comment]
It works in a notebook and I can't build the doc so I can't reproduce the issue.
It's not clear to me whats the problem
