### ISSUE TITLE
Can not assign element to column 12 en react template

### ISSUE THREAD

**Issue by nghenzi** [holoviz/panel#1676]
Running the next code in the react template 

```
responsive.main[0:2, 0:4] = pn.Card(hv.DynamicMap(sine), title='Sine')
responsive.main[0:2, 4:8] = pn.Card(hv.DynamicMap(cosine), title='Cosine')
responsive.main[0:2, 8:12] = pn.Card(hv.DynamicMap(tan), title='Tan')
```

In the console appears this error 

![image](https://user-images.githubusercontent.com/46707985/96756784-f1fa1a80-13aa-11eb-8b5f-78b968dde1d6.png)

If I change the last line replacing 12 by 11 it works, but it does not fill the width of the screen 

responsive.main[0:2, 8:11] = pn.Card(hv.DynamicMap(tan), title='Tan')

**Comment by philippjfr** [comment]
Fixed in #1670
