### ISSUE TITLE
Template Test Report

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1680]
I was asked in https://github.com/holoviz/panel/pull/1679 to test the Template by @philippjfr .

I've 

- run `git fetch`
- created a new branch from the holoviz master branch. 
- run `git pull holoviz master`
- run `python -c "from panel import compiler;compiler.bundle_resources()"`
- I've tested on Windows using Chrome.

#### Vanilla

- The sidebar height and main height needs to be adjusted.

![image](https://user-images.githubusercontent.com/42288570/96866943-56c97980-146c-11eb-8fce-c1ce326e8532.png)

#### Vanilla Dark

- HTML link in sidebar not readable
- Large gap between Sidebar Markdown and Sidebar Item
- Sidebar could use a bit more padding on the right

![image](https://user-images.githubusercontent.com/42288570/96868859-e839eb00-146e-11eb-8c91-56d1964836f1.png)

#### Material Dark

- HTML link in sidebar not readable
- Overlap between Sidebar Markdown and Sidebar Item
- Sidebar could use a bit more padding on the right
- Main could use a bit of padding at the bottom.

![image](https://user-images.githubusercontent.com/42288570/96868964-16b7c600-146f-11eb-91c0-2d18e025a2ef.png)

#### Material

- Markdown overlaps Sidebar Item
- The main could use a little bit of padding at the bottom.
- Sidebar background-color shold be Gray 50 `#FAFAFA`.

![image](https://user-images.githubusercontent.com/42288570/96869127-5aaacb00-146f-11eb-8277-aa52c4957842.png)

#### Golden

- Left and right padding is missing on the Sidebar. I had used a padding of `10px`. See https://github.com/holoviz/panel/pull/1659/files
- Sidebar Items overlap.
- Main could use padding at bottom

![image](https://user-images.githubusercontent.com/42288570/96869407-b5442700-146f-11eb-84a7-7aaf0c46e806.png)

#### Golden Dark

- Left and right padding is missing on the Sidebar. I had used a padding of `10px`. See https://github.com/holoviz/panel/pull/1659/files
- Sidebar Items overlap.
- Sidebar link is not readable.
- Main could use a bit of padding at bottom.

![image](https://user-images.githubusercontent.com/42288570/96869497-d3aa2280-146f-11eb-9867-ae30eb9eb20f.png)

#### Bootstrap Dark

- Title is blue and small
- Link is purple and unreadable.

![image](https://user-images.githubusercontent.com/42288570/97024986-c6686300-1557-11eb-8ac4-ad28e7e53530.png)

#### Bootstrap

- Title is blue and small
- App has vertical scrollbars
- Main needs padding on right
- Unmotivated space between text items and first `Sidebar item`.
- LInks in header are blue and underlined when hovering.

![image](https://user-images.githubusercontent.com/42288570/97025320-34ad2580-1558-11eb-891f-f277b395a04b.png)

**Comment by MarcSkovMadsen** [comment]
Wait @philippjfr . I can see that I need to build the resources first via `python -c "from panel import compiler;compiler.bundle_resources()"`. That is hard to know.

**Comment by philippjfr** [comment]
@MarcSkovMadsen It's now documented that you should run `python setup.py develop` when the resources change, after you requested it, but the dev docs haven't rebuilt yet. I will improve the development experience for this eventually but I did warn you about this a couple of times 😉

**Comment by philippjfr** [comment]
I'm also not sure you pulled after the CSS tweaks PR was merged because the plot heights were limited to 450 pixels in that PR and they are still stretching across the screen in your screenshots.

**Comment by philippjfr** [comment]
Thanks for reporting back though, sorry for the bad developer experience.

**Comment by MarcSkovMadsen** [comment]
FYI. @philippjfr . I've updated the above report after running python -c "from panel import compiler;compiler.bundle_resources()"

Unfortunately when I finished I got this

```bash
$ git pull holoviz master
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 14 (delta 7), reused 9 (delta 7), pack-reused 0
Unpacking objects: 100% (14/14), 7.91 KiB | 128.00 KiB/s, done.
From https://github.com/holoviz/panel
 * branch              master     -> FETCH_HEAD
   2ae530fa..bdf0c825  master     -> holoviz/master
Updating 2ae530fa..bdf0c825
Fast-forward
 panel/io/notebook.py                  | 12 ++++++++----
 panel/template/material/dark.css      |  2 +-
 panel/template/material/material.css  |  3 +++
 panel/template/material/material.html |  6 ++++++
 panel/template/vanilla/vanilla.css    |  7 +++++--
 panel/template/vanilla/vanilla.html   |  2 +-
 6 files changed, 24 insertions(+), 8 deletions(-)
```

**Comment by MarcSkovMadsen** [comment]
FYI @philippjfr . I will rerun the test.

**Comment by MarcSkovMadsen** [comment]
FYI. @philippjfr . I've rerun the test and updated the report above.

**Comment by MarcSkovMadsen** [comment]
I just tried rerunning `python setup.py develop` and a few of the tests. It did not change anything.

**Comment by MarcSkovMadsen** [comment]
```bash
$ git pull holoviz master
From https://github.com/holoviz/panel
 * branch              master     -> FETCH_HEAD
Already up to date.
```

**Comment by MarcSkovMadsen** [comment]
I've tested on Firefox. Here are differences

![image](https://user-images.githubusercontent.com/42288570/96870260-ebce7180-1470-11eb-9a9f-311f699478b2.png)

![image](https://user-images.githubusercontent.com/42288570/96870418-29cb9580-1471-11eb-881a-866d17fc4463.png)

**Comment by MarcSkovMadsen** [comment]
There are many things that can be improved about these templates and there will be bugs. But they are already SO AWESOME.

**Comment by MarcSkovMadsen** [comment]
FYI. @philippjfr . After a `git pull holoviz master` the Bootstrap Template works. I've updated the Test report above to with my findings.

**Comment by philippjfr** [comment]
This was super helpful, thanks @MarcSkovMadsen! However now that we're releasing any remaining problems should be broken down into smaller, concrete issues.
