### ISSUE TITLE
dynamic option in Tabs seems to be broken

### ISSUE THREAD

**Issue by krlng** [holoviz/panel#1681]
Using:
panel==0.9.7
jupyterlab==2.1.4

Even using `dynamic=True` all tabs seem to be rendered. 

For example the code below:
```
class TabClass(param.Parameterized):
    key = param.Integer(default=0)
    
    def tab1_func(self):
        return pn.Row(self.key)

    def tab2_func(self):
        setattr(self, 'key', self.key+1)
        return pn.Row("increase")
    
    def view(self):
        return pn.Tabs(self.tab1_func, self.tab2_func, dynamic=True)

obj = TabClass()
obj.view()
```

directly triggers an RecursionError, which in my point of view should not happen, until I click on the second tab, since it would not be rendered otherwise.

**Comment by philippjfr** [comment]
Dynamic is primarily about not sending the contents of all tabs to the frontend, it doesn't prevent the contents from being evaluated. In theory that at least seems feasible though.

**Comment by krlng** [comment]
Okay, that does explain a lot. Is there another way to only run a function if a tab is activated? Did not find any documentation on how to link tab activation to a function or similar.

**Comment by philippjfr** [comment]
This issue was added first but I'll close as a duplicate of https://github.com/holoviz/panel/issues/1933
