### ISSUE TITLE
Support adding custom css and .js to a Template or Page only - Not globally

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1696]
I am running multipage sites with Panel. I would like to give my self and my users the freedom to use the template they would like and want for their specific app/ page.

The problem is that as far as I can see there is no way to only add custom `pn.extension`, `js` or `css` to a page or Template.

1. Using pn.extension, pn.config.css_files, pn.config.raw_css, pn.config.js_files adds the asset(s) globally. Not only to the specific app.
2. The new Templates does not support this either. The BasicTemplate has a _resources dict for `js` and `css` but this is for bundled assets only. Not something the user can use.

#### Additional Context

- Since the new Templates are not mature they will need custom css for lots of use cases.
- Please also note that a lot of my `js` files need the `script` attribute `type='module'` this is not supported today either. Would be really, really nice to have

**Comment by MarcSkovMadsen** [comment]
#### Workaround (maybe)

I hope something like the below can be used to add css.

```python
def set_template_css(template, theme):
    TEMPLATE_CSS_ID = "/* CUSTOM TEMPLATE CSS */\n"
    # remove other site css
    pn.config.raw_css=[css for css in pn.config.raw_css if not css.startswith(TEMPLATE_CSS_ID)]

    files = [
        "all.css",
        f"all_{theme}.css",
        f"{template}_{theme}.css",
        f"{template}_{theme}.css",
    ]
    for file in files:
        if not file in pn.state.cache:
            file_css_id = f"/* {file} */\n"
            text = TEMPLATE_CSS_ID + file_css_id + (ROOT/file).read_text()
        else:
            text = pn.state.cache[file]
        pn.config.raw_css.append(text)
```

**Comment by philippjfr** [comment]
Can you explain how this differs from https://github.com/holoviz/panel/issues/1159?

**Comment by MarcSkovMadsen** [comment]
#1159 is more general in theory. It’s for any app/page. But in essence they are the same.

This request is focused on the new templates.

And I’ve also learned that it should include the option to serve the js and css of specific extensions only.

I’ve also learned that it would have been so nice that css was configured via a dictionary instead of a list. That would make it easier to update or remove for different templates.

**Comment by Jhsmit** [comment]
For me it would be useful if Subclassing existing default templates or ``BasicTemplate`` is easier. Although perhaps I should subclass the ``BaseTemplate``, but ``BasicTemplate`` has a lot of useful things for me. 

For panel 0.10.0 I've had to override `_template_resources` so that I can specify my own static directory.

Also, at the moment I'm monkey-patching `_template` on ``BasicTemplate`` with a subclass of ``str`` which has a ``read_text`` function so that I can provide the jinja template in a string rather than ``Path``

**Comment by philippjfr** [comment]
Templates now have their own `.config` object and the global config is now also per session which means CSS and JS declared on one application won't leak to other applications on the same server.
