### ISSUE TITLE
Text of fixed width alert not aligned

### ISSUE THREAD

**Issue by nritsche** [holoviz/panel#1723]
#### Description of expected behavior and the observed behavior
Expected text to be aligned with the alert.
Observed behaviour:
![Screenshot from 2020-10-30 11-34-30](https://user-images.githubusercontent.com/2536635/97744448-7aac4100-1aa4-11eb-8845-7b6e45e3f688.png)

#### Code

```
pn.pane.Alert(
            "**You already voted on the data quality of this day.** "
            "Choose a different option to change your decision.", 
            width=220,
            sizing_mode="fixed",
            alert_type="primary"
        )
```

#### software version info

Ubuntu 20.04.1 LTS
Python 3.8.5
panel 0.10.1

**Comment by philippjfr** [comment]
Weird, here's what I see:

<img width="230" alt="Screen Shot 2020-11-01 at 6 41 23 PM" src="https://user-images.githubusercontent.com/1550771/97810131-e8f22e80-1c71-11eb-97e4-d31d7755c495.png">

Also not great but not as broken as what you're seeing.

**Comment by xavArtley** [comment]
Same here I tested in jupyterlab and with a bokeh server on chrome and firefox
![Capture d’écran de 2020-11-01 18-44-49](https://user-images.githubusercontent.com/18531147/97810945-b9debb80-1c77-11eb-891a-4a680dfb7461.png)

**Comment by nritsche** [comment]
Mine is in an mdl-drawer (https://github.com/chime-experiment/bondia/blob/5a421afdce8c64651ea833e8426b34275bb8932d/bondia/templates/mdl.html#L49). I don't know if that's the reason it looks different.

**Comment by philippjfr** [comment]
That is probably the issue and I'm not sure how to reproduce. It's really more of a usage question since it's such a specific issue. If this issue still persists there's probably not a whole lot we can do about it until the bokeh layout engine changes which are scheduled for Bokeh 3.0 land.
