### ISSUE TITLE
App doesn't show in Firefox but in Chromium it does.

### ISSUE THREAD

**Issue by ghost** [holoviz/panel#1726]
So, as the title says, I build a simple app with panel and when I try to display it in the browser it fails to show in Firefox, but when I try with Chromium it shows perfectly.

Firefox (blank page)
![image](https://user-images.githubusercontent.com/51416186/97752796-5a877c80-1aba-11eb-8adc-6a348ea360fd.png)

Chromium
![image](https://user-images.githubusercontent.com/51416186/97753525-8bb47c80-1abb-11eb-842f-022fa47afb55.png)

This doesn't really bother me (I just open the app in chromium) but I would like to know if there is a way to set the default browser in which panel would open the apps; I have Firefox as my default browser, so I guess this is why when I call the  `.show()`
 method it opens the app in Firefox, ¿how to change this?

__Using:__
Python 3.8.3
Panel 0.10.1
Firefox 82.0 (64-bit)
Chromium 86.0.4240.111 
Ubuntu 20.04.1 LTS

**Comment by mattpap** [comment]
@Jhoan1970, what's the output from JS console in Firefox?

**Comment by Jhoan1970** [comment]
This is what I get in the JS console:
```
[Exception... "Favicon at "http://localhost:43017/favicon.ico" failed to load: Not Found."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 241"  data: no]
```

**Comment by philippjfr** [comment]
I can't reproduce any issues with Firefox. Could you provide an example of an app that doesn't render for you?
