### ISSUE TITLE
Confusing error for older panel versions with newer bokeh

### ISSUE THREAD

**Issue by ppwadhwa** [holoviz/panel#1738]
![Screen Shot 2020-11-02 at 10 23 59 AM](https://user-images.githubusercontent.com/54282105/97892574-ca357b80-1cf5-11eb-9fd8-7621f9577eca.png)

It is not clear, this can be easily fixed with a panel change, but the above exception is very confusing if you have a newer version of bokeh (e.g. bokeh 2.2.3) and an older version of panel (e.g. panel 0.9.7).  Ideally, we could detect the presence of a newer bokeh version and tell people to upgrade panel.

Alternatively, the conda recipe could be updated to an upper pin on bokeh.

**Comment by philippjfr** [comment]
Appreciate the report, this has since been resolved.
