### ISSUE TITLE
Varius Template Style Issues

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1742]
I plan to contribute PR to fix or improve the below ASAP. Screenshots are from current MASTER branch. 

This Bug Report is created to collect the bugs.

#### Material Template

![image](https://user-images.githubusercontent.com/42288570/98129196-24cb0500-1eb9-11eb-8f60-55811057e186.png)

#### Bootstrap

Does not obey `main_max_width`

![image](https://user-images.githubusercontent.com/42288570/98129333-4d52ff00-1eb9-11eb-9569-e8b36fcc101a.png)

![image](https://user-images.githubusercontent.com/42288570/98130928-167de880-1ebb-11eb-99c7-d46758d37ae7.png)

#### React

![image](https://user-images.githubusercontent.com/42288570/98129614-9c992f80-1eb9-11eb-9938-145a7469c896.png)

#### Vanilla

![image](https://user-images.githubusercontent.com/42288570/98129703-b9cdfe00-1eb9-11eb-8fb2-c083a684b0a0.png)

**Comment by MarcSkovMadsen** [comment]
Upps. The tests above are not fully valid. I at awesome-panel.org I have some css fixes for Panel 0.10. The above is for MASTER.

I will do the PR based on master and the test_manual.py file and only fix issues on that.

**Comment by philippjfr** [comment]
Are these all fixed now? Please reopen if not.
