### ISSUE TITLE
Panel 'viewer' or 'scrubber' layout type

### ISSUE THREAD

**Issue by jlstevens** [holoviz/panel#1747]
Panel has several ways to display collections of objects such as `Row`, `Column` `Tabs` etc. Both `Row` and `Column` display items simultaneously, while `Tabs` put things behind tabs where you view one tab at once. This works well until you have very large collections of objects that result in an overwhelming number of tabs.

One alternative that I think would be nice would also display a single item at a time but without the tabs. Instead, there would be a 'previous' and 'next' arrow/button on the left and right to scrub through the items. In HoloViews this is conceptually similar to a `HoloMap` where instead of a slider/scrubber you have a 'next' and 'previous' button. This whole concept is closely related to the HoloViews scrubber widget.

The two buttons are the minimal UI but there are various optional flourishes you can imagine:

* An item indicator e.g (3/45 to tell you that you are viewing item 3 out of a total of 45)
* Some way to jump straight to a specific item e.g if the first value in the item indicator suggestion above were editable.
* A first/last button to jump straight to the first or last item. This might be useful if you want to scrub in reverse order: you would hit the 'last' button and then tap the 'previous' button.

**Comment by jbednar** [comment]
Seems useful. The [player widget](https://panel.holoviz.org/reference/widgets/Player.html) itself might be usable here, since it already supports the "optional flourishes", plus also has a Play button so that you can passively watch the contents flip by. E.g. you might leave it continuously playing, and then if you ever noticed something interesting you could stop it.

**Comment by jlstevens** [comment]
I agree the player widget would be *one* option but I think it is overkill for the simple case. I would like something that is minimal by default (that you can add to if you desire) rather than something as complex as the player widget by default.

**Comment by jbednar** [comment]
Agreed; the Player UI is very heavyweight and would not be ideal as a default.

**Comment by philippjfr** [comment]
Going to close this one, I've not seen any more requests for this and it's simple enough to build the UI yourself with some buttons.
