### ISSUE TITLE
Component for browser alerts

### ISSUE THREAD

**Issue by jbednar** [holoviz/panel#1752]
It would be nice if it were easy for a Panel app to provide browser-based alerts like those in the [nyt-2020-election-scraper](https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html) ([github](https://github.com/alex/nyt-2020-election-scraper)).  It would presumably need to specify a periodic polling interval, some callback function for deciding if an alert is needed, and a function for calculating the text of the alert...

**Comment by philippjfr** [comment]
I remember discussing this at the time but I honestly forget what the alerts on that page looked like. Do you think this is covered by https://panel.holoviz.org/reference/global/Notifications.html? You can certainly set up a polling interval easily enough with add_periodic_callback or `setInterval` in JS and then adding the alert.
