### ISSUE TITLE
LoadingSpinner and BooleanStatus not showing up

### ISSUE THREAD

**Issue by fmaussion** [holoviz/panel#1755]
This is panel version 0.10.1, a very recent environment. The bug is reproducible on MyBinder: https://mybinder.org/v2/gh/OGGM/glacier_simulator/master?filepath=app.ipynb

Trying to run the [Busy Indicators example](http://blog.holoviz.org/panel_0.10.0.html#Busy-indicators) leads to:

![image](https://user-images.githubusercontent.com/10050469/98591393-77992800-22d0-11eb-92c5-195b348a6e75.png)

**Comment by philippjfr** [comment]
That's a huge bug, it seems that build has none of the CSS that's bundled with Panel. I'll have to release 0.10.2 today.

**Comment by philippjfr** [comment]
Only seems to affect the conda-forge build so I'll get out a new build on there.

**Comment by philippjfr** [comment]
Fixed in https://github.com/conda-forge/panel-feedstock/pull/31
