### ISSUE TITLE
Streamz example raises warning regarding add_periodic_callback

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1761]
Panel 0.10.1

Docs: https://panel.holoviz.org/reference/panes/Streamz.html#panes-gallery-streamz

![image](https://user-images.githubusercontent.com/42288570/98705291-d8326e80-237d-11eb-97f2-22225775fe29.png)

**Comment by philippjfr** [comment]
Thanks for the report but this has already been fixed: https://github.com/holoviz/panel/pull/1731
