### ISSUE TITLE
Plotly plot in Plotly Pane inside Card does not work well.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1770]
Panel 0.10.1

I'm trying to create a demo streaming app with the different plotting libraries supported by Panel. I can see that the Plotly plot does not (re-)size well inside a card. And furthermore does not work responsively in the ReactTemplate.

![plotly_card](https://user-images.githubusercontent.com/42288570/98850094-87da1000-2454-11eb-9c74-be10e8e5914c.gif)

#### Minimum reproducible example

![image](https://user-images.githubusercontent.com/42288570/98849777-071b1400-2454-11eb-95ef-021e9a6f9648.png)

![image](https://user-images.githubusercontent.com/42288570/98849825-1b5f1100-2454-11eb-9e34-7755e199cba0.png)

![image](https://user-images.githubusercontent.com/42288570/98849878-303ba480-2454-11eb-8488-b534e80c80b2.png)

```python
import numpy as np
import altair as alt
import pandas as pd
import panel as pn
from streamz.dataframe import DataFrame as sDataFrame
import hvplot.pandas
import plotly.express as px

plotly_pane = pn.pane.Plotly(sizing_mode="stretch_both", config={'responsive': True})

def update_plotly(data):
    data = pd.concat(data).reset_index()
    plot = px.line(data, y="y", title='Plotly', template="plotly_dark")
    plot.layout.autosize=True
    plotly_pane.object = plot

df = sDataFrame(example=pd.DataFrame({"y": []}, index=pd.DatetimeIndex([])))
window_stream = df.cumsum().stream.sliding_window(50)

plotly_sink = window_stream.sink(update_plotly)

def emit():
    df.emit(pd.DataFrame({"y": [np.random.randn()]}, index=pd.DatetimeIndex([pd.datetime.now()])))
emit()
pn.state.add_periodic_callback(emit, period=100, count=500)

layout = pn.template.ReactTemplate(
    site="Awesome Panel",
    title="Streaming w. Echarts",
    theme=pn.template.react.DarkTheme,
    row_height=200,
)
layout.main[0:2, 0:6]=pn.layout.Card(plotly_pane, header="PLOTLY", sizing_mode="stretch_both")
layout.servable()
```

**Comment by xavArtley** [comment]
From what I see it's more a plotly problem. It seems like plotly is not height responsive
https://plotly.com/javascript/responsive-fluid-layout/
I tried the codepen from the doc (https://codepen.io/pen/?&editable=true=https%3A%2F%2Fplotly.com%2F) and the height doen not appear to change

**Comment by MarcSkovMadsen** [comment]
Thanks @xavArtley 

Regarding the missing height responsiveness I've created an issue here https://github.com/plotly/plotly.js/issues/5270.

I can see that there are some technical discussions on the (lack of) responsiveness here 

- [Plotly Not Responsive When Parent Size Changes](https://github.com/plotly/plotly.js/issues/3984)
- [Responsive figure with locked aspect ratio](https://github.com/plotly/plotly.js/issues/3467)
- [dcc.Graph: Improve responsiveness, expose resize status, allow wrapper extension](https://github.com/plotly/dash-core-components/pull/706)

Maybe somebody more technically skilled than me can find a solution some day. That might also solve 

- [Responsive mode for Plotly plots not working in practice](https://github.com/holoviz/panel/issues/1514)

I am thinking how to handle this. Because a new user of Panel would not know or care that it really is Plotly.js that is the issue. **Should we put a small comment in the Plotly pane reference guide that Plotly is not height responsive and the the responsiveness of plotly overall is not that great?**

**Comment by jonmmease** [comment]
Here's an example that builds a width/height responsive plotly.js figure. This is a cleaned up version of the output of `plotly.io.write_html`.

```html
<html>
<head><meta charset="utf-8"/></head>
<body>
    <div>
        <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <div id="0c689639-14e5-46c8-bb86-7c8fe6f132c6" class="plotly-graph-div" style="height:100%; width:100%;"></div>
        <script type="text/javascript">
            window.PLOTLYENV=window.PLOTLYENV || {};                                    
            if (document.getElementById("0c689639-14e5-46c8-bb86-7c8fe6f132c6")) {
                Plotly.newPlot(
                    "0c689639-14e5-46c8-bb86-7c8fe6f132c6",  // elemend id
                    [{"type": "scatter", "y": [1, 3, 2]}],   // figure.data
                    {"title": {"text": "Fig title"}},        // figure.layout
                    {"responsive": true}                     // figure.config
                )
            };
        </script>
    </div>
</body>
</html>
```

![responsive_figure](https://user-images.githubusercontent.com/15064365/99074846-78f37a80-2586-11eb-963d-72680bc45662.gif)


As I recall, I think it was important to explicitly set the width and height of the div enclosing the figure to `100%`.
