### ISSUE TITLE
Image not scaling dynamically

### ISSUE THREAD

**Issue by johnzeringue** [holoviz/panel#1777]
#### ALL software version info

```
Python 3.9.0

bokeh==2.2.3
notebook==5.7.9
panel==0.10.1

macOS Catalina 10.15.7

Chrome 85.0.4183.121
```

##### Expected

I should be able to scale image up and down dynamically in Jupyter Notebook and using the standalone server.

##### Observed

In the notebook, I'm able to scale up and down <= 300 width. I can't make the image larger than 300 pixels wide.

Using the standalone server, it looks like it scales just once (either up or down) and then gets stuck.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn

def panel_logo(width=300):
    # also happens with .jpg
    return pn.panel("https://panel.holoviz.org/_static/logo_stacked.png", width=width)

pn.interact(panel_logo)
```

**Comment by jbednar** [comment]
I can reproduce:

![image](https://user-images.githubusercontent.com/1695496/99000842-84e82980-24ff-11eb-9e6b-81f02b4563b0.png)
![image](https://user-images.githubusercontent.com/1695496/99000873-90d3eb80-24ff-11eb-91f3-4a85846e6ffd.png)
![image](https://user-images.githubusercontent.com/1695496/99000916-9df0da80-24ff-11eb-9fe6-06cf4098204c.png)

**Comment by jbednar** [comment]
If I increase the initial width to 1000 it works up to 1000, so this seems like the same issue as for the Bokeh layout of a single-digit number, where there's no room left for the number to increase in size.

**Comment by johnzeringue** [comment]
It's probably worth adding that in the original use case, I was changing the URL too. Not sure if that makes it different from the single-digit number case layout-wise.

Using this code
```python
import panel as pn

logo_urls = {
    "panel": "https://panel.holoviz.org/_static/logo_stacked.png",
    "hvplot": "https://hvplot.holoviz.org/assets/hvplot-wm.png",
}

def panel_logo(logo="panel", width=300):
    return pn.panel(logo_urls[logo], width=width)

pn.interact(panel_logo, logo=logo_urls.keys())
```

You have the case
1. Load default (Panel logo, width 300)
2. Change width to 600 (no change in image size)
3. Change logo to hvPlot (image width is 600!)
