### ISSUE TITLE
Allow saving the state of a react template for later deployment

### ISSUE THREAD

**Issue by CesarRodriguezPereira** [holoviz/panel#1781]
The React template allows for dynamic resizing and positioning of the different elements in a panel. Using this template for dashboard design and synchronizing this design with python would allow for a great UX for dashboard design: you design your plots and various elements, you throw them all together without worrying about their positions and sizes, then you place each block in its final position, save the dashboard state in python and deploy that.

This comes from a question I made yesterday at pydata's Panel tutorial. From what I gather, saving this state should already be possible through JavaScript (but we're python programmers, aren't we :-). Two main possibilities came from the short discussion about the topic:

- Saving the dashboard state and deploying a fixed version of the react template (makes it so users don't have the capacity to worsen your design by accident). The decision to make the deployed version fixed or not (but conserving the original design unless the user modifies it) could also be good to implement.
- Allowing this design to be saved in the URL. Pros: Each user can link to a state containing only what matters to them. Cons: Extremely long URLs.

I don't know about how doable or even necessary this is. I'm a novice panel user, but I just thought this could make an already cool template even cooler.

**Comment by MarcSkovMadsen** [comment]
Fyi @nghenzi

**Comment by jbednar** [comment]
> The decision to make the deployed version fixed or not (but conserving the original design unless the user modifies it) could also be good to implement.

You could also provide a lock icon that the programmer can set open or closed by default, depending on how much they worked on the layout; the layout would then stay as designed unless the user explicitly unlocks it...

**Comment by MarcSkovMadsen** [comment]
Or you could use the url search parameters to store the information. Then the user can bookmark one or more configurations and actually share it with colleagues or friends.

**Comment by jbednar** [comment]
Yes, at least optionally letting a user persist the configuration to the URL would be very handy, so that users could set things up how they like.

Note that locking it to a specified configuration may not be feasible in general, given that each user has a different screen resolution and window size, so it won't necessarily look the same to them as to you. So it's great to be able to persist the configuration as a good starting point, but users will often benefit from being able to resize things properly for their own display.

**Comment by philippjfr** [comment]
Two things, the ReactTemplate now persists the state across sessions but that is entirely in Javascript. On the other end the [GridStack](https://pyviz-dev.github.io/panel/reference/layouts/GridStack.html#layouts-gallery-gridstack) layout provides the same functionality but as a Python component, which means you can access and restore the layout state.
