### ISSUE TITLE
Template not working in Notebook.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1794]
Panel 0.10.1, pyviz_comms 0.7.6

#### Context

One of the unique things about Panel is that you can create applications for the Jupyter Notebook. So applications you can actually give to users. That they can use in a Notebook. And they can get data, plots and model as output from the app to be used for further exploration and development. 

For example organisations developing ML frameworks can provide a GUI on top that can be used in the Jupyter Notebook.

Also just for examples in the Gallery and Reference Gallery it would be so awesome if it could be showcased how easy it is to create nicely designed apps in Panel.

But unfortunately the new Templates do not work in the notebook.

#### Reproducible Example

https://panel.holoviz.org/reference/templates/Vanilla.html#templates-gallery-vanilla

```python
import panel as pn
import numpy as np
import holoviews as hv

pn.extension()

vanilla = pn.template.VanillaTemplate(title='Vanilla Template')

pn.config.sizing_mode = 'stretch_width'

xs = np.linspace(0, np.pi)
freq = pn.widgets.FloatSlider(name="Frequency", start=0, end=10, value=2)
phase = pn.widgets.FloatSlider(name="Phase", start=0, end=np.pi)

@pn.depends(freq=freq, phase=phase)
def sine(freq, phase):
    return hv.Curve((xs, np.sin(xs*freq+phase))).opts(
        responsive=True, min_height=400)

@pn.depends(freq=freq, phase=phase)
def cosine(freq, phase):
    return hv.Curve((xs, np.cos(xs*freq+phase))).opts(
        responsive=True, min_height=400)

vanilla.sidebar.append(freq)
vanilla.sidebar.append(phase)

vanilla.main.append(
    pn.Row(
        pn.Card(hv.DynamicMap(sine), title='Sine'),
        pn.Card(hv.DynamicMap(cosine), title='Cosine')
    )
)
vanilla.servable()
```

#### Screenshots

![image](https://user-images.githubusercontent.com/42288570/99481304-1d483900-295a-11eb-8a0e-6793b9891c61.png)

![image](https://user-images.githubusercontent.com/42288570/99481485-892aa180-295a-11eb-9f6f-e8a7092f6c5e.png)

#### Trace Back

There are two fundamental problems. The `css` not being served and a communication problem.

```bash
Refused to apply style from 'http://127.0.0.1:8888/static/extensions/panel/bundled/vanillatemplate/vanilla.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

```bash
Refused to apply style from 'http://127.0.0.1:8888/static/extensions/panel/bundled/vanillatemplate/default.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

```bash
Python failed with the following traceback: 
c:\repos\private\panel-extensions-template\.venv\lib\site-packages\pyviz_comms\__init__.py _handle_msg L316
c:\repos\private\panel\panel\viewable.py _on_msg L258
	AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by philippjfr** [comment]
https://github.com/holoviz/panel/issues/2274 has a more extensive discussion about the issues surrounding this.
