### ISSUE TITLE
Broken gapminders demo

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#1802]
The docs frontpage at https://panel.holoviz.org/ points here when clicking the gapminder demo image: https://gapminders.pyviz.demo.anaconda.com/

Currently this gives 502 bad gateway, whereas the other demos are working.

Any idea what's wrong?

**Comment by jlstevens** [comment]
Thanks for reporting this!

I'm not quite sure why the deployment went down but I've restarted it and it looks like it is back up and working again.
