### ISSUE TITLE
Height of MultiChoice doesn't fit it's content

### ISSUE THREAD

**Issue by nritsche** [holoviz/panel#1806]
#### software version info
panel==0.10.2

I want to use `MultiChoice` instead of `MultiSelect` for a `param.ListSelector`:

```
    panel.param.Param(
            self.param,
            expand_button=False,
            widgets={
                "flags": panel.widgets.MultiChoice,
            },
        )
```

This is the result:
![bug](https://user-images.githubusercontent.com/2536635/100401580-c3590a80-300e-11eb-9a31-fa367f910f70.gif)

Expected behaviour: the height always fits the content
Observed behaviour: the height increases for some selections, for others it doesn't...

**Comment by nritsche** [comment]
workaround:
```
panel.param.Param(
            self.param,
            expand_button=False,
            widgets={
                "flags": panel.widgets.MultiChoice,
            },
            width=325,
        )
```

**Comment by philippjfr** [comment]
Sorry we never got to this but at some point this appears to have been fixed in bokeh.
