### ISSUE TITLE
FileSelector.controls not useable

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1814]
Panel 0.10.2
Bokeh 2.2.3

I'm trying to style all Panel widgets in the Fast.design framework. To be quickly test this visually for different parameter settings I use the `.controls` on the widget.

But for the `FileSelector` it only shows the name which is not very useful.

```python
from panel import widgets as pnw
import panel as pn

component = component = pnw.FileSelector(name="Hello", max_height=400)
controls = component.controls()
pn.Column(component, controls).servable()
```

![image](https://user-images.githubusercontent.com/42288570/100462312-5e62ea80-30ca-11eb-87c8-1af9aeca35b0.png)

### Solution

Add widget parameters to `FileSelector.controls` similarly to other widgets.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by philippjfr** [comment]
Please open one issue for all of these. Having 4 issues for different widgets for what is the same underlying issue is just introducing clutter.
