### ISSUE TITLE
FileDownload widget can't get disabled=False once created with disabled=True

### ISSUE THREAD

**Issue by hsansilva** [holoviz/panel#1820]
Dear Panel team,

I'm facing an issue with the new FileDownload widget which I believe to be a bug, unless I'm doing a bad utilization of it. For info, I'm using Panel version 0.10.2.

Consider the following MWE:

```python
import time
import panel as pn
pn.extension()

log_download1 = pn.widgets.FileDownload(button_type='success', label='Download log', disabled=True)

log_download2 = pn.widgets.Button(button_type='success', name='Download log', disabled=True)

def enable_button(button_obj):
    for i in range(5):
        time.sleep(1)
        if i == 3:
            button_obj.disabled = False

#then compare 
enable_button(button_obj=log_download1)

#against 
enable_button(button_obj=log_download2)
```

Upon calling enable_button on `log_download1` (FileDownload widget), the button won't get enabled when `i == 3`. Making the same for `log_download2` (Button widget) works as expected: the button is created disabled and it gets enabled if a given condition is met. It is unfortunate if the same behavior can't be obtained using FileDownload since in my use case, I need to make the download available only when a given flag is found in a log file.

Hope it helps.

Thanks in advance,

Hugo

**Comment by rafgonsi** [comment]
Hello,

I experienced similar issue with panel 0.9.7. It seems that the button gets enabled (at least in a sense that its `disabled` values is set to `False`, although this change is not visible. See gif below:

![Peek 2020-12-08 17-17](https://user-images.githubusercontent.com/33317987/101606722-faaeba80-3a03-11eb-9c92-cdc937a4b0c2.gif)

See the discussion and possible workaround here 
https://discourse.holoviz.org/t/filedownload-widget-does-not-disable-enable-correctly/1523
