### ISSUE TITLE
Curious why panel Card uses "title" instead of "name" as parameter

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#1832]
Just seemed a bit inconsistent since I think most if not all other panes/widgets use a "name" parameter
https://panel.holoviz.org/reference/layouts/Card.html#layouts-gallery-card

**Comment by philippjfr** [comment]
It's a good question which I don't have a great answer too. Since Card is a layout I don't think it's a massive issue though since `name` is only consistently used by widgets. At this point I think the ship has sailed on this.
