### ISSUE TITLE
Numeric Param Widgets, initialised with None, displayed as active "0"

### ISSUE THREAD

**Issue by okz** [holoviz/panel#1836]
#### ALL software version info
Panel 10.1

#### Description of expected behavior and the observed behavior
Widgets or parameters initialised as "None" has value of 'None', but still display an active '0' 

#### Complete, minimal, self-contained example code that reproduces the issue

```
class Test(param.Parameterized) :
    w_none_but_0 = param.Number(default=None, allow_None=True)
    w_none_forced = param.Number(default=None, allow_None=True)

    
    # Since default None, was not displayed correctly, tried to override with None,
    # to clear the widget, but had no effect..
    def __init__(self, **params):
        super().__init__(**params)
        self.param.set_param("w_none_forced", 450) 
        self.param.set_param("w_none_forced", None)    # didn't improve anything
          
    
t = Test()
pn.Row(t)

```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/3274852/102081667-82336980-3e08-11eb-8fa9-c13836f30b91.png)

**Comment by xavArtley** [comment]
Related to #581
