### ISSUE TITLE
AutocompleteInput

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#1840]
When I set restrict=False, it raises the following even though it's listed in the docs.
https://panel.holoviz.org/reference/widgets/AutocompleteInput.html#widgets-gallery-autocompleteinput

WARNING:param.AutocompleteInput00305: Setting non-parameter attribute restict=False using a mechanism intended only for parameters

**Comment by ahuang11** [comment]
Nevermind restarting kernel helped.

**Comment by jbednar** [comment]
Also maybe spelling it `restrict` and not `restict` helped. :-)
