### ISSUE TITLE
Styling Panel widget DataFrame

### ISSUE THREAD

**Issue by AlieCat** [holoviz/panel#1842]
#### Problem
I would like to style a pn.widgets.DataFrame() so that null values are highlighted in red

#### Desired solution
Pandas has a Styler that provides this feature:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.formats.style.Styler.highlight_null.html#pandas.io.formats.style.Styler.highlight_null
I would like to use this feature when using the DataFrame as a widget.

#### Considered alternatives
I've tried assigning the style to the value atrribute of the widget, but that doesn't seem to be displaying.
I've also considered using css and jquery to style the table, and that might be a good work around.

**Comment by philippjfr** [comment]
The new [Tabulator](https://pyviz-dev.github.io/panel/reference/widgets/Tabulator.html#widgets-gallery-tabulator) widget supports this.
