### ISSUE TITLE
Interactivity not working in jupyter lab (it is working in notebook)

### ISSUE THREAD

**Issue by lhoupert** [holoviz/panel#1845]
#### ALL software version info
holoviews version : 1.14.0
panel version : 0.10.2
bokeh verison: 2.2.3 (same behavior on 2.2.2 and 2.2.1)

jupyter core     : 4.7.0
jupyter-notebook : 6.1.5
qtconsole        : 5.0.1
ipython          : 7.19.0
ipykernel        : 5.4.2
jupyter client   : 6.1.7
jupyter lab      : 2.2.9
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5
#### Description of expected behavior and the observed behavior
I starting discussing my problem on a post on [discourse](https://discourse.holoviz.org/t/how-to-link-the-hover-text-so-it-change-automatically-when-switching-between-holomap-object/1573/4). The interactivity is not working on my jupyter notebook (see cell block 13 on: https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/bvhp6qckf66rrml/choropleth_data_link_holomaps.ipynb#Others-tests)
However, it is working when exported as a static html webpage  (you can download it here: https://dl.dropboxusercontent.com/s/z1qto9ws7htvmyt/maps_panel_discourse.html?dl=0)

From what I read it may be due to  bokeh so I am going to try with different version. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

#### Screenshots or screencasts of the bug in action
What I got on the notebook:
![Screenshot 2020-12-16 at 10 30 56](https://user-images.githubusercontent.com/10154151/102330494-833bd680-3f81-11eb-969f-e2d5a0b05cab.png)

What I have on my html export (and what I should have on the notebook):
![Screenshot 2020-12-16 at 10 32 50](https://user-images.githubusercontent.com/10154151/102330638-b5e5cf00-3f81-11eb-90f3-a79d1ae01b6d.png)

**Comment by lhoupert** [comment]
I check for several version of bokeh, it doesn't change anything. However, I just realised that the interactivity is working in jupyter notebook but not in jupyter lab.

**Comment by philippjfr** [comment]
Did you install the JupyterLab extension?

>jupyter labextension install @pyviz/jupyterlab_pyviz

**Comment by lhoupert** [comment]
@philippjfr thank you ! I was sure it was installed in this environment but it was not. Sorry for this beginner mistake... However, I still have a problem to run the "Getting started" example (https://panel.holoviz.org/getting_started/index.html) but I will open a specific issue for that.

**Comment by lhoupert** [comment]
By the way if you think it is a good example for the gallery. I attach the code below:

```python3
import holoviews as hv
from holoviews import opts
hv.extension('bokeh')

import panel as pn
import panel.widgets as pnw
pn.extension()

from bokeh.sampledata.us_counties import data as counties
from bokeh.sampledata.unemployment import data as unemployment


# Generate dummy data
data2 = {}
data3 = {}
for ind, keys in enumerate(list(unemployment.keys())):
    data2[keys] = unemployment[keys]+ind/10
    data3[keys] = unemployment[keys]-ind/10   

unemployment_datasets={
    "Unemployment": unemployment,
    "Data2": data2,
    "Data3": data3
}

def get_counties(var):
    result = []
    for cid, county in counties.items():
        if county["state"]=="tx":
            row = dict(county)
            row[var]=unemployment_datasets[var][cid]
            result.append(row)
    return result

def plot_map(var='Unemployment'):
    data = get_counties(var)
    choropleth = hv.Polygons(data, ['lons', 'lats'], [('detailed name', 'County'), var])#, label='Texas ' + var)
    choropleth.opts(opts.Polygons(width=400, height=400,  tools=['hover', 'tap'], xaxis=None, 
                     yaxis=None, color_index=var))
    return choropleth

def get_table(var='Unemployment'):
    data = get_counties(var)
    table = hv.Table(data, [('detailed name', 'County'), var])
    table.opts(
       opts.Table(height=328)
    )
    return table


statistics = ("Unemployment", 'Data2', 'Data3')

variable  = pnw.RadioButtonGroup(name='variable', value='Unemployment', 
                                 options=list(statistics))

@pn.depends(variable)
def reactive_map(variable):
    return plot_map(variable)

@pn.depends(variable)
def reactive_table(variable):
    return get_table(variable)

widgets   = pn.Column("<br>\n# Statistics", variable)
maps_pn = pn.Column(widgets,pn.Row(reactive_map, reactive_table))

#maps_pn.show()
maps_pn

```

**Comment by jbednar** [comment]
That looks like a good start for an example! It's a shame that the unemployment dataset only has that one column of data. I think it could be a compelling example if it used actual data for all three columns, if the table showed all three columns, and if link_selections were used so that clicking on or selecting counties on the map would highlight those rows of the table and clicking on rows in the table would highlight those counties on the map. That's the typical sort of interaction that I think users would want to have with such an example...

**Comment by lhoupert** [comment]
@jbednar Do you know another bokeh sample datasets I cuold be using instead? 
I like this idea of showing all three columns in the table. Do you have a panel example where the highlighting with link_selections is done ?

**Comment by jbednar** [comment]
Unfortunately, I don't know of another Bokeh dataset that has per-county data, just this one. So Data2 and Data3 may be the best we can do, unless we bring in an external dataset. The http://holoviews.org/user_guide/Linked_Brushing.html shows linking with datasets that do have multi-column data, but unfortunately none of that makes sense to link with choropleths.
