### ISSUE TITLE
Is there a difference between pn.widgets.Progress and pn.indicators.Progress?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#1850]
It's shown twice in the ref gallery
```
import panel as pn
pn.widgets.Progress()
pn.indicators.Progress()
```

**Comment by julioasotodv** [comment]
IIRC the widgets version is deprecated. The indicators one is definately a brand new addition

**Comment by philippjfr** [comment]
Right, you should no import it via indicators. Docs need to be updated though.

**Comment by philippjfr** [comment]
They are actually the exact same object, deleting the reference gallery entry in #2451
