### ISSUE TITLE
tabs and buttons in dark mode 

### ISSUE THREAD

**Issue by sophiamyang** [holoviz/panel#1855]
tab and buttons don't look great in dark mode. Maybe they could be brighter? 
![image](https://user-images.githubusercontent.com/39501859/102665242-19baf400-414a-11eb-92a5-f569c8ba5ade.png)

**Comment by MarcSkovMadsen** [comment]
Hi @sophiamyang . 

The Panel templates with dark theme have not (yet) been styled in any way. That is something for the future. I  also think its needed.

I've done at lot of the work for the `FastTemplate` and `FastGridTemplate` at awesome-panel.org. You can use them via `pip install awesome-panel-extensions`  and `from awesome_panel_extensions.frameworks.fast.templates import FastTemplate, FastGridTemplate`.

**Comment by sophiamyang** [comment]
@MarcSkovMadsen Looks amazing. Thanks so much!
