### ISSUE TITLE
Enable setting the width of the sidebar for a template

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1857]
One of the things on my wish or todo list for templates is a parameter for setting the width of the sidebar. I can see other users needs that as well. See https://discourse.holoviz.org/t/width-of-template-sidebar/1594/3

**Comment by MarcSkovMadsen** [comment]
My experience from working with the templates is that they need  a second iteration: Cleaning up, improving the API, fixing bugs and align cross templates. I know this is not very specific right now :-)

**Comment by danwild** [comment]
Linking related things 
- https://github.com/holoviz/panel/issues/2223
- https://github.com/holoviz/panel/pull/2301

**Comment by MarcSkovMadsen** [comment]
Thanks @danwild. The customizable sidebar width has been implemented and merged to master https://github.com/holoviz/panel/pull/2301. Will be released with Panel v0.12.

I will close this one.
