### ISSUE TITLE
Not all resources are load/ found when using ipyvolume

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1858]
Panel 0.10.2

Was trying to help a user on discourse https://discourse.holoviz.org/t/pn-row-with-two-pn-pane-panes-showing-an-ipyvolume-is-shown-in-a-column-instead-how-to-fix/1598.

When I run the below code I can see that the icons in the ipyvolume menu is not shown and there are errors in the console.

![image](https://user-images.githubusercontent.com/42288570/102680984-c1bdd500-41bd-11eb-9d16-c81ddd49f44f.png)

```python
import panel as pn
import ipyvolume as ipv
import numpy as np

N = 1000
x, y, z = np.random.normal(0, 1, (3, N))

fig = ipv.figure()
scatter = ipv.scatter(x, y, z, color="#4464ad")
pn.Column(pn.pane.Markdown("## Panel meets IPyVolume"), pn.panel(fig, margin=50)).servable()
```

This is "friction" and some users might just leave because they would not know how to get it working.

**Comment by MarcSkovMadsen** [comment]
#### Workaround

A workaround for now is to import fontawesome you self. There are still errors in the console though.

```python
import panel as pn
import ipyvolume as ipv
import numpy as np
FONTAWESOME_LINK = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.css"
pn.config.css_files.append(FONTAWESOME_LINK)

N = 1000
x, y, z = np.random.normal(0, 1, (3, N))

fig = ipv.figure()
scatter = ipv.scatter(x, y, z, color="#4464ad")
pn.Column(pn.pane.Markdown("## Panel meets IPyVolume"), pn.panel(fig, margin=50)).servable()
```

![image](https://user-images.githubusercontent.com/42288570/102681005-fa5dae80-41bd-11eb-965e-491e4a1f46e4.png)

**Comment by MarcSkovMadsen** [comment]
#### Ipywidgets reference guide is also affected

https://panel.holoviz.org/reference/panes/IPyWidget.html

![image](https://user-images.githubusercontent.com/42288570/102681037-3e50b380-41be-11eb-9c66-f55f17e0b653.png)


![image](https://user-images.githubusercontent.com/42288570/102681044-4a3c7580-41be-11eb-9b2a-b787a0f296a6.png)

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/3299 by adding font-awesome by default when Ipywidget is added. The remaining font issues are known in ipywidgets_bokeh.
