### ISSUE TITLE
HTMLDataTemplate and MarkdownDataTemplate

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1860]
Sometimes you would like to make some nice *component* with unidirectional communication. You can do that it html with the `HTML` pane or in markdown with the `Markdown` pane. But what if you would like to update it. For example stream data to it.

An example could be a dashboard of kpi indicators. Here most of the `object` you would send would be static html and you would maybe just like to update a few values.

![image](https://user-images.githubusercontent.com/42288570/102705982-e4b7ba00-428d-11eb-8bbd-b1fb6a9b7612.png)

It would be really handy to define a string `template` and a `data` dictionary. Send both to the client. But then only update the data when needed.

```python
template = "<span>{{value}} USD</span><span style="color:red">{{value_percent}} %</span>"
data = {"value": 45, "value_percent": 87}
panel = pn.pane.HTMLDataTemplate(template=template, data=data)
```

**Comment by MarcSkovMadsen** [comment]
Here is an example of a template. I think the important thing to understand is what template language can/ should be used on the client side.

![image](https://user-images.githubusercontent.com/42288570/102706560-3747a500-4293-11eb-9c8b-ba49af828907.png)

**Comment by MarcSkovMadsen** [comment]
This is an example of a markdown template

![image](https://user-images.githubusercontent.com/42288570/102706751-de790c00-4294-11eb-8217-766e70fb3b9d.png)

**Comment by philippjfr** [comment]
This functionality is covered by `ReactiveHTML` components. If you want a better entry-point for that functionality (i.e. letting users use it without writing a class) please open a new issues with a suggestion on what you'd like the API for that to look like.
