### ISSUE TITLE
Add Stats Cards

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1861]
To make more BI like dashboards with Panel it would be nice to have some high performing stats cards similar to what H2O wave has.

Something that we could stream to if needed.

![dashboard2](https://user-images.githubusercontent.com/42288570/102706065-dfa73a80-428e-11eb-8dbc-27ec5eab7c7e.gif)

**Comment by philippjfr** [comment]
Definitely would love to see some more indicators, the Trend is great already but that circular one looks good too.
