### ISSUE TITLE
panel Slow response protocol exceptions protocol error token is expired

### ISSUE THREAD

**Issue by khannaum** [holoviz/panel#1871]
my internal network panel web application contain hvplot table and heatmaps segregated on different tabs using dynamic options  but on remote chrome the loading page response is slow with following detail .

I am running following below mentioned panel stand alone web application with following below mentioned commands

/usr/bin/nohup /home/NCOR6649/anaconda3/bin/panel serve main_cell_alm_anly.py --port 5050 --address xx.xx.xx.xx --allow-websocket-origin=‘xxxxx:5050’ --unused-session-lifetime 60000 --keep-alive 10000 --use-xheaders --num-procs 0 &

and we are getting below mentioned an error thrown when we access the page from chrome, then after we refresh button on chrome it began to appear with web socket open appear in logs

020-12-07 12:46:06,466 WebSocket connection opened
2020-12-07 12:48:42,426 ServerConnection created

### **Error:**

**_HTTPServerRequest(protocol='http', host='xx.xx.xx.xx:5050', method='GET', uri='/main_cell_alm_anly/ws', version='HTTP/1.1', remote_ip='xx.xx.xx.xx')
Traceback (most recent call last):
  File "/home/NCOR6649/anaconda3/lib/python3.7/site-packages/tornado/websocket.py", line 956, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/home/NCOR6649/anaconda3/lib/python3.7/site-packages/bokeh/server/views/ws.py", line 135, in open
raise ProtocolError("Token is expired.")
bokeh.protocol.exceptions.ProtocolError: Token is expired._**

### Web error###
![image](https://user-images.githubusercontent.com/7712413/102858346-ed55ef00-444b-11eb-999a-b5c860653f81.png)

**Comment by philippjfr** [comment]
How slow is it? The default session token expiration is 300 seconds, which seems like more than enough for any normal application.

**Comment by khannaum** [comment]
web app sitting inside  internal network.
user access web app via internet using vpn connection to internal network from their dsl/fibre connections

I have other pan web which does  not invlove tabs . it loads on user  browsers quite well  
 web app internal linux host is 5 minutes before the user standard time

But this web app with tabs halts after 3 minutes . it loads after 2 to three time reloads/refresh button
using chrome developer

 tools i have generated profile file attached for your review

**Comment by khannaum** [comment]
[Profile-20201223T113252.zip](https://github.com/holoviz/panel/files/5733723/Profile-20201223T113252.zip)

**Comment by khannaum** [comment]
also python script file  that generate panel web app also attached
[main_cell_alm_anly.txt](https://github.com/holoviz/panel/files/5733804/main_cell_alm_anly.txt)

**Comment by philippjfr** [comment]
@khannaum Sorry I haven't had time to look into this but the `--session-token-expiration` can already be set via the commandline and this is likely an issue with your application rather than Panel itself. For user questions post to https://discourse.holoviz.org/.
