### ISSUE TITLE
Radioboxgroup checkboxes stay the same size when zooming in firefox

### ISSUE THREAD

**Issue by pat-schmitt** [holoviz/panel#1879]
#### ALL software version info
panel 0.10.2
firefox 84.0
chrome 87.0.4280.88

#### Description of expected behavior and the observed behavior
When you zoom in/out into a panel app using the keys 'Ctrl' and '+/-' the checkboxes stay the same size when using firefox. This leads to a misalignment of the text and the checkboxes. When using for example chrome the checkboxes change their size with no misalignment with the text.

I am not sure if this is a panel or firefox problem, but I want to let you know.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension()

radio_group = pn.widgets.RadioBoxGroup(name='RadioBoxGroup',
                                       options=['Biology', 'Chemistry', 'Physics'],
                                       inline=True)
radio_group.show()

```

#### Screenshots or screencasts of the bug in action
Firefox:

![zooming_firefox_v84](https://user-images.githubusercontent.com/50843444/103365829-41eb1100-4ac1-11eb-8d76-9906e811ef6e.gif)

Chrome:

![zooming_chrome_v87](https://user-images.githubusercontent.com/50843444/103365837-4a434c00-4ac1-11eb-9fd5-d6b86b93d7f4.gif)

**Comment by philippjfr** [comment]
Thanks @pat-schmitt! Since Panel is built on Bokeh, this is likely an issue with the Bokeh widget itself so it would be good to file this on the [Bokeh issue tracker](https://github.com/bokeh/bokeh).

**Comment by MarcSkovMadsen** [comment]
Hi @pat-schmitt 

Did you file this with Bokeh? Thx.

**Comment by MarcSkovMadsen** [comment]
Closed because its a request for Bokeh.

**Comment by pat-schmitt** [comment]
Thanks @MarcSkovMadsen for the reminder, I just posted the issue on the Bokeh issue tracker: https://github.com/bokeh/bokeh/issues/10937
