### ISSUE TITLE
Add `value_input` parameter to all TextInputs

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1882]
I can see that the Bokeh `TextInput` supports the `value_input`

![image](https://user-images.githubusercontent.com/42288570/103527584-e2a34d00-4e82-11eb-9ea7-a514fa12917b.png)

A user needs this. See https://discourse.holoviz.org/t/catching-textinput-value-while-the-user-is-typing/1652/2.

Please add this to Panel.

**Comment by philippjfr** [comment]
Definitely should add this, should be as simple as defining the parameter on the relevant widget classes.

**Comment by MarcSkovMadsen** [comment]
It is that simple.
