### ISSUE TITLE
Upgrade Echarts to v5.0.

### ISSUE THREAD

**Issue by nghenzi** [holoviz/panel#1883]
#### Is your feature request related to a problem? Please describe.
Echarts 5.0 was just released and they have a lot of new gauges 

![image](https://user-images.githubusercontent.com/46707985/103539096-3491a600-4e76-11eb-940a-d29b3f5af207.png)

![image](https://user-images.githubusercontent.com/46707985/103542828-52620980-4e7c-11eb-8d69-a3f329068c48.png)

#### Describe the solution you'd like
It would be like to have all these gauges in panel. They already work using the js_files extensions and pn.pane.ECharts 

https://user-images.githubusercontent.com/46707985/103539659-3019bd00-4e77-11eb-9272-127d0326db83.mp4

```
import panel as pn
js_files = {'echarts5':"https://cdn.jsdelivr.net/npm/echarts@5.0.0/dist/echarts.min.js"}
pn.extension(js_files=js_files)

from functools import partial 

# echart = pn.pane.ECharts(data, width=500, height=500)
slider = pn.widgets.IntSlider(start=10, end=100, value=11,  step=1, sizing_mode='stretch_width')

@pn.depends(slider.param.value)
def get_pane(value):
    dat = {'series': [{'type': 'gauge',
   'startAngle': 90,
   'endAngle': -270,
   'pointer': {'show': False},
   'progress': {'show': True,
    'overlap': False,
    'roundCap': True,
    'clip': False,
    'itemStyle': {'borderWidth': 1, 'borderColor': '#464646'}},
   'axisLine': {'lineStyle': {'width': 25}},
   'splitLine': {'show': False, 'distance': 0, 'length': 6},
   'axisTick': {'show': False},
   'axisLabel': {'show': False, 'distance': 30},
   'data': [{'value': 20,
     'name': 'Perfect',
     'title': {'offsetCenter': ['0%', '-47%']},
     'detail': {'offsetCenter': ['0%', '-27%']}},
    {'value': 40,
     'name': 'Good',
     'title': {'offsetCenter': ['0%', '-3%']},
     'detail': {'offsetCenter': ['0%', '16%']}},
    {'value': 60,
     'name': 'Commonly',
     'title': {'offsetCenter': ['0%', '38%']},
     'detail': {'offsetCenter': ['0%', '58%']}}],
   'title': {'fontSize': 18},
   'detail': {'width': 30,
    'height': 12,
    'fontSize': 14,
    'color': 'auto',
    'borderColor': 'auto',
    'borderRadius': 13,
    'borderWidth': 1,
    'formatter': '{value}%'}}]}
    
    dat['series'][0]['data'][0]['value']= value
    dat['series'][0]['data'][1]['value']= value-5
    dat['series'][0]['data'][2]['value']= value-10
    print (value, dat)
    return pn.pane.ECharts(dat, width=300, height=250)    
# card = pn.depends(slider.param.value, watch=True)(partial(get_pane))

donut =  pn.Card(get_pane, title='donut', sizing_mode='stretch_both')

pn.Column(slider,donut).show()
```

#### Describe alternatives you've considered
As described in several topics in the discourse forum, all the functionalities of Echarts are not leveraged in panel. In some cases this can be solved  using pyecharts and its render.embed method, but it adds a lot of overhead to the app. 

#### Additional context
I was not able to use some functionality of echarts like JS functions (function {do something }) 
and echarts objects (new echarts.graphic.LinearGradient(0, 0, 0, 1, [{offset: 0, color: '#c86589'}, {offset: 1, color: '#06a7ff'}], false)) in the dict definition. I think it is because they can not be serialized, or maybe, I only don´t know how.  

Playing with echarts I was able to get this cards https://github.com/nghenzi/echarts_test/blob/master/stats_card.ipynb), as discussed in the gitter channel. As you can see below, it is not high performing, and it takes some time to respond when there is a lot of cards. 

https://user-images.githubusercontent.com/46707985/103542404-a28c9c00-4e7b-11eb-934a-25898925cde2.mp4

**Comment by MarcSkovMadsen** [comment]
Ahh. @nghenzi . I think we should communicate :-) I am interested in creating some stats cards for Panel (similar to what h2o wawe has). I was adviced to look into bokeh for stacklines but O can see you have solved it using ECharts. I would like to use these with streaming data. Do you know if they perform well? (updating 40 statscards every 1 sec).

**Comment by MarcSkovMadsen** [comment]
This is simple to update via the echarts.py file.

![image](https://user-images.githubusercontent.com/42288570/103637123-4a24cf80-4f4b-11eb-8dbc-9aa1f8019b2e.png)

**Comment by nghenzi** [comment]
> Ahh. @nghenzi . I think we should communicate :-) I am interested in creating some stats cards for Panel (similar to what h2o wawe has). I was adviced to look into bokeh for stacklines but can see you have solved it using ECharts. I would like to use these with streaming data. Do you know if they perform well? (updating 40 statscards every 1 sec).

They do not perform well by several things to be solved. In some cases I am using a html pane to render it due to some objects like the color gradients (new echarts.graphic.LinearGradient(0, 0, 0, 1, [{offset: 0, color: '#c86589'}, {offset: 1, color: '#06a7ff'}], false)) can not be used in the echarts pane. But I am trying to optimize it, as it should be perfomed so fast as a bokeh plot. When optimized, only one or two numbers should be sent by each card.  

I found this page (www.makeapie.com), where there is a lot of realy nice examples to increase the aspect of our dashboards. So I am firmly convinced that echarts is the way forward :) !

**Comment by nghenzi** [comment]
> Ahh. @nghenzi . I think we should communicate :-) I am interested in creating some stats cards for Panel (similar to what h2o wawe has). I was adviced to look into bokeh for stacklines but can see you have solved it using ECharts. I would like to use these with streaming data. Do you know if they perform well? (updating 40 statscards every 1 sec).

@MarcSkovMadsen 

I was sending all the echarts data to the frontend. Only sending the data it works ok for 60 cards with updates each second and a periodic callback. As you can see in the following video, when calculating the dummy data it keeps busy to the app, so a better approach was to use a thread like in the second video. In that case, you can update the cards each less than 250 ms

periodic_callback video 

https://user-images.githubusercontent.com/46707985/103784187-66db0900-5018-11eb-9601-0f4d5dd2382b.mp4


threading video

https://user-images.githubusercontent.com/46707985/103784222-722e3480-5018-11eb-81c7-c104ab53d982.mp4


I have to improve the cards yet, because their size is fixed. I am still figuring out the echarts implementation to due a responsive echarts object. Besides I want to be able to use the gradients, and the javascript functionthe echarts pane definition. 

The code for the tests is below.  A better benchmark would be nice to do. 

```
import panel as pn, numpy as np
js_files = {'echarts5':"https://cdn.jsdelivr.net/npm/echarts@5.0.0/dist/echarts.min.js"}
pn.extension(js_files=js_files)
import pyecharts.options as opts
from pyecharts.charts import Line, Grid
from pyecharts.commons.utils import JsCode
from bokeh.palettes import Category20c
Category20c[12]

x_data = ["14", "15", "16", "17", "18", "19", "20", "21", "22", "23"]
y_data = [393, 438, 485, 631, 689, 824, 987, 1000, 1100, 1200]

colors = Category20c[12]

# def get_color(color)
area_color_js = ("new echarts.graphic.LinearGradient(0, 0, 0, 1, "
    "[{offset: 0, color: '#eb64fb'}, {offset: 1, color: '#3fbbff0d'}], false)")

def get_color(color):
    return ("new echarts.graphic.LinearGradient(0, 0, 0, 1, "
    f"[{{offset: 0, color: '{color}'}}, {{offset: 1, color: '#3fbbff0d'}}], false)")


background_color_js = (
    "new echarts.graphic.LinearGradient(0, 0, 0, 1, "
    "[{offset: 0, color: '#c86589'}, {offset: 1, color: '#06a7ff'}], false)"
)


def gen_echarts(x_data, y_data,area_color_js, width='180px'):
    c= (Line( init_opts={'is_animation':False})
        .add_xaxis(xaxis_data=x_data)
        .add_yaxis(series_name="", y_axis=y_data, is_smooth=True,
            is_symbol_show=False, linestyle_opts=opts.LineStyleOpts(color="red"),
            label_opts=opts.LabelOpts(is_show=False, position="top", color="white"),
            itemstyle_opts=opts.ItemStyleOpts(color="red", border_color="#fff", border_width=3),
            tooltip_opts=opts.TooltipOpts(is_show=False),
            areastyle_opts=opts.AreaStyleOpts(color=JsCode(area_color_js), opacity=0.8),)
        .set_global_opts(
            xaxis_opts=opts.AxisOpts(
                type_="category",boundary_gap=False,
                axislabel_opts=opts.LabelOpts(is_show=False, margin=0, color="#ffffff63"),
                axisline_opts=opts.AxisLineOpts(is_show=False),
                axistick_opts=opts.AxisTickOpts( is_show=False, length=5,
                    linestyle_opts=opts.LineStyleOpts(color="#ffffff1f"),),
                splitline_opts=opts.SplitLineOpts(
                    is_show=False, linestyle_opts=opts.LineStyleOpts(color="#ffffff1f")),
                ),
            yaxis_opts=opts.AxisOpts(
                type_="value",boundary_gap=True,
                min_ = 0,
                max_= 1200,
                offset=180,
                position='inside',
                axislabel_opts=opts.LabelOpts(is_show=False,margin=0, color="#ffffff63",
                                             font_size=0, distance=0, border_width=0),
                axisline_opts=opts.AxisLineOpts(
                    linestyle_opts=opts.LineStyleOpts(is_show=False, width=0, color="#fff")),
                axistick_opts=opts.AxisTickOpts(is_show=False),
                splitline_opts=opts.SplitLineOpts(
                    is_show=False, linestyle_opts=opts.LineStyleOpts(color="#ffffff1f")
                ),
            ),
            legend_opts=opts.LegendOpts(is_show=False),
        )
    )

    g = (
        Grid(init_opts=opts.InitOpts(width=width, height="120px"))
        .add(
            c,
            grid_opts=opts.GridOpts(
                pos_top="0%",
                pos_left="0%",
                pos_right="0%",
                pos_bottom="0%",
                is_contain_label=True,
            ),
        )
    )
    return g.render_embed()

number = pn.indicators.Number(
    name='', value=72, format='{value}%',
    colors=[(33, 'green'), (66, 'gold'), (100, 'red')]
)

number.font_size = '18pt'
number.title_size = '23pt'



tmpl = pn.template.ReactTemplate(title='Cards')
tmpl.row_height= 210 
tmpl.compact = 'both'


# dicts to manage the 60 cardss
cal = {}
dat = {}
div_ids = {}

for row in range(5):
    dat[row] = {}
    cal[row] = {}
    div_ids[row] = {}
    for col in range(12):
        dat[row][col] = gen_echarts(x_data, y_data,get_color(colors[col]),'150px')
        idx = (dat[row][col].find('id="'))
        div_ids[row][col] = dat[row][col][idx:idx+40].split("\"")[1]
        cal[row][col] = pn.Column(number, pn.pane.HTML(dat[row][col]))
        tmpl.main[row,col:col+1] = pn.Card(cal[row][col],title='Failure Rate', width=160, height=210)

# identifiers of each card
ids = sorted({x for v in div_ids.values() for x in v.values()}) 

#dummy html to send the javascript string actualization of all the charts

js_code = pn.pane.HTML("")
tmpl.header.append(js_code)

import string, random
N=16

################# periodic callback ##############################

# def update_cards():
#     code = ""
#     random_string = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(N))
#     for idie in ids[::]:
#         ygen = list(np.random.randint(1, high=1000, size=12))
#         code += f"""option_{idie}.series[0].data = {list(map(list, zip(x_data, ygen)))};\n"""
#         code += f"""chart_{idie}.setOption(option_{idie});\n"""

#     js_code.object= "<script>" + code + f"console.log('{random_string}');\n</script>"    
#     js_code.param.trigger('object')    
    
# pn.state.add_periodic_callback(update_cards, 1000)


################# threading ##############################
from threading import Thread # Asyncio
from functools import partial
import asyncio 

@asyncio.coroutine
def update(js_code, code):
    js_code.object= code
    js_code.param.trigger('object')   
 

def blocking_task(doc, js_code):
    print ('beginning')
    for i in range(1000): 
        code = ""
        random_string = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(N))
        for idie in ids[::]:
            ygen = list(np.random.randint(1, high=1000, size=12))
            code += f"""option_{idie}.series[0].data = {list(map(list, zip(x_data, ygen)))};\n"""
            code += f"""chart_{idie}.setOption(option_{idie});\n"""
        # update the document from callback
        code = "<script>" + code + f"console.log('{random_string}');\n</script>"  
        if doc:
            doc.add_next_tick_callback(partial(update,js_code = js_code, code=code))
        else:
            print('if not working', i)
     
def button_click(event):
    thread = Thread(target=partial(blocking_task, doc=pn.state.curdoc, js_code = js_code))
    thread.start()
    
btn = pn.widgets.Button(name='Run')    
btn.on_click(button_click)

tmpl.header.append(btn)


tmpl.show()
```

**Comment by MarcSkovMadsen** [comment]
@nghenzi . I tried the period callback version with `pn.state.add_periodic_callback(update_cards, 25)`

It actually performed really nice and the server did not spend much effort on this.

![image](https://user-images.githubusercontent.com/42288570/103930046-70e72f80-511e-11eb-8dfd-e9ca41225927.png)
