### ISSUE TITLE
pn.Accordion: click on a Card 

### ISSUE THREAD

**Issue by thuydotm** [holoviz/panel#1884]
#### ALL software version info
panel 0.10.0, Google Chrome browser

#### Description of expected behavior and the observed behavior
When click to open/close a Card, it jumps to the top of the page regardless of the position of the Card. In the example below, I add some mock cards, then scroll down and click on card Filter 25 and it jumps back to the top, the card opened/closed as expected though.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension()

n = 30

filters = pn.Column(sizing_mode='stretch_width', margin=0)
filters[:] = [
    pn.Row(
        '#### Filters',
    ),
    pn.layout.Divider(),
    pn.Accordion(
        *[('Filter ' + str(i), 'Filter ' + str(i)) for i in range(1, n)]
    )
]

tmpl = pn.template.MaterialTemplate()
tmpl.main.append(filters)
tmpl.servable()
```
#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/47617499/103545385-122e7580-4ed4-11eb-935b-cf35a4677ea4.png)

**Comment by ahuang11** [comment]
Same with card https://github.com/holoviz/panel/issues/1833
