### ISSUE TITLE
panel state location not fully initialized

### ISSUE THREAD

**Issue by WesleyTheGeolien** [holoviz/panel#1888]
#### ALL software version info
panel: 0.10.2

#### Description of expected behavior and the observed behavior
When using `panel.state.location` it appears that there are a number of attributes on the class that are not instantiated, notably:

- href
- hostname
- pathname
- protocol
- port
- hash

`search` is instantiated and `reload` has a default value.

There is access to the bokeh Document through `panel.state.curdoc` I wonder if we could use this to gain access to the attribute  values?

It looks like `pathname` is available through: `panel.state.curdoc.session_context.server_context.application_context.url`

#### Complete, minimal, self-contained example code that reproduces the issue

From the [example](https://panel.holoviz.org/gallery/simple/sync_location.html#simple-gallery-sync-location) with modification to print the attributes.

Run with `python -m panel serve sync.py` and navigate to http://localhost:5006 to see the printed results in the console

```
# sync.py
import panel as pn

widget = pn.widgets.FloatSlider(name='Slider', start=0, end=10)
widget2 = pn.widgets.TextInput(name='Text')
widget3 = pn.widgets.RangeSlider(name='RangeSlider', start=0, end=10)

if pn.state.location:
    pn.state.location.sync(widget, {'value': 'slider_value'})
    pn.state.location.sync(widget2, {'value': 'text_value'})
    pn.state.location.sync(widget3, {'value': 'range_value'})

for par in ['href', 'hostname', 'pathname', 'protocol', 'port', 'search', 'hash', 'reload']:
    print(par, ': ', getattr(pn.state.location, par))
pn.Row(widget, widget2, widget3).servable()

```

#### Stack traceback and/or browser JavaScript console output
```
href :  
hostname :  
pathname :  
protocol :  
port :  
search :  ?slider_value=0&range_value=%5B0%2C+10%5D
hash :  
reload :  False
```

**Comment by philippjfr** [comment]
They are not (and cannot be) initialized until the app is fully loaded. So if you want to respond to access one of these attributes you have to do so in a `pn.state.onload` callback or specifically attach a callback to a location parameter using `pn.state.location.param.watch(callback, 'href')` (for example).

**Comment by philippjfr** [comment]
Suggestions for improving the docs on this very welcome.

**Comment by WesleyTheGeolien** [comment]
Are these attributes ever set then? Would something similar to the `current_app` in flask work? No idea on the mechanics behind that though ...

A bit more digging reveals that `panel.state.curdoc.session_context.request._request` holds a bunch of information: `HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/sync', version='HTTP/1.1', remote_ip='127.0.0.1')` I do notice here though that not all those value are correct. ( I am running panel on `localhost:5006` but using `bokeh.embed.server_document` inside a flask app ...

**Comment by philippjfr** [comment]
Yes, they are set as soon as the application is rendered on the frontend. The `request` is a very different thing from the `location` and can currently be accessed as `pn.state.curdoc.session_context.request`.

**Comment by philippjfr** [comment]
Ah, sorry, should have read your whole comment. Which values specifically are wrong?

**Comment by philippjfr** [comment]
Okay, I guess I can see the issue. I don't think there's an easy way for Bokeh/Panel to know about the Flask app wrapping it. Let's continue the discussion on the [Discourse](https://discourse.holoviz.org/).
