### ISSUE TITLE
Bug ? Serve static files in the source of the page with pn.serve()

### ISSUE THREAD

**Issue by GilShoshan94** [holoviz/panel#1902]
Hi, I love Panel and want to use it more. Amazing product with  an amazing community.
Disclaimer: I'm a newbie in web technology, until last week I did not know anything about JS, CSS, HTML nor browser and the DOM. 
Hope I did not miss an obvious solution.

#### Is your feature request related to a problem? Please describe.

I am using Panel to build a dashboard, but I want to customize it and also need to serve it locally. It should work without internet access as well. So I need to serve the files like Panel does with its `static` folder.

The HTML pane is great to quickly implement and serve non standard pane. I am using CSS styling and JavaScript. I would like to use custom font as well. And also use an icon library such as `Font Awesome` (like explained https://www.w3schools.com/css/css_icons.asp). 

#### Describe the solution you'd like

A function `pn.config.add_static_folder(map)` where the argument `map` would be dictionary mapping directory name that will be served in the Sources and the path to the local directory.
For example: `pn.config.add_static_folder({"custom_static" : "C:\\Users\\Gil\\myproject\\custom_static"})`.

(Here I wrote the path fully but I actually use [Path from pathlib](https://docs.python.org/3/library/pathlib.html), would be nicer the use this instead of a str. Just cast it to str (str(Path)) in the function.)

Also the function should append the folder so users can add several folders if they wish ("custom_static1", "custom_static2", ...), and have a simple check the "static" name is not permitted as it is already taken for Panel's internal use.

#### Describe alternatives you've considered
I used `pn.config.js_files` and `pn.config.css_files` with `pn.serve(..., static_dirs={"custom_static": str(custom_static)}, ...)`. I also tried `extra_patterns=[(r"/custom_static/(.*)", StaticFileHandler, {"path": custom_static})]` in `pn.serve()`.

I read a lot of the code of Panel IO and then Bokeh and the Tornado. It is really complicated for me as I never learned before any web tech. Just very recently learn some CSS, HTML and JavaScript.

I succeeded so far to only add the JS files. I paid attention that the CSS is getting put immediately inside the HTML (index) generated by Panel inside the <head> in <script>. I also paid attention that PNG pane does not point to an image file upload as static resource but instead is converted as a very long data encoded string (which is pretty cool), I would like to have the image as a file for reusability. (And PNG pane should have the option to use a link internally : `<img src="custom_static/mylogo.png" />`)

For the CSS, I like that you can add it as ["Internal CSS" which can override "external CSS"](https://www.w3schools.com/css/css_howto.asp). It let me override Panel/Bokeh default styling to customize to my needs. But I would like to have also the possibility to include it as external CSS. So maybe add a method `pn.config.add_internal_css(css_file_path)` ?

#### Additional context
I succeed to add only my JS file in a custom_static file.
I would like to add more files like Panel does for itself.
![image](https://user-images.githubusercontent.com/29143941/104449954-b16ffe80-559f-11eb-9c09-f64b074a90fe.png)

You can see Panel can use a <link> to external CSS, while my CSS is only internal in a <style>.
![image](https://user-images.githubusercontent.com/29143941/104450259-1cb9d080-55a0-11eb-9b91-851a8868fed7.png)

#### Additional Note
A one page tutorial addressed to the people who want to style further to use the browser DevTools (`F12` on Chrome) to explore the classes used by each panel and to override them whit internal CSS would be a great addition to the amazing documention of Panel and Holoviz in general.

**Comment by GilShoshan94** [comment]
I forgot to mention, I also search in the Discourse. 
Found @MarcSkovMadsen question: https://discourse.holoviz.org/t/how-do-i-serve-a-folder-of-static-assets-like-sphinx-documentation-at-docs-with-panel-serve/554

I tried the solution @philippjfr  suggested with the `extra_patterns` and `StaticFileHandler` but without success.

**Comment by philippjfr** [comment]
This is already supported have a look at the Static File Hosting section [here](https://panel.holoviz.org/user_guide/Deploy_and_Export.html#static-file-hosting).

**Comment by philippjfr** [comment]
I like your suggestion for doing this programmatically with `pn.config.add_static_folder(map)` but that sadly cannot be supported since by the time any code is executed the server is already running and all the routes are already set up.

I'm going to close this issue but if you run into problems please reopen.

**Comment by GilShoshan94** [comment]
Hi @philippjfr ,

Thanks for your answer, I believe I did read the whole [Panel documention](https://panel.holoviz.org/index.html).
I carefully read the Deploy and Export (https://panel.holoviz.org/user_guide/Deploy_and_Export.html#static-file-hosting) guide.

I perfectly understand that the static resources needed to be defined before the server is already running and all the routes are already set up.
I was not suggesting adding them programmatically by after.

While I admit I don't use the command line `panel serve …`, I do use from my python program `pn.serve(panel_obj, static_dirs={'assets': './assets'}) `. 
But for me at least, I see that the only files that are being added from this static_dirs ('assets' in the example) are JS files. So I concluded it was on purpose like that and open a feature request.

Now that I think off it, maybe it is a bug ? 
Should all the subfolders and files in the static_dirs ('assets' in the example) be added in the Sources ? 
If so I than let you know that it does not work for me as it only find the JS files.

I prepared a minimal test for you in a zip file 
[minimal.zip](https://github.com/holoviz/panel/files/5809939/minimal.zip)

It contains one script called myapp.py and one directory called custom_static
![image](https://user-images.githubusercontent.com/29143941/104481520-2d7d3d00-55c6-11eb-968f-69cbb7693a61.png)

and in the custom_static dir you have a css file, a js dir with one js file and one img dir with the Panel logo as a png file.
![image](https://user-images.githubusercontent.com/29143941/104481720-67e6da00-55c6-11eb-9880-e77f0e8bff8b.png)

I use in the script myapp.py `pn.serve(..., static_dirs={...})`
![image](https://user-images.githubusercontent.com/29143941/104482000-b4cab080-55c6-11eb-813f-8d03a6153ef4.png)

And I don't see the any Static File Hosting working....
![image](https://user-images.githubusercontent.com/29143941/104483524-8057f400-55c8-11eb-9cd0-814df707e6c8.png)

Only when I add in the `pn.config.js_files` a dict pointing to the js file than only the js file is added. (you can uncomment the lines 21,22 and 23 in the minimal example to see it)
![image](https://user-images.githubusercontent.com/29143941/104483846-dc227d00-55c8-11eb-96fb-fdd398bd16b1.png)

**Comment by GilShoshan94** [comment]
> I like your suggestion for doing this programmatically with `pn.config.add_static_folder(map)` but that sadly cannot be supported since by the time any code is executed the server is already running and all the routes are already set up.
> 
> I'm going to close this issue but if you run into problems please reopen.

@philippjfr  I can't reopen the issue because you closed it. Can you do it please ?
"you cannot re-open your own issues if a repo collaborator closed them."

**Comment by philippjfr** [comment]
How are you running the application? When I launch your example with `python myapp.py` I can access the static files just fine at `
http://localhost:12345/custom_static/dashboard_style.css`. I guess you're assuming that all files in the static assets will somehow be loaded automatically by the page? 

That's definitely not how it's intended and I don't think that's particularly desirable behavior. You have to make sure yourself that the template (or your app code) loads all the resources, e.g. by adding it to `pn.config.js_files` and `pn.config.css_files` or by using a custom template.

**Comment by GilShoshan94** [comment]
I confirm that I can access the static files just fine at `http://localhost:12345/custom_static/dashboard_style.css` even the image at `http://localhost:12345/custom_static/img/logo_horizontal.png`.

I remind you that I am very new to web and browser tech. 
So from your answer I deduce that what I see in the `Sources` is only the assets that got loaded. Thank you so much !
It works perfectly than.

I just tried to add the image with
```python
pic = pn.pane.HTML()
pic.object = f"""<img src="custom_static/img/logo_horizontal.png" alt="Girl in a jacket" width="500" height="600">"""
```
and it worked. It loaded and got added to the Sources.

Thank you so much for your time and sorry for the stupid question.
I am closing the issue.

**Comment by philippjfr** [comment]
Glad it's all working for you. You seem to be figuring things out in record speed, so keep asking questions. It's a pleasure when they are so well crafted as this issue was. Our discourse at discourse.holoviz.org is a good place for usage questions and if we'd really appreciate it if you showcased what you are building.

**Comment by GilShoshan94** [comment]
I just open an account at discourse.holoviz.org 
I am still far to showcase but I did contribute a special "logviewer" pane here : 
Scrollable log text viewer - implementation #1904

Should I had post that in the discourse instead ? 
I thought it was general enough to be a nice feature request.
