### ISSUE TITLE
Difficulty with HTML pane

### ISSUE THREAD

**Issue by miliante** [holoviz/panel#1914]
I want to have som interaction in my panel, so as a test, I am trying to implement the [terminal.js](https://github.com/eosterberg/terminaljs).

I have dcreated acopy of PlotylyPlot and adapted everything so i can load the javascript with : pn.extensions('terminal').
So far so good and it loads properly. I included the example from give in test.html within a pn.pane.HTML.

```
html_pane = pn.pane.HTML("""
<script>
	var t1 = new Terminal()
	t1.setHeight("200px")
	t1.setWidth('600px')
	document.body.appendChild(t1.html)

	t1.print('Hello, world!')
	t1.input('Whats your name?', function (input) {
		t1.print('Welcome, ' + input)
	})
</script>
""")
```

To my surprise it actually worked, but the terminal is not showing where it should within main-content. I am awfull with html and css. Did I miss something ?

![2021-01-18 10_39_53-Clipboard](https://user-images.githubusercontent.com/18443314/104898183-8f98c200-5979-11eb-86fd-2aafb915cc2c.png)

**Comment by MarcSkovMadsen** [comment]
Hi @miliante 

I believe the problem is that you `document.body.appendChild(t1.html)`. I.e. you append the terminal to the `body` of the html document and outside anything that Panel controls.

Try inserting a `div` element into the `pn.pane. HTML` that the terminal can be appended to. Something like

```html
<div id="terminal-1"></div>
<script>
	var t1 = new Terminal()
	t1.setHeight("100%")
	t1.setWidth('100%')

    el = document.getElementById("terminal-1")
    el.appendChild(t1.html)

	t1.print('Hello, world!')
	t1.input('Whats your name?', function (input) {
		t1.print('Welcome, ' + input)
	})
</script>
```

**Comment by philippjfr** [comment]
@miliante Issues should be reserved for actual bugs or feature requests in the library, for support questions please post to our [discourse](https://discourse.holoviz.org/c/panel/5). Just this once I'll answer here though, you don't want to append to the `document.body` you'll want to create a div you can append to.

```
html_pane = pn.pane.HTML("""
<div id="terminal"></div>
<script>
	var t1 = new Terminal()
	t1.setHeight("200px")
	t1.setWidth('600px')
	document.getElementById('terminal').appendChild(t1.html)

	t1.print('Hello, world!')
	t1.input('Whats your name?', function (input) {
		t1.print('Welcome, ' + input)
	})
</script>
""")
```

**Comment by MarcSkovMadsen** [comment]
I'm a little bit interested in this use case and I can see that are many js terminals out there. For example https://xtermjs.org/. Why did you settle on terminaljs @miliante ?

**Comment by miliante** [comment]
Thank you for your replies. 

Sorry, I didn't know there was a discourse forum. Perhaps there are many solutions to my questions there. I am rather new to GitHub and I had to read a bit on how to do a pull request yesterday. Baby steps. I only program to simplify my life at work :)

@MarcSkovMadsen xtermjs seems indeed to be the most complete and the ideal candidate, but i picked this one because it was the most simple to implement. In my case I don't need a full terminal emulation as I only need a few commands to control my runs and some output.

**Comment by philippjfr** [comment]
>Sorry, I didn't know there was a discourse forum. 

No problem at all, just for future reference.

> I am rather new to GitHub and I had to read a bit on how to do a pull request yesterday. Baby steps.

Congrats! Really appreciate you contributing back.

>@MarcSkovMadsen xtermjs seems indeed to be the most complete and the ideal candidate, but i picked this one because it was the most simple to implement.

A fully fleshed out terminal component based on xtermjs would be great actually. Mind opening an issue as a feature request?
