### ISSUE TITLE
The "Getting Started" page is not helpful or up to date

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1924]
I am trying to help this user who cannot get started with Panel https://discourse.holoviz.org/t/panel-plots-are-not-updating-from-widget-inputs/1739/2.

Looking at the Getting Started documentation I see many issues

- It is stated that Panel works with Python 2.7.
- It tells the user to install `pyviz`. As far as I understand that is problematic and not that well supported.
- It tells the user to install the jupyter lab extension manually. Which is no longer required with jupyterlab 3.0.
- There is a link to the "outdated" announcing blog.

Furthermore there are no instructions on how to get a working setup locally of "Notebooks + Assets" making it very difficult to get started.

If you right click and download as stated on the right I'm pretty sure you don't download the assets. The links to the assets are relative and not to some absolute url.

![image](https://user-images.githubusercontent.com/42288570/104991869-07b9c300-5a20-11eb-898a-ceb4e5967291.png)

**Comment by jbednar** [comment]
Those sound like valid complaints, except:
- It's not telling anyone to install `pyviz`; `-c pyviz` just means to fetch panel from the `pyviz` conda channel, which is the correct way to ensure that you have the latest version of panel. (Without that, you'll get whatever is on the main conda channels, which is often the same as on `pyviz` but is out of our control and not updated as part of our own release process.)
- The jupyterlab extension instructions are still needed for any jupyterlab2 users, and shouldn't hurt for jlab3 users. It will be a while before we can assume that jlab == jlab3.
- Do you have a suggestion for how to handle static assets? We provide `panel examples` for fetching them all as a group, with all assets, but to me it still seems useful to let people download individual pages as notebooks, even some of the files needed won't be available. We could add warnings that some files might not be available, but I think that would be confusing to try to explain. So are you arguing that we shouldn't let people download individual .ipynb files?

**Comment by MarcSkovMadsen** [comment]
The primary problem as i see it is that there are no instruktions for installing the example notebooks with assets locally.

**Comment by jbednar** [comment]
I'll leave that up to @philippjfr ; our other projects do have such instructions (e.g. http://holoviews.org/index.html#usage), and I'm not sure whether their absence here was deliberate.

**Comment by MarcSkovMadsen** [comment]
I've promised to update this.

**Comment by luk-f-a** [comment]
on the topic of problems with "Getting Started", this page http://archive.ics.uci.edu/ml/datasets/Occupancy+Detection+ does not seem to contain any `occupancy.csv` file. Did I miss it?

**Comment by philippjfr** [comment]
At the top, the "data folder" link.

**Comment by luk-f-a** [comment]
hi @philippjfr , thanks for the fast reply. data folder contains `occupancy_data.zip` which contains `datatest.txt`, `datatest2.txt` and `datatraining.txt`. I cannot find occupancy.csv anywhere.

**Comment by philippjfr** [comment]
Ah, sorry thought you wanted to know where the raw data came from. The occupancy.csv is shipped in the Panel repo: https://github.com/holoviz/panel/tree/master/examples/assets

**Comment by luk-f-a** [comment]
I see, thanks.

**Comment by jbednar** [comment]
And it's installed when you install the panel examples using the command `panel examples` as listed in the [Getting Started section](https://panel.holoviz.org/index.html#id1). But I've reopened this issue because the [Getting Started *page*](https://panel.holoviz.org/getting_started/index.html) doesn't seem to list that requirement.

**Comment by philippjfr** [comment]
There are now numerous other issues about overhauling the current version of the getting started guide which is already quite different from the one this issue was originally filed about.
