### ISSUE TITLE
Terminal component

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1925]
A Terminal Component for Panel would be nice to have.

![image](https://user-images.githubusercontent.com/42288570/104992394-3f753a80-5a21-11eb-9232-639b67bfcea9.png)

There are many terminal components that could be used. See for example

- [Top 5 Terminal Components](https://ourcodeworld.com/articles/read/292/top-5-best-terminal-console-emulator-plugins-for-javascript-and-jquery)
- [React Terminal Component](https://github.com/rohanchandra/react-terminal-component)
- [XTerm.js](https://xtermjs.org/)
- [TerminalJS](http://www.erikosterberg.com/terminaljs/)

@philippjfr stated he would like an XTerm implementation for Panel and asked me to create this FR based on discussions in https://github.com/holoviz/panel/issues/1914

**Comment by MarcSkovMadsen** [comment]
## Related Issues

- https://github.com/holoviz/panel/issues/1978
- https://github.com/holoviz/panel/issues/1904

## Use Cases

- Capturing stdout/ stderr from your Panel Application
- Running processes in the terminal
    - For example I am trying to create a pipeline for my "daily routine operations". This includes running `kubectl` (kubernetes cli) in the command line. Some of the output I just need to inspect. Some of the output I need to respond to. Like saying yes/ no. Or opening a hyperlink to enter a username and password. Some output I need to transform into a color styled table that indicates where the problems are (if any).
- Creating true terminal experiences where you are connecting `bash`, `python` cli or `ipython cli` to the front end.
- Interactive Bots or Games.

**Comment by philippjfr** [comment]
An xterm.js based Terminal widget has been merged.
