### ISSUE TITLE
Replace DefaultTheme name with LightTheme name

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1935]
From using the templates I have noticed that the `DefaultTheme` is always the light theme. The `Default` theme does not have to be light I think.

In order to be able to mix and match templates in a site like awesome-panel.org it would be nice if the naming convention was more specific. I think there should be `LightTheme`, `DarkTheme` and maybe even more. And then one of these is the `default_theme`.

To me that would be the right/ logical/ consistent API.

**Comment by philippjfr** [comment]
Personally I'm -1 on this. The `DefaultTheme` makes minimal modifications to the default Bokeh CSS and Theming, which happens to be light by default (and that will not change at this point). I'd be happy to see a "cleaner" `LightTheme` to be added but do not think we should change the `DefaultTheme` at this point.

**Comment by MarcSkovMadsen** [comment]
The argument for me is that for Fast framework the default theme is dark. Not for Panel but for the framework it self. So for me it would be natural that also in Panel the default theme is dark. But then it's a problem when and if users see the DefaultTheme as light by default.

**Comment by MarcSkovMadsen** [comment]
I understand that there might be higher priorities. But I just see the current state as "technical debt". Something that will come back and bite later.

**Comment by MarcSkovMadsen** [comment]
Closed as there is not much support here :-)
