### ISSUE TITLE
param.trigger does not update the clicks in a button

### ISSUE THREAD

**Issue by ItamarShDev** [holoviz/panel#1944]
param.trigger does not update the clicks in a button

![image](https://user-images.githubusercontent.com/953371/105852160-c52e5280-5fec-11eb-9eb7-5916c6013bc0.png)

**Comment by philippjfr** [comment]
Thanks @ItamarShDev. Honestly, it's somewhat debatable whether this is a bug. If the event wasn't fired I think it would be a bug but since it does this seems like arguably the correct behavior. If you want to trigger an event an increment clicks you can just do `button.clicks += 1`.
