### ISSUE TITLE
display 2 pn.pane.VTKVolume() in the same render window

### ISSUE THREAD

**Issue by mel21122** [holoviz/panel#1945]

**Comment by philippjfr** [comment]
Apologies, didn't get to this in time. Did you figure out what you needed?

**Comment by mel21122** [comment]
No worries!
Unfortunately, I didn't figure it out. I displayed my volumes in 2 different windows.

**Comment by xavArtley** [comment]
VTKVolume allows only to work on 1 volume at a time.

**Comment by mel21122** [comment]
Ok, thank you! :)
