### ISSUE TITLE
Template : Title block is ignored

### ISSUE THREAD

**Issue by GilShoshan94** [holoviz/panel#1947]
Hi,

This issue will certainly interest @MarcSkovMadsen as he touched it in the discourse: https://discourse.holoviz.org/t/how-do-i-set-the-app-title-with-panel-serve/550

#### ALL software version info
Python : 3.8.6
Panel: 0.10.2
browser : Chrome 88

#### Description of expected behavior and the observed behavior
According to the tutorial "Templates" (https://panel.holoviz.org/user_guide/Templates.html), the **base template** has a block `title`:
```html
…
<title>{% block title %}{{ title | e if title else "Panel App" }}{% endblock %}</title>
…
```

I am using `pn.Template` with a Jinja2 html file I wrote and wanted to set the title with the help of the `.add_variable()` method.
While in the very first instant the new tab appears in the browser, the title get correctly display with my custom title, it then very quickly gets overwritten with the default "Panel App" (and stays like that).  

It's not a huge bug as I still have the regular way to set the title by passing my title in the `pn.serve()` call.
But it is not the behavior I expected from what I read in the documentation.

#### Complete, minimal, self-contained example code that reproduces the issue
(It's not the most minimal as I just copied the basic example given in the documentation, but added the `block title`)

```
import holoviews as hv
import panel as pn

template = """
{% extends base %}

{% block title %}
{{ mytitle | e }}
{% endblock %}

{% block postamble %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
{% endblock %}

<!-- goes in body -->
{% block contents %}
{{ app_text }}
<p>This is a Panel app with a custom template allowing us to compose multiple Panel objects into a single HTML document.</p>
<br>
<div class="container">
  <div class="row">
    <div class="col-sm">
      {{ embed(roots.A) }}
    </div>
    <div class="col-sm">
      {{ embed(roots.B) }}
    </div>
  </div>
</div>
{% endblock %}
"""

tmpl = pn.Template(template)

tmpl.add_variable("app_text", "<h1>Custom Template App</h1>")
tmpl.add_variable("mytitle", "My test title")

tmpl.add_panel("A", hv.Curve([1, 2, 3]))
tmpl.add_panel("B", hv.Curve([1, 2, 3]))

if __name__ == "__main__":

    try:
        import time

        server = pn.serve(tmpl, port=12345, threaded=True)
        while True:
            time.sleep(10)

    except Exception as e:
        print(e)
    finally:
        # stop the bokeh server (when needed)
        server.stop()
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/29143941/106069641-8ba03900-610b-11eb-8c9e-3de296743917.png)
Should have been "My test title"

### My conclusion ###
It's a transient behavior that occurs when the page is loading.

My web knowledge is pretty weak (I am learning), so it could be the Python backend that make the change but maybe it is the JavaScript that runs once the page is ready, the last <script> element :
![image](https://user-images.githubusercontent.com/29143941/106070066-6bbd4500-610c-11eb-86bb-7523164d930d.png)

I remarked that in the `fn` function you have in the `var render_items` dictionary, you have this item : `"use_for_title":true` (last key after `token`)
![image](https://user-images.githubusercontent.com/29143941/106070869-ed61a280-610d-11eb-807b-0db6e5369f08.png)

Maybe it is linked to the title issue ?

**Comment by philippjfr** [comment]
@GilShoshan94 Yes, I think you got that right, the `use_for_title` option is probably at fault here. Unfortunately it's pretty deeply burried in bokeh so it'll be hard to override.

**Comment by GilShoshan94** [comment]
@philippjfr 
Here is my findings:

I am trying to research how it works for the prebuild template (the classes that inherit from `BasicTemplate` like `GoldenTemplate`)..
There what I see is that the title is set in Python in the `_init_doc` method on the `doc` object: 
(In `panel/template/base.py`)
```python
def _init_doc(self, doc=None, comm=None, title=None, notebook=False, location=True):
        doc = doc or _curdoc()
        title = title or 'Panel Application'
        if location and self.location:
            loc = self._add_location(doc, location)
            doc.on_session_destroyed(loc._server_destroy)
        doc.title = title
        ...
```

Which is not what we are trying to do since we are trying to set the title on the Jinja template itself (in the `{% block title %}`).
So it has to be the JS code that override the title. After a quick Google search, (I don't know well web technologies) I found that `document.title` let you access the <title> element et manipulate it (including to override it).

So I search in Panel and Bokeh and found that only in bokeh seems relevant here.

I searched : `org:bokeh use_for_title` and `org:bokeh document.title` in GitHub.


I found this code that seems relevant in `bokehjs/src/lib/embed/standalone.ts`
```typescript
  ...
  if (use_for_title)
    window.document.title = document.title()

  document.on_change((event: DocumentChangedEvent): void => {
    if (event instanceof RootAddedEvent)
      render_model(event.model)
    else if (event instanceof RootRemovedEvent)
      unrender_model(event.model)
    else if (use_for_title && event instanceof TitleChangedEvent)
      window.document.title = event.title
  })
```

I didn't understood what the function document.title() return but I do see an assignment, so maybe if we can set `use_for_title` it will work as intended ?

I see also that a `TitleChangedEvent` can be trigger and cause to override the title but only if `use_for_title` is True.

I dug more into both libraries, and I have to admit that I have hard time to follow (especially on how work the interface Python and TypeScript / JavaScript) also because it's a huge codebase for me alone (wonderful by the way, I am learning a lot).
It seems that the 'title' attribute of the Python 'document' is important. And so if I don't set it in Python, Bokeh don't seem to like it.

Anyway I continued to search and found this in `bokeh/embed/server.py` : 
```python
def server_html_page_for_session(session, resources, title, template=FILE, template_variables=None):
    '''
    Args:
        session (ServerSession) :
        resources (Resources) :
        title (str) :
        template (Template) :
        template_variables (dict) :
    Returns:
        str
    '''
    render_item = RenderItem(
        token = session.token,
        roots = session.document.roots,
        use_for_title = True,
    )

    if template_variables is None:
        template_variables = {}

    bundle = bundle_for_objs_and_resources(None, resources)
    html = html_page_for_render_items(bundle, {}, [render_item], title,
        template=template, template_variables=template_variables)
    return html
```
Which is the only place I could find (in both Panel and Bokeh) where `use_for_title` is set to True.

And 'server_html_page_for_session' is itself only called in the class `DocHandler` (in `bokeh/server/views/doc_handler.py`).
`DocHandler` is itself use in the list of tuple `per_app_patterns` by `bokeh.server.tornado.BokehTornado` according to the documentation in `bokeh/server/urls.py`

And in `BokehTornado`, I kinda lost it but to my understanding it configure Tornado.


## **From my diggings, here my conclusion:**
As @philippjfr said, "it's pretty deeply burried in bokeh", so delicate to touch without breaking anything else.
I looks to me that `server_html_page_for_session` is responsible for setting `use_for_title` to `True` without asking anyone else.
It seems to me that if we set `use_for_title` to `False` it might fix the problem but also maybe it will cause other bug if the title in the html doesn't match the `title`
 attribute of the Python `document` object (No idea).

### **Ideas to fix:**

#### **1.** Easier and less risky I think but not the best user API:
To document (https://panel.holoviz.org/user_guide/Templates.html) that `<title>{% block title %}{{ title | e if title else "Panel App" }}{% endblock %}</title>` can be overridden only with the same variable name `title`, in fact, that `title` is a reserved parameter name in the template, and that in the method `add_variable(name, value)` in `panel/template/base.py` to add a special case for the variable `title` that will in addition set the title attribute of the document, like that :

In the `__init__` of `class BaseTemplate` we add a private attribute <code>**self._title = None**</code>
Then in the method `_init_doc` (still in `class BaseTemplate`):
```python
    def _init_doc(self, doc=None, comm=None, title=None, notebook=False, location=True):
        doc = doc or _curdoc()
        title = title or self._title or 'Panel Application'
        if location and self.location:
            loc = self._add_location(doc, location)
            doc.on_session_destroyed(loc._server_destroy)
        doc.title = title
        ...
```
I just added the <code>**or self._title"**</code>.
And finally, in the method `add_variable` in `class class Template` :
```python
    def add_variable(self, name, value):
        """
        Add parameters to the template, which may then be referenced
        by the given name in the Jinja2 template.
        Attention, `title` is a reserved parameters for the template to use only to set in the title block
        Arguments
        ---------
        name : str
          The name to refer to the panel by in the template
        value : object
          Any valid Jinja2 variable type.
        """
        if name in self._render_variables:
            raise ValueError('The name %s has already been used for '
                             'another variable. Ensure each variable '
                             'has a unique name by which it can be '
                             'referenced in the template.' % name)
        if name == "title":
            self._title = value
        self._render_variables[name] = value
```
I added the <code>**if name == "title": self._title = value**</code>

This solution will fix the problem without changing anything for the others `BasicTemplate` and children like `GoldenTemplate`.
But it add a "gotcha" in the documentation by reserving the parameter 'title' in the Jinja template.

#### **2.** More risky but sounds more correct for the end user API:
To fix the function `server_html_page_for_session` in `bokeh/embed/server.py` by adding to it an argument `use_for_title` defaulted to `True`. And then somehow pass `use_for_title=False` in the case of the Jinja template use that extend the base template override the `{% block title %}`. Sounds difficult and error prone, also I have no idea if it will break other things as the html document's title will not match the Python document object's tilte...


### **My point of view as a user**
I think we should go with solution 1 as it affects only the `class Template` which is anyway only used by advanced user that will study more Panel and read all the documentation anyway (I feel), the other available `BasicTemplate` won't be affected at all.
@MarcSkovMadsen what do you think ?

@bryevdv 
Maybe the Bokeh team want to take a look too and let us know if they prefer solution 2 or if there is a better solution I don't see/understand ?

@philippjfr what do you think ?

@philippjfr If you like solution 1 I can try to do the pull request if you want. Let me know.
(Just know that I am pretty new to OSS project and don't know the standard (am I supposed to do extensive tests ? how do you test such huge library,.... Do I have to open another branch in git ? is there a naming convention... I don't know but will be happy to learn 😄 ! If you have a tutorial to refer me it will help)

**Comment by bryevdv** [comment]
I'm definitely not far down in the weeds on this, but if anyone wants to add a new `use_for_title` parameter to the end of `server_html_page_for_session` that defaults to `True`, that seems trivially fine to do, and we'd be happy to accept that change. IIUC the templates you are referring to are not Bokeh templates so I don't have any opinion on that.

**Comment by GilShoshan94** [comment]
Hi @philippjfr,

I see you just post #[1967](https://github.com/holoviz/panel/pull/1967). 
Does it fix it ?

Did you had time to read my suggestion ? 
I can try solution 1 and do the pull request if you agree (after I make sure it works)
I didn't had time this last week but will this week.

Also Bryan answer positively to solution 2 but I am unable  to do it because I don't understand the project well enough to implement it (how to pass `use_for_title=False` ....)

Let me know if I can give it a shot or if you don't like solution 1 (Don't worry I will accept your call)

**Comment by philippjfr** [comment]
It already appears fixed now. I've had to copy the `server_html_page_for_session` function for other reasons and simply forced `use_title=False`. I've left it open to investigate whether this broke anything else but it seems to work as far as I can tell.

**Comment by GilShoshan94** [comment]
Ok great ! 
Thank you.

In the case this brake anything I am pretty sure my solution 1 is safe (but less elegant because add a special hardcoded keyword).
Have a good weekend.

**Comment by philippjfr** [comment]
Closing for now, will reopen if I find any issues with my recent changes.
