### ISSUE TITLE
panel png object does not update

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1952]
In the user guide https://panel.holoviz.org/user_guide/Components.html the `png.object` example does not work.

![image](https://user-images.githubusercontent.com/42288570/106487896-6ddc2680-64b3-11eb-9f99-17e595ea1915.png)

And I can replicate the problem

![image](https://user-images.githubusercontent.com/42288570/106488046-949a5d00-64b3-11eb-8148-ae3edd7fb9d3.png)

```python
import panel as pn
pn.extension()

png = pn.panel('https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png', width=300)

png

png.object = 'https://upload.wikimedia.org/wikipedia/commons/3/39/PNG_demo_heatmap_Banana.png'
```

**Comment by philippjfr** [comment]
Note on the website this cannot update since it is not a live kernel, locally I cannot reproduce.

**Comment by philippjfr** [comment]
Now you could say that we should not use such examples in the docs since they will never appropriately update but that would require an explicit issue and then a concerted effort to eliminate such examples from the docs.

**Comment by MarcSkovMadsen** [comment]
What about  the replication that I described above? I can replicate the problem in Jupyterlab.

**Comment by philippjfr** [comment]
Can you provide details about the exact versions? Because at least on master I cannot reproduce, hence I closed.

**Comment by philippjfr** [comment]
Including the version of JLab.
