### ISSUE TITLE
Enable pn.widgets.FileSelector() to watch for new files and update directory 

### ISSUE THREAD

**Issue by tlmille2** [holoviz/panel#1961]
**Problem Statement**
The general flow is a user can upload a series of images they would like to analyze or transform, select an image to do the analysis on, and then preform the analysis using Panel.

I'm using the `file_input = pn.widgets.FileInput()` to input files and  `= pn.widgets.FileSelector(nameofdir)` to allow the selection of images to be analyzed using panel.  However, I'm noticing the `pn.widgets.FileSelector()` doesn't update the available files unless you refresh the browser.

Additionally, the FileSelector() Widget has a method self._update_files() is called in response certain events, such as pressing the down arrow.  You can force a refresh without reloading the browser.  The only issue I have with using the UI to force the update is if you explicitly define a directory, without any children folders inside that directory, those buttons are basically disabled.

![image](https://user-images.githubusercontent.com/36211553/106793589-443f0e80-661d-11eb-88d7-7ccb3eb9968f.png)

**Desired Solution**
Add a periodic callback to watch the directory for any changes.

**Alternative Solution**
A refresh button that can refresh the directory and display any new changes

**Comment by philippjfr** [comment]
Thanks @tlmille2, very reasonable suggestions. I'll implement both, one question I have though, what did you do to get that layout for the `FileSelector`, it should really look like this:

<img width="760" alt="Screen Shot 2021-02-04 at 11 40 09 AM" src="https://user-images.githubusercontent.com/1550771/106881378-c1ca5380-66dd-11eb-8a83-1ca637ab1544.png">

**Comment by tlmille2** [comment]
@philippjfr - Appending the FileSelector in a bootstrap.main template (see below).  I filtered out a large chunk of variable names.

![image](https://user-images.githubusercontent.com/36211553/106929174-a78e7680-66d9-11eb-8873-50d2655e3c89.png)

I'm going to open another ticket about FileSelector not behaving it's margins when applied to the bootstrap template.  I'm trying to diagnose it's cause, but I think it's a css issue.

**Comment by philippjfr** [comment]
Thanks, I'll file a new issue.
