### ISSUE TITLE
(Calendar + clock) widget

### ISSUE THREAD

**Issue by jbednar** [holoviz/panel#1975]
It's not currently easy for a user to select a datetime value in Panel. Current options:

- **Datepicker** and **Dateslider**: convenient for selecting a date, but can't select a time
- **Datetimeinput**: returns a datetime, but not very friendly to the user; requires them to type a string without much feedback on what's accepted
- **Datetimeslider**: If #1972 is implemented, would make it easy to scroll through datetimes, and if https://github.com/bokeh/bokeh/issues/9943 is implemented would even make it feasible for a user to input a very specific datetime when needed, but would still not be that friendly for users who are thinking in terms of calendars and clocks

I think it would be valuable to have a datetime widget that is a drop-in replacement for the Datetimeinput widget, returning a single datetime64 value, but with user-friendly controls for people thinking of a specific time on a specific date: a calendar to select the date, and hh:mm:ss text boxes to select the time.  Obviously we can build such functionality already out of Bokeh widgets, but then you get date, hour, minute, and seconds values separately rather than a single datetime value useful for feeding to something like Pandas. Needing to select a datetime seems like a common and typical use case, and so I think there ought to be a straightforward drop-in widget like this to handle it.

**Comment by Hoxbro** [comment]
I have been playing around with the existing Datepicker in panel, the bokeh model and flatpickr. flatpickr has a option to enable time, and I got a working code of it in action (maybe with some small hacks...)   

https://user-images.githubusercontent.com/19758978/111658738-e8b39380-880c-11eb-801c-fe24b14dab00.mp4

**Comment by nghenzi** [comment]
this is awesome  !!!

I was using a JS library, but it would be nice if something like this is incorporated to panel

you can check the JS library here

https://discourse.holoviz.org/t/elegant-date-and-time-picker/1262/3?u=nghenzi2019

**Comment by MarcSkovMadsen** [comment]
Awesome both you @hoxbro and the work

**Comment by nghenzi** [comment]
flatpickr support a range date selection too. 

![image](https://user-images.githubusercontent.com/46707985/111695266-a9d40c80-8811-11eb-9e9c-a9e25a9bd5f9.png)

**Comment by jbednar** [comment]
Both of those look fabulously useful!

**Comment by philippjfr** [comment]
>I have been playing around with the existing Datepicker in panel, the bokeh model and flatpickr. flatpickr has a option to enable time, and I got a working code of it in action (maybe with some small hacks...)

Can you submit a PR? Would love to do this.

**Comment by philippjfr** [comment]
To be clear, in the long run we should upstream the widgets to bokeh but I'd love to get these into Panel asap.

**Comment by rsignell-usgs** [comment]
We have the nice [Panel DatetimePicker](https://panel.holoviz.org/reference/widgets/DatetimePicker.html) now, but unfortunately I just found out it doesn't like the datetime64 objects from xarray (and pandas, I guess).   

Here's a [short reproducible notebook](https://nbviewer.org/gist/72a9357bd04087e4b46736eb819209b2) showing the problem (screenshot below):
![datetime_picker](https://user-images.githubusercontent.com/1872600/189944765-f138c3c6-1752-4816-aba3-b5ba2a0e18c6.png)

**Comment by rsignell-usgs** [comment]
@philippjfr please let me know if I should raise a new issue -- I would be happy to do so.

**Comment by Hoxbro** [comment]
The main problem is that your data is discrete and that DatetimePicker can accept any datetime value.  

A way to get this to work is to find the last value in the dataset and plot that. Here is an example of how it could be done. 

``` python
import hvplot.xarray  # noqa
import pandas as pd
import panel as pn
import xarray as xr

xr_ds = xr.tutorial.open_dataset("air_temperature")
dt = pd.to_datetime(xr_ds.time)

datetime_widget = pn.widgets.DatetimePicker(
    value=dt.min(), start=dt.min(), end=dt.max()
)


def plot(t):
    t = dt[dt.get_indexer([t], method="ffill")[0]]  # Find the last valid value
    return xr_ds["air"].sel(time=t).hvplot(x="lon", y="lat")


pn.Column(pn.bind(plot, datetime_widget), datetime_widget)
```

https://user-images.githubusercontent.com/19758978/190118378-87691099-5ed7-4bc2-8698-402df0ab93bc.mp4

**Comment by maximlt** [comment]
I guess there could be a variation of a DatetimePicker that only allows to pick in a discrete list of date time values, everything else being greyed out. That'd be a feature request on Panel.

**Comment by Hoxbro** [comment]
I think you just described `disabled_dates`/`enabled_dates` of [DatePicker](https://pyviz-dev.github.io/panel/reference/widgets/DatePicker.html).

**Comment by rsignell-usgs** [comment]
@Hoxbro and @maximlt , thanks so much for providing the solution -- I never would have figured that out!  
Would it be possible to select with xarray without going to pandas?  Would be bit clearer since we are working with xarray data here.

**Comment by Hoxbro** [comment]
It is actually easier.

``` python
def plot(t):
    return xr_ds["air"].sel(time=t, method="ffill").hvplot(x="lon", y="lat")
```

The `pd.to_datetime` can also be replaced as it is only used to find the max and min value and convert it to a datetime object. Though, I think this is the easiest way to do it. :)

**Comment by rsignell-usgs** [comment]
Wow, this is getting easier and easier!
![2022-09-14_15-36-53](https://user-images.githubusercontent.com/1872600/190246652-e50bf87e-0efc-4bb2-9882-e0fc41309542.png)
Notebook here: https://nbviewer.org/gist/rsignell-usgs/f860014203b9276ae67c654eaa7c9788

**Comment by philippjfr** [comment]
The [`DatetimePicker`](https://panel.holoviz.org/reference/widgets/DatetimePicker.html) fulfills the brief of what is asked for in this issue and there are other issues about other date selection widgets, so I'll close.
