### ISSUE TITLE
Make it easy to display logs in Panel App

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1978]
Right now there is not supported or documented way of displaying logs and exceptions in your Panel app. Instead it is either not shown anywhere or in the terminal or in the browser console.

That is problematic while you are developing and testing. And for some apps it would also be nice to display logs inside Panel.

I would like support for

1) Providing a PanelLogStream as a logging handler. This would need a `write` method and the implementation would probably append the message to some value of the instance. If the class is not provided by Panel at least a description in the docs or Gallery would be nice
2) A nice terminal widget for displaying the logs.

**Comment by MarcSkovMadsen** [comment]
#### Example

![image](https://user-images.githubusercontent.com/42288570/107977211-06e26580-6fbb-11eb-989b-1985b7473f0d.png)

```python
import panel as pn
import param
import logging

class LogStream(param.Parameterized):
    value = param.String(precedence=1)
    latest = param.String(precedence=0, label="Message")

    def flush(self):
        pass

    def write(self, message):
        self.latest = message
        self.value = message + self.value


stream = LogStream()

def get_logger(name):
    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    handler = logging.StreamHandler(stream=stream)
    handler.setLevel(logging.DEBUG)
    handler.setFormatter(formatter)

    logger.addHandler(handler)
    return logger

logger = get_logger(__name__)

logger.info("Hello Logging World 1")
logger.info("Hello Logging World 2")
pn.Param(stream, sizing_mode="stretch_width", widgets={
        "value": {"widget_type": pn.widgets.TextAreaInput, "sizing_mode": "stretch_both"}
    }).servable()
```

**Comment by kcpevey** [comment]
I would love to see this too!

**Comment by philippjfr** [comment]
The Terminal widget you added provides great support for this.
