### ISSUE TITLE
Provide ParameterizedComponent

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1979]
I would like to provide easy to use domain models and components (like an BlackScholesOptionsModel from finance) that I can display and explore interactively. Putting the `view` in an attribute or providing it as a `view()` function is not how users would expect to be able to use their component.

Make it easy to implement a Parameterized component that displays in the notebook and on the server.

#### Brainstorm Design

provided by @philippjfr 

![image](https://user-images.githubusercontent.com/42288570/107977363-4610b680-6fbb-11eb-86c0-4445ad28c4af.png)

**Comment by jbednar** [comment]
Just to be clear, this would provide a Parameterized _panel_ component, right? I.e., with an explicit dependence on Panel?  The current Parameterized support does not require the Parameterized code to import from Panel or depend directly on it, but this new idea would.  Sounds good, in any case!

**Comment by MarcSkovMadsen** [comment]
Yes
