### ISSUE TITLE
Developer Guide does not work without node.js installed

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1992]
OS: Docker image `FROM continuumio/miniconda`.

I'm starting from the above "clean" docker image and following the developer instructions https://panel.holoviz.org/developer_guide/index.html

When I run

```bash
doit develop_install -c pyviz/label/dev -c conda-forge -c bokeh/label/dev -o build -o tests -o recommended
```

I get

```bash
ERROR: Command errored out with exit status 1: /opt/conda/envs/panel_dev/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/workspaces/panel/setup.py'"'"'; __file__='"'"'/workspaces/panel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
TaskFailed - taskid:develop_install
Command failed: 'pip install --no-deps --no-build-isolation -e .' returned 1
```

Solution:

Either mention that node.js should be installed or include it in the command.

ps. I've also changed the bokeh channel. I don't know if this should be changed in the developer instructions or whether this is a special situation??

**Comment by philippjfr** [comment]
Not sure when this was added but the instructions mention NPM:

>The above command installs Panel's dependencies using conda, then
performs a pip editable install of Panel. If it fails, ``nodejs>=14.0.0`` may be missing
from your environment, fix it with ``conda install -c conda-forge nodejs`` then rerun above command.
