### ISSUE TITLE
Displaying param.Number doesn't support float("-inf") 

### ISSUE THREAD

**Issue by okz** [holoviz/panel#1998]
No issues with  float('inf'), but the negative, float('-inf') fails.

```
class Numeric(param.Parameterized):
    works = param.Number(default=float('inf')) 
    fails = param.Number(default=float('-inf')) 

pn.Row(Numeric())
```

![image](https://user-images.githubusercontent.com/3274852/108747037-ea06de80-7534-11eb-898c-281271a5683e.png)

**Comment by mattpap** [comment]
ref https://github.com/bokeh/bokeh/issues/5439

**Comment by jbednar** [comment]
I've updated the issue title to indicate that it's not Param that fails to support -inf, it's Panel. Param does just fine with it:

![image](https://user-images.githubusercontent.com/1695496/108919810-43384600-75f9-11eb-9875-379bbdf1b27a.png)

**Comment by hyamanieu** [comment]
This is only an issue if you render it into a `pn.Param`-generated widget. Even the positive `inf` doesn't work if you change the value to it. I am not sure why you would want to have a widget to get inf from a user. It seems to be a problem with the json library.
[

https://user-images.githubusercontent.com/15906523/109357177-1480d080-7882-11eb-8542-08557cfb3c9e.mp4

](url)

**Comment by jbednar** [comment]
Right. Unfortunately, there are various objects accepted as integers by Param that don't map nicely into numeric widgets, including any of the float special values along with None when that's allowed. For those values there's not currently any way to edit them in a GUI. It would be great if they at least (a) did not error and (b) were displayed properly, in a Panel widget.  Here it seems like (a) is violated because we rely on JSON serialization that does not support -inf.

**Comment by okz** [comment]
If i"t did not error" it would be a big improvement actually.

>>  I am not sure why you would want to have a widget to get inf from a user
My usecase was the other way around, a param.Parameterized class instance, for a model fitting process. The boundary conditions can be +/- infinity and the idea was "expressing the parameters of a class (or a hierarchy of classes) completely independently of a GUI implementation" .

**Comment by jbednar** [comment]
Right; I think we should be able to achieve "does not error", precisely to fully support display of values from Param. @philippjfr  or @jlstevens can probably think of a way around the JSON round-trip issue involved.  

Fully supporting the various special values as inputs is a much bigger task that involves coordination with the underlying widget libraries, which weren't designed to expose all the full richness of Param Numbers or even regular floats.

**Comment by hyamanieu** [comment]
A widget is meant for a user (could be you) to set your variable from the GUI. If I understand you correctly (your user case being the other way around), the widget is not necessary. So you can filter out your two inf numbers by setting `preference` to `-1` within `param.Number()`. Then the widgets won't be generated and you won't get the error.
Setting them differently could be as simple as `n.works=float('-inf')` in the next notebook cell or could be set with a method of your `Numeric` class.

**Comment by jlstevens** [comment]
@hyamanieu That is one good suggestion! 

Though to avoid confusion, I think it is worth saying that you probably meant `precedence=-1` and not `preference`! :-)

**Comment by hyamanieu** [comment]
corrected

**Comment by okz** [comment]
Thanks Hugues, good workaround and I do have something similar

The reason I raised the issue was possible hind sight on Parameterized classes with widgets: 

Quotes from the Panel API user guide: 

"Expressing the parameters of a class (or a hierarchy of classes) completely independently of a GUI implementation" 
and 
"The resulting objects can then be used in both GUI and non-GUI contexts (batch computations, scripts, servers)."

These are great ideas, but requires GUI elements to handle displaying parameters handle them somehow, or at least not fail.

**Comment by jlstevens** [comment]
> ... or at least not fail.

Totally agreed! There will be parameter values that are hard to display but any value that stops the widget working at all is definitely a bug.
