### ISSUE TITLE
vtkGlyph3DMapper on Panel + JupyterLab gives javascript error, blank screen

### ISSUE THREAD

**Issue by LunarLanding** [holoviz/panel#2001]
On [vtk's discourse](https://discourse.vtk.org/t/vtkglyph3dmapper-on-panel-jupyterlab-gives-javascript-error-blank-screen/5240) I have been told this should work, but that panel doesn't handle `vtkGlyph3DMapper` correctly.

#### Software version info

- Python : 3.8.8
- Python Environment

  | name                    | version | build                      | channel     | 
  |-------------------------|---------|----------------------------|-------------| 
  | panel                   | 0.10.3  | pyhd8ed1ab_0               | conda-forge | 
  | jupyterlab              | 3.0.8   | pyhd8ed1ab_0               | conda-forge | 
  | vtk                     | 9.0.1   | no_osmesa_py38hf8772f4_104 | conda-forge | 

  <details><summary> More info </summary>
  <p>
  
   `conda list | grep -e bokeh -e python -e jupyter -e panel -e itk -e vtk -e pyvista`
  
  | name                    | version | build                      | channel     | 
  |-------------------------|---------|----------------------------|-------------| 
  | biopython               | 1.78    | py38h497a2fe_1             | conda-forge | 
  | bokeh                   | 2.2.3   | py38h578d9bd_0             | conda-forge | 
  | ipython                 | 7.20.0  | py38h81c977d_2             | conda-forge | 
  | ipython_genutils        | 0.2.0   | py_1                       | conda-forge | 
  | itk                     | 5.1.2   | py38h578d9bd_0             | conda-forge | 
  | itk-core                | 5.1.2   | pypi_0                     | pypi        | 
  | itk-filtering           | 5.1.2   | pypi_0                     | pypi        | 
  | itk-numerics            | 5.1.2   | pypi_0                     | pypi        | 
  | itk-registration        | 5.1.2   | pypi_0                     | pypi        | 
  | itk-segmentation        | 5.1.2   | pypi_0                     | pypi        | 
  | itkwidgets              | 0.32.0  | py38h32f6830_0             | conda-forge | 
  | jupyter_client          | 6.1.11  | pyhd8ed1ab_1               | conda-forge | 
  | jupyter_core            | 4.7.1   | py38h578d9bd_0             | conda-forge | 
  | jupyter_server          | 1.4.0   | py38h578d9bd_0             | conda-forge | 
  | jupyterlab              | 3.0.8   | pyhd8ed1ab_0               | conda-forge | 
  | jupyterlab_execute_time | 2.0.2   | pyhd8ed1ab_0               | conda-forge | 
  | jupyterlab_pygments     | 0.1.2   | pyh9f0ad1d_0               | conda-forge | 
  | jupyterlab_server       | 2.3.0   | pyhd8ed1ab_0               | conda-forge | 
  | jupyterlab_widgets      | 1.0.0   | pyhd8ed1ab_1               | conda-forge | 
  | mmtf-python             | 1.1.2   | py_0                       | conda-forge | 
  | msgpack-python          | 1.0.2   | py38h1fd1430_1             | conda-forge | 
  | panel                   | 0.10.3  | pyhd8ed1ab_0               | conda-forge | 
  | python                  | 3.8.8   | hffdb5ce_0_cpython         | conda-forge | 
  | python-dateutil         | 2.8.1   | py_0                       | conda-forge | 
  | python-graphviz         | 0.16    | pyh243d235_2               | conda-forge | 
  | python-libarchive-c     | 2.9     | py38h924ce5b_2             | conda-forge | 
  | python-slugify          | 4.0.1   | pyh9f0ad1d_0               | conda-forge | 
  | python_abi              | 3.8     | 1_cp38                     | conda-forge | 
  | pyvista                 | 0.28.1  | pyhd8ed1ab_1               | conda-forge | 
  | vtk                     | 9.0.1   | no_osmesa_py38hf8772f4_104 | conda-forge | 
  
  
  </p>
  </details>

- OS : WSL2 ( `Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` )
- Browser : Firefox 85.0.2 64-bit running on Windows 10 Pro Version 20H2 build 19042.804

#### Description of expected behavior and the observed behavior

Expected behavior: there's some cones on screen in a conic arrangement.
Observed behavior: blank canvas, javascript error any time the canvas is interacted with, sometimes the canvas turns black.

#### Complete, minimal, self-contained example code that reproduces the issue

I believe it is not dependent on OS/browser, but I detail that too. A jupyter notebook with the python code is here: https://gist.github.com/LunarLanding/185e6235cd966a3f186586fa540b620b

Install WSL2.
Install software-rendering libs:
```sh
sudo apt-get update
sudo apt-get install libgl1-mesa-glx xvfb
```

Setup screen

start
```sh
#!/bin/bash
export DISPLAY=:99.0
export PYVISTA_OFF_SCREEN=true
export PYVISTA_USE_IPYVTK=true
export PYVISTA_PLOT_THEME=document
which Xvfb
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
sleep 3
exec "$@"
```

Install miniconda 3.8, jupyter lab, vtk, panel (see environment below).
Start jupyter with a screen : `start jupyter lab --no-browser`.
Access jupyter at '127.0.0.1:8888'.
Open a notebook and run:

```python
import vtk
import panel as pn
pn.extension('vtk')

coneSource1 = vtk.vtkConeSource();
mapper = vtk.vtkGlyph3DMapper();
mapper.SetInputConnection(coneSource1.GetOutputPort());
coneSource = vtk.vtkConeSource();
mapper.SetSourceConnection(coneSource.GetOutputPort())
mapper.Update()
actor = vtk.vtkActor();
actor.SetMapper(mapper);


ren = vtk.vtkRenderer()
ren.AddActor(actor)
ren.ResetCamera()


win = vtk.vtkRenderWindow()
win.AddRenderer(ren)


geom_pane = pn.pane.VTK(win, width=500, height=500)
geom_pane
```

#### Stack traceback and/or browser JavaScript console output

```
Uncaught TypeError: t.oglmapper is undefined
    traverseOpaquePass index.js:63
    traverse index.js:27
    traverse index.js:35
    traverse index.js:75
    traverseAllPasses index.js:1066
    u index.js:348
    handleAnimation index.js:501
    requestAnimation index.js:369
    <anonymous> index.js:41
    handleLeftButtonPress index.js:124
    o index.js:59
    a macro.js:850
    <anonymous> macro.js:839
    <anonymous> index.js:773
    handleMouseDown index.js:309
    bindEvents index.js:231
    newInstance panel.min.js:117
    newInstance panel.min.js:117
    n macro.js:892
    init_vtk_renwin panel.min.js:116
    render panel.min.js:100
    build bokeh-2.2.3.min.js:449
    renderTo bokeh-2.2.3.min.js:449
    r bokeh-2.2.3.min.js:572
    add_document_standalone bokeh-2.2.3.min.js:572
    embed_items_notebook bokeh-2.2.3.min.js:579
    embed_document vtk.ipynb line 2 > injectedScript:5
    <anonymous> vtk.ipynb line 2 > injectedScript:8
    <anonymous> vtk.ipynb line 2 > injectedScript:24
    attachWidget jlab_core.f2b89b53957c2ff21ed9.js:2
    insertWidget jlab_core.f2b89b53957c2ff21ed9.js:2
    _insertOutput jlab_core.f2b89b53957c2ff21ed9.js:2
    onModelChanged jlab_core.f2b89b53957c2ff21ed9.js:2
    m jlab_core.f2b89b53957c2ff21ed9.js:2
    l jlab_core.f2b89b53957c2ff21ed9.js:2
    emit jlab_core.f2b89b53957c2ff21ed9.js:2
    _onListChanged jlab_core.f2b89b53957c2ff21ed9.js:2
    m jlab_core.f2b89b53957c2ff21ed9.js:2
    l jlab_core.f2b89b53957c2ff21ed9.js:2
    emit jlab_core.f2b89b53957c2ff21ed9.js:2
    push jlab_core.f2b89b53957c2ff21ed9.js:2
    _add jlab_core.f2b89b53957c2ff21ed9.js:2
    add jlab_core.f2b89b53957c2ff21ed9.js:2
```

#### Screenshots or screencasts of the bug in action

It's just a blank canvas. 
![Untitled](https://user-images.githubusercontent.com/4441338/108926678-c6c45800-7636-11eb-93b2-798fc583d7d4.png)

**Comment by xavArtley** [comment]
Indeed our serializer does not handle vtkGlyph3Dmapper

```
geom_pane = pn.pane.VTK(win, width=500, height=500, debug_serializer=True)
geom_pane
      !!!No serializer for vtkOpenGLGlyph3DMapper with id a804c84f-d0fe-4734-bbb5-642ad7c337fa000002bbf2626170
```

**Comment by LunarLanding** [comment]
Thanks for the quick response, but in fd9e09c the vtkGlyph3DMapper's is not behaving correctly: here I should see 8 spheres floating and not 8 cubes in a cube pattern:
![Untitled](https://user-images.githubusercontent.com/4441338/109009790-e1361a00-76a6-11eb-8068-1dcf7bd49360.png)
I can move this to a new issue if that's best.
Environment: same as above, except I built and installed locally the conda package from master via `conda-build conda.recipy --override-channels -c pyviz/label/dev -c bokeh/label/dev -c conda-forge`.

Code:
```python
import vtk
import panel as pn
pn.extension('vtk')

sphereSource = vtk.vtkSphereSource();
mapper = vtk.vtkGlyph3DMapper();
cubeSource = vtk.vtkCubeSource();
mapper.SetInputConnection(cubeSource.GetOutputPort())
mapper.SetSourceConnection(sphereSource.GetOutputPort())
mapper.SetScaleFactor(.3)
mapper.Update()
actor = vtk.vtkActor();
actor.SetMapper(mapper);

ren = vtk.vtkRenderer()
ren.AddActor(actor)
ren.ResetCamera()

win = vtk.vtkRenderWindow()
win.AddRenderer(ren)

geom_pane = pn.pane.VTK(win, width=300, height=300)
geom_pane
```

`conda list | grep -e panel -e pyviz -e vtk -e python -e jupyter` yields
```
biopython                 1.78             py38h497a2fe_1    conda-forge
ipython                   7.20.0           py38h81c977d_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
jupyter_server            1.4.0            py38h578d9bd_0    conda-forge
jupyterlab                3.0.8              pyhd8ed1ab_0    conda-forge
jupyterlab_execute_time   2.0.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
mmtf-python               1.1.2                      py_0    conda-forge
msgpack-python            1.0.2            py38h1fd1430_1    conda-forge
panel                     0.11.0b1.post2+gfd9e09c            py_0    <local>
python                    3.8.8           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-graphviz           0.16               pyh243d235_2    conda-forge
python-libarchive-c       2.9              py38h924ce5b_2    conda-forge
python-slugify            4.0.1              pyh9f0ad1d_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pyviz_comms               2.0.1              pyhd3deb0d_0    conda-forge
vtk                       9.0.1           no_osmesa_py38hf8772f4_104    conda-forge
```
