### ISSUE TITLE
FileSelector widgets adds folder icon to files

### ISSUE THREAD

**Issue by rafgonsi** [holoviz/panel#2044]
#### ALL software version info
python 3.7.6, panel==0.10.3, bokeh==2.2.3, linux

#### Description of expected behavior and the observed behavior
When `FileSelector` widget is initialized with multiple files as value, then a folder icon appear just as if those files were folders.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn
pn.extension()
files = pn.widgets.FileSelector('/files', value=["/files/file1.txt", "/files/file2.txt"])
files

```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/33317987/109643681-dd960d80-7b54-11eb-936d-0eb83f732947.png)

#### Potential solution
I suspect that there is a mistake in 171st line of code of panel/widgets/file_selector.py:
```python
# panel/widgets/file_selector.py
... 
class FileSelector(CompositeWidget):
    ...
    def _update_files(self, event=None):
        ...
        dirs, files = scan_path(path, self.file_pattern)
        for s in selected:
            check = os.path.realpath(s) if os.path.islink(s) else s
            if os.path.isdir(check):
                dirs.append(s)
            elif os.path.isfile(check):
                dirs.append(s)
        ...
```
I suspect that there should be `files` instead of `dirs` in the last line of this code.

**Comment by philippjfr** [comment]
Thanks @rafgonsi. Ordinarily I would have asked you to submit a PR but since I'm about 30 minutes away from tagging 0.11.0 I've submitted one myself.
