### ISSUE TITLE
Allow FileSelector widget to browse outside of initialized path

### ISSUE THREAD

**Issue by sdc50** [holoviz/panel#2051]
The `FileSelector` widget has a `directory` parameter that sets the initial path of for the selector to  browse:

```python
pn.widgets.FileSelector(directory='./', file_pattern='*.csv')
```
The widget allows you to move into subdirectories of the `directory` parameter, but it does not allow you to move to parent directories. I understand that this is often desirable for security reasons, if, for example, the widget is allowing a user to browse the file system of a server. But I often have a use cases where I'm using this widget on a local file system and would like the ability to browse around more freely.

One solution would be to add a flag to the `FileSelector` widget to not restrict browsing:

```python 
pn.widgets.FileSelector(directory='./', file_pattern='*.csv', restrict_browsing=False)
```

A more flexible solution would be to have two directory parameters: one to set the "root" directory and another to set the initial directory:

```python 
pn.widgets.FileSelector(initial_directory='./', root_directory='../../', file_pattern='*.csv')
```

If the default for the `root_directory` was the value of the `initial_directory` then the current behavior would be preserved, while allowing for the widget to provide more flexibility.

**Comment by dwr-psandhu** [comment]
@philippjfr @sdc50 On windows (sigh!) the topmost is a single drive. Can this be enhanced to allow selection of multiple drives ( C:, D:, etc)
