### ISSUE TITLE
Importing holoviews in Jupyter startup script prevents kernel from starting

### ISSUE THREAD

**Issue by norweeg** [holoviz/panel#2061]
#### ALL software version info

jupyter core     : 4.7.0
jupyter-notebook : 6.1.6
qtconsole        : 5.0.1
ipython          : 7.19.0
ipykernel        : 5.4.2
jupyter client   : 6.1.7
jupyter lab      : 3.0.1
nbconvert        : 6.0.7
ipywidgets       : 7.6.2
nbformat         : 5.0.8
traitlets        : 5.0.5
python        : 3.8.6

Windows 10 Version 10.0.18363 Build 18363
Google Chrome  87.0.4280.88 (Official Build) (64-bit)

#### Description of expected behavior and the observed behavior

in `.ipython\profile_default\startup` create a python file in which Holoviews is imported then open Jupyter.  The kernel will not start.  It just hangs in "connecting" while the terminal prints kernel nudge messages.  It does not matter what frontend you use, Notebook, Lab, Visual Studio Code.  All are unable to connect to the kernel when Holoviews is imported in a startup script. 

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import holoviews as hv
```

**Comment by jlstevens** [comment]
> Should I close this bug and open one on panel since the problem seems to be in that module??

No need! I've now transferred the issue directly to the panel repository.

**Comment by philippjfr** [comment]
I think this has been resolved, if not please reopen.
