### ISSUE TITLE
Include a debug/info decorator

### ISSUE THREAD

**Issue by hyamanieu** [holoviz/panel#2062]
### Current status

In its current status, interactive Panel objects raising errors will either create the traceback in the jupyter cell (depending on `panel.config.console_output`) or inside the console in a server context.

This is inconvenient in a production context as a raised error may just look like an unresponsive application.

### Short description
In a production context as well as during analytical work, quickly knowing why an error is raised is very helpful.

I would like to suggest a decorator to add to any function that is used to render a dynamic pane, e.g. using `pn.depends`, `param.depends`, or `pn.interact`.

This solution could be either included in the standard library, or if it is too niche inside a template or in the gallery.

### Proposed solution

add the following decorator in the standard library

```python
import sys
import traceback
import functools
import panel as pn

info_layout = pn.Tabs(closable=True)

def status_decorator(f: callable =None, behavior: str='raise', info_layout: pn.layout.base.ListPanel=info_layout) -> callable: 
    """   
    Parameters
    ----------
    f : callable, optional
        The function to decorate.
    behavior : str, optional
        If 'replace', the object which should have been rendered will be replaced by the error message and the error will not be raised. 
        If 'raise', the error will be raised, meaning the target object will look frozen. 
        If 'erase', the function will return None and nothing will be rendered in place of the target object. 
        The default is 'raise'.
        
        In all cases, the error message will be appended to the list-like panel object 'info_layout'
    info_layout : pn.layout.base.ListPanel, optional
        A list-like panel object where each element is an error status. The default is info_layout.


    Returns
    -------
    callable
        The decorated function.

    """
    
    def mydec(f):
        @functools.wraps(f)
        def wrapper(*args,**kwargs):
            try:
                #info_layout.clear()
                return f(*args,**kwargs)
            except Exception as e:
                v, e, tb = sys.exc_info()
                stack = traceback.extract_tb(tb)
                (filename, line, procname, text) = stack[-1]
                info = pn.pane.Alert(object=repr(stack[-1]), height=100)
                info_layout.append((procname,info))
                if behavior == 'replace':
                    return info
                elif behavior == 'raise':
                    raise e
                elif behavior == 'erase':
                    return
                    
        return wrapper
            
    if f is None:
        return mydec
    else:
        return mydec(f)
```

The `ListPanel` object I am using is Tabs, so that the user can close it once they acknowledge they read it. Whenever https://github.com/holoviz/panel/issues/1555 is closed, any type of list type layout would work well.

Could be also associated with a logging, see https://github.com/holoviz/panel/issues/1978 .

Additionally, it could become a class decorator so that several functions can be overwritten. For example a user could redefine what happens within the "try" close, like activating a loading spinner or so.

#### pn.interact

Here order is important! The `status_decorator` must come after the `interact` decorator.
```python
pn.extension()
@pn.interact(x=True, y=1.0)
@status_decorator(replace=True)
def g(x, y):
    if y>2:
        raise ValueError('y too big!')
    return (x, y)
g
```

https://user-images.githubusercontent.com/15906523/110381903-6e3f8280-805a-11eb-9c5d-8e83a3fff6e8.mp4

#### pn.depends with a template

```python
import holoviews as hv
pn.extension('echarts')

bootstrap = pn.template.BootstrapTemplate(title='Bootstrap Template')

pn.config.sizing_mode = 'stretch_width'

xs = np.linspace(0, np.pi)
freq = pn.widgets.FloatSlider(name="Frequency", start=0, end=10, value=2)
phase = pn.widgets.FloatSlider(name="Phase", start=0, end=np.pi)




          
@status_decorator
@pn.depends(freq=freq, phase=phase)
def sine(freq, phase):
    return hv.Curve((xs, np.sin(xs*freq+phase))).opts(
        responsive=True, min_height=400)


@pn.depends(freq=freq)
@status_decorator(behavior='replace')   
def throwerr(freq):
    if freq>8:
        raise ValueError("I don't like your freq")
    return pn.indicators.Gauge(name='Frequency', value=freq, bounds=(0, 8))

 
@pn.depends(freq=freq)
@status_decorator(behavior='raise')  
def throwerr2(freq):
    if freq>8:
        raise ValueError("I don't like your freq")
    return pn.indicators.Number(name='Frequency', value=freq)

bootstrap.sidebar.append(freq)
bootstrap.sidebar.append(phase)

bootstrap.sidebar.append(info_layout)

bootstrap.main.append(
    pn.Row(
        pn.Card(hv.DynamicMap(sine), title='Sine'),
        throwerr,
        throwerr2
    )
)


bootstrap.modal.append(pn.pane.Markdown('## HELLO!'))

bootstrap.servable();
```

https://user-images.githubusercontent.com/15906523/110383125-27528c80-805c-11eb-97c9-8a26570b60f0.mp4

#### param.depends

```python
class A(param.Parameterized):

    with_throttled_enabled = param.Range(
        default=(100, 250),
        bounds=(0, 250),
    )

    def __init__(self, **params):
        super().__init__(**params)
        widgets = {
            "with_throttled_enabled": {
                "type": pn.widgets.IntRangeSlider,
                "throttled": False,
            },
        }
        self.controls = pn.Param(self, widgets=widgets)

        
    @param.depends("controls")
    @status_decorator(behavior='erase')
    def calculation(self):
        if self.with_throttled_enabled[0] > 130:
            raise ValueError('too low')
        return pn.Pane((self.with_throttled_enabled), min_width=200)

    @param.depends("controls")
    @status_decorator(behavior='erase')
    def buggy_calculation(self):
        return pn.Pane(self.with_throttled_enabled[1]/self.with_throttled_enabled[0], min_width=200)

a = A()
pn.Column(a.controls, pn.pane.Markdown('### will bug above 130'), a.calculation, pn.pane.Markdown('### division by 0'), a.buggy_calculation, info_layout)
```

https://user-images.githubusercontent.com/15906523/110383329-67197400-805c-11eb-83a9-3dfe6c4b69c0.mp4

#### Additional context
After some feedback from the main dev I can submit a PR.

**Comment by philippjfr** [comment]
I'll think about this a bit but I'm generally in favor of anything that improves the debugging experience. Ping @jbednar and @MarcSkovMadsen for attention and thoughts.

**Comment by jbednar** [comment]
It certainly looks great to me! Definitely patches a usability hole in Panel.  I'd have to work with it in practice before having any specific feedback on it, but I'm eager to see something like this in Panel!

**Comment by MarcSkovMadsen** [comment]
Hi @hyamanieu . This is a great step forwards. Thank you for contributing this.

My initial thoughts for improvements are

1. A general way of catching all errors and sending them to the frontend
  -  Like it's already done with the new --auto flag.
  -  It would same me of decorating all functions
2. In production I would like the exception communicated to the user. But maybe as a small red flag or button that the user can click to expand for details.
  - To me it just seems a better user experience.

Item 1. above is close **to need to have** longer term. While 2 is **nice to have**.

**Comment by hyamanieu** [comment]
In my user cases, errors are not limited to bugs. In many cases issues arise because either the user made unexpected inputs (they can be very creative, they made me discover sheets can be hidden in Excel for example) or due to an infrastructure problem (understand: connection to an external database is lost).

So your point 3 is actually the main objective of my proposal. Get the right user feedback when issues arise. The worst is that it looks just frozen for now.
Concerning having a red flag or a button: you can design your own UI and add the ListPanel object to it. Unfortunately I was not successful in making modal windows with Panel, which I believe is what is needed here.

Concerning Item 1: having a decorator gives granularity to the dashboard developer and is easier to implement.  Your suggestion may need to be done at bokeh or tornado level, right?

Finally concerning 2, if the error is not raised (`behavior!='raise'`) it won't be logged. I'll think of something.

**Comment by hyamanieu** [comment]
Thinking further about points 1 & 2: I tried a simpler solution by using Marc's [Terminal widget](https://github.com/holoviz/panel/blob/master/examples/reference/widgets/Terminal.ipynb)  and stream tornado's logger (or just `tornado.application` would also be enough).

However it streams from all Bokeh sessions and there is nothing in the logging `record` object that helps discriminating between the bokeh's sessions. User A would see the errors from user B. On top of it, it works only in a server context. In a Jupyter notebook, it'll need to be a different logger **and** to work only within the cell.

I don't think there is a simple way. Decorators seem the way to go if we want to return to the user only what she or he needs to know.

Here's what I did:

```python
terminal = pn.widgets.Terminal(options={"cursorBlink": True},
    height=300, width=1000)

stream_handler = logging.StreamHandler(terminal)
stream_handler.terminator = "  \n"


#formatter = TermFormatter("%(asctime)s [%(levelname)s]: %(message)s",
#                          stack_limit=2)
formatter = logging.Formatter("%(asctime)s [%(levelname)s]: %(message)s")


stream_handler.setFormatter(formatter)
stream_handler.setLevel(logging.ERROR)

logger=  logging.getLogger('tornado')
logger.addHandler(stream_handler)
```

There is also what seems like a bug from `logging` package or a misunderstanding from my side: I wanted to subclass  `logging.Formatter` to modify the `formatException` method to have less stack trace on the UI. However it modifies **every** handler's exception format, even going to `sys.stderr`, contrary to `format` which makes it different for each.


This was the subclass commented out here above:


```python
class TermFormatter(logging.Formatter):
    
    def __init__(self, *args, stack_limit=1, **kwargs):
        super().__init__(*args, **kwargs)    
        self.stack_limit = stack_limit
    
    def formatException(self, ei):
        """
        Format and return the specified exception information as a string.

        This default implementation just uses
        traceback.print_exception()
        """
        sio = io.StringIO()
        tb = ei[2]
        # See issues #9427, #1553375. Commented out for now.
        #if getattr(self, 'fullstack', False):
        #    traceback.print_stack(tb.tb_frame.f_back, file=sio)
        traceback.print_exception(ei[0], ei[1], tb, self.stack_limit, sio)
        s = sio.getvalue()
        sio.close()
        if s[-1:] == "\n":
            s = s[:-1]
       return s
```

**Comment by hyamanieu** [comment]
I succeeded in using no decorator and filtering only errors coming from the session showing the terminal. I had to create a new logger 'panel.callback' and added it where necessary. I haven't tried in jupyter yet.

Here is my branch, feedback is welcome: https://github.com/hyamanieu/panel/tree/debugger_widget

@MarcSkovMadsen the Terminal widget responds weirdly within a Card widget, height is erratic.

Once you pip-installed, here's a sample code to try `panel serve` on:

```python
import panel as pn
import param
pn.extension()


class A(param.Parameterized):

    with_throttled_enabled = param.Range(
        default=(100, 250),
        bounds=(0, 250),
    )

    def __init__(self, **params):
        super().__init__(**params)
        widgets = {
            "with_throttled_enabled": {
                "type": pn.widgets.IntRangeSlider,
                "throttled": False,
            },
        }
        self.controls = pn.Param(self, widgets=widgets)

        
    @param.depends("controls")
    #@status_decorator(behavior='erase')
    def calculation(self):
        if self.with_throttled_enabled[0] > 130:
            raise ValueError('too low')
        return pn.Pane((self.with_throttled_enabled), min_width=200)

    @param.depends("controls")
    #@status_decorator(behavior='erase')
    def buggy_calculation(self):
        return pn.Pane(self.with_throttled_enabled[1]/self.with_throttled_enabled[0], min_width=200)

a = A()


debug = pn.widgets.Debugger(name='Debugger', width=1000,height=400)


a = pn.Column(a.controls, pn.pane.Markdown('### will bug above 130'), 
          a.calculation, 
          pn.pane.Markdown('### division by 0'), 
          a.buggy_calculation, 
          debug,
          )
a.servable()
```

**Comment by MarcSkovMadsen** [comment]
Hi @hyamanieu 

How would I reproduce the terminal behaviour? Do you have a code example?

**Comment by hyamanieu** [comment]
If you run my code sample using my branch, you'll see that. Or you can simply put the terminal & a button to clear it inside a Card.

Checking the navigator inspector, I can see the object xterm within the bk terminal object is much larger. Should I open a separate issue?

**Comment by hyamanieu** [comment]
Here's a current preview of my work so far. It still needs a better visualization: the "acknowledge" button isn't sober enough when opened, and it's still too big when collapsed.


https://user-images.githubusercontent.com/15906523/126051352-3aff5388-adf7-428f-99c8-d1c01e23288a.mp4

@MarcSkovMadsen , you can see the visual xterm bug at the 15th second. 44th second you can see in the inspector the xterm-screen was set at 720px. No idea where this is from. By right clicking it refits to the parent width.

**Comment by hyamanieu** [comment]
The PR https://github.com/holoviz/panel/pull/2548 is IMHO ready. I still have an open question: is this alright to call the logger `panel.callbacks`? We could use something more explicit that may not be generate by `__name__`, like `panel.userside`. I'm lacking idea here.
