### ISSUE TITLE
Doc: Explain the exact scenario where `watch=True` needs to be used in depends

### ISSUE THREAD

**Issue by dhruvbalwada** [holoviz/panel#2064]
In the documentation for Parameterized classes (https://panel.holoviz.org/user_guide/Param.html) the first place where `watch=True` is used is in the example with maps of countries and continents. 

It will be helpful to add a line or two here to say why `watch=True` needs to be used with some functions (`_update_countries`) and not some others (`view`). 

Is it because view is part of the panel, and so panel automatically makes sure the calls are made when parameters are updated? while `_update_countries` is never part of the panel, so it needs to be made to watch explicitly?

**Comment by MarcSkovMadsen** [comment]
Hi @dhruvbalwada 

Your explanation is correct. 

If you are up to it making a PR would be great. The documentation is in notebook files in the repository.

**Comment by dhruvbalwada** [comment]
I'll do this over the weekend.
