### ISSUE TITLE
Deployment of Templated Apps to Binder using jupypter-panel-proxy not working.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2066]
Panel 0.11

## My Pain

I would like to demonstrate to colleagues and the Panel community how easy it is to share Panel apps on binder. It's really just adding `jupyter-panel-proxy` as described in the Panel docs and your notebooks in the root directory.

But no. The world is not so easy and the FastGridTemplate does not work

## Reproducing Steps

Open https://mybinder.org/v2/gh/MarcSkovMadsen/load-forecasts/HEAD?urlpath=/panel/app

## Screenshot of bug

![image](https://user-images.githubusercontent.com/42288570/110526870-9b516b00-8116-11eb-971c-2c4ce5e42ef8.png)

## Repository

https://github.com/marcskovmadsen/load-forecasts

## Additional Context

I would also in the near future have access to a JupyterHub and would like to run my panel apps there. And it would be the same problem on JupyterHub. 

So there is a large community of users on Universities, Govt. institutions and in Enterprises that do not have easy access to share their Panel apps via JupyterHub.

FYI. @WesleyTheGeolien

**Comment by MarcSkovMadsen** [comment]
## Additional Context

When running locally the app looks like

![image](https://user-images.githubusercontent.com/42288570/110527428-3d715300-8117-11eb-86fe-dbc419d1427b.png)

**Comment by MarcSkovMadsen** [comment]
## Additional Context - reverse proxy

I believe the problem is more general tjen jupyter deployment. I believe panel have problems whenever it’s deployed besind a reverse proxy to a non-root path.

For example at work I deploy to kubernetes and i have to serve my panel apps at /. If i serve them at /panel-apps my bundled static files cannot be found. Because panel looks for them at /static not / panel-apps/static

Thus a whole lot of kubernetes users/ reverse proxy users will not be able to deploy their panel apps.

**Comment by philippjfr** [comment]
Yes, I think the paths are getting mangled here. We should fix this and then release 0.11.1.
