### ISSUE TITLE
pn.pane.markup.HTML breaks with latest panel and bokeh

### ISSUE THREAD

**Issue by jnolis** [holoviz/panel#2093]
Hello!

I have a small chunk of code to render HTML within a dashboard. It correctly renders with `panel==0.10.3` and `bokeh==2.2.3`, however when I upgrade to `panel==0.11.1` and `bokeh==2.3.0` instead of seeing the expected HTML map instead it is just a blank white space. This is all from Python 3.8.5.

```python
import panel as pn
import urllib.request

with urllib.request.urlopen(
    "https://saturn-public-data.s3.us-east-2.amazonaws.com/examples/dashboard/pickup_map.html"
) as f:
    pickup_map = pn.pane.markup.HTML(f.read().decode("utf-8"), min_height=500, min_width=500)


pickup_map.servable(title="Saturn Taxi")
```

This is the expected output:
![correct map](https://user-images.githubusercontent.com/3317138/111387431-f16c6400-866a-11eb-9069-adb9ea167095.png)

While with the latest versions of the packages the screen is blank.

Thank you for the help!

**Comment by MarcSkovMadsen** [comment]
Hi @jnolis 

To steps you can do is 

1) To [Hard Refresh your browser](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.YFHZkdqSkuU) it might be needed to pickup the new `.js` versions of Bokeh or Panel.
2) Check the browser [dconsole](https://balsamiq.com/support/faqs/browserconsole/#:~:text=To%20open%20the%20developer%20console,(on%20Windows%2FLinux).) for error messages and post them here.

**Comment by philippjfr** [comment]
>One alternative explanation could be that static plot you are loading is generated using Bokeh 2.2 and mixing it with Bokeh 2.3 is a problem?

This is almost certainly the issue, the linked file is generated with Bokeh 2.2.3 and loading it into an app running 2.3 is likely leading to Bokeh 2.2.3 and 2.3 to clash in various ways. Happy to help figuring out solutions on the [Discourse](https://discourse.holoviz.org/) but since this is not a supported configuration I'll close the issue.

**Comment by jnolis** [comment]
Thanks for the help! And yes, that's definitely the issue and now that I see it I can work around it.
