### ISSUE TITLE
ReactiveHTML => Bokeh warnings when deployed in a server

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#2095]
![reactive_ko](https://user-images.githubusercontent.com/18531147/111439617-d7339400-8705-11eb-8989-63ced747acca.gif)

**Comment by xavArtley** [comment]
Is there a reason to inherit from bokeh `HTMLBox` model on python side but from `Markup` bokehjs model on javascript side?

**Comment by philippjfr** [comment]
No that's a bug, will fix.
