### ISSUE TITLE
Dirty documentation

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#2099]
When accessing the documentation on the website the version is not clean. 

![image](https://user-images.githubusercontent.com/19758978/111617498-78444c80-87e3-11eb-9964-d9fda24abf41.png)

![image](https://user-images.githubusercontent.com/19758978/111617526-84300e80-87e3-11eb-9136-2fc09a0bef43.png)

**Comment by philippjfr** [comment]
Will have to put a git status into the doc build GH Action workflow before the next dev release to see what is making it dirty.

**Comment by philippjfr** [comment]
Thanks for pushing on this, wouldn't have gotten fixed without you!
