### ISSUE TITLE
Audio pane not working when updating from panel 0.10.3 to 0.11.1

### ISSUE THREAD

**Issue by nghenzi** [holoviz/panel#2110]
The audio pane appears unactivated in last panel version

![image](https://user-images.githubusercontent.com/46707985/111911145-108c3c80-8a43-11eb-96a7-082c2efac6c9.png)

This is a simple code to reproduce 

import panel as pn

audio = pn.pane.Audio('http://ccrma.stanford.edu/~jos/mp3/pno-cs.mp3', name='Audio')

pn.Row('# hola', audio).servable()

**Comment by Hoxbro** [comment]
This should also be fixed with #2109
