### ISSUE TITLE
JS Module not loadable @bokehjs/styles/buttons

### ISSUE THREAD

**Issue by JackDapid** [holoviz/panel#2113]
Bokeh-2.3.0
Panel-0.11.1
Holoviews-1.14.2
geoviews-1.9.1

All is fine (nothing in logs) on the server side, but on client side JS console bokehjs:
**Error: Cannot find module '@bokehjs/styles/buttons'**

while all fine with bokeh-2.2.3 , Panel-0.10.3, Holoviews-1.14.1, geoviews-1.8.2
maybe related to #1889

**Comment by philippjfr** [comment]
Thanks @JackDapid. To be able to reproduce please provide a fully reproducible example and tell us whether you are using pip or conda.

**Comment by philippjfr** [comment]
This can happen when Bokeh 2.2.3 is still hanging around in your browser and since I haven't heard back I'll assume you've solved this.

**Comment by JackDapid** [comment]
Thanks @philippjfr - not yet fully I think, I am working on a minimal example to fully understand what was happening, part of the game is changing in our own template that we use the loading of bundled JS resources the Template resource_name from 'reacttemplate' to 'js' ... but still there is seems to be an issue with some css loadings  as many widgets look strange / overlap ... but will update here when fully resolved

**Comment by JackDapid** [comment]
Thanks @philippjfr  - was good to close it, yes seems to have been as you said some 'old' bokeh hanging around, but the real underlying issue seems to be #2156 that I tried to describe now better with a min, example and I start to look into now
