### ISSUE TITLE
jupyter_bokeh3.0  import error in ipywidget function

### ISSUE THREAD

**Issue by fleming79** [holoviz/panel#2136]
The jupyter_bokeh 3.0 release does not have BokehModel at the top level. So `panel.io.notebook.ipywidget` causes an import error when called.

```
  File "...lib\site-packages\panel\io\notebook.py", ... , in ipywidget
    from jupyter_bokeh import BokehModel
ImportError: cannot import name 'BokehModel' from 'jupyter_bokeh' (...\lib\site-packages\jupyter_bokeh\__init__.py)
```

changing to 
```
from jupyter_bokeh.widgets import BokehModel
```
resolves the import error.

Another less import issue in that function is that the line
```obj._cleanup(current[0])```
emits an error when cleaning up objects that don't have a `_cleanup` method such as for a panel Table.

**Comment by philippjfr** [comment]
Thanks for discovering that, would you submit a PR fixing the import?

>emits an error when cleaning up objects that don't have a _cleanup method such as for a panel Table.

That's odd, all Panel objects have a `_cleanup` method.

**Comment by fleming79** [comment]
The following code produces the error for me in JupyterLab:
```
import hvplot.pandas
import panel as pn
import pandas as pd
from ipywidgets import Box
b = Box([pn.ipywidget(pd.DataFrame({'a':[1,2,3,4]}).hvplot.table(height=100))])
display(b)
b.children=[]
```

**Comment by MarcSkovMadsen** [comment]
I just experienced this bug as well in vs code in a longer notebook

![image](https://user-images.githubusercontent.com/42288570/113488883-26791300-94c1-11eb-88e6-a318c1d215f6.png)

**Comment by MarcSkovMadsen** [comment]
After changing the Panel code to

![image](https://user-images.githubusercontent.com/42288570/113488999-cf277280-94c1-11eb-860f-7ca9bb57c265.png)

I get the below error in VS Code

![image](https://user-images.githubusercontent.com/42288570/113488982-bd45cf80-94c1-11eb-9c5a-ca4c22666266.png)

**Comment by fleming79** [comment]
I got the same bug but think it is something to do with VS code. This error is also emitted ([using code cells](https://code.visualstudio.com/docs/python/jupyter-support-py))
```
Error: Module @bokeh/jupyter_bokeh, semver range ^3.0.0 is not registered as a widget module 
```

**Comment by MarcSkovMadsen** [comment]
FYI. @philippjfr . See VS Code bugs above.
