### ISSUE TITLE
Panel MASTER not working in VS Code

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2145]
OS: Windows
Python: 3.8
Panel: current master
jupyter_bokeh: 3.0.0
notebook: 6.3.0

I can see that the current Panel MASTER branch does not work in VS Code via `jupyter_bokeh .

## Steps

```bash
python -m venv .venv
source .venv/Scripts/activate
pip install git+https://github.com/holoviz/panel.git
pip install jupyter_bokeh
```

In the Jupyter interactive notebook run (select code and click SHIFT+ENTER).

```python
import panel as pn
pn.extension(comms='vscode')
pn.pane.Markdown("Hello")
```

and see the error

## Error

```bash
Error: Module @bokeh/jupyter_bokeh, semver range ^3.0.0 is not registered as a widget module
```

## Screenshot

![image](https://user-images.githubusercontent.com/42288570/113657565-811b9600-969e-11eb-9715-6baa5705ecf1.png)

**Comment by MarcSkovMadsen** [comment]
I can see that running `pip install jupyter_bokeh==2.0.0` solves the problem. 

![image](https://user-images.githubusercontent.com/42288570/113658296-0d7a8880-96a0-11eb-8776-302172757dce.png)

So some how/ some where I guess VS code is running on jupyterlab 2.x ??

![image](https://user-images.githubusercontent.com/42288570/113658218-eb810600-969f-11eb-80fd-15b453a48b94.png)

**Comment by MarcSkovMadsen** [comment]
It's funny because it seems my version of jupyter lab is 3.0.12.

![image](https://user-images.githubusercontent.com/42288570/113659102-9c3bd500-96a1-11eb-9f30-8c05233017f7.png)

**Comment by MarcSkovMadsen** [comment]
I can see that the comms after downgrading do not work as nothing happens when I click the button.

![image](https://user-images.githubusercontent.com/42288570/113659627-b75b1480-96a2-11eb-8c79-a42a55ffe462.png)

**Comment by smackesey** [comment]
For anyone who upgraded, broke their VSCode/panel notebook setup, and finds this issue in an attempt to fix, here are the versions that work for me:

- VSCode Insiders 1.56.0 commit 550035808407c15252e581e8abe1b820b9d311ee
- jupyter_bokeh 2.0.4
- jupyterlab 2.3.1
- panel 0.11.1

**Comment by philippjfr** [comment]
Thanks for digging into this @MarcSkovMadsen  and @smackesey.This is not really a Panel issue, we simply have to publish `jupyter_bokeh` 3.0 to npm. So I'm going to close and reference https://github.com/bokeh/jupyter_bokeh/issues/131 as the real source of the issue instead.
