### ISSUE TITLE
Tabulator with Empty DataFrame Ajax Error

### ISSUE THREAD

**Issue by HugoMichi** [holoviz/panel#2157]
Then using the Tabulator widget with an empty DataFrame, an error is displayed, that seems to be related with Ajax.
As far as I can tell, Tabulator tries to get data from ajax if none is provided and if AjaxURL is set.
A solution to fix this could be to not set AjaxURL in https://github.com/holoviz/panel/blob/6d36858fbeb38bfb971a2b931cd821ee5253ea43/panel/models/tabulator.ts#L169
#### ALL software version info
panel                     0.11.0

#### Description of expected behavior and the observed behavior
I dont expect an error when displaying an empty table
#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import panel as pn

table = pn.widgets.Tabulator(pd.DataFrame(columns=['foo','bar']))
pn.panel(table).show()

```

#### Stack traceback and/or browser JavaScript console output
Access to fetch at 'http://panel.pyviz.org/' from origin 'http://localhost:59931' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
panel.pyviz.org/:1 Failed to load resource: net::ERR_FAILED
tabulator.js:13150 Ajax Load Error - Connection Error:  TypeError: Failed to fetch
tabulator.js:12988 Ajax Load Error:  TypeError: Failed to fetch
﻿
​
#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/7372142/114170209-df60a700-9932-11eb-88bc-a44195eaad4f.png)

**Comment by philippjfr** [comment]
Thanks! It should definitely never actually make the request, it's only specified because otherwise it errors immediatately.
