### ISSUE TITLE
Distribution Tabs Demo affected by other pages in panel-gallery

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2167]
If you go to https://panel-gallery.pyviz.demo.anaconda.com/distribution_tabs and click refresh the application will randomly look differently.

- Theme will toggle between light and dark.
- Layout will change between fixed and responsive.

This also affects the page panel [Distribution Tabs](https://panel.holoviz.org/gallery/layout/distribution_tabs.html#layout-gallery-distribution-tabs) example as reported by [brl0](https://discourse.holoviz.org/u/brl0) here https://discourse.holoviz.org/t/panel-docs-website-strangeness/2123/4.

https://user-images.githubusercontent.com/42288570/114654919-7c349300-9ceb-11eb-943c-d98b5f10fcbd.mp4

My hypothesis is that some of the pages on the site changes the global configuration of the bokeh `theme` and `panel.config.sizing_mode`. I have done this mistake my self at awesome-panel.org :-)

## Solution

Identify cause and fix.

(And potentially make it easier for users to avoid introducing this problem them selves).

**Comment by philippjfr** [comment]
With the recent changes to `pn.config` this has now finally been fixed.
