### ISSUE TITLE
Improvements of new theme

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2171]
I will add these in posts below and just keep a list here.

- [ ] 1. Horizontal Logo
- [ ] 2. Move first text lines up
- [ ] 3. Make images bigger
- [ ] 4. (re-) move reactive programming section
- [ ] 5. Add link to binder where users can try the examples out in jupyter lab without the hazzle of installing things.
- [ ] 6. Add screenshots for each environment: A picture says more than a thousand words :-)
    - Make sure that what you promise holds true :-) VS code does not work currently.
- [ ] 7. Fix discourse url reported by @Hoxbro 
- [ ] 8. Change twitter background color to Panel green.
- [ ] 9. Consider adding a link to awesome-panel.org.
- [ ] 10. Remove horizontal scrollbars if notebook cells if not needed by @Hoxbro 
- [ ] 11. Consider a link to community extensions

**Comment by MarcSkovMadsen** [comment]
# 1. Horizontal Logo

It would look nicer with a wide, rectangular logo instead of a square logo

# 2. Move first text lines up

The page is very text heavy. With a logo and image at the top and only text below. Move the images a bit down.

![image](https://user-images.githubusercontent.com/42288570/114732050-82099300-9d42-11eb-8d51-5c484a00482c.png)

**Comment by Hoxbro** [comment]
Discourse logos url is wrong `https://https//discourse.holoviz.org/`

**Comment by MarcSkovMadsen** [comment]
# 8. Change twitter background color to Panel green

![image](https://user-images.githubusercontent.com/42288570/114735017-1543c800-9d45-11eb-9031-da3c01b13fef.png)

**Comment by MarcSkovMadsen** [comment]
# 9. Consider a link to awesome-panel.org

Awesome Panel has a lot of supplementary material and can show how awesome live apps looks. But of course you will the depend on a "3.rd party".

**Comment by Hoxbro** [comment]
Maybe only having horizontal scrollbar in output of jupyter cells if needed.
![image](https://user-images.githubusercontent.com/19758978/114735418-6e136080-9d45-11eb-8521-e495cf061e3c.png)

**Comment by MarcSkovMadsen** [comment]
# 11. Consider a link to 3rd party extensions.

Currently I know
- https://pypi.org/project/awesome-panel-extensions/
- https://pypi.org/project/panel-sketch/
- https://pypi.org/project/panel-highcharts/

**Comment by philippjfr** [comment]
The majority of these items are either done or captured elsewhere. The main things I will still do before 1.0:

- Horizontal logo
- Link to awesome-panel.org in some form.
