### ISSUE TITLE
Attractors panel not found

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2172]
First example link on panel home page is not found

https://attractors.pyviz.demo.anaconda.com/attractors_panel

![image](https://user-images.githubusercontent.com/42288570/114732563-e9bfde00-9d42-11eb-93d2-15224d37823e.png)

**Comment by Hoxbro** [comment]
This seems to have been found again:
![image](https://user-images.githubusercontent.com/19758978/114761619-066b0e80-9d61-11eb-986b-2428edf8479c.png)

**Comment by jbednar** [comment]
Every three months we have to restart all deployments to update their security certificates, and in this case we took the opportunity to upgrade the underlying deployment system. Everything went smoothly and it should all be back up now!
