### ISSUE TITLE
DatetimeSlider

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#2177]
Kind of like DateSlider, but more fine-grained (able to step by hours/minutes/seconds)

**Comment by ahuang11** [comment]
Oops, duplicate
https://github.com/holoviz/panel/issues/1972

**Comment by Hoxbro** [comment]
In version 0.12 there will be a [DatetimeRangePicker](https://pyviz-dev.github.io/panel/reference/widgets/DatetimeRangePicker.html).
