### ISSUE TITLE
Allow DatePicker to accept `datetime.datetime` instead of just `datetime.date`?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#2179]
I think `datetime.datetime` is used more often compared to `datetime.date`

So that:
`pn.widgets.DatePicker(value=datetime.today().date(), name='Date')`

Can be:
`pn.widgets.DatePicker(value=datetime.today(), name='Date')`

**Comment by jbednar** [comment]
But you don't want DatetimePicker (https://github.com/holoviz/panel/pull/2107) in that case, I guess?

**Comment by ahuang11** [comment]
Yeah, I still want to be able to use datetime.datetime types in DatePicker, but DatetimePicker looks awesome!

**Comment by philippjfr** [comment]
This appears to have been supported for a while.
