### ISSUE TITLE
Make it clearer that users need 'panel examples" so Introduction data is available

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#2182]
For the introduction, there's this snippet of code:
`data = pd.read_csv('../assets/occupancy.csv')`

I think it'd be more user-friendly if there was a function to load tutorial data rather than having the user retrieve that data themself to try it out, especially since "The interactive widgets will not work in a static version of this documentation."

Similar to xr.tutorial.open_dataset(), there could be a pn.tutorial.open_dataset()? Or even down to holoviews.

**Comment by jbednar** [comment]
Other than `panel examples`?

**Comment by ahuang11** [comment]
I wasn't aware of that

**Comment by jbednar** [comment]
I'll change the title to a request that the docs make it more obvious that users need to run `panel examples` to fetch the data, then! :-) I think someone else reported that the home page doesn't say it but the Getting started does; not sure if that was captured in an issue. Worst case, this is a duplicate then. In any case, we need to fix that (PRs welcome!)!
