### ISSUE TITLE
Logo is shown above instead of on the side with FastListTemplate

### ISSUE THREAD

**Issue by Stubatiger** [holoviz/panel#2184]
Hello,

the FastListTemplate shows the provided Logo above the title like this:
```
import panel as pn

template = pn.template.FastListTemplate(
    title="Fast Panel App",
    logo="https://panel.holoviz.org/_static/logo_stacked.png"
)

template.servable()
```

![grafik](https://user-images.githubusercontent.com/4622149/114993101-c2305900-9e9b-11eb-9654-201cd0591b39.png)

Instead it should be shown beside the title, like in the other templates, for example the bootstrap template:
```
import panel as pn

template = pn.template.BootstrapTemplate(
    title="Fast Panel App",
    logo="https://panel.holoviz.org/_static/logo_stacked.png"
)

template.servable()
```

![grafik](https://user-images.githubusercontent.com/4622149/114993266-edb34380-9e9b-11eb-83d3-2d75bd1bc837.png)

This is probably because of an extra div tag in the template here:
[https://github.com/holoviz/panel/blob/c84ee569927974d6f4a20e927d2f3047ba033277/panel/template/fast/list/fast_list_template.html#L102
](https://github.com/holoviz/panel/blob/c84ee569927974d6f4a20e927d2f3047ba033277/panel/template/fast/list/fast_list_template.html#L102
)
![grafik](https://user-images.githubusercontent.com/4622149/114994732-5d75fe00-9e9d-11eb-8521-58fbfa5d1e06.png)

If the Div is removed, the log shows correctly on the side again:

![grafik](https://user-images.githubusercontent.com/4622149/114994602-3a4b4e80-9e9d-11eb-8035-e56998487d00.png)

**Comment by Stubatiger** [comment]
Hello, this issue re-appears in 0.12.0 as the changed you did (mostly just removing the <div>) are not reflected as the <div> is reintroduced in #2484

To fix this, probably its enough to recommit the changes in this PR i assume.

**Comment by MarcSkovMadsen** [comment]
Done
