### ISSUE TITLE
Tabulator filtering removes styling

### ISSUE THREAD

**Issue by Stubatiger** [holoviz/panel#2185]
Hello,

using filtering options on a styled tabulator widget, removes the styling information.

With this example code, taken from the docs at [https://panel.holoviz.org/reference/widgets/Tabulator.html](https://panel.holoviz.org/reference/widgets/Tabulator.html) from the filtering and styling sections

```
import datetime as dt
import numpy as np
import pandas as pd
import panel as pn

pn.extension()

style_df = pd.DataFrame(np.random.randn(10, 5), columns=list('ABCDE'))
styled = pn.widgets.Tabulator(style_df, page_size=5)

def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'red' if val < 0 else 'black'
    return 'color: %s' % color

def highlight_max(s):
    '''
    highlight the maximum in a Series yellow.
    '''
    is_max = s == s.max()
    return ['background-color: yellow' if v else '' for v in is_max]

styled.style.applymap(color_negative_red).apply(highlight_max)

slider = pn.widgets.RangeSlider(start=0, end=3, name='A Filter')
styled.add_filter(slider, 'A')

pn.Column(slider, styled).servable()

```

The panel looks at startup like this:
![grafik](https://user-images.githubusercontent.com/4622149/115011831-61ab1700-9eaf-11eb-966e-faf83b941e14.png)

and after using the slider widget to filter, it looks like this:
![grafik](https://user-images.githubusercontent.com/4622149/115011995-91f2b580-9eaf-11eb-8bf4-150b55128279.png)

Even after resetting the slider to the default option, the styling information is still gone:
![grafik](https://user-images.githubusercontent.com/4622149/115012090-afc01a80-9eaf-11eb-8a6d-a92b3e46ca46.png)

**Comment by philippjfr** [comment]
Can no longer reproduce this on master, please reopen if the issue persists.

**Comment by philippjfr** [comment]
Seems intermittent, reopening.

**Comment by hyamanieu** [comment]
This issue seems to be similar than that of #2165 : the styling is applied on the index of the full dataframe index, not the filtered one.
If you filter then you rerun the cell contaning your tabulator widget, you can see positive numbers become red as well if they are replacing a negative one from the unfiltered version of the df.
I'll try to submit a PR today (if not it'll take a few weeks...)

**Comment by hyamanieu** [comment]
My bad, Philip already fixed the issue I mentioned above in https://github.com/holoviz/panel/commit/c930e6ed1e22867addab1b5399625a04fc94fbb8
For some reasons I had an older version of the `_get_style_data` function in my dev environment.
However his fix modifies the background of the cell as the applied functions are reinterpreted for the filtered dataframe, not the initial full one. E.g. using the tabulator example, filtering down to one row who return all cells with a yellow background as they would all be max. It depends on how we see this feature. But this is a separate issue.

Coming back to your issue @Stubatiger : in my case (py3.7/Ubuntu 18.04/Firefox latest) the style is systematically applied if the filter modified the shown dataframe. In case moving the selector doesn't modify the shown dataframe, the style is indeed gone.
Is this what you see?

**Comment by philippjfr** [comment]
> In case moving the selector doesn't modify the shown dataframe, the style is indeed gone.

That explains it, thanks for investigating. We may have to some how force it to reapply it.

**Comment by hyamanieu** [comment]
It seems all comes down to https://github.com/holoviz/panel/blob/b73a4992a5cf2c432776095e8b3f87f433159107/panel/io/notebook.py#L56-L62 .as the bokeh object is not changing, it returns. Not sure how dangerous for the performance it would be to take that `if` out.

As for perf, after some test, I can see `_update_cds` is called 5(!) times each time the filter cursor is moved, and `_apply_update` 3 times.
