### ISSUE TITLE
Output of Reference Examples not shown in a lot of places

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2189]
An example is https://panel.holoviz.org/reference/panes/HoloViews.html

For example 

![image](https://user-images.githubusercontent.com/42288570/115042251-96c96080-9ed3-11eb-8d05-395df0679f88.png)

But it seems to be a general problem.

**Comment by philippjfr** [comment]
Huh, confused, I see output, but it's not loading the Bokeh backend like it should.

<img width="1030" alt="Screen Shot 2021-04-16 at 6 07 39 PM" src="https://user-images.githubusercontent.com/1550771/115052799-a8643580-9ede-11eb-964d-1d0efad739df.png">

**Comment by philippjfr** [comment]
"A lot of places" isn't really specific enough to be actionable. Please reopen with a concrete list of issues on the dev site: https://pyviz-dev.github.io/panel/

**Comment by philippjfr** [comment]
That said I will double check the output before releasing.
