### ISSUE TITLE
Perspective.ipynb notebook raising errors

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2193]
I'm on the current `master` branch (copied to the new `binder` branch).

Check it out https://mybinder.org/v2/gh/holoviz/panel/binder?urlpath=lab/tree/examples/reference/panes/Perspective.ipynb

![image](https://user-images.githubusercontent.com/42288570/115051953-a9489780-9edd-11eb-9452-f135bea0f38a.png)

![image](https://user-images.githubusercontent.com/42288570/115052176-ec0a6f80-9edd-11eb-99d8-44a1ae8f42b5.png)

**Comment by philippjfr** [comment]
Looks like a 0.11.4 release is in the very near future.
