### ISSUE TITLE
Rename always_watch to watch for Streamz pane

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2194]
The `Streamz` pane uses the argument `always_watch`. I suggest aligning it with the `param.depends` terminology of `watch`. It will simplify the cognitive overhead.

![image](https://user-images.githubusercontent.com/42288570/115052907-c7fb5e00-9ede-11eb-9d8c-9f808c8fdea4.png)

**Comment by philippjfr** [comment]
I don't think they have the same semantics so I'm a -1 on the renaming here.
