### ISSUE TITLE
`warn` inaccurately documented for bar_color in Progress

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#2196]
```
bar_color (str): The color of the bar, one of ‘primary’, ‘secondary’, ‘success’, ‘info’, ‘warn’, ‘danger’, ‘light’, ‘dark’
```

ValueError: warn not in Parameter bar_color's list of possible objects, valid options include [primary, secondary, success, info, danger, warning, light, dark]

**Comment by hyamanieu** [comment]
Can be closed.
