### ISSUE TITLE
DataSlider not working in Reference Notebook

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2201]
I am on the current master branch of Panel deployed to binder and the DataSlider is not working as I would expect

https://mybinder.org/v2/gh/holoviz/panel/binder?urlpath=lab/tree/examples/reference/widgets/DateSlider.ipynb

The following is not working

- Controls
    - Direction (rtl not working)
    - Orientation (vertical)
    - Tooltips (cannot be disabled)

![image](https://user-images.githubusercontent.com/42288570/115103695-38909200-9f54-11eb-9f9d-3e5a7586e76b.png)

**Comment by philippjfr** [comment]
Please do not create duplicative issues like this. This is the exact same issue as https://github.com/holoviz/panel/issues/2200 and affects all sliders.
