### ISSUE TITLE
Create Square Panel Logo in SVG Format

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2206]
I'm working on getting Panel on to binder. This includes being able to launch apps via an icon like shown below.

![image](https://user-images.githubusercontent.com/42288570/115112536-3f37fd00-9f86-11eb-9eaa-73b73f7ff610.png)

For that I need to provide an SVG file as icon. Thus I need an updated Panel Logo which is square and in SVG format.

Something you have @jbednar ?

ps. The one I am using now is called `logo_stacked.svg`. But it does not use the correct font. And to me it looks a bit different in general to the square logo used at panel.holoviz.org.

**Comment by philippjfr** [comment]
Hmm, I think at this point this request is a little stale anyway and I'll close but just to address the issue. The point of SVGs is that everything is stored in vector format including the font, if you don't have the font specified in the SVG file it'll fall back to some other font. I don't think there's much we can do about that.

**Comment by MarcSkovMadsen** [comment]
Its still an issue for me that I don't have a nice looking Panel SVG. The font is not installed on windows. So it wont look nice for windows users.

**Comment by philippjfr** [comment]
Yes indeed, there's another issue about it with more details. So I'll leave this closed.
