### ISSUE TITLE
Feature request: adjustable sidebar_width on templates

### ISSUE THREAD

**Issue by alon-sht** [holoviz/panel#2216]
It would be very helpful to have an option to adjust the width of the sidebar on the built-in templates without needing to adjust the css.

This is the current workaround that worked for me, by adjusting css:

```
import panel as pn
css = """
.mdc-drawer {
background: #FFFFFF; /* GRAY 50 */
width: 700px !important;
}
.mdc-drawer.mdc-drawer–open:not(.mdc-drawer–closing)+.mdc-drawer-app-content {
margin-left: 700px !important;
}
"""
css_pane = pn.pane.HTML("<style>" + css + "</style>", width=0, height=0, sizing_mode="fixed", margin=0)
material = pn.template.MaterialTemplate( title='Material Template',)
material.sidebar[:]=[css_pane, pn.pane.Markdown("# Title")]
material.show()
```

but a simple material.sidebar.width parameter would be amazing and super comfortable

**Comment by philippjfr** [comment]
This was implemented and you can now set `sidebar_width` on all templates.
