### ISSUE TITLE
Cannot get VTK running on Binder

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2224]
When trying to use the Panel examples on Binder I cannot get the `VTKInteractive.ipynb` working. It raises a `ImportError: libGL.so.1: cannot open shared object file: No such file or directory` error.

![image](https://user-images.githubusercontent.com/42288570/115442251-162b9c80-a212-11eb-9abc-bad6c776734a.png)

You can try it out at https://mybinder.org/v2/gh/holoviz/panel/binder?urlpath=lab/tree/examples/gallery/demos/VTKInteractive.ipynb

## Additional Context

- You can find the binder configuration in https://github.com/holoviz/panel/tree/binder/binder
- I have tried installing `libgl1-mesa-dev` as described in https://codeslake.github.io/ubuntu/docker/docker-libGL-error/. But that makes the kernel die when I run the first cell.

![image](https://user-images.githubusercontent.com/42288570/115443933-30667a00-a214-11eb-92f6-36bfdf9403e4.png)

- I have tried installing vtk from conda-forge instead of using pip.

Nothing has solved the problem.

@xavArtley . Do you have any ideas on cause and suggestions for solutions?

**Comment by MarcSkovMadsen** [comment]
I found this https://pypi.org/project/dash-vtk/ which I will try out

![image](https://user-images.githubusercontent.com/42288570/115443092-1ed0a280-a213-11eb-85cc-c5c34ec1a3a8.png)

**Comment by MarcSkovMadsen** [comment]
I tried installing `libgl1-mesa-glx` but that also makes the kernel die on running the first cell.

**Comment by xavArtley** [comment]
No sorry I have no idea. I don't know binder. Are you using the same conda environnement as the one used for github actions?

**Comment by philippjfr** [comment]
Here's the stage in our GH Actions setup that makes it work: https://github.com/holoviz/panel/blob/master/.github/workflows/test.yaml#L55

**Comment by MarcSkovMadsen** [comment]
I could not get it working by using the link provided by @philippjfr 

I got it working **in the notebook** by using the cookiecutter provided by @xavArtley 

But when I panel serve the server dies

```bash
(base) root@7916b95d4f19:/workspaces/panel/examples/gallery/demos# panel serve VTKInteractive.ipynb 
2021-04-22 04:10:36,113 Starting Bokeh server version 2.3.1 (running on Tornado 6.1)
2021-04-22 04:10:36,114 User authentication hooks NOT provided (default user enabled)
2021-04-22 04:10:36,116 Bokeh app running at: http://localhost:5006/VTKInteractive
2021-04-22 04:10:36,116 Starting Bokeh server with process id: 2024
Segmentation fault
```

For reference I also found this link https://pyvista-doc.readthedocs.io/en/latest/jupyter/ipyvtk_plotting.html which might be useful.

**Comment by MarcSkovMadsen** [comment]
UPDATE: When the server died in the post above it was when I was running things inside the docker container on my laptop. It actually works on binder using the installation instructions from pyvista

![image](https://user-images.githubusercontent.com/42288570/115659386-c3013900-a33a-11eb-9b0f-28355a3da62c.png)

Thanks for the help.

**Comment by philippjfr** [comment]
Awesome, thanks so much for your efforts here!
