### ISSUE TITLE
Holoviews plots are not height responsive anymore (bokeh 2.3.1)

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#2228]
![image](https://user-images.githubusercontent.com/18531147/115690936-d96cbc00-a35d-11eb-9b63-23c599793a8b.png)

![image](https://user-images.githubusercontent.com/18531147/115690723-9ca0c500-a35d-11eb-9329-f9c9b6c0d5e1.png)

**Comment by xavArtley** [comment]
I tracked down the origin of the regression, it appears to be this PR: https://github.com/bokeh/bokeh/pull/11123
If I uncomment the   `row.policy=="fit"` test it works as before
![image](https://user-images.githubusercontent.com/18531147/115697380-cc52cb80-a363-11eb-85b9-fb6aff75f290.png)

**Comment by mattpap** [comment]
This is clearly a bokeh regression, so re-report this in our issue tracker.

**Comment by MarcSkovMadsen** [comment]
Leonidas and I are experiencing this issue as well.

https://discourse.holoviz.org/t/vertical-responsiveness-problem-holoviews-bokeh-with-panel-serve/2299
