### ISSUE TITLE
Wrap Labels for the Trend Indicator

### ISSUE THREAD

**Issue by tlmille2** [holoviz/panel#2229]
When your labels are a long number of character's, with underscores, the Trend Indicator doesn't wrap the labels.  The long label names will then 'misbehave' their css properties.  Padding the Trend Indicator is a temporary fix, but it would be nice if a trend indicator can support wrapping of labels.

**Comment by MarcSkovMadsen** [comment]
Hi @tlmille2 

Thanks for reporting.

It would help a lot of you provided a minimum, reproducible example and a screenshot of the problem. Could you do that?

Thanks.

**Comment by tlmille2** [comment]
@MarcSkovMadsen - Here's a reproducible example and screenshot 

### Example
```python
import pandas as pd
import panel as pn
  
data = [[1, 10, 15], [2, 15, 20], [3, 20, 25], 
       [4, 25, 30], [5, 30, 35], [6, 35, 40], 
       [7, 40, 45], [8, 45, 50], [9, 50, 55]]
  
df = pd.DataFrame(data, columns = ['week', 'TEST_LONG_NAME_WITH_UNDERSCORE_1', 'TEST_LONG_NAME_WITH_UNDERSCORE_2'])

columns = df.columns

list_of_trend = []

for i in columns:
    data = df[['week', i]]
    data = data.rename(columns={"week": "x", i: "y"})
    
    trend = pn.indicators.Trend(title=i, data=data, width=200, height=200, plot_type='area')
    
    list_of_trend.append(trend)
    
pn.Row(list_of_trend[0], list_of_trend[1], list_of_trend[2])
```
![image](https://user-images.githubusercontent.com/36211553/115896808-6c225f00-a421-11eb-9e0f-93ef2bc39188.png)


### Temporary Fix Using Margins
The temporary fix is to add margins to the indicator widget

```python
import pandas as pd
import panel as pn
  
data = [[1, 10, 15], [2, 15, 20], [3, 20, 25], 
       [4, 25, 30], [5, 30, 35], [6, 35, 40], 
       [7, 40, 45], [8, 45, 50], [9, 50, 55]]
  
df = pd.DataFrame(data, columns = ['week', 'TEST_LONG_NAME_WITH_UNDERSCORE_1', 'TEST_LONG_NAME_WITH_UNDERSCORE_2'])

columns = df.columns

list_of_trend = []

for i in columns:
    data = df[['week', i]]
    data = data.rename(columns={"week": "x", i: "y"})
    
    trend = pn.indicators.Trend(title=i, data=data, width=200, height=200, plot_type='area', margin=(25, 50))
    
    list_of_trend.append(trend)
    
pn.Row(list_of_trend[0], list_of_trend[1], list_of_trend[2])
```
![image](https://user-images.githubusercontent.com/36211553/115897180-c58a8e00-a421-11eb-9e0f-927b169f18e2.png)

**Comment by philippjfr** [comment]
Thanks @tlmille2!
