### ISSUE TITLE
AttributeError: 'vtkCommonDataModelPython.vtkCellArray' object has no attribute 'ImportLegacyFormat'

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#2234]
Tests failing due to a VTK error.

cc @xavArtley 

I'll try to pin an older version of whatever caused this for now.

**Comment by xavArtley** [comment]
do you have a link to the ci build with the error?

**Comment by philippjfr** [comment]
Here: https://github.com/holoviz/panel/pull/2233/checks?check_run_id=2420491419#step:12:1363

**Comment by xavArtley** [comment]
It's strange because older version may not have the method but not newest:
![image](https://user-images.githubusercontent.com/18531147/115887551-537e6d00-a452-11eb-879d-b28f8ed1263c.png)

**Comment by philippjfr** [comment]
Yeah, just realized that too, pinned an older version and that didn't work. Will pin 9.0.1 now.

**Comment by philippjfr** [comment]
Given that it's fine using the latest version I think I'll close. Not our fault that conda does not resolve to vtk 9.0.1 by default.
