### ISSUE TITLE
Panel Serve button for Jupyter lab

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2250]
I am working on enabling a powerful environment for data analytics on Binder for Panel and on a Jupyter Hub for work.

One of the things that makes it simple for Ipywidgets/ Voila users is that there is a Voila button to launch the notebook as an app in another window.

Explaining to users that clicking the Voila button will not work for their Panel apps will not be easy. Especially as the alternative is for them to navigate to the terminal and start it via `panel serve`. To beginning Pythonistas and people who just use Notebooks that others have developed this is a problem.

## Solution

Make it simple to `panel serve` panel apps in a Jupyter Lab based environment. In the perfect world it would be possible for the user to configure the flags (for example `--auto`).

https://user-images.githubusercontent.com/42288570/116029444-a9713180-a659-11eb-9072-2ba8f7b002c8.mp4

**Comment by philippjfr** [comment]
This is now fully implemented, just need to release pyviz_comms and Panel 0.12.
