### ISSUE TITLE
max_width regression

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2253]
Panel: Master/ binder branch
Bokeh: 2.3.1

When setting the `max_width` of a layout inside a `Row` the result is no longer as expected.

The use case for this is a `Column` or `Widgetbox` where in the notebook I would like a `max_width` of for example 500 and in the sidebar of a template I just want it to `stretch_width`, i.e. stretch to ~300px.

## Actual

![image](https://user-images.githubusercontent.com/42288570/116187097-2b7a5c80-a725-11eb-989c-e9a20bd348fe.png)

```pyton
import panel as pn

pn.extension(sizing_mode="stretch_width")

settings = pn.Spacer(max_width=300, height=600, background="blue")
plot = pn.Spacer(height=600, background="red")

pn.Row(settings, plot).servable()
```

## Expected

![image](https://user-images.githubusercontent.com/42288570/116187139-3fbe5980-a725-11eb-9a93-d1e3bbf7c20d.png)

I have used the code below to generate it.

```python
import panel as pn

pn.extension(sizing_mode="stretch_width")

settings = pn.Spacer(width=300, height=600, sizing_mode="fixed", background="blue")
plot = pn.Spacer(height=600, background="red")

pn.Row(settings, plot).servable()
```

**Comment by xavArtley** [comment]
Can you test with bokeh 2.3.0? I suspect it is related to https://github.com/bokeh/bokeh/issues/11188

**Comment by philippjfr** [comment]
No longer appears to be an issue.
