### ISSUE TITLE
Error serialization with Reactive HTML and FloatSlider

### ISSUE THREAD

**Issue by nghenzi** [holoviz/panel#2256]
#### ALL software version info
panel                     0.11.1.post9+gc73fda7 
param                     1.10.1
bokeh                     2.3.0  

#### Description of expected behavior and the observed behavior
![image](https://user-images.githubusercontent.com/46707985/116222533-0f76bb00-a725-11eb-8366-229501ed6de7.png)

If I click the icon  button an error _bokeh.core.property.bases.DeserializationError: Float expected Real, got None of type NoneType_ appears.  

On the other side, if I move the FloatSlider first,  everything work ok. 

![image](https://user-images.githubusercontent.com/46707985/116222307-ddfdef80-a724-11eb-9db1-d4ff8d092299.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import param
from panel.reactive import ReactiveHTML
from panel.layout.base import ListLike

pn.config.css_files.append("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css")


class menu(ListLike, ReactiveHTML):
    clicks = param.Integer(default=0)

    icon = param.String(default='home')

    menu = param.Integer(default=0)

    label = param.String(default='')

    _template = """ 
    <div>
        <button id="btn" onclick='${btn_click}'>
            <i class="fa fa-${icon} circle-icon">
        </i></button>
    </div>

    <div>       
    {% for obj in objects %}
        <div id="dragmenu-{{ loop.index0 }}">
        ${objects[{{ loop.index0 }}]}
        </div>
    {% endfor %}
    </div>
    """ 

    def __init__(self, *objects, **params):
        super().__init__(objects=list(objects), **params)

    def btn_click(self, event):
        self.clicks += 1
        print (self.clicks)

a = menu(pn.widgets.FloatSlider(name='fs', start=0, end=10, value=1), '#2','#3')

a.servable()


```

**Comment by philippjfr** [comment]
Odd I can't reproduce, maybe bokeh 2.3.0 vs 2.3.1?

**Comment by nghenzi** [comment]
updating to 2.3.1 it works. I'll close
