### ISSUE TITLE
Panel with Plotly - Latex not rendered

### ISSUE THREAD

**Issue by Davide-sd** [holoviz/panel#2258]
#### ALL software version info
OS: Ubuntu 20.04
Chrome: Version 89.0.4389.114 (Official Build) (64-bit)
Firefox: 88.0 (64-bit)
Python: 3.8.5
Panel: 0.11.3
Holoviews: 1.14.3
Bokeh: 2.3.1
Plotly: 4.14.3

#### Description of expected behavior and the observed behavior

Whenever I use a Plotly's figure with panel, and the figure contains Latex elements, those are not rendered. This is a major annoyance because I can't export and share the plot, since nobody will understand who is what (the different lines).

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import plotly.graph_objects as go
import numpy as np
pn.extension('katex', 'mathjax', 'plotly')

controls = []
controls.append( pn.widgets.FloatSlider(name="$A_{1} \, [cm]$", start=0.01, end=2.0, value=1) )
controls.append( pn.widgets.FloatSlider(name="$A_{2} \, [cm]$", start=0.01, end=2.0, value=2) )
controls.append( pn.widgets.FloatSlider(name="$\omega_{1} \, [Hz]$", start=0.001, end=2.0, value=0.5) )
controls.append( pn.widgets.FloatSlider(name="$\omega_{2} \, [Hz]$", start=0.001, end=2.0, value=1) )

@pn.depends(*[t.param.value for t in controls])
def get_plot(A1, A2, om1, om2):
    x = np.linspace(0, 10, 100)
    f1 = A1 * np.sin(om1 * x)
    f2 = A2 * np.sin(om2 * x)

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=x, y=f1, name="$f_{1}$"))
    fig.add_trace(go.Scatter(x=x, y=f2, name="$f_{2}$"))
    fig.update_layout(
        template = "plotly_dark",
        xaxis=dict(
            title = "Position [cm]"
        ),
        yaxis = dict(
            title = "Amplitude [cm]"
        ),
        showlegend = True,
    )
    return fig

pn.Column(*controls, get_plot)
```

#### Screenshots or screencasts of the bug in action

![Screenshot_20210427_173541](https://user-images.githubusercontent.com/9921777/116271005-e6374880-a77f-11eb-9f70-3499d0232b9f.png)

As you can see, a coworker may not be able to understand the plot ... what is the red line? what is the blue line? That's a mistery.

**Comment by philippjfr** [comment]
Sorry I never got back to you here, the widget labels render correctly if you use  `$$` as the delimiters and the legend label issue also seems to have been resolved:

<img width="717" alt="Screen Shot 2023-02-17 at 21 16 43" src="https://user-images.githubusercontent.com/1550771/219784669-34e28211-fa2f-4052-9d8c-f46bce505eab.png">
