### ISSUE TITLE
Simpler cross selector

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#2259]
I was thinking of just a pn.Column(pn.widgets.AutocompleteInput, pn.widgets.MultiSelect)

Similar to the left side of this
https://panel.holoviz.org/reference/widgets/CrossSelector.html#widgets-gallery-crossselector

**Comment by xavArtley** [comment]
This one?
https://panel.holoviz.org/reference/widgets/MultiChoice.html

**Comment by ahuang11** [comment]
You're right! I overlooked that
