### ISSUE TITLE
Support custom site_url

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2278]
On Binder if you click the `site` tag you will navigate to "/" which is equivalent to "https://hub.gke2.mybinder.org/hub/". 

![image](https://user-images.githubusercontent.com/42288570/116800553-8257ab80-ab02-11eb-80ea-9253ad323e00.png)

![image](https://user-images.githubusercontent.com/42288570/116800559-926f8b00-ab02-11eb-9f25-a602451dd35b.png)

Instead you should be navigating to "./" which would be equivalent to something like "https://hub.gke2.mybinder.org/user/holoviz-panel-4bjh53ze/panel".

![image](https://user-images.githubusercontent.com/42288570/116800720-06f6f980-ab04-11eb-8d73-b7406b630509.png)

## Solution

Enable the user to specify the `site_url`. And set it to for example "/" or "./".

## Alternatives

1. Setting the hard coded site_url to "./". It wont work for complicated scenarios where the Panel app(s) might be a part of a larger site and deployed at for example "/analytics/panel-apps" on for example kubernetes. Here the user would probably like to navigate to "/". At least that is what I want for my work use case.

2. Determining from either the host part of the url in js that you are running on Binder and the set the site_url to "./". This might work for a (long) while before a user would request to be able to specify the site_url manually.

**Comment by MarcSkovMadsen** [comment]
I accidently just pushed the implementation into the master branch @philippjfr . Sorry

It's a simple change. And I have tested that it works. I believe the risk is low.

Anyways it should not be possible to push without a PR ??

It is the commits

- https://github.com/holoviz/panel/commit/f2daa4fbfb8984de72fd6e634a2accadc2ba5e29 and
-  https://github.com/holoviz/panel/commit/9984f5590416521dc823f562e9a10809aa1593f1

**Comment by philippjfr** [comment]
Yeah ideally I'll enable branch protection. The only annoyance is that to tag releases I need to bump versions in the package.json and pushing PRs for that seems silly.

**Comment by philippjfr** [comment]
Commits look good, but at some point we'll have to set you up with the notebook metadata clearing script.

**Comment by MarcSkovMadsen** [comment]
I "clear cells" manually on each notebook (I believe). But maybe that is not enough?

**Comment by jbednar** [comment]
No, that is not enough; it still leaves metadata in the notebook that
differs between every person who runs it, introducing distracting bogus
diffs when used with git. You can use nbstripout or a custom script like
strip_kernel (below).

Jim

#!/bin/bash
cp "$1" /tmp/
/usr/local/bin/jq --indent 1 \
    '
    (.cells[] | select(has("outputs")) | .outputs) = []
    | (.cells[] | select(has("execution_count")) | .execution_count) = null
    | .metadata = {"language_info": {"name":"python", "pygments_lexer":
"ipython3"}}
    | .cells[].metadata = {}
    ' "$1" > /tmp/stripped.ipynb
cat /tmp/stripped.ipynb > "$1"
