### ISSUE TITLE
Tabulator widget, download_menu options ignored

### ISSUE THREAD

**Issue by daxid** [holoviz/panel#2283]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
bokeh==2.3.1
ipykernel==5.5.3
ipython==7.23.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jupyter==1.0.0
jupyter-bokeh==3.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyter-packaging==0.9.2
jupyter-server==1.6.4
jupyter-server-mathjax==0.2.2
jupyterlab==3.0.14
jupyterlab-git==0.30.0
jupyterlab-pygments==0.1.2
jupyterlab-server==2.5.0
jupyterlab-widgets==1.0.0
notebook==6.3.0
numpy==1.19.5
pyviz-comms==2.0.1

#### Description of expected behavior and the observed behavior

When I run the official example https://pyviz-dev.github.io/panel/reference/widgets/Tabulator.html#downloading

I expect a text widget for the filename with : 

- name : "Enter filename"*
- default value : "default.csv"

However (event if I change again  text_kwargs name and value arguments) , I'm stuck with : 

- name : "Filename"
- default value : "table.csv"

in the download menu

Note : changing button_kwargs name argument result in the expected behavior : changing the text on the download button.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import pandas as pd
import panel as pn

pn.extension()

download_df = pd.DataFrame(np.random.randn(10, 5), columns=list('ABCDE'))

download_table = pn.widgets.Tabulator(download_df)

filename, button = download_table.download_menu(
    text_kwargs={'name': 'Enter filename', 'value': 'default.csv'},
    button_kwargs={'name': 'Download'}
)

pn.Row(
    pn.Column(filename, button),
    download_table
)
```

**Comment by maximlt** [comment]
Fixed by #2763
