### ISSUE TITLE
Tabulator should not be loaded by default

### ISSUE THREAD

**Issue by hyamanieu** [holoviz/panel#2284]
This issue corresponds to point 1 the Discourse post https://discourse.holoviz.org/t/serving-panel-with-plotly-extension-offline/124/11

Tabulator models have been added recently and load by default. They require external resources which is problematic in an offline context.

Not loading Tabulator by default would help making offline-compatible Panel apps.

**Comment by meverson86** [comment]
This is causing issues for me trying to use 0.11.x offline.  As expected Tabulator does not work, but also all bokeh plots generated by holoviews do not render and any panel dash making use of bokeh plots do not render either when offline.  I am stuck then using panel 0.10.x and bokeh 2.2.x.

**Comment by philippjfr** [comment]
I'll prioritize a fix here this weekend and then release 0.11.4.

**Comment by MarcSkovMadsen** [comment]
Another user having problems https://discourse.holoviz.org/t/deploy-panel-offline/2394/2

**Comment by philippjfr** [comment]
Thanks, I really just need to cut the release finally, even if that's the only fix in it.

**Comment by algol60** [comment]
I also have what appears to be this problem. A new release would be excellent, thank you.

Also, if I try and use a widget offline (for example https://panel.holoviz.org/reference/widgets/CheckButtonGroup.html#display), I get `failed to load https://unpkg.com/@holoviz/panel@^0.11.3/dist/panel.min.js` in the console. Is this part of the same problem?

**Comment by philippjfr** [comment]
@algol60 Bokeh allows selecting where it loads resources from using the `BOKEH_RESOURCES` environment variable. By default this should be set to `'server'` which means that it will be served up by the bokeh/panel server. It sounds like this is set to `'cdn'` for whatever reason in your case. If you are talking about a standalone exported HTML file then I believe `'cdn'` is the default and the only other option is `'inline'`, which will embed the resources in the HTML file itself.

**Comment by algol60** [comment]
This is using a Panel widget inside a Jupyterlab 3 notebook, but since it looks like a different problem, I won't continue here. Thanks.
