### ISSUE TITLE
Bundle Tabulator js & css files

### ISSUE THREAD

**Issue by hyamanieu** [holoviz/panel#2285]
This issue corresponds to point 2 the Discourse post https://discourse.holoviz.org/t/serving-panel-with-plotly-extension-offline/124/11

Tabulator cannot be used in an offline context, although it is planned to become the default model for DataFrame widgets.

Bundling tabulator within Panel will help facing any server scenario.

**Comment by pankajp** [comment]
Does this enable use of tabulator in an offline context in a jupyter notebook? I attempted multiple combinations of settings but never seemed to be able to make it work.

Settings attempted:
```
bokeh.settings.settings.resources = 'inline'
pn.config.inline = True
pn.io.resources.RESOURCE_MODE = 'server'  # Somewhere in panel tabulator code it checks for server mode to serve local file
pn.extension('tabulator', inline=True)
bokeh.plotting.output_notebook(resources=bokeh.resources.INLINE)
```

Is there a canonical place where it is documented how to use panel offline?

**Comment by hyamanieu** [comment]
@pankajp : look at https://panel.holoviz.org/user_guide/Overview.html#python-and-environment-variables
The canonical place is this, and what you've done with `pn.config` (or `pn.extension` for a jupyter notebook) is correct. You could also try by setting the environment variable BEFORE starting your jupyter server. 

If it does not work as intended, I would invite you to submit a bug report with a minimal example :) .

**Comment by pankajp** [comment]
Thanks @hyamanieu for your comment
And yes, setting the `PANEL_INLINE=1` environment variable before starting the jupyter notebook command doesn't work as well. I suppose this is not a well tested or supported feature, as the whole panel/holoviews stack seems to have regressed. Just filed: https://github.com/holoviz/holoviews/issues/5469 which used to work 😢
