### ISSUE TITLE
Modal alerts are not displaying on call to template.open_modal()

### ISSUE THREAD

**Issue by DSDEV27001** [holoviz/panel#2288]
#### ALL software version info

Python 3.8
Panel 0.10.3

#### Description of expected behavior and the observed behavior

The modal window should open randomly every 1 to 5 minutes.

The modal window does not open with template.open_modal() but if you put in a line that calls a function that doesn't exist within the open_modal method code, it triggers the alert to display. Setting a button to call the method open_modal() works fine.

Not 100% clear if this is bug or working as intended, so apologies if this has been misfiled.

#### Complete, minimal, self-contained example code that reproduces the issue

```
""" Modal Alert for License Expiration - minimal code example"""
import datetime as dt
import random
import functools

import asyncio
import panel as pn

COLOR = "#E1477E"

# License not expired
# LICENSE_VALID = dt.date(2021, 6, 1)

# License expired
LICENSE_VALID = dt.date(2021, 5, 1)

def no_license_alert(valid_date, template, loop=None):
    """Displays an alert message every 1 to 5 minutes
    if the software license is expired"""

    if valid_date <= dt.date.today():
        alert_text = f"""
            Your software license expired on {valid_date.strftime('%d %B %Y')}.

            Please contact us to review or extend your license.
            """
        template.modal.objects[0][0] = pn.pane.Alert(
            alert_text.format(alert_type="danger"),
            alert_type="danger",
            margin=(0, 0, 45, 0),
        )

        # NOTE: the below code does nothing
        template.open_modal()

        template._js_area.object = """
        <script>
          console.log("TRIGGERED")
          var modal = document.getElementById("pn-Modal");
          modal.style.display = "block";
        </script>
        """

        # NOTE: Inserting any code that errors here will display the alert 
        template.open_moda()

        template._js_area.object = ""

        if not loop:
            try:
                loop = asyncio.get_event_loop()
                loop.call_soon(no_license_alert, valid_date, template, loop)
            except KeyError as e:
                raise KeyError("KeyError: %s", e)
        else:
            loop.call_later(
                random.randrange(60, 360), no_license_alert, valid_date, template, loop
            )

def open_modal_btn(event, template):
    template.open_modal()

app = pn.Row(pn.pane.Markdown("## Test"))

react = pn.template.ReactTemplate(
    title="Min Alert Test",
    header_background=COLOR,
    header_color="#ffffff",
)

btn = pn.widgets.Button(
    name="Show Alert", button_type="primary", sizing_mode="stretch_width"
)

btn.on_click(functools.partial(open_modal_btn, template=react))

react.sidebar.append(btn)

react.main[:4, :6] = pn.Card(app, title="Card")

# Initialises modal with a blank a row with a blank Markdown that can be overwritten
react.modal.append(pn.Row(pn.pane.Markdown("", margin=0), margin=0))

react.servable()

no_license_alert(LICENSE_VALID, react)


```

![image](https://user-images.githubusercontent.com/52406362/116999204-3447d100-acd7-11eb-90d0-9dcba7b85830.png)

**Comment by philippjfr** [comment]
>Panel 0.10.3

Can you upgrade to 0.11.3 and see if it's still broken?

**Comment by DSDEV27001** [comment]
![image](https://user-images.githubusercontent.com/52406362/117010914-344ecd80-ace5-11eb-93b5-b823fd41bae4.png)

So I upgrade it to panel 0.11.3 as you suggested and ran it with the code below commented out from the example:
'''
        # template._js_area.object = """
        # <script>
        #   console.log("TRIGGERED")
        #   var modal = document.getElementById("pn-Modal");
        #   modal.style.display = "block";
        # </script>
        # """
        #
        # # NOTE: Inserting an error here will display the alert
        # template.open_moal()
        #
        # template._js_area.object = ""
'''
As you can see from the picture it didn't display the alert or even the button or the card at all in that example.

**Comment by DSDEV27001** [comment]
![image](https://user-images.githubusercontent.com/52406362/117011943-4aa95900-ace6-11eb-88d6-6a8be59217cd.png)

Seems like some odd bokeh errors in the console

**Comment by DSDEV27001** [comment]
2021-05-04 14:40:05,214 404 GET /static/extensions/panel/bundled/js/ajax/libs/react-grid-layout/1.1.1/react-grid-layout.min.js.map (::1) 0.43ms
2021-05-04 14:40:05,273 404 GET /static/extensions/panel/bundled/css/bootstrap/3.3.7/css/bootstrap.min.css.map (::1) 0.49ms

**Comment by DSDEV27001** [comment]
I just realised an extension was blocking this and disabled it. The alert is not displaying though.

**Comment by philippjfr** [comment]
Which bokeh version have you got? Panel 0.11.x requires bokeh>=2.3.x.

**Comment by DSDEV27001** [comment]
Hello Philip,
This is running bokeh 2.3.1 (previously I was running 2.2.3 for panel 0.10.3).
Michael

**Comment by DSDEV27001** [comment]
Hi Philip,
I would greatly appreciate some help with this issue if possible.
Thanks

**Comment by MarcSkovMadsen** [comment]
Hi @DSDEV27001 

I tried restructuring your code and believe you can get it working from the below.

Uploading expire.mp4…

```python
""" Modal Alert for License Expiration - minimal code example"""
import datetime as dt
import functools

import panel as pn

COLOR = "#E1477E"

LICENSE_VALID = dt.date(2021, 5, 1)

def open_modal_btn(event, template):
    open_modal()

app = pn.Row(pn.pane.Markdown("## Test"))

react = pn.template.ReactTemplate(
    title="Min Alert Test",
    header_background=COLOR,
    header_color="#ffffff",
)

btn = pn.widgets.Button(
    name="Show Alert", button_type="primary", sizing_mode="stretch_width"
)

btn.on_click(functools.partial(open_modal_btn, template=react))

react.sidebar.append(btn)

react.main[:4, :6] = pn.Card(app, title="Card")
modal_component = pn.Row(margin=0)
react.modal.append(modal_component)

def open_modal():
    if LICENSE_VALID <= dt.date.today():
        alert_text = f"""
            Your software license expired on {LICENSE_VALID.strftime('%d %B %Y')}.

            Please contact us to review or extend your license.
            """
        alert = pn.pane.Alert(
            alert_text.format(alert_type="danger"),
            alert_type="danger",
            margin=(0, 0, 45, 0),
        )
        modal_component[:]=[alert]

        react.open_modal()

pn.state.add_periodic_callback(open_modal, period=2000)

react.servable()
```

**Comment by DSDEV27001** [comment]
@MarcSkovMadsen I'll confirm it works on 0.11.3. Thanks for looking into this.

**Comment by DSDEV27001** [comment]
@MarcSkovMadsen this only works on the pre release of 12. So I will wait until that version makes it to production to implement this. Thanks for your help.
