### ISSUE TITLE
ReactTemplate save layout to localStorage

### ISSUE THREAD

**Issue by syamajala** [holoviz/panel#2293]
It would be nice to have an option to save a layout to localStorage. 

See: https://github.com/react-grid-layout/react-grid-layout/blob/master/test/examples/7-localstorage.jsx

**Comment by MarcSkovMadsen** [comment]
Hi @syamajala 

I think so too. Could you write a little bit about your use case and how you would expect it to work. Maybe @nghenzi is interested in something similar?

**Comment by syamajala** [comment]
I was thinking just another parameter called save_layout and if its true then you add a reset layout button to the template somewhere (maybe in the header)? 

I wouldnt mind trying to do this and making a pull request.

**Comment by nghenzi** [comment]
@syamajala it woul be great to add this option. 

I believe that one complementary functionality  would ve when the app is refreshed if the layout is saved in local storage the  layout is loaded from local storage and no from the config generated in the reactemplate class . It should be add other parameter called load_layout.

**Comment by syamajala** [comment]
@nghenzi i believe thats what the example already does: https://react-grid-layout.github.io/react-grid-layout/examples/7-localstorage.html

**Comment by nghenzi** [comment]
Great then !!  I get confused with the rendering from python

**Comment by MarcSkovMadsen** [comment]
Would you like a PR from @syamajala on this @philippjfr ?

**Comment by philippjfr** [comment]
That would be incredible.

**Comment by MarcSkovMadsen** [comment]
That would be awesome. And I would copy the solution to the FastGridTemplate too. 👍

**Comment by syamajala** [comment]
I created a pull request: https://github.com/holoviz/panel/pull/2296

**Comment by philippjfr** [comment]
This was implemented.
