### ISSUE TITLE
Add global configuration to always throttle sliders

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#2295]
#### Is your feature request related to a problem? Please describe.
When developing and working with parameterized classes, I often find myself only wanting the sliders to be throttled because of large datasets or long calculation time.

What I'm doing now is using `pn.Param` and setting `throttled=True` for each widget. An example of this could be this
``` python
import panel as pn
import param


class Example1(param.Parameterized):
    a = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    b = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    c = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    d = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    e = param.Range(default=(0.1, 0.4), bounds=(0, 2))

    def __init__(self, **params):
        super().__init__(**params)

        widgets = {
            "a": {"throttled": True},
            "b": {"throttled": True},
            "c": {"throttled": True},
            "d": {"throttled": True},
            "e": {"throttled": True},
        }

        self.widgets = pn.Param(
            self,
            widgets=widgets,
            show_name=False,
        )

    @param.depends("widgets")
    def values(self):
        return self.a, self.b, self.c, self.d, self.e


example1 = Example1()
pn.Column(example1.widgets, example1.values).servable()
```

This is very cumbersome to implement, which means I usually look it up from my previous code to get it to work. I also think it adds a lot of extra code, which takes away the focus for the actual problem I'm trying to solve.

Furthermore, I have a problem getting `watch=True` in `param.depends` to work with a slider that needs to be throttled. For example, the following code
``` python
import panel as pn
import param


class Example2(param.Parameterized):
    a = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    b = param.String(None)

    def __init__(self, **params):
        super().__init__(**params)

        widgets = {
            "a": {"throttled": True},
        }

        self.a_slider = pn.Param(
            self,
            widgets=widgets,
            show_name=False,
        )

    @param.depends("a_slider", watch=True)
    def values(self):
        self.b = str(self.a_slider.value)


example2 = Example2()

pn.Column(example2.a_slider, example2.b).servable()
```
gives this error: `AttributeError: 'Example2' object has no attribute 'a_slider'`. I'm sure there is a solution to this problem, but I don't know if it is a good solution.

#### Describe the solution you'd like
I would like to have a global configuration that changes the sliders (and inputs) to always be throttled, something like `pn.config.throttled` or similar. This would make it possible to make my code significantly cleaner. Below is how Example1 will look:

``` python
import panel as pn
import param
pn.config.throttled = True


class Example1(param.Parameterized):
    a = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    b = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    c = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    d = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    e = param.Range(default=(0.1, 0.4), bounds=(0, 2))

    @param.depends("a", "b", "c", "d", "e")
    def values(self):
        return self.a, self.b, self.c, self.d, self.e


example1 = Example1()
pn.Column(example1, example1.values).servable()
```

At the same time, it would also make it easy to implement `watch=True`:

``` python
import panel as pn
import param
pn.config.throttled = True


class Example2(param.Parameterized):
    a = param.Range(default=(0.1, 0.4), bounds=(0, 2))
    b = param.String(None)

    @param.depends("a", watch=True)
    def values(self):
        self.b = str(self.a)


example2 = Example2()
pn.panel(example2).servable()
```

#### Additional context
I have an example of how `pn.config.throttled` could be implemented. The way I have done this is to delete `value` and renaming `value_throttled` to `value` both on property change. Right now, the code is only located on my local fork [here](https://github.com/Hoxbro/panel/pull/4/files).  Below is an example of how the implementation works for sliders and inputs with the code.

<details>
  <summary>code </summary>

``` python
import panel as pn
import datetime as dt


date_range_slider = pn.widgets.DateRangeSlider(
    name="Date Range Slider",
    start=dt.datetime(2017, 1, 1),
    end=dt.datetime(2019, 1, 1),
    value=(dt.datetime(2017, 1, 1), dt.datetime(2018, 1, 10)),
)

date_slider = pn.widgets.DateSlider(
    name="Date Slider",
    start=dt.datetime(2019, 1, 1),
    end=dt.datetime(2019, 6, 1),
    value=dt.datetime(2019, 2, 8),
)

discrete_slider = pn.widgets.DiscreteSlider(
    name="Discrete Slider", options=[2, 4, 8, 16, 32, 64, 128], value=32
)

int_range_slider = pn.widgets.IntRangeSlider(
    name="Integer Range Slider", start=0, end=10, value=(2, 8), step=2
)

int_slider = pn.widgets.IntSlider(
    name="Integer Slider", start=0, end=8, step=2, value=4
)

range_slider = pn.widgets.RangeSlider(
    name="Range Slider",
    start=0,
    end=4,
    value=(2, 3),
    step=0.01,
)

float_slider = pn.widgets.FloatSlider(name="Float slider")

int_input = pn.widgets.IntInput(name="Int input")

float_input = pn.widgets.FloatInput(name="Float input")

edit_float_slider = pn.widgets.EditableFloatSlider(name="Editable FloatSlider")

edit_int_slider = pn.widgets.EditableIntSlider(
    name="Editable IntSlider", start=0, end=8, step=2, value=4
)

edit_range_slider = pn.widgets.EditableRangeSlider(
    name="Editable RangeSlider", start=0, end=8, step=2, value=(1, 4)
)

widgets = [
    date_range_slider,
    date_slider,
    discrete_slider,
    int_range_slider,
    int_slider,
    range_slider,
    float_slider,
    int_input,
    float_input,
    edit_float_slider,
    edit_int_slider,
    edit_range_slider,
]

columns = [pn.Row(w, pn.bind((lambda x: x), w)) for w in widgets]
pn.Column(pn.config.param.throttled, *columns).servable()

```
</details>

https://user-images.githubusercontent.com/19758978/117197665-609f4280-ade8-11eb-90de-e922b67b3241.mp4

#### Describe alternatives you've considered
If this feature is decided not to be added to panel. I would like it to be possible for me to patch the implementation into my own code. This seems to be possible if I change the following line of codes from `super(_SliderBase, self)` to a `super()`.

https://github.com/holoviz/panel/blob/078c8b2efa03caa742139f5ce32e47bafcc8378f/panel/widgets/slider.py#L146

https://github.com/holoviz/panel/blob/078c8b2efa03caa742139f5ce32e47bafcc8378f/panel/widgets/slider.py#L177

**Comment by jbednar** [comment]
I'd be happy to see that functionality, but it's probably best for @philippjfr to comment on the implementation.

**Comment by philippjfr** [comment]
Agreed, would be happy to see such an option on `pn.config` as well.

**Comment by Hoxbro** [comment]
Awesome! 

Should I open a PR with my implementation to start with, and then we can take it from there?
