### ISSUE TITLE
Improve cache invalidation for panel.js

### ISSUE THREAD

**Issue by znstrider** [holoviz/panel#2305]
panel serve --show app.py | app.ipynb does not show bokeh DataTable.

With those versions it works:
Bokeh: 2.2.0
Panel: 0.10.3

With bokeh==2.3.1 and panel==0.11.3 it doesn't.

Example:

```python
from bokeh.models import ColumnDataSource, DataTable, TableColumn
import pandas as pd
import numpy as np
import panel as pn

pn.extension()

df = pd.DataFrame(np.random.rand(5, 4), columns=['A', 'B', 'C', 'D'])

class PanelApp:
    def __init__(self, df):
        self.source = ColumnDataSource(df)
        self.columns = [TableColumn(field=name, title=name) for name in df.columns]
        self.data_table = DataTable(source=self.source, columns=self.columns, width=1000, height=175)
        self.table_pane = pn.pane.Bokeh(self.data_table)

panel_app = PanelApp(df)

dashboard = pn.Row(panel_app.table_pane)
dashboard.servable()

```

The browser doesn't show anything.

**Comment by philippjfr** [comment]
Just tested without any issues. Could you:

1) Force reload the browser page to ensure the cache is cleared
2) Paste the JS console output here.

**Comment by znstrider** [comment]
To add to this:
Once I switch from the environement with bokeh==2.3.1 and panel==0.11.3 to the other with bokeh==2.2.0 and
panel==0.10.3 the output first remains blank again, reloading helps.
Seems this always happens, when switching from either env.

**Comment by mattpap** [comment]
This is a version mismatch between panel and bokehjs. Given similar issues were reported recently, I think we may actually do something about this, at least providing a meaningful error message.

**Comment by philippjfr** [comment]
>Given similar issues were reported recently, I think we may actually want to do something about this, at least providing a meaningful error message.

@mattpap  Is it possible there's something wrong with the caching behavior of bokeh.js or panel.js? I frequently see users having issues like this which go away after a force-reload of the page.

**Comment by mattpap** [comment]
> Is it possible there's something wrong with the caching behavior of bokeh.js or panel.js? 

Web browsers are very aggressive about caching, so it's not an uncommon problem. However, maybe cache management headers that we use, are not enough. Those URLs have version control parameters attached, so this should encourage cache invalidation, but maybe this is somehow broken, or browsers work around this. This definitively requires attention, but in the interim we should make panel check if a matching version of bokehjs is being used. We do a similar thing in bokehjs to verify the version of bokeh that was used to serialize a document.

**Comment by rsignell-usgs** [comment]
I'm getting blank output with latest conda-forge packages as [described on Discourse here](https://discourse.holoviz.org/t/blank-output-with-latest-holoviz-from-conda-forge/2276?u=rsignell). 

@philippjfr , you can login to https://jupyter.qhub.esipfed.org to confirm if you like.

**Comment by philippjfr** [comment]
@rsignell-usgs rendered fine for after clearing the notebook, reloading the page and running it again.

**Comment by rsignell-usgs** [comment]
@philippjfr , I think you were using an environment with the older libraries.  I logged in as you and ran the notebook you created with the "pangeodev" environment, and there is no output:
```

**Comment by philippjfr** [comment]
Just logged in again, this time with the pangeodev env and it rendered without me even doing anything:

<img width="1355" alt="Screen Shot 2021-05-14 at 5 22 23 PM" src="https://user-images.githubusercontent.com/1550771/118292511-fe75ca00-b4d8-11eb-9372-b6ca6ad2e9a9.png">

**Comment by rsignell-usgs** [comment]
@philippjfr,  yep, now everything is working.  I'm so confused.

**Comment by philippjfr** [comment]
I believe these issues are largely resolved, but if they do re-occur we should have a newer issue anyway.
