### ISSUE TITLE
pn.interact not makeing widgets for the dict or list arguments containing types which can be used to make the widgets.

### ISSUE THREAD

**Issue by VinayIsHere** [holoviz/panel#2308]
suppose I have list containing following values
```
data= ['some_text', 10]
```
and I am passing this as argument to the function. i.e:
```
def fun(data):
```
so i want when I use ```panel.interact(fun)```
one ```TextInput``` and one ```IntSlider``` should come.
but it's not happening but instead if i give those values in the function arguments like below:
```
def fun(data1='sometext', data2=10):
```
then it generate the ```TextInput``` and ```IntSlider```.

**Comment by philippjfr** [comment]
Struggling to follow here, how would `pn.interact` know what your `data` argument contains? Maybe I'm misunderstanding so please provide a code sample showing exactly what you tried, e.g. how did you pass `data` as an argument.

**Comment by VinayIsHere** [comment]
actually ```pn.interact``` is not understanding the type of my data that is the problem.
Actually I was telling, if i have a function like that
``` def fun(a='text', b=10)````
then the statement ```pn.interact(fun)``` will generate two widgets ```TextInput``` and ```IntSlider```
but when I store those arguments value in some list 
```data=['text', 10]```
and defined the function like that
```
def fun(*args)
```
then calling ```pn.interact(fun) don't generate any widgets because it don't know what values my arguments will have.

What I want to do is that I have a list which contains the values which can  be created to the ```panel widgets``` and these values are stored in the list i.e ```data=['text', 10]```
so how can i define the function and use the ```pn.interact``` so that It can generate the widgets based on the values stored in the list.

**Comment by philippjfr** [comment]
This is a usage question which should be filed on the [Discourse](https://discourse.holoviz.org/). 

That said if you want variable arguments you will have to make your function accept kwargs and then provide the kwargs to the `interact` call:

```python
def fn(**kwargs):
    return kwargs

kwargs = {'a': 'text', 'b': 10}

pn.interact(fn, **kwargs)
```

Using args and a list like you are suggesting is not supported.

**Comment by VinayIsHere** [comment]
Thanks this is exactly what I wanted, actually in my task I wanted to use the dictionary only but here I give the scenerio using list as I thought it will be easy to understand for the others. Thank you very much. This four lines of code has taken full day of mine. Thanks sir.
