### ISSUE TITLE
The Panel Gallery Documentation does not contain output

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2316]
Was navigating the Gallery examples for example https://panel.holoviz.org/gallery/apis/stocks_altair.html

I can see that in a lot of places there is no output from the cells.

THIS IS A GENERAL PROBLEM ACROSS MULTIPLE PAGES @philippjfr . I see this a a MAJOR problem.

![image](https://user-images.githubusercontent.com/42288570/118225585-afeb1000-b485-11eb-8199-c2bf4200b05d.png)

**Comment by MarcSkovMadsen** [comment]
I can see it's probably by design as the Reference Examples does not have this problem and the Gallery Examples end up being shown in an `iframe`. Unfortunately the `iframe` is static and not dynamic.

https://panel.holoviz.org/gallery/apis/stocks_hvplot.html#apis-gallery-stocks-hvplot

https://user-images.githubusercontent.com/42288570/118226055-854d8700-b486-11eb-826d-ead4f36527a5.mp4

**Comment by MarcSkovMadsen** [comment]
I can see that the source application is also static https://panel-gallery.pyviz.demo.anaconda.com/stocks_hvplot

https://user-images.githubusercontent.com/42288570/118226256-e83f1e00-b486-11eb-9078-7dc450fb9423.mp4

**Comment by philippjfr** [comment]
Very strange, definitely a priority item to fix.

**Comment by philippjfr** [comment]
Output is no longer static.
