### ISSUE TITLE
Add Flexspec similar to Flexbox

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2317]
The new [Flexbox](https://github.com/holoviz/panel/pull/2233) looks awesome. But normally I need the "cells"/ "panels" to have individual sizes. For that I would need something with the api of the `Gridspec`.

If would be nice to be able to 

- Also easily style (via css or `style` parameter) to clearly separate the panels. Similarly to what is done automatically in the Fast Templates and as is done here

![image](https://user-images.githubusercontent.com/42288570/118227149-5a643280-b488-11eb-9839-7b5b4d04d9bb.png)

- It would be even more awesome if all the things of the `FastGridTemplate` was supported like `resizing`, `dragging` and `maximizing`. Indirectly something like this is requested here https://github.com/holoviz/panel/issues/2292

**Comment by philippjfr** [comment]
>But normally I need the "cells"/ "panels" to have individual sizes. For that I would need something with the api of the Gridspec

The docs maybe don't do a good job at demonstrating this since the examples all have objects of the same size but the FlexBox allows individual sizing and simply reflows the items.

**Comment by MarcSkovMadsen** [comment]
I can see it is stated in the docs. I will close this one.
