### ISSUE TITLE
pn.interact not generating the interact widget for the functions having dictionary arguments

### ISSUE THREAD

**Issue by VinayIsHere** [holoviz/panel#2324]
sir I have a function
```
def simple(val={'a':1, 'b':2}):
...
```
so when I pass simple into the ```pn.interact``` it does not generate the interact widgets for ```a and b``` as specified by the dictionary arguments in the function.

but for
```
def simple(a=1, b=2):
...
```
it generates the interactive widgets, can you please help me with this.

**Comment by philippjfr** [comment]
@VinayIsHere For support questions please post to the [Discourse](https://discourse.holoviz.org/).
