### ISSUE TITLE
Function call for widgets in parameterized class is remembered with Django

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#2326]
#### ALL software version info
``` python
bokeh                     2.3.2            py37h03978a9_0    conda-forge
channels                  2.4.0                      py_0    conda-forge
django                    3.0.9                      py_0    conda-forge
panel                     0.11.3                     py_0    pyviz
```

#### Description of expected behavior and the observed behavior
I'm running my panel app with Django and noticed that if I have a widget in a parametrized class it will remember the function call and state even when the page is reloaded. 

As I can understand Bokeh will soon remove Django support. So I'm ok with this being a `wontfix`, but I'm curious to why it remember the function call and state even after a reload.

I don't observe this behavior by running `panel serve`.  

#### Complete, minimal, self-contained example code that reproduces the issue

``` python
import panel as pn
import param


class App(pn.viewable.Viewer):
    button = pn.widgets.Button(name="Button")

    @param.depends("button.clicks", watch=True)
    def func(self):
        print("button:", self.button.clicks)

    def __panel__(self):
        return pn.Column(self.button)

```

The full django code is here: 
[django_button.zip](https://github.com/holoviz/panel/files/6496474/django_button.zip)

#### Screenshots or screencasts of the bug in action

https://user-images.githubusercontent.com/19758978/118546761-afd66300-b758-11eb-8f12-99dd1ff17b95.mp4

### Workaround
I can get it to work by changing the code to the following.

``` python
import panel as pn


class App(pn.viewable.Viewer):
    def __init__(self, **params):
        super().__init__(**params)
        self.button = pn.widgets.Button(name="Button")
        self.button.param.watch(self.func, "clicks")

    def func(self, *events):
        print("button:", self.button.clicks)

    def __panel__(self):
        return pn.Column(self.button)

````

**Comment by philippjfr** [comment]
This is imo fully expected, idiomatic Python behavior and not at all a bug. Declaring something at the class level means that all instances of that class will share that object, so if you don't want state to be shared declare the object on the instance. The only reason why this doesn't happen in the `panel serve` case is that Bokeh creates a new module every time the application is launched which means each server session redeclares the class from scratch.

On the Django side we'll come up with a solution whether that is a separate bokeh-django package or something else.

**Comment by Hoxbro** [comment]
That make sense to me, thank you for the explanation!
