### ISSUE TITLE
Possibility to create plain HTML/CSS Panels and Widgets without the automatic JS formatting

### ISSUE THREAD

**Issue by ka-steve** [holoviz/panel#2328]
#### Is your feature request related to a problem? Please describe.

According to my experience, Panel formats every Panel and Widget element by constantly modifying style parameters via JavaScript and creating a very rigid layout for the current viewport, and then changing all the value every time the viewport changes or there are some changes in the layout. I'm not even convinced if this is ever a good idea, but that's beside the point. What I'm sure of is that for more complex projects, this creates a very fragile layout that can easily break without the developer having any control over it. 

 - One of the main problems seems to be that Panel assumes it knows every necessary information to make the correct calculations and set everything into stone, but often it does not take some css attributes of some elements into consideration, thus assuming incorrect available space and setting incorrect with/height or positional (top/left...) values. 
 - These settings are put into the style HTML attribute thus overwriting every predefined CSS classes or other definitions (except !important definitions that could cause even more trouble). 
 - Panel forces us to put styling options (like margin) into a widget definition, preventing separation of functionality and presentation. 
 - These styling options have much narrower capabilities, like for example there is no way to define different margin values for :first- and :last-childs, not to talk about practically losing the ability to use advanced CSS techniques in a web application, like an actual full-blown responsive grid.
 - The combination of these last two points causes that if you want to set a parameter based on a parent HTML element state, you have to do some parallel calculations in python and set the parameter dynamically, so you not only have to do this on the server-side, nothing can affect this from outside of your python script. This is fine for functionality, but styling could depend on a lot of other factors.
 - And again, as I mentioned, it is really prone to break. 

For example here is a project I'm currently developing. It shouldn't be hard to use a fluid+fixed 2 column full height layout. In CSS this is a solved issue for at least a decade. And yet, this is my 3rd totally different approach, this time with two flexbox columns, both of them containing an embed(), and weird issues like this just keep happening. This time the hover tool somehow makes Panel think something is wider than it is and thus Panel quickly resizes something and that makes the two elements not to fit next to each other, so the sidebar breaks below. That is until a window resize event is triggered, even if the viewport hasn't even changed (that's what I'm doing in the console). 

![hGFp7nDJyt](https://user-images.githubusercontent.com/4239832/118701872-7e22d200-b814-11eb-88f9-b4b098f09337.gif)

Now I don't consider this specific example a "bug", as of course, this is an edge case, I've put a lot of stuff together not necessarily the way it was intended, so I don't expect a JS engine to be able to take everything into consideration. And even if this would be debugged, there would be the next "bug" like this and the next, etc, as I've already had a dozen similar experiences in the last few weeks.

#### Describe the solution you'd like
I'd like to be able to turn off the JS sizing engine globally for every Widget and Panel. To the best of my knowledge, there is no reason why every form elements and accompanying static HTML elements should be hard formatted by JS. There can be some specific custom widgets that would require JS for their functionality, but even in those cases, I'm convinced that 99% of their styling could be done in CSS. And for most of the elements, not formatting them would be actually very-very easy. An H1, an Hr or a Div would look fine without any additional formatting, and if any styling is needed it is very easy to do so in CSS with much more precision. 

Slightly off: If I recall correctly, there already is an effort to revamp the pane.HTML() to a more flexible one that would allow to wrap children elements into custom HTML code. This feature would work together perfectly with that one giving much more control to the users over their own code but assuming disabling a feature based on a config value could be done more quickly, this feature in itself could provide a huge benefit.

**Comment by philippjfr** [comment]
Thanks for your excellent writeup here @ka-steve. This is in fact something we are acutely aware of and is something we are actively working towards. The background here is that Panel is built on top of Bokeh, which is first and foremost a plotting library, which also has a very flexible Model/View architecture, a powerful Tornado based server **and** a layout engine which is responsible for sizing, measuring and aligning different components. This makes sense in the context of a plotting library but in the context of a complex dashboard or application it has all the various drawbacks that you mention. So what are we doing about it:

- @mattpap on the Bokeh team is currently rewriting the layout engine from scratch to leverage CSS layouts instead of taking control of the layout via Bokeh's own custom layout implementations. He should have a very concrete enhancement proposal on this ready in the next few days.
- At the same time I set out to build the `ReactiveHTML` component which as you mentioned allows leveraging HTML and CSS to layout components yourself and also allows embedding children inside these custom layouts. This has in fact already been merged and will be part of the 0.12.0 release. There's a ton more examples for me to add but you can check out the basic design [here](https://pyviz-dev.github.io/panel/user_guide/Custom_Components.html) and install the 0.12 dev release using `pip install --pre panel==0.12.0a11` or `conda install -c pyviz/label/dev panel=0.12.0a11`. I'd love to hear your feedback here.

**Comment by MarcSkovMadsen** [comment]
You nailed it so much @ka-steve . Can’t wait to get css based layouts in Bokeh 3.0 👍

**Comment by ka-steve** [comment]
Just to make sure we're on the same page because I maybe created some confusion by mentioning the ReactiveHTML component.

Currently, if I write this:
```
slider = pn.widgets.FloatSlider(name='Slider', start=0, end=1, value=0)
select = pn.widgets.Select(options=['1', '2'], value='1')
content = pn.Column(slider, select, css_classes=['column_class'])
```
I get this HTML code:

```
<div class="bk column_class" style="position: relative; display: block; left: 0px; top: 0px; width: 320px; height: 48px; margin: 0px;">
    <div class="bk slider_class" style="position: absolute; display: block; left: 10px; top: 5px; width: 300px; height: 38px;">
        <div class="bk bk-input-group">
            <div class="bk bk-slider-title">Slider: <span class="bk bk-slider-value">0</span></div>
            <div class="bk noUi-target noUi-ltr noUi-horizontal noUi-txt-dir-ltr">
                <!-- the actual code of the slider -->
            </div>
        </div>
    </div>
    <div class="bk select_class" style="position: absolute; display: block; left: 10px; top: 53px; width: 300px; height: 31px;">
        <div class="bk bk-input-group">
            <label class="bk" style="display: none;"></label>
            <select class="bk bk-input"><option class="bk" value="1">1</option><option class="bk" value="2">2</option></select>
        </div>
    </div>
</div>
```
The main issue that bothers me is that I don't want the column div or the select and slider container divs to have any of the current styles hardcoded and then updated every time Panel feels like it. If they would just simply go away, I would be very happy. Of course, I still need the functionality of the widgets themselves, so they have to work the same way, being able to link them to other elements or functions, I just don't want their containers to be constantly resized in this absolute-relative scrapbook style.

On top of this, it would be nice if I could opt for a bare widget, for example in the case of the select I could set a `bare=True` and the generated code would be only the `<select class="bk bk-input"><option class="bk" value="1">1</option><option class="bk" value="2">2</option></select>` part without any divs and label as that would let me wrap the select however I want. But this is not that important as the previous point as I can deal with a few extra divs if they are not hard formatted.

I feel these points are pretty independent of the last two points @philippjfr mentioned:
 - ReactiveHTML looks awesome, but as far as I understand, that's about making it possible to create whatever element we'd like.  What I'm talking about is the possibility to use the already existing Widgets and Panels without the hardcoded formatting. (Btw, I have a pressing deadline tomorrow, but I will definitely try it after that as it looks really promising for what it offers.)
 - The templating functionality is something I already use. The template of the gif above looks somehow like this:
```
<div class="row row_content">
    <div class="col col_map_fluid_width">{{ embed(roots.content) }}</div>
    <div class="col col_widgetbar_fixed_width">{{ embed(roots.widgets) }}</div>
</div>
```
And that was exactly my issue, that even though I have a template styled by CSS, that works perfectly fine with any other content, the fixed JS sizing of the Panel Widgets makes it break. In that specific example the problem was that when a map hover tool reached the edge of the viewport, it triggered the body scrollbar which decreased the available viewport width. This wouldn't be normally a problem, as everything in the sidebar could be flexible with their widths, but since Panel formatted them with hardcoded widths, suddenly they became wider than the shrunk available space and had to break below. I found a workaround, but I've also had dozens of similar issues where I also had to find a workaround. And since I need the widget functionality, I can not create these elements in the template itself...

So I assume the Bokeh base is the root of the problem and that rewriting will be the solution too? I knew Panel used the Bokeh server and I've seen the `bk` classes in the HTML code, but I never would have imagined it uses Bokeh to "plot" the non-plot HTML elements too. If this is the case I assume it is not possible to detach the Panel Widgets and Panels to run their own layout engine (otherwise you already would have done it) as the Bokeh server requires everything to be handled by Bokeh? 

But even if so, is it possible to start with turning off the JS formatting for just these elements in Bokeh? I guess it's not that easy as setting a `do_formatting=False` in the Bokeh source code, but still, it probably could go live faster than the whole layout engine rewrite and it would already result in significant benefits.

**Comment by philippjfr** [comment]
Ping @mattpap for any thoughts on this and particularly how this relates to the layout refactor you're working on.

**Comment by ka-steve** [comment]
Just an update that no matter what I did, Bokeh kept sizing my widgets wider than the available space for them, so I had to resort to using CSS !important to force the browser to ignore the JS sizing (`.widget_col` is the class of my widget container):

```
.widget_col div.bk:not(.bk-input-group):not(.bk-slider-title):not(.noUi-target)
{
position: static!important;
top: initial!important;
left: initial!important;
width: initial!important;
height: initial!important;
}
```

The :not(...) classes are elements I did not want to reset as even though they have the .bk class, they are not being forcibly resized. I only use Selects and Sliders that were relevant, but with more type of elements, this :not() list could become pretty long quickly.

After this, this is how I can format anything (the repeated :not()s are necessary to create high enough specificity to overwrite the reset rule above), for example, a widget_label - widget_content block:

```
.widget_col div.bk:not(.bk-input-group):not(.bk-slider-title):not(.noUi-target).widget_label
{
display: inline-block!important;
width: 25%!important;
}

.widget_col div:not(.bk-input-group):not(.bk-slider-title):not(.noUi-target).bk.widget_content
{
display: inline-block!important;
width: 75%!important;
}
```

Pretty sure this is the ugliest CSS code I've ever written, and I'm not sure this wouldn't ever freak out the Bokeh engine as its instructions are completely disregarded, but so far it works. I have to pay special attention to specificity and have to declare a lot of parameters with !important, but at least I can set width, height, margin, padding etc freely and most importantly: in a way that enables a fluid and responsive layout without breaking all the time.

**Comment by MarcSkovMadsen** [comment]
Hi @ka-steve . Have you tried using `sizing_mode="stretch_width`? I normally just apply `pn.extension(sizing_mode="stretch_width")` and then I have far fewer problems.

**Comment by ka-steve** [comment]
Yes, I've experimented with the sizing_modes. The problem is, that "stretch_width" is not "letting the width stretch" instead it is "calculating in JS what the current width would be of the width would be allowed to stretch and hardcoding that into the element style". And if anything is miscalculated in JS, then that wrong value is used. The sizing_mode only affects the way the JS engine tries to figure out how wide the elements should be, not the way they get or not get hardcoded into the style attribute, at least as far as I understand...

**Comment by philippjfr** [comment]
On branch main which is using bokeh 3.1.0dev3 the layout is no longer managed by bokeh and you have the ability to inject custom styling and whole stylesheets with the `styles` and `stylesheets` parameters.
