### ISSUE TITLE
DateRangeSlider returns datetimes once used

### ISSUE THREAD

**Issue by cjw296** [holoviz/panel#2337]
#### ALL software version info

panel 0.11.3
bokeh 2.3.2
param 1.10.1

#### Description of expected behavior and the observed behavior

Once a `DateRangeSlider` has been adjusted, it's `value` will contain `datetime` instances rather than `date` instances.
This breaks consumers that expect a `date` object.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
from datetime import date
date_slider = pn.widgets.DateRangeSlider(start=date.min, end=date.max)
pn.Column(date_slider, pn.bind(lambda dates: repr(dates), dates=date_slider))
```

https://github.com/holoviz/panel/issues/1972 suggests there should be a separate `DatetimeRangeSlider`, an while I think that's necessary, I also think `DateRangeSlider` should be configurable to *always* return `date` instances, or *always* return `datetime` instances, but never an inconsistent mix of the two.

**Comment by philippjfr** [comment]
This appears to have been resolved at some point.
