### ISSUE TITLE
pane Audio fails in np array example

### ISSUE THREAD

**Issue by daniel-andreasen** [holoviz/panel#2338]
#### software version info:
panel: 0.11.3
numpy: 1.19.2
scipy: 1.6.1
Bokeh: 2.3.2
jupyter lab: 3.0.14
notebook: 6.2.0
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Firefox Quantum 68.4.1esr (32bit) (and Chrome Version 81.0.4044.122 (Official Build) (64-bit))
Windows 10 Enterprise version 1909

#### Description of expected behavior and the observed behavior

I failed to run the alternative numpy-array example at https://panel.holoviz.org/reference/panes/Audio.html. It produces an inactive widget, which can not play any audio and the total time counter shows 0:00. In the JS console it gives the error:

---------

Invalid URI. Load of media resource 0,203,406,609,812,1014,1216,1417...

---------

I then tried to run the corresponding example for the widgets audio widget (from https://panel.holoviz.org/reference/widgets/Audio.html) and it works without any problems.

I have tested this in both firefox and chrome.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import panel as pn

pn.extension()

sps = 44100 # Samples per second
duration = 10 # Duration in seconds

modulator_frequency = 2.0
carrier_frequency = 120.0
modulation_index = 2.0

time = np.arange(sps*duration) / sps
modulator = np.sin(2.0 * np.pi * modulator_frequency * time) * modulation_index
carrier = np.sin(2.0 * np.pi * carrier_frequency * time)
waveform = np.sin(2. * np.pi * (carrier_frequency * time + modulator))
    
waveform_quiet = waveform * 0.3
waveform_int = np.int16(waveform_quiet * 32767)

# This does not work
pn.pane.Audio(waveform_int, sample_rate=sps)  

# This works
# pn.widgets.Audio(value=waveform_int, sample_rate=sps)

```

#### Stack traceback and/or browser JavaScript console output
JavaScript console output:
![image](https://user-images.githubusercontent.com/77624306/119961471-60890180-bfa6-11eb-87d6-fbc534efd389.png)

I am not sure what the stack traceback is

#### Screenshots or screencasts of the bug in action

In firefox

![image](https://user-images.githubusercontent.com/77624306/119962444-56b3ce00-bfa7-11eb-8d0a-d438bdf7fa85.png)

In chrome:

![image](https://user-images.githubusercontent.com/77624306/119962635-8a8ef380-bfa7-11eb-9448-5f634a674196.png)

**Comment by rhhyon** [comment]
I'm encountering the same issue when trying to use a bumpy input to pn.pane.Audio(). pn.widgets.Audio() works, though. 

Do I need to somehow install the newest dev version of panel to get the fix?
