### ISSUE TITLE
Handle per-session config

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#2350]
Currently the `pn.config` is simply a global object, which usually isn't a problem. However when you're launching multiple applications on a Bokeh/Panel server this means the config is shared between them, which can cause real issues. A simple example are the `js_files` and `css_files` configuration options. Whenever one application requires one of these then all other applications will inherit these options. To avoid this we should isolate options which should not be shared and either create a per-session instance of the config object or create a WeakKeyDictionary for the per-session state, which is queried first.

**Comment by MarcSkovMadsen** [comment]
Very much needed.
