### ISSUE TITLE
Tabulator shows Nan if column name contains '.'

### ISSUE THREAD

**Issue by m1pro** [holoviz/panel#2354]
#### ALL software version info
panel 0.11.3
bokeh 2.3.1
pandas 1.2.4

#### Description of expected behavior and the observed behavior

When column name in a data frame contains periods Tabulator rendered column with Nan values
Does not happen if '_' or ',' are used in column names

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import datetime as dt
df = pd.DataFrame({
    'int': [1, 2, 3],
    'flo.at': [3.14, 6.28, 9.42],
    'str': ['A', 'B', 'C'],
    'bool': [True, False, True],
    'date': [dt.date(2019, 1, 1), dt.date(2020, 1, 1), dt.date(2020, 1, 10)]
}, index=[1, 2, 3])

df_widget = pn.widgets.Tabulator(df)
df_widget

```

**Comment by Stubatiger** [comment]
Its kind of an "Feature" of Tabulator see here https://github.com/olifolkerd/tabulator/issues/2911

**Comment by m1pro** [comment]
I think passing the nested field separator is a good idea.

**Comment by philippjfr** [comment]
This has already been fixed on master.

**Comment by philippjfr** [comment]
Thanks for filing this issue in any case, for reference see: https://github.com/holoviz/panel/pull/2289

**Comment by m1pro** [comment]
@philippjfr I've uninstalled panel 0.11.3 and reinstalled from master. 
I see the added line 171 in models/tabulator.ts: nestedFieldSeparator: false, 
but still get Nans.
