### ISSUE TITLE
Slider is no longer styled correctly in Fast Templates

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2369]
It used to look like

![image](https://user-images.githubusercontent.com/42288570/121463549-8f45a580-c9b2-11eb-856d-bf5a3a7ce428.png)

Now it looks like below on current MASTER branch

![image](https://user-images.githubusercontent.com/42288570/121463639-aedcce00-c9b2-11eb-8cdf-b42848046b0d.png)

FYI. @philippjfr . I will try to fix it. This really needs to get in before releasing the next version. Without it the Fast templates are not really useful.

**Comment by MarcSkovMadsen** [comment]
Code

```python
import panel as pn

slider = pn.widgets.FloatSlider(value=2, start=0, end=10, step=0.1)

pn.template.FastListTemplate(site="Panel", title="FloatSliderFix", sidebar=[slider]).servable()
```

![image](https://user-images.githubusercontent.com/42288570/121840708-0e9de680-ccdd-11eb-92b4-56620e7bf4e4.png)

**Comment by nghenzi** [comment]
I have seen some problems with the cpn.Card in the fast templates, but I am not sure if the css I am adding. Due to that I din´t report it.

**Comment by MarcSkovMadsen** [comment]
Please add any issues with Cards @nghenzi . I will fix them. Seeing examples will help me get it fixed.
