### ISSUE TITLE
Card in FastList templates render content in the header of the card

### ISSUE THREAD

**Issue by nghenzi** [holoviz/panel#2379]
The card renders well without the template. 

![image](https://user-images.githubusercontent.com/46707985/121843765-d66ac800-cd1d-11eb-99ff-2757877d041b.png)

With the template the header occupy more space, then it results in 

![image](https://user-images.githubusercontent.com/46707985/121843834-f5695a00-cd1d-11eb-933f-e4a314f379dd.png)

```
import panel as pn

d = pn.Card(pn.widgets.FloatSlider(name='Slider'),'#Hola', background = 'white')

tmpl = pn.template.FastListTemplate(theme=pn.template.DarkTheme)
tmpl.main.append(pn.Row(d))
tmpl.servable()
```

**Comment by MarcSkovMadsen** [comment]
## Workaround

Set `header="&#8203;"`.
 
![image](https://user-images.githubusercontent.com/42288570/123534620-ac9ea180-d71e-11eb-864b-e0c2f2f840d4.png)

```python
import panel as pn

d = pn.Card(pn.widgets.FloatSlider(name='Slider'),'#Hola', background = 'white', header="&#8203;")

tmpl = pn.template.FastListTemplate(theme=pn.template.DarkTheme)
tmpl.main.append(pn.Row(d))
tmpl.servable()
```

**Comment by MarcSkovMadsen** [comment]
## Cause and Potential Solution

![image](https://user-images.githubusercontent.com/42288570/123534687-2040ae80-d71f-11eb-9d13-a33219c34295.png)

![image](https://user-images.githubusercontent.com/42288570/123534697-3babb980-d71f-11eb-9df3-3e9f648dde90.png)
