### ISSUE TITLE
GridSpec with nested columns / rows not rendered in jupyter

### ISSUE THREAD

**Issue by cyruoff** [holoviz/panel#2386]
When adding a Column that contains a Row to a GridSpec, the gridspec is not rendered in panel 0.11.3.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
python : 3.8.5
panel : 0.11.3
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
OS : ubuntu 18.04
browser : firefox

#### Description of expected behavior and the observed behavior

Having a pn.Column of widgets inside a pn.GridSpec works as expected.
However, when adding a pn.Row to the column and adding it to the GridSpec, as in the example below, the GridSpec is not rendered anymore.

#### Complete, minimal, self-contained example code that reproduces the issue
```
import panel as pn
pn.extension()

print(pn.__version__)

gspec = pn.GridSpec()
gspec[0, 0] = pn.Column(pn.pane.Markdown(f'### Test'), 
                        pn.Row(pn.widgets.FloatInput(name='Start'), pn.widgets.FloatInput(name='End')))
gspec[0, 1] = pn.Spacer(background='red', margin=0)

gspec
```
does not display any widgets

**Comment by philippjfr** [comment]
Could not reproduce on master, please reopen if you can still reproduce with a Panel dev release (or Panel 0.12.0 due to be released this week).
