### ISSUE TITLE
Similar to pn.state.cache, can there be a pn.state.async_run(func, *args, **kwargs)

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2396]
Basically, I want to run tasks in the background, or https://discourse.holoviz.org/t/how-to-panel-with-worker-thread/947 without having to read all that.

Would be nicer with a decorator @pn.state.async_run (like @dask.delayed) that submits a job to the background when a watched widget value is changed.

**Comment by philippjfr** [comment]
I guess I'm not quite sure what you're after, `async_run` implies something very different from threading. Indeed if all you want is async support you can already attach asynchronous callbacks to `.param.watch` as long as you are using Python >=3.8:

```python
slider = pn.widgets.FloatSlider()

layout = pn.Column(slider)

async def callback(event):
    await asyncio.sleep(3)
    layout.append(event)
    
slider.param.watch(callback, 'value')

layout
```

**Comment by andhuang-CLGX** [comment]
Wow neat!
```
import asyncio
import panel as pn
pn.extension()

slider = pn.widgets.FloatSlider()

layout = pn.Column(slider)

def callback_first(event):
    layout.append("first")

async def callback(event):
    await asyncio.sleep(3)
    layout.append("second")

def callback_last(event):
    layout.append("last")

slider.param.watch(callback_first, 'value')
slider.param.watch(callback, 'value')
slider.param.watch(callback_last, 'value')

layout
```

**Comment by andhuang-CLGX** [comment]
Any ideas about getting around `TypeError: DynamicMap does not accept coroutine type, data elements have to be a ('ViewableElement', 'NdMapping', 'Layout').`

**Comment by philippjfr** [comment]
Without knowing what you're doing precisely it's hard to say, but that sounds like a HoloViews issue if anything.

**Comment by andhuang-CLGX** [comment]
I want to update a dynamic map asynchronously.

**Comment by MarcSkovMadsen** [comment]
Could you provide a minimum working example @andhuang-CLGX and package versions?

**Comment by ahuang11** [comment]
I guess similar to how Tiles work independently of what is running as a Python process? e.g. you can process something but still zoom in and load a Tile while processing something else. Is there a "pn.submit_job_in_background()" going on for the Tile? If so, I would like that exposed.

**Comment by andhuang-CLGX** [comment]
I think `pn.state.onload(some_function)` is what I was looking for
