### ISSUE TITLE
Horizontal scroll bar improperly positioning components

### ISSUE THREAD

**Issue by eric-yates** [holoviz/panel#2403]
#### ALL software version info

Panel - 0.11.3
Python - 3.7.9
Bokeh - 2.3.2
Browser - Firefox 89.0.1 (64-bit)

The bug also occurs in Chrome and Safari, so it appears to be browser independent.

#### Description of expected behavior and the observed behavior

The code is expected to produce a horizontal scrollbar of fixed-width components. 

Its observed behavior has the components overlapping each other in position, those hiding parts of the components.

The screenshot at the bottom should make it pretty clear.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

row = pn.Row(
    pn.Column(1, height=400, width=500, sizing_mode='fixed', background='blue'),
    pn.Column(2, height=400, width=500, sizing_mode='fixed', background='red'),
    pn.Column(3, height=400, width=500, sizing_mode='fixed', background='green'),
    pn.Column(4, height=400, width=500, sizing_mode='fixed', background='orange'),
    scroll=True
)

row.show()
```

#### Stack traceback and/or browser JavaScript console output

Python traceback:

```
Launching server at http://localhost:60998
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.53ms
```

Console output:

```
[bokeh] setting log level to: 'info' bokeh.min.js:184:1350
[bokeh] Websocket connection 0 is now open bokeh.min.js:585:3565
[bokeh] document idle at 23 ms bokeh.min.js:165:1329
Bokeh items were rendered successfully bokeh.min.js:163:859
```

#### Screenshots or screencasts of the bug in action

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/32752674/122504642-eac9f180-cfb7-11eb-8e66-4e8037d96468.png">

Notice that the 2nd div is positioned inside the end of the 1st div. It appears to me that the left/right positions are mixed up.

**Comment by eric-yates** [comment]
I realized that I set the default sizing_mode to stretch_width, and that seems to have been causing the issue. Is this expected behavior?

**Comment by MarcSkovMadsen** [comment]
I would say its not expected behavior.

As I see it your use case is adding 4 fixed sized items into a row. You would like to be able to scroll across that row no matter the width of the screen. I would implement that as you described.

**Comment by MarcSkovMadsen** [comment]
## Workaround

But a workaround would be to wrap it into an additional `Row` or `Column`.

https://user-images.githubusercontent.com/42288570/122653270-e3375380-d143-11eb-9af3-70766a476187.mp4

```python
import panel as pn
pn.extension(sizing_mode="stretch_width")

pn.Row(
    pn.Row(
        pn.Row(1, height=400, width=500, sizing_mode='fixed', background='blue'),
        pn.Row(2, height=400, width=500, sizing_mode='fixed', background='red'),
        pn.Row(3, height=400, width=500, sizing_mode='fixed', background='green'),
        pn.Row(4, height=400, width=500, sizing_mode='fixed', background='orange'),
        sizing_mode="fixed"
    ), scroll=True
).servable()
```

@eric-yates

**Comment by philippjfr** [comment]
Yeah this is definitely not expected.

**Comment by philippjfr** [comment]
This was fixed as part of the Bokeh 3.x layout rewrite.
