### ISSUE TITLE
Document Tabulator configuration parameter

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2408]
I'm on the current master branch of Panel (pre 0.12 release) and also using the dev documentation https://pyviz-dev.github.io/panel/reference/widgets/Tabulator.html.

## Context

I would like to be able to disable sorting of the headers of the Tabulator table. But don't see any parameters that can be used for this. 

In Tabulator.js this can be done via

```js
var table = new Tabulator("#example-table", {
    headerSort:false, //disable header sort for all columns
});
```

See http://tabulator.info/docs/4.9/sort

## Workaround

While seeing what it would take to support this I found out you can actually specify the `configuration` parameter in Python

```python
import pandas as pd
import datetime as dt
import panel as pn

pn.extension("tabulator", sizing_mode="stretch_width")

df = pd.DataFrame({
    'int': [1, 2, 3],
    'float': [3.14, 6.28, 9.42],
    'str': ['A', 'B', 'C'],
    'bool': [True, False, True],
    'date': [dt.date(2019, 1, 1), dt.date(2020, 1, 1), dt.date(2020, 1, 10)]
}, index=[1, 2, 3])

df_widget = pn.widgets.Tabulator(df, configuration={"headerSort": False})
df_widget.servable()
```

![image](https://user-images.githubusercontent.com/42288570/122652749-a87fec00-d140-11eb-876c-1321c8013e0d.png)

## Solution

- Add functionality corresponding to `headerSort` and/ or
- Document the `configuration` parameter.

As a start it would be nice to know what the preferred solution is.

**Comment by philippjfr** [comment]
We can't possibly expose all parameters for Tabulator but it's always a balancing act. As a start we should definitely document the `configuration` parameter since it provides a workaround even if we decide to eventually expose a parameter explicitly.

**Comment by MarcSkovMadsen** [comment]
I really like the idea of make the `configuration` an official and documented part of the api. That will give a lot of flexibility.
