### ISSUE TITLE
Sizing mode 'stretch_both' in panel v0.11.3

### ISSUE THREAD

**Issue by Jhsmit** [holoviz/panel#2414]
I'm having difficulties getting my figures to stretch both dimensions on panel 0.11.3 while the code I use does work for panel 0.11.0

#### ALL software version info
**Buggy behaviour versions**
python 3.8, windows, mozilla firefox
bokeh                     2.3.2            py38haa95532_0
panel                     0.11.3             pyhd3eb1b0_0
holoviews                 1.14.4             pyhd3eb1b0_1

**Working verions**
bokeh                     2.3.0            py38haa244fe_0    conda-forge
panel                     0.11.0             pyhd8ed1ab_0    conda-forge
holoviews                 1.14.2                     py_0    pyviz

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import holoviews as hv
from holoviews.streams import Buffer
import pandas as pd
import panel as pn
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource

data = pd.DataFrame({'x': [], 'y': [], 'count': []}, columns=['x', 'y', 'count'])
buffer = Buffer(data=data, length=int(1e6), index=False)

scatter = hv.DynamicMap(hv.Scatter, streams=[buffer])
scatter.opts(color='count', xlim=(0, 5), ylim=(0, 5), cmap='jet', responsive=True)

fig = figure()
source = ColumnDataSource(data={'x': [], 'y': [], 'color': []})
fig.scatter(x='x', y='y', color='color', source=source, line_color=None)


template = pn.template.FastGridTemplate(
    title='FastGridTemplate')


template.main[:2, :6] = pn.pane.HoloViews(scatter, sizing_mode='stretch_both')
template.main[:2, 6:] = pn.pane.Bokeh(fig, sizing_mode='stretch_both')

pn.serve(template)

```
I get the following result where sizing does not work:
<img src="https://user-images.githubusercontent.com/7881506/122999430-8ee3dc00-d3ae-11eb-9913-c91fb088824b.png" width=50% height=50%>

Expected result:
<img src="https://user-images.githubusercontent.com/7881506/122999531-af139b00-d3ae-11eb-9e79-1c303f397c31.png" width=50% height=50%>

This appears to be the same for other templates

**Comment by philippjfr** [comment]
Thanks for the detailed report, this is the same issue as:

https://github.com/bokeh/bokeh/issues/11161
https://github.com/holoviz/panel/issues/2228
https://github.com/bokeh/bokeh/issues/11188

So you can track the progress on this in bokeh. Will close this as a duplicate.
