### ISSUE TITLE
Y-axis labels of HoloViews plot in Fast Template does not position them selfes well

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2426]
I'm on the current master branch of Panel (pre 0.12 release)

![image](https://user-images.githubusercontent.com/42288570/123208118-cc378f00-d4be-11eb-8544-699ea200ee4c.png)

```python
import panel as pn
import pandas as pd
import holoviews as hv

pn.extension(sizing_mode="stretch_width")
hv.extension("bokeh")

ACCENT_COLOR = "#FDAC53"
data = pd.DataFrame(
    {
        "x": [1,2,3,4],
        "y": ["A"*10, "B"*4, "C"*6, "D"*3]
    }
)
plot = hv.Points(data).opts(color=ACCENT_COLOR, marker="o", size=25)
plot_panel = pn.pane.HoloViews(plot)

template=pn.template.FastListTemplate(
    title="Fast HoloViews",
    main=[plot_panel],
    header_background=ACCENT_COLOR,
    header_accent_base_color="white",
    accent_base_color=ACCENT_COLOR,
)
template.servable()
```

## Additional Context

Changing the template to `pn.template.VanillaTemplate` fixes the problem

![image](https://user-images.githubusercontent.com/42288570/123208463-6d264a00-d4bf-11eb-8f66-7e353eecfccb.png)

**Comment by MarcSkovMadsen** [comment]
## Cause/ Workaround

By removing a line from the the Panel file `theme.py` I can work around the problem.

![image](https://user-images.githubusercontent.com/42288570/123208969-3ef53a00-d4c0-11eb-8e16-7aaf05d52244.png)

![image](https://user-images.githubusercontent.com/42288570/123209075-63511680-d4c0-11eb-9dee-ce87c4e4e933.png)

A few questions for you @philippjfr 

- Is this a bug in Bokeh? Can bokeh not place the axis labels correctly if the font-size is changed? Should this be files as a bug with Bokeh?
- Is there a better workaround that can make this work without going back to very small font sizes?

**Comment by philippjfr** [comment]
>Is this a bug in Bokeh? Can Bokeh not place the axis labels correctly if the font-size is changed? Should this be filed as a bug with Bokeh?

@mattpap Does bokeh not like relative sizes like `em`?

**Comment by mattpap** [comment]
Possibly this is related to https://github.com/bokeh/bokeh/issues/11110, though there were other regressions to text rendering in 2.3.x. What version of bokehjs is being used and what's the content of JS console?

**Comment by MarcSkovMadsen** [comment]
Thanks @mattpap. 

**bokeh py**

![image](https://user-images.githubusercontent.com/42288570/123284457-8e615780-d50c-11eb-8a08-4cc2a160ee5a.png)

**console**

![image](https://user-images.githubusercontent.com/42288570/123284202-5ce88c00-d50c-11eb-855a-bdb13aad3c99.png)

**bokeh js**

![image](https://user-images.githubusercontent.com/42288570/123284344-78539700-d50c-11eb-8808-40f333c13b9b.png)

**Comment by mattpap** [comment]
This is definitively https://github.com/bokeh/bokeh/issues/11110 and it will be fixed 2.3.3.

**Comment by MarcSkovMadsen** [comment]
Thanks @mattpap 

FYI @philippjfr. I wanted to create a fix to temporarily workaround this problem. Unfortunately I pushed it directly to master. It's here https://github.com/holoviz/panel/commit/630a71cd4d0e337c7828e313796330e9ae5c4de2. I don't believe it will cause any problems. Please check it out and let me know. Thanks.

**Comment by philippjfr** [comment]
Resolve in bokeh, closing.
