### ISSUE TITLE
Cannot change sidebar width with custom css

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2431]
Semi convinced that this is a bug; I also tried modifying the source code at `/home/user/miniconda3/lib/python3.7/site-packages/panel/template/material.css` and there's still no effect

```
import panel as pn

RAW_CSS = """
.mdc-drawer {
background: #FAFAFA; /* GRAY 50 */
width: 1000px !important;
}

.mdc-drawer.mdc-drawer--open:not(.mdc-drawer–closing)+.mdc-drawer-app-content {
margin-left: 1000px !important;
}
"""

pn.config.sizing_mode = 'stretch_width'
pn.extension(raw_css=[RAW_CSS])

template = pn.template.MaterialTemplate()
template.sidebar.append(pn.widgets.Select())

template.servable()
```

**Comment by nghenzi** [comment]
I think you need to change the css in site-packages/panel/dist/bundled/materialtemplate/material.css

**Comment by andhuang-CLGX** [comment]
Is there a way to use raw_css without editing source code?

**Comment by nghenzi** [comment]
If with !important does not work, i do not know.

**Comment by MarcSkovMadsen** [comment]
In panel 0.12 and the current master branch support for custom sidebar width has been added to all templates.

**Comment by philippjfr** [comment]
Right, this is imo sufficiently addressed now.
