### ISSUE TITLE
AutocompleteInput options underlaid

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2434]
is there a way to use CSS to fix this?
```
import panel as pn

pn.config.sizing_mode = 'stretch_width'
pn.extension()

template = pn.template.MaterialTemplate()
template.sidebar.extend([pn.widgets.AutocompleteInput(options=["test"] * 1000), pn.widgets.Select(options=["a", "b", "c"]), pn.widgets.Select(name="under")])

template.servable()

```
![image](https://user-images.githubusercontent.com/83971150/123468319-d5078e00-d5ae-11eb-8a18-edd1bc9fd6db.png)

**Comment by Stubatiger** [comment]
i assume this has something to do with #2186 and is probably an underlying bokeh issue.

**Comment by MarcSkovMadsen** [comment]
## Workaround

You can wrap the widgets in a `pn.Column`.

![image](https://user-images.githubusercontent.com/42288570/123664018-42c5eb00-d837-11eb-8b34-d6a5153abf94.png)

```python
import panel as pn

pn.config.sizing_mode = "stretch_width"
pn.extension()

pn.template.MaterialTemplate(sidebar=[pn.Column(
    pn.widgets.AutocompleteInput(options=["test"] * 1000),
    pn.widgets.Select(options=["a", "b", "c"]),
    pn.widgets.Select(name="under"),
)
]
).servable()
```

**Comment by MarcSkovMadsen** [comment]
Panel 0.12.4, Bokeh: 2.4.0, Browser: Edge and Firefox, Os: Win

I was just trying out the first code and can no longer reproduce

![image](https://user-images.githubusercontent.com/42288570/137679561-4a0a0e9c-bb57-4707-8ef7-fccfa921fa2a.png)

```python
import panel as pn

pn.config.sizing_mode = 'stretch_width'
pn.extension()

template = pn.template.MaterialTemplate()
template.sidebar.extend([pn.widgets.AutocompleteInput(options=["test"] * 1000), pn.widgets.Select(options=["a", "b", "c"]), pn.widgets.Select(name="under")])

template.servable()
```

I will close this one. Feel free to reopen @andhuang-CLGX if you can still reproduce the problem.
