### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by arifin-chemist89** [holoviz/panel#2458]
This is the follow up of the discussion on the discourse.
https://discourse.holoviz.org/t/authentication-issue/2482

#### Description of expected behavior and the observed behavior
I could use the OAuth2 protocol  with Gitlab (and Github) as the authentication server. However, when it is redirected to the apps through your redirect URI, “500: Internal server error” is obtained. 

#### Error on Panel server log
```
2021-05-27 07:16:48,184 Uncaught exception GET /login?next=%2Fdashboard%3Fcode%3D7db8792a4a6294eaf73d16f38715c55729b80ecb408acdc11c21f7097a20e695%26state%3D3da727364438451b9d52aa5d04154171 (10.67.23.208)
HTTPServerRequest(protocol=‘http’, host=‘someIP:Port’, method=‘GET’, uri=’/login?next=%2Fdashboard%3Fcode%3D7db8792a4a6294eaf73d16f38715c55729b80ecb408acdc11c21f7097a20e695%26state%3D3da727364438451b9d52aa5d04154171’, version=‘HTTP/1.1’, remote_ip=‘ipAddress’)
Traceback (most recent call last):
File “/opt/conda/envs/dashboard/lib/python3.7/site-packages/tornado/web.py”, line 1704, in _execute
result = await result
File “/opt/conda/envs/dashboard/lib/python3.7/site-packages/panel/auth.py”, line 246, in get
user = await self.get_authenticated_user(**params)
File “/opt/conda/envs/dashboard/lib/python3.7/site-packages/panel/auth.py”, line 110, in get_authenticated_user
client_secret
File “/opt/conda/envs/dashboard/lib/python3.7/site-packages/panel/auth.py”, line 453, in _fetch_access_token
user = decode_response_body(user_response)
File “/opt/conda/envs/dashboard/lib/python3.7/site-packages/panel/auth.py”, line 40, in decode_response_body
body = codecs.decode(response.body, ‘ascii’)
UnicodeDecodeError: ‘ascii’ codec can’t decode byte 0xe5 in position 18: ordinal not in range(128)
```

#### Software version info
The python environment were built FROM continuumio/miniconda3 docker.
bokeh                             2.3.2
panel                             0.11.3

#### Additional comments
I could solve this problem when I replace  ‘ascii’ to  ‘UTF-8’ on panel/auth.py. Other small issue on the authentication is that --oauth_extra_params is unrecognized arguments, but it is not big deal since I can export it as PANEL_OAUTH_EXTRA_PARAMS.
`panel: error: unrecognized arguments: --oauth_extra_params=
`

**Comment by philippjfr** [comment]
Thanks, will get a fix in shortly.

>oauth_extra_params is unrecognized arguments

The argument is `--oauth-extra-params`.

**Comment by arifin-chemist89** [comment]
My bad. Did not realized that all arguments are using - instead of _. Thanks for confirmation.
