### ISSUE TITLE
Plotly tab preprocessor hook not activated when saving template

### ISSUE THREAD

**Issue by thomasbangels** [holoviz/panel#2473]
First of all I want to thank @philippjfr for the very quick response to my previous bug reports. Unfortunately, I was able to find another bug when I combine two recently added features (saving of templates & interactive plotly figures in tabs). The save procedure of the template does not trigger the preprocessor hook of the plotly tabs. As a result, plotly figures which overlap with other plotly figures in different tabs are not interactive.

Here is a code snippet to reproduce the problem:
``` 
import numpy as np
import panel as pn
import plotly.graph_objects as go

pn.extension('plotly')

plots = pn.Tabs(tabs_location="left")

x = np.arange(10)
p1 = go.Scatter(x=x, y=x**2, marker={"color": "red"})
p2 = go.Scatter(x=x, y=x**3, marker={"color": "green"})
plots.append(("quadratic", p1))
plots.append(("cubic", p2))

template = pn.template.BootstrapTemplate(title='Bootstrap Template')

template.main.append(plots)
template.save("plotly_tabs_in_template.html")
```

I had a look at the source code and found out that when I enable a preprocessing step in template/base.py:156, all works as expected. This is the code I modified (from template/base.py).
```
    def _init_doc(self, doc=None, comm=None, title=None, notebook=False, location=True):
        ...
        for name, (obj, tags) in self._render_items.items():
            if self._apply_hooks not in obj._hooks:
                obj._hooks.append(self._apply_hooks)
            # OLD CODE =======================
            # We skip preprocessing on the individual roots
            # model = obj.get_root(doc, comm, preprocess=False)
            # NEW CODE -----------------------
            model = obj.get_root(doc, comm, preprocess=True)
            # ========================
            mref = model.ref['id']
            doc.on_session_destroyed(obj._server_destroy)
```

I must admit that I have no clue what the overall impact would be from this change, but I hope it helps for fixing the bug.

Version info:
```
panel   git revision 5eef5fa45dbb874980718c10ac819142420a3407 (2021-07-01 02:23:14)
bokeh   2.3.2
param   1.10.1    
plotly  4.9.0
python  3.8.5
OS      Ubuntu 20.04
```

**Comment by philippjfr** [comment]
Thanks for catching this. That fix isn't going to work unfortunately because triggering the preprocessors for each root separately is quite expensive and it should run the preprocessor across all roots in a later step. I'll take a look.
