### ISSUE TITLE
Make it easy to modify Panel components by Template AND Theme

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2482]
I would like it to be really easy for users to create awesome looking apps in Panel. One way is using the built in Templates.

The templates do this to some extend. 

One example of custom styling is that I would like to be able to style Plotly, Altair etc. panes depending on the template AND theme chosen. For example for the Fast templates I would like the plotly plots to have a dark theme if the template is using a dark theme.

## Solution

Add modifiers on a Theme level c.f. https://github.com/holoviz/panel/pull/2425#issuecomment-872981314

**Comment by philippjfr** [comment]
We do have modifiers on Themes now.
