### ISSUE TITLE
Support Tabulator scrollToRow

### ISSUE THREAD

**Issue by douglas-raillard-arm** [holoviz/panel#2485]
#### Is your feature request related to a problem? Please describe.
Being able to scroll inside the table programmatically is very useful when linking plots with custom interactivity with some tabular data.

#### Describe the solution you'd like
An API allowing to scroll to the given row, and possibly linked to a stream so that a holoviews plot X position can scroll directly in a table displayed under it.

Tabulator seems to already have support for scrolling programmatically:
http://tabulator.info/docs/4.1/navigation#scroll-row

#### Describe alternatives you've considered

pn.widgets.DataFrame() automatically scrolls when its "selection" attribute is modified. It would be nice to have a similar behavior for Tabulator.

EDIT: add alternative

**Comment by philippjfr** [comment]
I'm out on vacation this week but will work a little bit on Thursday to release Panel 0.12. If a PR to implement this were to magically appear before then I'd happily merge it and get it into this release :)

**Comment by douglas-raillard-arm** [comment]
First time I touch Javascript in ~14 years but I'll give that a shot, I guess it should not be too hard :)

**Comment by douglas-raillard-arm** [comment]
So as a starter I was contemplating scrolling to the currently selected row, like pn.widgets.DataFrame. I tried this:
```
import panel as pn
pn.extension('tabulator')
import pandas as pd

df = pd.DataFrame(dict(a=[1,2], b=[3,4]))
df = pd.concat([df]*10)
df = df.reset_index(drop=True)

table = pn.widgets.Tabulator(df, height=100)
table

# Experiment with jscallback to see how it works
value1 =   pn.widgets.Spinner(value=0, width=75)
result =   pn.widgets.StaticText(value='0', width=50, align='center')

value1.jscallback(value="""
  result.text = v1.value.toString()
""", args={'result': result, 'v1': value1, 'thetb': table})

pn.Row(value1, result)
```

In the little experiment with jscallback, everything works well, until I add `'thetb': table` to the `args` dict. I tried some `console.log()` to no avail. It looks like that binding the Tabulator widget to a callback like that breaks the callback, which never fires. 

Any idea on what is happening ?
