### ISSUE TITLE
Download link on Getting Started page doesn't download all the necessary files

### ISSUE THREAD

**Issue by ablythed** [holoviz/panel#2486]
On the [Getting Started page](https://pyviz-dev.github.io/panel/getting_started/index.html), the link to download locally only saves the Introduction.ipynb notebook, not any of the other files like images that are required for the notebook to run. Instead,  maybe the link should download a zip file with all the necessary files.

**Comment by philippjfr** [comment]
There is no more download link, since we now allow users to open the notebooks directly in JupyterLite.
