### ISSUE TITLE
Tabulator not working in FastListTemplate in v0.12.0rc3

### ISSUE THREAD

**Issue by thomasbangels** [holoviz/panel#2491]
The Tabulator widget is broken when it is used in the FastListTemplate (see screenshot below). This is only since version v0.12.0rc3. In the previous release candidate (v0.12.0rc2), it worked beautifully.

![image](https://user-images.githubusercontent.com/53470294/124431750-0fbcb380-dd71-11eb-9fcc-c4ba22770897.png)

Code used to illustrate the problem:
```
import pandas as pd
import panel as pn

data = pd.DataFrame({'letter': ['A', 'B', 'C']})

table = pn.widgets.Tabulator(data)

# Tabulator in BootstrapTemplate works in v0.12.0rc2 and v0.12.rc3
# template = pn.template.BootstrapTemplate()

# Tabulator in FastListTemplate works in v0.12.0rc2, but not in v0.12.rc3
template = pn.template.FastListTemplate()

template.main.append(table)
template.save("template_table.html", resources="inline")
```

Version info:
```
panel   0.12.0rc3
param   1.10.1    
pandas  1.1.0
python  3.8.5
OS      Ubuntu 20.04
```

**Comment by MarcSkovMadsen** [comment]
I know @philippjfr has add a new `theme` based on a new Fast style sheet for Tabulator. Maybe that stylesheet has to be published to `npm` before it works. C.f. https://github.com/holoviz/panel/pull/2425

Maybe it will work if you the Tabulator `theme` to `simple` manually for now?

**Comment by philippjfr** [comment]
Hmm, but it should already be published now that there is an RC release out. @thomasbangels could you look at the Javascript console and paste any errors related to the CSS here?

**Comment by thomasbangels** [comment]
Sure, is this information enough?

![image](https://user-images.githubusercontent.com/53470294/124458936-e3fbf680-dd8d-11eb-8a10-0d09d95cac21.png)

```
Failed to load resource: net::ERR_INVALID_URL

template_table.html:1 Refused to apply style from 'https://cdn.jsdelivr.net/npm/@holoviz/panel/dist/bundled/tabulator-tables@4.9.3/dist/css/fast/tabulator_fast.min.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

template_table.html:216 [bokeh] setting log level to: 'info'

template_table.html:197 [bokeh] document idle at 23 ms

/static/extensions/panel/icons/favicon.ico:1 Failed to load resource: net::ERR_FILE_NOT_FOUND

template_table.html:1 Refused to apply style from 'https://cdn.jsdelivr.net/npm/@holoviz/panel/dist/bundled/tabulator-tables@4.9.3/dist/css/fast/tabulator_fast.min.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

DevTools failed to load source map: Could not load content for file:///home/bangels/python_scripts/panel.js.map: System error: net::ERR_FILE_NOT_FOUND
```

**Comment by thomasbangels** [comment]
I just retested using v0.12.0rc4 and it works :)

**Comment by MarcSkovMadsen** [comment]
Thanks for reporting and testing @thomasbangels . I am just looking so much forward to get Fast Template improvements out there including this one
