### ISSUE TITLE
GridSpec is broken in responsive sizing mode

### ISSUE THREAD

**Issue by mathrick** [holoviz/panel#2493]
#### ALL software version info
```
Python version      :  3.8.10 (default, Jun  2 2021, 10:49:15) 
IPython version     :  7.24.1
Tornado version     :  6.1
Bokeh version       :  2.3.2
BokehJS static path :  /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/bokeh/server/static
```
Tried this with both 0.12a20, 0.12a21, and 0.12rc4.

#### Description of expected behavior and the observed behavior
There are two problems I've observed in responsive mode:

1. The responsive mode doesn't make any difference whatsoever to the resulting gridspec's size. If I pass no explicit size arguments to the constructor, it will always assume the default 800x600 and will never get smaller than that. No amount of `sizing_mode` and `height_policy` fiddling that I could find made any difference, which makes it entirely useless for UI layout
2. In the `GridSpec.ipynb` in the docs, the responsive mode example is completely garbled, and results in a weird layout where every element is gigantic and bigger than my screen (see screenshots)

#### Complete, minimal, self-contained example code that reproduces the issue
Just run all cells in the `GridSpec.ipynb` to see the broken layout

#### Stack traceback and/or browser JavaScript console output
No visible errors reported

#### Screenshots or screencasts of the bug in action
This is what I see with `sizing_mode="stretch_both"` (yes, that is literally all you can see on the screen at once):
![gridspec-broken](https://user-images.githubusercontent.com/179487/124523709-0a7d5a00-ddad-11eb-999b-0c4b321a745e.png)

vs. non-responsive:

![gridspec-nonresponsive](https://user-images.githubusercontent.com/179487/124523793-62b45c00-ddad-11eb-83b1-2085771e985e.png)

Both screenshots are taken from the [user guide notebook](https://panel.holoviz.org/reference/layouts/GridSpec.html), just with `.show()` added and the `sizing_mode=` taken out for the second screenshot.

**Comment by MarcSkovMadsen** [comment]
I believe https://github.com/bokeh/bokeh/pull/11394 and bokeh 2.3.3 will solve this.

**Comment by mathrick** [comment]
Ah. In that case, should I open a separate ticket for the fact that the responsive sizing mode isn't actually responsive?

**Comment by philippjfr** [comment]
Can confirm that Bokeh 2.3.3 resolved this. So I'll close this one, but I am wondering what you mean about responsive sizing mode not being responsive so please do reopen if you are still able to reproduce this after installing 2.3.3.
