### ISSUE TITLE
Flexbox doesn't wrap its contents with direction=column

### ISSUE THREAD

**Issue by mathrick** [holoviz/panel#2494]
Flexbox doesn't seem to wrap its contents at all when the direction is specified as `column`. This is perfectly demonstrated by the current render of the development version docs: https://pyviz-dev.github.io/panel/reference/layouts/FlexBox.html

![screenshot](https://user-images.githubusercontent.com/179487/124524678-d3a94300-ddb0-11eb-9019-d34874c26416.png)

**Comment by mathrick** [comment]
I tried playing with the browser devtools a bit, and it seems that it's missing `height: 100%` in the CSS for the generated `<div class="flex">`

**Comment by philippjfr** [comment]
Thanks for discovering this and suggesting the fix.
