### ISSUE TITLE
Support multi item paste in MultiChoice

### ISSUE THREAD

**Issue by ItamarShDev** [holoviz/panel#2495]
Is this possible to add  support to paste multiple items at once in the MultiChoice input?

If it is, and need to be developed, I would be happy to help in doing it, if I could get some guidance where to start 

Thank you!

**Comment by mattpap** [comment]
`MultiChoice` widget is based on https://github.com/Choices-js/Choices, so you would have work it out there. Then bokehjs would get this functionality by proxy. However, the project doesn't seem to be actively developed anymore.

**Comment by ItamarShDev** [comment]
Thank you for your response.
If I were to create a new widget, where should I start?

**Comment by brunorpinho** [comment]
@ItamarShDev I would start with the `ReactiveHTML` object. There is a very useful example [here](https://pyviz-dev.github.io/panel/user_guide/Custom_Components.html#child-templates) .
