### ISSUE TITLE
Is it possible to have pn.SlideShow?

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2500]
Slide show as in like any photo app that lets you click on or swipe the left/right and it goes to the next photo / object.

With translucent arrow keys overlaid on objects (useful for photos).

**Comment by jbednar** [comment]
Anything's possible! That sounds very handy.

**Comment by MarcSkovMadsen** [comment]
Panel 0.12 willintroduce the ReactiveHTML component. One of the examples in the docs is a slideshow.
