### ISSUE TITLE
Panel master jupyter notebook layout tabulator messed up

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2504]
```
import pandas as pd
import panel as pn
pn.extension("tabulator")
mixed_df = pd.util.testing.makeMixedDataFrame()
filter_table = pn.widgets.Tabulator(mixed_df)

filter_table.add_filter((0, 3), 'A')

slider = pn.widgets.RangeSlider(start=0, end=3, name='A Filter')
filter_table.add_filter(slider, 'A')

select = pn.widgets.MultiSelect(options=['foo1', 'foo2', 'foo3', 'foo4', 'foo5'], name='C Filter')
filter_table.add_filter(select, 'C')

pn.Row(
    pn.Column(slider, select),
    filter_table,
    height=500,
    width=1000
)
```
![image](https://user-images.githubusercontent.com/83971150/124791874-b3d96280-df09-11eb-8d4d-9eaa1d10dab1.png)

**Comment by MarcSkovMadsen** [comment]
If I run the above in jupyterlab on the current master branch of Panel (pre 0.12) it works for me. Panel 0.12 can be released any day now.

![image](https://user-images.githubusercontent.com/42288570/124860034-3e28d180-dfb1-11eb-8d0d-ceddeb6836bf.png).

What you can do @andhuang-CLGX is to look in the browser console. I've experienced that sometimes there is a `js` error in the browser console that causes the problems you see.
