### ISSUE TITLE
Tabulator not working on current MASTER branch

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2507]
Hi @philippjfr 

**I believe this has to be solved before Panel 0.12 can be released!**

I'm on the current MASTER branch (pre panel 0.12 release).

I was trying to help on https://github.com/holoviz/panel/issues/2496. But when I run the small Tabulator example below with `panel serve 'script.py' --auto --show` it does not display 

```python
import pandas as pd
import panel as pn

pn.extension("tabulator")

df_orig = pd.DataFrame({"Column": ["A", "B", "C", "D"],
                        "Scenario": ["1", "1", "1", "1"],
                        "Number": [1,2,3,4]})
tabulator = pn.widgets.Tabulator(df_orig)
tabulator.servable()
```

Instead I see a blank screen and tons of errors in the browser console

![image](https://user-images.githubusercontent.com/42288570/124861694-5bab6a80-dfb4-11eb-9ddd-aa14479f5834.png)

**Comment by philippjfr** [comment]
Absolutely cannot reproduce this, I think you simply haven't rerun `python setup.py develop`.

**Comment by MarcSkovMadsen** [comment]
Can confirm this. I ran `panel build panel` and `python -c "from panel.compiler import bundle_resources;bundle_resources()" which I have been doing for a long time. But apperantly that is not enough.

**Comment by philippjfr** [comment]
>I actually thought python setup.py develop did not work for me. It did not use to (I think). But now it does.

That would be very worrying and should always be caught immediately since that is what CI tests run every time.

**Comment by MarcSkovMadsen** [comment]
Ahh now I think I know. The problem was in the "old days" some other install or rerun was recommended (??) that did not work for me on windows.
