### ISSUE TITLE
Panel sizing mode bokeh==2.3.2 vs bokeh==2.3.3 has big differences

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2517]
may make a minimal example later, but just wanted to note that there's some big changes to sizing_mode='stretch_width' in one minor version release

**Comment by philippjfr** [comment]
2.3.3 fixes a variety of regressions which happened in 2.3.1, so yes this is annoying but it also restores the old behavior. Please reopen if there's any weird side-effects.
