### ISSUE TITLE
Perspective Viewer not showing data in Reference Guide and on current MASTER

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2518]
If you look at the [Perspective reference guide](https://panel.holoviz.org/reference/panes/Perspective.html), then the first example is lacking data

![image](https://user-images.githubusercontent.com/42288570/125097261-3ca4f980-e0d6-11eb-84a9-0bed9241dc6b.png)

It's the same if I use the current MASTER branch (pre 0.12 release). 

![image](https://user-images.githubusercontent.com/42288570/125097808-c8b72100-e0d6-11eb-8231-ce7b76c7f343.png)

(I have run `python setup.py develop` and done a hard refresh).

```python
import panel as pn
import pandas as pd

pn.extension("perspective", sizing_mode="stretch_width")
data = {'x': [1, 2, 3], 'y': [1, 2, 3]}

perspective=pn.pane.Perspective(data).servable()
```

**Comment by MarcSkovMadsen** [comment]
The cause seems to be some js libs that cannot be found

![image](https://user-images.githubusercontent.com/42288570/125098795-a540a600-e0d7-11eb-882e-1648c999628c.png)

![image](https://user-images.githubusercontent.com/42288570/125098846-b1c4fe80-e0d7-11eb-8ef5-8a51f8491384.png)

FYI. @philippjfr .

**Comment by philippjfr** [comment]
Yep noticed this too today, will fix before releasing.
