### ISSUE TITLE
Make a button with svg content

### ISSUE THREAD

**Issue by jsignell** [holoviz/panel#253]
I have an icon.svg that I downloaded and am storing next to my panel object.

I can render it using pn.Row like so:
<img width="424" alt="screen shot 2019-02-28 at 12 25 31 pm" src="https://user-images.githubusercontent.com/4806877/53585583-46a4ae00-3b54-11e9-9bb2-de7277be57f5.png">

I'd like to be able to use that svg as the contents of a button. Something like:

```python
pn.widgets.Button('icons/baseline-search-24px.svg')
```

**Comment by jbednar** [comment]
Great idea.  Is PNG already supported?  If not I'd guess PNG support would be more urgent than SVG.

I don't see anything about graphical buttons on the Bokeh site, so presumably this would need a feature request there first (unless I missed it).

**Comment by jsignell** [comment]
I think only text is supported at the moment. I've never seen graphical buttons on bokeh either.

**Comment by MarcSkovMadsen** [comment]
I really would like that as well. It would be a very important building block for acceptable UX in an enterprise.

**Comment by MarcSkovMadsen** [comment]
But in general for styling it would be really, really nice if it was acceptable 

- Enter HTML and Markdown as "text" input to Buttons and similar

```python
button = pn.widgets.Button("<i class="fas fa-home"></i>Home")
```

- Wrap panes and widgets into custom HTML

```python
button = pn.widgets.Button()
template = """
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    {button}
  </div>
</div>"""
button_in_card = pn.layout.Template(
    template=template,
    button=button,
)
```

**Comment by xavArtley** [comment]
May be not very user friendly but here is a small workaround https://discourse.bokeh.org/t/image-button/2363/4?u=xavier_artusi

**Comment by MarcSkovMadsen** [comment]
If you need this you can use the `awesome_panel_extensions.widgets.ImageButton` until something like that reaches Panel.

The implementation is here

https://github.com/MarcSkovMadsen/awesome-panel-extensions/blob/master/awesome_panel_extensions/widgets/link_buttons/image_link_button.py

**Comment by MarcSkovMadsen** [comment]
It's now relative easy to make this using `ReactiveHTML`.

```python
class ImageButton(pn.reactive.ReactiveHTML):
    svg = param.String(doc="The SVG")
    clicks = param.Integer()
    value = param.Event()
    button_type = param.ObjectSelector(default='default', objects=BUTTON_TYPES)

    _template = """<button class="bk bk-btn bk-btn-${button_type}" type="button" id="pn_image_button" onclick="${_increment}">{{svg}}</button>"""

    def _increment(self, _):
        self.clicks+=1
        self.param.trigger('value')
```

which looks like 

https://user-images.githubusercontent.com/42288570/132986213-bfe31711-1f82-465b-8d19-8c45bce94271.mp4

**Comment by MarcSkovMadsen** [comment]
I would think the example I just posted would be a nice, basic example to add to the Panel `ReactiveHTML` part of the Gallery.

But would it make sense to include a `ImageButton` in Panel or just make images have clicks events in general in Panel?

**Comment by philippjfr** [comment]
Buttons support icons since 1.0.
