### ISSUE TITLE
panel serve --autoreload does not work consistently with imported modules

### ISSUE THREAD

**Issue by smackesey** [holoviz/panel#2531]
#### ALL software version info

- python: 3.9.2
    - holoviews: 1.14.4
    - jupyter_bokeh: 3.0.2
    - ipython 7.22.0
    - jupyterlab: 3.0.16
    - pyviz-comms: 2.0.1

- MacOS: 11.4

- VSCode Insiders: 
    - Version: 1.59.0-insider
    - Commit: f6df685c62da50886f7540cbf768ed4333d58bea
    - Date: 2021-07-13T05:15:28.368Z
    - Electron: 12.0.13
    - Chrome: 89.0.4389.128
    - Node.js: 14.16.0
    - V8: 8.9.255.25-electron.0
    - OS: Darwin x64 20.5.0

#### Description of expected behavior and the observed behavior

`panel --autoreload` does not trigger a reload when saving changes to an imported module.

However, if I first save the actual served module (triggering a reload), *then* subsequent saves of imported modules will also trigger reloads. It's as if the "registry" of imports is not populated when you first start serving, and only becomes populated after the first reload.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# test_panel.py
import holoviews as hv
import panel as pn

data = [('a', 10), ('b', 7)]
def test():
    return pn.panel(hv.Bars(data))

# test.py
import test_panel
test_panel.test().servable()
```

Try `panel serve --autoreload` with `test.py`. While serving, change the data values in `test_panel.py` and save. No reload.

Try the same thing again, but this time save `test.py` immediately after you begin serving (you don't have to change anytime, just save it to trigger a server reload). Now if you change the values in `test_panel.py`, it will reload.

**Comment by philippjfr** [comment]
Great find, and thanks for reporting this. Turned out to be a fairly subtle issue with race conditions between different sessions. In particular when starting the bokeh server with autoreload it automatically creates a session on load, when you then loaded a session in a browser these two would compete to detect the changed module and cause one of two bad outcomes described in the PR.
