### ISSUE TITLE
Authenticating User Before navigating to Each Panel App

### ISSUE THREAD

**Issue by BiswajitBiswa** [holoviz/panel#2534]
I have a directory of panel apps. I want to authenticate user (accessing panel urls) before navigating to url . I managed to stored token /cookie in the host where my bokeh server is hosted. Now I want that for each app(when user opens app url in browser)first this token/cookie from my browser is send to my different authentication server(not third party like google/github) rather my own backend and validated and if token is invalid user is redirected to a login page. 

For now I have running each panel app embedded into the roots of a jinja template and i have a custom javascript embedded into the body of jinja template. So when an app is loaded this javascript gets executed in browser and  validates the token with backend. If not validated user gets redirected else the panel app is showed.. But i am not able to add custom js from my directory in panel prebuilt template like bootrap Or react.... Rest works fine with Jinja Method. 

Question --is there any other way of authenticating each panel app. (Not social logins rather sending request to a backend) or the approach said above has no issue? And can i use custom js like raw_css in bootstrap template?

**Comment by philippjfr** [comment]
Apologies for not responding here, we have now had a basic login provider for a little while now, which is described here: https://panel.holoviz.org/how_to/authentication/basic.html
