### ISSUE TITLE
fsspec.gui.FileSelector button:  changing the name makes the button unresponsive

### ISSUE THREAD

**Issue by fleming79** [holoviz/panel#2541]
In Jupyterlab 3.0.16 running from latest WinPython distribution [3950](https://github.com/winpython/winpython/blob/master/changelogs/WinPython-64bit-3.9.5.0.md).

The `up` button (<) works as expected.
```
import fsspec.gui
import panel as pn

fs = fsspec.gui.FileSelector()
fs.up.button_type = 'primary'
fs

```
![image](https://user-images.githubusercontent.com/1474668/126021162-8406b221-6274-4b4f-92f4-a7f9a51ec6f4.png)

until
```
fs.up.name = "up"
```
![image](https://user-images.githubusercontent.com/1474668/126021173-622d68ac-8f90-45dc-87cc-732cbdedfc6e.png)

The name gets updated as expected. But the button no longer works. The same also applies to the 'go' button.

**Comment by philippjfr** [comment]
I **think** this is an issue with the fsspec GUI itself or rather with the way it's event system works, since it is keyed off the name of the widget, i.e. see https://github.com/intake/filesystem_spec/blob/master/fsspec/gui.py#L117

I'll close but please reopen if this is a Panel issue afterall.

**Comment by fleming79** [comment]
Thanks for checking anyway -I should have reported it at fsspec.
