### ISSUE TITLE
widget on svg image background

### ISSUE THREAD

**Issue by UTKARSHS1994** [holoviz/panel#2549]
I am looking for creating widgets on a svg image in panel. I tried using Gridspec but it simply overrides the svg image (and does not overlap it). I want to create  multiple widgets on 1 single svg image background. Is there a way to do that?

**Comment by philippjfr** [comment]
Thanks for the issue @UTKARSHS1994. However this is a usage question, so could you please post this on the discourse: https://discourse.holoviz.org/
