### ISSUE TITLE
Add Select widget which looks like MultiSelect

### ISSUE THREAD

**Issue by jsignell** [holoviz/panel#255]
`pn.widgets.MultiSelect` accepts a `size` argument to control the number of options displayed - `pn.widgets.Select` should have the same.

**Comment by philippjfr** [comment]
Not quite sure what this would look like, the Select widget is a dropdown so only displays a single object at the same time, what would it mean for it to expose a ``size``? Also if we want to support this then we would first have to be exposed in bokeh.

**Comment by jbednar** [comment]
I would assume it's the number of options visible at any one time, as for MultiSelect?

**Comment by philippjfr** [comment]
I've never seen a dropdown that shows more than the currently selected item or do you mean the number of options shown when expanding the dropdown?

**Comment by jsignell** [comment]
> it's the number of options visible at any one time (during selection)

Right - ran into this when working on the intake GUI which was using the ipywidgets equivalent to expose a file explorer-like experience

**Comment by jsignell** [comment]
It would look exactly like a MultiSelect, but only allow the selection of one item.

**Comment by philippjfr** [comment]
That seems like a separate widget entirely then, ideally what is currently Select would be renamed to Dropdown.

**Comment by jbednar** [comment]
That makes sense to me.  Or maybe MultiSelect could accept a restriction on how many items can be selected, so that by default it acts as the current MultiSelect, if set to 1 it would act like the proposed Select here, and other values in between can be chosen?

**Comment by jsignell** [comment]
I think a separate widget would probably make more sense. It would be confusing to have the output from MultiSelect be an object or a list depending on an argument.

**Comment by jbednar** [comment]
I don't think it would ever change output type; it would always be a list.  But if set up to return only a single item, the consumer of it could always take the first item in the list.  It's true that having a separate widget would make it slightly more convenient to the user of this parameter in the single-item case, though.

**Comment by kcpevey** [comment]
Just subclass the existing bokeh multiselect

**Comment by philippjfr** [comment]
The main obstacle here is naming, the implementation would be pretty simple and look something like this (not tested):

```python
import {MultiSelectView, MultiSelect} from "@bokehjs/models/widgets/multiselect"

export class SelectInputView extends MultiViewWidgetView {
  model: SelectInput

  render(): void {
    super.render()
    this.select_el.multiple = false
  }
}

export interface MultiSelect extends MultiSelect.Attrs {}

export class SelectInput extends InputWidget {
  properties: SelectInput.Props
  __view_type__: SelectInputView

  constructor(attrs?: Partial<SelectInput.Attrs>) {
    super(attrs)
  }

  static init_SelectInput(): void {
    this.prototype.default_view = SelectInputView

    this.define<SelectInput.Props>({    })
  }
}
```

**Comment by philippjfr** [comment]
On balance I have decided that the size argument does make sense here.
