### ISSUE TITLE
Auth-Module works only with panel serve and not with panel.serve

### ISSUE THREAD

**Issue by BiswajitTri** [holoviz/panel#2558]
#### ALL software version info
Browser:chromium :latest
OS: ubuntu 21.04 

#### One should be able to pass an auth-module either with panel serve --auth-module from cli or running a main.py(with panel.serve()) using python main.py.
1) while serving multiple apps with python main.py I am not being able to use auth module.
2) if i use panel.serve and panel serve together i get two instance of bokeh running and the auth-module gets applied to localhost:5006 ,which is the default bokeh instance
3)i tried passing auth_module,AUTH_MODULE,PANEL_AUTH_MODULE to pn.serve() but none of them works

```
from appOne import appOne_serve_func
from appTwo import appTwo_serve_func
import panel as pn

pn.serve({"new_occupancy": appOne_serve_func,
          "occupancy2": appTwo_serve_func}, port=7087,AUTH_MODULE='/home/PANEL/multi_apps/request_handler.py')

```

**Comment by philippjfr** [comment]
Sorry for the lack of response here. Yes, module based handlers are not supported for programmatic `serve` calls. However we have a range of OAuth providers now and it's possible to define custom ones by adding an auth provider to: `panel.auth.AUTH_PROVIDERS` or adding a `panel.auth` entrypoint.
