### ISSUE TITLE
default-app cli flag not working

### ISSUE THREAD

**Issue by BiswajitTri** [holoviz/panel#2559]
#### ALL software version info
Browser:chromium 
OS: ubuntu 21.0
Panel:0.11.3

#### using  --default-app flag gives following error .
 panel serve main.py --default-app=filename
usage: panel [-h] [-v] {copy_examples,examples,build,info,init,json,sampledata,secret,serve,static,oauth-secret} ...
panel: error: unrecognized arguments: --default-app

**Comment by philippjfr** [comment]
Where did you read about ``--default-app``? It was only temporarily introduced and replaced with `--index`.

**Comment by BiswajitTri** [comment]
Thanks for response but I found it in deploy and export section in the following link
 https://panel.holoviz.org/user_guide/Deploy_and_Export.html
![Screenshot from 2021-07-22 17-31-04](https://user-images.githubusercontent.com/75363869/126636121-81ba46e1-4580-4617-b67b-ebf5dda4d1aa.png)

I too never saw it before untill browsing the docs today.Thanks for update.
