### ISSUE TITLE
enable_theme_toggle is actually theme_toggle

### ISSUE THREAD

**Issue by Stubatiger** [holoviz/panel#2560]
The Docs here https://panel.holoviz.org/reference/templates/FastListTemplate.html
state:
`enable_theme_toggle (boolean): If True a switch to toggle the Theme is shown. Default is True.`

but actually the parameter is called theme_toggle 
`    theme_toggle = param.Boolean(default=True, doc="""
        If True a switch to toggle the Theme is shown.""")`

as it is declared in the FastBaseTemplate.

**Comment by MarcSkovMadsen** [comment]
Thanks @Stubatiger
