### ISSUE TITLE
"packages" no longer supported in __js_require__

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2571]
I just upgraded the `panel-highchart` extension to Panel 0.12.0. But I can see something changed.

![image](https://user-images.githubusercontent.com/42288570/126873135-60f4bf5c-7cb5-454b-9a0e-be836f97f8c4.png)

You can replicate this on Binder: https://mybinder.org/v2/gh/marcskovmadsen/panel-highcharts/6c10727?urlpath=lab/tree/examples/HighChart.ipynb

I believe the issue is that I "mock" Panel to be able to load the extension via `pn.extension('highchart')`. The mocking is done in https://github.com/MarcSkovMadsen/panel-highcharts/blob/6c107271a4902f7a8df0b87f3b7a9c81d58c1149/panel_highcharts/config.py

![image](https://user-images.githubusercontent.com/42288570/126873255-fbbfaf75-2afb-4d64-a715-a580e021b706.png)

This worked in Panel 0.11 but appearently not in Panel 0.12.

## Solution

Describe and support a way to develop and deploy Panel Extensions. Currently I have to investigate, do some mocking and then fix when mocking breaks in new versions.

**Comment by MarcSkovMadsen** [comment]
If I disable the `_imports` above I don't get the error. But then again HighCharts is not loaded.

![image](https://user-images.githubusercontent.com/42288570/126873387-76eba19c-02bf-4121-90f2-fb5e7de14acf.png)

**Comment by MarcSkovMadsen** [comment]
Hmmm. It seems to work locally in Jupyterlab. So the problem is on Binder?

**Comment by MarcSkovMadsen** [comment]
Ok. Adding the "key" packages removes the error in the cell. 

![image](https://user-images.githubusercontent.com/42288570/126876110-06f639dc-676e-4926-a392-e309fa8e7d50.png)

But then an error appears in the js console

![image](https://user-images.githubusercontent.com/42288570/126876130-6cfd21f1-81ac-48e1-b6df-829ef5b7a7bb.png)

![image](https://user-images.githubusercontent.com/42288570/126876153-2a225c6d-52da-4e1a-b09c-4ffa6ce5b18a.png)

**Comment by MarcSkovMadsen** [comment]
If I change the "exports" from None to something random like below

![image](https://user-images.githubusercontent.com/42288570/126876365-3d893bec-7017-4b0c-a33e-3e8674ae1955.png)

it works.

![image](https://user-images.githubusercontent.com/42288570/126876372-a32ad5a9-8b33-47a1-ad65-3dd83e809716.png)

The question is then if an `exports` value of `None` should be supported or not. What do you think @philippjfr ?

**Comment by philippjfr** [comment]
Should have thought about this before merging the changes I made. `__js_require__` is a Panel only API (Bokeh models do not support it) and is not fully documented so I did not anticipate anyone would be using it.

**Comment by MarcSkovMadsen** [comment]
I don’t deeply understand this. But as a developer of extensions I can see it’s needed.
