### ISSUE TITLE
Simple login/password auth example without oauth

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2575]
I want to use bokeh's auth module:

Directory structure
```
- test/
-     test/
-         main.py
-         auth.py
-         login.html
```

main.py
```
import panel as pn

pn.pane.Markdown("Login was successful!").servable()
```

auth.py: https://github.com/bokeh/bokeh/blob/branch-2.4/examples/howto/server_auth/auth.py

login.html: https://github.com/bokeh/bokeh/blob/branch-2.4/examples/howto/server_auth/login.html

`panel serve test/ --port 1234 --allow-websocket-origin="*" --auth-module=test/auth.py`

So if I login to `localhost:1234/login` and enter the proper username/password, it redirects fine.

But I can also bypass the login page by going to `localhost:1234/test`. I thought by passing --auth-module, panel would automatically redirect to the /login endpoint if `pn.state.cookies["user"]` did not exist.

Any ideas on how I can fix this?

**Comment by orangeSi** [comment]
> I want to use bokeh's auth module:
> 
> Directory structure
> 
> ```
> - test/
> -     test/
> -         main.py
> -         auth.py
> -         login.html
> ```
> 
> main.py
> 
> ```
> import panel as pn
> 
> pn.pane.Markdown("Login was successful!").servable()
> ```
> 
> auth.py: https://github.com/bokeh/bokeh/blob/branch-2.4/examples/howto/server_auth/auth.py
> 
> login.html: https://github.com/bokeh/bokeh/blob/branch-2.4/examples/howto/server_auth/login.html
> 
> `panel serve test/ --port 1234 --allow-websocket-origin="*" --auth-module=test/auth.py`
> 
> So if I login to `localhost:1234/login` and enter the proper username/password, it redirects fine.
> 
> But I can also bypass the login page by going to `localhost:1234/test`. I thought by passing --auth-module, panel would automatically redirect to the /login endpoint if `pn.state.cookies["user"]` did not exist.
> 
> Any ideas on how I can fix this?

I have the same question now.  Before really resolve it, I use this https://github.com/holoviz/panel/issues/4113 as the temporary resolution.
