### ISSUE TITLE
Binder link not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2583]
If you click the binder link below it will not open correctly.

![image](https://user-images.githubusercontent.com/42288570/127155912-e17b3924-2c75-4fcd-bbbc-11b471e674fb.png)

![image](https://user-images.githubusercontent.com/42288570/127155937-8e51dce2-1f11-43c4-ba2b-e778109ef3fe.png)

## Cause

The url is not correct: https://mybinder.org/v2/gh/holoviz/panel/master?urlpath=lab/tree/examples/reference/panes/Plotly

`.ipynb` is missing.

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/2590
