### ISSUE TITLE
FastListTemplate theme toggle seems broken?

### ISSUE THREAD

**Issue by vlvalenti** [holoviz/panel#2584]
#### ALL software version info
panel: 0.12.0
param: 1.10.1
holoviews: 1.14.4
 
on MacOS Catalina

#### Description of expected behavior and the observed behavior
Expected the theme toggle in the FastListTemplate to change the theme shown, however it does not change. Using the panel documentation FastListTemplate example.

#### Complete, minimal, self-contained example code that reproduces the issue

```
template = pn.template.FastListTemplate(title='FastListTemplate')

xs = np.linspace(0, np.pi)
freq = pn.widgets.FloatSlider(name="Frequency", start=0, end=10, value=2)
phase = pn.widgets.FloatSlider(name="Phase", start=0, end=np.pi)

@pn.depends(freq=freq, phase=phase)
def sine(freq, phase):
    return hv.Curve((xs, np.sin(xs*freq+phase))).opts(
        responsive=True, min_height=400, title="Sine")

@pn.depends(freq=freq, phase=phase)
def cosine(freq, phase):
    return hv.Curve((xs, np.cos(xs*freq+phase))).opts(
        responsive=True, min_height=400, title="Cosine")

template.sidebar.append(pn.pane.Markdown("## Settings"))
template.sidebar.append(freq)
template.sidebar.append(phase)

template.main.append(hv.DynamicMap(sine),)
template.main.append(hv.DynamicMap(cosine))
template.servable();

```

#### Stack traceback and/or browser JavaScript console output
None

#### Screenshots or screencasts of the bug in action
Video of the bug in action

https://user-images.githubusercontent.com/71399442/127212424-dd8d40c8-7832-4121-aafe-70c2e64804bf.mov

Thank you!

**Comment by Stubatiger** [comment]
Well i can kind of reproduce this.
If i use your code and start it with `panel serve example.py --show` it works (with minor changes like the missing imports and removing the semicolon).

But if i change `.servable` with `.show` and start it with `python example.py` i get the behaviour you have shown.
Same error when i use the code in a notebook cell with `.show` or like you with `pn.serve`.

**Comment by MarcSkovMadsen** [comment]
At least using `panel serve` works for me on Windows, Panel: 0.12

https://user-images.githubusercontent.com/42288570/127270640-50cfadc4-8fe1-4b11-b54b-65462916865d.mp4

**Comment by MarcSkovMadsen** [comment]
Hi @vlvalenti and @Stubatiger 

If you want to use `pn.serve` you will have to wrap the template in a function like shown in the video.

https://user-images.githubusercontent.com/42288570/127271480-71bc3d40-bfcd-4871-9a8c-9983dd35c41c.mp4

----

The technical reason is that without wrapping it in a function you are creating a template once and serving that on all sessions to all users. And the theme is determined on construction of the template. And in your case actually from the (missing) `?theme=...` in the notebooks url - that is why it's light all the time.

**Comment by MarcSkovMadsen** [comment]
Regarding `.show` I don't think you can get theme toggle to work. Because there you would be creating the template once and the theme would be determined once based on the *query args* of the notebook url.

Please reopen if this does not "solve" your problems. Thanks.

**Comment by vlvalenti** [comment]
This is great, thank you!
