### ISSUE TITLE
Number Indicator overlaps with Fast Templates

### ISSUE THREAD

**Issue by Stubatiger** [holoviz/panel#2600]
Hello,

when using the Number indicator on a fast template, the sizing is broken.
```python
import panel as pn
pn.extension()

pn.template.FastListTemplate(
    main=[pn.indicators.Number(name="MyNumber", value=42)]
).show()
```
![fast_broken](https://user-images.githubusercontent.com/4622149/127983082-5e3565bb-6d29-4fd2-87d0-c7880bf07379.JPG)

Other templates show it fine, e.g. bootstrap
```python
import panel as pn
pn.extension()

pn.template.BootstrapTemplate(
    main=[pn.indicators.Number(name="MyNumber", value=42)]
).show()
```

![bootstrap_fine](https://user-images.githubusercontent.com/4622149/127983101-a5edf205-9e78-463e-a1bb-72d35853e08c.JPG)

**Comment by philippjfr** [comment]
@MarcSkovMadsen Any ideas?

**Comment by Stubatiger** [comment]
Somehow the <div> tag influences this behaviour.

If i change the html for the number indicator here https://github.com/holoviz/panel/blob/b220588de764e7a8aae92b8d5d764c21d7374c4a/panel/widgets/indicators.py#L196 and use <p> elements like this
```python
value = format.format(value=value).replace('nan', nan_format)
text = f'<p  style="font-size: {font_size}; color: {color}">{value}</p>'
if self.name:
    title_font_size = msg.pop('title_size', self.title_size)
    text = f'<p style="font-size: {title_font_size}; color: {color}">{name}</p>\n{text}'
```

![toofar](https://user-images.githubusercontent.com/4622149/128074797-552f4e4a-adfc-4076-8450-0807baa3a49a.JPG)

it does not overlap, but seems a little bit too far off

**Comment by MarcSkovMadsen** [comment]
I believe the issue is related to the `line-height`.

![image](https://user-images.githubusercontent.com/42288570/128083068-96f3b29d-12fa-4334-9130-244e356fa5a3.png)

It seems to be difficult to add something to the fast css to change the height of the indicator as it has no class name defined.

So it would probably have to be set in the bokeh model?
