### ISSUE TITLE
Make profiling easier in Panel

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#2621]
Going to flesh this out more later but the basic idea is that I want to offer users tools for profiling their application both from the command line and in a running application.

I'll use this issue to collect tools that can help us with this:

- cProfiler
- [pyinstrument](https://github.com/joerick/pyinstrument)

**Comment by MarcSkovMadsen** [comment]
Some tools that I have been using or looking at

- Nice profiling viz https://jiffyclub.github.io/snakeviz/
- https://github.com/pyutils/line_profiler really powerful. Especially for PyCharm users in connection with https://gitlab.com/line-profiler-pycharm/line-profiler-pycharm-python/
- PyCharm integrated profiling has a nice diagram https://www.jetbrains.com/help/pycharm/profiler.html#view-graph
- https://github.com/gaogaotiantian/viztracer

**Comment by philippjfr** [comment]
Profiling has been part of the admin pane for a while.
