### ISSUE TITLE
`obj.visible=False` should apply `display: none!important` instead of `display:none`

### ISSUE THREAD

**Issue by brunorpinho** [holoviz/panel#2627]
#### ALL software version info
panel=0.12.1
bokeh=2.3.3

#### Description of expected behavior and the observed behavior
This might be a bokeh issue, but I have seen that setting `obj.visible=False` on a `panel` object doesn't always work when you pass a css class to `css_classes` that already have a `display` defined like `display: block!important`. Setting `obj.visible=False` should replace that as well.

My suggestion is: `obj.visible=False` should apply `display: none!important` instead of `display:none` as css.

I've seen this behaviour on an app and couldn't reproduce on a notebook because of issues with jupyterlab. Maybe it's an issue with `CrossSelector`. Try this:

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn

CSS = """
.is-display-block {
    display: block!important;
}
"""

pn.extension(raw_css=[CSS])

test = pn.widgets.CrossSelector(options=['a', 'b', 'c'], css_classes=['is-display-block'])
# <render `test`>
test.visible = False
```

**Comment by philippjfr** [comment]
I think all bets are off when you use `!important` in some custom CSS you define, so I'll close as wontfix.
