### ISSUE TITLE
Binder link still not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2648]
If I go to https://panel.holoviz.org/gallery/simple/random_number_generator.html

and click

![image](https://user-images.githubusercontent.com/42288570/130346484-dc8fba37-c2b4-4963-ae90-a8768d939bcd.png)

It will open https://mybinder.org/v2/gh/holoviz/panel/master?urlpath=lab/tree/examples/gallery/simple/random_number_generator

I.e. the `.ipynb` ending is missing and you will get a "file not found" error from jupyterlab.

I thought this was fixed from https://github.com/holoviz/panel/issues/2583. But apparently not.

**Comment by philippjfr** [comment]
The doc build had just failed for the 0.12.1 release, I restarted it and this is now fixed.
