### ISSUE TITLE
Add "open this app on pyviz" link

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2649]
If I go to https://panel.holoviz.org/gallery/simple/temperature_distribution.html I can see that live applications are now embedded in the page. That is great.

![image](https://user-images.githubusercontent.com/42288570/130346701-8d3a9881-58e4-4113-994b-40c3688d04ff.png)

Unfortunately they don't always "scale" well being embedded in a "small" iframe. Thus it would be really helpful if I could see the app running full screen. And navigation back and forth between pages in an iframe can be a pain.

## Solution 

Provide "open this app on pyviz" link just below "Open this example in Binder" link https://panel-gallery.pyviz.demo.anaconda.com/temperature_distribution.

**Comment by philippjfr** [comment]
These have been added.
