### ISSUE TITLE
Clean up https://panel-gallery.pyviz.demo.anaconda.com/ and share links to it in central places.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2650]
I just discovered https://panel-gallery.pyviz.demo.anaconda.com/ and I believe its an important resource.

But not all pages in the Gallery work well yet.

For example https://panel-gallery.pyviz.demo.anaconda.com/idom_snake is empty.

![image](https://user-images.githubusercontent.com/42288570/130346837-52db66ae-98d5-43e2-8a24-157a4c786923.png)

There are several of these issues. Also it seems the gallery is not running the latest release panel 0.12.1.

## Must Have

- All items in the gallery should "work".
- Market this gallery on pyviz and panel sites.

## Nice to have

- Get it upgraded to latest version of Panel.
- Setup load testing using [locust](https://locust.io/). It would be a really great thing for identifying gallery examples no longer working or not performant. It's pretty simple to configure and use.

**Comment by philippjfr** [comment]
There's still 3 items in the current gallery that don't work. I know why and will find a solution and this task is captured elsewhere so I'll close.
