### ISSUE TITLE
Make editable sliders name parameter editable (from python)

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#2663]
Editable sliders are a very nice addition to panel components and can advantageously replace conventional sliders in most cases in my opinion. However there is a difference currently with respect to the name parameter, which is constant in editable sliders while it is not in conventional sliders.

As in my app I use sliders which have their name changed programmatically, I would like to know if editable sliders could be modified so that the name parameter is no longer constant? In general I think it's best to make editable sliders behave identically to their non-editable counterparts as far as practicable.

**Comment by MarcSkovMadsen** [comment]
Hi Could you provide a small, reproducible code example? That would make it easier to reproduce, explore, fix and release a fix. Thanks.

**Comment by TheoMathurin** [comment]
Sure
```
import panel.widgets as pnw

slider = pnw.EditableFloatSlider(name='name1')
slider.param.set_param(name='name2')
```

**Comment by MarcSkovMadsen** [comment]
I tried to fine a workaround but it errors

```python
import param
import panel.widgets as pnw
import panel as pn

pn.extension()

slider = pnw.EditableFloatSlider(name='name1')

with param.edit_constant(slider):
    slider.name='name3'

slider
```

```bash
TypeError: Constant parameter 'name' cannot be modified
```

**Comment by TheoMathurin** [comment]
That is the same error you get when trying to modify it directly.

**Comment by xavArtley** [comment]
The work around is :
`slider._label.param.set_param(**{'margin': (0,10,0,0), 'value': "name3"})`

**Comment by TheoMathurin** [comment]
It works, thanks @xavArtley!

**Comment by maximlt** [comment]
'''python
try:
    slider.name =  "name3"
except TypeError:
    pass
```
also works. This is because the name of the widget is actually being correctly set in the first place (under the hood the value of a `StaticText` widget is set). However, the code currently sets the name of the `Column` param that wraps the `StaticText` and the slider. The `name` of any param can be set but not edited, which is what raises the error.
