### ISSUE TITLE
option_limit of MultiChoice widget doesn't work when typing initials

### ISSUE THREAD

**Issue by zhh210** [holoviz/panel#2665]
The option_limit allows specifying how many items to display in the MultiChoice widget. When setting it > 4, it works when nothing is in the input widget: 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/3037080/130988155-5007ce2f-b9b6-426e-948c-435ab02548c7.png">

However, when any string is used to search item initials, only 4 items will be displayed.
<img width="308" alt="image" src="https://user-images.githubusercontent.com/3037080/130988252-c35eee8b-0868-4c85-a8a5-c8948d5d2c2c.png">

Is it possible to allow option_limit to work when searching from the choices?

**Comment by ingebert** [comment]
Thanks for pointing out. I was about to post the same issue. 
Also without setting option_limit it would be helpful, to be able to scroll through all proposed list items after filtering with search string.
