### ISSUE TITLE
curdoc.add_root() does not work when using templates

### ISSUE THREAD

**Issue by eschutz** [holoviz/panel#2668]
Ubuntu 20.04.2 LTS
Python 3.6.14
Panel 0.12.1
Bokeh 2.3.2
Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)

Document fails to render when using a template at the same time as `pn.state.curdoc.add_root()`.

Code example:

```python
import panel as pn
from bokeh.models import Button
from bokeh.plotting import figure

button = Button()

p = figure()
p.line([1,2,3], [1,2,3])

template = pn.template.BootstrapTemplate()
template.main.append(pn.pane.Bokeh(p))

def app():
    # Removing the following line will fix the issue
    pn.state.curdoc.add_root(button)

    return template

pn.serve(app)
```

This example may seem a little contrived as there are easier ways to add buttons, but this is part of a larger app where some custom JS is attached to the button to allow keyboard input.

JS console output:
```javascript
Uncaught (in promise) Error: Error rendering Bokeh model: could not find #50290277-b1ac-4779-a87a-668c2ac56814 HTML tag
    at u ((index):1461)
    at Object.n._resolve_root_elements ((index):1461)
    at w ((index):1041)
    at Object.t.embed_items ((index):1041)
``` 

With `add_root()`:
![image](https://user-images.githubusercontent.com/17667220/131085062-0e8ed5b9-77fd-4b9e-a81b-c106f5c47390.png)

Without `add_root()`:
![image](https://user-images.githubusercontent.com/17667220/131085103-a460df01-4d88-4333-bb53-336b8e33c7ca.png)

**Comment by eschutz** [comment]
My bad, it was a remnant of old code from before refactoring to use templates, I thought Bokeh might have needed it to be added directly or something, but apparently not - it's all working now using templates directly. Thank you!

**Comment by philippjfr** [comment]
Great to hear and thanks for reporting back!
