### ISSUE TITLE
Support rendering Pandas Styler object

### ISSUE THREAD

**Issue by caseyjlaw** [holoviz/panel#2695]
Running panels 0.12.1 and pandas 0.25.3 in Jupyter notebook on OSX in Chrome.

I love tabulator and the way it helps me create dashboards for dataframes.

I made a function to apply a style (text highlighting). However, the behavior after running the `apply` method and displayed as a `pn.Row` is not what I expected. It seems that the table loses all styling information.

```
<import stuff>
<get df>
df_applied = pn.widgets.Tabulator(df).style.applymap(color_bad)
df_applied  # this one looks fine when displayed in notebook
pn.Row(df_applied)  # this one seems to have no style

```

Here is a screenshot that shows a reproducible example:

![Screen Shot 2021-08-31 at 10 00 51 AM](https://user-images.githubusercontent.com/1878317/131545451-1b16b92a-bea2-471e-8ab5-93d8325174c8.png)

**Comment by philippjfr** [comment]
Thanks for the issue, this is unrelated to Tabulator however, the object returned by the styling API is a Pandas Styler object, which we currently do not explicitly support and therefore it just gets rendered using the standard `HTML` pane. Supporting the Styler object seems like a good idea to me though.
