### ISSUE TITLE
Cannot panel serve on Master branch - I.e. cannot contribute

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2702]
For the last couple of weeks when I have been trying to start a contribution from the MASTER branch it has not been possible.

Also today when I `git pull`, `pip install -e . -U` and then `panel serve script.py` I see 

```python
$ panel serve 'script.py' --autoreload --show
ERROR: 'Document' object has no attribute '_callbacks'
```

It is highly problematic that the master branch does not work because 1) Nobody can start contributing 2) We have lots of binder links linking to the MASTER branch. I.e. our documentation does not work

#### Solution

1) Get Master branch working
2) Replace binder links with links to the latest release. It does not make sense to link binder to something that is under development and might not reflect the documentation.

#### Example

```python
import plotly.express as px

import panel as pn

pn.sizing_mode="stretch_width"


def get_plotly_carshare_data():
    return px.data.carshare()


def plotly_carshare_plot(carshare):
    fig = px.scatter_mapbox(
        carshare,
        lat="centroid_lat",
        lon="centroid_lon",
        color="peak_hour",
        size="car_hours",
        color_continuous_scale=px.colors.cyclical.Phase,
        size_max=15,
        zoom=10,
        mapbox_style="carto-positron",
    )
    fig.layout.autosize = True
    return fig


data = get_plotly_carshare_data()
component = plotly_carshare_plot(data)
carshare_panel = pn.pane.Plotly(
    component,
    config={"responsive": True},
    background="yellow",
)

pn.Column(
    component,
    background="lightgray",
    sizing_mode="stretch_both",
).servable()
```

**Comment by philippjfr** [comment]
Which Bokeh version are you running, as I can't reproduce this.

**Comment by philippjfr** [comment]
Yeah, absolutely can't reproduce even after I created a new environment and ran `pip install -e . -U`

**Comment by philippjfr** [comment]
Will close but please reopen if you figure out what was causing this or how you created your environment.

**Comment by philippjfr** [comment]
Also just tried the master deployment on Binder without isssue.

**Comment by philippjfr** [comment]
Still would like to know what happened here, any ideas @MarcSkovMadsen ?

**Comment by MarcSkovMadsen** [comment]
Nope

**Comment by philippjfr** [comment]
Anyway, appreciate the issues and glad they resolved themselves. Transitioning between Bokeh versions is the likely culprit, master will switch to being >=2.4 very soon.
