### ISSUE TITLE
DiscreteSlider label not updated in ReactiveHTML layout

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#2709]
Hello,
DiscreteSlider label is not updated in ReactiveHTML layout

```python
class CustomLayout(pn.reactive.ReactiveHTML):
    
    elem = param.Parameter()
    
    _template = """
        <div id="custom">${elem}</div>
    """
slider = pn.widgets.DiscreteSlider(value=1, options=[1,2,3])
pn.Row(CustomLayout(elem=slider),  slider)
```
![ds_bug](https://user-images.githubusercontent.com/18531147/131973953-bab30bb4-71cf-4649-a187-9e7d57608f33.gif)

**Comment by philippjfr** [comment]
Fixed by https://github.com/holoviz/panel/pull/3278. Note that the example above still doesn't work because of https://github.com/holoviz/panel/issues/552
