### ISSUE TITLE
Panel Ipywidgets does not support adding LayerGroup to Ipyleaflet map 

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2710]
I'm on Panel: 0.12.1, ipywidgets_bokeh: 1.0.2, ipykernel: 5.5.5.

If run the code with the `LayerGroup` below I get the error 

```bash
Error: Could not create a view for model id 3b8ba78129574343a928e1e32b8dc236
    at ipywidgets_bokeh.js:95
```

![image](https://user-images.githubusercontent.com/42288570/131986330-786adf77-7e20-4e60-8196-80ca13523b29.png)

```python
import panel as pn
from ipyleaflet import LayerGroup, LayersControl, Map, Marker

pn.extension("ipywidgets")

def get_marker_and_map():
    m = Map(center=(50, 0), zoom=5)

    marker1 = Marker(name='marker1', location=(48, -2))
    marker2 = Marker(name='marker2', location=(50, 0))
    marker3 = Marker(name='marker3', location=(52, 2))
    layer_group = LayerGroup(layers=(marker1, marker2, marker3), name="My markers")

    # m.add_layer(marker1)
    # m.add_layer(marker2)
    # m.add_layer(marker3)
    m.add_layer(layer_group)

    control = LayersControl(position='topright')
    m.add_control(control)
    return m


map_leaflet = get_marker_and_map()
map_leaflet

pn.panel(map_leaflet, height=400).servable()
```

## Workaround

If I add the markers individually it works.

![image](https://user-images.githubusercontent.com/42288570/131986606-84aadddb-bc3e-4c84-be6a-63b80721fdd2.png)

```python
import panel as pn
from ipyleaflet import LayerGroup, LayersControl, Map, Marker

pn.extension("ipywidgets")

def get_marker_and_map():
    m = Map(center=(50, 0), zoom=5)

    marker1 = Marker(name='marker1', location=(48, -2))
    marker2 = Marker(name='marker2', location=(50, 0))
    marker3 = Marker(name='marker3', location=(52, 2))
    # layer_group = LayerGroup(layers=(marker1, marker2, marker3), name="My markers")

    m.add_layer(marker1)
    m.add_layer(marker2)
    m.add_layer(marker3)
    # m.add_layer(layer_group)

    control = LayersControl(position='topright')
    m.add_control(control)
    return m


map_leaflet = get_marker_and_map()
map_leaflet

pn.panel(map_leaflet, height=400).servable()
```

**Comment by MarcSkovMadsen** [comment]
I'm both interested in a cause, solution and a workaround. A workaround would mean a lot also.

**Comment by MarcSkovMadsen** [comment]
@mattpap. Do you have any ideas on what could cause this error and where I could get started investigating or fixing?

**Comment by MarcSkovMadsen** [comment]
## Workaround using ReactiveHTML

As a workaround Leaflet can be used via `ReactiveHTML`. Check out the showcase https://discourse.holoviz.org/t/leaflet-with-reactivehtml/2762

https://user-images.githubusercontent.com/42288570/132096487-1782b01f-4e4b-4110-8c53-8757b8d00e24.mp4

**Comment by philippjfr** [comment]
Thanks for detailing the issue so well, however since we can't resolve this in Panel it should be moved to `ipywidgets_bokeh`.
