### ISSUE TITLE
Model ‘panel.models.reactive_html.ReactiveHTML’ does not exist

### ISSUE THREAD

**Issue by arifin-chemist89** [holoviz/panel#2720]
#### Description of expected behavior and the observed behavior

This is a follow up from the Holoviz discourse.
https://discourse.holoviz.org/t/model-panel-models-reactive-html-reactivehtml-does-not-exist/2766

As I mentioned there,  I tried to update Panel version used in my app from 0.11.3 to 0.12.1. However, when I run it, nothing was shown. I checked the google chrome console and found the error below.

![image](https://user-images.githubusercontent.com/55862390/132225730-00a89d48-fd2a-4871-94c5-3337c60f6045.png)

I thought that this problem comes from my Python environments or the code. However, I could not reproduced the error when I rebuild the Docker images and **using another port number.** My code also work on the development server.

I solved this problem by **removing the cache and cookies of my browser** (Google Chrome). After I cleaned it, the error is gone and it work as expected.

#### ALL software version info
panel 0.12.1
bokeh 2.3.3

**Comment by philippjfr** [comment]
@arifin-chemist89 @bryevdv Any ideas on making sure the browser cache is invalidated for bokeh extensions after a version upgrade?

**Comment by bryevdv** [comment]
How are the extensions loaded? Are they served as JS files from the panel server? If so, think you'd have to cache bust by appending a UUID as an HTML request argument or something. If not, I don't really have any ideas.

**Comment by philippjfr** [comment]
They are loaded from the Bokeh/Panel server yes, specifically the URL is generated here in Bokeh: https://github.com/bokeh/bokeh/blob/branch-2.4/bokeh/embed/bundle.py#L344

**Comment by philippjfr** [comment]
Submitted https://github.com/bokeh/bokeh/pull/11573 as a fix in Bokeh.

**Comment by philippjfr** [comment]
Will be fixed in Bokeh 2.4, which will be required for Panel 0.12.2
