### ISSUE TITLE
Feature request: timeout for cookies

### ISSUE THREAD

**Issue by arifin-chemist89** [holoviz/panel#2722]
This is one of the follow up of the authentication issue discussed in https://discourse.holoviz.org/t/tips-guide-on-creating-a-simple-username-password-auth-for-panel-app/2582.

#### Is your feature request related to a problem? Please describe.
I am using authentication to keep my app secure. However, since there is no expiration of the cookies in Panel, the user could directly access the app and bypass the login page after it is authenticated.

#### Describe the solution you'd like
It is better to have configurable cookies timeout in Panel.

#### Describe alternatives you've considered
Another way is to clear cookies `on_session_destroyed`

**Comment by philippjfr** [comment]
This was implemented in #2724.
