### ISSUE TITLE
Failed to load front-end resources (bokeh 2.4.0dev7, panel 0.13.0a5)

### ISSUE THREAD

**Issue by AjayThorve** [holoviz/panel#2726]
When starting a panel server, resources fail to load and dashboards fails to load.  I get a bunch of 404 errors in the JS console. This happens both in-notebook and if I start a panel server via `.show()`

#### ALL software version info
bokeh 2.4.0dev7, panel 0.13.0a5

#### Description of expected behavior and the observed behavior
Server should start with all the resources loaded

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
import panel as pn
pn.extension()
pane = pn.pane.Markdown('''
# H1
''')

pane.show()

```

#### Stack traceback and/or browser JavaScript console output
```bash
Failed to load resource: the server responded with a status of 404 (Not Found) dataframe.css:1
Failed to load resource: the server responded with a status of 404 (Not Found) json.css:1
Failed to load resource: the server responded with a status of 404 (Not Found) alerts.css:1
Failed to load resource: the server responded with a status of 404 (Not Found) loading.css:1
Failed to load resource: the server responded with a status of 404 (Not Found) markdown.css:1 
Failed to load resource: the server responded with a status of 404 (Not Found) card.css:1
...
```

**Comment by bryevdv** [comment]
Also seeing this with recent `0.12.2` is there a configuration change to adapt to?

**Comment by philippjfr** [comment]
Don't know how I missed this one. I'm on vacation but @maximlt is looking at this now and I should have some time on my flight tomorrow.

**Comment by philippjfr** [comment]
As Maxime discovered this is down to https://github.com/bokeh/bokeh/pull/11531. We are going to patch the `create_static_handler` function in Bokeh for now. But the problem is that for apps served at the root (`/`) the per app static handler we just added overrides the root static handlers and more importantly the MultiRootStaticHandler which is responsible for serving the extension assets. In Bokeh we will have to make sure that the per app static handlers also add this MultiRootStaticHandler. Does that seem reasonable @bryevdv ?

**Comment by bryevdv** [comment]
The seems reasonable to me, in general whatever hooks Panel needs for customizing app serving are going to be fine.

**Comment by bryevdv** [comment]
FWIW I'd like to have  2.4.1 with whatever fix you need in a few weeks. Should the fix in #2748 be conditioned somehow (explicit version or some other implicit check?)

**Comment by bryevdv** [comment]
I suppose alternatively we could let `create_static_handler` itself be a hook that is intended to be overridden, again happy to follow whatever the needs of Panel dictate, I'd just like to make sure downstream test coverage is increased  in the process

**Comment by bryevdv** [comment]
@philippjfr @maximlt please hold off on releasing

**Comment by bryevdv** [comment]
OK n/m there appeared to be a new issue in notebooks but it seems to have resolved.

**Comment by maximlt** [comment]
Ok thanks for checking! :)

**Comment by philippjfr** [comment]
>I suppose alternatively we could let create_static_handler itself be a hook that is intended to be overridden, again happy to follow whatever the needs of Panel dictate, I'd just like to make sure downstream test coverage is increased in the process

Might not be a bad idea but note that the issue we are seeing here will apply to ALL Bokeh extensions. It's probably just quite rare that other extensions users will launch an app on the root. I'll open an issue on bokeh when I get the chance (flying back home today).

**Comment by bryevdv** [comment]
@philippjfr that just sounds like something that needs a documentation note somewhere that we can point to in the rare instance that it is applicable.
