### ISSUE TITLE
Can panel encapsulate html in the same file? 

### ISSUE THREAD

**Issue by Jacob-Barhak** [holoviz/panel#273]
This is a feature request.

It is possible for panel to show another html file within it using the <object> html tag that links to the other html URL. 

However it is not possible to bring the html into the same file. For some reason encoding the object as data using : 

```
'<object  data="data:text/html;base64,%s"></object>' works only partially in some cases in some browsers, yet generally fails.
```

Is there a way to allow panel to copy all html / images to the same html file so there will not be a need to pass links? 

If this is possible it would help reproducible science since all dependencies will be archived in the same file - even if it is big. If resources are copied in the same file, it would be possible to use where there is no internet connectivity - this opens up some possible applications.

**Comment by kcpevey** [comment]
can be done with:

f"""<iframe srcdoc="{html_report}" style={STYLE} frameborder="0" allowfullscreen></iframe>"""

**Comment by Jacob-Barhak** [comment]
Sorry Kim, 

Your suggestion does not seem to work. 

Perhaps I am doing something wrong, yet I was trying to use the suggested version using iframe to show a panel plot saved as an html file and read as a string into the iframe and for some reason it does not work. It shows an empty square where the iframe should show the sub plot. Also note that object should do the same as iframe - yet it does not work. Do you have working example using iframe?

Here is the function I wrote to generate the panel contents using your suggested method:
````
def ObjectInlineHTML(ExtrnalFileName,Width=Width,Height=700):
    'Encodes html from a file into object'
    DataFile = open(ExtrnalFileName,'rb')
    Data = DataFile.read()
    DataFile.close()
    RetStr = '<iframe srcdoc="{}" style={}"width:100%;height:100%;" frameborder="0" allowfullscreen></iframe>'.format(Data, "width:100%;height:100%;")

    #RetStr = '<object width="'+str(Width)+'" height="'+str(Height)+'" data="%s">Warning:%s Not Accesible!</object>'%(ExtrnalFileName,ExtrnalFileName)
    return RetStr
```

Again, this does not work. Perhaps the issue was closed too early.

Hopefully it is a minor issue on my end.

**Comment by philippjfr** [comment]
This works fine for me:

```python
src = '<html><body><h1>ABC</h1></body></html>'
html = '<iframe srcdoc="{src}" width={width} height={height} frameborder="0" allowfullscreen></iframe>'.format(src=src, width=200, height=200)
pn.pane.HTML(html)
```

You introduced some weirdness when you adapted the code e.g. this part `style={}"width:100%;height:100%;"`.

**Comment by Jacob-Barhak** [comment]
Yes Philipp,

Yet your code is very simple. You are using very simple html - I suspect
this works well with the code I initially suggested as well. Yet more
complex html will not work . I am trying to use an html file generated
before hand by panel with a plot and all the javascript in it already with
a complex plot.

For example look at the interactive poster coded here:
https://github.com/Jacob-Barhak/Presentations/blob/master/MSM_IMAG2020/MSM_IMAG_Poster2020.py


It uses the function ObjectInlineHTML to  bring in another plot previously
generated by panel and stored in another file. You can do it with an iframe
tag or with an object tag. However, the resource has to be in a
separate file for this to work. What I was asking is to have all the plots
in one html file. This way this one file archives all the plot information.
I do not care about its size - yet I know that once I ship the file to
someone, the other person has all the data and can reproduce the plot.
Otherwise, someone can update or change one of the other files and the file
I am sending does not contain all the data.

This feature is far from critical, yet if there was a way that panel can
encapsulate an entire html file that is complex in the same file, it would
be a feature that supports reproducibility.

**Comment by philippjfr** [comment]
The approach I laid out above should work just fine with arbitrarily complex HTML documents you just need to make sure the HTML is escaped correctly, i.e. you should use `from html import escape` on the `src` in my example.

**Comment by Jacob-Barhak** [comment]
Thanks Philipp, 

You are correct!

Now. with escaping the html it works. 

However, one also needs to be mindful of encoding to make this work properly. 

Below is code that was tested in the current development version of panel and with python 2.7 and works nicely on several complex examples - some of which I had issues with in the past that are now working. 

````
import holoviews as hv
import panel as pn
import bokeh
from bokeh.resources import INLINE
import sys
from html import escape
import io

hv.extension('bokeh')
pn.extension(safe_embed=True) 


print ("Python version is: %s"%sys.version)
for library in [hv,pn,bokeh]:
    print ("%s version %s"% ( library.__name__, library.__version__))


def embed_html(extrnal_filename, encoding='utf8'):
    'embeds html from a file into object'
    if sys.version_info[0] == 3:
        file = open(extrnal_filename,'r', encoding=encoding)
    else:
        file = io.open(extrnal_filename, 'r', encoding=encoding)
    data = file.read()
    file.close()
    escaped_data = escape(data)
    html_str = u'<iframe srcdoc="{}" style={};" frameborder="0" allowfullscreen></iframe>'.format(escaped_data, "width:100%;height:100%;")
    return html_str

# Test files were downloaded from 
# https://github.com/Jacob-Barhak/Jacob-Barhak.github.io/raw/master/MSM_IMAG2020/TheReferenceModelHistory_Populations.html
# https://github.com/Jacob-Barhak/Jacob-Barhak.github.io/blob/master/CommonResources/HoloviewsPlot.html
# https://github.com/Jacob-Barhak/Jacob-Barhak.github.io/blob/master/PosterIMAG2019Resources/ModelMixturePlotsActive.html
# https://github.com/Jacob-Barhak/Jacob-Barhak.github.io/blob/master/Poster_CDISC2019.html

test_files = ['TheReferenceModelHistory_Populations.html', 'HoloviewsPlot.html', 'ModelMixturePlotsActive.html', 'Poster_CDISC2019.html']

for test_enum, test_file in enumerate(test_files):
    html_str = embed_html(test_file)
    pane_obj = pn.panel(html_str, width=1200, height=600)
    pane_obj.save('out_embed_%i'%test_enum, resources=INLINE, title = 'HTML Embed test', embed=True)

````

Now that there is a path to handle this properly, it can be used to reduce the embed time of objects with large trees of widgets that create too many states that we discussed in issue https://github.com/holoviz/panel/issues/1009 . 

If this can be automated somehow, it may also will help resolving the embed issue in some cases and help close  https://github.com/holoviz/panel/issues/982 . 

Note that resolving this opens the path for users to create very complex interactive graphics embedded in a single file that its construction time by panel is reasonable since you can manually avoid the exponentially rising number of states when saving. 

It also makes their results more reproducible.  For my use cases, this is an important breakthrough.

Many many thanks.

**Comment by nghenzi** [comment]
I think this is  an amazing feature :) !!! You can have something like powerpoint, ..... a panelpoint presentation !!

**Comment by Jacob-Barhak** [comment]
Well Nestor,

This feature already exists and I have been using panel for several years
now instead of powerpoint. There are multiple presentations I created that
you can find in:
https://github.com/Jacob-Barhak/Presentations

What Philipp did here is help reduce a limitation that made some things
harder to do with panel. There is still much more work, yet I prefer to use
panel these days due to the interactive components that power point
presentations cannot do. Also since panel generates html files - it is much
more compatible for many use cases.

The Holoviz team is really doing amazing things for several years now.
