### ISSUE TITLE
Support step and format on DateSlider

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2731]
The current version of Panel is 0.12.1.

If I look at the Bokeh [DateSlider](https://docs.bokeh.org/en/latest/docs/reference/models/widgets.sliders.html#bokeh.models.widgets.sliders.DateSlider) I can see it supports a `step` and `format` which the Panel `DateSlider` does not.

I think supporting that would be quite useful for Panel as that would allow sliding through other timeperiods than days down to milliseconds as far as I can see.

## Todo

It's probably as simple as

- Add `step` and `format` parameters to Panels `DataSlider`
- Add tests or test manually that it works
- Update reference guide.

## Additional Context

It would for example increase the possibilities for *Creating a dynamic map with datetime range*. See https://github.com/holoviz/panel/issues/673

**Comment by Axeldnahcram** [comment]
Hi, long time lurker but I guess I kinda want to get involved after using panel for more than a year now. How can I push my changes to a branch to make my first PR @MarcSkovMadsen ?

**Comment by Axeldnahcram** [comment]
I guess I need to fork my own version of panel. I will do it tonight

**Comment by maximlt** [comment]
Hi @Axeldnahcram,

Yes indeed as an external contributor you must fork this repository, then create a new branch in your local fork and push it to your remote repo. At this point Github will offer you to merge your branch into this repository, that's a Pull Request.

You can find the developer instructions here for more details: https://panel.holoviz.org/developer_guide/index.html
