### ISSUE TITLE
LoadingSpinner and other Loading indicators not ever rendering

### ISSUE THREAD

**Issue by tokotchd** [holoviz/panel#2746]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
Panel 0.12.1, Tornado 6.0.3, python 3.7, Chrome 93.0.4577.63

#### Description of expected behavior and the observed behavior
LoadingSpinner should render in a standalone example, setting the loading parameter of widgets should overlay a loading spinner

#### Complete, minimal, self-contained example code that reproduces the issue
```
idle = pn.indicators.LoadingSpinner(value=False, width=100, height=100)
loading = pn.indicators.LoadingSpinner(value=True, width=100, height=100)
test_row = pn.Row(idle, loading)
material.main.append(test_row)
material.servable()

```

#### Stack traceback and/or browser JavaScript console output  
Seemingly no errors
```
Got main parameters
ContentManager.ts:69 Got main parameters {configurationData: {…}, pageInformation: {…}, statusCode: 200, wpmParameters: {…}, documentTitle: 'Test', …}
ContentManager.ts:70 Configuration {ConfigurationVersion: 2, MaxPropertyLength: 256, VisibilityMonitoringIntervalMs: 300, BackoffGracePeriodMs: 1000, ElementsDiscoveryIntervalMs: 1500, …} http://10.164.208.136:5006/panel_bug
DocumentTitleManager.ts:32 DocumentTitleManager using window.top.document.title. Got title:  Test
bokeh.min.js?v=d8b57d042be15c164dc13fb107534054:184 [bokeh] setting log level to: 'info'
AppInternals.ts:209 DOM loaded
VisibilityEventsMonitor.ts:65 Initializing DOM events...
ChromeDocumentTitleManager.ts:41 Received message from background {messageType: 'documentTitleRequest'}
ChromeDocumentTitleManager.ts:41 Received message from background {messageType: 'documentTitleUpdate', documentTitle: 'Test'}
ChromeDocumentTitleManager.ts:59 Updating title to:  Test
ChromeDocumentTitleManager.ts:41 Received message from background {messageType: 'documentTitleRequest'}
ChromeDocumentTitleManager.ts:41 Received message from background {messageType: 'documentTitleUpdate', documentTitle: 'Test'}
ChromeDocumentTitleManager.ts:59 Updating title to:  Test
bokeh.min.js?v=d8b57d042be15c164dc13fb107534054:585 [bokeh] Websocket connection 0 is now open
bokeh.min.js?v=d8b57d042be15c164dc13fb107534054:165 [bokeh] document idle at 93 ms
bokeh.min.js?v=d8b57d042be15c164dc13fb107534054:163 Bokeh items were rendered successfully
```

#### Screenshots or screencasts of the bug in action
There's nothing on the webpage :(

I've tried 4 different ways to render one of these LoadingSpinners:
1. Directly on the main page (as above)
2. Adding it to a modal instead (instead of main)
3. Using `pn.params.set_value` for loading: https://panel.holoviz.org/gallery/simple/loading_spinner.html
4. Using `bind`'s loading parameter: https://panel.holoviz.org/gallery/param/loading_indicator.html

![image](https://user-images.githubusercontent.com/8561315/133816660-c805f6ff-d026-4e03-b940-2e6adea0fd42.png)
Using inspect we can see that the element is being created on the webpage, 
![image](https://user-images.githubusercontent.com/8561315/133816873-39c69d9a-2b58-4d23-b6e0-afe1c06972cb.png)
Inspecting the elements shows the space they take is being used, but not rendering.

**Comment by philippjfr** [comment]
I can't reproduce this at all. Can you provide a full example and maybe try again with the latest versions (i.e. bokeh 2.4 and panel 0.12.3)?

**Comment by tokotchd** [comment]
I updated to bokeh 2.4 and panel 0.12.3 and the problem persists:
`
import panel as pn
from panel.template.material import MaterialDefaultTheme

material = pn.template.MaterialTemplate(title="Test", theme=MaterialDefaultTheme)
idle = pn.indicators.LoadingSpinner(value=False, width=100, height=100)
loading = pn.indicators.LoadingSpinner(value=True, width=100, height=100)
test_row = pn.Row(idle, loading)
material.main.append(test_row)
material.servable()
`

Obviously above doesn't cover #3 or #4 testing situations, but I figured I'd start simple.
I would consider this a fluke but it's happened on two different webhosts from all computers with multiple browsers for me.

I'm currently installing panel/bokeh with conda... maybe I'll start looking at some other installation methods or dependency versions.

**Comment by maximlt** [comment]
I can't reproduce either with bokeh 2.4 and panel on master.

**Comment by philippjfr** [comment]
Unfortunately I can't fix it without being able to reproduce it so I'll park this for now.

**Comment by tokotchd** [comment]
Some additional information from my own experimenting:
1. Bug does not happen when personally compiling master branch of panel locally (python 3.9)
2. Bug does happen on Python 3.7 using conda to install panel+bokeh
3. Bug does happen on Python 3.7 + Python 3.9 using native pip to install panel+bokeh

I've also tried chrome, firefox, and OperaGX on ubuntu and windows (clients) with no difference between them.
I've tried both ubuntu and windows webhosts for the bug and there's no difference between them.

My best guess right now is that this is an issue with python version and/or using the prepacked .wheel or .egg versus compiling from source? 

I'll keep digging as I have the time.

Thanks

**Comment by philippjfr** [comment]
That's helpful thanks! I'll try to dig into those packages and see if they're maybe missing something.

**Comment by philippjfr** [comment]
Can you maybe try again with the `0.12.4rc2` build?

**Comment by tokotchd** [comment]
From experimenting with the RC build and conda/pip I have discovered that my issue is stemming from a repository/mirror configuration setup and not from this library itself.  From my understanding of the issue it shouldn't affect any other users.

I appreciate the time taken for helping with debugging and your dev work.  Closing the ticket!
