### ISSUE TITLE
ERROR: 'Document' object has no attribute '_callbacks'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2755]
I've just installed Panel from scratch according to the developer guide https://panel.holoviz.org/developer_guide/index.html.

When I `panel serve 'script.py' --autoreload --show` I get

```bash
ERROR: 'Document' object has no attribute '_callbacks'
```

(I installed this from scratch as I got the same error in my existing installation).

## script.py

```python
import panel as pn
import pandas as pd
import param

pn.extension()

data = pd.DataFrame()

class MyDataClass(param.Parameterized):
    data = param.DataFrame()

my_data = MyDataClass()

button = pn.widgets.Button(name="UPDATE")

@param.depends(button.param.value)
def update(value):
    my_data.data = pd.DataFrame({"x": [1]*10})

pn.Column("# Test", pn.Param(my_data), button).servable()
```

**Comment by maximlt** [comment]
What version of bokeh do you have?

**Comment by maximlt** [comment]
Without https://github.com/holoviz/panel/pull/2741 being merged it's likely that you end up with a 2.3 version instead of the actually required 2.4 one.

**Comment by Hoxbro** [comment]
I'm having the same problem and I'm running on master branch of panel and bokeh version 2.4.0. The problem only happens when running `panel serve` with `--autoreload`. The error is coming from: https://github.com/holoviz/panel/blob/80a66c3f03b255c417dc0dc246e41b360fe5d9c4/panel/command/serve.py#L39

**Comment by philippjfr** [comment]
Damn, looks like we indeed missed a compatibility change with Bokeh 2.4 and will likely have to release **another** patch release (i.e. 0.12.4).
