### ISSUE TITLE
Add ability to nest other panel components inside Tabulator rows

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#2761]
Today I came across a usecase for the ability to nest tables. However we do not need to limit the nesting to other tables but instead provide the ability for users to insert arbitrary Panel objects inside Tabulator rows and treat it kind of like an accordion. This would be useful in a variety of scenarios, in particular when you want to be able to show a lot of additional detail about a particular table row. 

In Tabulator this can relatively easily be implemented using the `rowFormatter` and [here is an example](http://tabulator.info/examples/4.5#nested-tables).

**Comment by MarcSkovMadsen** [comment]
I have an angular application where if i click the row it expands and I can see a highly customized chart. That has worked really well

**Comment by philippjfr** [comment]
Just want to record my thoughts about implementation. I think requiring the panel objects to be inserted as a column on the dataframe would be weird so instead I would like to allow defining a `row_detail` function which is given the table row as an argument and can return either an HTML string OR a panel object, which will be rendered below the table row.

**Comment by philippjfr** [comment]
And yes I agree that this needs to be dynamic. One other question I had is whether we should also support JS formatter functions?

**Comment by MarcSkovMadsen** [comment]
Probably. But supporting js functions could need some generalized thoughts. Most js libs including viz libs (for example echarts) can do amazing things if js is supported.

but maybe a way of supporting this is examples of using these js libs via Reactive HTML?

**Comment by philippjfr** [comment]
Got it working, PR coming shortly:

![tabulator_nested](https://user-images.githubusercontent.com/1550771/134156863-91a7e44d-cb35-4eb5-9c4d-e2245b644744.gif)

**Comment by philippjfr** [comment]
This was implemented.
