### ISSUE TITLE
Regression in Panel Exports with INLINE resources.

### ISSUE THREAD

**Issue by hokieg3n1us** [holoviz/panel#2790]
Upgrading from 0.11.3 to 0.12.X, the CSS styling for many Panel components is not being exported with the INLINE resources for the HTML. This is preventing my team from being able to upgrade, since we export and serve static self-contained reports. 

Minimal Code Example:

```python
import panel as pn
from bokeh.resources import INLINE

pn.extension()

column = pn.Column()
column.append(pn.pane.Alert("WARNING", alert_type="warning"))
column.append(pn.Card(title="CARD", width=400, height=400, collapsible=False))

column.save('panel-css.html', resources=INLINE)
```

In 0.11.3, HTML shown below:

![image](https://user-images.githubusercontent.com/36244490/135167530-25c7a530-60e0-4f6d-8347-d2ccd8d9924c.png)

In 0.12.1 and 0.12.4:

![image](https://user-images.githubusercontent.com/36244490/135167144-16511eac-064c-4259-b122-5ed55aa34cd0.png)

Additionally, a cause for concern that I noticed, the exported HTML in 0.12.4 doubled in size. 
![image](https://user-images.githubusercontent.com/36244490/135167364-d5de46b8-90c2-41f4-9bac-333153050875.png)

**Comment by philippjfr** [comment]
Resolved the bug in #2794. As for the file size that's down to Bokeh now including a 1.8 MB bokeh-mathjax.js bundle. We'll have to to some work to ensure that Panel only includes the bundles that are actually used in which case the file size will probably shrink.

**Comment by philippjfr** [comment]
Opened an issue about the file size issue or more specifically bokeh bundling behavior here: https://github.com/holoviz/panel/issues/2796

**Comment by hokieg3n1us** [comment]
That was quick work. Thanks for that @philippjfr, and for opening a ticket for the file size.
