### ISSUE TITLE
Avoid bundling unused resources in saved files, notebooks and on server

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#2796]
Currently we inject all bokeh bundles in a server context and when saving to HTML. In the server/notebook context this is because we cannot know which bundles might be needed at a later stage and in the save context we currently do it because bokeh does not correctly discover that panel.js requires both the widget and table bundles to be available. In the past this was not a huge issue since the supplemental bundles were either required anyway for Panel (widget/table) or they were small (webGL), however with the addition of a 1.8 MB MathJax bundle in Bokeh 2.4 this is a real issue now.

The save context is easy to fix I think by simply including a dummy `DataTable` model when asking bokeh to generate the JS bundle (although it'd be nice if we had explicit control here). For the notebook and server case I would at minimum like to offer an option for a user to explicitly disable the inclusion of certain bundles (specifically webGL and MathJax) and maybe even ask a developer to explicitly enable the MathJax bundle if it is not included in the app on load.

**Comment by mattpap** [comment]
Shouldn't have this issue been open on bokeh, or is panel's handling of resources so different for this to be handled separately? We have to solve this problem in bokeh anyway.

**Comment by philippjfr** [comment]
Wanted to discuss it with you in person before filing a Bokeh issue.
