### ISSUE TITLE
Toast Widget (pop up notifications)

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2802]
Often times you would like to inform the user of progress, events, errors etc. One way to do this is via a `Toast`.

## Potential Requirements

- success+error message
  - Other message types, for example corresponding to `button_type`
- string message
- Markdown string message
- Supports icons
- Can trigger event/ action when clicked
- Supports buttons
- General pane message like `HoloViews` plot or `Markdown` pane
- Prevents duplicate messages/ Allows duplicate messages
- Can provides list of historical messages and maybe even show them to the user
- Can send Web Notifications

## Potential JS Libraries

- [Notyf](https://github.com/caroso1222/notyf)
- [Toastr](https://codeseven.github.io/toastr/demo.html)
- [Sweet Alert](https://github.com/sweetalert2/sweetalert2) (Very advanced features)
- [Notistack](https://iamhosseindhv.com/notistack/demos) (react based)
- [Toastify](https://github.com/apvarun/toastify-js)
- [Notie](https://github.com/jaredreich/notie) (Works like an Alert).
- [PNotify](https://sciactive.com/pnotify/) (Supports showing lots of toast using a system called *modalish*).

You can find a very long list here https://openbase.com/categories/js/best-javascript-toast-libraries

## Panel Example - Notyf

See https://discourse.holoviz.org/t/toast-a-pop-up-notification/2903

![toast](https://user-images.githubusercontent.com/42288570/136136746-b2ba3b84-daef-462e-b2e1-e5c034141a47.gif)

**Comment by maximlt** [comment]
@MarcSkovMadsen can we close this issue now we have `Notfications`? :)

**Comment by MarcSkovMadsen** [comment]
Yes
