### ISSUE TITLE
Tabulator: selectable="checkbox" results in auto-selection upon editing

### ISSUE THREAD

**Issue by lermana** [holoviz/panel#2806]
A `pn.Tabulator` created with `selectable="checkbox"` results in the following condition:

- if someone clicks in to edit a cell, that cell's row is automatically selected

I think the expectation is that the selection and editing are decoupled, i.e. someone could edit a cell without having to select it.

Panel version `0.12.1`.

**Comment by philippjfr** [comment]
Thanks @lermana! Let's consider this as a bug and fix it in 0.12.5.
