### ISSUE TITLE
Session problem with pn.serve

### ISSUE THREAD

**Issue by c-stephan** [holoviz/panel#2820]
**Software version :**
Panel 0.12.4

**Description of the bug  :** 
When uploading a dashboard I realized that the dashboard shared the same sessions for all users. when I use pn.serve.

However if I use the command line `panel serve Dashboard.ipynb` it will work independently for each user.

**A reproducible example :** 
```
import panel as pn
slider = pn.widgets.FloatSlider(name='Another widget', width=200)

pn.serve(pn.Column(slider, width=200))
```

With this code by opening several browsers or by giving access to other computers, the session will be unique.

But if I run panel serve on this  : 
```
import panel as pn
slider = pn.widgets.FloatSlider(name='Another widget', width=200)

pn.Column(slider, width=200).servable()
```

This will manage independent sessions for each user (or window).

**Comment by hyamanieu** [comment]
Philipp,

the documentation is indeed confusing. 

First, the `pn.serve` function is located [within the *Display in the notebook* chapter](https://panel.holoviz.org/user_guide/Deploy_and_Export.html#serving-multiple-apps), although it works in a standard python file the exact same way.

Second, the `panel` argument is presented as something that could either be an object or a function, which is what led to this issue. It is not obvious here that the `param` parameters are shared with all sessions with the former case, while the latter case creates a new instance of the object per session. I'm not even sure I understood it right, but I do believe different bokeh sessions are in fact running in the former case, it's just that all `param` parameters are in sync.
