### ISSUE TITLE
Misc header filters issues

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#2829]
Follow-up on #2807

The 'autocomplete' filter doesn't actually filter the column.
![tabulator_filter_str1](https://user-images.githubusercontent.com/35924738/137497906-0d1fa9ee-aacb-4667-aad5-c8b3f3e62aac.gif)

If I switch to a dropdown filter (there should be an example of that :)), I can filter the column but I can't clear the filter.
![tabulator_filter_str2](https://user-images.githubusercontent.com/35924738/137497931-9cd07670-515e-43ca-add0-ff5256c4bbf7.gif)

It might be a limitation of Tabulator, I can't clear the Gender filter on their interactive demo:
http://tabulator.info/examples/4.9?#filter-header

**Comment by AntonBiryukovUofC** [comment]
I have also noticed that if a table has a frozen row, it gets filtered out, which I think defeats the purpose of freezing the row.

**Comment by philippjfr** [comment]
>I have also noticed that if a table has a frozen row, it gets filtered out, which I think defeats the purpose of freezing the row.

Thanks for reporting this but please provide a reproducible example with the exact version you are using.

**Comment by dslemusp** [comment]
In a similar note the `list` type does not accept the `mutiselect` option.

```python
table_filters = {
    "experiment_type": {"type": "list", "multiselect":"true"},
}


pn_table = pn.widgets.Tabulator(
    experiments_df[["experiment_type"]], 
    pagination="remote", 
    page_size=30, 
    sizing_mode="stretch_width", 
    header_filters=table_filters
)
pn_table.show()
```

![image](https://github.com/holoviz/panel/assets/6799189/0bcf0b3e-d641-4e74-b023-a6be3f4b53f5)

**Comment by maximlt** [comment]
@dslemusp this will be documented in the next version of Panel (https://github.com/holoviz/panel/pull/5825), you need to see the multiselect filter with `func` set to `'in'`.

**Comment by maximlt** [comment]
The first issue I reported in the original post appears to be fixed:
![Kapture 2023-11-14 at 17 02 49](https://github.com/holoviz/panel/assets/35924738/e2186868-0ff4-4621-a940-022cf8df15f4)

I will open an issue for the second one as it is still an issue.
