### ISSUE TITLE
Add a user guide about effective development and debugging practices

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#2833]
When working on Panel, problems can occur, and for complicated apps, it can be hard to know exactly where the problems occur. It could therefore be great to have a user guide about effective development and debugging practices. 

I have been using VS code with the following in my `launch.json` to use VS Code's debug tool on my own apps and to fix Panel / Holoviz issues.

``` json
{
    "name": "Python: Panel",
    "type": "python",
    "request": "launch",
    "module": "panel",
    "args": [
        "serve",
        "${file}",
    ],
}
```
<details><summary>  <i>Screenshot of debugging in action</i> </summary>

![image](https://user-images.githubusercontent.com/19758978/137774188-562ad888-06b2-4b99-b220-cca6e6ef6760.png)

</details>

I suspect other people have similar tools/methods to work and debug Panel with, and it could be nice if these were combined into one place. 

It could also be nice to have the usual questions asked when people have problems with Panel in this guide:
- If they are running on the latest version of Panel / Bokeh / Holoviz stack.
- Look at the browser console.
- The notebook dance (clear notebook, close jupyter, hard refresh browser, etc.)
- Redirect to the discourse if implementation help / Github if it is an issue. Both with a minimal reproducible example.
- Other?

This issue is a continuation of https://discourse.holoviz.org/t/developping-a-panel-app-dev-tools-for-being-efficient-at-it/335

**Comment by MarcSkovMadsen** [comment]
A user is in need of that here as well https://discourse.holoviz.org/t/panel-in-pycharm-debug-mode/5559

**Comment by nishikantparmariam** [comment]
+1 for this. 

We've been using `debugpy` to connect VSCode debugger to Panel Python process for remote debugging and it works great for us. But, we weren't able to make it work when you're developing Panel apps in `.ipynb` files - I've logged an issue https://github.com/microsoft/debugpy/issues/1321 by making a reproducer using nbconvert. Do people have ideas on this?

**Comment by MarcSkovMadsen** [comment]
Hi @nishikantparmariam 

I've been working on a VS code guide PR here. Please consider sharing your tips and tricks there too https://github.com/holoviz/panel/pull/5196. Thanks

**Comment by nishikantparmariam** [comment]
I shared more details on debugging not working when developing apps in `.ipynb` files - https://github.com/microsoft/debugpy/issues/1321#issuecomment-1681653889. Let me know if others have any leads here.

**Comment by MarcSkovMadsen** [comment]
Closing as we now have VS Code and PyCharm guides

https://panel.holoviz.org/how_to/editor/vscode_configure.html
https://panel.holoviz.org/how_to/editor/pycharm_configure.html

If improvements are needed feel free to open new more specific feature requests.
