### ISSUE TITLE
Layout issue in GoldenTemplate

### ISSUE THREAD

**Issue by Jhsmit** [holoviz/panel#2843]
I have encountered an issue with pn.Accordion in the GoldenLayout template:

```python
import panel as pn

btn = pn.widgets.Button(name='Button')
selector = pn.widgets.Select(name='Selector')

acc = pn.Accordion(btn, selector)

md = pn.pane.Markdown('# Main')

tmpl = pn.template.GoldenTemplate(
    site="Panel", title="Golden Accordion",
    sidebar=acc,
    main=md
    )

pn.serve(tmpl)

```

Result:

![image](https://user-images.githubusercontent.com/7881506/138243378-542dc12d-3002-45c4-a856-38b7f6fa0c1f.png)

Error in browser console:

![image](https://user-images.githubusercontent.com/7881506/138243810-a75739d7-11f2-4793-808f-2f12e7a7065e.png)

If I use `FastListTemplate` instead:

![image](https://user-images.githubusercontent.com/7881506/138243628-a5094ef9-41aa-40af-9381-abbb45fbf610.png)

Versions:
```
bokeh                     2.4.1            py38haa244fe_0    conda-forge
holoviews                 1.14.6             pyhd3eb1b0_1
hvplot                    0.7.3              pyhd3eb1b0_1
panel                     0.12.4                     py_0    pyviz
param                     1.11.1             pyhd3eb1b0_0
python                    3.8.11               h6244533_1
```

This issue appears similar to [this](https://discourse.holoviz.org/t/how-can-i-add-third-component-in-goldenlayout/2971) issue posted on Discourse.

When I'm using my custom GoldenLayout Template instead of the one shipped with panel I have the same problem. So I'm suspecting its an issue between bokeh/GoldenLayout.

**Comment by MarcSkovMadsen** [comment]
I can reproduce the problem with Panel 0.12.4 and Bokeh 2.4.1

But with Panel 0.12.6 and Bokeh 2.4.2 I can no longer reproduce.

![image](https://user-images.githubusercontent.com/42288570/147446694-a0383156-ffc8-4c3b-839b-75abd6a2ca19.png)

I will close this one. Please reopen @Jhsmit if you can still reproduce with latest version of Panel and Bokeh. Thanks.
