### ISSUE TITLE
Tabulator converts dates to datetime64[ms] after edit

### ISSUE THREAD

**Issue by bnikolic** [holoviz/panel#2855]
When a dataframe with a date field is passed to Tabulator then any edit to the data in the Tabulator (i.e., if any cell is edited) appears to cause the date column to be converted to "datetime64[ms]" even if the original is in "datetime64[ns]". As a result the dataframe can no longer properly interpret the data. Easy to workaround by using an astype cast but very confusing until you realise what is going on.

Panel version 0.13.0a9.post4+gc97b57e8 but also noted in 0.12.3

```python
import datetime as dt
import numpy as np
import pandas as pd
import panel as pn

pn.extension('tabulator')

print ("Panel version" , pn.__version__)
```

    Panel version 0.13.0a9.post4+gc97b57e8

```python
df = pd.DataFrame({
    'int': [1, 2, 3],
    'float': [3.14, 6.28, 9.42],
    'str': ['A', 'B', 'C'],
    'bool': [True, False, True],
    'date': [dt.date(2019, 1, 1), dt.date(2020, 1, 1), dt.date(2020, 1, 10)]
}, index=[1, 2, 3])

df_widget = pn.widgets.Tabulator(df)

```

```python
df
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>int</th>
      <th>float</th>
      <th>str</th>
      <th>bool</th>
      <th>date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>3.14</td>
      <td>A</td>
      <td>True</td>
      <td>2019-01-01</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>6.28</td>
      <td>B</td>
      <td>False</td>
      <td>2020-01-01</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>9.42</td>
      <td>C</td>
      <td>True</td>
      <td>2020-01-10</td>
    </tr>
  </tbody>
</table>
</div>

```python
df_widget.show() # and change any field in the app
```

    Launching server at http://localhost:58536

    <bokeh.server.server.Server at 0x7f5b68a1a7c0>

```python
df
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>int</th>
      <th>float</th>
      <th>str</th>
      <th>bool</th>
      <th>date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>3.15</td>
      <td>A</td>
      <td>True</td>
      <td>1.546301e+12</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>6.28</td>
      <td>B</td>
      <td>False</td>
      <td>1.577837e+12</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>9.42</td>
      <td>C</td>
      <td>True</td>
      <td>1.578614e+12</td>
    </tr>
  </tbody>
</table>
</div>

```python
df.astype({"date" : "datetime64[ms]"})
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>int</th>
      <th>float</th>
      <th>str</th>
      <th>bool</th>
      <th>date</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>3.15</td>
      <td>A</td>
      <td>True</td>
      <td>2019-01-01</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>6.28</td>
      <td>B</td>
      <td>False</td>
      <td>2020-01-01</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>9.42</td>
      <td>C</td>
      <td>True</td>
      <td>2020-01-10</td>
    </tr>
  </tbody>
</table>
</div>

```python

```

**Comment by philippjfr** [comment]
Will have to investigate, I suspect the issue is that Javascript int types only have 53-bit precision so we basically cannot represent `datetime64[ns]` client-side.

**Comment by philippjfr** [comment]
Also interesting that this only happens on the server and not in a notebook. Not sure why the transport layer would have any effect here.
