### ISSUE TITLE
Terminal example does not allow repeated input

### ISSUE THREAD

**Issue by jlstevens** [holoviz/panel#2864]
Using panel 0.12.4, the Python example [in the docs](https://panel.holoviz.org/reference/widgets/Terminal.html#run-an-interactive-process-in-the-terminal) does not respond to repeated key input.

For instance, I can type `1` at the Python prompt but not `11`.

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/2878
