### ISSUE TITLE
Misc issues with the Tabulator widgets

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#2908]
As of the last dev release:

- [x] After rendering a table and before selecting any row `selected_dataframe` is set to the whole dataframe, while it should probably be an empty dataframe.
- [x] The events returned by `on_edit` report the old value.
- [ ] The `frozen_rows` parameter no longer works:
![image](https://user-images.githubusercontent.com/35924738/141381801-5cfabe81-e22f-462a-882c-876ee19ab494.png)
- [x] Grouping columns manually can end up in a weird state, but that might just be a Tabulator issue. (As a side note I actually didn't even know that the columns could be reordered manually, that's pretty cool!)
![tissue1](https://user-images.githubusercontent.com/35924738/141382144-8aa772e0-92b8-47b9-8181-0c385c49203e.gif)
 - [x] I can't select any row on a paginated table with `pagination='remote'`

**Comment by philippjfr** [comment]
> The events returned by on_edit report the old value.

Ugh, this is a hard one, it works fine on the server but in a notebook we perform client side debouncing which means that the change event of the data actually gets sent **after** the edit event. Might have to temporarily disable debouncing during table edits.

**Comment by philippjfr** [comment]
>Grouping columns manually can end up in a weird state, but that might just be a Tabulator issue. (As a side note I actually didn't even know that the columns could be reordered manually, that's pretty cool!)

Did not realize this was enabled. Would be nice to actually support reordering and reflect that server side. However for now I'd say we just disable it until we have a real way to expose this.

**Comment by maximlt** [comment]
> Did not realize this was enabled. Would be nice to actually support reordering and reflect that server side. However for now I'd say we just disable it until we have a real way to expose this.

Would be nice indeed! But yes let's disable it for now.
