### ISSUE TITLE
Change JSON Pane to Widget

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2918]
I often have parameterized classes with List of Dict parameters. I want to us the `JSON` as a widget for them.

I would like to be able to specify `JSON` as a widget to `pn.Param`. I would like to be able to use `pn.widgets.JSON.from_param`.

Instead I have to use less convenient methods to setup and sync my parameter with the `JSON` pane.

## Solution

Change `JSON` from pane to widget.

**Comment by philippjfr** [comment]
The JSON pane is not a widget by Panel's definition. A `Pane` renders output, a `Widget` allows editing the output. We will add a JSONEditor eventually and I'd even be open to supporting a `Pane` in pn.Param mappings for constant/readonly parameters. Would be happy to see that as an issue.
