### ISSUE TITLE
ReactiveHTML: descriptor does not exist

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2937]
Panel 0.12.4

Seems using a variable name like `datamodel` causes a `odel` property descriptor does not exist 😄 

```python
import panel as pn

class MyElement(pn.reactive.ReactiveHTML):
    _template = """<div id="component">Hi</div>"""
    _scripts = {
        "render": "const datamodel=data"
    }

MyElement().servable()
```

![image](https://user-images.githubusercontent.com/42288570/142737181-3c075f58-9714-4db4-9665-73afdf2514f7.png)

**Comment by MarcSkovMadsen** [comment]
I experienced another similar issue which can be condensed to.

```python
import panel as pn
import param

class MyElement(pn.reactive.ReactiveHTML):
    data_url = param.String("abcd")
    _template = """<div id="component">Hi</div>"""
    _scripts = {
        "render": """dt={data_url: "abcd};dt.data_url="123";"""
    }

MyElement().servable()
```

![image](https://user-images.githubusercontent.com/42288570/142738111-d0891ff2-51c7-4a14-9eff-08c3d14e512a.png)

**Comment by philippjfr** [comment]
Ugh, really silly one letter mistake in the data model assignment detection regex.

Was `data.([^[^\d\W]\w*)` should be `data\.([^[^\d\W]\w*)`.
