### ISSUE TITLE
Style of the buttons is not displayed correctly

### ISSUE THREAD

**Issue by c-stephan** [holoviz/panel#2950]
**Software version :**
Panel 0.12.5

**Description of the bug  :** 
I'm not 100% sure this is a bug, but with the FastListTemplate ButtonTypes are not showing correctly.
The warning button is the same as the default and the others ones are just differents. Maybe because of the Template.

**A reproducible example :** 
```
import panel as pn
default = pn.widgets.Button(name='default', button_type='default',
                                       width=150, height=40)
primary = pn.widgets.Button(name='primary', button_type='primary',
                                        width=150, height=40)
success = pn.widgets.Button(name='success', button_type='success',
                                       width=150, height=40)
warning = pn.widgets.Button(name='warning', button_type='default',
                                       width=150, height=40)
danger = pn.widgets.Button(name='danger', button_type='danger',
                                       width=150, height=40)
light = pn.widgets.Button(name='danger', button_type='light',
                                       width=150, height=40)

dashboard = pn.template.FastListTemplate()
dashboard.main.append(pn.Row(default, primary, success, warning, danger, light))

dashboard.servable()
```

With this code, all types of buttons are displayed. You can see the strange button_type for this template. 
I then tried to compare with the other templates and it is the only one in this case.  
BUT for : MaterialTemplate, BootstrapTemplate, VanillaTemplate, FastListTemplate and GoldenTemplate the 'warning' look like the 'default' type.

**Comment by MarcSkovMadsen** [comment]
Hi @c-stephan. Thanks for reporting this. It's a bit tricky because the button types used by Panel are really a bootstrap concept. It's not something the Fast Button supports. Instead it supports an appearance which can be `accent`, `lightweight`, `neutral`, `outline` or `stealth`. 

Furthermore the `light` `button_type` was added after the `FastTemplates` where styled and has not been updated accordingly.

If someone could specify the best conversion from `button_type` to `accent` I would be happy to update.

You can play around with the original `fast-button` here https://explore.fast.design/components/fast-button.

**Comment by philippjfr** [comment]
These are the updated styles for the Fast design:

<img width="1029" alt="Screen Shot 2023-05-06 at 15 09 47" src="https://user-images.githubusercontent.com/1550771/236626244-c6b2966d-f618-4c26-aed3-f9f91ff4b610.png">
<img width="1021" alt="Screen Shot 2023-05-06 at 15 10 11" src="https://user-images.githubusercontent.com/1550771/236626251-38a86eb4-e886-49a3-a9a4-9e1b863d08c6.png">

>BUT for : MaterialTemplate, BootstrapTemplate, VanillaTemplate, FastListTemplate and GoldenTemplate the 'warning' look like the 'default' type.

This is a bug in your code, you had:

```python
warning = pn.widgets.Button(name='warning', button_type='default',
                                       width=150, height=40)
```
