### ISSUE TITLE
IDOM Documentation: ImportError: cannot import name 'IDOM_CLIENT_IMPORT_SOURCE_URL

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2962]
If you go to https://panel.holoviz.org/reference/panes/IDOM.html you see

![image](https://user-images.githubusercontent.com/42288570/144026066-8dc866c0-23b2-43ed-a08a-8feaed190918.png)

**Comment by philippjfr** [comment]
I'm aware and should have noted that in the docs (and hidden the IDOM pane for now). I really do not have the bandwidth to make the necessary updates so unless that's something you want to tackle I will bump the actual work on this to a later milestone.

**Comment by MarcSkovMadsen** [comment]
Understand. Feel free to bump.

**Comment by kenzylouis** [comment]
Hi @philippjfr. Any update on this? Thanks.

**Comment by philippjfr** [comment]
Closing, the IDOM integration is no longer maintained. If there's interest we'll revive it as a separate extension.
