### ISSUE TITLE
Support mypy by adding py.typed file

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2968]
When running mypy on my code containing `panel` I get `error: Skipping analyzing "panel": found module but no type hints or library stubs`.

This is a problem for me because 

1) I cannot get help from my editor/ IDE because it does not understand the panel code
2) I have to spend time on *ignoring* this signal.

I believe its relatively easy to fix as its a matter of adding a py.typed file to the project. See https://stackoverflow.com/questions/60716482/error-skipping-analyzing-flask-mysqldb-found-module-but-no-type-hints-or-lib.

I know that adding type hints all over Panel could take time. This is not the request. It is just adding this file.

Thanks.

**Comment by philippjfr** [comment]
I'm at the point where I would happily start adding typing to Panel but am also happy to accept a PR adding the typing file for now.
