### ISSUE TITLE
JSON pane does not adjust height when object changes

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2971]
Panel: 0.12.5

I would expect the "Something else" text to be moved downwards when the JSON pane expands. But it does not.

https://user-images.githubusercontent.com/42288570/144559504-d71edd15-9faf-477a-9752-20564bdb6b44.mp4

```python
from typing import Dict
import panel as pn
from typing import Dict

pn.extension(sizing_mode="stretch_width")

def data(n):
    return {index: index for index in range(n)}

slider = pn.widgets.IntSlider(value=0, start=0, end=100)
idata = pn.bind(data, slider)
pn.Column(
    slider,
    idata, "Something else"
).servable()
```

**Comment by Hoxbro** [comment]
If I change this line 
https://github.com/holoviz/panel/blob/d15caf60444ff31b4017fda830ec21d98296e602/panel/models/layout.ts#L76
to: 
``` typescript
  if (cached != null && cache_count != null && (cache_count >= min_count) && (isFinite(viewport.width)) && (isFinite(viewport.height))) {
```
It moves "Something else" down with the resizing of the JSON pane.

https://user-images.githubusercontent.com/19758978/146680118-0f882ca7-f42f-4c74-a38a-50688bf7e1db.mp4

**Comment by philippjfr** [comment]
Nice, @Hoxbro! Could you make a PR with that change?

**Comment by CmpCtrl** [comment]
Im running into a very similar issue currently (panel 0.13.0), the difference is that the resizing isn't happening correctly when expanding or collapsing objects in the json display.

**Comment by MarcSkovMadsen** [comment]
Could you please create a new issue with a reproducible code example. Its much, much easier to start from for the maintainers. Thanks.

**Comment by philippjfr** [comment]
This issue should have been reopened in any case since the fix had to be reverted.

**Comment by philippjfr** [comment]
Fixed in main due to the new bokeh 3.x layout engine.
