### ISSUE TITLE
Panel markdown output goes to new line 

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#2976]
#### ALL software version info
Python 3
Jupyter Lab 3
Panel 0.12.4

#### Description of expected behavior and the observed behavior
The following code goes to new line on typing something while I would expect it to remain on the same line.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn
pn.extension()

def f(x):
    return pn.pane.Markdown(x)

pn.interact(f, x="Hi there!", )
```

#### Screenshots or screencasts of the bug in action
![panel bug](https://user-images.githubusercontent.com/25079291/144708061-c5213984-eb48-4e1d-aaa0-12fbd56d6bfe.gif)

**Comment by nghenzi** [comment]
I think the markdown panel component has a fixed width. When the text gets to the left, it begins a new line.

**Comment by govinda18** [comment]
@nghenzi Is there a way to make it responsive?

**Comment by ahuang11** [comment]
Maybe:
`pn.pane.Markdown(sizing_mode='stretch_width')`

**Comment by govinda18** [comment]
@ahuang11  I already tried that actually but it did not work.

**Comment by ahuang11** [comment]
Have you done it on the container too?

**Comment by MarcSkovMadsen** [comment]
## Workaround

Hi @govinda18. You can use `pn.extension(sizing_mode="stretch_width")`.

```python
import panel as pn
pn.extension(sizing_mode="stretch_width")

def f(x):
    return pn.pane.Markdown(x)

pn.interact(f, x="Hi there!", ).servable()
```

![image](https://user-images.githubusercontent.com/42288570/147729326-884239cf-f997-41fb-9a77-0fcd9a70a7fd.png)

**Comment by MarcSkovMadsen** [comment]
@govinda18. I hope this solves you problem. If not please reopen and specify what you would propose changed in Panel. Thanks.
