### ISSUE TITLE
MultiChoice has too much height

### ISSUE THREAD

**Issue by ItamarShDev** [holoviz/panel#2979]
It seems like MultiChoice reserves  place for the options, which mess around with other elements below it.

It seems that the options are hidden but still there when inspecting.

![image](https://user-images.githubusercontent.com/953371/144871393-ba0a6c4b-f8c0-4ac4-9c07-38bdfebe5a3e.png)

**Comment by ItamarShDev** [comment]
![image](https://user-images.githubusercontent.com/953371/144872520-a55c7a96-81f5-49c6-96bf-3058a876247a.png)

**Comment by philippjfr** [comment]
I'm not quite following tbh, in the example we explicitly put it in a column with a fixed height so that the items are not cut off by the cell below it. In an actual application if you do not add the column you should not have that issue. So could you explain precisely what your issue is?

**Comment by ItamarShDev** [comment]
I want to use the input in the application without it taking extra height.
![image](https://user-images.githubusercontent.com/953371/146667755-ebc76b31-8a39-4b64-b6a4-66e563ba6d11.png)


Will be happy to supply more info if neeeded
