### ISSUE TITLE
Provide list of all user-defined watchers associated with a widget

### ISSUE THREAD

**Issue by jsignell** [holoviz/panel#298]
## Problem Statement
At the moment there is no good way to view all the user-defined watchers associated with a widget. All of the watchers are available at `widget._param_watchers`, but included in that dict is a lot of internal watchers that the user shouldn't care about. 

The main use case for such a list would be to unwatch all the watchers - but I could also imagine making a graph of the relationships between different widgets using such a list. 

## Minimal example
```python
import panel as pn

md = pn.pane.Markdown('Did clicks: 0')

def callback(event):
    md.object += f', {event.new}'
    
button = pn.widgets.Button(name='CLICK')
watcher = button.param.watch(callback, 'clicks')

pn.Column(button, md)
```

```python
>>> watcher in button._param_watchers['clicks']['value']
True
```

## Proposal

I think there should be a separate list that captures all the watchers that a user defines on a particular widget. 

```python
>>> button._watchers == [watcher]
True
```

I think this list would mostly be used to support user-facing functionality like:

```python
>>> button.unwatch()  # unwatch all of the watchers in button._watchers
```

**Comment by jbednar** [comment]
Functionality like this seems useful to me.  I'd think that it should apply to user-defined watchers by default, but for it to be configurable to allow access to/removal of watchers of any type if requested.

**Comment by philippjfr** [comment]
I'm not giving users access to internal watchers via a public api. Too much potential to break things for no benefit as far as I can see.

**Comment by jbednar** [comment]
Up to you.

**Comment by kcpevey** [comment]
something like what dash does:
https://community.plotly.com/t/announcing-dash-dev-tools/22481

**Comment by philippjfr** [comment]
Since param 2.0 watchers are now listed under: `.param.watchers`.
