### ISSUE TITLE
Add ability to inline internal resources in Jupyter

### ISSUE THREAD

**Issue by jonnyboynewton** [holoviz/panel#3013]
We are running a jupyter-lab application environment behind a strict firewall and users cannot access the internet.  Hence for all panel work we have a default environment variable set for PANEL_INLINE

This works for most panels functions but not for tabulator as the code for models/tabulator.py has explicit dependence on the tabulator and moment CDNs.  I think this is an issue for plotly functions too.

As a general feature request - PANEL_INLINE should inline all panel and included items like tabulator, plotly (bokeh seems to work)

**Comment by jonnyboynewton** [comment]
from panel/models/tabulator.py:

JS_SRC = "https://unpkg.com/tabulator-tables@5.0.7/dist/js/tabulator.js"
MOMENT_SRC = "https://cdn.jsdelivr.net/npm/luxon/build/global/luxon.min.js"

THEME_PATH = "tabulator-tables@5.0.7/dist/css/"
THEME_URL = f"https://unpkg.com/{THEME_PATH}"
PANEL_CDN = f'https://cdn.jsdelivr.net/npm/@holoviz/panel/dist/bundled/{THEME_PATH}'


none of this supports PANEL_INLINE from what I can tell..

**Comment by philippjfr** [comment]
This is a general problem that goes beyond just tabulator and affects all external components. We do not currently support inlining external resources. However since we a) bundle all external components and b) have a server extension for Jupyter that serves up the bundled resources we should be able to server them from that endpoint instead.

**Comment by MarcSkovMadsen** [comment]
Just for reference. Dove88 is also trying to use Tabulator and Plotly offline in a notebook without luck. See https://discourse.holoviz.org/t/panel-doesnt-show-output-in-the-jupyter-lab-notebook/5104.

**Comment by philippjfr** [comment]
Yup working on this in the coming week. Technically this should already work on main but it's loading from an endpoint that isn't always defined so I'll experiment with inlining instead.

**Comment by sunilkr** [comment]
We too have an isolated environments where having tabualtor working in offline context with solve most of Jupyter UI issues.

**Comment by sunilkr** [comment]
@philippjfr I am still seeing requests being made to following URLs which fails on an isolated device.

https://cdn.holoviz.org/panel/1.1.0/dist/panel.min.js

Following are installed packages.

bokeh 3.3.0
panel 1.1.0

Was my understanding of this patch was incorrect that updated versions would work in offline context?

**Comment by philippjfr** [comment]
Inline resources are very inefficient and therefore not enabled by default. If you want to inline resources you should request it explicitly with pn.extension(inline=True)

**Comment by sunilkr** [comment]
@philippjfr Issue I reported just now has disappeared, but I am still seeing failed requests to following URLs which makes the rendered table illegible.

```
Failed to load resource: net::ERR_CONNECTION_CLOSED  https://cdn.holoviz.org/panel/1.1.0/dist/css/loading.css
 loading.css:1

Failed to load resource: net::ERR_CONNECTION_CLOSED https://cdn.holoviz.org/panel/1.1.0/dist/bundled/font-awesome/css/all.min.css
all.min.css:1 


Failed to load resource: net::ERR_CONNECTION_CLOSED https://cdn.holoviz.org/panel/1.1.0/dist/bundled/theme/default.css
default.css:1 


Failed to load resource: net::ERR_CONNECTION_CLOSED https://cdn.holoviz.org/panel/1.1.0/dist/bundled/theme/native.css
native.css:1 


Failed to load resource: net::ERR_CONNECTION_CLOSED https://cdn.holoviz.org/panel/1.1.0/dist/bundled/datatabulator/tabulator-tables@5.4.4/dist/css/tabulator_simple.min.css
tabulator_simple.min.css:1 
```

**Comment by sunilkr** [comment]
@philippjfr I was looking around in the source to see if putting css in the installation folder would work.
I see that [loading.css](https://github.com/holoviz/panel/blob/111242ac939aa51449bed50dd4c5b98922fa4f17/panel/dist/css/loading.css#L1) exists, but other css files are missing.

Also, `panel/dist/css/bundled` does not contain `font-awesome` folder.

**Comment by sunilkr** [comment]
Hi @philippjfr , should I create a new issue for this?

**Comment by philippjfr** [comment]
Please do, thank you!
