### ISSUE TITLE
Tooltips can not be disabled in the DeckGL pane

### ISSUE THREAD

**Issue by danwild** [holoviz/panel#3015]
Tested in `panel=0.12.6` with `pydeck==0.7.1` but pretty sure I saw the issue in previous versions.

The [docs for DeckGL pane](https://panel.holoviz.org/reference/panes/DeckGL.html) indicate there are two tooltip settings:

- `pydeck.Deck.tooltip`; and 
- `pn.pane.DeckGL.tooltips`

Both of these accept `Boolean` type, so I would expect that setting either (or both) of these to `False` should disable tooltips, however this is not the case.

This can be easily reproduced in the [PyDeck notebook example from the docs](https://hub.gke2.mybinder.org/user/holoviz-panel-lyvsn525/lab/tree/examples/reference/panes/DeckGL.ipynb#PyDeck):

- pass `tooltip=False` to `pydeck.Deck`; and/or
- pass `tooltips=False` to  `pn.pane.DeckGL`

Any combination I try, I still get a tooltip showing up on the map:

<img width="842" alt="Screen Shot 2021-12-14 at 13 38 24" src="https://user-images.githubusercontent.com/3774647/145923064-3570c00f-8fe8-46e8-9996-b374c52efaab.png">

Cheers,
Dan

**Comment by maximlt** [comment]
Thanks @danwild, I could reproduce this issue.

**Comment by MarcSkovMadsen** [comment]
I've tried to identify the cause. If I change `tooltips` to `tooltip` every where in the `deckgl.py` pane file it starts working. So somehow the `tooltips` to `tooltip` transform is not working or sent to the client.

**Comment by MarcSkovMadsen** [comment]
For some unknown reason this starts working if I change the default `.ts` value from `{}` to `false`.
