### ISSUE TITLE
Tabulator overlaps with other widgets when using Row

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#3028]
#### ALL software version info
``` yaml
panel    0.12.6
```
#### Description of expected behavior and the observed behavior
When using `pn.Param` on a DataFrame as a `pn.widgets.Tabulator` it overlaps with other `pn.widgets.Tabulator`.

#### Complete, minimal, self-contained example code that reproduces the issue
``` python
import param
import pandas as pd
import panel as pn
pn.extension('tabulator')

class Example(param.Parameterized):
    dataframe = param.DataFrame(pd._testing.makeDataFrame())

    def __init__(self, **params):
        super().__init__(**params)
        # This overlaps:
        self.view = pn.Param(self.param, widgets={"dataframe": pn.widgets.Tabulator})
        
        # This do not overlap:
        #self.view = pn.Param(self.param, widgets={"dataframe": pn.widgets.Tabulator})[1]

        # This do not overlap:
        # self.view = pn.widgets.Tabulator.from_param(self.param.dataframe)

    def stat_view(self):
        return pn.widgets.Tabulator(self.dataframe.describe())

    
e = Example()
pn.Row(e.view, e.stat_view)

```

#### Screenshots or screencasts of the bug in action
With overlap:
![Screenshot 2021-12-21_16 36 08](https://user-images.githubusercontent.com/19758978/146958149-eea7d328-18aa-4fd9-8150-7cb1c4b0ac5c.png)

With no overlap:
![Screenshot 2021-12-21_16 36 17](https://user-images.githubusercontent.com/19758978/146958190-e4b6f5f2-7133-4b0a-a3fc-a2800f4c6e89.png)

**Comment by dharhas** [comment]
I'm seeing a similar issue.

```python
pn.Row(pn.widgets.Tabulator(pd._testing.makeDataFrame()), pn.pane.Markdown('TEST'))
```
![Tabulator_overlap](https://user-images.githubusercontent.com/561301/146982754-e2a36369-340d-442d-8d0a-14a95b065932.png)

**Comment by philippjfr** [comment]
Issue is fixed on main due to the new layout engine.
