### ISSUE TITLE
pn.ipywidget is not working on 0.12

### ISSUE THREAD

**Issue by ItamarShDev** [holoviz/panel#3030]
```
jupyterlab===2.0.1
ipywidgets===7.5.1
panel===0.12.6
jupyter-bokeh===2.0.4

```

![image](https://user-images.githubusercontent.com/953371/147092649-72dd4db3-d33b-411c-9509-7fab1a6dc945.png)

**Comment by philippjfr** [comment]
What version of `jupyter_bokeh` do you have?

**Comment by philippjfr** [comment]
Thanks for the issue. Please try upgrading to jupyter_bokeh 3.0.2 and reopen if you still experience issues.
