### ISSUE TITLE
Plotly boxplot Interactivity within tabs not working since version 0.12.5

### ISSUE THREAD

**Issue by alon-sht** [holoviz/panel#3041]
Hi, 
Plotly interactivity stopped working for me since v0.12.5 within tabs, see an example below 
Problems happen also on v0.12.6, but not on v0.12.4
I am using Plotly v 5.4.0

Description of the problems:
- hover not showing; hover sometimes (for reasons i cannot explain) works on the right-most and left-most ~20% of the plot, but not in the middle....
- zooming not reacting 
- double clicking to reset shows notification but nothing is changing
- panning not working
- zooming in and out still works

```
import plotly.express as px
import panel as pn
import pandas as pd
import numpy as np
pn.extension("plotly")
box_tabs=pn.Tabs()
scatter_tabs=pn.Tabs()
df=pd.DataFrame(np.random.randint(1,100,size=(150,15)),columns=['x0','y0','z0','x1','y1','z1','x2','y2','z2','x3','y3','z3','x4','y4','z4']).reset_index()
for i in range(0,5):
    scatter=px.scatter_3d(df,x='x'+str(i),y='y'+str(i),z='z'+str(i))
    scatter.update_layout(autosize=True)
    scatter_tabs.append(pn.Column(pn.panel(scatter, config={'responsive': True}), sizing_mode="stretch_both"))

for i in range(0,3):
    box=px.box(df,x='x'+str(i),y='y'+str(i))
    box.update_layout(autosize=True)
    box_tabs.append(pn.Column(pn.panel(box, config={'responsive': True}), sizing_mode="stretch_both"))
main_tabs=pn.Tabs(box_tabs,scatter_tabs)
main_tabs.servable()
```

In this example the issue happens with the box plots but not with the 3d scatter plots

Hope someone can help me with this issue, since older versions have different problems with plotly within tabs that were fixed for me since this version

**Comment by MarcSkovMadsen** [comment]
## Workaround

Hi @alon-sht 

On the current `master` branch with `plotly==5.5.0` and `dynamic=True` on Tabs it seems to work.

https://user-images.githubusercontent.com/42288570/147885814-80475bd6-dabc-41e5-96da-9c5ed6c9cec3.mp4

```python
import plotly.express as px
import panel as pn
import pandas as pd
import numpy as np
pn.extension("plotly")
box_tabs=pn.Tabs(dynamic=True)
scatter_tabs=pn.Tabs(dynamic=True)
df=pd.DataFrame(np.random.randint(1,100,size=(150,15)),columns=['x0','y0','z0','x1','y1','z1','x2','y2','z2','x3','y3','z3','x4','y4','z4']).reset_index()
for i in range(0,5):
    scatter=px.scatter_3d(df,x='x'+str(i),y='y'+str(i),z='z'+str(i))
    scatter.update_layout(autosize=True)
    scatter_tabs.append(pn.Column(pn.panel(scatter, config={'responsive': True}), sizing_mode="stretch_both"))

for i in range(0,3):
    box=px.box(df,x='x'+str(i),y='y'+str(i))
    box.update_layout(autosize=True)
    box_tabs.append(pn.Column(pn.panel(box, config={'responsive': True}), sizing_mode="stretch_both"))
main_tabs=pn.Tabs(box_tabs,scatter_tabs)
main_tabs.servable()
```

**Comment by alon-sht** [comment]
which version of panel are you using? 
pn.Tabs(dynamic=True) causes an error for me with panel 0.12.6
![image](https://user-images.githubusercontent.com/787767/147910224-ec1c9ab1-bae6-4cce-83eb-838e9751f207.png)

On panel 0.12.6 the hover and all the other reactive functions i mentioned above do not work for me. 


On panel 0.12.4 dynamic=True does not cause an error, the hover and other stuff work but i still see the size changing when switching from tab to tab.

**Comment by MarcSkovMadsen** [comment]
I'm on the current `master` branch of Panel.

**Comment by philippjfr** [comment]
@alon-sht Could you try upgrading to latest `param`?

**Comment by alon-sht** [comment]
> 

It did help in the simplified code above but still doesn't work in my full app for some reason...
here's a list of my environment packages
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
attrs                21.2.0
autopep8             1.6.0
backcall             0.2.0
black                21.9b0
bleach               4.1.0
bokeh                2.4.2
certifi              2020.12.5
cffi                 1.15.0
chardet              4.0.0
charset-normalizer   2.0.7
click                8.0.3
colorama             0.4.4
colorcet             2.0.6
cycler               0.10.0
debugpy              1.4.3
decorator            5.1.0
defusedxml           0.7.1
entrypoints          0.3
et-xmlfile           1.1.0
fonttools            4.28.2
holoviews            1.14.6
hvplot               0.7.3
idna                 3.2
importlib-metadata   4.8.1
ipykernel            6.5.1
ipython              7.29.0
ipython-genutils     0.2.0
ipywidgets           7.6.5
jedi                 0.18.0
Jinja2               2.11.3
jsonschema           4.1.2
jupyter-bokeh        3.0.4
jupyter-client       7.1.0
jupyter-core         4.9.1
jupyterlab-pygments  0.1.2
jupyterlab-widgets   1.0.2
kiwisolver           1.3.1
Markdown             3.3.3
MarkupSafe           1.1.1
matplotlib           3.5.0
matplotlib-inline    0.1.3
mistune              0.8.4
mypy-extensions      0.4.3
nbclient             0.5.9
nbconvert            6.3.0
nbformat             5.1.3
nest-asyncio         1.5.1
notebook             6.4.6
numpy                1.21.2
openpyxl             3.0.9
packaging            20.9
pandas               1.3.0
pandocfilters        1.5.0
panel                0.12.4
param                1.12.0
parso                0.8.1
pathspec             0.9.0
pickleshare          0.7.5
Pillow               8.3.2
pip                  20.2.3
platformdirs         2.4.0
plotly               5.5.0
prometheus-client    0.12.0
prompt-toolkit       3.0.16
pycodestyle          2.8.0
pycparser            2.21
pyct                 0.4.8
Pygments             2.8.0
pyparsing            2.4.7
pyrsistent           0.18.0
python-dateutil      2.8.1
pytz                 2021.1
pyviz-comms          2.1.0
pywin32              302
pywinpty             1.1.6
PyYAML               5.4.1
pyzmq                22.0.3
regex                2021.11.1
requests             2.26.0
retrying             1.3.3
Send2Trash           1.8.0
setuptools           49.2.1
setuptools-scm       6.3.2
six                  1.15.0
smart-open           5.2.1
tenacity             8.0.1
terminado            0.12.1
testpath             0.5.0
toml                 0.10.2
tomli                1.2.2
tornado              6.1
tqdm                 4.62.2
traitlets            5.1.1
typing-extensions    3.10.0.2
urllib3              1.26.7
wcwidth              0.2.5
webencodings         0.5.1
wheel                0.36.2
widgetsnbextension   3.5.2
zipp                 3.5.0
