### ISSUE TITLE
Cannot set page title

### ISSUE THREAD

**Issue by josselex** [holoviz/panel#3049]
Using panel 0.12.6

I cannot set the title of the site. I use panel serve.

However I cannot find the proper way of setting the page title. It is always "Panel Application"
For example this does not work:
```
import panel as pn
pn.extension(sizing_mode='stretch_width')
template = pn.template.FastGridTemplate(
    site="Panel", title="FastGridTemplate",
    sidebar=[pn.pane.Markdown("## Settings")],
)
template.servable()
```

**Comment by jbednar** [comment]
template.servable("Title") ?

**Comment by josselex** [comment]
> template.servable("Title") ?

Thanks. Indeed this works. And also my code above. 

It does not work however when there is another servable in the document. I think this was the error.

**Comment by josselex** [comment]
Is there a proper way to do it? Is this intended behaviour?

**Comment by jbednar** [comment]
Not sure. Try adding the same title to all servable calls?

**Comment by josselex** [comment]
Indeed, it works when adding the title just to the last call. 
My suggestion: Maybe the title should not get overwritten if nothing is passed explecitly.

**Comment by MarcSkovMadsen** [comment]
I cannot reproduce the problem (using Panel: 0.12.6).

If I run the initial script the title is there.

![image](https://user-images.githubusercontent.com/42288570/147560942-e25f302e-1f83-4d8e-8f9a-34cd45ebce58.png)

```python
import panel as pn
pn.extension(sizing_mode='stretch_width')
template = pn.template.FastGridTemplate(
    site="Panel", title="FastGridTemplate",
    sidebar=[pn.pane.Markdown("## Settings")],
)
template.servable()
```

**Comment by josselex** [comment]
> I cannot reproduce the problem (using Panel: 0.12.6).
> 
> If I run the initial script the title is there.

Indeed it works. The problem was caused by another .servable() call below.

MY proposed solution would be that other servable calls do not override the title (to be the default) unless a title is explicitely given there with .servable(title=...)

**Comment by philippjfr** [comment]
Here's what I'd propose:

- The `title` on the template, if set, takes absolute precedence
- If no title is set the last explicitly set `.servable(title=...)` takes precedence
- `.servable()` without a title should have no effect on previously set titles

**Comment by josselex** [comment]
> * The `title` on the template, if set, takes absolute precedence
> 
> * If no title is set the last explicitly set `.servable(title=...)` takes precedence
> 
> * `.servable()` without a title should have no effect on previously set titles

I think this sounds reasonable and intuitive.
