### ISSUE TITLE
remove need to enable serverextension

### ISSUE THREAD

**Issue by raybellwaves** [holoviz/panel#3051]
Per https://discourse.holoviz.org/t/what-does-the-render-with-panel-jupyter-lab-button-do/3039/5

If there a way to not need to do `jupyter serverextension enable panel.io.jupyter_server_extension`

For example doing `jupyter serverextension list` I see the voila extension was enabled (see below) when I installed it. Is there a way to reproduce for this project?

```
config dir: /Users/ray/miniconda3/envs/test_env/etc/jupyter
    voila.server_extension  enabled
    - Validating...
      voila.server_extension  OK
```

**Comment by MarcSkovMadsen** [comment]
It was a decision by @philippjfr not to force the installation. 

I would argue that it should be installed by default if you install Panel. The Panel Jupyter Preview button is so powerful. But its a pain trying to tell users how to install it. And as far as I recall the only docs about it is in a blog post.

Could we just install it by default @philippjfr ?

**Comment by philippjfr** [comment]
Honestly I don't think it was so much as a deliberate decision as it was me not knowing how to do it automatically.

**Comment by MarcSkovMadsen** [comment]
Would it be something you run in `setup.py`.

**Comment by raybellwaves** [comment]
Hope you don't mind me brain storming here.

Looking at voila for inspiration.

`pip install voila`
you get
/Users/ray/miniconda3/envs/test_env/share/jupyter/voila/templates/lab/index.html.j2
https://github.com/voila-dashboards/voila/tree/main/share/jupyter/voila/templates
I think this may be called here
https://github.com/voila-dashboards/voila/blob/main/setup.py

**Comment by Hoxbro** [comment]
I think the extension is now enabled when installing `0.13.1a1` with `jupyterlab>3`. Installed with `pip install panel --pre` or `conda install -c pyviz/label/dev "panel=0.13.1a1" -c conda-forge`. 

I have no idea why it suddenly works. Maybe #3172?

I have tested it on Windows, macOS, and Linux in new conda environments.
