### ISSUE TITLE
panel to work in jupyter lab dark mode

### ISSUE THREAD

**Issue by raybellwaves** [holoviz/panel#3052]
Would be nice  to see text in apps when jupyter lab is in Dark mode

<img width="946" alt="Screen Shot 2021-12-28 at 11 43 36 PM" src="https://user-images.githubusercontent.com/17162724/147628073-b73ef50c-fd92-4887-851b-e7ad64b14c92.png">

<img width="938" alt="Screen Shot 2021-12-28 at 11 45 08 PM" src="https://user-images.githubusercontent.com/17162724/147628137-24f6f484-0367-498e-897f-1efd11dac10b.png">

**Comment by MarcSkovMadsen** [comment]
Related to https://github.com/holoviz/panel/issues/520

**Comment by raybellwaves** [comment]
Thanks @MarcSkovMadsen. Closing as dup
