### ISSUE TITLE
Closable tabs throws errors in jupyter lab

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#3061]
#### ALL software version info
Bokeh 2.4.2
Panel 0.12.4
Jupyter Lab 3.2.3

#### Description of expected behavior and the observed behavior
Closable tabs throws an error in Jupyter Lab. 

![panel-closable-tabs](https://user-images.githubusercontent.com/25079291/148183454-01b4deca-e107-47a0-a7e7-6fb5abcad6fe.gif)

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension()
djs_tabs_2 = pn.Tabs(("C 1", "C1"),("C 2", "C2"),closable=True)
djs_tabs_2

```

**Comment by maximlt** [comment]
Thanks @govinda18 for your bug report, I can reproduce it on both panel `1.12.6` and on the `master` branch:
```python
import panel as pn
pn.extension()
t = pn.Tabs(("C 1", "C1"), ("C 2", "C2"), closable=True)
t
```

**Comment by philippjfr** [comment]
Can no longer reproduce on master, you should be able to install a dev release and confirm. Please reopen if the issue persists.
