### ISSUE TITLE
GoldenTemplate - bokeh.js errors in chrome based browsers

### ISSUE THREAD

**Issue by haditya** [holoviz/panel#3062]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
panel 0.12.6
bokeh 2.4.2
python 3.8
browsers = vivaldi, edge (chromium based)

#### Description of expected behavior and the observed behavior
With regard to posting in discourse https://discourse.holoviz.org/t/goldentemplate-issues/3222/4
Golden Template does not layout the components 
Subsequent inspection of the HTML components revealed that the CSS and JS links have been updated for the goldentemplate layout. 

#### Complete, minimal, self-contained example code that reproduces the issue
From the example here https://panel.holoviz.org/reference/templates/GoldenLayout.html
```
import panel as pn
import numpy as np
import holoviews as hv

pn.extension(sizing_mode='stretch_width')


golden = pn.template.GoldenTemplate(title='Golden Template')

xs = np.linspace(0, np.pi)
freq = pn.widgets.FloatSlider(name="Frequency", start=0, end=10, value=2)
phase = pn.widgets.FloatSlider(name="Phase", start=0, end=np.pi)


@pn.depends(freq=freq, phase=phase)
def sine(freq, phase):
    return hv.Curve((xs, np.sin(xs * freq + phase))).opts(
        responsive=True, min_height=400)


@pn.depends(freq=freq, phase=phase)
def cosine(freq, phase):
    return hv.Curve((xs, np.cos(xs * freq + phase))).opts(
        responsive=True, min_height=400)


golden.sidebar.append(freq)
golden.sidebar.append(phase)

golden.main.append(
    pn.Row(
        pn.Card(hv.DynamicMap(sine), title='Sine'),
        pn.Card(hv.DynamicMap(cosine), title='Cosine')
    )
)
golden.main.append(
    pn.Row(
        pn.Card(hv.DynamicMap(sine), title='Sine'),
        pn.Card(hv.DynamicMap(cosine), title='Cosine')
    )
)

golden.show()

```

#### Stack traceback and/or browser JavaScript console output
![image](https://user-images.githubusercontent.com/61999659/148252337-64a04c8d-41dc-4a53-a1b5-70d8c11d41ca.png)

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/61999659/148252431-7694403a-5731-4d50-a25c-914d369572da.png)

**Comment by haditya** [comment]
If this sounds like a good GFI, I'd be happy to give it a shot at creating a PR later tonight?

**Comment by MarcSkovMadsen** [comment]
Hi @haditya 

I just tried running it on the current `master` branch. And for me your script above works.

![image](https://user-images.githubusercontent.com/42288570/148255365-828e025a-1f35-4a66-9657-0da1f138b56b.png)

It would be very much appreciated if you could try to see if it works with the current `master` and if not make a PR to fix. Thx.

**Comment by haditya** [comment]
Thanks @MarcSkovMadsen 
I see the correct .cs and .js file is in the template code on master and in tag 0.12.6

Something must've broken on my end when I did the conda update panel from 0.12.1

**Comment by haditya** [comment]
@MarcSkovMadsen 
Just removed and re-installed panel in my conda env. Still see the same issue

These files import a URL that doesn't exist - https://golden-layout.com/assets/css/goldenlayout-dark-theme.css
panel\template\golden\*.css

**Comment by haditya** [comment]
Pretty consistently seeing this even after reinstalling my conda env.
Wonder if some dependency is still goofed up somewhere?

Does the uncaught promise in bokeh.min.js - suggest something to anyone?

**Comment by haditya** [comment]
> Hi @haditya
> 
> I just tried running it on the current `master` branch. And for me your script above works.
> 
> ![image](https://user-images.githubusercontent.com/42288570/148255365-828e025a-1f35-4a66-9657-0da1f138b56b.png)
> 
> It would be very much appreciated if you could try to see if it works with the current `master` and if not make a PR to fix. Thx.

@MarcSkovMadsen  - I assume you are also running bokeh 2.4.2?

**Comment by MarcSkovMadsen** [comment]
Hi @haditya 

I can see that there is a difference between chrome and firefox. I can replicate your issue with Panel 0.12.6, bokeh 2.4.2 and Chrome or Edge browser. But it works with firefox (right below).

![image|690x369](upload://rcPLfVi8Xt5P6GVq41waW2u9w2l.png)

```python
import panel as pn
import numpy as np
import holoviews as hv

pn.extension(sizing_mode = 'stretch_width')

golden = pn.template.GoldenTemplate(title='Golden Template')

xs = np.linspace(0, np.pi)
freq = pn.widgets.FloatSlider(name="Frequency", start=0, end=10, value=2)
phase = pn.widgets.FloatSlider(name="Phase", start=0, end=np.pi)

@pn.depends(freq=freq, phase=phase)
def sine(freq, phase):
    return hv.Curve((xs, np.sin(xs*freq+phase))).opts(
        responsive=True, min_height=400)

@pn.depends(freq=freq, phase=phase)
def cosine(freq, phase):
    return hv.Curve((xs, np.cos(xs*freq+phase))).opts(
        responsive=True, min_height=400)

golden.sidebar.append(freq)
golden.sidebar.append(phase)

golden.main.append(
    pn.Row(
        pn.Card(hv.DynamicMap(sine), title='Sine'),
        pn.Card(hv.DynamicMap(cosine), title='Cosine')
    )
)
golden.main.append(
    pn.Row(
        pn.Card(hv.DynamicMap(sine), title='Sine'),
        pn.Card(hv.DynamicMap(cosine), title='Cosine')
    )
)

golden.servable()
```

**Comment by philippjfr** [comment]
Seems related to https://github.com/holoviz/panel/issues/3089

I haven't been able to reproduce yet, but will keep trying.

**Comment by Jhsmit** [comment]
I have the same issue in  a new conda env

I've attached my enironment.yml (renamed to txt) file
[environment.txt](https://github.com/holoviz/panel/files/7890935/environment.txt)

**Comment by philippjfr** [comment]
Can reproduce now, the issue here is that we let the golden layout library dynamically populate the bokeh root DOM nodes but Bokeh executes before they have been added to the DOM. We somehow have to ensure that Bokeh waits until the DOM nodes are actually present.

**Comment by Jhsmit** [comment]
Thanks! I was having people confused when faced with an empty GUI 

I've implemented your hack into my hack of GoldenTemplate for a nice and sustainable solution :)
But it works

**Comment by philippjfr** [comment]
At some point we'll have to somehow get the Bokeh plot script to defer loading until some condition is met but I didn't want to bite that bullet before the 0.13.0 release. Could you maybe open an issue?

**Comment by Jhsmit** [comment]
Ok, I've opened an issue, not sure if done correctly (or if it should have been a bokeh issue) since this stuff is above my pay grade so I've basically copied your previous comments in there
