### ISSUE TITLE
Tabulator selectable=1 not working

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#3074]
MRE:
```python
import numpy as np
import panel as pn
import pandas as pd
pn.extension('tabulator')

df = pd.DataFrame(pd.DataFrame(np.random.rand(10,2), columns=["X1", "X2"]), columns=["X1", "X2"])
t = pn.widgets.Tabulator(value=df,selectable=1)
t
```
![tabulator_bug](https://user-images.githubusercontent.com/18531147/148564123-0a310ee7-80a6-4c30-8bab-75c61faed792.gif)

Calling `t.get_root().select_mode` return `True` instead of 1
Using `selectable=2` does not lead to a bug  `t.get_root().select_mode` return `2`  as expected

removing the default of select_mode make it works.
https://github.com/holoviz/panel/blob/92df8c43bb9df1546ab1c557c3a2e84afcb2f523/panel/models/tabulator.py#L108

However I think the current code should work and seems a bokeh bug

**Comment by philippjfr** [comment]
Thanks for filing this @xavArtley. Not sure there's any way to work around this due to the bokeh issue (https://github.com/bokeh/bokeh/issues/11936).

**Comment by xavArtley** [comment]
I think removing the default value set to True in the custom model will allow at least to make selectable=1 works
It will not solve the problem when changing 1 to True but I think for the moment it's better than nothing
