### ISSUE TITLE
Add reference guide for panel.bind

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3080]
`pn.bind` is said to be the one api to prefer using and communicating to users. It is shown in the getting started sections. But not really promoted as the preferred api.

There is not a good reference guide either. Compare that to the situation with `pn.Param` that has its own Reference Guide https://panel.holoviz.org/reference/panes/Param.html.

If you search for `bind` it is not very clear where to go either https://panel.holoviz.org/search.html?q=bind#

The consequence is that it is hard to point users to `pn.bind`. Where should they go to get the introduction and a deeper dive? How can they really get to understand it?

## Solution

Add reference guide for `pn.bind`.

## Additional Context

![image](https://user-images.githubusercontent.com/42288570/148636398-ec33c0b0-3ef6-4b4c-b477-64696394defa.png)

**Comment by philippjfr** [comment]
Seems like a nice idea to have reference guides for the main APIs:

- Reactive parameter binding with `pn.bind`
- Class based with `pn.depends`
- Callback based with `.param.watch`

**Comment by droumis** [comment]
https://panel.holoviz.org/how_to/interactivity/index.html
