### ISSUE TITLE
User Guide doc is incomplete when compared to downloaded notebook

### ISSUE THREAD

**Issue by dnabb** [holoviz/panel#3082]
The documentation that is currently shown on the User Guide for the [Select widget](https://panel.holoviz.org/reference/widgets/Select.html) seems to be only a subset of what is actually available downloading the [example notebook](https://raw.githubusercontent.com/holoviz/panel/master/examples/reference/widgets/Select.ipynb) with the link at the beginning of the page.  

As example, for the Select widget, the website doesn't show any example of using a `dict` as `option` and doesn't mention `group` (which might be intended, as the example on the notebook does not actually work for me, but this is a different issue).

From what I could find, only the Selected widget doc has a notebook that is 'inconsistent' compared to the user guide, while for other related widgets (I checked DiscreteSlider and RadioButtonGroup) the User Guide is the same as the Notebook.

**Comment by maximlt** [comment]
Yes indeed the link displayed in the box on the right side (`This web page was generated from a Jupyter notebook and not all interactivity will work on this website. Right click to download and run locally for full Python-backed interactivity.`) points to the *master* branch while it should point to a tag. This is an issue in [nbsite](https://github.com/pyviz-dev/nbsite).

**Comment by maximlt** [comment]
Nope I went a little too fast. `nbsite` seems to rely on environment variables to figure out the base path of the notebooks linked in this info box. I believe that if in the docs build we set the environment variable `BRANCH` to the appropriate tag then the link should be fine.

```
# v0.12.6
https://raw.githubusercontent.com/holoviz/panel/v0.12.6/examples/user_guide/Customization.ipynb
# master
https://raw.githubusercontent.com/holoviz/panel/master/examples/user_guide/Customization.ipynb
```
It'd be anyway nice to have `nbsite` accept a `TAG` environment variable or variable instead of `BRANCH` for this case.
