### ISSUE TITLE
Add template kwargs to servable

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3086]
I've been told that Panel would like to promote a code flow where the template is specified in `pn.extension`.

For me the current way it works is cumbersome. Everytime I use that flow I would need to extract the template and set its parameters. Something like `site`, `accent_base_color`, `header_background` almost always need to be set. And sometimes `sidebar_width` etc. also needs to be set.

Please support providing these arguments either in `pn.extension` or `.servable`.

I would prefer to add **kwargs** to `.servable` or a dict argument `template_kwargs` to `pn.extension`.

## Example

How could I easily set the above template parameters in the example below?

```python
import plotly.express as px


def plot(count):
    x = [str(i) for i in range(0, count)]
    y = list(range(0, count))
    return px.bar(x=x, y=y)


import panel as pn

pn.extension("plotly", sizing_mode="stretch_width", template="fast")

count = pn.widgets.IntSlider(name="Count", start=10, end=50, value=10).servable(
    location=True, area="sidebar"
)
icount = pn.bind(plot, count)  # Makes function rerun when the widget value is changed
pn.panel(icount).servable(title="Slider Example", area="main")
```

**Comment by philippjfr** [comment]
+1 on adding `template_kwargs` to `pn.extension` and by extension `pn.config`.

**Comment by philippjfr** [comment]
It sounds like we decided not to do this and instead use `pn.state.template.param.update`.
