### ISSUE TITLE
FastGridTemplate not working

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#3089]
#### ALL software version info
panel 0.12.4
bokeh 2.4.2

#### Description of expected behavior and the observed behavior
`pn.template.FastGridTemplate` throws an error.

#### Complete, minimal, self-contained example code that reproduces the issue

```javascript
import panel as pn

def get_app():

    return pn.template.FastGridTemplate(
        title="FastGridTemplate",
        main=[
            pn.Row(pn.pane.Markdown("Asdasda"))
        ]
    )


if __name__.startswith("bokeh"):
    get_app().servable()
```

#### Stack traceback and/or browser JavaScript console output
<details>
15:53:30.380 bokeh.min.js?v=9a137e81b89226b35f88ee7ff09c361d5ea660df375d424455ce365650655a048986a1142db9af98117fa2dd6974ba733be2b3d97ee398b4d387b82d5e73f79d:585 Uncaught (in promise) Error: Error rendering Bokeh model: could not find #35643923-dfa1-4f43-8260-fa15a2b236a7 HTML tag
    at u (bokeh.min.js?v=9a137e81b89226b35f88ee7ff09c361d5ea660df375d424455ce365650655a048986a1142db9af98117fa2dd6974ba733be2b3d97ee398b4d387b82d5e73f79d:585)
    at n._resolve_root_elements (bokeh.min.js?v=9a137e81b89226b35f88ee7ff09c361d5ea660df375d424455ce365650655a048986a1142db9af98117fa2dd6974ba733be2b3d97ee398b4d387b82d5e73f79d:585)
    at w (bokeh.min.js?v=9a137e81b89226b35f88ee7ff09c361d5ea660df375d424455ce365650655a048986a1142db9af98117fa2dd6974ba733be2b3d97ee398b4d387b82d5e73f79d:163)
    at Object.t.embed_items (bokeh.min.js?v=9a137e81b89226b35f88ee7ff09c361d5ea660df375d424455ce365650655a048986a1142db9af98117fa2dd6974ba733be2b3d97ee398b4d387b82d5e73f79d:163)
u @ bokeh.min.js?v=9a137e81b89226b35f88ee7ff09c361d5ea660df375d424455ce365650655a048986a1142db9af98117fa2dd6974ba733be2b3d97ee398b4d387b82d5e73f79d:585
n._resolve_root_elements @ bokeh.min.js?v=9a137e81b89226b35f88ee7ff09c361d5ea660df375d424455ce365650655a048986a1142db9af98117fa2dd6974ba733be2b3d97ee398b4d387b82d5e73f79d:585
w @ bokeh.min.js?v=9a137e81b89226b35f88ee7ff09c361d5ea660df375d424455ce365650655a048986a1142db9af98117fa2dd6974ba733be2b3d97ee398b4d387b82d5e73f79d:163
t.embed_items @ bokeh.min.js?v=9a137e81b89226b35f88ee7ff09c361d5ea660df375d424455ce365650655a048986a1142db9af98117fa2dd6974ba733be2b3d97ee398b4d387b82d5e73f79d:163

</details>

**Comment by govinda18** [comment]
Facing the same issue with GoldenTemplate too. Is there something I am doing wrong?

**Comment by govinda18** [comment]
Nope, does not work with Firefox either.

**Comment by philippjfr** [comment]
Cannot reproduce any issue here, could you try upgrading to 0.12.6 and try again?

**Comment by govinda18** [comment]
Sorry for the delayed response. it works fine with 0.12.6.

Closing.
