### ISSUE TITLE
Setting [sidebar_width] in template results in warning and does not change width

### ISSUE THREAD

**Issue by pjansen1985** [holoviz/panel#3101]
#### ALL software version info
panel                     0.12.6                     py_0    pyviz
bokeh                     2.4.2                      py_0    bokeh
python                    3.7.3                

#### Description of expected behavior and the observed behavior
I get the following warning when I try to change the sidebar width of a template class in Panel (and the width does not seem to change at all).

`WARNING:param.VanillaTemplate00147: Setting non-parameter attribute sidebar_width=450 using a mechanism intended only for parameters`

After [posting ](https://stackoverflow.com/questions/70712336/setting-sidebar-width-option-in-panel-template-gives-warning-and-does-not-seem?noredirect=1) on stackoverflow, it was suggested this might be a bug and I was advised to report the issue here.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

vanilla = pn.template.VanillaTemplate(title='test', sidebar_width=450)
vanilla.sidebar.append(pn.widgets.Button(name="Click Me"))

vanilla.show();
```

**Comment by maximlt** [comment]
Hi @pjansen1985, I've just tried to reproduce your reported issue based the `master` branch and did not encounter the warning you apparently received. I'm going to close this issue then (a new version of Panel should be released in the coming weeks).
