### ISSUE TITLE
HSpacer can overlap with ToggleGroup

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#3114]
#### Description of expected behavior and the observed behavior
When having a ToggleGroup with many options HSpacer can overlap with it, making it impossible to click on it.

First observed the issue here:  https://github.com/holoviz/hvplot/issues/697

#### Complete, minimal, self-contained example code that reproduces the issue

``` python
import panel as pn
pn.extension()

mfr = pn.widgets.ToggleGroup(
    options=["ford", "chevrolet", "plymouth", "honda", "sbaru", "volkswagen"],
    value=["ford", "chevrolet", "plymouth", "honda", "sbaru", "volkswagen"],
)
pn.Row(mfr, pn.layout.HSpacer())

```

#### Screenshots or screencasts of the bug in action
https://user-images.githubusercontent.com/19758978/150152188-6f5f3df5-4897-432b-96ce-432f2357de86.mp4

**Comment by philippjfr** [comment]
At this point I will likely wait to deal with any layout issues until the Bokeh 3.0 layout refactor is available.
