### ISSUE TITLE
Add a Search widget

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#3117]
Panel has the `AutocompleteInput` widget that helps application users to select an item among a large list of options available. However it only works from left-to-right. A full-blown Search widget would be a very nice addition to Panel.

**Comment by xavArtley** [comment]
Some times ago I implemented this widget:
![ms_widget](https://user-images.githubusercontent.com/18531147/150354330-09f3ed88-52ee-4a5f-b42e-64ab2e3588fd.gif)

It needs some polish but it can be a base
The code can be found in this repository
https://github.com/xavArtley/BokehParallelCoordinates.git
https://github.com/xavArtley/BokehParallelCoordinates/blob/7a743e5d92e72072fa647bbb225dd122a1bf280f/pcp/models/multiselect.py
https://github.com/xavArtley/BokehParallelCoordinates/blob/7a743e5d92e72072fa647bbb225dd122a1bf280f/pcp/models/multiselect.ts

**Comment by maximlt** [comment]
Thanks @xavArtley for sharing the code of this widget which seems very powerful. Sort of a mix of a Search widget/Select/Multichoice. Btw I also recently opened an issue for a Select widget with a select-all feature, a la Excel or Tableau (https://github.com/holoviz/panel/issues/3018).

**Comment by alon-sht** [comment]
This widget would be very useful!!
Some kind of a mix between MultiChoice and Select widgets. 
All the above suggestions sound great:
- Option to Select All or Dis-select all
- Search bar that filters the shown dropdown - this can be either in a dedicated search bar or in the widget itself. 
- Maybe also an option to "select all" that selects just the filtered results (after filtering by the search bar).

**Comment by maximlt** [comment]
Thanks for chiming in @hyamanieu, what you say totally makes sense to me.

> I would focus this issue on changing the search method of `AutocompleteInput` to search within the whole string rather than just the beginning. What do you think?

I am not sure it's a good idea. The semantics of auto-completing is different from searching. Also if the search functionality is embedded in the auto-complete widget it makes it harder for users to find it. I'd be more in favor of dedicated Search widget.
