### ISSUE TITLE
Events are not being sent in Panel/Django apps

### ISSUE THREAD

**Issue by sdc50** [holoviz/panel#3129]
Panel=0.13.0a31
Bokeh=2.4.2
Django=2.2.14

Ever since #3115 I can't get a Panel app embedded in Django to work. It initially renders fine, but it stalls on any interaction. It appears that events messages are not being sent over the websocket. 

WebSocket messages with Panel=0.13.0a31
![image](https://user-images.githubusercontent.com/6454472/150607171-1a7f00ec-3b4f-4202-873d-84101c75f31e.png)

WebSocket messages with Panel=0.13.0a28
![image](https://user-images.githubusercontent.com/6454472/150607392-bcdbeac3-3db2-448b-8799-99ba26f56603.png)

**Comment by sdc50** [comment]
@philippjfr I think this is the issue that I've been dealing with in updating the bokeh-django repo. When I installed Panel=0.13.0a28 then it works. I'll start looking at what has changed since that tag to see if I can figure out how to fix it.

**Comment by philippjfr** [comment]
Hmm, yeah if you can track that down that would be tremendously helpful.

**Comment by sdc50** [comment]
fixed by #3828
