### ISSUE TITLE
Upgrade event-to-object.js

### ISSUE THREAD

**Issue by rmorshea** [holoviz/panel#3133]
I noticed that Panel seems to have leveraged the `event-to-object.js` file from IDOM. Since the time that file was originally copied over IDOM has made [several improvements](https://github.com/idom-team/idom/blob/main/src/client/packages/idom-client-react/src/event-to-object.js) which extend the amount of information that is sent over about each event type. Thus is seems like it would be cool if Panel could take advantage of that work:

The highlights of these improvements are:

- Pointer events now have all the same properties as standard mouse events.
- Event target information has now been moved under the `"target"` key to give it a dedicated namespace.
- Added information about `currentTarget` and `relatedTarget` elements.

Unfortunately, moving target information under a separate `"target"` key is a breaking change, so integrating these improvements would require some period of time for users to upgrade. Presently, IDOM is employing a [temporary shim](https://github.com/idom-team/idom/blob/main/src/idom/core/_event_proxy.py) that makes `event["value"]` a proxy for `event["target"]["value"]` with a deprecation warning.

To make upgrades like this easier in the future, perhaps `event-to-object` should be split out into a separate JS package?

**Comment by philippjfr** [comment]
>To make upgrades like this easier in the future, perhaps event-to-object should be split out into a separate JS package?

This would indeed be great!

**Comment by philippjfr** [comment]
Implemented in #3150

**Comment by philippjfr** [comment]
I've manually updated for now but if you ever make it a standalone package please ping me.
