### ISSUE TITLE
Add files to `__init__` for autocomplete in VS Code

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#3135]
When writing in vs code the autocomplete only works for modules imported in an `__init__.py` file, e.g. `pn.widgets.IntSlider` work but `pn.viewable.Viewer` does not.  See here:

https://user-images.githubusercontent.com/19758978/150685703-a235b219-6052-4e6e-b1f5-b121dc1f1558.mp4

The solution is pretty easy as `.viewable` only needs to be added to the `__init__`.

https://user-images.githubusercontent.com/19758978/150685758-3b1e5468-bcbe-4337-a62a-f3a4da8d9caf.mp4

I don't know if #3132 will fix this. When you have time @MarcSkovMadsen can you check this?

**Comment by MarcSkovMadsen** [comment]
I don't think or expect #3132 to fix it.
