### ISSUE TITLE
Update Viewer  to work with depends on `__panel__`

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#3136]
#### Is your feature request related to a problem? Please describe.
I often have some code that looks like this:
``` python
import panel as pn
import param


class Example(pn.viewable.Viewer):
    def __init__(self, **params):
        self.button = pn.widgets.Button(name="Click")
        super().__init__(**params)

    @param.depends("button.clicks")
    def __panel__(self):
        return pn.Column(self.button, self.button.clicks)


ex = Example()
ex.servable() 
``` 

![1](https://user-images.githubusercontent.com/19758978/150692802-39cd9746-83fe-472b-8c15-95610a1a4a12.gif)

Which does not update when pressing the button, what I need to do is change the last line to `pn.panel(ex.__panel__).servable()` or add an extra function like this to get it to work.
``` python
class Example(pn.viewable.Viewer):
    def __init__(self, **params):
        self.button = pn.widgets.Button(name="Click")
        super().__init__(**params)

    @param.depends("button.clicks")
    def _return_click(self):
        return self.button.clicks
    
    def __panel__(self):
        return pn.Column(self.button, self._return_click)
```

![2](https://user-images.githubusercontent.com/19758978/150692806-9ecc4b91-6078-4839-bf9c-c571704e7e0e.gif)

#### Describe the solution you'd like
The solution to this particular problem seems to update the `Viewer` to something like the following. But if there is a reason why this was not done in the first place, I would like to hear it as it seems pretty fundamental to my understanding of param/panel.

![viewer](https://user-images.githubusercontent.com/19758978/150692844-80c7e677-d1f2-42e4-af64-411485dc9d6c.png)

**Comment by MarcSkovMadsen** [comment]
I've been experiencing and thinking the same.

**Comment by philippjfr** [comment]
I'd be okay with this change but at minimum I'd only perform the wrapping into a `ParamMethod` or `ParamFunction` object (i.e. what you're doing by wrapping `pn.panel(self.__panel__)`) if actually needed, otherwise this will add pointless nesting and overhead for no reason.

**Comment by Hoxbro** [comment]
Seem like the natural thing to do. 

Do you have a link to `ParamMethod` or `ParamFunction`? I would like to know exactly what they do and what the difference is between them.

**Comment by jbednar** [comment]
The difference is just that one's for standalone functions and one's for object methods:

https://panel.holoviz.org/api/panel.param.html#panel.param.ParamFunction
https://panel.holoviz.org/api/panel.param.html#panel.param.ParamMethod
