### ISSUE TITLE
deckgl tooltips pane doesn't work

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#3145]
https://panel.holoviz.org/reference/panes/DeckGL.html

It works when I pass a single layer's tooltip to the deck, but not the panel pane.

**Comment by andhuang-CLGX** [comment]
This works, but not the example in the gallery
```
import pydeck as pdk

layer = pdk.Layer(
    'HexagonLayer',
    "https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/3d-heatmap/heatmap-data.csv",
    get_position='[lng, lat]',
    auto_highlight=True,
    elevation_scale=50,
    pickable=True,
    elevation_range=[0, 3000],
    extruded=True,
    coverage=1)

# Set the viewport location
view_state = pdk.ViewState(
    longitude=-1.415,
    latitude=52.2323,
    zoom=6,
    min_zoom=5,
    max_zoom=15,
    pitch=40.5,
    bearing=-27.36)

# Combined all of it and render a viewport
r = pdk.Deck(
    layers=[layer],
    initial_view_state=view_state,
    tooltip={
        'html': '<b>Elevation Value:</b> {elevationValue}',
        'style': {
            'color': 'white'
        }
    }
)

pn.pane.DeckGL(r, sizing_mode='stretch_width', height=600)
```

**Comment by andhuang-CLGX** [comment]
Pretty dumbfounded... it works in Binder's notebook (mybinder.org/user/holoviz-panel-spwyv9q0/lab/tree/examples/reference/panes/DeckGL.ipynb) and when I .save("test.html"), but when I go back to my own notebook it doesn't work, until I save to html?

**Comment by andhuang-CLGX** [comment]
My own notebook shows this:
![image](https://user-images.githubusercontent.com/83971150/151456418-56237609-0297-4b61-90f5-80e5fc421f2c.png)

While the saved html shows:
![image](https://user-images.githubusercontent.com/83971150/151456477-1f248812-803f-4e45-8f0d-ea1e3732d62b.png)

**Comment by andhuang-CLGX** [comment]
In my notebook inspect
![image](https://user-images.githubusercontent.com/83971150/151457152-d32af88d-fdff-43d0-af0b-2e338b22f70a.png)

In my binder inspect
![image](https://user-images.githubusercontent.com/83971150/151457214-d3033408-667e-4ab7-a5f5-a1e2044c9206.png)

Seems like I'm missing mapbox.js?

**Comment by andhuang-CLGX** [comment]
Okay I found that passing the JSON spec with the tooltips work, but not using a pydeck pane, e.g.
the
```
tooltip = {
    "geojson": geojson_tooltip,
    "landcover": {
        "html": "The background",
        "style": {
            "backgroundColor": "red",
            "color": "white"
       }
    }
}

pn.pane.DeckGL(json_spec, tooltips=tooltip, mapbox_api_key=MAPBOX_KEY, sizing_mode='stretch_width', height=600)
```

part.

I guess that's why the landcover tooltip was stripped in the latter PyDeck object example.

**Comment by philippjfr** [comment]
This should be documented better. I've implemented support for the nested tooltips myself, however in the classic notebook we load the the official deck.gl jupyter widget implementation that does not support the nested spec. I'll try to use my own renderer in both cases but last time I had serious issues getting the deck.gl bundles loaded properly in classic notebook.

**Comment by philippjfr** [comment]
Managed to find a fix.
