### ISSUE TITLE
Matplotlib figure shows twice if instantiated from inside a class

### ISSUE THREAD

**Issue by Davide-sd** [holoviz/panel#3146]
#### ALL software version info

* OS: Ubuntu 21.10
* Python: 3.9.7
* panel: 0.12.0
* matplotlib: 3.5.1

#### Description of expected behavior and the observed behavior

I'm not sure if this problem can be solved, as it is an intrinsic behavior of Matplotlib and Jupyter Notebook. Namely, every time a matplotlib figure is instantiated on an interactive environment such as Jupyter Notebook, it will be visualized on the screen, even without executing `plt.show()`.

Let's say I have a class that is generating some kind of plot which I'd like to visualize inside a panel application. The moment the figure is instantiated, it will be visualized on the screen. Then, panel kicks in and output its `Pane` containing the figure. Overall, two pictures will be visualized on the screen: the first (the smallest one) is created by Matplotlib and Jupyter, the second is created by Panel.

Instead, only panel's output should be visible on the screen.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
import panel as pn
pn.extension()

class Test():
    def __init__(self):
        self._fig = None
        self.ax = None
    
    def _create_figure(self):
        self._fig = plt.figure()
        self.ax = self._fig.add_subplot(1, 1, 1)
        Y, X = np.mgrid[-3:3:100j, -3:3:100j]
        U = -1 - X**2 + Y
        V = 1 + X - Y**2
        speed = np.sqrt(U*U + V*V)
        strm = self.ax.streamplot(X, Y, U, V, color=U, linewidth=2, cmap=cm.autumn)
        self._fig.colorbar(strm.lines)
    
    @property
    def fig(self):
        if self._fig is None:
            self._create_figure()
        return self._fig

    def show(self):
        if self._fig is None:
            self._create_figure()
        plt.show()

t = Test()
mpl_pane = pn.pane.Pane(t.fig)
mpl_pane
```

#### Screenshots or screencasts of the bug in action

![Screenshot_20220127_105605](https://user-images.githubusercontent.com/9921777/151335703-4dac4e79-d599-42cb-bc37-88db16121a92.png)

**Comment by Hoxbro** [comment]
You should use `matplotlib.figure.Figure` instead of `matplotlib.pyplot.figure`, see https://panel.holoviz.org/reference/panes/Matplotlib.html

``` python
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
import panel as pn
from matplotlib.figure import Figure

pn.extension()

class Test():
    def __init__(self):
        self._fig = None
        self.ax = None
    
    def _create_figure(self):
        self._fig = Figure()
        self.ax = self._fig.subplots()
        Y, X = np.mgrid[-3:3:100j, -3:3:100j]
        U = -1 - X**2 + Y
        V = 1 + X - Y**2
        speed = np.sqrt(U*U + V*V)
        strm = self.ax.streamplot(X, Y, U, V, color=U, linewidth=2, cmap=cm.autumn)
        self._fig.colorbar(strm.lines)
    
    @property
    def fig(self):
        if self._fig is None:
            self._create_figure()
        return self._fig


t = Test()
mpl_pane = pn.pane.Pane(t.fig, tight=True)
mpl_pane
```

![image](https://user-images.githubusercontent.com/19758978/151551415-c50e2dfb-27c2-49c2-9944-2c799f435c84.png)

**Comment by MarcSkovMadsen** [comment]
Please reopen again @Davide-sd if the solution proposed by @Hoxbro does not work for you.

**Comment by Davide-sd** [comment]
@Hoxbro  Thanks, it worked!
