### ISSUE TITLE
A reload button to reset the golden template 

### ISSUE THREAD

**Issue by alanntl** [holoviz/panel#3148]
Hi everyone,

I am using the golden layout template but I am wondering how to reset my webpage/layout. 

I realize there is a reset button that comes with the page title, however, is there any method( a function call ?) I can reset the whole page with an in-page widget?

Also, I want to use a sidebar button to add a new widget(new tab in golden layout) to the main page, but then I realize I have to click the title button every time to make the new tab show up.

I am new to panel and wondering if anyone has faced the same issue? Thanks! 

![image](https://user-images.githubusercontent.com/91423561/151440044-3da4319e-df91-4edd-867d-fd83d00f1a2a.png)

**Comment by maximlt** [comment]
Hi @alanntl,

I don't have the problem you're experiencing, the following snippet (that you can run in a notebook or execute with `python app.py` allows to add a tab to the Tab component by clicking on a button:
```python
import panel as pn
pn.extension()

t = pn.Tabs(('a', 'A'), ('b', 'B'))

bt = pn.widgets.Button(name='Click')

def cb(event):
    t.append(('c', 'C'))

bt.on_click(cb)

golden = pn.template.GoldenTemplate(title='Golden Template')
golden.sidebar.append(bt)
golden.main.append(t)

golden.show()
```

As for a way to refresh a page, I believe setting `pn.state.location.reload` to True will trigger a page refresh.

Note that the Github issue tracker should be used to report bugs or feature requests, usage questions are best suited for the [Discourse forum](https://discourse.holoviz.org/) where  you'll find a community of users who can help you :)

**Comment by alanntl** [comment]
I am trying to do 

Thank you for sharing the tab solution. 

> Hi @alanntl,
> 
> I don't have the problem you're experiencing, the following snippet (that you can run in a notebook or execute with `python app.py` allows to add a tab to the Tab component by clicking on a button:
> 
> ```python
> import panel as pn
> pn.extension()
> 
> t = pn.Tabs(('a', 'A'), ('b', 'B'))
> 
> bt = pn.widgets.Button(name='Click')
> 
> def cb(event):
>     t.append(('c', 'C'))
> 
> bt.on_click(cb)
> 
> golden = pn.template.GoldenTemplate(title='Golden Template')
> golden.sidebar.append(bt)
> golden.main.append(t)
> 
> golden.show()
> ```
> 
> As for a way to refresh a page, I believe setting `pn.state.location.reload` to True will trigger a page refresh.
> 
> Note that the Github issue tracker should be used to report bugs or feature requests, usage questions are best suited for the [Discourse forum](https://discourse.holoviz.org/) where you'll find a community of users who can help you :)

Hi @maximlt ,

I am trying to add a new content tab instead of another tab widget. Because the content tab is resizable and movable( the golden layout feature ). something like this:

```
import panel as pn
pn.extension()

bt = pn.widgets.Button(name='Click')

def cb(event):
    golden.main.append(t)  # add anothe content tab instead of tab widget

bt.on_click(cb)

golden = pn.template.GoldenTemplate(title='Golden Template')
golden.sidebar.append(bt)
golden.main.append(t)

golden.show()
```
Thanks for your solution, I will use the widget tab if the adding content tab is not available.
