### ISSUE TITLE
Not waiting until bokeh scripts loaded from CDN

### ISSUE THREAD

**Issue by stas-sl** [holoviz/panel#3169]
#### ALL software version info
```
bokeh: 2.4.2
panel: 0.12.6
holoviews: 1.14.17
python: 3.9.7
ipython: 8.0.1
ipykernel: 6.7.0
ipywidgets: 7.6.5
jupyter_client: 6.1.12
jupyter_core: 4.9.1
jupyter_server: 1.4.1
jupyterlab: 3.2.1
notebook: 6.4.6
os x: 10.15.7
chrome: 97.0.4692.99
```

#### Description of expected behavior and the observed behavior

Hi, if I load panel extension in jupyter notebook like this:

```python
import panel as pn
pn.extension()
```
and then convert this notebook with only 2 lines to html:
```bash
jupyter nbconvert panel.ipynb --to html --execute
```
and open the resulted html in browser I see the following error in console:

![image](https://user-images.githubusercontent.com/4602302/152263246-7da7ad9f-08df-436f-aa79-992838c1d9da.png)

![image](https://user-images.githubusercontent.com/4602302/152263281-fdfc611d-89d3-4d68-b467-773d3b10048b.png)

I think the reason is because this function is called too early - before bokeh scripts loaded. When digging deeper, I found possible reason in PR https://github.com/holoviz/panel/pull/2875, namely this lines:

https://github.com/holoviz/panel/blob/80d11123b7e16e058f6bd6e560c03da103428821/panel/_templates/autoload_panel_js.js#L88-L101

When I change this
```js
root._bokeh_is_loading = css_urls.length + {{ requirements|length }}; 
```
to this
```js
root._bokeh_is_loading = css_urls.length + js_urls.length + {{ requirements|length }}; 
```
the problem seems to go away, but I'm not completely sure if this is a correct way to fix it.

**Comment by philippjfr** [comment]
Thanks for your investigations @stas-sl. This is a high-priority issue and I hope to take a look this week.

**Comment by philippjfr** [comment]
Just looked at this, I can indeed reproduce with 0.12.6 but this seems to have been resolved on master in https://github.com/holoviz/panel/pull/2875.
