### ISSUE TITLE
Render with Panel button breaks with Jupyterlab root_dir

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#3170]
#### ALL software version info
Jupyterlab 3.2.8
Panel master

#### Description of expected behavior and the observed behavior
Hi team, jupyterlab allows you to set a custom root_dir and preferred_dir config for your server app. You can set it using the following:
```bash
$ jupyter notebook --generate-config
```

Then in your `~/.jupyter` folder you should find `jupyter_notebook_config.py` and there we can set a configuration like:
```python
## The directory to use for notebooks and kernels.
#  Default: ''
c.ServerApp.root_dir = '/'
## Preferred starting directory to use for notebooks and kernels.
#  Default: ''
import os
c.ServerApp.preferred_dir = os.getcwd()
```

Now when you launch jupyter, the jupyter extensions get file path relative to the `root_dir`. So suppose you launch your lab from `/home/gt` and root dir is set to `/` and we try to render a panel preview for a file located at `/home/gt/notebook.ipynb`, this will break as the path passed to the [PanelHandler.get](https://github.com/holoviz/panel/blob/master/panel/io/jupyter_server_extension.py#L83) is actually `home/gt/notebook.ipynb` but the bokeh utility [here](https://github.com/bokeh/bokeh/blob/branch-3.0/bokeh/command/util.py#L117) tries to get abspath which is relative to cwd (which is /home/gt) and it turns out to be `/home/gt/home/gt/notebook.ipynb`.

Here, what the PanelHandler should be doing is setting the path to bokeh as `root_dir + path`. A good example is the [FileContentsManager](https://github.com/jupyter-server/jupyter_server/blob/7615f32497df4f2a133eea451a11cb16b51dd8b1/jupyter_server/services/contents/filemanager.py#L46) of jupyter extension. As you can see [here](https://github.com/jupyter-server/jupyter_server/blob/7615f32497df4f2a133eea451a11cb16b51dd8b1/jupyter_server/services/contents/filemanager.py#L51), for all the utility it evaluates the path relative to the root dir.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension()
pn.pane.Markdown("# Test").servable()
```

This simple code throws 500 Internal server errors if the following configuration is done - 

```python
c.ServerApp.root_dir = '/'
import os
c.ServerApp.preferred_dir = os.getcwd()
```

and the lab is launched from a directory other than the root_dir. What the above config does is it allows you to access files outside your cwd as well from the lab. 

#### Stack traceback and/or browser JavaScript console output
```python
ERROR 00:22:44 Uncaught exception GET /panel-preview/render/home/totla/Untitled.ipynb (10.218.24.254)

    HTTPServerRequest(protocol='https', host='myhost.com', method='GET', uri='/panel-preview/render/home/totla/Untitled.ipynb', version='HTTP/1.1', remote_ip='10.218.24.254')
    Traceback (most recent call last):
      File "/usr/local/python/python-3.9/std/lib64/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/python/python-3.9/std/lib64/python3.9/site-packages/panel/io/jupyter_server_extension.py", line 93, in get
        app = build_single_handler_application(path)
      File "/usr/local/python/python-3.9/std/lib64/python3.9/site-packages/bokeh/command/util.py", line 135, in build_single_handler_application
        raise ValueError("Path for Bokeh server application does not exist: %s" % path)
    ValueError: Path for Bokeh server application does not exist: /home/totla/home/totla/Untitled.ipynb
```

#### Proposed Fix

A simple fix here would be similar to what FileContentManager does:

```python
def get_abs_path(self, path):
    try:
        # May be there is a better way to do this
        root_dir = self.application._app.settings['config']['ServerApp']['root_dir']
    except:
        import os
        root_dir = os.getcwd()
    return root_dir + path  

# To be added here https://github.com/holoviz/panel/blob/master/panel/io/jupyter_server_extension.py#L84
path = self.get_abs_path(path)
```

Similarly, this should be done for PanelWSHandler as well. I was able to make it work with the above change. If this looks fine, I would be happy to raise a PR too. Please let me know if you feel there is a better way to achieve the same.

**Comment by philippjfr** [comment]
Thanks @govinda18! Would absolutely love to see a PR with your suggested changes.

**Comment by govinda18** [comment]
Done.
