### ISSUE TITLE
Panel serve: cannot set app as an index. 

### ISSUE THREAD

**Issue by mjmare** [holoviz/panel#3208]
I tried to set a panel app as the index, like so:
```
panel serve ../src/dashboard/apps/* --index start_here
```
This will generate this exception when accessing the app at http://localhost:5006:
```
2022-02-21 12:04:02,825 Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/ACHN/Dashboard/.venv/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/mjm/Dropbox/Devel/ACHN/Dashboard/.venv/lib/python3.8/site-packages/panel/io/server.py", line 275, in get
    await super().get(*args, **kwargs)
  File "/Users/mjm/Dropbox/Devel/ACHN/Dashboard/.venv/lib/python3.8/site-packages/bokeh/server/views/root_handler.py", line 66, in get
    self.render(index, prefix=prefix, items=sorted(self.applications.keys()))
  File "/Users/mjm/Dropbox/Devel/ACHN/Dashboard/.venv/lib/python3.8/site-packages/tornado/web.py", line 862, in render
    raise RuntimeError("Cannot render() after finish()")
RuntimeError: Cannot render() after finish()
```

Please see discussion here:
https://discourse.holoviz.org/t/cannot-set-panel-app-as-index-with-index-option/3202/2

**Comment by MarcSkovMadsen** [comment]
I would like to be able to set an app as the index. This seems very natural.

**Comment by philippjfr** [comment]
To be clear this is supported but I think you'd have to use `--index start_here.py`. I'll make this more robust and fix that RuntimeError though.

**Comment by mjmare** [comment]
Don't think so. If I pass a non-existing app panel serve will raise an error. 
```
ERROR: The --index argument must either specify a jinja2 template with a .html file extension or select one of the applications being served as the default. The specified application 'start_hereXX' could not be found.
```

**Comment by philippjfr** [comment]
> If I pass a non-existing app panel serve will raise an error.

I think the validation logic is just not correctly implemented. I'm using the app as an index pattern successfully in a number of production applications.

**Comment by mjmare** [comment]
AFAICT this is not fixed in Panel v0.13.0.

This won't work:
```
--index /absolute/path/to/default_app_dir
--index /absolute/path/to/default_app_dir/main.py
--index default_app_dir
```
The only thing that works is:
```
--index /absolute/path/to/index.html
```

If it is fixed, please update the docs and CLI help

**Comment by philippjfr** [comment]
Thanks @mjmare! You are indeed correct, directory based apps are not supported right now. Could you open another issue?

**Comment by mjmare** [comment]
Done.

**Comment by philippjfr** [comment]
Really appreciate it @mjmare!

**Comment by mjmare** [comment]
Of course. No prob.
