### ISSUE TITLE
PyDeck example not executing properly

### ISSUE THREAD

**Issue by diehl** [holoviz/panel#3213]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
MacOS 12.1
Chrome 98.0.4758.102
python 3.8.12
panel 0.12.6
bokeh 2.4.2

jupyter --version
Selected Jupyter core packages...
IPython          : 8.0.1
ipykernel        : 6.9.1
ipywidgets       : 7.6.5
jupyter_client   : 7.1.2
jupyter_core     : 4.9.2
jupyter_server   : 1.13.5
jupyterlab       : 3.2.9
nbclient         : 0.5.11
nbconvert        : 6.4.2
nbformat         : 5.1.3
notebook         : 6.4.8
qtconsole        : not installed
traitlets        : 5.1.1

#### Description of expected behavior and the observed behavior
Copied the PyDeck example from [this page](https://panel.holoviz.org/reference/panes/DeckGL.html) into a notebook to test locally and I am not seeing any visualization in the output cell. At the command line where I executed `jupyter notebook`, I'm seeing the following:

> [I 14:06:27.372 NotebookApp] Replaying 3 buffered messages
> [IPKernelApp] ERROR | No such comm target registered: hv-extension-comm
> [IPKernelApp] WARNING | No such comm: hv-extension-comm
> [IPKernelApp] WARNING | No such comm: hv-extension-comm

UPDATE: A surprising behavior I discovered after posting this is that if I execute the notebook, save and close it, shutdown the kernel and then relaunch the notebook, the visualization is now visible in the reloaded notebook. 

#### Complete, minimal, self-contained example code that reproduces the issue

Link to the notebook: https://gist.github.com/diehl/25cbd226727fad5554621708b56fba68

#### Stack traceback and/or browser JavaScript console output
Browser JavaScript console output after a Restart and Run All in the notebook.
> Kernel: kernel_restarting (0ee99af6-3e40-4dd0-9a76-9d678bcbc55f)
> kernel.js:107 Kernel: kernel_created (0ee99af6-3e40-4dd0-9a76-9d678bcbc55f)
> kernel.js:464 Starting WebSockets: ws://localhost:8888/api/kernels/0ee99af6-3e40-4dd0-9a76-9d678bcbc55f
> kernel.js:107 Kernel: kernel_connected (0ee99af6-3e40-4dd0-9a76-9d678bcbc55f)
> kernel.js:107 Kernel: kernel_ready (0ee99af6-3e40-4dd0-9a76-9d678bcbc55f)
> VM63 bokeh-2.4.2.min.js:184 [bokeh] setting log level to: 'info'
> assert.js:3 Uncaught (in promise) Error: null loader
>     at n (assert.js:3:11)
>     at o (normalize-loader.js:19:3)
>     at Object.a [as registerLoaders] (register-loaders.js:15:30)
>     at u.initialize (VM56 panel.min.js:71:1237)
>     at c (VM63 bokeh-2.4.2.min.js:278:133)
>     at t.build_view (VM63 bokeh-2.4.2.min.js:278:257)
>     at f (VM63 bokeh-2.4.2.min.js:584:353)
>     at t.add_document_standalone (VM63 bokeh-2.4.2.min.js:584:476)
>     at Object.t.embed_items_notebook (VM63 bokeh-2.4.2.min.js:591:2656)
>     at embed_document (<anonymous>:5:22)

#### Screenshots or screencasts of the bug in action
After initial execution of the notebook, I see no visualization. 
<img width="1145" alt="no_output" src="https://user-images.githubusercontent.com/349843/155428443-e90da11a-791a-4716-b83f-b1d7ff795e30.png">

After closing the notebook and relaunching it, the visualization becomes visible.
<img width="1141" alt="nowvisible" src="https://user-images.githubusercontent.com/349843/155431057-d9b9030f-adb5-4dcd-862b-1ddb0dc83131.png">

**Comment by philippjfr** [comment]
Thanks for reporting, this is working fine for me with latest dev releases.
