### ISSUE TITLE
Missing instructions in getting_started to create occupancy.csv

### ISSUE THREAD

**Issue by robmarkcole** [holoviz/panel#3230]
On https://panel.holoviz.org/getting_started/index.html a file `occupancy.csv` is used, and the source given as http://archive.ics.uci.edu/ml/datasets/Occupancy+Detection+ However downloading the dataset returns a couple of txt files. Reformatting to csv and deleting an index returns a dataset similar to that shown in the docs, but not identical to it. Suggest either documenting the steps or providing `occupancy.csv` directly. I guess there might be some licensing issue with the latter

**Comment by robmarkcole** [comment]
OK I discovered it is here https://github.com/holoviz/panel/blob/master/examples/assets/occupancy.csv

**Comment by Hoxbro** [comment]
Changing `pd.read_csv('../assets/occupancy.csv')` to `pd.read_csv("https://raw.githubusercontent.com/holoviz/panel/master/examples/assets/occupancy.csv")` seem like a good thing to do to enhance the new user experience. Especially, as it is more likely that a new user will download a single page and not the repository. 

If you are up for it @robmarkcole you can make a PR for it.
