### ISSUE TITLE
Panel button.loading not working perfectly

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#3233]
#### ALL software version info

panel==0.13.0a38

 

#### Description of expected behavior and the observed behavior

The panel button.loading=True is not working as expected in deployed app. It works fine in a jupyter notebook though. Check the gif below:

 

![panel-button-loading-bug](https://user-images.githubusercontent.com/25079291/157586991-a5f76e4d-5d70-4ca7-8f56-a27ce4d31592.gif)

 

 

#### Complete, minimal, self-contained example code that reproduces the issue

 

```python

  def app():
      hint_box = pn.pane.Alert('Ready')
      submit_button = pn.widgets.Button(name='Submit', width=100)

      def on_click(event):
          submit_button.loading = True
          hint_box.object = 'Loading'
          hint_box.alert_type = 'warning'

          time.sleep(5)

          submit_button.loading = False
          hint_box.object = f'Clicked {submit_button.clicks} times'
          hint_box.alert_type = 'primary'

      submit_button.on_click(on_click)
      return pn.Column(hint_box, submit_button)

  app().servable()
```

 

#### Stack traceback and/or browser JavaScript console output

No errors thrown

 

#### Screenshots or screencasts of the bug in action

Added above

**Comment by philippjfr** [comment]
Could you try again with 0.13.0a42? I think https://github.com/holoviz/panel/pull/3231 should have addressed this.

**Comment by govinda18** [comment]
Thanks @philippjfr this is indeed fixed, sorry for the delayed response.
