### ISSUE TITLE
Contribute simple docker example?

### ISSUE THREAD

**Issue by robmarkcole** [holoviz/panel#3235]
I created a simple example using docker, would it be of interest to contribute this to the docs? 

```dockerfile
FROM continuumio/miniconda3

EXPOSE 5006

RUN conda install -c conda-forge nodejs
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY panel.ipynb .
CMD panel serve --show panel.ipynb
```

This would work nicely after https://github.com/holoviz/panel/pull/3234 is merged

**Comment by philippjfr** [comment]
Absolutely! Maybe add a section to https://panel.holoviz.org/user_guide/Server_Deployment.html

**Comment by robmarkcole** [comment]
@philippjfr I see this will require editing a jupyter notebook (`examples/user_guide/Server_Deployment.ipynb`). I checked your dev guide but did not see any instructions in how it is recommended to do this. In my experience jupyter notebook PR will create large diff when the notebook is opened in jupyter notebook, so perhaps you edit the markdown directly?

**Comment by philippjfr** [comment]
@robmarkcole indeed (almost) all the docs are built from jupyter notebooks. The diffs indeed aren't great but as long as you don't commit the output (which we never do) they shouldn't be too bad.

**Comment by philippjfr** [comment]
Would suggest adding this to a the doc/how_to/deployment section now.

**Comment by tdehaeze** [comment]
On my side I have an issue to access the web-app when running panel with Docker. I get the following message:
`Refusing websocket connection from Origin 'http://172.17.0.2:5006';                       use --allow-websocket-origin=172.17.0.2:5006 or set BOKEH_ALLOW_WS_ORIGIN=172.17.0.2:5006 to permit this; currently we allow origins {'localhost:5006'}`

**Comment by abunimeh** [comment]
here is some

**Comment by petegordon** [comment]
Looks to be completed. Close? Simple docker container used here... https://panel.holoviz.org/tutorials/basic/deploy.html
