### ISSUE TITLE
Support local resources for ReactiveHTML components

### ISSUE THREAD

**Issue by Poltto** [holoviz/panel#3241]
Environment:

  - python=3.9
  - folium
  - ipywidgets
  - jupyterlab
  - jupytext
  - panel
  - pyproj
  - sentinelsat
  - vtk
  - plotly
  
Happens on multiple machines and on both Windows 10 and Ubuntu.

#### Description of expected behavior and the observed behavior

Trying to use panel.extend() with external javascript and/or css -files results in a failed import, citing a faulty MIME-type (text/html).

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
from panel.reactive import ReactiveHTML

class TestClass(ReactiveHTML):
    __javascript__ = ['./index.umd.js'] #point to local file, have tried both relative/absolute paths
    __css__ = ['./index.css'] #point to local file, have tried both relative/absolute paths
    
    _template = """
    <h1 id="hello">Hello World!</hi>
    """
    
pn.extension()

testClassInstance = TestClass()
testClassInstance

```

#### Stack traceback and/or browser JavaScript console output
Refused to apply style from 'http://localhost:8888/lab/workspaces/auto-9/tree/index.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

This does however work when pointing to a CDN for example. I can only reproduce this bug with local files.

**Comment by MarcSkovMadsen** [comment]
Local files and/ or `raw_css` would be very nice indeed. I've been missing the `raw_css` opportunity.
