### ISSUE TITLE
Django - 'DocConsumer' object has no attribute 'application'

### ISSUE THREAD

**Issue by kRutkowski0** [holoviz/panel#3246]
Bokeh 2.4.2
Panel 0.12.6
Django 2.2.9

Description of expected behavior and the observed behavior:

In our project we are serving jupyter notebooks through Django, but after updating to Bokeh 2.4.2 and Panel 0.12.6 those notebooks stopped working(displaying anything) without any error message. After few hours of debugging and inserting try/except blocks directly in Panel i've found that the culprit is in module `io.django.py`, in function `doc_handle(self, body):`. There is this code:
`resources = Resources.from_bokeh(self.application.resources())` and the reason why it's throwing errors is that, in my opinion, the `resources()` method should be called on `self` variable, which is an instance of `DocConsumer`, not `application` attribute, which in fact doesn't exist. :)

**Comment by maximlt** [comment]
Hi @kRutkowski0,
Does the fix you suggest solve your issue?

**Comment by kRutkowski0** [comment]
Hi @maximlt 
Yes, it does. With this fix those notebooks started displaying correctly on my local machine.
