### ISSUE TITLE
Tabulator styling does not update on patch

### ISSUE THREAD

**Issue by Kadek** [holoviz/panel#3248]
#### ALL software version info
Python 3.8.8
panel 0.12.6

#### Description of expected behavior and the observed behavior
Expected behaviour: When patching data in Tabulator the styling should adapt to new data.
Observed behaviour: When using patch function on tabulator whole styling disappears

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import pandas as pd
import panel as pn

df = pd.DataFrame(np.random.randn(10, 5), columns=list('ABCDE'))
styled = pn.widgets.Tabulator(df, height=500)

def highlight_max(s):
    '''
    highlight the maximum in a Series yellow.
    '''
    is_max = s == s.max()
    return ['background-color: yellow' if v else '' for v in is_max]

styled.style.apply(highlight_max)


def start_updating(*args):
    pn.state.add_periodic_callback(update, period=1000)

def update():
    df = pd.DataFrame(np.random.randn(10, 5), columns=list('ABCDE'))
    styled.patch(df)

button = pn.widgets.Button(name="Start")
button.on_click(start_updating)

pn.Column(button, styled).servable()
```

#### Screenshots or screencasts of the bug in action

https://user-images.githubusercontent.com/2953645/158997659-74a8487f-17bf-43af-9287-12c160a5a921.mp4

**Comment by philippjfr** [comment]
Thanks for the report, already fixed in master however.

**Comment by Kadek** [comment]
Ahh nice! Yes, testing on the [pre-release ](https://github.com/holoviz/panel/releases/tag/v0.13.0a43) I can see that it works. Thanks!

**Comment by Kadek** [comment]
Ohh no, it seems I have been to fast with judgment. It seems the styling doesn't disappear but it also doesn't update according to the new values. 

Here is the same code as in the issue statement running on panel 0.13.0a43

https://user-images.githubusercontent.com/2953645/159002061-a5972a78-ed57-4490-9057-612ebdf2c80c.mp4

The yellow cells simply stay in the same positions even though the max values are present in different cells.
