### ISSUE TITLE
jinja2.Markup import broken for jinja2=3.1

### ISSUE THREAD

**Issue by dillonroach** [holoviz/panel#3260]
short description: conda env solves with jinja2=3.1 (default panel install as of March25 afternoon) break on `import panel`

`ImportError: cannot import name 'Markup' from 'jinja2' (/home/user/anaconda3/envs/panel/lib/python3.10/site-packages/jinja2/__init__.py)`

Reverting to jijna2 3.0.* fixes the issue, but long-term an example solution may be found here:

**https://github.com/pallets/jinja/issues/1628**

**Comment by philippjfr** [comment]
Thanks @dillonroach, duplicate issue https://github.com/holoviz/panel/issues/3257

**Comment by qwweerdf** [comment]
many thanks!
