### ISSUE TITLE
Terminal not writing incrementally/ asynchronously

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3261]
Panel: 0.12.6

I was trying to illustrate how the Panel Terminal can be used to capture `stdout` to report on progress and logs for machine learning applications. But I found that the terminal only writes to the client when a callback is finalized. Not incrementally.

The example below illustrates the issues. I would expect to see incremental output to the Terminal every second. Instead I see it all after 5 seconds.

https://user-images.githubusercontent.com/42288570/160225266-fa685c8c-a0c3-4617-ae95-5149933ea1c5.mp4

```python
import panel as pn
import sys
import time


pn.extension(sizing_mode="stretch_width")

terminal = pn.widgets.Terminal(height=400).servable()

sys.stdout = terminal

def train(e, n=5):
    print("train")
    for n in range(n):
        time.sleep(1)
        print(n)

button = pn.widgets.Button(name="Train", button_type="primary").servable()

pn.bind(train, e=button, watch=True)
```

**Comment by MarcSkovMadsen** [comment]
Its the same with this example

```python
import panel as pn
import sys
import time


pn.extension(sizing_mode="stretch_width")

terminal = pn.widgets.Terminal(height=400).servable()

def train(e, n=5):
    terminal.write("train")
    for n in range(n):
        time.sleep(1)
        terminal.write(n)

button = pn.widgets.Button(name="Train", button_type="primary").servable()

pn.bind(train, e=button, watch=True)
```

I'm pretty sure this example did use to work as I created `.gifs` for showcasing functionality like this when I initially contributed the widget.

**Comment by MarcSkovMadsen** [comment]
## Async Loop Working

An async callback with loop works.

https://user-images.githubusercontent.com/42288570/160225667-b03152c3-0621-481a-aa2d-47d2f7243719.mp4

```python
import panel as pn
import sys
import asyncio


pn.extension(sizing_mode="stretch_width")

terminal = pn.widgets.Terminal(height=400).servable()

sys.stdout=terminal

async def train(e, n=5):
    print("train")
    for n in range(n):
        await asyncio.sleep(1)
        print(n)

button = pn.widgets.Button(name="Train", button_type="primary").servable()

button.on_click(train)
```

**Comment by Hoxbro** [comment]
Seems to work fine for me on master:

https://user-images.githubusercontent.com/19758978/160234156-870db026-f4db-42c8-97f9-f1f52a1b9620.mp4

``` 
panel:  0.13.0a46
param:  1.12.1a1.post9+gfb6f4d9
```

**Comment by philippjfr** [comment]
Thanks for checking @Hoxbro. @MarcSkovMadsen When filing a bug report it's always best to check against master.
