### ISSUE TITLE
Support async functions for pn.bind

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3262]
I would like it to be as simple as possible to create performant data apps as possible. This includes sprinkling in async once in a while.

It would make it super easy to use async if `pn.bind` and `pn.depends` supported it. But it does not.

When I run the below code I get

```bash
c:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py:2000: RuntimeWarning: coroutine 'train' was never awaited
  watcher.fn(*args, **kwargs)
```

```python
import panel as pn
import sys
import asyncio


pn.extension(sizing_mode="stretch_width")

terminal = pn.widgets.Terminal(height=400).servable()

sys.stdout=terminal

async def train(e, n=5):
    print("train")
    for n in range(n):
        await asyncio.sleep(1)
        print(n)

button = pn.widgets.Button(name="Train", button_type="primary").servable()

pn.bind(train, e=button, watch=True)
```

```python
import panel as pn
import sys
import asyncio


pn.extension(sizing_mode="stretch_width")

terminal = pn.widgets.Terminal(height=400).servable()

sys.stdout=terminal

button = pn.widgets.Button(name="Train", button_type="primary").servable()

@pn.depends(button, watch=True)
async def train(e, n=5):
    print("train")
    for n in range(n):
        await asyncio.sleep(1)
        print(n)
```

My Feature Request is to support async for `pn.bind` and `pn.depends`.

**Comment by Hoxbro** [comment]
I think I got this to work. Two changes are needed one in param and another in panel. Both are by checking if the function to watch is an async function and then making the `wrapped`/`cb` function an async function too. I will submit PR to get this implemented.

In param:
https://github.com/holoviz/param/blob/fb6f4d92d7ce9006deb269669ebe34cdaa006d4a/param/parameterized.py#L432-L435

In panel:
https://github.com/holoviz/panel/blob/98a63e8699791b3ff64db97595dead743ae55105/panel/depends.py#L151-L172

**Comment by philippjfr** [comment]
Yeah, looks like I handled it for non-watched functions but not for `watch=True`.
