### ISSUE TITLE
Replace `pkg_resources` with `importlib_metadata`

### ISSUE THREAD

**Issue by jakirkham** [holoviz/panel#3282]
Currently `pkg_resources` is used in a few places (in particular `iter_entry_points`). Would be good to replace this with [`importlib_metadata`]( https://github.com/python/importlib_metadata ) ([`importlib.metadata`]( https://docs.python.org/3/library/importlib.metadata.html ) added in Python 3.8 & stable in Python 3.10), which supersedes `pkg_resources`. In particular usages of `iter_entry_points` can be replaced by [`entry_points`]( https://docs.python.org/3.8/library/importlib.metadata.html#entry-points ).

This also would allow `setuptools` to be dropped as a runtime requirement.

**Comment by jakirkham** [comment]
FWIW a similar change was made in Distributed recently ( https://github.com/dask/distributed/pull/5923 ). Maybe provides a better idea how this might look here

**Comment by philippjfr** [comment]
Thanks @jakirkham, we do still support Python 3.7 for the time being so I'm not sure we can switch quite yet.

**Comment by jakirkham** [comment]
Right the backport package supports Python 3.7
