### ISSUE TITLE
Tabulator Selected Rows (checkbox) reset after Patch

### ISSUE THREAD

**Issue by jjiteshh** [holoviz/panel#3285]
#### ALL software version info
panel version = 0.13.0a46.post8+g73e68396

#### Description of expected behavior and the observed behavior

Observed Behaviour : Tabulator selected rows reset when the table is patched when using 'checkbox' as selected method. 
Expected Behaviour : Selected rows stay as is on patch.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import numpy as np
import panel as pn
pn.extension('tabulator')
print(pn.__version__)


df = pd.DataFrame(np.random.randn(10, 4), columns=list('ABCD'))
df_table = pn.widgets.Tabulator(df,selectable='checkbox')

df_table

df_table.patch(pd.DataFrame(np.random.randn(10, 4), columns=list('ABCD')))

```

#### Screenshots or screencasts of the bug in action

https://user-images.githubusercontent.com/44354969/160980757-a279192f-3640-4a4e-b84e-ab999a36df39.mp4

**Comment by jjiteshh** [comment]
Additional issue:

df_table.selected_dataframe does not show the selected set of dataframe. It seems I have to rerun the df_table cell to be able to get the selected_dataframe.

**Comment by philippjfr** [comment]
Thanks @jjiteshh! I'll take a look.
