### ISSUE TITLE
My v0.13 Blog Feedback

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3302]
# Summary

Here I will provide my comments and suggestions

## Todo

- [] Provide reproducible *Expandable rows* example
- [] Add gif illustrating *Expandable rows*

**Comment by MarcSkovMadsen** [comment]
The *Expandable" rows example is difficult to replicate as it is using hard to install geopandas and a file nobody knows where is located.

![image](https://user-images.githubusercontent.com/42288570/161401140-af37b055-9376-424d-a7fa-af4a99bee926.png)

Furthermore the example should contain a Gif illustrating what *expandable rows* is.

**Comment by philippjfr** [comment]
Thanks! Confusing I know but can you move this to https://github.com/pyviz-dev/blog. Should probably migrate that repo over to the HoloViz org (since it houses the HoloViz blog).
