### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by douglas-raillard-arm** [holoviz/panel#3312]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
Python 3.8
panel/holoviews latest stable PyPI version (I assume)

#### Description of expected behavior and the observed behavior

Import error on `import holoviews`

#### Complete, minimal, self-contained example code that reproduces the issue

N/A, the issue happened on our CI, and unfortunately I haven't been able to reproduce locally. There seems to be some fishy dependency ordering in panel sources though between `panel.config`, `panel.io.__init__` and `panel.io.notebook`.

#### Stack traceback and/or browser JavaScript console output
```
  File \"/lava-364500/0/tests/0_container-test-run/lisa/lisa/analysis/base.py\", line 37, in <module>
    import holoviews as hv
  File \"/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv-3.8/lib/python3.8/site-packages/holoviews/__init__.py\", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)
  File \"/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv-3.8/lib/python3.8/site-packages/holoviews/annotators.py\", line 10, in <module>
    from panel.pane import PaneBase
  File \"/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv-3.8/lib/python3.8/site-packages/panel/__init__.py\", line 1, in <module>
    from . import layout # noqa
  File \"/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv-3.8/lib/python3.8/site-packages/panel/layout/__init__.py\", line 1, in <module>
    from .accordion import Accordion # noqa
  File \"/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv-3.8/lib/python3.8/site-packages/panel/layout/accordion.py\", line 5, in <module>
    from .base import NamedListPanel
  File \"/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv-3.8/lib/python3.8/site-packages/panel/layout/base.py\", line 13, in <module>
    from ..reactive import Reactive
  File \"/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv-3.8/lib/python3.8/site-packages/panel/reactive.py\", line 26, in <module>
    from .config import config
  File \"/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv-3.8/lib/python3.8/site-packages/panel/config.py\", line 21, in <module>
    from .io.notebook import load_notebook
  File \"/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv-3.8/lib/python3.8/site-packages/panel/io/__init__.py\", line 9, in <module>
    from ..config import config
ImportError: cannot import name 'config' from partially initialized module 'panel.config' (most likely due to a circular import) (/lava-364500/0/tests/0_container-test-run/lisa/.lisa-venv->
```

**Comment by philippjfr** [comment]
@douglas-raillard-arm Any idea about the exact version that got pulled in?

**Comment by philippjfr** [comment]
I'm not particularly worried about this since neither panel.reactive.py nor panel.io.__init__.py now imports config, so whatever caused this it should be resolved now.

**Comment by douglas-raillard-arm** [comment]
@philippjfr The CI log is weirdly missing pip install output that would "prove" the version but it does show in essence:
```
python3.8 -m pip install --no-cache-dir requirements.txt
```

The requirements.txt in question does not pin any specific version, so it would have pulled the latest PyPI version from exactly 8 days ago (March 28th). This job ran the same Python program multiple times, and only at iteration 18 did the import error show up, so it's definitely an intermittent bug. The thing is I can't see where the variability can be, apart from ordering of imports in sources, which is obviously fixed since the code stayed the same all along.
