### ISSUE TITLE
FastListTemplate not working on panel==0.13.0rc5 - CSS is missing

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3340]
When I run awesome-panel.org on panel==0.13.0rc5 it does not look good.

![image](https://user-images.githubusercontent.com/42288570/162267762-90f24819-c455-4d00-bc38-df01f6253e9f.png)

**Comment by MarcSkovMadsen** [comment]
I can see the cause is some missing css files.

With panel 0.12.6 at awesome-panel.org I see

![image](https://user-images.githubusercontent.com/42288570/162268395-d8b46720-fbb1-45ea-88ba-ff62144e103a.png)

With panel 0.13.0rc5 locally I see 

![image](https://user-images.githubusercontent.com/42288570/162268489-2ce3cee8-644e-4fbc-a999-c1e0e24d9938.png)

For example the padding of the `fast-card` that used to be set in the `fast_panel.css` is missing.

**Comment by MarcSkovMadsen** [comment]
Let me know if you need more info here @philippjfr. My guess is that either the cause is just that it is a release candidate or that something systematically about bundling is wrong??

**Comment by philippjfr** [comment]
Thanks, looking first thing tomorrow.

**Comment by MarcSkovMadsen** [comment]
Will there be a RC6 that I should test @philippjfr ?

**Comment by philippjfr** [comment]
There already is an RC6 for you to test.

**Comment by MarcSkovMadsen** [comment]
Can confirm this one has been fixed with RC6 @philippjfr .
