### ISSUE TITLE
the panel sliders don't expose the fomart atribute in the bokeh AbstractSlider class

### ISSUE THREAD

**Issue by danielmesser1** [holoviz/panel#335]
The panel sliders should expose all the attributes that are defined in the bokeh sliders

**Comment by philippjfr** [comment]
We should consider https://github.com/bokeh/bokeh/issues/6899 for background and try to put together a concrete proposal we can raise in bokeh.

**Comment by philippjfr** [comment]
The format attribute has now been exposed for a while.
