### ISSUE TITLE
Make online documentation interactive

### ISSUE THREAD

**Issue by joelostblom** [holoviz/panel#3350]
I noticed in the release notes that you are planning a documentation overhaul for 1.0. I have been away from Panel for a while, but am interested to check it out again, particularly with the Vega event additions, and I am excited for the docs to be updated! One suggestion I would like to make is to try to make it so that the online documentation is interactive. Although it is possible to download the notebooks and run locally, this is not as convenient as seeing the intended behavior directly in the online docs and is especially a barrier to entry for new users.

I understand that having a running Python server for the docs might not be an option, but I wonder if a workaround would be possible. For example, I have always considered the `.embed` method a great strength of Panel and maybe you could leverage that here by automatically appending `.embed` on all displayed panel objects during the doc build, so that they render online? There could be a max allowed size so that this does not increase the size of the docs more than necessary.

Edit: After learning more about Panel's plans toward WASM compilation and seeing the pyscript announcement, I am excited to see how these can be used to add interactivity to the docs!

**Comment by philippjfr** [comment]
(Almost) all docs will be runnable with the sphinx-pyodide extension I've built starting in 1.0.

**Comment by joelostblom** [comment]
That's awesome! Thank you working on this!

**Comment by philippjfr** [comment]
This is now complete, you can try it out on: https://pyviz-dev.github.io/panel/

**Comment by joelostblom** [comment]
@philippjfr Is it possible to use the sphinx-pyodide extension you made with other projects or is it custom-built for panel? I would like to use it for some of my lecture notes and eventually with the altair docs too. I have tried a bit with jupyter-lite sphinx, but it would be great to just add a play button to all existing code cells like in the panel docs without restructuring the docs completely.

**Comment by MarcSkovMadsen** [comment]
Hi @joelostblom 

I believe What is currently possible is documented here https://panel.holoviz.org/how_to/wasm/sphinx.html
