### ISSUE TITLE
Enable setting color of needle on Gauge

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3357]
I've always lacked the ability to set the color of the needle on the Gauge to make it look nice.

![image](https://user-images.githubusercontent.com/42288570/162604618-fc54d323-b186-4c14-81b7-560abb855995.png)

**Comment by aktech** [comment]
Hey @MarcSkovMadsen You could still do it via custom options, is that all you wanted?

```python
pn.indicators.Gauge(
    name="Engine", custom_opts={
        "pointer": {
            "itemStyle": {
                "color": 'red'

            }
        }
    }
)
```

<img width="1085" alt="Screenshot 2023-09-25 at 10 04 40 pm" src="https://github.com/holoviz/panel/assets/5647941/908c38c2-b27a-4a96-bbc4-aca2f0725ecd">

**Comment by aktech** [comment]
Should this be closed now or should we add a property named "needle_color"?

**Comment by MarcSkovMadsen** [comment]
That is a good question. We could also just add it as an example to the reference guide?

**Comment by aktech** [comment]
That sounds more reasonable, thanks I'll add that.
