### ISSUE TITLE
SVG Reference Notebook displays error

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3373]
https://panel.holoviz.org/reference/panes/SVG.html

![image](https://user-images.githubusercontent.com/42288570/163102602-b3ea5baf-577a-4cd7-8db3-934ba19cb10b.png)

**Comment by Hoxbro** [comment]
This is probably just related to bad timing when creating the current documentation.

The SVG can be found on the current development documentation: https://pyviz-dev.github.io/panel/reference/panes/SVG.html#panes-gallery-svg

**Comment by MarcSkovMadsen** [comment]
Thanks.

Users going to the existing reference notebook would get a bad impression though.

**Comment by Hoxbro** [comment]
The problem will fix itself* with the upcoming release of Panel.

*) Assuming the site is not under maintenance again...

**Comment by philippjfr** [comment]
Right, this will fix itself.
