### ISSUE TITLE
Add YT reference notebook or gallery example

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3376]
When adding docstrings to panes I discovered the `YT` pane. I did not know of this pane and guess other users would not either.

![image](https://user-images.githubusercontent.com/42288570/163110792-cab60917-3a21-4359-9b8c-35d1d205008e.png)

Please document this via a reference notebook or gallery example.

**Comment by philippjfr** [comment]
YT is deprecated.
