### ISSUE TITLE
documentation/examples do not exist/work

### ISSUE THREAD

**Issue by Make42** [holoviz/panel#3380]
I encountered a lot of issues with the panel documentation, especially with the examples. https://examples.pyviz.org/attractors/attractors.ipynb does not seem to exist anymore. Also https://examples.pyviz.org/attractors/attractors_panel.html does not seem to do anything in my Firefox.

**Comment by maximlt** [comment]
Thanks for pointing at broken links in the docs!

As for the second link you shared, it is expected that the app displayed at the end of the *attractors* page doesn't work. Panel apps (unless embedded) require a Python process to be running, which is not the case this page. You'll see warnings throughout Panel's documentation about that.
