### ISSUE TITLE
Use RAPIDS cudf.DataFrame instead of pandas.DataFrame for speedup

### ISSUE THREAD

**Issue by whaowhao** [holoviz/panel#3396]
I tried to replace pandas DataFrame with RAPIDS cudf DataFrame to speed up my scatterplot application, but it doesn’t seem to be supported. Is there plan on integrating RAPIDS cudf or cuxfilter?

**Comment by jbednar** [comment]
Panel itself doesn't care what type of dataframe you use; it's up to whatever plotting library you work with. hvPlot should work with both. BTW, cuxfilter includes Panel already, I believe, or at least it's in some of their examples.

**Comment by philippjfr** [comment]
Thanks for the issue. cuxfilter is indeed built on Panel and datashader. I'm closing this issue because it is not very specific. It depends entirely on what plotting library you use whether cuDF is supported or not and whether it provides any speedups.
