### ISSUE TITLE
Tab expansion working poorly in VS Code

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3400]
I'm on Panel 0.13.0. If I write  from `panel.pane import ` and press `CTRL+Space` or start typing `Markdown` I would expect VS Code to help me identify what is possible to import. It does not.

https://user-images.githubusercontent.com/42288570/163605291-3ff10210-1955-48bc-a7dc-82cde2e5433b.mp4

This is just an example of a general problem that makes it harder than it has to be to use Panel.

**Comment by MarcSkovMadsen** [comment]
Its the same with other combinations `pn.pane.` and `from panel import pane`. I simply cannot get any help that `Markdown` is available under `panel.pane`.

**Comment by philippjfr** [comment]
What does VSCode use for completion here? Guess it's not dynamic.

**Comment by MarcSkovMadsen** [comment]
VS Code uses the Python Language Server and static type analysis (similar to mypy).

I can see if I

1. Move the `from .layout import ...` to the top of the root `__init__.py` file
2. Restart VS Code
![image](https://user-images.githubusercontent.com/42288570/163608308-64ddd915-3c7d-444a-96ad-71966d735319.png)

the I start to be able to see some classes.

https://user-images.githubusercontent.com/42288570/163608340-51abecc3-c6da-4a21-ae8f-98554323d40f.mp4

**Comment by MarcSkovMadsen** [comment]
I've tried to set the Log Level for pylance to `trace`

![image](https://user-images.githubusercontent.com/42288570/163608453-3de15fb3-b72e-4063-8a58-56a2fb59d2d2.png)

and inspect the logs. But don't see any errors. See the pylance logs below.

![image](https://user-images.githubusercontent.com/42288570/163608583-d5a49d1f-3991-46c8-a2b0-a7259d750c59.png)

[log.txt](https://github.com/holoviz/panel/files/8497503/log.txt)

**Comment by MarcSkovMadsen** [comment]
It might have something todo with static analysis for panel not working at all as you can see below.

![image](https://user-images.githubusercontent.com/42288570/163608767-f67b8066-f73f-4045-96c2-c0dce0712cf8.png)

**Comment by MarcSkovMadsen** [comment]
But we are not alone https://github.com/microsoft/pylance-release/issues/844.

But for example Streamlit just works.

**Comment by MarcSkovMadsen** [comment]
Similarly if I run

![image](https://user-images.githubusercontent.com/42288570/163610212-ff787ddd-37e8-41ca-a2e5-c03a458d8508.png)

then mypy errors. I don't know for sure this is the cause. But might be.

**Comment by MarcSkovMadsen** [comment]
Pylance is built on top of `pyright` - not mypy. So maybe running `pyright` will reveal something?`

https://github.com/microsoft/pylance-release/issues/193

**Comment by MarcSkovMadsen** [comment]
I tried creating a new project and virtual environment. Everything fresh. Same problem.

**Comment by MarcSkovMadsen** [comment]
But I can confirm the problematic import seems to be `from . import param # noqa`. Somehow this makes intellisense not work.

But if I remove it, it works. Also for `pn.widgets` and `pn.pane`.

https://user-images.githubusercontent.com/42288570/163624380-c54dc5df-81a5-44d2-940a-ef19904b1704.mp4

**Comment by MarcSkovMadsen** [comment]
Why do we need `from . import param` @philippjfr?

**Comment by maximlt** [comment]
I just tried in my dev env and it actually works for me. I'll try to confirm that later in a new env with a fresh panel version.

**Comment by philippjfr** [comment]
Definitely more to improve on the editor experience but this specific issue is resolved by https://github.com/holoviz/panel/pull/3411
