### ISSUE TITLE
Document pn.extension

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3404]
I'm on Panel 0.13.0.

If I search the Panel web site I cannot find a reference page or other material documenting `pn.extension`. 

Besides `import panel as pn` this is the most used Panel command, so I believe it should be documented. There are so many things you can do with this command.

**Comment by maximlt** [comment]
I agree. But I would hold on for now on this one. One of the goals for the next release is a documentation overhaul, we'll have to decide the extent of this overhaul and how to reorganize the documentation (between ref guides,  howtos, etc.).

**Comment by greg-krulin** [comment]
Hi all,

I am wondering if there is any update to having full documentation of pn.extension? The closest I can find is on this [page](https://panel.holoviz.org/api/panel.config.html#panel.config.panel_extension) and it refers here. Hoping to get more insight into usage of it. Thanks!
