### ISSUE TITLE
Notification is not worked!

### ISSUE THREAD

**Issue by hengaini2055** [holoviz/panel#3407]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
Os： windows10
Jupyter lab: 3.3.2
Python: 3.9.11
panel: 0.13.0

#### Description of expected behavior and the observed behavior
I check the new function about notification from [panel_0.13.0 blog](https://blog.holoviz.org/panel_0.13.0.html)

#### Complete, minimal, self-contained example code that reproduces the issue

```
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/20587475/163669166-d0b20ae8-96bd-4e11-b5ee-84a02b8b321b.png)

**Comment by maximlt** [comment]
Hi @hengaini2055,

If you check Panel's documentation on the [notifications](https://panel.holoviz.org/reference/global/Notifications.html#global-gallery-notifications) you'll see you have to enable notifications with `pn.extension(notifications=True)`.

I'm closing this issue, if things still go wrong just let us know and I'll reopen it.

**Comment by hengaini2055** [comment]
Thanks!
