### ISSUE TITLE
Remove Pane from the public api

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3423]
I've never used `Pane` directly. I am not aware of any documentation explaining users to use it. On the opposite the documentation states to use specific panes or `pn.panel`. C.f. https://panel.holoviz.org/user_guide/Components.html#panes

Please simplify by removing it from the public api.

![image](https://user-images.githubusercontent.com/42288570/163765183-94cbf249-3903-4312-a822-e67212e052bd.png)

**Comment by philippjfr** [comment]
Agreed, let's issue a DeprecationWarning as soon as possible and then remove it entirely for the 1.0 release.
