### ISSUE TITLE
Inverted data when editing a cell in a sorted column

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#3431]
When using header sorters and then editing the data in a tabulator widget the data gets inverted.

As an example, starting with this dataframe:
```
   a  b
0  1  x
1  2  y
2  3  z
```

Then applying a header/frontend sorter, editing a cell (here `3` to `4`) and applying the header sorter again (the data should be displayed in the same order):
```
   a  b
0  4  z
1  2  y
2  1  x
```

**Comment by philippjfr** [comment]
Damn, was worried this could happen when syncing the `sorters`. We'll have to apply the sorters only for the `current_view` and not for the internal `_processed` attribute.
