### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3432]
I think for many reasons we should rename master to main like every one else does. For example 

![image](https://user-images.githubusercontent.com/42288570/164166009-35681cd2-84da-42b8-89e5-a13ed20f97c7.png)

**Comment by philippjfr** [comment]
Agreed, should do this soon. As a side-note, the enhancement label is for improvements to the actual library not developer related tasks or API changes.

**Comment by philippjfr** [comment]
Completed.
