### ISSUE TITLE
Notifications do not work with .show()

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3445]
A user of Panel 0.13.0 is trying out the notifications but cannot get it working with `.show()` https://discourse.holoviz.org/t/notifications-with-templates/3613. 

```python
import panel as pn

pn.extension(notifications=True)

def notify(event):
    pn.state.notifications.info('this is a notification')
    
btn = pn.widgets.Button(name='Notify')
btn.on_click(notify)

template = pn.template.FastGridTemplate(sidebar=[btn])
template.show()
```

**Comment by Rystaman** [comment]
Thanks for added this functionality, I found a further issue that I could not find a solution (perhaps a bug with the .destroy() command)

```
import panel as pn
import time

pn.extension(notifications=True)

def notify(event):
    noti1=pn.state.notifications.info('this is a notification',duration=0)
    
    #Do some task
    time.sleep(3)
    
    noti1.destroy()
    noti2=pn.state.notifications.info('this is another notification',duration=0)
    
    #Do some task
    time.sleep(3)
     
    noti2.destroy()


btn = pn.widgets.Button(name='Notify')
btn.on_click(notify)

template = pn.template.FastGridTemplate(sidebar=[btn])
template.show() 
```

For me the first notification appears and doesn't go away (I'd expected it to disappear after 3s)  whereas the second notification appears for 3 seconds then is correctly destroyed.

**Comment by maximlt** [comment]
Could you please open an other issue? This seems different from the original issue.
