### ISSUE TITLE
Plotly pane animation frame does not work

### ISSUE THREAD

**Issue by eli-pinkus** [holoviz/panel#3448]
#### ALL software version info
`panel==0.13.0`
`plotly==5.7.0`
`plotly-express==0.4.1`

#### Description of expected behavior and the observed behavior
Expected: a play bar renders at the bottom of the plot that causes the plot results to evolve over time based on the `animation_frame` argument.

Observed: a play bar renders, however, no changes associated with the bar are reflected and the play button does not reflect any clicks.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import panel as pn
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/earthquakes-23k.csv')
fig = px.scatter_mapbox(df, lat='Latitude', lon='Longitude',
                        center=dict(lat=0, lon=180), zoom=0,
                        animation_frame='Magnitude',
                        mapbox_style='open-street-map')
pn.pane.Plotly(fig)
```

#### Stack traceback and/or browser JavaScript console output
<img width="560" alt="Screen Shot 2022-04-23 at 11 06 07 PM" src="https://user-images.githubusercontent.com/89038244/164954509-a4b2b467-c5b7-4c22-809a-1fc6ff17d0ef.png">

#### Screenshots or screencasts of the bug in action

https://user-images.githubusercontent.com/89038244/164954764-68bc6a82-a02e-42fd-ab20-f43efcae41d0.mov

**Comment by wjingen** [comment]
Hi, I'm facing the same issue as @eli-pinkus. Wondering what was the fix you used?

**Comment by maximlt** [comment]
@wjingen do you still experience this issue?
