### ISSUE TITLE
Multi-Index Attribute Error When Using Tables

### ISSUE THREAD

**Issue by pbrennan-mvz** [holoviz/panel#3454]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

python3.9
Firefox
Windows 10

#### Description of expected behavior and the observed behavior

I keep getting this AttributeError: 'NoneType' object has no attribute 'MultiIndex' whenever I am using a table. I even got it when using the example from your documentation. I have tried both Tabulator and DataFrame widgets and they both result in the same error.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import panel as pn

pn.extension()
df = pd.DataFrame({'int': [1, 2, 3], 'float': [3.14, 6.28, 9.42], 'str': ['A', 'B', 'C'], 'bool': [True, False, True]}, index=[1, 2, 3])

df_widget = pn.widgets.Tabulator(df, name='DataFrame')

df_widget

```

#### Stack traceback and/or browser JavaScript console output
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [64], in <cell line: 7>()
      4 pn.extension()
      5 df = pd.DataFrame({'int': [1, 2, 3], 'float': [3.14, 6.28, 9.42], 'str': ['A', 'B', 'C'], 'bool': [True, False, True]}, index=[1, 2, 3])
----> 7 df_widget = pn.widgets.Tabulator(df, name='DataFrame', hierarchical=False)
      9 df_widget

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/panel/widgets/tables.py:1002, in Tabulator.__init__(self, value, **params)
   1000 self._on_edit_callbacks = []
   1001 self._on_click_callbacks = {}
-> 1002 super().__init__(value=value, **params)
   1003 self._configuration = configuration
   1004 self.param.watch(self._update_children, self._content_params)

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/panel/widgets/tables.py:88, in BaseTable.__init__(self, value, **params)
     86 self._renamed_cols = {}
     87 self._filters = []
---> 88 super().__init__(value=value, **params)

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/panel/reactive.py:956, in ReactiveData.__init__(self, **params)
    955 def __init__(self, **params):
--> 956     super().__init__(**params)
    957     self._old = None

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/panel/reactive.py:630, in SyncableData.__init__(self, **params)
    628 self.param.watch(self._update_selected, 'selection')
    629 self._validate()
--> 630 self._update_cds()

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/panel/widgets/tables.py:1288, in Tabulator._update_cds(self, *events)
   1284     return
   1285 recompute = not all(
   1286     e.name in ('page', 'page_size', 'pagination') for e in events
   1287 )
-> 1288 super()._update_cds(*events)
   1289 if self.pagination:
   1290     self._update_max_page()

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/panel/util.py:379, in updating.<locals>.wrapped(self, *args, **kwargs)
    377 self._updating = True
    378 try:
--> 379     fn(self, *args, **kwargs)
    380 finally:
    381     self._updating = updating

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/panel/widgets/tables.py:210, in BaseTable._update_cds(self, *events)
    207 @updating
    208 def _update_cds(self, *events):
    209     old_processed = self._processed
--> 210     self._processed, data = self._get_data()
    211     # If there is a selection we have to compute new index
    212     if self.selection and old_processed is not None:

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/panel/widgets/tables.py:1106, in Tabulator._get_data(self)
   1104 def _get_data(self):
   1105     if self.pagination != 'remote' or self.value is None:
-> 1106         return super()._get_data()
   1107     import pandas as pd
   1108     df = self._filter_dataframe(self.value)

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/panel/widgets/tables.py:463, in BaseTable._get_data(self)
    461 if len(indexes) > 1:
    462     df = df.reset_index()
--> 463 data = ColumnDataSource.from_df(df)
    464 if not self.show_index:
    465     data = {k: v for k, v in data.items() if k not in indexes}

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/bokeh/models/sources.py:342, in ColumnDataSource.from_df(cls, data)
    330 @classmethod
    331 def from_df(cls, data: pd.DataFrame) -> DataDict:
    332     ''' Create a ``dict`` of columns from a Pandas ``DataFrame``,
    333     suitable for creating a ``ColumnDataSource``.
    334 
   (...)
    340 
    341     '''
--> 342     return cls._data_from_df(data)

File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/bokeh/models/sources.py:257, in ColumnDataSource._data_from_df(df)
    254 _df = df.copy()
    256 # Flatten columns
--> 257 if isinstance(df.columns, pd.MultiIndex):
    258     try:
    259         _df.columns = ['_'.join(col) for col in _df.columns.values]

AttributeError: 'NoneType' object has no attribute 'MultiIndex'

**Comment by philippjfr** [comment]
Closing for lack of response. I'm pretty sure this is some issue in the user environment but please reopen if you have additional details.

**Comment by edduardoo** [comment]
For people in the future with the same problem: try restarting your Jupyter kernel. I was getting the same error, after I came here and noticed that it could be a problem with pandas import, I tried the import_module above, which didn't work. Then I tried the most obvious solution: restarting the kernel. And it worked. Some weird pandas importing stuff.
