### ISSUE TITLE
Fast template : 404 error fastbasetemplate/images/header-columns-over-bg.gif

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#3455]
When using a pandas Dataframe widget in a fast template I receive this error?
![image](https://user-images.githubusercontent.com/18531147/165506058-ec31a0e5-a989-4992-98bb-38e1f6505150.png)
I suppose the gif is missing in resources

**Comment by philippjfr** [comment]
Not quite sure why that would load a gif.

**Comment by xavArtley** [comment]
I don't know but it seeams to be here :
https://github.com/holoviz/panel/blob/4429e319e1aa5145ee0baa1d109d58d0c981e626/panel/template/fast/css/fast_bokeh_slickgrid.css#L74

**Comment by MarcSkovMadsen** [comment]
The original slickgrid also loads images.

**Comment by philippjfr** [comment]
I see, problem here is that the url path is relative to where the CSS is served from and that original CSS referenced an image served from within slickgrid itself.
