### ISSUE TITLE
pn.extension('plotly') disables pn.widgets.xxx that are otherwise visible using pn.extension()

### ISSUE THREAD

**Issue by BehroozBashokooh** [holoviz/panel#3459]
Hello,

Here is a problem I am facing:

Python 3.9.7
Jupyter notebook version 6.4.11
panel version 0.13.0
plotly version 5.7.0
plotly_express version 0.4.1

Running Jupyter notebook in Chrome and MS Edge

#### Description of expected behavior and the observed behavior
Building a panel app that requires pn.widget.FileDownload(), pn.widget.FileInput(), pn.widget.MultiSelect(). These widgets facilitate data import that is turned into a dataframe. The dataframe should get plotted with plotly. 

if I use pn.extention(), I can see the widgets and they work fine but the plotly chart does't display. However, if I use pn.extention('plotly'), then the widgets are not displayed.

```
import numpy as np
import pandas as pd
import panel as pn
pn.extension('plotly')

import plotly.graph_objects as go
import plotly_express as px

# prompt to download the formation top template
file_download= pn.widgets.FileDownload(file='Template.xlsx',filename='Template.xlsx')
file_download  #does not show the file_dowload widget button. if I reset kernel and just use pn.extension() then the plotly chart that comes later based on the input, is not displayed
```

#### Stack traceback and/or browser JavaScript console output
![image](https://user-images.githubusercontent.com/36369649/165692108-57880834-e757-4f49-bf3a-6990585b1131.png)

#### Screenshots or screencasts of the bug in action
if I use pn.extension() the widgets work well but when I get to the point to plot the plotly plot, I get this error

![image](https://user-images.githubusercontent.com/36369649/165692890-f7bdff54-d152-4e1b-93f7-91c982e9e901.png)
WARNING:param.main: PlotlyPlot was not imported on instantiation and may not render in a notebook. Restart the notebook kernel and ensure you load it as part of the extension using: pn.extension('plotly')

**Comment by philippjfr** [comment]
I cannot reproduce this, this is suggesting that there is some network error that is preventing Plotly to load, which in turn means that the extension does not fully initialize. Could you open your browser's JS console and report the errors?

**Comment by BehroozBashokooh** [comment]
The error message only appears if I start with pn.extension() and then ask for a plotly plot. if I start with pn.extension('plotly'), it does not produce an error but the pn.widgets don't appear in the notebook.

**Comment by BehroozBashokooh** [comment]
set the pn.extenstion('plotly') and checked the browser JS console when I execute a block containing a pn.widget. it says:

Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing

I installed the jupyter_bokeh library with the hope that this would be it but the error persists.

**Comment by philippjfr** [comment]
It seems like your network can't access the various resources it needs. Anything special about your setup?

**Comment by philippjfr** [comment]
I'm going to close since the issue is not in Panel but something to do with your browser/network configuration. Feel free to follow up on [Discourse](https://discourse.holoviz.org/) if you need more assistance in figuring this out.

**Comment by BehroozBashokooh** [comment]
Thanks very much for looking into this. it is very possible that my work computer and the IT policies it is adhering to might be the cause.

**Comment by philippjfr** [comment]
An issue you could file would be to allow inlining all resources in the notebook, which would avoid any network requests being made.

**Comment by BehroozBashokooh** [comment]
The strange thing is that the widgets alone, without the plotly components work well and the plotly component without the widgets works well too. When I want to use them together, they don't
