### ISSUE TITLE
Simplify public api of base.py

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3478]
For Panel v1.0.0 an improvement of the api is on the Roadmap.

One hint to easily understand what is public to users is to run `stubgen` (installed together with `mypy`) on a file.

If I run

```bash
stubgen 'panel/pane/base.py'
```

I see the below. I believe the 5 things marked with a minus below could/ should be removed from the public api.

![image](https://user-images.githubusercontent.com/42288570/166096121-3864fbe0-0b37-422b-86cc-1e390dbbc9f4.png)

You can discuss as the objects would be provided to *developers* that inherit from the classes. But users who uses child classes just get overloaded by the number of available methods.

**Comment by philippjfr** [comment]
Can see an argument for `priority` and `get_pane_type` but the others are useful API methods.

**Comment by philippjfr** [comment]
On balance I'm -1 on making any of these private, they are all useful if not commonly so. The cleanup of the param API will clean up the namespace significantly.
