### ISSUE TITLE
Please align panel.io.pyodide.show and pyscript.write

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3480]
I would like it to be as easy as possible for users to use Panel with pyscript.

I don't understand 

- Why Panel uses the term `show` while pyscript uses `write`. Please consider aligning the two.
- Why `show` uses the id of the dom element as the second argument while `write` uses it as the first argument. That is just mental overhead. Please align.
- Please also consider adding the `append` argument. Its pretty useful and powerful to be able to either *replace* or *append*. Replace for example makes it easy to use loading indicators before a dom element is populated. Append makes it possible to minimize the amount of html elements you have to add.

:-)

**Comment by MarcSkovMadsen** [comment]
Regarding having the dom element as the first argument to `write`/ `show`. Every `.js` library also does it this way when you create a new element. So having the id of of the dom element as the second argument is just mental overhead again.

**Comment by philippjfr** [comment]
All reasonable suggestions, one comments though. There is absolutely zero guarantee that any of the API in pyscript will exist even a couple of weeks from now. I will probably deprecate `show` in favor of a `write` function though because I'm not really too happy with the naming.

**Comment by jbednar** [comment]
Also note that even though PyScript and Panel are both from Anaconda, they are managed entirely separately, in different parts of the organization. So in general there isn't a mechanism by which the two would end up with similar APIs apart from one project adapting to the other "manually".
