### ISSUE TITLE
Make it possible to use Panel code in pyscript without have to specialize the code

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3482]
Its great that Panel can be used with pyscript. For example exporting a Panel app as a standalone wasm/ pyscript/ pyodide application https://github.com/holoviz/panel/pull/3481.

Another way that of using it that has immediate potential is using it in markdown or html directly. I would like to be able to write code that both works on my windows/ mac os/ linux machine and in the browser.

- For educational reasons I would like the code to look the same such that I don't have to explain that "in the browser you write this, but otherwise that".
- For being able to separate the code and the deployment.

Right now you would have to write something like

```html
<py-script>
import panel as pn

component=pn.pane.Markdown("Hello Panel World")
component2=pn.pane.Markdown("Hello Again")

pn.io.pyodide.show(component, "target")
pn.io.pyodide.show(component2, "target")
</py-script>
```

Why not enable writing something like

```html
<py-script output="target">
import panel as pn

pn.pane.Markdown("Hello Panel World").servable()
pn.pane.Markdown("Hello Again").servable()
</py-script>
```

Or

```html
<py-panel output="target">
import panel as pn

pn.pane.Markdown("Hello Panel World").servable()
pn.pane.Markdown("Hello Again").servable()
</py-panel>
```

?

You could maybe even support outputting to different dom elements via the argument `area`, i.e. `.servable(area='target1')` and `.servable(area='target2')`. You might even deprecate `area` and rename to `container`?

**Comment by philippjfr** [comment]
Implemented, this will all be formalized and documented in the 0.14.0 release.
