### ISSUE TITLE
https://panel.holoviz.org/ demos broken

### ISSUE THREAD

**Issue by Niko-La** [holoviz/panel#3488]
Other than the Gapminder demo the other 4 Panel examples are not opening up.   
The last two Glaciers and Porfolio Optimizer show "502 Container is still loading. Wait, then refresh.Check logs for more details."  The nyc demo is asking for anaconda login.

Tried on both chome and firefox

https://panel.holoviz.org/

Attractors
NYC Taxi
Glaciers
Portfolio Optimizer

**Comment by philippjfr** [comment]
Thanks for reporting this! Just brought them all back up. Will improve our downtime monitoring as well.

**Comment by Niko-La** [comment]
@philippjfr awesome looks like they are all back, except for the taxi one it takes you to a anaconda login page, unless that is by design?

**Comment by philippjfr** [comment]
Not by design, will redeploy without auth.
