### ISSUE TITLE
Change names of the Vega panes page to "Altair & Vega"

### ISSUE THREAD

**Issue by joelostblom** [holoviz/panel#3490]
Although Vega is the technically correct term, I think most people coming from a Python background will want to know how to use Panel with Altair, and they might not even know that Altair is built upon Vega and VegaLite. It seems like the [panes pages in the reference gallery](https://pyviz-dev.github.io/panel/reference/panes/Vega.html#panes-gallery-vega) all use their file name as the page title, which might mean that there are some restrictions on which names will work well, but something like "Altair & Vega" would be a great descriptive title that would make this page more easily discoverable.

**Comment by philippjfr** [comment]
I agree, we should probably allow defining aliases in the gallery configuration to make this possible.

**Comment by philippjfr** [comment]
Shouldn't have been closed yet. Are there any other entries that we should define better names for?

**Comment by joelostblom** [comment]
Thank you for the super quick fix!

**Comment by joelostblom** [comment]
@philippjfr and @MarcSkovMadsen it seems like these changes are not live as the documentation page still calls this section "Vega" rather than "Altair & Vega". Is there something else required to make this aliases live on the doc page?

![image](https://user-images.githubusercontent.com/4560057/217128046-94569afe-decb-4db2-b2ee-77d0104c38eb.png)

**Comment by jbednar** [comment]
In the [dev website](https://pyviz-dev.github.io/panel/reference/index.html), the longer name is used in the gallery:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1695496/217803931-a5bb7d9e-74bd-428a-8d91-e22f9558b684.png">
but the shorter name is used on the actual page:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/1695496/217804025-9dbdc4af-bcf9-4c1a-a69f-a82a1dd6f97b.png">
Not sure what the intent was.

**Comment by joelostblom** [comment]
Cool I didn't know there was a dev site, thanks for linking that. In addition to what you mentioned about the title of the page not being updated, it seems like the left side bar is also not updated and it is just called "Vega" there, which I think will make it harder to find for people using Altair (especially those not knowing that altair sits on top of vega-lite which sits on top of vega).

**Comment by jbednar** [comment]
Looks like sorting also uses the original name, which is confusing.

**Comment by joelostblom** [comment]
@philippjfr Just checking in on this again, I still see that the name is just "Vega"  at https://panel.holoviz.org/reference/panes/Vega.html#vega. Could it be changed to say "Altair & Vega" both as the title of the page and in the left side panel? 

![image](https://github.com/holoviz/panel/assets/4560057/99086b86-108c-49c2-bb05-fd514330efab)
