### ISSUE TITLE
Panel 0.13 fails with Jinja2>= 3.1.0

### ISSUE THREAD

**Issue by ItamarShDev** [holoviz/panel#3503]
Jinja2 removed Markup (see [here](https://jinja.palletsprojects.com/en/3.1.x/changes/?highlight=markup#version-3-1-0))
Which results in 
```log
lib\site-packages\panel\io\resources.py:24, in <module>
     22 from bokeh.resources import Resources as BkResources
     23 from bokeh.settings import settings as _settings
---> 24 from jinja2 import Environment, Markup, FileSystemLoader
     26 from ..util import url_path
     27 from .state import state

ImportError: cannot import name 'Markup' from 'jinja2'
```

**Comment by maximlt** [comment]
Are you sure you're using Panel `0.13`? The test suite currently passes with jinja2 `3.1.2`. See https://github.com/holoviz/panel/runs/6342876429?check_suite_focus=true#step:10:202

**Comment by ItamarShDev** [comment]
Reinstalled Panel and all is working.
Seems like something silently failed on the original upgrade 

Closing.
