### ISSUE TITLE
Tabulator nested in a tabulator row not being fully displayed

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#3504]
Reporting one or two issue(s) with the Tabulator widget, when another Tabulator widget is displayed as a `row_content`. The two cases I've seen are:

1. When the nested Tabulator widget is set with `sizing_mode` to `'stretch_both'`, its data isn't rendered (but its headers and pagination UI yes):

![image](https://user-images.githubusercontent.com/35924738/167602586-c9dfb7b6-9e93-4467-873a-7ebf97e7a059.png)

2. When the nested Tabulator widget is opened and an event test the loading attribute of the parent Tabulator widget to True and then False, the nested gets only partially displayed:

![image](https://user-images.githubusercontent.com/35924738/167602866-7f5efff9-e379-4a01-8bc5-56a116f4400c.png)

Minimal code to reproduce the two cases (in the first case, the dummy load button is useless):
```python
import time

import numpy as np
import pandas as pd
import panel as pn

pn.extension('tabulator')


df = pd.DataFrame(np.random.rand(10, 5))

def cb(row):
    # 1st case: with sizing_mode set to stretch_both only the table headers and pagination ui are displayed, not the content
    t2 = pn.widgets.Tabulator(pd.DataFrame(np.random.rand(10, 5)), pagination='local', sizing_mode='stretch_both')

    # 2nd case: the tabulator data content disappears partially after clicking on the load button
    # t2 = pn.widgets.Tabulator(pd.DataFrame(np.random.rand(10, 5)), pagination='local')

    return t2

t = pn.widgets.Tabulator(df, row_content=cb)

def cb2(event):
    t.loading = True
    time.sleep(1)
    t.loading = False

b = pn.widgets.Button(name='load')
b.on_click(cb2)

pn.Row(b, t).servable()
```

**Comment by philippjfr** [comment]
>When the nested Tabulator widget is set with sizing_mode to 'stretch_both', its data isn't rendered (but its headers and pagination UI yes):

Honestly I don't think this is a bug, the table fills the available space and really there is no "available space" inside the accordion, if you need a minimum height you will have to set the `min_height` parameter.

>When the nested Tabulator widget is opened and an event test the loading attribute of the parent Tabulator widget to True and then False, the nested gets only partially displayed:

This does seem like a bug.
