### ISSUE TITLE
panel.io has no attribute notifications

### ISSUE THREAD

**Issue by jhannink** [holoviz/panel#3516]
I am running macOS with jupyterhub `1.4.2` to serve panel dashboards with some notifications / toasts. This works perfectly fine from  jupyterlab, but once I try to preview the panel application outside of the jupyter notebook, it crashes because `panel.io has no attribute notifications` anymore which I could perfectly import from my jupyter notebook :(

Any idea what is the issue here? Thanks a lot :)

```
python == 3.9
panel == 0.13.0
bokeh == 2.4.
```

#### Complete, minimal, self-contained example code that reproduces the issue
```
import panel as pn
pn.extension(notifications=True)
pn.state.notifications.info('Test')
pn.io.notifications.NotificationArea().servable()
```

#### Stack traceback and/or browser JavaScript console output
Nothing in the JS console
#### Screenshots or screencasts of the bug in action
![grafik](https://user-images.githubusercontent.com/21099194/168273728-c4f1953e-d8f5-42d8-9c7e-0221787fd821.png)

**Comment by jbednar** [comment]
That sounds like you are running in a different conda environment than the one you need, with a different Panel version. You should be able to update the Panel version in that environment and fix this issue.
