### ISSUE TITLE
More explicit documentation will help

### ISSUE THREAD

**Issue by Jacob-Barhak** [holoviz/panel#353]
The current documentation in the development version is very helpful with very nice examples, yet in many cases, it does not include all options allowed for a command. 

For example, panel can take margins and options, and although those are documented [here](https://pyviz-dev.github.io/panel/user_guide/Customization.html) many questions remain. 

For example can I control font color?

Adding reference to attributes by linking to a page such as [this](http://www.stylinwithcss.com/resources_css_properties.php) or a similar page will be helpful for someone to locate all attributes used. 

Yet more importantly knowing the names of the parameters allowed for each class used, will help - especially for beginners.

**Comment by philippjfr** [comment]
Please feel free to make a PR to add this clarification.

**Comment by Jacob-Barhak** [comment]
OK @philippjfr ,
Since you were helpful, I will try and contribute. Yet I really do not know which list of attributes will be best. Here are examples: 
https://www.w3.org/Style/CSS/all-properties#list
http://www.stylinwithcss.com/resources_css_properties.php
https://www.w3.org/TR/CSS/#css

Which one of those links is preferred and what attributes you do not support due to possible conflict. Knowing this will help.

**Comment by philippjfr** [comment]
Great thanks. I think the w3 links are the most canonical reference for html/css. I think there's no way to really reason about which ones will have an effect it'll depend on the type of object and other factors.

**Comment by Jacob-Barhak** [comment]
Ok @philippjfr ,

This first link is a bit overwhelming, and the last link it too detailed , Perhaps adding all of those will be best. 
In any case the documentation should have a warning that some attributes will not work with some objects and situations, yet at least the data will be out there. I was looking for the documentation file for the customization, yet only found https://github.com/pyviz/panel/blob/master/doc/user_guide/index.rst

I did not find the source for the customization file where the links should be added.  In any case, I pan on some simple cosmetic fix rather than a full solution for documentation.

Hopefully you can help me out here so I can do the leg work.

**Comment by philippjfr** [comment]
I suppose as a non-notebook user this will be a bit of a pain for you since most of our docs are generated directly from notebooks, e.g.: https://github.com/pyviz/panel/blob/master/examples/user_guide/Customization.ipynb

If you suggest an edit I can add it some time this evening when my flight lands.

**Comment by Jacob-Barhak** [comment]
Sure Philipp,

Jupyter is a nice tool I used in the past, yet I rather you check the text anyway, so here are suggested minor fixes - in between <<>>:


# Edit 1:

css_classes
The css_classes allows associating a CSS class with a component which allows referencing the component from a CSS style. CSS styles can be embedded in raw form or by referencing an external .css file by providing each to the panel extension using the raw_css and css_files arguments; both should be supplied as lists. Outside the notebook or if we want to add some CSS in an external module or library we can simply append to the pn.config.raw_css and pn.config.js_files config parameters. 

<< For information on CSS, please visit the official [Cascading Style Sheets
home page](https://www.w3.org/Style/CSS/), yet note that some CSS elements may not be supported depending on use - although most styles should work. >>

To demonstrate this let us define a CSS class called widget-box which we will give a background and a nice border:

# Edit 2:

style
Certain components, specifically markup related panes, expose a style parameter which allows defining CSS styles which apply to the HTML container of the Pane's contents, e.g. the Markdown pane. <<The example below shows a simple font change using the 'font-family' property of the style, yet many other attributes may be applicable from the [following list](https://www.w3.org/Style/CSS/all-properties#list). >>

# In the future
The above is just a minor fix that will cover my little question, yet in the future you should consider writing properties for each interface you have. For example:
### panel.pane.Markdown 
#### Properties:
width - int - width of widget

height - int - height of widget

style - dict - dictionary containing css style properties and their values from [following list](https://www.w3.org/Style/CSS/all-properties#list)

margin - tuple - defines space around the element in the format (top, right, bottom, and left)

background - define background color for the element using one of the following [colors](https://www.w3.org/TR/SVG11/types.html#DataTypeColor)

# And have a nice trip!

**Comment by Jacob-Barhak** [comment]
After the creation of Discourse https://discourse.holoviz.org/ this issue can be closed since documentation is being built there continuously.
