### ISSUE TITLE
RadioBoxGroup width do not adapt to content

### ISSUE THREAD

**Issue by pat-schmitt** [holoviz/panel#3533]
#### ALL software version info
panel 0.13.0

#### Description of expected behavior and the observed behavior
I would expect that the width of the RadioBoxGroup should change in accordance with the length of the options (when using `inline=True`). But it seems that the width is constant (However, you can use `sizing_mode='stretch_width'` to use the whole available space, but this is not what I want). Thanks for any help!

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension()

radio_group = pn.widgets.RadioBoxGroup(name='RadioBoxGroup',
                                       options=['Biology', 'Chemistry', 'Physics', 'Something with a long name'],
                                       inline=True,
                                       background='red'  # included background to see extend of RadioBoxGroup
                                      )

radio_group

```

#### Screenshots of the bug in action
Actual Output:
![Screenshot from 2022-05-18 13-47-08](https://user-images.githubusercontent.com/50843444/169031876-0e28b0ad-01ec-4863-adad-4a9f2a3a3ec3.png)

Desired Output:
![Screenshot from 2022-05-18 13-47-52](https://user-images.githubusercontent.com/50843444/169031933-b4084fe2-a81c-4650-bd3e-eb742c93652a.png)

**Comment by maximlt** [comment]
This seems like a Bokeh bug:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/35924738/171695998-f980107c-e44f-4d45-9f0a-84fea3628fb6.png">
