### ISSUE TITLE
windows 10 pip install fail

### ISSUE THREAD

**Issue by Niko-La** [holoviz/panel#3535]
`Installing collected packages: panel, holoviews
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\kava\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\panel\\dist\\bundled\\datatabulator\\npm\\@holoviz\\panel\\dist\\bundled\\tabulator-tables@4.9.3\\dist\\css\\fast\\tabulator_fast.min.css'`

`pip install holoviews[recommended] --user`

**Comment by maximlt** [comment]
A possible workaround, could you try to install Panel in a [virtual environment ](https://docs.python.org/3/library/venv.html) instead of in your user account's local python package install location?

**Comment by philippjfr** [comment]
Closing due to non-response.
