### ISSUE TITLE
Tabulator embed content dropdown not visible

### ISSUE THREAD

**Issue by tomascsantos** [holoviz/panel#3559]
#### ALL software version info
https://gist.github.com/tomascsantos/96205204fe6252c6f0626536242a4508

#### Description of expected behavior and the observed behavior
I'm following along with the tutorial here: https://panel.holoviz.org/reference/widgets/Tabulator.html?highlight=tabulator#row-contents

And expect that when I duplicate the code, the results will be the same. I.e.: 
<img width="1068" alt="Screen Shot 2022-05-25 at 11 00 33 AM" src="https://user-images.githubusercontent.com/7690514/170331846-d82e0d26-b736-4411-a98f-6f255740bf95.png">

Instead when `embed_content=True` I don't see any content: 
<img width="1396" alt="Screen Shot 2022-05-25 at 11 01 24 AM" src="https://user-images.githubusercontent.com/7690514/170331990-462082e8-51fb-416e-b3d6-3d66e3c707eb.png">

When `embed_content=False` There are no dropdown widgets in the first column: 
<img width="1399" alt="Screen Shot 2022-05-25 at 11 02 09 AM" src="https://user-images.githubusercontent.com/7690514/170332339-84a729c9-c67b-4091-bf92-b88797e65f95.png">

#### Complete, minimal, self-contained example code that reproduces the issue

(copied from user guide)

```python
from bokeh.sampledata.periodic_table import elements

periodic_df = elements[['atomic number', 'name', 'atomic mass', 'metal', 'year discovered']].set_index('atomic number')

content_fn = lambda row: pn.pane.HTML(
    f'<iframe src="http://en.wikipedia.org/wiki/{row["name"]}?printable=yes" width="100%" height="300px"></iframe>',
    sizing_mode='stretch_width'
)

periodic_table = pn.widgets.Tabulator(
    periodic_df, height=500, layout='fit_columns', sizing_mode='stretch_width',
    row_content=content_fn, embed_content=False
)

periodic_table
```

Thanks for the awesome library, it's been a little rocky getting started but I'm hooked by the potential!

**Comment by tomascsantos** [comment]
It inexplicably started working. I think there must have been some old javascript files from the previous versions or something lingering on the machine.

**Comment by maximlt** [comment]
Yes this sometimes happens indeed. Cleaning up entirely the notebook output plus a hard refresh of the browser tab usually cleans up the cache to pull the right javascript files.
