### ISSUE TITLE
ReactTemplate and used external resources

### ISSUE THREAD

**Issue by keul** [holoviz/panel#3565]
#### ALL software version info

- panel 0.12.7
- 

#### Description of expected behavior and the observed behavior

Testing a panel application using ReactTemplate on both embedded mode inside JupyterLab and using the `panel serve --show`.

Looking at https://github.com/holoviz/panel/blob/7d21b7337409340562af4c5dcd0779beda91a0d8/panel/template/react/__init__.py#L54 I see

1. while React is fixed to most updated 16 version (OK), poiting to https://unpkg.com/babel-standalone@latest/babel.min.js seems not a good idea
1. react-grid-layout use a different CDN (but using the same of react is possible: https://unpkg.com/react-grid-layout@1.1.1)
1. react is loaded using **development bundle**

The last one is the bigger issue in my opinion. Having the development version of React is useful for local development and testing purpose, but it's not something to be distributed to users.

_Please note_: I'm pretty new with Jupyter+panel, I don't know if there is a "debug mode" that can be activated or not.
If so: probably the best would be to load the `.dev` version only in this case. But an applications served using `panel serve --show xxxx` should use the production bundle.

#### Screenshots or screencasts of the bug in action

![Schermata 2022-05-27 alle 12 31 18](https://user-images.githubusercontent.com/284924/170683114-e527c280-fc3b-46e4-8e8c-99ed97f719e1.png)

**Comment by maximlt** [comment]
I guess I would agree with your suggestions, thoughts on this one @philippjfr ?
