### ISSUE TITLE
Altair plot does not resize properly after leaving maximized screen in Fast template.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3571]
Panel 0.13.1

If you maximize and minimize again you will notice that the altair plot does not resize nicely. 

https://user-images.githubusercontent.com/42288570/170887092-9f18c19e-ad35-45ff-ae46-a62a1d24f51b.mp4

If it worked the maximize functionality is really strong. Now it just would not work for the user.

I don't know if its an Altair or FastListTemplate thing. But I've seen the same problem for the FastGridTemplate and for other panes as well.

## Code

```python
import altair as alt
import pandas as pd
import panel as pn

pn.extension("vega", sizing_mode="stretch_width")

data = pd.read_json(
    "https://raw.githubusercontent.com/vega/vega/master/docs/data/penguins.json"
)

brush = alt.selection_interval(name="brush")

chart = (
    alt.Chart(data)
    .mark_point()
    .encode(
        x=alt.X(
            "Beak Length (mm):Q",
            scale=alt.Scale(zero=False),
        ),
        y=alt.Y("Beak Depth (mm):Q", scale=alt.Scale(zero=False)),
        color=alt.condition(brush, "Species:N", alt.value("lightgray")),
    )
    .properties(width="container", height="container")
    .add_selection(brush)
)

vega_pane = pn.pane.Vega(chart, debounce=10, height=500)


@pn.depends(vega_pane.selection.param.brush)
def filtered_table(selection):
    if not selection:
        return "#### No selection"
    query = " & ".join(
        f"{crange[0]:.3f} <= `{col}` <= {crange[1]:.3f}"
        for col, crange in selection.items()
    )
    return pn.pane.DataFrame(data.query(query))


table = pn.Row(filtered_table, height=300, scroll=True)
component = pn.Column(vega_pane, table)

template = pn.template.FastListTemplate(
    site="Awesome Panel",
    title="Panel/ Altair Data App - WOW",
    accent="#F08080",
    main=[component],
).servable()
```

**Comment by MarcSkovMadsen** [comment]
I can see its related to https://github.com/holoviz/panel/issues/2617

**Comment by philippjfr** [comment]
Doubt it, I think it's the age old bug that Vega does not report the size of the plot including the legend (or colorbar) in some cases.

**Comment by MarcSkovMadsen** [comment]
Hi @philippjfr . I've tried searching for the so-called "old bug" in the Panel github issues but was not able to find it. Could you please share a link. It would help me understand and try to fix. Thanks.

**Comment by MarcSkovMadsen** [comment]
This issue might also be related to https://github.com/holoviz/panel/issues/3572
