### ISSUE TITLE
Feedback on "core concepts"

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3573]
https://pyviz-dev.github.io/panel/getting_started/core_concepts.html

1. Add autoreload

![image](https://user-images.githubusercontent.com/42288570/170888389-3dc84518-2efd-48b1-9d56-c65b3ec87d88.png)

2. Include the Panel Jupyter Preview icon in the Tip

![image](https://user-images.githubusercontent.com/42288570/170888428-6340b926-c410-4056-9c12-9e6a08d4c3fc.png)

(New users will not know which icon you are talking about)

3. Remove "construct construct"

![image](https://user-images.githubusercontent.com/42288570/170888499-991959eb-c302-4dc9-a41b-2b8fff450e03.png)

**Comment by philippjfr** [comment]
Please provide feedback in the PR: https://github.com/holoviz/panel/pull/3568
