### ISSUE TITLE
Errors not logged when nthreads is enabled

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#3574]
Errors raised in callbacks dispatched with `--num-threads` enabled are not logged in the console.

```python
# app.py
import panel as pn

def cb(e):
    raise ValueError('Not logged')

b = pn.widgets.Button(name='Action')
b.on_click(cb)

b.servable()
```

served with `panel serve app.py --num-threads 2`

**Comment by TheoMathurin** [comment]
Hope this will get attention, debugging without error logs is a real pain.

**Comment by jbednar** [comment]
Any debugging help would be greatly appreciated!

**Comment by TheoMathurin** [comment]
Ok, right now I don't know how to do so, but I will give it a try when I get a chance.

**Comment by Hoxbro** [comment]
I'm still not seeing anything on master.
