### ISSUE TITLE
Unable to remove the first panel notification when using show() and the destroy() command

### ISSUE THREAD

**Issue by Rystaman** [holoviz/panel#3581]
Using panel 0.13.1, I found an issue with the notifications (perhaps a bug with the .destroy() command) where the first notification cannot be destroyed

```
import panel as pn
import time

pn.extension(notifications=True)

def notify(event):
    noti1=pn.state.notifications.info('this is a notification',duration=0)
    
    #Do some task
    time.sleep(3)
    
    noti1.destroy()
    noti2=pn.state.notifications.info('this is another notification',duration=0)
    
    #Do some task
    time.sleep(3)
     
    noti2.destroy()


btn = pn.widgets.Button(name='Notify')
btn.on_click(notify)

template = pn.template.FastGridTemplate(sidebar=[btn])
template.show() 
```
For me the first notification appears and doesn't go away (I'd expected it to disappear after 3s) whereas the second notification appears for 3 seconds then is correctly destroyed.

**Comment by maximlt** [comment]
Thanks for reporting this issue, I could reproduce it with the example you shared.

@philippjfr I've noticed that when multiple notifications are open with `duration=0`, removing a notification from the UI does not actually remove it from the list of notifications of the `NotificationArea` class, this only happens when the last displayed notification is removed. This may be the root cause of this issue.

**Comment by jan-schueler** [comment]
In Panel 1.4.2 it seems still only possible to destroy the last displayed notification, see the slightly adjusted example from above. 

@philippjfr @maximlt Is this a known issue?
```
import time

import panel as pn

pn.extension(notifications=True)


def notify(event):
    noti1 = pn.state.notifications.info("this notification can not be destroyed", duration=0)

    time.sleep(3)

    noti2 = pn.state.notifications.info("this notification can be destroyed", duration=0)

    time.sleep(3)

    noti2.destroy()
    noti1.destroy()


btn = pn.widgets.Button(name="Notify")
btn.on_click(notify)

template = pn.template.FastGridTemplate(sidebar=[btn])
pn.serve(template)
```
