### ISSUE TITLE
Player.interval required to be an integer parameter when float should be acceptable

### ISSUE THREAD

**Issue by dmarx** [holoviz/panel#3584]
The "interval" attribute can be used to set the starting play speed of the Player widget.

Under the hood, usage of this value clearly does not presume that it is an integer, so it seems unnecessary (and constraining) to restrict users to providing integer values in the widget's init method:

https://github.com/holoviz/panel/blob/646f4d297994ac3798186276152ddba48542871e/panel/models/player.ts#L264-L270

Forcing users to provide integer values only permits arbitrarily accelerating the animation

demo code:

```
# permitted:
kargs['i'] = pn.widgets.Player(interval=1, name='step', start=1, end=n_imgs_per_group, step=1, value=1, loop_policy='reflect')

# raises an error:
kargs['i'] = pn.widgets.Player(interval=0.5, name='step', start=1, end=n_imgs_per_group, step=1, value=1, loop_policy='reflect')
```

**Comment by dmarx** [comment]
oh you know what... I think my confusion here was just that the default interval is 500. this probably doesn't need to be a float, I misinterpreted this parameter as a multiplier on the default play speed rather than a number of microseconds. clarifying that this interval is "microseconds between updates" in the docstring and help docs would probably resolve this confusion going forward.

**Comment by maximlt** [comment]
You're right the docs could be improved there, do you feel like opening a PR to fix that?

**Comment by dmarx** [comment]
Sure, no problem
