### ISSUE TITLE
Weird resizing issue when using loading=True while app is loading

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3602]
`pip install panel==0.13.1 panel-highcharts==20220428.1`

----------

My app needs to load a lot of data before being able to display to the user. So I would like show a loading spinner while it loads.

Unfortunately this leads to the app not being able to resize to sizes smaller than then initially loaded window size.

I don't know if this is a Panel or Panel-HighCharts issue. But its quite mysterious to me why changing one parameter of a Panel `Column` can have such an impact. So if the fix is on the Panel-HighCharts side I would appreciate a hint at what to look for. If it can help the panel-highcharts typescript is [here](https://github.com/MarcSkovMadsen/panel-highcharts/blob/main/panel_highcharts/models/highbase.ts).

## The issue: using `loading=True`.

As you can see in the video my app cannot responsively resize to anything smaller than the initial window size. You see this by the scrollbars being added.

https://user-images.githubusercontent.com/42288570/172998258-e38dccf0-4113-48f0-968d-f1c7cab5150d.mp4

```python
import panel as pn
import panel_highcharts as ph

pn.config.loading_spinner = "bar"
ph.config.js_files(highcharts_no_data=True, highcharts_variwide=True)
pn.extension("highchart", sizing_mode="stretch_width")

configuration = {
    "title": {"text": "HighChart Pane"},
    "series": [
        {
            "name": "series1",
            "data": [1, 2, 3, 4, 5],
        }
    ]
}

plot = ph.HighChart(object=configuration, sizing_mode="stretch_both")
app = pn.Column(plot, sizing_mode="stretch_both", loading=True)

def on_load():
    app.loading=False

app.servable()
pn.state.onload(on_load)
```

## Works if not setting `loading=True`

If I don't set `loading=True` the resizing works nicely.

https://user-images.githubusercontent.com/42288570/172998537-8707e5f0-1e4b-4f29-a3ae-6b5660c263ea.mp4

```python
import panel as pn
import panel_highcharts as ph

pn.config.loading_spinner = "bar"
ph.config.js_files(highcharts_no_data=True, highcharts_variwide=True)
pn.extension("highchart", sizing_mode="stretch_width")

configuration = {
    "title": {"text": "HighChart Pane"},
    "series": [
        {
            "name": "series1",
            "data": [1, 2, 3, 4, 5],
        }
    ]
}

plot = ph.HighChart(object=configuration, sizing_mode="stretch_both")
app = pn.Column(plot, sizing_mode="stretch_both")

def on_load():
    app.loading=False

app.servable()
pn.state.onload(on_load)
```

## Hacky Workaround: temporarily change `sizing_mode` after load.

If I add 

```python
plot.sizing_mode="fixed"
plot.sizing_mode="stretch_both"
``` 

to `on_load` it magically works.

https://user-images.githubusercontent.com/42288570/172999072-c0bce737-358a-4344-8aa4-3ab5ffe10804.mp4

```python
import panel as pn
import panel_highcharts as ph

pn.config.loading_spinner = "bar"
ph.config.js_files(highcharts_no_data=True, highcharts_variwide=True)
pn.extension("highchart", sizing_mode="stretch_width")

configuration = {
    "title": {"text": "HighChart Pane"},
    "series": [
        {
            "name": "series1",
            "data": [1, 2, 3, 4, 5],
        }
    ]
}

plot = ph.HighChart(object=configuration, sizing_mode="stretch_both")
app = pn.Column(plot, sizing_mode="stretch_both", loading=True)

def on_load():
    app.loading=False
    plot.sizing_mode="fixed"
    plot.sizing_mode="stretch_both"

app.servable()
pn.state.onload(on_load)
```

**Comment by philippjfr** [comment]
Think this was fixed by https://github.com/holoviz/panel/pull/3599, please confirm.

**Comment by philippjfr** [comment]
Closing since we haven't heard back.
