### ISSUE TITLE
Panel not working in Jupyterlite

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3605]
I was just trying out if the latest version of Panel works in Jupyterlite. It does not. 

![image](https://user-images.githubusercontent.com/42288570/173214495-467d2942-794c-444b-9a34-6c6cda8f612b.png)

```python
import piplite
await piplite.install(['bokeh', 'jupyter_bokeh', 'panel==0.13.1'])

import panel as pn

pn.extension()

slider = pn.widgets.IntSlider(value=0, start=0, end=10)

slider
```

I was expecting it to work because of https://twitter.com/PhilippJFR/status/1506070969491898369?s=20&t=9nmyNRWhBE4oDdzsssv8Rg

**Comment by MarcSkovMadsen** [comment]
Its probably related to `Uncaught (in promise) Error: Module @bokeh/jupyter_bokeh, semver range ^3.0.4 is not registered as a`
        
       Uncaught (in promise) Error: Module @bokeh/jupyter_bokeh, semver range ^3.0.4 is not registered as a`

![image](https://user-images.githubusercontent.com/42288570/173214553-e4d5c8e6-ef72-4896-9136-23edbfcccb7f.png)

**Comment by MarcSkovMadsen** [comment]
I just tested with Panel 0.14.0. Now its a different error

![image](https://user-images.githubusercontent.com/42288570/196885006-d039296b-f95a-484b-87b8-c548ba1f7400.png)

## Additional Context

A user is asking here about Panel in Jupyterlite https://discourse.holoviz.org/t/jupyterlite/4405

**Comment by philippjfr** [comment]
Will get a fix into 0.14.1 and then release this evening.

**Comment by MarcSkovMadsen** [comment]
Still not working

![image](https://user-images.githubusercontent.com/42288570/201531198-00ebea15-7489-4bb0-8310-c5708e1438e5.png)

**Comment by philippjfr** [comment]
The `jupyter_bokeh` extension has to be installed on the Jupyterlite server:

<img width="661" alt="Screen Shot 2022-11-13 at 17 42 46" src="https://user-images.githubusercontent.com/1550771/201533284-8c01040c-ade7-4577-8f78-f717c1ce9840.png">

**Comment by philippjfr** [comment]
i.e. to configure this you have to follow these instructions and add `jupyter_bokeh` as a dependency:

https://jupyterlite.readthedocs.io/en/latest/howto/configure/simple_extensions.html

**Comment by philippjfr** [comment]
Try it out on https://panelite.holoviz.org/lab/index.html

**Comment by riziles** [comment]
I receive an error message: `Couldn't find a pure Python 3 wheel for 'widgetsnbextension~=4.0'`
