### ISSUE TITLE
FastGridTemplate: maxWidth not Number

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3608]
Panel 0.13.1

I've noticed that the `FastGridTemplate` raises errors in the console: `maxWidth not Number`, `maxHeight not Number`.

![image](https://user-images.githubusercontent.com/42288570/173221956-fdac4a13-d370-40da-8f48-78f3579d7ff8.png)

```python
import panel as pn

pn.extension()

component = pn.pane.Markdown("hello")

template = pn.template.FastGridTemplate(
  title="hello"
)
template.main[0:6,0:6]=component
template.servable()
```

**Comment by philippjfr** [comment]
Fixed.
