### ISSUE TITLE
Install precommit as part of developer installation

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3610]
I can see precommit does not get installed when I follow the developer instructions https://panel.holoviz.org/developer_guide/index.html.

If possible please also make sure the precommit hooks are added and run automatically to lower the friction of contributing to Panel and to hinder me making PRs like https://github.com/holoviz/panel/pull/3607 that fail tests https://github.com/holoviz/panel/runs/6848081608?check_suite_focus=true

**Comment by philippjfr** [comment]
>If possible please also make sure the precommit hooks are added and run automatically

`pre-commit install` is definitely something you'll have to run yourself but should definitely be documented.
