### ISSUE TITLE
Load spinner in default templates does not spin during plot update with panel >= 0.13.0

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#3619]
#### ALL software version info
holoviews 1.14.*
panel >= 0.13.0

#### Description of expected behavior and the observed behavior
Panel 0.13.0 introduced an undesirable change in the behavior of the spinner in default templates.

When you update for instance a DynamicMap, it's good to have the indicator spinning if the update is somewhat costly and takes some time. That was the behavior before panel 0.13.0 but now the spinner is busy for a very brief moment only. Then it indicates that the app is idle when it's clearly not. This can be confusing for the user.

#### Complete, minimal, self-contained example code that reproduces the issue
Take for example the following simple case of a DynamicMap driven by a slider. I use FastListTemplate but I think all default templates are affected.

```python
import pandas as pd
import panel as pn
import numpy as np
import holoviews as hv

pn.extension()


def make_plot(value):
    df['z'] = value*np.random.random(50000)
    return hv.Points(df, vdims='z').opts(color='z', clim=(0, 10))


df = pd.DataFrame({'x': np.random.random(50000),
                   'y': np.random.random(50000)})

slider = pn.widgets.IntSlider(start=1, end=10)
figure = hv.DynamicMap(pn.bind(make_plot, value=slider.param.value_throttled))

content = pn.Column(figure)
pn.template.FastListTemplate(main=content, sidebar=slider).servable()
```

#### Screenshots or screencasts of the bug in action
With panel 0.12.7:
![panel_0 12 7](https://user-images.githubusercontent.com/49269671/173373301-3d38dcb1-f03e-43d1-8362-73cddf7e7ec6.gif)

With panel 0.13.0 or 0.13.1:
![panel_0 13 0](https://user-images.githubusercontent.com/49269671/173373315-7b0ec58b-825b-4ddb-a5aa-1b277aa3abb2.gif)

**Comment by TheoMathurin** [comment]
Hello @MarcSkovMadsen, sorry to target you personally but I know you worked on templates.

Do you have an idea as to what caused this regression? If that helps, I'm willing to make a PR myself provided I know where to look.

I would really like to use the most recent versions of Panel which have very interesting new features but in the meantime I think that this regression is a real pain in terms of user experience.

**Comment by philippjfr** [comment]
Very odd, it seems more like this is a change in HoloViews than Panel. Still investigating though.

**Comment by philippjfr** [comment]
It's quite possible that a change in Panel meant that HoloViews needed updates to match. Fixed those now. I'll release a HoloViews 1.15.0 RC2 some time later today.
