### ISSUE TITLE
New warning in panel 0.13.1 –param function

### ISSUE THREAD

**Issue by mayonnaisecolouredbenz7** [holoviz/panel#3628]
Hi, I have been using panel to build a large scale multi page app. To achieve the multi page aspect I have been using tabs combined with param functions so as to defer the load of the page until the tab is selected, as is showing in an example in the documentation page. [Tabs — Panel v0.13.1 1](https://panel.holoviz.org/reference/layouts/Tabs.html)

After updating to 0.13.1 I get the following warning

> WARNING:param.Function 1: The function ‘func1’ does not have any dependencies and will never update. Are you sure you did not intend to depend on or bind a parameter or widget to this function? If not simply call the function before passing it to Panel. Otherwise, when passing a parameter as an argument, ensure you pass at least one parameter and reference the actual parameter object not the current value, i.e. use object.param.parameter not object.parameter.

Here is a MRE:
![image](https://user-images.githubusercontent.com/38597661/173980464-5e6b8595-1f80-4f97-9c59-65857eea1040.png)

Interestingly this warning is now reflected in the Tabs documentation, but not explained.

This issue was first presented by myself on the holoviz discourse.  Was responded to and now opened up as an issue here.

**Comment by philippjfr** [comment]
Thanks for reporting this, this is a usage of `ParamFunction` I had not considered when adding that warning but it does make sense of course. I'll think about it more and come up with a solution.
