### ISSUE TITLE
View.invalidate_layout causes issue with dynamic tabs

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#3630]
#### ALL software version info
panel 0.13.1

#### Description of expected behavior and the observed behavior
A while back I asked a query here [React with bokeh extension](https://discourse.holoviz.org/t/react-with-bokeh-extension/2864) related to rendering react with bokeh. To ensure that the layout is correctly formed after rendering, it was suggested to use view.invalidate_layout for my use case.

While this has been working perfectly, we have ran into an issue with this solution when using dynamic tabs.

Here when you change tabs, it seems like the previous tabs disappear for some reason.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel.widgets as pnw
slider  = pnw.IntSlider(value=10, start=1, end=60)


from panel.reactive import ReactiveHTML

class Test(ReactiveHTML):
    
    _template = "<div id='element'></div>"

    _scripts = {
        'render': """
        setTimeout(() => {
            element.innerHTML = '<div style="width: 500px; height: 500px; background-color: red"></div>'
            view.invalidate_layout()
        }, 1000)        
        """
    }

t1 = Test()
t2 = Test()
t3 = Test()
t4 = Test()


pn.Tabs(
    ("Chart 1", t1),
    ("Chart 2", t2),
    ("Chart 3", t3),
    ("Chart 4", t4),
    dynamic=True,
)

```

#### Stack traceback and/or browser JavaScript console output
No errors

**Comment by philippjfr** [comment]
invalidate_layout will no longer be needed in Panel 1.0 so I'll close.
