### ISSUE TITLE
Render with panel button not respecting pn.state related options

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#3639]
#### ALL software version info
panel master

#### Description of expected behavior and the observed behavior
Some really cool features were added panel 0.13 such as notifications and task scheduling. These seem to not be respected in the `Render with Panel` button in jupyter lab.

For example, in the two simple reproducers shared below, the widgets work fine in lab but not with the preview.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn
pn.extension(notifications=True)

def notify_click(event):
    pn.state.notifications.info('Button was clicked', duration=2000)

button = pn.widgets.Button(name='Click me', button_type='primary')
button.on_click(notify_click)
button.servable()
```

Example 2:
```python
import datetime as dt
import asyncio
import panel as pn
pn.extension('djs')

async def task():
    print(f'Task executed at: {dt.datetime.now()}')

pn.state.schedule_task('task', task, period='1s')
await asyncio.sleep(5)

pn.state.cancel_task('task')
```
#### Stack traceback and/or browser JavaScript console output
No errors shown

**Comment by philippjfr** [comment]
Top level awaits are not supported outside a notebook context so the second example not working is not surprising. The first example works now so I'll close.

**Comment by philippjfr** [comment]
Also generally tasks are for things that should happen independently of a session while a periodic callback should be used for actions that are tied to a specific session.
