### ISSUE TITLE
Sorter automatically applied on a cell edit

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#3659]
Currently when a cell is edited in a column that has a sorter applied the sorter is automatically re-applied. I believe we introduced this behavior recently and in hindsight I don't think it's correct. If I intend to edit more than one cell per row then the fact that the table is resorted after the edit forces me to find the row again to keep editing it. This is disrupting in a session with many edits expected.

The default behavior of Tabulator is not to apply the sorters after a cell edit, this can be tested here: http://tabulator.info/examples/5.2#editable

@philippjfr thoughts on that?

**Comment by philippjfr** [comment]
Agree this is an issue of course but my question is, when should the sorter be reapplied? If it's not reapplied at all that seems quite inconsistent. I'd be okay with reverting the change though.

**Comment by maximlt** [comment]
To re-apply a sorter after a cell edit you would need to click again on the UI sorters to trigger them. That's what Tabulator JS offers by default and I believe that's what you get in Excel/GSheet.

**Comment by philippjfr** [comment]
Sounds good, please feel free to revert.
