### ISSUE TITLE
HoloViews backend Plotly is not responsive

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3666]
I'm trying to create a Panel demo app using hvplot, HoloViews and the Plotly backend. The problem is that its not responsive. This is friction and makes it so much harder to use *the tools you know and love*. 

```python
import pandas as pd
import hvplot.pandas
import panel as pn
import holoviews as hv
import holoviews.plotting.mpl

pn.extension("plotly", sizing_mode="stretch_width")

hv.extension("bokeh", "plotly")

data = pd.DataFrame(
    {
        "x": [1, 2, 3, 4, 5, 6],
        "y": [2, 4, 8, 16, 32, 64],
    }
)
plot = data.hvplot(x="x", y="y", responsive=True)

pn.pane.HoloViews(plot, backend="plotly", sizing_mode="stretch_width", height=400).servable()
pn.pane.HoloViews(plot, backend="bokeh", sizing_mode="stretch_width", height=400).servable()
```

![image](https://user-images.githubusercontent.com/42288570/176989059-2f307581-91a6-43d4-8914-0b5d1e826516.png)

## Additional Context

Please dont tell me I can use a hook. Hooks sound complex. Its a last resort. Not something that should be needed for basic usage. 

Responsive behaviour is what I see users ask for all the time. I've never seen a use case where people want fixed size. And if responsive behaviour is difficult to achieve then they leave because they have too many other problems to solve.

**Comment by Hoxbro** [comment]
This seems to work on main if you are using `hv.extension("plotly", "bokeh")` but not if you are using  `hv.extension("bokeh", "plotly")`. @philippjfr any idea why this could be the case?

![image](https://user-images.githubusercontent.com/19758978/226544918-be245ebf-d954-40a4-842f-83ae2198a74e.png)

![image](https://user-images.githubusercontent.com/19758978/226544991-9c614728-5807-46ed-a1f2-f47021f0a82f.png)

``` python
import holoviews as hv
import hvplot.pandas
import pandas as pd
import panel as pn

# hv.extension("bokeh", "plotly")  # Does not work
hv.extension("plotly", "bokeh")  # Works

data = pd.DataFrame({"x": [1, 2, 3, 4, 5, 6], "y": [2, 4, 8, 16, 32, 64]})
plot = data.hvplot(x="x", y="y", responsive=True)

pn.pane.HoloViews(plot, backend="plotly", sizing_mode="stretch_width", height=400)
pn.pane.HoloViews(plot, backend="bokeh", sizing_mode="stretch_width", height=400)
```

**Comment by philippjfr** [comment]
Pretty odd, I'll have to take a look.

**Comment by philippjfr** [comment]
It's not surprising really, if you enable the 'plotly' extension then `.opts` will apply to the Plotly version. This is not a Panel issue but a hvPlot/HoloViews usage issue.
