### ISSUE TITLE
Wrong command suggested in help

### ISSUE THREAD

**Issue by janimo** [holoviz/panel#3674]
#### ALL software version info

Panel 0.13.1

#### Description of expected behavior and the observed behavior

panel serve  suggests generating a value for PANEL_OAUTH_ENCRYPTION using the inexistent oauth-key command, instead of  oauth-secret

 "generate a key with the `panel oauth-key` CLI "

**Comment by philippjfr** [comment]
Appreciate you catching this, any chance you want to contribute a fix? The code for it lives here: https://github.com/holoviz/panel/blob/master/panel/command/serve.py#L415

**Comment by janimo** [comment]
https://github.com/holoviz/panel/pull/3697

**Comment by philippjfr** [comment]
Thank you!
