### ISSUE TITLE
Allow further formatter customization for pn.inidicators.Number

### ISSUE THREAD

**Issue by ablythed** [holoviz/panel#3676]
As far as I can tell, the `format` parameter for [pn.indicators.Number](https://panel.holoviz.org/reference/indicators/Number.html) does not allow for customization beyond appending to the beginning or end of the number, but there are cases when more customization is needed. For instance, I am trying to display a float that I would like to format as $XX,XXX.XX or $XX,XXX, but adding the comma and/or the decimal does not seem possible with the current `format` parameter. @maximlt had the idea to accept a Bokeh `NumberFormatter`, which would be more flexible.

**Comment by Hoxbro** [comment]
I think the format is just a format string or f-string, so it should be possible with something like this

``` python
import panel as pn
pn.extension()
pn.indicators.Number(value=10000, format='${value:,.2f}')
```

![image](https://user-images.githubusercontent.com/19758978/177607617-9f0f2824-e015-4676-a5be-924761bdeeb7.png)

**Comment by maximlt** [comment]
Oh yes obviously! Thanks @Hoxbro !
