### ISSUE TITLE
Improve installation instructions 

### ISSUE THREAD

**Issue by haesleinhuepf** [holoviz/panel#3678]
#### Is your feature request related to a problem? Please describe.
Installation instructions appear insufficient.
https://panel.holoviz.org/getting_started/index.html

#### Describe the solution you'd like
Following the current installation instructions leads to an error and I (beginner user) need to figure out how to install it myself.

I executed these commands:
```
conda install -c pyviz panel
jupyter labextension install @pyviz/jupyterlab_pyviz
```

And this error is shown:
```
An error occurred.
ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
See the log file for details:  C:\Users\rober\AppData\Local\Temp\jupyterlab-debug-d952thpi.log
```

Consider updating the installation instructions so that they hint to installing node.js.

I couldn't figure out how to install npm at all. The [website](https://www.npmjs.com/) looks like I need to buy it.

#### Describe alternatives you've considered
It would be great if installation would be less complicated; e.g. in a single conda install ... command... I know that's tricky.

#### Additional context
I'm using Windows 10 OS.

**Comment by Hoxbro** [comment]
I'm sorry to hear you have problems with installing. 

Suppose you have a `jupyterlab` version 3 or above (which I strongly recommend). In that case, you don't need to use the command `jupyter labextension install @pyviz/jupyterlab_pyviz`, and therefore work by running the single command `conda install -c pyviz panel`.

`npm` is bundled with node.js, so you don't need to pay for it. But you don't need to install either to be able to play around with panel.

**Comment by haesleinhuepf** [comment]
Ok, cool. Thanks for the feedback @Hoxbro ! Obviously, this issue is obsolete then. 🌞
