### ISSUE TITLE
Support PANEL_AUTORELOAD

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3681]
I'm trying to add support for Panel to lighting.ai. For technical reasons I need to run `pn.serve`. I can see that I need the ability to use `autoreload` when developing Panel applications with lightning. I can provide `autoreload` as an argument to `pn.serve`. But I don't seem to be able to set an environment variable `PANEL_AUTORELOAD` that also set the autoreload.

Please add this.

**Comment by MarcSkovMadsen** [comment]
In lightning I currently do

```python
def _serve():
    port = int(os.environ["LIGHTNING_RENDER_PORT"])
    address = os.environ["LIGHTNING_RENDER_ADDRESS"]
    url = os.environ["LIGHTNING_FLOW_NAME"]
    websocket_origin = _get_websocket_origin()

    # PANEL_AUTORELOAD not yet supported by Panel. See https://github.com/holoviz/panel/issues/3681
    # Todo: With lightning, the server autoreloads but the browser does not. Fix this.
    autoreload = os.environ.get("PANEL_AUTORELOAD", "no")=="yes"

    view = _get_view()

    pn.serve({url: view}, address=address, port=port, websocket_origin=websocket_origin, show=False, autoreload=autoreload)
    _logger.debug("Panel server started on port http://%s:%s/%s", address, port, url)
```

When `AUTO_RELOAD` is set to `yes` the panel server reloads. But only slowly and it does not reload the browser. My guess is that its really applying the slow `--dev` option. Not the fast `--autoreload` option. 


How do get I change the above to get fast reload? Its important to figure out because developing without fast reload is a tedious process.

**Comment by MarcSkovMadsen** [comment]
I can see the websocket connection is lost when the autoreload is triggered

![image](https://user-images.githubusercontent.com/42288570/178136996-4f803f1c-2c84-45b0-ac95-b74339336885.png)

**Comment by philippjfr** [comment]
PANEL_AUTORELOAD is not a supported environment variable and I don't want to expose environment variables for every option. What's wrong with setting `pn.config.autoreload = True`?

**Comment by philippjfr** [comment]
>UPDATE: If I run pn.serve(..., autoreload=True) standalone without lightning it seems to refresh the browser as well. So the issue is probably some kind of lightning proxy ???

The problem is probably down to the fact that the `pn.state.location` component is not working correctly within Lightning? Do they use an iframe to embed the app? That might be the problem.

**Comment by MarcSkovMadsen** [comment]
The issue with lighting is probably the iframe. But it is technically possible to trigger a reload from inside an iframe. See https://github.com/Lightning-AI/lightning/issues/13593#issuecomment-1179975695.

**Comment by MarcSkovMadsen** [comment]
Its really hard to trace down what goes on on the Panel server. But my hypothesis is actually that `pn.serve(..., autoreload=True)` is the bokeh way of reloading. I.e. the browser reload is never triggered - only the server. 

My hypothesis is that the autoreload_watcher is only started with `panel serve`?

![image](https://user-images.githubusercontent.com/42288570/178198248-39decf52-a401-4042-88f4-79912e21c6c5.png)

**Comment by MarcSkovMadsen** [comment]
This shows that `pn.serve(..., autoreload=True)` only reloads the server. It also shows that triggering `pn.state.location.reload=True` actually reloads inside the iframe.

`pn_serve.py`

```python
import panel as pn
pn.serve({"/": "pn_app.py"}, port=5007, autoreload=True, show=False)
```

`pn_app.py`

```python
import datetime as dt

import panel as pn
pn.extension(sizing_mode="stretch_width")


def get_time():
    return dt.datetime.now().isoformat()


pn.panel("# Hello Panelss2GGGG").servable()
pn.panel("last reload: " + get_time()).servable()
current_time = pn.pane.Markdown().servable()
js_pane = pn.pane.HTML().servable()

def update_current_time():
    current_time.object = "Current time: " + get_time()
pn.state.add_periodic_callback(update_current_time, 1000)

button = pn.widgets.Button(name="Reload").servable()

@pn.depends(button, watch=True)
def button_click_handler(*args):
    print("Reload triggered", get_time())
    pn.state.location.reload=True
    print("Reload finished", get_time())
```

`pn_iframe.py`

```python
import panel as pn

pn.pane.HTML("""
    <iframe src="http://localhost:5007" style="height:100%;width:100%"></iframe>
""", sizing_mode="stretch_both").servable()
```

In two terminals run

```bash
python pn_serve.py
```

```bash
panel serve pn_iframe.py
```

https://user-images.githubusercontent.com/42288570/178208278-0de6015b-ff26-4fe3-937c-480c215fddb4.mp4

So now the question @philippjfr is how to start the `--autoreload` functionality? I've tried adding 

```python
from panel.io.reload import autoreload_watcher
pn.state.onload(autoreload_watcher)
```

to `pn_app.py`. But it did not seem to do it.

**Comment by MarcSkovMadsen** [comment]
If instead your run `panel serve pn_app.py --autoreload --port 5007` you get autoreload in the iframe.

https://user-images.githubusercontent.com/42288570/178211086-5abeb809-f3f7-41dc-a257-80ce4ab17fc3.mp4

For lightning I could change my implementation to start a process using `panel serve` for `.py` and `.ipynb` files, that would solve most of the problems. Serving a `render_fn` function would still have to be done with `pn.serve` I believe unless I could also wrap it in a file somehow.

**Comment by MarcSkovMadsen** [comment]
Got hot reloading for the lightning `PanelFrontend` by using `panel serve` instead of `pn.serve` for files. 

![hot-reload-working](https://user-images.githubusercontent.com/42288570/178224533-0d2d5021-c200-439a-bafb-b0d8e58f8c8f.gif)

**Comment by MarcSkovMadsen** [comment]
I've now worked around this issue by using `panel serve` also for a `render_fn` function. I close this issue.

The workaround is to `panel serve` the below script.

```python
import inspect
import os

import panel as pn

from lightning_app.frontend.utilities.app_state_watcher import AppStateWatcher
from lightning_app.frontend.utilities.other import get_render_fn_from_environment

def _get_render_fn():
    render_fn_name = os.environ["LIGHTNING_RENDER_FUNCTION"]
    render_fn_module_file = os.environ["LIGHTNING_RENDER_MODULE_FILE"]
    render_fn = get_render_fn_from_environment(render_fn_name, render_fn_module_file)
    if inspect.signature(render_fn).parameters:

        def _render_fn_wrapper():
            app = AppStateWatcher()
            return render_fn(app)

        return _render_fn_wrapper
    return render_fn

if __name__.startswith("bokeh"):
    # I use caching for efficiency reasons. It shaves off 10ms from having
    # to get_render_fn_from_environment every time
    if not "lightning_render_fn" in pn.state.cache:
        pn.state.cache["lightning_render_fn"] = _get_render_fn()
    pn.state.cache["lightning_render_fn"]()
```

where 

```python
def get_render_fn_from_environment(render_fn_name: str, render_fn_module_file: str) -> Callable:
    """Returns the render_fn function to serve in the Frontend."""
    module = pydoc.importfile(render_fn_module_file)
    return getattr(module, render_fn_name)
```
