### ISSUE TITLE
Formatting of Markdown links

### ISSUE THREAD

**Issue by apahl** [holoviz/panel#3685]
#### ALL software version info
Python 3.9, Panel 13.0, Ubuntu 22.04, Firefox 103.0b6 / Chrome 104.0

#### Description of expected behavior and the observed behavior
Links in the sidebar of the FastListTemplate are formatted in way that disrupts text flow ("FCsp3" in the screenshot).  
Is there a way to format them so that they are displayed inline with the rest of the text?

#### Complete, minimal, self-contained example code that reproduces the issue

```Python
# panel serve minimal.py


import panel as pn
import panel.widgets as pnw

pn.extension(sizing_mode="stretch_width")

button = pnw.Button(name="Start Calculation", button_type="primary", disabled=False)


@pn.depends(button)
def show_result(event=None):
    print("In function")
    if smiles_input.value == "":
        return pn.pane.Markdown("Please enter a SMILES string")


title = "Property Calculator"
enter_smiles = pn.pane.Markdown(
    "Enter the SMILES of one or more compounds (one per line) for which the properties should be calculated."
)
explanation = pn.pane.Markdown(
    """
Calculates the following physchem properties:

* **MW**
* **LogP**
* **TPSA** (Topological Polar Surface Area)
* **[FCsp3](https://doi.org/10.1021/jm901241e)** (Fraction of sp3-hybridized carbons)
"""
)
smiles_input = pnw.TextAreaInput(
    name="SMILES List", placeholder="Enter SMILES", max_length=5000, height=400
)

print("Starting...")


app = pn.template.FastListTemplate(
    title=title,
    sidebar=[enter_smiles, smiles_input, button, explanation],
    main=[
        pn.Column(
            show_result,
            sizing_mode="stretch_width",
        )
    ],
    main_layout="",  # Removes the grey background around the results in the main panel
)

app.servable()

```

#### Screenshots or screencasts of the bug in action
![Screenshot_20220712_110616](https://user-images.githubusercontent.com/9406836/178454541-81c14b50-8968-49e7-8aa9-b473f47ce638.png)

----

Thanks a lot for your help!

Kind regards,
Axel

**Comment by Hoxbro** [comment]
This is more of a user question and would be better to ask on [Discourse](https://discourse.holoviz.org/).

But the solution is changing the link to HTML and setting the style:
``` html
* <a style="display:inline; padding:0" href="https://doi.org/10.1021/jm901241e">**FCsp3**</a> (Fraction of sp3-hybridized carbons)
```
![image](https://user-images.githubusercontent.com/19758978/178496639-20510fd7-19ef-4c98-afe6-57e6ec56f6c6.png)
