### ISSUE TITLE
Regression: Names of Parameterized options not used as labels of Selectors

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3688]
Panel 0.13.1

```python
import panel as pn

component1=pn.panel("Value1")
component2=pn.panel("Value2")

selection = pn.widgets.RadioBoxGroup(value=component1, options=[component1, component2])

pn.Column(
    selection
).servable()
```

shows

![image](https://user-images.githubusercontent.com/42288570/178573885-12e5afef-ecda-4332-a970-fe6c17ef26b8.png)

I would expect "Value1" and "Value2" to be shown as labels. It used to be like that and it was simple and powerful.

**Comment by maximlt** [comment]
Even if it worked before, I'm not sure it should actually have, as I find this usage as shown in the example pretty confusing. Do you have a more specific use case in mind that would motivate supporting that?

**Comment by philippjfr** [comment]
I can't think of any mechanism that would have allowed this to work in the past tbh. I'm -0 on supporting this, I think it's not unreasonable to support but it seems of very limited utility. The `.object` of a pane is very rarely something that would make sense as an option label (e.g. what happens for non-string types and what happens if the string is very long). It does seem better to be explicit about the actual label.

**Comment by philippjfr** [comment]
Also just tested all Panel versions in the 0.11.x, 0.12.x as well as 0.13.0 and this has never worked as far as I can tell. Therefore I'm going to close as invalid.

**Comment by philippjfr** [comment]
The reason why I also think this is wrong is that the `.object` of a pane is mutable. If you update it and the label does not also update it is very confusing.

**Comment by jbednar** [comment]
Was this maybe the intent of the original post?

```python
import panel as pn
pn.extension()

component1=pn.panel("Value1", name="V1")
component2=pn.panel("Value2", name="V2")

selection = pn.widgets.RadioBoxGroup(value=component1, options=[component1, component2])

pn.Column(
    selection
).servable()
```

In that case I would have expected `name` to be used as the option label, but it isn't:

<img width="247" alt="image" src="https://user-images.githubusercontent.com/1695496/180331530-d0419461-e167-4ecc-a2d6-ce6aeaa570de.png">

**Comment by jbednar** [comment]
Sure, but it's worth checking if it used to work this way...

**Comment by MarcSkovMadsen** [comment]
I've checked panel==0.10.0/ param==1.9.3 with this example

```python
import param
import panel as pn

class MyClass(param.Parameterized):
    value = param.Number()

options = [
    MyClass(name="obj1"), MyClass(name="obj2")
]

pn.widgets.Select(options=options).servable()
```

It does not work.

I simply don't understand it. In my head I've used that so many times :-)

I would still argue it is very valuable to support and very much in line with how the [Parameter Subobjects](https://panel.holoviz.org/user_guide/Param.html#parameter-subobjects) example works for parameterized classes and how `Tabs` works. I would very much appreciate you reconsider @philippjfr. It would make using widgets to select between parameterized objects/ subcomponents much easier that having to construct a dictionary.

## Parameter Subobjects

```python
import param
import panel as pn


options = [pn.panel("Value1", name="value1"), pn.panel("Value2", name="value2")]

class MyOptionsClass(param.Parameterized):
    value = param.Selector(objects=options)

my_options = MyOptionsClass()

pn.Param(my_options, widgets={"value": pn.widgets.RadioBoxGroup}, expand_button=False).servable()
```

![image](https://user-images.githubusercontent.com/42288570/180479487-5df33f1f-6eda-43eb-9b81-cbcdb9859a6f.png)

## Tabs

```python
import panel as pn

options = [pn.panel("Value1", name="value1"), pn.panel("Value2", name="value2")]

pn.Tabs(*options).servable()
```

![image](https://user-images.githubusercontent.com/42288570/180479750-ed3f8ae4-7853-42a9-9a15-a54f0041d212.png)

**Comment by philippjfr** [comment]
Wait, that example is very different from the example you had posted originally. I fully agree that the `name` parameter should be used.

**Comment by MarcSkovMadsen** [comment]
I'm using the other examples because I believe they are all should behave similar using the `name` parameter.

I guess I thought the widgets would use the `name` parameter by default because I've been using the `param.Selector` and `pn.Param` so much. I though it was the widget that used the `name` parameter. But it seems `Param` does some magic.

**Comment by MarcSkovMadsen** [comment]
Ahh. I forgot the

> Was this maybe the intent of the original post?
> 
> ```python
> import panel as pn
> pn.extension()
> 
> component1=pn.panel("Value1", name="V1")
> component2=pn.panel("Value2", name="V2")
> 
> selection = pn.widgets.RadioBoxGroup(value=component1, options=[component1, component2])
> 
> pn.Column(
>     selection
> ).servable()
> ```
> 
> In that case I would have expected `name` to be used as the option label, but it isn't:
> 
> <img alt="image" width="247" src="https://user-images.githubusercontent.com/1695496/180331530-d0419461-e167-4ecc-a2d6-ce6aeaa570de.png">

Yes. This was the initial example I would like to display the value of the `name` parameter.

**Comment by jbednar** [comment]
Ah, ok. You confused us all with an apparently actual issue with an accurate issue title but the wrong code snippet. :-) I too think it used to say `V1` where it now says `Markdown(str, name='V1')`, and `V1` seems much more appropriate.
