### ISSUE TITLE
Strange vtkFollower position behavior away from the origin

### ISSUE THREAD

**Issue by darikg** [holoviz/panel#3699]
I'm trying to use vtkVectorText with vtkFollower. Text positioned at the origin behaves as expected. For text away from the origin, orbiting the view causes the non-origin-text to move away from its anchor point. This occurs in the panel viewer in the browser, but not in the standard VTK system viewer.

#### ALL software version info
panel                     0.14.0a4.post4+g1790cc01
pyvista                   0.36.dev0
vtk                          9.1.0
jupyterlab               3.4.3

windows 10, chrome/firefox

#### Description of expected behavior and the observed behavior
Expected / correct behavior in the standard VTK system viewer: The text away from the origin (blue sphere) remains anchored on the sphere after orbiting.
![image](https://user-images.githubusercontent.com/6875882/179289776-24105725-6fdd-48da-863e-0b1d99f18358.png)

Using the panel viewer in jupyter: the text away from the origin is in the wrong position.
![image](https://user-images.githubusercontent.com/6875882/179289978-f6859cf5-3a48-4a7c-8ecd-9b292d94b31d.png)

Notably, using a standard vtkActor (e.g. setting `follow=False`) in the example code below, the text stays in the correct position in the panel viewer, so I do think this is specific to `vtkFollower` somehow.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import vtk
import panel as pn
from pyvista import Plotter, Sphere

def add_point_text(plotter, pt, label, color, follow=True):
    text = vtk.vtkVectorText()
    text.SetText(label)
    mapper = vtk.vtkPolyDataMapper()
    mapper.SetInputConnection(text.GetOutputPort())

    if follow:
        actor = vtk.vtkFollower()
        actor.SetCamera(plotter.renderer.GetActiveCamera())
    else:
        actor = vtk.vtkActor()

    actor.SetMapper(mapper)
    actor.SetScale(.1)
    actor.SetPosition(*pt)
    plotter.add_actor(actor)
    plotter.add_mesh(Sphere(center=pt, radius=.01), color=color)

p = Plotter()
add_point_text(p, (0.0, 0, 0), '0', 'red', follow=True)
add_point_text(p, (1.0, 1, 1), '1', 'blue', follow=True)

p.show()  # vtk
# pn.panel(p.ren_win)  # jupyter
```

**Comment by xavArtley** [comment]
I think it's a bug on vtk.js side.
I opened an issue on their github: https://github.com/Kitware/vtk-js/issues/2531

**Comment by darikg** [comment]
thank you for isolating this to vtk.js @xavArtley

**Comment by maximlt** [comment]
Closing since this seems to be a vtk.js bug. Feel free to chime in if it appears to be a Panel issue.
