### ISSUE TITLE
FileInput doesn't work with any file 

### ISSUE THREAD

**Issue by sg-s** [holoviz/panel#3700]
#### ALL software version info

| thing | version |
| ---- | ---- |
| panel | 0.13.1 |
| bokeh | 2.4.3 |
| OS | macOS 12.4 |
| Python | 3.8.13 |

#### Description of expected behavior and the observed behavior

I expect file input to read in some file. instead, it is always none (after choosing a file in the pop-up chooser)

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import io
import panel as pn
pn.extension()

file_input = pn.widgets.FileInput()
file_input

# choose some file

file_input.value # is None

```

#### Stack traceback and/or browser JavaScript console output

nothing in JS console

#### Screenshots or screencasts of the bug in action

<img width="407" alt="Screen Shot 2022-07-18 at 8 31 41 AM" src="https://user-images.githubusercontent.com/6005346/179511675-d00a8694-b20a-4bc0-818d-60daf9c4eeb8.png">

**Comment by maximlt** [comment]
I just tried and the widget works as expected, i.e. it loads the file I chooses and its `value` parameter is set. Are you selecting large files?

**Comment by sg-s** [comment]
nevermind, it works now, no idea what changed. for future souls: all i did was shut down the kernel, jill jupyterlab lab, and restart.
