### ISSUE TITLE
Add copy-paste button to code sections on Discourse

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3711]
## Request

Add copy-paste functionality to code sections on discourse

## Motivation

I'm often trying to help the community on discourse. The first thing I do is to copy the minimum, reproducible code example included. That often involves selecting the all the code and sometimes even scrolling. The takes time and sometimes I don't even get all code copied and don't find out before later in the process where I cannot understand the output of the code.

It would help so much if I could just copy the code via a copy-paste button like in the Streamlit discourse forum https://discuss.streamlit.io/t/error-using-st-cache/27727

![image](https://user-images.githubusercontent.com/42288570/180494500-35708bcc-d9c3-4608-bdd2-0c73fe91aac0.png)

**Comment by philippjfr** [comment]
Done.
