### ISSUE TITLE
Plotly viewport_update_policy = 'mouseup' not working with Plotly Rangeslider 

### ISSUE THREAD

**Issue by pythonguy89** [holoviz/panel#3712]
#### ALL software version info

panel == 0.13.1
plotly == 5.9.0
pandas == 1.4.3

Platform: windows 10
browser: FireFox 102.0.1, Chrome 103.0.5060.134

#### Description of expected behavior and the observed behavior

When the pn.pane.Plotly has the setting viewport_update_policy='mouseup', it should only update the viewport param when the mouse click is released.  The plot does this correctly for regular zoom / panning. However, plotly has a [RangeSlider](https://plotly.com/python/range-slider/) feature, which allows users to pan using a separate slider. When users use the RangeSlider, it updates the viewport param continuously, similar to if viewport_update_policy='continuoius' instead of 'mouseup'. 

Thanks for the help

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import panel as pn
import plotly.express as px

# Load data
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv")
df.columns = [col.replace("AAPL.", "") for col in df.columns]

fig = px.line(x=list(df.Date), y=list(df.High))

# Add range slider
fig.update_layout(
    xaxis=dict(
        rangeslider=dict(
            visible=True
        ),
        type="date"
    )
)

# Add figure to panel
panel_pane = pn.pane.Plotly(fig, viewport_update_policy='mouseup')

i = 0


@pn.depends(vp=panel_pane.param.viewport)
def viewport_reader(vp):
    global i
    i += + 1
    return f"# viewport updated {i} times"


pn.serve(pn.Column(panel_pane,viewport_reader))

```

#### Screenshots or screencasts of the bug in action

https://user-images.githubusercontent.com/109829124/180580994-91724da8-cb22-4d8b-8f2a-ec30af73b8ab.mp4

**Comment by philippjfr** [comment]
Sounds like a bug but can you confirm this is not a bug in Plotly itself?

**Comment by pythonguy89** [comment]
After digging around, it looks like it is a bug in Plotly. My mistake. 

https://github.com/plotly/plotly.js/issues/2216

**Comment by philippjfr** [comment]
Appreciate the investigation and reporting back!
