### ISSUE TITLE
I've pushed some gallery notebook changes to master by mistake

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3733]
I was working on contributing some improvements to the gallery notebooks. Unfortunately I pushed to `master`.

- I've added a SeabornStyle.ipynb notebook that I will need your help @philippjfr to add to the gallery. I will also need you to upload the `seaborn-styles.gif` file below similarly to the `matplotlib-styles.gif`.
- I've corrected the wrong gif mentioned in https://github.com/holoviz/panel/issues/3731.
- I've addressed https://github.com/holoviz/panel/issues/3730

```python
$ git push
Enumerating objects: 35, done.
Counting objects: 100% (35/35), done.
Delta compression using up to 12 threads
Compressing objects: 100% (26/26), done.
Writing objects: 100% (26/26), 5.87 KiB | 182.00 KiB/s, done.
Total 26 (delta 21), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (21/21), completed with 9 local objects.
To https://github.com/holoviz/panel.git
   6d96647d..06b05fa5  master -> master
```

I'm not aware it will cause problems except the history.

Would it be possible to disable push to master without PRs? You should be able to protect the `master` branch by setting a policy https://stackoverflow.com/questions/46146491/prevent-pushing-to-master-on-github.

![seaborn-styles](https://user-images.githubusercontent.com/42288570/181919934-c8499162-a117-4855-a58a-8bd48e351d35.gif)

**Comment by Hoxbro** [comment]
I will fix it. Nothing to worry about.

**Comment by mattpap** [comment]
The simplest non breaking way to resolve this, is to create a revert commit and push again to `master`.

**Comment by MarcSkovMadsen** [comment]
Please Conformance @Hoxbro or @philippjfr if this is What I should do?

**Comment by Hoxbro** [comment]
If you are unsure what to do, please don't do it. You haven't done anything which can't be fixed. 

Just wait for someone other to fix it.

**Comment by philippjfr** [comment]
Yeah don't worry about it. I wouldn't even revert it. If you added it to the right directory it'll appear in the gallery automatically. If you want to make further changes just makes those in a new PR.

**Comment by philippjfr** [comment]
We can lock master, it's a little annoying because I usually push to master for dev releases.
