### ISSUE TITLE
Add extension entry point

### ISSUE THREAD

**Issue by jmosbacher** [holoviz/panel#3738]
I am currently writing an extension package for Panel would like to make some of the functionality loaded when `panel.extension()` is called. Unfortunately there is no entry point for this, and I'm not too happy with the alternatives of having my own duplicitous `extension()` function or having users import my package just for the extra Pane to be registered and never accessing it, as their IDEs will constantly remind them of this import without usage.

Would the maintainers be open to adding such an entry point group?
I opened a draft PR #3737 with how I would imagine the implementation, but I can of course change it to some other implementation based on feedback.

**Comment by philippjfr** [comment]
Sorry for the slow response, I've been out traveling. Very much open to this idea and the approach you submitted in your PR. I'll review more closely and then go from there.
