### ISSUE TITLE
Cannot find instructions for installing examples

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3740]
According to https://panel.holoviz.org/getting_started/

![image](https://user-images.githubusercontent.com/42288570/182767356-33ea632f-43cf-4bfb-a09c-00eb81847377.png)

I can jump to https://panel.holoviz.org/#installation to find instructions for installing the examples. But they are not there!

![image](https://user-images.githubusercontent.com/42288570/182767436-441a356c-1f5e-4dd1-b70f-98491916394e.png)

**Comment by maximlt** [comment]
Please check the dev website for the latest updates of the docs, there's new content there :)

In particular the installation instructions have been updated, have a look at this https://pyviz-dev.github.io/panel/getting_started/installation.html#getting-the-examples and if you find it alright you can close this issue.
