### ISSUE TITLE
Card header height wrong for some strings

### ISSUE THREAD

**Issue by jpursell** [holoviz/panel#3741]
panel                     0.13.1

bokeh                     2.4.3
holoviews                 1.15.0
jupyter_client            7.3.4 
jupyter_core              4.11.1 
jupyter_server            1.18.1 
jupyterlab                3.4.4  
jupyterlab_pygments       0.2.2 
jupyterlab_server         2.15.0 
notebook                  6.4.12 
notebook-shim             0.1.0
python                    3.10.5

Linux WSL Ubuntu 20.04
Chrome 99.0.4844.84 (Official Build) (64-bit)
Windows 10.0.19044 Build 19044

Expect Card header height to adjust to fit different length headers

```
import holoviews as hv
import panel as pn

hv.extension("bokeh")

pn.Card(header="one two three four five six seven")
```
![Capture](https://user-images.githubusercontent.com/1526297/182939967-42ea01e5-e4e2-4cc0-9c30-312696d83cb2.JPG)

**Comment by philippjfr** [comment]
Fixed:

<img width="173" alt="Screen Shot 2023-05-03 at 02 56 40" src="https://user-images.githubusercontent.com/1550771/235815126-5fae7042-f693-4b83-99e7-17267bf0bf3b.png">
