### ISSUE TITLE
WidgetBox background color does not change when using Dark Theme on Bootrstrap Template

### ISSUE THREAD

**Issue by pmav99** [holoviz/panel#3762]
``` python
import panel as pn

bootstrap = pn.template.BootstrapTemplate(
    theme="dark",
    sidebar=[pn.WidgetBox(pn.widgets.TextAreaInput(name="asdf"))],
)

_ = bootstrap.servable()
```
The background color of the `WidgetBox` does not change when `theme = "dark"`. This means that:
1. it looks ugly
2. the name of the widget (i.e. `asdf`) is no longer visible.

![image](https://user-images.githubusercontent.com/411196/185077853-3aefb0fc-6ea4-480f-8aab-506afa72a9c7.png)
![image](https://user-images.githubusercontent.com/411196/185077956-eb75aba7-1ff5-46bf-a39e-614c8a28c515.png)

#### ALL software version info
python 3.10
panel 0.13.1 installed from PyPi.
Tested on both firefox and Chromium on Linux

**Comment by philippjfr** [comment]
Fixed on main.
