### ISSUE TITLE
Tabulator within template row_content callback bug

### ISSUE THREAD

**Issue by tomascsantos** [holoviz/panel#3764]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
https://gist.github.com/tomascsantos/510244e11e4a92ad51b54d8ac259519d

#### Description of expected behavior and the observed behavior
When using `row_content` of tabulator, I expect that closing one row has no impact on the other rows. I find that the first time an opened row is closed, the rest of the rows are reverted to their "birth" properties. This ONLY HAPPENS IN A TEMPLATE, not in other containers. How strange?

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import asyncio
import pandas as pd
import panel as pn

pn.extension('tabulator',)


class Test(pn.viewable.Viewer):

    def __init__(self):

        self.table = pn.widgets.Tabulator(
            pd.DataFrame({'a': range(40)}),
            row_content=self.fn,
        )

    async def fn_helper(self, placeholder, row):
        """update placeholder after blocking task"""
        await asyncio.sleep(3)
        # placeholder.loading = False
        placeholder.background = 'yellow'

    def fn(self, row):
        placeholder = pn.Column(height=100, width=100, background='purple')

        asyncio.create_task(self.fn_helper(placeholder, row))

        return placeholder

    def __panel__(self):
        return self.table


# works outside template event in nested containers
# t = Test()
# pn.Column(pn.Column(t)).servable()

# # does not work inside Template
t = Test()
template = pn.template.VanillaTemplate(main=[t])
template.servable()
```

#### Screenshots or screencasts of the bug in action

Watch closely to see what happens ONLY the first time the row content is closed...
![bug_report_row_content](https://user-images.githubusercontent.com/7690514/185263274-fb3078d6-253d-4a08-9c5d-a1c3e22b190d.gif)
This bug does not exist without the template
![bug_report_row_content2](https://user-images.githubusercontent.com/7690514/185263402-629aa23a-e379-4d0c-8909-d95f581771dd.gif)

Thank you!

**Comment by philippjfr** [comment]
Fixed as of 1.4.5
