### ISSUE TITLE
Panel does not show memory / cpu usage with py3.9

### ISSUE THREAD

**Issue by tomascsantos** [holoviz/panel#3787]
#### Description of expected behavior and the observed behavior
Admin panel shows CPU/Memory usage with python 3.7 but not python 3.9

![image](https://user-images.githubusercontent.com/7690514/186985878-521e15dc-94da-4082-b8ce-09980fad9d9f.png)
![image](https://user-images.githubusercontent.com/7690514/186985893-d1467846-b86f-4d77-b687-9398520c67d7.png)

**Comment by Hoxbro** [comment]
You are probably missing the package `psutil` in the python-3.9 environment. I have it available:
![image](https://user-images.githubusercontent.com/19758978/187063572-ecdb9796-f48d-4a74-94be-9378420ce15b.png)


I think adding a small note in the Overview tab about `psutil` is needed to show CPU and Memory Usage would harm no one.

**Comment by tomascsantos** [comment]
You are quite right, thanks!

**Comment by philippjfr** [comment]
PR welcome to mention this in `doc/how_to/profiling/admin.md`

**Comment by philippjfr** [comment]
It is mentioned now.
