### ISSUE TITLE
Hide time in DatetimeRangePicker widget if enable_time is false?

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#3789]
The `DatetimeRangePicker` widget can be used as a date range picker if `enable_time` is False.

In this case it may be better to change the string format in the value field so that instead of the full datetime, you would simply see "2022-01-01 to 2022-01-02" as the time is not relevant in this context. It can also be confusing to display the time while it cannot be changed in the browser.

![image](https://user-images.githubusercontent.com/49269671/187182982-0467189f-174d-4bfa-954b-04a43ddbcf5f.png)

**Comment by TheoMathurin** [comment]
Sorry I did not know there was [an open PR for a DaterangePicker](https://github.com/holoviz/panel/pull/2804). This issue may therefore be ignored.

If a dedicated date range picker widget exists, the "enable_time" option in DatetimeRangePicker could become obsolete.

**Comment by TheoMathurin** [comment]
I will close this issue when #2804 is merged. If it's decided that it's not the way to go, there could be a discussion on how to make DatetimeRangePicker more suitable for picking dates.

**Comment by maximlt** [comment]
I think it would indeed be nicer to have a `DateRangePicker` widget, to complete the series of the date/time widgets which makes them more easily discoverable.

**Comment by MarcSkovMadsen** [comment]
But still it would be nice to be able to control the formatting. The underlying Bokeh model has the `format` property. Panel has not implemented that.

**Comment by Hoxbro** [comment]
I want to implement Bokeh's implementation of `DatetimePicker`, `DatePicker`, `DatetimeRange`, and `DateRangePicker`. Panel's current `DatetimePicker` and `DatetimeRangePicker` were implemented before Bokeh's current implementation and are based on an old version of `DatePicker` + some updates to work with Bokeh 3. 

I haven't done it because of point 2 of https://github.com/bokeh/bokeh/issues/12904, where local timezones affect the start and end times.

**Comment by jhyoo1982** [comment]
@MarcSkovMadsen Is there any workaround to hide time part before things improved/fixed?

**Comment by TheoMathurin** [comment]
Maybe `enable_time` could be removed from `_DatetimePickerBase` and this issue will be closed.

In fact I don't know what is the benefit from having `enable_time = False` in `DatetimePicker`. And now that `DateRangePicker` is coming, I'm struggling to think of a situation where it will be useful for `DatetimeRangePicker` either.
