### ISSUE TITLE
pn.state.location.unsync does not update URL

### ISSUE THREAD

**Issue by tomascsantos** [holoviz/panel#3795]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
https://gist.github.com/tomascsantos/40d5575d1faab94960c2be673337bcca

#### Description of expected behavior and the observed behavior
When I call `pn.state.location.unsync(my_widget)` I expect the URL to no longer reference `my_widget`
 
#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn

w = pn.widgets.MultiSelect(name='Test widget', options=["Hello", "Hi"])

if pn.state.location:
    pn.state.location.sync(w)

btn = pn.widgets.Button(name='Unsync')


def unsync_w(event):
    pn.state.location.unsync(w)


btn.on_click(unsync_w)

pn.Column('My App', w, btn).servable()
```

#### Screenshots or screencasts of the bug in action
Note that even after I "unsync" the widget, the URL still shows the widget parameter. This is going to lead to very long URL's full of information that is no longer relevant and difficult to debug startup behavior.

![unsync](https://user-images.githubusercontent.com/7690514/187287588-e4979b7e-ae00-4603-ae21-9ee15cf9a5b6.gif)

Thank you for your time!

**Comment by tomascsantos** [comment]
Wow thanks for the quick fix! I'm wondering what the release cadence might be? How often are new panel versions typically released?

**Comment by TheoMathurin** [comment]
@tomascsantos 

You can have a look at the previous releases: https://github.com/holoviz/panel/releases.

**Comment by philippjfr** [comment]
As with all projects the release cadence hasn't been as consistent or fast paced as I'd like. The current plan is to release 0.14.0 very soon, i.e. later this week or next.
