### ISSUE TITLE
Enable or document how to render options in a List Parameter as Literal elements

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3802]
## Request

Enable or document how to render options in a List Parameter as Literal elements

## Motivation

I'm trying to show a user how to create a custom dropdown component using ReactiveHTML in https://discourse.holoviz.org/t/customize-panel-components-widgets-design/4187.

There is already an example of a *child* template/ dropdown here https://panel.holoviz.org/user_guide/Custom_Components.html#child-templates

Unfortunately the drop down options are not rendered as Literal values but instead as panels, i.e. wrapping the literal value in `bk` `div`s.

In my example it makes the dropdown not look nice because a lot of margin is added.

![image](https://user-images.githubusercontent.com/42288570/188283341-7364227c-03d1-4aaf-ab07-b349acf4c214.png)

```python
from panel.reactive import ReactiveHTML
import param

class ShoelaceSelect(ReactiveHTML):
    value = param.Parameter()
    options = param.List()
    _template = """
<sl-dropdown>
  <sl-button slot="trigger" caret>Dropdown</sl-button>
  <sl-menu>
   {% for obj in options %}
    <sl-menu-item id="option">${obj}</sl-menu-item>
    {% endfor %}
  </sl-menu>
</sl-dropdown>
"""

    __javascript_modules__=["https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.82/dist/shoelace.js"]
    __css__ = ["https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.82/dist/themes/light.css"]
    # _child_config = {'obj': 'literal'}

import panel as pn

pn.extension()

select = ShoelaceSelect(options=["apple", "pear", "banana"])

pn.Column(select).servable()
```

I simple cannot find any documentation or example telling me how to provide these a literal values.

**Comment by MarcSkovMadsen** [comment]
## Working example

I found an example on discourse that helped construct this one using `loop.index0`. I think this should be documented somewhere.

```python
from panel.reactive import ReactiveHTML
import param

class ShoelaceSelect(ReactiveHTML):
    value = param.Parameter()
    options = param.List()
    _template = """
<sl-dropdown>
  <sl-button slot="trigger" caret>Dropdown</sl-button>
  <sl-menu>
  {% for option in options %}
    <sl-menu-item id="option-{{ loop.index0 }}">{{ option }}</sl-menu-item>
    {% endfor %}
  </sl-menu>
</sl-dropdown>
"""

    __javascript_modules__=["https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.82/dist/shoelace.js"]
    __css__ = ["https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.82/dist/themes/light.css"]
    # _child_config = {'obj': 'literal'}

import panel as pn

pn.extension()

select = ShoelaceSelect(options=["apple", "pear", "banana"])

pn.Column(select).servable()
```

**Comment by philippjfr** [comment]
The problem here was that you did not assign and ID to the `sl-menu` node so ReactiveHTML got very confused on how to insert the data. I will now enforce that loops must be enclosed in a node with an id. In this case you will now get an error like this:

```
ValueError: Loops may only be used inside a DOM node with an assigned ID. The following loop could not be expanded because the <sl-menu> node did not have an assigned id:

    {% for option in options %}
```

**Comment by philippjfr** [comment]
Actually a secondary issue is that loop expansion does not currently handle literal variables which is why you had to insert the `-{{ loop.index0 }}` stuff yourself. I can address that too I think.
