### ISSUE TITLE
launch a .py file without using the "Editor + Server" method

### ISSUE THREAD

**Issue by Philliec459** [holoviz/panel#3808]
I am using panel interact to create an interactive presentation of instantaneous calculated values using the "Editor + Server" method on a .py or a Jupyter Notebook with no problems.  However, I want to use this same code in another application that can only be launched from a python .py file with no "panel serve ...." command to preface it. Is there another way to launch a .py file to get the same interactive panel?

This application can be found at the following link:

https://github.com/Philliec459/Calculate-Archie-Water-Saturations-after-Fine-Tuning-Electrical-Properties-to-Pickett-and-Buckles-Pl

![pickett_log_sats3](https://user-images.githubusercontent.com/56929340/188511917-93ae1e47-e3eb-4cb7-8417-efd92a8478b3.gif)

**Comment by MarcSkovMadsen** [comment]
There is. Try asking on Discourse. It's for usage questions. Throw in a link here and close the issue, then I plan to answer there. Thanks 👍
