### ISSUE TITLE
Enabling panel-managed threading breaks pn.state.notifications and blocks code execution

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#3819]
Clean install with: 
Panel 0.13.1
Bokeh 2.4.3

The use of panel-managed threading leads to a strange behavior when calling methods (or setting attributes) from pn.state.notifications such as pn.state.notifications.clear() or pn.state.notifications.info() etc.

In short, the execution seemingly just stops without throwing an error server-side or in the browser console. The server and the session keep going and will listen to further events. This bug arises when enabling threading through the CLI or with pn.extension(nthreads=n).

In the example below I use a FastListTemplate because I could not get notifications to work without a template (if confirmed, that would be a separate issue). But the behavior reported here is observed regardless, with or without a template.

```python
import panel as pn

pn.extension(nthreads=2, notifications=True)
pn.state.notifications.position = 'center-center'


def callback1(event):
    button1.name = f'Clicks: {event.new}'  # That works fine


def callback2(event):
    print('here')
    pn.state.notifications.error('Error', duration=1000)  # Fails and execution stops here
    print('there')
    button2.name = f'Clicks: {event.new}'


button1 = pn.widgets.Button(name='Clicks: 0')
button1.on_click(callback1)
button2 = pn.widgets.Button(name='Clicks: 0')
button2.on_click(callback2)

pn.template.FastListTemplate(main=[], sidebar=[button1, button2]).servable()
```

If you click on button2, the notification is not displayed and the button name is not updated. But clicks on button1 and button2 will still be processed after that. Remove "nthreads=2" and it works as expected.

**Comment by MarcSkovMadsen** [comment]
I don't think it works without a template. Was also confusing to me in the beginning. I would happily upvote a bug report/ feature request for supporting notifications also without using a template.

**Comment by philippjfr** [comment]
This appears to be working fine in master and 0.14.0a11. Could someone confirm?

**Comment by TheoMathurin** [comment]
@philippjfr 

I can confirm that it works in 0.14.0a11!

However I failed to build a working environment with master so I can't say.

**Comment by philippjfr** [comment]
Thanks @TheoMathurin!
