### ISSUE TITLE
Combining different layout

### ISSUE THREAD

**Issue by davidpasquale** [holoviz/panel#3827]
Hi, 
I would like to combine two elements of different layout package.
- nav or navbar of bootstrap layout (or react, material layout)
- docking system provided by goldenlayout, i.e. [https://github.com/caplin/FlexLayout](https://github.com/caplin/FlexLayout)

or 

is it possible to use directly a wrapper to react FlexLayout inside panel window containers?

Thank you!

**Comment by philippjfr** [comment]
@davidpasquale Could you post this to our Discourse (https://discourse.holoviz.org/) since it's is really more of a usage question?
