### ISSUE TITLE
Spacing shows up differently in the server compared to the notebook version

### ISSUE THREAD

**Issue by jsignell** [holoviz/panel#385]
## Server
<img width="1472" alt="Screen Shot 2019-04-15 at 2 15 33 PM" src="https://user-images.githubusercontent.com/4806877/56155506-10e34980-5f89-11e9-94c8-875ba5a2150d.png">

## Notebook
<img width="1446" alt="Screen Shot 2019-04-15 at 2 17 07 PM" src="https://user-images.githubusercontent.com/4806877/56155550-340df900-5f89-11e9-8c1b-b14abc7f9e58.png">

**Comment by philippjfr** [comment]
I'm going to close, I've reduced the header spacing for the Markdown pane but in the end there's little hope of smoothing over all the CSS differences.
