### ISSUE TITLE
Widgets not working in VSCODE but works with jupyter notebook

### ISSUE THREAD

**Issue by mganesa-porsche** [holoviz/panel#3872]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
VSCode = 1.71.2
jupyter-bokeh = 3.0.5
python = 3.10.0
OS = macOS 12.6
panel = 0.13.1

#### Description of expected behavior and the observed behavior
Expected = float slider widget
observed = TypeError as shown in the screenshot

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension(comms="vscode")

pn.widgets.FloatSlider(value=0.0, 
                              start=0.0, 
                              end=5.0, 
                              step=0.5, 
                              name='Test')

```

#### Stack traceback and/or browser JavaScript console output

```
import panel as pn
pn.extension(comms="vscode")

pn.widgets.FloatSlider(value=0.0, 
                              start=0.0, 
                              end=5.0, 
                              step=0.5, 
                              name='Test')

```

#### Screenshots or screencasts of the bug in action
<img width="1307" alt="Screenshot 2022-09-22 at 12 41 43" src="https://user-images.githubusercontent.com/111494140/191734009-91281e35-cd84-4bc2-a024-33eb2b9a2a9b.png">

**Comment by Hoxbro** [comment]
Thank you for the report.  This seems to have been broken but is fixed on master. 

The new version of panel should be out soon with the fix, but if you can't wait, you can install the latest dev release with `pip install panel==0.14.0a24 --pre` or `conda install panel=0.14 -c pyviz/channel/dev`.

I will close this issue but feel free to open it again if you still think it is a problem.
