### ISSUE TITLE
Transfer of high resolution image takes way too long and even raises WebSocketClosedError

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3874]
holoviews==1.15.0, panel==0.13.1

I am trying to help a user create a Panel application for using his high resolution camera here https://discourse.holoviz.org/t/best-practice-for-displaying-high-resolution-camera-images-captured-on-server/4285.

He reports that transfering a 3208x2200 image of 7.1MB takes +7 seconds on his computer to transfer from server to client. This is a lot.

I have produced a minimum, reproducible example below. I also experience that the transfer time is high. But I also experience a `StreamClosedError` way before I get to the users dimensions.

https://user-images.githubusercontent.com/42288570/191795881-d371903d-1c86-4f32-a7e3-9ea4214eb988.mp4

```python
import param
import panel as pn
import numpy as np
import holoviews as hv
import time

pn.extension()

bounds=(-1,-1,1,1)

X=2200
Y=3208

class Camera(param.Parameterized):
    
    xresolution = param.Integer(100, bounds=(100, 2200), step=100)
    yresolution = param.Integer(100, bounds=(100, 3200), step=100)
    
    take = param.Event()
    count = param.Integer()
    duration = param.Number()

    value = param.Parameter() # Just some initial content


    @pn.depends("take", watch=True, on_init=True)
    def _take_a_picture(self):

        xls = np.linspace(0, 10, self.xresolution)
        yls = np.linspace(0, 10, self.yresolution)
        xx, yy = np.meshgrid(yls, xls)
        
        start = time.time()
        self.value = np.sin(xx+self.count)*np.cos(yy)
        end = time.time()
        
        self.count += 1
        self.duration = end-start

camera = Camera()

@pn.depends(image=camera.param.value)
def img0(image):
    return hv.Image(image,bounds=bounds)
layout = pn.Column(pn.Param(camera, parameters=["xresolution", "yresolution", "take", "duration"]), hv.DynamicMap(img0), ).servable()
```
```bash
2022-09-22 15:51:15,374 Failed sending message as connection was closed
2022-09-22 15:51:15,374 Task exception was never retrieved
future: <Task finished name='Task-2604' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /opt/conda/lib/python3.9/site-packages/tornado/websocket.py:1100> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/tornado/websocket.py", line 1102, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/tornado/websocket.py", line 1104, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
2022-09-22 15:51:15,375 WebSocket connection closed: code=None, reason=None
```

**Comment by philippjfr** [comment]
Surprising that this would crash the websocket. The default `--websocket-max-message-size` should be 20 MB. The latency is also surprising but I think arises from encoding and decoding the image.

**Comment by philippjfr** [comment]
Okay, latency arises for entirely preventable reasons in HoloViews. Will open an issue there.

**Comment by philippjfr** [comment]
I can't reproduce the websocket issue but if I fix the HoloViews issue the 3200x2200 image transfers in 130 ms.

**Comment by philippjfr** [comment]
<img width="383" alt="Screen Shot 2022-09-23 at 20 18 32" src="https://user-images.githubusercontent.com/1550771/192031882-31b8b130-a261-40ba-bf57-ea717b1f2954.png">

**Comment by MarcSkovMadsen** [comment]
Maybe the crash can be caused by me running on a Jupyter hub with some kind of constraints?

**Comment by philippjfr** [comment]
>Maybe the crash can be caused by me running on a Jupyter hub with some kind of constraints?

Yes, probably. I don't know how you've set up your Panel server on the JupyterHub but Jupyter configures quite harsh message size limits that you probably need to tweak. Happy to have that documented in the server deployment section but that's separate from this issue and the core issue here was in HoloViews so I'll close.
