### ISSUE TITLE
Make it easier to defer the loading of panels

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3881]
## Request

Make it easier to defer computations and displaying complex/ big objects to after the page has loaded.

## Motivation

I often see users of Panel develop applications that takes a long time to load. In the mean time the application appears unresponsive. This then leads to a bad user experience because users are not used to this and starts wondering if the application has failed or not. They  might refresh the application leading to more stress on the server.

Working with deployment on Lighting AI I can also see they have built in to their framework an expectation that the application responds fast (less than a second). This works for all the existing frameworks they support including data app frameworks like Streamlit, Dash and Gradio. 

- Streamlit works because it only responds with a minimum response to connect the web socket. The rest is loaded over the web socket.
- Gradio normally does not do anything heavy before the user has clicked a "submit" button.

For Panel it can be quite hard to respond within 1 second if you start loading data, using a template and/ or respond with a complicated dashboards.

Streamlit provides a `st.spinner` context manager to make this really easy. So they have never had the problem that their apps appears unresponsive.

## Existing solution

To defer load Panel provides the `pn.state.onload` function that you can use defer the heavy lifting to after the initial response.

This works. But its a callback api and means you have to write a lot of boiler plate code to use it. 

## Potential new solutions

- Change the initial request of Panel to do the same as Streamlit, i.e. respond with the minimum required to enable the app to transfer the rest via the web socket
    - This will solve the lightning ai 1 second issue
    - This will **not** give the user a better UI.
- Provide a `pn.state.loaded` parameter that users can `pn.bind` and `pn.depends` to.
    - This will remove the callback api
    - Users will have to provide an extra loaded argument to their functions which is not ideal.
- Add a `defer_load` parameter to  `pn.panel` to signal that the object or bound function should not load before the page has loaded. In the meantime some spinner should be shown.
- Provide a `defer_load` parameter to `pn.extension` that will defer the load of all `pn.panel`s to after the initial load. And before the initial load they will individually show a loading spinner.
- `defer_load` could potentially be added to `pn.bind` and `pn.depends` instead of `pn.panel`.
- `pn.defer_load` could potentially be an annotation and function instead.

## Basic App

This app takes a long time to load. In the mean time the app is unresponsive. This is what we normally teach our users to do. This is a bad user experience.

https://user-images.githubusercontent.com/42288570/192103784-97efd2c5-b124-4253-aeee-7e16c6bdee05.mp4

```python
import time
start = time.time()

import pandas as pd
import panel as pn
import hvplot.pandas

pn.extension(sizing_mode="stretch_width", template="fast")

def duration():
    return time.time()-start

def big_load():
    time.sleep(2)
    return pd.DataFrame({"x": [1,2,3], "y": [1,2,3]})

def big_plot():
    time.sleep(2)
    return pd.DataFrame({"x": [1,2,3], "y": [1,2,3]}).hvplot()

pn.Column(
    duration, big_load, big_plot
).servable()
```

## Basic App with `pn.state.onload`

This is provides a much better user experience. But the developer experience is not great. Its a callback and the callback might become complicated if there are many `.servables` you want to update. This is so hard to explain to the *new* or *inexperienced* users I know.

It seems like a lot of boilerplate code that you always must add your self if you want to provide a nice user experience.

https://user-images.githubusercontent.com/42288570/192106000-8f1d13b6-0310-4d80-8d27-cfdc35a63353.mp4

```python
import time
start = time.time()

import pandas as pd
import panel as pn
import hvplot.pandas

pn.extension(sizing_mode="stretch_width", template="fast")

def duration():
    return time.time()-start

def big_load():
    time.sleep(2)
    return pd.DataFrame({"x": [1,2,3], "y": [1,2,3]})

def big_plot():
    time.sleep(2)
    return pd.DataFrame({"x": [1,2,3], "y": [1,2,3]}).hvplot()

layout = pn.Column(
    pn.indicators.LoadingSpinner(value=True, width=200, height=200)
)

def on_load():
    layout[:]=[big_load, big_plot, duration]
pn.state.onload(on_load)

layout.servable()
```

**Comment by MarcSkovMadsen** [comment]
## Basic App with `defer_load`

With just a `defer_load` parameter added to `pn.panel` we can make it much, much easier to provide a nice user experience. If we could even set the default value of `defer_load` in `pn.extension` it would be amazing.

https://user-images.githubusercontent.com/42288570/192105091-5514931c-5ca4-4075-8cd8-232f64cf1346.mp4

```python
import param
import panel as pn

class DeferLoad(param.Parameterized):
    loaded = param.Boolean()

    def __init__(self, **params):
        super().__init__(**params)

        pn.state.onload(self.onload)

    def onload(self):
        self.loaded=True

    def panel(self, object, defer_load=False):
        if not defer_load:
            raise NotImplementedError()

        @param.depends(self.param.loaded)
        def _panel(loaded):    
            if not loaded:
                if defer_load is True:
                    return pn.indicators.LoadingSpinner(value=True, width=100, height=100)
                else:
                    return defer_load
            else:
                return pn.panel(object)
        return _panel

defer_load = DeferLoad()
panel = defer_load.panel

# ******* General Functionality Above **********

import time
start = time.time()

import pandas as pd
import panel as pn
import hvplot.pandas

pn.extension(sizing_mode="stretch_width", template="fast")

def duration():
    return time.time()-start

def big_load():
    time.sleep(2)
    return pd.DataFrame({"x": [1,2,3], "y": [1,2,3]})

def big_plot():
    time.sleep(2)
    return pd.DataFrame({"x": [1,2,3], "y": [1,2,3]}).hvplot()

pn.Column(
    panel(big_load, defer_load=True),
    panel(big_plot, defer_load=pn.indicators.Progress(active=True, height=25)),
    panel(duration, defer_load="Loading ..."),
).servable()
```

**Comment by MarcSkovMadsen** [comment]
## Additional Considerations

Maybe `defer_load` could be combined with `loading_indicator`. Currently `loading_indicator` only shows a loading indicator when updating things after the initial load. But maybe it could also defer the loading of the object or function and shows a loading indicator.

**Comment by MarcSkovMadsen** [comment]
## Basic app with Streamlit

Streamlit provides a `st.spinner` context manager to make it easy

https://user-images.githubusercontent.com/42288570/192105823-53e5da57-44be-4d65-be6d-699317bf75c8.mp4

```python
import streamlit as st
import time
import pandas as pd
import hvplot.pandas
import holoviews as hv

start = time.time()

def duration():
    return time.time()-start

def big_load():
    time.sleep(2)
    return pd.DataFrame({"x": [1,2,3], "y": [1,2,3]})

def big_plot():
    time.sleep(2)
    return hv.render(pd.DataFrame({"x": [1,2,3], "y": [1,2,3]}).hvplot())

with st.spinner('Wait for it...'):
    st.write(big_load())
with st.spinner('Wait for it...'):
    st.write(big_plot())
with st.spinner('Wait for it...'):
    st.write(duration())
```

**Comment by MarcSkovMadsen** [comment]
A first thing would be for @philippjfr to acknowledge whether this is something that we should add. And if yes which solution he would be prefer.

**Comment by MarcSkovMadsen** [comment]
On a second thought ‘defer_load’ could also just be called ‘on_load’.

**Comment by philippjfr** [comment]
So https://github.com/holoviz/panel/pull/3679 would probably address this problem for 90%+ of cases. The problem with it is that the limitations are subtle and hard to communicate and we can't enable it by default.

**Comment by MarcSkovMadsen** [comment]
After sleeping on it I think `defer_load`/ `onload` argument to `pn.panel`, `pn.config`, `pn.extension` is an essential and missing piece of functionality in the Panel API. Would you be willing to look positively at a PR @philippjfr. 

I think https://github.com/holoviz/panel/pull/3679 might address some of the issues. But it will not give you the same kind of simplicity and level of control as what is proposed here.

**Comment by philippjfr** [comment]
I just don't really understand what the proposal is. The problem isn't that components somehow take a long time to transfer but that the script or notebook defining all the components has to be executed first and defer_load will make no difference there. Serving up a pre-cached page is currently the only way to avoid that.

The only other thing I can imagine that would allow us to put something on the screen quickly is streaming the page in bit by bit, but I haven't done much reading about that.

**Comment by philippjfr** [comment]
Sorry I missed all your messages in the middle. Have a look at my PR, we can also amend it with a configurable placeholder object. A completely automatic solution would still be nice but I agree this is an important addition.
