### ISSUE TITLE
FastTemplate not working on current master branch

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3883]
Running the example in https://github.com/holoviz/panel/pull/3882 on the current `master` branch, I noticed the *theme toggle button* is not white. Looking at the browser console I can see it has problems loading a js file.

![image](https://user-images.githubusercontent.com/42288570/192143889-f3ee3ad8-9f73-4045-b199-a859b2f62adb.png)

```bash
       Uncaught TypeError: Failed to resolve module specifier "static/extensions/panel/bundled/js/@microsoft/fast-colors@5.3.1/dist/index.js". Relative references must start with either "/", "./", or "../".
```

**Comment by philippjfr** [comment]
Had the same issue but was pretty sure this was fixed. Will take a look later.

**Comment by philippjfr** [comment]
Turned out to be a tiny little typo, will push up a fix shortly.
