### ISSUE TITLE
DeprecationWarning: make_current is deprecated

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#3885]
Seeing a lot of these warnings in the test suite.

``` python
  /usr/share/miniconda3/envs/test-environment/lib/python3.9/site-packages/tornado/ioloop.py:350: DeprecationWarning: make_current is deprecated; start the event loop first
    self.make_current()
```

**Comment by philippjfr** [comment]
This isn't our fault, Tornado added the deprecation but did not remove all calls to `make_current` from their codebase:

https://github.com/tornadoweb/tornado/blob/6cfa37ab4e03a7c82bfd2869ce528a452bd521e5/tornado/ioloop.py#L350

**Comment by Hoxbro** [comment]
What about this one?

https://github.com/holoviz/panel/blob/4bcf0116db0327bea0a6ec79ecf0f0c46ec4963e/panel/io/server.py#L875

**Comment by philippjfr** [comment]
Just spotted that too. Thanks!
