### ISSUE TITLE
Tabulator resetting to first page on edits

### ISSUE THREAD

**Issue by xnsde** [holoviz/panel#3888]
#### ALL software version info
Windows + Linux, Python 3.9
Panel 0.13.1
pandas 1.5.0
bokeh 2.4.3

#### Description of expected behavior and the observed behavior
Paginated Tabulator resets to page 1 on edit of columns on subsequent pages.
1) Load example with `panel serve app.py`
2) Visit page
3) Click next (or last) to go to another page
4) Edit any column
5) Hit Enter to "save" (or click outside the field)

Hitting Tab button lets you (mostly) move to the next field and hence edit multiple in a row.

I would expect it to stay on the current page allowing the user to properly edit multiple columns.

I verified that this behavior did not occur in panel 0.12.x. I haven't yet compared if it's a regression in 0.13 or 0.13.1

#### Complete, minimal, self-contained example code that reproduces the issue

```python3
import pandas as pd
import panel as pn

pn.extension("tabulator")

df = pd._testing.makeDataFrame()

tab = pn.widgets.Tabulator(
    df,
    pagination="local",
    page_size=5,
)

if __name__.startswith("bokeh_app"):
    tab.servable()

```

**Comment by philippjfr** [comment]
Thanks for reporting this. This issue has already been fixed on master so look out for the 0.14 release later this week.
