### ISSUE TITLE
Panel REST API can not deploy

### ISSUE THREAD

**Issue by CongTang** [holoviz/panel#3899]
Hi
I am trying to run the rest API example which i find from:
https://gist.github.com/MarcSkovMadsen/5ccea41b801a8b9f3c555a5b2968586d

when I run `panel serve app.py --rest-provider tranquilizer --autoreload`  i get a error of:
cannot import name 'parse_rule' from 'werkzeug.routing' 

So I solved it by installing pip install Werkzeug==2.1.2 

But it turns out to:
ERROR: __init__() got an unexpected keyword argument 'unbound_message'

And here is my env:
Werkzeug==2.1.2
tranquilizer==0.8.0
panel==0.13.1

Is there my environment issue or i didn't run the example properly
Do we have any ideas there? Any comments while being grateful

Kind regards
Victor

**Comment by CongTang** [comment]
Bug figure by downgrading flask and Werkzeug to 2.1.2

**Comment by philippjfr** [comment]
We cannot control upstream issues (with Tranquilizer) so this isn't a bug. The requirement should be documented though.
