### ISSUE TITLE
_repr_mimebundle_ throwing error when used in VSCode

### ISSUE THREAD

**Issue by sriramvenkateshan** [holoviz/panel#3901]
When using panel in VSCode notebook with interactive window rendering the viewable, the _repr_mimebundle_ function gets called by formatter. 
The widget._repr_mimebundle_(include, exclude) invocation on the base ipywidget.Widget object then raises a signature mismatch exception 

Code
`import panel as pn;
pn.extension();
pn.Column("# Hello Panel World")`

Output
![image](https://user-images.githubusercontent.com/17196617/192867933-2ce83669-b579-462f-ad8a-cf0a2fe9e437.png)

If I change the line panel/viewable.py:612 to use no arguments to _repr_mimebundle_, the function works just fine.

**Comment by philippjfr** [comment]
Would you like to submit a PR, otherwise I'll make the fix tomorrow and include it in the 0.14.0rc3 build.

**Comment by Hoxbro** [comment]
This has already been fixed in #3765

**Comment by philippjfr** [comment]
Thanks @Hoxbro :)

**Comment by sriramvenkateshan** [comment]
Thanks guys. Will wait for the next build! Cheers!

**Comment by philippjfr** [comment]
If you could try 0.14.0rc2 today that would actually be very helpful. You can get it with `pip install panel==0.14.0rc2` or `conda install -c pyviz/label/dev panel==0.14.0rc2`.
