### ISSUE TITLE
Improve loading by showing progress

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3907]
I'm trying out `panel convert..`. And the loading time takes time. Its nice with the spinner but it would be even nicer with some kind of indication of steps.

The new documentation with "run" buttons on the cells shows this so nicely. It changes status text every time a new package is loaded. I watch that and don't think so much about the loading time. The same would be really nice here.

https://user-images.githubusercontent.com/42288570/193083662-18234423-d9cf-4aa6-a0aa-d30e19b77bc9.mp4

**Comment by philippjfr** [comment]
Accidentally pushed this straight to master. Will be available in 0.14.0rc3.
