### ISSUE TITLE
Expose Markdown syntax highlighting

### ISSUE THREAD

**Issue by jsignell** [holoviz/panel#391]
There are markdown syntax highlighting extensions, https://python-markdown.github.io/extensions/code_hilite/ that would be nice to expose in `pn.pane.Markdown` so code highlighting could easily be enabled by a user.

Originally came up in https://github.com/intake/intake/pull/325

**Comment by philippjfr** [comment]
I think instead of specifically enabling and depending on syntax high-lighting it might be nice to simply expose the list of markdown extensions so a user can use whatever extensions they desire.

**Comment by MarcSkovMadsen** [comment]
I was looking for this one. In order to reduce the friction of using Panel it would be so nice that fenced code blocks where syntax highlighted.

Take for example Streamlit. It just works out of the box. I've now been spending 2 hours on trying to find out how to get fenced code blocks markdown working in Panel.

- I does not work with highlite.js. I think it's because the code is transfered over a web socket and does not trigger highlite.js?
- I think the alternative is to use markdown.markdown and then include a css file.

Panel is very, very powerfull. But there is a lot of friction to using it.

But thanks for all the good work that has already been done.

**Comment by MarcSkovMadsen** [comment]
A minimum example is

```python
import panel as pn

code = """
```python
def add(a,b):
    return a+b
```
"""

app = pn.pane.Markdown(code)
app.servable()
```
and there is no syntax highliting

![image](https://user-images.githubusercontent.com/42288570/69902805-f3d17e80-1391-11ea-9b8a-952cde0e829b.png)

**Comment by MarcSkovMadsen** [comment]
And now i have code highlighting

![image](https://user-images.githubusercontent.com/42288570/69903086-7f004380-1395-11ea-9f04-201c78bb0f37.png)

```python
import panel as pn
import markdown

css = """
.codehilite .hll { background-color: #ffffcc }
.codehilite  { background: #f8f8f8; }
.codehilite .c { color: #408080; font-style: italic } /* Comment */
.codehilite .err { border: 1px solid #FF0000 } /* Error */
.codehilite .k { color: #008000; font-weight: bold } /* Keyword */
.codehilite .o { color: #666666 } /* Operator */
.codehilite .ch { color: #408080; font-style: italic } /* Comment.Hashbang */
.codehilite .cm { color: #408080; font-style: italic } /* Comment.Multiline */
.codehilite .cp { color: #BC7A00 } /* Comment.Preproc */
.codehilite .cpf { color: #408080; font-style: italic } /* Comment.PreprocFile */
.codehilite .c1 { color: #408080; font-style: italic } /* Comment.Single */
.codehilite .cs { color: #408080; font-style: italic } /* Comment.Special */
.codehilite .gd { color: #A00000 } /* Generic.Deleted */
.codehilite .ge { font-style: italic } /* Generic.Emph */
.codehilite .gr { color: #FF0000 } /* Generic.Error */
.codehilite .gh { color: #000080; font-weight: bold } /* Generic.Heading */
.codehilite .gi { color: #00A000 } /* Generic.Inserted */
.codehilite .go { color: #888888 } /* Generic.Output */
.codehilite .gp { color: #000080; font-weight: bold } /* Generic.Prompt */
.codehilite .gs { font-weight: bold } /* Generic.Strong */
.codehilite .gu { color: #800080; font-weight: bold } /* Generic.Subheading */
.codehilite .gt { color: #0044DD } /* Generic.Traceback */
.codehilite .kc { color: #008000; font-weight: bold } /* Keyword.Constant */
.codehilite .kd { color: #008000; font-weight: bold } /* Keyword.Declaration */
.codehilite .kn { color: #008000; font-weight: bold } /* Keyword.Namespace */
.codehilite .kp { color: #008000 } /* Keyword.Pseudo */
.codehilite .kr { color: #008000; font-weight: bold } /* Keyword.Reserved */
.codehilite .kt { color: #B00040 } /* Keyword.Type */
.codehilite .m { color: #666666 } /* Literal.Number */
.codehilite .s { color: #BA2121 } /* Literal.String */
.codehilite .na { color: #7D9029 } /* Name.Attribute */
.codehilite .nb { color: #008000 } /* Name.Builtin */
.codehilite .nc { color: #0000FF; font-weight: bold } /* Name.Class */
.codehilite .no { color: #880000 } /* Name.Constant */
.codehilite .nd { color: #AA22FF } /* Name.Decorator */
.codehilite .ni { color: #999999; font-weight: bold } /* Name.Entity */
.codehilite .ne { color: #D2413A; font-weight: bold } /* Name.Exception */
.codehilite .nf { color: #0000FF } /* Name.Function */
.codehilite .nl { color: #A0A000 } /* Name.Label */
.codehilite .nn { color: #0000FF; font-weight: bold } /* Name.Namespace */
.codehilite .nt { color: #008000; font-weight: bold } /* Name.Tag */
.codehilite .nv { color: #19177C } /* Name.Variable */
.codehilite .ow { color: #AA22FF; font-weight: bold } /* Operator.Word */
.codehilite .w { color: #bbbbbb } /* Text.Whitespace */
.codehilite .mb { color: #666666 } /* Literal.Number.Bin */
.codehilite .mf { color: #666666 } /* Literal.Number.Float */
.codehilite .mh { color: #666666 } /* Literal.Number.Hex */
.codehilite .mi { color: #666666 } /* Literal.Number.Integer */
.codehilite .mo { color: #666666 } /* Literal.Number.Oct */
.codehilite .sa { color: #BA2121 } /* Literal.String.Affix */
.codehilite .sb { color: #BA2121 } /* Literal.String.Backtick */
.codehilite .sc { color: #BA2121 } /* Literal.String.Char */
.codehilite .dl { color: #BA2121 } /* Literal.String.Delimiter */
.codehilite .sd { color: #BA2121; font-style: italic } /* Literal.String.Doc */
.codehilite .s2 { color: #BA2121 } /* Literal.String.Double */
.codehilite .se { color: #BB6622; font-weight: bold } /* Literal.String.Escape */
.codehilite .sh { color: #BA2121 } /* Literal.String.Heredoc */
.codehilite .si { color: #BB6688; font-weight: bold } /* Literal.String.Interpol */
.codehilite .sx { color: #008000 } /* Literal.String.Other */
.codehilite .sr { color: #BB6688 } /* Literal.String.Regex */
.codehilite .s1 { color: #BA2121 } /* Literal.String.Single */
.codehilite .ss { color: #19177C } /* Literal.String.Symbol */
.codehilite .bp { color: #008000 } /* Name.Builtin.Pseudo */
.codehilite .fm { color: #0000FF } /* Name.Function.Magic */
.codehilite .vc { color: #19177C } /* Name.Variable.Class */
.codehilite .vg { color: #19177C } /* Name.Variable.Global */
.codehilite .vi { color: #19177C } /* Name.Variable.Instance */
.codehilite .vm { color: #19177C } /* Name.Variable.Magic */
.codehilite .il { color: #666666 } /* Literal.Number.Integer.Long */
"""

pn.config.raw_css.append(css)

code = """
``python
def add(a,b):
    return a+b
```
""

html = markdown.markdown(code, extensions=["fenced_code", "codehilite"])
app = pn.pane.HTML(html)
app.servable()
```

**Comment by MarcSkovMadsen** [comment]
And if implemented it would be so, so nice to have it in a box with easy copy-paste

![image](https://user-images.githubusercontent.com/42288570/69903107-c555a280-1395-11ea-9dbc-bd126d81d7dc.png)

like found here

https://squidfunk.github.io/mkdocs-material/extensions/codehilite/

**Comment by MarcSkovMadsen** [comment]
For now if anybody needs it a nice Code class is

```python
import panel as pn
import markdown


class Code(pn.pane.HTML):
    """A HTML code block"""

    def __init__(
        self, code: str = "", language: str = "python", sizing_mode="stretch_width", *args, **kwargs
    ):
        """A HTML code block"""
        code_markdown = f"""
``{language}
{code}
``
"""
        code_html = markdown.markdown(code_markdown, extensions=["fenced_code", "codehilite"])
        super().__init__(code_html, sizing_mode=sizing_mode)
```

(remember to replace `` with three `)

**Comment by MarcSkovMadsen** [comment]
I can confirm that this works in the latest release candidate for v0.8

![image](https://user-images.githubusercontent.com/42288570/73419432-696cb300-431f-11ea-9067-35f678d0c691.png)

**Comment by CmpCtrl** [comment]
I dont seem to be able to make this work in v0.13.1. Any tips on what i am missing?

Note: Only using `` to avoid breaking the code section in github.

```python
"""markdown emphasis bug"""
import panel as pn


def main():
    """test"""
    mkdn = """
# Test

would result in $${(100+10)*2=220}$$ **NOT** $${100+10*2=120}$$ like you would expect

``python
def test():
    this=False
``
``json
{
  "selected_sigs": ["Ambient Pressure", "CAN Bus 1 Diagnostic"],
  "fits": {
    "Engine.Efficiency.Value": {
      "f_orig": 0.07,
      "f_smooth": [0.11, 0.16]
      }
    }
}
``


    """

    col = pn.Column(pn.pane.Markdown(mkdn, extensions=["fenced_code", "codehilite"]))
    col.servable()

    return col


pn.serve(main)
```
![image](https://user-images.githubusercontent.com/90776324/187268782-02f19245-b387-4518-8fd3-c0463e404a8d.png)

**Comment by philippjfr** [comment]
Syntax highlighting is enabled with triple backticks.

**Comment by CmpCtrl** [comment]
Copy that. I showed it above with 2 so that github would render it better. like @MarcSkovMadsen was doing above. 

unedited doesnt render right here...

```python
"""markdown emphasis bug"""
import panel as pn


def main():
    """test"""
    mkdn = """
# Test

would result in $${(100+10)*2=220}$$ **NOT** $${100+10*2=120}$$ like you would expect

```python
def test():
    this=False
```
```json
{
  "selected_sigs": ["Ambient Pressure", "CAN Bus 1 Diagnostic"],
  "fits": {
    "Engine.Efficiency.Value": {
      "f_orig": 0.07,
      "f_smooth": [0.11, 0.16]
      }
    }
}
```


    """

    col = pn.Column(pn.pane.Markdown(mkdn))
    col.servable()

    return col


pn.serve(main)
```

**Comment by CmpCtrl** [comment]
@philippjfr Any tips on this? As best i can tell the codehilite js isn't being included or isn't being run. The pre and code tags seem to be appropriate

![image](https://user-images.githubusercontent.com/90776324/187681209-775b0c9e-789e-4df9-b65a-03ca2a128323.png)

**Comment by philippjfr** [comment]
Very strange, here's what I see running your example:

<img width="621" alt="Screen Shot 2022-08-31 at 14 48 37" src="https://user-images.githubusercontent.com/1550771/187681979-39e677a5-b40f-439c-9180-8bc6883b43b5.png">

**Comment by CmpCtrl** [comment]
Interesting. I tried making a new directory with a new venv and a fresh install of Panel. Still get the same result. I checked in both chrome and edge. Am i missing some optional package? 


```
Python 3.10.2

Package            Version
------------------ ---------
bleach             5.0.1    
bokeh              2.4.3
certifi            2022.6.15
charset-normalizer 2.1.1
colorama           0.4.5
idna               3.3
Jinja2             3.1.2
Markdown           3.4.1
MarkupSafe         2.1.1
numpy              1.23.2
packaging          21.3
panel              0.13.1
param              1.12.2
Pillow             9.2.0
pip                21.2.4
pyct               0.4.8
pyparsing          3.0.9
pyviz-comms        2.2.1
PyYAML             6.0
requests           2.28.1
setuptools         58.1.0
six                1.16.0
tornado            6.2
tqdm               4.64.0
typing_extensions  4.3.0
urllib3            1.26.12
webencodings       0.5.1
```

**Comment by philippjfr** [comment]
@Hoxbro could you try to reproduce?

**Comment by Hoxbro** [comment]
@philippjfr I see the same as you.
![image](https://user-images.githubusercontent.com/19758978/187691786-fb0a5d8b-fab2-4950-8ed0-bc1d3472854f.png)

@CmpCtrl What OS are you running? 

Can you try to open a private window and see if still happens? And do you see any errors in the console?

**Comment by CmpCtrl** [comment]
I'm running windows 10 21H2. I've been testing in guest mode, but also tried a private window and MS Edge. all with the same result. 

I get a 404 error for the favicon, but didn't suspect that was related.
![image](https://user-images.githubusercontent.com/90776324/187693148-3f66fc12-d872-40c9-9d0a-85d53e6816d1.png)

**Comment by Hoxbro** [comment]
I get the no color in a clean environment. 

![image](https://user-images.githubusercontent.com/19758978/187700364-5dce359b-8ee0-4d9e-9794-713da18fd45e.png)

I get the color back again if I install `jupyterlab>3`, so try to install that... No matter what, make a new issue describing this problem. 
![image](https://user-images.githubusercontent.com/19758978/187702853-a997dda8-bf7a-403f-b113-b35704c238f9.png)

**Comment by CmpCtrl** [comment]
Thanks for the tip. Created issue #3799
