### ISSUE TITLE
Failed to load resource: favicon

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3910]
When running a `panel convert` app I see a 404 in the console.

![image](https://user-images.githubusercontent.com/42288570/193092970-3e68cc5a-9ebf-42b6-8564-2c1fc8600633.png)

```bash
Failed to load resource: the server responded with a status of 404 ()
```

It cannot find [https://panel.holoviz.org/_static/icons/favicon.ico](https://panel.holoviz.org/_static/icons/favicon.ico).

**Comment by philippjfr** [comment]
That'll get fixed when the new docs are uploaded.
