### ISSUE TITLE
IntSlider() throws exception '_repr_mimebundle_() takes 1 positional argument but 3 were given'

### ISSUE THREAD

**Issue by Waqar06** [holoviz/panel#3914]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
Python 3.8
OS windows
browser chorme 

#### Description of expected behavior and the observed behavior
IntSlider() throws exception '_repr_mimebundle_() takes 1 positional argument but 3 were given' 

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
int_slider = pn.widgets.IntSlider(name='Integer Slider', start=0, end=8, step=2, value=4)

int_slider
```

#### Stack traceback and/or browser JavaScript console output
_repr_mimebundle_() takes 1 positional argument but 3 were given
IntSlider(end=8, name='Integer Slider', step=2, value=4)

**Comment by Hoxbro** [comment]
I think this is already fixed and will work in the upcoming release.

Can you verify it by trying it out by: `pip install panel==0.14.0rc2` or `conda install -c pyviz/label/dev panel==0.14.0rc2`?

**Comment by debroize** [comment]
> I think this is already fixed and will work in the upcoming release.
> 
> Can you verify it by trying it out by: `pip install panel==0.14.0rc2` or `conda install -c pyviz/label/dev panel==0.14.0rc2`?

Had the same issue, this answer fixed it. Thanks!

**Comment by Hoxbro** [comment]
Panel has been released since my comment above. So if it is not what you already have done, you should be able to install `panel=0.14.1`.
