### ISSUE TITLE
Panel slows down with ipywidget

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#3915]
#### ALL software version info
panel master, ipywidgets 7.6.x

#### Description of expected behavior and the observed behavior
Panel is extremely slow both in lab and notebook with ipywidgets. The code below takes more than 10 seconds to render completely. Moreover in the lab, it seems to render asynchronously causing a visible delay in rendering.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import time
st = time.time()
x = pn.Column(

    *[
        pn.Row(
            *[
                
                    pn.Row(w.HTML("asdasdasdas"), pn.pane.HTML("qweqweqweqw"))
                
            ]*2
        )
        for i in range(50)
    ]
)
x
```

**Comment by philippjfr** [comment]
Seems like we perform a layout invalidation after each component is rendered which seems excessive. Will think about a fix but this should also get resolved once we upgrade to the new layout engine in Bokeh 3.0.

**Comment by govinda18** [comment]
Thanks for the quick fix @philippjfr 

I had a query though, is it possible to avoid the dependency on ipywidgets-bokeh for panel or is there a fundamental issue there? I would be willing to spend some efforts here and raise a pr as it feels like except for the part related to kernel, most of the code is redundant. For example, the fix you made here probably needs to be ported there as well. Also, panel ofcourse is much more actively maintained.

**Comment by philippjfr** [comment]
>I had a query though, is it possible to avoid the dependency on ipywidgets-bokeh 

No chance whatsoever. In a JupyterLab and classic notebook environment we can simply piggyback on the widget manager that is already present but when we're running a Bokeh/Panel server we need to provide our own widget manager, which is what ipywidgets-bokeh does.

**Comment by govinda18** [comment]
> No chance whatsoever. In a JupyterLab and classic notebook environment we can simply piggyback on the widget manager that is already present but when we're running a Bokeh/Panel server we need to provide our own widget manager, which is what ipywidgets-bokeh does.

I see. I will still probably want to avoid the redundancy in the code as any fix at either of the places needs to be patched at the other one too. Will think a bit more and see if I can find something.
