### ISSUE TITLE
panel convert example not working: ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3919]
I've followed in the [Example](https://github.com/holoviz/panel/blob/master/doc/user_guide/Running_in_Webassembly.md#example) on the master branch

![image](https://user-images.githubusercontent.com/42288570/193385652-cb77f060-d075-44e6-81e9-427efd2b3960.png)

**Comment by MarcSkovMadsen** [comment]
sklearn is actually not found either

![image](https://user-images.githubusercontent.com/42288570/193392532-0d7efa75-3d03-46ac-a907-866be330d179.png)

**Comment by MarcSkovMadsen** [comment]
Actually xgboost is not found either

![image](https://user-images.githubusercontent.com/42288570/193392603-c7fdc575-9b27-4c2c-abe1-41ca8fc4ff4b.png)

**Comment by MarcSkovMadsen** [comment]
Actually the example does not work at all

![image](https://user-images.githubusercontent.com/42288570/193392666-d09d1302-f113-472f-baac-21130a860c69.png)


```python
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

import panel as pn

pn.extension(sizing_mode="stretch_width", template="fast")
pn.state.template.param.update(site="Panel in the Browser", title="XGBoost Example")

iris = load_iris()

iris_df = load_iris(as_frame=True)

trees = pn.widgets.IntSlider(start=2, end=30, name="Number of trees")

def pipeline(trees):
    model = XGBClassifier(max_depth=2, n_estimators=trees)
    model.fit(iris.data, iris.target)
    accuracy = round(accuracy_score(iris.target, model.predict(iris.data)) * 100, 1)
    return pn.indicators.Number(
        name="Test score",
        value=accuracy,
        format="{value}%",
        colors=[(97.5, "red"), (99.0, "orange"), (100, "green")],
    )

pn.Column(
    "Simple example of training an XGBoost classification model on the small Iris dataset.",
    iris_df.data.head(),
    "Move the slider below to change the number of training rounds for the XGBoost classifier. The training accuracy score will adjust accordingly.",
    trees,
    pn.bind(pipeline, trees),
).servable()
```

```bash
panel convert script.py --to pyodide-worker --out pyodide --requirements pandas scikit-learn xgboost
```

**Comment by philippjfr** [comment]
Everything except pandas is installed correctly for me. I'll work something out to allow it to auto-detect the pandas requirement for that example and will then write a section on when `--requirements` is needed and not needed.
