### ISSUE TITLE
pn.panel({}) raises Uncaught (in promise) 

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3921]
I'm on the current master branch of panel

```python
import panel as pn

pn.panel({}).servable()
```

```bash
Uncaught (in promise) {message: 'Could not determine data format for {}, with JS typeof object'}
```

![image](https://user-images.githubusercontent.com/42288570/193393909-57d429d8-b78e-4c9c-b441-61f68bcd1321.png)

**Comment by philippjfr** [comment]
I don't follow what you're doing here at all.

**Comment by philippjfr** [comment]
Okay, I see. Seems the Perspective pane has precedence when you pass in a dictionary.

**Comment by MarcSkovMadsen** [comment]
It might not seem like the app a user would make. But `{}` could be the result of some transformation as in my case. Instead of me having to add error handling, its better that Panel removes that friction.

**Comment by philippjfr** [comment]
Yes, the JSON pane should have precedence here.
