### ISSUE TITLE
convert_apps creates app with error

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3924]
## Issue 1

I'm on the current master branch

`script.py`

```python
import panel as pn
pn.panel("Hello World").servable()
```

`script2.py`
```
from panel.io.convert import convert_apps

convert_apps(apps=["script.py"])
```

```bash
python 'script2.py'
python3 -m http.server
```

![image](https://user-images.githubusercontent.com/42288570/193408010-c372c902-a29f-4d8f-87e5-c297c301e192.png)

```bash
Uncaught SyntaxError: missing ) after argument list (at sharing?config=eyJhcHBzIjogeyJzY3JpcHQucHkiOiAiXG5pbXBvcnQgcGFuZWwgYXMgcG5cbnBuLnBhbmVsKFwiSGVsbG8gV29ybGRcIikuc2VydmFibGUoKVxuIn19:38:3)
```

I believe its missing a `)` here

![image](https://user-images.githubusercontent.com/42288570/193408120-de6d32ed-c54b-475a-b955-0df0301df76a.png)

**Comment by MarcSkovMadsen** [comment]
If I add the missing `)` I get another error because `serviceWorker.js` is not created by `convertApps`

![image](https://user-images.githubusercontent.com/42288570/193408359-b4818cc1-04bf-4f9b-8f71-29d0fd6452ef.png)

![image](https://user-images.githubusercontent.com/42288570/193408373-48fd9082-bba9-4355-ab5d-0833a658de9b.png)

**Comment by MarcSkovMadsen** [comment]
If I convert using `convert_apps(apps=["script.py"], build_index=False, build_pwa=False)` it bypasses the above errors but I am left with the error in #3921

![image](https://user-images.githubusercontent.com/42288570/193408699-1ee2a740-399c-4017-9886-3b241954c7c0.png)

**Comment by MarcSkovMadsen** [comment]
This does not solve the entire issue unfortunately. I'm still left with the TypeError: (intermediate value) is not iterable.

After inspection I can see the issue is that `await self.pyodide.runPythonAsync(code)` returns `undefined`.

**Comment by philippjfr** [comment]
Will set up some tests for the `pyodide-worker` runtime option.
