### ISSUE TITLE
App generated by convert_apps from a larger Panel app is not working.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3939]
I am working on creating a concept for easily sharing Panel apps live via `convert_apps`. In the beginning this worked out really, really well as `convert_apps` 1) worked 2) was super fast.

But at some point in time the converted app could no longer render - there was an error on the js side. The prerendering still looked fine. The app could still render if converted via `panel convert`.

To figure out the cause I compared the `.html` file generated by `convert_apps` and `panel convert`. I could see that the one generated by `convert_apps` contained traces of the `Ace` and a custom `ReactiveHTML` component. None of these where in the script I converted. But they where in the Panel app where I executed the `convert_apps` function by clicking a button.

My hypothesis is that this is the cause.

I tried to create a minimum reproducible example from scratch but could not. I hope to get back to to creating a minimum reproducible example later. But right now I want to focus on my app and I can execute `panel convert` via `subprocess.run`. It works but is much slower. So eventually if the Panel sharing app takes off I would need this fixed.

For now this is mostly for info.

-------

The app I was converting.

```python
import panel as pn

pn.panel("Hello World").servable()
```

**Comment by philippjfr** [comment]
Looking into it. Initially I had a ton of these issues because all the apps were converted in the same process but then I switched to using multiprocessing to run each conversion in a different process. But I think because these processes are forked from the main process they are still not fully isolated.

**Comment by MarcSkovMadsen** [comment]
Agree.

**Comment by MarcSkovMadsen** [comment]
Ahh. Now I changed to `convert_app` instead of `convert_apps`.

Is `convert_app` running in the same process?

**Comment by MarcSkovMadsen** [comment]
Problem solved for `convert_apps`. 

![image](https://user-images.githubusercontent.com/42288570/193608260-595befc6-e0d2-48db-9f69-c2189f92ed4b.png)

**Comment by MarcSkovMadsen** [comment]
Should I keep this issue open because `convert_app` has the issue @philippjfr ?

**Comment by MarcSkovMadsen** [comment]
And thanks for the effort. You have made so made big and small things here. I think the whole loading experience of Panel on Pyodide is amazing now.

This below video is speeded up twice. Its beautiful. I'm really enjoying the Panel experience. The `exception_handler` and the `notifications` work so great.

![panel-sharing-speedup](https://user-images.githubusercontent.com/42288570/193609852-b318c1a0-c769-4b99-9314-2c2c73aa95da.gif)

**Comment by MarcSkovMadsen** [comment]
I will close this for now.
