### ISSUE TITLE
NameError: name 'iris' is not defined in `panel convert` example

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3941]
I'm on the current master. When I run `panel convert...` the xgboost reference example I get

```bash
 File "/home/jovyan/repos/private/panel/apps/development/source/961e9c59-1bd4-4fad-a7b9-c6ef1df82ffb/app.py", line 16, in pipeline
    model.fit(iris.data, iris_df.target)
NameError: name 'iris' is not defined
```

You will need to add back `iris = load_iris()` to the example.

This is the key example when releasing Panel 0.14. Its the one that people will look up and try to run. Please test that it works when you change it @philippjfr. Otherwise you risk loosing so many potential new users.

**Comment by philippjfr** [comment]
Thanks! Need to make sure it's under test too.

**Comment by philippjfr** [comment]
Passing iris_df.data as opposed to iris.data works just fine though.

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/commit/a5973cd49f6d8ead16ef71fc2d739ade2e221e67
