### ISSUE TITLE
pn.pane.Str style options

### ISSUE THREAD

**Issue by kcpevey** [holoviz/panel#396]
The style options for panel String are not working properly. The following code:  
`pn.pane.Str('Visibility', style={'font-size': '13pt', 'color':'blue'})`
  
Works for the color attribute, but doesn't work for the font-size attribute. I believe @philippjfr saw the opposite effect - working font-size and not working color.  
  
Panel version 0.5.1

**Comment by philippjfr** [comment]
Appears to be working now. Not sure what changed.
