### ISSUE TITLE
invalid command name ".!canvas" 

### ISSUE THREAD

**Issue by aliabdelmoaty** [holoviz/panel#3972]
![pong_game py - pthon - Visual Studio Code 10_7_2022 3_50_25 PM](https://user-images.githubusercontent.com/68239507/194715515-8d305eac-b5df-4754-b717-3f8059032dff.png)
wind = turtle.Screen()
wind.title(" ping pong by Ali Abdelmoaty")  # 
wind.bgcolor("black")  # 
wind.setup(width=800, height=600)  # 
wind.tracer(0)  # stop update
#___________________________________________________

#madrab1
madrab1 = turtle.Turtle()
madrab1.speed(0)  # 
madrab1.shape("square")  #  
madrab1.color("white")  #  
madrab1.shapesize(stretch_wid=6, stretch_len=1)  #  
madrab1.penup()  # 
madrab1.goto(350, 0)  # 
#--------------------------------------------

#madrad2
madrab2 = turtle.Turtle()
madrab2.speed(0)  # 
madrab2.shape("square")  #  
madrab2.color("red")  #  
madrab2.shapesize(stretch_wid=6, stretch_len=1)  #   
madrab2.penup()  # 
madrab2.goto(-350, 0)
#----------------------------------

#ball
ball = turtle.Turtle()
ball.speed(0)  # 
ball.shape("circle")  #
ball.color("blue")  #  
ball.penup()  #
ball.goto(0, 0)
ball.dx = .1  #
ball.dy = .1
#-----------------------------------------------------

#functions

def madrab1_up():
    y = madrab1.ycor()  
    y += 20  # 
    madrab1.sety(y)  #
#-----------------------------------------------

def madrab1_down():
    x = madrab1.ycor()
    x -= 20
    madrab1.sety(x)

#--------------------------------------------------
def madrab2_up():
    z = madrab2.ycor()
    z += 20
    madrab2.sety(z)

#-----------------------------------------------------

def madrab2_down():
    q = madrab2.ycor()
    q -= 20
    madrab2.sety(q)

#--------------------------------------------------------
#

wind.listen()  # 

wind.onkeypress(madrab1_up, "w")
wind.onkeypress(madrab1_down, "s")

wind.onkeypress(madrab2_up, "Up")
wind.onkeypress(madrab2_down, "Down")

while True:
    wind.update()
    #

    ball.setx(ball.xcor() + ball.dx)
    # 
    ball.sety(ball.ycor() + ball.dy)
    #border check
    if ball.ycor() > 290:
        ball.sety(290)
        ball.dy *= -1

    if ball.ycor() < -290:
        ball.sety(-290)
        ball.dy *= -1

    if ball.xcor() > 390:
        ball.goto(0, 0)
        ball.dx *= -1

    if ball.xcor() < -390:
        ball.goto(0, 0)
        ball.dx *= -1

    #------------------------------------------------------

    if (ball.xcor() > 340 and ball.xcor() < 350) and (ball.ycor() < madrab2.ycor() + 40 and ball.ycor() > madrab2. ycor - 40):
        ball.setx(340)
        ball.dx *= -1

    if (ball.xcor() < -340 and ball.xcor() < 350) and (ball.ycor() < madrab1.ycor() + 40 and ball.ycor() > madrab1. ycor - 40):
        ball.setx(-340)
        ball.dx *= -1

**Comment by philippjfr** [comment]
@aliabdelmoaty Was this meant to be a Panel issue? I can't see any use of Panel in your code.

**Comment by aliabdelmoaty** [comment]
> Was this meant to be a Panel issue? I can't see any use of Panel in your code.

Sorry I'm new to GitHub and English not my language 

My problem is when I run the program, this problem appears in the picture

**Comment by jbednar** [comment]
Hope you are able to debug that code! However, that's not a topic for this repository, which is about the Panel library.
