### ISSUE TITLE
Exception handler does not work when threading is enabled

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#3974]
Panel 0.14.0

I was excited to use the new exception handler mechanism but noticed that it does not work when panel-managed threading is enabled. Take for instance the code used in the release blog post:

```python
import logging
import panel as pn

def exception_handler(ex):
    logging.error("Error", exc_info=ex)
    pn.state.notifications.error(f'{ex}')

pn.extension(nthreads=2, exception_handler=exception_handler, notifications=True, template="fast")

pn.state.template.param.update(site="Awesome Panel", title="Easy and powerful exception handling added for production apps")

button = pn.widgets.Button(name="Raise Exception").servable()

def raise_exception(_=None):
    raise ValueError(f"Something went wrong when clicking the button")

button.on_click(raise_exception)

slider = pn.widgets.IntSlider(value=0, start=0, end=5, name="Raise exception on 3").servable()

@pn.depends(value=slider, watch=True)
def _raise_exception_2(value):
    if value==3:
        raise ValueError("Some slider error")

```

The error is not intercepted and is raised as if there were no handler in place.

**Comment by philippjfr** [comment]
I see the mistake and can push a fix but even then it only works sometimes. The Python docs appear to be lying to me since the [add_done_callback](https://docs.python.org/3/library/concurrent.futures.html) is not always executed on the same thread as where I added it:

>Added callables are called in the order that they were added and are always called in a thread belonging to the process that added them.
