### ISSUE TITLE
Bad link in the homepage gallery

### ISSUE THREAD

**Issue by c-stephan** [holoviz/panel#3981]
On the Panel homepage several applications are shown as examples. 
The link for the 'Glacier' application is not correct and points to 'https://penguins-crossfilter.pyviz.demo.anaconda.com/', which leads to a 404 Error, instead of redirecting to 'https://glaciers.pyviz.demo.anaconda.com'. 

![grafik](https://user-images.githubusercontent.com/70373646/195027937-1e3a5f10-c7d6-4876-9955-31b574b8a697.png)

**Comment by Hoxbro** [comment]
Do you want to make a PR for this?
