### ISSUE TITLE
Panel embedding does not work properly with pn.widgets.Tabulator

### ISSUE THREAD

**Issue by Mounji-Salma** [holoviz/panel#3985]
#### ALL software version info
panel==0.14.0
python==3.8.8
bokeh==2.4.2

#### Description of expected behavior and the observed behavior
Embedding described [here](https://panel.holoviz.org/user_guide/Display_and_Export.html#embedding) does not work with pn.widgets.Tabulator. Please see the example below.

#### Complete, minimal, self-contained example code that reproduces the issue

```
slider = pn.widgets.IntSlider(start=0, end=4)

@pn.depends(slider.param.value)
def callback(value):
    pn.extension('tabulator')
    return pn.widgets.Tabulator(pd.DataFrame([value]))

col = pn.Column(slider, callback)
col.embed(max_opts=4)
```

After running the above script, when moving the Slider the output dose not change. 

#### Stack traceback and/or browser JavaScript console output
_None._
#### Screenshots or screencasts of the bug in action
Here is an example of slider being at value `4`, but showing the results for value `0` in the output:
![image](https://user-images.githubusercontent.com/74664742/195195118-68382c88-674a-4e84-b0ad-aaa6486e8825.png)

**Comment by Hoxbro** [comment]
It seems to work as expected for me. 

https://user-images.githubusercontent.com/19758978/195277603-d577d6eb-3861-4f88-84ca-771a1716c907.mp4

I notice that your example uses `col`, but your screenshot use `row` could this be the reason why you are not seeing anything?

**Comment by philippjfr** [comment]
Also cannot reproduce. Happy to reopen if it turns out to be an issue but for now I'll close.
