### ISSUE TITLE
pn.serve oauth does not work

### ISSUE THREAD

**Issue by t-houssian** [holoviz/panel#3995]
software version info
panel 0.14
python 3.10.6

Description of expected behavior and the observed behavior:

When using pn.serve I get the following error while trying to use oauth:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.10/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.10/site-packages/panel/auth.py", line 315, in get
    user = await self.get_authenticated_user(**params)
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.10/site-packages/panel/auth.py", line 129, in get_authenticated_user
    return await self._fetch_access_token(
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.10/site-packages/panel/auth.py", line 592, in _fetch_access_token
    raise ValueError('The client secret are undefined.')
ValueError: The client secret are undefined.
 
It appears the oauth_redirect_uri was not included in the get_server() (line 728 in panel/io/server.py) function param list.

By simply adding it:

```python
def get_server(
    panel: 'TViewableOrFunc' | Mapping[str, 'TViewableOrFunc'],
    port: int = 0,
    address: Optional[str] = None,
    websocket_origin: Optional[str | list[str]] = None,
    loop: Optional[IOLoop] = None,
    show: bool = False,
    start: bool = False,
    title: bool = None,
    verbose: bool = False,
    location: bool | Location = True,
    admin: bool = False,
    static_dirs: Mapping[str, str] = {},
    oauth_provider: Optional[str] = None,
    oauth_key: Optional[str] = None,
    oauth_secret: Optional[str] = None,
    oauth_redirect_uri: Optional[str] = None,
    oauth_extra_params: Mapping[str, str] = {},
    cookie_secret: Optional[str] = None,
    oauth_encryption_key: Optional[str] = None,
    session_history: Optional[int] = None,
    **kwargs
)
```

Then also adding both oauth_redirect_uri and oauth_secret to the configs:

```python
from ..config import config
    if oauth_provider:
        from ..auth import OAuthProvider
        config.oauth_provider = oauth_provider # type: ignore
        opts['auth_provider'] = OAuthProvider()
    if oauth_key:
        config.oauth_key = oauth_key # type: ignore
    if oauth_secret:
        config.oauth_secret = oauth_secret # type: ignore
    if oauth_redirect_uri:
        config.oauth_redirect_uri = oauth_redirect_uri # type: ignore
    if oauth_extra_params:
        config.oauth_extra_params = oauth_extra_params # type: ignore
    if cookie_secret:
        config.cookie_secret = cookie_secret # type: ignore
    opts['cookie_secret'] = config.cookie_secret
```

It seems to fix the problem and authentication works again.

Here is a reproducible example. You will have to use your own google web api credentials and add the correct redirect uri and your own encryption and cookie keys.

```python
import panel as pn

def abc():
    return pn.pane.JSON({'abc': 123})

def bcd():
    return pn.pane.JSON({'bcd': 123})

template = pn.template.FastListTemplate(
    main=abc()
).servable()

template2 = pn.template.FastListTemplate(
    main=bcd()
).servable()

APP_ROUTES = {
    "/": template,
    "/bcd": template2
}

pn.serve(
    APP_ROUTES,
    port=5010,
    allow_websocket_origin=["127.0.0.1:5010"],
    address="127.0.0.1",
    show=True,
    autoreload=True,
    oauth_provider="google",
    oauth_key="KEY",
    oauth_secret="SECRET",
    oauth_encryption_key="k",
    cookie_secret="c",
    oauth_redirect_uri="http://127.0.0.1:5010/bcd"
)
```

Before:
![Screenshot from 2022-10-13 13-36-01](https://user-images.githubusercontent.com/25035266/195679020-77df15f8-509a-46a3-a6e2-28abf4c6e91b.png)
![Screenshot from 2022-10-13 12-50-08](https://user-images.githubusercontent.com/25035266/195679084-edfbf53b-1bb0-4ef7-b826-04bc08ef662d.png)
![Screenshot from 2022-10-13 12-49-55](https://user-images.githubusercontent.com/25035266/195679047-81acbb0b-b826-4370-8cff-2164d790cc7d.png)

After:
![Screenshot from 2022-10-13 13-41-33](https://user-images.githubusercontent.com/25035266/195679815-22f845b5-cd40-4c7d-bbbb-c2df11af00ca.png)

I can open pull request with the changes if this is confirmed.

**Comment by philippjfr** [comment]
Thanks @t-houssian! I want to get a dev release out asap so I'm going to push this fix and your other fix up. You deserve all the credit here. Please always feel free to push up a PR since you already went through all the effort investigating these issues.

**Comment by t-houssian** [comment]
@philippjfr No problem! Glad to contribute!

**Comment by Khalilsqu** [comment]
I get the same error, The app is ready but cannot find a way to secure the app access.

![image](https://user-images.githubusercontent.com/22060413/198716989-8198068f-4ba6-4d5a-9d9e-eeb385fb9502.png).
