### ISSUE TITLE
Jupyter Panel Preview can no longer show the panel-chemistry extension on Binder

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3997]
After upgrading to Panel 0.14.0, the `panel-chemistry` extension no longer shows when using the Panel Jupyter Preview on Binder.

It works in the notebooks.

**It is my hypothesis that the new implementation of the Jupyter Panel Preview forgets to serve the assets of bokeh extensions?** Maybe only if the are installed via `pip install -e .`?

## Reproduce

1. Open https://mybinder.org/v2/gh/awesome-panel/panel-chemistry/feature/binder-working
2. Open the JSMEEditor.ipynb example notebook and verify it works
3. Open the Jupyter Panel Preview and verify it does not work.

![image](https://user-images.githubusercontent.com/42288570/195751265-da175f4f-9435-4165-90ca-c82439398fb5.png)

4. Find the link to the Panel application in shown in the preview iframe
5. Open the link
6. Open the *Network* tab in the browser.
7. Refresh the browser
8. See that the `panel_chemistry.js` is not found while the `panel.min.js` is

![image](https://user-images.githubusercontent.com/42288570/195751451-ccf01ae6-604c-4524-a6a6-537472d38b51.png)

```bash
https://hub.gke2.mybinder.org/user/awesome-panel-panel-chemistry-yjyfkah4/panel-preview/static/extensions/panel/panel.min.js?v=514f2a7b05a1ef2ad45a3b4321cf452aee6fe7b50d0be86fd33ffe9a1990db1d

https://hub.gke2.mybinder.org/user/awesome-panel-panel-chemistry-yjyfkah4/panel-preview/static/extensions/panel_chemistry/panel_chemistry.js?v=77e3b0df3cc2634331ad7f8f5afc2924308e4108dec5f2839a37662d082ac218
```

## Additional Context

You can find the example branch here https://github.com/awesome-panel/panel-chemistry/tree/feature/binder-working

**Comment by philippjfr** [comment]
Can't get that binder branch to build which makes this pretty difficult to debug.

**Comment by philippjfr** [comment]
Okay, figured it out. Need to communicate any changes to the `bokeh.embed.bundle.extension_dirs` dictionary back to the main process.

**Comment by MarcSkovMadsen** [comment]
Thanks. Unfortunately Binder is becoming more and more slow and instable.

**Comment by maximlt** [comment]
Yes, they lack 💰 and are badly affected by crypto miners.
