### ISSUE TITLE
Jupyter Panel Preview no longer working on my Jupyter Hub

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3998]
After upgrading to Panel 0.14.0 I try out running the `panel-chemistry` extension on my jupyter hub.

It works fine in the notebook. But the Jupyter Panel Preview raises a `ModuleNotFoundError:`. It used to be that they where using the same `base`kernel.

As a user I am stuck here and don't know what to do.

![image](https://user-images.githubusercontent.com/42288570/195752930-8bca443d-dc82-4955-94df-e84804c4f541.png)

![image](https://user-images.githubusercontent.com/42288570/195753188-17ff6b2f-ee3a-45fd-b204-8ef0a287be4c.png)

**You can see from the investigation below that the Jupyter Panel Preview does not work if I do a `pip install -e .` of `panel-chemistry`. But if I install the wheel it works.**

## Additional Context

If I manually `panel serve` the notebook in a terminal it works.

![image](https://user-images.githubusercontent.com/42288570/195753586-4f89405c-35e5-4223-80d3-7e8926419aae.png)

I've tried setting the `kernel` argument to `base`, `python3` and `panel_chemistry` but it does not change anything.

![image](https://user-images.githubusercontent.com/42288570/195755464-f186b386-0afd-4003-b443-aed56e649fc6.png)

If I create a simple notebook to show me which `__file__` is used for `panel` and `panel_chemistry` I get

![image](https://user-images.githubusercontent.com/42288570/195755960-478ff963-7315-4f78-bcbc-71fa87ed25b0.png)

If I install the package wheel, `pip install dist/panel_chemistry-0.0.14rc1-py3-none-any.whl ` instead of `pip install -e .` it works.

![image](https://user-images.githubusercontent.com/42288570/195756527-f06268d4-58c3-404a-aeb4-c7ddb89222f1.png)

If I go back do the editable install it no longer works again

![image](https://user-images.githubusercontent.com/42288570/195757294-f1037dc5-8d33-4d88-809c-42821c7f22b0.png)

**Comment by philippjfr** [comment]
The fact that it works in some situations but not others seems to indicate this a problem with environment management not with Panel. That said the preview should open the exact same kernel as the notebook running beside it so it's definitely odd this would happen. This is going to be extremely difficult to debug without having being able to reproduce.

**Comment by philippjfr** [comment]
Please report back if you are still seeing this.

**Comment by MarcSkovMadsen** [comment]
No issue now. Closing.
