### ISSUE TITLE
FileNotFoundError in Panel preview pane in JupyterHub (lab)

### ISSUE THREAD

**Issue by JoranDox** [holoviz/panel#4017]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
bokeh                         2.4.2
Cython                        0.29.32
ipykernel                     6.16.0
ipython                       8.5.0
jupyter-client                7.3.4
jupyter_core                  4.11.1
jupyter-server                1.21.0
jupyter-server-proxy          3.2.2
jupyterhub                    1.5.0
jupyterlab                    3.2.5
jupyterlab_server             2.16.0
notebook                      6.5.1
panel                         0.14.0
Python: 3.10.6
OS: running on k8s inside a docker image running a recent ubuntu
Browser: I'm running on brave, but doesn't seem to be relevant as nothing is blocked, just the wrong path

#### Description of expected behavior and the observed behavior

Expected: see some form of panel preview in a new jupyter lab tab
Observed: 500 internal server error

#### Complete, minimal, self-contained example code that reproduces the issue

Change (one or both? I'm mostly suspecting the serverapp.root_dir) of the following settings:
https://jupyterhub.readthedocs.io/en/stable/api/spawner.html#jupyterhub.spawner.Spawner.notebook_dir
https://jupyter-server.readthedocs.io/en/latest/other/full-config.html
```
c.Spawner.notebook_dir = "/home/persistent"
c.ServerApp.root_dir = "/home/persistent"
```

#### Stack traceback and/or browser JavaScript console output

```
HTTPServerRequest(protocol='https', host='redacted', method='GET', uri='/user/jorandox/panel-preview/render/notebooks/personal/panel.ipynb', version='HTTP/1.1', remote_ip='10.224.0.35')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/panel/io/jupyter_server_extension.py", line 337, in get
    with open(notebook_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/notebooks/personal/panel.ipynb'
```
which makes total sense since the notebook is at /home/persistent/notebooks/personal instead.

![image](https://user-images.githubusercontent.com/7152733/196146882-8c265fe5-2c11-442b-8a6d-d5d7ed65a274.png)

The issue here is probably that we've changed some defaults from jupyter, and the panel preview button is ignoring those.
I'm assuming adding some background variables like the full path of the notebook (instead of relative path, which I assume is what happened here) would work, or using the actual values for those changed settings instead of the defaults (but that may lead to other similar issues maybe?)

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/7152733/196149281-4d8c782b-bb4f-4640-9c77-065f1d6a017e.png)

**Comment by philippjfr** [comment]
Seems to be the `root_dir` that's confusing the extension. Looking at this now.
