### ISSUE TITLE
MultiSelect widget pop up box should render above everything

### ISSUE THREAD

**Issue by mhueser** [holoviz/panel#4024]
I observed that the MultiSelect's popup-box is sometimes hidden i.e. rendered below other
layout components. I think this is never correct, pop-up boxes for selecting 
elements should always render above other layout components,
except of course other popup-messages.

**Comment by mhueser** [comment]
This was observed on various browsers (Firefox, Safari) on
the latest versions on Panel/Tornado/Bokeh.

**Comment by mhueser** [comment]
It makes the MultiSelection Widget close to unusable, 
because I need to reserve space in the layout so the
popup-box has space to expand. Is there any quick fix possible
on the user side?

**Comment by maximlt** [comment]
Aren't you talking about the `MultiChoice` widget?

Could you also provide more information about your application. Do you use a template? If so which one? Or a custom one?

If so I'll just list for now some issues to that widget and what you're reporting:
- https://github.com/holoviz/panel/issues/3218
- https://github.com/holoviz/panel/issues/2979
- https://github.com/holoviz/panel/issues/2186

And a possibly related Bokeh PR https://github.com/bokeh/bokeh/pull/11388

**Comment by mhueser** [comment]
Yes sorry, I meant MultiChoice. I use a custom layout, with reasonably deep
nested column/rows layout. 

In the Holoviz discourse after discussing the problem, I noticed this is an issue of 
the widget WidgetBox, over whose boundaries the pop up of MultiChoice does not render 
correctly. The fix is to replace pn.WidgetBox by pn.Column and the problem will disappear.

**Comment by mattpap** [comment]
All of those issue related to z ordering should be fixed by now, some in bokeh 2.4 and the rest in 3.0.

**Comment by philippjfr** [comment]
Have confirmed these are fixed.
