### ISSUE TITLE
404: link to developer guide not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4030]
https://panel.holoviz.org/user_guide/Server_Deployment.html

![image](https://user-images.githubusercontent.com/42288570/196650314-6726ee07-5a3d-407a-bc55-f33a908c2ed3.png)

https://examples.pyviz.org/developer_guide.html

![image](https://user-images.githubusercontent.com/42288570/196650394-bc2808f6-9184-4ece-ac8d-8d5cb78618ed.png)

**Comment by philippjfr** [comment]
@MarcSkovMadsen Just to keep things clean, please do not label documentation issues with the bug label. Bugs are for code.

**Comment by MarcSkovMadsen** [comment]
Ok. Did not know. 

How do you distinguish between issues in existing documentation and enhancements to the docs then?
