### ISSUE TITLE
Size of Altair Pane increasing for every object update

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4034]
panel==0.14.0 altair==4.2.0 (but its the same with older versions)

As you can see on the video below the height of the `Altair` pane increases every time I emit a new `object`. The dashboard originally contains `holoviz`, `plotly`, `altair` and `echarts` panes. None of the other exhibit this behaviour.

```python
from datetime import datetime

import altair as alt
import numpy as np
import pandas as pd
import panel as pn
from streamz.dataframe import DataFrame as sDataFrame

alt.themes.enable("dark")

def _create_altair(data):
    data = data.reset_index()
    return (
        alt.Chart(data, height="container", width="container")
        .mark_line()
        .encode(
            x="index",
            y="y",
        )
    )

def view():
    """Returns an instance of the Streaming Plots app"""
    altair_pane = pn.pane.Vega(sizing_mode="stretch_both", margin=100)

    df_stream = sDataFrame(example=pd.DataFrame({"y": []}, index=pd.DatetimeIndex([])))
    df_window_stream = df_stream.cumsum().stream.sliding_window(50).map(pd.concat)

    def update_altair(data):
        altair_pane.object = _create_altair(data)

    df_window_stream.sink(update_altair)
    
    def emit():
        df_stream.emit(
            pd.DataFrame({"y": [np.random.randn()]}, index=pd.DatetimeIndex([datetime.utcnow()]))
        )

    emit()
    pn.state.add_periodic_callback(emit, period=250, count=240)  # Will stream for 1 mins

    component = pn.Column(
        pn.pane.Markdown("## VEGA via ALTAIR"), altair_pane, sizing_mode="stretch_both"
    )
    template = pn.template.FastListTemplate(
        theme="dark",
        main=[component]
    )
    
    return template


if __name__.startswith("bokeh"):
    pn.extension("vega", sizing_mode="stretch_width")
    view().servable()
```

https://user-images.githubusercontent.com/42288570/196667390-8fbb885a-5135-4234-9b34-97f42ff3e890.mp4

**Comment by MarcSkovMadsen** [comment]
But how would I or an experienced user now that they have the same underlying cause? They would search for their specific problem and find the issue. Not some consolidated one.

What I can do is mark them all `altair-sizing` or something. Then you or someone else can filter on them when there is time to solve them.

**Comment by MarcSkovMadsen** [comment]
An alternative would probably be to start using https://github.com/holoviz/panel/projects?query=is%3Aopen.

**Comment by philippjfr** [comment]
Then we should create (or rename) an issue that is sufficiently general. I'd like to avoid proliferation of custom labels as well. It's not a huge issue if users accidentally create a duplicate but I'm holding you to a higher standard than any regular user.
