### ISSUE TITLE
Format displayed DatetimeRangeSlider start, end and values.

### ISSUE THREAD

**Issue by killcoder** [holoviz/panel#4044]
Panel DatetimeRangeSlider accepts karg format="%H:%M:%S" but displays start, end and values in datetime format ("%d/%b/%Y %H:%M:%S")

```
date_range_slider = pn.widgets.DatetimeRangeSlider(
       name='Time Range',
       start=start,
       end=end,
       value=(start,end),
       format="%H:%M:%S",
       step=60000,
       width=300,
       sizing_mode="fixed",
)
datetime_range_slider
```
![image](https://user-images.githubusercontent.com/5696094/197303870-4fbf6422-4435-4a9b-972f-3b34b483b35a.png)

Bokeh equivalent code 
```
timerange_wid = DateRangeSlider(
    title="Time Range",
    name="timerange",
    value=(start, end),
    start=start,
    end=end,
    format="%H:%M:%S",
)
```
![image](https://user-images.githubusercontent.com/5696094/197297585-80c99fc2-7c70-41d8-ac74-656d91cbde9b.png)

#### ALL software version info
panel                     0.14.0
bokeh                     2.4.3

#### Description of expected behavior and the observed behavior
Panel DatetimeRangeSlider widget should display datetime objects in the format requested by the user.

**Comment by Hoxbro** [comment]
This seems to have been fixed on main:

![image](https://github.com/holoviz/panel/assets/19758978/c7315661-f4a6-4ce8-ba7b-ff6bd46bdcd0)

**Comment by killcoder** [comment]
Thanks for the update.
