### ISSUE TITLE
Make it easy and useful to use the VideoStream

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4046]
I've never seen any showcases of the `VideoStream` in Panel. As Panel can update relatively quickly via Tornado and websockets it should be the best data app framework for Video. And with `panel convert` even better.

But there are lot of issues

- There are no inspirational examples out there
- When you try out you run into several issues
  - The VideoStream transfers a high resolution image
  - The VideoStream transfers a .png base64 data url. It is slow to work with in Pillow and other frameworks. JPEG is much faster to load and transform
  - You need to be able to convert from base64 to PIL.Image for using Pillow and np.ndarray for using scikit-learn etc. This might be easy for experienced data vision people. But for beginners this is so hard.

To make it easier for Panel users to get started and create something useful. I propose we add an example to the Gallery that people can use for inspiration. We can use the example to identify and solve any performance issues.

The example should end up being easy to understand and use + super performant.

## Additional Context

[Yuichiro](https://twitter.com/whitphx) has done some really amazing work to make this possible in Streamlit. We should be able to find inspiration and make something at least as awesome. See https://edit.share.stlite.net/?sampleAppId=realtime_image_processing

[![image](https://user-images.githubusercontent.com/42288570/197327999-d67c824c-4303-44e1-9a06-623304116f0d.png)](https://twitter.com/whitphx/status/1583708572063772675?s=20&t=lZLbNEIl7LQpVWu1RyNEiQ)

**Comment by philippjfr** [comment]
Agreed, as first steps it would be good to add:

- `scale`: A parameter to downscale the images
- `format`: The data format, 'png', 'jpg' etc.

More examples would also be very welcome.

**Comment by MarcSkovMadsen** [comment]
The format is already support. The scale should be absolute as in (width, height).

**Comment by philippjfr** [comment]
I'm not convinced by width/height but maybe you can convince me otherwise. I just don't see distorted aspect ratios as ever being useful.
