### ISSUE TITLE
FastListTemplate main content not updating once rendered

### ISSUE THREAD

**Issue by unikill066** [holoviz/panel#4054]
Hi, I am trying to update the template.main of `FastListTemplate` post rendering based on a `Select` widget `on_click` and `param.watch`.

## Use-case:
Based on a `Select` widget value from `FastListTemplate` sidebar, I want to display the content in the `template.main` area. Also, on the landing page, I am already displaying an image and some text. So `on_click` or `param.watch` of the `Select` widget should generate charts and replace the existing `template.main`.

I tried replacing it, however, once the template is rendered I don’t see it changing when I select a different value in the selector.

Please suggest or point me to any resources that can help me here, many thanks!

**Comment by Hoxbro** [comment]
This should be possible, but this is more of a usage question and would be better to ask on [Discourse](https://discourse.holoviz.org/). 

Can you share a [minimal, reproducible example (MRE)](https://stackoverflow.com/help/minimal-reproducible-example) on Discourse?

**Comment by unikill066** [comment]
Indeed @Hoxbro, my issue is resolved now and here is the [resolution.](https://discourse.holoviz.org/t/how-to-update-the-fastlisttemplate-based-on-the-type-of-chart-selected/4451/3)
