### ISSUE TITLE
`pn.bind` does not treat `param.Parameter` arguments as dependencies

### ISSUE THREAD

**Issue by WildfireXIII** [holoviz/panel#4059]
#### ALL software version info

Tested both in JupyterLab 3.4.7 (in Firefox) as well as from a script

Panel: both 0.13.1 and 0.14.0
Param: 1.12.2
Python: 3.10.6

#### Description of expected behavior and the observed behavior

I would expect that calling `pn.bind` with a function and a `param.Parameter` would treat that parameter as a dependency, and that changing the parameter value would re-execute the function. 

(I assumed this based on the documentation of `panel.depends.bind`, which states that `args` and `kwargs` can both accept `param.Paramter`, and from the code https://github.com/holoviz/panel/blob/master/panel/depends.py#L175 that checks for `param.Parameter` arguments and inserts them into the dependencies)

As an example, if I try to copy a param to another class variable via a binding versus using a `@param.depends`:

```python
import panel as pn
import param

class BindingsTest(param.Parameterized):
	param_value = param.Integer(5)
	def __init__(self, **params):
		super().__init__(**params)

		self.attempted_param_binding_copy = 0
		self.working_param_depends_copy = 0

		self.param_binding = pn.bind(self.this_binding_copy_does_not_work, watch=True, value_to_copy=self.param_value)

	def this_binding_copy_does_not_work(self, value_to_copy):
		self.attempted_param_binding_copy = value_to_copy

	@pn.depends("param_value", watch=True)
	def this_copy_works(self):
		self.working_param_depends_copy = self.param_value
```

I would expect changing `param_value` to set both `self.attempted_param_binding_copy` and `self.working_param_depends_copy` to the same value.

When testing it with this:
```python
t = BindingsTest()
print(t.param_value, t.attempted_param_binding_copy, t.working_param_depends_copy)
> 5 0 0
```

```python
t.param_value = 3
print(t.param_value, t.attempted_param_binding_copy, t.working_param_depends_copy)
> 3 0 3
```

it appears only the `depends` function actually runs.

I tried investigating this a little, and it looks like the `isinstance(p, param.Parameter)` calls in the [`_param_bind` function](https://github.com/holoviz/panel/blob/master/panel/depends.py#L129) may not return what's expected?

If I try running `isinstance` on `param_value`:
```python
print(type(t.param_value))
> <class 'int'>
print(isinstance(t.param_value, param.Parameter))
> False
```

And so looking at what I assume is the dependency information of the binding versus the depends function:
```python
print(t.param_binding._dinfo)
> {'dependencies': (), 'kw': {}, 'watch': True, 'on_init': False}
print(t.this_copy_works._dinfo)
> {'dependencies': ('param_value',), 'kw': {}, 'watch': True, 'on_init': False}
```

Maybe I'm just missing or misunderstanding something, but I'm assuming `param_value` should show up in both of those, but let me know if it's not actually expected for a user to be able to use a parameter instead of a widget value!

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn
import param

class BindingsTest(param.Parameterized):
	param_value = param.Integer(5)
	def __init__(self, **params):
		super().__init__(**params)

		self.attempted_param_binding_copy = 0
		self.working_param_depends_copy = 0

		self.param_binding = pn.bind(self.this_binding_copy_does_not_work, watch=True, value_to_copy=self.param_value)

	def this_binding_copy_does_not_work(self, value_to_copy):
		self.attempted_param_binding_copy = value_to_copy

	@pn.depends("param_value", watch=True)
	def this_copy_works(self):
		self.working_param_depends_copy = self.param_value

t = BindingsTest()
print(t.param_value, t.attempted_param_binding_copy, t.working_param_depends_copy)

t.param_value = 3
print(t.param_value, t.attempted_param_binding_copy, t.working_param_depends_copy)
```

#### Additional context

I ran into this because I'm trying to implement tabulator filter functions (which the documentation suggests making with `pn.bind`) that are based on param values rather than widgets, and those value changes aren't triggering the filters, or even providing the correct current parameter values when the value of the tabulator itself is changed. I think I can figure out a way to make it work with `@pn.depends` instead, but when I was testing the above, it looked like this might be a bug.

**Comment by jbednar** [comment]
`pn.bind` is meant to create a reactive function that gets executed when its provided parameters change, with the _output_ displayed by panel. So if you want it to get called, you'd need to put `param_binding` into a Panel layout (`pn.Row`, `pn.Column`, etc.). `pn.depends` when used in a `Parameterized` class as you have here is already in a container that has such reactive behavior (the Parameterized object).

**Comment by xavArtley** [comment]
`self.param_value` is not a parameter but the value of the parameter
you want to bind your function against `self.param.param_value` instead of

**Comment by jbednar** [comment]
Good catch! Indeed, only a parameter object can be bound, not the parameter value, which is the actual problem here. 

But now I'm curious why the bound function is in fact invoked above when it's an instance attribute of a Parameterized when it didn't work in my test case unless embedded in a Panel container:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/1695496/198284125-c751ebcd-b46a-4c65-8fca-f867e9b6549b.png">

I'm guessing that setting the bound function as an instance attribute is making it into a method that a Parameterized class then handles, which I don't think was an intended behavior of a Parameterized but appears to fall out. I could just be confused, though!

**Comment by xavArtley** [comment]
Toi forgot To a de watch argument ro true

**Comment by WildfireXIII** [comment]
@xavArtley perfect, that works and makes sense. I misunderstood how the param objects work, thanks so much!

**Comment by jbednar** [comment]
Ok, thanks! I'll delete my comments to avoid confusing people who find this later!
