### ISSUE TITLE
panel 0.14.1 build issue: Cannot find module '@bokehjs/base'

### ISSUE THREAD

**Issue by Schamschula** [holoviz/panel#4071]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
panel 0.14.1
Python 3.10, under MacPorts, macOS 12.6 (Xcode 14.0, arm64)

#### Expected:
Clean build, as for version 0.14.0.

#### Observed:

```
...
Running npm install.
Using /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_python_py-panel/py310-panel/work/panel-0.14.1/panel/tsconfig.json
Compiling styles
Compiling TypeScript (51 files)
panel/index.ts:4:31 - error TS2307: Cannot find module '@bokehjs/base' or its corresponding type declarations.

4 import {register_models} from "@bokehjs/base"
                                ~~~~~~~~~~~~~~~
panel/models/ace.ts:1:20 - error TS2307: Cannot find module '@bokehjs/core/properties' or its corresponding type declarations.

1 import * as p from "@bokehjs/core/properties"
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
panel/models/ace.ts:2:23 - error TS2307: Cannot find module '@bokehjs/models/layouts/html_box' or its corresponding type declarations.

2 import {HTMLBox} from "@bokehjs/models/layouts/html_box"
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
panel/models/ace.ts:3:21 - error TS2307: Cannot find module '@bokehjs/core/dom' or its corresponding type declarations.

3 import { div } from "@bokehjs/core/dom";
                      ~~~~~~~~~~~~~~~~~~~
panel/models/ace.ts:23:11 - error TS2339: Property 'initialize' does not exist on type 'PanelHTMLBoxView'.

23     super.initialize()
             ~~~~~~~~~~
panel/models/ace.ts:36:10 - error TS2339: Property 'connect' does not exist on type 'AcePlotView'.

36     this.connect(this.model.properties.code.change, () => this._update_code_from_model())
            ~~~~~~~
panel/models/ace.ts:37:10 - error TS2339: Property 'connect' does not exist on type 'AcePlotView'.

37     this.connect(this.model.properties.theme.change, () => this._update_theme())
            ~~~~~~~
panel/models/ace.ts:38:10 - error TS2339: Property 'connect' does not exist on type 'AcePlotView'.

38     this.connect(this.model.properties.language.change, () => this._update_language())
            ~~~~~~~
panel/models/ace.ts:39:10 - error TS2339: Property 'connect' does not exist on type 'AcePlotView'.

39     this.connect(this.model.properties.filename.change, () => this._update_filename())
            ~~~~~~~
panel/models/ace.ts:40:10 - error TS2339: Property 'connect' does not exist on type 'AcePlotView'.

40     this.connect(this.model.properties.print_margin.change, () => this._update_print_margin())
            ~~~~~~~
panel/models/ace.ts:41:10 - error TS2339: Property 'connect' does not exist on type 'AcePlotView'.

41     this.connect(this.model.properties.annotations.change, () => this._add_annotations())
            ~~~~~~~
panel/models/ace.ts:42:10 - error TS2339: Property 'connect' does not exist on type 'AcePlotView'.

42     this.connect(this.model.properties.readonly.change, () => {
            ~~~~~~~
panel/models/ace.ts:43:43 - error TS2339: Property 'readonly' does not exist on type 'AcePlot'.

43       this._editor.setReadOnly(this.model.readonly)
...
```

**Comment by Schamschula** [comment]
Is this an expected error?
The build does finish.

**Comment by philippjfr** [comment]
Thanks for reporting @Schamschula. Just trying to understand exactly what you are trying to do and what steps you took. All releases should include pre-compiled bundles. I also cannot reproduce this issue locally.

**Comment by Schamschula** [comment]
I'm the port maintainer for py-panel under MacPorts.

All I was trying to do is upgrade the Portfile from version 0.14.0 to 0.14.1.

**Comment by philippjfr** [comment]
Got it, thanks for the background. Not much has changed on the JS/TS side so this is quite surprising. I'll try to follow those steps when I get a chance.

**Comment by mattpap** [comment]
Probably `npm install` failed silently or `npm` is very outdated, or there is some kind of mismatch between install and build environments. I would start with checking the contents of `node_modules/`, specifically `panel/node_modules/@bokeh/bokehjs/build/js/types/`. The presented set of errors is always a result of type declarations being unavailable for one or the other reason.

**Comment by philippjfr** [comment]
Yes, I think something must have gone wrong with `npm install`. Any chance you could try again @Schamschula. Really appreciate your work btw.

**Comment by Schamschula** [comment]
I just tried on a different machine: Python 3.10, under MacPorts, macOS 13.0 (Xcode 14.1, Intel)

Same result.

**Comment by Schamschula** [comment]
Figured it out: I need to add npm as a build dependency.

**Comment by philippjfr** [comment]
Great, glad you figured it out and thanks for reporting back!
