### ISSUE TITLE
cannot switch theme for fastlisttemplate when using pn.serve() function

### ISSUE THREAD

**Issue by Khalilsqu** [holoviz/panel#4072]
#### ALL software version info

panel 0.14.1

#### Description of expected behavior and the observed behavior
the FastListTemplate theme switch must be toggleable, but it cannot when using pn.serve function!

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

pn.extension()

template = pn.template.FastListTemplate(
    title="My App",
)

template.main.append(pn.pane.Markdown("## Simple App"))

pn.serve(
    {
        "/": template
    },
)

```

**Comment by Hoxbro** [comment]
A way to get it to work is to wrap your template into main like this:

``` python
import panel as pn

pn.extension()


def main():
    template = pn.template.FastListTemplate(
        title="My App",
    )

    template.main.append(pn.pane.Markdown("## Simple App"))
    return template


pn.serve({"/": main})

```

**Comment by Khalilsqu** [comment]
Thank you very much, indeed it works
