### ISSUE TITLE
CORS issue with static-dirs

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4075]
I'm having a cors issue when serving `panel convert` apps via `--static-dirs` at awesome-panel.org. 

I believe tornado needs to add some headers to avoid this issue

## "Reproduce"

1. Deploy a panel app and make it publicly accessible
2. Serve `panel convert` apps with FastListTemplate via `--static-dirs`
3. Open one of the apps and see the issue.

Open [panel sharing example](https://awesome-panel.org/sharing?project=eyJzb3VyY2UiOnsiY29kZSI6ImltcG9ydCBwYW5lbCBhcyBwblxuXG5wbi5leHRlbnNpb24oc2l6aW5nX21vZGU9XCJzdHJldGNoX3dpZHRoXCIsIHRlbXBsYXRlPVwiZmFzdFwiKVxuXG5wbi5wYW5lbChcIllvdSBjYW4gc2VlIHRoZSB0b2dnbGUgYnV0dG9uIG9uIHRoZSByaWdodCBpcyByZWQuIElmIHlvdSAqaW5zcGVjdCogeW91IHdpbGwgc2VlIHRoZSBjb3JzZSBpc3N1ZVwiKS5zZXJ2YWJsZSgpIiwicmVhZG1lIjoiIyBJbnRyb2R1Y3Rpb25cblxuVGhlIHB1cnBvc2Ugb2YgdGhpcyBwcm9qZWN0IC4uLlxuXG4jIyBSZXNvdXJjZXNcblxuLSBbUGFuZWxdKGh0dHBzOi8vcGFuZWwuaG9sb3Zpei5vcmcpIHwgW1dlYkFzc2VtYmx5IFVzZXIgR3VpZGVdKGh0dHBzOi8vcGFuZWwuaG9sb3Zpei5vcmcvdXNlcl9ndWlkZS9SdW5uaW5nX2luX1dlYmFzc2VtYmx5Lmh0bWwpIHwgW0NvbW11bml0eSBGb3J1bV0oaHR0cHM6Ly9kaXNjb3Vyc2UuaG9sb3Zpei5vcmcvKSB8IFtHaXRodWIgQ29kZV0oaHR0cHM6Ly9naXRodWIuY29tL2hvbG92aXovcGFuZWwpIHwgW0dpdGh1YiBJc3N1ZXNdKGh0dHBzOi8vZ2l0aHViLmNvbS9ob2xvdml6L3BhbmVsL2lzc3VlcykgfCBbVHdpdHRlcl0oaHR0cHM6Ly9tb2JpbGUudHdpdHRlci5jb20vcGFuZWxfb3JnKSB8IFtMaW5rZWRJbl0oaHR0cHM6Ly93d3cubGlua2VkaW4uY29tL2NvbXBhbnkvNzk3NTQ0NTApXG4tIFtBd2Vzb21lIFBhbmVsXShodHRwczovL2F3ZXNvbWUtcGFuZWwub3JnKSB8IFtHaXRodWIgQ29kZV0oaHR0cHM6Ly9naXRodWIuY29tL21hcmNza292bWFkc2VuL2F3ZXNvbWUtcGFuZWwpIHwgW0dpdGh1YiBJc3N1ZXNdKGh0dHBzOi8vZ2l0aHViLmNvbS9NYXJjU2tvdk1hZHNlbi9hd2Vzb21lLXBhbmVsL2lzc3Vlcylcbi0gTWFyYyBTa292IE1hZHNlbiB8IFtUd2l0dGVyXShodHRwczovL3R3aXR0ZXIuY29tL01hcmNTa292TWFkc2VuKSB8IFtMaW5rZWRJbl0oaHR0cHM6Ly93d3cubGlua2VkaW4uY29tL2luL21hcmNza292bWFkc2VuLylcbi0gU29waGlhIFlhbmcgfCBbVHdpdHRlcl0oaHR0cHM6Ly90d2l0dGVyLmNvbS9zb3BoaWFteWFuZykgfCBbTWVkaXVtXShodHRwczovL3NvcGhpYW15YW5nLm1lZGl1bS5jb20vKVxuLSBbUHlvZGlkZV0oaHR0cHM6Ly9weW9kaWRlLm9yZykgfCBbRkFRXShodHRwczovL3B5b2RpZGUub3JnL2VuL3N0YWJsZS91c2FnZS9mYXEuaHRtbClcbi0gW1B5U2NyaXB0XShodHRwczovL3B5c2NyaXB0Lm5ldC8pIHwgW0ZBUV0oaHR0cHM6Ly9kb2NzLnB5c2NyaXB0Lm5ldC9sYXRlc3QvcmVmZXJlbmNlL2ZhcS5odG1sKVxuIiwicmVxdWlyZW1lbnRzIjoiIn19)

![image](https://user-images.githubusercontent.com/42288570/199055699-9081da30-82bd-4100-8d61-026fe5f9ef40.png)

![image](https://user-images.githubusercontent.com/42288570/199055854-967f2a91-2d94-4564-9663-7b7ab746a605.png)

**Comment by xavArtley** [comment]
I suppose you run it on windows?

**Comment by xavArtley** [comment]
Actually I can't reproduce
I have a bunch of error but none about cors:
![image](https://user-images.githubusercontent.com/18531147/199462748-e97ac0f3-3acc-45cd-a604-b69450c11e81.png)

**Comment by MarcSkovMadsen** [comment]
Thanks so much for checking @xavArtley . Which browser are you using?

**Comment by MarcSkovMadsen** [comment]
I just tried Chrome. There is no issue.

![image](https://user-images.githubusercontent.com/42288570/199501756-34214f39-5ff8-47e0-a720-507d8b2e50d1.png)

**Comment by MarcSkovMadsen** [comment]
I also retried edge. There is no issue any more.

Besides this way of checking I have also created a CDN for serving static web assembly apps. For example https://sharing.awesome-panel.org/user/MarcSkovMadsen/app/videostream-interface/app.html. There I also had the CORS issue but solved it by creating some network rules in azure.

I will close this one now. But please note that this issue https://github.com/holoviz/panel/issues/4080 is related to the same *fast* file from the new CDN.
