### ISSUE TITLE
Tabulator does not respect the current sorting when highlighting

### ISSUE THREAD

**Issue by hoxbro** [holoviz/panel#4076]
When a tabulator is sorted and selecting multiple items with shift + click, it does not respect the current ordering of the tabulator but highlights all the items between the two indexes. 

``` python
import pandas as pd
import numpy as np
import panel as pn

pn.extension("tabulator")

df = pd.DataFrame(np.random.rand(10000))
pn.widgets.Tabulator(df, disabled=True)
```

https://user-images.githubusercontent.com/19758978/199202892-88a9a8c0-cb40-463f-bda0-b9227c5aae23.mp4

**Comment by philippjfr** [comment]
Likely the same issue as https://github.com/holoviz/panel/issues/5826

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/7063
