### ISSUE TITLE
Panel 0.14.0 breaks Fast Templates

### ISSUE THREAD

**Issue by mayonnaisecolouredbenz7** [holoviz/panel#4080]
Running the code exactly from documentation https://panel.holoviz.org/reference/templates/FastListTemplate.html 

Using panel 0.14.1 gives:

![image](https://user-images.githubusercontent.com/38597661/199426176-1e46ddff-f7fe-4c0a-84df-19b565f1299b.png)

**Comment by MarcSkovMadsen** [comment]
Hi @mayonnaisecolouredbenz7 

Could you share a bit more information

1. How and where are you running this? (I.e. running it behind an enterprise firewall etc could cause issues)
2. What are the logs from the server?
3. Could you share the errors from the browsers console? (right click, inspect, select the *console*).

**Comment by mayonnaisecolouredbenz7** [comment]
1. Running it locally, windows machine in a python virtual environment. And running installs for only panel and holoviews
![image](https://user-images.githubusercontent.com/38597661/199455742-6076bad8-d893-49e7-8788-a0a02b72e836.png)

2. Logs look normal
```
2022-11-02 20:40:12,077 Bokeh app running at: http://localhost:5006/test
2022-11-02 20:40:12,077 Starting Bokeh server with process id: 24196
2022-11-02 20:40:20,200 Subprotocol header received
2022-11-02 20:40:20,200 WebSocket connection opened
2022-11-02 20:40:20,201 Receiver created for Protocol()
2022-11-02 20:40:20,202 ProtocolHandler created for Protocol()
2022-11-02 20:40:20,202 ServerConnection created
2022-11-02 20:40:20,293 Sending pull-doc-reply from session 's1RzWcutYRiBzQenVwFj5UhsoIjjFzntCG1eSTRmphvB'
2022-11-02 20:40:27,067 [pid 24196] 1 clients connected
2022-11-02 20:40:27,067 [pid 24196]   /test has 1 sessions with 0 unused
```

3. Looks like some browser console errors/warnings of note
![image](https://user-images.githubusercontent.com/38597661/199457182-a24ee51c-1c5d-4bac-ba8c-6a13f7cad560.png)

**Comment by xavArtley** [comment]
Ok it's due to a windows register key
I don't know at wich level it should be considered as an issue but the
solution I found is the following one :
```python
import mimetypes
mimetypes.add_type("application/javascript", ".js")
```

**Comment by mayonnaisecolouredbenz7** [comment]
Interesting, re: the solutions @xavArtley posted.  Both adding the code/changing the registry worked for firefox.  But chrome is still throwing errors

![image](https://user-images.githubusercontent.com/38597661/199467107-7350fa75-8e56-4ef5-be8f-a5ab8f2d2b99.png)

**Comment by xavArtley** [comment]
maybe add this
import mimetypes
mimetypes.add_type("application/javascript", ".mjs")

**Comment by xavArtley** [comment]
Actually on chrome you should may be use shift+F5 to reload the application

**Comment by MarcSkovMadsen** [comment]
I see something similar for `panel convert` apps served via `--static-dirs`

![image](https://user-images.githubusercontent.com/42288570/199807130-b86a46d4-0260-407c-b9c2-849b20005ecd.png)

```bash
Access to script at 'https://cdn.holoviz.org/panel/0.14.0/dist/bundled/js/@microsoft/fast-components@1.21.8/dist/fast-components.js' from origin 'https://mnr-jupyterhub.de-prod.dk' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
app.html:67 
       GET https://cdn.holoviz.org/panel/0.14.0/dist/bundled/js/@microsoft/fast-components@1.21.8/dist/fast-components.js net::ERR_FAILED 200
```

**Comment by MarcSkovMadsen** [comment]
Now it works for me again. I am not aware I changed anything.

![image](https://user-images.githubusercontent.com/42288570/199809544-3ef2d16c-ab1f-47e1-bf60-eb6ba32675a6.png)

**Comment by mayonnaisecolouredbenz7** [comment]
Just for completeness from my end.  I am running my production apps on azure on a Linux machine. And initially the green font etc loads for a second or two before rendering correctly, both chrome and firefox.  

This is the only warning that pops up, not sure if related
![image](https://user-images.githubusercontent.com/38597661/199855563-68885816-8aec-45f4-884c-0dff728816f9.png)

**Comment by philippjfr** [comment]
Sounds like this is still biting people. I'm unfortunately really not sure why since in S3 all JS files correctly have the mime-type set to application/javascript:

<img width="1100" alt="Screen Shot 2022-11-14 at 09 34 41" src="https://user-images.githubusercontent.com/1550771/201612976-19233ee3-7752-4c84-9f85-d064fcc7589d.png">

**Comment by philippjfr** [comment]
@MarcSkovMadsen Could you access https://cdn.holoviz.org/panel/0.14.1/dist/bundled/js/@microsoft/fast-components@1.21.8/dist/fast-components.js pull up the developer console and look at the Response Header? Here's what I see:

<img width="276" alt="Screen Shot 2022-11-14 at 09 42 32" src="https://user-images.githubusercontent.com/1550771/201614462-14ac5774-b252-4677-8073-97d5aae83f47.png">

**Comment by philippjfr** [comment]
Ah I see, yes that is probably also true in the @MarcSkovMadsen's case. My mind went to the CDN since that's the only thing we really changed in 0.14.0 so I wonder what changed between 0.13.1 and 0.14.0 that would have messed with the mime-types of locally served resources.

**Comment by philippjfr** [comment]
Actually I think I might know, previously we loaded the module like this, i.e. without specifying the specific JS file:

            'fast-colors': 'https://unpkg.com/@microsoft/fast-colors@5.1.4',

while now we do this:

            'fast-colors': f'{config.npm_cdn}/@microsoft/fast-colors@5.3.1/dist/index.js',

It sounds like this is down to a misconfiguration on Windows. Should we just always apply this patch on Windows:

```python
import mimetypes
if '.js' not in mimetypes.types_map:
    mimetypes.add_type("application/javascript", ".js")
```

**Comment by xavArtley** [comment]
For me patching windows should be the solution
However I don't know why it's not done at tornado level

**Comment by philippjfr** [comment]
Perfect, thank you!

**Comment by philippjfr** [comment]
This is reported on the Python issue tracker: https://github.com/python/cpython/issues/76643

Technically this has nothing to do with Panel or Tornado and we are also not the correct place to patch this, however given that it is quite obscure to figure out and I don't see harm in patching it automatically I will add the patch. However @MarcSkovMadsen and @mayonnaisecolouredbenz7 this is likely to break other applications on your machines and you should really fix your Windows registry keys (as described in [the Stackoverflow post](https://stackoverflow.com/a/12057490/11825544)).

**Comment by MarcSkovMadsen** [comment]
Thanks. I cannot change this my self, but will try to get our IT to change it.

**Comment by MarcSkovMadsen** [comment]
I just experienced this again. Probably my registry keys where changed by IT. The problem is that I an any other enterprise user is not in control of our windows setttings. So this cannot be on the users to solve.

**Comment by philippjfr** [comment]
This has been patched explicitly in Panel, are you sure you were using Panel 0.14.2

**Comment by MarcSkovMadsen** [comment]
I just build the container and panel is not set to a specific version. But I will investigate.

**Comment by MarcSkovMadsen** [comment]
Yes Panel 0.14.2

![image](https://user-images.githubusercontent.com/42288570/211845648-2b48af3c-1efc-4a86-b597-e18d91e41589.png)

![image](https://user-images.githubusercontent.com/42288570/211845905-97cb60f6-8c6c-4fff-ac54-86f1247773cc.png)

**Comment by MarcSkovMadsen** [comment]
Could it be the nginx/ kubernetes messing with things?

**Comment by MarcSkovMadsen** [comment]
It can load all `.js files except the two that starts with `./`

![image](https://user-images.githubusercontent.com/42288570/211847136-9837bc8c-70ff-49e6-9f08-2dbafcfa4245.png)

**Comment by MarcSkovMadsen** [comment]
I think its a misconfiguration of the kubernetes cluster ingress.

**Comment by MarcSkovMadsen** [comment]
I was a misconfiguration of the 'path' setting in an ingress file.

**Comment by philippjfr** [comment]
Thanks for reporting back!
