### ISSUE TITLE
pn.state.on_session_destroyed() fails in 0.14.1

### ISSUE THREAD

**Issue by ncvangilse** [holoviz/panel#4094]
Adding callbacks to pn.state.on_session_destroyed() fails in version 0.14.1 but not in 0.13.1

`RuntimeError: Could not add session destroyed callback since no document to attach it to could be found.`
```
import panel as pn

class App(pn.viewable.Viewer):

    def __init__(self):
        super().__init__()
        self.w = pn.pane.Markdown('Hello world')
        self._on_close_callback = pn.state.on_session_destroyed(self._callback)

    def _callback(self, *_):
        print('Callback')

    def __panel__(self):
        return self.w

server = pn.serve(
    App(),
    start=True,
    show=True,
)
```

**Comment by philippjfr** [comment]
Unfortunately this behavior cannot be correctly restored as even in 0.13.1 this would have been extremely prone to errors. Before you serve an application the curdoc does not yet exist which means you indeed cannot attach a callback to it.

The correct way to handle this is the following:

```python
def create_app():
    return App()

server = pn.serve(
    create_app,
    start=True,
    show=True,
)
```
