### ISSUE TITLE
Bokeh 3.0 compatibility

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#4097]
The migration to support Bokeh 3.0 is a huge project that will take several months to complete. Initial work for compatibility has started in https://github.com/holoviz/panel/pull/3752 but it is not sustainable to keep pushing commit after commit into that PR. Therefore we have decided to create `branch-1.0` and merge the current progress into that PR and then follow up with further fixes (and features) in followup PRs.

For reference, a migration guide to bokeh 3.0 can be found [here](https://github.com/bokeh/bokeh/wiki/Migration-Guides).

# Components

This list of components highlights which items render correctly. Note that unchecked items may work and checked items may still have weird interactions when laid out with other components).

## Panes

- [x] Alert (needs some color tweaks)
- [x] Audio
- [x] Bokeh
- [x] DataFrame
- [x] DeckGL
- [x] ECharts
- [x] Folium
- [x] GIF
- [x] HTML
- [x] HoloViews
- [x] ICO
- [x] IDOM (deprecated)
- [x] IPyLeaflet (@maximlt same as IpyWidget)
- [x] IPyWidget (@maximlt https://github.com/holoviz/panel/issues/4410)
- [x] Interactive
- [x] JPG
- [x] JSON
- [x] LaTeX (`KaTeX` model does not yet work correctly - @Hoxbro)
- [x] Markdown
- [x] Matplotlib
- [x] PDF
- [x] PNG
- [x] Param
- [x] ParamFunction
- [x] ParamMethod
- [x] Perspective (scrollbars not right) (@philippjfr)
- [x] Plotly
- [x] RGGPlot (@maximlt)
- [x] SVG
- [x] Str
- [x] Streamz (@Hoxbro)
- [x] VTK
- [x] VTKJS (@philippjfr)
- [x] VTKVolume (@philippjfr)
- [x] Vega (@maximlt https://github.com/holoviz/panel/issues/4379)
- [x] Video
- [x] YT (deprecated)

## Widgets

- [x] Ace (weird height sizing - @Hoxbro)
- [x] ArrayInput
- [x] AutocompleteInput
- [x] BooleanStatus (#4129)
- [x] Button
- [x] CheckBoxGroup
- [x] CheckButtonGroup
- [x] Checkbox
- [ ] ColorPicker (https://github.com/holoviz/panel/issues/4385)
- [x] CrossSelector
- [x] DataFrame
- [x] DatePicker
- [x] DateRangeSlider (@Hoxbro)
- [x] DateSlider (@Hoxbro)
- [x] DatetimeInput (@Hoxbro)
- [x] DatetimePicker
- [x] DatetimeRangeInput (@Hoxbro)
- [x] DatetimeRangePicker
- [x] DatetimeRangeSlider (@Hoxbro)
- [x] Dial
- [x] DiscretePlayer
- [x] DiscreteSlider
- [x] EditableFloatSlider
- [x] EditableIntSlider
- [x] EditableRangeSlider
- [x] FileDownload (@maximlt https://github.com/holoviz/panel/issues/4382)
- [x] FileInput (@maximlt)
- [x] FileSelector (@maximlt https://github.com/holoviz/panel/issues/4381)
- [x] FloatInput
- [x] FloatSlider
- [x] Gauge
- [x] IntInput
- [x] IntRangeSlider
- [x] IntSlider
- [x] JSONEditor (Ace editing mode has same issues as Ace itself)
- [x] LinearGauge
- [x] LiteralInput
- [x] LoadingSpinner  (#4129)
- [x] MenuButton
- [x] MultiChoice
- [x] MultiSelect
- [x] Number  (#4129)
- [x] NumberInput (@Hoxbro)
- [ ] PasswordInput (weird rendering of show/hide toggle - @philippjfr)
- [x] Player
- [x] Progress  (#4129)
- [x] RadioBoxGroup
- [x] RadioButtonGroup
- [x] RangeSlider
- [x] Select
- [x] SpeechToText (@maximlt https://github.com/holoviz/panel/pull/4383)
- [x] StaticText (@Hoxbro)
- [x] String  (#4129)
- [x] Tabulator (version bump?! @maximlt)
- [x] Terminal (cell width/height handling not correct @philippjfr)
- [x] TextAreaInput
- [x] TextEditor (@Hoxbro)
- [x] TextInput
- [x] TextToSpeech (@maximlt)
- [x] Toggle
- [x] ToggleGroup
- [x] Tqdm (@Hoxbro)
- [x] Trend (@Hoxbro)
- [x] VideoStream

## Layout

- [x] Accordion (@philippjfr)
- [x] Card (background not working @philippjfr)
- [x] Column (@Hoxbro)
- [x] Debugger (@Hoxbro)
- [x] FlexBox
- [x] GridBox (@maximlt)
- [x] GridSpec (@maximlt https://github.com/holoviz/panel/issues/4384)
- [x] GridStack (@maximlt https://github.com/holoviz/panel/issues/4409)
- [x] Row (@Hoxbro)
- [x] Tabs (@Hoxbro)
- [x] WidgetBox (@philippjfr)

## Templates

- [x] BootstrapTemplate (@philippjfr)
- [x] FastGridTemplate (@philippjfr)
- [x] FastListTemplate (@philippjfr)
- [x] GoldenTemplate (@philippjfr)
- [x] MaterialTemplate (@philippjfr)
- [x] ReactTemplate (deprecated)
- [x] VanillaTemplate (@philippjfr)

# Documentation

- User Guides Migrations
  - [x] Custom Components (@droumis)
  - [x] Pipeline (@droumis)
- How-tos
   - [ ] Review pass (@droumis)
- Reference Gallery
   - [ ] Synchronize component descriptions with docstrings 
   - [ ] Synchronize component parameter descriptions with docstrings
   - [ ] Write script to generate .md files for reference items
- API Reference
- [ ] Decide what to do? (@droumis)
- Gallery
- Frontpage
  - [ ] Review and merge Marc's PR (@philippjfr)
- Background
  - [ ] Review (@droumis)
- About
  - [ ] Decide to remove (@droumis)
- Developer Guide
  - [ ] Cleanup (@philippjfr)

# Deprecations

- [x] Want to have 0.14.3 release with deprecation announcements (@philippjfr) 
- [x] ReactTemplate (@philippjfr)
- [x] IDOM (@philippjfr)
- [x] VTK? (@philippjfr)
- [x] YT

# Other issues

- [x] Currently have had to add custom `.css` properties to certain models to sync imported CSS and then during rendering we patch this property with the CDN or local server path (@philippjfr)
- [x] UI tests do not work with bokeh 3.0 and are disabled for now. (@Hoxbro & @maximlt)  

# Related tasks

- [x] Bokeh now requires pandas. Therefore it could make sense to also have it for panel, which will make files like `panel.widgets.tables.py` cleaner.  (@maximlt https://github.com/holoviz/panel/pull/4411)

**Comment by MarcSkovMadsen** [comment]
Would it make sense to add Templates to the above todo list?

**Comment by philippjfr** [comment]
Yes. They'll need quite a bit of work, indeed we probably have to provide some architecture that will make it easy to allow templates to inject CSS on the appropriate components.

**Comment by philippjfr** [comment]
There's plenty more to do here but all components should now be working.
