### ISSUE TITLE
pn.state.busy value is unreliable when threading is enabled

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#4099]
Panel 0.14.1

When threading is enabled, the value in `pn.state.busy` may not reflect the actual state of the server.

It seems that when a callback is finished, the value of `pn.state.busy` is toggled, leading to the wrong value if several callbacks overlap (whether there are triggered in one session or separate sessions). When it is `True` while it should not, it does not respond to further callbacks.

This has implications for all templates that display a busy indicator by default.

```python
import panel as pn
import time

pn.extension(nthreads=2)


def callback(_):
    log.object += 'Starting callback\n'
    time.sleep(5)
    log.object += 'Finishing callback\n'


button = pn.widgets.Button(name='Click here')
button.on_click(callback)
indicator = pn.indicators.LoadingSpinner()
log = pn.pane.Str('')
pn.state.sync_busy(indicator)
pn.Row(pn.Column(button, log), indicator).servable()
```

![busy_bug](https://user-images.githubusercontent.com/49269671/201114769-cd6956fe-af8e-4bc7-8727-7f7e439d5172.gif)

**Comment by TheoMathurin** [comment]
Maybe incrementing/decrementing a counter based on the number of currently busy threads would do. You could then set `state.busy` to `bool(state._busy_counter)` once the callback is finished.

I have not thought this through and I'm not familiar with Panel's inner workings, but this approach would have the advantage of being pretty simple.

**Comment by philippjfr** [comment]
Yes, an internal counter will be the correct way to resolve this.
