### ISSUE TITLE
Breaking change: 0.14.0 -> 0.14.1 for pn.template.MaterialTemplate

### ISSUE THREAD

**Issue by tomascsantos** [holoviz/panel#4101]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
https://gist.github.com/tomascsantos/8c8047c1380ee3d00479fef003095b31

#### Description of expected behavior and the observed behavior
Panel should render a template if it is returned in `__panel__`. It used to, but now it returns something wrong.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn
import param


class Test(pn.viewable.Viewer):

    def __init__(self):
        super().__init__()

        self._main = pn.Column('main')
        self._sidebar = pn.Column('sidebar')

        self._template = pn.template.MaterialTemplate(
            main=self._main,
            sidebar=self._sidebar,
        )

    def __panel__(self):
        return self._template


# This is a breaking change from 0.14.0 -> 0.14.1
Test().servable()


class Test2(param.Parameterized):

    def __init__(self):
        super().__init__()

        self._main = pn.Column('main')
        self._sidebar = pn.Column('sidebar')

        self._template = pn.template.MaterialTemplate(
            main=self._main,
            sidebar=self._sidebar,
        )


# This still works
# Test2()._template.servable()

```

#### Screenshots or screencasts of the bug in action

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/7690514/201225959-27c5d77d-cb41-4832-b3ec-1ccafecd4a04.png">

Thanks for all the hard work everyone!

**Comment by Hoxbro** [comment]
Pretty sure this is because of changes made in https://github.com/holoviz/panel/pull/4065.

**Comment by philippjfr** [comment]
Yes thanks @Hoxbro, looks like Templates weren't handled in that PR. I honestly had not considered Templates as a valid return types of Viewer components but I guess if you support it someone will end up relying on it :)

**Comment by maximlt** [comment]
> Panel should render a template if it is returned in __panel__. 

Should it really? I like thinking about the Viewer as a simple way to wrap well-defined components. It's clear and easy to document. Templates are full apps so it's breaking that simple definition and I'm fine considering the previous support as a bug to be honest rather than a feature.

**Comment by tomascsantos** [comment]
I don't have a strong opinion either way. It was frustrating to have the rug pulled from under my feet, but after identifying the issue it's an easy fix :)

**Comment by philippjfr** [comment]
So it's actually more of a pain to disallow this than to continue allowing it. So the old behavior is getting restored.
