### ISSUE TITLE
input password when first login(like the way in jupyter notebook)

### ISSUE THREAD

**Issue by orangeSi** [holoviz/panel#4113]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### Is your feature request related to a problem? Please describe.
I run a panel app by ``` panel serve xx.py ``` and get a web url, but everyone can access the url.  So I want to add a password(which I can set at background), only the people which enter the password can access the url . 
Just like the way in jupyter notebook!

#### Describe the solution you'd like
add a password when first login the app by the url.

#### Describe alternatives you've considered
NA

#### Additional context
In Jupyter notebook, we can set a password in config, the open by the url then enter the password and start use the notebook!

**Comment by philippjfr** [comment]
Thanks @orangeSi! This would indeed be very nice. For more complex usecases setting up OAuth is more appropriate but we should have a simple example using a simple password. There is an issue here: https://github.com/holoviz/panel/issues/2575 that already makes this request. Therefore I'll close this issue and continue updating the other one.

**Comment by orangeSi** [comment]
@philippjfr  I made a mini demo like this and it works for me ~
```

import param
import panel as pn
from panel.reactive import ReactiveHTML
import os
import sys

pn.extension(sizing_mode="stretch_width")
    
# create main_app which will show after enter right password
main_app = pn.widgets.IntInput(name='Number:', value=50, step=1, start=0, end=100)
main_app.visible = False

# create password page and check password if is right
def check_password(self):
    pw = "this_is_password" # this is the right password
    if self.obj.value == pw:
        #hide password page
        password_input.visible = False
        #show main app
        main_app.visible = True
password_input = pn.widgets.TextInput(name="enter passwrod:", placeholder="password")
password_input.param.watch(check_password, 'value')

# serve the app
app = pn.Column(password_input, main_app)
app.servable(title="set simple password check!") 
```
