### ISSUE TITLE
Enable users to easily create apps that depends or binds to the PeriodicCallback

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4125]
## Request

Enable users to easily create apps that depends or binds to the `PeriodicCallback`

## Motivation

We increasingly suggest to use `pn.bind` (or alternatively `pn.depends`). When you create streaming applications or applications that need to update on a schedule you cannot use these apis without adding your own boiler plate code.

## Cannot get working

I cannot write code in the below style. The problem is that 1) I must provide a callback to the `PeriodicCallback` 2) It has no parameter I can bind to or depends on.

```python
import panel as pn
import pandas as pd
import datetime

pn.extension()

periodic_callback = pn.state.add_periodic_callback(lambda: print("update"))

def get_object(*args):
    "Returns a plot of the data"
    return datetime.datetime.now()

pn.panel(
    pn.bind(plot, periodic_callback.param.UNKNOWN)
).servable()
```

## Workaround with boiler plate code

```python
import datetime

import pandas as pd
import panel as pn
import param
from panel.io.callbacks import PeriodicCallback

pn.extension()

class Timer(param.Parameterized):
    value = param.Date()
    periodic_callback = param.ClassSelector(class_=PeriodicCallback)

    def __init__(self):
        super().__init__()
        
        self.periodic_callback = pn.state.add_periodic_callback(self._update_value)

    def _update_value(self):
        self.value = datetime.datetime.now()

def get_object(value):
    "Returns a plot of the data"
    print(value)
    return value

timer=Timer()

pn.Column(
    timer.periodic_callback.param.period, pn.bind(get_object, timer.param.value)
).servable()
```

## Discussion

One solution would be to extend the api of the PeriodicCallback. Another would be to add a dedicated `Timer` or `PeriodicTrigger` class.

**Comment by philippjfr** [comment]
I have no particular objections to add parameters like this to the `PeriodicCallback` class:

```python
    counter = param.Integer()

    last_executed = param.Date()
```
