### ISSUE TITLE
Tabulator add support for column header tooltip

### ISSUE THREAD

**Issue by RaphaelRosset** [holoviz/panel#4138]
Tabulator javascript handle column header tooltips: https://tabulator.info/docs/5.4/menu#tooltips

Pass a dictionary {column: tooltip_string} as optional parameter to Tabulator constructor
Update the javascript columns array accordingly.

User case: limited space to display table, so using short acronyms as column headers but would like to exposed full name in tooltips.

**Comment by RaphaelRosset** [comment]
I just realized that it is in fact already possible to setup a tooltip easily to any text displayed in the table by passing an html string with a tooltip setup:
"header/cell text"  =>  "<span title='tooltip text'>header/cell text</span>"

**Comment by dslemusp** [comment]
Hi @RaphaelRosset, Could you elaborate a bit more on how to do this? (Perhaps with a bit of sample code). I am interested on doing this but cannot understand quite well what you mean.

Thx

**Comment by RaphaelRosset** [comment]
Hi @dslemusp,
Yes my answer was indeed very unclear, below is an example where second column header is modified through html.
The title keyword allows to pass a tooltip string
`
df = pd.DataFrame(
          {
              "int": [1, 2, 3],
              "<span style='background-color:beige;' title='Tooltip text'>header</span>": [
                  True,
                  False,
                  True,
              ],
          },
          index=[1, 2, 3],
      )
      tabulator = pn.widgets.Tabulator(df)
`

**Comment by CTPassion** [comment]
I second this as a requirement :)

**Comment by hmijail** [comment]
Thirded :)

**Comment by ahuang11** [comment]
Would anyone be interested in contributing to implement this feature? I can provide guidance if needed.
