### ISSUE TITLE
Tabulator: Glitches when update value and resize with frozen_columns

### ISSUE THREAD

**Issue by thuydotm** [holoviz/panel#4153]
#### Description of expected behavior and the observed behavior
Let's say we have a dropdown filter, a data table which is a Tabulator object with some frozen columns. The table content is defined by the dropdown's selected value. There appears glitches when resizing the frozen columns or the one next to it.

Expectation: In the column next to frozen column, there should be no redundant space, and its content should not be hidden.

#### Complete, minimal, self-contained example code that reproduces the issue
```
import pandas as pd
import panel as pn

df = pd.DataFrame({
    'TITLE': [
        'This is a title - One',
        'This is a title - Two',
    ],
    'STATUS': ['WIP', 'Closed'],
})

table = pn.widgets.Tabulator(
    df,
    frozen_columns=['TITLE'],  # no issue if this line is commented, i.e no frozen columns
    layout='fit_data_stretch',
    margin=0,
    sizing_mode='stretch_width',
    show_index=False,
    theme='bootstrap4',
    formatters={
        'STATUS': {
            'type': 'lookup',
            'WIP': '<div style="padding: 0.5em; border-radius: 2px; background-color: #bbdbf0; color: #0e71b3;">WIP</div>',
            'Closed': '<div style="padding: 0.5em; border-radius: 2px; background-color: #bbdbf0; color: #0e71b3;">Closed</div>',
        },
    }
)

choose_status = pn.widgets.Select(name="Select status", options=['WIP', 'Closed'])

def update_table(event):
    filtered_df = df[df['STATUS']==event.new]
    table.value = filtered_df

choose_status.param.watch(update_table, 'value')

pn.Column(
    choose_status,
    table,
    width=500,
).servable()
```

#### Screenshots or screencasts of the bug in action
https://user-images.githubusercontent.com/47617499/203957624-6f988b6a-3f4d-459d-84c6-da8c37bd365a.mov

cc @maximlt

**Comment by maximlt** [comment]
Fixed on main.
