### ISSUE TITLE
Notifications example fails on Colab

### ISSUE THREAD

**Issue by lidar532** [holoviz/panel#4154]
The notifications example notebook ( [https://raw.githubusercontent.com/holoviz/panel/master/examples/reference/global/Notifications.ipynb](https://raw.githubusercontent.com/holoviz/panel/master/examples/reference/global/Notifications.ipynb) )  fails on Google Colab with this error:

```
AttributeError: '_state' object has no attribute 'notifications'
```

The colab notebook is located here: [https://drive.google.com/file/d/1eIXQiSwngVz4TCljSZfYRVpt_OsNyBN4/view?usp=sharing](https://drive.google.com/file/d/1eIXQiSwngVz4TCljSZfYRVpt_OsNyBN4/view?usp=sharing)

Screenshot:
![image](https://user-images.githubusercontent.com/6384461/204090641-3f608b5e-6416-4dd3-9ce1-791240a2c03f.png)

**Comment by philippjfr** [comment]
Colab seems to ship an old version of Panel (specifically 0.12.1). We don't have control over the default version but you can update the version with `!pip install panel==0.14.1`.
