### ISSUE TITLE
On Colab, Panel fails to display or produce sound when inside an `if (__name__ == '__main__'):`

### ISSUE THREAD

**Issue by lidar532** [holoviz/panel#4156]
I've only tested this on Colab, but probably true other notebooks as well.  When the panel object is 
executed as required for Colab as the last statement outside the `if (__name__ == '__main__'):` block it works as expected.  When it is executed last, but inside the `if` block, it doesn't produce any output and doesn't generate any apparent errors either.

```
if (__name__ == '__main__'):
  import panel as pn
  pn.extension(notifications=True)
  p = pn.pane.Markdown('#Hello World')
  print(p)
p
```
Output:
![image](https://user-images.githubusercontent.com/6384461/204168239-c0089d43-3dc5-46ba-996f-6290650c70b2.png)

Moving the 'p' inside:
```
if (__name__ == '__main__'):
  import panel as pn
  pn.extension(notifications=True)
  p = pn.pane.Markdown('#Hello World')
  print(p)
  p
```
Output:
```
Markdown(str)
```

only generates the output from the print function.  The same happens with the TextToSpeech function, and the other panel elements as well.

Software info:  Running in Google Colab.  
Browser: Windows 10 Chrome

**Comment by Hoxbro** [comment]
This has nothing to do with panel. See this simple example below: 
![image](https://user-images.githubusercontent.com/19758978/204556771-f62f9665-9ea4-4630-9e70-c556d38d2e21.png)
