### ISSUE TITLE
Decode error when authenticating with Azure AD

### ISSUE THREAD

**Issue by mhangaard** [holoviz/panel#4157]
I am trying to run a Panel app with Azure authentication, but I am getting a UnicodeDecodeError.

#### ALL software version info
python 3.9.15
panel 0.14.1
bokeh 2.4.3
requests 2.28.1
requests-oauthlib 1.3.1

Browser: Edge

#### Complete, minimal, self-contained example code that reproduces the issue

I have set all the PANEL_OAUTH_ variables and also the PANEL_COOKIE_SECRET
The `PANEL_OAUTH_REDIRECT_URI` is set to "http://localhost:5006"
PANEL_OAUTH_PROVIDER is `azure` or `azurev2` (same result)

```
import panel as pn
def authorize(user_info):
    return True
pn.config.authorize_callback = authorize
pn.serve(
    {
        '/login': pn.pane.Markdown("# Logging you in..."),
        '/': pn.pane.Markdown("# app"),
    },
    port=5006,
    allow_websocket_origin=["localhost:5006"],
)
```

#### Description of expected behavior and the observed behavior

When running `python minimal.py` I get the following console output and a 500 Internal Server Error response.
I am reproducing this locally on Ubuntu 20.04 (WSL2) and also in a docker container on Azure App Service, which is built on the official Python 3.9 image.

#### Stack traceback and console output
```
Launching server at http://localhost:5006
Uncaught exception GET /login (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/login', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/mhhn/.pyenv/versions/pe/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/mhhn/.pyenv/versions/pe/lib/python3.9/site-packages/panel/io/server.py", line 340, in get
    if config.authorize_callback and not config.authorize_callback(state.user_info):
  File "/home/mhhn/.pyenv/versions/pe/lib/python3.9/site-packages/panel/io/state.py", line 957, in user_info
    return json.loads(base64url_decode(payload_segment).decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
500 GET /login (::1) 74.84ms
```
I have not figured out what the encoding is, but it's the `.decode('utf-8')` call that is failing. I tried printing the `payload_segment` and decoding it with ascii, cp12252, windows-1252 and utf-16, but no luck so far.

**Comment by mhangaard** [comment]
Okay I guess this happened, because I encrypted the cookie. If I unset `PANEL_COOKIE_SECRET`, this doesn't happen. Maybe this is not a bug, but more a lack of documentation. There is not a lot of information in the User Guide about this: https://panel.holoviz.org/user_guide/Authentication.html#cookie-secret

**Comment by mhangaard** [comment]
Not sure this is a bug. I can no longer reproduce after clearing my cookies.

**Comment by philippjfr** [comment]
Thanks for getting back to this. Will close, but please reopen if this reoccurs.
