### ISSUE TITLE
Matplotlib pane seems to not care about dpi with Matplotlib 3.6.2

### ISSUE THREAD

**Issue by Davide-sd** [holoviz/panel#4158]
#### ALL software version info

* panel: 0.14.1
* matplotlib: 3.6.2
* notebook: 6.5.2

#### Description of expected behavior and the observed behavior

Recently I have upgraded from Matplotlib 3.5.3 to 3.6.2 and I've noticed a weird behavior when using Matplotlib pane: it doesn't seem to apply dpi anymore.

This is a screenshot produced with the code below and Matplotlib 3.5.3: note that everything is crisp. If I open the picture on a new browser window I can see it has this size: 1280x960

![Screenshot 2022-11-29 at 09-03-56 Untitled22 - Jupyter Notebook](https://user-images.githubusercontent.com/9921777/204474492-64e778c4-87a7-457f-b20e-45a46e1e1c55.png)

This is a screenshot produced with the same code and Matplotlib 3.6.2: the picture is blurry. The actual picture size is 640x480.

![Screenshot 2022-11-29 at 09-00-58 Untitled22 - Jupyter Notebook](https://user-images.githubusercontent.com/9921777/204475181-2a4ed3f0-0fb4-45e8-8c61-a10af75b5ae6.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import numpy as np
import matplotlib
from matplotlib.figure import Figure
from matplotlib import cm
import panel as pn
pn.extension()

print(matplotlib.__version__)
# 3.6.2
print(pn.__version__)
# 0.14.1

Y, X = np.mgrid[-3:3:100j, -3:3:100j]
U = -1 - X**2 + Y
V = 1 + X - Y**2
speed = np.sqrt(U*U + V*V)

fig0 = Figure()
ax0 = fig0.subplots()
strm = ax0.streamplot(X, Y, U, V, color=U, linewidth=2, cmap=cm.autumn)
fig0.colorbar(strm.lines)

mpl_pane = pn.pane.Matplotlib(fig0, width=1200, dpi=200)
mpl_pane
```

**Comment by philippjfr** [comment]
Thanks for the issue, with matplotlib 3.6.3 and current dev releases (1.0.0b2) I can no longer reproduce.
