### ISSUE TITLE
Toggle / button icons

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#4166]
Is it possible to have icons that act like `pn.widgets.Toggle` or `pn.widgets.Button`, but rather than a clunky checkbox or a button, it can simply be an icon (https://fonts.google.com/icons?selected=Material+Icons)

**Comment by philippjfr** [comment]
Duplicate of https://github.com/holoviz/panel/issues/1592

**Comment by philippjfr** [comment]
Suppose that's not really it, you can easily build a custom icon button with ReactiveHTML though. Worth adding an example.

**Comment by ahuang11** [comment]
Implemented now https://panel.holoviz.org/reference/widgets/ButtonIcon.html https://panel.holoviz.org/reference/widgets/ToggleIcon.html
