### ISSUE TITLE
Tabulator streaming sets `-` string for inital empty Dataframes

### ISSUE THREAD

**Issue by geronimogoemon** [holoviz/panel#4180]
#### ALL software version info
Python 3.9.14
panel==0.14.1
pandas==1.5.2

#### Description of expected behavior and the observed behavior
When streaming to an initial empty Tabulator the data should simply show up. Instead the cells are filled with `-` values. The issue seems very similar to https://github.com/holoviz/panel/issues/2217 but here I am trying to stream strings.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import pandas as pd
import numpy as np

pn.extension('tabulator')

different_sized_stream_df = pd.DataFrame({"column":[]})
different_sizedstream_table = pn.widgets.Tabulator(different_sized_stream_df, layout='fit_columns', width=450, height=400)

def different_sized_stream_data(follow=True):
    different_sizedstream_table.stream({"column": ["a"]}, follow=follow)

pn.state.add_periodic_callback(different_sized_stream_data, period=1000)

pn.Column(
pn.Row(different_sizedstream_table)
).servable()
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/106987324/206165761-cef8a550-1b8e-4431-ae39-16e1964539c4.png)

If I specify 
```
different_sized_stream_df = pd.DataFrame({"column":["a"]})
```
as the initial dataframe then I can see
![image](https://user-images.githubusercontent.com/106987324/206165927-90bdea21-0d18-4556-ab49-a0e754477925.png)

**Comment by philippjfr** [comment]
The problem here is that you cannot stream strings to a numeric column and since you initialized the dataframe with a list it defaults to a float dtype.
