### ISSUE TITLE
Exporting ECharts to Sphinx

### ISSUE THREAD

**Issue by riziles** [holoviz/panel#4185]
When I try to include a notebook with an EChart Pane in a Sphinx doc, I get a 404 error for 
https://cdn.jsdelivr.net/npm/echarts-gl@2.0.2/dist/echarts-gl.min.js.js

In looking at the code, it appears `.js` suffix is getting duplicated here:

https://github.com/holoviz/panel/blob/1a2be00ad34f86d49468473fd701dfe903a541c8/panel/models/echarts.py#L35-L39

**Comment by maximlt** [comment]
@riziles did you manage to fix your issue? For your information Panel's docs are built with Sphinx and [display ECharts Panes correctly](https://panel.holoviz.org/reference/panes/ECharts.html).

**Comment by riziles** [comment]
Sort of, but I'm not quite sure how. Full disclosure: I was using JupyterBook/MyST to generate the Sphinx docs. I did a couple things, and now it's working:
1. I removed the `.js` in line 38 above in my local install of Panel.
2. I was previously including `require.js` in my Sphinx config per the instructions here : https://jupyterbook.org/en/stable/interactive/interactive.html#plotly . I removed that line line.

I'm still fairly certain that JavaScript should be trying to import `echarts-gl.min.js.js`. I just don't know which of the two steps above fixed the issue.

**Comment by philippjfr** [comment]
Yeah, that require URL should **not** use the .js extension. A PR to remove it would be welcome.

**Comment by philippjfr** [comment]
Oh and two answer your question I suspect either 1. or 2. would have been enough to fix your issue.

**Comment by riziles** [comment]
I hope to get to the point yet where I'd feel confident enough to submit a PR, but I'm definitely not there yet.
