### ISSUE TITLE
Tabulator `.filters` reset when parent pane `loading`

### ISSUE THREAD

**Issue by tomascsantos** [holoviz/panel#4188]
#### ALL software version info
https://gist.github.com/tomascsantos/ef343893be02a793c18a6536507bc59a

#### Description of expected behavior and the observed behavior
Tabulator `.filters` parameter should persist when the parent `Pane.loading` is set as True. 

Currently, when `Tabulator.loading = True`, `Tabulator.filters` is persisted, but this is NOT the case when the parent pane is set as loading.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from time import sleep
import pandas as pd
import panel as pn

df = pd.DataFrame({'hi': [1, 2, 3]})

btn = pn.widgets.Button(name='set loading')

tabulator = pn.widgets.Tabulator(df, header_filters=True)
col = pn.Column('my tabulator: ', tabulator, btn)


def callback(*args):
    col.loading = True
    sleep(1)
    col.loading = False


btn.on_click(callback=callback)

col.servable()
```

#### Screenshots or screencasts of the bug in action
![tabulator_filters](https://user-images.githubusercontent.com/7690514/207110232-04733331-d6ff-450e-9cd1-bd641e3b1c48.gif)

**Comment by maximlt** [comment]
Thanks for the bug report, I could reproduce it 👍

**Comment by philippjfr** [comment]
Thanks for the bug report, can no longer reproduce in 1.0.0b2.
