### ISSUE TITLE
Dashboard issues

### ISSUE THREAD

**Issue by jbednar** [holoviz/panel#42]
I'm developing a couple of Datashader-based Panel apps/dashboards as self-contained examples and to work out some of the issues that arise in more complex settings, without getting into the added complexity of intra-plot linkages that comes with HoloViews/Bokeh plots and streams.  

The first, simple app works fine with `conda install -c pyviz  pyviz`:

   https://anaconda.org/jbednar/datashaderclifford

It has no fatal flaws and works well in both a notebook and Bokeh Server context, with simple, clean, and clear code.  It does have some non-fatal issues that I've worked around:

- [x] **Non-class version:** It doesn't seem like a class should be needed for such a simple case, and I suspect that many potential users will get put off by having to write a class from the very start.  So it would be good to have a version of this notebook that doesn't require writing a class, at least as a comparison.  Using something like ipywidgets' `interact` function might be a good approach.
- [x] **Image sizing:** I used a URL-based image (`logo  = "https://tinyurl.com/y9c2zn65/logo_stacked_s.png"`) because it works well in a notebook (avoiding issues finding a file on the filesystem) and on the server.  However, I had to put an image of the correct final size at that URL, because if I try reducing the displayed size of a larger image by embedding it in a explicit `pane.PNG(url, width=..., height=...)`, it was resized only in the notebook but it instead covered up the rest of the page on Bokeh Server.  Not sure if that's a Bokeh or Panel issue.
- [x] **Secifying a widget pane as .param**: Right now, a Panel will show widgets for a Parameterized object `c` supplied to it (as in `pp.Row(pp.Column(logo, c), c.view)`), but I found that to be quite unintuitive -- objects can have many different things one might want to use as the representation, and it's surprising that I get a set of widgets by default for object `c`.  I think it would be much clearer and more explicit if the user typed `pp.Row(pp.Column(logo, c.param), c.view)` instead, clearly laying out the widgets in the column and the graphical representation of the object in the row.

The second app needs Param and Panel master (in addition to pyviz as above), and is available at 

  https://anaconda.org/jbednar/datashaderattractors

This more complex dashboard mostly works, but there are still some fatal problems:

- [x] **No object selection**: param.ObjectSelector is meant for selecting an object from a list of allowed objects (here `attractors`), but it currently provides just one buttton, which when clicked pops up a widget box with the parameters of the existing object:
```
class Attractors(param.Parameterized):
    attractor = param.ObjectSelector(attractors["Clifford"], attractors)
```
<img src="https://user-images.githubusercontent.com/1695496/45719437-f9182400-bb65-11e8-96da-c8092e164635.png" width="50%"><br> The subobject's parameters can be then edited, but the object itself cannot be selected.  Moreover, if the object is selected manually in a different notebook cell (as e.g. `ats.attractor=attractors["Svensson"]`) the button text never updates to reflect that change (always saying "Clifford Attractor").

- [x] **No param-change batching**: When selecting different sets of known-good parameters using the `current` widget, if the new attractor object happens to be the same one that is currently being displayed, the view gets redrawn once for every parameter that is changed, which is very slow and shows bogus intermediate patterns, making the app seem buggy.  Instead there needs to be a mechanism for batching changes and updating the view only on completion.
<br>

There are also several non-fatal problems that have been worked around but which shouldn't have *had* to be worked around:

- [ ] **Subobject widgets overwrite other panes**:  I've worked around this by wrapping the `ats` parameters in a pane and explicitly selecting column-based layout, because if I don't (`pp.Row(pp.Column(logo, ats), ats.view)`), the subobject parameters overwrite the next item in the column:
![image](https://user-images.githubusercontent.com/1695496/45719749-2c0ee780-bb67-11e8-9c04-b4e7bc018c8c.png)<br> Similar issues occur in the column layout if there is anything below the main app's widgets in the column (`pp.Row(pp.Column(logo, widgets, params), ats.view)`): <br><img src="https://user-images.githubusercontent.com/1695496/45719651-d5a1a900-bb66-11e8-9072-a72cdd3ad2b9.png" width="75%"><br>Ideally the `params` object wouldn't have needed to be a parameter in Attractors at all, just provided to Panel to get some widgets, but I had to make it a Parameter so that the column layout would respect it.

- [x] **Having to use bogus parameters to force updates**: Maybe someone can think of a better way to do this, either with current Panel and Param or by adding some clean mechanism, but I found I had to add a bogus hidden parameter `parameters_changed` to achieve the behavior I wanted, which was for the display to update whenever a new `current` parameter set was changed with a widget, independently of the display updating whenever the parameters of the current attractor object were modified with widgets.  I.e., I wanted the contents of `_update_from_parameters()` to be executed when (and only when) the ParameterSet's parameters were changed, and then for `view()` to be triggered.  I couldn't see any direct way to trigger `view()`, so I added the dummy parameter and made `view()` depend on that, so that it would be triggered appropriately to get an update.  Whereas if I had put the `_update_from_parameters()` code into `view()` itself, then I found no way to know whether `view()` was triggered by an update to `params` or by an update to one of the attractor parameters.  (And the code needs to do different things in those two cases, i.e. either overwrite the attractor parameters or not.)  So it's working, but it seems like a hack and I'm not sure how to avoid it.  One could of course make `_update_from_parameters()` and `view()` *both* depend on `params.param`, but then there would be an ordering problem -- view must then always be called second, *after* the parameters have been updated.  Jean-Luc suggested we could maybe specify a precedence for such dependencies, to control the order they are run in, and that does seem like it would work in this case, but I'd hope for some less drastic solution.

- [x] **No subobject parameter editing for ClassSelector**: My first version of this app used ClassSelector rather than ObjectSelector, which does allow the type to be selected, but did not allow the subobject parameters to be selected:
![image](https://user-images.githubusercontent.com/1695496/45750821-dde4fd00-bbd5-11e8-9319-9f14418df061.png)<br>When `is_instance=True`, it behaves the same as above -- allows subobject parameters to be edited, but not allowing the class to be selected.

**Comment by lazarusA** [comment]
For the **Non-class version.** Two comments: 
1. The way you call it,  is not given the right intervals for a,b,c,d, (this is easy to change), you have a default interval. 
2. You are only allow to put one cmap, and not a set for selection. And if you pass cmap as another parameter to the function, doesn't work 👎

**Comment by jbednar** [comment]
> For the **Non-class version.** Two comments:
> 
> 1. The way you call it,  is not given the right intervals for a,b,c,d, (this is easy to change), you have a default interval.

Here's a new version that shows both how you get a default interval at first, and then specifies the intervals for a server version: https://anaconda.org/jbednar/datashadercliffordinteract

> 2. You are only allow to put one cmap, and not a set for selection. And if you pass cmap as another parameter to the function, doesn't work 👎

You should be able to pass Matplotlib colormaps (e.g. `from colorcet import cm; cm["fire"]), but Bokeh palettes are lists, which aren't hashable and don't have names.  I'm looking at ways around that...

**Comment by jbednar** [comment]
@lazarusA, I think both the issues you raised have now been fixed in current Panel and Param master; see https://anaconda.org/jbednar/datashadercliffordinteract .

**Comment by lazarusA** [comment]
@jbednar Hi, my code is not working properly, everything seems to run but once I move the sliders the plots are not updated. What is your env? or version control packages?

**Comment by jbednar** [comment]
Sorry; we briefly left Param master and Panel master in an incompatible state last night.  Should be ok now if you use the latest master of both.

**Comment by lazarusA** [comment]
Thank you. Now is working properly. Everything looks fine ! 👍
