### ISSUE TITLE
Make panelite notebook installs specific to the packages that are imported

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4209]
All over the place generic `micropip.install`s are made. An example is shown below

![image](https://user-images.githubusercontent.com/42288570/208231789-867ff792-6f2b-45d9-8768-94cf6347385b.png)

This slows down the notebook when loading. It might also lead some newbies to think that these `install`s are needed.

Please make the installs specific.

## Additional Context

If you tell me this would be beneficial @philippjfr I would try to find the time to clean up. Right now my guess is you did it this way due to not having enough time to specialize the installs across all notebooks?

**Comment by MarcSkovMadsen** [comment]
After looking at the panel code I believe its the code below that has to be improved such that the imports depends on the notebook

![image](https://user-images.githubusercontent.com/42288570/208232063-2dab48b6-4afb-4d3b-993f-7bd68a724cc0.png)

**Comment by MarcSkovMadsen** [comment]
My recommendation would be to make this specific by including it in the notebook.

Currently it takes 28 secs for me to `piplite.install` the `Notifications.ipynb` notebook. Something that makes the notebook almost not useful. And if you have a slow internet connection or device its even worse.

![image](https://user-images.githubusercontent.com/42288570/216773960-8f624fdb-58e2-4067-a979-a33e5838e5d1.png)

I would recommend making the notebooks specific. Something like

```
import sys

if "pyodide" in sys.modules and "IPython" in sys.modules:
    import piplite
    await piplite.install(['panel'])
```

This takes less than 3 secs on my laptop, which is very usable.

**Comment by MarcSkovMadsen** [comment]
Would you accept a PR with a change like this across notebooks @philippjfr ? I would also clean up the existing code that adds the big, generel `piplite.install`.

**Comment by philippjfr** [comment]
If you have a good solution for this problem i would to see a PR yes.
