### ISSUE TITLE
The penguins example at the top of the home page shows an error 500.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4215]
The penguins example at the top of the home page shows an error 500.

https://penguin-crossfilter.pyviz.demo.anaconda.com/penguin_crossfilter

![image](https://user-images.githubusercontent.com/42288570/208252702-fc1ce7da-e73f-4cf4-895e-37a37b3da96c.png)

**Comment by philippjfr** [comment]
Should be back up now and will also modernize it with the rest of the apps.
