### ISSUE TITLE
Make it easy to bring your own functions independent of HoloViz and add caching

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4220]
The promise of the recommended `pn.bind` api is that you can bring already existing functions and very easily use them Panel and the HoloViz ecosystem.

If you want to add caching Panel provides `pn.cache`. But at the moment there is no easy way to apply the caching unless you define and cache new functions on top of the existing functions.

```bash
def plot(year):
    ...

@pn.cache
def new_plot(year):
    return plot(year)

new_plot = pn.bind(new_plot, year)
```

It would be very helpful and simple to be able to do for example 

```bash
plot = pn.bind(pn.cache(plot), year)
```

**Comment by philippjfr** [comment]
Closing as this has always been supported and no further details have been provided.
