### ISSUE TITLE
pn.cache not working on class method

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4232]
panel==0.14.2

I'm trying to help a user develop an efficient architecture when having a expensive computation.

I wanted to use `pn.cache` on a class method. But it seems not to work.

```python
import param
import panel as pn

pn.extension()

class Model(param.Parameterized):
    data = param.Parameter(1)

    def expensive_update(self, value):
        print("expensive!")
        self.data = self.expensive_calculation(value)
        print(self.data)

    @pn.cache()
    def expensive_calculation(self, value):
        return 2*value

model=Model()
model.expensive_update(2)
```

```bash
$ python script2.py
expensive!
Traceback (most recent call last):
  File "/home/jovyan/repos/private/hvplot/script2.py", line 19, in <module>
    model.expensive_update(2)
  File "/home/jovyan/repos/private/hvplot/script2.py", line 11, in expensive_update
    self.data = self.expensive_calculation(value)
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/panel/io/cache.py", line 336, in wrapped_func
    dinfo = getattr(wrapped_func, '_dinfo')
AttributeError: 'function' object has no attribute '_dinfo'
```

**Comment by Hoxbro** [comment]
Not saying this should not happen, but I just want to make people aware that this could lead to memory leaks if not handled correctly. I haven't looked at the code to see if this is an actual problem. 

Ref: https://stackoverflow.com/questions/33672412/python-functools-lru-cache-with-instance-methods-release-object

**Comment by philippjfr** [comment]
@Hoxbro That is not a concern for us, `cache` does not hash on the method but rather on a hash of the class name, module name and method name.
