### ISSUE TITLE
Ability to use a local cdn in panel

### ISSUE THREAD

**Issue by govinda18** [holoviz/panel#4257]
#### Is your feature request related to a problem? Please describe.
Panel currently uses holoviz.cdn for assets that is potentially vulnerable for a closed network environment. It will be helpful if panel can provide a way to use a local cdn network instead.

It will be on the local cdn ofcourse to ensure all the assets are available.

#### Describe the solution you'd like
Some parameter to panel serve or pn.extension to override the default cdn in panel should be good.

**Comment by philippjfr** [comment]
@govinda18 A little confused here, by default Panel will use the local server to serve the assets it only switches to CDN resources if you request it. Is there really any benefit to standing up a separate CDN locally?

**Comment by philippjfr** [comment]
Closing since Panel serves local resources by default and no further explanation was provided.

**Comment by govinda18** [comment]
Hi @philippjfr 

Apologies, missed this one. The idea here was to avoid picking any calls to external cdn such cdn.holoviz.com and serve all resources via a local cdn. Jupyter and other OSS frameworks also provide a way to be able to do this. This primarily helps improving load times in an intranet environment and also avoids any potential security concerns.

One example is the ability to override cdn url here - https://github.com/holoviz/panel/blob/0957973c76f430f587b09786ad387100f3349740/panel/io/resources.py#L67.

**Comment by govinda18** [comment]
Noting that this request is not meant to fire up a different cdn server for local assets but to be able to use a different cdn host for assets loaded from unpkg, jsdeliver or cdn.holoviz

**Comment by philippjfr** [comment]
I'm still unclear why, if you are concerned about security, you would use a CDN at all when you can just use the default server resources. That said I'm happy to reenable support for other CDNs.

**Comment by govinda18** [comment]
Hmm, let me think it through a bit and check it again. The default server was not serving all the required assets afair but let me frame the problem a bit better and get back.
Thanks for your response @philippjfr
