### ISSUE TITLE
Images overlap plots in GridSpec

### ISSUE THREAD

**Issue by droumis** [holoviz/panel#4268]
#### ALL software version info
panel v0.14.2

#### Description of expected behavior and the observed behavior
When plotting an image after a plot in a GridSpec, the image overlaps with the plot. I would have expected that the images would be stretched to fit into their assigned grid cells. Using sizing_mode='stretch_both' makes it worse. 

#### Complete, minimal, self-contained example code that reproduces the issue
```
import panel as pn
from bokeh.plotting import figure

p1 = figure(width=300, height=300)
p1.line([1, 2, 3], [1, 2, 3])

gridspec = pn.GridSpec()

gridspec[1, 0:2] = p1

gridspec[0, 0:2] = 'https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png'

gridspec
```
<img width="793" alt="image" src="https://user-images.githubusercontent.com/6613202/211544779-8273948b-4717-4797-a5f2-daa18751f22c.png">

Using `sizing_mode='stretch_both'`:

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/6613202/211545318-62aa0a7f-7ba4-4bd4-8bc3-99cc2bfef649.png">

**Comment by philippjfr** [comment]
This is a known issue (although I can't find the earlier issue about this) and is related to the bokeh layout engine. This should be resolved automatically once we upgrade to Bokeh 3.0 with the new layout engine.
