### ISSUE TITLE
Deprecate YT pane

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4273]
There is an YT pane but no reference guide. Please add it

https://panel.holoviz.org/api/panel.pane.html#panel.pane.plot.YT

**Comment by philippjfr** [comment]
Honestly -0 on adding it. It's a niche, domain specific, library and a simple Matplotlib wrapper. I think there are many such small compatibility wrappers that we should support but not necessarily document.

**Comment by MarcSkovMadsen** [comment]
Should the YT pane be removed then?

**Comment by MarcSkovMadsen** [comment]
But dont we at least need to list the (most interesting) Python objects that work with Panel. 

Right now search engines and chat bots have no way to aquire the knowledge. And users searching for  support and examples have no way of finding it.
