### ISSUE TITLE
File browser widget

### ISSUE THREAD

**Issue by kcpevey** [holoviz/panel#430]
The FileInput widget will automatically load a file into memory when a file is selected. However, sometimes there is a need to select one (or more files), do some other things, then trigger a load for all the files at once with the load being something I code on my end. Basically, I need a simple file browser that allows users to navigate to local files and store filepaths as strings. It seems like the FileInput has much of that functionality, but I don't want it to automatically load the files and I'd like the ability to set a default. And in reality, it would be nice as a param widget so I can use param.depends on it instead of a workaround.   
  
Is there any way to get this functionality out of the existing widgets?

**Comment by philippjfr** [comment]
This has been requested a few times and the [intake GUI](https://github.com/intake/intake/tree/master/intake/gui) already has some component like this, so it's just a matter of someone writing a panel version. You could probably build something from existing widgets but it may not be worth it.

**Comment by jbednar** [comment]
Doesn't `param.Filename` already work this way?

**Comment by kcpevey** [comment]
@jbednar The `param.Filename` is just a string textbox with no browser functionality. It checks for validity but doesn't allow users to navigate to a local file.   
  
![image](https://user-images.githubusercontent.com/15659110/57638670-e2e72a00-7573-11e9-8ca7-c0c96ed9534f.png)

**Comment by kcpevey** [comment]
I'll check out the intake gui

**Comment by jbednar** [comment]
Ok, sounds like the Param support is there already, but the corresponding mapping to a usable widget is missing from Panel.  I _think_ there were already widgets for Filename in ParamTk and/or ParamNB, but I may be misremembering.

**Comment by joelostblom** [comment]
In addition to being able to choose one or many files, it would be great to be able to choose one or many folders and return their names. This would be useful when searching recursively within multiple subfolders, which cannot be achieved via file multiselection.

Being able to filter on file extensions to only display certain file types when browsing could also be useful.

**Comment by joelostblom** [comment]
I just noticed that the ability to return the filename has been implemented in the Bokeh version of the FileInput widget https://github.com/bokeh/bokeh/pull/9100
