### ISSUE TITLE
Plotly behavior changing when included in panel in notebook 

### ISSUE THREAD

**Issue by rfenouil** [holoviz/panel#4304]
Thank you for the great work on panel, love it so far.

While playing with Plotly scatterplots in a jupyterlab notebook, I noticed a different behavior of selection tools when I do a simple `fig.show()` or include the figure in a plotly pane.
Outside of the pane, the selection tools have handles to modify selection, and it is possible to move selection over the area.
When included in the Plotly pane, the selection is fixed.

I don't really understand how panel works but I suspect my notebook uses different Plotly versions (on the javascript side ?) between the pane-included figure and the `fig.show()` call.
Not sure how two versions can coexist in the same notebook/client though... 

```
trace_points = go.Scattergl(x=np.random.normal(size=100), 
                            y=np.random.normal(size=100), 
                            mode='markers')

layout = go.Layout(title="Title Fig", 
                   width=500,
                   height=500)
```

![Screenshot from 2023-01-20 10-33-06](https://user-images.githubusercontent.com/35697321/213663495-23e08bda-57b2-4599-96ae-c4d28aa4402f.png) 

![Screenshot from 2023-01-20 10-33-12](https://user-images.githubusercontent.com/35697321/213663491-6588abf0-7a92-42fd-ac33-d74da1ed74f4.png) 

Actually got the answer regarding plotly.js versions when doing the screen captures...

Could you please explain whether we can synchronize both versions, or if there is a way to update the version used in panel ?

Thank you for your help !

My notebook setup:
numpy==1.23.5
pandas==1.5.2
panel==0.14.2
plotly==5.11.0

**Comment by MarcSkovMadsen** [comment]
Hi @rfenouil 

Thanks for posting the issue. Could you please provide a *minimum, reproducible* example. It makes it much, much faster to reproduce the issue and try to fix it. Thanks.

**Comment by MarcSkovMadsen** [comment]
You could try running something like

```python
from panel.models import PlotlyPlot
PlotlyPlot.__javascript_raw__[1]='https://cdn.plot.ly/plotly-2.16.1.min.js'
PlotlyPlot.__js_require__["paths"]["plot"]='https://cdn.plot.ly/plotly-2.16.1.min.js'
```

before you run `pn.extension()` to use a specific version of plotly.js.

You can see that the version is defined here https://github.com/holoviz/panel/blob/b7dc4589e29bd4733a53e9ec0c75c4f055cc2164/panel/models/plotly.py#L21.

**Comment by rfenouil** [comment]
Hello @MarcSkovMadsen thank you for your answer.

Your suggestion allows me to use a more up-to-date version of plotly.js which is great !
I thought it would also require the adaptation of the associated python wrappers in panel or so... but apparently not :)

I will close this issue, but probably open other ones in the coming days regarding plotly integration and interactivity.

Thank you again !!
