### ISSUE TITLE
Feature request: source code views

### ISSUE THREAD

**Issue by stuartarchibald** [holoviz/panel#431]
This is a feature request for this sort of use case... please feel free to edit any part of this (title included) so it makes sense!

[Numba](https://github.com/numba/numba) compiles Python source code to machine code just-in-time. The Numba compilation pipeline has potentially useful intermediate output, for users debugging logic and performance problems, approximately as follows (IR = intermediate representation, LLVM=http://llvm.org):

`python source` -> `numba IR` -> `LLVM IR` -> `hardware specific assembly code`

Assuming it becomes possible to track line numbers from the Python source through to the assembly code, it'd be great to have the ability to display multiple source code representations side by side (as they are all technically translations of one another) and have them lined up and/or highlighted based on line number.

Horrible ASCII art picture:

```
|-----------------|-----------------------------------------------|-----------|-------------|
| # Python source | # Numba IR                                    | # LLVM IR | # Assembler |
| def foo(x):     | x = arg(0, name=x)  :: int64                  |   Not     |     Or      |
|  return x + 1   | $const0.2 = const(int, 1)  :: Literal[int](1) |   Writing |     This!   |
|                 | $0.3 = x + $const0.2  :: int64                |   This!   |             |
|                 | del x                                         |           |             |
|                 | del $const0.2                                 |           |             |
|                 | $0.4 = cast(value=$0.3)  :: int64             |           |             |
|                 | del $0.3                                      |           |             |
|                 | return $0.4                                   |           |             |
|-----------------|-----------------------------------------------|-----------|-------------|
```

Thanks!

As an addendum, were "source code display" to work in general, it'd be very helpful to be able to have a custom highlighting map for the source so that e.g. assembler instructions can be colour graded based on their potential performance. It'd also be great to have the ability to "hover" over some text in `LLVM IR` or `Assembler` view and be able to pop up a box with some supplied information about the instruction.

**Comment by MarcSkovMadsen** [comment]
Since there has been no real activity on this for 2 years and it seems a bit out of scope for the core of Panel I close this open. I could have its place as a custom component though. Feel free to reopen.

**Comment by philippjfr** [comment]
I originally asked for this to be opened so I do feel a bit bad to see this closed. I do agree this one is better implemented as a custom extension though.

**Comment by stuartarchibald** [comment]
Is there somewhere that tracks things that ought to go into extensions/ideas for extensions?
