### ISSUE TITLE
Cannot import js files in Jupyterlab when combining panel and hvplot.pandas

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4312]
panel==0.14.2, hvplot==0.8.2, pandas==1.5.3, holoviews==1.15.1, jupyterlab 3.5.0, ipykernel==6.17.0, ipywidgets==8.0.2

I was trying to create a `Modal` for a user on discourse. During testing I found that I had trouble importing the needed js library in Jupyterlab. 

It was pretty hard to nail down the issue and find a [workaround](https://github.com/awesome-panel/panel-modal/blob/02dbcf9e4b492f98cb0cc5884169a527c0dcb3f8/src/panel_modal/modal.py#L189) for.

https://user-images.githubusercontent.com/42288570/213903157-53244a7c-45a5-4f66-bfd8-2999879e7449.mp4

## Does not work

- Start with a clean jupyterlab and notebook
- Put the code below in a cell
- Restart the kernel and run all cells.
- Go to the browser console and verify the `A11yDialog` is not available

```python
import panel as pn
import hvplot.pandas  # noqa
import pandas as pd

pn.config.js_files["hello"]="https://cdn.jsdelivr.net/npm/a11y-dialog@7/dist/a11y-dialog.min.js"
pn.extension(sizing_mode="stretch_width")
```

## Works

Same steps as before but here the `A11yDialog` is available.

```python
import panel as pn
# import hvplot.pandas  # noqa
# import pandas as pd

pn.config.js_files["hello"]="https://cdn.jsdelivr.net/npm/a11y-dialog@7/dist/a11y-dialog.min.js"
pn.extension(sizing_mode="stretch_width")
```

## Additional Context

- I see the same problem when using `__javascript__` files in `ReactiveHTML`. This was where I initially saw the issue.
- I don't thee the problem when running on a server with `panel serve`.

**Comment by philippjfr** [comment]
The issue is running `hvplot.pandas` before the extension. I can re-add a warning about this.

**Comment by MarcSkovMadsen** [comment]
But my understanding is that pep8 wants you to have imports at the top. Then you can run pn.extension afterwards. Every linter would screem if not done this way signaling that hvplot is for exploration but not production. If they could automatic import formaters would also Nice hvplot.pandas before pn.extension.

**Comment by philippjfr** [comment]
I have never seen anyone use an isort linter on a notebook.

**Comment by MarcSkovMadsen** [comment]
I am not talking about notebooks. I seldom using them. I'm talking about python scripts 😉

**Comment by MarcSkovMadsen** [comment]
Hmm. I write the same code in a notebook as I do in a Python script. Thought that was the natural thing to do?

**Comment by philippjfr** [comment]
As a matter of principle I don't disagree, but without re-architecting extension handling entirely (which may be done eventually), this is the only feasible approach that doesn't dump huge amounts of unnecessary JS/CSS in a notebook.
