### ISSUE TITLE
Consider introducing signalling API

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#433]
In Panel we now have multiple approaches for defining callbacks, each with their own drawbacks. The watch callbacks are the lowest level and therefore most versatile approach to defining callbacks but it is very easy to end up with a horrible amount of complexity if you define a lot of callbacks. Various GUI toolkits have solved this in different ways. Qt, for example, has a signaling  API where you define a signal by name and then you can connect to those signals by name. This is a powerful way to group and keep track of callbacks and reduces the amount of complexity a user has to keep track of. As part of the [dfviz](https://github.com/martindurant/dfviz) project to build a GUI on top of Panel, @martindurant implemented a basic signaling mechanism by defining a simple [SigSlot class](https://github.com/martindurant/dfviz/blob/master/dfviz/widget.py#L20). This implementation may need a little while to iron out various kinks but in the long run we should consider whether to include an example like that in the docs or even ship a mix-in class like the one defined there.

**Comment by rsignell-usgs** [comment]
Do we still advocate using `sigslot` for complex panel applications?

**Comment by martindurant** [comment]
`SigSlot` was never explicitly advocated, although I thought it well matched my way of thinking about GUI elements (obviously). There are many ways to pass messages in Panel, and it very much depends on the type of application you are building and the style you like to use. I would go as far as to say that `SigSlot` is one valid and useful way to do this. Is that advocating?

**Comment by MarcSkovMadsen** [comment]
As there has been no real activity on this for 1½ years and Panel already have 5 different event/ signal apis, I propose closing this one. Feel free to reopen.
