### ISSUE TITLE
CrossSelector filter does not filter options

### ISSUE THREAD

**Issue by SRGDamia1** [holoviz/panel#4337]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
Windows 11
python: 3.9.15
bokeh: 2.4.3
panel: 0.14.2

#### Description of expected behavior and the observed behavior
Typing text into the filter field of the cross-selector has no effect.  It doesn't even work on the example code from the CrossSelector page

#### Complete, minimal, self-contained example code that reproduces the issue

```
cross_selector = pn.widgets.CrossSelector(name='Fruits', value=['Apple', 'Pear'], 
    options=['Apple', 'Banana', 'Pear', 'Strawberry'])

cross_selector
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/5374350/214919404-37f092e3-6d38-4b6c-aed1-262d08c29832.png)

**Comment by philippjfr** [comment]
Does seem to work for me, however it only triggers when you press enter or give focus to some other component. We should switch the callback from `value` -> `value_input` so the filtering occurs on every keystroke.
