### ISSUE TITLE
Cross Selectors overlap when created from parameters

### ISSUE THREAD

**Issue by SRGDamia1** [holoviz/panel#4338]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
Windows 11
python: 3.9.15
bokeh: 2.4.3
panel: 0.14.2

#### Description of expected behavior and the observed behavior
When converting parameters into cross-selector widgets, the created widgets overlap.  

#### Complete, minimal, self-contained example code that reproduces the issue

```
class Produce(param.Parameterized):
    fruits=param.ListSelector(
                label="Fruits",
                objects=['Apple', 'Banana', 'Pear', 'Strawberry'],
                default=['Apple', 'Pear'],
            )
    veggies=param.ListSelector(
                label="Veggies",
                objects=['Broccoli', 'Green Beans', 'Carrots', 'Lima Beans'],
                default=['Broccoli', 'Carrots'],
            )
pn.Row(
    pn.Param(Produce.param.fruits,widgets={"fruits": pn.widgets.CrossSelector}),
    pn.Param(Produce.param.veggies,widgets={"veggies": pn.widgets.CrossSelector})
)
```

#### Screenshots or screencasts of the bug in action
With the code from above, the two cross selectors overlap, so the selected of the first is covered by the not-selected of the first.
![image](https://user-images.githubusercontent.com/5374350/214923036-68b666f2-b33e-4a9c-a39d-12d0e68fcf0c.png)

If the widgets are made from a single call to pn.Param, they overlap vertically:
![image](https://user-images.githubusercontent.com/5374350/214923492-77b30f1f-f4c3-41ff-bf2f-a46e282ef248.png)

If the CrossSelector widgets are made without parameters, the output is fine:
![image](https://user-images.githubusercontent.com/5374350/214923224-6ff1841d-659b-4685-9734-891e9d0c9c23.png)

**Comment by philippjfr** [comment]
With the upgrade to Bokeh 3.x and the release of Panel 1.0 problems like this should resolve automatically because Bokeh uses a new layout engine.

**Comment by philippjfr** [comment]
Indeed, this is fixed in main.
