### ISSUE TITLE
Better error message when passing pd.NA to Perspective

### ISSUE THREAD

**Issue by riziles** [holoviz/panel#4362]
#### Is your feature request related to a problem? Please describe.
When passing pd.NA to Perspective, Panel throws an error `module 'numpy' has no attribute 'float'`. The issue is easy enough to work around, but it took a while to troubleshoot because of the misleading error message. `np.float` was deprecated in 1.20.0 and removed in 1.24.1.

Apologies if this has already been reported or addressed!

#### Describe the solution you'd like
Please remove the reference to `np.float`.

#### Describe alternatives you've considered
It's very easy to workaround but .challenging to troubleshoot.

#### Additional context
Sample code:
```python
pn.pane.Perspective(
    pd.DataFrame([[pd.NA, 1.0]])
)
```

**Comment by maximlt** [comment]
Thanks for reporting that!
