### ISSUE TITLE
Tabulator row selection does not persist when changing pages

### ISSUE THREAD

**Issue by CrashLandonB** [holoviz/panel#4367]
MRE:
```
import panel
import pandas
import numpy

data = numpy.random.random((300,6))
df = pandas.DataFrame(data)
tab = panel.widgets.Tabulator(value=df, sizing_mode='fixed', disabled=True, pagination='remote', page_size=25,
                              selectable='checkbox', header_filters=True)
panel.serve(tab)
```

With the example above, if I select a few rows, change pages, select a few more rows, and return to the original page, I don’t see the rows selected any longer.

The MRE above seems to recreate the issue with 300 rows.  I intend to use this on a data set with around 100,000 rows.

(FYI, relevant conversation and confirmation that others have seen the issue available [here](https://discourse.holoviz.org/t/selection-of-rows-is-not-persisted-when-tabulator-is-sorted/2961/7))

**Comment by philippjfr** [comment]
Thanks @CrashLandonB. Agree that this may be nice however we intentionally did not implement this as relying on it seems somewhat error prone. Basically my concern here is that selections reset if you don't press `Ctrl`/`Shift` while selecting a new row and if you are on a different page you have zero visibility on whether you accidentally reset your selection. Very open to suggestions on improving the UX around selections though.

**Comment by CrashLandonB** [comment]
@philippjfr Interesting point about the `Ctrl/Shift`; I can see that could be error prone.  With the settings above in the MRE, I was just using the `checkbox` method, so hadn't even thought that far ahead.  

In my head, I was equating the `selectable` function to the idea of simply having another column in my DataFrame that I might call "Selected" and just toggle the value between True or False.  Perhaps that might be my best option for my current task, requiring a little more deliberate and traceable action from the user.  

But to your question, I'd say `Ctrl/Shift` is commonly-used in very-fleeting cases of item selection, and I agree that seems error prone.  I suppose my main feedback then is that it seems counter-intuitive that the selections are not persisting.  I'd lean more-towards letting them have "enough rope to hang themselves with".  Perhaps a risk mitigation would be, when items are selected, an indicator of "total selected items" count would be show somewhere by default?  (Excel kind of does this, for example)

I've also realized that even if I made my selections, I don't see a means to filter the table to "selected rows", right?  I definitely want to do this, so my best approach might be to simply give the users that extra "selected" column, let them manually change that value, and then use the header filtering to let the user collapse it to selected rows.

**Comment by CrashLandonB** [comment]
Sounds good.  I think I have an alternate approach with Tabulator to get the job done, but I'll certainly look forward to seeing the change if you proceed.  Thanks!

**Comment by orangeSi** [comment]
> Sounds good. I think I have an alternate approach with Tabulator to get the job done, but I'll certainly look forward to seeing the change if you proceed. Thanks!
Could you share the alternate approach ? I just encounter the same question as you now~
