### ISSUE TITLE
Images in VideoStream notebook not found

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4373]
Just checking the new videostream in the Gallery. Unfortunately the images are not found.

https://panel.holoviz.org/gallery/streaming/streaming_videostream.html

![image](https://user-images.githubusercontent.com/42288570/215836748-1a4d3ad2-3199-4a44-bb95-20834ae1c471.png)

For example it cannot find the image https://panel.holoviz.org/gallery/streaming/assets/VideoStreamInterfaceSobel.jpg

Only @philippjfr can fix.

**Comment by philippjfr** [comment]
Actually, anyone with push access can correct since we still host the docs on the gh-pages branch.

**Comment by philippjfr** [comment]
I'm very confused why it turned `../../assets/VideoStreamInterfaceSobel.jpg` into `assets/VideoStreamInterfaceSobel.jpg`. @maximlt any idea?

**Comment by philippjfr** [comment]
Manually fixed for now but have to figure out why sphinx mangled the relative path.

**Comment by philippjfr** [comment]
Have to patch the thumbnail as well: <img width="203" alt="Screen Shot 2023-01-31 at 19 07 48" src="https://user-images.githubusercontent.com/1550771/215846203-f8d52213-3b4c-4ddd-a326-09d9c0dc7e5a.png">

**Comment by maximlt** [comment]
There's a bit of code in `nbsite` that "fixes" assets links. Maybe it's coming from that?

https://github.com/pyviz-dev/nbsite/blob/fc98519cf0e6b5793b1e2de89b4f2265d7df4f21/scripts/nbsite_fix_links.py#L115-L124

How do you manually fix that? Pushing directly the fix to the *gh-pages* branch?

**Comment by philippjfr** [comment]
Already did, but will have to redo it once the new build is done.

**Comment by MarcSkovMadsen** [comment]
> Actually, anyone with push access can correct since we still host the docs on the gh-pages branch.

What do you mean here @philippjfr . Which branch can a contributer push to, to fix docs?

**Comment by philippjfr** [comment]
Anyone can make a PR against the gh-pages branch.

**Comment by MarcSkovMadsen** [comment]
Its also an issue for the VuePDBInput example https://panel.holoviz.org/gallery/components/VuePdbInput.html

![image](https://user-images.githubusercontent.com/42288570/228740905-a1baeea7-74ab-4e08-b6b1-471b235ae7a7.png)
