### ISSUE TITLE
ColorPicker issues on the branch 1.0

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#4385]
- [ ] Unnamed ColorPicker has an "inner" zero width
![image](https://user-images.githubusercontent.com/35924738/216478983-09f33d97-bf90-4575-aab2-e74c8f269478.png)

Might be an issue shared with other components?

**Comment by philippjfr** [comment]
I've generally had to set some default width. For other components I've just set `param.Integer(default=300)` (which should all be reviewed and cleaned up). I'm not sure whether a colorpicker really needs that wide a default width.

**Comment by maximlt** [comment]
300px wide feels a little to wide indeed. Apparently a width of 56px makes the colored part square.

![image](https://user-images.githubusercontent.com/35924738/216985968-bc0c3829-e5f0-4f31-a29a-7a714ba8e833.png)

An alternative would be not to have any padding around the colored part. If so, I guess such a change would make more sense if applied directly in Bokeh.

 > For other components I've just set param.Integer(default=300) (which should all be reviewed and cleaned up).
 
 Yes indeed reviewing that seems important, I'll open an issue to keep track of it, too easy to forget! Would it make sense to make that width configurable at a global level?
