### ISSUE TITLE
Notifications not working in Panelite

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4387]
I was trying to get started on improving the User Experience of Panelite in #4209.

The first thing I see is that the `notifications` work in the notebook, but not the Panelite notebook.

If you run the reference notebook you get

![image](https://user-images.githubusercontent.com/42288570/216775362-5db96e82-c3cf-498a-9a23-016058cdd525.png)

**Comment by philippjfr** [comment]
Works correctly on https://pyviz-dev.github.io/panelite-dev/lab/index.html
