### ISSUE TITLE
DeckGl notebook not working in Panelite: 

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4390]
For some unknown reason I cannot import `panel`+`pydeck` in the existing `DeckGL` notebook if I go directly to this notebook and open it, then it just loads for ever. If I look in the developer console there are errors.

![image](https://user-images.githubusercontent.com/42288570/216780387-3d37f27b-6a47-4dc0-8a9c-39766569d8c0.png)

```bash
kernel.ts:49 
        
       Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/_pyodide/_base.py", line 531, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 357, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 3, in <module>
OSError: [Errno 28] Invalid argument: 'reference/panes'

    at new_error (cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.js:10:179954)
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at method_call_trampoline (cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.js:10:229349)
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.wasm
    at Module.callPyObjectKwargs (cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.js:10:123403)
    at Module.callPyObject (cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.js:10:123781)
    at wrapper (cdn.jsdelivr.net/pyodide/v0.22.0/full/pyodide.asm.js:10:219389)
```

The funny thing is that I can install it in a new notebook.

![image](https://user-images.githubusercontent.com/42288570/216780014-e964f032-eddd-42d7-a791-b6d200621a23.png)

The funny thing is, if I navigate to some other notebook in the `reference/panes` folder and then to the DeckGL notebook, then I can install `panel`+`pydeck`.

**Comment by MarcSkovMadsen** [comment]
I can see the issue now affect all notebooks. I can no longer run then. Also if I do a *hard refresh* ???

**Comment by philippjfr** [comment]
Can't reproduce any problems for most notebooks, pydeck won't install last I checked because it tries to pull in tornado.

**Comment by philippjfr** [comment]
Actually even the DeckGL notebooks works just fine for me.

**Comment by philippjfr** [comment]
Yup, even after clearing all caches and site data there is no issue for me.

**Comment by MarcSkovMadsen** [comment]
My hypothesis is that using a direct link like https://panelite.holoviz.org/lab/index.html?path=reference/panes/DataFrame.ipynb to a notebook in a subfolder caused the issue. Somehow it changed the `root` folder to `reference/panes` such that navigating from the original folder to `reference/panes` no longer makes sense?

(See also https://github.com/jupyterlite/jupyterlite/discussions/379#discussioncomment-1457817)

**Comment by philippjfr** [comment]
Yep, I'd bet that's it.

**Comment by MarcSkovMadsen** [comment]
I fixed it by closing down my browser windows.

I tried to replicate the issue in a another browser (Firefox) but could not. I would have liked to file an issue with Jupyterlite.

I will close the issue for now. But reopen if I experience again and can replicate the issue.

**Comment by MarcSkovMadsen** [comment]
I decided to file the issue here https://github.com/jupyterlite/jupyterlite/issues/973.

**Comment by philippjfr** [comment]
Excellently crafted bug report, annoying you can't reproduce.

**Comment by MarcSkovMadsen** [comment]
I would really love to be able to share direct links from documentation, social events, when supporting colleagues online and at conferences.
