### ISSUE TITLE
Str.object not updating in Panelite in chromium browsers

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4396]
Panelite==0.14.3

When I open and run the reference/panes/Str.ipynb notebook, the output in cell 3 does not update when I change the `object` in cell 4.

![image](https://user-images.githubusercontent.com/42288570/216802768-66b3eec4-0342-49fd-8882-ffd54cc42a6d.png)

## Additional Context

I just tried in a *normal* jupyter notebook (not Panelite) and there it works.

![image](https://user-images.githubusercontent.com/42288570/216802814-a6029de3-078e-419e-ae6a-f117a1d8c004.png)

**Comment by MarcSkovMadsen** [comment]
I believe there is a more general issue. For example when i set `vtk_pane.object` in reference/panes/VTKJS.ipynb it does not update either.

https://user-images.githubusercontent.com/42288570/216804397-23d05727-71c0-4360-bc32-106120672285.mp4

Note: Due to CORS issues (?) I've changed the url to `vtk_pane.object = "https://raw.githubusercontent.com/Kitware/vtk-js-datasets/master/data/vtkjs/TBarAssembly.vtkjs"`

**Comment by MarcSkovMadsen** [comment]
For example the Terminal widget in reference/widgets/Terminal.ipynb does not update either

![image](https://user-images.githubusercontent.com/42288570/216840166-d70cf261-f706-457d-89b1-b2df48b8c150.png)

**Comment by MarcSkovMadsen** [comment]
I can now see that 

- There is no issue in Firefox. Only Edge and Chrome.
- If I rerun the cell that does not update initially then it starts working. This seems related to https://github.com/holoviz/panel/issues/4416

## Edge

https://user-images.githubusercontent.com/42288570/217330885-3fad0718-336a-429b-b411-c8d8576c3d8f.mp4

## Chrome

https://user-images.githubusercontent.com/42288570/217331053-1f00f8ee-3770-4dc5-9ad1-490658979f2f.mp4

## Firefox

https://user-images.githubusercontent.com/42288570/217331136-a392e99e-1aa9-4d77-93ca-6f7700dbb450.mp4

**Comment by philippjfr** [comment]
Cannot reproduce any of these issues (except VTKJS which is caused by something else).
