### ISSUE TITLE
CrossSelector not working in Panelite: 

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4398]
Panelite==0.14.3

Open reference/widgets/CrossSelector.ipynb. Execute the cells.

Try to use the `<<` or `>>` buttons to select/ unselect items. It does not work and there are errors in the console.

![image](https://user-images.githubusercontent.com/42288570/216807257-6dbe4ec5-8341-44ab-bbc5-67c088d89bfb.png)

```bash
Uncaught Error: reference {"id":"1009"} isn't known (not in Document?)
```

**Comment by philippjfr** [comment]
Appears to be fixed on https://pyviz-dev.github.io/panelite-dev/lab/index.html
