### ISSUE TITLE
IpyWidgets issues on the branch 1.0

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#4410]
**Notebook**

- [x] Widgets are not correctly rendered

![image](https://user-images.githubusercontent.com/35924738/217035165-f6d25a25-c9e0-4660-8b03-685655e9383b.png)

**Server**

- [x] `ipywidgets_bokeh` doesn't yet support Bokeh 3, Simon opened a PR to make it install-able with Bokeh 3 (https://github.com/bokeh/ipywidgets_bokeh/pull/77), but there seems to be remaining errors

**Comment by philippjfr** [comment]
ipywidgets_bokeh 1.4.0dev3 resolves remaining issues.
