### ISSUE TITLE
Getting_Started.ipynb cell 3 not working in Panelite in Edge Browser

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4416]
Panelite=0.14.3, OS=Windows

I'm trying the notebook Getting_Started.ipynb in Panelite. Unfortunately cell 3 does not work the first time the cell is executed. If I executed it a second time the communication starts working and the component works. See the video below.

I can only replicate this in Edge. Not Chrome or Firefox.

https://user-images.githubusercontent.com/42288570/217323659-87d7279e-dd4d-40e7-b11a-3abedc3dec12.mp4

**Comment by MarcSkovMadsen** [comment]
There is a similar issue in the user_guide/Async_and_Concurrency.ipynb notebook. The first time cell 3 is executed it does not work. The second time it does work.

https://user-images.githubusercontent.com/42288570/217326529-e0730f98-9fd6-4106-8a37-ad1929eb6e47.mp4

**Comment by MarcSkovMadsen** [comment]
There is a similar issue in gallery/param/action_button.ipynb. The first time I execute cell 3 nothing happens when I click the button. Second time I execute cell 3 it works.

**Comment by MarcSkovMadsen** [comment]
Other notebooks experiencing this issue in Panelite

- gallery/param/download_upload_csv.ipynb

**Comment by MarcSkovMadsen** [comment]
This is a major issue for the usability of Panelite @philippjfr. It affects so many notebooks.

**Comment by Hoxbro** [comment]
I just tested this, and it worked for me on the first try. 

![image](https://user-images.githubusercontent.com/19758978/231109777-648f8be6-4fb1-40d1-9fce-5f9a81c1b484.png)

**Comment by philippjfr** [comment]
Yeah, we're going to need more detail here, "Edge" is very vague. Are we talking old-school Edge or modern edge which is based on the Chrome engine? If it's the former I doubt there's much we can do here.

**Comment by MarcSkovMadsen** [comment]
Its modern edge. I will find the version tomorrow.

**Comment by MarcSkovMadsen** [comment]
My version of edge is `Version 112.0.1722.39 (Official build) (64-bit)`. My version of windows is

**Comment by MarcSkovMadsen** [comment]
> I just tested this, and it worked for me on the first try.
> 
> ![image](https://user-images.githubusercontent.com/19758978/231109777-648f8be6-4fb1-40d1-9fce-5f9a81c1b484.png)

Thanks @Hoxbro . Which os and browser (version) are you running?

**Comment by Hoxbro** [comment]
I'm running on Windows and Edge. I have no plugin installed. Could you test it out in a private browser?

Windows (from Windows Settings About):  
``` yaml
Edition	Windows 10 Pro
Version	22H2
Installed on	‎7/‎10/‎2022
OS build	19045.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0
````

Edge (from  edge://settings/help):
``` yaml
Version 112.0.1722.39 (Official build) (64-bit)
```

**Comment by philippjfr** [comment]
I have also tested this and can't reproduce. I suspect this is something to do with your setup, so I'm going to close. If this persists please report it upstream (in JupyterLite).
