### ISSUE TITLE
pn.pane.JPG throws ValueError is pointed to an `.jpeg` file

### ISSUE THREAD

**Issue by krlng** [holoviz/panel#4420]
The [JPG doc](https://panel.holoviz.org/reference/panes/JPG.html) states the component would understand `.jpeg` files. However, if you point it to one, it throws: `ValueError: JPG pane cannot parse a string that is not a filename or URL.`.

When I rename the `.jpeg` file to `.jpg` everything works nicely.

**Comment by MarcSkovMadsen** [comment]
Hi @krlng . Would you be interested in contributing a PR to fix this? If YES please let us know if you need help getting started.

**Comment by krlng** [comment]
I had a short look and think it is not as easy as one might think at first hand. 

To do this properly, [filetype](https://github.com/holoviz/panel/blob/main/panel/pane/image.py#L30) should be changed to a list. However [applies](https://github.com/holoviz/panel/blob/main/panel/pane/image.py#L54) and `_b64` and `_data` methods all use it and are not documented. So I am unsure, what they do exactly and how do deal with this. 

I guess this is something philipp can do really fast, but which would take me a couple of hours (I sadly don't have right now)

**Comment by krlng** [comment]
Btw: I just saw in the source code you added a general Image component. That is just great. I actually had something small to do the same on my own and I guess many who worked with the image components had the same....

**Comment by krlng** [comment]
Okay, sorry for texting you so much. If there is a new Image component, users most likely will not use the dedicated file-type extensions much more. So it would probably also be okay to just add a dedicated JPEG component (which basically means just copy-paste the JPG). This is a bit redundant, how ever, it keeps code less complex which is always a good thing for open source. 

So if you give me a thumbs up, I can just add the dedicated JPEG component.

**Comment by philippjfr** [comment]
Fair points, had missed this background when you submitted the PR. I'll mull it over a bit.
