### ISSUE TITLE
Typo in custom-templates docs

### ISSUE THREAD

**Issue by riziles** [holoviz/panel#4425]
Should this say "Goes in head" instead of "Goes in body"?

![image](https://user-images.githubusercontent.com/98712531/217696151-704ac018-0db2-433a-b9f9-f54ab3236520.png)

<https://panel.holoviz.org/user_guide/Templates.html#using-custom-templates>

**Comment by MarcSkovMadsen** [comment]
Yes 👍

**Comment by MarcSkovMadsen** [comment]
Are you interested in doing a PR to fix this? If YES let me know if you need help.

**Comment by droumis** [comment]
@riziles, if you want to do a PR, this typo is now [here](https://github.com/holoviz/panel/blob/main/doc/how_to/templates/template_custom.md) because we are reorganizing the docs for an upcoming release.

**Comment by riziles** [comment]
> Are you interested in doing a PR @riziles to fix this? If YES let me know if you need help.

I would love to take a swing at it, but unfortunately I'm way behind on work for the job I get paid for (and can't afford to lose), and I'll be traveling all of next week. If I can find some time to work my way through the development guide this weekend, I will certainly try to do so.
