### ISSUE TITLE
Panel 1.0. No margin between panels in Fast template

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4438]
I'm on the current `main` branch of Panel (post 0.14.3). When I try out the `FastListTemplate` I can see that there is no longer any margin between the panes.

![image](https://user-images.githubusercontent.com/42288570/218243150-3a273a08-fe82-4b59-9853-e29859e217ef.png)

```python
import panel as pn

pn.extension(sizing_mode="stretch_width", template="fast")

pn.Column("Header", "Main", "Footer").servable()
pn.Column("Header", "Main", "Footer").servable()
```

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/4326
