### ISSUE TITLE
Fast template header color is green and background white on startup

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4442]
I'm on the current `main` branch of Panel. One thing that has been annoying me about the FastTemplates is that if you network is slow, your template is big or some javascript goes wrong you end up with an app where the header background is white and the color is green. At least for a split of a second.

This looks very unprofessional. I will try to fix.

You can see it in the upper right corner in the video below

https://user-images.githubusercontent.com/42288570/218275833-84184f42-c52e-469a-96ea-2813dea5842e.mp4

```python
import panel as pn
import pandas as pd

pn.extension(template="fast")

data = pd.DataFrame({"x": [1]*1000, "y": [2]*1000})

pn.panel(data).servable()
```

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/4326
