### ISSUE TITLE
Tabulator scrolls to top when other element on the page changes

### ISSUE THREAD

**Issue by Wijnko** [holoviz/panel#4451]
**Versions:**
Panel 0.14.3
Python 3.10.4
MacOS 12.6
Chrome (Version 109.0.5414.119 (Official Build) (arm64))
(Same behaviour on Safari Version 16.0 (17614.1.25.9.10, 17614)

I have a Tabulator Table Element and another Element (for example an HTML Pane) on the same page. When the Tabulator table is scrolled down, and I change the contents of the other Element, the Tabulator Table scroll back to the first row.
 
Expected behaviour: Tabulator Table keep scroll position independent of other Elements.

(This bug makes a master-detail combination of tabulators impossible, as the master scrolls back to top when the detail changes)

```python
import panel as pn
import pandas as pd
pn.extension('tabulator')

sample_data = pd.DataFrame([{'Title': f'Sample Text in row {i}',
                             'Row Num':i,
                             'Row Num Squared':i*i} for i in range(50)])

table = pn.widgets.Tabulator(sample_data, height=200)
table_row = pn.Row(table)

dummy_text = pn.pane.HTML('Table scrolls to top when this text changes', width=600)
text_row = pn.Row(dummy_text, background='lightgray')

button = pn.widgets.Button(width=600, name='Add some dots to the text')

def add_dot(event):
    dummy_text.object += '...'
button.on_click(add_dot)

pn.Column(
    table_row,
    text_row,
    button
).servable()
```

![Kapture 2023-02-16 at 09 46 17](https://user-images.githubusercontent.com/17784946/219316745-8fdb9bd0-2dd5-4910-86a9-5ec5f068bbef.gif)

**Comment by Wijnko** [comment]
The behaviour described in this bug ticket is no longer occurring in Panel>=1

The table stills scrollt to top after data patching. New ticket opened for that:
https://github.com/holoviz/panel/issues/5000

**Comment by dwr-psandhu** [comment]
I worked around by wrapping the components in another container such as Row or Column

**Comment by alan0526** [comment]
@dwr-psandhu Have you solve this problem by use another container? Can you provide the example, thanks.
