### ISSUE TITLE
Bump ECharts to v5.4.1 and ECharts-GL to v2.0.9

### ISSUE THREAD

**Issue by mzy2240** [holoviz/panel#4453]
ECharts has fixed many bugs in the last two years and we are still on version v5.0.1. I think it is a good time to upgrade to the latest version, and I dont see any changes that would break the current API.

**Comment by mzy2240** [comment]
https://echarts.apache.org/en/changelog.html

**Comment by philippjfr** [comment]
Done in https://github.com/holoviz/panel/pull/2174
