### ISSUE TITLE
Tabulator does not render formatting correctly

### ISSUE THREAD

**Issue by FredDuj** [holoviz/panel#4468]
#### ALL software version info
jupyterlab==3.5.2
pandas==1.3.5
panel==0.14.2

#### Description of expected behavior and the observed behavior
Either using a formatted dataframe or the formatter parameters in the Tabulator function does not render a formatted table

#### Complete, minimal, self-contained example code that reproduces the issue

using a formatted dataframe
```
import pandas as pd
import numpy as np
import panel as pn
pn.extension('tabulator')
df = pd.DataFrame(np.random.rand(4, 4), columns=list('ABCD'))
df_styled = df.style.format('{:.2%}')
pn.widgets.Tabulator(df_styled)
```
using the Tabulator  formatter parameters :

```
df = pd.DataFrame(np.random.rand(4, 4), columns=list('ABCD'))
pn.widgets.Tabulator(df, formatters={'A': '{:.2%}', 'B': '{:.2%}', 'C': '{:.2%}', 'D': '{:.2%}'})
```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/113023746/220888695-95d8ca56-cbe8-4b38-a715-9a146083e729.png)

**Comment by maximlt** [comment]
Hi @FredDuj,

Formatting the Tabulator widget is done by passing either a Bokeh formatter instance or a dictionary that defines a Tabulator formatter. This is detailed in the reference doc here: https://panel.holoviz.org/reference/widgets/Tabulator.html#formatters.

Here's how to achieve that using the Number formatter from Bokeh:
```python
from bokeh.models.widgets.tables import NumberFormatter

df = pd.DataFrame(np.random.rand(4, 4), columns=list('ABCD'))

pct_fmt = NumberFormatter(format='0.00%')

pn.widgets.Tabulator(
    df,
    formatters={'A': pct_fmt, 'B': pct_fmt, 'C': pct_fmt, 'D': pct_fmt}
)
```

<img width="319" alt="image" src="https://user-images.githubusercontent.com/35924738/222669490-8c487476-5f2b-4587-926e-cf4fe254bd10.png">

As far as I know, your first example using `.style.format` isn't supported. The reference doc explicitly lists only `.style.apply` and `.style.applymap`: https://panel.holoviz.org/reference/widgets/Tabulator.html#styling.

Your second example actually emits a warning in the browser console, that's a nice little trick to find out when things go wrong:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/35924738/222672828-4d9ccb2f-35f2-4cbf-a3a3-0dc320e00944.png">

I'm going to go ahead and close this issue, assuming the support for formatting is already good enough and the documentation matches the implementation. Feel free to argue against it in which case we may open it again :) !

**Comment by FredDuj** [comment]
Hi Maxime,

Thanks a lot for your answer. It's more clear for me regarding how to apply the percentage formatter. However, this is only the first part of my problem (I tried to simplified it in my question).
Basically, I'm trying to format a dataframe with :

  *   Percentage format

and

  *   Custom colormap

With you solution, I'm able to input a dataframe to the Tabulator function and get the output with the correct percentage format
I'm already able to apply a custom colormap to the dataframe, then input it to the Tabulator function (my understanding is that it is not a dataframe anymore but a styler) and get the correct output with the colormap
However, when I use your solution with the styler I get from my colormap transformation,  the percentage format does not apply (I do not have any error, it just does not apply).

Do you know how to do both with Tabulator ?

Thanks a lot for your help.

Cheers,

Fred
