### ISSUE TITLE
AutocompleteInput doesn't resize Jupyter cell

### ISSUE THREAD

**Issue by jbednar** [holoviz/panel#448]
For the reference example, AutocompleteInput initially has enough space, but during completion the output gets cut off in a Jupyter notebook cell:

![image](https://user-images.githubusercontent.com/1695496/58385780-50a34500-7fbb-11e9-9f37-b2256dcc212d.png)
![image](https://user-images.githubusercontent.com/1695496/58385783-5d279d80-7fbb-11e9-9c97-49800b931dcd.png)

**Comment by jbednar** [comment]
Same for DatePicker:

![image](https://user-images.githubusercontent.com/1695496/58386740-aed72480-7fc9-11e9-9078-feb34b21e9cf.png)

**Comment by philippjfr** [comment]
Should be filed in bokeh as we can't do anything about it in panel.

**Comment by philippjfr** [comment]
Going to close this is entirely a bokeh issue, please reopen there.
