### ISSUE TITLE
Add example of altair with dropdown and interval selection

### ISSUE THREAD

**Issue by joelostblom** [holoviz/panel#4487]
I wanted to add an altair chart where the data was filtered based on a panel dropdown and a table was filtered based on a selection in the chart. This took me some time so I think it could be helpful to add an example to the documentation, but I am not sure if I have found the simplest approach yet. I wonder if I can simplify what I have so far further and if there is a preference between 1 or 2 from the panel side of things (I also wonder if there is a preference between the function decorators `pn.depends` or `pn.bind` as I have used it here):

1. Create the chart first and only update the data in the function:

```python
import panel as pn
import pandas as pd
import altair as alt


pn.extension('vega', template='fast-list')

def filter_table(selection, selected_island):
    if not selection:
        return '## No selection'
    query = ' & '.join(
        f'{crange[0]:.3f} <= `{col}` <= {crange[1]:.3f}'
        for col, crange in selection.items()
    )
    return pn.Column(
        f'Query: {query}',
        pn.pane.DataFrame(df.query(query + '& Island == @selected_island'), width=600, height=300)
    )

def update_chart(selected_island):
    altair_pane = pn.pane.Vega(chart.properties(data=df.loc[df['Island'] == selected_island]))
    return pn.Row(
        altair_pane,
        pn.bind(filter_table, altair_pane.selection.param.brush, selected_island)
    )

penguins_url = "https://raw.githubusercontent.com/vega/vega/master/docs/data/penguins.json"
df = pd.read_json(penguins_url)

brush = alt.selection_interval(name='brush')  # selection of type "interval"
chart = alt.Chart(df).mark_point().encode(
    x=alt.X('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
    y=alt.Y('Beak Depth (mm):Q', scale=alt.Scale(zero=False)),  
    color=alt.condition(brush, 'Species:N', alt.value('lightgray'))
).add_selection(
    brush
)

island_dropdown = pn.widgets.Select(options=df['Island'].unique().tolist(), width=300)

pn.Column(
    island_dropdown,
    pn.bind(update_chart, island_dropdown),
)
```

2. Recreate the chart entirely each time inside the update function:

```python
import panel as pn
import pandas as pd
import altair as alt


pn.extension('vega', template='fast-list')

def filter_table(selection, selected_island):
    if not selection:
        return '## No selection'
    query = ' & '.join(
        f'{crange[0]:.3f} <= `{col}` <= {crange[1]:.3f}'
        for col, crange in selection.items()
    )
    return pn.Column(
        f'Query: {query}',
        pn.pane.DataFrame(df.query(query + '& Island == @selected_island'), width=600, height=300)
    )

def update_chart(selected_island):
    brush = alt.selection_interval(name='brush')
    altair_pane = pn.pane.Vega(
        alt.Chart(df.loc[df['Island'] == selected_island]).mark_point().encode(
            x=alt.X('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
            y=alt.Y('Beak Depth (mm):Q', scale=alt.Scale(zero=False)),  
            color=alt.condition(brush, 'Species:N', alt.value('lightgray'))
        ).add_selection(
            brush
        )
    )
    return pn.Row(
        altair_pane,
        pn.bind(filter_table, altair_pane.selection.param.brush, selected_island)
    )

penguins_url = "https://raw.githubusercontent.com/vega/vega/master/docs/data/penguins.json"
df = pd.read_json(penguins_url)
island_dropdown = pn.widgets.Select(options=df['Island'].unique().tolist(), width=300)

pn.Column(
    island_dropdown,
    pn.bind(update_chart, island_dropdown),
)
```

**Comment by philippjfr** [comment]
Many ways to do this but I'd probably do something similar to this:

```python
def filter_table(data, selection):
    if not selection:
        return '## No selection'
    query = ' & '.join(
        f'{crange[0]:.3f} <= `{col}` <= {crange[1]:.3f}'
        for col, crange in selection.items()
    )
    return pn.Column(
        f'Query: {query}',
        pn.pane.DataFrame(data.query(query), width=600, height=300)
    )

penguins_url = "https://raw.githubusercontent.com/vega/vega/master/docs/data/penguins.json"
df = pd.read_json(penguins_url)

island_dropdown = pn.widgets.Select(options=df['Island'].unique().tolist(), width=300)

dynamic_data = pn.bind(lambda island: df.loc[df['Island'] == island], island_dropdown)

brush = alt.selection_interval(name='brush')  # selection of type "interval"
chart = alt.Chart(dynamic_data()).mark_point().encode(
    x=alt.X('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
    y=alt.Y('Beak Depth (mm):Q', scale=alt.Scale(zero=False)),  
    color=alt.condition(brush, 'Species:N', alt.value('lightgray'))
).add_params(
    brush
)

altair_pane = pn.pane.Vega(chart)

def update_chart(_):
    altair_pane.object = chart.properties(data=dynamic_data())
    
island_dropdown.param.watch(update_chart, 'value')

pn.Column(
    island_dropdown,
    pn.Row(
        altair_pane,
        pn.bind(filter_table, dynamic_data, altair_pane.selection.param.brush)
    )
)
```

**Comment by philippjfr** [comment]
>After the using the drop down to change the chart, subsequent selections no longer update the table and it's still looking at the bounds of that initial selection.

Ah indeed, I think that's an easy fix. Basically I won't overwrite the Selections object unless the available selections change.

**Comment by joelostblom** [comment]
Great, thank you for the swift fix and new release @philippjfr , that was really quick! The table now updates when selecting in the chart even after using the dropdown with your examples above.

I think one further improvement would be if the selection and table is cleared when the dropdown is used and the chart/data with the current selection changes. Here is an example using your code from above where the selection in the table stays the same even when the chart changes and the grey selection rectangle is visually cleared from the chart:

https://user-images.githubusercontent.com/4560057/222938065-ba2f4062-ccd0-4960-b063-326531b8965a.mp4

As you can see, the initial selection area is still active and selects in the next chart after the dropdown is used even if there is no visual selection in the chart, which I think is confusing. The expected behavior for me would be if the selection is cleared when the dropdown is used, as when using one of the code snippets I posted above:

https://user-images.githubusercontent.com/4560057/222938064-3c33aa6b-e7ec-479d-b69d-2838fcfca2c5.mp4

**Comment by joelostblom** [comment]
@philippjfr Just checking in on my comment above, do you think this makes sense for the default behavior? And do you want me to open a separate issues to track this?

**Comment by philippjfr** [comment]
Yes, I agree with that. Just need to reset the selection object values to default. Let's just keep this issue to track that.
