### ISSUE TITLE
PyDeck tooltip not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4501]
Panel=0.14.4, PyDeck=0.8.0

Diehl reports in https://discourse.holoviz.org/t/custom-pydeck-tooltip-in-panel-application-fails-to-access-data/5016 that PyDeck tooltips are not working for him.

After working with his example I believe this is a bug. 

## Reproducible Example

```python
import pydeck as pdk
import panel as pn
pn.extension('deckgl')

INITIAL_VIEW_STATE = pdk.ViewState(
  latitude=38,
  longitude=-97,
  zoom=3,
  min_zoom=3,
  max_zoom=16,
  pitch=0,
  bearing=0
)

ACCESS_TOKEN = "pk.eyJ1IjoicGFuZWxvcmciLCJhIjoiY2s1enA3ejhyMWhmZjNobjM1NXhtbWRrMyJ9.B_frQsAVepGIe-HiOJeqvQ"

layer = pdk.Layer(
    "MVTLayer",
    'https://api.mapbox.com/v4/diehl.6baso3o2/{z}/{x}/{y}.mvt?access_token='+ACCESS_TOKEN,
    get_line_color = [0, 255, 0],
    line_width_min_pixels = 1,
    pickable=True
)

TOOLTIP_HTML = ('<b>{ALLOT_NAME}</b><br />'
                '<b>Allotment #</b>: {ALLOT_NO}<br />'
                '<b>Acres</b>: {GIS_ACRES}<br />')

r = pdk.Deck(
    layers=[layer],
    initial_view_state=INITIAL_VIEW_STATE,
    map_style='dark',
    tooltip={'html': TOOLTIP_HTML}
)

map = pn.pane.DeckGL(r, sizing_mode='stretch_both') 
map.servable()
```

![image](https://user-images.githubusercontent.com/42288570/222919052-fb9cca09-8f9e-4213-8ffd-88e06e182365.png)

As you can see in the above example the parameters `{ALLOT_NAME}`, `{ALLOT}` and `{GIS_ACRES}` are not being replaced.

## Works without Panel in the notebook

![image](https://user-images.githubusercontent.com/42288570/222919018-6995a531-12c9-43ed-bd39-4d2e7993e8b8.png)

Here parameters are replaced with their values.

**Comment by diehl** [comment]
@MarcSkovMadsen It turns out this issue is resolved by using `{properties.<DATA_FIELD_NAME>}` as opposed to `{<DATA_FIELD_NAME>}`.

**Comment by MarcSkovMadsen** [comment]
Thanks for sharing. I keep this open as I Think we should document this.

**Comment by diehl** [comment]
My pleasure @MarcSkovMadsen - I totally agree with documenting this to make it clear.
