### ISSUE TITLE
GridSpec responsiveness breaks when embedding a geoviews object

### ISSUE THREAD

**Issue by zassa** [holoviz/panel#451]
This bug appears when using the Integer parameter widget to set the number of points shown on a geoviews map. On updating the geoviews plot based on the widget values the plot is redrawn with dimensions that don't appear to be inherited from the GridSpec layout that it is contained by.

A minimal 3 point demo is in the link below.
https://github.com/zazbot5000/pyviz-panel-gridspec-example

**Comment by philippjfr** [comment]
Thanks, this is high priority for me to fix, so I'll try to take a look today.

**Comment by zazbot5000** [comment]
Awesome stuff! The geoviews plot also doesn't fill the vertical space available, though I'm not sure if that should go in as a separate ticket.

**Comment by philippjfr** [comment]
Sorry this took so long, now fixed.
