### ISSUE TITLE
Rename tabs in GoldenLayout 

### ISSUE THREAD

**Issue by theHenks** [holoviz/panel#4512]
Is there any option to rename the tabs in the GoldenLayout in the main area? So far, all tabs have "Content" as name by default and there is no option available (at least according to my knowledge) to rename them when appending a new tab to the main area. 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/46198814/223735849-039faa11-a0fe-4daf-bd9e-c5083e9f4f8b.png">

Maybe I am just missing something, but from the code, I can't see an option how to set the name of the tabs.

**Comment by ingebert** [comment]
Hi, see here:
[https://discourse.holoviz.org/t/change-title-label-of-sidebar-and-main-window-in-golden-template/2724](https://discourse.holoviz.org/t/change-title-label-of-sidebar-and-main-window-in-golden-template/2724)

**Comment by theHenks** [comment]
Thank you very much, and sorry for the issue. Could not find this in the discourse. Next time I will post my question there.
