### ISSUE TITLE
Ipycytoscape not working with Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4536]
Reported by Weed in https://discourse.holoviz.org/t/ipycytoscape-is-not-displayed/5090

If you serve

```python
import panel as pn
from ipycytoscape import CytoscapeWidget
import networkx as nx
pn.extension("ipywidgets")


G = nx.complete_graph(5)
cyto = CytoscapeWidget()
cyto.graph.add_graph_from_networkx(G)

pn.pane.IPyWidget(cyto).servable()
```

you see errors in the browsers console

![image](https://user-images.githubusercontent.com/42288570/225362068-b5824e7f-cdec-446b-88f6-059dc84433c4.png)

```bash
Error rendering Bokeh items: Error: reference {"id":"1"} isn't known (not in Document?)
```

My guess is that this should be reported upstream somewhere. But I don't know where.

**Comment by philippjfr** [comment]
Appears to work with main and ipywidgets_bokeh=1.4.0dev3

<img width="1044" alt="Screen Shot 2023-05-03 at 00 12 52" src="https://user-images.githubusercontent.com/1550771/235797298-4ac77e63-3ee2-417c-b867-7570b944a573.png">
