### ISSUE TITLE
Output is not showing when adding argument in "panel.extension()"

### ISSUE THREAD

**Issue by dove88** [holoviz/panel#4542]
Hello, I am trying to use the panel for jupyter dashboards, everything works fine for hvplot.pandas with panel.extension(), but when i am trying to add extension arguments, i get null output, please help...

I am using the demo from panel website

https://panel.holoviz.org/gallery/simple/altair_brushing.html

Prigith

**Comment by philippjfr** [comment]
Appreciate the issue, should be resolved by https://github.com/holoviz/panel/pull/4752
