### ISSUE TITLE
Apps at https://panel-gallery-dev.pyviz.demo.anaconda.com/ will be loading all js frameworks possible

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4559]
When the site https://panel-gallery-dev.pyviz.demo.anaconda.com/ has been alive for a longer period of time any page will be loading any `.js` framework. This make the loading very, very slow. Éspecially the first time you load a page which will happen for a lot of users.

For example https://panel-gallery-dev.pyviz.demo.anaconda.com/penguin_crossfilter

![image](https://user-images.githubusercontent.com/42288570/227707412-29f3dac4-4353-40f4-a8a9-d589dcefe29b.png)

I experience the same issue at awesome-panel.org.

Please make it so that only js defined on a specific page is loaded.

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/4562, if you could also close all other related issues (I think you've filed this issue several times now) that would be super helpful.

**Comment by MarcSkovMadsen** [comment]
Done. I found only 1 open issue.
