### ISSUE TITLE
Apps at https://panel-gallery-dev.pyviz.demo.anaconda.com/ don't always render

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4560]
Some of the apps renders nicely most of the time. But sometimes they don't.

![image](https://user-images.githubusercontent.com/42288570/227707843-c987fbb8-3574-43ba-804a-f7912867d209.png)

![image](https://user-images.githubusercontent.com/42288570/227707856-e60bc833-5a99-46e0-bac7-14f1be123dab.png)

I can't say why.

This happens for a lot of apps. And it happens a lot in the automated tests that I have set up in https://github.com/holoviz/panel/pull/4558

![image](https://user-images.githubusercontent.com/42288570/227707915-0cb3a84f-ec7c-47e6-9f79-5c50f136e79d.png)

**Comment by philippjfr** [comment]
## General issues

- Panel.js seems to be inlined (slowing things down)


## Components

- FileDownload: horizontal center align text correct
- SpeechToText:
```
Error rendering Bokeh items: Error: panel.models.speech_to_text.SpeechToText(p3131).grammars given invalid value: [{"src":"#JSGF V1.0; grammar colors; public <color> = aqua | azure | beige | bisque | black | blue | brown | chocolate | coral | crimson | cyan | fuchsia | ghostwhite | gold | goldenrod | gray | green | indigo | ivory | khaki | lavender | lime | linen | magenta | maroon | moccasin | navy | olive | orange | orchid | peru | pink | plum | purple | red | salmon | sienna | silver | snow | tan | teal | thistle | tomato | turquoise | violet | white | yellow ;","weight":1}]
```

- Tabs: Tabs updates still broken, e.g.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'resizeCanvas')

- FastTemplate: Margin when no sidebar is non-existent
- DeckGL.remove is not a function

## Examples

- altair_choropleth: errors

```
"python3.10/site-packages/panel/pane/vega.py", line 79, in _get_schema_version
     schema = obj.get('$schema', '')
```

- file_download_examples: Image sizing incorrect
- distribution_tabs: Suffers from Tabs issue
- download_upload_csv: Tabulator not loaded
- Gapminders
  - Uncaught Error: Unrecognized signal name: "selector005"
-   Sidebar not wide enough

**Comment by philippjfr** [comment]
The majority of this has been addressed and the remaining two broken apps, vtk_warp and vtk_interactive I'm already investigating.
