### ISSUE TITLE
Cannot import panel at pyscript.com

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4572]
I've tried several times in many different ways to get Panel imported at pyscript.com. But cannot. Don't know if its a Panel issue or a pyscript.com issue.

## Reproduce

- Create a new project
- Add  Panel requirement to the `pyscript.toml`: `packages=["panel"]`
- Click run

![image](https://user-images.githubusercontent.com/42288570/228744555-7e63ee92-6c43-4180-b46c-3d21c7942a04.png)

![image](https://user-images.githubusercontent.com/42288570/228744464-305beee3-5443-4fc8-a535-33e649499300.png)

```bash
(PY1001): Unable to install package(s) 'panel==0.14.4'. Reason: Can't find a pure Python 3 Wheel for package(s) 'panel==0.14.4'. See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel for more information.
```

But it can import plotly

![image](https://user-images.githubusercontent.com/42288570/228744754-a7885cda-a7c6-49de-99b0-465a60246db3.png)

and Bokeh

![image](https://user-images.githubusercontent.com/42288570/228745894-0dcd39ca-a205-4ed2-9e77-ccd9b5488041.png)

**Comment by MarcSkovMadsen** [comment]
Is the problem the naming of our `.whl` file compared to bokehs`? Why do we still have `py2` in the name?

![image](https://user-images.githubusercontent.com/42288570/228746271-d70baead-5cbf-4dae-9248-d92d8b68a1fc.png)


![image](https://user-images.githubusercontent.com/42288570/228746174-76a76056-03e5-46a6-86e0-fcbf552b3f14.png)

**Comment by Hoxbro** [comment]
> Why do we still have py2 in the name?

I think this is a legacy thing and will be fixed with the changes in #4541

> And why is our .whl file so big?

You can take a look inside it, it is a zip file. It seems to come from bundling up libraries.

![image](https://user-images.githubusercontent.com/19758978/228753443-1afcaa06-3d05-470e-a697-bb732b08d781.png)

This isn't a problem on a normal install but a problem when using it with something like pyscript. This is why we have https://github.com/holoviz/panel/blob/main/scripts/build_pyodide_wheels.py for the panelite.

**Comment by Hoxbro** [comment]
Looking at the error message, it could be a problem having py2 in the name. 

![image](https://user-images.githubusercontent.com/19758978/228756292-9a553fa8-f45b-4b72-89ac-0c2d62da46e0.png)

**Comment by Hoxbro** [comment]
I tried using the .whl described [here](https://pyviz-dev.github.io/panel/how_to/wasm/standalone.html#pyodide) and got this error:

![image](https://user-images.githubusercontent.com/19758978/228758230-0412640b-1635-4a88-8dce-526a8aa80c5e.png)

**Comment by MarcSkovMadsen** [comment]
These works for me now.

```bash
packages=[
    "https://cdn.holoviz.org/panel/0.14.4/dist/wheels/bokeh-2.4.3-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/0.14.4/dist/wheels/panel-0.14.4-py3-none-any.whl",
]
```

![image](https://user-images.githubusercontent.com/42288570/228930036-e7d22370-fd30-4901-ac6e-5541078dc68f.png)

**Comment by Hoxbro** [comment]
Oh. It seems like the URL are wrong on the website (missing dist)

**Comment by MarcSkovMadsen** [comment]
This is an example app

**index.html**

```bash
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Red Recipe</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.03.1/pyscript.css" />
    <script defer src="https://pyscript.net/releases/2023.03.1/pyscript.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.3.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.4.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@holoviz/panel@0.14.4/dist/panel.min.js"></script>
</head>
<body>
    <div id="main"></div>
    <py-config src="./pyscript.toml"></py-config>
    <py-script src="./main.py"></py-script>
</body>
</html>
```

**main.py**

```bash
import panel as pn

pn.extension(sizing_mode="stretch_width")

slider = pn.widgets.FloatSlider(start=0, end=10, name='Amplitude')

def callback(new):
    return f'Amplitude is: {new}'

pn.Row(slider, pn.bind(callback, slider)).servable(target="main")
```

**pyscript.toml**

```bash
packages=[
    "https://cdn.holoviz.org/panel/0.14.4/dist/wheels/bokeh-2.4.3-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/0.14.4/dist/wheels/panel-0.14.4-py3-none-any.whl",
]
```

**Comment by liquidcarbon** [comment]
https://github.com/pyscript/pyscript/issues/1446 related

**Comment by philippjfr** [comment]
Should work now.
