### ISSUE TITLE
Make docs readable on mobile

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4577]
I'm on my iPhone Reading https://pyviz-dev.github.io/panel/getting_started/build_app.html#declarative-panels

The example below is not useful because i cannot see the plot.

![image](https://user-images.githubusercontent.com/42288570/229332675-57e5c2da-e140-4ce3-bcce-570e5363755c.png)

Please use Column layout or add som css to make output fit Window width

**Comment by MarcSkovMadsen** [comment]
When i go to the HomePage https://pyviz-dev.github.io/panel/index.html# i see

![image](https://user-images.githubusercontent.com/42288570/229332883-6c12e26c-7609-4a6f-a8fb-a8ebe0d63247.jpeg)

This does not give me a quick, positive impression of some framework i want to use. Why do I have to scroll down to see that?

For camparison other frameworks nail it

![image](https://user-images.githubusercontent.com/42288570/229333014-11c9bbfb-b750-4772-a3ed-b299a6a32b1c.jpeg)

![image](https://user-images.githubusercontent.com/42288570/229333033-95913228-5824-4d12-bd64-ad204304cb68.jpeg)

**Comment by philippjfr** [comment]
The new PyData Sphinx theme version improved the situation a lot, so now the width of the output is the main issue. Closing in favor of https://github.com/holoviz/panel/issues/4588
