### ISSUE TITLE
Make home page example fit mobile screen

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4579]
I'm reading the home page at https://pyviz-dev.github.io/panel/index.html# on my iPhone

But I cannot see the plot of the example ![image](https://user-images.githubusercontent.com/42288570/229339146-0dde9b0b-54b6-484e-9acf-54ce600c545e.jpeg)

Please make it fit the mobile screen.

**Comment by philippjfr** [comment]
Duplicate https://github.com/holoviz/panel/issues/4577
