### ISSUE TITLE
Document example of using widgets (like Player) to interact with panel objects

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#458]
I feel a little lost on how to actually wrap the Player widget with my panel objects.

I can do this (although index 0 can't be reselected after the first touch), but how would I use a custom Player widget instead of a slider?

```
import matplotlib.pyplot as plt
fig1 = plt.figure()
ax = plt.subplot()
ax.plot([0, 1, 2])

fig2 = plt.figure()
ax = plt.subplot()
ax.plot([3, 6, 4])

panes = [pn.Pane(fig1), pn.Pane(fig2), pn.Pane(fig1)]

@interact(i=(0, len(panes) - 1, None, 0))
def slider(i):
    return panes[i]

slider
```

**Comment by philippjfr** [comment]
How to declare a widget explicitly is documented under Widget abbreviations on the [interact user guide](http://panel.pyviz.org/user_guide/Interact.html) but an example might still be nice.

**Comment by MarcSkovMadsen** [comment]
I took a look. As Philipp writes there is already the example

![image](https://user-images.githubusercontent.com/42288570/133667027-695a2b08-a0e2-4352-b0ec-5c7d3a7d3274.png)

I see too options for adding an example. Either

- right after the above one. As a way to show that different kinds of widgets can be used.
- some gallery example with lots of interact examples.

I don't know if either is useful or really needed. How would you solve this @ahuang11 ?

**Comment by philippjfr** [comment]
The building an animation tutorial does this now.
