### ISSUE TITLE
Cannot execute docs cells on iPhone

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4581]
When Reading the dev documentation. I cannot get Pyodide execution working.

When i click the run button the first time i get a Warning about Big download. The second time nothing happens and the cell never executes.

![image](https://user-images.githubusercontent.com/42288570/229376049-1906abe0-c5e2-4761-ad6a-b467ef21fb2c.jpeg)

**Comment by apachaves** [comment]
Hello,

I was trying to find typos in the docs and I tried to run the code on the Getting Started page (https://pyviz-dev.github.io/panel/getting_started) and just got this error:
![image](https://user-images.githubusercontent.com/3076785/230482019-46cef4ee-1c57-4837-9f84-ec106dc70ab6.png)

It looks like it talks about an f-string but I couldn't spot the error. Plus, I'm running from my computer, so I don't know if there is a correlation, but I wanted to share with you here in case it is better than creating a new issue.

**Comment by philippjfr** [comment]
The doc build is currently broken so this isn't unexpected, the next build will fix it.
