### ISSUE TITLE
Add ability to open custom notebook in Panelite.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4607]
The Jupyter lite extension https://github.com/jupyterlab-contrib/jupyterlab-open-url-parameter enables you to open a notebook from an url in Jupyterlite.

This would be really powerful to include in the build of Panelite as we can the start to share links to notebooks that opens quickly for the user with a working environment.

**Comment by MarcSkovMadsen** [comment]
For a lot of background info leading to this extension check out https://github.com/jupyterlite/jupyterlite/issues/430

**Comment by philippjfr** [comment]
Docs about how to enable this here: https://github.com/jupyterlite/jupyterlite/blob/76cd0496add7494bec9a749b2044e28074f60781/docs/howto/content/open-url-parameter.md
