### ISSUE TITLE
Missing Gallery notebooks

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4641]
## Viz is missing from dev and prod docs

If I go to the Gallery in the [current document](https://panel.holoviz.org/gallery/index.html) or [current dev documentation](https://pyviz-dev.github.io/panel/gallery/index.html) I don't see the *gallery/viz* section.

But if I open Panelite its there

![image](https://user-images.githubusercontent.com/42288570/231937800-95ff0a7b-9913-49dc-a296-7b5d8301e33a.png)

## Links and Param notebooks are missing from dev

I can't find the Apis, Links and Param notebooks in the dev docs. Maybe some of this is on purpose?

**Comment by Hoxbro** [comment]
> I can't find the Apis, Links and Param notebooks in the dev docs. Maybe some of this is on purpose? 

This is most likely on purpose. Try to look at the [how-to](https://pyviz-dev.github.io/panel/how_to/index.html) section.

**Comment by philippjfr** [comment]
Sections for the gallery no longer exist. I may re-add these examples but probably elsewhere.
