### ISSUE TITLE
Search Feature is hard to find and use in dev docs

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4647]
When using the `dev` docs I had a hard time finding the search feature. First of all because its moved :-) But also because 

- its not very central on the page
- has a color which does not stand out
- Its *cramped* together (small margin) with other icons in the top, right corner.

![image](https://user-images.githubusercontent.com/42288570/232181337-39417b73-3277-40e0-869a-7f768ddb1952.png)

Furthermore it requires more clicks to use it. Before you needed 1 click to start writing your search. 

![image](https://user-images.githubusercontent.com/42288570/232181359-ed4d15af-6ffd-41d8-87e4-7a1ffdc7fbb7.png)

Now it requires two clicks. A 100% increase.

![image](https://user-images.githubusercontent.com/42288570/232181371-96feff35-0f27-453a-b2fb-27e4ae1e51cc.png)

I think the most important Feature is the navigation in menus, and that has been improved. But search is very close in importance and that has not been improved. Lots of users could misleadingly believe there was no search. And then the site is very hard to use.

**Comment by MarcSkovMadsen** [comment]
Just visited Jupyterlite. And I can see our problem is that we have a header with a custom dark color. And the icon color for search and light/ dark theme have not been adjusted accordingly.

I would actually recommend using the same header color as Jupyterlite. It has a much more fresh look and feel :-)

https://user-images.githubusercontent.com/42288570/232197567-66db6ae7-970d-4766-bae3-32e04f39a796.mp4

**Comment by philippjfr** [comment]
>I would actually recommend trying out the same header color as Jupyterlite. It has a fresh look and feel :-)

I'll try it out, but I'm not sure I agree with that.
