### ISSUE TITLE
Light/ dark theme icon is not same size as rest of icons

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4648]
When looking at the new `dev` docs at https://pyviz-dev.github.io/panel/index.html the new light/ dark theme icon catches my eye.

- Its much bigger than the other icons around which does not look nice 😄 
- The light/ dark theme icon comes next after the search icon. Since left to right is some kind of a priority list I believe that priority is too high. I believe the icon should be on the right.
- The default icon I have not seen before, which makes it hard for me to recognice as a light/ dark theme switch. But I can see its a bootstrap so its probably well known.

I think the user experience could be improved

**Please make the icon height smaller. Please consider moving it to the right. Please consider adding a little bit more left/ right margin to the icons**.

![image](https://user-images.githubusercontent.com/42288570/232181796-11af58e0-8734-4e0a-976e-bdc10432ab42.png)

**Comment by MarcSkovMadsen** [comment]
Just visited Jupyterlite. And they use the same sphinx template but their styling is much better in general and specifically for the light/ dark theme icon.

https://user-images.githubusercontent.com/42288570/232197395-c7604a4c-1f7f-4325-8f3b-caa1f6c546e8.mp4

**Comment by philippjfr** [comment]
>their styling is much better in general 

What makes you say that apart from the icon?

**Comment by MarcSkovMadsen** [comment]
> > their styling is much better in general
> 
> What makes you say that apart from the icon?

Maybe it was a bit too broad of a statement. But I believe the Panel header background is a bit dusted/ old school. And the Panel logo green together with the web page blue accent color also seems a bit dusted/ old school.
