### ISSUE TITLE
MaterialTemplate for Palmer Penguins not using Roboto font

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4650]
I can see that the MaterialTemplate for Palmer Penguins is not using the Roboto font (default for Material). Its uses the Ubuntu font which at least on my screen looks ugly and is hard to read.

![image](https://user-images.githubusercontent.com/42288570/232182754-7b837da2-b883-453a-ab7f-223a62bb5ada.png)

Its bad because its one of our featured examples on the home page

![image](https://user-images.githubusercontent.com/42288570/232182789-d2e7bb7b-e5af-4e59-8880-bc58697604dc.png)

It could be one reason that some people think our apps look old and dusted.

**Comment by MarcSkovMadsen** [comment]
I actually thought I contributed a major improvement including moving to the fast template ???

**Comment by philippjfr** [comment]
We will no longer link to the deployments from examples.pyviz.org.
