### ISSUE TITLE
Intro example on home page not reacting as expected

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4653]
When I load the [dev docs](https://pyviz-dev.github.io/panel/) and interact with the intro example it does not react as expected.

At first it does not react. After some time it starts reacting. But only for some values.

Its a bit hard to predict the behavior, but as a user I'm left with the feeling that this does not work well. I cannot expect it to work.

https://user-images.githubusercontent.com/42288570/232184281-780de5dd-5ca0-441a-bb82-aff5b69a4844.mp4

**Comment by philippjfr** [comment]
Already fixed, just not redeployed yet.
