### ISSUE TITLE
ButtonGroup not styled in FastTemplate on dev branch

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4668]
If you go to the `dev` VideoStream example https://panel-gallery-dev.pyviz.demo.anaconda.com/streaming_videostream, you can see the ButtonGroup is not styled

![image](https://user-images.githubusercontent.com/42288570/233148342-405cda52-c742-4f96-a4d5-cf5adcae1da1.png)

**Comment by philippjfr** [comment]
Please create a meta-issue for all styling issues.

**Comment by philippjfr** [comment]
Superseded by https://github.com/holoviz/panel/issues/4727
