### ISSUE TITLE
The dev videostream app does not show the videostream

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4669]
If I go to the `dev` Videostream app at https://panel-gallery-dev.pyviz.demo.anaconda.com/streaming_videostream and "allow" access to the Video Camera, then nothing shows

![image](https://user-images.githubusercontent.com/42288570/233148829-06716c0e-5575-4924-a692-c51ca4e00570.png)

There is a `DomException` in the console

![image](https://user-images.githubusercontent.com/42288570/233149044-153dfb33-71eb-497d-b14a-dc1ed702a072.png)

**Comment by philippjfr** [comment]
Quite certain that's a problem with your browser:

![Uploading Screen Shot 2023-04-19 at 19.44.13.png…]()
