### ISSUE TITLE
Issues with `dev` Palmer Penguins app

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4670]
I'm visiting the `dev` Palmer Penguins app at https://panel-gallery-dev.pyviz.demo.anaconda.com/penguin_crossfilter

- [x] Not taking theme query arg into account
- [x] Starts repeating update cycle when you reset the plot
- [x] The number of selected penguins has black text color. Should be white
- [x] No clear separation between sidebar and main area

## Not taking theme query arg into account

Try opening https://panel-gallery-dev.pyviz.demo.anaconda.com/penguin_crossfilter?theme=dark and you will see

![image](https://user-images.githubusercontent.com/42288570/233150417-3b8046bd-dc4b-44f6-98e3-581926ed5d47.png)

## Starts repeating update cycle when you reset the plot

- Open https://panel-gallery-dev.pyviz.demo.anaconda.com/penguin_crossfilter
- Try Box Selecting some points in the Scatter Plot
- Reset the plots

https://user-images.githubusercontent.com/42288570/233151500-81daba1d-9097-4bdc-ab8e-ff0429a1cb46.mp4

## The number of selected penguins has black text color. Should be white

Text in the header should be white. I also believe this text should out as it is something that updates dynamically.

![image](https://user-images.githubusercontent.com/42288570/233151758-de2d0d38-48e4-4ec8-868f-9e6e6aad50ad.png)

## No clear separation between sidebar and main area

Maybe its on purpose, but there is no longer any styling to clearly separate the `sidebar` and the `main` area.

Maybe its on purpose? Maybe it simplifies things and makes them better?

![image](https://user-images.githubusercontent.com/42288570/233152810-1c3cf86b-72b6-4e7e-ac86-f99856c71c6d.png)

**Comment by philippjfr** [comment]
@MarcSkovMadsen Please do not create issues for each app. Create one issue for all apps.

>Maybe its on purpose, but there is no longer any styling to clearly separate the sidebar and the main area.

No I think we should restore this for all templates.

**Comment by philippjfr** [comment]
https://github.com/holoviz/panel/pull/4671 fixes the theming issue and black text color. The weird selection behavior probably has to be resolved in HoloViews.
