### ISSUE TITLE
Issues with `dev` Portfolio Optimizer App

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4672]
I'm exploring the `dev` Portfolio Optimizer App at https://panel-gallery-dev.pyviz.demo.anaconda.com/portfolio_optimizer

- [] No hover information in Risk/ Reward plot
- [] Log Returns don't take up available space.

Generally I like this app better than the other apps because its snappier. It updates faster. All the other apps I have to wait a lot.

## No hover information in Risk/ Reward plot

The Hover information is some of the information I need the most :-)

https://user-images.githubusercontent.com/42288570/233157721-dcc19efc-f538-4d73-8891-cc77ba1ebb7c.mp4

Note: I learned after recording the move that the points on the edge has tooltips. But I also need it for the other points. Maybe for some practical reasons they are the ones I can/ will buy.

## Log Returns don't take up available space.

Why not give the plots a height to fill up the space?

![image](https://user-images.githubusercontent.com/42288570/233158729-29764248-c85e-4178-bb5a-95674c49c3f8.png)

**Comment by philippjfr** [comment]
The reason they don't have hover is because at the densest region you'll get hundreds of tooltips.

**Comment by philippjfr** [comment]
https://github.com/holoviz/panel/pull/4671 fixes the log return sizing.

**Comment by philippjfr** [comment]
I'll close, hover does not seem advisable on a plot as dense as this and it doesn't really add more information (i.e. it'd just be the coordinates of the point which you can already see visually).
