### ISSUE TITLE
panel-gallery-dev.pyviz.demo.anaconda.org/windturbines is not secure

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4673]
Try to open https://panel-gallery-dev.pyviz.demo.anaconda.org/windturbines

![image](https://user-images.githubusercontent.com/42288570/233161885-114bc351-75fe-49af-8637-1beaa20a3cff.png)

```bash
Your connection isn't private
Attackers might be trying to steal your information from panel-gallery-dev.pyviz.demo.anaconda.org (for example, passwords, messages, or credit cards).
NET::ERR_CERT_COMMON_NAME_INVALID
```

![image](https://user-images.githubusercontent.com/42288570/233161995-7731cf3e-820a-4c91-ab4d-59e4e03f3741.png)

```bash
The certificate for this site is not valid.

Because this connection is not secure, information (such as passwords or credit cards) will not be securely sent to this site and may be intercepted or seen by others.

We suggest you don't enter personal information into this site or avoid using this site.​
```

I'm on Windows and can reproduce in both Edge and Chrome browsers.

**Comment by philippjfr** [comment]
Wrong link, already fixed.
