### ISSUE TITLE
Can't resolved bokeh dependency with jupyter-bokeh

### ISSUE THREAD

**Issue by xareelee** [holoviz/panel#4678]
#### ALL software version info

macOS == 13.3.1
VSCode == 1.77.3 (my IDE)
poetry == 1.4.2 (Python package manager)

In poetry venv:

python == 3.11.3
pandas == 2.0.0
bokeh == 2.4.3
panel == 0.14.4 (depending on bokeh >=2.4.0 && < 2.5.0)
jupyter_bokeh == 3.0.2 (not 3.0.7, because of panel dependency, please see below)

## dependency conflict when installing jupyter_bokeh 3.0.7 and bokeh 3.x

I can't install `panel` (depending on bokeh (>=2.4.0,<2.5.0)) and `jupter-bokeh` (depending on bokeh (>=3.0.0,<4.0.0)) at the same time.

```sh
$ poetry add jupyter_bokeh                
Using version ^3.0.7 for jupyter-bokeh

Updating dependencies
Resolving dependencies... (1.5s)

Because no versions of jupyter-bokeh match >3.0.7,<4.0.0
 and jupyter-bokeh (3.0.7) depends on bokeh (>=3.0.0,<4.0.0), jupyter-bokeh (>=3.0.7,<4.0.0) requires bokeh (>=3.0.0,<4.0.0).
And because panel (0.14.4) depends on bokeh (>=2.4.0,<2.5.0)
 and no versions of panel match >0.14.4,<0.15.0, jupyter-bokeh (>=3.0.7,<4.0.0) is incompatible with panel (>=0.14.4,<0.15.0).
So, because finable depends on both panel (^0.14.4) and jupyter-bokeh (^3.0.7), version solving failed.```
```

I've tried latest panel, but it failed:

```sh
# in pyproject.toml
# panel = { git = "https://github.com/holoviz/panel.git", tag = "v1.0.0b16" }
$ poetry install
Because panel (1.0.0b16) @ git+https://github.com/holoviz/panel.git@v1.0.0b16 depends on xyzservices (>=2021.09.1) which doesn't match any versions, panel is forbidden.
So, because finable depends on panel (1.0.0b16) @ git+https://github.com/holoviz/panel.git@v1.0.0b16, version solving failed.
```

## try using jupyter-bokeh 3.0.2 but it shows an error when rendering component

Furthermore, I've tried using jupyter-bokeh 3.0.2 (depending on bokeh >=2.0), now all version dependencies are solved, but it shows an error when rendering holoview object when following [Panel tutorial](https://panel.holoviz.org/getting_started/build_app.html#reactive-functions):

```py
first_app = pn.Column(window, sigma, interactive)

first_app
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File {path_to_project}/.venv/lib/python3.11/site-packages/jupyter_bokeh/widgets.py:135, in BokehModel._sync_model(self, _, content, _buffers)
    133         cb(attr, old, new)
    134 elif kind == 'MessageSent':
--> 135     self._document.apply_json_event(content["msg_data"])

AttributeError: 'Document' object has no attribute 'apply_json_event'
```

I also report this issue in [jupyter_bokeh #192](https://github.com/bokeh/jupyter_bokeh/issues/192).

I have no idea how to start up my first Panel rendering in my VSCode. Is there any tutorial about that?

## try using jupyter-bokeh 2.0.4 but it render nothing in VSCode

With jupyter-bokeh 2.0.4, it renders nothing in my VSCode (official panel tutorial code):

![Screenshot 2023-04-21 at 10 59 56](https://user-images.githubusercontent.com/804308/233530252-61284215-084d-4d46-b7d9-f15cfc98a442.png)

**Comment by MarcSkovMadsen** [comment]
Hi @xareelee . Panel does not yet work with Bokeh >= 3.

Bokeh 3 on the surface might not seem like a major change. But underneath it is. And it will enable many, many improvements in Panel.

There is a major effort ongoing to get Panel 1.0 ready with support for Bokeh 3. Last target release date I have heard is beginning of May.

**Comment by xareelee** [comment]
@MarcSkovMadsen Thanks for your reply.

I've also tried Bokeh 2.4.3 with jupyter-bokeh 2.0.4 together, it did not render anything in my VSCode with Jupyter Notebook (`.ipynb`). 

I try to put all code in a `dashboard.py` file, and run it with `panel serve dashboard.py --show --autoreload`. It did render in my browser.

I still need to make my `.ipynb` file to render the holoview in VScode. Any suggestion?

**Comment by xareelee** [comment]
I tried to use ipywidgets, and it renders the UI, but Panel did not. I really don't know why.

![Screenshot 2023-04-23 at 12 46 16](https://user-images.githubusercontent.com/804308/233820367-bbb51c90-29c3-46cc-9690-2c144695f818.png)

**Comment by xareelee** [comment]
After removing miniconda, it now can render.
