### ISSUE TITLE
Reorder and Rename top entries in toc tree

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4681]
Based on my experience with Panel we should

- Rename the "Gallery" to "App Gallery" and move it to the right (After Reference Gallery)
- Rename "Reference Gallery" to "Component Gallery". The word might not cover 100% but users would know what to expect here. In my experience the "Component Gallery" is used very often when a user has learned the basics. Component Gallery is also what every javascript framework has. So I think this is the right word to use.
- Consider renaming "Background" to "Explanation". Diataxis and Matplotlib uses this term. This will help users recognize what this is.

![image](https://user-images.githubusercontent.com/42288570/233802039-3d31a7d6-3f86-4b50-9be1-2d84e60c432a.png)

**Comment by MarcSkovMadsen** [comment]
I'm experimenting with these changes in https://github.com/holoviz/panel/pull/4674

**Comment by MarcSkovMadsen** [comment]
Ahhh. Makes so much more sense.

![image](https://user-images.githubusercontent.com/42288570/233805264-e35069c3-1598-495a-8734-5b9f27e809a3.png)

**Comment by philippjfr** [comment]
+1 on all of this. Would love to hear @droumis' thoughts but we were never quite happy with "Background" so I'm fully on board.

**Comment by droumis** [comment]
+1 on the Gallery renaming.

I dislike 'Background' more than 'Explanation' and I can't think of anything better so +1 from me on this as well!

**Comment by maximlt** [comment]
Should not forget to set redirect links together with these changes.
