### ISSUE TITLE
Fenced code block not rendering nicely in Markdown pane on `main` branch

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4698]
I was testing out the improved Markdown in Panel 1.0 on the `main` branch. When I serve a fenced code block Markdown pane it does not render nicely without or with templates.

```python
import panel as pn

pn.extension(sizing_mode="stretch_width")

pn.pane.Markdown("""
``python
import panel as pn
import requests

pn.extension(sizing_mode="stretch_width", template="fast")

@pn.cache()
def get_text():
    url = "https://www.markdownguide.org/assets/markdown-cheat-sheet.md"
    return requests.get(url).text
text = get_text()

pn.pane.Markdown(text).servable()
``
""").servable()
```

(change double ticks to triple ticks in above text)

I do not see any issues in the browser console

![image](https://user-images.githubusercontent.com/42288570/234650940-58fa7440-9daa-49c3-83b4-a2862847284a.png)

**Comment by MarcSkovMadsen** [comment]
If I change the `--code-bg-color` to `black` it looks very nice indeed.

![image](https://user-images.githubusercontent.com/42288570/234660943-e2188494-dc04-4c49-b252-674b7b4a7cbe.png)

**Comment by philippjfr** [comment]
This has already been fixed, the CDN just hadn't updated.

**Comment by philippjfr** [comment]
Or rather in your case I don't think you re-bundled with `panel bundle --themes --local-only`

**Comment by MarcSkovMadsen** [comment]
I believe I did run `python setup.py develop` as described in https://pyviz-dev.github.io/panel/developer_guide/index.html#bundling-resources. But there is nothing about `panel bundle --themes --local-only` in the developer docs.

**Comment by philippjfr** [comment]
>I believe I did run python setup.py develop as described in https://pyviz-dev.github.io/panel/developer_guide/index.html#bundling-resources.

That works just fine too, I just checked.

**Comment by MarcSkovMadsen** [comment]
Somehow a way to easily get "updated" when you `git pull origin main` would help a lot. You are always "up to date". But everyone else will have to do things corresponding to creating a new virtual developer environment. And thats a lot of work.

**Comment by philippjfr** [comment]
Pulling all the bundled resources all the time is very expensive, updating only the local resources should be feasible though.

**Comment by philippjfr** [comment]
Reminds me, that I need to implement a CSS minifier in the local bundling step.

**Comment by MarcSkovMadsen** [comment]
But a section on "Getting updated after pull from main". Right now its not very clear what to do and what not to do.

**Comment by philippjfr** [comment]
The hatch PR is the place to bring this up.

**Comment by MarcSkovMadsen** [comment]
I believe you currently need to 

- rerun `pip install -e .[all, build] -U`
- run `python setup.py develop`
- Hard refresh your browser

But I don't know if thats enough or too much?

**Comment by MarcSkovMadsen** [comment]
> panel bundle --themes --local-only

This command does not work on current `main` branch for me @philippjfr 

![image](https://user-images.githubusercontent.com/42288570/234961053-72c344de-6859-484b-8706-db40344e6e2f.png)

I have run `python setup.py develop`, but I'm still struggling with the FastTemplates

![image](https://user-images.githubusercontent.com/42288570/234961456-ef360544-4332-4303-9e61-fcd0a83d84a5.png)

I want to contribute a screenshot to this example https://pyviz-dev.github.io/panel/getting_started/core_concepts.html#templates

**Comment by philippjfr** [comment]
Yeah, I messed that up, should be `panel bundle --themes --only-local`

**Comment by philippjfr** [comment]
And run `panel bundle --all` once just to be sure that you've bundled all the latest resources.
