### ISSUE TITLE
Templating improvements

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#470]
- [ ] Add global `pn.config.template` which allows overriding the default template
- [ ] Add various default templates
  - [ ] AdminLTE
  - [ ] Bootstrap grid
  - [ ] Foundation
  - [ ] Materialize
  - ... (More suggestions welcome)

**Comment by fj-sanchez** [comment]
Foundation?

**Comment by MarcSkovMadsen** [comment]
Hi @philippjfr 

I'm thinking a little bit different here (I think :-)).

It's nice with some templates where you can add plots to. But to me they are there for inspiration or as a starting point. 

What I would really like is actually to be able to access a combination of basic app Templates and then additional layouts and widgets corresponding to the style of the template.

For example for awesome-panel.org I have a BootstrapDashboardTemplate with a header, sidebar and then additional bootstrap inspired widgets and layouts.

So I would really like access to something like

```python
# Bootstrap
pn.framework.bootstrap.BootstrapDashboardTemplate
pn.framework.bootstrap.Bootstrap.widgets.InfoAlert
pn.framework.bootstrap.Bootstrap.widgets.WarningAlert
pn.framework.bootstrap.Bootstrap.widgets.ErrorAlert
pn.framework.bootstrap.Bootstrap.layouts.Modal
pn.framework.bootstrap.Bootstrap.layouts.Card
...

# Material
pn.frameworks.material.MaterialTemplate
pn.frameworks.material.Button
pn.frameworks.material.Card
pn.frameworks.material.Checkbox
pn.frameworks.material.Chips
pn.frameworks.material.Dialog
...

# Vaadin
pn.frameworks.vaadin.CheckBox
pn.frameworks.vaadin.ComboBox
pn.frameworks.vaadin.CustomField
pn.frameworks.vaadin.DatePicker
pn.frameworks.vaadin.EmailField
...
pn.frameworks.vaadin.AppLayout
...

and I would like be able to specify from which of these frameworks the widgets for `pn.Param` and any parameters are taken, so that its easy to use these things.

Maybe this is too ambitious. My hope would be that some of this work could be semi-automated. Wrapping these components into bokeh models and the panel layouts/ widgets is close to the same for each. So maybe creating some code to create boiler plate code or maybe some code to reduce the needed boiled plate code could be an idea.

Also we would not need to implement everything up front. For awesome-panel.org I have working implementations of the listed bootstrap components. Thus this might be enough as a starter to build an application.

And maybe the BDFL of Panel could decide which of these frameworks would be the main framework for Panel and where the main effort and support would be.

And maybe these frameworks could or should be provided as seperate packages?

All of the above are ideas only. I hope it could foster a discussion and some decissions. 

I just think that providing something like the above would be awesome. It would make it easy to create awesome looking analytics apps in Python that can compete with what you get from a modern front end framework like Angular, React or Vue.

And this would enable to very quickly build apps in line with the tweet https://twitter.com/pwang/status/1228705376209686529?s=20

**Comment by MarcSkovMadsen** [comment]
I would like to contribute the bootstrap things i have already developed at awesome-panel.org if you would like them. Just let me know @philippjfr .

**Comment by MarcSkovMadsen** [comment]
Regarding the app templates. 

It would be nice if they had the same api across the different frameworks. Making it easy to switch.

It would be nice of some of the settings where parameterized. For example the color paletter or the template style like white or dark.

**Comment by MarcSkovMadsen** [comment]
Another interesting set of web components is https://www.predix-ui.com/#/gallery that was developed by GE. There is really a large set of components.

**Comment by MarcSkovMadsen** [comment]
Inspiration for templates can also be found here

https://www.htmlelements.com/demos/

**Comment by MarcSkovMadsen** [comment]
FYI @philippjfr . I've started contributing my ideas and code regarding app templates and themes here https://github.com/holoviz/panel/pull/1157.

**Comment by MarcSkovMadsen** [comment]
Regarding templates. I think there is a lot of inspiration for example here https://themes.getbootstrap.com/.

If someone can demonstrate its actually easy to use some of those themes (especially frontpage+gallery+dashboard themes) in Panel that would be awesome.

**Comment by philippjfr** [comment]
Closing since this discussion is outdated and we've now added a number of custom templates.
