### ISSUE TITLE
Feature Request: Searchable Multi-Select Dropdown

### ISSUE THREAD

**Issue by sr2424** [holoviz/panel#471]
I would like to ask for a new widget that behaves similar to the Dash dropdown or Select2 dropdown.

Dash Dropdown:  https://dash.plot.ly/dash-core-components/dropdown
Select2:  https://select2.org/

The CrossSelector widget is close to what I'm looking for, but it doesn't give the full functionality.  I would like to be able to search/filter the dropdown and select multiple entries.  I use the Dash version to select individual parameters that are a various temperature, pressure, speed, etc... telemetry with datetime, value pairings and quickly plot the parameter. However, I would prefer to use panel and have the ability to use hvplot and datashader for larger datasets.

**Comment by jbednar** [comment]
Can you elaborate a bit?  The [CrossSelector](https://panel.pyviz.org/reference/widgets/CrossSelector.html#gallery-crossselector) seems like it already has filtering and selecting multiple entries.  Is searching (as for Autocompleteinput) the missing bit?

**Comment by sr2424** [comment]
Sorry for the slow response.  Maybe it's an option/customization that I don't realize. If I have a list of options that is hundreds of items long, then scrolling through everything isn't possible. If each option has some built in structure, i.e. TX Apple Green ("State Fruit Color"), then you can filter using the text in order, but not out of order.  The other difficulty is that the filter, selects options, but doesn't filter the list of options.  If you are trying to select just one or two out of hundreds with an expected return on your filter being 10 or so, then it is difficult to accomplish this.  I am using this for selecting data parameters to chart.  The options list I have has location, hardware set, component, parameter/sensor type information in the option text.  This can all be broken down into multiple drop down boxes and linked, but I prefer the simplicity of a single box for searching, selecting, and tracking of the selections.

**Comment by xavArtley** [comment]
Like here?
https://github.com/pyviz/panel/issues/392

**Comment by sr2424** [comment]
The new multichoice widget in bokeh 2.0 adds this feature.  It looks like it will be available with 0.9 release.
https://github.com/bokeh/bokeh/pull/9546
