### ISSUE TITLE
FastListTemplate Issues

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4714]
If you go to https://panel-gallery-dev.pyviz.demo.anaconda.com/portfolio_analyzer 

- [] The reset button in the upper right corner is missing its background color (maybe its on purpose?)
- [] The hyperlink in the table is not using the accent color

![image](https://user-images.githubusercontent.com/42288570/234858196-6ed1b0e3-3f17-4eeb-859f-6614be4f050f.png)

**Comment by MarcSkovMadsen** [comment]
Besides that the app is really impressive and the fast layout updates when you resize a panel or the browser windows is just amazing.

**Comment by philippjfr** [comment]
Superseded by: https://github.com/holoviz/panel/issues/4727
