### ISSUE TITLE
vtk_slicer demo app issues

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4718]
https://panel-gallery-dev.pyviz.demo.anaconda.com/vtk_slicer

[] Its not using the Panel Icon

![image](https://user-images.githubusercontent.com/42288570/234919024-45a1c520-72fb-4ce1-ba5a-c3510c38d883.png)

[] Widgets in the sidebar are not responsive. So when the window width is decreased they get cut off.

![image](https://user-images.githubusercontent.com/42288570/234919514-9220442c-db68-44d8-b57d-a674bf498bf7.png)

[] There is no loading indicator. For example when changing the dataset the app is inactive for a longer period of time.

**Comment by philippjfr** [comment]
> Its not using the Panel Icon

Yeah there's something off about template inheritance, so it inherits from the Bokeh base template, not ours.

> Widgets in the sidebar are not responsive. So when the window width is decreased they get cut off.

Easy fix, want to submit a PR? 😄 

>There is no loading indicator. For example when changing the dataset the app is inactive for a longer period of time.

Also seems like a simple fix, same PR? 😁

**Comment by MarcSkovMadsen** [comment]
ok
