### ISSUE TITLE
Dev Swipe reference notebook not working in Pyodide

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4729]
I was testing out https://pyviz-dev.github.io/panel/reference/layouts/Swipe.html and running it in pyodide. The last cell fails.

![image](https://user-images.githubusercontent.com/42288570/235160246-f59ef0fe-0e2b-465c-8a83-7cf7d322df3c.png)

**Comment by Hoxbro** [comment]
Missing scipy:

![image](https://user-images.githubusercontent.com/19758978/235162103-1ef66f48-0d74-4503-8759-795846307ec8.png)

**Comment by MarcSkovMadsen** [comment]
Migrated to #4735
