### ISSUE TITLE
Dev Documentation Issues

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4735]
I've been asked on Discord to post all `dev` Docs  issues identified pre the 1.0 release in one Bug Report. So here goes.

## Migrated Issues

For details see

- [ ] App Thumbnails not looking nice (see below)
- [ ] Twitter not using new logo, tagline and description
- [ ] Discord Invite link is invalid (see below)
- [ ] #4732
- [ ] Old Jupyter Panel Preview icon shown
- [ ] CodeEditor Control not shown component page
- [ ] JS Linked Controls in reference docs not working
- [ ] VTK Interactive app demo app never loads (see below)
- [ ] Panelite version not in sync with docs (see below)
- [ ] Improve app sign buttons
- [x] #4734
- [x] #4733
- [x] #4731
- [x] #4730
- [x] #4729
- [x] #4728
- [x] Debugger issues (see below)
- [x] Favicon on demo apps needs update (see below)
- [x] source link in Gallery points to app not code. See https://twitter.com/gypsyvirus/status/1654212248737394688?s=46&t=QCeLnYcdhHHHwawHQ7y8xA

**Comment by philippjfr** [comment]
Thank you!

**Comment by philippjfr** [comment]
Most of these were easy fixes, not sure about the Bokeh one yet.

**Comment by MarcSkovMadsen** [comment]
## Debugger Issues

When I go to https://pyviz-dev.github.io/panel/reference/widgets/Debugger.html, I see 

### 1 - Wird button

![image](https://user-images.githubusercontent.com/42288570/235829993-0f6bfbd1-893c-492e-850f-3af0d44f26b6.png)

The play symbol confuses me. Should it be there. 1 min later I realize its a collapsed accordion. I think either the button should be vertically alligned such that the header looks like a button to be clicked or that in the example the debugger should be expanded by default.

### 2 - Too little container

The example below is put in a very small container with a scrollbar which makes it not very useful

![image](https://user-images.githubusercontent.com/42288570/235830259-be42bb32-3acf-422a-b813-144036d4959c.png)

### 3 - Missing Icon

![image](https://user-images.githubusercontent.com/42288570/235830341-a9382f68-d352-4be4-a530-a714af71fab9.png)

**Comment by MarcSkovMadsen** [comment]
## Favicon on demo apps needs update

For example https://panel-gallery-dev.pyviz.demo.anaconda.com/vtk_interactive

![image](https://user-images.githubusercontent.com/42288570/236020845-4821c2a3-e560-4c2d-b5e2-c6c591e40e6a.png)

## VTK Interactive app never loads

If I go to For example https://panel-gallery-dev.pyviz.demo.anaconda.com/vtk_interactive the app loads for ever

![image](https://user-images.githubusercontent.com/42288570/236020925-63da0c99-211b-46cd-833a-faedc0b34fe7.png)

**Comment by MarcSkovMadsen** [comment]
## CodeEditor Control not shown component page

If I go 1) to https://pyviz-dev.github.io/panel/reference/widgets/CodeEditor.html and 2) run the docs in pyodide and 3) navigate to the Controls section I don't see the `CodeEditor`.

![image](https://user-images.githubusercontent.com/42288570/236023239-532381ee-8e51-432c-af30-dfcf742e79f1.png)

**Comment by philippjfr** [comment]
There's three apps that load:

- vtk_interactive
- vtk_wrap
- iris_kmeans

Haven't worked out why yet, logs show no errors.

**Comment by MarcSkovMadsen** [comment]
## Twitter not using new logo, tagline and description

Still looks like

![image](https://user-images.githubusercontent.com/42288570/236040441-755e9d9e-32f3-4180-b06b-ed5a5841513b.png)

I've updated Linked In which looks like

![image](https://user-images.githubusercontent.com/42288570/236040657-f3857c3b-c7e0-4a69-afa5-4cba25b9068b.png)

I've been using the below cover image

![collage_0 14](https://user-images.githubusercontent.com/42288570/236040742-64eacc70-e5c7-494f-922c-c6159b3e7b0c.png)

**Comment by philippjfr** [comment]
Favicons are currently served from the main docs page, so they will reflect the changes when complete. That said, I don't think they should be pointing to the docs, we should have a copy of the favicon in the `dist` directory so we can serve it from CDN.

**Comment by MarcSkovMadsen** [comment]
## App Thumbnails not looking nice

On the front page the app thumbsnail are too big and there are too many.

I would recommend having just the 4 best and then saving awesome-panel.org for the App Gallery.


![image](https://github.com/holoviz/panel/assets/42288570/e0d5a42d-abd8-40a0-8cd2-6e41ad313bd1)

**Comment by MarcSkovMadsen** [comment]
## Discord Invite is invalid

It seems the discord invite link has expired!? https://discord.gg/muhupDZM

![image](https://github.com/holoviz/panel/assets/42288570/43a30318-d0c7-488a-b44c-a01f3081348b)


![image](https://github.com/holoviz/panel/assets/42288570/9c91f429-dd70-45ec-9e49-861893f4405a)

**Comment by MarcSkovMadsen** [comment]
## Improve app sign buttons

It would be **nice** to

- have the signs have the same width. (The right part should stretch).
- Help the user more by changing "server" to "server app" and "pyodide" to "pyodide app". Or adding tooltips. Especially for the second button I did not know what to expect before clicking the button. And newbies would not understand they open an app running on Pyodide.

![image](https://github.com/holoviz/panel/assets/42288570/45c0aefb-dc47-4ce7-85e1-ae908996fedc)

**Comment by MarcSkovMadsen** [comment]
## Old Jupyter Panel Preview icon shown

When I open Jupyter lab (installed in `panel_dev` environment) I still see the green icon. Not the new blue icon.

![image](https://github.com/holoviz/panel/assets/42288570/0e9b5f79-be92-46a8-99a1-4ef44eae4c6f)

**Comment by philippjfr** [comment]
>Panelite version not in sync with docs

This is not true, it's just that you have a cached version running locally and Jupyterlite does not provide a reasonable way to cache bust. The new Getting started notebook includes some code to reset your Jupyterlite cache.
