### ISSUE TITLE
widgets and pane not shown

### ISSUE THREAD

**Issue by gorkir** [holoviz/panel#4749]
Hi, I have installed panel version 1.0 and found that in Jupyter-lab widgets and pane not show. 
I read the sugestions about  "For versions of jupyterlab>=3.0 the necessary extension is automatically bundled in the pyviz_comms package, which must be >=2.0." . The version of Jupyter-lab is 3.5 and of the pacjkage pyviz_comms 2.0.2.

Example from panel dev website:
import panel as pn
pn.extension()
pane = pn.panel('<marquee>Here is some custom HTML</marquee>')
pane

The pane is not shown, but when I run 
print(pane)
is shown
Markdown(str)

**Comment by philippjfr** [comment]
I'm working on improving this workflow before full release but can you try following these steps:

1. Close all but on JupyterLab tab
2. Restart and Clear all outputs
<img width="303" alt="Screen Shot 2023-04-30 at 19 41 06" src="https://user-images.githubusercontent.com/1550771/235367960-18d9fe9f-9e5d-47c9-95a6-2a7a2dddff61.png">
3. Save the notebook
4. Reload the browser page
5. Rerun the notebook

**Comment by gorkir** [comment]
Yes, it works.
Thanks

**Comment by philippjfr** [comment]
Should be fixed permanently by https://github.com/holoviz/panel/pull/4752
