### ISSUE TITLE
Featured dev examples are down

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4755]
For example https://panel-gallery-dev.pyviz.demo.anaconda.com/portfolio_analyzer gives a 404 as pointed out by a potential user in  
https://www.linkedin.com/posts/panel-org_python-pydata-pyviz-activity-7057975427977342976-R7Op?utm_source=share&utm_medium=member_ios

When I try the other featured apps on the dev home page I also get a 404.

**Comment by philippjfr** [comment]
Need to figure out a way how we can safeguard this and get notifications when it's down more than a few minutes.

**Comment by philippjfr** [comment]
Have redeployed and set up an uptime robot that emails developers@holoviz.org and posts to Discord.
