### ISSUE TITLE
7 Strange Employees on LinkedIn

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4768]
If I go to LinkedIn, I see 7 strange people/ employees including an owner

https://www.linkedin.com/company/panel-org/people/?viewAsMember=true

![image](https://user-images.githubusercontent.com/42288570/236036938-98f7b564-82ad-4a45-91b5-8d86c0e5f8cb.png)

They should be removed.

**Comment by maximlt** [comment]
Thanks for reporting that, I don't think there is much we can do. I'm going to close as I really have no clue how to label such an issue, that's in my opinion clearly outside of the scope of a Github issue tracker.

**Comment by MarcSkovMadsen** [comment]
You can do something about it by reporting it to linkedin as described in the link above. Its about credibility and trust.

Having people associated, especially and owner, that has nothing to do with the project is not credible.

The Github issue tracker is just a tracker. Can be used for tracking anything really. Also issues with one of the associated web sites.

I would suggest reopening and fixing.
