### ISSUE TITLE
Panel not working in VSCODE

### ISSUE THREAD

**Issue by pcdeadeasy** [holoviz/panel#4776]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

Selected Jupyter core packages...
IPython          : 8.13.1
ipykernel        : 6.22.0
ipywidgets       : 8.0.6
jupyter_client   : 8.2.0
jupyter_core     : 5.3.0
jupyter_server   : 2.5.0
jupyterlab       : 3.6.3
nbclient         : 0.7.4
nbconvert        : 7.3.1
nbformat         : 5.8.0
notebook         : 6.5.4
qtconsole        : 5.4.2
traitlets        : 5.9.0

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

import panel as pn  # GUI
pn.extension(comms="vscode")
pn.pane.Markdown("Hello")

Nothing gets rendered.

**Comment by philippjfr** [comment]
Thanks @pcdeadeasy. Could you report the panel version you are using?

**Comment by XT1108** [comment]
I met the similar issue: panel V0.14.4 needs  installation bokeh==2.4.3, but the Jupyter lab needs installation jupyter_bokeh==3.0.*. So they can not run in the same virtual environment.  However, the program can run , I guess the Jupyter lab find the higher level jupyter_bokeh==3.0.7.

**Comment by Hoxbro** [comment]
I have it working in VS Code, but I'm running on the latest dev releases. The next release, 1.0, will be out in the coming days. 

If the problem is still there after the 1.0 upgrade, please say so and write down all your dependencies with `pip list` or `conda list` in the environment you are using.

**Comment by XT1108** [comment]
Thanks for your reply, I highlighted the points with bold text in the following pip list.

jupyter-bokeh==3.0.7
  **- bokeh [required: ==3.*, installed: 2.4.3]**
    - Jinja2 [required: >=2.9, installed: 3.1.2]
      - MarkupSafe [required: >=2.0, installed: 2.1.2]
    - numpy [required: >=1.11.3, installed: 1.24.3]
    - packaging [required: >=16.8, installed: 23.1]
    - pillow [required: >=7.1.0, installed: 9.5.0]
    - PyYAML [required: >=3.10, installed: 6.0]
    - tornado [required: >=5.1, installed: 6.3.1]
    - typing-extensions [required: >=3.10.0, installed: 4.5.0]
  - ipywidgets [required: ==8.*, installed: 8.0.6]
    - ipykernel [required: >=4.5.1, installed: 6.22.0]



panel==0.14.4
  - bleach [required: Any, installed: 6.0.0]
    - six [required: >=1.9.0, installed: 1.16.0]
    - webencodings [required: Any, installed: 0.5.1]
  - **bokeh [required: >=2.4.0,<2.5.0, installed: 2.4.3]**
    - Jinja2 [required: >=2.9, installed: 3.1.2]
      - MarkupSafe [required: >=2.0, installed: 2.1.2]
    - numpy [required: >=1.11.3, installed: 1.24.3]
    - packaging [required: >=16.8, installed: 23.1]
    - pillow [required: >=7.1.0, installed: 9.5.0]
    - PyYAML [required: >=3.10, installed: 6.0]
    - tornado [required: >=5.1, installed: 6.3.1]
    - typing-extensions [required: >=3.10.0, installed: 4.5.0]
  - markdown [required: Any, installed: 3.4.3]
  - param [required: >=1.12.0, installed: 1.13.0]
  - pyct [required: >=0.4.4, installed: 0.5.0]
    - param [required: >=1.7.0, installed: 1.13.0]
  - pyviz-comms [required: >=0.7.4, installed: 2.2.1]
    - param [required: Any, installed: 1.13.0]
  - requests [required: Any, installed: 2.30.0]
    - certifi [required: >=2017.4.17, installed: 2023.5.7]
    - charset-normalizer [required: >=2,<4, installed: 3.1.0]
    - idna [required: >=2.5,<4, installed: 3.4]
    - urllib3 [required: >=1.21.1,<3, installed: 2.0.2]
  - setuptools [required: >=42, installed: 67.7.2]
  - tqdm [required: >=4.48.0, installed: 4.65.0]
  - typing-extensions [required: Any, installed: 4.5.0]
  -

**Comment by pcdeadeasy** [comment]
Just FYI after some intense debugging I was able to get things working in the anaconda 3 environment, running Python 3.10.9 in a JupyterLab notebook in vscode.

These are the version of the modules:
bokeh: 2.4.3
panel: 0.14.4
jupyter_bokeh: 3.0.5

jupyter --version
Selected Jupyter core packages...
IPython          : 8.10.0
ipykernel        : 6.19.2
ipywidgets       : 7.6.5
jupyter_client   : 7.3.4
jupyter_core     : 5.2.0
jupyter_server   : 1.23.4
jupyterlab       : 3.5.3
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.7.0
notebook         : 6.5.2
qtconsole        : 5.4.0
traitlets        : 5.7.1

Thanks for all your help.

**Comment by philippjfr** [comment]
Really appreciate you following up here, @pcdeadeasy! We'll likely release Panel 1.0 tomorrow or Wednesday at which point you can upgrade to latest bokeh and jupyter_bokeh.
