### ISSUE TITLE
cache policy not functionning

### ISSUE THREAD

**Issue by hyamanieu** [holoviz/panel#4785]
#### ALL software version info
Panel 0.14.4

#### Description of expected behavior and the observed behavior

Documentation states that the `policy` argument of the `pn.cache` decorator can either accept FIFO, LRU, or LFU.

However there is an error https://github.com/holoviz/panel/blob/2d471ce991d15ac40f644f3e320bbecb07fbc04d/panel/io/cache.py#L242, 'lifo' is expected instead of 'fifo', and there is no else.

I would advise to:

1. control the input `policy` to make sure it respects the boundaries ('FIFO', 'LRU','LFU'). Why not use `param`?
2. fix the typo in line 242

I could do a PR for point 2 as it's simple, but for point 1 it's about design.

**Comment by philippjfr** [comment]
We could indeed use a ParameterizedFunction here, seems like overkill though.
