### ISSUE TITLE
embed() fails for some widgets

### ISSUE THREAD

**Issue by poplarShift** [holoviz/panel#479]
```
import panel as pn # 0.6.0
pn.extension()

plotsel = pn.widgets.CheckBoxGroup(name='Panels', value=['mean'], options=['mean', 'int', 'r'])

plotsel.embed()
```
fails with `AttributeError: 'CheckboxGroup' object has no attribute 'value'`.

This also happens for some other widgets, e.g. `pn.widgets.CheckButtonGroup`.

**Comment by maximlt** [comment]
I have no error when I run that, @poplarShift dou you still get this error? Thanks!

**Comment by poplarShift** [comment]
Nope, gone on `0.9.5`! :)
