### ISSUE TITLE
Feature request: pn.pane.Pill() and/or pn.pane.Badge()

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#4799]
#### Is your feature request related to a problem? Please describe.
Would like a pill pane; looks like a button, but is more round and isn't clickable. It can be hovered over if hover_text is available.

#### Describe the solution you'd like
HTML + CSS like this with options to have left / right labels or single labels.
https://codepen.io/calebnance/pen/MKEobV
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/15331990/236703264-7abe3d1b-7c3a-4e94-b3db-dc0c079eed17.png">

#### Describe alternatives you've considered
Wrapping HTML / CSS manually.

Not sure if Pill + Badge should be a single pane, or separate. I can see the badge as multiple label while pill as single label with hoverable text.

#### Additional context
Gmail:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/15331990/236702981-03c88fe5-11cc-4fd7-bd6f-be109c75ee4c.png">
<img width="47" alt="image" src="https://user-images.githubusercontent.com/15331990/236702993-8a2bfd68-21de-4b96-850b-f1fcfe892c14.png">
weatherspark.com
<img width="561" alt="image" src="https://user-images.githubusercontent.com/15331990/236702999-8a0f52c5-69af-48e3-b8bb-efc70449972f.png">
https://www.leagueofgraphs.com/
<img width="440" alt="image" src="https://user-images.githubusercontent.com/15331990/236703122-550dff5a-eef7-45e8-866a-328efb1f8ba4.png">

**Comment by ahuang11** [comment]
I believe this can be done with Button and description kwarg now.

**Comment by davidhyman** [comment]
This would be useful. If the functionality is already available, perhaps it could be exposed through a more semantically correct api (e.g. `badge` or `pill` that inherits from `button` to configure it in this manner).

Alternatively to document how to achieve this using the existing components.

@ahuang11 to help others such as myself it would be greatly appreciated if you could provide a few more hints / examples as to how you configured button to behave like this.

e.g. I would think it needs to set `disabled=True` but the styling that results seems incorrect for this usage.

**Comment by philippjfr** [comment]
I agree, buttons are not the same as pills. Note that I'm planning to release [panel-material-ui](https://github.com/panel-extensions/panel-material-ui) soon, which will have a pill component.

**Comment by Coderambling** [comment]
Does the Chip pane provide the Pill functionality as discussed above in pmui, @philippjfr ?

https://panel-material-ui.holoviz.org/reference/panes/Chip.html#

Or can / should it be achieved using Button somehow?

Either way, searching for "Pill" in the pmui docs does not return any results. I will add a phrase about Pill to the docs once I have feedback on the above, so users can find it when they search for it.

**Comment by ahuang11** [comment]
Alternatively https://discourse.holoviz.org/t/statusbadge-implementation/8653

**Comment by Coderambling** [comment]
Thanks!  So this makes it currently possible in both Panel and pmui?

Would still like to know if Chip is a better / easier way to achieve this (with less code?), so we can point users that way.

Have you used Chip already in (chat) implementations?

**Comment by Coderambling** [comment]
Is Chip also the preferred way to create a Badge?

I see Chatstep -> Badge in pmui, but what is the preferred way to create badges in general in pmui?

If Chip (or Button?) is the way, "badge and "badges" should be part of the wording in the doc, so users can at least find it when then enter one of those words as a search term, and so that those words can be picked up by search and AI crawlers for indexing / ingesting.

https://panel-material-ui.holoviz.org/reference/chat/ChatStep.html#badges

**Comment by Coderambling** [comment]
Related / overlap with this issue:

https://github.com/panel-extensions/panel-material-ui/issues/195

MUI has a Badge component @ahuang11 , but it is not implemented yet in pmui.

https://mui.com/material-ui/react-badge/

**Comment by ahuang11** [comment]
Ah I think the MUI chip functionality is what I wanted, I probably mixed up the terminology
