### ISSUE TITLE
panel==1.0.0rc7 cannot be served on JupyterHub using jupyter server proxy

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4816]
panel==1.0.0rc7

I use Panel on our JupyterHub. Normally I can `panel serve script.py` and open it in my browser. It works because we have the jupyter server proxy installed.

I tried upgrading to panel==1.0.0rc7. Now I can no longer serve my app because the bokeh and panel `.js` files is searched for on localhost which is not correct.

## Reproducible example

```python
import panel as pn

pn.extension()

pn.panel("hello").servable()
```

```bash
panel serve script.py
```

Open https://DOMAIN/WORKSPACE/user/USERNAME/proxy/5006/script

See the errors in the console.

![image](https://github.com/holoviz/panel/assets/42288570/f70be166-9c02-45a6-b49f-e27abdb455de)

![image](https://github.com/holoviz/panel/assets/42288570/ede60a02-24e2-4dc5-baaf-c8c1de990b3c)

**Comment by MarcSkovMadsen** [comment]
As far as I can see this will not only affect my work on the JupyterHub. It will affect any deployment @philippjfr

**Comment by Hoxbro** [comment]
Can you try setting the environment variable `BOKEH_RESOURCES=cdn`?

**Comment by philippjfr** [comment]
This does seem like a critical regression, just wondering what the previous behavior was and why it's switching to server resources now.

**Comment by philippjfr** [comment]
To be clear, server resources have always been the default for `panel serve` so I'm confused how that worked before without overriding the resource configuration.

**Comment by philippjfr** [comment]
Ah I guess the problem is absolute vs relative resources. Think I know then.

**Comment by MarcSkovMadsen** [comment]
Exactly

**Comment by MarcSkovMadsen** [comment]
@Hoxbro . It works with  `BOKEH_RESOURCES=cdn panel serve script.py`. 

Changing the local resources from relative to absolute is a major breaking change though and would be problematic to anyone working or deploying behind a reverse proxy.

**Comment by Hoxbro** [comment]
I just wanted to know if it worked.  

I agree with you that it is a breaking change.

**Comment by MarcSkovMadsen** [comment]
I just tried with panel==1.0.0rc8 and the issue is still there. But this time its only the `panel.min.js` file that is served at an absolute url.

**Comment by philippjfr** [comment]
Ugh, that's in a completely different part of the codebase. @mattpap are you aware that your recent changes to resource handling in 3.1.1 seem to have switched resource paths from relative to absolute URLs?

**Comment by philippjfr** [comment]
I guess that was the intention behind https://github.com/bokeh/bokeh/pull/13041. Will have to dig in more deeply to understand all implications.

**Comment by mattpap** [comment]
> I guess that was the intention behind https://github.com/bokeh/bokeh/pull/13041. Will have to dig in more deeply to understand all implications.

This wasn't intentional and I would consider this a regression.
