### ISSUE TITLE
Dev docs search broken

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#4817]
The dev docs search is broken.

Link: https://pyviz-dev.github.io/panel/search.html?q=spam

Error: This site can’t be reached

<img width="1173" alt="Screenshot 2023-05-10 at 08 23 28" src="https://github.com/holoviz/panel/assets/852409/98e4d5ee-e015-45f7-b2d5-0a597344c319">

**Comment by cdeil** [comment]
It also seems outdated. At https://pyviz-dev.github.io/panel/ I see "v1.0.0rc1" but newer dev releases are available.

**Comment by Hoxbro** [comment]
A new dev website has been released, which fixes this. :+1:
