### ISSUE TITLE
FloatPanel is not displayed on button click

### ISSUE THREAD

**Issue by ivandorte** [holoviz/panel#4841]
panel==1.0.0rc8
bokeh>=3.1.1,<3.2.0
holoviews>=1.16.0a2

OS: Ubuntu 22.04.2 LTS, WSL 2, Windows 11
Tested in Chrome and Edge

Please document how to open a FloatPanel on button click within the same data app. 

This is what i've tested so far in my data APP:
https://github.com/ivandorte/eo-notebooks-apps/blob/db610539b6c1e5d84d00afbeceed8ad2a6ec3853/s2-panel-app/app.py#L318-L352

You can find the full code of the data APP here:
[s2-panel-app](https://github.com/ivandorte/eo-notebooks-apps/tree/main/s2-panel-app)

This is what I would like to obtain:
![05](https://github.com/holoviz/panel/assets/1726395/fb7cdfe5-e978-4171-a537-1d042621a39f)

**Comment by philippjfr** [comment]
Thanks @ivandorte, this issue is not a bug but incorrect usage of Panel APIs. Please post an issue to our Discourse to ask how to add components dynamically.
