### ISSUE TITLE
Simplify notifications import

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4848]
With panel==1.0.0rc8 you have to specify `notifications` twice to `pn.extension`.

For example like

```python
pn.extension("terminal", "notifications", notifications=True, design="bootstrap")
```

This is hard to remember and overcomplicates the user experience. I would recommend to simplify things such that only one of the two is required.

If we are to pick I believe the "notifications" would be the one I prefer. I.e. simplify to

```python
pn.extension("terminal", "notifications", design="bootstrap")
```

**Comment by philippjfr** [comment]
Seems like a simple thing and I think either should be supported.
