### ISSUE TITLE
Unstable webpage in documentation due to table

### ISSUE THREAD

**Issue by hyamanieu** [holoviz/panel#4857]
#### ALL software version info
Firefox
Windows

#### Description of expected behavior and the observed behavior

Browsing https://panel.holoviz.org/user_guide/Performance_and_Debugging.html#concurrent-processing with Firefox makes the scrolling bar unstable, it's impossible to read it. It's jumping due to the table changing its size near the top (see screencast).

The same page with Microsoft Edge doesn't have this problem.

#### Complete, minimal, self-contained example code that reproduces the issue

Unrelevant

#### Screenshots or screencasts of the bug in action

This is happening in a loop, no matter where we've scrolled down to below the table.

https://github.com/holoviz/panel/assets/15906523/0ccafd9e-55a1-4f99-b4c1-d2fca8c03156

**Comment by philippjfr** [comment]
This page no longer exists in Panel 1.0 dev documentation https://pyviz-dev.github.io/panel/
