### ISSUE TITLE
Not able to integrate Panel App with Django 4.3 and channels 3.0.5

### ISSUE THREAD

**Issue by piyali88** [holoviz/panel#4876]
I'm trying to integrate Panel App with Django.
Django version is 4.2 and channels version is 3.0.5

I have followed the instructions as mentioned here:
https://panel.holoviz.org/how_to/integrations/Django.html

but I'm not sure about the bokeh_django library, 
can anyone please guide me how to install the bokeh_django library?

**Comment by philippjfr** [comment]
@sdc50 Is the maintainer of bokeh_django. If I'm not wrong it isn't quite ready but will be very soon.

**Comment by sdc50** [comment]
> @sdc50 is the bokeh_django library available for integration?

I'm working on some basic documentation and still need to test it with Bokeh 3.

There is a preliminary package available at:

`conda install -c erdc/label/dev bokeh-django`

https://anaconda.org/erdc/bokeh-django
