### ISSUE TITLE
Tooltip issues

### ISSUE THREAD

**Issue by jbednar** [holoviz/panel#4887]
The new tooltips on widgets in Panel 1.0 are great! However, the UX isn't quite right, because hovering over the (?) takes so long that I reflexively click on the (?), which then stops the hover text from appearing. I think the delay should be maybe half what it is, and clicking on it should make the tooltip first appear, then (if clicked again) disappear, rather than suppress it silently without ever having shown it. That's probably a Bokeh issue rather than Panel, but maybe Panel sets the defaults.

Also, I think Panel or Param should strip out leading spaces that appear either on all lines of the doc or on all but the first line, so that docstrings can be formatted naturally in the code but also display naturally in the UI:

<img width="691" alt="image" src="https://github.com/holoviz/panel/assets/1695496/1c557c03-e9d1-449b-960a-83b64febd58d">

**Comment by philippjfr** [comment]
Most of this is a request for Bokeh. I certainly agree that the timeout is too long and clicking shouldn't have any effect.

**Comment by mattpap** [comment]
> I certainly agree that the timeout is too long and clicking shouldn't have any effect.

Note that plain text (string) description uses HTML's `title` attribute, so we don't have any control over how this behaves. If you want full control, then those descriptions have to be wrapped in an explicit `Tooltip(content=...)`. Thus in bokeh:
```py
input_widget.description = "string"
```
and
```py
input_widget.description = Tooltip(content="string")
```
are not equivalent.

**Comment by philippjfr** [comment]
Maybe I don't know how to use it correctly, but this doesn't work for me at all:

```
input_widget.description = Tooltip(content="string")
```

No tooltip is ever shown.

**Comment by philippjfr** [comment]
Nevermind, had to provide a position. I'll probably switch to explicit tooltips immediately.

**Comment by philippjfr** [comment]
Was able to resolve that by setting `syncable=False` on the `Tooltip` model but still seems like an issue.

**Comment by mattpap** [comment]
> Was able to resolve that by setting `syncable=False` on the Tooltip model but still seems like an issue.

Setting `syncable=False` in such cases is a generally good idea. The serialization error is a bug and I thought I already fixed it. Or maybe it was reported somewhere and got forgotten.

**Comment by mattpap** [comment]
> Nevermind, had to provide a position. I'll probably switch to explicit tooltips immediately.

The API of tooltips is not well refined. Setting `position` is one of those issue, which I trip over every time I use `Tooltip`.

**Comment by kcpevey** [comment]
I have a complicated app with one `pn.widgets.TooltipIcon`. I was having an issue with the app where it would throw  

>Error: [object HTMLDivElement] is not serializable 

and then the app would become inoperable (as if the front end was no longer connected to the backend, buttons no longer triggered callbacks, etc). 

After seeing the discussion above, I removed the instance of `TooltipIcon` and it seemed to fix the issue - the error is no longer thrown. I'm wondering if the same fix above needs to be applied to this widget too?

Panel v1.4.5
