### ISSUE TITLE
Card layout broken when updating objects

### ISSUE THREAD

**Issue by Lnk2past** [holoviz/panel#4897]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

* `panel==1.0.1`
* `bokeh==3.1.1`
* `holoviews==1.16.0`
* `param==1.13.0`
* `python==3.10.10`

#### Description of expected behavior and the observed behavior

I have layouts with HoloViews panes that I update with different `DynamicMaps` depending on other selections within the dashboard. These layouts are typically `Card` layouts to allow collapsing to remove clutter.

With the newest `panel` release whenever I update the object managed by the HoloViews pane the entire layout seems to break and then displays nothing.

#### Complete, minimal, self-contained example code that reproduces the issue

Example places a `Column` and `Card` within a single layout, showing the same `HoloViews`. When that pane's object is changed both layouts should change. Not only does the `Card` break, but it prevents the `Column` from updating as well.

```python
# test.py
import random
import holoviews as hv
import panel as pn

hv.extension('bokeh')
pn.extension()

limits = (0, 10)

def new_points():
    return [
        (random.randint(*limits),random.randint(*limits)),
        (random.randint(*limits),random.randint(*limits)),
    ]

hv_pane = pn.pane.HoloViews(
    hv.Points(new_points()).opts(xlim=limits, ylim=limits)
)

btn = pn.widgets.Button(name='Update')
def update(event):
    hv_pane.object = hv.Points(new_points()).opts(xlim=limits, ylim=limits)
btn.on_click(update)

column = pn.Column(
    hv_pane
)

card = pn.Card(
    hv_pane
)

pn.Column(
    btn,
    column,
    card  # remove this and the column will update as expected
).servable()
```

```shell
panel serve test.py
```

Oddly enough, the error only happens if the card is actually rendered - if you remove the card from the served `Column` the plot will updated as expected. As (unexpectedly) expected, if you only render the `Card` the plot still fails to update and the card breaks.

---

<details>
<summary>Probably Unrelated</summary>
<li> The pane is also not visually located within the card.
<li> Clicking the button in this example too quickly will result in errors like:

```text
bokeh.core.serialization.DeserializationError: can't resolve reference 'p2609'
```
</details>

---

#### Stack traceback and/or browser JavaScript console output

No errors are reported in the terminal running the dashboard, no errors reported in the browser console.

#### Screenshots or screencasts of the bug in action

N/A (Cannot provide this from my current location)

**Comment by philippjfr** [comment]
Got a fix in #4899 so should have a release with this fix later tonight.

**Comment by Lnk2past** [comment]
Awesome, thank you so much for the incredibly quick turn-around! I'll test on my end as soon as a release is available.

**Comment by Lnk2past** [comment]
Sorry for the late follow up, weekend hit and my brain shut off :)

Looks fixed on my end! Thanks!

**Comment by philippjfr** [comment]
Thanks for reporting back @Lnk2past!
