### ISSUE TITLE
Pyodide Example failed

### ISSUE THREAD

**Issue by hengaini2055** [holoviz/panel#4907]
#### ALL software version info
OS: windows 10 
Python: virtualenv 3.9.11
Panel: 1.0.0Rc7
bokeh ：3.1.1
tornado ： 6.3.1

#### Description of expected behavior and the observed behavior
I follow panel doc: [how_to/wasm/convert.html](https://pyviz-dev.github.io/panel/how_to/wasm/convert.html). App cannot run successful. The script.html and script.js are placed under the http file server using [HFS](https://www.rejetto.com/hfs/?f=dl). The url is [http://192.168.56.1/script.html](http://192.168.56.1/script.html). The error from Chrome console as follows:
```
{"notify":"init_tab"}
bokeh-3.1.1.min.js:183 [bokeh] setting log level to: 'info'
bokeh-3.1.1.min.js:165 [bokeh] document idle at 69 ms
script.js:12 Loading pyodide!
script.js:16 Loaded!
pyodide.asm.js:9 Loading micropip, packaging, pyparsing
pyodide.asm.js:9 Loaded pyparsing, packaging, micropip
pyodide.asm.js:9 Loading pandas, numpy, python-dateutil, six, pytz, jinja2, markupsafe, pyyaml, pillow
pyodide.asm.js:9 Loaded six, python-dateutil, pytz, markupsafe, jinja2, pyyaml, pillow, numpy, pandas
pyodide.asm.js:9 packaging already loaded from default channel
pyodide.asm.js:9 six already loaded from default channel
pyodide.asm.js:9 pyparsing already loaded from default channel
pyodide.asm.js:9 Loading typing-extensions, tqdm, bleach, webencodings, setuptools, distutils, idna, certifi
pyodide.asm.js:9 Loaded typing-extensions, tqdm, webencodings, bleach, distutils, idna, certifi, setuptools
pyodide.asm.js:9 numpy already loaded from default channel
pyodide.asm.js:9 distutils already loaded from default channel
pyodide.asm.js:9 Loading scikit-learn, scipy, clapack, joblib, threadpoolctl
pyodide.asm.js:9 Loaded threadpoolctl, joblib, clapack, scipy, scikit-learn
pyodide.asm.js:9 numpy already loaded from default channel
pyodide.asm.js:9 scipy already loaded from default channel
pyodide.asm.js:9 setuptools already loaded from default channel
pyodide.asm.js:9 Loading xgboost
pyodide.asm.js:9 Loaded xgboost
script.js:40 Packages loaded!
bokeh-3.1.1.min.js:165 [bokeh] document idle at 44 ms
bokeh-3.1.1.min.js:211 Uncaught (in promise) Error: reference 6619baf6-c892-408a-b7c6-b75151b5e043 isn't known
    at p.error (bokeh-3.1.1.min.js:211:4951)
    at p._decode_ref (bokeh-3.1.1.min.js:211:4572)
    at p._decode (bokeh-3.1.1.min.js:211:1046)
    at p._decode_plain_object (bokeh-3.1.1.min.js:211:2340)
    at p._decode (bokeh-3.1.1.min.js:211:1066)
    at bokeh-3.1.1.min.js:211:2249
    at f (bokeh-3.1.1.min.js:178:450)
    at p._decode_plain_array (bokeh-3.1.1.min.js:211:2237)
    at p._decode (bokeh-3.1.1.min.js:211:928)
    at bokeh-3.1.1.min.js:211:614
```
#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/panel/assets/20587475/096da8c4-3aed-40b6-8cea-e20fa80e49d6)

**Comment by philippjfr** [comment]
It's a really inconsequential error, seems like one of the stylesheet models is not deserialized correctly.

**Comment by hengaini2055** [comment]
From [convert-format](https://pyviz-dev.github.io/panel/how_to/wasm/convert.html#formats), three formarts have the same error:

**Comment by hengaini2055** [comment]
panel convert script.py --to pyodide-worker --out pyscript

**Comment by philippjfr** [comment]
Right, I can reproduce. That said the error has no actual effect and the example still works as normal.

**Comment by hengaini2055** [comment]
This is not very accurate. Refresh the page for the first time, drag the number, and the percentage will follow; when you look back, the percentage will no longer change.
![image](https://github.com/holoviz/panel/assets/20587475/beb95273-e3ae-416b-9a24-88b41db47c1a)
![image](https://github.com/holoviz/panel/assets/20587475/f84c8a7e-fd6c-46eb-b255-2a8559b0da31)

**Comment by philippjfr** [comment]
Ah, that's the second error you're seeing which was fixed in https://github.com/holoviz/panel/pull/4913

**Comment by philippjfr** [comment]
Deserialization errors should be ignored starting in Bokeh 1.2 so I'll mark this as resolved.
