### ISSUE TITLE
Datatable example not working

### ISSUE THREAD

**Issue by henriqueribeiro** [holoviz/panel#492]
The Datatable example (https://panel.pyviz.org/gallery/external/DataTable.html#gallery-datatable) isn't working. The output is a normal pandas dataframe. Do you have any idea why?
Thanks

**Comment by philippjfr** [comment]
Suspect the JS isn't loaded in time, will have to take a look.

**Comment by henriqueribeiro** [comment]
Thank you @philippjfr

**Comment by philippjfr** [comment]
Fixed https://pyviz-dev.github.io/panel/gallery/external/DataTable.html
