### ISSUE TITLE
Call to registered_names causes JavaScript exception

### ISSUE THREAD

**Issue by alexmilowski** [holoviz/panel#4940]
#### ALL software version info
bokeh==3.1.1
ipywidgets-bokeh==1.4.0
panel==1.0.2

#### Description of expected behavior and the observed behavior

We're getting a lot of JavaScript exceptions in Jupyterhub when we use things like the Tabulator. They look like:

```
[Error] TypeError: Bokeh.Models.registered_names is not a function. (In 'Bokeh.Models.registered_names()', 'Bokeh.Models.registered_names' is undefined)
	is_loaded (Script Element 3:38:165)
	(anonymous function) (Script Element 3:45)
```

#### Complete, minimal, self-contained example code that reproduces the issue

Essentially, any use of ipywidgets / tabulator

#### Stack traceback and/or browser JavaScript console output

```
[Error] TypeError: Bokeh.Models.registered_names is not a function. (In 'Bokeh.Models.registered_names()', 'Bokeh.Models.registered_names' is undefined)
	is_loaded (Script Element 3:38:165)
	(anonymous function) (Script Element 3:45)
```

I have narrowed the issue to the doc_nb_js.js file that seems to be out of date with the latest Bokeh in use.  Here is a PR for a proposed fix (which may or may not accomplish the same intent):

https://github.com/holoviz/panel/pull/4939

**Comment by philippjfr** [comment]
This check should only ever occur if `ipywidgets_bokeh` is imported and when working in a notebook that should generally not be the case. Are you explicitly importing it for some reason?

**Comment by philippjfr** [comment]
Thanks for your PR!
