### ISSUE TITLE
Make it possible to override enabled_dates by setting disabled_dates in DatePicker

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#4949]
#### Is your feature request related to a problem? Please describe.
Suppose you have set a list of valid dates with enabled_dates and want to make all dates available again. Reading the docs you could imagine that setting disabled_dates to an empty list would do the trick but in fact it cannot override enabled_dates (the reverse works). However in 0.14.4, updating enabled_dates to an empty list did that.

The behaviour has changed with 1.0 and an empty enabled_dates makes all dates unavailable. This is more intuitive but now to my knowledge there is no way to reinitialise the available dates. I've also tried setting enabled_dates to None which yields an error in javascript. See the following code:

```python
import panel as pn
pn.extension()


def update(event):
    if event.obj == button1:
        picker.enabled_dates = [] # Used to work in 0.14.4
    elif event.obj == button2:
        picker.enabled_dates = None # Error in browser console
    elif event.obj == button3:
        picker.disabled_dates = []
    elif event.obj == button4:
        picker.disabled_dates = None


picker = pn.widgets.DatePicker(enabled_dates=['2023-05-26'])
button1 = pn.widgets.Button(name='enabled_dates=[]')
button2 = pn.widgets.Button(name='enabled_dates=None')
button3 = pn.widgets.Button(name='disabled_dates=[]')
button4 = pn.widgets.Button(name='disabled_dates=None')

button1.on_click(update)
button2.on_click(update)
button3.on_click(update)
button3.on_click(update)

pn.Column(picker, pn.Row(button1, button2, button3, button4)).servable()
```

#### Describe the solution you'd like
From a user perspective it would be nice to make both parameters able to override the other?

#### Describe alternatives you've considered
It may be possible, albeit not ideal, to reinstate the original behaviour.

**Comment by TheoMathurin** [comment]
I filed an issue upstream because the Bokeh model is used directly for `DatePicker`, so I believe nothing can be done in Panel to fix this.

https://github.com/bokeh/bokeh/issues/13192

However `DatetimePicker` which is added by Panel shows the same behavior.

**Comment by Hoxbro** [comment]
`DatetimePicker` in Panel is basically a copy of an old Bokeh version of `DatePicker`. We will switch to Bokeh's version when Point 2 of https://github.com/bokeh/bokeh/issues/12904 is fixed.
