### ISSUE TITLE
Panel plotting two of the same plots

### ISSUE THREAD

**Issue by Philliec459** [holoviz/panel#4952]
I have been using Ipywidgets in Jupyter Notebook that works perfectly, but am switching to panel to use the code in another python scripting package where I need to use Panel. I am not sure what I am doing wrong.

The following is the simple code for this example where cbw_int_plot is a matplotlib plot shown below:

CBW_Int_slider  = pn.widgets.FloatSlider(name='CBW_Intercept',start=0,end=0.5,step=0.01,value=0.25)

pn.interact(cbw_int_plot, CBW_Int = CBW_Int_slider)

<img width="173" alt="panel_dual_plots" src="https://github.com/holoviz/panel/assets/56929340/433931f5-fcad-46ed-8ffe-324ae0f204e8">

Do you have any suggestions?

This is the plot definition. 

def cbw_int_plot(CBW_Int):
    fig=plt.figure(figsize=(5,4))
    plt.title('Vsh vs.CBWa', color = 'blue')
    plt.plot(logs.vsh,logs.CBWa,'r.', label='',color='red')
    plt.plot(logs.vsh,logs.vsh*CBW_Int,'k-', label='',color='black')
    plt.xlim(0.0,1.0)
    plt.ylim(0.0,1.0)
    plt.ylabel('CBWa [v/v]', color = 'blue')
    plt.xlabel('Vsh [v/v]', color = 'blue')
    
    return fig

**Comment by jbednar** [comment]
I think the FAQ addresses this:

<img width="1037" alt="image" src="https://github.com/holoviz/panel/assets/1695496/30ba5f47-4fc7-4bea-99df-6c906ef01176">

**Comment by Philliec459** [comment]
So I tried you suggestion and I now have a single plot, but I want an interactive figure too. I tried to add the widget using the following code, but that did not work. Is there any way to add the widget to this:


from matplotlib.figure import Figure


fig=plt.Figure(figsize=(5,4))
plt.title('Vsh vs.CBWa', color = 'blue')
plt.plot(logs.vsh,logs.CBWa,'r.', label='',color='red')
plt.plot(logs.vsh,logs.vsh*CBW_Int,'k-', label='',color='black')
plt.xlim(0.0,1)
plt.ylim(0.0,1.0)
plt.ylabel('CBWa [v/v]', color = 'blue')
plt.xlabel('Vsh [v/v]', color = 'blue')
plt.grid()


CBW_Int_slider  = pn.widgets.FloatSlider(name='CBW_Intercept',start=0,end=0.5,step=0.01,value=0.25)

test = pn.pane.Matplotlib(fig)
pn.interact(test, CBW_Int = CBW_Int_slider)

_TypeError: unsupported callable_


I then tried:

def cbw_int_plot(CBW_Int):
    fig=plt.Figure(figsize=(5,4))
    plt.title('Vsh vs.CBWa', color = 'blue')
    plt.plot(logs.vsh,logs.CBWa,'r.', label='',color='red')
    plt.plot(logs.vsh,logs.vsh*CBW_Int,'k-', label='',color='black')
    plt.xlim(0.0,1)
    plt.ylim(0.0,1.0)
    plt.ylabel('CBWa [v/v]', color = 'blue')
    plt.xlabel('Vsh [v/v]', color = 'blue')
    plt.grid()
    pn.pane.Matplotlib(fig)    

CBW_Int_slider  = pn.widgets.FloatSlider(name='CBW_Intercept',start=0,end=0.5,step=0.01,value=0.25)
pn.interact(cbw_int_plot, CBW_Int = CBW_Int_slider)


This looks great with 1 plot, but that plot does now interact with the slide bar.I guess for my Jupyter Notebook I am best staying with ipywidgets and in my other application, that is not a notebook, then use panel. I just like to use the Notebook as a documented help type file for the primary application, and I would love to use the same code on both.

**Comment by Philliec459** [comment]
There is another way to run this interactive plot by using panel server, but then it spews out a long series of my interactive plots at the end after saving the value of the widget. Is there any way to suppress these extra plots created while saving the value (CBW_Int = CBW_Int_slider.value) from the slider?

CBW_Int_slider  = pn.widgets.FloatSlider(name='CBW_Intercept',start=0,end=0.5,step=0.01,value=0.25)
pane = pn.interact(cbw_int_plot, CBW_Int = CBW_Int_slider)

# Button to stop the server    
def button_callback():
    #sys.exit()  # Stop the server
    print('Panel Stop')
    bokeh_server.stop()

button = Button(label="Stop", button_type="success")
button.on_click(button_callback)

def app():

    return pn.Row(pn.Column( button, pane[0], width=350, sizing_mode="fixed"), pn.layout.VSpacer(width=10),pane[1])

pn.serve({"localhost:": app}, port=5006)

**Comment by Hoxbro** [comment]
To get it to work, do something like this:
``` python
import matplotlib.pyplot as plt
import numpy as np
import panel as pn
from matplotlib.figure import Figure

pn.extension()


def cbw_int_plot(CBW_Int):
    fig = plt.Figure(figsize=(5, 4))
    ax = fig.subplots()

    ax.set_title("Vsh vs.CBWa", color="blue")
    ax.plot(np.arange(10), np.arange(10) * CBW_Int, "k-", label="")
    ax.set_xlim(0.0, 1)
    ax.set_ylim(0.0, 1.0)
    ax.set_ylabel("CBWa [v/v]", color="blue")
    ax.set_xlabel("Vsh [v/v]", color="blue")
    ax.grid(True)
    return fig


CBW_Int_slider = pn.widgets.FloatSlider(
    name="CBW_Intercept", start=0, end=0.5, step=0.01, value=0.25
)

mpl_plot = pn.pane.Matplotlib(pn.bind(cbw_int_plot, CBW_Int_slider))

pn.Column(CBW_Int_slider, mpl_plot)
```

https://github.com/holoviz/panel/assets/19758978/d20a7108-57fd-4f9a-af98-e8016557c303


I will close this issue as it is more of a usage question, and it would be better to ask on [Discourse](https://discourse.holoviz.org/).
