### ISSUE TITLE
Wrap Leaflet.js card appears twice

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4956]
If I go to https://panel.holoviz.org/how_to/custom_components/index.html I see

![image](https://github.com/holoviz/panel/assets/42288570/bb904120-fe8f-4c6b-87e0-92a5538b1eb1)

The second is about Material UI

**Comment by Hoxbro** [comment]
This is already fixed in https://github.com/holoviz/panel/pull/4943
