### ISSUE TITLE
TextEditor does not show headings

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#4962]
I think it gets transformed to <p>

```
import panel as pn

pn.extension("texteditor")

pn.widgets.TextEditor(
    value="<h1>A title</h1>",
).servable()
```

<img width="379" alt="image" src="https://github.com/holoviz/panel/assets/15331990/8138f18c-762f-433a-bc33-41401caa774c">
<img width="99" alt="image" src="https://github.com/holoviz/panel/assets/15331990/5ec43051-0b14-49dd-ba8f-109d5a07a12f">

**Comment by maximlt** [comment]
This is fixed on the main branch.
