### ISSUE TITLE
Rendering performance drop regarding dynamic layout control in template

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#4976]
#### ALL software version info
Panel 1.0.3
Bokeh 3.1.1
Ubuntun 22.04 and Fedora 38
Latest Firefox/Chromium

#### Description of expected behavior and the observed behavior
I have a large, complex app that I am very happy to update to Panel 1.0 and Bokeh 3.

After launching it with the necessary adaptations, I noticed significant delays in the main callback (+5 seconds compared to 0.14.4) which loads a map and adapts the widgets on screen. Upon inspection I figured it was linked to events like `layout.append(widget)`.

Edit: this only happens in a template

#### Complete, minimal, self-contained example code that reproduces the issue

You can compare the performance using the following code on Panel 1.0.3 v Panel 0.14.4. As you add more widgets, you will notice the additional time it takes to render is quite noticeable.

With 100 widgets on screen on my laptop, rendering takes ~3s on Panel 1.0.3 and ~0.5 on Panel 0.14.4. It is not as dramatic as what I observe in my app but the app layout is more complex, although I'm far from having 100 components on screen.

```python
import panel as pn
pn.extension()


def callback(_):
    column.append(pn.widgets.MultiChoice(options=list('ABCDE')))
    nwidgets.object = str(len(column))
    print(nwidgets.object)


column = pn.Column()
button = pn.widgets.Button(name='Click')
nwidgets = pn.pane.Markdown('0')
content = [button, nwidgets, column]
button.on_click(callback)

template = pn.template.VanillaTemplate(main=content)
template.servable()
```

**Comment by philippjfr** [comment]
Thanks for reporting, we'll investigate asap and expedite a fix.

**Comment by philippjfr** [comment]
Cannot reproduce any issue here, when I try, even with a 1000 widgets, the render time is roughly 0.5 seconds.

**Comment by Hoxbro** [comment]
I can't recreate it either (even with the added button). Do you have any special environment variables set?

**Comment by TheoMathurin** [comment]
I reverted the example code to the original version I posted: it turns out the issue only happens in a template. Just tried on a clean 1.0.3 install.

**Comment by Hoxbro** [comment]
Yep. That seems to have done the trick.

**Comment by philippjfr** [comment]
Suspect the theme/designs must be triggering some recursive recomputation.
