### ISSUE TITLE
`pn.pane.Plotly` selection not working unless `jslink=True`

### ISSUE THREAD

**Issue by ambrustorok** [holoviz/panel#4977]
Edit: Cross out the version I updated from, as it might have been broken before too, but went unnoticed.

Hi,

I have recently updated to version 1.0.2 ~~from 0.14.4~~ (python 3.10), and came across the following issue.

Consider the following code:

```python
import panel as pn
import pandas as pd
import plotly.express as px

pn.extension("plotly")

data = pd.DataFrame([
    ('Monday', 7), ('Tuesday', 4), ('Wednesday', 9), ('Thursday', 4),
    ('Friday', 4), ('Saturday', 4), ('Sunay', 4)], columns=['Day', 'Orders']
)

fig = px.line(data, x="Day", y="Orders")
fig.update_traces(mode="lines+markers", marker=dict(size=10), line=dict(width=4))
fig.layout.autosize = True

responsive = pn.pane.Plotly(fig)

pn.Column('# A responsive plot', responsive, sizing_mode='stretch_width')
```
Now, if you run this in jupyter, then select some of the points using the Box Select (or the Lasso Select) tool, then you will get a JavaScript console error in doing so.

![image](https://github.com/holoviz/panel/assets/31830274/9734be86-da0c-409e-a49e-857d746f8722)

The error: 

```js
3.min.js:195  Uncaught Error: [object Undefined] is not serializable
    at f.to_serializable (VM200 bokeh-2.4.3.min.js:195:1391)
    at f.to_serializable (VM200 bokeh-2.4.3.min.js:195:1278)
    at f.to_serializable (VM200 bokeh-2.4.3.min.js:195:1169)
    at f.to_serializable (VM200 bokeh-2.4.3.min.js:195:1278)
    at [serialize] (VM200 bokeh-2.4.3.min.js:200:815)
    at f.to_serializable (VM200 bokeh-2.4.3.min.js:195:1042)
    at f.to_serializable (VM200 bokeh-2.4.3.min.js:195:1169)
    at E.create_json_patch (VM200 bokeh-2.4.3.min.js:165:9363)
    at d.process_events (VM206 panel.min.js:50:1694)
    at VM206 panel.min.js:50:1487
to_serializable @ VM200 bokeh-2
```

If you try to access the selected points, you will get a `None`:
```python
responsive.selected_data
```

However, if you run the following code (or replace the last line of the previous code block with this), you will get a working selection.

```python
pn.Row(responsive.controls(jslink=True), responsive)
```

You get no errors in the console and `responsive.selected_data` will have your data too.

I have tried this on my organizational jupyterhub, as well as Google Colab, they proved to behave identically.

**Comment by philippjfr** [comment]
Thanks for reporting! Pretty critical bug, we'll turn around a fix asap.
