### ISSUE TITLE
Tabulator pandas styling no longer working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4994]
I'm on Panel 1.0.3. I was trying to use the pandas styling with Tabulator. But I get no styling.

You can also see its the case in the documentation at https://panel.holoviz.org/reference/widgets/Tabulator.html#styling

![image](https://github.com/holoviz/panel/assets/42288570/c908e666-c7ea-4fbe-b870-2f5cf0cc1a55)

**Comment by philippjfr** [comment]
Looks like this is merely broken in docs as in notebooks and when running in an app the styling applies okay:

<img width="438" alt="Screen Shot 2023-05-31 at 16 05 39" src="https://github.com/holoviz/panel/assets/1550771/00e940b8-1290-4c79-9107-c344c986bdee">

**Comment by Hoxbro** [comment]
For me, the docs example look fine:
![image](https://github.com/holoviz/panel/assets/19758978/66c265b8-8152-49f3-a065-4c748d586967)

**Comment by philippjfr** [comment]
Seems flakey as I observed the same issue, suspect it's a race condition based on when the CSS stylesheet loads.

**Comment by SKlerk** [comment]
For what it's worth, I just encountered this issue as well when serving my app. The style always applies properly when first opening the app in a new window or tab. After that, both reloading the tabulator from within the app or refreshing the browser fails to apply the styles.

**Comment by philippjfr** [comment]
Haven't been able to reproduce this since adding some extra handling for making this more robust. Will close but if we encounter this again let's reopen.
