### ISSUE TITLE
Markdown no longer handling indented text

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4996]
One of the things that was implemented early on with inspiration from a completing framework was indented markdown strings.

It seems to be lost with Panel 1.0. This just makes it hard for new users to understand what goes on and for experienced users to use the code formatting they are used to.

## Example - Indented - Not working as expected

```bash
import panel as pn

pn.extension()

def my_func():
    return pn.pane.Markdown(
        """## Header

    some text
    """
    )

pn.Column(my_func).servable()
```

You can see the indented markdown is rendered as code with a bluish color.

![image](https://github.com/holoviz/panel/assets/42288570/e45581d6-c1d4-4398-9278-c480af66504f)

## Example - Not indented - works as expected

```bash
import panel as pn

pn.extension()

def my_func():
    return pn.pane.Markdown(
        """## Header

some text
"""
    )

pn.Column(my_func).servable()
```

![image](https://github.com/holoviz/panel/assets/42288570/99203b94-2727-40bd-93ed-b96601ee382c)

**Comment by philippjfr** [comment]
This is definitely not a regression as the behavior is identical in 0.14.4 (except that code now has a default color) and I also would not consider it a bug.

**Comment by philippjfr** [comment]
I'm going to close, streamlit has exactly the same behavior.
