### ISSUE TITLE
BokehUserWarning: reference already known 'ced6deab-9713-4f3b-baa3-e06949e4e15b'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5010]
I'm on Panel 1.0.4 and trying to help VoRodin in https://discourse.holoviz.org/t/problems-with-tabulator-widget-in-vs-code-jupyter-notebook/5454.

I'm running his example code in VS Code on my windows laptop. Every time I select a row in the table I get a new `BokehUserWarning: reference already known 'ced6deab-9713-4f3b-baa3-e06949e4e15b'` in the output cell.

![image](https://github.com/holoviz/panel/assets/42288570/32d4c55d-daea-43ff-92ab-ac5cd1f87471)

```python
import datetime as dt
import numpy as np
import pandas as pd
import panel as pn

pn.extension('tabulator')

sel_df = pd.DataFrame(np.random.randn(5, 5), columns=list('ABCDE'))
select_table = pn.widgets.Tabulator(sel_df)
select_table

pn.panel(select_table.param.selection)
```

bokeh==3.1.1 jupyter-bokeh=3.0.7

**Comment by Hoxbro** [comment]
Already fixed
