### ISSUE TITLE
The message "User authentication hooks NOT provided (default user enabled)" is confusing for new users

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5021]
In https://discourse.holoviz.org/t/cannot-execute-script-with-panel/5464 *NoBody* gets confused by the message `User authentication hooks NOT provided (default user enabled)` that is shown with `panel serve`. He thinks this is causing him not to be authenticated to read files on his server.

As authentication is not normally something new users think about I would propose 

- Not showing this message when the server is launched without authentication hooks
- Showing the message `User authentication hooks provided` when the server is started with authentication hooks.

This is a small step to reducing the complexity of Panel for new users.

**Comment by philippjfr** [comment]
I do agree that this message is confusing and I don't think it should be there and I also realize it's annoying to ask you to open this issue somewhere else but please file this upstream with Bokeh as we have no direct control over this without duplicating a ton of code.

**Comment by MarcSkovMadsen** [comment]
Done in https://github.com/bokeh/bokeh/issues/13177
