### ISSUE TITLE
markdown-it-py version issue on Pyscript.com

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5022]
It seems that pyscript.com uses and requires `markdown-it==3.0.0`. But Panel requires `markdown-it<3`.

![image](https://github.com/holoviz/panel/assets/42288570/aad18aeb-a831-45e5-90dc-65cf8d53f533)

## Steps

- Create a Panel app like https://pyscript.com/view/be229e67-7265-4455-8f39-aebc46a74565/c8596ae2-60fa-4050-88ce-c0d3f6fb4747/latest/
- open the link to the app

![image](https://github.com/holoviz/panel/assets/42288570/96145d08-1b4f-4ddc-940f-8e2ab567cd96)

- See the issue

**Comment by MarcSkovMadsen** [comment]
## Workaround

Seems you can workaround the issue by specifying the version in the `.toml` file.

![image](https://github.com/holoviz/panel/assets/42288570/d3ba9c8c-ce8e-4d7f-a446-54b2aa832158)

**Comment by leriomaggio** [comment]
Ah thanks @MarcSkovMadsen - I was about to report this as well! You've been faster than I was 🙌 

This was indeed my fix on the `Simple Panel App` ([link](https://pyscript.com/view/37c8e61f-8cf6-4517-9652-2483b9db9016/5724cd5e-0ad8-44f5-a458-2e0f4eeb8140/latest/)) that is now **Featured** on PyScript.com :)

**Comment by MarcSkovMadsen** [comment]
You can find my Panel Starter App [here](https://be229e67-7265-4455-8f39-aebc46a74565.pyscriptapps.com/c8596ae2-60fa-4050-88ce-c0d3f6fb4747/latest/). Maybe we could share ideas?

One issue with pyscript is that there is a long period of time 6-10 seconds where Panel is loading and pyscript has removed its loading indicator. Its a bad UX. So I've added one in the "template" that I remove once python is executing.

**Comment by philippjfr** [comment]
The part I'm not fully following here is what introduces the `<3` pin, Panel itself does not pin it at all.

**Comment by philippjfr** [comment]
Seems like it's probably https://github.com/executablebooks/mdit-py-plugins that required <3 but they're going to get a patch release out in the next few hours. If not please chase them.

**Comment by MarcSkovMadsen** [comment]
Just for info @leriomaggio . I've sent a mail to the pyscript support with a list of the things I need before I can really start using pyscript.com (to replace awesome-panel.org gallery).

See ticket [37019](https://support.anaconda.com/hc/requests/37019)

**Comment by leriomaggio** [comment]
Thanks a lot @MarcSkovMadsen  - I can definitely tell you that some of the features you're asking for are on the TODO list already and will be featured in the upcoming releases of PyScript.com :) 

Great to be on the same page! :)

**Comment by leriomaggio** [comment]
Also (RE Template): That can be easily done already. 

You create your *Template* project in your dashboard that you can copy and duplicate every time you need to start from scratch with the same things (e.g. panel apps)

Surely that is **not** an actual template: there is a lack of "Skeleton Template APP" in PyScript.com right now.
However, this is what I normally do to speed up App creation and it simply works :)

**Comment by leriomaggio** [comment]
> You can find my Panel Starter App [here](https://be229e67-7265-4455-8f39-aebc46a74565.pyscriptapps.com/c8596ae2-60fa-4050-88ce-c0d3f6fb4747/latest/) @leriomaggio . Maybe we could share ideas?

Here is an alternative idea leveraging the default [`py-splashscreen`](https://docs.pyscript.net/latest/reference/plugins/py-splashscreen.html) PyScript plug-in: [app](https://37c8e61f-8cf6-4517-9652-2483b9db9016.pyscriptapps.com/516c1815-c307-420d-bca4-f7fa2eef4594/latest/)

WDYT?

**Comment by MarcSkovMadsen** [comment]
Thanks. The `py-splashscreen` can help improve the situation. But there is still some +2 secs where the screen is just blank and the app is loading.

See video below and issue https://github.com/pyscript/pyscript/discussions/1501

https://github.com/holoviz/panel/assets/42288570/365c6c05-8558-4f96-8f54-173e224f46cb

**Comment by leriomaggio** [comment]
Yes, ok - that was more an experiment-in-the-making, than an actual solution.
 
If you want to do these things properly one should sync up on signals from events, or perhaps moving everything into a webworker to load the entire app would do the trick :)

**Comment by stonebig** [comment]
I have the same issue with Jupyterlite.
