### ISSUE TITLE
Not same origin on Pyscript.com: NotSameOriginAfterDefaultedToSameOriginByCoep

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5023]
When deploying apps on pyscript.com I get errors in the browser console.

![image](https://github.com/holoviz/panel/assets/42288570/17d42eb3-7f52-47e2-99aa-45059dbd85d9)

```bash
rDefaultedToSameOriginByCoep
loading.css:1 
        Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
default.css:1 
        Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
listpanel.css:1 
        Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
bootstrap_default.css:1 
        Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
bootstrap.css:1 
        Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
bootstrap.min.css:1 
        Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
markdown.css:1 
        Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
```

## Reproduce

Open https://be229e67-7265-4455-8f39-aebc46a74565.pyscriptapps.com/c8596ae2-60fa-4050-88ce-c0d3f6fb4747/latest/

**Comment by leriomaggio** [comment]
Hey @MarcSkovMadsen I've noticed this as well while working on PyScript.com. 

IMHO this has nothing to do specifically with `panel` but more with PSDC using two different origins between _Preview_ and _View_ mode, so CORS is calculated differently. 

This will be unified soon, to avoid issues like that - we have an issue already internally to manage this! :)

**Comment by philippjfr** [comment]
Sounds like this is not a Panel issue, if it does turn out to be a problem with Panel or the CDN configuration please reopen.
