### ISSUE TITLE
Reactive helper

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5025]
This is a request for a reactive helper as discussed in https://twitter.com/PhilippJFR/status/1664805434081828866?s=20.

![image](https://github.com/holoviz/panel/assets/42288570/7590561e-c69d-4f49-9371-0619f5009a92)

If you don't want to use the Parameterized api you often get stuck if you need to keep state like `is_running` or `count` that is not natural to place in a widget. You then end up using a widget any ways. Or switch to the Parameterized api as in 

```python
class state(param.Parameterized):
    is_running = param.Boolean()
    counter = param.Integer()
```

An alternative to a reactive helper would be to be able to just use `is_running = param.Boolean()` and `counter=param.Integer()`. I've tried and it did not work.

**Comment by philippjfr** [comment]
The nicer approach here would indeed be if you could simply use an unbound parameter as the reactive variable.

**Comment by MarcSkovMadsen** [comment]
So either implement it in Param. Or make a `parameters` module in Panel with helpers. The `parameters` module can then be replace with `param` one day when it supports it.

**Comment by MarcSkovMadsen** [comment]
.rx has solved this. Closing.
