### ISSUE TITLE
X3D support

### ISSUE THREAD

**Issue by banesullivan** [holoviz/panel#503]
Could you all add support for X3D? It'd be great if the javascript from http://www.x3dom.org/download/x3dom.js was encompassed in a panel extension for displaying 3D scenes.

### Example

```py
from IPython.display import HTML

javascript = '''
<script type='text/javascript' src='http://www.x3dom.org/download/x3dom.js'> </script> 
<link rel='stylesheet' type='text/css' href='http://www.x3dom.org/download/x3dom.css'></link> 
<x3d width='400px' height='300px'>
    <scene>
        <shape>
            <appearance>
                <material diffuseColor='1 0 0'></material>
            </appearance>
            <box></box>
        </shape>
    </scene>
</x3d>  
'''

HTML(javascript) 
```

### Why

I just added an X3D exporter to PyVista and this would give use a more stable scene viewer than VTKjs until we can work out a lot of bugs with VTKjs. See https://github.com/pyvista/pyvista/pull/300

Relevant to #408 

### Notes

There's a way to make binary X3D scenes - it'd be best if we could figure out how to use the binary scenes over ASCII HTML.

**Comment by xavArtley** [comment]
It works now
![x3d](https://user-images.githubusercontent.com/18531147/97877589-af76fd00-1d1d-11eb-9507-ae9483a34343.gif)
