### ISSUE TITLE
Make swipe layout work with holoviews heatmaps as before after objects

### ISSUE THREAD

**Issue by GeoVizNow** [holoviz/panel#5039]
Thanks for providing great new functionality in panel 1.x!
I wanted to notify that, by some reason, I cannot make the new Swipe layout work with holoviews heatmaps. I would love to know how to best debug this. 

#### ALL software version info
panel: 1.0.2
pandas: 1.5.3
bokeh: 3.1.1
hvplot: 0.8.3
browser: Edge
os: windows 10 
env: jupyter

#### Description of expected behavior and the observed behavior
Expectation: possible to sweep between two different heatmaps. 
Observed: swipe layout given two heatmaps does not show anything. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import pandas as pd
import hvplot.pandas
pn.extension()

hm1 = pd.DataFrame({'a': [1, 2, 3], 'b': [2,2,2], 'c':[2,3,1]}).hvplot.heatmap()
hm2 = pd.DataFrame({'a': [1, 1, 1], 'b': [2,2,2], 'c':[2,3,2]}).hvplot.heatmap()

layout = pn.layout.Swipe(hm1[()], hm2[()])
layout
```

#### Stack traceback and/or browser JavaScript console output
No error output

#### Screenshots or screencasts of the bug in action
Not much to show, but hm1 and hm2 can be displayed as normal elements.

**Comment by philippjfr** [comment]
I believe @ianthomas23 had a fix for this in Bokeh so when we upgrade to Bokeh 3.2 this will get fixed. For now a workaround would be to disable webgl rendering in Bokeh:

```python
hv.renderer('bokeh').webgl = False
```

**Comment by GeoVizNow** [comment]
Thanks you very much for the suggestion @philippjfr. I can confirm that it works with the suggested workaround. But it is a bit slow it seems. Looking forward to bokeh 3.2 and a fix. 
For context I am trying to rasterize an array which has lots of y values and few categorical x values. I have pre-made the grid and tried using rasterize on an image for it. This works quite nicely with customized ticks, but I would have loved to be able to only rasterize in one dimension and thus not having to control x-range zoom or similar (see example in [discourse](https://discourse.holoviz.org/t/control-sampling-of-rasterized-image-to-avoid-blending-of-pixels-while-zooming/5440)). Do you think that it would be possible to tweak the re-grid or something to only re-grid in one dimension using rasterize on an image? It would be almost like rasterize heatmap, but the latter is much slower it seems.

**Comment by ahuang11** [comment]
It seems like Panel swipe doesn't work with tile sources either:
```python
import geoviews as gv
import panel as pn
gv.extension("bokeh")
gv.renderer("bokeh").webgl = False

pn.Swipe(
    gv.tile_sources.EsriImagery(),
    gv.tile_sources.OpenTopoMap(),
    height=500,
    width=500
).servable()
```

**Comment by philippjfr** [comment]
That doesn't look like a Swipe issue, more likely the ranges on those plots aren't set right, e.g. global_extents isn't working.

**Comment by ahuang11** [comment]
It works fine alone:
```python
import geoviews as gv
import panel as pn
gv.extension("bokeh")
gv.renderer("bokeh").webgl = False

pn.panel(gv.tile_sources.ESRI().opts(global_extent=True)).servable()
```
<img width="245" alt="image" src="https://github.com/holoviz/panel/assets/15331990/b9a6a90b-9b54-4b31-bdea-3ebb99bcf987">

**Comment by GeoVizNow** [comment]
As far as I can see my issue is working fine in panel 1.2.1.
Also the below works for holoviews tiles now (did not try with geoviews though):
```
import panel as pn
import holoviews as hv
hv.extension('bokeh')
pn.extension()

tiles1 = hv.element.tiles.EsriImagery()
tiles2 = hv.element.tiles.OpenTopoMap()

layout = pn.layout.Swipe(tiles1, tiles2)
layout
```
See animation below:
![2023-08-11_14-13-31](https://github.com/holoviz/panel/assets/31777090/dbb3aad6-9ad3-4a8d-be91-2e71a0c96bec)

**Comment by GeoVizNow** [comment]
I am closing this now as it seems supported and no longer a problem. Thanks for fixing it!
