### ISSUE TITLE
Generator stream not working as expected

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5043]
I'm on the main branch and have just fetched and pulled the latest version.

When I run 

```python
import panel as pn
from asyncio import sleep
pn.extension()

def stream():
    for i in range(0,100):
        sleep(0.25)
        yield i

pn.Column("The stream is below", stream).servable(
```

I would expect to see a streaming `i` value in my app. But I don't see it. Instead it looks like

![image](https://github.com/holoviz/panel/assets/42288570/0ea78d55-9f06-47fe-b069-6d56189a8546)

**Comment by Hoxbro** [comment]
Aren't you missing `async` in the def?

**Comment by MarcSkovMadsen** [comment]
Thanks

**Comment by Hoxbro** [comment]
And `await` before sleep

**Comment by MarcSkovMadsen** [comment]
Just saw that as well. Thanks.

**Comment by MarcSkovMadsen** [comment]
It works
