### ISSUE TITLE
some problems with columns formatted with icons in tabulator widgets

### ISSUE THREAD

**Issue by federalSoftware** [holoviz/panel#5049]
#### ALL software version info
Panel version 1.0.4 and 1.1.0
Windows 11
Microsoft Edge Version 114.0.1823.37 (Official build) (64-bit)
Google Chrome Version 114.0.5735.45 (Official Build) beta (64-bit)
Google Chrome Version 114.0.5735.91 (Official Build) (64-bit)

#### Description of expected behavior and the observed behavior

I list here the problems that I have encountered when I wanted to use icons in columns of the tabulator widgets.
Some problems I don't know if they are bugs

1) I want to add a print button, as shown in the official documentation (https://panel.holoviz.org/reference/widgets/Tabulator.html), as follows:
tabulator= pn.widgets.Tabulator(df, buttons={'Print': "<i class='fa fa-print'></i>"})
However, the printer icon is not displayed, as seen in the image attached below.
I don't know if I need to add something in pn.extension or install some other library where the printer icon is (the documentation does not say). It does not give an error, but the icon is not shown in the tabulator widgets.

2) I wanted to add an icon or image to a tabulator column, whose image file name is read according to the cell content. In my test case I am doing it for a column with the value F for Female and M for Male. I have two images in a directory data M.png and F.png
I did not find any reference in the panel documentation on how to do it, however I asked bing chatgpt and it gave me a solution to incorporate into the tabulator_formatters
  'genderImage': {'type': 'image', 'urlPrefix': './data/', 'urlSuffix': '.png'} # to display an icon based on the value of the genderImage column
This solution did not work in the tabulator widgets, as shown in the image attached below.

However, when putting an option to save the panel as html, with the save command, in the html the images or icons are displayed correctly, as shown in the image attached below.

3) the links to the Bokeh formatters (BooleanFormatter
DateFormatter
NumberFormatter
HTMLTemplateFormatter
StringFormatter
ScientificFormatter) that are in the documentation, in tabulator widgets section, lead to pages that do not exist.
This is a problem in the documentation and not in the library.

Thank you very much for the effort you are making to make this library so great.
```
# code goes here between backticks

import numpy as np
import panel as pn
import pandas as pd
from panel.theme import Bootstrap, Material, Native, Design,Fast
from bokeh.resources import INLINE

pn.extension('tabulator')

df = pd.DataFrame({
    'str': ['A', 'B', 'C','D','E','F','G','H','I','J'],
    'int': [ 5, 8,6,3,9,10,1,2,4,7],
    'gender': [ 'M','F','M','F','M','F','M','F','M','F'],
    'genderImage': [ 'M','F','M','F','M','F','M','F','M','F'],
    'float': [3.14, 6.28, 9.42,3.14, 6.28, 9.42,3.14, 6.28, 9.42,3.14],
    'bool': [True, False, True,True, False, True,True, False, True,True],
}, index=[1, 2, 3,4,5,6,7,8,9,10])

def create_components(design):
    tabulator_formatters = {
        'float': {'type': 'progress', 'max': 10},
        'bool': {'type': 'tickCross'},
        'genderImage': {'type': 'image', 'urlPrefix': './data/', 'urlSuffix': '.png'}} # to display an icon based on the value of the gender column
    tabulator = pn.widgets.Tabulator(df, sizing_mode='stretch_width',height=800, buttons={'Print': "<i class='fa fa-check'></i>"}, formatters=tabulator_formatters)
    tabulator.on_click(click) 

    return pn.Row(tabulator)

def click(event):
    print(f'Clicked cell in {event.column!r} column, row {event.row!r} with value {event.value!r}')

# Optionally we can also limit the callback to a specific column
# select_table.on_click(click, column='A') 

def save(event):    
    layout_tabulator.save(filename='miHttp.html',embed=True, resources=INLINE)


btn1=pn.widgets.Button(name='Save')
btn1.on_click(save)

layout_tabulator= create_components(Native)
pn.Column(btn1,layout_tabulator).servable()

```

#### Screenshots or screencasts of the bug in action

Tabulator in app

![tabulator panel in app](https://github.com/holoviz/panel/assets/21069237/909000e5-6882-4d93-8224-32b8221aa2b5)

Tabulator in Html File

![tabulator panel in html file](https://github.com/holoviz/panel/assets/21069237/c35dbdeb-f2b1-4189-b538-7e6a3a4d4cb0)

**Comment by Hoxbro** [comment]
I think you should serve the static files with something like: https://panel.holoviz.org/how_to/server/static_files.html

**Comment by philippjfr** [comment]
Indeed, this is a usage problem not a bug. The resources need to be available to be loaded.
