### ISSUE TITLE
Tooltip Icon in component gallery has broken link to preview

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5055]
https://panel.holoviz.org/reference/index.html
<img width="211" alt="image" src="https://github.com/holoviz/panel/assets/15331990/c02c084b-a489-455d-bfc2-818f83ba3ca0">

**Comment by Hoxbro** [comment]
I have added the icon to the S3 bucket.

**Comment by ahuang11** [comment]
Wait I still see it missing
<img width="1245" alt="image" src="https://github.com/holoviz/panel/assets/15331990/7cc98356-52c3-483c-8a48-a93d98716e2e">

**Comment by Hoxbro** [comment]
I think it needs a doc rebuild.

**Comment by philippjfr** [comment]
I'll close, we'll have a 1.1.1 release soon enough.

**Comment by Hoxbro** [comment]
I had already set over a docs build for 1.1.0. But it does now show this (if cache is not in the way):

![image](https://github.com/holoviz/panel/assets/19758978/e4061157-75fb-47db-a07a-fd6cbf2df85f)
