### ISSUE TITLE
Tabulator: Invalid patch index error when calling patch with non-standard pandas indices

### ISSUE THREAD

**Issue by gorj-tessella** [holoviz/panel#5056]
#### Tabulator version info
1.0.4

#### Description of expected behavior and the observed behavior

On a dataframe with non-standard index (ordered integer starting at zero), patch index should be applied but fails with `ValueError: Invalid patch index`

I believe the bug is here, where `as_index` is used to interpret the row index in `patch_value` as actual value or position when updating the underlying dataframe, but then `patch_value` is passed to the underlying `_patch` without modifcation. The downstream code appears to require positional information, not named index. 

https://github.com/holoviz/panel/blob/e4f4c5d8bac96a4b33f92fd64f37b6fc81de5aca/panel/widgets/tables.py#L807-L815

#### Complete, minimal, self-contained example code that reproduces the issue

In a jupyter notebook:

First cell:

```
from panel.widgets import Tabulator
import pandas as pd

df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
widget = Tabulator(df1)
widget
```

Second cell (works):

```
widget.patch({'x':[(0, 5)]}, as_index=False)
```

Third cell (fails with error below):

```
widget.patch({'x':[('a', 10)]})
```

#### Stack traceback and/or browser JavaScript console output

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[73], line 1
----> 1 widget.patch({'x':[('a', 10)]})

File /opt/miniconda3/envs/ais/lib/python3.9/site-packages/panel/widgets/tables.py:815, in BaseTable.patch(self, patch_value, as_index)
    813             else:
    814                 self.value.iloc[ind, columns.index(k)] = value
--> 815     self._patch(patch_value)
    816 else:
    817     raise ValueError(
    818         f"Patching with a patch_value of type {type(patch_value).__name__} "
    819         "is not supported. Please provide a DataFrame, Series or Dict."
    820     )

File /opt/miniconda3/envs/ais/lib/python3.9/site-packages/panel/util/__init__.py:372, in updating.<locals>.wrapped(self, *args, **kwargs)
    370 self._updating = True
    371 try:
--> 372     fn(self, *args, **kwargs)
    373 finally:
    374     self._updating = updating

File /opt/miniconda3/envs/ais/lib/python3.9/site-packages/panel/widgets/tables.py:1443, in Tabulator._patch(self, patch)
   1441 if not patch:
   1442     return
-> 1443 super()._patch(patch)
   1444 self._update_style()
   1445 self._update_selectable()

File /opt/miniconda3/envs/ais/lib/python3.9/site-packages/panel/util/__init__.py:372, in updating.<locals>.wrapped(self, *args, **kwargs)
    370 self._updating = True
    371 try:
--> 372     fn(self, *args, **kwargs)
    373 finally:
    374     self._updating = updating

File /opt/miniconda3/envs/ais/lib/python3.9/site-packages/panel/reactive.py:1035, in SyncableData._patch(self, patch)
   1033 if comm or not doc.session_context or state._unblocked(doc):
   1034     with unlocked():
-> 1035         m.source.patch(patch)
   1036     if comm and 'embedded' not in root.tags:
   1037         push(doc, comm)

File /opt/miniconda3/envs/ais/lib/python3.9/site-packages/bokeh/models/sources.py:723, in ColumnDataSource.patch(self, patches, setter)
    720                     _check_slice(subind)
    722         else:
--> 723             raise ValueError("Invalid patch index: %s" % ind)
    725 self.data._patch(self.document, self, patches, setter)

ValueError: Invalid patch index: a

**Comment by gorj-tessella** [comment]
Possibly this is related to the following code section; although Tabulator has a `filters` param, it also has a `_filters` attribute which is the one that appears to be used throughout the code. Thus even when you have done `add_filter` this section is skipped.

https://github.com/holoviz/panel/blob/60ba9c91990044e8f06c3cc9ca2bc66c4dab73b1/panel/widgets/tables.py#L1432-L1435

**Comment by philippjfr** [comment]
Fixed by https://github.com/holoviz/panel/pull/5645
