### ISSUE TITLE
New layers do not update on ipyleaflet map in panel

### ISSUE THREAD

**Issue by lalligagger** [holoviz/panel#5064]
I've been having trouble getting basemap tiles and layers to load to an ipyleaflet map displayed in a panel app. In the following code, I am expecting the new basemap to load on the map. Instead it goes grey and I get the attached console errors (coming from `ipywidgets_bokeh`).

```
from ipyleaflet import (Map, basemaps, basemap_to_tiles)
import panel as pn
import param


layers = dir(basemaps.OpenStreetMap)
class MapManager(param.Parameterized):

    ls = param.ListSelector([layers[-1]], objects=layers)
    _map = Map(center=(47.4, -122.2), zoom=6, scroll_wheel_zoom=True)

    def __init__(self, **params):
        super().__init__(**params)
        self.param.watch(self.update_layer, ['ls'], what='value')

    # @pn.depends('items.value', watch=True)
    def update_layer(self, selection):
        print('updating layer:')
        print(selection.new[0])

        # create basemap
        bmap = basemap_to_tiles(basemaps.OpenStreetMap[selection.new[0]])

        # clear last layer and add new basemap
        self._map.clear_layers()
        self._map.add_layer(bmap)

        pass
    
    def panel(self):
        return pn.Column(self.param.ls, pn.panel(self._map))

map_mgr = MapManager() 
map_mgr.panel().servable()
```

![image](https://github.com/holoviz/panel/assets/11700267/ef470fd5-eddc-4502-8bf1-c0aea43ac7b6)

I have also started a discourse discussion [here](https://discourse.holoviz.org/t/issue-updating-layers-basemaps-to-ipyleaflet-component/5507) where I am open to workarounds as well.

**Comment by lalligagger** [comment]
I am on `panel==1.1.0`, `ipyleaflet==0.17.0` & `param==1.13.0` (also tried on `ipyleaflet==0.17.3).

**Comment by MarcSkovMadsen** [comment]
Does this issue block your contribution to the data app context @lalligagger ?

**Comment by lalligagger** [comment]
@MarcSkovMadsen pretty much, unless there is a workaround/ patch to get me through. I tried geoviews today with mixed results and anything static like matplotlib would really be a letdown given how quickly I can load decent resolution data into memory.

I will be working on the LangChain tools using my notebook interface and standing by for any hints or updates on this issue. Thanks for your help so far!

**Comment by philippjfr** [comment]
Got a fix for this, will try to get a new ipywidgets_bokeh version along with the Panel fix out asap.

**Comment by lalligagger** [comment]
Hi @philippjfr ... first off, thanks for the help on this! I've tried a `pip ... upgrade` for both Ipywidgets_bokeh and panel. I'm still seeing a grey map on layer reload. Is the fix still pre-release, or is there anything else I can try on my end?

(Still clearing layers -> adding basemap/ image overlay on a map that displays fine on first load.)

**Comment by Hoxbro** [comment]
The change has not been released yet. We are planning to make a pre-release at the start of next week.

**Comment by MarcSkovMadsen** [comment]
@lalligagger . The change has now been released. Let us know if it works for you.
