### ISSUE TITLE
Add Perspective date and number formatting

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5066]
I'm getting more and more happy about the `Perspective` pane because it is super performant and provides a lot of interactivity easily.

But I lack the ability of being able to format dates and numbers similar to Tabulator. Please add.

(I've not been able to find documentation of this is supported by the Perspective Viewer js component or the Perspective Python api)

UPDATE: There is some indication of support below.

**Comment by philippjfr** [comment]
If this isn't supported by Perspective itself, I'd ask you to raise this as an issue with them first and reopen once they have added support.

**Comment by MarcSkovMadsen** [comment]
Support for datetime column formatting was added here https://github.com/finos/perspective/pull/1932. The documentation is not extensive though.

**Comment by MarcSkovMadsen** [comment]
Our reference documentation is incorrect

![image](https://github.com/holoviz/panel/assets/42288570/ffbe3686-c743-4414-971e-eabceb797181)

But you can actually provide a dictionary with some configuration

![image](https://github.com/holoviz/panel/assets/42288570/0d8b3b16-a988-48a2-a5fa-ecf2417a63c2)

It might be possible to then configure the numeric precision you can set manually in this older streaming example on the Perspective web page

![image](https://github.com/holoviz/panel/assets/42288570/405c4c9b-ba22-4931-8d36-7ccc031aa999)

**Comment by MarcSkovMadsen** [comment]
I've added a request for better documentation here https://github.com/finos/perspective/issues/2251

**Comment by MarcSkovMadsen** [comment]
You can set the `fixed` precision

![image](https://github.com/holoviz/panel/assets/42288570/47612359-3c25-4e5f-816e-28c8ec8ea9cc)

Found it deep in the rust file

https://github.com/finos/perspective/blob/22430d113b65b0c1938d0479d1460824a6c3adc6/rust/perspective-viewer/src/rust/components/number_column_style.rs
