### ISSUE TITLE
Misplaced vline in pn.pane.Plotly

### ISSUE THREAD

**Issue by ChristopherRussell** [holoviz/panel#5082]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
I'm seeing this bug when viewing the output in jupyter lab cells
plotly=='5.9.0', bokeh=='3.1.1', panel==1.1.0, python=3.8.16

#### Description of expected behavior and the observed behavior
When adding a vline to a figure in plotly where the x-axis the x position of the vline changes when displayed via pn.pane.Plotly and is incorrect.

#### Complete, minimal, self-contained example code that reproduces the issue

```
x = pd.to_datetime(['2023-06-06 09:24:40', '2023-06-06 09:24:50']).to_series()
y = [-1, 1]
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=y))
fig.add_vline(pd.Timestamp('2023-06-06 09:24:45'))
pane = pn.pane.Plotly(fig)
pane  # vline is not in correct place

pane.object  #vline in correct place

fig # vline in correct place
```

#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/panel/assets/19709603/c92c46c0-a3ad-409e-9d4e-f4a64d9e66ea)

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/7319
