### ISSUE TITLE
Styling does not properly render with Tabulator header filters on version 1.1.0

### ISSUE THREAD

**Issue by enismaxim1** [holoviz/panel#5085]
Panel version: 1.1.0

Styling on tables does not render properly when paired with header filters. If we add a filter to a column, then if a given value is filtered out of the table, the table loses the styling on the element when the element appears back in the table data. In the example below, when typing "-1" into the filter then clearing it, you will observe that the "-2" element loses the red coloring.

#### (For jupyter notebook)
```
import panel as pn
import pandas as pd
pn.extension('tabulator')
df = pd.DataFrame({
    'a': ['1', '-1', '2', '-2']
}, 
)

header_filters = {
    'a': {'type': 'input'}
}

tb = pn.widgets.Tabulator(df, header_filters=header_filters, layout = 'fit_columns')
tb.style.applymap(lambda val: 'color: red' if int(val) < 0 else '')
tb
```

https://github.com/holoviz/panel/assets/42425794/1dd0eed7-a6fa-4246-ae60-b697298ae423

**Comment by Hoxbro** [comment]
Try upgrading to 1.1.

**Comment by enismaxim1** [comment]
> Try upgrading to 1.1.

Bug still exists on version 1.1
