### ISSUE TITLE
Capture guidance about working with Matplotlib figures

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#509]
In https://github.com/pyviz/panel/pull/505 @tacaswell helpfully demonstrated the best way to work with matplotlib figures, we should capture that same guidance in the Matplotlib pane reference notebook.

**Comment by tacaswell** [comment]
Ah, when I put in #505 I was looking for https://panel.pyviz.org/reference/panes/Matplotlib.html but could not find it...

**Comment by philippjfr** [comment]
It lives in ``/examples/reference/panes/Matplotlib.ipynb``
