### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5091]
I was trying to "run" the page https://panel.holoviz.org/how_to/concurrency/async.html. But it fails

```python
ModuleNotFoundError: No module named 'aiohttp'
```

## Reproduce

- Open https://panel.holoviz.org/how_to/concurrency/async.html
- Click the pyodide button twice
- See the exception

![image](https://github.com/holoviz/panel/assets/42288570/58c15f5c-4bf3-42cb-bb92-d82138ff9ddd)

**Comment by philippjfr** [comment]
Well that was very silly, made the code compatible but left the import at the top.

**Comment by Glatzli** [comment]
created a PR for that 
https://github.com/holoviz/panel/pull/5130
not quite sure if that's the common workflow for such minimal issues (my first fix)
