### ISSUE TITLE
Tabulator header filter does not work with row_content

### ISSUE THREAD

**Issue by SKlerk** [holoviz/panel#5095]
Using the header filters in tabulator and then trying to expand the row gives an error for seemingly all rows except at index 0. The issue is very simple to reproduce:

```python
import panel as pn
import pandas as pd
pn.extension('tabulator')
df = pd.util.testing.makeMixedDataFrame()
def _row_content(e):
    return pn.Column("Hello!")
tab = pn.widgets.Tabulator(df, row_content=_row_content, header_filters=True)

pn.Column(tab).servable()
```
![bug](https://github.com/holoviz/panel/assets/95422770/4c66958b-28da-4c14-b01c-8093c34ce89c)

**Comment by nicolazarte** [comment]
Also, to provide some guide, when you open some row contents (for example in row nº 1 and nº 3) and then filter with the headers, the new filtered data is shown with its row contents already opened in the same numbers (nº 1 and 3).

**Comment by philippjfr** [comment]
Appreciate the nice reproducer. It was very helpful in fixing this. Between #7103 and https://github.com/holoviz/panel/pull/7133 this is now resolved.
