### ISSUE TITLE
Random index from Altair's selection_point after transform_aggregate

### ISSUE THREAD

**Issue by jhyoo1982** [holoviz/panel#5103]
From this thread I am opening a new issue: https://github.com/holoviz/panel/issues/3398#issuecomment-1570118424

#### ALL software version info
panel 1.0.3
altair 5.0.1

#### Description of expected behavior and the observed behavior
Expected: Returns index of the selected data point
Observed:
In the provided code example:

'multi_point' returns the index of the original dataframe (incremented by 1) that is input into alt.Chart.
'multi_bar_ref' returns a seemingly random index of the aggregation key from the original dataframe that has been aggregated by Altair.
Although I understand there may not be a precise index for the dataset aggregated internally by Altair, it would be beneficial to have a consistent starting index, such as 0 or 1.

Additionally, it is unclear how aggregation keys map to specific index numbers. Ideally, the program should return the aggregation key itself rather than a seemingly arbitrary index of the aggregation key.

If that's not possible, a good alternative could be to sort the aggregation keys and their corresponding indexes first. Then, using the index of the aggregation key provided by the panel, I could aggregate my dataset using pandas and sort the keys to determine the correlation between the index and the aggregation key.

This process isn't particularly efficient because it requires both Altair and pandas to aggregate data twice, but it could serve as a temporary workaround.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import altair as alt
import pandas as pd
import panel as pn

pn.extension('vega', template='fast')

pn.state.template.title = "Altair Brushing Example"
df = pd.read_json("https://raw.githubusercontent.com/vega/vega/master/docs/data/penguins.json")
df = df.rename({"Beak Length (mm)":"beak_len", "Beak Depth (mm)":"beak_dep"}, axis=1)

df_agg = df.groupby('Species').mean().reset_index().sort_values(by='Species')

multi_point = alt.selection_point(name='multi_point')
multi_bar_ref = alt.selection_point(name='multi_bar_ref')

base = alt.Chart(df)

chart_raw = (
    base.mark_point(tooltip=True).encode(
            x=alt.X('beak_len:Q', scale=alt.Scale(zero=False)),
            y=alt.Y('beak_dep:Q', scale=alt.Scale(zero=False)),
            color=alt.condition(multi_point, 'Species:N', alt.value('lightgray'))
        )
        .properties(
            width=300,
            height=300
        )
        .add_params(multi_point)
)

vega_pane_raw = pn.pane.Vega(chart_raw, debounce=10)


chart_agg = (
    base.mark_bar(tooltip=True)
        .transform_aggregate(
            beak_len_mean = 'mean(beak_len)',
            groupby=['Species']
        )
        .encode(
            x=alt.X('beak_len_mean:Q'),
            y=alt.Y('Species:N'),
            color=alt.condition(multi_bar_ref, 'Species:N', alt.value('lightgray'))
        )
        .properties(
            width=300,
            height=300
        )
        .add_params(multi_bar_ref)
)

vega_pane_agg = pn.pane.Vega(chart_agg, debounce=10)


def print_selection(selection):
    print(selection)

    if(len(selection)>0):
        try:
            for i in selection:
                print(df.iloc[int(i)-1])
        except IndexError:
            print("failed to find data point")

def print_selection_agg(selection):
    print(selection)
    if(len(selection)>0):
        try:
            for i in selection:
                print(df_agg.iloc[int(i)-1])
        except IndexError:
            print("failed to find data point")

            

res = pn.Row(
    vega_pane_raw,
    vega_pane_agg,
    pn.Column(
            pn.bind(print_selection, vega_pane_raw.selection.param.multi_point),
            pn.bind(print_selection_agg, vega_pane_agg.selection.param.multi_bar_ref),        
    )
)

res.servable()
```

#### Screenshots or screencasts of the bug in action
Selecting points in a scatter chart works without using transform_aggregate:
<img width="1376" alt="Screenshot 2023-06-13 at 5 54 11 PM" src="https://github.com/holoviz/panel/assets/876125/6b88a310-8b3b-4205-ba58-caa964f45dab">

Selecting bars in a bar chart does not work using transform_aggregate because index is random like 346:
<img width="1375" alt="Screenshot 2023-06-13 at 5 54 25 PM" src="https://github.com/holoviz/panel/assets/876125/a9f08b12-5177-498d-aedb-10f2ad7d4a82">

**Comment by philippjfr** [comment]
Were you able to resolve this?

**Comment by jhyoo1982** [comment]
> Were you able to resolve this?

I created another issue because it is impossible to get keys with the example code above.
https://github.com/holoviz/panel/issues/5133
