### ISSUE TITLE
pn.config.defer_load not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5105]
I'm on Panel 1.1.0 and trying to use `pn.extension(defer_load=True)` but it seems not to be working.

## Reproduce

```python
import panel as pn

pn.extension(defer_load=True, loading_indicator=True, template="fast")


def some_object():
    import time

    time.sleep(5)
    return f"loaded"


pn.Column(
    "before", pn.panel(some_object), "after", height=500, width=500
).servable()
```

I would expect the template to quickly show up and contain a loading indicator for 5 seconds. But it does not.

https://github.com/holoviz/panel/assets/42288570/e635d153-65a1-4021-bee0-5615f16ef68d

## Workaround - Set `loading_indicator=True` explicitly

This seems to work

```python
import panel as pn

pn.extension(defer_load=True, loading_indicator=True, template="fast")

def some_object():
    import time

    time.sleep(5)
    return f"loaded"

pn.Column("before", pn.panel(some_object), "after", height=500, width=500).servable()
```

https://github.com/holoviz/panel/assets/42288570/49aab626-b18b-4802-93ba-1efaf27e3771

## Regression

This used to work.

## Docs missing

That you can set `pn.extension(defer_load=True)` should be documented somewhere. But its not. I believe it should be documented here https://panel.holoviz.org/how_to/callbacks/load.html. But its not.

**Comment by MarcSkovMadsen** [comment]
The functionality was originally added in https://github.com/holoviz/panel/pull/3882

**Comment by MarcSkovMadsen** [comment]
In PR the `pn.state.loaded` parameter was also added. Its still there, but not working. I cannot bind to it. I can see there is also a property called `loaded`. I think that is the issue.

**Comment by MarcSkovMadsen** [comment]
Yes. It would be very nice. Every time you cannot create reactive interfaces using pn.bind or pn.depends, but have to use callbacks it complicates the "story" and creates friction.

**Comment by philippjfr** [comment]
@MarcSkovMadsen Could you maybe make a list of parameters that would be helpful on `pn.state` and put that in an issue?
