### ISSUE TITLE
pn.cache only caches for a session. 

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5109]
panel==1.1.0

When working on the Streamlit Migration guide in https://github.com/holoviz/panel/pull/5027 I discovered that `@pn.cache` only caches for a user session. Not globally. 

Globally was what I and @philippjfr expected. Globally is what I need most often.

## Reproduce

```python
from time import sleep

import numpy as np
import panel as pn
from matplotlib.figure import Figure


def get_data():
    print("running get_data func")
    sleep(0.1)
    return np.random.normal(1, 1, size=100)

def plot(data, bins):
    print("running plot func", bins)
    sleep(2)
    fig = Figure(figsize=(8,4))
    ax = fig.subplots()
    ax.hist(data, bins=bins)
    return fig

pn.extension(sizing_mode="stretch_width", template="bootstrap")

data = get_data()
bins = pn.widgets.IntSlider(value=20, start=10, end=30, step=1)
cplot = pn.cache(plot)
bplot = pn.bind(cplot, data, bins)
pn.Column(bins, pn.panel(bplot, loading_indicator=True)).servable()
```

You can see how it reruns the `plot` function after a reload of the browser below.

https://github.com/holoviz/panel/assets/42288570/ef0832ec-7c88-472f-83c2-a34469933ffa

## Additional Context

You actually need to be able to both cache things for a users session and globally. Globally probably accounts for 99% of use cases though.

You could handle this by providing two caches:

- pn.cache_user: caches for a user session
- pn.cache_global: caches globally across user session.

If we just want the one we could describe in the documentation how to get the session id (I don't know how) and use this to cache for a user session. This documentation could be added to the *cache* documentation https://panel.holoviz.org/how_to/caching/index.html.

See also https://github.com/holoviz/panel/issues/5028#issuecomment-1576002494 and https://github.com/holoviz/panel/issues/5028#issuecomment-1576025645

I'm on windows. Don't think it matters.

**Comment by philippjfr** [comment]
I'll add an argument to `pn.cache` to support per-session caches.

**Comment by MarcSkovMadsen** [comment]
Looks like you are right. I overlooked this. Thanks
