### ISSUE TITLE
Bug in Tabulator filter when using 'in' function and a list with single element

### ISSUE THREAD

**Issue by TBym** [holoviz/panel#5123]
Hi,
there is a bug in `BaseTable` class in function `_get_header_filters(self, df)`. When applying a filter with 'in' function and passing a list with single value, the list gets converted to the single value. This is causing an error at line 486 where Pandas isin(val) function is expecting a list.
Simple solution would be to convert the value back to list within the 'in' if statement.
```
... 
elif op == 'in':
    if not isinstance(val, list):
        val = list(val)          
    filters.append(col.isin(val))
```

**Comment by Hoxbro** [comment]
Can you make a PR with this fix and a test?

**Comment by TBym** [comment]
I submitted a pull request #5125.
