### ISSUE TITLE
ParagraphInput / TextInput to use vertical space

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#515]
```
import panel as pn
pn.extension()

gs = pn.GridSpec()
gs[:5, 0] = pn.widgets.TextInput()
gs
```
Text overflows to the side instead of using the available vertical space.

![image](https://user-images.githubusercontent.com/15331990/60995006-818acf80-a306-11e9-99a0-86a0f6847432.png)

**Comment by philippjfr** [comment]
May be a bokeh feature request but I'd have to investigate.

**Comment by philippjfr** [comment]
We now have a [TextAreaInput](http://panel.pyviz.org/reference/widgets/TextAreaInput.html) widget.
