### ISSUE TITLE
impossible to display a title with Trend widget

### ISSUE THREAD

**Issue by nicho2** [holoviz/panel#5165]
in the version 1.1.1, 
Renamed Trend parameter title to name ([#5092](https://github.com/holoviz/panel/pull/5092))

and now , how to displayed a title (because name displays nothing)

**Comment by Hoxbro** [comment]
This is an oversight.  A work-around for now will be the following: `pn.indicators.Trend._rename["name"] = "title"`

``` python
import panel as pn

pn.extension()
pn.indicators.Trend._rename["name"] = "title"

import numpy as np
import panel as pn

pn.extension()

data = {'x': np.arange(50), 'y': np.random.randn(50).cumsum()}
trend = pn.indicators.Trend(
    name='Price', data=data, width=200, height=200
)
```

![image](https://github.com/holoviz/panel/assets/19758978/06e4a48c-127a-4c44-8036-a7ba22d36e56)
