### ISSUE TITLE
Ipython display widget no longer works with new release

### ISSUE THREAD

**Issue by nicho2** [holoviz/panel#5168]
We use the YouTubeVideo widget from Ipython

from IPython.display import YouTubeVideo

with the panel version 0.14, it was going well  (panel serve final_notebook.ipynb --port 8080 --show --autoreload)

ex: there is iframe in the html cade

<iframe width="100%" height="540px" src="https://www.youtube.com/embed/Daolqfjen94?autoplay=1" frameborder="0" allowfullscreen="" allow="autoplay"></iframe>

now with the release 1.1.1

we have an image in the html code

<img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQA..............................CCCCACCCCAP/Z" style="max-width: 100%; max-height: 100%; object-fit: contain; width: 100%; height: auto;">

(the display in jupyter lab is always good.)

**Comment by philippjfr** [comment]
Seems like YouTubeVideo has both `_repr_jpeg_` and `_repr_html_` methods and `pn.pane.JPEG` returns a higher precedence than `pn.pane.HTML` does. For now you can just do:

```python
yt = pn.pane.HTML(YouTubeVideo('https://www.youtube.com/embed/Daolqfjen94?autoplay=1'))
```
