### ISSUE TITLE
Chatbox text getting squeezed

### ISSUE THREAD

**Issue by lalligagger** [holoviz/panel#5171]
This issue is observed on panel `1.1.1`, downgrading to `1.1.0` fixes what I am seeing.

In the chatbox widget, the text for both user queries and responses are squeezed (see screenshot).

I have confirmed this is present when running the basic Chatbox code.
```
import panel as pn

chat_box = pn.widgets.ChatBox(
    value=[
        {"You": "Hello!"},
        {"Machine": "Greetings!"},
        {"You": "Question for you..."},
        {"You": "What is the meaning of life?"},
        {"Machine": "I don't know. Do you know?"},
    ],
)

chat_box.servable()
```
![image](https://github.com/holoviz/panel/assets/11700267/cf272d15-3de8-443e-b4b6-96801e106864)

**Comment by ahuang11** [comment]
Thanks for reporting this; will try to fix this soon.

At the moment, a work around:
```python
import panel as pn
pn.extension(sizing_mode="stretch_width")

chat_box = pn.widgets.ChatBox(
    value=[
        {"You": "Hello!"},
        {"Machine": "Greetings!"},
        {"You": "Question for you..."},
        {"You": "What is the meaning of life?"},
        {"Machine": "I don't know. Do you know?"},
    ],
)

chat_box.servable()
```
