### ISSUE TITLE
Different output in jupyter notebook vs panel serve

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#518]
```
import pandas as pd
import panel as pn
pn.extension()

df = pd.util.testing.makeDataFrame()
pn.WidgetBox(pn.pane.HTML(pd.concat([df] * 25, axis=1), max_width=50), sizing_mode='stretch_both').servable()
```

![image (1)](https://user-images.githubusercontent.com/15331990/61086002-92ab0d80-a3e6-11e9-8eeb-242419a738c7.png)
![image (2)](https://user-images.githubusercontent.com/15331990/61086003-9343a400-a3e6-11e9-8b1e-bf22b62b38f2.png)

**Comment by philippjfr** [comment]
Look the same to me in all environments on master.
