### ISSUE TITLE
FileInput `name` keyword doesn't add name

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#519]
```
import panel as pn
pn.extension()

file_input = pn.widgets.FileInput(name='Select a file!')
file_input
```
![image](https://user-images.githubusercontent.com/15331990/61087256-fe42aa00-a3e9-11e9-8be1-4efe7c43274e.png)

**Comment by maximlt** [comment]
Just had a look at this one. It seems that the bokeh `FileInput` widget does have a `name` attribute but that it's not used at all for UI purposes (it's an internal id used to select a bokeh model in a document).

There is a similar issue in bokeh https://github.com/bokeh/bokeh/issues/9552 dating from the beginning of this year. Apparently it's not a straightforward fix.

For the time being we could just remove ```name`` as a **Display** property in the reference docs [here](https://panel.holoviz.org/reference/widgets/FileInput.html) not to confuse people. @philippjfr  are you ok with that?

**Comment by philippjfr** [comment]
Sure I suppose. What I would like to do is make a single issue listing all the widgets that don't have a way to set a title/name, rather than the multiple issues that we have currently.

**Comment by maximlt** [comment]
> What I would like to do is make a single issue listing all the widgets that don't have a way to set a title/name, rather than the multiple issues that we have currently.

I can take care of that.

**Comment by philippjfr** [comment]
Fabulous, I've made you a collaborator btw, so feel free to close issues once you've made the general one.
