### ISSUE TITLE
Panel labels do not follow jupyterlab theme

### ISSUE THREAD

**Issue by timsnyder** [holoviz/panel#520]
Jupyterlab (1.0.2) has theming support.  Theme can be selected under the "Settings->JupyterLab Theme" menu.

Observed behavior with 
[holoviz-tutorial-py37.conda_env.yml.txt](https://github.com/pyviz/panel/files/3384559/holoviz-tutorial-py37.conda_env.yml.txt) is that running the first four cells of the 02_Building_Panels.ipynb from the SciPy'19 tutorial this week, displays labels in black text above the row slider and table row widget:
![light_theme](https://user-images.githubusercontent.com/83846/61095831-a83a2a80-a41a-11e9-9495-8fbd23764975.png)

Here's a screenshot of the JupyterLab Theme menu:
![menu_select_dark](https://user-images.githubusercontent.com/83846/61095856-c30c9f00-a41a-11e9-82b3-6ea2e7c3c686.png)

Once in the dark theme, the panel labels stay black and are not readable:
![dark_theme_panel_labels_stay_black](https://user-images.githubusercontent.com/83846/61095873-dddf1380-a41a-11e9-8ebd-37f87d78d086.png)

I haven't dug into the Juperterlab theming implementation or pyviz labextension yet to be able to suggest a fix or supply a PR but @jlstevens suggested that I open a ticket here to start.

**Comment by timsnyder** [comment]
Looks like the default dark theme may come from https://github.com/jupyterlab/jupyterlab/tree/master/packages/theme-dark-extension 

@jasongrout is that the right place to be looking at what the Dark theme I selected in the screenshots above is doing?

**Comment by jasongrout** [comment]
Yes. In particular, we theme using CSS variables, so if you use those, you should get the theme font colors, etc. However, even if you don't want to use the built-in css variables, you can still key your theming off of the light/dark data attribute set on the body element.

**Comment by timsnyder** [comment]
Thanks.  That's the concise overview I was hoping for. :)

I'll see if I can whip up a PR for this.

**Comment by timsnyder** [comment]
Looking a bit closer, The div is coming from Bokeh ("bk bk-slider-title")
![panel_widget_title_div](https://user-images.githubusercontent.com/83846/61100792-07a13600-a42d-11e9-86ff-3092e468e6a3.png)

**Comment by jasongrout** [comment]
> That's the concise overview I was hoping for. :)

If it was too concise, let me know and I can elaborate a bit :).

**Comment by timsnyder** [comment]
Variables on the body look like data-jp-theme-light="<true|false>" and data-jp-theme-name="JupyterLab <Light|Dark>".  Guessing, I'd say that data-jp-theme-light is the "light/dark data attribute" Jason mentioned above.

![body_vars](https://user-images.githubusercontent.com/83846/61101854-0c67e900-a431-11e9-83a6-230029f7d295.png)

**Comment by philippjfr** [comment]
Thanks for the issue @timsnyder and thanks for the background @jasongrout. I think we may want to raise this in bokeh since they are affected too and the implementation will likely have to be in bokeh itself.

**Comment by jasongrout** [comment]
>  Guessing, I'd say that data-jp-theme-light is the "light/dark data attribute" Jason mentioned above.

Yes.

**Comment by timsnyder** [comment]
@philippjfr, I reached out to the Bokeh folks [in their discourse]( https://discourse.bokeh.org/t/jupyterlab-bokehjs-loading-wonkyness-and-css-theming/3743) get a conversation started about how to fix the Bokeh part of it.  Looking more, Bokeh seems to be providing the slider but panel-dataframe provides the dataframe row.

After remembering how to use the FF dev tools to inspect the css, it looks like bk-slider-title is ending up without any CSS setting it's color and thus defaulting to something. (Perhaps user client or HTML standard default?)
![bk-slider-title_doesnt-set-color](https://user-images.githubusercontent.com/83846/61128213-ef560900-a476-11e9-9063-1bd80f397f8f.png)
I won't go more into the Bokeh details here other than to say that their css looks to be autogenerated in BokehJS's build.  I'm looking at it and I'll crosslink an issue if it turns into one.

panel-df looks like it is getting it's font color from CSS that is probably provided by panel somewhere:
![panel-df_color_is_black](https://user-images.githubusercontent.com/83846/61128609-f6c9e200-a477-11e9-901c-bbcf41d39fe3.png)

So, perhaps the \@pyviz/jupyterlab_pyviz labextension could do something to the CSS for panel when it knows it's in the jupyterlab environment?  That being said, we would want to be careful that rendered panels outside of jupyter continue to look the same when loaded as when the user created them, possibly from inside jupyterlab.

**Comment by jsignell** [comment]
I think bokeh is still going to be the right place for these changes.

**Comment by chuktuk** [comment]
I'm not sure if this is still a bokeh issue, but I'm following the tutorial, and the first pn.interact slider doesn't render in appropriate colors for jupyter lab dark theme.
![Screenshot from 2020-06-06 23-29-19](https://user-images.githubusercontent.com/45741689/83959668-b290be80-a84d-11ea-841c-ec03768d5aef.png)
This issue goes away if you switch back to the light theme.
![Screenshot from 2020-06-06 23-31-47](https://user-images.githubusercontent.com/45741689/83959681-e9ff6b00-a84d-11ea-81bd-866def16db24.png)

**Comment by raybellwaves** [comment]
Recently came across this. I didn't see white text in Dark mode as stated above

**Comment by philippjfr** [comment]
I think the theming support currently only works for regular inline rendering, when using the preview button the content is put into an iframe which probably does not transfer the CSS variables. Will have to see how/if Voila Preview Deals with this.

**Comment by philippjfr** [comment]
The theming support in Panel 1.x should have largely addressed this. If there's remaining issues those should be raised separately.
