### ISSUE TITLE
Automatic vscode detection is not always working 

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#5200]
Continuation of #5007. 

When running VSCode inside a virtualization/containerized environment, for example, WSL on Windows, the system environment variable we use `VSCODE_PID` to detect if we are running inside a vs code notebook is not set. Below is an example of the `VSCODE_` environment variables set in a notebook environment on WSL. 

```
import os
sorted(k for k in os.environ if "VSCODE" in k)
```

![image](https://github.com/holoviz/panel/assets/19758978/82b1a588-c3a3-4b35-a851-d254da710885)

![image](https://github.com/holoviz/panel/assets/19758978/93927c6d-4afc-4d48-8ba0-7ca32c67301e)

**Comment by Hoxbro** [comment]
@giladpn, Is it possible for you to run the above code in a notebook running in a docker container?

**Comment by philippjfr** [comment]
Would propose we check for VSCODE_CWD in addition to VSCODE_PID

**Comment by MarcSkovMadsen** [comment]
What about warning if jupyter_bokeh not installed?

**Comment by Hoxbro** [comment]
Unrelated to this issue. 

See your _own_ issue here https://github.com/holoviz/panel/issues/5190
