### ISSUE TITLE
Broken link to sync_url.png in state docs

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#5223]
There's a broken link on this page: https://panel.holoviz.org/how_to/state/index.html

It tries to load  https://assets.holoviz.org/panel/how_to/state/sync_url.png which gives error 403 forbidden.

https://github.com/holoviz/panel/blob/eb12414c9de7502ea3d247e4f03b3b6c23830c8c/doc/how_to/state/index.md?plain=1#L36

**Comment by philippjfr** [comment]
Thanks, fixed.
