### ISSUE TITLE
Panel docs issues

### ISSUE THREAD

**Issue by jsignell** [holoviz/panel#523]
I was watching people click around on the panel docs during the talk at scipy and seeing some UX things that they are struggling with:

 - It doesn't seem to be clear that something meaningful is changing between the screenshot and the iframe: http://panel.pyviz.org/gallery/demos/clifford.html#gallery-clifford
 - People expected the reset button to unselect glaciers:
   <img width="270" alt="Screen Shot 2019-07-12 at 3 27 00 PM" src="https://user-images.githubusercontent.com/4806877/61156689-9eb3cf80-a4b9-11e9-8420-d2fe71392f1f.png">
 - There is no image in this notebook: http://panel.pyviz.org/gallery/simple/clifford_interact.html#gallery-clifford-interact
 - Empty plot: http://panel.pyviz.org/gallery/apis/stocks_altair.html#gallery-stocks-altair
 - Binder notebook link is broken for http://panel.pyviz.org/gallery/demos/clifford.html#gallery-clifford and others that aren't called app anymore. (I pushed to gh-pages to fix this quickly).

**Comment by philippjfr** [comment]
>It doesn't seem to be clear that something meaningful is changing between the screenshot and the iframe

Any suggestion on what would make it clear?

>People expected the reset button to unselect glaciers:

Not sure what to do about this. I've heard similar things in multiple contexts, people often assume the reset tool does more than it actually does, but it will never do that, so there is no obvious fix.

>Empty plot

Need to investigate. Usually this is due to issues with cross-origin policies but this embeds the data so I have no idea.

**Comment by jsignell** [comment]
> It doesn't seem to be clear that something meaningful is changing between the screenshot and the iframe

Maybe a spinner with text that says something very short like "Loading interactive version"

> people often assume the reset tool does more than it actually does

Yeah it'd be nice to be able to capture repeated clicks and show an alert, but that seems weird to implement. 

> Binder notebook link is broken

I fixed the binder links in the github repo, so you should be able to grab them from there, but I guess they are dynamically generated? Maybe the notebook name isn't actually needed?

**Comment by philippjfr** [comment]
>Maybe a spinner with text that says something very short like "Loading interactive version"

That's what I used initially but @jbednar argued strongly that we should use a screenshot in case the deployment fails for whatever reason.

>Maybe the notebook name isn't actually needed?

That's a good point, should try that.

**Comment by jsignell** [comment]
> That's what I used initially but @jbednar argued strongly that we should use a screenshot in case the deployment fails for whatever reason.

Maybe there could be some overlay on the static version?

**Comment by jbednar** [comment]
An overlay like a watermark would help.

**Comment by philippjfr** [comment]
Don't have any idea how we'd achieve that.

**Comment by jsignell** [comment]
Can't we just have an html text box over the image? Or we could make a new image with the loader text directly on it...

**Comment by philippjfr** [comment]
The current solution is very simple in that we simply put a background image on the iframe and then remove it onload. Adding any extra image or text on top adds a fair amount of complexity, so it's definitely doable but not quite as simple.

@jsignell just suggested that we could add the text straight to the image in a way that makes the difference obvious. That might be the simplest solution.

**Comment by jbednar** [comment]
Sounds good to me.

**Comment by fmaussion** [comment]
>> People expected the reset button to unselect glaciers

Can we (for this specific app) give a color to the "Clear selection" button? It will at least raise awareness to its presence...

**Comment by philippjfr** [comment]
Closing in favor of https://github.com/holoviz/panel/issues/1827 and https://github.com/holoviz/panel/issues/1500
