### ISSUE TITLE
Player widget not updating plot

### ISSUE THREAD

**Issue by droumis** [holoviz/panel#5239]
#### ALL software version info
Bokeh: 3.2.0 
HoloViews: 1.16.2
Panel: 1.2.0

#### Description of expected behavior and the observed behavior
The player widget no longer updates the linked plot

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import xarray as xr
import panel as pn; pn.extension()
import holoviews as hv; hv.extension('bokeh')
import hvplot.xarray
import bokeh

N = 10
data = np.zeros((N, N, N))
indices = np.arange(N)
data[indices, indices, indices] = 1
da = xr.DataArray(data, coords=[("a", indices), ("b", indices), ("c", indices)], name="data")

player = pn.widgets.Player(start=int(da.coords['c'].values.min()), end=int(da.coords['c'].values.max()))

main_view = da.hvplot.image('a', 'b', groupby="c", widgets={"c": player}, width=300, colorbar=False)
print(f"Bokeh: {bokeh.__version__} \nHoloViews: {hv.__version__} \nPanel: {pn.__version__}")
main_view
```

## Panel 1.2 (not working)
<img width="741" alt="image" src="https://github.com/holoviz/panel/assets/6613202/037cbb49-e076-45ac-ae81-3e55b527ad64">

## Panel 1.1 (working)
<img width="712" alt="image" src="https://github.com/holoviz/panel/assets/6613202/e9036943-3b01-4005-944d-59ae28c3220a">

**Comment by philippjfr** [comment]
Can't reproduce this one, works just fine for me in 3.2.

**Comment by philippjfr** [comment]
@droumis suspect this was something to do with your notebook setup, e.g. the jupyter-client issue. I'll close but if you can reproduce after pinning jupyter-client<8, please reopen.
