### ISSUE TITLE
If server stopped, is it possible to alert the user upfront?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5240]
Like an overlay that says "Unable to process event; cannot connect to backend server"

**Comment by MarcSkovMadsen** [comment]
Please combine this with a message for websocket connection lost/ closed.

Would be a huge improvement to user experience.

**Comment by philippjfr** [comment]
Indeed, they're really the same thing. It's already possible but I'll add a simpler API.

**Comment by MarcSkovMadsen** [comment]
If this is already possible it might also be an idea to just teach us and/ or improve the documentation.

**Comment by ahuang11** [comment]
I wonder if it's possible to also show traceback notifications too for debugging?

**Comment by philippjfr** [comment]
Please open a separate issue about the traceback notification handling. For Websocket disconnect there is now a config option.
