### ISSUE TITLE
Text Alignment Issue in HTML Pane

### ISSUE THREAD

**Issue by diehl** [holoviz/panel#5246]
#### ALL software version info
Panel v1.2.0, macOS Ventura 13.4, Chrome 114.0.5735.198

#### Description of expected behavior and the observed behavior
I’m noticing some unexpected outcomes when varying the text-align CSS property in an HTML pane. I’m trying to center text within an HTML pane and kept noticing what looked like a misalignment. Adding a visible border to the pane helped clarify indeed that there is an offset. See the following.

![image](https://github.com/holoviz/panel/assets/349843/05ebb5a1-9fc6-41d9-ac93-fb7eae4a0934)

On a whim, I thought I’d check to see what happens when I set text-align to left and right. Strangely enough, I’m seeing a bias to the right in both of these results. For left justified text, it doesn’t go quite to the border. For right justified text, it goes a bit farther to the right. Similarly, the centered text is biased to the right.

![image](https://github.com/holoviz/panel/assets/349843/3daee735-f958-4545-a324-b0f22496f848)

![image](https://github.com/holoviz/panel/assets/349843/25851828-e784-4a65-9b7a-8b256ffacc2c)

**Comment by philippjfr** [comment]
The problem here is that the example above simply does not allocate enough space because together with the margin it overflows the container:

```python
pn.Row(
    pn.pane.HTML(
        'Geolocation', styles={'border': '1px solid black', 'font-weight': 'bold', 'text-align': 'left'},
        width=120, margin=0
    ),
    pn.pane.HTML(
        'Geolocation', styles={'border': '1px solid black', 'font-weight': 'bold', 'text-align': 'center'},
        width=120, margin=0
    ),
    pn.pane.HTML(
        'Geolocation', styles={'border': '1px solid black', 'font-weight': 'bold', 'text-align': 'right'},
        width=120, margin=0
    )
)
```


<img width="375" alt="Screenshot 2024-08-26 at 23 59 46" src="https://github.com/user-attachments/assets/7f0386dc-80d5-4eea-ae48-acd4d85aeae6">


```python
pn.Row(
    pn.pane.HTML(
        'Geolocation', styles={'border': '1px solid black', 'font-weight': 'bold', 'text-align': 'left'},
        width=60
    ),
    pn.pane.HTML(
        'Geolocation', styles={'border': '1px solid black', 'font-weight': 'bold', 'text-align': 'center'},
        width=60
    ),
    pn.pane.HTML(
        'Geolocation', styles={'border': '1px solid black', 'font-weight': 'bold', 'text-align': 'right'},
        width=60
    )
)
```

<img width="251" alt="Screenshot 2024-08-27 at 00 06 01" src="https://github.com/user-attachments/assets/a63eeea4-302c-43a5-96af-5d132aca1334">
