### ISSUE TITLE
Align ReactiveHTML with AnyWidget

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5248]
- [ ] make it possible to develop ReactiveHTML in external files with super fast auto reload without loosing state as AnyWidget can
- [ ] make AnyWidgets work with Panel and document this
- [ ] Make sure the Panel intro to ReactiveHTML is on par with AnyWidget
- [ ] Make it easy to wrap React components minimum as simple as https://github.com/widgetti/ipyreact

## Resources

- https://blog.jupyter.org/anywidget-jupyter-widgets-made-easy-164eb2eae102

**Comment by philippjfr** [comment]
Superseded by the work on ESM components.
