### ISSUE TITLE
Vizzu Chart Tooltip

### ISSUE THREAD

**Issue by derrickmcs** [holoviz/panel#5255]
Vizzu chart tooltip would be very useful for analysis. Can you please add this as part Vizzu pane?

Example:
https://lib.vizzuhq.com/latest/examples/analytical_operations/drilldown/Area_Area/
`chart.feature('tooltip', true);
`

**Comment by MarcSkovMadsen** [comment]
Hi @derrickmcs 

The link shows 404 error to me. Could you provide the working one?

**Comment by MarcSkovMadsen** [comment]
I believe this is the correct link https://lib.vizzuhq.com/latest/examples/analytical_operations/drilldown/area/

The doumentation for the `chart.feature` can be found here https://lib.vizzuhq.com/latest/reference/classes/Vizzu/?h=feature#feature

**Comment by derrickmcs** [comment]
@MarcSkovMadsen yes, that's correct. Thank you. Sorry about the link. I had the page opened and didn't realize it had changed.

**Comment by philippjfr** [comment]
Support was merged.
