### ISSUE TITLE
Cannot move slider in material_ui how to guide

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5269]
When I drag the slider in the [material_ui how to guide](https://panel.holoviz.org/how_to/custom_components/examples/material_ui.html) it does not move. Its stuck.

![image](https://github.com/holoviz/panel/assets/42288570/048e4f63-503d-4748-b5c4-4a0bcce53006)

**Comment by philippjfr** [comment]
I think we'll just remove that example now that we have ESM components.
