### ISSUE TITLE
Enhance ChatBox Guide

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5271]
I'm on Panel 1.20. My son was trying to build a chat bot using the `ChatBox` and `openai`.

He had some difficulty getting started because its not documented how to `bind` to and handle new messages from the user. Its not explained that new messages from the users gets appended to the `value` list and that you can bind to that. To me that was not clear either. I thought they would be set on some *special parameter*. So I was trying to find that parameter in the guide. And got stuck.

It also takes some code and understanding to get a nice chatbot similar to the example in https://discourse.holoviz.org/t/openai-conversation-using-chatbox/5548.

Please document this and add a nice working example

**Comment by ahuang11** [comment]
Ideally, in the near future, we would have a Langchain integration that wraps all that and users would only need to specify an agent or model.

**Comment by MarcSkovMadsen** [comment]
Langchain is just one framework. The feedback I see on langchain is great for experimentation but not for production. For production people often do from scratch implementations.

I would at least like to be able to use OpenAI REST API directly. I'm also interested in the Microsoft Guidance framework. It fits my brain quite well.

**Comment by MarcSkovMadsen** [comment]
I will close this one as the ChatBox is about to be deprecated with Panel 1.3.0.
