### ISSUE TITLE
panel server method difference between programmatic  and cli(commandline)

### ISSUE THREAD

**Issue by orangeSi** [holoviz/panel#5272]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
```
Python v3.11.4
panel v1.2.0
bokeh v3.2.0
```
```
OS: window 10
```
#### Description of expected behavior and the observed behavior.
1.assumpt:  ```app = pn.widgets.TextInput(name="email")``` and open two Chrome tab pages(```tab A and tab B```).
2.expect behavior:
    If server the same app by ```panel serve demo.py```  or ```pn.serve(app)``` should be the same result, example If I fill the input widget with new value  at the ```tab A``` and the vallue of input widget of ```tab B```  will not be changed.

3.observed behavior:
   When serve by ```panel serve demo.py``` , it's ok.
   But when use  ```pn.serve(app)``` and ```python demo.py``` , then I open two Chrome tab pages(```tab A and tab B```) and both access http://192.168.8.85:8080/ .Then if I fill the input widget with new value  at the ```tab A``` , then at the same time the same new value will sync to the input widget of ```tab B``` !  It's wired ?

#### Complete, minimal, self-contained example code that reproduces the issue
If  serve by ```panel serve demo.py``` , the code is:
```
#!/user/bin/env python
import param
import panel as pn
import os
import sys
import socket

app = pn.widgets.TextInput(name=f"email:", placeholder="x@y.com")
app.servable(title="")  
```
If serve by ```pn.serve(app)```, the code is:
```
#!/user/bin/env python
import param
import panel as pn
import os
import sys
import socket

port=8080
local_ip = socket.gethostbyname(socket.gethostname())
app = pn.widgets.TextInput(name=f"email:", placeholder="x@y.com")
pn.serve(app,  port=int(port), websocket_origin=[f"{local_ip}:{port}", f"localhost:{port}"])   ###  app.show() will get the same wired behavior as pn.serve()
```

#### Stack traceback and/or browser JavaScript console output
```
[bokeh] setting log level to: 'info'
[bokeh] Websocket connection 0 is now open
 Bokeh items were rendered successfully
[bokeh] document idle at 11 ms
```
#### Screenshots or screencasts of the bug in action
If  serve by ```panel serve demo.py``` ,  the two tabs at below:
![two_tab_new_20230717135745](https://github.com/holoviz/panel/assets/12126846/1e383f10-2ea2-4a40-b827-7d07cd2850c1)

If serve by ```pn.serve(app)```, the two tabs at below:
 ![two_tabs_20230717134745](https://github.com/holoviz/panel/assets/12126846/0953df6a-051b-4289-bea0-d7573a217ed6)

**Comment by Hoxbro** [comment]
This is expected behavior. `pn.serve` is using the same instance of the TextInput. If you want them separated either use `panel serve` or wrap your TextInput into a function:

``` python
import socket

import panel as pn

port = 8080

local_ip = socket.gethostbyname(socket.gethostname())


def app():
    return pn.widgets.TextInput(name="email:", placeholder="x@y.com")


pn.serve(
    app, port=int(port), websocket_origin=[f"{local_ip}:{port}", f"localhost:{port}"]
)
```

**Comment by orangeSi** [comment]
> This is expected behavior. `pn.serve` is using the same instance of the TextInput. If you want them separated either use `panel serve` or wrap your TextInput into a function:
> 
> ```python
> import socket
> 
> import panel as pn
> 
> port = 8080
> 
> local_ip = socket.gethostbyname(socket.gethostname())
> 
> 
> def app():
>     return pn.widgets.TextInput(name="email:", placeholder="x@y.com")
> 
> 
> pn.serve(
>     app, port=int(port), websocket_origin=[f"{local_ip}:{port}", f"localhost:{port}"]
> )
> ```

thanks~ I will try this way

**Comment by philippjfr** [comment]
Not sure this difference is clear from the docs, would be good to find a place to compare CLI and programmatic/dynamic server setups.
