### ISSUE TITLE
Fix ChatBox.value list of tuples issue

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5276]
Currently the ChatBox.value parameter is a list of *messages* on the form `{name: text}`.

I strongly believe that messages should be tuples and not dictionaries because its easier to explain, understand and work with. And it does not make sense to use dictionaries with one item only. Its the wrong choice.

Please change this before the ChatBox gets major adoption.

## Alternatives

Add a *utility* function that you can use.

```python
def value_as_tuples(self):
    return [next(iter(item.items())) for item in self.value]
```

But then again there is more to explain and maintain. And also it could lead to performance issues.

I don't like this solution as it adds unnecessary complexity.

### Code Example

If I'm to get the last value I need to do

```python
user, value = next(iter(chat_box.value[-1])).items()
```

How am I to

- remember how to do this?
- explain this to colleagues or users on discourse?

I believe users should be able to do

```python
user, value = chat_box.value[-1]
```

I believe most users will be requsting the last value because they want to 

- check if this is a prompt from the user
- get a response from an AI or similar.

So every user will have issues and it will hinder adoptance.

## Additional Context

I think you will understand the issue better as soon as you try to add example use cases to the documentation. Then you will figure out that the ChatBox is not easy to use yet. And the first and main issue is this.

## Comment

For me this is a major issue for the ChatBox @philippjfr and @ahuang11. It will hold me down using and promoting the `ChatBox`. Would you be willing to change this or accept a PR?

**Comment by philippjfr** [comment]
My opinion is (and I've stated this somewhere before) that we should simply support but never use or mention the dictionary format again and then eventually warn and remove support.

**Comment by philippjfr** [comment]
Thanks @ahuang11, I do agree we should also support the OpenAI dictionary format so I just merged that PR. I'm now also understanding the point of the export better.

**Comment by MarcSkovMadsen** [comment]
Regarding the `message` format used for the `ChatBox.value`. We currently have two dimensions `user` and `value`. I think over time we will understand there is minimum one more dimension: `view`. The way we view the value.

Looking at the Gradio example. I can see that they assume the `ChatBox` keeps track of the conversation history in the form of the text strings. We also need that because the AI needs the context of the previous conversation in the form of the text string.

Looking at the Streamlit LangChain callback handler for each value instead of showing the value they show a *view* containing the thinking, actions and result of the AI.

With our `ChatBox` we can set the message value to complicated Panel components if we want to improve the *view* of the value.

The question to me is if the `ChatBox` what the ChatBox value should keep track of? The *raw*,  final result returned by the AI, the *raw* intermediate and final result returned by the AI or the way we view/ display the result from the AI.

What do you think @ahuang11 and @philippjfr ?

**Comment by leej3** [comment]
> I can imagine that each message could also have a timestamp, a unique ID, reactions, etc.

+1 for using dataclasses to support future expansion of message metadata.

> The raw, final result returned by the AI, the raw intermediate and final result returned by the AI or the way we view/ display the result from the AI.

I like the idea of a view. It seems like keeping track of the raw message would be best and make view configurable... though the latter user configuration might already be achievable by setting `default_message_callable`?

**Comment by ahuang11** [comment]
ChatBox will soon be deprecated and is superseded by ChatInterface.

ChatInterface.value accepts a list of strings, a list of dicts, e.g. `{"value": ..., "user": ..., "avatar": ...}` (value key must be provided), or a list of `ChatMessage(value=..., user=..., avatar=...)`.
