### ISSUE TITLE
Make ChatBox usage easy

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5277]
From experience the ChatBox is currently not as easy to use as it should be.

I believe there is functionality and documentation that should be added, changed or updated. This can be done in many ways.

I believe the best way to agree on solutions is to document how to easily use the ChatBox for the most common use cases.

Please add documentation and tests for the most common use cases. Improve the `ChatBox` based on these use cases.

## Use Cases

I think we can find use cases by looking at

- Streamlit
- Gradio
- Langchain
- Guidance

And similar frameworks.

**Comment by ahuang11** [comment]
ChatInterface is now merged; https://github.com/holoviz/panel/pull/5333
