### ISSUE TITLE
DatePicker in notebook, output cell does not resize to fit calendar

### ISSUE THREAD

**Issue by gwbischof** [holoviz/panel#528]
I am running the example notebook for DatePicker. When I click on selection box, the calendar opens but it is out of view. I think the position of the calendar could be better, and the output cell should resize to fit it.

![image](https://user-images.githubusercontent.com/11858848/61186552-dc893300-a634-11e9-935f-8c3ea9a39ca2.png)

**Comment by philippjfr** [comment]
This should probably be raised in bokeh.

**Comment by philippjfr** [comment]
I'm going to have to close this since it's not something we can address in Panel. Would be good to file this with bokeh (and mention that it also affects other widgets which expand).
