### ISSUE TITLE
`pn.widgets.EditableFloatSlider` format not always working

### ISSUE THREAD

**Issue by ambrustorok** [holoviz/panel#5286]
When creating an `EditableFloatSlider` and slowly dragging the slider, it does not always follow the defined formatting. 

This is a silent issue and does not produce any errors neither in python nor in javascript.

```python
import panel as pn
pn.extension()

pn.widgets.EditableFloatSlider(
            name='Threhshold', 
            start=0,
            end=5,
            step=0.01,
            value=3.5,
            format='1[.]0'
            )
```

![chrome-capture-2023-6-19](https://github.com/holoviz/panel/assets/31830274/03e1bb1b-3172-4fed-8f7b-37f3c68fe1ad)

**Comment by peytondmurray** [comment]
I'd like to chime in here and say that the formatter doesn't work on the `EditableFloatSlider` but it does work on the `EditableRangeSlider` using the same steps:

```python
import numpy as np
import panel as pn
from bokeh.models.formatters import NumeralTickFormatter

pn.extension()

pn.serve(
    pn.Row(
        pn.widgets.EditableFloatSlider(
            start=0,
            end=np.pi,
            step=0.111111,
            value=0.3,
            format=NumeralTickFormatter(format='0.00'),
        ),
        pn.widgets.EditableRangeSlider(
            start=0,
            end=np.pi,
            step=0.111111,
            value=(0.3, 0.4),
            format=NumeralTickFormatter(format='0.00'),
        )
    )
)
```

And here's the screenshot:

![image](https://github.com/holoviz/panel/assets/14017872/c524f11e-4346-4f7a-9acd-4789ec501559)
