### ISSUE TITLE
Core Concepts: Wrong gif for Editor workflow

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5325]
The Editor workflow gif shows a notebook based workflow.

![image](https://github.com/holoviz/panel/assets/42288570/478663e6-36a0-4b3f-8c9a-63133b18f91d)

https://panel.holoviz.org/getting_started/core_concepts.html

**Comment by philippjfr** [comment]
Just patched the live site and fixed it in #5327.
