### ISSUE TITLE
FloatPanel status not working

### ISSUE THREAD

**Issue by mayonnaisecolouredbenz7** [holoviz/panel#5364]
#### ALL software version info
panel==1.2.1
holoviews==1.16.0

#### Description of expected behavior and the observed behavior
Attempting to start a floatpanel minimized.  It looks like status parameter not working.  However it works in the documentation with the jslink.  Also tried it with the config parameter with jsPanel configuration to no avail.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
pn.extension('floatpanel')

float_panel=pn.layout.FloatPanel("Test panel","this is a test panel",status='minimized')


app = float_panel
app.servable(target='main')

```
#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/panel/assets/38597661/7ac4be5b-4155-483c-9639-6b4ccfe13e62)

**Comment by mayonnaisecolouredbenz7** [comment]
Trying to set the status with config does not work either, however other settings do work (_resizeit_ etc).  Interestingly the documentation on jsPanel's website is broken for _setstatus_. Not sure if related:
https://jspanel.de/#options/setstatus
![image](https://github.com/holoviz/panel/assets/38597661/06e65d77-4cf5-48d4-9913-bf1330453cfb)
Code snippet here:
```
        config={
            "resizeit": False,
            "setstatus": "minimized",
            "headerControls": {
                "maximize": "remove",
                "close": "remove",
                "smallify": "remove",
            },
```

**Comment by skemp117** [comment]
@philippjfr 

Thanks for all your hard work, sorry if I do not correctly know how to report this issue. I am having this same issue with setting the status except for setting it to "smallified". It makes the smallify button set to the correct state, but the float panel itself isn't smallified. All this does is make the user need to press the smallify button twice.

Panel version 1.3.8

`import panel as pn
pn.extension('floatpanel')

float_panel=pn.layout.FloatPanel("Test panel","this is a test panel",status='smallified')


app = float_panel
app.servable(target='main')`
