### ISSUE TITLE
Updating Accordions' titles / objects names

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5377]
```python
import panel as pn

pn.extension(sizing_mode="stretch_width")
accordion = pn.Accordion(
    pn.pane.Markdown("Contents", name="Name"),
)
accordion.objects[-1].name = "New Name"
```

This raises:
```python
TypeError: Constant parameter 'name' cannot be modified
```

This works; equivalent for one card:
```python
import panel as pn

pn.extension(sizing_mode="stretch_width")
card = pn.Card("contents", title="Name")
card.show()
card.title = "New Name"
```

**Comment by philippjfr** [comment]
The name is not what determines the Accordion title anyway, it's simply used to give it an initial title if None is provided. The correct way to update the accordion name is to assign it with a tuple:

```python
import panel as pn

pn.extension(sizing_mode="stretch_width")
md = pn.pane.Markdown("Contents", name="Name")
accordion = pn.Accordion(md)
accordion[-1] = ('New Name', md)
```

That said, this also does not currently work and needs a small fix.

**Comment by ahuang11** [comment]
Actually, I think this still might not be working:

```python
import panel as pn

pn.extension(sizing_mode="stretch_width")
accordion = pn.Accordion(
    pn.pane.Markdown("Contents", name="Name"),
)
accordion.objects[-1].title = "New Name"
accordion
```
<img width="465" alt="image" src="https://github.com/holoviz/panel/assets/15331990/8eb37185-486a-4406-9ccd-f509b9952329">

**Comment by ahuang11** [comment]
This works, but touches internal var.
```python
cards = list(accordion._panels.values())
cards[0].title = "new title"
```

**Comment by philippjfr** [comment]
As mentioned above, the API to override the title is as follows:

```python
import panel as pn

pn.extension(sizing_mode="stretch_width")
md = pn.pane.Markdown("Contents", name="Name")
accordion = pn.Accordion(md)
accordion[-1] = ('New Name', md)
```

This:

```python
accordion.objects[-1].title = "New Name"
```

simply sets the `title` attribute on the object in the last card, which in most cases will not have a title attribute at all.

**Comment by ahuang11** [comment]
I'm curious if it's possible to access the current name of the active card?
