### ISSUE TITLE
GridSpec using only colon should raise an error / set default

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#540]
I thought this:
```
import panel as pn

grid = pn.GridSpec()
grid[0:50, :] = pn.Spacer(background='red')
grid[50:100, :] = pn.Spacer(background='blue')
grid
```

would be equivalent to:

```
import panel as pn

grid = pn.GridSpec()
grid[0:50, 0:100] = pn.Spacer(background='red')
grid[50:100, 0:100] = pn.Spacer(background='blue')
grid
```

But the first one doesn't work
![image](https://user-images.githubusercontent.com/15331990/61547573-4036a600-aa11-11e9-8b43-8613ae168d58.png)

**Comment by philippjfr** [comment]
There should be a warning I think, the semantics of the colon is fill the maximum specified width. If there is no width at all that maximum width is zero.

An example that demonstrates the filling behavior:

```python
grid = pn.GridSpec()
grid[0:50, :100] = pn.Spacer(background='red')
grid[50:100, :] = pn.Spacer(background='blue')
grid
```

**Comment by philippjfr** [comment]
They appear to behave identically now:

![Screen Shot 2019-12-29 at 3 56 57 PM](https://user-images.githubusercontent.com/1550771/71558454-e45a5980-2a53-11ea-82bb-b24d8c253191.png)
