### ISSUE TITLE
Logout Button

### ISSUE THREAD

**Issue by simonaay** [holoviz/panel#5411]
I'm frustrated on how to develop a logout button. Basically, I tried to force an href "logout" to the pathname so I can sign out the user from the authenticated generic provider. Regardless of the provider's type, I can't seem to be able to logout even after learning  the LogoutHandler class found under auth.py file. 

What I'd like to have a button widget to be created and use its callback function to have the user click on it when they need to logout.

I found 2 alternatives where both of which are not helping me or are rather misused.:
- first: https://discourse.holoviz.org/t/forcing-oauth2-logout/4936
- second: https://discourse.holoviz.org/t/tips-guide-on-creating-a-simple-username-password-auth-for-panel-app/2582/3

 Would appreciate the help on this. 

As additional context, I have a dashboard to display using MaterialTemplate and I managed to configure its authentication and authorization steps but I am left with no logout button to develop. All suggestions did not work with me. It would be great if we can simplify the process of logging out with a button widget found either in header or sidebar. Thanks.

**Comment by philippjfr** [comment]
Can you provide some more detail, e.g. which auth providers you tried and the exact details on how you implemented the logout button? I just tried it with something like this and that seemed to work fine:

```
import panel as pn

b = pn.widgets.Button(name='Logout')

b.js_on_click(code="""window.location.href = '/logout'""")

b.servable()
```

**Comment by MarcSkovMadsen** [comment]
Hi @simonaay 

I've updated the `basic` docs in #5441 . Please take a look. Thanks.

**Comment by simonaay** [comment]
> Can you provide some more detail, e.g. which auth providers you tried and the exact details on how you implemented the logout button? I just tried it with something like this and that seemed to work fine:
> 
> ```
> import panel as pn
> 
> b = pn.widgets.Button(name='Logout')
> 
> b.js_on_click(code="""window.location.href = '/logout'""")
> 
> b.servable()
> ```

Hi, yes I happened to have tried this but it's not working. I'll get back to you.
