### ISSUE TITLE
Support line breaks for long column names in Tabulator

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5417]
Currently, I am doing this:
```python
        df.columns = [
            fill(str(col), width=40, break_long_words=False).replace("\n", "<br>")
            for col in df.columns
        ]
```

I wonder if there can be a param that does this automatically?

**Comment by philippjfr** [comment]
With https://github.com/holoviz/panel/pull/5421 you'll be able to set `title_formatters={<column>: 'textarea'}` which supports wrapping.
