### ISSUE TITLE
plotly figure not refreshed fully

### ISSUE THREAD

**Issue by peterlee18** [holoviz/panel#5456]
Windows 11
panel 1.2.1
plotly 5.16.1
Microsoft Edge - Version 116.0.1938.62 (Official build) (64-bit)

Have cut-down example of selecting different graphs. When you switch from "bar" to "kde", the kde plot retains the axes of the bar chart, rather than fully changing.

```
import numpy as np
import pandas as pd
import panel as pn
import plotly.figure_factory as ff
import plotly.express as px

data_bar = pd.DataFrame([1, 2, 3, 4], columns=["Count"], index=["A", "B", "C", "D"])
data_bar.index.name = "Category"
data_bar.reset_index(inplace=True)
data_cts = np.random.randn(1000)
group_labels = ["distplot"]


def select_graph(type):
    if type == "bar":
        plot = px.bar(x=data_bar["Category"], y=data_bar["Count"])
    else:
        plot = ff.create_distplot(
            [data_cts],
            group_labels,
            bin_size=0.5,
            show_hist=False,
            show_rug=False,
            histnorm="probability",
        )
    return plot


select_type = pn.widgets.Select(name="Select Type", options=["bar", "kde"])
select_type.value = "bar"

dash = pn.Column(select_type, pn.bind(select_graph, select_type))
pn.serve(dash)

```

The second figure is the result of the bug. The third figure is what the graph should look like (got by setting "kde" as default instead of "bar"). However, when you switch to "bar" and then back to "kde" you get the second figure again.

![image](https://github.com/holoviz/panel/assets/99048186/cdd6abeb-10c2-4c43-987f-374bb1604ce6)

![image](https://github.com/holoviz/panel/assets/99048186/28f93ffa-9a67-449f-8ab5-8af241a49cac)

![image](https://github.com/holoviz/panel/assets/99048186/da78e028-c378-41c6-9637-773a9f809149)

**Comment by peterlee18** [comment]
Fantastic. Thanks very much. 

 

I’m finding Panel more and more powerful. Its relatively easy to build some quite complex apps.

**Comment by philippjfr** [comment]
Thanks for the kind words and thanks for the detailed bug reports!
