### ISSUE TITLE
CompositeWidget does not inject stylesheets above it

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5472]
I've tried to do:
```python
        self._composite.css_classes = ["chat-interface"]
        self._composite.stylesheets = self._stylesheets
```

But I don't see any stylesheets above this line:
<img width="483" alt="image" src="https://github.com/holoviz/panel/assets/15331990/e07c9495-2a90-4659-9c2d-bcf3e15eeee0">

I had to manually set styles.
```python
        self._composite.styles = {"border": "1px solid var(--panel-border-color, #e1e1e1)"}
```

**Comment by philippjfr** [comment]
The `_composite` mirrors the layout and style properties on self, so you should simply set the defaults on the CompositeWidget baseclass to achieve this.
