### ISSUE TITLE
ipywidgets do not work inside templates

### ISSUE THREAD

**Issue by peterlee18** [holoviz/panel#5485]
Windows 11
panel 1.2.2
ipywidgets 8.1.0
ipywidgets_bokeh 1.5.0
Microsoft Edge - Version 116.0.1938.62 (Official build) (64-bit)

ipywidgets work fine in basic components  (simple_app) but not inside a template (app_screen). Also tried putting inside the main area and that doesn't work either.

```
import panel as pn
import ipywidgets as ipw

pn.extension("ipywidgets")

date = ipw.DatePicker(description="Date")
slider = ipw.FloatSlider(description="Float")

simple_app = pn.Column(
    pn.pane.Markdown("### Enter Date"),
    date,
    pn.pane.Markdown("### Enter Number"),
    slider,
)
simple_app.show()

app_screen = pn.template.BootstrapTemplate(
    title="Test Template",
    sidebar_width=350,
    sidebar=[
        pn.pane.Markdown("### Enter Date"),
        date,
        pn.pane.Markdown("### Enter Number"),
        slider,
    ],
)

app_screen.main.append(pn.Column("## TBA"))
app_screen.show()

```

The simple app gives:
![image](https://github.com/holoviz/panel/assets/99048186/67962b9e-0751-4d01-a47e-b061d97f175c)

app_screen gives:

![image](https://github.com/holoviz/panel/assets/99048186/627eb9d9-bd87-4183-bba6-db72b87721aa)

**Comment by MarcSkovMadsen** [comment]
Can you share a screenshot of the browser console? It propably contains some logs with errors.

**Comment by peterlee18** [comment]
![image](https://github.com/holoviz/panel/assets/99048186/9b700561-1e42-414c-8ff1-a83f9bbb2ccc)
![image](https://github.com/holoviz/panel/assets/99048186/0e8ed233-44d0-42e3-b0f1-0f6505abbccd)

**Comment by peterlee18** [comment]
I actually discovered that the Vanilla template works fine so its seems that only certain templates are affected. I haven't done a systematic check of all the templates.
