### ISSUE TITLE
ReactiveHTML: Cannot insert value containing tilde using Jinja2

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5499]
I'm on the current `main` branch of Panel trying to better explain ReactiveHTML jinja templating. While exploring good examples I see the below exception raised

```python
import panel as pn

pn.extension()

class CustomComponent(pn.reactive.ReactiveHTML):
    """I'm a custom component with a `color` parameter"""
    
    _template = """
<p>{{ __doc__ }}</p>
"""

CustomComponent(width=500).servable()
```

![image](https://github.com/holoviz/panel/assets/42288570/bffb98cd-270c-47fa-9486-ce74a2b1bcaa)

**Comment by philippjfr** [comment]
Duplicate of https://github.com/holoviz/panel/issues/5500
