### ISSUE TITLE
state.add_periodic_callback not working in 1.2.2

### ISSUE THREAD

**Issue by sylvaint** [holoviz/panel#5505]
#### Software:
panel 1.2.2
bokeh 3.2.2
python 3.10.10
MAC OS Ventura 3.5.2

#### Description of expected behavior and the observed behavior
pn.state.add_periodic_callback not firing
Works fine when downgrading to panel 1.2.1
In code below text updates with 1.2.1 and does not with 1.2.2

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import time
pn.extension()

text = pn.widgets.StaticText(value="test")

def test():
    print("halo")
    text.value = "halo"
    time.sleep(1)
    text.value = "halo2"


pn.state.add_periodic_callback(test, period=2000)

pn.Row(text).servable()
```

**Comment by Hoxbro** [comment]
Thank for the report. The problem you are describing has been fixed in #5490. 

I hope we can have a new Panel release by the end of today.
