### ISSUE TITLE
node.js v6.10.0 or higher is needed

### ISSUE THREAD

**Issue by banesullivan** [holoviz/panel#551]
Cross-posting from https://github.com/pyvista/pyvista/issues/322. 

The user has the latest version of panel and node.js. The following causes the error:

```py
import panel
panel.extension('vtk')
```

### Errors:

<img width="1017" alt="61985267-4b637600-afbd-11e9-9a1c-ec1509ca1132" src="https://user-images.githubusercontent.com/22067021/61997784-2c6bef00-b064-11e9-962e-10019e9516ce.png">
<img width="983" alt="61985271-4f8f9380-afbd-11e9-8556-67c22f84d644" src="https://user-images.githubusercontent.com/22067021/61997786-2e35b280-b064-11e9-8704-663926ff594a.png">

### Software versions:

```
--------------------------------------------------------------------------------
  Date: Fri Jul 26 21:27:47 2019 PDT

            Darwin : OS
                 8 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
            Python : Environment

  Python 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1
  (tags/RELEASE_401/final)]

  Could not import : pyvista
  Could not import : vtk
            1.17.0 : numpy
             2.5.0 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             7.6.1 : IPython
             7.5.0 : ipywidgets
             0.6.0 : panel
--------------------------------------------------------------------------------
```

latest version of nodejs installed using `conda install nodejs`. 

Name |                   Version|                   Build  Channel
---|---|---
nodejs    |                10.13.0     |         h0a44026_0

**Comment by philippjfr** [comment]
Hmm, that's quite scary and may be down to the fact that we recently deleted a specific version of nodejs from the pyviz channel. That all being said all the latest versions of panel should come with panel precompiled so I'd need to know exactly where they installed panel from.

**Comment by banesullivan** [comment]
@pinshuai, would you be able to help with more information?

**Comment by pinshuai** [comment]
@philippjfr I installed panel using `pip install panel`.  Here is the info from `conda list panel`:

```
# Name                    Version                   Build  Channel
panel                     0.6.0                    pypi_0    pypi
```

**Comment by philippjfr** [comment]
Okay, the build infrastructure has now changed entirely so I don't think this is still an issue. If it comes up again please reopen.
