### ISSUE TITLE
KeyError 'data' on table edit

### ISSUE THREAD

**Issue by nmillerPCMC** [holoviz/panel#5513]
Just trying to get the Tabulator example posted on the main webpage to work.  Editing the cells throws a KeyError exception.
https://panel.holoviz.org/reference/widgets/Tabulator.html

#### ALL software version info
panel v1.2.2
ipywidgets v8.1.1
bokeh v3.2.2
jupyter_bokeh v3..0.7
Windows 10
python 3.11
working within VScode v1.82.2 with Jupyter Extension v2023.8.1002501831
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

#### Description of expected behavior and the observed behavior
should be able to edit without fatal error
#### Complete, minimal, self-contained example code that reproduces the issue

```
#Holoviz panel
import datetime as dt
import numpy as np
import pandas as pd
import panel as pn

np.random.seed(7)
pn.extension('tabulator')

df_widget = pn.widgets.Tabulator(df)
df = pd.DataFrame({
    'int': [1, 2, 3],
    'float': [3.14, 6.28, 9.42],
    'str': ['A', 'B', 'C'],
    'bool': [True, False, True],
    'date': [dt.date(2019, 1, 1), dt.date(2020, 1, 1), dt.date(2020, 1, 10)],
    'datetime': [dt.datetime(2019, 1, 1, 10), dt.datetime(2020, 1, 1, 12), dt.datetime(2020, 1, 10, 13)]
}, index=[1, 2, 3])

df_widget = pn.widgets.Tabulator(df, buttons={'Print': "<i class='fa fa-print'></i>"})
display(df_widget)

```

#### Stack traceback and/or browser JavaScript console output
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File [c:\Users\NMiller\AppData\Local\pypoetry\Cache\virtualenvs\poetry-A7ZAAhQy-py3.11\Lib\site-packages\jupyter_bokeh\widgets.py:162](file:///C:/Users/NMiller/AppData/Local/pypoetry/Cache/virtualenvs/poetry-A7ZAAhQy-py3.11/Lib/site-packages/jupyter_bokeh/widgets.py:162), in BokehModel._sync_model(self, _model, content, _buffers)
    160 elif kind == "ColumnsPatched":
    161     model = content["model"]
--> 162     patches = content["data"]
    164     assert isinstance(model, ColumnDataSource)
    165     model.patch(patches, setter=setter)

KeyError: 'data'

**Comment by Hoxbro** [comment]
Hi, can you check what versions of Bokeh and ipywidgets_bokeh you have installed?

**Comment by nmillerPCMC** [comment]
bokeh version is 3.2.2

I do not have ipywidgets_bokeh listed as installed.  Is it perhaps included within ipywidgetsv8.1.0?  or do I need to install it directly?

**Comment by Hoxbro** [comment]
Try installing it; be sure you get the latest version 1.5.

**Comment by nmillerPCMC** [comment]
installed 1.5.  Same issue.

**Comment by Hoxbro** [comment]
mmh, I don't have any clear ideas then, it works on my computer. 

 Can you send me your full package list with `pip list` or `conda env export`?

**Comment by sylvaint** [comment]
Getting same error.

**Comment by earshinov** [comment]
Same problem. Already tried experimenting with different versions of jupyter-boken, bokeh, ipywidgets, panel etc. Added 

```diff
 elif kind == "ColumnsPatched":
+    import sys
+    print(content, file=sys.stderr)
     model = content["model"]
     patches = content["data"]
 
     assert isinstance(model, ColumnDataSource)
     model.patch(patches, setter=setter)
```

to `jupyter_bokeh/widgets.py` directly inside my venv and got this:

```
{'kind': 'ColumnsPatched', 'attr': 'data', 'model': {'id': '0e79a6be-6a5d-46f3-a5ff-00145578fdab'}, 'patches': {'type': 'map', 'entries': [['name', [[7, 'Introduction to Linguistics (update)']]]]}}
```

I have no idea when it comes from, but looks like it isn't the format `jupyter_boken` expects.

I am running this on Windows inside VS Code (with its built-in support for Jupyter notebooks).

**Comment by maximlt** [comment]
I've been able to reproduce and opened a tentative PR on `jupyter_bokeh` to fix the reported bug https://github.com/bokeh/jupyter_bokeh/pull/206.
