### ISSUE TITLE
DEV Home page broken

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5533]
I've been building the `dev` homepage to review the ´ReactiveHTML` PR. But the front page is now broken.

https://holoviz-dev.github.io/panel/

![image](https://github.com/holoviz/panel/assets/42288570/a076ccde-a088-40c0-bfe2-3a9e8191c6c2)

**Comment by philippjfr** [comment]
I think you need to rebase main before rebuilding the next time, the current build is fine.

**Comment by MarcSkovMadsen** [comment]
Its not me deploying. Someone deployed and its broken.

https://www.linkedin.com/posts/sunscrapers_dive-into-the-world-of-data-visualization-activity-7110941967714258944-ffnK?utm_source=share&utm_medium=member_ios

**Comment by Hoxbro** [comment]
This will be fixed in the next deployment as an fix in HoloViews was needed https://github.com/holoviz/holoviews/pull/5906 

(You also used the wrong link, I think...)

**Comment by philippjfr** [comment]
@MarcSkovMadsen for future reference, errors in dev builds should not be assigned a milestone.

**Comment by MarcSkovMadsen** [comment]
How do I Mark them in a way such that they dont get overlooked before next release then?

**Comment by philippjfr** [comment]
Good point, let's create a label for them then, something like `task`. That said, assigning them to next will not get me to look at them before a release either, 1.3.0 is the next release. `next` should only be created if it is unclear what the next release will be.

**Comment by philippjfr** [comment]
Actually, at least in the current setup `next` is the release that is next after the currently scheduled release.

**Comment by MarcSkovMadsen** [comment]
I thought `next` was currently the same as 1.3.0?
