### ISSUE TITLE
Investigate capturing the IPython Output with panel.

### ISSUE THREAD

**Issue by tonyfast** [holoviz/panel#559]
**Is your feature request related to a problem? Please describe.**
Panel cannot easy capture IPython output objects, like `ipywidgets.Output`.

**Describe the solution you'd like**
	
	with panel.Output() as output: display(holoviews_plot)

**Additional context**
Phillip requested this issue.

**Comment by philippjfr** [comment]
Since no one has expressed major interest in this issue I'll close, can always reopen if someone expresses a strong need.
