### ISSUE TITLE
Panel convert | wrong bokeh dependency

### ISSUE THREAD

**Issue by jbbarre** [holoviz/panel#5596]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

conda 23.7.4

```
Name                    Version                   Build  Channel              
bokeh                     3.2.1                      py311h92b7b1e_0  
panel                      1.2.3                      py_0    pyviz 
python                    3.11.4                    h955ad1f_0  
```

#### Description of expected behavior and the observed behavior

Serving the panel app after `panel convert `leads to an error related to bokeh version. In the code :`https://cdn.holoviz.org/panel/1.2.3/dist/wheels/bokeh-3.2.1-py3-none-any.whl.` Expected : `https://cdn.holoviz.org/panel/1.2.3/dist/wheels/bokeh-3.2.2-py3-none-any.whl`
as @Hoxbro suggested me to test. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
conda install panel hvplot -c pyviz
```
app.py contains the standard [example](https://discourse.holoviz.org/t/cdn-holoviz-org/6156) :

```
import panel as pn

from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

pn.extension(sizing_mode="stretch_width", template="fast")
pn.state.template.param.update(site="Panel in the Browser", title="XGBoost Example")

iris_df = load_iris(as_frame=True)

trees = pn.widgets.IntSlider(start=2, end=30, name="Number of trees")

def pipeline(trees):
    model = XGBClassifier(max_depth=2, n_estimators=trees)
    model.fit(iris_df.data, iris_df.target)
    accuracy = round(accuracy_score(iris_df.target, model.predict(iris_df.data)) * 100, 1)
    return pn.indicators.Number(
        name="Test score",
        value=accuracy,
        format="{value}%",
        colors=[(97.5, "red"), (99.0, "orange"), (100, "green")],
    )

pn.Column(
    "Simple example of training an XGBoost classification model on the small Iris dataset.",
    iris_df.data.head(),
    "Move the slider below to change the number of training rounds for the XGBoost classifier. The training accuracy score will adjust accordingly.",
    trees,
    pn.bind(pipeline, trees),
).servable()

```
Web page production
```
panel convert app.py --to pyodide --out docs/app
```
and open the app.html

Then, a wheel is indefintely turning. The console shows some errors (see below)

#### Stack traceback and/or browser JavaScript console output

Console ouput in chrome :

```
Failed to load resource: net::ERR_INVALID_URL
bokeh-3.2.1.min.js:183 [bokeh] setting log level to: 'info'
app.html:218 Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///home/jbbarre/docs/app/app.js' cannot be accessed from origin 'null'.
    at file:///home/jbbarre/docs/app/app.html:218:29
bokeh-3.2.1.min.js:165 [bokeh] document idle at 28 ms
﻿
```
To make it work, I manually changed the bokhe dependency to `bokeh-3.2.2-py3-none-any.whl` in the html file:
```
      await pyodide.runPythonAsync(`
        import micropip
        await micropip.install(['https://cdn.holoviz.org/panel/1.2.3/dist/wheels/bokeh-3.2.2-py3-none-any.whl', 'https://cdn.holoviz.org/panel/1.2.3/dist/wheels/panel-1.2.3-py3-none-any.whl', 'pyodide-http==0.2.1', 'scikit-learn', 'xgboost', 'pandas']);
      `);
```
#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this

**Comment by philippjfr** [comment]
Thanks @jbbarre, this is quite critical. I'm not 100% sure how best to deal with this. We will either have to hardcode the Bokeh version per release meaning that the pyodide app may not load the same Bokeh version that you have installed locally OR we should simply upload the Bokeh wheels separately from the Panel wheels.
