### ISSUE TITLE
panel-gallery certificate not valid in recent Chrome

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#5597]
When I go to https://panel.holoviz.org/ and click the first example it takes me to here:

https://panel-gallery.pyviz.demo.anaconda.com/portfolio_analyzer

It works OK for me on Safari and Firefox, but with recent Chrome Version 117.0.5938.92 (Official Build) (arm64) I get 
an error NET::ERR_CERT_AUTHORITY_INVALID saying the connection isn't private and certificate isn't valid.

<img width="1345" alt="Screenshot 2023-10-09 at 13 25 50" src="https://github.com/holoviz/panel/assets/852409/954694a5-1dfd-4d52-bc76-1f5b4bbedb1f">

**Comment by Hoxbro** [comment]
I can't recreate it on Mac with `Version 117.0.5938.149 (Official Build) (arm64)`

Can you try to see if it is happening in an incognito window?

**Comment by philippjfr** [comment]
Indeed, cannot reproduce myself.

**Comment by cdeil** [comment]
I still see it even if updating to very latest Chrome Version 118.0.5993.70 (Official Build) (arm64)

I see the same error in an incognito window.

I'm not sure what the problem is. Maybe the certificate hierarchy isn't as it should be?

<img width="1624" alt="Screenshot 2023-10-11 at 13 37 30" src="https://github.com/holoviz/panel/assets/852409/2bd733c6-3fcf-4244-9799-1f20e00d9d2f">

**Comment by cdeil** [comment]
It now also works for me. Maybe there was something weird with my network. Closing this ticket. Sorry for the noise.

<img width="1029" alt="Screenshot 2023-10-11 at 16 30 19" src="https://github.com/holoviz/panel/assets/852409/ede89cd0-82c2-4e4a-82cd-249933b273ec">
