### ISSUE TITLE
Feature Request: Accordion widget box layout

### ISSUE THREAD

**Issue by kcpevey** [holoviz/panel#561]
**Is your feature request related to a problem? Please describe.**
I have a series of complex dashboards and the existing Layout options in Panel are unable to be adapted to my specific issues due to the 1) the volume of information and 2) the computational time of rendering the complex layouts. 

**Describe the solution you'd like**
I would like to have an additional layout option of accordion widget boxes that can be easily minimized. Additionally, lazy rendering of Tabs will help with initial layout building time. 

**Describe alternatives you've considered**
My current solution of a plethora of nested tabs is seriously time consuming.

**Comment by philippjfr** [comment]
`Accordion` has now been added.
