### ISSUE TITLE
Enable setting the `authorize_callback` globally when serving multiple apps.

### ISSUE THREAD

**Issue by joshes** [holoviz/panel#5611]
#### Is your feature request related to a problem? Please describe.
I am serving multiple Panel apps from a single server and would like to enforce the same `authorize_callback` on all served apps and configure this globally to minimize configuration errors per app.

#### Describe the solution you'd like
Ideally something like:
```shell
panel serve --help
...

--authorize-callback    Path to a authorization module that exposes an authorize function

...
```

```python
## authorizer.py
def authorize(user_info, request_path):
    pass
```

Example usage:
```shell
panel serve --authorize-callback /path/to/authorizer.py /path/to/apps/*.py
```

#### Describe alternatives you've considered
By reading the docs, it would seem naively that one could `os.environ["AUTHORIZE_CALLBACK"] = authorizer.authorize` which does not work.

I've tried the following ahead of starting the server with no luck, note that I'm starting the server from Python which may have some bearing on the possible solutions.

```python
import panel as pn
from panel.command import main

import authorizer

# dynamically build args to `panel serve`
sys.argv[1:] = build_command() 

# Expects a string, so startup fails of course
os.environ['AUTHORIZE_CALLBACK'] = authorizer.authorize

# The following does not work either
# pn.config.authorize_callback = authorizer.authorize

# Start panel
main()
```

#### Additional context
Happy to find any workarounds and to submit a PR if an approach is found.

**Comment by philippjfr** [comment]
You should be able to set it up inside a `--setup` script.

**Comment by joshes** [comment]
Ah, I didn't think of that! That seems to work fine, thanks for the quick response.
Will close this out.
