### ISSUE TITLE
Support webp format in pn.pane.Image

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5612]
I want to do:
```python
import panel as pn
pn.extension()
pn.pane.Image(https://mistral.ai/images/logo_hubc88c4ece131b91c7cb753f40e9e1cc5_2589_256x0_resize_q97_h2_lanczos_3.webp)
```

Also this works with `pn.pane.PNG` but not `pn.pane.Image`:
MISTRAL_LOGO = "https://media.licdn.com/dms/image/D4E0BAQErOXd640ewXQ/company-logo_200_200/0/1695914855060?e=2147483647&v=beta&t=eVv-NeP8WEtVx2bfsBj8SXQ45p_hwj0wh8s0pxOnPGc"

**Comment by philippjfr** [comment]
That would be great. Basically you'd just copy the implementation of one of the existing Image types (e.g. PNG) and then rewrite the implementation to support webp.

**Comment by vaniisgh** [comment]
thanks will check it out and revert.

**Comment by vaniisgh** [comment]
just a question regarding the tests, 

similar to these:

````
JPG_FILE = 'https://assets.holoviz.org/panel/samples/jpg_sample.jpg'
JPEG_FILE = 'https://assets.holoviz.org/panel/samples/jpeg_sample.jpeg'
PNG_FILE = 'https://assets.holoviz.org/panel/samples/png_sample.png'
SVG_FILE = 'https://assets.holoviz.org/panel/samples/svg_sample.svg'
```

we would need a webp file too ?
