### ISSUE TITLE
Dynamic Tabs are blocked by calculations

### ISSUE THREAD

**Issue by mayonnaisecolouredbenz7** [holoviz/panel#5616]
#### ALL software version info
panel = 1.2.3

#### Description of expected behavior and the observed behavior
When setting dynamics = True in Tabs,  rendering of those tabs are blocked by any other calculations/running code

#### Complete, minimal, self-contained example code that reproduces the issue

```import panel as pn
import param
import time
pn.extension()

class Example(param.Parameterized):
    action = param.Event()
    
    @param.depends('action')
    def run(self):
        if not self.action:
            yield "Click the button"
        yield "Running calcs"
        time.sleep(10)
        yield 'Done calcs'
example = Example()
    
pn.Tabs(('Tab1',pn.Column('Stuff in Tab 1')),('Tab2',pn.Column(example.param.action,example.run)),dynamic=True)
```

#### Screenshots or screencasts of the bug in action
When dynamic = False, it is possible to switch between tabs freely.  When dynamic = True, Tab1 will not render until run function finishes. 
![image](https://github.com/holoviz/panel/assets/38597661/ce36d56d-75d2-461d-972c-f3c56e82c6ea)

Not sure if this is classified as a a *bug*.  But in my particular use case having dynamics tabs is a great feature in a server context as it improves the responsiveness of the app as a whole.  But then the blocking nature of my calculations presents a problem.

**Comment by mayonnaisecolouredbenz7** [comment]
Yep makes sense what you are saying. 

```
class Example(param.Parameterized):
    action = param.Event()
    
    @param.depends("action")
    async def run(self):
        if not self.action:
            yield "Click the button"
            return
        for i in range(10):
            await asyncio.sleep(0.01)
            time.sleep(1)
            yield "Running calculations"
        yield "Done calcs"
example = Example()
    
pn.Tabs(('Tab1',pn.Column('Stuff in Tab 1')),('Tab2',pn.Column(example.param.action,example.run)),dynamic=True)
```
When running this I get the following:

> TypeError: object async_generator can't be used in 'await' expression


Further to that.  What is interesting is that when the function is async (regardless of the decorator being there), `self.action` always returns False even on button click.  When the function is not async, `self.action` returns True on button click as expected.

**Comment by rsdenijs** [comment]
It seems `param` does not play well with async generators. Fortunately `panel` does.  The crux is that you can't just `await` an async generator, and that `await` happens inside param, so you can't do much about it. This works though


```
import param
import panel as pn
import asyncio
import time


class Example(param.Parameterized):
    clicked = param.Boolean(default=False)

    def __panel__(self):
        button = pn.widgets.Button(name="click me")
        button.on_click(lambda _: setattr(button, "visible", False))

        return pn.Column(
            button, pn.widgets.StaticText(value=pn.bind(self.calculate, button))
        )

    async def calculate(self, clicked):
        if clicked:
            for i in range(10):
                await asyncio.sleep(.01)
                yield f"Running calculations ({i+1}/10)"
                time.sleep(1)
            yield "Done calcs"

pn.Column(
    pn.Tabs(
        ("Tab1", "Hello!"),
        ("Tab2", Example()),
        dynamic=True,
    )
).servable()
```

There may be a away to get it to work with a param.Event or a param.Action but fundamentally this should do it.

**Comment by mayonnaisecolouredbenz7** [comment]
@rsdenijs thanks so much for that example!  Was a massive help for my application.

**Comment by rsdenijs** [comment]
No problem. 

@MarcSkovMadsen just fyi in case this fits any of the tutorials you've been working on. Although simple, imo this example shows quite a nice combination of providing updates while performing small blocking operations. Specially because it is combining multiple intermediate concepts like async, yielding values and the reactive api. Of course, an even nicer version would include full multiprocessing so one could run heavy computations in the background.
