### ISSUE TITLE
Card: content set with `max_height` affects the surrounding layout

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#5618]
The `max_height` of the card content affects the surrounding layout when the Card is collapsed.

```python
import panel as pn

pn.extension()

obj = pn.pane.HTML(
    'text<br>'*50, max_height=500, sizing_mode='stretch_both',
    styles={'background-color': 'grey', 'overflow': 'auto'}
)
pn.Column(
    pn.Card(obj, title='Title', collapsed=True),
    'Why am I down there? :D',
).servable()
```

<img width="432" alt="image" src="https://github.com/holoviz/panel/assets/35924738/bd7c5bac-e5ae-4da5-aa32-7f282f812838">

I noticed this issue while investigation another issue, because it affects Cards it affects Accordions too:

```python
import panel as pn

pn.extension()

objs = [
    pn.pane.HTML(
        'text<br>'*50, max_height=500, sizing_mode='stretch_both',
        styles={'background-color': 'grey', 'overflow': 'auto'}
    )
    for i in range(3)
]
acc = pn.Accordion(*objs)
acc.servable()
```

<img width="503" alt="image" src="https://github.com/holoviz/panel/assets/35924738/200d3c31-26a2-4a52-8112-805e7332e251">

**Comment by philippjfr** [comment]
Hmm, the problem here is that the Card inherits the sizing_mode from the `HTML`, which means it "correctly" stretches to fill the space. I'm honestly not sure what the right fix is. I'm guessing internally a `collapsed` Card would to set `sizing_mode=None` and then restore the value after the fact.
