### ISSUE TITLE
Add widgets multiple times to a template

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#5621]
I was surprised that widgets can only be added to templates once.

Example:
```python
import panel as pn

pn.extension(design="material")
button = pn.widgets.Button(name="Click me", button_type="primary")
template = pn.template.MaterialTemplate()
template.sidebar.append(button)
template.main.append(button)
template.servable()
```

will only show the button once, not twice, even though I added it to the main and sidebar area.
(any other template, or adding it twice e.g. to the main area also it only shows up once)

On the other hand it can be added to a column any number of times, this will show the button 3 times:
```
col = pn.Column(button, button, button)
```

Is this intended behaviour or a bug?

In the docs at https://panel.holoviz.org/how_to/templates/template_arrange.html it currently reads "... templates can be populated as desired ..."

**Comment by maximlt** [comment]
I can reproduce and this looks like a bug to me.

**Comment by philippjfr** [comment]
This is caused by `_render_items` being a dictionary indexed by the id of the component.
