### ISSUE TITLE
Move Chat Components to their own namespace

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5625]
I think the chat components should be moved to their own namespace `pn.chat` for the reasons below.

- They are not all widgets. For example they don't all have a parameter `value`.
- To keep it simple. The `ChatInterface` can be used almost stand alone for users who does not know a lot about Param and Panel.
- To give it focus. The chat components would get their own section in the Component Gallery.
- To enable chat components to grow. I would expect more components to be added later. For example the `EnvironmentWidget` that makes it easy to use a combination of environment variables and user input for api keys etc.
- To make it easier to carve out. Maybe one day this is too big or specialized for Panel and should be in its own `panel-chat` package.

**Comment by ahuang11** [comment]
> To enable chat components to grow. I would expect more components to be added later. For example the EnvironmentWidget

I don't think is specific to Chat though.

**Comment by philippjfr** [comment]
+1 on moving them into their own namespace. These aren't widgets as Panel defines them even if they have a `value`. Widgets are inputs or controls, while these components are used for bi-directional communication and rendering of rich outputs.

**Comment by MarcSkovMadsen** [comment]
For the `ChatEntry` might have a `.value` parameter. But the `value` is not something the user can input. Instead its actually displayed as an output.

**Comment by philippjfr** [comment]
Yep, indeed. I do wonder if it should even subclass `CompositeWidget` but that's not too important.

**Comment by ahuang11** [comment]
Will add this before release.
