### ISSUE TITLE
Dynamic update of pn.Column does not work when used as main of a template

### ISSUE THREAD

**Issue by ncvangilse** [holoviz/panel#5626]
I have designed a singleton progressbar container that allows for any progress bar in my app and sub components to render in the same container widget. It works fine when not a part of a template, but when a template is used, the container never renders. I need the dynamic behavior of the container as it is not known at compile time how many progress bars will be attached to the container.

Here is a minimal example that illustrates the issue:
(Panel version 1.2.3)
```
from time import sleep

import panel as pn

def run(*_):
    progress = pn.indicators.Progress(value=0, max=10)
    container.append(progress)
    for i in range(10):
        sleep(0.3)
        progress.value += 1
    container.pop(-1)

button = pn.widgets.Button(name='Run')
button.on_click(run)
container = pn.Column(button)

template=pn.template.FastListTemplate(main = container)

#Uncomment to activate the failure:
# template.show()
container.show()
```

**Comment by ncvangilse** [comment]
@MarcSkovMadsen, I was hoping you could chip in here? I understand that the template's main is fixed once rendered, but I thought that as long as I am changing the container in-place, it should be ok?

**Comment by rsdenijs** [comment]
You may be missing pn.extension()

**Comment by ncvangilse** [comment]
Adding `pn.extension()` has no effect

**Comment by maximlt** [comment]
Hi @ncvangilse , can you try wrapping the container in a list when passing it to the template?

```
template=pn.template.FastListTemplate(main=[container])
```

**Comment by ncvangilse** [comment]
@maximlt, wrapping it in a list has no effect either

**Comment by philippjfr** [comment]
Yeah, we should simply guard `main` from accepting layout types. They are currently unpacked into a list which means you can't then update them.

**Comment by ncvangilse** [comment]
@maximlt, Thank you very much for your answer. It worked :-)

@philippjfr , yes I think the current (undocumented?) behavior can cause confusion.


My actual usecase was a little more complicated due to my use of singleton progress bar container. 

My problems were a mixture of poor implementation of the singleton (which I have now also fixed), using tabs and then the issue solved in this thread.
But I really liked the idea of being able to place a `GlobalProgressBarContainer` anywhere in the app where I would like to see progress and then let instances of my `AutoProgressBar`s scattered around in lengthy processes attach themselves to these containers via the singleton with minimum boilerplate/managing.  Now it all works :-)

Thank you all
