### ISSUE TITLE
The ChatInterface should clear any widget after "send"

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5694]
Currently the `ChatInterface` clears the `TextInput.value` when it is "sent". This makes it easy to type/ input the next value.

I don't see why this is only done for the `TextInput`? Should also apply to other widgets like `TextAreaInput`, `CodeEditor` and `FileInput`. But currently it does not as you can see from the screenshot below from the reference notebook. This makes it more cumbersome to use the `ChatInterface`.

![image](https://github.com/holoviz/panel/assets/42288570/6656a3b8-bd57-42e3-9df6-e1f42c84b37d)

**Comment by ahuang11** [comment]
There's `reset_on_send` param. I think I did this so that `FileInput` doesn't clear to access it's value, but perhaps with the [PDF assistant](https://github.com/holoviz-topics/panel-chat-examples/blob/main/docs/examples/langchain/langchain_pdf_assistant.py) refactored, it's no longer necessary.
