### ISSUE TITLE
PanelCallbackHandler design principle

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5707]
yesterday I changed the PanelCallBackHandler handler to also output the final response from the agent.

![image](https://github.com/holoviz/panel/assets/42288570/444a258c-71e4-4158-a55a-1225ecf1db3a)

The change is marked below.

![image](https://github.com/holoviz/panel/assets/42288570/f8d86452-85f8-4a39-a1d8-b7d34c3dd375)

I can see that Streamlits Callback handler does not write the 'output'. The user/ developer have to manually do this. 

![image](https://github.com/holoviz/panel/assets/42288570/d79028f8-e30e-4e44-a814-b2e063bee409)

I'm thinking that maybe it was a mistake by me to change this. What do you think @ahuang11 ?

**Comment by ahuang11** [comment]
Right if users type return / yield in the callback, it would duplicate the results.

At the same time, all of the streaming from Langchain does not require any yield/return so if users use return, its also semi inconsistent. 

One last point to consider is the tool usually reports the final answer.

**Comment by MarcSkovMadsen** [comment]
I'm more and more convinced it was a mistake. The CallbackHandler should be seen as something you attach to debug and can remove again. You should not change what else you do.

The code should be

```python
pn_cb = pn.chat.langchain.PanelCallbackHandler(instance=instance)
response = state.pandas_df_agent.run(contents, callbacks=[pn_cb])
return response
```

not

```python
pn_cb = pn.chat.langchain.PanelCallbackHandler(instance=instance)
response = state.pandas_df_agent.run(contents, callbacks=[pn_cb])
```

I will make a PR to revert including updating the example notebooks. Then we can discuss from there.
