### ISSUE TITLE
Fast css not applied initially when using ChatInterface

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5709]
I'm on the current `main` branch of Panel and trying to contribute a LangChain Panel DataFrame agent.

What I experience is that the fast css is not applied initially to the Tab component below.

```python
import panel as pn
import pandas as pd

pn.extension("perspective")

chat_interface = pn.chat.ChatInterface(
    widgets=[pn.widgets.FileInput(name="Upload"), pn.widgets.TextInput(name="Message")],
    renderers=pn.pane.Perspective,
    callback_exception="verbose",
)
    
chat_interface.send("I'm your LangChain Pandas Agent!", user="Pandas Agent", avatar="🐼", respond=False)

pn.template.FastListTemplate(
    main=[chat_interface]
).servable()
```

When opening the app it looks like

![image](https://github.com/holoviz/panel/assets/42288570/3f1aba5d-12c0-4e95-b2b0-916b672979bd)

What you see is the default Bokeh css at the bottom.

If I click the `Message` tab, the fast css gets applied.

![image](https://github.com/holoviz/panel/assets/42288570/a52855ee-fe40-4eb9-8057-75cf6f2c8434)

**Comment by ahuang11** [comment]
This is a strange bug, but I don't think this is 100% critical to the release of v1.3.0.
