### ISSUE TITLE
ChatInterface: Expose Actions

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5711]
I'm on the `main` branch of Panel working on contributing a LangChain Pandas DataFrame Agent. https://github.com/holoviz-topics/panel-chat-examples/pull/83

I would like to be able to reset the *agent*. For that we have the *reset* button. But this button resets the `objects` of the `ChatInterface` only. And I don't see any `reset` action/ event exposed that I can bind or depends to.

Please expose a `reset` event.

Similar for other actions like `revert`, `undo` and `rerun`. When I use these, I will sometimes have to add custom logic to handle  what my model or agent should do.

On the same note. Please also expose the method to let me clear the `ChatInterface` programmatically.

On the same note. Please let me add custom buttons to the task bar. Like a custom `Clear` button.

## Workaround

I can add the `reset_button` manually and somewhere else via 

```python
def _reset(_=None):
    state.reset()
    chat_interface.objects=[] # Clear Chat Interface
    chat_interface.send(
        state.welcome_message, user="Pandas Agent", avatar="🐼", respond=False
    )

_reset()
reset_button = pn.widgets.Button(name="Restart", on_click=_reset, button_type="primary", button_style="outline")
```

**Comment by MarcSkovMadsen** [comment]
On the same note. Please also expose the method to let me clear the `ChatInterface` programmatically.

**Comment by MarcSkovMadsen** [comment]
On the same note. Please let me add custom buttons to the task bar. Like a custom `Clear` button.

**Comment by ahuang11** [comment]
Right, I had this in mind down the line https://github.com/holoviz/panel/issues/5567#issue-1922999520

Associate additional hooks to the existing buttons, and/or allowing users to add buttons with custom functionality easily.
