### ISSUE TITLE
Widgets overflow ChatInterface when using Material design

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5716]
I'm on the current `main` branch of Panel working on contributing a Pandas Agent to Panel.

I'm building a `ChatInterface` with two widgets and using the `Material` design. I can see that the label of the `TextInput` overflows the tab.

![image](https://github.com/holoviz/panel/assets/42288570/fa6ad813-9804-43dd-b30d-e90113bc8659)

**Comment by ahuang11** [comment]
I think this is not specific to ChatInterface, but more generally `pn.Tabs(("Message", pn.widgets.TextAreaInput(name="Message")))`

**Comment by philippjfr** [comment]
Damn, I just removed some margin around the Material inputs and it looks like this is now causing issues. Will work on a fix.
