### ISSUE TITLE
ChatInterface callback_user and callback_avatar enhancements

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5717]
I'm on the current `main` branch of Panel studying the dev documentation of the ChatInterface at https://holoviz-dev.github.io/panel/reference/chat/ChatInterface.html.

I see the following potential enhancements

- The `callback_user` parameter is not mentioned in the Parameter section. It should be added.
  - It is in an example though.
- There is no `callback_avatar` parameter. It should added.
  - The lack of this is why I tried to have the `callback` return a `ChatMessage(value=..., user=..., avatar=...)` which lead to #5712.
  - It would make examples like the Pandas Agent at panel-chat-examples much simpler if it existed.

**Comment by ahuang11** [comment]
About `callback_avatar`, I had that initially, but I believe [you suggested it to be removed](https://github.com/holoviz/panel/pull/5420#issuecomment-1685200577).

**Comment by ahuang11** [comment]
As I'm using this more, let's add callback_avatar too.

**Comment by shwetabh-23** [comment]
Hey, I went through the repo once to try and fix the issue, but it seems I'll need something more. Can you pinpoint what is to be done so I can contribute to this? 
Thanks
- shwetabh

**Comment by ahuang11** [comment]
Thanks for your interest!

I believe you need to add `callback_avatar`, something similar to `callback_user` somewhere here.

https://github.com/holoviz/panel/blob/main/panel/chat/feed.py#L101-L102

Basically, reverting these changes from
https://github.com/holoviz/panel/pull/5420/commits/a1420603fb5da14d45c106e3813a5b38f7a3b1aa#diff-79a0463f14b802fa33f80516b9a6201485dc5a7af3271c249dee96886cf79a2cL656

**Comment by shwetabh-23** [comment]
I have create a PR, can you please review it and mention any more changes/corrections required?

**Comment by aksharasoman** [comment]
I'm confused. 
Why was the 'callback_avatar' removed? 
The docs of ChatInterface says it inherits ChatFeed. ChatFeed has "callback_avatar" parameter, while ChatInterface doesn't. I would like to specify custom 'callback_avatar'.

**Comment by ahuang11** [comment]
It'll be available in panel 1.5.0.
