### ISSUE TITLE
PanelCallbackHandler example return response before LLM Callback Value

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5727]
I'm on the current `main` branch of Panel.

I would expect the two answers below to be in the opposite order.

![image](https://github.com/holoviz/panel/assets/42288570/cf867d39-2d0e-4552-868f-ba3c26327f0d)

```python
import panel as pn
from langchain.llms import OpenAI

pn.extension()

llm = OpenAI(temperature=0)

def callback(contents, user, instance):
    callback_handler = pn.chat.langchain.PanelCallbackHandler(instance)    
    return llm.predict(contents, callbacks=[callback_handler])

pn.chat.ChatInterface(callback=callback).servable()
```

**Comment by MarcSkovMadsen** [comment]
## Correct Order

The correct order should be as below. Which the streaming version produces.

**Comment by ahuang11** [comment]
Related to this line, but not sure how to fix.
https://github.com/holoviz/panel/blob/main/panel/chat/langchain.py#L103-L110

**Comment by ahuang11** [comment]
Okay nevermind, found a fix https://github.com/holoviz/panel/pull/5729
