### ISSUE TITLE
Panel 1.3.0: ReactiveHTML with custom param.Parameter broken.

### ISSUE THREAD

**Issue by emcd** [holoviz/panel#5730]
#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
```
$ python --version
Python 3.10.12
$ panel --version
1.3.0
```

#### Description of expected behavior and the observed behavior

Successful execution (like in Panel 1.2.3) is the expected behavior.
In Panel 1.3.0, the observed behavior is an `AttributeError` exception.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from panel.reactive import ReactiveHTML
from param import Parameter

class Kaboom( ReactiveHTML ):

    foo = Parameter( )

    def __init__( self, **params ):
        self.foo = 1
        super( ).__init__( **params )

Kaboom( ).show( )
```

#### Stack traceback and/or browser JavaScript console output

```
$ python3 laboratory/panel-1.3.0-bug.py 
Traceback (most recent call last):
  File "/home/me/src/ai-experiments/laboratory/panel-1.3.0-bug.py", line 12, in <module>
    Kaboom( ).show( )
  File "/home/me/src/ai-experiments/laboratory/panel-1.3.0-bug.py", line 10, in __init__
    super( ).__init__( **params )
  File "/home/me/src/ai-experiments/.local/environments/langchain/lib/python3.10/site-packages/panel/reactive.py", line 1594, in __init__
    super().__init__(**params)
  File "/home/me/src/ai-experiments/.local/environments/langchain/lib/python3.10/site-packages/panel/reactive.py", line 545, in __init__
    if name not in self._param__private.explicit_no_refs:
AttributeError: '_InstancePrivate' object has no attribute 'explicit_no_refs'
```

**Comment by philippjfr** [comment]
Can you report the param version?

**Comment by emcd** [comment]
@philippjfr : Looks like something is pulling in a release candidate rather than a stable release:
```
$ python3 -m pip list | grep param
param                     2.0.0rc7
```

I'll check to see which version is being pulled in under Panel 1.2.3. I just rebuilt my virtual environment a little while ago, so it's possible that another package is pulling in this dependency.

**Comment by philippjfr** [comment]
Thanks, I can also reproduce.

**Comment by philippjfr** [comment]
We should definitely fix this but you really shouldn't set a parameter value before calling super, i.e. this would be preferred:

```python
from panel.reactive import ReactiveHTML
from param import Parameter

class Kaboom( ReactiveHTML ):

    foo = Parameter( )

    def __init__( self, **params ):
        params['foo'] = 1
        super( ).__init__( **params )
```

**Comment by philippjfr** [comment]
Thankfully we haven't quite released Param 2.0 yet (you raised this just in time), so we can get a fix in before the release.

**Comment by emcd** [comment]
Ah, okay. I was not aware of that preference/limitation. Moving the super invocation to the top of the initializer does indeed provide a workaround. Feels a bit Python-non-intuitive that the behavior of setting an attribute on an object would be linked to superclass initialization. Thanks for the quick response.

**Comment by maximlt** [comment]
For reference, there's a Param issue about deprecating this usage https://github.com/holoviz/param/issues/815.

> Feels a bit Python-non-intuitive that the behavior of setting an attribute on an object would be linked to superclass initialization.

Agreeing with you, Param can do better there.

**Comment by maximlt** [comment]
@philippjfr the alternative to https://github.com/holoviz/param/pull/876 is apply this change and release Panel 2.0.1. I assume you prefer patching Param before I release it today?

```diff
diff --git a/panel/reactive.py b/panel/reactive.py
index 83f3017ed..f1705b811 100644
--- a/panel/reactive.py
+++ b/panel/reactive.py
@@ -542,7 +542,7 @@ class Reactive(Syncable, Viewable):
 
     def __init__(self, refs=None, **params):
         for name, pobj in self.param.objects('existing').items():
-            if name not in self._param__private.explicit_no_refs:
+            if name not in type(self)._param__private.explicit_no_refs:
                 pobj.allow_refs = True
         if refs is not None:
             self._refs = refs
```

**Comment by maximlt** [comment]
I'd prefer Param to provide a public API here if there's a need for one. Let's patch Param for now and release, and then:

- provide a public API for what you need in Panel in this case
- update the internals of Param if they're too sketchy

**Comment by philippjfr** [comment]
Sounds fine to me.
