### ISSUE TITLE
Regression in markdown code block newline output between panel 1.2.3 and 1.3

### ISSUE THREAD

**Issue by blooop** [holoviz/panel#5737]
In panel 1.2.3 any text in a code block will show newlines as expected (and as in the markdown docs)
https://panel.holoviz.org/reference/panes/Markdown.html

In panel 1.3, the newlines are ignored and the code block shows only on a single line.

Minimal example:

shared env:
ubuntu 22.04
chrome
python3.10

running this code:
```
import panel as pn
pn.pane.Markdown("# Code block\n```\na\nb\n```").show()
```

env:
panel 1.2.3

correct output:
![image](https://github.com/holoviz/panel/assets/1213400/fc820bd8-7fce-4788-9cbf-d5c2fb708796)

env:
panel 1.3

incorrect output:
![image](https://github.com/holoviz/panel/assets/1213400/07710041-9952-4bb3-9319-d9c068239a1f)

**Comment by philippjfr** [comment]
Very strange, I cannot reproduce.

**Comment by blooop** [comment]
you can reproduce it on the markdown docs page by comparing the output as shown by default, compared to what the output is when you run the code live on the webpage.

**Comment by philippjfr** [comment]
Indeed, I see it. Seems like the Markdown renderer differs between the two versions resulting in slightly different DOM structures which in turn changes the `white-space` property that is applied.

**Comment by blooop** [comment]
Is there a workaround to get the old behaviour in 1.3?

**Comment by philippjfr** [comment]
I'm not sure yet because I still haven't found a way to reproduce locally, try:

```python
import panel as pn

stylesheet = '.codehilite > code { white-space: break-spaces; }'
pn.pane.Markdown("# Code block\n```\na\nb\n```", stylesheets=[stylesheet]).show()
```
