### ISSUE TITLE
Implement a nested dropdown select

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5744]
Can we have something like a nested, n-dim select dropdown built-in to Panel widgets?  (I vaguely remember seeing @jlstevens implement this somewhere?)

```python
import panel as pn
pn.extension()

WX_VARS_LEVS = {"precip": [1000], "temp": [1000, 925, 700, 500, 300], "vorticity": [500, 300]}
WX_VARS = list(WX_VARS_LEVS.keys())

def update_lev_select(var):
    return pn.widgets.Select(options=WX_VARS_LEVS[var])

var_select = pn.widgets.Select(options=WX_VARS)
lev_select = pn.bind(update_lev_select, var=var_select)
pn.Column(var_select, lev_select)
```

<img width="606" alt="image" src="https://github.com/holoviz/panel/assets/15331990/ea3ee769-eb4d-4be4-86ad-e7706067bf34">

<img width="687" alt="image" src="https://github.com/holoviz/panel/assets/15331990/f0abd566-d988-412b-9df6-5f76de4ca7ee">

Not sure if it's enough to support just one level, but for multiple levels, I imagine a dict of dict of list? `{"precip": {"conus": [1000], "global": [1000]}, "temp": {"conus": [1000, 925, 700, 500, 300], "global": {"temp": [1000, 500]}}}`

[Here's an applicable example](https://projectpythia.org/web-map-feature-services-cookbook/notebooks/nasa_earthdata_gibs_explorer.html) of multi-level dropdowns:
1. Product
2. Layer
3. Time
(potentially 4. Level)
<img width="722" alt="image" src="https://github.com/holoviz/panel/assets/15331990/21dd625b-f52f-433c-b525-818f6f1a4f10">

**Comment by MarcSkovMadsen** [comment]
Very often the data you have is not a dict, but a dataframe

**Comment by ahuang11** [comment]
However, transforming a dataframe to a dict is semi-trivial.

**Comment by philippjfr** [comment]
Usually you'd have a multi-index that maps to the dict. I'm fine with a `.from_index()` method or similar.

**Comment by philippjfr** [comment]
Generally I've always wanted a `.from_pandas` method for most widgets that automatically computes the bounds for sliders and the options for select widgets.

**Comment by MarcSkovMadsen** [comment]
> To be consistent with other widgets, I like the idea of keeping dict, list. (I suppose Tabulator/Perspective uses param.DataFrame)
> 
> Also, I think transforming a dataframe to a dict is semi-trivial `df.to_dict()`
> 
> I wonder how a dataframe with multi-level would look.

Its not *just* transforming a dataframe to a dictionary. You might have a DataFrame with 10mn rows containing categorical columns `category1`, `category2`, `category3` and other columns. You then want to select first from the unique category1 values. Then form the reduced set of unique `category2` values under `category1` etc.

**Comment by ahuang11** [comment]
So I suppose this widget should definitely support n-nesting, and I agree that I prefer `from_pandas` or `from_index` instead of a `param.DataFrame` field.

**Comment by ahuang11** [comment]
I can try creating a prototype. Would this be a `CompositeWidget`?

**Comment by benbarn313** [comment]
One thing to note is that it would be nice to have some more complex dependencies. For example you could have one widgets contents be dependent on two independent widgets.

**Comment by ahuang11** [comment]
Interesting idea; not entirely clear how to express that as a Python type--perhaps tuples as keys?

`{("variable", "level"): [*times]}`

**Comment by legout** [comment]
Although this feature is already merged, I want to ask, if this could be extended to Multiselect.
