### ISSUE TITLE
Tabulator icons are not showing up

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5759]
Not sure why it shows up in the docs, but I can't seem to get it working on my end.

No console errors either.

```python
import pandas as pd
import datetime as dt
import panel as pn

pn.extension('tabulator')

df = pd.DataFrame({
    'int': [1, 2, 3],
    'float': [3.14, 6.28, 9.42],
    'str': ['A', 'B', 'C'],
    'bool': [True, False, True],
    'date': [dt.date(2019, 1, 1), dt.date(2020, 1, 1), dt.date(2020, 1, 10)],
    'datetime': [dt.datetime(2019, 1, 1, 10), dt.datetime(2020, 1, 1, 12), dt.datetime(2020, 1, 10, 13)]
}, index=[1, 2, 3])

button_table = pn.widgets.Tabulator(df, buttons={
    'print': '<i class="fa fa-print"></i>',
    'check': '<i class="fa fa-check"></i>'
})

string = pn.widgets.StaticText()

button_table.on_click(
    lambda e: string.param.update(value=f'Clicked {e.column!r} on row {e.row}')
)

pn.Row(button_table, string).show()
```

<img width="575" alt="image" src="https://github.com/holoviz/panel/assets/15331990/bdb5b07b-7396-4cde-8aa2-01297c70dc4c">

<img width="848" alt="image" src="https://github.com/holoviz/panel/assets/15331990/5b9bcc2f-8f6e-4002-8a80-7604a598efb0">

**Comment by philippjfr** [comment]
This is a usage issue, if you're using font-awesome icons you actually have to make sure you load them.

**Comment by ahuang11** [comment]
Should that be mentioned in the docs?
https://panel.holoviz.org/reference/widgets/Tabulator.html#buttons

**Comment by philippjfr** [comment]
Yes!

**Comment by MarcSkovMadsen** [comment]
There are users experiencing this pain them here https://discourse.holoviz.org/t/panel-tabulator-buttons/6133/5
