### ISSUE TITLE
panel convert --to pyscript is broken

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5767]
I'm on the `main` branch of Panel trying to figure out how to most easily embed Panel into existing websites and documentation. Now I'm trying to `panel convert` to `pyscript` and I see some issues.

```python
import panel as pn

pn.extension()

pn.panel("hello world").servable()
```

```bash
panel convert script.py --to pyscript
```

The loading looks like

![image](https://github.com/holoviz/panel/assets/42288570/4e46aeae-835e-4ac6-ba7c-77f284a19937)

The final result looks like

![image](https://github.com/holoviz/panel/assets/42288570/b4200b92-a791-4432-b073-23ad4a57d226)

**Comment by philippjfr** [comment]
Suspect this is because we dropped the pyscript.css by default.
