### ISSUE TITLE
pn.pane.HTML has trouble with tooltips 

### ISSUE THREAD

**Issue by dataist** [holoviz/panel#577]
#### ALL software version info 
panel 0.6
bokeh 1.2.0
pygal 2.4
Python 3.7.0 
IPython 7.6.1

#### Description of expected behavior and the observed behavior
With some effort I was to get [pygal](http://pygal.org/en/stable/) to work in an `interact` context. However both myself and tweaks from @philippjfr were unable to get tooltip hovers to work despite them working when rendering the same `html` with `ipython.display.HTML`.

I would provide a more minimal example below but `javascript` is not at all in my wheelhouse. 

### Tooltips not working as rendered by `panel`
```
import panel as pn

from pygal import Treemap

js_files = {
    'pygal': 'http://kozea.github.com/pygal.js/javascripts/svg.jquery.js',
    'pygal_tooltips': 'http://kozea.github.io/pygal.js/latest/pygal-tooltips.js'
}

pn.extension(js_files=js_files)

html_pygal = """
<figure>{pygal_render}</figure>
"""

def get_treemap(size):
    treemap = Treemap()
    treemap.add('A', [{'value': size, 'label': 'This is the second'}, 1, 12, 4, 2, 1, 1, 3, 12, 3, 4, None, 9])
    treemap.add('B', [4, 2, 5, 10, 3, 4, 2, 7, 4, -10, None, 8, 3, 1])
    treemap.add('C', [3, 8, 3, 3, 5, 3, 3, 5, 4, 12])
    treemap.add('D', [23, 18])
    treemap.add('E', [1, 2, 1, 2, 3, 3, 1, 2, 3,
          4, 3, 1, 2, 1, 1, 1, 1, 1])
    treemap.add('F', [31])
    treemap.add('G', [5, 9.3, 8.1, 12, 4, 3, 2])
    treemap.add('H', [12, 3, 3])
    return pn.pane.HTML(html_pygal.format(pygal_render=treemap.render().decode('utf-8')),
                        sizing_mode='stretch_both', height=800, width=800)

pn.interact(get_treemap,size=(1,100))
```
### Tooltips working as rendered 
```
from pygal import Treemap

html_pygal = """
<figure>
    <script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/svg.jquery.js"></script>
    <script type="text/javascript" src="https://kozea.github.io/pygal.js/2.0.x/pygal-tooltips.min.js""></script>
    {pygal_render}
</figure>
"""

def get_treemap(size):
    treemap = Treemap()
    treemap.add('A', [{'value': size, 'label': 'This is the second'}, 1, 12, 4, 2, 1, 1, 3, 12, 3, 4, None, 9])
    treemap.add('B', [4, 2, 5, 10, 3, 4, 2, 7, 4, -10, None, 8, 3, 1])
    treemap.add('C', [3, 8, 3, 3, 5, 3, 3, 5, 4, 12])
    treemap.add('D', [23, 18])
    treemap.add('E', [1, 2, 1, 2, 3, 3, 1, 2, 3,
          4, 3, 1, 2, 1, 1, 1, 1, 1])
    treemap.add('F', [31])
    treemap.add('G', [5, 9.3, 8.1, 12, 4, 3, 2])
    treemap.add('H', [12, 3, 3])
    return HTML(html_pygal.format(pygal_render=treemap.render().decode('utf-8')))

get_treemap(100)
```

This issue was initially discussed [here on gitter](https://gitter.im/pyviz/pyviz?at=5d49e060d7fc9547500f862c)

Also, this issue could be related to a nascent feature request of more official support of pygal in panel by exposing `pygal` support via  `pn.extension('pygal')`

**Comment by philippjfr** [comment]
The problem here is that the pygal-tooltips.js function does not seem to get re-executed on each slider event, which means the hover works only on first render.

**Comment by dataist** [comment]
Interesting, I wasn't able to get the first render to work

**Comment by philippjfr** [comment]
Here's what that looked like:

<img width="779" alt="Screen Shot 2019-08-07 at 8 49 07 PM" src="https://user-images.githubusercontent.com/1550771/62649244-d2690480-b954-11e9-8278-0a9fd5a287dc.png">

**Comment by philippjfr** [comment]
Honestly I think this is more to do with the particular library being wrapped than the HTML component itself since this hasn't come up in other contexts.
