### ISSUE TITLE
500 error when using `authorize_callback` for custom authorization

### ISSUE THREAD

**Issue by armaaar** [holoviz/panel#5776]
#### ALL software version info

Python 3.10.13
Panel: 1.3.0
Bokeh: 3.3.0
Param: 2.0.0

#### Description of expected behavior and the observed behavior

If we try to register an `authorize_callback` while `id_token` is not presented, we het a 500 error

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn

def authorize(user_info, request_path):
    print(user_info, request_path)
    return True

pn.config.authorize_callback = authorize

pn.serve("# Hello")
```

#### Stack traceback and/or browser JavaScript console output

```
python issues.py
Launching server at http://localhost:54179
Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:54179', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/***/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
  File "/opt/homebrew/Caskroom/miniconda/base/envs/***/lib/python3.10/site-packages/panel/io/server.py", line 548, in get
    auth_args = (state.user_info, self.request.path,)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/***/lib/python3.10/site-packages/panel/io/state.py", line 1097, in user_info
    return decode_token(id_token)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/***/lib/python3.10/site-packages/panel/util/__init__.py", line 282, in decode_token
    if signed and "." in token:
TypeError: argument of type 'NoneType' is not iterable
500 GET / (::1) 141.92ms
```

#### Screenshots or screencasts of the bug in action

![Screenshot 2023-10-30 at 10 46 26 AM](https://github.com/holoviz/panel/assets/25823409/6323e373-519b-4052-b3fb-76c477c41e6f)

- [ ] I may be interested in making a pull request to address this

**Comment by philippjfr** [comment]
Thanks, should already be fixed on main. Will release 1.3.1 with a fix today.

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/5747
