### ISSUE TITLE
Dynamic Map restricted to data referenced on first invocation

### ISSUE THREAD

**Issue by ba-ab-not-a-ba** [holoviz/panel#5782]
I think this is a bug, but it could be an understanding or usage problem.  
 
#### ALL software version info
Windows Server 2022 Datacenter
Microsoft Edge Version 118.0.2088.76
panel                     1.3.0              pyhd8ed1ab_0    conda-forge
holoviews                 1.18.0             pyhd8ed1ab_0    conda-forge
bokeh                     3.3.0              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0             pyhd8ed1ab_10    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_bokeh             2.0.4              pyhd8ed1ab_0    conda-forge
jupyter_client            8.5.0              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.4.0           py311h1ea47a8_0    conda-forge
jupyter_events            0.8.0              pyhd8ed1ab_0    conda-forge
jupyter_server            2.8.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.7              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
**nbclassic**                 1.0.0              pyhb4ecaf3_1    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
#### Description of expected behavior and the observed behavior

I expect panel to (effectively) invoke a dynamic map function call whenever the bound parameter value changes in a manner that would change the return value of that function.  The function only prints on subsequent invocations if I use pn.serve (but not without pn.serve).  Somehow the plot updates correctly, **if and only if the initial invocation of the function referenced all of the data required for the update**.  Constrast the two examples to see what I mean.

**I am using jupyter nbclassic**.  With pn.serve changing the slider value also failed to update the plot in the second case, just with print statements.    

Can the dynamic map only handle updates on subsets of the data it initially references?

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import pandas as pd
import panel as pn
import holoviews as hv
hv.extension('bokeh')
pn.extension()

# Create a data frame with 10 points along y = x
df = pd.DataFrame(np.arange(20).reshape(10,2),columns=['x','y'])

# This works: dynamic map which shows first n rows of df using a slider to control n
# It "works" because as the slider changes, the number of points on the plot changes accordingly
def f(n):
    print(f"In function call with argument {n}")
    return hv.Scatter(data=df.iloc[0:n],kdims=['x'],vdims=['y'])

slider = pn.widgets.DiscreteSlider(name='Discrete Slider', options=[0,1,2,3,4,5,6,7,8,9], value=9)
dmap = hv.DynamicMap(pn.bind(f,n=slider))
pn.Row(slider,dmap)

```

```
# This does NOT work: same idea but start with only one point on the first invocation of the dynamic map
# Notice that the value argument of the slider is now 1.
# It "does not work" because as you change the slider to values greater than 1, the plot still contains only one point.
slider = pn.widgets.DiscreteSlider(name='Discrete Slider', options=[0,1,2,3,4,5,6,7,8,9], value=1)
dmap = hv.DynamicMap(pn.bind(f,n=slider))
pn.Row(slider,dmap)
```

**Comment by ba-ab-not-a-ba** [comment]
So I initially thought this was a bug, but now I'm starting to think it's just a "how does this work" question... don't know how to relabel the issue.

**Comment by Hoxbro** [comment]
The problem is that the axis is not updating with each update.

 Try this `dmap = hv.DynamicMap(pn.bind(f,n=slider)).opts(framewise=True)` or `dmap = hv.DynamicMap(pn.bind(f,n=slider)).opts(xlim=(-1, 15), ylim=(-1, 15))`

**Comment by philippjfr** [comment]
Indeed, this should probably be documented better but it's a HoloViews issue, not a Panel one.
