### ISSUE TITLE
Exposing _counter and having `value` as a param in add_periodic_callback

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#579]
I was thinking that it'd be useful to have _counter as a public method/to show in `periodic.params()`?

```
import panel as pn
pn.extension()

test = pn.widgets.Toggle(name='Test')

def toggle():
    test.value = not test.value

periodic = test.add_periodic_callback(toggle, 1000)
print(periodic._counter)
```

Also maybe periodic.value = True mapped to periodic.start() and periodic.value = False mapped to periodic.stop() so there's less boilerplate and can use a .link() / .jslink() directly with a toggle

```
def toggle_periodic_callback(event):
    if event.new is True:
        periodic_cb.start()
    else:
        periodic_cb.stop()
```
becomes
`toggle.jslink(periodic, value='value')`

**Comment by philippjfr** [comment]
>toggle.jslink(periodic, value='value')

Note this cannot work since the value toggle would be server-side, .link would work though.

**Comment by philippjfr** [comment]
This would be an API change and users could simply keep their own counter so I'm -1 and will close.

**Comment by philippjfr** [comment]
Also the other part of this proposal was implemented. You can now set the `running` parameter on `PeriodicCallback`.
