### ISSUE TITLE
Tooltip icon too prominent

### ISSUE THREAD

**Issue by jbednar** [holoviz/panel#5803]
Using hvPlot's explorer I found the tooltip icons much too prominent and distracting:

![image](https://github.com/holoviz/panel/assets/1695496/a52bfdc5-12eb-439d-a2a5-7875e02a57e5)

I think this is being determined at the [Panel](https://panel.holoviz.org/reference/widgets/Button.html) level, because in Panel they are also dark:

<img width="560" alt="image" src="https://github.com/holoviz/panel/assets/1695496/ab66609c-881f-4908-b92b-5d365ecf4a59">

While on the [Bokeh](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/tooltips.html#ug-interaction-tooltips) website, they are lighter gray:

![image](https://github.com/holoviz/panel/assets/1695496/a3743416-a1b3-4e08-8d25-ee7925db5d4e)

I think the (?) symbol should be only barely visible, because it detracts from the look of the page and makes it harder to focus on the meaningful values and labels, so I'd vote for greatly reducing the alpha of this symbol. Also making it smaller might help, as it's larger than the text in the label, but maybe that makes the `?` unreadable.

**Comment by MarcSkovMadsen** [comment]
+1

**Comment by Hoxbro** [comment]
We have an opacity setting at 0.7 in the `native.css` but it looks like it is being overwritten by inline styling:
![image](https://github.com/holoviz/panel/assets/19758978/7b43f5e0-7712-4636-b09a-ca17815d90de)

``` python
import panel as pn

button = pn.widgets.TooltipIcon(
    value="This is a simple tooltip by using a string"
).servable()
```

@jbednar: please put in the URL, so it easy to access the sites in question.

**Comment by ahuang11** [comment]
The screenshots I believe are from
https://hvplot.holoviz.org/user_guide/Explorer.html#geographic-options

**Comment by philippjfr** [comment]
@Hoxbro that's the explicit TooltipIcon model while @jbednar is referring to the automatically created tooltip. I think we do just need to reduce the default opacity to 0.5 or so.

**Comment by philippjfr** [comment]
opacity: 0.5 actually appears to be the default and for some reason we override it in native.css

**Comment by Hoxbro** [comment]
It is set in `inline` to 1. Native.css has it as 0.7. It is the same for both `TooltipIcon` and the automatically created tooltip.

**Comment by philippjfr** [comment]
Ah looking at your screenshot, you are simply picking up the hover CSS class, that should have a opacity of 1.

**Comment by jbednar** [comment]
If I'm following correctly, yes, while it's being hovered over, it should have an opacity of 1. I think it should have an opacity of 0.5 otherwise, as even 0.7 as in Bokeh I think is too dark. It should be visible but not at all distracting.
