### ISSUE TITLE
Tabulator text_align is not working with Bokeh NumberFormatter

### ISSUE THREAD

**Issue by dlyngman** [holoviz/panel#5807]
#### ALL software version info
panel 1.3.0, bokeh 3.2.2

#### Description of expected behavior and the observed behavior

When using Bokeh NumberFormatter column gets left aligned no matter what is passed to text_align, without the formatters the alignment is working as expected.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import panel as pn
from bokeh.models.widgets.tables import NumberFormatter

pn.extension('tabulator') 

df = pd.DataFrame({
    "float": [1.23, 4.56, 7.89, -1.23, -4.56, -7.89],
    "int": [10, 20, 30, -10, -20, -30],
    "pct": [0.25, 0.50, 0.75, -0.25, -0.50, -0.75]
})

pn.widgets.Tabulator(
    df,
    formatters = {
        'float': NumberFormatter(format='0,0.0'),
        'int': NumberFormatter(format='0,0'),
        'pct': NumberFormatter(format='0%'),
    },
    text_align = {
        'float': 'right',
        'int': 'right',
        'pct': 'right',
    },
)

```

#### Screenshots or screencasts of the bug in action

![image](https://github.com/holoviz/panel/assets/79541294/e264a4c3-6ebe-4cda-b5d9-7aab50367a5b)

- [ ] I may be interested in making a pull request to address this

**Comment by Hoxbro** [comment]
As a temporary work-around you can use: `NumberFormatter(format="0,0.0", text_align="right")`

``` python
import pandas as pd
import panel as pn
from bokeh.models.widgets.tables import NumberFormatter

pn.extension("tabulator")

df = pd.DataFrame(
    {
        "float": [1.23, 4.56, 7.89, -1.23, -4.56, -7.89],
        "int": [10, 20, 30, -10, -20, -30],
        "pct": [0.25, 0.50, 0.75, -0.25, -0.50, -0.75],
    }
)

pn.widgets.Tabulator(
    df,
    formatters={
        "float": NumberFormatter(format="0,0.0", text_align="right"),
        "int": NumberFormatter(format="0,0", text_align="right"),
        "pct": NumberFormatter(format="0%", text_align="right"),
    },
)
```

![image](https://github.com/holoviz/panel/assets/19758978/895f4fad-1c9f-450f-ae6e-acabb86d1653)

**Comment by philippjfr** [comment]
Which means we can simply set the `text_align` on the bokeh formatter if provided.

**Comment by Hoxbro** [comment]
Curious about what should take priority in a case like this:

``` python

pn.widgets.Tabulator(
    df,
    formatters = {
        'float': NumberFormatter(format='0,0.0', text_align='left'),
    },
    text_align = {
        'float': 'right',
    },
)
```

**Comment by philippjfr** [comment]
Knew you were going to ask that :)

I'd say we warn if the Formatter `text_align` value is non-default and an explicit text_align is provided and then apply the explicit `text_align` value.
