### ISSUE TITLE
Color bar not appearing when clicking on `...` in jupyter notebook - VTK extension

### ISSUE THREAD

**Issue by francesco-ballarin** [holoviz/panel#5809]
#### ALL software version info
* `panel`: 1.3.1
* `pyvista`: 0.42.3
* `python`: 3.11.6
* browser: chrome

#### Description of expected behavior and the observed behavior
When running the jupyter notebook below (please rename from `ipynb.txt` to `ipynb`), the panel pane appears. At the bottom left of it, there are `...` which used to show the color bar. With the current version, the color bar does not appear anymore upon clicking, and the `...` disappear.

#### Complete, minimal, self-contained example code that reproduces the issue
[panel.ipynb.txt](https://github.com/holoviz/panel/files/13258834/panel.ipynb.txt)

#### Stack traceback and/or browser JavaScript console output
```
TypeError: Cannot read properties of undefined (reading 'getInteractor')
    at l.remove (panel.min.js:159:4776)
    at l.remove (panel.min.js:175:991)
    at s (bokeh-3.3.0.min.js:218:908)
    at bokeh-3.3.0.min.js:218:1155
    at bokeh-3.3.0.min.js:218:1160
    at S._trigger_on_change (bokeh-3.3.0.min.js:165:4949)
    at S.remove_root (bokeh-3.3.0.min.js:165:3911)
    at S.clear (bokeh-3.3.0.min.js:165:1639)
    at P._disposePlot (445.e0d338852f1bcbe1aa57.js?v=e0d338852f1bcbe1aa57:1:10925)
    at P.dispose (445.e0d338852f1bcbe1aa57.js?v=e0d338852f1bcbe1aa57:1:11089)
    e.exceptionHandler	@	jlab_core.975ecba59e…ecba59e6dfbddeb44:1
panel.min.js:176 Uncaught TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')

Uncaught TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
    at e.resize (panel.min.js:176:2137)
    at l.after_layout (panel.min.js:159:4474)
    at l.compute_layout (bokeh-3.3.0.min.js:560:5540)
    at l._after_resize (bokeh-3.3.0.min.js:560:732)
    at l.after_resize (bokeh-3.3.0.min.js:439:2547)
    at ResizeObserver.<anonymous> (bokeh-3.3.0.min.js:439:2043)
```

**Comment by francesco-ballarin** [comment]
The same issue appears on the documentation website, see https://panel.holoviz.org/reference/panes/VTK.html#scene-creation

**Comment by francesco-ballarin** [comment]
My understanding is that this is caused (at least partially) by 
https://github.com/holoviz/panel/blob/eb3ea1966675687d9ab847304fabd10961bd3641/panel/models/vtk/vtksynchronized.ts#L54
By deleting before calling the parent destructor, when the execution arrives at
https://github.com/holoviz/panel/blob/eb3ea1966675687d9ab847304fabd10961bd3641/panel/models/vtk/vtklayout.ts#L235
the object `this._vtk_renwin` is gone. 
The order of the `if` statement and `super.remove()` should be swapped in
https://github.com/holoviz/panel/blob/eb3ea1966675687d9ab847304fabd10961bd3641/panel/models/vtk/vtksynchronized.ts#L52
or, even better, the whole override should be dropped, since `this._vtk_renwin.delete()` is already called in the parent destructor.

This change seems to have been introduced in #4758 by @philippjfr. I tried to this locally, but after installing with `pip install .` I do not seem to be able to use the local `panel.min.js` instead of the one coming from holoviz cdn.

**Comment by edsaac** [comment]
In case this info is useful, color bars are displayed correctly using old versions:
```
panel==0.14.4
bokeh==2.4.3
param==1.12.0
```

**Comment by francesco-ballarin** [comment]
Thanks @edsaac for the workaround, and for mentioning that #5176 is related. I am going to close this since it is a duplicate, but still add a link to this issue in #5176.
