### ISSUE TITLE
allow_None in a param parameter doesn't allow empty String widgets

### ISSUE THREAD

**Issue by hyamanieu** [holoviz/panel#581]
Software Versions:
```
bokeh 1.3.4
panel 0.6.1
jupyter core 4.5.0
jupyter-notebook 6.0.0
```

I would expect setting a `param.Integer` with `allow_None = True` to return a widget that accepts empty values and returns None. Alternatively, I would expect using a `LiteralInput `with `placeholder="0" `and `type=int` to set "0" when entering no value (as both None & 0 are considered as False in `if` statements)
Instead, `(invalid)` is appended to the widget name and no callback happens.

Example 1:
```python
class CustomExample(param.Parameterized):
    """An example Parameterized class"""

    select_string = param.Selector(objects=["red", "yellow", "green"])
    select_number = param.Selector(objects=[0, 1, 10, 100])
    some_number = param.Integer(default = None, allow_None=True)
    
pn.Param(CustomExample.param, widgets={
    'select_string': {'type': pn.widgets.RadioButtonGroup, 'button_type': 'success'},
    'select_number': pn.widgets.DiscretePlayer
}
)
```

Example 2:
```python
class CustomExample(param.Parameterized):
    """An example Parameterized class"""

    select_string = param.Selector(objects=["red", "yellow", "green"])
    select_number = param.Selector(objects=[0, 1, 10, 100])
    some_number = param.Integer(default = None, allow_None=True)
    
pn.Param(CustomExample.param, widgets={
    'select_string': {'type': pn.widgets.RadioButtonGroup, 'button_type': 'success'},
    'select_number': pn.widgets.DiscretePlayer,
    'some_number': {'type': pn.widgets.LiteralInput, 'placeholder':0,type:int}
}
)
```

**Comment by jbednar** [comment]
I agree with your first point; there should be a way to select nothing and to end up with the value set to None.  I don't know how that would actually be achieved with the widgets available, but I do think that's what we should strive for.

For LiteralInput, the placeholder is meant for things like "Type your number here", so I would _not_ have an expectation that the contents of that string would be processed by Python.  If you want the value to actually be zero, shouldn't you just set the initial value to zero (rather than setting the placeholder to the string "0")?

**Comment by hyamanieu** [comment]
My bad, I misunderstood the "placeholder" function. However, whatever I write into placeholder, it never shows up.

For now, I guess I have to explicitly tell the user to enter 0 when she/he doesn't anything.

**Comment by jbednar** [comment]
Not seeing the placeholder text sounds like a bug; please open a separate issue with screenshots.  If you are telling the user to enter 0, why not just make the default value 0?

**Comment by hyamanieu** [comment]
It's supposed to correspond to a filter on a table column with thousands of int (it's simply an incremented number, like an index). Most people would expect writing nothing means filter is off, not writing a 0 (which could be a legitimate index, although not the case here).

**Comment by jbednar** [comment]
Ok, makes sense.  My overall understanding is then:

1. The widget for param.Integer does not allow None to be a properly selectable option (this issue). I agree that it's a problem, but Panel is just one of many different widget libraries that can be used with Param (Tk, ipywidgets, and Bokeh being others previously used), and not all widget libraries support the notion of "no value" for a numeric widget.  If we can get Panel's widgets to support that, great!, but I don't know the answer myself.
2. The issue with not seeing the placeholder text for LiteralInput seems like a bug, which should be reported in a separate issue.
3. I don't think LiteralInput will help in this case anyway, as you've told it to use type `int` but None is not of type `int`, and LiteralInput doesn't currently allow multiple possible types.

**Comment by philippjfr** [comment]
>LiteralInput doesn't currently allow multiple possible types

This is not true, you can provide a tuple of types.

**Comment by jbednar** [comment]
The docs are incorrect, then, because I checked them before writing that:
![image](https://user-images.githubusercontent.com/1695496/62736438-f713b980-b9f2-11e9-950c-0704b6baaa8f.png)
