### ISSUE TITLE
Issue with oauth2 authentication, for google oauth and panel version above 1.3.0: "Some requested scopes were invalid ... invalid=[offline_access]"

### ISSUE THREAD

**Issue by el-abcd** [holoviz/panel#5815]
SUMMARY:
From some googling, I __think__ that google oauth does NOT like the URL sent to it to contain: "&scope=...+offline_access", instead it wants to have a "&access_type=offline&" segment in the URL.  
IIUC, using "&scope=...+offline_access" might be the "openid standard way" but google oauth might not be following the standard for this field?

References:
* https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient
  * only documents using the "access_type" parameter
* https://github.com/ory/kratos/pull/3088
  * Sounds like a very similar issue in another open-source package.
* https://community.qlik.com/t5/Official-Support-Articles/quot-Error-400-Invalid-Scope-invalid-offline-access-quot-when/ta-p/1808663
  * Also sounds like the same issue

DETAILS:

#### ALL software version info
panel version 1.3.0 and 1.3.1.  
I am running this on a docker container in google cloud run.  Based on my debugging so far I think it is very likely a change in panel 1.3.0 (this is working in version 1.2.3)
Most likely in this change:
Unify OAuth implementations and refresh access_token (https://github.com/holoviz/panel/pull/5627)

#### Description of expected behavior and the observed behavior
I am running this in a docker container running in google cloud run.  
When using panel==1.2.3 the oauth login page "works as expected", I see the prompt asking me to authorize.  

When running with panel==1.3.0 (and 1.3.1) I see an error screen: 
<img width="378" alt="image" src="https://github.com/holoviz/panel/assets/39447831/4ead4531-c182-40b2-afe9-0c64028716e5">

I am launching my code in a docker container, using a command line like this...
```
CMD panel serve 220514_01_awesome_panel.py --address 0.0.0.0 --port 8080 --allow-websocket-origin="*" \
--oauth-provider=google \
--oauth-key=<my key> \
--oauth-redirect-uri=<my redirect url>
```

From inspecting the chrome developer tools I think the issue is the "+offline_access" after the &scope=:
* BAD: 
  * https://accounts.google.com/o/oauth2/v2/auth?response_type=code&redirect_uri=https....googleusercontent.com&state=...&scope=openid+email+profile+offline_access
* It WORKS if I edit the URL to use &access_type=offline instead:
  * &scope=openid+email+profile&access_type=offline&
* In panel v1.2.3, I see the URL does NOT include the offline field...
  * &scope=profile+email

#### Complete, minimal, self-contained example code that reproduces the issue

See notes above...

#### Stack traceback and/or browser JavaScript console output

```
Access blocked: Authorization Error

<my google email address>
Some requested scopes were invalid. {valid=[openid, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile], invalid=[offline_access]} [Learn more about this error](https://developers.google.com/identity/protocols/oauth2)
If you are a developer of <my app name>, see [error details](https://accounts.google.com/).
Error 400: invalid_scope
```

#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this

**Comment by el-abcd** [comment]
@philippjfr 
Hi Philipp,

Just adding a comment with your username, as I think this item is probably related to 
https://github.com/holoviz/panel/pull/5627

**Comment by el-abcd** [comment]
And one more reference:
https://github.com/int128/kubelogin/issues/405

IIUC: It sounds like the URL might need to change some depending on the oauth provider?  
i.e. It sounds like:
* google wants "&access_type=offline" in the url, 
* but okta wants "&scope=...+offline_access"

And it sounded like google might be the "special case/outlier"...

**Comment by philippjfr** [comment]
Really appreciate the detailed writeup, let's get a fix out asap. Would you be willing to submit a PR changing the default scopes for the Google handler?
