### ISSUE TITLE
Hover tooltips get misaligned when using the FastListTemplate.

### ISSUE THREAD

**Issue by OSuwaidi** [holoviz/panel#5816]
#### ALL software version info:
panel=1.3.1
bokeh=3.3.0
python=3.12.0
OS Name: Microsoft Windows 10 Enterprise
OS Version: 10.0.19045 N/A Build 19045
System Type: x64-based PC

#### Description of expected behavior and the observed behavior:
Upon using the `FastListTemplate`, the hover tooltips on a Bokeh scatter plot are completely misplaced/misaligned, where some dots are far off, while others are not as bad, but still mispositioned by a weird offset (all other templates don't have this issue).

You can see it in action in Panel's own "App Galary" in the [Penguin Crossfiltering](https://panel-gallery.pyviz.demo.anaconda.com/penguin_crossfilter) app.

Below is an MRE:
```
import pandas as pd
import numpy as np
import panel as pn
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource

np.random.seed(0)

num_points = 50
ad_spend = np.random.normal(loc=1000, scale=300, size=num_points)
sales = ad_spend * np.random.normal(loc=1.5, scale=0.3, size=num_points)

df = pd.DataFrame({
    'ad_spend': ad_spend,
    'sales': sales
})

p = figure(
    width=1100, height=550,
tooltips=[("@ad_spend", "@sales"), ("TEST", "@sales{0.00}%")]
)

p.scatter('ad_spend', 'sales', source=ColumnDataSource(df), fill_alpha=0.5, size=15)
bokeh_pane = pn.pane.Bokeh(p, sizing_mode='stretch_width')
```
Then whether you use `pn.template.FastListTemplate(title="TEST", main=[bokeh_pane]).servable()` and the end of the script or use:
```
template = pn.template.FastListTemplate(title="TEST")
template.main.append(bokeh_pane)
template.servable()
```
The issue persists in both approaches.

**Comment by Hoxbro** [comment]
Likely this [regression](https://github.com/bokeh/bokeh/issues/13428)  in Bokeh 3.3 will be fixed in the next release (3.3.1).
