### ISSUE TITLE
py3Dmol pane?

### ISSUE THREAD

**Issue by ericmjl** [holoviz/panel#582]
This is following-up on the gitter channel discussion.

I did a hack to get py3dmol working on my local machine.

```python
from IPython.display import HTML
import py3Dmol as pmol
import panel as pn

view = pmol.view(query='pdb:1ubq')
view.setStyle({'cartoon':{'color':'spectrum'}})

pn.pane.HTML(HTML(view.startjs + view.endjs))
```

@philippjfr found a better idea!

**Comment by philippjfr** [comment]
For reference if we could generate HTML output like that easily it would be cleanest:

```
import panel as pn

pn.extension(js_files={'$3Dmol': 'https://3dmol.csb.pitt.edu/build/3Dmol.js'})

pn.pane.HTML("""
<div id="3dmolviewer_UNIQUEID"  style="position: relative; width: 640px; height: 480px">
</div>

<script>
viewer_UNIQUEID = $3Dmol.createViewer($("#3dmolviewer_UNIQUEID"),{backgroundColor:"white"});
$3Dmol.download("pdb:1ubq", viewer_UNIQUEID, {}, function() {
  viewer_UNIQUEID.setStyle({"cartoon": {"color": "spectrum"}});
  viewer_UNIQUEID.render();
})
</script>
""").show()
```

**Comment by philippjfr** [comment]
While this made sense when Panel was just starting out I think domain specific components should probably be maintained externally. So we should document how to wrap something like py3dmol when we document extensions/plugins (see https://github.com/holoviz/panel/issues/506).

**Comment by jbednar** [comment]
Or maybe py3Dmol itself could have a suitable HTML representation, usable in both Jupyter and Panel?
