### ISSUE TITLE
Looks like Latex not working on panel documentation page. I'm having the same issue localy. 

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/panel#5833]
![image](https://github.com/holoviz/panel/assets/31582215/84d0e5d1-058c-48c4-b6d9-1f18f47aa3b3)

https://panel.holoviz.org/reference/panes/Markdown.html#latex-support

I'm failing to have latex rendered in local development, the same way that it appears to be failing on the docs.

**Comment by MarcSkovMadsen** [comment]
+1. Just noticed this too

![image](https://github.com/holoviz/panel/assets/42288570/18d6d1bf-8bc6-4e54-9a9b-55f0d0bf50f9)

**Comment by MarcSkovMadsen** [comment]
Also reported by a user here https://discourse.holoviz.org/t/in-jupyter-lab-the-markdown-panel-cannot-render-latex-syntax-mathjax-imported/6910
