### ISSUE TITLE
404 error in URL for hugging face docker space deployment guide

### ISSUE THREAD

**Issue by metaperl** [holoviz/panel#5836]
The [guide to deploy to huggingface](https://panel.holoviz.org/how_to/deployment/huggingface.html) has a button to deploy that links to this URL - https://huggingface.co/new-space?template=Panel-Org/panel-template

However that URL does not work. In fact, no URL directly to a Panel docker template works.

The best you can do is this link - https://huggingface.co/new-space

**Comment by philippjfr** [comment]
Think it should be: https://huggingface.co/new-space?template=Panel-Org%2Fpanel-template

**Comment by philippjfr** [comment]
Nope, weird.

**Comment by MarcSkovMadsen** [comment]
I can't reproduce. I clicked the link in the first post and it works for me. I've clicked and shift-clicked the button in the tutorial.

![image](https://github.com/user-attachments/assets/132f7e01-b17f-4d1c-bc65-f6a269ddbf36).

Feel free to reopen if you can re-produce issue.
