### ISSUE TITLE
Speed up initial load 3% by not resolving the same paths over and over again

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5852]
I'm on the `main` branch of Panel trying to find performance improvements.

I can see that its quite expensive (3% of app load time) to lookup the `p` attribute on the `theme`. It should not be like that. Its the same path we are loading again and again and again.

![image](https://github.com/holoviz/panel/assets/42288570/f58e120b-21ed-412e-8219-702696d9f661)

The problem is in Param where the `raw_path` is being resolved again and again.

![image](https://github.com/holoviz/panel/assets/42288570/b4626645-d3e5-4d49-9097-526db829f053)

## Reproduce

```python
import panel as pn

N=10

pn.Column(
    *[pn.Row(
        *[pn.pane.Markdown("Hello World") for i in range(N)]
    ) for i in range(N)]
).servable()
```

Run

```bash
 panel serve script.py --autoreload --index script --admin --profiler pyinstrument
```

Open the app 5 times and inspect the pyinstrument report.

![image](https://github.com/holoviz/panel/assets/42288570/087c5643-b6a4-4c83-8aed-4abe396f8b01)

**Comment by MarcSkovMadsen** [comment]
Will be closed by https://github.com/holoviz/param/pull/890

**Comment by philippjfr** [comment]
Fix is upstream, so will close.
