### ISSUE TITLE
Error in Getting Started - Core Concept - Widgets example

### ISSUE THREAD

**Issue by fohria** [holoviz/panel#5858]
There's an error in the first example on creating a widget at: https://panel.holoviz.org/getting_started/core_concepts.html#widgets

#### Description of expected behavior and the observed behavior
In the existing example, we have the following code:

```python
import panel as pn

x = pn.widgets.IntSlider(name='x', start=0, end=100)

def square(x):
    return f'{x} squared is {x**2}'

pn.Row(pn.bind(square, x))
```

I expected a slider to pop up, but there was just the text.

I believe what is intended in this example is for the slider to show, which means we should change the last line to:

```python
pn.Row(x, pn.bind(square, x))
```

- [x] I may be interested in making a pull request to address this

**Comment by MarcSkovMadsen** [comment]
We would ♥️ a Pr
