### ISSUE TITLE
Player widget's Slider option to change callback_policy 

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#587]
Currently I think it's only mouseup

**Comment by philippjfr** [comment]
The slider implementation on Player is completely separate from the bokeh slider, so we'd have to copy the logic over. Then there's the fact that bokeh has deprecated callback_policy and will be switching to the ``value_throttled`` policy instead.

**Comment by philippjfr** [comment]
We now expose the ``value_throttled`` property.

**Comment by philippjfr** [comment]
Nevermind, we do on slider but not on `Player`
