### ISSUE TITLE
ChatFeed tests are a bit flaky

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5877]
Noting it down from https://github.com/holoviz/panel/pull/5875
```python
FAILED panel/tests/chat/test_feed.py::TestChatFeed::test_send_with_respond - TimeoutError: wait_until timed out in 5000 milliseconds
FAILED panel/tests/chat/test_feed.py::TestChatFeedCallback::test_yield_chat_message_stream[None-None] - TimeoutError: wait_until timed out in 5000 milliseconds
FAILED panel/tests/chat/test_feed.py::TestChatFeedCallback::test_yield_chat_message_stream[C-Bob] - TimeoutError: wait_until timed out in 5000 milliseconds
```

**Comment by ahuang11** [comment]
I wonder if we can just make timeout seconds to 10000?

**Comment by ahuang11** [comment]
If I had to take a guess, I suspect it's this that makes it flake:
https://github.com/holoviz/panel/blob/main/panel/chat/feed.py#L437-L439

**Comment by Hoxbro** [comment]
> I wonder if we can just make timeout mseconds to 10000?

It shouldn't take 5 seconds for a chat message to be updated. I think something is not being triggered, if that is the case, we will see the same thing when changing it to 10 seconds.

Running `pytest panel/tests/chat -n logical --dist loadgroup`:

I sometimes get this problem: 
``` task: <Task pending name='Task-4' coro=<ChatFeed._prepare_response() running at /home/shh/Repos/holoviz/panel/panel/chat/feed.py:438> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/tornado/ioloop.py:685]>```

**Comment by ahuang11** [comment]
I think this should be fixed now so closing. Please re-open if not the case.
