### ISSUE TITLE
Button not responsive in jupyter lab

### ISSUE THREAD

**Issue by EduardoLZevallos** [holoviz/panel#5890]
#### ALL software version info
I am on firefox browser, python3.11 on windows 
Package                   Version
------------------------- ------------
anyio                     4.0.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.1.0
Babel                     2.13.1
beautifulsoup4            4.12.2
bleach                    6.1.0
bokeh                     3.3.1
certifi                   2023.11.17
cffi                      1.16.0
charset-normalizer        3.3.2
comm                      0.2.0
contourpy                 1.2.0
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
executing                 2.0.1
fastjsonschema            2.19.0
fqdn                      1.5.1
idna                      3.4
iniconfig                 2.0.0
ipykernel                 6.26.0
ipython                   8.17.2
isoduration               20.11.0
jedi                      0.19.1
Jinja2                    3.1.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.20.0
jsonschema-specifications 2023.11.1
jupyter_client            8.6.0
jupyter_core              5.5.0
jupyter-events            0.9.0
jupyter-lsp               2.2.0
jupyter_server            2.10.1
jupyter_server_terminals  0.4.4
jupyterlab                4.0.9
jupyterlab-pygments       0.2.2
jupyterlab_server         2.25.2
linkify-it-py             2.0.2
Markdown                  3.5.1
markdown-it-py            3.0.0
MarkupSafe                2.1.3
matplotlib-inline         0.1.6
mdit-py-plugins           0.4.0
mdurl                     0.1.2
mistune                   3.0.2
nbclient                  0.9.0
nbconvert                 7.11.0
nbformat                  5.9.2
nest-asyncio              1.5.8
notebook_shim             0.2.3
numpy                     1.26.2
overrides                 7.4.0
packaging                 23.2
pandas                    2.1.3
pandocfilters             1.5.0
panel                     1.3.1
param                     2.0.1
parso                     0.8.3
pexpect                   4.8.0
Pillow                    10.1.0
pip                       23.2.1
platformdirs              4.0.0
pluggy                    1.3.0
prometheus-client         0.18.0
prompt-toolkit            3.0.41
psutil                    5.9.6
ptyprocess                0.7.0
pure-eval                 0.2.2
pycparser                 2.21
Pygments                  2.17.0
pytest                    7.4.3
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2023.3.post1
pyviz_comms               3.0.0
PyYAML                    6.0.1
pyzmq                     25.1.1
referencing               0.31.0
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.13.0
Send2Trash                1.8.2
setuptools                65.5.0
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.6.3
terminado                 0.18.0
tinycss2                  1.2.1
tornado                   6.3.3
tqdm                      4.66.1
traitlets                 5.13.0
types-python-dateutil     2.8.19.14
typing_extensions         4.8.0
tzdata                    2023.3
uc-micro-py               1.0.2
uri-template              1.3.0
urllib3                   2.1.0
wcwidth                   0.2.10
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.4
xyzservices               2023.10.1

#### Description of expected behavior and the observed behavior
I am trying to use the panel button  in jupyter lab .  I created a notebook and am I using the out of the box code for panel.  
However button.clicks is not updating it stays at zero. 

```
button = pn.widgets.Button(name='Click me', button_type='primary')
button
button.clicks

```

![image](https://github.com/holoviz/panel/assets/72849155/16291d16-93f9-4c87-9faf-183f2b2a1f91)

**Comment by MarcSkovMadsen** [comment]
Hi @EduardoLZevallos 

The displayed `button.clicks` value will not automatically update. You will have to rerun the cell to see the latest value.

To automatically display the updated value you have to refer to the parameter `button.param.clicks`. For example like below.

https://github.com/holoviz/panel/assets/42288570/bb7ac4bf-7513-4713-8d35-c283d50597dc

I will close this issue. Feel free to reopen if you still have problems using the button.

**Comment by EduardoLZevallos** [comment]
apologies, the clicks isn't updating even after I rerun the cell.
