### ISSUE TITLE
Logging in with Generic Provider in V1.3+

### ISSUE THREAD

**Issue by simonaay** [holoviz/panel#5897]
Hi friends,

After unifying the access token in latest versions in Panel 1.3+, I started encountering problems with logging in with the Generic Provider feature. I'm not sure if I got to the bottom of this correctly, but what I noticed that the id_token does not contain all user info part of which is a key I pass to USER_KEY when I setup the CLI command. Keep in mind in any version of 1.0 to 1.2.3, the webapp works completely fine and successfully logs in. Would appreciate the help on this matter.

**Comment by philippjfr** [comment]
Would love a little bit more detail on this part:

>what I noticed that the id_token does not contain all user info part of which is a key I pass to USER_KEY when I setup the CLI command

What is contained and what isn't? What precisely isn't working? What are the error messaes?

**Comment by philippjfr** [comment]
Thanks! Could it be related to the scopes? They changed slightly and those partially determine the information available in the user token.

**Comment by philippjfr** [comment]
@simonaay can you maybe list the keys that **are** present in the id_token?

**Comment by simonaay** [comment]
Hi Philip,

Unfortunately, I can't reach my laptop for today. I'll see what I can share tomorrow. On another note, for security reasons I don't I can share everything. I'll see what I can do.

**Comment by simonaay** [comment]
> Thanks! Could it be related to the scopes? They changed slightly and those partially determine the information available in the `id_token`.

I usually use the default parameters of scope, do you think I should reinstate them in `--oauth-extra-params`? In older versions, they were openid and email, right?

**Comment by simonaay** [comment]
Quick updates.

I tried modifying in the `scope` key-value in `--oauth-extra-params` and then modifying directly in the source code. I tried multiple ways, initially I used to rely on the older version's default values, namely "openid" and "email". Following that logic, I kept passing several properties such as offline_access, UsersInfo and Identities. Result: internal server error similar to the aforementioned error.  Example below:

`   @property
    def _SCOPE(self):
        if 'scope' in config.oauth_extra_params:
            return config.oauth_extra_params['scope']
        elif 'PANEL_OAUTH_SCOPE' not in os.environ:
            return ['openid', 'email']
        return [scope for scope in os.environ['PANEL_OAUTH_SCOPE'].split(',')]`

**Comment by simonaay** [comment]
Good morning @philippjfr , let me know if I can help in any way.

**Comment by simonaay** [comment]
Is it possible to change the response type of the authenticator? What I noticed is that the user key in panel v1.2.0 is extracting user_response by fetching user_url. However, in panel v1.3+, the user key is taken directly from the decoded id_token. the self._on_auth method is different where in panel v1.2.0 it is taking the user info in the parameter, but in panel v1.3+, it is taking the id_token in the parameter.

sample code in panel v1.2.0:

`        user_response = await http.fetch(user_url, headers=user_headers)
        user = decode_response_body(user_response)

        if not user:
            return

        log.debug("%s received user information.", type(self).__name__)
        return self._on_auth(user, body['access_token'], body.get('refresh_token'))`

code snippet of panel v1.3.0:

`    def _on_auth(self, id_token, access_token, refresh_token=None, expires_in=None):
        if isinstance(id_token, str):
            decoded = decode_token(id_token)
        else:
            decoded = id_token
            id_token = base64url_encode(json.dumps(id_token))
        

        user_key = config.oauth_jwt_user or self._USER_KEY
        if user_key in decoded:
            user = decoded[user_key]
        else:
            log.error("%s token payload did not contain expected %r.",
                      type(self).__name__, user_key)
            raise HTTPError(400, "OAuth token payload missing user information")
`

**Comment by philippjfr** [comment]
> Is it possible to change the response type of the authenticator? What I noticed is that the user key in panel v1.2.0 is extracting user_response by fetching user_url. However, in panel v1.3+, the user key is taken directly from the decoded id_token. the self._on_auth method is different where in panel v1.2.0 it is taking the user info in the parameter, but in panel v1.3+, it is taking the id_token in the parameter.

Good catch, my assumption was that if the initial request returns an id_token that would be identical to the token returned by the user URL but that is clearly not true. At minimum I will make a PR to check whether the `id_token` returned by the initial request contains the user_key and if not have it fall back to making the request to the user_url.
