### ISSUE TITLE
Tabulator Frozen Column Positions

### ISSUE THREAD

**Issue by CTPassion** [holoviz/panel#5901]
#### Is your feature request related to a problem? Please describe.
I want to freeze two columns in my pn.Widgets.Tabulator but when I do so they are moved to be the first columns of the table.

#### Describe the solution you'd like
I want their position to be customizable or at least remain where they were. They were originally the columns the furthest right representing a TOTAL and EXPECTED value. I would like to freeze them on the right and be able to scroll across the other columns before them.

#### Describe alternatives you've considered
Having them unfrozen and scrolling to the end of the table
**If anyone can think of a workaround for now, I am happy to use that.**

#### Additional context
Frozen:
![image](https://github.com/holoviz/panel/assets/60933427/4d50aaf9-f424-4155-b78a-c4d916d70d1d)

Unfrozen:
![image](https://github.com/holoviz/panel/assets/60933427/4ae970f1-235c-45da-83bb-46ee0a90be77)

**Comment by maximlt** [comment]
Hi @CTPassion, it looks like Tabulator allows to freeze the right most columns (see https://tabulator.info/docs/5.5/layout#frozen-column) so that's a feature that could be implemented in Panel. Do you want to give it a try?

**Comment by CTPassion** [comment]
@maximlt  If I get time I will give it a try :)

**Comment by suryako** [comment]
Ran into this too! @CTPassion did you have any luck? Can give it a try otherwise! :)

**Comment by CTPassion** [comment]
> Ran into this too! @CTPassion did you have any luck? Can give it a try otherwise! :)

Yes I did do it and was easy to implement, I just need to get it in a PR. Will attempt tonight :)
