### ISSUE TITLE
param.Selector action does not update param.String

### ISSUE THREAD

**Issue by MrHenning** [holoviz/panel#593]
First, thanks to the panel team! Panel is a great and really useful package :smiley: 

There may be a bug when changing the value of `param.String` when triggered by `param.Selector` (version `panel-0.6.2`).

Example:
```python
import param
import panel as pn

pn.extension()

class Gui(param.Parameterized):
    text      = param.String('initial text')
    dropdown  = param.Selector(['1', '2', '3'])
    action    = param.Action(lambda x: x.param.trigger('action'), label='Action!')
    
    @param.depends('action', watch=True)
    def onaction(self, **params):
        self.text = 'action!'
        
    @param.depends('dropdown', watch=True)
    def ondropdown(self):
        self.text = 'dropdown!'
        self.param['action'].label = 'dropdown action'

gui = Gui()
pn.Column(gui.param)
```

* I can modifying `param.String` with the action-button.
* I can modify the `param.Selector` with the dropdown
* I *cannot* modify the `param.String` with the dropdown :thinking: 

I don't see any errors in the javascript console.

**Comment by philippjfr** [comment]
Thanks for reporting this. Can't immediately see what's going wrong here.

**Comment by MrHenning** [comment]
I try to modify the `text` param to "dropdown!" with a callback from the dropdown, which is somehow not working for me.

Changing `text` with the action button works.

**Comment by philippjfr** [comment]
Sorry should have been clearer, I can reproduce but couldn't immediately figure out why it doesn't work.
