### ISSUE TITLE
Update thumbnails in Templates section

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5933]
The thumbnails in the Templates section of the Component gallery have not been updated to Panel blue. I.e. they are not giving the right impression.

![image](https://github.com/holoviz/panel/assets/42288570/ea75abac-4877-4b5f-b63e-418cad54d60f)

I've created the thumbnails (500x500), but do not know how to get them updated as they are not part of the repository.

Could you update @philippjfr . Thanks.

![Vanilla](https://github.com/holoviz/panel/assets/42288570/92476373-7d63-4ce1-8d1f-2ec4482742e3)
![React](https://github.com/holoviz/panel/assets/42288570/6478a5b4-761e-4990-b0dd-47a27bf37b6d)
![Material](https://github.com/holoviz/panel/assets/42288570/cfcf66e6-b69b-4e5d-968c-dca73a66491d)
![Golden](https://github.com/holoviz/panel/assets/42288570/9368b15c-4e02-456d-ba64-fd2b014fcb9f)
![FastListTemplate](https://github.com/holoviz/panel/assets/42288570/dbb9aba3-0943-4651-8b63-b2605e0073b0)
![FastGridTemplate](https://github.com/holoviz/panel/assets/42288570/0044274c-b5f2-4004-8f9e-ab86d318c4d3)
![Bootstrap](https://github.com/holoviz/panel/assets/42288570/3298c44a-1b3b-474b-872e-3ec403def743)

**Comment by philippjfr** [comment]
Done, will be deployed on the next release.
