### ISSUE TITLE
panel website app gallery: Secure Connection Failed

### ISSUE THREAD

**Issue by matsvandecavey** [holoviz/panel#5964]
Can't seem to open the apps in the https://panel.holoviz.org/gallery/index.html 
(Firefox nor Chrome)
![image](https://github.com/holoviz/panel/assets/2987662/b087331b-1e69-42a0-ae10-bb8daf2e48ff)

**Comment by philippjfr** [comment]
Thanks, this should be fixed now (at least it is on my end). In general we've had some certificate issues with the deployment which should go away once we upgrade it to the latest version.
