### ISSUE TITLE
Clearly document requirement for pyviz_comms in JupyterLab environment

### ISSUE THREAD

**Issue by MatusGasparik** [holoviz/panel#5965]
#### ALL software version info
- panel: 1.3.4
- param: 2.0.1
- jupyterlab: 4.0.8
- python: 3.11.6
- Browser: Chrome 119.0.6045.199 (arm64)

#### Description of expected behavior and the observed behavior
Creating UI widgets from `param.Parametrized` instances with parameter dependencies declared with the `param.depends` does NOT work - i.e. changing the params in the UI has no effect.

I'm genuinely puzzled by what I'm missing...

#### Complete, minimal, self-contained example code that reproduces the issue

Example from the docs ()

```python
import param
import panel as pn

print('param:', param.__version__)
print('panel:', pn.__version__)

pn.extension()


class Mul(param.Parameterized):
    a = param.Number(5,  bounds=(-100, 100))
    b = param.Number(-2, bounds=(-100, 100))

    @param.depends('a', 'b')
    def view(self):
        return str(self.a*self.b)

    def view2(self):
        return str(self.a*self.b)

prod = Mul(name='Multiplier')
pn.Row(prod.param, prod.view)
```

#### Stack traceback and/or browser JavaScript console output
- no errors

#### Screenshots or screencasts of the bug in action

https://github.com/holoviz/panel/assets/15058994/00dd067e-48ea-4aeb-8c19-fb236ea18726

**Comment by MatusGasparik** [comment]
Thanks, @Hoxbro for the very quick response. The JuperLab is v4.0.8. 

Running `jupter labexternsion list` show no `pyviz_comms`... Am I missing the extension?

**Comment by Hoxbro** [comment]
pyviz_comms is a python package

**Comment by MatusGasparik** [comment]
Thanks, that fixed the issue. I missed this step (but also couldn't find any mention in the panel docs...)

**Comment by Hoxbro** [comment]
I'm not completely sure what is needed as pyviz_comms is a required dependency of panel.

**Comment by philippjfr** [comment]
If you install JupyterLab in a separate env from the kernel that panel is installed in then you need to make sure that pyviz_comms is explicitly installed.
