### ISSUE TITLE
Matplotlib: size of div inside host does not take border styles into account

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5972]
I'm on the main branch of panel

The `div` inside the host of a Matplotlib pane (and probably an HTML/ Markup pane?) does not take styles like borders into account.

This make it hard for users including me to style things with Panel. 

Below I would expect the yellow border to stay inside the black border

![image](https://github.com/holoviz/panel/assets/42288570/ed7a13ed-a285-4495-a7c7-9a34577fb24f)

```python
import panel as pn

from matplotlib.figure import Figure


fig = Figure(figsize=(16,4))
fig.set_facecolor("lightgray")

component = pn.pane.Matplotlib(
    fig,
    height=300,
    sizing_mode="stretch_width",
    styles={"border": "10px solid black"},
    stylesheets=["div {border: 10px solid yellow}"]
)

pn.state.location.sync(component, [
    "height",
])

pn.Column(
    pn.widgets.IntSlider.from_param(component.param.height, value=300, start=100, end=400),
    component,
).servable()
``` 

## Additional Context

I don't understand why the size of the inner `div` needs to be hard coded. Would 100% height and width not work?

If I change it manually it does work

![image](https://github.com/holoviz/panel/assets/42288570/e4a896ff-2f29-4ec1-a162-dbd29b949408)

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/6054
