### ISSUE TITLE
Lots of broken links from 'docs' to 'examples'

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5983]
Streamlit's components are linked, but not Panel's.
https://panel.holoviz.org/how_to/streamlit_migration/chat.html#create-chat-interfaces

We should link them to the corresponding pages like https://panel.holoviz.org/reference/chat/ChatInterface.html

<img width="830" alt="image" src="https://github.com/holoviz/panel/assets/15331990/16f56808-925d-4248-9529-76bf93167dcb">

**Comment by MarcSkovMadsen** [comment]
I can see the links in the source document. But they don't show up in the build documentation.

![image](https://github.com/holoviz/panel/assets/42288570/71d8b1bc-75bb-4286-9201-ecff900f61e2)

**Comment by MarcSkovMadsen** [comment]
Its the same problem other places in the documentation with references from the `docs` to the reference `examples`.

![image](https://github.com/holoviz/panel/assets/42288570/6e388e9a-50ba-41d4-8c52-6a6d3e43190a)

![image](https://github.com/holoviz/panel/assets/42288570/2dcbd3cb-18e9-45d3-b6b8-1e927d66ef72)

**Comment by MarcSkovMadsen** [comment]
Here is another example of it not working

![image](https://github.com/holoviz/panel/assets/42288570/e302ffdd-546d-48e5-a88b-3717943faebf)

![image](https://github.com/holoviz/panel/assets/42288570/4f9774c3-ad4c-4f18-8fab-109dd9674258)
