### ISSUE TITLE
Add a default `Help` avatar to ChatFeed

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#5984]
In a lot of our [examples](https://github.com/holoviz-topics/panel-chat-examples/blob/main/docs/examples/langchain/langchain_with_memory.py#L19-L21), I do this:
```python
chat_interface = pn.chat.ChatInterface(callback=answer, callback_user="OpenAI")
chat_interface.send(
    "Ask me anything about Python libraries!", user="System", respond=False,
)
```

Instead, maybe we can add `intro_message`, `intro_user`, `intro_avatar` params?
```python
chat_interface = pn.chat.ChatInterface(callback=answer, callback_user="OpenAI", intro_message="Ask me anything about Python libraries!", intro_user="System")
```

Any thoughts on this @MarcSkovMadsen?

**Comment by MarcSkovMadsen** [comment]
My recommendation would be to add intro messages via the `objects` parameter.

**Comment by ahuang11** [comment]
We should probably have an `Instructions` user or `Welcome` user

**Comment by ahuang11** [comment]
Done in https://github.com/holoviz/panel/pull/6311
