### ISSUE TITLE
Pydeck/DeckGL to work with Mapbox Standard style

### ISSUE THREAD

**Issue by mayonnaisecolouredbenz7** [holoviz/panel#5991]
https://docs.mapbox.com/api/maps/styles/

Right now PyDeck/DeckGL works perfectly with the classic Mapbox styles (some versions need to be slightly different to the latest ones on the above page, for example Satellite streets works with v11 but not v12)

However I can't seem to get it working with the Mapbox Standard Style.   (mapbox://styles/mapbox/standard)

Minimal example below:
```
view_state =pdk.ViewState(
            latitude=round(latlon.y, 4),  #This I programmatically set
            longitude=round(latlon.x, 4),
            zoom=zoom,
            max_zoom=19,
            pitch=30,
            bearing=0,
            transition_duration=1500,
        )

 self.r = pdk.Deck(
            api_keys={"mapbox": os.environ["MAPBOX_KEY"]},
            layers=[],
            initial_view_state=view_state ,
            map_style="mapbox://styles/mapbox/standard",   #THIS STYLE NOT WORKING
            views=[pdk.View(type="MapView", controller={
                            "doubleClickZoom": True})],
        )

self.deck_gl = pn.pane.DeckGL(
            self.r, tooltips=geojson_tooltip, sizing_mode="stretch_both"]
        )
```
The above works with mapbox://styles/mapbox/satellite-streets-v11 for example.

Obviously the Mapbox website states that there is a whole migration guide to get this working, so might not be such a straight fix/enhancement.  But would be great to be able to use that style

**Comment by mayonnaisecolouredbenz7** [comment]
Futher investigation:
![image](https://github.com/holoviz/panel/assets/38597661/33abb87c-ca95-4a68-b5a0-b33d9f4634d5)

https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css
I have tried to use the mapbox css above as a stylesheet on the pn.pane.DeckGL object and through pn.config.css_files, but no luck yet

**Comment by mayonnaisecolouredbenz7** [comment]
After working on this longer than I want to admit the solution was rather simple:

```
mapboxgl_js = 'https://api.mapbox.com/mapbox-gl-js/v3.0.1/mapbox-gl.js'
mapboxgl_css = 'https://api.mapbox.com/mapbox-gl-js/v3.0.1/mapbox-gl.css'

pn.extension( deckgl', js_files={'mapboxgl': mapboxgl_js}, css_files=[mapboxgl_css])
```

**Comment by philippjfr** [comment]
Thanks @mayonnaisecolouredbenz7, want to make a quick PR to update those files in panel/models/deckgl.py?

**Comment by mayonnaisecolouredbenz7** [comment]
Thanks @philippjfr .  Would have loved to contribute a PR. Looks like it was done overnight my timezone so was already done by the time I woke up.   Next time..

**Comment by philippjfr** [comment]
Yes sorry about that, was pushing to get a release out.
