### ISSUE TITLE
Supplying a authorize_callback that returns False results in a 500 internal server error

### ISSUE THREAD

**Issue by mitulb** [holoviz/panel#6016]
#### ALL software version info
panel==1.3.4
bokeh==3.3.2

#### Description of expected behavior and the observed behavior
When setting an authorize_callback  that returns False, there is a bug that throws a TypeError instead of returning the rendered auth_template
#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

def authorize(user_info):
    return False

pn.config.authorize_callback = authorize

pn.Row("hello world").servable()

```

```
panel serve test.py --port 5000 --dev --login-endpoint="login" #plusinteral generic oidc codig
```

#### Stack traceback and/or browser JavaScript console output

```TypeError: write() only accepts bytes, unicode, and dict objects```
#### Screenshots or screencasts of the bug in action

- [ x ] I may be interested in making a pull request to address this

**Comment by philippjfr** [comment]
Thanks for the fix!
