### ISSUE TITLE
Tabler Icon no longer hosts static URLs for its icons so ChatReactionIcons is broken

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#6022]
E.g. the following no longer exists: https://tabler.io/icons/static/tabler-icons/icons/heart.svg 

I was looking at how Bokeh does it for its buttons, but I don't fully understand how to implement it using ReactiveHTML. I think it's loading a CSS stylesheet and using a font class for it.
https://github.com/bokeh/bokeh/blob/main/bokehjs/src/lib/models/ui/icons/tabler_icon.ts

**Comment by mattpap** [comment]
Icons are inlined into bokehjs' bundles, see https://github.com/bokeh/bokeh/blob/branch-3.4/bokehjs/src/less/icons.less.

**Comment by MarcSkovMadsen** [comment]
A simple solution would be to host the icons at the holoviz cdn. And continue to use urls. @ahuang11

**Comment by ahuang11** [comment]
So to clarify, I would add:
https://unpkg.com/@tabler/icons@latest/iconfont/tabler-icons.min.css

To:
https://github.com/holoviz/panel/tree/main/panel/dist/bundled/

Like Tabulator?
https://github.com/holoviz/panel/tree/main/panel/dist/bundled/datatabulator/tabulator-tables%405.5.0/dist/css

**Comment by ahuang11** [comment]
Okay, after discussing with Marc, I believe that we need to build a Panel TS model around Bokeh's icons or else we have to host all of the available tabler icons.

**Comment by ahuang11** [comment]
I was thinking of using the existing Toggle icon param, but it seems like I can't dynamically update the icon
```python
import panel as pn
pn.extension()

toggle = pn.widgets.Toggle(icon="heart", width=25, height=25, stylesheets=["""
    :host(.solid) .bk-btn.bk-btn-default {
        background-color: transparent;
        border-color: transparent;
        margin: 0px;
        padding: 0px;
        outline: none;
    }

"""])
toggle

toggle.icon = "thumb-up"

```
