### ISSUE TITLE
Unwanted logs from pandas.Styler in Panel 1.3.4

### ISSUE THREAD

**Issue by CTPassion** [holoviz/panel#6040]
#### ALL software version info
panel == 1.3.4
pandas == 2.1.4
python == 3.11.6

#### Description of expected behavior and the observed behavior

Observed logs in console when applying `style.map` to a panel tabulator

> (<function Styler.map.<locals>.<lambda> at 0x000002AF6727D760>, (<function LiveStatusPage._status_text_colour at 0x000002AF66F07600>, ['ALERT_STATUS']), {})
> (<function Styler.map.<locals>.<lambda> at 0x000002AF6727D760>, (<function LiveStatusPage._status_text_colour at 0x000002AF66F07600>, ['ALERT_STATUS']), {})
> (<function Styler.map.<locals>.<lambda> at 0x000002AF6727D760>, (<function LiveStatusPage._status_text_colour at 0x000002AF66F07600>, ['ALERT_STATUS']), {})

These are only present in **PANEL 1.3.4**. If I rollback to 1.3.2 they are not there.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import pandas as pd
import panel as pn


def callback_method(val):
    return f"color: red;"


table = pn.widgets.Tabulator()


def some_method():
    table.value = pd.DataFrame({
    "NODE_NUMBER": [1, 2, 3, 4, 5, 6, 7, 8],
    "PARENT_NODE_NUMBER": [0, 1, 1, 1, 3, 5, 6, 6],
    })
    table.style.map(
        callback_method
    )
    return table


def tab_show():
    some_method()
    return pn.Column('#### Table', table)


tab_show().show()
```

#### Stack traceback and/or browser JavaScript console output

> Launching server at http://localhost:64744
> (<function Styler.map.<locals>.<lambda> at 0x00000196BB43FD80>, (<function callback_method at 0x000001969DFAE200>, None), {})

#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this

**Comment by philippjfr** [comment]
Thank you @CTPassion. This has been fixed and I'll release 1.3.5 today.
