### ISSUE TITLE
Not compatible with memray 1.11.0 - RuntimeError

### ISSUE THREAD

**Issue by bsdz** [holoviz/panel#6045]
The recent release of [memray 1.11.0 utilizes textual](https://github.com/bloomberg/memray/releases/tag/v1.11.0). When one uses this version for profiling panel server the following error is raised: "RuntimeError: asyncio.run() cannot be called from a running event loop".

Textual has some issues when embedded in apps with their own event loop. A similar issue occurs when [embedding textual in a Jupyter Notebook](https://github.com/Textualize/textual/issues/615).  I tried to fix textual and submitted [this PR](
https://github.com/Textualize/textual/pull/3868) but it appeared there were deeper issues.

When I pinned my memray to 1.10.0, then profiling worked.

**Comment by philippjfr** [comment]
This was fixed when we added Textual support.
