### ISSUE TITLE
FileDownload text not aligned center vertically when changing the height.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6093]
For some unknown reason the `FileDownload` button has a different height than other buttons. This makes it hard to get things to align and look beautiful.

And if you change the height, the text does not align center vertically.

```python
import panel as pn

pn.extension()

download = pn.widgets.FileDownload()
download_height = pn.widgets.FileDownload(height=31)
button = pn.widgets.Button(name="Click Me")

pn.Row(
    download, download_height, button
).servable()
```

![image](https://github.com/holoviz/panel/assets/42288570/3ceab7a1-b0a1-4feb-bf20-a8f5b1d783c2)

## Additional Context

I would be using this with the `Fast` templates. So a solution should also work there.

If someone has a (css) workaround, then that would also be appreciated for now.

**Comment by philippjfr** [comment]
Found the issue, fix coming in 1.3.6.
