### ISSUE TITLE
FileDownload css not working with icons

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6107]
#6101 made it possible to adjust the `height` og the `FileDownload`. Unfortunately the `icon` and `text` is no longer aligned horizontally.

![image](https://github.com/holoviz/panel/assets/42288570/d250d2d1-8275-4233-9fde-232d86a791fa)

```python
import panel as pn

pn.extension(design="bootstrap")

n=4

layout=pn.Column()

for i in range(n):
    row = pn.Row()
    layout.append(row)
    for j in range(n):
        download = pn.widgets.FileDownload(height=50+25*j, width=125+25*j, file=__file__, icon="download", button_type="primary")
        row.append(download)

layout.servable()
```

**Comment by monodera** [comment]
I had the same issue after upgrading to 1.3.6. It seems that `display: inline;` in `.bk-btn a` element will fix the issue.

```python
import panel as pn

pn.extension(design="bootstrap")

n = 4

stylesheet = ".bk-btn a {display: inline;}"

layout = pn.Column()

for i in range(n):
    row = pn.Row()
    layout.append(row)
    for j in range(n):
        download = pn.widgets.FileDownload(
            height=50 + 25 * j,
            width=125 + 25 * j,
            file="script.py",
            icon="download",
            button_type="primary",
            stylesheets=[stylesheet],
        )
        row.append(download)

layout.servable()
```

![Screenshot 2023-12-21 at 13 39 19](https://github.com/holoviz/panel/assets/90394/fbb6262b-bc44-4c78-8f9c-4ab2acc69c92)

I don't know much about css, but maybe a better combination exists. FYI, `inline-block` does not work as expected `inline flex` may also be okay.

**Comment by philippjfr** [comment]
Thank you both. Will try to get a 1.3.7 release out early next week.
