### ISSUE TITLE
navbar toggle icon for boostrap template is dark

### ISSUE THREAD

**Issue by mayonnaisecolouredbenz7** [holoviz/panel#6109]
When using the bootstrap template the nav bar toggle icon is black which does not work with a dark header color

![image](https://github.com/holoviz/panel/assets/38597661/f37abb78-fa6c-4d2f-80c1-4a2053ae8bec)

as opposed to material template where it is white:
![image](https://github.com/holoviz/panel/assets/38597661/cfd6e965-3382-48c1-bbe2-2349fc66099d)

and fast template:
![image](https://github.com/holoviz/panel/assets/38597661/30ea128d-192f-45c5-890d-4bfc5547a2c9)

Not sure if this is by design, but I wonder if there was a way to set this?

**Comment by maximlt** [comment]
Hi @mayonnaisecolouredbenz7, I doubt this is by design so it might well be a bug :) Would you be interested in trying to fix it?

**Comment by mayonnaisecolouredbenz7** [comment]
See PR #6111

**Comment by cdeil** [comment]
@philippjfr - I think you fixed this old issue in #6562 . Close?

**Comment by philippjfr** [comment]
Yep thanks!
