### ISSUE TITLE
Widgets misaligned when a HoloViews holomap is displayed with a Row widget layout

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#6110]
`HoloViews.widgets_from_dimensions` set a bunch of margins, it seems they're not adapted for when the widget layout is a `Row`.

https://github.com/holoviz/panel/blob/7f25eb140deaade949560233d2ae0798e02428af/panel/pane/holoviews.py#L610-L619

```python
import numpy as np
import random
import panel as pn
import hvplot.pandas
import pandas as pd

df = pd.DataFrame(dict(
    x=np.random.random(50),
    y=np.random.random(50),
    cat1=random.choices('abc', k=50),
    cat2=random.choices('XYZ', k=50),
))
plot = df.hvplot.scatter(groupby=['cat1', 'cat2'])
pn.pane.HoloViews(plot, widget_layout=pn.Row, widget_location='bottom')
```

<img width="721" alt="image" src="https://github.com/holoviz/panel/assets/35924738/34d1f188-98ee-4ba9-b413-8f4989cdd2bc">

xref: https://github.com/holoviz/hvplot/pull/1199

**Comment by philippjfr** [comment]
This was fixed.
