### ISSUE TITLE
ChatInterface Regression:  value must be an instance of Future, not Future pending

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6118]
I just upgraded from Panel 1.3.4 to 1.3.6. I did not change my code. I get the exception.

![image](https://github.com/holoviz/panel/assets/42288570/b725f051-9ad8-4e4d-8dd8-687a751ad056)

```bash
Encountered ValueError("ClassSelector parameter 'ChatInterface._callback_future' value must be an instance of Future, not <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /opt/conda/lib/python3.11/asyncio/futures.py:387]>."). Set callback_exception='verbose' to see the full traceback.
```

If I downgrade to Panel 1.3.4 it works again.

I will make a minimum, reproducible example when I get back to work.

**Comment by philippjfr** [comment]
Guess we're having a 1.3.7, @ahuang11 any ideas?

**Comment by MarcSkovMadsen** [comment]
My work app is working in the same way as https://github.com/run-llama/llama-hub/blob/e621be95150d15ae9048c1a521c5f5c9821edbb4/llama_hub/llama_packs/panel_chatbot/app.py. Just populating the vector store from a local folder instead of github.

**Comment by ahuang11** [comment]
The easy fix would be changing callback future into param.Parameter since I don't see the difference between future pending and future type

**Comment by ahuang11** [comment]
If we're releasing 1.3.7, would also like https://github.com/holoviz/panel/pull/6105 in.
