### ISSUE TITLE
Matplotlib pane cannot be instantiated empty

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#6121]
```
import panel as pn
pn.extension()

# pn.pane.HoloViews() this works

pn.pane.Matplotlib()
```

<img width="1001" alt="image" src="https://github.com/holoviz/panel/assets/15331990/63ec929e-4526-48fe-b3af-5d88bda368cd">

Also results in a misleading error
<img width="880" alt="image" src="https://github.com/holoviz/panel/assets/15331990/0f7ed312-8ee3-43d7-819f-137e52245a1a">

**Comment by philippjfr** [comment]
Reminder to set labels on your issues @ahuang11 🙂
