### ISSUE TITLE
ImportError: cannot import name 'ReactiveExpr' from 'panel.pane'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6124]
If I run the pyodide code at https://panel.holoviz.org/how_to/wasm/sphinx.html I get

![image](https://github.com/holoviz/panel/assets/42288570/ddbafe6a-764a-48b1-ab2a-7f332b8de844)

```bash
ImportError: cannot import name 'ReactiveExpr' from 'panel.pane'
```

**Comment by philippjfr** [comment]
Yep, I broke all our pyodide docs in 1.3.6 because the pyodide module was currently not testable. I've already refactored it so we can properly add unit tests so such a regression does not re-occur.

**Comment by MarcSkovMadsen** [comment]
Works now. Closing
