### ISSUE TITLE
panel==1.3.5 broke the ChatFeed placeholder

### ISSUE THREAD

**Issue by pmeier** [holoviz/panel#6139]
This is coming from [Ragna](https://ragna.chat) `main` with the only change artificially slowing down the callback.

## `panel==1.3.4`

[Screencast from 2023-12-29 11-50-43.webm](https://github.com/holoviz/panel/assets/6849766/9d333950-dbf3-4a63-9fa9-32089c146fe4)

## `panel>=1.3.5`

[Screencast from 2023-12-29 11-51-53.webm](https://github.com/holoviz/panel/assets/6849766/ee36fa74-cab4-4da9-8d6e-d561bb219dcf)

**Comment by ahuang11** [comment]
Thanks for reporting this! I believe it's fixed with https://github.com/holoviz/panel/pull/6105
