### ISSUE TITLE
Fix datetimepicker for most common Pangeo xarray use case

### ISSUE THREAD

**Issue by rsignell-usgs** [holoviz/panel#6143]
There are a bunch of [open issues for datetimepicker](https://github.com/holoviz/panel/issues?q=is%3Aissue+is%3Aopen+datetimepicker) and it seems like many of them could be summarized by making one of the most common Pangeo xarray use cases work -- simply using a datetimepicker instead of a slider or select when selecting n-dimensional array output.  

For example, make this simple xarray tutorial dataset work:
``` python
import hvplot.xarray  
import xarray as xr
import panel as pn
pn.extension()

ds = xr.tutorial.open_dataset('air_temperature')
viz = ds['air'].hvplot(x='lon', y='lat')
pn.panel(viz, widgets={'time': pn.widgets.DatetimePicker})    
```

**Comment by amsnyder** [comment]
Our project is planning to make several panel apps for datasets with large time series, so this would be helpful for our team as well.

**Comment by ahuang11** [comment]
Thanks for raising this! I made changes in #6152 to fix this and other various DatetimePicker functionality. If you have the time, I'd appreciate help testing that PR!
![image](https://github.com/holoviz/panel/assets/15331990/a18857b6-07df-4734-92b9-4405eea81b84)

**Comment by rsignell** [comment]
@ahuang11 , that's awesome!   
I tried the above and it works, but how do you get the whole calendar to appear in a notebook cell?
![Screenshot 2024-01-03 164404](https://github.com/holoviz/panel/assets/125569335/e5da85a6-7ddf-4e94-82ae-339c3a9652c9)

**Comment by ahuang11** [comment]
Not sure why the CSS is not updated in jupyter lab cells. Maybe when it's released, it'll be fixed? Or clearing of cache?

<img width="1162" alt="image" src="https://github.com/holoviz/panel/assets/15331990/39b1b20e-9e95-4cf7-9079-33f30d9312dc">

**Comment by rsignell** [comment]
@ahuang11 I tried [following this procedure from @philippjfr](https://discourse.holoviz.org/t/blank-output-with-latest-holoviz-from-conda-forge/2276/11?u=rsignell), which usually clears up my strange holoviz display issues. 

Didn't work this time though.  When I run the cell and click on the widget, I can only just barely see the top of the calendar and can't figure out how to get the rest to display:
![Screenshot 2024-01-04 100943](https://github.com/holoviz/panel/assets/125569335/38c613ea-b449-40e3-9822-fc38b8591692)

**Comment by ahuang11** [comment]
Yeah I have the same issue; not sure how to refresh the notebook.

**Comment by rsignell** [comment]
This works for me.  Does it need a review from a professional or can it be merged?

**Comment by ahuang11** [comment]
Probably needs a review from @philippjfr

**Comment by rsignell** [comment]
@ahuang11, I was so happy to see this arrive in the latest release of Panel! 

Still a bit confused about how to use it properly though: https://youtu.be/VHv-EHI0rc0

**Comment by ahuang11** [comment]
I think you need to unfocus the calendar to have it updated.

**Comment by rsignell** [comment]
The data in the example is only available at [0,6,12,18] hours of the day, but the picker allows other times, and does non-intuitive things when non-valid times are selected.  

I tried to figure out how to set `enabled-dates`, but wasn't sure how to do that starting with `ds.time.values` which are datetime64

**Comment by ahuang11** [comment]
Right, at the moment there's no way to do that either to disable other times. As a workaround, you can write a function to get the nearest time (but you wouldn't be able to use `pn.panel()` alone; you'd have to use `pn.bind()`.


Can you submit a separate feature request for that?

**Comment by rsignell** [comment]
A feature request to allow greying out unavailable times, right?

**Comment by rsignell** [comment]
Got it
