### ISSUE TITLE
Panel >=1.2.2 messes out webpage scrolling in the reactive API

### ISSUE THREAD

**Issue by julioasotodv** [holoviz/panel#6180]
## ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

- `panel>=1.2.2` (it does not happen with previous versions)
- Any modern version of Firefox, tested from `99.0` to `121.0`; also happens in Safari `17.2.1`. But it does not happen in Chrome nor Opera for instance

## Description of expected behavior and the observed behavior

For some reason, using a widget that modifies some pane is making the browser's scrollbar go directly to the widget location; changing user's viewport in a Panel app

## Complete, minimal, self-contained example code that reproduces the issue

We can create a file called `test.py`:

```python
import random

import panel as pn
pn.extension()

import matplotlib
import matplotlib.pyplot as plt

# Reactive function for pn.bind:
def plot_points(n):
    x = [random.uniform(0, 10) for i in range(n)]
    y = [random.uniform(0, 10) for i in range(n)]
    fig = plt.Figure()
    ax = fig.add_subplot()
    ax.scatter(x, y)
    return pn.pane.Matplotlib(fig, 
                              width=500,
                              tight=True)

# Widget:
selector_n = pn.widgets.IntSlider(start=2, end=100)

# We put both the widget and the chart in a column.
# I also include a tall Spacer to make the app tall enough
# to be scrollable:
app = pn.Column(pn.Spacer(width=300, height=3000, styles={"background":'#BCA600'}),
                selector_n, 
                pn.bind(plot_points, n=selector_n))
app.servable()
```

Which we can run with:
```sh
panel serve test.py
```

## Stack traceback and/or browser JavaScript console output
No warnings nor error tracebacks appear in any web browser's console

## Screenshots or screencasts of the bug in action
You can see the weird behavior in the following GIF:

![test_bug_panel](https://github.com/holoviz/panel/assets/20630819/86e6bcbe-cce1-4122-b919-ec5af1782a3b)

Thank you!

**Comment by JulienLrx** [comment]
Same problem here for panel >= 1.2.2 on all browser i've tested so far (latest chrome, edge, firefox and opera)

**Comment by philippjfr** [comment]
Seems very annoying, I indeed was not able to reproduce in Chrome but Firefox and Safari were affected. Investigating with the profiling indicates this happens immediately after the slider is updated and not when the matplotlib plot is redrawn which was what I had expected.
