### ISSUE TITLE
Altair add_selection is deprecated

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6197]
When I run the Getting_Started.ipynb notebook on panelite I get 

```python
/lib/python3.11/site-packages/altair/utils/deprecation.py:65: AltairDeprecationWarning: 'add_selection' is deprecated. Use 'add_params' instead.
  warnings.warn(message, AltairDeprecationWarning, stacklevel=1)
```

![image](https://github.com/holoviz/panel/assets/42288570/e691b946-1a0a-4ebe-b5e8-d00a9295ed6e)

**Comment by philippjfr** [comment]
This was already updated in the `Altair/Vega` reference notebook, we just have to update this example as well.
