### ISSUE TITLE
Static assets URL parser wrong

### ISSUE THREAD

**Issue by skaller** [holoviz/panel#6219]
When using say 
```
--static-dirs assets=somedir
```
then the URL 
```
assets/index.html
```
works fine, and correctly finds the file
```
somedir/index.html
```
as it should. However the URL
```
assets/subdir/index.html
```
fails with a 403 forbidden error and the message something like
```
somedir/subdir is not a file
```

It seems the URL parser is broken: it only works for one level. It should link to
```
somedir/subdir/index.html
```
and when the URL in the browser is modified by adding `/index.html` it serves just fine.

**Comment by philippjfr** [comment]
Cannot reproduce this, I just ran `panel serve app.py --static-dirs assets=doc` and then placed an `index.html` at `doc/_static/index.html`, which loaded just fine:

<img width="466" alt="Screenshot 2024-01-18 at 09 50 36" src="https://github.com/holoviz/panel/assets/1550771/0b99c4aa-2575-4d3e-acd1-becf6c48c1d6">

**Comment by skaller** [comment]
interesting .. let me see if I can get some screenshots from my client (and a version number .. how do you get that?)

**Comment by skaller** [comment]
ok we have Panel serve 1.2.3 .. installed using Conda ..

**Comment by skaller** [comment]
AH! You aren't doing the same test, that's why you're not reproducing it perhaps. You're putting the URL in the browser search line. That works for us too. What fails is if the URL is in an `<a href="...">...</a>` tag and you click on it.

In our case that tag is generated by Quarto blog generator, and the click works just fine if we start with the browser pointing at the top level of the blog (i.e. the index page) as a file. But if we point the browser at a the http connection running Panel, we can go into `assets/index.html` just fine, but clicking on the linking *in* that page fails.

I'll send more data shortly. We spent all night here trying to get conda-forge to install the latest version. The base `conda` package is 1.2.3 which is way out of date.

**Comment by skaller** [comment]
Just to be clear, the top level entry into `assets` works fine but a link in *that* file to an indiex.html in a subdirectory fails with a 403 and the web server reports, on the command line, that the directory is not a file .. leaving out the `index.html`. The browser search line *also* shows the wrong link, i.e. without the `index.html` at the end. I don't understand this because the construction of the link is done by the browser but BOTH safari and chrome fail the same way.

**Comment by skaller** [comment]
It could be our CDM system. We have only tried with the live online service, we haven't tried with localhost. I'll get my client to test that, Thanks for holding!

**Comment by skaller** [comment]
I have made a simple test case, and it works just fine. But it fails with the quarto generated html. On the other hand the quarto html works fine if its index is the entry. None of this makes any sense to me, since the browser should just be adding a prefix to the anchor href, and the quarto anchor's href is, in my opinion, correct. 

In any case I apologise for raising this issue, and thank you for your help, and am now closing it.
