### ISSUE TITLE
pn.template attribute not found when lazy loading panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6292]
panel==1.3.8

As Panel takes ~2secs to import I would like to lazy load it in one of my packages. This package provides different utility functions. Only some are panel related.

Lazy loading of modules in Python is defined here https://docs.python.org/3/library/importlib.html#implementing-lazy-imports. When I use that I get an `AttributeError` because the attribute `template` is not defined on `panel`. Without lazy loading this works.

## Minimum reproducible example

`lazy_loader.py`

```python
import importlib.util
import sys

def lazy_import(name):
    spec = importlib.util.find_spec(name)
    loader = importlib.util.LazyLoader(spec.loader)
    spec.loader = loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    loader.exec_module(module)
    return module

pn = lazy_import("panel")
# import panel as pn

def extension():
    return pn.extension()
```

`app.py`

```python
from lazy_loader import extension
import panel as pn

extension()

pn.template.FastListTemplate(title="Hello", main=["world"]).servable()
```

```bash
panel serve app.py --autoreload --index app
```

![image](https://github.com/holoviz/panel/assets/42288570/38eb6479-88ba-4e4e-a256-f817b9226ba5)
¨

```bash
AttributeError: module 'panel' has no attribute 'template'

Traceback (most recent call last):
  File "/home/jovyan/repos/aw-lib/.venv/lib/python3.11/site-packages/bokeh/application/handlers/code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "/home/jovyan/repos/aw-lib/app.py", line 6, in <module>
    pn.template.FastListTemplate(title="Hello", main=["world"]).servable()
    ^^^^^^^^^^^
AttributeError: module 'panel' has no attribute 'template'
```

**Comment by Hoxbro** [comment]
What happens if you, do this?

``` python
from lazy_loader import extension, pn

extension()

pn.template.FastListTemplate(title="Hello", main=["world"]).servable()

**Comment by MarcSkovMadsen** [comment]
The problem is that `template` is not imported in `__init__.py` :-) I'm working on a PR.

**Comment by MarcSkovMadsen** [comment]
This pytest will replicate issue

```python
import importlib.util
import sys

def lazy_import(name):
    spec = importlib.util.find_spec(name)
    loader = importlib.util.LazyLoader(spec.loader)
    spec.loader = loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    loader.exec_module(module)
    return module

def test_pn_template():
    lazy_import("panel")
    import panel as pn
    assert hasattr(pn, "template")
```

**Comment by MarcSkovMadsen** [comment]
## Additional Context: Also issue for static analysis

The cause is that `template` is not imported in `__init__`. This also means that static analysis cannot discover it and an error is highlighted like below.

![image](https://github.com/holoviz/panel/assets/42288570/6f9deace-28eb-42c0-83e9-3489d142fdef)

**Comment by MarcSkovMadsen** [comment]
Thanks @philippjfr 

Unfortunately I start seeing more of these issues. If I lazy import holoviews then it starts failing because of below.

![image](https://github.com/holoviz/panel/assets/42288570/65e52272-0267-4ab7-8c59-163ad59a25c7)

Do you think these are issues that can and should be solved? Or are they not issues and I should not try to use lazy loading?

**Comment by Hoxbro** [comment]
Lazy loading is tricky. Maybe try to take a look at how polars does it here: https://github.com/pola-rs/polars/blob/main/py-polars/polars/dependencies.py
