### ISSUE TITLE
Param subjobject doesnot close when changing object

### ISSUE THREAD

**Issue by slamer59** [holoviz/panel#630]
panel version '0.6.0'
param version '1.9.1'
Espected behavior :
Close sub-widget changing object (Circle or NGon) since it's no more related.

The code is the one from documentation:
https://panel.pyviz.org/gallery/param/param_subobjects.html#gallery-param-subobjects

![bug-subobj](https://user-images.githubusercontent.com/25283272/64025327-bebc5280-cb3c-11e9-9c1e-108508685e06.gif)

**Comment by jbednar** [comment]
That does seem confusing.
