### ISSUE TITLE
FileDownload widget height issues

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#6316]
Panel 1.3.8

The parts of the button that don't hold text have a default height which is too small. The central part has dimensions that fit the label.

See example below (with "success" button type to make it more visible):

```python
import panel as pn

filedownload = pn.widgets.FileDownload(label='Download', button_type='success', width=200)

pn.template.FastListTemplate(main=[filedownload]).servable()
```

![image](https://github.com/holoviz/panel/assets/49269671/cae08aa6-dc52-49a6-984d-47812498c707)

Workaround: explicitly setting the height, here it would be 28 pixels.

**Comment by Hoxbro** [comment]
I think this was introduced in https://github.com/holoviz/panel/pull/6133

**Comment by TheoMathurin** [comment]
In fact the FileDownload button seems to have issues with other templates and without a template too (height appears somewhat small to me, one could expect it to have the same default height as the Button widget).

![image](https://github.com/holoviz/panel/assets/49269671/40893650-55d1-448a-aaa5-3154bdcb914d)
