### ISSUE TITLE
Loading Spinner does not respect value kwarg

### ISSUE THREAD

**Issue by singharpit94** [holoviz/panel#6321]
I am using panel 1.3.8 and notice that the LoadingSpinner does not respect value kwarg

```
import panel as pn
pn.extension()
idle = pn.indicators.LoadingSpinner(width=100, height=100, bgcolor='dark', value=True, color='primary')
idle
```
The above code should display a non spinning indicator but it does not.

![loadingspinner](https://github.com/holoviz/panel/assets/7591673/ddb423f7-0a31-4f54-a9f5-dd1d3647e4d4)

**Comment by Hoxbro** [comment]
I think you meant to pass `value=False`.

**Comment by singharpit94** [comment]
> I think you meant to pass `value=False`

Yes, my bad, even with `value=False` I can see it spinning, thats the actual issue.
