### ISSUE TITLE
AutocompleteInput items jumps by 2 on single arrow key stroke

### ISSUE THREAD

**Issue by singharpit94** [holoviz/panel#6322]
I am using panel 1.3.8 and noticed that the items in autocomplete jumps by 2 on single key down. Refer below code snippet and gif

```
values = ['a', 'ab', 'ac', 'ad', 'ae']
pn.widgets.AutocompleteInput(
            name='Test',
            options=values,
            restrict=True,
            case_sensitive=False,
            width=300,
            min_characters=1,
            placeholder='Enter value here',
        )

```

![autocompleteinput](https://github.com/holoviz/panel/assets/7591673/4760a9af-d38b-465d-b8cc-92c4a9f96005)

**Comment by Hoxbro** [comment]
Can you try upgrading to the latest bokeh 3.3.4?

**Comment by Hoxbro** [comment]
This was fixed in  https://github.com/bokeh/bokeh/issues/13574.

I will close the issue, if you still have a problem after upgrading Bokeh, please reopen.
