### ISSUE TITLE
Feature request: Add support to `expander` layout

### ISSUE THREAD

**Issue by OSuwaidi** [holoviz/panel#6336]
I've been looking through Panel's docs for an `expander` like layout, similar to the one that [streamlit ](https://docs.streamlit.io/library/api-reference/layout/st.expander) supports, but I couldn't find any under Panel's [layouts](https://panel.holoviz.org/api/panel.layout.html#layout-package) section.

Natively supporting the `expander` layout will deem very helpful as it allows users to easily show/hide multi-media elements in a very intuitive way.

(Sidenote; the following Panel layout components: `HSpacer`, `ListLike`, `ListPanel`, `Panel`, `Spacer`, `VSpacer` are all not mentioned under [Layouts ](https://panel.holoviz.org/reference/index.html#layouts) in the "Component Gallery" section. `Spacer` specifically is really powerful!)

**Comment by ahuang11** [comment]
I think you are looking for `pn.Card`
