### ISSUE TITLE
`pn.widgets.TextAreaInput` does not always register text

### ISSUE THREAD

**Issue by ambrustorok** [holoviz/panel#6341]
I have a more complex widget that has a silent error. Here is a miniaturized version of the widget:
```python
import panel as pn
import param

pn.extension(
    'tabulator',
    'plotly',
    notifications=True
)

class UserInterface(param.Parameterized):
    def __init__(self, **params):
        self.radio_button_group = pn.widgets.RadioBoxGroup(
            name='RadioButtonGroup', 
            options = {"FirstOption": "first_option", "SecondOption": "second_option"},
            inline=False,
            value="second_option",
        )
        self.text_area_input = pn.widgets.TextAreaInput(
            name='TextAreaInput',
            placeholder='Enter text here',
        )
        self.widget_box = pn.WidgetBox(
            '# 1. Search',
            self.radio_button_group,
            self.text_area_input,
        )
        super().__init__(**params)

    @property
    def user_interface(self):
        input_panel = pn.GridSpec(min_height = self.widget_box.height)
        input_panel[0, 0] = self.widget_box
        
        return input_panel

user_interface_instance = UserInterface()
user_interface_instance.user_interface
```
![image](https://github.com/holoviz/panel/assets/31830274/b77cf03e-4f02-423d-a532-0515d62cecc5)

Now when I enter something into the text field,

![image](https://github.com/holoviz/panel/assets/31830274/93a6ed74-d94e-47d1-91aa-6707cbc957fc)

then try to access it using code, it sometimes returns an empty string.

```python
user_interface_instance.text_area_input.value
```

![image](https://github.com/holoviz/panel/assets/31830274/ad1dc388-c48e-4506-ac74-b9479aa6b125)

I do not get any errors in the console and the issue is resolved once I click out and back into the widget. 

Does anyone have a similar issue? It works maybe 9 out of 10 times, but it is pretty annoying when it doesn't.

**Comment by Hoxbro** [comment]
Can you try using `user_interface_instance.text_area_input.value_input`?

**Comment by ambrustorok** [comment]
That appears to work. Thanks @Hoxbro!
