### ISSUE TITLE
Feature Request: Add `gap` property to `pn.FlexBox()`

### ISSUE THREAD

**Issue by OSuwaidi** [holoviz/panel#6350]
Panel's `pn.FlexBox()` is quite versatile.

However, it lacks one import property which is `gap`; and if I were to manually inject the `gap` CSS into the flexbox via:
`pn.FlexBox(flex_direction='column', ..., styles={"gap": "1rem"})`, it doesn't take effect.

Though if I were to switch `pn.FlexBox()` to `pn.Column()`, and apply the following CSS:
```
pn.Column(..., styles={
            "display": "flex",
            "flex-direction": "column",
            "align-items": "center",
            "justify-content": "center",
            "gap": "1rem"
            })
```
then it works fine!

**Comment by philippjfr** [comment]
Would you be open to making a PR?

**Comment by philippjfr** [comment]
Really just need to add the parameter and then update `panel/layout/flex.html` and add the gap:

```
<div id="flexbox" style="display: flex; flex-wrap: ${flex_wrap}; justify-content: ${justify_content}; flex-direction: ${flex_direction}; align-content: ${align_content}; align-items: ${align_items}; gap: ${gap}; height: 100%;">
```
