### ISSUE TITLE
dyanmic auto_grow on TextAreaInput 

### ISSUE THREAD

**Issue by wara6** [holoviz/panel#6352]
It would be nice to have TextAreaInput's height dynamically updated when using auto_grow=True and changing the value inside a callback.
Example : 
```
import panel as pn

text_area = pn.widgets.TextAreaInput(auto_grow=True)
b = pn.widgets.Button(name='add a line')

def add_line(e):
    text_area.value_input=text_area.value_input+"\nnew line"

b.on_click(add_line)

pn.Column(
    text_area,
    b
).servable()
```
Clicking on the "add a line" button does not dynamically update the height of the text area, even with auto_grow set to True, see the screenshot below.
<img width="174" alt="image" src="https://github.com/holoviz/panel/assets/157014262/1b54f241-30d7-4ee0-8fc6-88b891eaa002">

**Comment by ahuang11** [comment]
I think you can do this
```python
import panel as pn

text_area = pn.widgets.TextAreaInput(auto_grow=True)
b = pn.widgets.Button(name="add a line")


def add_line(e):
    text_area.value_input = text_area.value_input + "\nnew line"
    text_area.rows = text_area.rows + 1


b.on_click(add_line)

pn.Column(text_area, b).show()
```

**Comment by wara6** [comment]
great idea ! thanks
