### ISSUE TITLE
Long messages in panel notifications aren't displayed properly

### ISSUE THREAD

**Issue by ATL2001** [holoviz/panel#6359]
#### ALL software version info
Python 3.11.8
Panel 1.3.8
Observed in both Chrome and Edge

#### Description of expected behavior and the observed behavior
Error messages in notifications are displayed with white text with a red background and it works perfectly for short messages, but for long messages the white text seems to overrun the red background and is lost in the notification.  If the user highlights the text, it shows up, but it would be ideal if the background filled the entire notification box instead of the way it is displayed (looks like part of a circle to me)

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

pn.extension(notifications=True)

button = pn.widgets.Button(name="Big Notification")

def on_button_click(x=None):
    message = """This is a really long 
    notificaiton to tell my user that 
    something bad happened and they need to 
    do something about it.  I would like to 
    provide a lot of detail but the text gets 
    lost in the notification box unless they
    highlight it to see the white on white.
    I realize this is a total edge case and 
    most notifications arent this long."""
    pn.state.notifications.error(message, duration=0)
button.on_click(on_button_click)

app = pn.Column(button)
app.servable()

```

Image showing the notification:
![image](https://github.com/holoviz/panel/assets/35881864/1e1017ca-6e35-4c39-b5f0-bef9b2fa999a)

Image showing the text is there, when highlighted:
![image](https://github.com/holoviz/panel/assets/35881864/78ed40b3-4654-467c-af3a-4956e2205593)

I'd be happy to help with a fix if someone could point me where to start, I poked around and it wasn't apparent to me where the root issue was, and perhaps it's upstream in Bokeh..

**Comment by philippjfr** [comment]
Looks like an upstream issue with Notyf.js, see https://github.com/caroso1222/notyf/issues/137

**Comment by ATL2001** [comment]
Thank you for the very fast response, I'll go look around over there!

**Comment by philippjfr** [comment]
Got a fix over in #6360

**Comment by ATL2001** [comment]
I'll stop looking! that's great, thank you so much!

**Comment by contang0** [comment]
Is this in the 1.4.0rc2? I still see my messages cut short, but to the right side, not at the bottom.

**Comment by philippjfr** [comment]
Can you post a screenshot?

**Comment by ATL2001** [comment]
I just updated to 1.4.0rc1 and it is working properly, the whole notification is the appropriate color 😎

**Comment by contang0** [comment]
@philippjfr yes, please see below. this appears to be an issue with very long strings with no spaces. I do have a use case for them (long database IDs) 

![image](https://github.com/holoviz/panel/assets/10067941/dd8a3ac5-5a79-4166-b019-ef490cbf04bb)

![image](https://github.com/holoviz/panel/assets/10067941/be502b58-8b97-4ff3-ab56-7a04b4b990b6)

**Comment by WhackyBoyg0d** [comment]
are there any work arounds to increase the size of the notification box ?
