### ISSUE TITLE
jslink breaks gui sync when linked object is deeply nested

### ISSUE THREAD

**Issue by dataist** [holoviz/panel#637]
#### ALL software version info (Panel, bokeh, python, notebook, OS, browser, any other relevant packages)
```
python 3.7
chrome
osx

panel==0.6.0
param==1.9.1
bokeh==1.2.0
```

#### Description of expected behavior and the observed behavior
Ran into a very subtle and nefarious bug when using `jslink`.  Essentially, objects stop being updated once quiet failure happens internally.  After some effort I was able to find a minimal example that hinges only on the presence on one additional level of `panel` layout nesting. 

#### Complete, minimal, self-contained example code that reproduces the issue

Minimal working example
```
class CopyText(param.Parameterized):
    
    slider = param.Number(bounds=(0,100))
    val = pn.widgets.StaticText(value='')
    copy_button = pn.widgets.Button(name='Copy')
    
    @param.depends('slider',watch=True)
    def view(self):
        self.val.value = str(self.slider)
        return pn.Column(self.param['slider'],self.copy_button,self.val)
    
    def panel(self):
        link = self.copy_button.jslink(self.val, 
                        code={'clicks': 'navigator.clipboard.writeText(target.text)'})

        return pn.Column(self.view)
    
CopyText().panel()
```

Minimal Breaking Example (just adds an encapsulating `pn.Row` to `view` return)

```
class CopyText(param.Parameterized):
    
    slider = param.Number(bounds=(0,100))
    val = pn.widgets.StaticText(value='')
    copy_button = pn.widgets.Button(name='Copy')
    
    @param.depends('slider',watch=True)
    def view(self):
        self.val.value = str(self.slider)
        return pn.Column(pn.Row(self.param['slider'],self.copy_button),self.val)
    
    def panel(self):
        link = self.copy_button.jslink(self.val, 
                        code={'clicks': 'navigator.clipboard.writeText(target.text)'})

        return pn.Column(self.view)
    
CopyText().panel()
```

#### Stack traceback and/or browser JavaScript console output

```
main.min.js?v=eef572336006937e9a017afbdebc65fe:36773 Comm promise not found for comm id 9fee39713b54437190686a2c9e571340
CommManager.comm_msg @ main.min.js?v=eef572336006937e9a017afbdebc65fe:36773
i @ main.min.js?v=eef572336006937e9a017afbdebc65fe:2
Kernel._handle_iopub_message @ main.min.js?v=eef572336006937e9a017afbdebc65fe:38211
Kernel._finish_ws_message @ main.min.js?v=eef572336006937e9a017afbdebc65fe:38003
(anonymous) @ main.min.js?v=eef572336006937e9a017afbdebc65fe:37994
Promise.then (async)
Kernel._handle_ws_message @ main.min.js?v=eef572336006937e9a017afbdebc65fe:37994
i @ main.min.js?v=eef572336006937e9a017afbdebc65fe:2

```

upon rerender  (another call to `.panel()`) you can get the following console error:

```
Python failed with the following traceback: 
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/param/parameterized.py set_param L2572
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/param/parameterized.py set_param L1365
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/param/parameterized.py _batch_call_watchers L1480
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/panel/viewable.py param_change L604
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/panel/layout.py _update_model L69
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/panel/viewable.py _preprocess L255
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/panel/links.py _process_links L124
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/panel/links.py __init__ L200
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/panel/links.py _init_callback L206
/home/ec2-user/SageMaker/envs/frame/lib/python3.7/site-packages/panel/links.py _resolve_model L184
	KeyError: '16538'
```

**Comment by philippjfr** [comment]
Sorry I let this sit so long. You are doing something pretty weird here:

a) You are using watch=True when you don't need to causing the callback to be called twice.
b) You are returning a new slider whenever the slider value changes.

So for now I'm going to close this as unreproducible. Please reopen if you can reproduce this in an example that doesn't have the issues above.

**Comment by dataist** [comment]
okay, well good to know both of those things, though that means I've not correctly understood what `watch` is doing or that referencing an existing param like so `self.param['slider']` creates a new copy of that parameter. Since `self.slider` is just the current value of the slider widget; what is the intended way to get reference to the visual element of a parameter?

**Comment by philippjfr** [comment]
>that means I've not correctly understood what watch is doing 

watch=True should be used when you have a callback that has side-effects but isn't invoked directly or passed to Panel. When you have a callback that returns something that's an indication you do not want watch=True. 

>that referencing an existing param like so self.param['slider'] creates a new copy of that parameter

That's not what I meant. The problem in your example is that the ``view`` method returns self.param['slider'] in the first place. That means every time the slider value changes you are creating a new layout containing the slider which is pointless and expensive and results in weird flicker.

Here's how I'd write the example, it's exactly analogous:

```
class CopyText(param.Parameterized):
    
    slider = param.Number(bounds=(0,100))
    val = pn.widgets.StaticText(value='')
    copy_button = pn.widgets.Button(name='Copy')
    
    @param.depends('slider')
    def view(self):
        self.val.value = str(self.slider)
        return pn.Column(self.val)
    
    def panel(self):
        link = self.copy_button.jslink(self.val, 
                        code={'clicks': 'navigator.clipboard.writeText(target.text)'})

        return pn.Column(pn.Row(self.param['slider'],self.copy_button), self.view)
    
CopyText().panel()
```

**Comment by philippjfr** [comment]
It's clear that explaining the watch keyword needs some more docs. You're definitely not the first person confused by it.

**Comment by dataist** [comment]
Thanks for those details! I think I now understand where some of my performance issues might be coming from on some of the larger dashboards I've made--pointless expensive flickers everywhere...

**Comment by philippjfr** [comment]
That having been said, I think there is a decent chance we could make Panel smarter and avoid rerendering stuff that hasn't actually changed. I'll see how hard that would be in practice.

**Comment by philippjfr** [comment]
I've opened https://github.com/holoviz/panel/issues/878 to remind me to explore that possibility.

**Comment by philippjfr** [comment]
So, uhm, I just gave this a try and it was actually kind of trivial, maybe you could try out https://github.com/holoviz/panel/pull/879 and see if your apps behave a little bit better.

**Comment by dataist** [comment]
hah, awesome, will do that now
