### ISSUE TITLE
Changing slider with keyboard in Column jumps to end of cell

### ISSUE THREAD

**Issue by hoxbro** [holoviz/panel#6394]
The following example in a notebook will jump to the end of the output cell when a slider changes with the keyboard.

``` python
import panel as pn
pn.extension()

pn.widgets.IntSlider(end=10, height=1200)
```

https://github.com/holoviz/panel/assets/19758978/34c366ee-e413-4ca9-8f59-84ed29d11f59

The same does not seem to be the case when using `pn.Row` + large width

**Comment by philippjfr** [comment]
Duplicate, **I think**, see https://github.com/holoviz/panel/issues/6314

**Comment by Hoxbro** [comment]
Another case is `ChatAreaInput`, which does not work with shift+enter because it reruns the current cell:

```
import panel as pn

pn.extension()

pn.chat.ChatAreaInput(placeholder="Type something, and press Enter to clear!")
```

https://github.com/holoviz/panel/assets/19758978/8ec4b399-3a61-403e-9906-5b67d919ce4a

**Comment by hoxbro** [comment]
@krassowski, do you have any recommendations for what to do?
