### ISSUE TITLE
Cannot run jupyter notebooks with '#'

### ISSUE THREAD

**Issue by singharpit94** [holoviz/panel#6431]
I am using panel 1.3.8 and bokeh 3.3.4 and noticed that when running panel serve from a notebook having a cell throws an error

`"Unterminated String Literal"`

Simple Reproducer:

```
import panel as pn

pn.extension()
pn.pane.Markdown("# Test ").servable()

```

To reproduce the issue, create a notebook with a cell having the above code and run panel serve. Can you please check this?

**Comment by Hoxbro** [comment]
This should be fixed in https://github.com/holoviz/panel/pull/6380

**Comment by singharpit94** [comment]
Thanks @Hoxbro
