### ISSUE TITLE
Ipywidgets not working if added dynamically

### ISSUE THREAD

**Issue by anton-br** [holoviz/panel#6439]
<details>
<summary>ALL software version info</summary>
General:<br>
Ubuntu 22.04.2 LTS<br>
python 3.11.3<br>
<br>
library versions:<br>
bokeh==3.3.4<br>
ipympl==0.9.3<br>
ipykernel==6.29.3<br>
ipyleaflet==0.18.2<br>
ipympl==0.9.3<br>
ipython==8.22.1<br>
ipython_genutils==0.2.0<br>
ipywidgets==8.1.2<br>
ipywidgets-bokeh==1.5.0<br>
jupyterlab==4.1.2 <br>
jupyterlab_pygments==0.3.0<br>
jupyterlab_server==2.25.3<br>
jupyterlab_widgets==3.0.10<br>
matplotlib==3.8.3<br>
panel==1.3.8<br>

browser:
Chrome 122.0.6261.94
</details>

#### Description of expected behavior and the observed behavior
I am trying to dynamically add new widgets by button click. But got a message **Wrong widget protocol version: received protocol version '', but was expecting major version '2** and created widgets are not updating. Here is a code example:
```python
import ipywidgets as ipw
import panel as pn
pn.extension('ipywidgets', sizing_mode="stretch_width")

button = pn.widgets.Button(name='button', width=100)
def calculate(a):
    if not a:  # aviod widgets creation before button is clicked
        return None
    slider = ipw.widgets.FloatSlider(value=10, start=0, end=100)
    text = ipw.widgets.FloatText(description='Current slider value:')
    @pn.depends(slider, watch=True)
    def slider_update(a):
        text.value = str(a)
        print("update", text.value)
    return pn.Column(slider, text)

bind_button = pn.bind(calculate, button)
pn.Column(button, bind_button).servable()
```

If serve the code, push the button and drug the slider, I would expect the slider's value to be printed in floattext widget but nothing happend.

![image](https://github.com/holoviz/panel/assets/19351782/50a78ae7-a7e3-4da2-8edc-83c7aa5c5bec)

But, from console we can conclude that widgets is updating as expected:

![image](https://github.com/holoviz/panel/assets/19351782/a9f9d761-35b1-4159-b35b-714044894284)

**Comment by Coderambling** [comment]
Hi @anton-br . Found this very old Github entry mentioning the same error and a workaround. Does that help in anyway? It seems to mention the package / module that generates the error warning. https://github.com/JuliaGizmos/Interact.jl/issues/176

**Comment by Coderambling** [comment]
Regrettably I don't really have specific knowledge of those details of the stack.

The only other thing I can suggest is running the code on Anaconda Cloud (or in a similar Notebook environment), and see if the issue persists there.

**Comment by anton-br** [comment]
Thank you for the suggestion! Unfortunately, I am not sure that switching an environment would help to solve the issue, as I need to start a panel application from the console. I've seen @philippjfr has previously solved this problem before. So, Philip, would you mind to give any clue on how to fix this bug?

**Comment by Coderambling** [comment]
Had a look at the issue you referenced, and looks like some code was changed in ipywidgets_bokeh to solve it. So you're possibly on the right track, but I have no idea beyond that.

**Comment by anton-br** [comment]
yeah, I've also checked and problem with version disappears! @philippjfr, thank you!

But, I've found another one. If you try to create interactive pn.pane.Matplotlib instead of slider you'll receive an error "Comm is already created". I'll try to figure out why is happenning and let you know.

**Comment by philippjfr** [comment]
Can you provide a reproducer?

**Comment by anton-br** [comment]
```
import ipywidgets as ipw
import panel as pn
import matplotlib.pyplot as plt

pn.extension('ipywidgets')#, sizing_mode="stretch_width")

button = pn.widgets.Button(name='button', width=100)
def calculate(a):
    if not a:  # aviod widgets creation before button is clicked
        return None
    fig, ax = plt.subplots()
    ax.plot((1, 2, 3))
    return pn.pane.Matplotlib(fig, interactive=True, high_dpi=False)

bind_button = pn.bind(calculate, button)
pn.Column(button, bind_button).servable()
```

**Comment by philippjfr** [comment]
Thanks, also now fixed in https://github.com/bokeh/ipywidgets_bokeh/pull/104

**Comment by anton-br** [comment]
Great now is working as intended!

**Comment by Coderambling** [comment]
Wow that was a quick turnaround @philippjfr !
