### ISSUE TITLE
tabulator bug using 2 modals

### ISSUE THREAD

**Issue by wara6** [holoviz/panel#6449]
Having a tabulator inside a modal in a panel application that handles several modals produces a bug.
I used the reply on [this holoviz discourse about how to handle several modals](https://discourse.holoviz.org/t/how-to-create-two-seperate-modals-in-panel/5382/2).

Opening the modals various times make the tabulator look empty.
Here's a way to reproduce the bug using the code below : open the modal 2, close it, open it again, close it and then open the tabulator modal.

```
import panel as pn
import pandas as pd
pn.extension('tabulator')

ui = pn.template.VanillaTemplate()

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 22, 35],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}

modal1 = pn.widgets.Tabulator(pd.DataFrame(data))
modal2 = pn.pane.Markdown("""# Some Markdown""")
ui.modal.append(pn.Column())

button1 = pn.widgets.Button(name='open tabulator modal')
button2 = pn.widgets.Button(name='open modal 2')
def callback1(event):
    ui.modal[0].clear()
    ui.modal[0].append(modal1)
    ui.open_modal()
def callback2(event):
    ui.modal[0].clear()
    ui.modal[0].append(modal2)
    ui.open_modal()
button1.on_click(callback1)
button2.on_click(callback2)
ui.main.append(button1)
ui.main.append(button2)

ui.servable()
```

You can also reproduce this bug using other scenarios. 
I found this bug using panel 1.3.8

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/6355
