### ISSUE TITLE
The Panel docs App Gallery links are broken

### ISSUE THREAD

**Issue by fohrloop** [holoviz/panel#6463]
#### Description of expected behavior and the observed behavior
- Links to the examples are broken at https://panel.holoviz.org/gallery/index.html

#### Complete, minimal, self-contained example code that reproduces the issue
- Go to https://panel.holoviz.org/gallery/index.html
- Click the image of any of the example. For example, the portfolio optimizer

![image](https://github.com/holoviz/panel/assets/17479683/f5f3ab0e-dc3f-4ea6-9334-da3bb9174dd9)

which links to https://panel-gallery-dev.pyviz.demo.anaconda.com/portfolio_optimizer

#### Screenshots or screencasts of the bug in action

![image](https://github.com/holoviz/panel/assets/17479683/3c242d7c-a46a-47c2-a442-7fcbed61ce84)

- [ ] I may be interested in making a pull request to address this

**Comment by Coderambling** [comment]
Weirdly, it loads for me when I try on Android (and works after a minute spinning load indicator), But on desktop I get a 404. Observed the same behaviour some days ago.

**Comment by fohrloop** [comment]
@Coderambling just tested and it does *not* work on my Android phone (or on linux laptop). I get the same nginx 404 page.

**Comment by philippjfr** [comment]
Can confirm, we migrated the hosting of our apps and had to trigger a rebuild of the docs and in the process caused us to swap over to the dev gallery.

**Comment by philippjfr** [comment]
Okay this is now fixed. Unfortunately Panel is set up as a so called PWA and all pages are cached (not just in the regular browser cache) so for anyone who already visited one of the pages they won't see the fixed links. Thankfully Panel 1.4.0 is around the corner so it'll be fixed properly soon.

Thanks again for reporting! I'll configure a link checker going forward.

**Comment by Coderambling** [comment]
Great! Regarding link checker, there is a (related) open issue for that [here]https://github.com/holoviz/panel/issues/6418).
