### ISSUE TITLE
Hovertool box not on plot

### ISSUE THREAD

**Issue by benbarn313** [holoviz/panel#6480]
```python
import holoviews as hv
import numpy as np
import panel as pn

pn.extension()
hv.extension('bokeh')

data = 10*np.random.rand(10,10)
img = hv.Image(data).opts(tools=['hover'])
pn.panel(img)
```

![image](https://github.com/holoviz/panel/assets/55669975/e1762761-6bf6-4ebf-865e-5fd329782fce)

As you can see in the image, the box is off to the right of the plot.
This also happens when the hv image is displayed without the panel pane.

bokeh                     3.3.0
holoviews               1.18.1
jupyterlab               4.0.11
panel                      1.3.7  
param                     2.0.2
pyviz_comms          3.0.0 
python                    3.11.4

**Comment by Hoxbro** [comment]
Try updating to bokeh 3.3.4.
