### ISSUE TITLE
Inconsistent IntRangeSlider Value Behavior in Panel Library

### ISSUE THREAD

**Issue by mjm-yuto** [holoviz/panel#6483]
I've encountered an unexpected behavior when using the IntRangeSlider widget in the Panel library within a Jupyter notebook. Specifically, the returned value of the slider does not always match the range selected in the UI. For example, selecting a range of 4 to 7 in the UI results in (3, 6) when accessing slider.value, whereas selecting a range of 3 to 9 correctly returns (3, 9).

**Steps to Reproduce**

Create an IntRangeSlider widget with a range from 1 to 10.

```
import panel as pn
pn.extension()
slider = pn.widgets.IntRangeSlider(start=1, end=10, step=1, name='Sample IntRangeSlider')
```

Display the slider and select a range of 4 to 7 in the UI.
Access the value of the slider using slider.value.

**Expected Behavior**
The value attribute should accurately reflect the range selected in the UI, e.g., selecting 4 to 7 should return (4, 7).

**Actual Behavior**
The value attribute does not always match the UI selection. Selecting 4 to 7 returns (3, 6), which is inconsistent with the expected behavior. However, selecting a range of 3 to 9 correctly returns (3, 9).

**Comment by philippjfr** [comment]
Thanks for the issue. Can you list the versions of Jupyter(Lab) and Panel you have installed? I could not reproduce this.
