### ISSUE TITLE
Serving a panel application using `pn.serve` in a Python script results in shared state

### ISSUE THREAD

**Issue by peterroelants** [holoviz/panel#6489]
#### Description of expected behavior and the observed behavior

Serving a panel application using `pn.serve` in a Python script results in shared state, despite wrapping the app in a function ([as suggested in the documentation](https://panel.holoviz.org/how_to/server/multiple.html)).

I believe this to be a result of using [`param.Parameterized`](https://param.holoviz.org/reference/param/generated/param.Parameterized.html#param-parameterized). I first thought I could delay the initialization, but this seems to not be the intended usage according to the [param documentation](https://param.holoviz.org/reference/param/generated/param.Parameterized.html#param-parameterized) and [my experiment documented here](https://discourse.holoviz.org/t/how-to-have-non-shared-session-states/2116/9?u=peterroelants), so I believe this to be a bug.

#### Complete, minimal, self-contained example code that reproduces the issue

Running this with `python test_panel.py` results in application with shared state:
```python
import panel as pn
import param
from panel.viewable import ServableMixin


class TestViewerApp(param.Parameterized):

    view: pn.template.BaseTemplate
    # Parameters
    input_widget = pn.widgets.TextInput(
        name="Input",
        placeholder="Enter Some text ...",
    )
    output_widget = pn.widgets.StaticText(name="Output", value="")

    def __init__(
        self,
        **params,
    ):
        super().__init__(**params)
        self._init_view()

    def _init_view(self) -> None:
        self.view = pn.template.BootstrapTemplate()
        self.view.main.append(self.input_widget)
        self.view.main.append(self.output_widget)

    @param.depends("input_widget.value", watch=True)
    def _update_output(self) -> None:
        inpt = self.input_widget.value
        if inpt is not None:
            self.output_widget.value = f"Input: {inpt!r}"


def session_test_app() -> ServableMixin:
    """A simple test app to check if the platform client is running."""
    return TestViewerApp().view


print(f"test_panel.py {__name__=!r}")
if __name__ == "__main__":
    # Run with `python test_panel.py`
    pn.serve(
        {"session_test": session_test_app},
    )
else:
    # Run with `panel serve test_panel.py`
    session_test_app().servable()

```
Running this code with `panel serve test_panel.py` doesn't result in shared state.
Running this code with `python test_panel.py` results in application with shared state (see video below)

#### Screenshots or screencasts of the bug in action

https://github.com/holoviz/panel/assets/951093/dc17cca1-42e7-48eb-91db-09f8cb5a134e

#### ALL software version info
- python=3.11.8
- panel=1.3.8
- param=2.0.2

- [ ] I may be interested in making a pull request to address this

**Comment by Hoxbro** [comment]
Try to remove widgets into init.

**Comment by peterroelants** [comment]
> Try to remove widgets into init.

@Hoxbro I tried this based on the suggested in [this discourse thread](https://discourse.holoviz.org/t/how-to-have-non-shared-session-states/2116) (see my remark above), however this seems to result in other potential issues:

The following:
```python
class TestViewerApp(param.Parameterized):

    view: pn.template.BaseTemplate
    # Parameters
    input_widget: pn.widgets.TextInput
    intermediary: str
    output_widget: pn.widgets.StaticText

    def __init__(
        self,
        **params,
    ):
        self.input_widget = pn.widgets.TextInput(
            name="Input",
            placeholder="Enter Some text ...",
        )
        self.output_widget = pn.widgets.StaticText(name="Output", value="")
        self.intermediary = param.String(default="")
        super().__init__(**params)
        self._init_view()

    def _init_view(self) -> None:
        self.view = pn.template.BootstrapTemplate()
        self.view.main.append(self.input_widget)
        self.view.main.append(self.output_widget)

    @param.depends("intermediary", watch=True)
    def _update_output(self) -> None:
        inpt = self.input_widget.value
        if inpt is not None:
            self.output_widget.value = f"Input: {inpt!r}"
```

Fails with
```python-traceback
Traceback (most recent call last):
  File "test_panel.py", line 6, in <module>
    class TestViewerApp(param.Parameterized):
  File "./env/lib/python3.11/site-packages/param/parameterized.py", line 3313, in __init__
    deps, dynamic_deps = _params_depended_on(minfo, dynamic=False)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./env/lib/python3.11/site-packages/param/parameterized.py", line 681, in _params_depended_on
    ddeps, ddynamic_deps = (minfo.cls if minfo.inst is None else minfo.inst).param._spec_to_obj(d, dynamic, intermediate)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./env/lib/python3.11/site-packages/param/parameterized.py", line 2860, in _spec_to_obj
    raise AttributeError(f"Attribute {attr!r} could not be resolved on {src}.")
AttributeError: Attribute 'intermediary' could not be resolved on <class '__main__.TestViewerApp'>.
```

**Comment by Hoxbro** [comment]
Try `intermediary = param.Parameter()`.

**Comment by peterroelants** [comment]
> Try `intermediary = param.String()`.

@Hoxbro Thanks, the following seems to work:

```python
class TestViewerApp(param.Parameterized):

    view: pn.template.BaseTemplate
    # Parameters
    input_widget: pn.widgets.TextInput
    intermediary: str = param.String()
    output_widget: pn.widgets.StaticText

    def __init__(self):
        self.input_widget = pn.widgets.TextInput(
            name="Input",
            placeholder="Enter Some text ...",
        )
        self.output_widget = pn.widgets.StaticText(name="Output", value="")
        super().__init__()
        self._init_view()

    def _init_view(self) -> None:
        self.view = pn.template.BootstrapTemplate()
        self.view.main.append(self.input_widget)
        self.view.main.append(self.output_widget)

    @param.depends("input_widget.value", watch=True)
    def _update_intermediary(self) -> None:
        self.intermediary = self.input_widget.value

    @param.depends("intermediary", watch=True)
    def _update_output(self) -> None:
        inpt = self.intermediary
        if inpt is not None:
            self.output_widget.value = f"Input: {inpt!r}"
```

However, it seems weird that `param` objects need to be initialized, but `panel` widgets not. Btw, aren't panel widgets also instances of `param.Parameterized`? Would you have any ideal why I should treat them differently?

**Comment by Hoxbro** [comment]
In short: 
- `param.String` is a `Parameter` which a `Parameterized` class uses. 
- Yes, panel widgets are instances `Parameterized`.
-  As this is Python, things run from top to bottom, therefore when you create an instance (a widget) in the class variable space, it will only be created once, whereas in `__init__`, it will be created each time the class is instantiated.
- `Parameter` in the class variable space will be copied to be unique for each instance.
- `panel serve` will run the script each time you load the page, where as `python` + `pn.serve` will only run the script once.
