### ISSUE TITLE
Issues to be solved before 1.4

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6513]
- [x] Add missing ChatInputArea image to component Gallery
- [x] Markdown code blocks are not formatted (neither in 1.3.8 or 1.4.0rc2). Solution is to install `pygments`.
- [x] Fix Perspective worker issue caused by running Panel behind jupyter-proxy-server on JupyterHub
- [x] Pending Writes issue https://github.com/holoviz/panel/issues/6521
- [ ] Notyf issue

Maybe more items to be added.

## Missing Image

![image](https://github.com/holoviz/panel/assets/42288570/bcc2def6-2f46-46bb-8297-27a7bf6e0d23)

## Missing Code Highlighting

![image](https://github.com/holoviz/panel/assets/42288570/564c9fe6-eccb-4306-a01f-e5c100e9b523)

````python
import panel as pn

pn.extension()

pn.pane.Markdown("""
# Code

```python
from io import BytesIO

import holoviews as hv
import numpy as np
import panel as pn
import pyarrow.parquet as pq
from fsspec.parquet import open_parquet_file
from PIL import Image

pn.extension()

parquet_url = "https://huggingface.co/datasets/Major-TOM/Core-S2L2A/resolve/main/images/part_03520.parquet"
parquet_row = 445
column = "thumbnail"
with open_parquet_file(parquet_url, columns=[column]) as f:
    with pq.ParquetFile(f) as pf:
        first_row_group = pf.read_row_group(parquet_row, columns=[column])

stream = BytesIO(first_row_group[column][0].as_py())
image = Image.open(stream)
image_array = np.array(image)
if image_array.ndim==2:
    plot = hv.Image(image_array).opts(cmap="gray", colorbar=True)
else:
    plot = hv.RGB(image_array)

plot.opts(xaxis=None, yaxis=None)

pn.panel(plot).servable()
```

""").servable()
````

## Perspective not working

panel==1.4.0rc2, bokeh=3.4.0

```python
import panel as pn
import pandas as pd

pn.extension("perspective")

pn.pane.Perspective(pd.DataFrame({"a": [1,2]})).servable()
```

![image](https://github.com/holoviz/panel/assets/42288570/1157951e-bea3-4c93-8930-5a01b2749924)

**Comment by ahuang11** [comment]
Maybe highlighting related to https://discourse.holoviz.org/t/chatinterface-syntax-identification-is-not-working-in-deployment-but-works-in-local/6926/10?u=ahuang11

**Comment by MarcSkovMadsen** [comment]
> Maybe highlighting related to https://discourse.holoviz.org/t/chatinterface-syntax-identification-is-not-working-in-deployment-but-works-in-local/6926/10?u=ahuang11

I can confirm that installing `pygments` adds code highlighting.

![image](https://github.com/holoviz/panel/assets/42288570/159f888c-d43c-4281-8061-d79329b0bb9b)

Should `pygments` be a panel dependency? Should we have a way to install `panel[all]`? Should we describe `pygments` in the installation or markdown guide? @philippjfr ?

**Comment by philippjfr** [comment]
Cannot reproduce the perspective issues:

<img width="479" alt="Screenshot 2024-03-18 at 14 36 03" src="https://github.com/holoviz/panel/assets/1550771/36ee2e5b-ec85-4e50-a5fb-17be238bdc8b">

**Comment by philippjfr** [comment]
Definitely need to document the pygments dependency somewhere. I wouldn't be entirely opposed to making it a hard requirement either, it's 1.2 MB, which is a little large for pyodide but not major in the grand scheme of things.

**Comment by philippjfr** [comment]
Hmm but other extensions work? They all use the same codepaths so it's pretty weird that this only affects perspective.

**Comment by MarcSkovMadsen** [comment]
> Hmm but other extensions work? They all use the same codepaths so it's pretty weird that this only affects perspective.

Same problem if I change to Tabulator. But for some unknown reason it still renders

![image](https://github.com/holoviz/panel/assets/42288570/b392df72-120d-4c14-ac6b-5717b9aaf4d2)

**Comment by MarcSkovMadsen** [comment]
> Hmm but other extensions work? They all use the same codepaths so it's pretty weird that this only affects perspective.

No problem if I change to Tabulator.

![image](https://github.com/holoviz/panel/assets/42288570/b582225f-5bd8-4c96-9f27-78e9bda4cf73)

**Comment by MarcSkovMadsen** [comment]
Actually I see problem with tabulator_simple_min.css.map in terminal 

![image](https://github.com/holoviz/panel/assets/42288570/1840d2a5-8836-4274-9a3f-3d556f67629f)

**Comment by MarcSkovMadsen** [comment]
I think you have hardcoded the location to `/static/..` :-)

![image](https://github.com/holoviz/panel/assets/42288570/8cfaa357-5fa7-4b39-9ce3-bfe68176b632)

**Comment by philippjfr** [comment]
Okay, thanks will have to investigate, paths should always be relative.

**Comment by philippjfr** [comment]
Oh, actually I think it might be an issue for modules only. We have a general issue with `.map` files since we don't generally include them so that's a separate issue.

**Comment by MarcSkovMadsen** [comment]
The Perspective issue on JupyterHub seems solved with panel==1.4.0rc3.

**Comment by MarcSkovMadsen** [comment]
## Notif issue

I see the below with panel==1.4.0rc3 with an app I just deployed. Its comes at random. Sometimes when I hard refresh I see it. Sometimes I don't. I don't have time to make reproducible example yet.

![image](https://github.com/holoviz/panel/assets/42288570/2d11ebb0-9518-4dcf-aec1-83c09cd7c80f)

**Comment by philippjfr** [comment]
Please open a new issue for that if you figure out something reproducible. I just tried a few apps and could not reproduce.

**Comment by MarcSkovMadsen** [comment]
I'll close again. Cannot reproduce now.
