### ISSUE TITLE
Disable possibility to make text input wider than available area

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6515]
I tested out new ChatAreaInput in ChatInterface in panel==1.4.0.rc2. I found that users can change the width beyond the buttons which is not very useful. Please disable this.

![image](https://github.com/holoviz/panel/assets/42288570/d4446a16-9b2e-4936-8ad9-423d2e35d69f)

## Workaround

Just provide the `ChatInputArea` your self. Then you cannot change width.

![image](https://github.com/holoviz/panel/assets/42288570/49653f65-5613-40f6-ba1e-b55863c0c232)

**Comment by ahuang11** [comment]
Do you mean dragging the bottom right square can change the width? 

If so, cannot reproduce after doing a hard refresh shift + cmd + r.
```
    resizable = param.ObjectSelector(
        default="height",
        objects=["both", "width", "height", False],
        doc="""
        Whether the layout is interactively resizable,
        and if so in which dimensions: `width`, `height`, or `both`.
        Can only be set during initialization.""",
    )
```

**Comment by MarcSkovMadsen** [comment]
I will try to find cause. At least you can also make it less wide which is also surprising to me at least.

![image](https://github.com/holoviz/panel/assets/42288570/2d1e8177-0057-4b6b-aae8-c0cb12615a68)

```python
import panel as pn
from time import sleep

pn.extension(sizing_mode="stretch_width")

def get_response(contents, user, instance):
    if "turbine" in contents.lower():
        response = "A wind turbine converts wind energy into electricity."
    else:
        response = "Sorry, I don't know."
    sleep(1)
    return response

chat_bot = pn.chat.ChatInterface(callback=get_response, max_height=500)
chat_bot.send("Ask me what a wind turbine is", user="Assistant", respond=False)
pn.template.FastListTemplate(
    main=[chat_bot],
    main_max_width="1000px",
).servable()
```

**Comment by MarcSkovMadsen** [comment]
> I tested out new ChatAreaInput in ChatInterface in panel==1.4.0.rc2. I found that users can change the width beyond the buttons which is not very useful. Please disable this.
> 
> ![image](https://private-user-images.githubusercontent.com/42288570/313597832-d4446a16-9b2e-4936-8ad9-423d2e35d69f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzYzODUsIm5iZiI6MTcxMDc3NjA4NSwicGF0aCI6Ii80MjI4ODU3MC8zMTM1OTc4MzItZDQ0NDZhMTYtOWIyZS00OTM2LThhZDktNDIzZDJlMzVkNjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE1MzQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NjhkZTRlOTAyMGFiM2NmYzg5M2EwNTFlNmNlZTI2ZmY1YjI2MmVlMmU1MmQwMmZjMjYxMGYyYmY2Yjg2ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yK21PrzDGs2RNArRKEE07QK5FoOqbaHvUiRg3qiohKw)
> 
> ## Workaround
> Just provide the `ChatInputArea` your self. Then you cannot change width.
> 
> ![image](https://private-user-images.githubusercontent.com/42288570/313598647-49653f65-5613-40f6-ba1e-b55863c0c232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzYzODUsIm5iZiI6MTcxMDc3NjA4NSwicGF0aCI6Ii80MjI4ODU3MC8zMTM1OTg2NDctNDk2NTNmNjUtNTYxMy00MGY2LWJhMWUtYjU1ODYzYzBjMjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE1MzQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MTJiMjE0YWMyNjE0M2U4MTNkYzM5Y2YxMWJlYTQzOTNhNTFjODQ1NGVmM2YzZWMwYTE0ZjdhYTQ3YjBjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L9ah3vMlLGF-qjnqvrA0D_JUJsbZ7Wft8ujRqt-9mjI)

I can no longer reproduce original issue.
