### ISSUE TITLE
Cannot run notebook with usage of cell magics

### ISSUE THREAD

**Issue by singharpit94** [holoviz/panel#6532]
I am using panel 1.3.8 and bokeh 3.3.4 and noticed that when running panel serve from a notebook having the below cells throws an error

`"invalid syntax"`

Simple Reproducer:

Cell 1
```
%%HTML
<h2>Cell Magic in Jupyter Notebook</h2>
<p>This is a paragraph of text!</p>
<ul>
    <li>First item</li>
    <li>Second item</li>
</ul>

```

Cell 2
```
import panel as pn
pn.extension()

button = pn.widgets.Button(name='Click me', button_type='primary')
button
```

To reproduce the issue, create a notebook with the above 2 cells and run panel serve. Can you please check this?

**Comment by singharpit94** [comment]
@philippjfr curious to check the reason behind using regex based parsing a notebook and not using[ nbconvert](https://nbconvert.readthedocs.io/en/latest/)

**Comment by philippjfr** [comment]
We could certainly convert some of the code parsing into a proper nbconvert Processor but in the end the parsing would still be needed because in certain scenarios we need to capture the output of cells.

**Comment by singharpit94** [comment]
Thanks for the response @philippjfr, given how stable nbconvert has been, it would be great if we can consider it for panel notebook support.

**Comment by philippjfr** [comment]
I'm still unclear what you're suggesting here. We do use nbconvert, but to do what we need we need to apply various code transformations.

**Comment by singharpit94** [comment]
Ahh got it, I missed the part that panel already uses nbconvert.
