### ISSUE TITLE
tabulator display with long values

### ISSUE THREAD

**Issue by wara6** [holoviz/panel#6539]
With long string values **at the end** of a dataframe, the tabulator widget doesn't wrap the text correctly.

Here's an example  : 
```
import pandas as pd
import panel as pn

pn.extension('tabulator')
data = {
    'Name': 400*['John Doe'],
    'Age': 400*[30],
    'Gender': 400*['Male'],
    'Occupation': 400*['Engineer'],
    'Address': 400*['123 Main St'],
    'Description1': 250*[""]+150*["Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel interdum ex. Duis dictum id nisi quis hendrerit"],
    'Description2': 250*[""]+150*["Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel interdum ex. Duis dictum id nisi quis hendrerit"]
}

df = pd.DataFrame(data)
ui = pn.template.VanillaTemplate()
ui.main.append(pn.widgets.Tabulator(df))
ui.servable()
```
For the last pages, when there's more text, the columns width in the tabulator don't fit the text and by consequence the user cannot see the full text.
<img width="336" alt="image" src="https://github.com/holoviz/panel/assets/157014262/37d19aee-e4fc-4323-b624-c3683fde8934">

It seems that the size of the columns in the tabulator fit the data of the first pages because in this example the display is well build : (the horizontal scrollbar appears and the user is able to see the full text)

```
import pandas as pd
import panel as pn

pn.extension('tabulator')
data = {
    'Name': 400*['John Doe'],
    'Age': 400*[30],
    'Gender': 400*['Male'],
    'Occupation': 400*['Engineer'],
    'Address': 400*['123 Main St'],
    'Description1': 400*["Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel interdum ex. Duis dictum id nisi quis hendrerit"],
    'Description2': 400*["Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel interdum ex. Duis dictum id nisi quis hendrerit"]
}

df = pd.DataFrame(data)
ui = pn.template.VanillaTemplate()
ui.main.append(pn.widgets.Tabulator(df))
ui.servable()
```

Reproduced with panel 1.4.0rc3

**Comment by philippjfr** [comment]
This is expected, if you need wrapping you will have to use the `'textarea'` formatter.

```python
pn.widgets.Tabulator(df, formatters={'Description1': 'textarea'}, widths={'Description1': 200})
```

<img width="1569" alt="Screenshot 2024-03-21 at 14 23 04" src="https://github.com/holoviz/panel/assets/1550771/6b7edd50-faf1-4df7-a0a5-6c3abf1074ad">

**Comment by philippjfr** [comment]
The issue with the column measurement being done only on the first page contents is real though but I honestly don't know what the right solution is there. Computing the widths on what could be millions of records isn't a feasible solution and recomputing on page changes would result in awkward flicker. The best I can suggest there is providing explicit `widths` (maybe percentage based) for all columns.
