### ISSUE TITLE
EditableTemplate layout issues

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#6568]
With #6556 fixed I could now try out the EditableTemplate. It mostly works but I do see some glitches.

#### ALL software version info

Chrome Version 123.0.6312.58 (Official Build) (arm64)
```
panel                     1.4.0rc4                 pypi_0    pypi
bokeh                     3.4.0                    pypi_0    pypi
jupyter_bokeh             4.0.1                      py_0    bokeh
```

#### Description of expected behavior and the observed behavior

Issue 1: In the description here I think it should be "top left" for the rearrange icon?
https://holoviz-dev.github.io/panel/reference/templates/EditableTemplate.html

<img width="599" alt="Screenshot 2024-03-25 at 08 59 09" src="https://github.com/holoviz/panel/assets/852409/1dc5cdf8-a580-44df-8ef7-9f992621e6db">

Issue 2: There's a save (disk) icon in the top right, but it doesn't seem to do anything and I don't see it mentioned on the docs page!?

<img width="104" alt="Screenshot 2024-03-25 at 09 00 06" src="https://github.com/holoviz/panel/assets/852409/07c27047-38de-42f8-a34f-dd5f9346d6bc">

Issue 3: In the initial page load, the plot widget height is a bit too small. Then clicking the refresh (arrow circle) icon in the top right on each click reduces the height further.

#### Complete, minimal, self-contained example code that reproduces the issue

Same as in #6556 - just run the current example from the docs locally.

#### Stack traceback and/or browser JavaScript console output

None

#### Screenshots or screencasts of the bug in action

https://github.com/holoviz/panel/assets/852409/5a44585c-3128-4246-af0e-404ae6c0d60f

**Comment by philippjfr** [comment]
>Issue 3: In the initial page load, the plot widget height is a bit too small. Then clicking the refresh (arrow circle) icon in the top right on each click reduces the height further.

Strangely I can't reproduce this one.

**Comment by cdeil** [comment]
@philippjfr - Can you please re-open this ticket?

I still see this bug with any browser on MacOS (Chrome, Safari, Firefox).

It seems to be related to CSS height updates on enclosing divs:

```
<div class="muuri-grid-item muuri-item-shown muuri-item" data-id="p2552" style="left: 0px; top: 0px; transform: translateX(0px) translateY(0px); width: calc(100% - 30px); height: 335.125px; overflow-y: auto;">
      <div id="76ac78b8-2ea7-4e32-836c-44278109cf2a" data-root-id="p2552" style="display: contents; opacity: 1; transform: scale(1);"><div class="bk-Row"></div></div>
      <span class="muuri-handle drag" style="touch-action: none; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></span>
      <span class="muuri-handle delete"></span>
      <span class="muuri-handle resize"></span>
    </div>
```

https://github.com/holoviz/panel/assets/852409/95894634-b5c4-4a63-976b-3f10be33e705

**Comment by philippjfr** [comment]
Very strange, I've also tried every imaginable browser on OSX and have yet to encounter the issue.

**Comment by philippjfr** [comment]
Ah, actually nevermind, I can reproduce the shrink on reset issue.
