### ISSUE TITLE
pn.chat.ChatAreaInput <Enter> key binding Feature Request

### ISSUE THREAD

**Issue by ea42gh** [holoviz/panel#6575]
Multiline input will likely cause users to inadvertently send an incomplete prompt when typing <Enter>

I would prefer having the option to bind <Enter> to carriage return/line feed
and <Shift Enter> and/or <Ctrl Enter> be bound to `Send`

This would be in line with the behavior of jupyter cells.

**Comment by ahuang11** [comment]
I don't fully comprehend the `bind to carriage return/line feed` or `and and/or be bound to Send`

The current behavior of <Enter> to send follows OpenAI, MistralAI, etc.

For multi-line input, use <Shift + Enter>

**Comment by ea42gh** [comment]
I know about <Shift-Enter>, and I know that is what OpenAI, etc bind to new-line.
It causes me no end of greaf, since most other apps and all my editors use <Enter> for newline.

Result: I send incomplete prompts to the LLM more often than not.
I am not suggesting you change the default binding,
I am suggesting you give me the option to override the default!

**Comment by ahuang11** [comment]
Thanks for clarifying. In that case, I'd be happy to accept and review a PR to configure it.

Perhaps a boolean to swap the order.
https://github.com/holoviz/panel/blob/main/panel/models/chatarea_input.ts#L34

**Comment by ea42gh** [comment]
OK, I can try my hand at it. Hope I won't have to bother you with explanations about how the code works:
about to go have a look!

**Comment by ahuang11** [comment]
Thanks! https://github.com/holoviz/panel/pull/6508 Here's a good PR to use as reference; it adds a new parameter `disable_enter` and connects the Python to Typescript model.

**Comment by ea42gh** [comment]
Thinking about it: I'd need explanations of what was meant in the comment PR.

right this moment I think there are three states:
   None:               Send is disabled
   <Enter>:           Send occurs when <Enter>         is pressed
   <Shift-Enter>:  Send occurs when <Shift-Enter> is pressed

Actually, I could imagine allowing any combination of <Enter>, <Shift-Enter>, or <Ctrl-Enter>
What do you think?

**Comment by ahuang11** [comment]
> None: Send is disabled

I don't think this should be considered because that's captured by `disabled=True`

I'm a tad hesitant on Ctrl-Enter because it's unclear in Mac.

**Comment by ea42gh** [comment]
OK, perfect.

**Comment by ahuang11** [comment]
When working with typescript models in Panel, don't forget to properly set up your env and run `panel build panel` upon every typescript change.

See https://panel.holoviz.org/developer_guide/index.html

**Comment by ea42gh** [comment]
think I got it set up right, and am running `panel build panel`
Trying to test it with
```
def output(value):
    return f"Submitted: {value}"

chat_area_input = pn.chat.ChatAreaInput(placeholder=">") #, shift_enter_sends=True)
output_markdown = pn.bind(output, chat_area_input.param.value)
pn.Row(chat_area_input, output_markdown)
```
Then `chat_area_inputs.controls()` shows the new variable.
I added some `console.log()` statements to
```
    this.el.addEventListener("keydown", (event) => {
      console.log( "keydown event" )
```
but do not see any keydown event logs?!
Typing a message and hitting Enter works.

Any idea what step I might be missing?

**Comment by ahuang11** [comment]
Can you create a pr to see the changes

**Comment by ea42gh** [comment]
Let me work on this some more: this might be related to the comms problem I keep having every so often:
I shut down all but one notebook, reloaded the page, and now I do see the console.log messages.
A bit frustrating, that.

**Comment by ahuang11** [comment]
Closed in https://github.com/holoviz/panel/pull/6592
