### ISSUE TITLE
Panel not working in Quarto preview within VS Code

### ISSUE THREAD

**Issue by DmitriyLeybel** [holoviz/panel#6576]
#### ALL software version info
VSCode == 1.86.2
panel == 1.3.8
holoviews == 1.18.3
bokeh == 3.3.4
juypter_bokeh == 4.0.1
quarto-cli === 1.4.551

#### Description of expected behavior and the observed behavior

I just started working on a Quarto blog in VS Code and in running the sanity checks/testing, I encountered a weird bug that I can't seem to wrap my head around.
When using the Quarto preview for the ipynb to view the page, Panel objects do not render at all, however, Bokeh, Matplotlib, Holoviews, Hvplot ones do.
**However**, when I convert the ipynb into a qmd file, then preview it(this is when the *quarto_notebook_test_success* file was generated), the widgets show up normally as you'd expect.

I'm also attaching the generated Quarto HTML files that show the issue.(converted to txt because apparently github doesn't accept HTML files)
Doing a Compare of the two, I'm noticing slight differences but can't make heads or tails of it.(mostly formatting?).

Maybe I should crosspost this issue to Quarto as well?

#### Complete, minimal, self-contained example code that reproduces the issue
```python
import holoviews as hv
import panel as pn

hv.extension("bokeh") # same as hvplot.extension("bokeh")
pn.extension(design="material")
```

```python
import numpy as np

def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

frequencies = [0.5, 0.75, 1.0, 1.25]
phases      = [0, np.pi/2, np.pi, 3*np.pi/2]

curve_dict_2D = {(p,f):sine_curve(p,f) for p in phases for f in frequencies}

hv.HoloMap(curve_dict_2D, kdims=['phase', 'frequency']).opts(responsive=True, height=300)
```

```python
slider = pn.widgets.IntSlider(name="Select a value", value=2, start=0, end=10)
pn.Column(
    pn.Row("You selected: ", slider),
)
```

## Success
![image](https://github.com/holoviz/panel/assets/6779278/00644dc8-ad5f-4587-b39c-09e64dc1126c)

## Fail
![image](https://github.com/holoviz/panel/assets/6779278/19c031d4-2d51-43f6-b733-76a1a994aab3)

- [ ] I may be interested in making a pull request to address this
[quarto_notebook_test_fail.txt](https://github.com/holoviz/panel/files/14746953/quarto_notebook_test_fail.txt)
[quarto_notebook_test_success.txt](https://github.com/holoviz/panel/files/14746954/quarto_notebook_test_success.txt)

**Comment by philippjfr** [comment]
@DmitriyLeybel This is working now?

**Comment by DmitriyLeybel** [comment]
> @DmitriyLeybel This is working now?

It hit me that it's related to another issue I recently raised, given that I am creating the ipynbs in VS Code, which does not save Panel objects in a way that allows that to persist when opened in neither Juypter Notebook or in the VS Code Notebook - https://github.com/holoviz/panel/issues/6702
