### ISSUE TITLE
Loading indicator updates when scrolling when the style overflow-y auto is set

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#6581]
After testing out Panel 1.4.0rc6, I noticed that when scrolling, the loading indicator would update when scrolling. The MRE use a height of 100% to show off the problem. I can also recreate it with the `stretch_both` sizing mode on both of the `Markdown` and `Column`.

``` python
import panel as pn

obj = pn.Column(
    pn.pane.Markdown(height=2000, sizing_mode="stretch_width"),
    styles={"overflow-y": "auto", "height": "100%"},
    sizing_mode="stretch_both",
)

pn.template.BootstrapTemplate(main=[obj]).servable()
```

https://github.com/holoviz/panel/assets/19758978/967c93df-6c93-4bb6-9a76-f22c52af31bb

**Comment by philippjfr** [comment]
Fixed by https://github.com/holoviz/panel/pull/6582
