### ISSUE TITLE
Code Editor does render correctly when loaded in a method

### ISSUE THREAD

**Issue by singharpit94** [holoviz/panel#6596]
I am using panel 1.3.8 and observed that when I try to load the codeeditor extension in a method it does not render properly

Reproducer code

```
import panel as pn

def editor():
    pn.extension('codeeditor')
    py_code = "import sys"
    editor = pn.widgets.CodeEditor(value=py_code, sizing_mode='stretch_width', language='python', height=300)
    return editor

def simple():
    pn.extension()

    # Create a button
    button = pn.widgets.Button(name='Open Editor', button_type='primary')

    # Create a placeholder for the editor
    editor_placeholder = pn.Column()

    # Define what happens when the button is clicked
    def button_click(event):
        # Attach the code editor to the screen
        editor_placeholder.append(editor())

    # Link the button click to the function
    button.on_click(button_click)
 
    # Create the table
    w1 = pn.pane.Str("This is a test")

    # Return the layout
    return pn.Row(w1, button, editor_placeholder)

simple().servable()
```

Output

![image](https://github.com/holoviz/panel/assets/7591673/de8b1be0-529b-4544-8773-8aeab5c269ef)

Ideally I expected the code editor to load properly but it fails and I also get the following console error
![image](https://github.com/holoviz/panel/assets/7591673/b7ce87c4-530b-4f47-8676-11a23b989a04)

Can you please check this and recommended solutions here?

The reason I am loading the editor in a separate method is because when loaded together with other extensions it creates some conflicts with my own panel extension and they fail to render.

**Comment by philippjfr** [comment]
The extension must always be called with all required extension on initial render, i.e. you should do:

```python
import panel as pn

pn.extension('codeeditor')
```
