### ISSUE TITLE
Layout builder example not working

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6600]
I was trying to use the layout builder with example in the how-to guide https://panel.holoviz.org/how_to/notebook/layout_builder.html. 

But it does not work for me as the matplotlib plot is not displayed??

![image](https://github.com/holoviz/panel/assets/42288570/4f578085-5f7f-4fc0-b693-06f5bf4b64b2)

panel==1.4.0 bokeh=3.4.0 pyviz_comms=3.0.2

**Comment by MarcSkovMadsen** [comment]
When I restart jupyterlab and preview again it looks like

![image](https://github.com/holoviz/panel/assets/42288570/50bfe0b7-99f3-484b-984f-c3a0f1701a53)

If I drag the panels I can see content in the 3 first ones. But I have no way to reset the configuration from the UI. This will make it really hard for newbies.

**Comment by MarcSkovMadsen** [comment]
If I add `matplotlib.use('agg')` it works.

![image](https://github.com/holoviz/panel/assets/42288570/16310605-a349-4886-8baf-66c28f4be927)

But if I click either the refresh or save button nothing visible happens. The buttons don't have any visual effect when clicked. And I don't see anything refreshing or saved?

**Comment by MarcSkovMadsen** [comment]
The natural question is also why do I have two "refresh" buttons? What is the difference?

![image](https://github.com/holoviz/panel/assets/42288570/a57e0be7-862f-4365-8ad7-f91b467adb67)

**Comment by MarcSkovMadsen** [comment]
A comment is also that the guide is a mix of a tutorial, how-to guide and an explanation. Its not really clear what it is.

My recommendation would be to make it a tutorial. The target audience is newbees and non-panel users that want to share their notebooks as dashboards.

**Comment by MarcSkovMadsen** [comment]
Ahh. I can now see that the new, second "refresh" button is not a refresh button but a "clear settings button". Something happened when the layout was not the "default".

![image](https://github.com/holoviz/panel/assets/42288570/cf9763dd-5938-46a5-9777-916e75c960a8)

**Comment by MarcSkovMadsen** [comment]
Now I start getting the error below :-)

![image](https://github.com/holoviz/panel/assets/42288570/5d6e6189-511e-4033-8d9d-b7053af061ee)

**Comment by philippjfr** [comment]
Good feedback, thanks. On balance I think a video is probably the best way to convey how to use it.

>But it does not work for me as the matplotlib plot is not displayed??

This is very surprising to me, the code forces the backend to be agg. 

> Now I start getting the error below :-) And matplotlib will not display in the notebook.

Now that you can't blame on Panel 😄

**Comment by philippjfr** [comment]
>Something happened when the matplotlib pane did not take up the full width.

Matplotlib plots are set to scale, if you forced it to fill the space you'd have to distort it horribly.

**Comment by MarcSkovMadsen** [comment]
But I end up in a state like this and cannot solve. That is on Panel to solve.

https://github.com/holoviz/panel/assets/42288570/438ac560-7f42-4450-a3b3-dd776b4d27d1

**Comment by philippjfr** [comment]
Could you look at your browser console? Are there any weird errors?

**Comment by MarcSkovMadsen** [comment]
> Could you look at your browser console? Are there any weird errors?

![image](https://github.com/holoviz/panel/assets/42288570/b72897cc-f007-42a9-942d-6584602a5b45)

**Comment by MarcSkovMadsen** [comment]
This is what I get when I clear the browser and hit "refresh" in the Jupyter Panel Preview.

![image](https://github.com/holoviz/panel/assets/42288570/89e33b7a-d642-4559-9361-7682d0862cc1)

**Comment by philippjfr** [comment]
Doesn't look like there's anything related to Panel, but it does seem like there's an issue with the layout persistence. The layout persists in two levels:

- As you do any action in the preview the changes are written to a `.layout` file that lives next to the notebook.
- When you save the notebook the data in the `.layout` file is persisted into the notebook metadata.

I have not been able to reproduce the issue you seem to be having which is that the data written to the .layout file does not persist.

**Comment by MarcSkovMadsen** [comment]
I have not been able to identify a `.layout` file so far.

![image](https://github.com/holoviz/panel/assets/42288570/9e5a197b-e1e3-45d2-87e2-47b0f8fda602)

**Comment by philippjfr** [comment]
It's a hidden file, try `ls -a`

**Comment by philippjfr** [comment]
I think I've also encountered the issue, could you try removing spaces from the filename?

**Comment by MarcSkovMadsen** [comment]
Its there

![image](https://github.com/holoviz/panel/assets/42288570/487cac0c-3633-448e-9d53-68f8f85bde70)

```json
{"cells": {"ae3c447a-fa81-499e-a9ce-1d4f03c0865d": {"width": 62.6789, "height": 506, "visible": true}, "e1dbb77f-7860-4b2f-9837-03d9f513b7c3": {"width": 100, "height": 10, "visible": true}, "7352e53c-e521-45ba-8e3f-83050c4e8561": {"width": 100, "height": 10, "visible": true}, "3cbfb569-34fc-44c2-b8fe-096452cdf5e0": {"width": 100, "height": 10, "visible": true}}, "order": ["ae3c447a-fa81-499e-a9ce-1d4f03c0865d", "e1dbb77f-7860-4b2f-9837-03d9f513b7c3", "7352e53c-e521-45ba-8e3f-83050c4e8561", "3cbfb569-34fc-44c2-b8fe-096452cdf5e0"]}
```

**Comment by MarcSkovMadsen** [comment]
> I think I've also encountered the issue, could you try removing spaces from the filename?

I've renamed. Restarted Jupyter lab. Is see no change.

![image](https://github.com/holoviz/panel/assets/42288570/ae3402dd-9d3e-462d-a2a7-677096eabca7)

**Comment by MarcSkovMadsen** [comment]
When I restart jupyterlab and reload my notebook too, I see

![image](https://github.com/holoviz/panel/assets/42288570/53a72b34-9ca8-405e-b697-63363489e9bc)

(I am running on fresh virtual environment)

**Comment by MarcSkovMadsen** [comment]
Reading the docs again it appears to me the save button is only for use outside of Jupyter Panel Preview? If that is the case I think it should not be shown when running in the Jupyter Panel Preview.

**Comment by philippjfr** [comment]
>If that is the case I think it should not be shown when running in the Jupyter Panel Preview.

Yes I agree.

**Comment by MarcSkovMadsen** [comment]
I tried installing panel==1.4.0a1. But not it cannot find the `vanilla.css` file.

![image](https://github.com/holoviz/panel/assets/42288570/a73543f9-d6ae-45a6-a4a6-3c5271a30201)

**Comment by MarcSkovMadsen** [comment]
Ok. After some running notebooks from other folder than Panel repository root it seems to work better.

I had to delete all my `.layout` and `.ipynb` files and start all over. After that the example from the documentation started working for me.

- The `save` button is still shown though

![image](https://github.com/holoviz/panel/assets/42288570/57e8beb8-f796-4bf5-a4ea-59f21f25ddcc)

I would say the robustness can still be improved.

- Improve errors messages (Try rendering a notebook with markdown in a code cell)
- Support renaming of notebooks (currently I have to close and reopen the preview, also rename .layout file).
- Support deletion of notebooks (also delete .layout file).

**Comment by philippjfr** [comment]
That old error page seems to be indicating it's using an old version of Panel.

**Comment by MarcSkovMadsen** [comment]
> That old error page seems to be indicating it's using an old version of Panel.

D*mn. I've redone my test and updated the above post.

**Comment by philippjfr** [comment]
Thanks so much for the detailed testing.

>I can get into a state where I cannot get a working layout

I absolutely cannot reproduce this.

>The save button is still shown

It is not, you still seem to be picking up a wrong version of Panel.

>Avoid making height smaller and smaller for each reset click

Again, this is due to an older version of Panel.

>Make it clear how error message should be and are handled.

Very open to suggestions here, worth noting that apps that have an error have the same behavior but I suppose there you usually have access to the logs/terminal.

>Not clear how to fully clear all layout state

Yeah, there needs to be some mechanism for this. If I change the reset to be a full reset then I could probably achieve this.

>Make it clear when state has not been synced to notebook

Great idea, UI suggestions very welcome.

>Rename/Delete .layout file with Notebook

Indeed, will have to be changed in `pyviz_comms`.

**Comment by MarcSkovMadsen** [comment]
> It is not, you still seem to be picking up a wrong version of Panel. Jupyter installs are finnicky, check what jupyter serverextension list says.

As far as I can see everything is correctly configured

![image](https://github.com/holoviz/panel/assets/42288570/7f13fd25-e1e0-4e58-81ef-3c2ad310c6fc)

![image](https://github.com/holoviz/panel/assets/42288570/9a344c78-f89a-4832-a04c-6045b7e2db55)

**Comment by MarcSkovMadsen** [comment]
I just tried `pip install panel==1.4.0a1` again. I can see that it uninstalls bokeh 3.4.0 and installs 3.3.4. Could that be the issue/ difference?

**Comment by MarcSkovMadsen** [comment]
I tried forcing bokeh upgraded to 3.4.0 and I can still reproduce the "I can get into a state where I cannot get a working layout" issue.

**Comment by MarcSkovMadsen** [comment]
My mistake was testing panel==1.4.0a1 instead of 1.4.1a1. I've retested with 1.4.1a1 and updated posted above.

**Comment by MarcSkovMadsen** [comment]
The example from the docs still does not work for me. Added video and info above.

**Comment by philippjfr** [comment]
Very strange, absolutely cannot reproduce that issue.

**Comment by philippjfr** [comment]
Could it be that 1.4.1a1 still isn't the version it's running as the jupyter serverextension?

**Comment by philippjfr** [comment]
Jupyter sadly is very finicky since extensions can be installed in various places and precedence of each one is unclear to me, e.g. you can have an extension installed globally and in a particular environment.

**Comment by MarcSkovMadsen** [comment]
Are you sure that nothing is persisted in the browser cache/ storage system when doing this. To me that could be an explanation.

**Comment by MarcSkovMadsen** [comment]
![image](https://github.com/holoviz/panel/assets/42288570/08948e51-e5cb-469a-a421-f72743298157)

**Comment by MarcSkovMadsen** [comment]
Hmm. Clearing the local storage and hard refreshing does not help.

![image](https://github.com/holoviz/panel/assets/42288570/bc922ac8-a41f-42af-b18c-cfcf3cf1160e)

**Comment by MarcSkovMadsen** [comment]
The console error is just missing favicon

![image](https://github.com/holoviz/panel/assets/42288570/f1f297a8-ec82-4004-85bb-733d8b4fa501)

**Comment by philippjfr** [comment]
Seems like the first step to getting to the bottom of this will be to make the reset actually reset everything, local storage, .layout file and notebook metadata.

**Comment by MarcSkovMadsen** [comment]
I've

- cleared the metadata and .layout via the script
- cleared the localstorage
- restarted jupyter lab

Then it works

![image](https://github.com/holoviz/panel/assets/42288570/1c1ad150-12f0-4db4-9ab0-f28dda7870fb)

**Comment by philippjfr** [comment]
If the jupyterlab restart was actually required the only thing I can think of was that your JLab server was still running the old version before the restart.

**Comment by philippjfr** [comment]
Anyway, I'll work on the full reset next.

**Comment by MarcSkovMadsen** [comment]
I've have been restarting it many times this morning after installing panel==1.4.1a1.

**Comment by MarcSkovMadsen** [comment]
I think docs need improvement. I did not understand localstorage also involved for notebooks in preview. I thought that was only for served apps with `?editable=True`. Now I don't understand what takes precedence?

**Comment by philippjfr** [comment]
>I think docs need improvement. I did not understand localstorage also involved for notebooks in preview. I thought that was only for served apps with ?editable=True. Now I don't understand what takes precedence?

Since we removed the save button in the preview it should no longer allow you to use localstorage. Seems likely you had something in localstorage from before we hid the save button. The precedence hierarchy generally is:

1. `.layout` file
2. Notebook metadata
3. Localstorage

**Comment by MarcSkovMadsen** [comment]
Do you cache anything during the "layout" computation? Could that be an explanation?
