### ISSUE TITLE
DateRangePicker reference docs issues

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6605]
I'm testing out the new DaterangePicker

I see some issues.

## Output Cell not heigh enough

I cannot see the calender dropout when clicking the widget because the cell is not very heigh. This is confusing for new users trying to explore what this is and how it works.

![image](https://github.com/holoviz/panel/assets/42288570/dedc70fa-c754-465b-840d-291dcbd5184f)

## No real example provided

For a new user that might not even realise difference between `date` and `datetime` it can be hard to understand this widget when no example with real `date` `start` and `end` values are given.

## JSON serialization Error

When picking a date range in the controls section I get a JSON serialization error

https://github.com/holoviz/panel/assets/42288570/25358ca7-251f-4108-821e-b5826bd30c05

**Comment by TheoMathurin** [comment]
Thanks, I'll look into it.

I've used this as a custom widget for some time now and have not noticed anything but I still have to test it in v1.4.0.

**Comment by TheoMathurin** [comment]
It seems that the issue concerning visibility is not limited to this widget. The docs for the standard DatePicker also exhibits this behaviour.

For the second point, I'll make a PR with the value tuple set at instantiation.

However I have no idea why we're getting these serialisation errors. On my side I don't see this outside the docs, be it in a server or a notebook or a converted app.
