### ISSUE TITLE
Panel dev pytest-playwright conda version conflict

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#6622]
#### ALL software version info

See here: https://gist.github.com/cdeil/9291046977f5af468654af57dd083de6

#### Description of expected behavior and the observed behavior

I expect the instructions here to work to set up a dev environment:

https://panel.holoviz.org/developer_guide/index.html

#### Complete, minimal, self-contained example code that reproduces the issue

Trying to install pytest-playwright with conda fails.

#### Stack traceback and/or browser JavaScript console output
```
(panel_dev) panel $ conda install pytest-playwright -c microsoft -c conda-forge
Channels:
 - microsoft
 - conda-forge
 - defaults
 - pyviz/label/dev
 - bokeh
 - pyviz
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides playwright >=v1.33.0 needed by pytest-playwright-0.4.2-py_0

Could not solve for environment specs
The following packages are incompatible
└─ pytest-playwright is not installable because there are no viable options
   ├─ pytest-playwright 0.4.2 would require
   │  └─ playwright >=v1.33.0 , which does not exist (perhaps a missing channel);
   └─ pytest-playwright [0.4.3|0.4.4] would require
      └─ playwright >=1.37.0 , which does not exist (perhaps a missing channel).
```

I guess conda dependencies need to be modernised somehow?

**Comment by Hoxbro** [comment]
This is not a panel problem, playwright is not available on osx-arm64, see https://github.com/microsoft/playwright-python/pull/2211

We could update the documentation with a note.

**Comment by cdeil** [comment]
Ah OK, thanks! Maybe wait a bit to see if they build the conda package, and if they don't add the note.

**Comment by Tobias-Fischer** [comment]
It’s available from my channel if you need it: https://anaconda.org/tobiasrobotics/playwright

**Comment by philippjfr** [comment]
Long-time no see, thanks @Tobias-Fischer!

**Comment by Tobias-Fischer** [comment]
Good to see you here @philippjfr! I hope all is well. It’s been ten years since Edinburgh days!!
