### ISSUE TITLE
Windturbine Explorer App not secure

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6631]
If I go to https://panel.holoviz.org/gallery/index.html and click 

![image](https://github.com/holoviz/panel/assets/42288570/fbc6db1a-b834-41eb-97e2-5390efa2be9b)

It leads me to https://panel-gallery.pyviz.demo.anaconda.com/windturbines

which looks like

![image](https://github.com/holoviz/panel/assets/42288570/eeb7f22d-6c03-479f-8a07-4f72c621f808)

```bash
Your connection isn't private
Attackers might be trying to steal your information from panel-gallery.pyviz.demo.anaconda.com (for example, passwords, messages, or credit cards).
NET::ERR_CERT_DATE_INVALID
```

**Comment by philippjfr** [comment]
Very confused, we should have switched over to our new cluster by now.

**Comment by philippjfr** [comment]
Fixed in https://github.com/holoviz/panel/pull/6645
