### ISSUE TITLE
notifications page no in navigation index

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6646]
If you go to https://panel.holoviz.org/how_to/callbacks/notifications.html the page will not be shown in navigation index

![image](https://github.com/holoviz/panel/assets/42288570/005c648c-4506-4a6f-9ca9-9b879e67e3c1)

The similar page https://panel.holoviz.org/how_to/callbacks/server.html is

![image](https://github.com/holoviz/panel/assets/42288570/a3ae31ff-a267-48ec-88ae-ec4ccfdcf34e)

I tried to fix but could not find the cause.

**Comment by philippjfr** [comment]
Already fixed in https://github.com/holoviz/panel/pull/6615
