### ISSUE TITLE
Make --autoreload fully robust

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6649]
I experience various situations where autoreload will not work.

Often a manual browser refresh can solve the issue. But this is friction because

- The developer has to leave the editor and keyboard.
- The developer might not know what goes on if he does not have access to the terminal/ logs.

Please make sure that serving with autoreload always connects and never serves a blank page.

## Reproducible examples to solve

The examples below will be posted in individual comments below.

- [x] 1. Serve without `.servable()`
- [x] 2. SyntaxError: Change `900` to `0900`

I plan to add more examples as I experience them. I believe there are more cases also after Panel 1.4.0 release. But now I need to note them down.

**Comment by MarcSkovMadsen** [comment]
## 1. Serve without `.servable()`

```python
import panel as pn

pn.extension()

pn.panel("Hello World")
```

```bash
panel serve app.py --autoreload
```

![image](https://github.com/holoviz/panel/assets/42288570/4e4c7ef2-f9ef-468c-893b-29af49740a40)

- I would like a red alert box asking me to mark one or more objects as .servable(). Currently I get a blank window.
- I would like the browser to reload if I update to `pn.panel("Hello World").servable()`. Currently it does not.

**Comment by philippjfr** [comment]
Much appreciated!

**Comment by MarcSkovMadsen** [comment]
## Change `900` to `0900`

```python
import panel as pn

pn.extension()

pn.panel("hello", width=900).servable()
```

Try changing `900` to `0900`. Your window will turn blank and the terminal show

```bash
2024-04-02 21:15:39,402 Error running application handler <panel.io.handlers.ScriptHandler object at 0x0000027F68EE1ED0>: Invalid syntax in 'app.py' on line 5:
pn.panel("hello", width=0900).servable() Traceback (most recent call last):
  File "C:\repos\private\panel-140-social\.venv\Lib\site-packages\bokeh\application\handlers\code_runner.py", line 104, in __init__
    nodes = ast.parse(source, os.fspath(path))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\repos\private\panel-140-social\app.py", line 5
    pn.panel("hello", width=0900).servable()
                            ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```
