### ISSUE TITLE
No loading spinner with panel convert --to pyodide

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6652]
In https://discourse.holoviz.org/t/pyodide-loading-spinner-in-1-4/7045 zmoon reports that with Panel 1.4.0 there is no longer a loading spinner when he uses `panel convert --to pyodide app.py` on

```python
import panel as pn

pn.extension()

pn.pane.Markdown("# hi").servable()
```

I can reproduce this issue.

## Additional Context

With the reference example in https://panel.holoviz.org/how_to/wasm/convert.html it works for me though.

**Comment by zmoon** [comment]
Thanks
