### ISSUE TITLE
Perspective 2.8.0 rendering issues in Panel 1.4

### ISSUE THREAD

**Issue by sjpfenninger** [holoviz/panel#6653]
#### ALL software version info

OS: macOS 14.4.1
Python: 3.12.2
Panel: 1.4.0

#### Description of expected behavior and the observed behavior

There seems to be some issues with the updated perspective in Panel 1.4.0.

Running the first example from https://panel.holoviz.org/reference/panes/Perspective.html, this is how it is rendered in  the most recent Chrome (on macOS):

![chrome](https://github.com/holoviz/panel/assets/141709/700a84f6-dc9a-4cab-b1b9-525b3a6e5675)

Looks fine!

But this is how it looks in both the most recent versions of Firefox 124 and Safari 17.4.1 on macOS:

![firefox](https://github.com/holoviz/panel/assets/141709/c078494f-0472-4b7e-893e-a02f8563ede4)

Quite a bit of formatting is lost. There is no highlight on hover. And, various operations (scrolling, but also collapsing and uncollapsing grouped indexes) trigger the [scrolling bug described here](https://github.com/finos/perspective/issues/2357).

Given the presence of that bug in perspective this seems to be at least partly an upstream issue. BUT most of the examples on the perspective website do work fine in Firefox, and none of the perspective website examples trigger these issues in Safari. So there seems to be something specific to how perspective is included in Panel that triggers this bug in both Firefox and Safari.

Note that Panel 1.3 with perspective 1.9.3 works fine in all three browsers.

#### Complete, minimal, self-contained example code that reproduces the issue

This is the first example from https://panel.holoviz.org/reference/panes/Perspective.html with no modifications except the addition of the `.show()` call:

```python
import panel as pn
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

pn.extension('perspective')

data = {
    'int': [random.randint(-10, 10) for _ in range(9)],
    'float': [random.uniform(-10, 10) for _ in range(9)],
    'date': [(datetime.now() + timedelta(days=i)).date() for i in range(9)],
    'datetime': [(datetime.now() + timedelta(hours=i)) for i in range(9)],
    'category': ['Category A', 'Category B', 'Category C', 'Category A', 'Category B',
             'Category C', 'Category A', 'Category B', 'Category C',],
    'link': ['https://panel.holoviz.org/', 'https://discourse.holoviz.org/', 'https://github.com/holoviz/panel']*3,
}
df = pd.DataFrame(data)

p = pn.pane.Perspective(df, width=1000)
p.show()
```

#### Stack traceback and/or browser JavaScript console output

There are no errors and no visible signs of anything unusual happening in the Javascript console.

**Comment by philippjfr** [comment]
Thank you for the detailed bug report! Likely something to do with the way CSS is included in the shadow DOM. I'll try to get a fix into 1.4.1.

**Comment by sjpfenninger** [comment]
Thanks! Is it an option in the meantime to locally override the perspective version back to the fully working <2? Having quickly scanned the code, it seems to me that its integration is hardcoded in various ways so you can't just e.g. monkey-patch `PERSPECTIVE_VERSION` back to `1.9.3`.

**Comment by philippjfr** [comment]
Yeah, I wouldn't think that would work well. I'll try to get the release out asap.

**Comment by sjpfenninger** [comment]
Thanks a lot, that was super quick!
