### ISSUE TITLE
Issue with examples in `Add Interactivity with pn.bind` tutorial

### ISSUE THREAD

**Issue by jrycw** [holoviz/panel#6688]
While following the [Add Interactivity with pn.bind](https://panel.holoviz.org/how_to/streamlit_migration/interactivity.html) tutorial, I noticed some discrepancies in the documentation that may require attention:

1. The code for the [Panel Multiple Updates Example](https://panel.holoviz.org/how_to/streamlit_migration/interactivity.html#panel-multiple-updates-example) appears to be missing.
2. The code for the [Panel Multiple Updates Alternative Indicator Example](https://panel.holoviz.org/how_to/streamlit_migration/interactivity.html#panel-multiple-updates-alternative-indicator-example) is not executable due to an error message stating `AttributeError: 'Button.param' object has no attribute 'set'`.
3. The code for the [Panel Multiple Results Example](https://panel.holoviz.org/how_to/streamlit_migration/interactivity.html#panel-multiple-results-example) does not seem to match the animation provided.

Unfortunately, I am unable to address the first two issues. However, I've attempted to reconstruct the code for the last issue as follows:

```python
import random
import time

import panel as pn

pn.extension(sizing_mode="stretch_width", template="material")


def model():
    time.sleep(1)
    return random.randint(0, 100)


def results(running):
    if not running:
        yield layout
        return

    layout.clear()
    for i in range(10):
        layout.append(loading)
        yield layout
        result = model()
        result = pn.panel(f"Result {i}: {result}")
        layout[-1] = result
        yield layout


run_input = pn.widgets.Button(name="Run model")
loading = pn.widgets.LoadingSpinner(
    value=True, size=50, name="Running... Please Wait!"
)
layout = pn.Column("Calculation did not run yet")

pn.Column(run_input, pn.bind(results, run_input)).servable()
```

## Animation Comparisons
* Provided animation
![Provided animation](https://assets.holoviz.org/panel/gifs/panel_sync_multi_example.gif )

* Reconstructed animation
https://github.com/holoviz/panel/assets/67060418/5578d7c0-7c81-4df0-b180-4672876724d0

**Comment by philippjfr** [comment]
For 2. the API is `button.param.update(loading=True)`

**Comment by jrycw** [comment]
Thanks for the response. The code for 2 is now able to run, but it seems the result resembles more closely the animation for 1.

**Comment by jrycw** [comment]
@MarcSkovMadsen Thank you for the PR. It appears that for part 1, the animation is more closely aligned with complete removal of the line `with run_input.param.update(loading=True):`. 

Meanwhile, I've noticed something interesting: when selecting `B` for the first time, the gap between `B` and `You chose: B` narrows slightly. Is there any way to prevent this behavior?
