### ISSUE TITLE
Inconsistent pn.state.busy when throttling is enabled globally

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#6697]
#### ALL software version info
Panel 1.4.0
Bokeh 3.4.0
In a server

#### Description of expected behavior and the observed behavior
I expect `pn.state.busy` to reflect the actual state of the app. With Panel 1.4.0, if `pn.config.throttled` is set to `True`, the busy parameter will be `True` as soon as a slider is moved, even if it's not released, and stay `True` forever, including in new sessions for the remainder of the app life cycle.

Note that this does not happen if throttling is disabled globally and the function is bound to `slider.param.value_throttled`.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn

pn.extension(throttled=True)


def synced_spinner(value):
    return pn.indicators.LoadingSpinner(value=value)


slider = pn.widgets.IntSlider(name='Slider', start=0, end=1)
text = pn.bind(lambda x: f'Value of slider is {x}', slider)
spinner = pn.bind(synced_spinner, pn.state.param.busy)

pn.Row(pn.Column(slider, text), spinner).servable()
```

#### Stack traceback and/or browser JavaScript console output
No error in python or javascript

#### Screenshots or screencasts of the bug in action
![busy_bug](https://github.com/holoviz/panel/assets/49269671/ab13ba97-1737-4588-aa47-b804b06aa7e4)

**Comment by philippjfr** [comment]
Strangely I was able to reproduce this once, and then never again.
