### ISSUE TITLE
Perspective not rendering in reference docs after Panel 1.4.1 release

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6699]
https://panel.holoviz.org/reference/panes/Perspective.html

![image](https://github.com/holoviz/panel/assets/42288570/24f95f86-027d-490d-9498-f8a2e6dff5cb)

I've tried refreshing and hard refreshing. Nothing is shown. Don't see errors in browser console.

**Comment by philippjfr** [comment]
This is an nbsite, issue, I'm working on it.

**Comment by MarcSkovMadsen** [comment]
Works for me. Thanks.
