### ISSUE TITLE
Proposal to add context managers to all Layouts + Templates

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#6712]
Inspired by @MarcSkovMadsen's comment https://github.com/holoviz/panel/pull/6617#issuecomment-2033012533

Many times, I find myself doing something like:

```python
widget_box = pn.WidgetBox(pn.widgets.TextInput())

def process(event):
    try:
        widget_box.loading = True
        ...
    finally:
        widget_box.loading = False
```

I'm wondering whether we can simplify it:

```python
widget_box = pn.WidgetBox(pn.widgets.TextInput())

with widget_box:
    ...
```

For templates, it'd be the same:

```python
template = pn.templates.FastListTemplate()
with template:  # disables all
    ...
```

I think this would work with all layouts, except maybe Swipe (which I think is more fitting to be a Pane).

Additionally, for a future `pn.StatusCard` ([or currently `pn.chat.ChatStep`](https://github.com/holoviz/panel/pull/6617/files#diff-d3616d3db8f32d74dfaa200f179c2cfcd27066a3b6a43f8f8f36420c9a178bfaR117-R142)), I imagine it would also update the `status` param on `finally`.

**Comment by ahuang11** [comment]
Maybe it can be useful for BooleanIndicators too.

**Comment by ahuang11** [comment]
Ah Philipp mentioned that we could simply use `with param.update`

```python
import time
import panel as pn

pn.extension()

layout = pn.WidgetBox(pn.widgets.TextInput(), pn.widgets.Button(name="Click me!"))
layout
```

I think there's no need for this proposal then!
```
with layout.param.update(loading=True, disabled=True):
    time.sleep(2)
    layout[0].value = "Loaded!"
```

**Comment by MarcSkovMadsen** [comment]
I have also seen pn.con.set and .set_values. Would be Nice to align on .update to reduce What you need to remember.

**Comment by maximlt** [comment]
`<obj>.param.update()` has been added in Param 2.0 so it's quite recent. It can be used as a context manager or not.
