### ISSUE TITLE
Panel applications server lost styling in 1.4

### ISSUE THREAD

**Issue by yt87** [holoviz/panel#6714]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
```
browsers: Chromium, Firefox
python                    3.12.2          hab00c5b_0_cpython    conda-forge
bokeh                     3.4.0              pyhd8ed1ab_0    conda-forge
panel                     1.4.1              pyhd8ed1ab_0    conda-forge
```

#### Description of expected behavior and the observed behavior
The app selection window is displayed in black/white, the link to panel website (blue icons) no longer works. Browser console output show missing thumbnails - shown on the included screenshot. I do not recall seeing them before. Those messages are also printed to stdout:
```
/tmp python foo.py 
Launching server at http://localhost:50000
404 GET /thumbnails/foo.png (::1) 0.33ms
404 GET /thumbnails/admin.png (::1) 0.14ms
```
#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
import panel as pn

pn.extension(theme='dark')

def foo():
    return pn.template.FastListTemplate(
            main=[pn.pane.Markdown('Some text here')],
            title='Test',
            )

pn.serve({'foo': foo}, show=False, admin=True, port=50000)
```

#### Stack traceback and/or browser JavaScript console output

﻿
#### Screenshots or screencasts of the bug in action
![panel](https://github.com/holoviz/panel/assets/40218891/f7091923-fb68-40d1-91f6-3de8d3d4b05a)

- [ ] I may be interested in making a pull request to address this

**Comment by philippjfr** [comment]
This is expected, we simplified the design because the old one was quite garish. Restoring the link to the website we should consider.

**Comment by philippjfr** [comment]
>Browser console output show missing thumbnails - shown on the included screenshot. I do not recall seeing them before. Those messages are also printed to stdout:

These were there before, the idea being that it loads the thumbnails if they are available but falls back otherwise.

**Comment by yt87** [comment]
OK, I see. So the difference is that the fancy colour strip, links to the Panel website and the theme toggle are gone. I checked the release page, could not find a relevant entry.

**Comment by yt87** [comment]
Should I close this, or you want to wait until you decide on restoring the link? I found the link useful during presentation of a suite of my apps. Someone asked about the underlying technology, my response was to click on the blue icons.
A minor quirk: the `Reference` link https://panel.holoviz.org/user_guide/Server_Configuration.html#serving-multiple-apps in ``pn.serve`` docstring  is dead. I can't figure out how to use the ``title`` keyword. Neither a string nor dictionary make a difference in the display.
