### ISSUE TITLE
1.4 Perspective issues

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6722]
I'm on Panel==1.4.1 on linux jupyter hub, edge browser on windows

The settings sidebar background does not look great

![image](https://github.com/holoviz/panel/assets/42288570/f3fe6466-b89f-481f-bd95-7f08dd01255c)

```python
import panel as pn
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

pn.extension('perspective')

data = {
    'int': [random.randint(-10, 10) for _ in range(9)],
    'float': [random.uniform(-10, 10) for _ in range(9)],
    'date': [(datetime.now() + timedelta(days=i)).date() for i in range(9)],
    'datetime': [(datetime.now() + timedelta(hours=i)) for i in range(9)],
    'category': ['Category A', 'Category B', 'Category C', 'Category A', 'Category B',
             'Category C', 'Category A', 'Category B', 'Category C',],
    'link': ['https://panel.holoviz.org/', 'https://discourse.holoviz.org/', 'https://github.com/holoviz/panel']*3,
}
df = pd.DataFrame(data)

perspective = pn.pane.Perspective(df, height=600, width=1000)
pn.Column(perspective.param.settings, perspective).servable()
```

If I go to the documentation it looks fine

![image](https://github.com/holoviz/panel/assets/42288570/6a841ab2-0e9e-49f9-b827-0c2643e42790)

If I change from Edge to Firefox browser the served app also looks fine.

![image](https://github.com/holoviz/panel/assets/42288570/3f0a6e9a-2c7e-4e85-b8a1-be4775828837)

### App on Edge

No issues in Console. No issues in Network.

But sidebar background looks as shown above.

If I disable the background it looks like

![image](https://github.com/holoviz/panel/assets/42288570/186e5dbf-b96d-4865-b1c9-b272624abcf2)

### Documentation on Edge

The output cells are empty unless I hard refresh. After hard refresh Perspective looks fine.

![image](https://github.com/holoviz/panel/assets/42288570/cc831fc3-f997-4b66-b3c1-f0a857a52715)

There are no errors in the browser console. But material-dark.css is missing.

![image](https://github.com/holoviz/panel/assets/42288570/548dffd5-88d5-4350-9bfb-84b11c93f9ae)

### App on Firefox

No issues in Console. No issues in Network.

**Comment by philippjfr** [comment]
Fixed the material theme issues in #6764 and could not reproduce any issues in Edge anymore so will (auto-)close when merging the PR.
