### ISSUE TITLE
A tooltip on javascript widgets could be useful

### ISSUE THREAD

**Issue by jlstevens** [holoviz/panel#674]
One static thing that could be mentioned on hover is that 'P'  plays forward and 'R' plays in reverse.

This would already be useful, but if you want to be fancier you could generate dynamic tool tips that also supply some information about the dimensions that are varied over.

**Edit:** This isn't really specific to slider widgets really...

**Comment by philippjfr** [comment]
Closing in favor of https://github.com/holoviz/panel/issues/1298
