### ISSUE TITLE
Tabulator `page_size` sometimes has no effect

### ISSUE THREAD

**Issue by hoxbro** [holoviz/panel#6747]
I don't know why it happens, In the example below, when the dataframe size is 9999 or smaller, it will show all the data and not the page size.

https://github.com/holoviz/panel/assets/19758978/605efeab-67f2-4303-ad8a-da7b9b69aa2a

``` python
import pandas as pd
import panel as pn
import param
import numpy as np

pn.extension("tabulator", throttled=True)

N = 20_000

class Example(pn.viewable.Viewer):
    date = param.Range(default=(0, N // 2), bounds=(0, N), step=1)
    filtered_df = param.DataFrame(precedence=-1)
    _df = pd.DataFrame({"Datetime": np.arange(N)})

    @param.depends("date", watch=True, on_init=True)
    def _update(self):
        mask = self._df["Datetime"].between(*self.date)
        self.filtered_df = self._df[mask].copy()

    def __panel__(self):
        return pn.Row(
            pn.Param(self),
            pn.widgets.Tabulator(value=self.param.filtered_df, page_size=10),
        )


Example()
```

**Comment by philippjfr** [comment]
This is (currently) expected behavior, `page_size` does nothing to control whether pagination is on. The default behavior is that we automatically toggle pagination to 'remote' if the data contains more than 10,000 rows. I don't think it'd be unreasonable to enable pagination automatically if you set a page_size however.

**Comment by philippjfr** [comment]
I'm going to close as wontfix, `pagination` is the correct way to toggle pagination behavior, `page_size` simply controls the page size once it is enabled.

**Comment by hoxbro** [comment]
Could a warning be made if page_size is set and pagination is not?
