### ISSUE TITLE
[Build] Minified PlotlyPlot can't be downloaded

### ISSUE THREAD

**Issue by waarmond** [holoviz/panel#6785]
#### ALL software version info
ArchLinux
Python 3.10
bokeh 3.4.1 (git master)
node 18.20.2
more?

#### Complete, minimal, self-contained example code that reproduces the issue

```
python -m build --wheel --no-isolation
```

#### Stack traceback and/or browser JavaScript console output
```
Output written to ./panel/panel/dist
All done.
Bundling custom model resources:
error: Failed to fetch PlotlyPlot dependency: https://cdn.plot.ly/plotly-2.31.1.min.js. Errored with a bytes-like object is required, not 'NoneType'.
```

Shall I override the following?
```
    __javascript_raw__ = [
        JS_URLS['jQuery'],
        'https://cdn.plot.ly/plotly-2.31.1.min.js'
    ]
```
Plotly installs an equivalent file to
`/usr/lib/python3.10/site-packages/plotly/package_data/plotly.min.js`

#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this

**Comment by philippjfr** [comment]
Sorry for the slow response, I can't reproduce any problem here.
