### ISSUE TITLE
Add container option for subpanel_layout

### ISSUE THREAD

**Issue by jbednar** [holoviz/panel#68]
Right now, the Param pane supports an option `subpanel_layout`, which can be set to a Row, Column, or Tabs layout, which determines what happens when someone clicks on '..." to edit the subobject's parameters (i.e. either opening up a new set of widgets in a row, in a column, or in a different tab). There's a fourth useful option, which is to open up those widgets in a specific container provided explicitly, so that users can put that container anywhere on the visible page.  There would need to be a way to pass in that container, and there might need to be a way to specify which parameter this container applies to (either all subobjects, or maybe just one specific subobject, with another container provided for each other subobject).

**Comment by philippjfr** [comment]
Partially addressed. It's not yet possible to provide separate containers for each subobject.

**Comment by jbednar** [comment]
That's great, thanks!

**Comment by kcpevey** [comment]
Closing until someone needs this particular function (re @philippjfr ). Otherwise, this is partially addressed.
