### ISSUE TITLE
Download functionality

### ISSUE THREAD

**Issue by coobas** [holoviz/panel#680]
A feature that would enable an easy way to download an app (or its part) as html would be useful, especially when running on a server.

Example use case: Report generator. User provides inputs, clicks on a generate button, a generated report is diplayed in the app, optionally interacts with plots in the generated report, the report *can be downloaded by the user as an html file* by clicking on a download button.

So far it seems we could use the `save` method, which generates a local html file, and use some custom JS to serve this file to the user (e.g. something like https://stackoverflow.com/questions/49388511/send-file-from-server-to-client-on-bokeh).

**Comment by philippjfr** [comment]
This seems like a great idea!

**Comment by coobas** [comment]
I may have some time to help but I have no contribution to Panel / Bokeh (yet ;) but would welcome getting an experience) and minimum JS skills hence would need hints to contribute efficiently ;)

**Comment by philippjfr** [comment]
We now have the `FileDownload` widget and you can define static directories to serve alongside your app.
