### ISSUE TITLE
NestedSelect example does not work

### ISSUE THREAD

**Issue by itsgifnotjiff** [holoviz/panel#6827]
[This NestedSelect tutorial](https://panel.holoviz.org/reference/widgets/NestedSelect.html) does not work. It throws `ValueError` as is and I am really trying to make it work but I simply can't.

```python
def list_options(level, value):
    if level == "time_step":
        options = {"Daily": list_options, "Monthly": list_options}
    elif level == "level_type":
        options = {f"{value['time_step']}_upper": list_options, f"{value['time_step']}_lower": list_options}
    else:
        options = [f"{value['level_type']}.json", f"{value['level_type']}.csv"]

    return options

pn.widgets.NestedSelect(
    options=list_options,
    levels=["time_step", "level_type", "file_type"],
)
```

**Comment by ahuang11** [comment]
Can you please share the error? It works fine for me.

<img width="893" alt="image" src="https://github.com/holoviz/panel/assets/15331990/50754e46-cbe1-40bb-b5f5-97bedd1beee6">

**Comment by itsgifnotjiff** [comment]
This one might be on me. Ever since I upgraded to Panel 1.4.2 from 1.3.8 I have been having very exotic issues like not displaying widgets and ValueErrors. I would actually close this issue until someone else reports it as I have zero confidence blaming Panel for the mishap.
