### ISSUE TITLE
pn.interact does not support holoviews hv.Layout and hv.Overlay objects

### ISSUE THREAD

**Issue by gdk-gagan** [holoviz/panel#683]
Problem description:
I am building a dashboard for real-time anomaly detection using panel and holoviews for plotting. To visualize anomalies scattered over the plot, I am using Layout objects in my custom plot function.

Requested solution:
Support for Layout objects in pn.interact

Error:
ValueError: interactive pane does not support objects of type 'Overlay'

**Comment by philippjfr** [comment]
Could you provide a minimal example? Works fine for me:

```python
def a(a=1):
    return hv.Curve([1, 2, a]) + hv.Curve([3, 2, a])

pn.interact(a)
```

It sounds like you're passing the Overlay/Layout object directly to the pane? Interact is meant to be given a function.
