### ISSUE TITLE
`--autoreload` leads to error after upgrade to 1.4.2

### ISSUE THREAD

**Issue by yjcui** [holoviz/panel#6838]
I recently updated from 1.3.x to latest 1.4.2 and noticed the previously working dashboard based on Jupyter Notebook stopped working. After trial and error, I located the cause with `--autoreload` option. With it, I kept getting below message but no dashboard was created in my localhost. I did get this `FIXED_SIZING_MODE` warning before, but it did not stop generating the dashboard.

![image](https://github.com/holoviz/panel/assets/87352042/b581a191-f9f3-448d-80f9-e1039bb65b47)

If I remove the `--autoreload` option, everything works just like before.

**Comment by philippjfr** [comment]
Does it work if you install `watchfiles`?

**Comment by sylvaint** [comment]
> Does it work if you install `watchfiles`?
I have the same issue and it does not work when installing watchfiles.

**Comment by philippjfr** [comment]
Okay, I've got a request for you. Could one of you go into your installed panel and edit `panel/command/__init__.py` and change line 96 from `die("ERROR: " + str(e))` to `raise e` and then report back with the error message?

**Comment by sylvaint** [comment]
<img width="1537" alt="image" src="https://github.com/holoviz/panel/assets/5510517/a7c67173-ac17-4311-9254-8dc438cd5d6a">

**Comment by philippjfr** [comment]
Super helpful. Thank you. Will get a fix into 1.4.3.

**Comment by sylvaint** [comment]
Awesome, thank you.
