### ISSUE TITLE
AutocompleteInput that allows non-pre-defined options as their value

### ISSUE THREAD

**Issue by ericmjl** [holoviz/panel#685]
**Is your feature request related to a problem? Please describe.**

This is not related to a problem.

**Describe the solution you'd like**

I am putting in a feature request for `AutocompleteInput` that allows non-predefined values as its value, as well as a feature request for `AutocompleteInput` to permit substring matching.

The use case is as follows: We have a database field that is free text but short, representing human-defined categories of stuff. (In our case, it's plates attached to experiments, where the experiment names are defined by humans.) 

At the moment, we use two text boxes, and tell our users to use the correct one: AutocompleteInput if they are attaching plates to an existing experiment, and a plain text input box if they are creating a new experiment. 

The front-end might be simplified by allowing users to enter the experiment name into the text box directly, and then choosing an existing experiment name from there. Permitting substring matching would be helpful in this case, for example we might have an experiment name that is "cherry-picking on mutant 53", but I might only remember 53 and enter it first.

**Describe alternatives you've considered**

I understand this may break the API compatibility with "single value, option selection" widgets. Hence, if this were a different widget, that would be cool too.

**Additional context**

No other additional context that I can think of.

**Comment by analog-cbarber** [comment]
I would like this feature. All of my use-cases in which I would have liked an auto-complete widget need to accept inputs other than the predefined options.

**Comment by ltalirz** [comment]
Indeed, this enhancement would significantly expand the applicability of this widget. 
So far, its purpose is to select a value from a very long but fixed list - but long lists often are long because people keep adding to them.

@philippjfr Perhaps some pointers on how to implement this could help move this forward?

**Comment by ltalirz** [comment]
Having a brief look, the widget seems to build upon the `bokeh.models.widgets.AutocompleteInput` widget
https://github.com/holoviz/panel/blob/42065be49e87bccc81375424d350c5f4ef6bd491/panel/widgets/select.py#L194

and there already is a parallel issue https://github.com/bokeh/bokeh/issues/9605 I guess this feature should be added in bokeh.

**Comment by ltalirz** [comment]
@philippjfr The PR that adds this functionality in bokeh has been merged https://github.com/bokeh/bokeh/pull/10476#event-3753562265

Looking at the corresponding code in panel
https://github.com/holoviz/panel/blob/42065be49e87bccc81375424d350c5f4ef6bd491/panel/widgets/select.py#L182-L196
it's not entirely clear to me whether one needs to add the new `restrict` field in panel explicitly or whether it will be "inherited"?

**Comment by philippjfr** [comment]
It will indeed need to be mirrored into Panel as a parameter.

**Comment by ltalirz** [comment]
How should I go about adding this? Do I need to wait for bokeh 2.3.0 to be released?

I've asked them to make a 2.3.0dev0 release - I could increase the minimum bokeh version to that in the PR...
