### ISSUE TITLE
Interactivity tutorial returns error when first cell is run.

### ISSUE THREAD

**Issue by Coderambling** [holoviz/panel#6850]
Page: https://panel.holoviz.org/tutorials/intermediate/interactivity.html

Result of pressing Play on first cell:

pyodide.ffi.JsException: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://assets.holoviz.org/panel/tutorials/turbines.csv.gz'.

The file downloads fine when the link is entered in a browser.

Content of first cell:

import panel as pn
import pandas as pd

pn.extension("tabulator")

data_url = 'https://assets.holoviz.org/panel/tutorials/turbines.csv.gz'

turbines = pn.cache(pd.read_csv)(data_url)

cols = pn.widgets.MultiChoice(
    options=turbines.columns.to_list(), value=['p_name', 't_state', 't_county', 'p_year', 't_manu', 'p_cap'],
    width=500, height=100, name='Columns'
)

**Comment by philippjfr** [comment]
Cannot reproduce this, seems like a network error on your end.

**Comment by Coderambling** [comment]
Tried again and it works for me now. Strange, beause separate  download of the file was worked fine at the time I observed the error.

**Comment by philippjfr** [comment]
Thanks for reporting back, I'll close for now.
