### ISSUE TITLE
Tabulator inputs trigger keyboard shortcuts

### ISSUE THREAD

**Issue by eaglesemanation** [holoviz/panel#6852]
I'm experiencing the same issue as discussed in #6314, but only limited to Tabulator inputs

#### ALL software version info
Panel 1.4.2
JupyterLab 4.1.6

#### Description of expected behavior and the observed behavior
Expecting to enter any numbers without issues.
In reality, if I try to write numbers into tabulator widget - cell converts into markdown.
If I try to write into another input first and only then write into tabulator - works without any issues.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import pandas as pd
pn.extension("tabulator")
pn.Column(
    pn.widgets.IntInput(),
    pn.widgets.Tabulator(pd.DataFrame({"A": [0], "B": [1]}))
)
```

#### Stack traceback and/or browser JavaScript console output
Nothing helpful here

#### Screenshots or screencasts of the bug in action

[Screencast from 2024-05-19 14-44-12.webm](https://github.com/holoviz/panel/assets/52473614/9a23ef2d-8f96-4ecd-b29a-53b3d832021c)

- [x] I may be interested in making a pull request to address this

**Comment by hoxbro** [comment]
This should be fixed with https://github.com/holoviz/panel/pull/6825, and will be released this week.
