### ISSUE TITLE
panel 1.4.3 regression: KeyError: 'content' in jupyterlab

### ISSUE THREAD

**Issue by avivazran** [holoviz/panel#6865]
#### ALL software version info
OS: win10
Jupyter Lab Version 4.1.5
bokeh version: 3.4.1
Python version: 3.9.13

#### Complete, minimal, self-contained example code that reproduces the issue

```python
multi_select = pn.widgets.MultiSelect(name='MultiSelect', value=['Apple', 'Pear'],
    options=['Apple', 'Banana', 'Pear', 'Strawberry'], size=8)

multi_select
```

```python
Traceback (most recent call last):
  File "C:\PythonCodes\SEVToolBox\sev_tools_env\sevtoolboxenv\lib\site-packages\pyviz_comms\__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "C:\PythonCodes\SEVToolBox\sev_tools_env\sevtoolboxenv\lib\site-packages\panel\viewable.py", line 469, in _on_msg
    patch = manager.assemble(msg)
  File "C:\PythonCodes\SEVToolBox\sev_tools_env\sevtoolboxenv\lib\site-packages\panel\models\comm_manager.py", line 29, in assemble
    msg_obj = cls(header, msg['metadata'], msg['content'])
KeyError: 'content'
```

#### Stack traceback and/or browser JavaScript console output
![image](https://github.com/holoviz/panel/assets/39994570/3f994721-490a-402a-8afe-9d9b67c672bc)

#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/panel/assets/39994570/ce2106d5-a2e2-4788-bb26-c329de8ceec0)

- [ ] I may be interested in making a pull request to address this

**Comment by hoxbro** [comment]
Can't seem to recreate it. Can you check if you have the latest version of pyviz_comms?

**Comment by xdev-x** [comment]
Same issue here, with the latest version of pyviz_comms. How can we help you to reproduce ?

**Comment by avivazran** [comment]
Looks like issue affects widgets based on jupyter widgets or ipywidgets. Issue is gone after pulling previous environment from git. My venv code sits on its own repo.

**Comment by ahuang11** [comment]
I think downgrading to 1.4.2 works `pip install panel!=1.4.3`. Just be sure to restart kernel / close browser / clear browser cache after.

**Comment by pmav99** [comment]
> I think downgrading to 1.4.2 works pip install panel!=1.4.3. Just be sure to restart kernel / close browser / clear browser cache after.

@ahuang I think that the trick is to actually "clean" the notebook. (e.g. `nbstripout` or "Restart and clean all cell outputs"). If I understand this correctly, `panel.extension()` injects some JS code in the `*.ipynb` file which loads the JS/CSS files from the CDN. If you don't clean the notebook, then as soon as the browser page loads, this JS code seems to gets executed and the result is that you get the behavior of the "before-the-update" panel version.

**Comment by vsriram11** [comment]
I'm facing the same issue, and the fix suggested above to restart/hard reload does not work for me. The regression is actually from 1.3.8 to 1.4.0, fixing panel version to 1.3.8 resolves the issue for me.

**Comment by pmav99** [comment]
Nope. 1.4.1 and 1.4.2 work fine. But you must clean the notebook **and** save it before you reload the tab and restart the kernel. That being said if you don't need some feature from panel 1.4 (or bokeh 3.4) then you are fine with downgrading to 1.3, too

**Comment by MarcSkovMadsen** [comment]
I also experienced this issue in our Jupyterlab after upgrading its Python environment.

**Comment by philippjfr** [comment]
Yes, this is an urgent regression. Will release 1.4.4 tomorrow.
