### ISSUE TITLE
Accordion vertical text after toggling on/off

### ISSUE THREAD

**Issue by lsagorin** [holoviz/panel#6869]
This is my first issue, so forgive me in case of a wrong usage or duple issue, but couldn't find anything.

#### ALL software version info
panel==1.3.8

#### Description of expected behavior and the observed behavior

Originally the accordion loads correctly, but after toggling off and on the accordion using the button, the displayed names are all messed up. Clicking on the accordion correct the problem.

#### Complete, minimal, self-contained example code that reproduces the issue
I used ChatGPT to create a easy example of this issue.
```
import panel as pn

# Initialize the panel extension
pn.extension()

# Define the content for each panel
panel1 = pn.pane.Markdown("## Panel 1 Content\nThis is the content of the first panel.")
panel2 = pn.pane.Markdown("## Panel 2 Content\nThis is the content of the second panel.")
panel3 = pn.pane.Markdown("## Panel 3 Content\nThis is the content of the third panel.")

# Create the accordion
accordion = pn.Accordion(('Panel 1', panel1), ('Panel 2', panel2), ('Panel 3', panel3))

# Create the button
toggle_button = pn.widgets.Button(name='Toggle Accordion', button_type='primary')

# Define the callback function to toggle the visibility
def toggle_accordion(event):
    accordion.visible = not accordion.visible

# Attach the callback to the button
toggle_button.on_click(toggle_accordion)

# Layout the button and accordion
layout = pn.Column(toggle_button, accordion)

# Serve the layout
layout.show()


```

#### Screenshots or screencasts of the bug in action
Before toggling : 
![image](https://github.com/holoviz/panel/assets/171029078/c9c4d7b7-bb5f-462c-aa78-087c903c8aca)

After toggling : 
![image](https://github.com/holoviz/panel/assets/171029078/ac4c7081-9c46-4c58-9d40-2849df309881)

**Comment by hoxbro** [comment]
Welcome! This is a great first issue. 

Can you try and upgrade Panel to 1.4.3 and see if the problem persists?

**Comment by lsagorin** [comment]
Hello, thanks for the quick answer @hoxbro 👍 
Indeed, upgrading Panel solves the issue.
However, as it is part of a bigger interface, I would like to keep panel 1.3.8 to not have side effects, do you have any idea if this is fixable without upgrading? If not, I'll upgrade the project to 1.4.3.

Also, is it possible to change the style of the accordion? I feel like 1.3.8's was more beautiful.

Anyways, thanks !

**Comment by hoxbro** [comment]
I don't have an idea of what fixed this issue. You can try looking at the PR tracker for `Accordion` or `Card`. 

If it is a CSS-related fix, you could try to see if you can redo it in Panel 1.3.8, with https://panel.holoviz.org/how_to/styling/apply_css.html.

I will close this issue, as it has already been fixed in the latest releases.
