### ISSUE TITLE
Running examples in cells on documentation website fails (seems there are some 404s)

### ISSUE THREAD

**Issue by matthalstead** [holoviz/panel#6882]
There appears to be an issue, at least with Safari and Chrome on OSX, that means loading the web runtime and running cells in the documentation is failing. I have attached screenshots of console from both. The first one is just the console error in safari, the second one is the full page and console error.

<img width="1726" alt="panel_website_issue_safari" src="https://github.com/holoviz/panel/assets/1395861/c1dadc61-307a-474a-9502-a3af05b6354e">
<img width="1725" alt="panel_website_issue_chrome" src="https://github.com/holoviz/panel/assets/1395861/b1fe0896-ab40-47c8-805d-841960bdad21">

**Comment by philippjfr** [comment]
This is very high priority and a blocker for the 1.4.4 release, the issue here is the Sphinx no longer seems to provide:

`DOCUMENTATION_OPTIONS.URL_ROOT`
