### ISSUE TITLE
Layout of app titles on homepage

### ISSUE THREAD

**Issue by Coderambling** [holoviz/panel#6905]
On the homepage the titles of the examples take 4 lines, like below.

Portfoli
o
Analyze
r

Untidy, and it pushes content down the page.

Could this be fixed, for example with some CSS or HTML?

Can the {grid-item-card} element be styled to achieve this? Maybe add 2.5 em like in the snippet below? Any guidance welcome.

https://github.com/holoviz/panel/blob/main/doc/index.md

:::{grid-item-card} Portfolio Analyzer :link: https://|gallery-endpoint|.holoviz-demo.anaconda.com/portfolio_analyzer :link-type: url

{grid-item-card} {octicon}rocket;2.5em;sd-mr-1 Getting Started :link: getting_started/index :link-type: doc

**Comment by philippjfr** [comment]
I don't see this under any screen configuration (I tried all simulated phone and tablet configuration in the Chrome dev console). So at best this a very niche problem. The fix should also be applied in `sphinx-design` which provides the grid layouts.
