### ISSUE TITLE
FileInput default to higher websocket_max_message_size?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#6923]
Currently, the default is 20 MBs, but this is pretty small for most use cases.

If it exceeds the 20 MBs, it silently disconnects the websocket (at least in notebook; when serving, it does show `2024-06-14 11:39:36,766 WebSocket connection closed: code=None, reason=None`). This leaves the user confused as to why nothing is happening (perhaps a separate issue).

Is there a good reason why the default is 20 MBs, or can we make it larger?

For reference:
https://discourse.holoviz.org/t/file-upload-is-uploading-the-file-but-the-value-is-always-none/7268/7

**Comment by philippjfr** [comment]
For larger files I'd recommend the new `FileDropper` widget.
