### ISSUE TITLE
Tabulator selectable is broken

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6946]
panel==1.4.4

I believe Tabulator js has changed how `selectable` works and Panel needs to adapt. It will change even for from 5.5 (current panel version) to 6.2 (latest js version).

```python
import panel as pn
import pandas as pd
import numpy as np
pn.extension("tabulator")

sel_df = pd.DataFrame(np.random.randn(3, 5), columns=list('ABCDE'))
select_table = pn.widgets.Tabulator(sel_df, selectable='toggle', selection=[0], disabled=True)
pn.Column(select_table, select_table.param.selection).servable()
```

I expect to be able to select one row and when I select another it change to that other one. Instead I select both. `checkbox-single` is not working either.

![image](https://github.com/holoviz/panel/assets/42288570/a9359565-1cc2-41be-91e3-c392f0accaf8)

## Workaround

Set `selectable=1` instead of `toggle`.

## Additional Context

- Tabulator 5.5 docs on row selection https://tabulator.info/docs/5.5/select
-

**Comment by maximlt** [comment]
I don't think this is a bug, this is the intended behavior with `toggle` if I remember correctly. @philippjfr 

![Monosnap screencast 2024-07-22 16-08-28](https://github.com/user-attachments/assets/cb362e1c-3f06-4855-8cb7-a5262da41f7d)

If that's the behavior that you're after, you could set `selectable=1` to have only 1 row always selected:

![Monosnap screencast 2024-07-22 16-09-58](https://github.com/user-attachments/assets/512ea567-a617-4266-b488-0d0808ed4293)

https://github.com/holoviz/panel/issues/3140 is a feature request about being able to configure with more precision the selection behavior and number of rows.

**Comment by philippjfr** [comment]
Yeah, little confused here.

> select one row and when I select another it change to that other one 

This is the default behavior with `selectable=True`. It doesn't limit the number however.

>checkbox-single is not working either.

It's poorly named and described I'd say. The proposal in #3140 raises many of the same points and correctly suggests that we should have distinct options to control the number of selectable items and how the selection works with `'toggle', 'checkbox' and 'default' as the options. Will close as duplicate.
