### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Mohammad-Amin-Heydari** [holoviz/panel#6952]
Hello 
i have problem that i couldn't change the size of the checkbox button in 
pn.widgets.Checkbox
could you write solution for this problem?
thank you

**Comment by ahuang11** [comment]
Hi! Have you had a chance to take a look at https://panel.holoviz.org/how_to/styling/apply_css.html yet? If so, can you share what you've tried?

**Comment by MarcSkovMadsen** [comment]
The way to do it is to inspect the HTML. There you will see the checkbox is the `input` tag and the text is inside that `span` tag.

Then you would change the size via a `stylesheet`.

![image](https://github.com/user-attachments/assets/a9f87187-c14f-406c-ae42-9b598b14b9b2)

```python
import panel as pn

pn.extension()

CSS = """
input {
    height: 40px;
    width: 40px;
}
span {
    font-size: 50px;
}
"""

pn.widgets.Checkbox(name="Checked?", stylesheets=[CSS]).servable()
```

**Comment by MarcSkovMadsen** [comment]
I will close this one. Feel free to reopen if you there is something specific we can improve.
