### ISSUE TITLE
Inconsistent Button/FileDownload Icon location

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#6972]
The icon for FileDownload is justified to the left, while the icon for Button is next to the words.

<img width="1338" alt="image" src="https://github.com/user-attachments/assets/923fa53e-d2c8-4e3f-9b56-4f15dcdd617f">

```python
import panel as pn
pn.extension()

download = pn.widgets.FileDownload(icon="cloud", file=" ", sizing_mode="stretch_width")
button = pn.widgets.Button(icon="cloud", name="Download", sizing_mode="stretch_width")
pn.Column(download, button).show()
```

**Comment by MarcSkovMadsen** [comment]
From what I can see, the problem is that the icon is placed outside the anchor `<a>`. It should probably be inside it.

![image](https://github.com/user-attachments/assets/097b1b83-8745-440f-9542-a62162aa9d3f)
