### ISSUE TITLE
Styler object has no attribute 'map'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6990]
See https://panel.holoviz.org/gallery/portfolio_analyzer.html

![image](https://github.com/user-attachments/assets/f0cd456d-3db2-4cfa-9a81-b5e8bce52d08)

**Comment by MarcSkovMadsen** [comment]
## Solution

If I upgrade locally to a more recent version (like 2.2.2) it works.

**Comment by MarcSkovMadsen** [comment]
How do we force micropip to resolve to a more recent version of Pandas @philippjfr ?

**Comment by philippjfr** [comment]
Probably just need to bump the pyodide version in `panel.io.convert` and the new pyodide distribution likely contains a more recent version.

**Comment by philippjfr** [comment]
Oh I see, the doc build is using that old version, unclear to me why that's the case.

**Comment by philippjfr** [comment]
Fixed: https://holoviz-dev.github.io/panel/gallery/portfolio_analyzer.html
