### ISSUE TITLE
Tabulator not handling SelectionEvent and CellClickEvent correctly when header filtering is applied.

### ISSUE THREAD

**Issue by Cyb3r-Monk** [holoviz/panel#6997]
#### ALL software version info
panel 1.4.4
bokeh 3.4.2
python 3.10

#### Description of expected behavior and the observed behavior

I think this is a core issue that affects other tabulator functionalities. When the table is filtered using the header filters, selection and click actions don't return the correct index, hence causing issues. 

#### Complete, minimal, self-contained example code that reproduces the issue

Apply the filter "use" on the "Message" column, click rows and check the `row` value. Interestingly, the `value` seems to be correct. 

```Python
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import panel as pn
pn.extension("tabulator")


timestamps = [datetime.now() - timedelta(minutes=5 * i) for i in range(10)]
messages = [
    "User logged in",
    "File uploaded",
    "Error: File not found",
    "User logged out",
    "Database connection established",
    "New user registration",
    "Password changed",
    "System update completed",
    "Email sent to user",
    "User password reset",
]

log_df = pd.DataFrame({"Timestamp": timestamps, "Message": messages})
# set random integers for the index
log_df.index = np.random.randint(0, 1000, size=len(log_df))

def click(event):
    print(f'Clicked cell in {event.column!r} column, row {event.row!r} with value {event.value!r}')
    


table = pn.widgets.Tabulator(log_df, disabled=True, header_filters=True)
table.on_click(click) 
table

```

#### Screenshots or screencasts of the bug in action
![image](https://github.com/user-attachments/assets/4a2861f8-9bf7-40b2-b9f5-5858b689383b)

**Comment by philippjfr** [comment]
The `Tabulator.selection` indices and event `row` values are currently always relative to the original dataset. On balance I think is more generally useful since the display output just represents a view of the data and on the backend the user will usually be interacting with the original data. Would be happy to consider other perspectives and clarifications needed in the docs.

**Comment by Cyb3r-Monk** [comment]
Isn't it strange that while the `row` returns the index from original dataset, but the `value` returns the correct value of the selected cell? If the `value` also returns the value from the original dataset and not from the displayed output, it would make sense. However, `row` and `value` doesn't match in this case. 

Would it be possible to return the index value of the selected cell and assign it to something like `Tabulator.selection_index` ? 

Apart from that, If I use the `Tabulator.add_filter` method, I believe I shouldn't experience the same issue, should I? This could be the alternative solution.

**Comment by philippjfr** [comment]
But they do match, no? The 6th row has the matching value, which corresponds with a zero indexed row index of 5.

**Comment by Cyb3r-Monk** [comment]
Yes, but the row that is selected on the display is not the 6th. You click on the 3rd row on the displayed (filtered) view and it says, "you clicked the 6th row". 

One of the main problems here is that if I want to register a callback function, my computations on the triggered callback will not be the computations of the row that I selected. Besides, if I try to use the `.selected_dataframe`, it may throw an error depending on which row I clicked.

![image](https://github.com/user-attachments/assets/6102a473-e345-484c-88e8-0979aa9e3d0a)

**Comment by philippjfr** [comment]
The idea is that you can use those row and column indexes with .iloc on the original dataframe, which afaik all works correctly.

**Comment by philippjfr** [comment]
But yes I do believe there is a bug in selected_dataframe that has been reported separately (on my phone right now so I can't check which issue).

**Comment by Cyb3r-Monk** [comment]
Yes, I've seen the `.selected_dataframe` bug report. I hope it gets released soon, I got stuck in the development :(

**Comment by maximlt** [comment]
This is the issue tracking the `selected_dataframe` issue https://github.com/holoviz/panel/issues/3670. I think Philipp has replied clearly about the value of `row` and how it can be used. However, I also sometimes get confused about the value of `row`, I'll open another issue to discuss how we could improve that.
