### ISSUE TITLE
Select widget does not show assigned value first time of asking

### ISSUE THREAD

**Issue by joshua-brumpton-uniper** [holoviz/panel#7007]
#### ALL software version info
python 3.12.1
panel 1.4.4

#### Description of expected behavior and the observed behavior

Not sure if this is a bug or a misunderstanding of the widget on my part.

When I instantiate a Select widget and give it a set of options and define it's value, I expect the widget to display that value to the user. Instead it is blank, despite the underlying widget value being set.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
from collections import OrderedDict
import param

select_widget = pn.widgets.Select(name='Select', options=[])

name_to_web_id = {"A": "1", "B": "2", "C": "3"}

select_widget.options = name_to_web_id
select_widget.value = 1

def selected_value_label(selected_value):
    return f"Selected Value: {selected_value}"

dynamic_label = pn.bind(selected_value_label, select_widget)

pn.WidgetBox(
    pn.Column(
        select_widget,
        dynamic_label,
        sizing_mode="stretch_width",
    ),
    sizing_mode="stretch_both",
).show()


```

#### Screenshots or screencasts of the bug in action
![image](https://github.com/user-attachments/assets/5b7ecd16-b428-4549-985f-db8e9c670b0b)

- [x] I may be interested in making a pull request to address this

**Comment by ahuang11** [comment]
I believe you used an int instead of a str; this seems to work.

```python
import panel as pn
from collections import OrderedDict
import param

select_widget = pn.widgets.Select(name='Select', options=[])

name_to_web_id = {"A": "1", "B": "2", "C": "3"}

select_widget.options = name_to_web_id
select_widget.value = "1"

def selected_value_label(selected_value):
    return f"Selected Value: {selected_value}"

dynamic_label = pn.bind(selected_value_label, select_widget)

pn.WidgetBox(
    pn.Column(
        select_widget,
        dynamic_label,
        sizing_mode="stretch_width",
    ),
    sizing_mode="stretch_both",
).show()

```

**Comment by joshua-brumpton-uniper** [comment]
Thanks, it was my fault!

**Comment by ahuang11** [comment]
No worries! Happy to have helped!
