### ISSUE TITLE
pyodide/pyscript html loading spinner stutters

### ISSUE THREAD

**Issue by samimia-swks** [holoviz/panel#7050]
When a panel app is converted to pyodide / pyscript with `panel convert`, a loading spinner is shown while pyodide loads, which can take 10s of seconds. The spinner freezes every second or so, which is not a big deal, but it is not great to look at. 
It would be good to make it smoother, or at least give the user the option to replace the spinner with a basic 'loading...' text modal. 

![image](https://github.com/user-attachments/assets/82d73cb6-4db9-4ca3-846d-b8438696fa06)

#### ALL software version info
panel 1.4.4
html opened with chrome on linux or edge on windows 11

**Comment by philippjfr** [comment]
Indeed, the default `pyodide` target is nice and simple since you can just share the resulting HTML but if you care about performance then you should use `pyodide-worker` instead. This is documented here: https://panel.holoviz.org/how_to/wasm/convert.html#formats

**Comment by samimia-swks** [comment]
I actually need a portable html file so I cannot use pyodide-worker. Also, the performance of 'pyodide' for what I am doing is great, the only problem is the spinner. I feel like if the pyodide target cannot handle rendering a spinner then there shouldn't be one. A simple 'loading...' text would do and would not over the impression of a bad UI.

**Comment by philippjfr** [comment]
That's fair.
