### ISSUE TITLE
Tabulator callbacks not firing when selectable='checkbox'

### ISSUE THREAD

**Issue by droumis** [holoviz/panel#7056]
#### ALL software version info

<details> <summary> Versions </summary>

```bash
Python              :  3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:35:20) [Clang 16.0.6 ]
Operating system    :  macOS-13.5.2-arm64-arm-64bit
Panel comms         :  default

holoviews           :  1.19.0a3.dev3+g732876b22

bokeh               :  3.4.1
colorcet            :  3.1.0
cudf                :  -
cupy                :  -
dask                :  2024.4.2
dask-expr           :  1.0.12
datashader          :  0.16.0
geoviews            :  -
hvplot              :  0.9.2
ibis-framework      :  -
IPython             :  8.22.2
ipywidgets-bokeh    :  -
jupyter-bokeh       :  4.0.4
jupyterlab          :  4.1.6
matplotlib          :  3.8.4
networkx            :  -
notebook            :  -
numba               :  0.59.1
numpy               :  1.26.4
pandas              :  2.2.2
panel               :  1.4.1
param               :  2.1.0
pillow              :  10.3.0
plotly              :  5.21.0
pyarrow             :  15.0.2
pyviz-comms         :  3.0.3
scikit-image        :  -
scipy               :  1.13.0
spatialpandas       :  -
streamz             :  -
tsdownsample        :  0.1.3
xarray              :  2024.3.0
```

</details>

#### Description of expected behavior and the observed behavior
Tabulator callbacks not firing when `selectable='checkbox'`

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import pandas as pd
import panel as pn
import numpy as np

pn.extension('tabulator')

df = pd.DataFrame(np.random.randn(5, 2), columns=['x', 'y'])

receiver = pn.pane.Str('Click Event Log:\n\n', width=400)
t = pn.widgets.Tabulator(df, widths=100, selectable='checkbox')
i = 0

def callback(e):
    print(e)
    global i
    receiver.object += f'Click Event #{i} {e.value}\n'
    i += 1

t.on_click(callback)
pn.Row(t, receiver).servable()
```

#### Screenshots or screencasts of the bug in action

https://github.com/user-attachments/assets/1e80b13e-52cd-4e5a-8aec-960fc8945fc1

- [ ] I may be interested in making a pull request to address this

**Comment by hoxbro** [comment]
A way to do what you want is to bind the function to `t.param.selection`.

**Comment by droumis** [comment]
yep, except that it gets cumbersome because that just returns integers instead of rows. You can get the selection from running t.selected_dataframe within the callback, but if you only want to update the particular row/cell that has changed, then you need to maintain the 'old' state and do a comparison. It would be much better if we could just get the old/new row/cell from `on_click` or `on_edit` with the checkbox

**Comment by droumis** [comment]
> A way to do what you want is to bind the function to `t.param.selection`.

yep, except that it gets cumbersome because that just returns integers instead of rows. You can get the selection from running t.selected_dataframe within the callback, but if you only want to update the particular row/cell that has changed, then you need to maintain the 'old' state and do a comparison. It would be much better if we could just get the old/new row/cell from `on_click` or `on_edit` with the checkbox

**Comment by droumis** [comment]
> This is intentional, the checkbox column is not considered a real column and the events do fire when clicking on other rows.

Personally, I didn't expect that to be the case because setting `selection='checkbox'` to me means that the checkbox will dictate if a row is selected and therefore trigger an event. I guess if it's not going to change then it's more a matter of updating docs.

**Comment by philippjfr** [comment]
I'd be fine with a `on_selected` event.
