### ISSUE TITLE
Improve collaboration experience in non-conda environments

### ISSUE THREAD

**Issue by a-recknagel** [holoviz/panel#706]
**Problem**

The current project setup is tailored to people using conda to build their environments, which isn't too unusual a requirement in scientific/academic python communities. But there are plenty of people out there (👋) who would like to contribute and are only familiar with `pip` and `virtualenv`, and low-scale wrappers like `poetry` or `flit`. It took me a bunch of fiddling to start contributing, and even more to run tests and build the docs. Also, the travis builders are kind of slow.

**Discussion Points and Proposed Solution**

- we should have a `CONTRIBUTING.md` that potential contributors can refer to to have a comprehensive list of instructions and guidelines on how to contribute
  - packaging, running tests, and building docs should be things that work reliably and simple
  - is there a template in the anaconda/pyviz space that should be used?
- the CI could be improved to use docker images that come pre-loaded with all dependencies instead booting up vms
- try out github actions as soon as it's enabled, with the run matrix on push/PR being `[[windows, linux, mac],[py2,py3.6,..other_py3s/pypy?],[conda,pip]]`
- `pip install -e .` should be supported over `python setup.py dev` for dev installs - or if noone is opposed, I'd love to have `poetry` instead and get rid of `setup.py/setup.cfg/MANIFEST.in` all together
  - I have no clue what conda will think of these changes (or what problem `dodo.py` solves), but my impression was that as long as it gets an sdist-like tarball it's happy, which both `pip` and `poetry` can do
- none of these changes should break the existing regression test suites within the `pyviz` toolchain

Pinging @ceball @jsignell and @philippjfr who I assume have authority and/or an opinion on the matter. If I forgot anyone, please add them.

**Comment by ceball** [comment]
You mention some tools you use, including pip, virtualenv, poetry, and flit. As far as I know (correct me if I'm wrong), those are all 'python' tools. So how do you propose we should deal with 'non-python' dependencies? E.g. taking examples from #797 maybe.

**Comment by a-recknagel** [comment]
You're right, they are all python-only. Everything non-python would need to have some kind of install instruction, in the README for runtime requirements and in CONTRIBUTING for dev/build requirements.

Using binaries from pypi is possible, but something I've never done. Honestly, it sounds horrible to me and like something that might cause more problems than it solves, but it might be a good idea at least for runtime requirements so that installing a panel wheel with pip will just work.

**Comment by ceball** [comment]
We definitely try to make user installation possible via pip. So if there's something simple to make the user installation clearer for non-conda users, that would be worth a PR to improve http://panel.pyviz.org/#installation.

As for development, I think you are overall proposing to:

1. _Write a CONTRIBUTING.md_. I see the trend is to have this file (and people expect to see it on github), but we already have a developer guide at http://panel.pyviz.org/developer_guide/index.html. What should we do about that? Maybe just make CONTRIBUTING.md point to the existing guide? (I don't like duplication, but maybe my suggestion is not the best way?)

2. _Extend the developer guide/contributing file with instructions for developing without conda_, as an alternative to using conda. That seems fine, although core developers (who use conda) might struggle to maintain such instructions. If the instructions are captured on CI (github action/travis/similar), maybe they'll have a better chance :)

Any of the specific changes/tools you suggested in your original post could be part of this work. You'd have to make panel work with them if not already working, and that would need to not interfere with also being able to use conda, and it would need to not introduce a large maintenance cost, etc.

**Comment by a-recknagel** [comment]
Alright, all of this sounds reasonable and fits my initial expectation.

I think a link in CONTRIBUTING.md to the existing dev guide is fine, there should only be one version. Alternatively, the dev guide could be generated based on a CONTRIBUTING.md, but I have no clue if that makes sense. I would only propose or push changes related to that myself if I have success with setting up a non-conda dev environment, which is what I'll focus on.

I didn't mention it in the opening post, but this might also be a good point in time to adopt some kind of code of conduct, which is another piece of information that will usually be linked or contained in a CONTRIBUTING.md.

This might take a while, so as a short outline this is what I'll do:
 - make `pip install -e .` work and deprecate the `python setup.py develop` option
 - explore options regarding non-python dependencies so that the README or CONTRIBUTING section on `pip install` isn't an unmaintainable nightmare
 - write a CI script that ensures the functionality given the [python_version * os] support-matrix (I don't know how hard the dependency on travis is, if possible I'd like to use github actions instead, I have more experience with it and there might be some additional gains)
 - try to make the dev install work with poetry - this would get rid of MANIFEST.in, setup.py, setup.cfg and move all the config info to pyproject.toml (confidence that this works out is low, it would probably need a serious restructuring of the project that would break every downstream tooling and would thus just not be worth it.. but I'll try, because it would imo make a much cleaner cut between source and artifacts, and simplify build/distribution)
 - not break or complicate the conda workflow, the full website build (travis does that, right?), or any  of the other pyviz projects that depend on panel

If any of these are a problem or imply that I'm unaware of something, I'm thankful for warnings.

**Comment by ceball** [comment]
1. Perhaps in the past `python setup.py develop` was required because pip didn't do something (e.g. build the models)? Or pip did something strange and/or changed behavior too much? I can't remember. Or it might be based on [bokeh's developer instructions](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#building-and-installing), which also use setup.py develop rather than pip (in general, if I find myself doing something different from bokeh, I always worry why...). In any case, http://panel.pyviz.org/developer_guide/index.html#building-and-installing says to do `python setup.py develop` or `python setup.py install`, both of which seem risky, even for conda users (`easy_install` might get involved for any missing dependencies...). If I'd installed the dependencies with conda, I'd expect to do `pip install -e . --no-deps` after.

2. Good luck :)

3. Probably a few people are curious to know how github actions turn out - they might be useful in various ways. So feel free to do that. Or any other service. We use travis and appveyor because they're what was around in the past. I have no idea if they've the best any more.

4. Good luck :)

5. Yes, travis does the website build.

**Comment by ceball** [comment]
See also #866

**Comment by jbednar** [comment]
For what it's worth, I only ever use `pip install -e .`; I never use `python setup.py develop` for developing Panel. So I know that works well already, as long as the dependencies are already installed (by conda in my case).

@ceball , didn't you investigate using pyproject.toml alone and find that it was not feasible? I don't recall the details.

**Comment by philippjfr** [comment]
pyproject.toml can't deal with non-Python dependencies of course so you'd have to install nodejs yourself.

**Comment by ceball** [comment]
> didn't you investigate using pyproject.toml alone and find that it was not feasible? I don't recall the details.

I found it was not feasible given other constraints, e.g. supporting conda (build). But in general, it depends what tool(s) you use. For instance, if you were to use flit instead of setuptools, I think you could have just pyproject.toml. But whether that makes sense depends what the goals are.

**Comment by jbednar** [comment]
Supporting building conda packages is definitely not optional.  Do you mean that using flit one could still get conda packages using pyproject.toml as the source?

**Comment by MarcSkovMadsen** [comment]
> 
> 
> For what it's worth, I only ever use `pip install -e .`; I never use `python setup.py develop` for developing Panel. So I know that works well already, as long as the dependencies are already installed (by conda in my case).
> 
> @ceball , didn't you investigate using pyproject.toml alone and find that it was not feasible? I don't recall the details.

Hi @jbednar . Should the `pip install -e ` then be the one and only description in the documentation? 

Right now I'm just confused. I can pick between the two recommendations in the documentation and then this one. But I don't really know the implications and what would work best in practice. Are the some use cases where one is better than the other and vice versa?

**Comment by philippjfr** [comment]
>Are the some use cases where one is better than the other and vice versa?

The main issue with using just pip is that it does not let you install ``nodejs`` which is required to compile custom models. This is essential if you want to avoid 30+ second install times. If you have somehow already satisfied those you can also use `pip install -e .[tests]`. If you also want to be able to build docs however you will also have to satisfy the `selenium` and `phantomjs` dependencies in some form.

**Comment by philippjfr** [comment]
We have now switched to a [pixi](https://prefix.dev/docs/prefix/overview) based setup. Overall it makes it really easy to get a development environment set up and thanks to the changes to pyproject.toml it's now also possible to get started with `pip` (as long as you have nodejs set up locally).
