### ISSUE TITLE
Many relative links are broken in Panel documentation site

### ISSUE THREAD

**Issue by dennisjlee** [holoviz/panel#7087]
#### ALL software version info
Mac OSX 14.5
Chrome 127

#### Description of expected behavior and the observed behavior

Many relative links inside the Panel documentation are broken - they are being interpreted with a `#` in front of the relative path.

E.g. on [this page](https://panel.holoviz.org/reference/layouts/Accordion.html), there is a sentence near the top:

```
For further layout and styling-related parameters see the [customization user guide](https://panel.holoviz.org/reference/layouts/Accordion.html#../../user_guide/Customization.html).
```

I'm not sure where the `#` is coming from - in the source code for this documentation, the links do not have `#`: https://github.com/holoviz/panel/blob/ad94551cfa5fc15c637d459748aeb8da340974e2/examples/reference/layouts/Accordion.ipynb?short_path=d69f44e#L31

#### Complete, minimal, self-contained example code that reproduces the issue

On the documentation site panel.holoviz.org

#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this

**Comment by MarcSkovMadsen** [comment]
I can confirm its also broken in current dev docs https://holoviz-dev.github.io/panel/reference/layouts/Accordion.html

**Comment by Coderambling** [comment]
# 7086

**Comment by Coderambling** [comment]
#6418

**Comment by MarcSkovMadsen** [comment]
All broken links can probably be found in the docs build logs.

This is an example https://github.com/holoviz/panel/actions/runs/10329645761/job/28597689026

![image](https://github.com/user-attachments/assets/418ca256-a8a6-4b4d-a1a2-71ab9de0ae24)

**Comment by dennisjlee** [comment]
@MarcSkovMadsen thanks for fixing!
