### ISSUE TITLE
Characters disappear when typing in the ChatAreaInput.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7096]
The below video shows a part of my ChatInterface app in deployed to production on kubernetes. You can see for example after ~2secs a character disappering. I.e. the text changes from `sometimes` to `someties`. Later `you` becomes `yo`.

https://github.com/user-attachments/assets/76863777-2f19-4c6f-8eb7-2f2f647e02ff

When I run the exact same code in my development environment (JupyterHub on kubernetes) I cannot reproduce the issue.

I cannot share my production code. But its similar to

```python
"""Settings for the MT Analytics Home App"""

import panel as pn

pn.chat.ChatMessage.show_reaction_icons = False

async def generate_response(contents, user, instance):
    for i in range(5):
        yield str(i)

chat_interface = pn.chat.ChatInterface(
    callback=generate_response,
    widgets=pn.chat.ChatAreaInput(
        placeholder="Enter some text and click Send",
        auto_grow=True,
        max_length=20000,
    ),
)
chat_interface.send(
    """I'm an assistant. Try asking me questions about Panel
""",
    user="assistant",
    respond=False,
)

template = pn.template.FastListTemplate(
    main=[chat_interface],
    main_max_width="1200px",
    main_layout=None,
)
template.servable()
```

I've had the problem for a long time over multiple releases of Panel. I'm currently on 1.4.5. I will try to find reproducible example or cause as its quite annoying for users.

My **hypothesis** is that somehow each character input triggers a round trip to the server and back updating the text I've just written. And that round trip could be slower than I type?

https://github.com/user-attachments/assets/bddddd4c-ca8a-4c2b-9130-61d2b1b5ca6a

**Comment by MarcSkovMadsen** [comment]
If my **hypothesis** is correct I should of course investigate why my the network communication of my deployed apps is so slow. But it might also be an architectural problem with the chat interface and all text like inputs that you send each change over the wire. It will not scale.

**Comment by philippjfr** [comment]
In theory at least #7093 might indeed fix this. Is there anything else special about your deployment, e.g. is `--num-threads` enabled?

**Comment by philippjfr** [comment]
@ahuang11 have you ever observed this happening?

**Comment by ahuang11** [comment]
Not in ChatInput, but I think I've seen related issues, e.g.

https://github.com/holoviz/panel/issues/6738

and one other I couldn't find. I think it's an issue across all text inputs that communicates between value / input.

**Comment by ahuang11** [comment]
Oh found it https://github.com/holoviz/panel/issues/6414

**Comment by philippjfr** [comment]
I can't reproduce any of these with or without the fix in #7093.

**Comment by philippjfr** [comment]
Can either of you?

**Comment by ahuang11** [comment]
Without the fix:

```python

import panel as pn

pn.extension(
    nthreads=0,
)

def dashboard_page():
    return pn.widgets.TextInput(name="Enter text", placeholder="Type here...")

ROUTES = {
    "Dashboard": dashboard_page,
}
pn.serve(ROUTES, port=8501, admin=True
)
```

https://github.com/user-attachments/assets/4e6a9da6-a2eb-43f6-b8a1-3fbba3aaf22b

**Comment by ahuang11** [comment]
Seems slightly better with fix, but still happens.

https://github.com/user-attachments/assets/c6e16c99-7a26-449c-b6e8-439d493f21ca

**Comment by philippjfr** [comment]
Yeah, the PR currently makes no difference in the threaded case. Will look at that next.

**Comment by MarcSkovMadsen** [comment]
How come @ahuang11 can reproduce while @philippjfr cannot?

**Comment by ahuang11** [comment]
> Yeah, the PR currently makes no difference in the threaded case. Will look at that next.

Seems like Philipp can now; maybe he wasn't typing enough random characters at once :)

**Comment by philippjfr** [comment]
Could you try again with my latest changes in #7093 ?

**Comment by ahuang11** [comment]
Seems better; I can't tell if it happens or not now.

https://github.com/user-attachments/assets/aae418ac-31ef-4ae9-ab71-9c297924d5bd

**Comment by philippjfr** [comment]
Could you put a `if msg: print(msg, curdoc_events)` on line 370 in `panel/reactive.py` and then try again and paste the output?

**Comment by philippjfr** [comment]
I cannot reproduce anymore, however hard I try.

**Comment by ahuang11** [comment]
Woops I was on the wrong environment; seems to work fine now!


```
{} {'value_input': 'a'}
{} {'value_input': 'ab'}
{} {'value_input': 'abdka'}
{} {'value_input': 'abdkasj'}
{} {'value_input': 'abdkasjh'}
{} {'value_input': 'abdkasjhk'}
{} {'value_input': 'abdkasjhklasdj'}
{} {'value_input': 'abdkasjhklasdjhk'}
{} {'value_input': 'abdkasjhklasdjhkdsa'}
{} {'value_input': 'abdkasjhklasdjhkdsajl'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhads'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskl'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhas'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskl'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskld'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjh'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsak'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsakl'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsaklsjh'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsaklsjhkds'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsaklsjhkdsjhd'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsaklsjhkdsjhdk'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsaklsjhkdsjhdkasj'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsaklsjhkdsjhdkasjkld'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsaklsjhkdsjhdkasjkldh'}
{} {'value_input': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsaklsjhkdsjhdkasjkldhkalsd'}
{} {'value': 'abdkasjhklasdjhkdsajljhadskldjhaskldjhdsaklsjhkdsjhdkasjkldhkalsd'}
```

**Comment by philippjfr** [comment]
Yep, that output is what I expected. Previously it was effectively applying older `model` updates.

**Comment by philippjfr** [comment]
Thank you both!

**Comment by MarcSkovMadsen** [comment]
> > Yeah, the PR currently makes no difference in the threaded case. Will look at that next.
> 
> Seems like Philipp can now; maybe he wasn't typing enough random characters at once :)

Philipp testing it out 😄 

![image](https://github.com/user-attachments/assets/4d8ccbbf-c92e-4ec3-8f6a-603fbc3a8e9a)
