### ISSUE TITLE
Restructure ChatMessage UI layout?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#7155]
I think the icons are all over the place and the margins are messed up.

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/26d46955-ed29-4bee-8316-c559c7dc3018">

I'm thinking of moving the chat reaction icons to the top next to the copy icon.
<img width="180" alt="image" src="https://github.com/user-attachments/assets/52e4ba00-bd6c-4623-b887-dbebcfd2951d">

Also, I'm planning to implement an edit message alongside https://github.com/holoviz/panel/pull/7148 so there'll also be a pencil icon.

Inspirations

<img width="749" alt="image" src="https://github.com/user-attachments/assets/6ea1eb20-b1f1-4342-91ca-0293e20897a7">

<img width="743" alt="image" src="https://github.com/user-attachments/assets/1bff9c3f-418f-4d15-a6ea-3c73afd45b12">

**Comment by MarcSkovMadsen** [comment]
Consider moving hhe icons to the bottom. That is where chatGPT and most other chat interfaces have them.

When they are at the top you have to scroll (a lot) after the response is given.

**Comment by ahuang11** [comment]
```python
import panel as pn

pn.extension()

chat_message = pn.chat.ChatMessage(
    "Just testing!",
    footer_objects=[pn.widgets.Button(name="Reply", button_type="primary")],
    reaction_icons={"favorite": "heart", "like": "thumb-up", "dislike": "thumb-down"},
)
chat_message.servable()
```

In progress:
<img width="851" alt="image" src="https://github.com/user-attachments/assets/4c084870-4b95-4ba6-b1db-11029fbb2cc7">
<img width="833" alt="image" src="https://github.com/user-attachments/assets/a82acb53-1965-4deb-a86c-39ef7c9cd226">

**Comment by ahuang11** [comment]
Not sure if I like timestamp on bottom or left more https://github.com/holoviz/panel/pull/7157

**Comment by ahuang11** [comment]
Completed in https://github.com/holoviz/panel/pull/7157
