### ISSUE TITLE
Better landing page for `panel serve *.ipynb`

### ISSUE THREAD

**Issue by jsignell** [holoviz/panel#716]
Just ran into this when working on juptyer-panel-proxy. The landing page looks just terrible. Clearly it's missing its css, also the bokeh logo is rather big. 

<img width="524" alt="Screen Shot 2019-10-18 at 5 55 38 PM" src="https://user-images.githubusercontent.com/4806877/67130929-db861580-f1d0-11e9-845d-d47107cd7e7c.png">

**Comment by philippjfr** [comment]
We now have a custom template in panel/_templates/index.html. We can tweak it as we go since for now it is very simple:

![Screen Shot 2020-01-20 at 2 18 35 AM](https://user-images.githubusercontent.com/1550771/72692277-35c5a800-3b2b-11ea-9381-071de40187e1.png)
