### ISSUE TITLE
Feature request: Include Tooltip in Input style widgets

### ISSUE THREAD

**Issue by ambrustorok** [holoviz/panel#7174]
When one is creating a form and wants to include a `pn.widgets.TooltipIcon`, they are required to manually set a label for that input for it to be properly aligned with the input.

Consider the code below. A set of inputs is created, where some of them have tooltips. I have noticed that the label is also part of the widget, and therefor aligning the tooltip to a widget with a label results in it being vertically misaligned when compared to the input itself.

Code for creating a `pn.widgets.TooltipIcon` and the current workaround:
```python
import panel as pn

pn.extension()

my_label = pn.widgets.StaticText(
    value="Input with a tooltip",
    align=('start', 'end'), 
    height_policy="min", 
    margin=(0, 0, 0, 10)
)
my_input = pn.widgets.FloatInput( 
    step=1e-2,
    start=0.0,
    end=1.0,
    value=0.3,
    sizing_mode='scale_width',
    height_policy="min",
    margin=(0, 0, 0, 10)
)
my_tooltip = pn.widgets.TooltipIcon(
    value="Very useful tooltip.", 
    align="center"
)

pn.WidgetBox(
    pn.widgets.FloatInput(name="First input",sizing_mode='scale_width'),
    pn.Column(my_label,pn.Row(my_input,my_tooltip)), 
    pn.Row(
        pn.widgets.TextInput(name="Some other input",sizing_mode='scale_width'),
        pn.widgets.TooltipIcon(
            value="Another tooltip.", 
            align="center"
        )
    ),
    width=200
)
```
![image](https://github.com/user-attachments/assets/6690818c-acf2-4fb3-8dad-53164fe1d62e)

My proposal would be to take a tooltip parameter in the initializer of these widgets where it could display a properly aligned tooltip icon.

```python
my_input = pn.widgets.FloatInput( 
    step=1e-2,
    start=0.0,
    end=1.0,
    value=0.3,
    tooltip="super useful tooltip"
)
```

**Comment by ahuang11** [comment]
I think it's already doable with description.

<img width="580" alt="image" src="https://github.com/user-attachments/assets/e70f543e-270d-472f-b26d-19348f2092a0">
```python
import panel as pn
pn.extension()

pn.widgets.FloatInput(description="Name", **name="Hello")**
```
