### ISSUE TITLE
"Debugging in VS Code" Documentation insufficient?

### ISSUE THREAD

**Issue by michaelweinold** [holoviz/panel#7292]
#### ALL software version info

```plaintext
panel==1.5.0
VS Code Version: 1.93.1 (Universal)
```    

#### Description of expected behavior and the observed behavior

When adding a VS Code debugging configuration as suggested in the documentation, I expect to see Panel site variables in the debugging pane (even without setting a breakpoint). Unfortunately, the debugging configurations don't work for me... the debugging pane remains empty (see screenshot below).

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn

def example(a):
    b = a + 3
    return b

pn.interact(example, a=2).servable()
```

Top configuration from the [VS Code documentation page](https://panel.holoviz.org/how_to/editor/vscode_configure.html#debugging), bottom configuration from the issue opened by @hoxbro: https://github.com/holoviz/panel/issues/2833

```json
{
    "name": "panel serve",
    "type": "debugpy",
    "request": "launch",
    "program": "-m",
    "args": [
        "panel",
        "serve",
        "${relativeFile}",
        "--index",
        "${fileBasenameNoExtension}",
        "--show"
    ],
    "console": "integratedTerminal",
    "justMyCode": true
},
{
    "name": "Python: Panel",
    "type": "python",
    "request": "launch",
    "module": "panel",
    "args": [
        "serve",
        "${file}",
    ],
}
```

#### Stack traceback and/or browser JavaScript console output

N/A

#### Screenshots or screencasts of the bug in action

<img width="1728" alt="Screenshot 2024-09-18 at 07 03 10" src="https://github.com/user-attachments/assets/b019ddaa-1e4f-4e16-a727-1363b5f7f853">

- [x] I may be interested in making a pull request to address this

**Comment by michaelweinold** [comment]
@MarcSkovMadsen - I believe you're the VS Code Panel super-user 😎

Is there some obvious mistake I am making here? I have selected the right Python interpreter - and the Panel application _is_ served - the debugging pane just remains empty.

**Comment by hoxbro** [comment]
You need to add a breakpoint to get the information. This is how the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) works.

Running a normal Python script is the same, though it will just exit at the end of the file.

**Comment by michaelweinold** [comment]
Ah - whoops 😬
