### ISSUE TITLE
Documentation issue for pn.pane.Image and others

### ISSUE THREAD

**Issue by jtheligand** [holoviz/panel#7337]
I noticed that the reference for pn.pane.Image, pn.pane.PNG, and pn.pane.JPG (and I suspect some of the other image related panes) says to use `style` to denote CSS style, when it's `styles` as the actual parameter keyword that should be used.

Sorry if this is not the best place to put this! I'm never sure where documentation errors should be left.

**Comment by hoxbro** [comment]
Thank you. This is the right place to report it.

**Comment by chryshumble** [comment]
I will like to open a pull request to resolve this, can someone point the file where this correction can be made to me please?

**Comment by hoxbro** [comment]
They are in this folder as Jupyter Notebook.  https://github.com/holoviz/panel/blob/main/examples/reference/panes/GIF.ipynb
