### ISSUE TITLE
DateSlider step parameter is not in ms

### ISSUE THREAD

**Issue by rgr-1** [holoviz/panel#7352]
#### ALL software version info
panel: 1.5.1 (and 1.5.0)
bokeh: 3.5.2 (and 3.6.0)

#### Description of expected behavior 
https://panel.holoviz.org/reference/widgets/DateSlider.html

- step (number): The selected step i the slider in milliseconds

#### Observed: 
step is in days. I.e. step=1 adjusts slider in 1 day increment. 

In addition: 
- on your page above I can make 1 hour increment by specifying step = 1/(24). Please see attached. This would be absolutely acceptable..
- however in my project it fails with bokeh (rightfully?) expecting integer for step parameter. 
``` bash
  File "~/miniconda3/envs/my/lib/python3.12/site-packages/bokeh/core/property/bases.py", line 363, in prepare_value
    raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
ValueError: failed to validate DateSlider(id='9e019eed-0b4d-4faa-bb5e-aee6fca643ba', ...).step: expected a value of type Integral, got 0.041666667 of type float
```

#### Screenshots or screencasts of the bug in action
![2024-10-02_23-04](https://github.com/user-attachments/assets/f934b415-bcbe-442c-a971-1a184b2b7457)

**Comment by hoxbro** [comment]
Bokeh changed it from milliseconds to days at some point. I have opened a PR to clarify this. 

It does not look like Bokeh has a `DatetimeSlider`.
