### ISSUE TITLE
Enable autoreloading a package installed for development

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7395]
I'm always developing a package like panel, panel-mermaid or internally. And this package is installed with `pip install -e .`. I'm almost always also developing some Panel app in a `script.py` or `examples/some_app.py` file outside the `src/name_of_package` folder.

The problem is that when serving the panel file, `panel serve script.py --dev --index script` and making changes to the package the script.py file does not autoreload. I have to restart the server which is quite cumbersome.

Please either watch the package installed for development, make it an option to watch the package installed for development or enable me to specify a file or a folder to watch too.

**Comment by philippjfr** [comment]
Fixed by https://github.com/holoviz/panel/pull/7399
