### ISSUE TITLE
Cannot upload accepted_filetypes pdf

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7407]
I'm on panel 1.5.2 using the FileDropper and try to make a working example for https://discourse.holoviz.org/t/problem-with-accessing-pdf-file-s-input-in-panel/8339.

![image](https://github.com/user-attachments/assets/72998338-44de-4191-bf7f-858a9d09b5d0)

```python
import io
import panel as pn
import base64
from PyPDF2 import PdfReader

pn.extension('filedropper')

def transform_pdfs(value):
    pages = {}
    for key, value in value:
        f=io.BytesIO(file_input.value)
        reader = PdfReader(f)
        page = reader.pages[0]
        pages[key]=page
        print(pages)

file_input = pn.widgets.FileDropper(accepted_filetypes=[".pdf"])

pn.Column(
    file_input, pn.bind(transform_pdfs, file_input)
).servable()
```

I've also tried `accepted_filetypes=["pdf"]` without success.

**Comment by MarcSkovMadsen** [comment]
I was a little bit sad to see that the `.value` parameter of the FileDropper is not the same as the `FileInput`. For its important to recognize that long term there will be a lot of different specialized `FileInput` widgets for different types of media - Like `FileInput`, `FileDropper`, `ImageInput`, `TabulatorInput`, `VideoInput`, `AudioInput` etc. Their value will all be one or more files. Those widgets should be a family of widgets with the same python api to make them easy to use. At least that is what Gradio has recognized is helping their users.

**Comment by pasuka** [comment]
Hi @MarcSkovMadsen, IMHO the workaround for your issue is easy. Just replace the
```file_input = pn.widgets.FileDropper(accepted_filetypes=[".pdf"])```
by
```file_input = pn.widgets.FileDropper(accepted_filetypes=["application/pdf"])```
And support for custom file types is still a problem.
