### ISSUE TITLE
"Getting Set Up" Developer Instructions Hang on Windows Using Conda

### ISSUE THREAD

**Issue by kleavor** [holoviz/panel#741]
An attempt to follow the instructions on the Panel documentation under the developer guide was unable to complete as written on Windows 10 Enterprise. To isolate the problem a fresh environment initialized with only `conda create -n paneldev python=3.7` was created. Conda version information is

```
      conda version : 4.7.12
conda-build version : 3.18.10
     python version : 3.7.3.final.0
```

#### Installed packages are
```
# Name                    Version                   Build  Channel
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
setuptools                41.6.0                   py37_1    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.33.6                   py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
```

#### Description of expected behavior and the observed behavior

After activating the `paneldev` environment the command `conda install -c pyviz pyctdev>0.5.0` was executed. However, the process was noted to hang for 10 minutes without any information provided by conda or a request for permission to install packages.

The expected behavior is that the pyctdev installation should complete through normal conda installation processes.

*Note*: The documentation, followed as-is, would install pyctdev in a user's base environment. It is unclear if this is intended behavior, but a later step indicates creation of a `panel_dev` environment.

#### Complete, minimal, self-contained example code that reproduces the issue

1. Open an anaconda prompt
1. 
```
conda create -n paneldev python=3.7
conda activate paneldev
conda install -c pyviz pyctdev>0.5.0
```

#### Stack traceback and/or browser JavaScript console output

N/A

#### Screenshots or screencasts of the bug in action

N/A

**Comment by mattpap** [comment]
@philippjfr, I suppose this is the same problem with have in CI?

**Comment by philippjfr** [comment]
Yes, that sounds very plausible. I'll see if I can track that down soon.

**Comment by philippjfr** [comment]
I just fixed the appveyor build so doesn't seem to be the same issue. @ceball Do you have any idea here?

**Comment by ceball** [comment]
I'm afraid I haven't been following issues until recently, so I'll have to catch up.

In the meantime, @kleavor please could you re-run your conda install command but with `--debug` or `--verbose` (I can't remember exactly which - we want to see where the conda install command is hanging) and report the output here?

**Comment by ceball** [comment]
Re-opening as the issue link in the commit appears to be mixed up.

**Comment by kleavor** [comment]
Apologies for not responding sooner. Travel back from PyData, etc.

I've been able to still repeat this behavior on *three* different Windows machines at this point, and I let it sit for ~1 hour before killing the process. I've attached a text file containing the Anaconda Prompt contents following execution of `conda install -c pyviz pyctdev>0.5.0`. For disclosure, any instance of "**" in a path is me sanitizing out my personal directory structure.

Attachment Here: [paneldev.txt](https://github.com/pyviz/panel/files/3827642/paneldev.txt)

It looks like it's waiting on user input, but I've never been prompted for anything. I could attempt to do the install with the -y flag, but the second attempt at running to check for consistency has actually destroyed my Miniconda install on my personal computer while trying to break out using Ctrl+C, so I'm going to need to reinstall that first. This is unfortunately also not the first time I've encountered this with Anaconda, and it actually completely removes the Anaconda prompt from anywhere Windows recognizes it. Still looking for a way to quickly undo that, but it's something we're unfortunately used to around the office...

---

Ok, so that took me long enough that I ran it on a different computer while writing this, and -y allowed it to complete successfully. I'll edit the log from that in momentarily.

**Comment by ceball** [comment]
Sorry for the delay in responding. I think you are probably redirecting the output of `conda install -c pyviz pyctdev` to the file `0.5.0`. I've made #834 to clarify the instructions. Would be great if you get chance to re-test the command with quotes:
```
conda install -c pyviz "pyctdev>0.5.0"
```
If it doesn't fix the problem, please re-open.

Thanks for reporting!
