### ISSUE TITLE
Setting `objects` on a layout mutates the elements within the new list

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#7414]
Panel 1.5 introduced a behavior change described in this snippet, by which setting `.objects` on a layout mutates the list, replacing the original Viewer instances with the output from their `__panel__` method. I think that the recommended API isn't to set `objects` but to use the `layout[:] = new_elements` annotation which still works as expected. @philippjfr is `layout.objects = new_elements`  a supported API? `git bisect` points to https://github.com/holoviz/panel/pull/5593.

```python
import panel as pn


class SomeView(pn.viewable.Viewer):

    def __panel__(self):
        return pn.pane.Markdown("boom")


my_list = [SomeView(name="a"), SomeView(name="b")]
col = pn.Column()
col.objects = my_list  # bad
# col[:] = my_list     # ok
# col.extend(my_list)  # ok

print(my_list)
# Panel 1.5
# [Markdown(str), Markdown(str)]
# Panel 1.4.5
# [SomeView(name='a'), SomeView(name='b')]
```

**Comment by philippjfr** [comment]
Setting `objects` like this is valid and indeed should not mutate.
