### ISSUE TITLE
Panel Notifications now show the last notification multiple times for each displayed notification, instead of provided notifications

### ISSUE THREAD

**Issue by jnareb** [holoviz/panel#7504]
#### ALL software version info

<details>
    <summary>Software Version Info</summary>

```plaintext
panel==1.5.4
Python 3.10.4
Windows 10 Home 22H2 (64-bit)

bokeh==3.6.0
Chrome 130.0.6723.117 (64-bit)
```
</details>

#### Description of expected behavior and the observed behavior

When sending multiple notifications within the duration time of previous notification, I expect to see all notifications, one below another, vanishing one after the other.

What I get with Panel 1.5.4 is seeing multiple copies of the last notification (type and the message).

This is a **regression**, because I remember not having this problem before updating Panel. I thing that Panel 1.5.3 did not have this issue.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn

pn.extension(
    notifications=True,
)
pn.state.notifications.position = 'top-center'


def onload_callback() -> None:
    pn.state.notifications.warning("Warning", duration=0)
    pn.state.notifications.info("Info", duration=0)


pn.state.onload(onload_callback)
pn.pane.Markdown("# Hello world").servable()
```

#### Screenshots or screencasts of the bug in action

![Screenshot of Panel app, with two notifications reading "Info"](https://github.com/user-attachments/assets/f05259e4-ae3f-4469-943b-790afea047a8)

I would expect to see warning notification with the "Warning" message above info notification with "Info" message, instead of seeing info notification with "Info" message twice.

- [x] I may be interested in making a pull request to address this

**Comment by hoxbro** [comment]
It looks like it happens somewhere between 1.3.8 and 1.4.0.
