### ISSUE TITLE
Panel Deployment Error at particular url.

### ISSUE THREAD

**Issue by sameerCoder** [holoviz/panel#782]
I have a Holoview plot as a panel object . I want to deploy this plot at my own server , 
So After executed in my jupyter notebook through my Terminal command i want to deploy into my server at particular url address. 
**I am getting Error as ERROR: -2**
The command i am using for deploying at my own server at particular url is below : 
```
(plotenv) username@username-Desktop:~$ sudo /home/username/anaconda3/envs/plotenv/bin/panel serve Deployment_steepness.ipynb --address https://172.16.XXXX.XXXX/portal/osf/swan --allow-websocket-origin=*
2019-11-14 10:34:25,783 Starting Bokeh server version 1.3.4 (running on Tornado 6.0.3)
ERROR: -2
```
Can i know why this Torando ERROR -2 is coming and how i can solve this issue so that i am able to deploy my plot into my own server , so that other users can come to my server location and can see my plot with dynamic data zooming features.

**Comment by jbednar** [comment]
As @bryevdv suggested on [Gitter](https://gitter.im/pyviz/pyviz?at=5dcd94bd5eb2e813db24362e), you can try setting the env var BOKEH_DEV=1 before you launch the `panel serve` command. That should give you more informative debugging information. 

Also note that `--allow-websocket-origin=*` is a bit dangerous given that shells expand the wildcard `*` to a list of files; it's safer to escape it with `--allow-websocket-origin='*'`.
