### ISSUE TITLE
After turning a Holoviews layout into a panel, linking behaviour is different.

### ISSUE THREAD

**Issue by olbermann** [holoviz/panel#798]
#### ALL software version info (Panel, bokeh, python, notebook, OS, browser, any other relevant packages)
panel==0.6.4
bokeh==1.4.0
notebook==6.0.2
holoviews==1.12.6
python 3.7.3 on ubuntu 18.04, firefox

#### Description of expected behavior and the observed behavior
I created a holoviews Layout from a list of hv.Heatmap objects, where the n-th object is an nxn heatmap. This displays nicely as a holoviews Layout. When turning this into a pn.panel, all heatmaps are only 1x1 (in another example, 2x2). I expected that not much would change visually, i.e. the n-th object should still be an nxn heatmap.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import holoviews as hv
hv.extension('bokeh')
import pandas as pd
import panel as pn

heatmaps = []
for k in range(1,9):
    df = pd.DataFrame.from_records([[i,j,i+j] for i in range(k) for j in range(k)])
    heatmaps.append(hv.HeatMap({'x': df[0], 'y':df[1], 'z': df[2]}, ['x', 'y'], 'z'))
layout=hv.Layout(heatmaps).cols(3)
layout
```
```
pn.panel(layout)
```
#### Screenshots or screencasts of the bug in action
![grafik](https://user-images.githubusercontent.com/25321913/69092052-e04a1d80-0a4b-11ea-8a94-f4f50e32fcfe.png)
![grafik](https://user-images.githubusercontent.com/25321913/69092082-f0fa9380-0a4b-11ea-952f-c35f17e354be.png)

**Comment by ahuang11** [comment]
Try `pn.panel(layout, linked_axes=False)`

Should reproduce the original hv.Layout. Also, I think linked_axes should be added to the FAQ.

**Comment by olbermann** [comment]
Thank you, this works! I changed the issue title, and I also think this should be mentioned in the docs.

**Comment by philippjfr** [comment]
Tbh, the main issue here is a HoloViews one. If it's going to link categorical axes it should also merge the categories.

**Comment by philippjfr** [comment]
This PR fixes merging of categorical axes in Panel: https://github.com/holoviz/panel/pull/968 and this one implements it for HoloViews https://github.com/holoviz/holoviews/pull/4194
