### ISSUE TITLE
Pipeline is not responsive in Jupyter when rendered first

### ISSUE THREAD

**Issue by sdc50** [holoviz/panel#800]
#### Versions
panel=0.7.0a17
bokeh=1.4.0
python=3.8.0
jupyter lab=1.2.3
chrome=78.0.3904.97
OS=macOS 10.14.6

#### Description of expected behavior and the observed behavior
When a Pipeline is the first thing rendered in a notebook then it is not responsive. In the following example clicking the `Next stage` button should advance the stage, but it doesn't.

![image](https://user-images.githubusercontent.com/6454472/69095560-3604d280-0a18-11ea-9e14-c8c7fae58303.png)

However, if something is rendered before the pipeline (or if the cell with the `p.layout` is rendered twice), then the pipeline works as expected.

![image](https://user-images.githubusercontent.com/6454472/69095425-f211cd80-0a17-11ea-9b14-8c437485ba67.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import param
pn.extension()

class Stage(param.Parameterized):
    ready = param.Boolean(precedence=-1)
    number = param.Number()
    next_stage = param.Action(lambda self: self.go_to_next())
    
    def go_to_next(self):
        self.number += 1
        self.ready = True
        self.param.next_stage.constant = True
        
    def panel(self):
        return pn.Column(self.param.number, self.param.next_stage)

p = pn.pipeline.Pipeline(ready_parameter='ready', auto_advance=True, debug=True)
p.add_stage('Stage 1', Stage(number=1))
p.add_stage('Stage 2', Stage())
p.add_stage('Stage 3', Stage())
p.add_stage('Stage 4', Stage())
p.add_stage('Stage 5', Stage(), auto_advance=False)

p.layout
```

**Comment by xavArtley** [comment]
I can't reproduce

**Comment by philippjfr** [comment]
Same here.

**Comment by sdc50** [comment]
I can't reproduce now either. I must have been in some crazy state that just needed a reset. 

On a semi-related note, what is the best way produce gif screen captures so that I can show these kind of issues in action?

**Comment by philippjfr** [comment]
>On a semi-related note, what is the best way produce gif screen captures so that I can show these kind of issues in action?

I use Monosnap, I also know some people use LICECap and I'm sure there are others.
