### ISSUE TITLE
The way that precedence is used in pipelines is confusing

### ISSUE THREAD

**Issue by sdc50** [holoviz/panel#801]
#### Versions

panel=0.7.0a17
bokeh=1.4.0
python=3.8.0
jupyter lab=1.2.3
chrome=78.0.3904.97
OS=macOS 10.14.6

#### Description of expected behavior and the observed behavior
There are several confusing behaviors associated with how `precedence` is used in pipelines. 

1. If the `ready_parameter` doesn't specify the `precedence` the `auto_advance` has unexpected behavior. In the following example when `Next stage` is clicked in the first stage then it automatically advances through all of the stages:

![image](https://user-images.githubusercontent.com/6454472/69096054-4ec1b800-0a19-11ea-8a9e-ded3545ee401.png)

I assume this is happening because the value for `ready` is being passed from stage to stage since the precedence isn't set to a negative value. So, once it's set to `True` it remains `True` through the whole pipeline. I would have assumed that the value of the `ready_parameter` would be blocked from being passed between stages.

2. Setting a negative `precedence` for parameters passed via `@param.output` may cause unwanted behavior. Consider the following:

![image](https://user-images.githubusercontent.com/6454472/69096676-7feeb800-0a1a-11ea-9da3-cbc6db890fd6.png)
![image](https://user-images.githubusercontent.com/6454472/69096702-8b41e380-0a1a-11ea-9924-de80029fb84b.png)
![image](https://user-images.githubusercontent.com/6454472/69096715-9268f180-0a1a-11ea-968d-b1e501351be6.png)
![image](https://user-images.githubusercontent.com/6454472/69096731-97c63c00-0a1a-11ea-9555-84adbdafd082.png)

The value for `n` is set in the `start` stage and is passed to `stage1` but the precedence is then set to negative, and so it then is not passed on to the subsequent stages.

I think there are use cases where I want precedence to be negative for some value (e.g. a database connection) but I want that value to be passed from stage to stage.

In general I think the data flow through a pipeline should be independent of precedence. 

#### Complete, minimal, self-contained example code that reproduces the issue
Example 1:
```
import panel as pn
import param
pn.extension()

class Stage(param.Parameterized):
    ready = param.Boolean()
    number = param.Number()
    next_stage = param.Action(lambda self: self.go_to_next())
    
    def go_to_next(self):
        self.number += 1
        self.ready = True
        self.param.next_stage.constant = True
        
    def panel(self):
        return pn.Column(self.param.number, self.param.next_stage)

p = pn.pipeline.Pipeline(ready_parameter='ready', auto_advance=True, debug=True)
p.add_stage('Stage 1', Stage(number=1))
p.add_stage('Stage 2', Stage())
p.add_stage('Stage 3', Stage())
p.add_stage('Stage 4', Stage())
p.add_stage('Stage 5', Stage(), auto_advance=False)

p.layout
```
Example 2:
```
class Start(param.Parameterized):
    n = param.Number(default=3)
    
    @param.output(n=param.Number)
    def next_stage(self):
        return self.n * 2
    
    def panel(self):
        return pn.panel(self)
    
def get_add_x_stage(_x):
    class Stage(param.Parameterized):
        x = param.Number(default=_x, precedence=-1)
        n = param.Number(precedence=1)
        
        def panel(self):
            return pn.panel(f'{self.n} + {self.x} = {self.n + self.x}')
    return Stage

start = Start()
stage1 = get_add_x_stage(1)()
stage2 = get_add_x_stage(2)()
stage3 = get_add_x_stage(3)()    

p = pn.pipeline.Pipeline(auto_advance=True)
p.add_stage('start', start)
p.add_stage('1', stage1)
p.add_stage('2', stage2)
p.add_stage('3', stage3)
p.layout
```

**Comment by philippjfr** [comment]
Agree with you on all fronts. The ready_parameter should definitely not be passed through and the other precedence changes seem sensible to. Time for 0.7.1.  I'll try to have a fix by tomorrow.
