### ISSUE TITLE
Getting started Example is not working for me

### ISSUE THREAD

**Issue by Lazloo** [holoviz/panel#802]
I was trying the  [getting started example](http://panel.pyviz.org/getting_started/index.html). The sliders appears but they show no effect on the image. What could be the reason?

**Comment by xavArtley** [comment]
Did you install `jupyter labextension install @pyviz/jupyterlab_pyviz`

**Comment by Lazloo** [comment]
Yes I did

**Comment by ceball** [comment]
Can you say more about what you are doing/using? E.g. what browser, how are you running panel (in jupyter lab?), and so on. Any error messages in the browser's developer tools console? And what versions of things are you using (including at least panel, jupyterlab_pyviz, bokeh, python, notebook/jupyter lab, operating system)?

**Comment by Lazloo** [comment]
I tried Firefox else as well as Chrome. There is, unfortunately, no error message:

![grafik](https://user-images.githubusercontent.com/10186284/69403926-2a592a80-0cfc-11ea-8624-d72472e217c1.png)

Is it normal that there is so much space between slider and image?

Here is the Jupiter notebook, where I tried to get it started: 
[get_started.zip](https://github.com/holoviz/panel/files/3878263/get_started.zip)

**Comment by Lazloo** [comment]
The following example works fine:

`
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import panel as pn
# %matplotlib inline

def mplplot(df, **kwargs):
    fig = df.plot().get_figure()
    #plt.close(fig)
    return fig

def sine(frequency=1.0, amplitude=1.0, n=200, view_fn=mplplot):
    xs = np.arange(n)/n*20.0
    ys = amplitude*np.sin(frequency*xs)
    df = pd.DataFrame(dict(y=ys), index=xs)
    return view_fn(df, frequency=frequency, amplitude=amplitude, n=n)


pn.extension()
pn.interact(sine)
`

**Comment by Lazloo** [comment]
I can also see that the function arguments are actually processed that the image is not updated

**Comment by philippjfr** [comment]
The difference is that if you do not close the figure the native matplotlib rendering will still kick in, but that is rendering the plot completely outside of panel (and also causes the whitespace issue).

**Comment by philippjfr** [comment]
This is almost certainly something to do with the user setup. Please join us on [discourse](https://discourse.holoviz.org/) if this continues to be a problem.
