### ISSUE TITLE
Interactive matplotlib

### ISSUE THREAD

**Issue by baserge** [holoviz/panel#807]
Is it possible to add support for interactive matplotlib plots? 

Though the project is new, I really like how it looks and feels. It is quite easy and quick to develop a nice looking dashboard you can share with colleagues. However, there is one question that puzzles me. Of course, there are all those nice plotting libraries that came recently and that are really great for the web. But, I think mpl is still the most complete and the most used library in the Python community. It has multiple advantages, especially when it comes to the customization and producing publication quality plots. In addition, we know that it is possible to use mpl in an interactive way. Finally, this is what works quite well in Jupyter (the webagg backend, as I understand). Unfortunately, there seems to be no dashboarding toolkit that allows to use mpl in the same way to create standalone web-apps. I was wondering if it is possible to add such a support to Panel or there is a fundamental problem that I overlook here. I believe having such a feature may help to strongly bias users, at least those who know mpl well, towards Panel.

**Comment by ceball** [comment]
As an aside: have you seen ipympl/[jupyter-matplotlib](https://github.com/matplotlib/jupyter-matplotlib/)? You can likely use that with voila, at least (although I haven't tried).

**Comment by nitrocalcite** [comment]
Is this closed with #1469 and the release of 0.10.0 or is there more work coming in this direction?

**Comment by MarcSkovMadsen** [comment]
I think an example demonstration that it is now possible to use would add value
