### ISSUE TITLE
Template support for parameters (not panels)

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#809]
## Intro

I'm trying to develop a reusable Template based on the [getbootstrap dashboard](https://getbootstrap.com/docs/4.3/examples/dashboard/). In that template I need to be able to insert parameters like "app_title". I then experience two pains

1) The api for inserting parameters is not there/ cumbersome.
2) The parameters get's wrapped into multiple Bokeh Divs. Which makes styling via Css cumbersome.

```python
template.add_panel("app_title", pn.Row(pn.pane.HTML("Company Name")))
````

```html
{{ embed(roots.app_title) }}
```

![image](https://user-images.githubusercontent.com/42288570/69489205-78913980-0e74-11ea-9769-92da65b9c287.png)

## Solution

Instead I would like to be able to insert parameters directly into my template something like

```python
template.add_parameter("app_title", "Company Name")
````

```html
{{ root.app_title }}
```
![image](https://user-images.githubusercontent.com/42288570/69489246-1258e680-0e75-11ea-9fae-9f3fa1dc0d19.png)

## Additional Context

If it was just one parameter I needed I could live with the pains above. But the next thing coming up could be reporting multiple numbers in a card and for that it would also be very handy to have an easier api to insert into the template, avoid the Bokeh Divs and use the power of jinja2 templating.

![image](https://user-images.githubusercontent.com/42288570/69489289-ad51c080-0e75-11ea-9ebd-4f4d513873eb.png)

And the perspective is not just one off use. But being able to use the power of jinja2 templates to be able do advanced layout for individual pages in a multipage app or for building reuseable Panes, Widgets or Panels would be great.

My preliminary code can be found here

https://github.com/MarcSkovMadsen/awesome-panel/blob/master/package/awesome_panel/express/templates/_bootstrap_dashboard.py

**Comment by philippjfr** [comment]
This seems like a simple addition, I'll assign to the 0.7.1 milestone.

**Comment by MarcSkovMadsen** [comment]
Thanks  @philippjfr .

Things to consider
- Which types can a parameter be? Only str or any python type that jinja2 can handle? I think the latter as I would like to be able to input floats, ints, lists and nested objects that jinja2 can loop over.
- Will a strings be escaped? Or can I input html codes as well as

```python
template.append_parameter("hello_world", "<p>Hello World</p>")
```

**Comment by philippjfr** [comment]
>Which types can a parameter be?

Anything type supported by Jinja2 templates will work.
