### ISSUE TITLE
Enable jinja2 templating to layout Panels, Panes and Widgets components (not app)

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#810]
## Introduction

I'm trying to develop a reusable Dashboard App Template based on the [getbootstrap dashboard]((https://getbootstrap.com/docs/4.3/examples/dashboard/).

In the app I have multiple pages. I can layout the app using a Template and thats very nice. But I cannot layout individual "pages" or "components" using jinja2 Templates.

And when when wrapping panes and widgets into panels everything is wrapped into multiple Divs making styling and combinations with for example font awesome cumbersome.

And I currently cannot embed panes and widgets into for example cards except in the one, main app template. 

I can embed into Column, Rows and Tabs in Panel though, but why not allow embedding into arbitrary jinja2 templates?

## Example

For example I would like to be able to make a "component" like the below where I embed the title, text and chart into a Reusable Card Template.

![image](https://user-images.githubusercontent.com/42288570/69489523-90b78780-0e79-11ea-9731-d710ff509c10.png)

## Solution

Extend the functionality to allow for multiple Template panels in one app that can be used to develop reusable components.

## Additional context

I am sometimes developing in Angular and maybe my thinking is influenced by that background. :-) But I would really like to use Python and Panel instead to build awesome analytical apps because I believe it would be so much faster and powerfull.

In Angular you build reusable components from a combination of typescript code, html layout and css styling. I'm thinking the same power here would be possible to add and make Panel, very, very usefull if the expectation would be to build an application from beautiful and reusable components.

I would not build facebook in it. But in the large engineering or trading organizations I have experienced what you need is the ability to quickly build internal analytics apps for a smaller number of highly skilled super users. And there Panel could be perfect with a few improvements added.

Thanks for the great work already done :+1:

**Comment by philippjfr** [comment]
I'd love this functionality and it has come up in the past so thanks for making such a detailed issue about it. So far I haven't figured out how much work this would be and what the API would be and what level of nesting we would want to allow, e.g. putting a bootstrap or materialize Card inside a Row/Column should ideally be possible. Your expertise from an Angular background would be very helpful here as I'm not too familiar with any JS frameworks.

Currently I've been working on a less general pattern where we have a few basic templates which allow adding Cards, accordions and other components in a bootstrap grid like pattern. In my prototype that looked something like this:

```python
template = MaterializeTemplate(title='Materialize App', logo='http://panel.pyviz.org/_static/logo_horizontal.png')

text = pn.widgets.TextInput(name='Enter Text')
button = pn.widgets.Button(name='Toast')
button.js_on_click(code="""  
  M.toast({html: text.value})
""", args={'text': text})

template.modal.append('This is some modal content')
modal_button = pn.widgets.Button(name='Open Modal')
modal_button.js_on_click(code=template.open_modal)

template.add_sidebar('slider', pn.widgets.FloatSlider(name='Some slider', start=0, end=1))
template.add_sidebar('text', text)
template.add_sidebar('button', button)
template.add_sidebar('modal_button', modal_button)

template.add_card('Curve', hv.Curve([1, 2, 3]).opts(min_height=300, responsive=True), width=4)
template.add_card('Area', hv.Area([1, 2, 3]).opts(min_height=300, responsive=True), width=4)
template.add_card('Bars', hv.Bars([1, 2, 3]).opts(min_height=300, responsive=True), width=4)

template.add_card('Scatter', hv.Scatter([1, 2, 3]).opts(min_height=300, responsive=True), width=6)

template.add_collapsible('#1', 'A', width=6)
template.add_collapsible('#2', 'B', active=True)
template.add_collapsible('#3', 'C')

template.show()
```

<img width="1200" alt="materialize (1)" src="https://user-images.githubusercontent.com/1550771/69498258-523ac080-0eab-11ea-9fe2-3ca6e49ddc87.png">

That obviously doesn't have the flexibility you are imagining so there's still more work to be done.

**Comment by MarcSkovMadsen** [comment]
Hi @philippjfr 

I can see we are thinking very much along the same lines :+1: My template api looks like

```python
import panel as pn
import views
import awesome_panel.express as pnx


def main() -> pn.Pane:
    page = views.PageView()
    app = pnx.templates.BootStrapDashboardTemplate(app_title="Company Name")
    app.sidebar.append(page.select)
    app.main.append(page.view)
    return app


if __name__ == "__main__" or __name__.startswith("bk_script"):
    main().servable()
```

and the app looks like 

![image](https://user-images.githubusercontent.com/42288570/69513088-ef970280-0f46-11ea-9df0-cb38dc7b9080.png)

But I would like it to look like

![image](https://user-images.githubusercontent.com/42288570/69513109-fcb3f180-0f46-11ea-8489-ef445a052cb8.png)

eventually

Se [source code](https://github.com/MarcSkovMadsen/awesome-panel/tree/master/gallery/bootstrap_dashboard)

I'm also working with Streamlit (I've the developer of https://awesome-streamlit.org/) and from my experience it's currently much easier to use Streamlit than Panel because

- They have a template that looks ok and works without any hazzles
- The API is simpler and more "logical". It needs less code to get something done.
- The documentation is easier to understand and use (its actually searchable!) 
- They have a very active [discuss](https://discuss.streamlit.io) site which is much better than Panels Gitter site in my opinion.

The downside to Streamlit is that it cannot (yet) do all the things Panel can.

I can see that Panel really has a lot of power allready. But there is a lack of an "express" api (ala plotly.express) with built in templates for getting started and a simple api for adding panels to a a sidebar and a main section.

So I'm currently experimenting with an express api. See [source](https://github.com/MarcSkovMadsen/awesome-panel/tree/master/package/awesome_panel/express)

My motivation is to end up with a powerfull and simple to use template for large engineering and trading groups in an Enterprise (I work a [Ørsted](https://orsted.com/)), who want's and needs to develop simple to large tools in Python primarely but with a lot of power.

**Comment by MarcSkovMadsen** [comment]
Hi @philippjfr 

Would you be willing to share the code behing MaterializeTemplate? I think I could learn a lot from it.

**Comment by MarcSkovMadsen** [comment]
Hi @philippjfr 

A few thoughts on your template api.

- I think the Card and Collabsible should be layouts just like Column, Row and Tab. You should not `add_card` or `add_collabsible`.
- I think that instead of `.add_xyz` you should think more in line of `.xyz.add` or `.xyz.append`. It is easier to remember and search using Intellisense in VS Code and similar. And this would be nice for any template to say

`template.top.append`
`template.sitebar.append`
`template.footer.append`
`template.my_custom_area.append`

etc.

**Comment by MarcSkovMadsen** [comment]
And could we have a HTML layout component to wrap panes ala

`html=pn.layouts.HTML(my_pane, pre="<p>", post="</p>")`

**Comment by philippjfr** [comment]
I've pushed my initial work to https://github.com/holoviz/panel/pull/813, it is very preliminary (I essentially just played around for a couple of hours).

**Comment by MarcSkovMadsen** [comment]
@philippjfr 

Here is an example of how the api for allowing templating could look.

- Enter HTML and Markdown as "text" input to Buttons and similar

```python
button = pn.widgets.Button("<i class="fas fa-home"></i>Home")
```

- Wrap panes and widgets into custom HTML

```python
button = pn.widgets.Button()
template = """
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    {button}
  </div>
</div>"""
button_in_card = pn.layout.Template(
    template=template,
    button=button,
)
```

**Comment by MarcSkovMadsen** [comment]
An example use case is https://github.com/holoviz/panel/issues/253

**Comment by MarcSkovMadsen** [comment]
Another example use case is the bootstrap card discussed here https://discourse.holoviz.org/t/awesome-panel-org-change-log/66/2?u=marc

**Comment by philippjfr** [comment]
With the new templates and `ReactiveHTML` having been merged I think this request has now been addressed fully.
