### ISSUE TITLE
Documentation: Update references to Audio pane instead of widget

### ISSUE THREAD

**Issue by NumesSanguis** [holoviz/panel#818]
When Googling "PyViz Panel audio" or on the website Reference Gallery -> Widgets -> Audio, you land on this page:  https://panel.pyviz.org/reference/widgets/Audio.html#gallery-audio

Here we have a nice warning: `Warning: The Audio widget is deprecated use the Audio pane instead.`
Problem however is that there is no link to this improved Audio pane.

Suggested improvements:

- Make `Audio pane` in the warning clickable and refer it to the Audio pane documentation page
- If that page doesn't exist yet, would be nice if it could be created :)
- Include a link to your example ipynb example: https://github.com/holoviz/panel/blob/9172586b2f9435790641780453f6cd3542b570c9/examples/reference/panes/Audio.ipynb (I had to find it by searching this GitHub repo for "audio")
- Feel free to include this audio example (or I can make a pull request once my sync problem is solved) on how to sync a plot VLine to the Audio pane's property `Audio.time` in a HoloViews plot: https://stackoverflow.com/questions/59063698/sync-holoviews-vline-with-pyviz-panel-audio-time

**Comment by philippjfr** [comment]
Mostly addressed, adding the example app would still be nice but can be done separately.
