### ISSUE TITLE
The Plotly widget does not support autosize in Column and is not responsive

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#822]
ALL software version info (Panel, bokeh, python, notebook, OS, browser, any other relevant packages)
Panel: 0.7
Bokeh: 1.3.4
Python: Python 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
notebook: 6.0.1
browser: Chrome

#### Description of expected behavior and the observed behavior

I would expect it to be easy to place full width, responsive Plotly plots inside a Column or Row in Panel.

This is not the case (for me at least :-))

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from typing import List, NamedTuple

import pandas as pd
import plotly.express as px

import panel as pn


class Dashboard:
    def __init__(self):
        chart_data = {
            "Day": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",],
            "Orders": [15539, 21345, 18483, 24003, 23489, 24092, 12034],
        }
        self.chart_data = pd.DataFrame(chart_data)

        table_data = [
            (1001, "Lorem", "ipsum", "dolor", "sit"),
            (1002, "amet", "consectetur", "adipiscing", "elit"),
            (1003, "Integer", "nec", "odio", "Praesent"),
            (1003, "libero", "Sed", "cursus", "ante"),
            (1004, "dapibus", "diam", "Sed", "nisi"),
            (1005, "Nulla", "quis", "sem", "at"),
            (1006, "nibh", "elementum", "imperdiet", "Duis"),
            (1007, "sagittis", "ipsum", "Praesent", "mauris"),
            (1008, "Fusce", "nec", "tellus", "sed"),
            (1009, "augue", "semper", "porta", "Mauris"),
            (1010, "massa", "Vestibulum", "lacinia", "arcu"),
            (1011, "eget", "nulla", "Class", "aptent"),
            (1012, "taciti", "sociosqu", "ad", "litora"),
            (1013, "torquent", "per", "conubia", "nostra"),
            (1014, "per", "inceptos", "himenaeos", "Curabitur"),
            (1015, "sodales", "ligula", "in", "libero"),
        ]
        self.table_data = pd.DataFrame(
            table_data, columns=["Header0", "Header1", "Header2", "Header3", "Header4"]
        ).set_index("Header0")

    def _chart(self):
        fig = px.line(self.chart_data, x="Day", y="Orders")
        fig.update_traces(mode="lines+markers", marker=dict(size=10), line=dict(width=4))
        fig.layout.paper_bgcolor = "rgba(0,0,0,0)"
        fig.layout.plot_bgcolor = "rgba(0,0,0,0)"
        fig.layout.autosize = True
        return pn.pane.Plotly(fig, width_policy="max", css_classes=["dashboard-chart"])

    def _table(self):
        return pn.widgets.DataFrame(self.table_data, sizing_mode="stretch_width")

    def view(self, name="Dashboard"):
        return pn.Column(
            pn.pane.Markdown("## Dashboard"),
            self._chart(),
            pn.pane.Markdown("## Section Title"),
            self._table(),
            sizing_mode="stretch_width",
            name=name,
        )


if __name__.startswith("bk"):
    Dashboard()._chart().servable("no_column")
    Dashboard().view().servable("column")
```

#### Screenshots or screencasts of the bug in action

As you can see below the Plotly plot uses the full width when not served in a Column. But if served in a Column it does not.

![image](https://user-images.githubusercontent.com/42288570/69854461-7de1f000-1289-11ea-8542-e4f505f8956c.png)

Further more if you try to run change the window size the Plotly plot does not respond

![image](https://user-images.githubusercontent.com/42288570/69854504-918d5680-1289-11ea-9de4-08e8db7955df.png)

**Comment by MarcSkovMadsen** [comment]
A workaround for now is to use the holoviews plotting library. For example replacing the `_chart` function in the code above with

```
def _chart(self):
        import holoviews.plotting.bokeh
        from bokeh.plotting import figure

        fig = figure(sizing_mode="stretch_width")
        fig.scatter([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 2, 1, 0, -1, -2, -3])
        fig.toolbar_location=None
        fig.toolbar.logo=None
        return fig
```

**Comment by MarcSkovMadsen** [comment]
To me it's important for the success of panel to be able to use your favourite plotting library with minimum friction. 

And currently my favourite plotting library is Plotly.

**Comment by MarcSkovMadsen** [comment]
Are real minimal example is shown here

```python
import panel as pn
import pandas as pd
import plotly.express as px

chart_data = {
    "Day": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",],
    "Orders": [15539, 21345, 18483, 24003, 23489, 24092, 12034],
}
fig = px.line(chart_data, x="Day", y="Orders")
fig.layout.autosize = True
app = pn.Column(fig, sizing_mode="stretch_width", background="gray")
app.servable()
```

I would expect the plotly plot to expand to the full width of the Column and be responsive. But it's not.

![image](https://user-images.githubusercontent.com/42288570/69856323-acfa6080-128d-11ea-80f7-19af55ad41f1.png)

**Comment by philippjfr** [comment]
I was not aware of the `autosize` option in Plotly so it's not totally surprising I missed this. Totally agree that this should work.

**Comment by MarcSkovMadsen** [comment]
There is a similar (but slightly worse) issue with Altair. See https://github.com/holoviz/panel/issues/947

**Comment by MarcSkovMadsen** [comment]
I can only partially confirm that this is solve in Panel v0.8 @philippjfr .

Its full width but not responsive. Full width is must have. But responsiveness would be nice to have.

![plotly_not_responsive](https://user-images.githubusercontent.com/42288570/73419791-bac97200-4320-11ea-9c0f-e02e42a2e372.gif)

**Comment by philippjfr** [comment]
@MarcSkovMadsen To get a responsive Plotly plot you need to set the plot to be responsive in the config (autosize is not sufficient). See the responsive example here: https://panel.holoviz.org/reference/panes/Plotly.html

**Comment by MarcSkovMadsen** [comment]
I can confirm that using the config option works.

-----
![plotly](https://user-images.githubusercontent.com/42288570/73608175-d7370a00-45bf-11ea-9037-31aad469e43d.gif)

```python
import panel as pn
import pandas as pd
import plotly.express as px

chart_data = {
    "Day": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",],
    "Orders": [15539, 21345, 18483, 24003, 23489, 24092, 12034],
}
fig = px.line(chart_data, x="Day", y="Orders")
fig.layout.autosize = True
plot = pn.pane.Plotly(fig, config={"responsive": True})
app = pn.Column(plot, sizing_mode="stretch_width", background="gray")
app.servable()
```

**Comment by MarcSkovMadsen** [comment]
When I adjusted the above code i thought there was a bit of friction because

- I both need to set autosize and responsive to get responsive behaviour. And I need to know this.
- I need to explicitly use `pn.pane.Plotly` instead of just providing the `fig` to a `Column`?

Would it be an idea that if `autosize=True` then `responsive` is set to True by default?

**Comment by philippjfr** [comment]
This is fully resolved now as far as I can tell. Please reopen if you can't confirm that.
