### ISSUE TITLE
Recommended way to send data from python to javascript

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#824]
Hello,

For the visualisation of temporal 3D data with the VTK pan I need to to send some data from python to javascript. To achieve this I use a sort of hack.
I construct an invisible StaticText widget and I use it to call a jscallback :
```python
comm_py_js = pn.widgets.StaticText(style={'visibility': 'hidden', 'width': 0, 'height': 0, 'overflow': 'hidden'}, margin=0)

comm_py_js.jscallback(args={'vtkpan': vtkpan}, value="""
    const binary_string = atob(cb_obj.text)
    const len = binary_string.length;
    const vtk_color_data = new Uint8Array(len);
    for (var i = 0; i < len; i++) {
        vtk_color_data[i] = binary_string.charCodeAt(i);
    }
    const renderer = vtkpan.renderer_el.getRenderer()
    const actors = renderer.getActors()
    const renderWindow = vtkpan.renderer_el.getRenderWindow()
    actors[0].getMapper().getColorMapColors().setData(vtk_color_data)
    actors[0].modified()
    renderWindow.render()
""")
```

Then I have a player which trigger a python callback and update the `comm_py_js` value:
```python
def update_visu3d(nb_file):
    pl.clear()
    scalars = get_scalars_file('vtk_creation/Results/VTK/MacroElem0_{:d}.vtk'.format(nb_file))
    #min_s, max_s = scalars.min(), scalars.max()
    min_s, max_s = 0, 6e-4
    color_bar = cbpan.object.below[0]
    color_bar.color_mapper.low = min_s
    color_bar.color_mapper.high = max_s
    color_bar.ticker = FixedTicker(ticks=np.linspace(min_s, max_s, 5))
    comm_py_js.value = base64encode(scalars_to_color(scalars, cmap, low=min_s, high=max_s))

def callback(*events):
    update_visu3d(nb_file=events[0].new)

player.param.watch(callback, ['value'], onlychanged=False)
```

It works well however it seems to me a little bit hacky and I'd like to know if there is a more recommended way to achieve this behavior

**Comment by philippjfr** [comment]
I've used a ColumnDataSource for this purpose, it gives you binary serialization and should therefore be considerably faster. Still feels a bit hacky but it's the best approach until Bokeh supports binary buffers on general properties. You can look at the Vega and Plotly models to see how that works.

**Comment by mattpap** [comment]
> (...) until Bokeh supports binary buffers on general properties.

I intend to implement this for 2.0.

**Comment by xavArtley** [comment]
@philippjfr To use a ColumnDataSource I have to modify the VTK model?
I was looking for a way to make it work without modifying panel code

**Comment by philippjfr** [comment]
>To use a ColumnDataSource I have to modify the VTK model?

Ah, I see. I'll have to think about it a bit. I'd always hoped bokeh could provide some model you could add just to sync state.

>Will it be really faster?

Yes, a lot, up to 10x.

**Comment by mattpap** [comment]
> I'd always hoped bokeh could provide some model you could add just to sync state.

That's "data" models and is also scheduled for 2.0.

**Comment by benbovy** [comment]
@xavArtley is there any place where I can look for a complete example of your hack above? I'd like to try using Panel to show/control an animation of an evolving topography (i.e., similar to the St Helens example linked with a player widget), but unfortunately my knowledge of vtk(js) is pretty limited.

**Comment by xavArtley** [comment]
You could look at here : https://github.com/pyvista/pyvista/issues/482
It's not an optimized version since the one using directly jscallbacks is in a bigger (closed source project)

**Comment by benbovy** [comment]
Many thanks for the pointer! I guess I'll need an optimized version, though:

![Feb-19-2020 09-24-54](https://user-images.githubusercontent.com/4160723/74815721-0b1d6980-52fa-11ea-8ad2-8235dd7648c4.gif)

(I used Panel 0.8.0, Jupyterlab 1.2.6, Firefox 72.0.2 for this example)

**Comment by philippjfr** [comment]
This really is and has been a bokeh issue. In the bokeh 3.0 release syncing array data will be fully supported so I'll close.
