### ISSUE TITLE
Dataframe widget not servable using bokeh

### ISSUE THREAD

**Issue by gdk-gagan** [holoviz/panel#827]
#### Software version
python 3.7
panel 0.7.0

#### Description of expected behavior and the observed behavior
I have two servable panels in my notebook, one rendering a dataframe widget. Rendering the app using panel serve notebook.ipynb raises the following error - 

2019-11-30 18:23:08,595 Starting Bokeh server with process id: 11003
<IPython.core.display.HTML object>
2019-11-30 18:23:18,486 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x7fcdf8643b00>: *module 'panel.widgets' has no attribute 'DataFrame'*
File "Anomaly_Detection_Facilities_Dashboard.ipynb", line 259, in <module>:
"\n", Traceback (most recent call last):
  File "/Users/gk87/anaconda3/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/Users/gk87/Work/Facilities/Code/Anomaly_Detection_Facilities_Dashboard.ipynb", line 259, in <module>
    "\n",
AttributeError: module 'panel.widgets' has no attribute 'DataFrame'

Appreciate any help!

**Comment by philippjfr** [comment]
Are you sure that the environment you're serving it from has latest panel installed. It looks like it's running from the anaconda base environment.

**Comment by gdk-gagan** [comment]
Hi Philipp, 

I am running from a separate environment with panel 0.7.0, throws the same error. Is there anything else I can try?

Also, I have been facing difficulty in linking params with my dataframe to support dynamic calculations as demoed in the Portfolio Optimization app in the Gallery. Would it possible to look at the code behind it? It would be really helpful!

Thanks in advance
Gagan

**Comment by philippjfr** [comment]
Not sure what to say, `panel.widgets.DataFrame` definitely exists in panel 0.7.0 so I can only assume you have environment issues.

Here's the code for the portfolio app: https://github.com/pyviz-topics/examples/blob/master/portfolio_optimizer/portfolio.py

I'm going to close this issue since Panel itself is not at fault here. Happy to help further though if needed.

**Comment by gdk-gagan** [comment]
Okay, I'll double-check the environment, and thank you so much for sharing the code link! I have been obsessed with this library for quite some time now and I love it!
