### ISSUE TITLE
When using Markdown the Div height is too large

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#829]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### Description of expected behavior and the observed behavior

When using the `pn.pane.Markdown` in Panel I would expect the containing Div height to be appropriate. I would expected there to be symmetry between the space above the text and below the text.

But that is not the case.

![image](https://user-images.githubusercontent.com/42288570/69910154-eacec480-1406-11ea-8c33-1e571b97aade.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn


def main():
    text = """\
Navigate to the **Dashboard Page** via the **Sidebar** to see the result.
As you can see there is some friction in using markdown in Panel!

But Panel could be so awesome with just a bit of friction removed :-)"""
    app = pn.Column(
        pn.pane.Markdown(text, sizing_mode="stretch_width"),
        sizing_mode="stretch_width",
        background="#d1ecf1",
    )
    app.servable()


main()
```

#### Additional Context

When looking at the HTML I see a lot of "new lines" and that the height is in the element.style. So my understanding is that the Bokeh Javascript code sets the height. Maybe it get's "confused" by all the "new lines"?

![image](https://user-images.githubusercontent.com/42288570/69910216-ad1e6b80-1407-11ea-8e39-208e33a6f04d.png)

**Comment by MarcSkovMadsen** [comment]
This example is even worse

![image](https://user-images.githubusercontent.com/42288570/69910254-72690300-1408-11ea-85ff-5678e9269dc8.png)

```python
import panel as pn


def main():
    text = """Navigate to the Dashboard Page via the Sidebar to see the result. As you can see there is some friction in using markdown in Panel! But Panel could be so awesome with just a bit of friction removed :-)"""
    app = pn.Column(
        pn.pane.Markdown(text, sizing_mode="stretch_width"),
        sizing_mode="stretch_width",
        background="#d1ecf1",
    )
    app.servable()


main()
```

But it's funny. If I resize the window then it looks like

![image](https://user-images.githubusercontent.com/42288570/69910265-86146980-1408-11ea-9548-da26d2b482ea.png)

**Comment by MarcSkovMadsen** [comment]
**Problem solved**. 

I removed the `sizing_mode="stretch_width"` inside the `pn.pane.Markdown`.

![image](https://user-images.githubusercontent.com/42288570/69910274-de4b6b80-1408-11ea-8346-7bf81c5c0795.png)

![image](https://user-images.githubusercontent.com/42288570/69910276-e5727980-1408-11ea-9040-81032d77b5e1.png)

```python
import panel as pn


def main():
    text = """Navigate to the Dashboard Page via the Sidebar to see the result. As you can see there is some friction in using markdown in Panel! But Panel could be so awesome with just a bit of friction removed :-)"""
    app = pn.Column(pn.pane.Markdown(text), sizing_mode="stretch_width", background="#d1ecf1",)
    app.servable()


main()
```

**Comment by devystack** [comment]
Thank you for your tips but
Is there any styling to set the height of div like style = "height: 320px" in html
