### ISSUE TITLE
Create Discuss Forum to foster community discussions and knowledge sharing on Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#831]
I'm a newcomer to the world of HoloViz but I've been trying extensively over the last three weeks to learn and get up to speed. I think the tools are some of the greatest out there in Python. But they are are undercommunicated and there is a lot of friction to get up to speed.

I am an experienced data, models and analytics developer in Python though. And I'm the developer of http://awesome-streamlit.org/ which was easy to develop in Streamlit.

One of the pains is the community discussions and knowledge sharing. It's on Gitter and it's difficult to search and a crowded place. In my experience something like a Discuss forum which distinct post that can be followed is really great at building a community and sharing+documentating knowledge.

So.... Please replace Gitter with a dedicated Discuss forum for Panel. See for example https://discuss.streamlit.io for inspiration.

If for some reason you decide that Discuss would be great but you would like to maintain only one site for all of PyViz/ HoloViews. Please set it up in a way so that it is very easy to stay in a Panel bubble in there if your primary interest is Panel. 

I can see I'm not the only guy out there thinking this :-)

![image](https://user-images.githubusercontent.com/42288570/69931166-807d5900-14c6-11ea-83ed-27249f0084ea.png)

**Comment by philippjfr** [comment]
So I've started setting up a discourse here: https://discourse.holoviz.org/

I haven't really done much except setting up the basic configuration. Let me know if you have any suggestions on how to structure it.

**Comment by MarcSkovMadsen** [comment]
It seems to work perfectly. An idea could be to add some links or dropdowns with links in the topbar to 

- The individual sites like https://panel.pyviz.org/
- The individual repos like https://github.com/holoviz/panel
- The individiual create issues like https://github.com/holoviz/panel/issues/new/choose

That would ease the navigation back and forth.

If you do please open the links in a new tab.

![image](https://user-images.githubusercontent.com/42288570/70765807-3022b880-1d5c-11ea-91d2-0ca6f42b09d8.png)

**Comment by philippjfr** [comment]
Thanks good suggestion @MarcSkovMadsen, I'll try to set that up. Further discussion can happen on the Discourse itself though.
