### ISSUE TITLE
Change search functionality at https://panel.pyviz.org/ to return Panel specific results

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#832]
I'm a new user of Panel trying to get up to speed. One of the friction points for me is the search functionality at https://panel.pyviz.org/. It returns results across the PyViz/ HoloViews ecosystem.

The search functionality does not filter to Panel specific results are ranks the Panel specific results higher. Because the rest of the ecosystem is so large most often do not find any Panel specific answers. 

I can take a look of the search results. But every time I have to spend time learning a bit of the rest of the ecosystem and maybe finding out that the answer is not applicable to Panel. That is overwhelming and time consuming.

An example is a simple search for `sizing_mode`.

![image](https://user-images.githubusercontent.com/42288570/69931970-8f193f80-14c9-11ea-9fc0-4b69bfc4fc5a.png)

**Comment by MarcSkovMadsen** [comment]
Another example is the **hidden reference guide**. I am actually looking for the reference guide. But I cannot find it via the Navigation.

But after some time I find out that the **reference guide** is just called **reference gallery**. I think that is confusing. I go to a reference gallery to get inspiration on how to use the technology and how to put it together. But normally I refer to a reference guide if I wan' to see which input parameters are available or how they should be used.

Please rename Reference Gallery to Reference Guide.

And by the way the Reference Gallery is great and contains a lot of the information I need. I just personally like the Sphinx/ Read the Docs format better.

![image](https://user-images.githubusercontent.com/42288570/69933194-24b6ce00-14ce-11ea-95e5-7bab1a4899a7.png)

Then we just need the markdown to be able to render code blocks as well :-) See https://github.com/holoviz/panel/issues/391

**Comment by ceball** [comment]
Technical aside (doesn't help the issue reporter): Probably only results from holoviews are being returned at the moment; see https://github.com/pyviz-dev/nbsite/issues/25.

**Comment by philippjfr** [comment]
Fixed in https://github.com/pyviz-dev/sphinx_holoviz_theme/pull/13

**Comment by MarcSkovMadsen** [comment]
I just tested. And I cannot confirm it works.

I've searched for `pane` and all that shows up are HoloViews answers.

![image](https://user-images.githubusercontent.com/42288570/73418483-edbd3700-431b-11ea-8075-b122f4bb3d8d.png)

**Comment by philippjfr** [comment]
The main website won't be rebuilt until I release.
