### ISSUE TITLE
Please add more structure, search, navigation and content to Panel Documentation

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#833]
I have been investing a lot of time to get up to speed with Panel over the last 3 weeks because it seems so powerfull. 

But there is a lot of friction to getting started. One friction point is the documentation.

For example lets assume i'm a newbie and want to do a simple thing like learning about how to add markdown to my app.

If I use the search functionality at panel.pyviz.org i get no help

![image](https://user-images.githubusercontent.com/42288570/69932486-a8bb8680-14cb-11ea-9747-007bc511fb78.png)

I've created a seperate feature request on improving the search functionality at https://github.com/holoviz/panel/issues/832.

Let me try to navigate via the menu then

![image](https://user-images.githubusercontent.com/42288570/69932598-fe902e80-14cb-11ea-8b2f-92e6cbfdb2b6.png)

Let me see. Where should I start? Let's start with the "Getting Started". No there is nothing on Markdown according to CTRL+f

![image](https://user-images.githubusercontent.com/42288570/69932644-2bdcdc80-14cc-11ea-8781-e74ba19df0da.png)

What about the user guide then? Wow there is a lot of possibilities? Where should I start then?

![image](https://user-images.githubusercontent.com/42288570/69932674-54fd6d00-14cc-11ea-93da-29828adaa599.png)

I was lucky :-) On the components page there is something

![image](https://user-images.githubusercontent.com/42288570/69932725-8413de80-14cc-11ea-8525-2c6080e63b09.png)

But the example is not focused on markdown and it does not tell me much. I would like something more structured like what is normal in documents structured by Sphinx and a Read the Docs theme.

![image](https://user-images.githubusercontent.com/42288570/69932853-043a4400-14cd-11ea-8591-75464b9d1337.png)

**Comment by MarcSkovMadsen** [comment]
Another example is the **hidden reference guide**. I am actually looking for the reference guide. But I cannot find it via the Navigation.

But after some time I find out that the **reference guide** is just called **reference gallery**. I think that is confusing. I go to a reference gallery to get inspiration on how to use the technology and how to put it together. But normally I refer to a reference guide if I wan' to see which input parameters are available or how they should be used.

Please rename Reference Gallery to Reference Guide.

And by the way the Reference Gallery is great and contains a lot of the information I need. I just personally like the Sphinx/ Read the Docs format better.

![image](https://user-images.githubusercontent.com/42288570/69933194-24b6ce00-14ce-11ea-95e5-7bab1a4899a7.png)

Then we just need the markdown to be able to render code blocks as well :-) See https://github.com/holoviz/panel/issues/391

**Comment by MarcSkovMadsen** [comment]
Please note I write these thinks because I think that Panel could be so great and I can so so much effort has already been put into it and the HoloViews/ Bokeh ecosystem that it leverages. And thanks for that.

But it's not easy to get started and build a nice looking multipage analytics app.

**Comment by ceball** [comment]
@MarcSkovMadsen I think one thing you're asking for is a 'reference manual' (or API documentation) - is that right? E.g. like this (from holoviews):

![api](https://user-images.githubusercontent.com/1929/69946685-0956bd80-14e4-11ea-92e8-984fc2eec7db.png)

(Ignoring that the generated reference manual for holoviews and other holoviz projects is currently a bit ugly/awkward in various ways.)

**Comment by MarcSkovMadsen** [comment]
Hi @ceball 

Yes and no.

Yes. In priciple the holoviews api documentation is the reference guide i'm looking for. 
No. I don't wan't something similar to the holoviews api documentation. It's difficult to understand the structure of and to read. 

I think the Reference Gallery is closer to what I need. I just think it should be called Reference Guide and then more systematic information on the function and it's arguments´+return arguments.

But Read the Docs format is so well know and easy to read. Why not use it?

**Comment by ceball** [comment]
Yes, thanks, your comments/issues are valuable - please keep making them. (For background, we're aware of many of these kinds of issues, but finding time to address them is always the problem. Some problems are historical and even newer projects like panel have inherited them because we've had to optimize for maintainer time, to allow a small number of people to maintain multiple projects.)

> And Read the Docs format is so well know and easy to read. Why not use it?

I can recall two issues we have with reference manual generation across holoviz projects:
1. We need to improve handling of Parameters in auto-generated documentation. We can't just "use readthedocs" (actually the tools underlying it) without some customization because the most important items to document (Parameters) would not appear.
2. We've never agreed to use one of the standard docstring formats (I think), e.g. numpy style. And we don't have consistent docstring style within/across projects.

**Comment by MarcSkovMadsen** [comment]
I've added a feature request for a style guide for Panel as this would help create better help in modern editors/ IDEs and when using Sphinx.

https://github.com/holoviz/panel/issues/1042

**Comment by philippjfr** [comment]
The website has received a significant overhaul since this was posted and a lot of the items here were addressed. I'll close this but I'd encourage filing requests for specific improvements that you'd still like to see.
