### ISSUE TITLE
A simple layout with a column and 2 markdown panes displays on top of each other

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#835]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### Description of expected behavior and the observed behavior

If I do a simple layout using columns and markdown with an image I would expect it to display nicely. 

It does not. Instead it displays on top of each other.

![image](https://user-images.githubusercontent.com/42288570/70017590-d106bc00-1583-11ea-9dfb-8d5b5f3f4399.png)

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn

ABOUT = """\
# About

[Panel](https://panel.pyviz.org/) is a powerfull framework for building awesome-analytics apps in [Python](https://www.python.org/).

The purpose of this app is to test that a **multi-page Dashboard Layout** similar to the [bootstrap dashboard template](https://getbootstrap.com/docs/4.3/examples/dashboard/) from [getboostrap.com](https://getbootstrap.com/) can be implemented in [Panel](https://panel.pyviz.org/).

[![GetBootstrap Dashboard Template](https://getbootstrap.com/docs/4.4/assets/img/examples/dashboard.png)](https://getbootstrap.com/docs/4.3/examples/dashboard/)
"""

INFO = """\
Navigate to the **Dashboard Page** via the **Sidebar** to see the result.
Or Navigate to the **Limitations Page** to learn of some of the limitations of Panel that
I've experienced."""

about = pn.pane.Markdown(ABOUT)
info = pn.pane.Markdown(INFO, background="#d1ecf1")
app = pn.Column(about, info)
app.servable()
```

### Additional Context

If I then resize or refresh the window. Then it displays correctly.

![issue_markdown_w_image_markdown](https://user-images.githubusercontent.com/42288570/70017452-6ce3f800-1583-11ea-98e7-f47204b77d33.gif)

I have a feeling the Bokeh javascript some how lays out the page before actual knowing that there is a image taking up some space. But that's the feeling.

**Comment by MarcSkovMadsen** [comment]
#### Workaround

For now a workaround is not to have images in the Markdown but display them as a seperate PNG pane.

![image](https://user-images.githubusercontent.com/42288570/70017988-fcd67180-1584-11ea-9342-52cf2f3b01d7.png)

```python
import panel as pn

ABOUT = """\
# About

[Panel](https://panel.pyviz.org/) is a powerfull framework for building awesome-analytics apps in [Python](https://www.python.org/).

The purpose of this app is to test that a **multi-page Dashboard Layout** similar to the [bootstrap dashboard template](https://getbootstrap.com/docs/4.3/examples/dashboard/) from [getboostrap.com](https://getbootstrap.com/) can be implemented in [Panel](https://panel.pyviz.org/).
"""

IMAGE = "https://getbootstrap.com/docs/4.4/assets/img/examples/dashboard.png"

INFO = """\
Navigate to the **Dashboard Page** via the **Sidebar** to see the result.
Or Navigate to the **Limitations Page** to learn of some of the limitations of Panel that
I've experienced."""

about = pn.layout.Row(pn.pane.Markdown(ABOUT))
image = pn.pane.PNG(IMAGE)
info = pn.layout.Row(pn.pane.Markdown(INFO, background="#d1ecf1"))
app = pn.Column(about, image, info)
app.servable()
```

But I don't think that is a valid long term solution for Panel. 

In order to use panel frictionless its important to be able to write more static parts of your page in markdown. This includes images and code and handling indentation nicely. 

- For code see issue https://github.com/holoviz/panel/issues/391
- For indentation see issue https://github.com/holoviz/panel/issues/828

**Comment by philippjfr** [comment]
I think the main issue here is the latency in loading the image, bokeh's layout engine tries to measure the size of the component before the image is fully loaded. We should probably file an issue with bokeh to ensure that measurements wait on external components to be fully loaded.

**Comment by MarcSkovMadsen** [comment]
I've now created an issue with Bokeh. See https://github.com/bokeh/bokeh/issues/10033

**Comment by MarcSkovMadsen** [comment]
This is still such a major problem. For example now when I am trying to refactor awesome-panel.org. I would like to add more images but still use Markdown. It looks like if I want each section to be a Markdown Pane such that I can be used to illustrate the react layout.

![image](https://user-images.githubusercontent.com/42288570/97540312-c20ed080-19c3-11eb-99e5-de9b1945c4ad.png)

@mattpap is writing that there is a js workaround to force redrawing when the images are loaded. I have not been able to figure it out.

**Comment by MarcSkovMadsen** [comment]
And like this when I use the Material layout

![image](https://user-images.githubusercontent.com/42288570/97540499-04381200-19c4-11eb-8d29-99323aa14fad.png)

It's one of those fundamental things that should just work.

**Comment by philippjfr** [comment]
Given that there is now a full proposal for a Bokeh layout engine rewrite [here](https://github.com/bokeh/bokeh/wiki/CSS-Layout-Design) which will happen independently of any work in Panel I will close this issue.
