### ISSUE TITLE
Downloadable DataFrame

### ISSUE THREAD

**Issue by apahl** [holoviz/panel#839]
Hi, thanks for this great dashboarding framework.  
I have used it now for the first time to offer a PCA / t-SNE Dimension reduction app for one of our in-house data sets and it works great.

In addition to the PCA / t-SNE plot the tool also displays the calculated table as a panel.widgets.DataFrame, which also looks very nice.

But of course, the first request by my users was to have a link or button to download the table for further processing.

I unsuccessfully tried to implement a download link, is there any possibility to achieve something like this?  
Like, saving the dataframe as a csv, then offer a download link to it?

The app is served with `panel serve app_*.py` .

Many thanks again.

Kind regards,  
Axel

**Comment by MarcSkovMadsen** [comment]
I would definately need this. 

What I really would like is to be able to expose url endpoints that when clicked starts the download of the file. That would enable the use to store the link an use it again and again in Python, Excel, etc. An alternative is just a button, that when clicks starts the download.

The files types I would expect to expose would be csv, xlsx, txt, parquet, json and maybe one day docx.

See also discussion on Gitter

![image](https://user-images.githubusercontent.com/42288570/70080026-21bef900-1606-11ea-82d8-b04981bdd97a.png)

**Comment by ahuang11** [comment]
Here's code to download Ace content:
```
ace = pn.pane.Ace()
btn = pn.widgets.Button(name='Download')
btn.jscallback(args={'ace':ace}, clicks="""
filename = 'ace_content.txt'
var element = document.createElement('a');
element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(ace.code));
element.setAttribute('download', filename);

element.style.display = 'none';
document.body.appendChild(element);

element.click();

document.body.removeChild(element);

""")
pn.Row(ace, btn)
```
credits to @xavArtley

**Comment by MarcSkovMadsen** [comment]
The functionality I would like could be inspired by `pn.pane.img`. When using that Panel/ Bokeh exposes an url to the image. I would like to be able to do exactly the same with a file.

I'm just brainstorming. Maybe I need an `FileEndpointWidget` that has an `on_request` method where I get the request context like full url including parameters in my event handler. And I can the code the file response including filename. 

Or maybe I just need to be able to annote a `file_response_function` with a `@down_load_file` annotation.

**Comment by apahl** [comment]
@MarcSkovMadsen : Your `data:file` example actually works for me. I did not know that was possible, thank you.  
For reference, this is the code I used (snippet from my project):

```Python
import base64
# When no file name is given, pandas returns the CSV as a string, nice.
csv = df_comp.to_csv(sep="\t", index=False)
b64 = base64.b64encode(csv.encode()).decode()  # some strings <-> bytes conversions necessary here
href = f'<a href="data:file/csv;base64,{b64}">Download Table</a> (right-click and save as <some_name>.txt)'
result_column[pos_dl_table] = pn.pane.HTML(href)
```

It might not be ideal but at least for now, the users can download their data, which usually consists of less than 200 lines in our case, so very much manageable by this solution.

Should I keep the issue open for further discussion?

KR Axel

**Comment by MarcSkovMadsen** [comment]
Yes. The problems with the workaround is that 

- it always transfers the and not on request. 
- it does not support more advanced use cases where the user gets an url to the file that they then can use in python, excel, tableau etc.

**Comment by MarcSkovMadsen** [comment]
And ... @apahl . In fact the `data:file` example was just something i imagined. Did not know that it's actually a supported thing :-)

But it is as you can read here https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

You can get some inspiration on the possibilities here https://base64.guru/converter/encode/file

And since i'm also using [Streamlit](https://streamlit.io/) and file download has not been a possibility there, I shared the solution in that community as well via the site awesome-streamlit.org that I run.

![file_download_workaround](https://user-images.githubusercontent.com/42288570/70142115-cdb12480-1698-11ea-9237-2254437a6fea.gif)

So in combination we've actually helped a lot of people today :-) Thanks.

**Comment by apahl** [comment]
Oh, I didn't realize that it is you who is hosting awesome-streamlit.org, very cool. I have evaluated streamlit, dash and panel for my project, and chose to go with panel.

KR Axel

**Comment by MarcSkovMadsen** [comment]
Hi @apahl . I'm on the same mission of evaluation.

Do you have any details of why you chose Panel over the others?

(I would like to make a small comparison document some day and any pros/ cons are appreciated).

**Comment by RRaphaell** [comment]
> @MarcSkovMadsen : Your `data:file` example actually works for me. I did not know that was possible, thank you. For reference, this is the code I used (snippet from my project):
> 
> ```python
> import base64
> # When no file name is given, pandas returns the CSV as a string, nice.
> csv = df_comp.to_csv(sep="\t", index=False)
> b64 = base64.b64encode(csv.encode()).decode()  # some strings <-> bytes conversions necessary here
> href = f'<a href="data:file/csv;base64,{b64}">Download Table</a> (right-click and save as &lt;some_name&gt;.txt)'
> result_column[pos_dl_table] = pn.pane.HTML(href)
> ```
> 
> It might not be ideal but at least for now, the users can download their data, which usually consists of less than 200 lines in our case, so very much manageable by this solution.
> 
> Should I keep the issue open for further discussion?
> 
> KR Axel

Hello
thanks for your solution.
do you know any way to click this link with a script? I want to download file with script and not click on this link

**Comment by MarcSkovMadsen** [comment]
Hi @RRaphaell 

Could you please ask the question on the discourse site. It will help build hhe community Knowledge base. Thanks.

**Comment by RRaphaell** [comment]
> Hi @RRaphaell
> 
> Could you please ask the question on the discourse site. It will help build the community knowledge base. Thanks.

sorry, can you link me to where should I post it?

**Comment by Hoxbro** [comment]
Here is the link: https://discourse.holoviz.org/
