### ISSUE TITLE
Update cached image in tabs

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#844]
Because it's the same filename, the tabs figure doesn't update.

```
import panel as pn
import matplotlib.pyplot as plt
pn.extension()

plt.plot([0, 1, 2])
plt.savefig('test.png')

tabs = pn.Tabs(pn.pane.PNG('test.png', embed=False))
tabs

plt.plot([0, 1, 3])
plt.savefig('test.png')

tabs.objects = [pn.pane.PNG('test.png', embed=False)]
```

![image](https://user-images.githubusercontent.com/15331990/70163866-c896aa00-1685-11ea-9d2b-140e2aeef220.png)

**Comment by philippjfr** [comment]
The problem here is that Panel/Bokeh have no way of knowing that the underlying file has changed so since the filename is exactly the same it doesn't actually trigger an event.

**Comment by ahuang11** [comment]
Is it possible to do a keyword `force_refresh`. Not too sure how it works behind-the-scenes though.

**Comment by philippjfr** [comment]
We could probably generate events manually somehow.

**Comment by philippjfr** [comment]
Honestly, I'll declare this out of scope, there's plenty of other options to do this, e.g. writing to a PIL image.
