### ISSUE TITLE
Cannot create full width Markdown pane without a lot of empty space

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#848]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### My Pain

In my app I would like to add Alert Boxes with Markdown content inspired by https://www.w3schools.com/bootstrap/bootstrap_alerts.asp.

I'm able to using a combination of `pn.pane.Markdown` and custom css. The only thing left is to make the `stretch_width` by default.

And it seems there I can't do that nicely. I believe there is a bug in the first example below where a lot of empty space is added.

#### Viz

![image](https://user-images.githubusercontent.com/42288570/70202811-19a4ad80-171b-11ea-8e96-bf3a9e2f625f.png)

#### Reproducing Code

```python
import panel as pn

ABOUT = """\
# About

[Panel](https://panel.pyviz.org/) is a powerfull framework for building **awesome analytics apps** in [Python](https://www.python.org/).

The purpose of this app is to test that a **multi-page Dashboard Layout** similar to the [bootstrap dashboard template](https://getbootstrap.com/docs/4.3/examples/dashboard/) from [getboostrap.com](https://getbootstrap.com/) can be implemented in [Panel](https://panel.pyviz.org/).
"""


about_sizing_mode_stretch_width = pn.pane.Markdown(
    ABOUT, sizing_mode="stretch_width", background="lightblue"
)
about = pn.pane.Markdown(ABOUT, background="lightgreen")
about_width_policy_max = pn.pane.Markdown(ABOUT, width_policy="max", background="burlywood")
app = pn.Column(
    about_sizing_mode_stretch_width,
    about,
    about_width_policy_max,
    background="lightgray",
    sizing_mode="stretch_width",
)
app.servable()
```

**Comment by MarcSkovMadsen** [comment]
This bug is a hazzle all the time when I try to add markdown with sizing_mode="stretch_width".

And I need this functionality to make nice, responsive Bootstrap inspired Alerts and Cards with Markdown content.

**Comment by philippjfr** [comment]
This seem to work okay if you set `sizing_mode='stretch_both'` on the containing column.

**Comment by MarcSkovMadsen** [comment]
Hmm :-) @philippjfr . I would not say it works ok. It creates other problems. Like the empty areas marked with a red line below and then the responsive behaviour in the video below.

![image](https://user-images.githubusercontent.com/42288570/71359409-9e515180-258c-11ea-900c-08ab69859f70.png)

```python
import panel as pn

ABOUT = """\
# About

[Panel](https://panel.pyviz.org/) is a powerfull framework for building **awesome analytics apps** in [Python](https://www.python.org/).

The purpose of this app is to test that a **multi-page Dashboard Layout** similar to the [bootstrap dashboard template](https://getbootstrap.com/docs/4.3/examples/dashboard/) from [getboostrap.com](https://getbootstrap.com/) can be implemented in [Panel](https://panel.pyviz.org/).
"""
about_sizing_mode_stretch_width = pn.pane.Markdown(
    ABOUT, sizing_mode="stretch_width", background="lightblue"
)
about = pn.pane.Markdown(ABOUT, background="lightgreen")
about_width_policy_max = pn.pane.Markdown(ABOUT, width_policy="max", background="burlywood")
app = pn.Column(
    about_sizing_mode_stretch_width,
    about,
    about_width_policy_max,
    background="lightgray",
    sizing_mode="stretch_both",
)
app.servable()
```

![markdown-problems](https://user-images.githubusercontent.com/42288570/71359622-5f6fcb80-258d-11ea-8e5a-874c40dee0db.gif)

**Comment by MarcSkovMadsen** [comment]
**Is it only me who wants to use Markdown in Panel with text, images and code? **

For me Markdown is time consuming to use because I have to spend time on investigating the problem and finding mitigating actions. When Markdown works out of the box it's so easy to use and get nice looking documents and apps.

I would think that Markdown is one of the first touch points of a *newbie* in Panel. And if it does not work you risk loosing your users.

But maybe most use cases for Panel are like the ones you have in your gallery which are focused on plots with widgets, minimal text, images and code and a minimum of styling. I can just see in the Streamlit community it's the opposite. Their users start with some text, images and code and then start adding plots and interactivity.

I also have these issues regarding Markdown.

https://github.com/holoviz/panel/issues/863
https://github.com/holoviz/panel/issues/835

**Is it a problem that should be raised for Bokeh instead?**

**Comment by philippjfr** [comment]
Turns out this is an issue in Panel itself, specifically this line is at fault:

https://github.com/holoviz/panel/blob/master/panel/pane/markup.py#L49

Specifically `height: 100%` is at fault. I'll see if there's a good reason for that and if not I'll likely revert that. This was originally added to get GridSpecs to work well but I'll have to see if it's really needed now. I've pushed a fix here:

https://github.com/holoviz/panel/compare/div_pane_height?expand=1

**Comment by MarcSkovMadsen** [comment]
@philippjfr . I tried installing the `div_pane_height` branch. But the example first posted still displays with a lot of empty space.

![image](https://user-images.githubusercontent.com/42288570/71361926-c2189580-2594-11ea-87a0-39ccb95bc5c1.png)

**Comment by philippjfr** [comment]
Going to have to assume something is wrong with your environment and it's using the old version of panel. Looks like this for me:

![Screen Shot 2019-12-23 at 3 01 13 PM](https://user-images.githubusercontent.com/1550771/71362041-29364a00-2595-11ea-9a7d-f1d7d612c24b.png)

**Comment by MarcSkovMadsen** [comment]
Ok. I will trust you and look forward to the 0.71 release. Thanks so much. :+1:

**Comment by MarcSkovMadsen** [comment]
I can confirm that in the latest release candidate for v0.8.0 it works.

----

The  code

```python
import panel as pn

ABOUT = """\
# About

[Panel](https://panel.pyviz.org/) is a powerfull framework for building **awesome analytics apps** in [Python](https://www.python.org/).

The purpose of this app is to test that a **multi-page Dashboard Layout** similar to the [bootstrap dashboard template](https://getbootstrap.com/docs/4.3/examples/dashboard/) from [getboostrap.com](https://getbootstrap.com/) can be implemented in [Panel](https://panel.pyviz.org/).
"""


about_sizing_mode_stretch_width = pn.pane.Markdown(
    ABOUT, sizing_mode="stretch_width", background="lightblue"
)
about = pn.pane.Markdown(ABOUT, background="lightgreen")
about_width_policy_max = pn.pane.Markdown(ABOUT, width_policy="max", background="burlywood")
app = pn.Column(
    about_sizing_mode_stretch_width,
    about,
    about_width_policy_max,
    background="lightgray",
    sizing_mode="stretch_width",
)
app.servable()
```

produces

![image](https://user-images.githubusercontent.com/42288570/73419543-d3855800-431f-11ea-83b8-7495c62bf17c.png)

It's so, so nice. It's makes it much easier to layout your apps without using hacks. Thanks.
