### ISSUE TITLE
Improve hot reload speed and process to enable fast development-test cycle

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#849]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### My Pain

When developing apps in Panel if often wan't to see how the change looks. It's possible to do by using the `--dev` flag but

- The restart of the Panel/ Bokeh server is very slow compared to the alternative technologies of Streamlit and Angular that I'm used to.
- The browser window does not automatically reload. I have to wait for the bokeh server to reload and then I can click refresh. In Streamlit and Angular I do not have to do this. I don't have to do this when I work with Sphinx either.

![hot_reload_process_slow](https://user-images.githubusercontent.com/42288570/70203790-68a01200-171e-11ea-9d20-400bd9fed99f.gif)

(Note I have to run panel server as a *python module* in order for reload to work on windows).

#### Solutions

- Improve restart time for Panel/ Bokeh server
- Enable automatic reload of the browser.

I believe enabling automatic reload of the browser alone would be very, very valuable if its difficult to improve the restart time for the Panel/ Bokeh server.

**Comment by jbednar** [comment]
If you add `--show`, a new tab will open whenever the file changes, so that you can see the new version, but then you get a browser window that eventually clogs up with lots of tabs.  In any case I believe this is a Bokeh rather than a Panel issue.

**Comment by MarcSkovMadsen** [comment]
Thanks @jbednar . I've added a feature request to bokeh here https://github.com/bokeh/bokeh/issues/9501
