### ISSUE TITLE
Behavior different between Tornado 6 and 5

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#860]
Hello,

today we had hard time to find a bug with the progress bar.
A coworker ask me some help to implement a progress bar,
Here is a minimal example to illustrate:
```python
import time
import panel as pn

pb = pn.widgets.Progress(value=0)
btn = pn.widgets.Button(name='start')
def work(*events):
    pb.value=0
    for i in range(5):
        time.sleep(1)
        pb.value = int(100*(i+1)/5)
btn.on_click(work)
pn.Row(pb, btn).show()
```

everything worked fine on my computer
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/18531147/70536201-9510bf80-1b5e-11ea-9612-59d97d06a4db.gif)

however on my coworker computer the behavior was :
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/18531147/70536398-eae56780-1b5e-11ea-8d15-eab2f448d47f.gif)

It took me a while to find the difference:
I was using tornado=5.1.1 but he was using tornado=6.0.3
However he uses conda but `conda install panel` does not restrict the tornado version
https://github.com/holoviz/panel/blob/0fdc326bf30769e6b9d95ac41257913687c22f70/environment.yml#L6

The issue seems fixed with https://github.com/holoviz/panel/pull/857

**Comment by philippjfr** [comment]
The environment.yml was used for testing early on but isn't actually used for anything now so I'll probably remove it.

**Comment by philippjfr** [comment]
Interesting that upgrading tornado changed the behavior, I did think something had changed and was very confused that I had to implement #857 at all.

**Comment by xavArtley** [comment]
I let the issue open until next realease for the record because it was really hard to find the bug and can help other people

**Comment by philippjfr** [comment]
Going to close now because this is fixed and release is close.

**Comment by MarcSkovMadsen** [comment]
I can confirm that after upgrading to Panel 0.8.0 I can use Tornado 6.0.3 with awesome-panel.org.
