### ISSUE TITLE
Display parameter docstrings

### ISSUE THREAD

**Issue by ceball** [holoviz/panel#862]
I'm not sure how best to display the info (and we've certainly debated that before in other toolkits 😁), but I would love to see parameter docstrings displayed somehow.

**Comment by jbednar** [comment]
I was just apologizing to people at a Panel tutorial on Saturday that it hasn't been implemented yet.  It totally should be implemented, whether it's as traditional hover on the parameter name or via a separate icon  ⓘ.

**Comment by philippjfr** [comment]
Once bokeh 3.0 is out we can include the docstrings in tooltips, so scheduling this issue for 1.0.

**Comment by philippjfr** [comment]
Closing in favor of https://github.com/holoviz/panel/issues/3441 which is a more specific request.
