### ISSUE TITLE
Markdown and HTML panes do not react the same to sizing_mode="stretch_width".

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#863]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### Problem

I would like to be able to use the Markdown pane in Panel. My end goal is to be able to use Markdown full width and responsive for ease of use. But I cannot.

One problem is this bug https://github.com/holoviz/panel/issues/848

Another bug (this is one) is just a source of confusion.

The Markdown and HTML panes do not reach the same to `sizing_mode="stretch_width"`

![image](https://user-images.githubusercontent.com/42288570/70593110-23775680-1bdc-11ea-9fee-1febb69c3fe2.png)

```python
import panel as pn
import markdown


TEXT = """# Awesome Panel ![Awesome Badge](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)

Panel is announced as **a high-level app and dashboarding solution for Python**. I think the terms **powerfull** and **full of features** should be added to that.

The purpose of the Awesome Panel Project is to share knowledge on how Awesome Panel is and can become."""

app_markdown = pn.Column(
    pn.pane.Markdown(TEXT, background="yellow"), sizing_mode="stretch_width", background="blue"
)

app_markdown.servable()

app_html = pn.Column(
    pn.pane.HTML(TEXT, background="yellow"), sizing_mode="stretch_width", background="blue",
)

app_html.servable()

app_markdown_html = pn.Column(
    pn.pane.HTML(markdown.markdown(TEXT), background="yellow"),
    sizing_mode="stretch_width",
    background="blue",
)

app_markdown_html.servable()
```

**Comment by MarcSkovMadsen** [comment]
And for the motivation. Why do I need to have full width, responsive Markdown. Well I would like to have some "static pages" in Markdown. And I try but it does not render nicely.

![image](https://user-images.githubusercontent.com/42288570/70593307-d6e04b00-1bdc-11ea-8865-019fd1b2ea18.png)

**Comment by philippjfr** [comment]
I can't quite understand the difference but I actually think the `HTML` pane is behaving unexpectedly here. If we set the sizing_mode on the actual Markdown pane to 'stretch_width' it behaves as I would expect. Without setting that I would expect it to default to a fixed width.

```
app_markdown = pn.Column(
    pn.pane.Markdown(TEXT, background="yellow", sizing_mode='stretch_width'), sizing_mode="stretch_width", background="blue"
)

**Comment by MarcSkovMadsen** [comment]
SOLVED

I am on Panel 0.12.1 with bokeh 2.3.3 and the first script now looks like

![image](https://user-images.githubusercontent.com/42288570/132103616-3b74016e-d961-44ad-9d8c-a77b7231c70a.png)

**Comment by philippjfr** [comment]
Love a bug that resolves itself.
