### ISSUE TITLE
Update Django docs to use django-channels

### ISSUE THREAD

**Issue by stefjunod** [holoviz/panel#865]
Hi, 

Using the user guide example: [https://panel.pyviz.org/user_guide/Django_Apps.html], I am trying to build a Django project with two apps "sliders" and "sliders2" with some different config/panel.

When I run the project, I have either the "sliders" or "sliders2" displaying. The Thread seems to be pointing to the same address....each app has its own bk_worker
````
def bk_worker():
    # Note: num_procs must be 1; see e.g. flask_gunicorn_embed.py for num_procs>1
    server = Server({server_cfg['app_name']: bk_app},
                    io_loop=IOLoop(),
                    address=server_cfg['address'],
                    port=server_cfg['port'],
                    allow_websocket_origin=["127.0.0.1:8000"])
    server.start()
    server.io_loop.start()
````
I have tried to check the flask_gunicor_embed.py and change my bk_worker to !!!!!
````
def bk_worker():
    asyncio.set_event_loop(asyncio.new_event_loop())

    bokeh_tornado = BokehTornado({server_cfg['app_name']: bk_app},
                                 extra_websocket_origins=[f"{server_cfg['address']}:8000"])
    bokeh_http = HTTPServer(bokeh_tornado)
    bokeh_http.add_socket(sockets)
    server = BaseServer(IOLoop.current(), bokeh_tornado, bokeh_http)
    server.start()
    server.io_loop.start()
````
but not working...
my server_cfg is just:
```
server_cfg = dict(
    app_name='/bk_sliders_app',
    address="localhost",
    port=5006,
    template='./sliders/sliders.html',
    tag='server_script',
)
```
How shall I configure my  Tornado and project to be able to run sliders and sliders2 ?

Thanks,
Stef

**Comment by philippjfr** [comment]
Sorry I haven't replied yet, I'll try to have an actual response tomorrow. The example in the docs is actually somewhat outdated, in recent versions of bokeh you can now integrate directly with Django using django-channels so there's not even a need for a separate server.

**Comment by philippjfr** [comment]
That being said, this is more of a usage questions so I'd prefer if we moved this to the [discourse](https://discourse.holoviz.org).

**Comment by stefjunod** [comment]
Hi Philipp,

Thanks for taking the time to look into it. Panel is great!!!
Is there any docs, example I can use  or could you point me to the right direction (sample code).
Happy to help update the docs Panel/Django is you need some help.

Panel is really great! Thanks,
Stef

**Comment by stefjunod** [comment]
Hi,

I have move it to the discourse as suggested.

Cheers,
Stef

**Comment by stefjunod** [comment]
Closing

**Comment by philippjfr** [comment]
I think we can reopen and change the purpose of the issue to update the docs.

**Comment by philippjfr** [comment]
Here is a bokeh based templates we could try to adapt:

https://github.com/bokeh/bokeh/tree/master/examples/howto/server_embed/django_embed

**Comment by stefjunod** [comment]
Great, I will look at the example and let you know if I can get it to work.
Thanks,
Stef

**Comment by philippjfr** [comment]
In fact it looks like there's already a Panel component in there:

https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/django_embed/django_embed/shape_viewer.py

**Comment by stefjunod** [comment]
Hi Philipp,

I have made some progress...[https://bitbucket.org/stephane_junod/django_embed/src/master/](url)

What I did:
- remove all unnecessary code from the Django_Embed root directory, keeping the sea_surface app
- create another app call sliders implementing the sinewave app (bk_model "sinewave.py", bk_app create the app)
- updated the root url patterns 

``` python

import sliders.bk_app as sliders_app

bokeh_apps = [
    autoload("sea_surface", views.sea_surface_handler),
    autoload("sliders", sliders_app.app),
]
```

Could you have a look at let me know if this is correct or if there is a better way to do it.
Then I will clean it up with a Django project with two django app ("landing", "sliders")...Then we can document it...don't know how, but happy to try...there is always a first time.

Cheers,
Stef

**Comment by philippjfr** [comment]
Thanks for the update! Glad you got it working. As far as I know the two apps you are describing are pure bokeh apps, it would be good to replace them with Panel apps. Let me know if you want to work on documenting it together, just open a PR and we can collaborate.

**Comment by stefjunod** [comment]
Is my sliders app (sinewave) not a panel app?, sea_surface seems to be a bokeh app ?

autoload comes from bokeh 

> from bokeh.server.django import autoload

Is there something equivalent in panel ?

Happy to help for the documentation. If sliders is a panel app, I will clean the project with two panel app, then we can start documenting it.

**Comment by stefjunod** [comment]
Some high level attend at document what I have done...probably missing some important steps


# Django Apps

As the core user guides including the Introduction have demonstrated, it is easy to display Panel apps in the notebook, launch them from an interactive Python prompt, and deploy them as a standalone Bokeh server app from the commandline. However, it is also often useful to embed a Panel app in large web application, such as a Django web server. Using Panel with Django requires a bit more work than for notebooks and Bokeh servers.

To run this example app yourself, you will first need to install django 2 or 3 (e.g. conda install "django=2").

We will show how to build a simple django apps with 3 apps stockscreener, sliders, sliders_cosine. this app shows how to integrate Panel with a Django view, but there's currently no interaction between the Param and Django models.

### Init
In the root directory (alongside settings.py):
- Install channels 

- Create a file ***asgi.py***:

```python
import os

import django
from channels.routing import get_default_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Django_Panel_Multi.settings')
django.setup()
application = get_default_application()
```

- Create a file ***routing.py***:
```python
from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
from django.apps import apps

bokeh_app_config = apps.get_app_config('bokeh.server.django')

application = ProtocolTypeRouter({
    'websocket': AuthMiddlewareStack(URLRouter(bokeh_app_config.routes.get_websocket_urlpatterns())),
    'http': AuthMiddlewareStack(URLRouter(bokeh_app_config.routes.get_http_urlpatterns())),
})
```

- In  ***setting.py***:

```python
from bokeh.settings import bokehjsdir
...

# WSGI_APPLICATION = 'Django_Panel_Multi.wsgi.application'
ASGI_APPLICATION = 'Django_Panel_Multi.routing.application'
...
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # local
    'channels',
    'bokeh.server.django',
]

#  at the bottom 
STATICFILES_DIRS = [bokehjsdir()]
```
## Sliders panel app
- Create a new app:
```python
python manage.py startapp sliders
```
- Create ***pn_model.py*** for the panel class
```python
import numpy as np
import param
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

class SineWave(param.Parameterized):
    offset = param.Number(default=0.0, bounds=(-5.0, 5.0))
    amplitude = param.Number(default=1.0, bounds=(-5.0, 5.0))
    phase = param.Number(default=0.0, bounds=(0.0, 2 * np.pi))
    frequency = param.Number(default=1.0, bounds=(0.1, 5.1))
    N = param.Integer(default=200, bounds=(0, None))
    x_range = param.Range(default=(0, 4 * np.pi), bounds=(0, 4 * np.pi))
    y_range = param.Range(default=(-2.5, 2.5), bounds=(-10, 10))

    def __init__(self, **params):
        super(SineWave, self).__init__(**params)
        x, y = self.sine()
        self.cds = ColumnDataSource(data=dict(x=x, y=y))
        self.plot = figure(plot_height=400, plot_width=400,
                           tools="crosshair, pan, reset, save, wheel_zoom",
                           x_range=self.x_range, y_range=self.y_range)
        self.plot.line('x', 'y', source=self.cds, line_width=3, line_alpha=0.6)

    @param.depends('N', 'frequency', 'amplitude', 'offset', 'phase', 'x_range', 'y_range', watch=True)
    def update_plot(self):
        x, y = self.sine()
        self.cds.data = dict(x=x, y=y)
        self.plot.x_range.start, self.plot.x_range.end = self.x_range
        self.plot.y_range.start, self.plot.y_range.end = self.y_range

    def sine(self):
        x = np.linspace(0, 4 * np.pi, self.N)
        y = self.amplitude * np.sin(self.frequency * x + self.phase) + self.offset
        return x, y
```
- Create ***pn_app.py*** for the panel app
```python
import panel as pn
from .pn_model import SineWave

def app(doc):
    sw = SineWave()
    row = pn.Row(sw.param, sw.plot)
    row.server_doc(doc)
```

- In **views.py** add:
```python
# Create your views here.
from bokeh.embed import server_document

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

def sliders(request: HttpRequest) -> HttpResponse:
    script = server_document(request.build_absolute_uri())
    return render(request, "sliders/sliders.html", dict(script=script))
```
We assume that the templates forlder is in the root directory of the django project and each app has its own folder

- Create ***urls.py***:
```python
from django.urls import path

from . import views

app_name = 'sliders'
urlpatterns = [
    path('', views.sliders, name='sliders'),
]
```
- In the project urls.py the urls for the app

```python
from bokeh.server.django import autoload
from django.apps import apps
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

import gbm.pn_app as sliders_cosine_app
import sliders.pn_app as sliders_app

pn_app_config = apps.get_app_config('bokeh.server.django')

urlpatterns = [
    path('/sliders', include('sliders.urls')),
    path('admin/', admin.site.urls),
]

base_path = settings.BASE_PATH
# print(f"base_path: {base_path}")

bokeh_apps = [
    autoload("sliders", sliders_app.app),
]

urlpatterns += staticfiles_urlpatterns()
print(f"urlpatterns: {urlpatterns}")
```



## Sliders_Cosine panel app
Do the same as above....and update your project urls.py
```python
from bokeh.server.django import autoload
from django.apps import apps
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

import gbm.pn_app as sliders_cosine_app
import sliders.pn_app as sliders_app


pn_app_config = apps.get_app_config('bokeh.server.django')

urlpatterns = [
    path('sliders/', include('sliders.urls')),
    path('sliders_cosine/', include('gbm.urls')),
    path('admin/', admin.site.urls),
]

bokeh_apps = [
    autoload("sliders", sliders_app.app),
    autoload("sliders_cosine", sliders_cosine_app.pp),
]

urlpatterns += staticfiles_urlpatterns()
print(f"urlpatterns: {urlpatterns}")
```

**Comment by MarcSkovMadsen** [comment]
Just a comment/ question here on why the focus on Django and not Flask?

The reason being. I am a data scientist developer who made a choice 1½ years ago to use Django over Flask for an analytics trading application at my company. Personally I like Django and has learned a lot from using it. But I cannot really get any fellow pythonistas, data engineers or data scientist to contribute to it. I really have to pursuide and help them. They all seem to pick Flask.

And now I'm wondering should I move to Flask with all the cost that move has because then I can get contributors.

So for an analytics app framework like Panel **why focus on Django and not Flask?**

**Comment by philippjfr** [comment]
@stefjunod That looks fabulous, thanks so much for taking this on! Would be great to get a PR opened so I can comment on things directly, but to comment on your question, yes mapping the parameter to the widget is currently the best approach. We can iterate on that in your PR though.

>Just a comment/ question here on why the focus on Django and not Flask?

Mostly because we had a client pay for Django integration. That doesn't mean we don't want to document Flask integration in fact it is on our to-do list. However a) bokeh now actually has integration to run entirely on a Django server (without launching a separate bokeh server) and b) there are already some blogs and documentation in bokeh about flask integration, which will almost certainly always involve embedding scripts from a separately running bokeh server. That said I would absolutely **love** to see a similar example for flask in our docs.

**Comment by MarcSkovMadsen** [comment]
Hi @philippjfr. How does Panel performance compare in Tornado vs Django? In my experience Tornado is very, very fast.

**Comment by MarcSkovMadsen** [comment]
One perspective on this improvement is that in scerios (like mine) where there are different teams with different preferences you can actually combine apps from Django, Panel, Dash (using https://github.com/GibbsConsulting/django-plotly-dash) and Angular in one commen Django Application. And take advantage of all the user management etc.

I would dream of doing that and creating something where I can use the AD and Django User Groups to enable access to specific apps only. Something like what Tableau server provides. But people can just use the power of Python and their favourite analytics app technology.

Would be awesome.

**Comment by philippjfr** [comment]
I've never done any profiling, the main benefit of using the Django-channels integration is really not requiring an entirely separate server to be running which adds additional complications in terms of ports, security etc.

>you can actually combine apps from Django, Panel, Dash (using https://github.com/GibbsConsulting/django-plotly-dash), Angular, Vue and React in one commen Django Application. And take advantage of all the user management etc.

That's precisely the use case of the client we implemented this for. They have a large framework with user management and a variety of apps built using different technologies and wanted to serve bokeh/panel apps from within this framework without launching separate tornado servers.

**Comment by MarcSkovMadsen** [comment]
Yeah. Right now I'm orchestrating seperate build pipelines and docker containers for Django (Admin+Rest API), Sphinx (Documentation), Angular Front End, Two Streamlit aps and one Dash app. 

Auch. I know I have to get rid of that. But we had to ship, so I did it.

**Comment by MarcSkovMadsen** [comment]
When I use Panel via Django I guess I can use the Django goodness like the Django ORM?

**Comment by stefjunod** [comment]
Great, I will:
- Get the Django app to run with 3 apps (sinwave, gbm, and stockscreener (to show pn.widget))
- Open PR

Then we can finalize...and do the same type of apps with Flask....or look at what next!

For my 2 cents of Flask vs Django:
Started with Flask as I could not understand Django boilerplate code....Flask makes it easier to start until you need admin, user,...

**Comment by jbednar** [comment]
As someone who has never done much with either Django or Flask, don't trust me much, but the sense I get from lots of people talking is that Flask is very easy to get started with, but is then a dead end where people get quite frustrated that they have no way to add the features they eventually realize they need. Conversely Django has all the features they need, but is very difficult to get started with, so people only reach it after much frustration with other tools. Seems like a no-win situation!

**Comment by stefjunod** [comment]
Hi,

I have done a PR (first time for me, ...)
Django Panel with channels for multi apps

Still some issues, but getting there.

I guess we can close this Issues.

Cheers,Stef

**Comment by philippjfr** [comment]
>I have done a PR (first time for me, ...)

Woo, congrats! We really, really appreciate it.
