### ISSUE TITLE
Developer guide out of date

### ISSUE THREAD

**Issue by kgullikson88** [holoviz/panel#866]
I am setting up a development environment in order to start tackling https://github.com/holoviz/panel/issues/864

I noticed the following small issues with the Developer guide documentation on the website:

1. After cloning, you should say to `cd` into the `panel` directory. If you don't, the `doit` command gives an error about not finding a `dodo.py` file
2. This command: `doit env_create -c pyviz/label/dev -c conda-forge --name=panel_dev --python=3.6` needs the `bokeh` channel to find `jupyter_bokeh`. It should be `doit env_create -c pyviz/label/dev -c conda-forge  -c bokeh --name=panel_dev --python=3.6`
3. This command: `doit develop_install -c pyviz/label/dev -c conda-forge -o tests -o recommended` failed saying I need to install nodejs. I ran `conda install nodejs`, and then ran the command again and it worked. Can that `doit` task be updated to install nodejs?
4. It appears that the `doit develop_install` command installs `panel` via `python setup.py develop`, so the "Building and Installing" section seems redundant.

**Comment by philippjfr** [comment]
Thanks for the feedback. All your suggestions sound very reasonable. Let's aim to get these updates into 0.7.1.

**Comment by ceball** [comment]
> doit develop_install -c pyviz/label/dev -c conda-forge -o tests -o recommended failed saying I need to install nodejs

Just to note that on travis, the options being installed are `-o recommended -o tests -o build`, and the channels being used are `-c pyviz/label/dev -c bokeh -c conda-forge` (both different from the developer guide).

**Comment by ceball** [comment]
> It appears that the doit develop_install command installs panel via python setup.py develop, so the "Building and Installing" section seems redundant.

I think it's `pip install --no-deps -e .` but the point is still correct (apparently redundant instruction).

**Comment by ceball** [comment]
I've also noticed that a develop_install of panel using conda now unfortunately installs a panel conda package from anaconda.org, because panel is a dependency of holoviews (which is a recommended dependency of panel). I think pyctdev should avoid doing that...
