### ISSUE TITLE
Portfolio-optimizer example in gallery raises "502 Bad GateWay"

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#871]
The portfolio example at https://panel.pyviz.org/gallery/demos/portfolio-optimizer.html#gallery-portfolio-optimizer raises "502 Bad Gateway" error.

![image](https://user-images.githubusercontent.com/42288570/70875233-88082c00-1fb5-11ea-93bb-655182a1a23b.png)

**Comment by philippjfr** [comment]
Thanks I'll redeploy.

**Comment by philippjfr** [comment]
Fixed.
