### ISSUE TITLE
Please replace MultiSelect widget with something more compact, effective and nicer looking

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#874]
#### My Pain

I know of experience that many of my dashboard have multiple multi-selections. 

The MultiSelect widget of panel is not compact so it takes up a lot of space.

Furthermore I find the MultiSelect not very nicely looking. I would like my dashboards to look appealing and fresh.

Futhermore I think navigating and selecting in the MultiWidget is slow if as soon as you have to start scrolling.

![image](https://user-images.githubusercontent.com/42288570/70967814-c2e29080-2097-11ea-97cd-e41d3b9e1bc7.png)

#### Solution

Implement compact, efficient and nicer looking MultiSelect. 

It should work as a dropdown with multiselect.

#### Additional Context

You can get inspiration from Dash, Streamlit and Tableau that all have a much more compact and modern looking widget.

![image](https://user-images.githubusercontent.com/42288570/70967921-240a6400-2098-11ea-9d99-cefe44ed27dc.png)

![image](https://user-images.githubusercontent.com/42288570/70967964-3d131500-2098-11ea-8991-3ff2f1c29fc8.png)

Here it's used an that's where I have my evaluation from

![kickstarter_dashboard](https://user-images.githubusercontent.com/42288570/70968057-72b7fe00-2098-11ea-8680-73de1f2bf843.gif)

**Comment by jbednar** [comment]
I think that would be a request for Bokeh.  I agree it would be nice to have a more compact option!

**Comment by philippjfr** [comment]
The MultiChoice widget was added in Panel 0.9.
