### ISSUE TITLE
pn.pane.Vega(spec) not showing within notebook (related to report #872)

### ISSUE THREAD

**Issue by jandot** [holoviz/panel#885]
See image: using the example spec provided in bug [report #872](https://github.com/holoviz/panel/issues/872), I can draw using `Vega(spec)` as before, and indeed a `pn.panel(spec).show()` opens a new browser tab and shows the barchart. However, wanting to show the panel in the notebook itself still does not work yet: `pn.panel(spec)`.

![Image 1: Working or non-working output given different commands](https://discourse.holoviz.org/uploads/default/original/1X/898df258176c3c19cef4ee83977796286a6491ee.png)

**Comment by philippjfr** [comment]
Did you load the 'vega' in the extension? You have to load it using:

```python
pn.extension('vega')
```

**Comment by philippjfr** [comment]
Looking back at your discourse post your issue is this:

```
pn.extension()
pn.extension('vega')
```

You should only call the extension once and 'vega' should be in that first call.

**Comment by philippjfr** [comment]
I can't reproduce and it looks like what I described above is the issue. Please reopen if the issue persists.
