### ISSUE TITLE
Render issue when width is set on HTML pane

### ISSUE THREAD

**Issue by sdc50** [holoviz/panel#893]
There seems to be a rendering issue that was introduced in 0.7.1a. When the `width` is set on and `pn.pane.HTML` pane the positioning of the next element is off.

#### Panel 0.7.0
![image](https://user-images.githubusercontent.com/6454472/71200660-1a325d80-225e-11ea-83ae-b0e8e0318d3a.png)

#### Panel 0.7.1a2
![image](https://user-images.githubusercontent.com/6454472/71200885-7dbc8b00-225e-11ea-972a-83f4599e5305.png)

**Comment by philippjfr** [comment]
Thanks for reporting this, I have a good idea what it is.

**Comment by philippjfr** [comment]
Will tag a new dev release as soon as the PR is merged.
