### ISSUE TITLE
The HoloViews panel does not support css_classes

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#902]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Tornado 5.1.11
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### My Pain

I would like to control some of the styling of panels like for example the HoloViews panel using the `css_classes` attribute and some `raw_css`. 

But specifying the css_classes attribute on the HoloViews panel does not end up in the HTML in the browser!

![image](https://user-images.githubusercontent.com/42288570/71343897-6ed91f80-2561-11ea-9de5-dca7b7bb7a2f.png)

I would have expected the css_classes appended to show up in the spot marked by the red circle.

#### Solution

Support this! :-)

#### Reproducing Example

```python
import hvplot.pandas
import pandas as pd
import panel as pn


def _get_chart_data() -> pd.DataFrame:
    """## Chart Data

    Returns:
        pd.DataFrame -- A DataFrame with dummy data and columns=["Day", "Orders"]
    """

    chart_data = {
        "Day": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",],
        "Orders": [15539, 21345, 18483, 24003, 23489, 24092, 12034],
    }
    return pd.DataFrame(chart_data)


def _holoviews_chart():
    """## Dashboard Orders Chart generated by HoloViews"""
    data = _get_chart_data()
    line_plot = data.hvplot.line(
        x="Day", y="Orders", width=None, height=500, line_color="#007BFF", line_width=6,
    )
    scatter_plot = data.hvplot.scatter(x="Day", y="Orders", height=300).opts(
        marker="o", size=10, color="#007BFF"
    )
    fig = line_plot * scatter_plot
    gridstyle = {"grid_line_color": "black", "grid_line_width": 0.1}
    fig = fig.opts(
        responsive=True,
        toolbar=None,
        yticks=list(range(12000, 26000, 2000)),
        ylim=(12000, 26000),
        gridstyle=gridstyle,
        show_grid=True,
    )
    return fig


chart = _holoviews_chart()
chart_panel = pn.panel(chart, css_classes=["holo-chart"])
app = pn.Column(chart_panel, width=500)
app.servable("no css_classes")
```

#### Additional Info

According to the help text for the HoloViews panel this should be supported

![image](https://user-images.githubusercontent.com/42288570/71344008-bb245f80-2561-11ea-8818-80919337c32b.png)

The motivation for this is that I would like to add **card functionality** to the Bootstrap Template for awesome-panel.org. But I need css_classes to do this properly.

![image](https://user-images.githubusercontent.com/42288570/71344134-076f9f80-2562-11ea-8b8e-ee76f1485615.png)

It works for the HTML panel

![image](https://user-images.githubusercontent.com/42288570/71344371-a1cfe300-2562-11ea-92a7-6ddb9be749be.png)

**Comment by MarcSkovMadsen** [comment]
It works for the HTML panel

![image](https://user-images.githubusercontent.com/42288570/71344346-8ebd1300-2562-11ea-866f-5434f6d4b72a.png)

**Comment by philippjfr** [comment]
Should be an easy fix.

**Comment by MarcSkovMadsen** [comment]
I can confirm this has been solved in the latest release candidate for Panel v.0.8.0

----

![image](https://user-images.githubusercontent.com/42288570/73425346-a93c9600-4331-11ea-83fd-21655849df0c.png)
