### ISSUE TITLE
Drag and Drop FileInput Widget

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#917]
## Feature Request - Drag and Drop FileInput Widget

It would be **nice** to be able to drag and drop files onto a area for upload instead of the more tedious process of the current fileupload.

Something like the one in Streamlit

![image](https://user-images.githubusercontent.com/42288570/71719933-2ef71f80-2e20-11ea-898d-b6e1f0ee20aa.png)

Or in Dash

![image](https://user-images.githubusercontent.com/42288570/71719964-433b1c80-2e20-11ea-9338-1aea76b5c278.png)

## Additional Context

The request is based on the experience from the Image Classification app I've add to the galleries at awesome-streamlit.org and awesome-panel.org.

It's simply a **better experience**, **much faster**, **more interactive** and **more fun** to be able to drag and drop files instead of the current process of clicking and selecting.

### Streamlit 

![image_classifier](https://user-images.githubusercontent.com/42288570/71720079-a927a400-2e20-11ea-8ce7-92031f2fe09c.gif)

### Panel

![image_classifier](https://user-images.githubusercontent.com/42288570/71720096-b775c000-2e20-11ea-9dab-79f88b67c528.gif)

**Comment by MarcSkovMadsen** [comment]
If it was possible to set the uploaded image as the background image of the drag and drop area it would actually be awesome.

**Comment by MarcSkovMadsen** [comment]
Any news on this one? I think this is a fundamental one. I can just see how users of apps developed in alternative frameworks are able to drag and drop files from mail and chat into their apps.

**Comment by MarcSkovMadsen** [comment]
We can create a quick fix by adding the css below to the Panel stylesheet and describing how to use it in the Reference Guide.

```css
.pnx-file-upload-area input[type=file] {
    width: 100%;
    height: 100%;
    border: 3px dashed #9E9E9E;
    background: #EEEEEE;
    border-radius: 5px;
    text-align: left;
    margin: auto;
}
```


@philippjfr . Let me know if you would accept a PR on this. And please also tell me where in the Panel repo I can find that stylesheet. I cannot find it from version 0.10.0.

#### How it looks

![image](https://user-images.githubusercontent.com/42288570/98458805-c5a91100-2194-11eb-8d5b-66d9d22d3fed.png)

**Comment by MarcSkovMadsen** [comment]
I would like the FileInputArea to be able to show the file uploaded. Either as a preview (without sending to server) or as a panel that the user can populate with what ever he wants.

Something like this :-)

https://user-images.githubusercontent.com/42288570/146669572-54513497-fde0-45fb-b4ba-a8cb211f40b2.mp4

**Comment by nascifMode** [comment]
+1, I am building an app using the FileInput widget and the first comment I got from my internal customers is that they would rather be able to drop the file than navigate to find it.

**Comment by MarcSkovMadsen** [comment]
They can actually drop onto the button. But it's not obvious.

**Comment by nascifMode** [comment]
Not at all. :)
Also not documented. Adding a note about it being supported in https://panel.holoviz.org/reference/widgets/FileInput.html would be helpful. But ideally the widget itself should communicate that possibility. Maybe a tooltip?

**Comment by philippjfr** [comment]
The FileDropper widget addresses this.
