### ISSUE TITLE
`Interact` fails with multiple data sources with Altair/Vega

### ISSUE THREAD

**Issue by mansenfranzen** [holoviz/panel#920]
## Expected and observed behavior
First of all, thanks for the great package! 

I'm using panel in conjunction with altair. I ran into an issue while composing multiple altair subplots into one altair chart and wrapping it with `pn.interact.interact`. The problem only occurs when the altair subplots have distinct data sources. In the example below, if both subplots use the same pandas dataframe (e.g. df1), everything works as expected. However, if distinct data sources are used, I run into a type error (see traceback below).

The example works fine if panel is not used at all.

## Reproducible example

```python
import altair as alt
import pandas as pd
from panel.interact import interact
pn.extension('vega')

def plot(multiply=1):
    
    df1 = pd.DataFrame({"col1": range(20), "col2": range(20)})
    df1["col1"] = df1["col1"] * multiply
    
    df2 = pd.DataFrame({"col1": range(20), "col2": range(20)})
    df2["col2"] = df2["col2"] * multiply
    
    line = alt.Chart(df1).mark_line().encode(x="col1:Q", y="col2:Q")
    bar = alt.Chart(df2).mark_bar().encode(x="col1:Q", y="col2:Q")
    
    return (line | bar)

interact(plot, multiply=(1, 20, 1))
```

## All software version info:

<details><summary><b>pandas.show_versions()</b></summary>

commit           : None
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : de_DE.UTF-8
LOCALE           : None.None

</details>

<details><summary><b>pip freeze</b></summary>

altair==3.3.0               
attrs==19.3.0               
backcall==0.1.0             
bleach==3.1.0               
bokeh==1.4.0                
certifi==2019.11.28         
colorama==0.4.3             
decorator==4.4.1            
defusedxml==0.6.0           
entrypoints==0.3            
et-xmlfile==1.0.1           
importlib-metadata==1.3.0   
ipykernel==5.1.3            
ipython==7.11.1             
ipython-genutils==0.2.0     
ipywidgets==7.5.1           
jdcal==1.4.1                
jedi==0.15.2                
Jinja2==2.10.3              
jsonschema==3.2.0           
jupyter==1.0.0              
jupyter-client==5.3.4       
jupyter-console==6.0.0      
jupyter-core==4.6.1         
Markdown==3.1.1             
MarkupSafe==1.1.1           
mistune==0.8.4              
more-itertools==8.0.2       
nbconvert==5.6.1            
nbformat==4.4.0             
notebook==6.0.2             
numpy==1.18.0               
openpyxl==3.0.2             
packaging==19.2             
pandas==0.25.3              
pandocfilters==1.4.2        
panel==0.7.0                
param==1.9.2                
parso==0.5.2                
pickleshare==0.7.5          
Pillow==7.0.0               
prometheus-client==0.7.1    
prompt-toolkit==2.0.10      
pyct==0.4.6                 
Pygments==2.5.2             
pyparsing==2.4.6            
pyrsistent==0.15.6          
python-dateutil==2.8.1      
pytz==2019.3                
pyviz-comms==0.7.2          
pywin32==227                
pywinpty==0.5.7             
PyYAML==5.2                 
pyzmq==18.1.1               
qtconsole==4.6.0            
Send2Trash==1.5.0           
six==1.13.0                 
terminado==0.8.3            
testpath==0.4.4             
toolz==0.10.0               
tornado==6.0.3              
traitlets==4.3.3            
wcwidth==0.1.8              
webencodings==0.5.1         
widgetsnbextension==3.5.1   
wincertstore==0.2           
xlrd==1.2.0                 
zipp==0.6.0                 

</details>

## Traceback
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\.conda\envs\env_pycon2019\lib\site-packages\IPython\core\formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

~\.conda\envs\env_pycon2019\lib\site-packages\panel\viewable.py in _repr_mimebundle_(self, include, exclude)
    308         comm = state._comm_manager.get_server_comm()
    309         doc = _Document()
--> 310         model = self._render_model(doc, comm)
    311         if config.embed:
    312             return render_model(model)

~\.conda\envs\env_pycon2019\lib\site-packages\panel\viewable.py in _render_model(self, doc, comm)
    263         if comm is None:
    264             comm = state._comm_manager.get_server_comm()
--> 265         model = self.get_root(doc, comm)
    266 
    267         if config.embed:

~\.conda\envs\env_pycon2019\lib\site-packages\panel\viewable.py in get_root(self, doc, comm)
    432         """
    433         doc = doc or _curdoc()
--> 434         root = self._get_model(doc, comm=comm)
    435         self._preprocess(root)
    436         ref = root.ref['id']

~\.conda\envs\env_pycon2019\lib\site-packages\panel\layout.py in _get_model(self, doc, root, parent, comm)
    117         if root is None:
    118             root = model
--> 119         objects = self._get_objects(model, [], doc, root, comm)
    120         props = dict(self._init_properties(), objects=objects)
    121         model.update(**self._process_param_change(props))

~\.conda\envs\env_pycon2019\lib\site-packages\panel\layout.py in _get_objects(self, model, old_objects, doc, root, comm)
    109                 child, _ = pane._models[root.ref['id']]
    110             else:
--> 111                 child = pane._get_model(doc, root, model, comm)
    112             new_models.append(child)
    113         return new_models

~\.conda\envs\env_pycon2019\lib\site-packages\panel\layout.py in _get_model(self, doc, root, parent, comm)
    117         if root is None:
    118             root = model
--> 119         objects = self._get_objects(model, [], doc, root, comm)
    120         props = dict(self._init_properties(), objects=objects)
    121         model.update(**self._process_param_change(props))

~\.conda\envs\env_pycon2019\lib\site-packages\panel\layout.py in _get_objects(self, model, old_objects, doc, root, comm)
    109                 child, _ = pane._models[root.ref['id']]
    110             else:
--> 111                 child = pane._get_model(doc, root, model, comm)
    112             new_models.append(child)
    113         return new_models

~\.conda\envs\env_pycon2019\lib\site-packages\panel\pane\vega.py in _get_model(self, doc, root, parent, comm)
    125         else:
    126             json = self._to_json(self.object)
--> 127             self._get_sources(json, sources)
    128         props = self._process_param_change(self._init_properties())
    129         self._get_dimensions(json, props)

~\.conda\envs\env_pycon2019\lib\site-packages\panel\pane\vega.py in _get_sources(self, json, sources)
     77                 import altair as alt
     78                 if (not isinstance(self.object.data, (alt.Data, alt.UrlData)) and
---> 79                     columns == set(self.object.data)):
     80                     data = ColumnDataSource.from_df(self.object.data)
     81                 else:

TypeError: 'UndefinedType' object is not iterable
```

**Comment by kavvkon** [comment]
Same error here:
A single object is of type:  `altair.vegalite.v4.api.Chart`
but a combined object is of type : `altair.vegalite.v4.api.LayerChart`

If a function returns the former it works properly. If The latter then it raises the error mentioned above
