### ISSUE TITLE
Param cannot use DatePicker as widget for Parameterized Class

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#921]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Tornado 5.1.11
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### Description of expected behavior and the observed behavior

I'm trying to use a DatePicker widget for a Parameterized Class similarly to the example of *Custom Widgets* in the [Panel Param Documentation](https://panel.pyviz.org/user_guide/Param.html).

But it does not work for me.

Just as I can get a `pn.widgets.RadioButtonGroup` working I would have expected to be able to get a `pn.widgets.DatePicker` working.

![cannot_use_datepicker_for_param_class](https://user-images.githubusercontent.com/42288570/71775693-85ca3980-2f85-11ea-82e4-6b03f013e4d1.gif)

#### Reproducing example code

```python
"""I cannot set the widget to a DatePicker for a Parameterized Class"""

import param
import panel as pn
class CustomExample(param.Parameterized):
    """An example Parameterized class"""

    select_string = param.Selector(objects=["red", "yellow", "green"])
    date = param.Date()
    calendar_date = param.CalendarDate()

view = pn.Param(CustomExample.param, widgets={
        'select_string': pn.widgets.RadioButtonGroup,
        'date': pn.widgets.DatePicker,
        'calendar_date': pn.widgets.DatePicker}
    )

app = pn.Column(
    __doc__,
    view,
    pn.pane.Markdown("# Stand Alone Widget"),
    pn.widgets.DatePicker(),
    width=1000,
)
app.servable()
```

**Comment by MarcSkovMadsen** [comment]
Problem "solved". I found out I just need to set default values and bounds. Then it works. And it sort of makes sense.

The problem is it took me some time to figure out. And my guess is it will also take other people time. I.e. there is some friction here.

#### Ideas for improvement

I'm just brainstorming. But it would have been helpful with

- Error messages. Cannot use XYZWidget with param.ABC with no bounds!
- Something in the Custom Widgets section of the [Documentation](https://panel.pyviz.org/user_guide/Param.html) that a widget may not work if the default value or bounds are not set.

Furthermore I was looking for the Param pane documentation via the "Reference Gallery", but it's actually not there. Maybe it would be an idea to include it there. It's sort of "hidden" as it is now in the Parameters section as it is now.

#### Solution

```python
"""I cannot set the widget to a Slider for a Parameterized Class"""

import param
import panel as pn
import datetime

start = datetime.date(2019, 1, 1)
end = datetime.date(2021, 1, 1)
default = datetime.date(2020, 1, 1)


class CustomExample(param.Parameterized):
    """An example Parameterized class"""

    select_string = param.Selector(objects=["red", "yellow", "green"])
    date = param.CalendarDate(default=default, bounds=(start, end))
    number = param.Number(default=0, bounds=(-5.0, 5.0))


view = pn.Param(
    CustomExample.param,
    widgets={
        "select_string": pn.widgets.RadioButtonGroup,
        "date": pn.widgets.DatePicker,
        "number": pn.widgets.FloatSlider,
    },
)

app = pn.Column(
    __doc__, view, pn.pane.Markdown("# Stand Alone Widget"), pn.widgets.FloatSlider(), width=1000,
)
app.servable()
```

![image](https://user-images.githubusercontent.com/42288570/71780909-b2537500-2fc8-11ea-8980-c43e762dddd4.png)

![image](https://user-images.githubusercontent.com/42288570/71780911-b97a8300-2fc8-11ea-9cf1-72b267ec76df.png)

I included the Number of FloatSlider in the example because there I had the same problem.

**Comment by philippjfr** [comment]
Agreed at minimum the error message should be improved.

**Comment by kcpevey** [comment]
Thanks for posting this! I hit this last week and didn't have any idea why it wasn't working. Thanks!

**Comment by misolietavec** [comment]
Big "Thank you" also. I created an issue in ipywidgets_bokeh, but my simple example did not capture the essence of problem. The problem was in using DatePicker from panel.widgets.

**Comment by philippjfr** [comment]
This appears to have been fixed, precisely when I'm not sure.
