### ISSUE TITLE
The `selection` param in DataFrame does not change for user interactivity

### ISSUE THREAD

**Issue by atticusfyj** [holoviz/panel#923]
#### Environment

Environment: jupyterhub
Chrome: 78.0
panel: 0.7.0
holoviews: 1.12.7
bokeh: 1.4.0

#### Description of expected behavior and the observed behavior

When a row is selected in `DataFrame`, the `selection` param is not changed accordingly. The following code can reproduce the issue:

```python
import panel as pn
import holoviews as hv
import pandas as pd
import numpy as np


hv.extension('bokeh', logo=False)
tab = pn.widgets.DataFrame(pd.DataFrame({'name': ['a', 'b']}))


@pn.depends(tab.param.selection)
def test_plot(tab):
    return hv.Curve(np.random.random(size=5))


pn.Row(test_plot, tab)
```

Note that upon change the graph should change. But it did not.

<img width="943" alt="Screen Shot 2020-01-05 at 5 36 54 PM" src="https://user-images.githubusercontent.com/33437563/71777988-b5f3f580-2fe2-11ea-8830-ebbd19fc2059.png">

Manual prints show that the list is still empty:

<img width="255" alt="Screen Shot 2020-01-05 at 5 36 59 PM" src="https://user-images.githubusercontent.com/33437563/71777998-c906c580-2fe2-11ea-9408-e6e4c0341e57.png">

Only manual assignment can make the plot change:
```
tab.selection = [1]
```

**Comment by philippjfr** [comment]
Thanks, seems like there's a naming issue, it does seem to set `tab.selected` which is clearly wrong.
