### ISSUE TITLE
Holomap sliders do not change value when saved with panel

### ISSUE THREAD

**Issue by Jacob-Barhak** [holoviz/panel#925]
When saving holomap using panel, the resulting html file does not behave properly with sliders that do not update the number. Note than drop down lists work properly. The issue is with sliders and only in panel - if saved with holoviews it works. The following code reconstructs the problem in windows, Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)] on win32. Library versions are:
holoviews' version 1.12.7
panel version 0.7.0
bokeh version 1.4.0

````
import holoviews as hv
import numpy as np
import panel as pn
import bokeh
from bokeh.resources import INLINE

for library in [hv,pn,bokeh]:
	print ("%s version %s"% ( library, library.__version__))


hv.extension('bokeh') 

frequencies = [0.5, 0.75, 1.0, 1.25]


def sine_curve(phase, freq):
    xvals = [0.1* i for i in range(100)]
    return hv.Curve((xvals, [np.sin(phase+freq*x) for x in xvals]))

phases      = [0, np.pi/2, np.pi, 3*np.pi/2]
curve_dict_2D = {(p,f):sine_curve(p,f) for p in phases for f in frequencies}
hmap = hv.HoloMap(curve_dict_2D, kdims=['phase', 'frequency'])

panel_Object = pn.pane.HoloViews(hmap)
panel_Object.save('test_panel.html', resources=INLINE, title = 'Bug Example', embed=True)

hv.save(hmap,'test_holoviews.html')


````

The script generates the same output using both panel and holoview to show that the issue happens only in panel.

Here is the correct plot generated by holoviews:
![image](https://user-images.githubusercontent.com/1986155/71842135-a29a6600-3086-11ea-9dc1-704f9c679313.png)
Note that the sliders are not at the start and that the title on top of the slider matches the plot title with values.

Here is the panel plot:
![image](https://user-images.githubusercontent.com/1986155/71842002-5e0eca80-3086-11ea-82fa-03ecda965ab5.png)

Notice that there is a mismatch in the slider values and the plot - the slider widget titles are not refreshed when the slider is moved. The slider always shows the initial slider value, even when moved.

Hopefully this is enough to catch and fix the bug. And hopefully the fix will still work on Python 2.

**Comment by philippjfr** [comment]
Can't reproduce an issue with Panel and HoloViews master. Sorry for making you go through the effort to write this up.

**Comment by Jacob-Barhak** [comment]
Ok Philipp,

Yet again, please include the version this was closed. And if you have an
estimated release date, it will help - since the current release version
still has the problem - so the issue exists for current users who currently
have no solution.

Hopefully you will release the new version fast and it will work on Python
2.

             Jacob

**Comment by Jacob-Barhak** [comment]
This issue needs to be reopened - still not fixed in panel  version 0.8.0a2.post3+g82f5514

**Comment by philippjfr** [comment]
>This issue needs to be reopened - still not fixed in panel version 0.8.0a2.post3+g82f5514

Cannot reproduce.

**Comment by xavArtley** [comment]
Cannot reproduce too
<module 'holoviews' from 'd:\\python\\python37-64\\pyenv\\py37\\lib\\site-packages\\holoviews\\__init__.py'> version 1.13.0a21.post10+gdf1a5803
<module 'panel' from 'd:\\pythonworkspace\\modules\\panel\\panel\\__init__.py'> version 0.8.0a2.post3+g82f5514-dirty
<module 'bokeh' from 'd:\\python\\python37-64\\pyenv\\py37\\lib\\site-packages\\bokeh\\__init__.py'> version 1.4.0

**Comment by Jacob-Barhak** [comment]
This may be a python 2 vs. Python 3 issue. 
I am using 2.7.16
Hopefully the problem can be reproduced now.

**Comment by Jacob-Barhak** [comment]
Verified as working on python 2.7.16 on Windows after the following fix https://github.com/holoviz/panel/pull/997/ with the following versions:

holoviews version 1.13.0a21.post10+gdf1a5803
panel version 0.8.0b1.post4+geaecd6b
bokeh version 1.4.0

**Comment by WulfLuck** [comment]
Sorry, I apologize. Without changing anything this now runs:

Layout object containing two representations of multidimensional space

Stevens et al., Holoviews, SCIPY 2015, fig.2

mport numpy as np
import holoviews as hv
from holoviews import dim, opts
hv.extension('bokeh')


phases = np.arange(100)
holomap = hv.HoloMap(kdims=['Frequency', 'Amplitude', 'Function'])
for freq in [0.01, 0.05, 0.1]:
    for amp in range(1,4):
        for name, fn in [('sin', np.sin), ('cos', np.cos)]:
            cdata = fn(phases*freq*np.pi)*amp
            holomap[freq, amp, name] = hv.Curve(cdata, kdims=['Phase'], vdims=['Amplitude'])
holomap.grid(['Amplitude', 'Frequency']) + holomap

**Comment by Jacob-Barhak** [comment]
Yes @WulfLuck - this issue was verified fixed on Jan 23d 2020 - the issue was closed already. Yet the double verification helped. 

The nice thing about Holoviz was that most functionality still worked in Python 2 for a long time after it was abandoned. Think about all those organizations that have legacy code that needs visualization - this gives them some chance if they do not want to migrate to python 3 - sometimes such migration is painful for multiple reasons.  This is a commercial advantage you do not want to downplay...
