### ISSUE TITLE
No way to retrieve error message from button.on_click function

### ISSUE THREAD

**Issue by edishu** [holoviz/panel#926]
There seems to be no way to retrieve run time error in button.on_click function. Following code is error free and produces the output in the screen shot
```
import panel as pn
import numpy as np
import pandas as pd

from bokeh.plotting import figure
from bokeh.models import ColumnDataSource

pn.extension()

sentiment = ['Positive', 'Negative']
percentage = [0.5, 0.5]
data = dict([('sentiment', sentiment), ('percentage', percentage)])

p = figure(x_range=sentiment, plot_height=250, title="Sentiment Dist")
r = p.vbar(x='sentiment', top='percentage', width=0.9, source=data) 
bokeh_pane = pn.pane.Bokeh(p)

def mkHist():
    pos = np.random.uniform()
    neg = 1-pos
    x = ['Positive', 'Negative']
    y = [pos, neg]
    return x, y

textx = pn.widgets.TextInput(); texty = pn.widgets.TextInput()
button = pn.widgets.Button(name='Click me', button_type='primary')

def histPlot(event):
    X, Y = mkHist()
    textx.value = '{ev} {lst} yeah'.format(ev=event.obj.clicks, lst = X)
    texty.value = '{ev} {lst}'.format(ev=event.obj.clicks, lst = Y)    
    r.data_source.data['sentiment'] = X
    r.data_source.data['percentage'] = Y
    bokeh_pane.param.trigger('object')

button.on_click(histPlot)
col = pn.Column(button, textx, texty, bokeh_pane)
col
```
![Capture](https://user-images.githubusercontent.com/37514088/71846233-1729d080-3098-11ea-925c-eb7e1239b52c.JPG)

However, if I introduce errors in histPlot function above. I do not get any error on clicking the button.

```
def histPlot(event):
    X, Y = mkHist()
    textx.value = '{ev} {lst} yeah and nae'.format(ev=event.obj.clicks, lst = X)
    texty.value = '{ev} {lst}'.format(ev=event.obj.clicks, lst = Y)    
    r.data_source.data['sentiment'] = non_existing_var
    r.data_source.data['percentage'] = non_existing_var2
    bokeh_pane.param.trigger('object')

button.on_click(histPlot)
```
![Capture2](https://user-images.githubusercontent.com/37514088/71846598-fada6380-3098-11ea-92f5-b36e138c8707.JPG)

See the textx box. The message seems to be updated but r.data_source.data['percentage'] is still responsive on click. however histPlot points it to a non-existing variable now.

**Comment by philippjfr** [comment]
Could you clarify what environment you are running this in? Presumably in the notebook? If so errors will be shown in the browser console.

**Comment by edishu** [comment]
Yes, I'm running in notebook. I can see the error in browser console. However, the plot still get updated, which I am not expecting if on_click function has errors. Can you tell me how it is getting updated?

**Comment by philippjfr** [comment]
Not, sure, but in the next release callbacks will display errors/print output in the notebook.
