### ISSUE TITLE
panel does not keep shared_axes=False for layout of NdOverlay

### ISSUE THREAD

**Issue by AurelienSciarra** [holoviz/panel#929]
I've tried to make a dashboard that return a layout of several NdOverlay, and I wanted to not link their y axes. So I have added the option shared_axes=False to my layout but panel keeps linking the axes.

Here is an example
```
import pandas as pd
import panel as pn
import param
import numpy as np
import hvplot.pandas
import holoviews as hv

df_1=pd.DataFrame(np.random.randint(-100,100,size=(100,4)))
df_2=pd.DataFrame(np.random.randint(-10,10,size=(100,4)))

dict_df={'plot1':df_1,'plot2':df_2}

class Dashboard(param.Parameterized):
    plots = param.ListSelector(default=['plot1','plot2'],objects=['plot1','plot2'])

    
    @param.depends('plots')
    def view(self):
        list_plot=[]
        for plot in self.plots:
            df= dict_df[plot]
            list_plot.append(((df-df.mean())).hvplot())
        return hv.Layout(list_plot).opts(shared_axes=False).cols(1)
```
```
vtest=Dashboard()
p=pn.Row(vtest.param,vtest.view)
p
```
![br1](https://user-images.githubusercontent.com/33750617/71979505-2b97d580-321e-11ea-9c87-82994d776736.PNG)

the axes are linked then I've tried to acces vtest.view

![br2](https://user-images.githubusercontent.com/33750617/71979604-6a2d9000-321e-11ea-9706-5b1b3fe07d02.PNG)

The result is the same but if I display the holoview object instead of the vtest.view the shared_axes=False option works.

![br3](https://user-images.githubusercontent.com/33750617/71979673-934e2080-321e-11ea-80aa-cd38be626607.PNG)

Here is the hierarchy of my plot :
:Layout
     .NdOverlay.I  :NdOverlay   [Variable]
        :Curve   [index]   (value)
     .NdOverlay.II :NdOverlay   [Variable]
        :Curve   [index]   (value)

This bug occurs for a layout of NdOverlay but doesn't for a layout of Curve.

Environment:
panel :  0.7.0a15
holoviews : 1.12.6
python : 3.6.9
param : 1.9.2
firefox : 70.0.1

EDIT: I turned my dashboard into a servable and at first the axes were linked. But after having selected plot1 then plot2, the bug was solved. This manipulation does not work in the notebook.

first display of the servable
![br4](https://user-images.githubusercontent.com/33750617/71983701-a44f5f80-3227-11ea-9f81-4ffe31b20b52.PNG)

and after the reselection
![br5](https://user-images.githubusercontent.com/33750617/71983702-a44f5f80-3227-11ea-8d37-8f5d4a676a98.PNG)

**Comment by philippjfr** [comment]
It should indeed respect the option. For now you can disable the linking with:

```python
        return pn.panel(hv.Layout(list_plot).cols(1), linked_axes=False)
```

**Comment by AurelienSciarra** [comment]
Update
After having updated all my package, the bug was fixed.
At first I couldn't succeed to update panel because I hadn't the latest version of bokeh. Conda doesn't allowed me to update panel without notifying the dependency problem with bokeh. 
I'm sorry for this mistake and thank you.
