### ISSUE TITLE
Inclusion of pn.extension() is Causing Intermittent Javascript Errors

### ISSUE THREAD

**Issue by malekop** [holoviz/panel#931]
**Problem Desciption**:

When I try to create a Panel app I am getting intermittent javascript errors.
The source of the problem appears to be caused the inclusion of `pn.extension()`. 

When `pn.extension()` is included:

- Sometimes no error is raised and the Panel app is produced as expected.

- Sometimes **Error 1** is raised - the rest of the Jupyter notebook still executes despite the error and the Panel app is served.

- Sometimes **Error 2** is raised - despite some browser slowdown, sometimes the rest of notebook executes and the Panel app is served and sometimes it causes my browser to crash completely and no app is served.

**Expected Result:**
That the Panel app will be served without raising any errors or crashing the browser.

**Possible Workaround:**
I have found that commenting out `pn.extension()` prevents the error being raised and doesn't seem to have any negative affect on serving the app, however that doesn't seem right as it must have a function.

**Current software versions:**

```python3
python                    3.7.5
jupyter                   1.0.0
notebook                  6.0.2
os                        macOS Catalina
browser                   firefox 72.0.1
pandas                    0.25.3
numpy                     1.17.3
feather-format            0.4.0
plotly                    4.3.0
plotly_express            0.4.1
panel                     0.7.0
holoviews                 1.12.6
geoviews                  1.6.5
cartopy                   0.17.0
hvplot                    0.5.2
colorcet                  2.0.2
```
**Code Example:**
```python3
import pandas as pd
import numpy as np
import random
import copy
import feather
import plotly.graph_objects as go
import plotly.express as px
import panel as pn
import holoviews as hv
import geoviews as gv
import geoviews.feature as gf
import cartopy
import cartopy.feature as cf
from geoviews import opts
from cartopy import crs as ccrs
import hvplot.pandas # noqa
import colorcet as cc
from colorcet.plotting import swatch
hv.extension("bokeh") 
gv.extension("bokeh")
pn.extension()
```

**Errors**
- **Error 1**: 
`Comm promise not found for comm id hv-extension-comm main.min.js:47464:21
Bokeh: BokehJS not loaded, scheduling load and callback at 
Date Thu Jan 09 2020 11:51:45 GMT+0000 (Greenwich Mean Time)
main.min.js:199:13
Bokeh: injecting script tag for BokehJS library:  https://cdn.plot.ly/plotly-latest.min.js main.min.js:233:15
Bokeh: injecting script tag for BokehJS library:  https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js main.min.js:233:15
Bokeh: all BokehJS libraries/stylesheets loaded main.min.js:205:17
Bokeh: BokehJS plotting callback run at 
Date Thu Jan 09 2020 11:51:45 GMT+0000 (Greenwich Mean Time)
main.min.js:1297:15
[bokeh] setting log level to: 'info' main.min.js:574:2263
Bokeh: all callbacks have finished main.min.js:183:13
Comm promise not found for comm id hv-extension-comm main.min.js:47464:21
Bokeh: BokehJS not loaded, scheduling load and callback at 
Date Thu Jan 09 2020 11:51:48 GMT+0000 (Greenwich Mean Time)
main.min.js:44:13
Error: "Mismatched anonymous define() module: function(){return rt}
http://requirejs.org/docs/errors.html#mismatch"
    makeError http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    intakeDefines http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1251
    localRequire http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1443
    requirejs http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1794
    config http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1802
    load_libs http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e line 45772 > eval:72
    <anonymous> http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e line 45772 > eval:1136
    <anonymous> http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e line 45772 > eval:1141
    append_javascript http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45772
    append_mime_type http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45705
    append_display_data http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45668
    append_output http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45355
    handle_output http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45266
    output http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:47115
    _handle_output_message http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:48875
    proxy http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:10502
    _handle_iopub_message http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:48902
    _finish_ws_message http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:48694
    _msg_queue http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:48685
main.min.js:45774:21
`

- **Error 2**:
`Comm promise not found for comm id hv-extension-comm main.min.js:47464:21
Bokeh: BokehJS not loaded, scheduling load and callback at 
Date Thu Jan 09 2020 11:56:04 GMT+0000 (Greenwich Mean Time)
main.min.js:44:13
Error: "[object Object]"
    makeError http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:168
    intakeDefines http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1251
    localRequire http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1443
    requirejs http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1794
    config http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f:1802
    load_libs http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e line 45772 > eval:72
    <anonymous> http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e line 45772 > eval:1136
    <anonymous> http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e line 45772 > eval:1141
    append_javascript http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45772
    append_mime_type http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45705
    append_display_data http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45668
    append_output http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45355
    handle_output http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:45266
    output http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:47115
    _handle_output_message http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:48875
    proxy http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:10502
    _handle_iopub_message http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:48902
    _finish_ws_message http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:48694
    _msg_queue http://localhost:8888/static/notebook/js/main.min.js?v=6516ab272ec0ae364bcab50a8b64c82e:48685
main.min.js:45774:21
`

**Comment by jbednar** [comment]
`pn.extension()` serves several functions if you add optional arguments, but when used like that, its function is to install the JavaScript code needed for working with a Jupyter notebook. It's designed to be a no-op in cases where it isn't needed, so that you can write a single set of code and use it in many contexts.  Here, the errors are worrying, but it should be safe to omit it if you aren't using it in a notebook.

**Comment by philippjfr** [comment]
@malekop Could you clarify if you're using classic notebook or JupyterLab?

**Comment by philippjfr** [comment]
I guess based on the fact that requirejs is mentioned it's classic notebook. Could you also report your version of bokeh?

**Comment by philippjfr** [comment]
Separately though:

```
hv.extension("bokeh") 
gv.extension("bokeh")
pn.extension()
```

this is total overkill, only one of these is needed.

**Comment by malekop** [comment]
Thanks both for the quick response.

I am using a Jupyter notebook not JupyterLab and I am using Bokeh 1.4.0.

@philippjfr your last point seemed to fix it - I have switched to only using `hv.extension("bokeh","plotly")` and it seems like I am no longer seeing the errors/crashes.

I have been messing about a lot with panel, plotly express, hvplot, holoviews and geoviews - I think I just got myself confused bringing the plots from different libraries together in a single Panel app.

Just to clarify, if `hv.extension()` is the top level, then would it be acceptable to just use `hv.extension("bokeh","plotly")` even if I was only plotting using geoviews or hvplot or plotly express as part of a Panel app? Or should you always use the specific extension where ever possible but then switch to using `hv.extension()` when I have multiple different types of libraries plotting like in my case?

**Comment by philippjfr** [comment]
>Just to clarify, if hv.extension() is the top level, then would it be acceptable to just use hv.extension("bokeh","plotly")

This should be sufficient to plot using holoviews, hvplot, geoviews, plotly and plotly-express within a panel app. If you require other optional Panel components (e.g. vega or KaTeX) you would also have to include `pn.extension('vega', 'katex')`.

**Comment by malekop** [comment]
Perfect, thanks for the clarification
