### ISSUE TITLE
Plot in jupyter using matplotlib is not updating

### ISSUE THREAD

**Issue by AsadDUET** [holoviz/panel#938]
when i change the slider, Plot in jupyter using matplotlib is not updating. but no error shows up.

**Comment by jbednar** [comment]
We'd need much more information to determine what you mean, i.e. which plot (one of our examples? Something you wrote (if so post the code)?), which versions of Panel, Bokeh, Matplotlib, and Jupyter, etc.  

In any case, you can often use the browser's Javascript console (under Developer Tools in Chrome) to see error messages from JS code.

**Comment by philippjfr** [comment]
Also please report whether are using classic notebook or JupyterLab?

**Comment by AsadDUET** [comment]
I am running examples "Introduction.ipynb"
I am using:
  panel- 0.7.0
  bokeh- 1.4.0
  matplotlib- 3.0.3
  jupyter notebook- 5.6.0
  
The js console shows- 
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at E (compiled.js:2)
    at Object.u (compiled.js:25)
    at compiled.js:25

**Comment by AsadDUET** [comment]
> Also please report whether are using classic notebook or JupyterLab?

I am using the classic notebook.

**Comment by philippjfr** [comment]
At this point I'm going to close this as unreproducible. I'd recommend upgrading to the latest versions and trying again. Sorry we couldn't help you here.
