### ISSUE TITLE
The reference example for pane.DataFrame links to widgets.DataFrame

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#939]
If you go to https://panel.holoviz.org/reference/index.html 

![image](https://user-images.githubusercontent.com/42288570/72198954-5445e800-3435-11ea-9423-13ff38c2eaef.png)

and click the Panes - Dataframe link you go to the **widgets example**

https://panel.holoviz.org/reference/widgets/DataFrame.html#gallery-dataframe

and not the **pane example**

https://panel.holoviz.org/reference/panes/DataFrame.html

Futhermore the latter documentation does seem unfinished or the output is just not shown.

![image](https://user-images.githubusercontent.com/42288570/72198942-3a0c0a00-3435-11ea-8513-037b4c76ea94.png)

**Comment by philippjfr** [comment]
Likely a bug in nbsite.

**Comment by philippjfr** [comment]
Fixed in https://github.com/pyviz-dev/nbsite/pull/159
