### ISSUE TITLE
Sensible defaults for widgets.DataFrame

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#940]
#### My Pain

I'm trying to port the YahooQuery app from awesome-streamlit.org to awesome-panel.org. 

One of the things I need is the capability to display DataFrames with data from the Yahoo Finance endpoints. I don't know the shape, headers or rows up front. But I would like to be able to display them to the user so that he can get an impression of what is in there. 

Using the `pn.widgets.DataFrame` I don't really get something useable

![image](https://user-images.githubusercontent.com/42288570/72199080-0631e400-3437-11ea-838c-b945f0ebec4d.png)

```python
from yahooquery import Ticker
import panel as pn

data = Ticker("ORSTED.CO").balance_sheet(frequency="annual")
app = pn.widgets.DataFrame(data, fit_columns=True, sizing_mode="stretch_width")
app.servable()
```

I will say the defaults in the original app are more useable

![image](https://user-images.githubusercontent.com/42288570/72199087-28c3fd00-3437-11ea-8507-fe754f404e64.png)

Although not perfect either because there is no thousands symbol.

#### Solution

Implement sensible defaults for widgets.DataFrame so that you can get 80% of the layout you wan't as default. Enabling nice looking prototypes etc. to be developed rapidly.

My take on sensible defaults is

- minimum column widths should be determined from both the column header and the column data. Both should be visible in full. A horizontal scrollbar should be available if there is overflow.
- Align numeric data right.
- If column data is integers then shown them without decimals.

And keep the thousands symbol. Thats great.

**Comment by MarcSkovMadsen** [comment]
I would be easy to align numeric data right by setting the `text_align="right"` attribute in the file https://github.com/holoviz/panel/blob/master/panel/widgets/tables.py

![image](https://user-images.githubusercontent.com/42288570/72204202-a3137200-3475-11ea-8412-f118c262630f.png)

**Comment by MarcSkovMadsen** [comment]
Before I took at look at the Panel `Dataframe` code I actually implemented a partial solution. See https://discourse.holoviz.org/t/awesome-panel-org-change-log/66/8?u=marc

**Comment by philippjfr** [comment]
Just to be clear, any particular reason you are using the [`DataFrame` widget](https://panel.holoviz.org/reference/panes/DataFrame.html) which is meant for editing tables and not the [`DataFrame` pane](https://panel.holoviz.org/reference/panes/DataFrame.html) which is meant to display tables? Related to the fact that the gallery apparently has issues with objects with the same name?

**Comment by MarcSkovMadsen** [comment]
Yes @philippjfr . I started out with the `DataFrame` pane. 

But there is no sorting or filtering. It does not look like something that will support a lot of data. At least I don't get a scrollbar when using it at awesome-panel.org as far as I remember. Maybe this is just because I don't master this will enough yet :-)

But it looks like this

![image](https://user-images.githubusercontent.com/42288570/72613131-09ddd300-392f-11ea-9110-9a75ca66dea4.png)

If I run the code below

```python
import panel as pn
from yahooquery import Ticker

data = Ticker("ORSTED.CO").balance_sheet(frequency="annual")
app = pn.pane.DataFrame(data, sizing_mode="stretch_width")
app.servable()
```

**Comment by philippjfr** [comment]
The DataFrame pane behavior is a lot nicer now and Tabulator has largely replaced pn.pane.DataFrame. I'm deciding separately whether pn.widgets.DataFrame should now use Tabulator.

**Comment by maximlt** [comment]
Just noting that this is already indicated in the Dataframe widgets doc:

> Also note that the DataFrame widget will eventually be replaced with the [Tabulator](https://panel.holoviz.org/reference/widgets/Tabulator.html) widget, and so new code should be written to use Tabulator instead.

Also wondering whether the DataFrame pane should just be a non-editable Tabulator widget.
