### ISSUE TITLE
Create a pn.Param reference example

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#943]
# My Pain

I think that pn.Param is very important and does not get the attention or detailed explanation that it needs.

As a newbie to Panel I read quickly through the *getting started* and *user guide* and then started experimenting to learn. After that when I needed to understand Panel I wen't to the Reference Gallery as I thought this was the API/ Reference Documentation. It confused me a lot that I could not find pn.Param in there.

Also the example use case of `pn.Param` in the *User Guide - Parameters* section has not provided the level of detail for my use cases. So i've struggled a bit.

- I did not understand how to include only selected parameters via the `parameters` attribute.
- I did not understand how to change the `default_layout`.

I also think that `pn.Param` cannot really layout a complicated Parent-Child Child alone. You need to add in some more layout. That should be in the mix as well.

# Solution

Add a more detailed `pn.Param` example to the Reference Gallery. As it's not a panel, layout or widget (what is it? Why is it not a Pane?) I would suggest adding a section called Other.

**Comment by philippjfr** [comment]
>Why is it not a Pane?

It is in fact a Pane, but a special one. That said I should probably move into the pane sub-package regardless.
