### ISSUE TITLE
Divider isn't documented in reference gallery

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#946]
pn.layout.Divider

**Comment by MarcSkovMadsen** [comment]
Second this. I actually added it to the awesome-panel package because I did not know it existed.

![image](https://user-images.githubusercontent.com/42288570/72447107-07f00480-37b5-11ea-9cfe-d80d216dc620.png)

**Comment by jbednar** [comment]
Seems like a great opportunity for someone to snag an easy PR! :-)
