### ISSUE TITLE
Panel does not layout Altair/ Vega Charts nicely and does not support responsive Charts

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#947]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Tornado 5.1.11
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### My Pain

I would really like to be able to use different plotting libraries with Panel but there is some Friction to using Altair/ Vega because Panel does not layout the plots nicely and/ or support responsive plots.

#### Example

![image](https://user-images.githubusercontent.com/42288570/72495273-8b960980-3826-11ea-9bef-d17b068a8807.png)

I would expect to see 

- four altair Charts below each other.
- The third chart should be full width and horizontally responsive.
- The fourth chart should be full width and height and responsive inside the pink Row.

#### Code

```python
import panel as pn
import altair as alt
import pandas as pd

DATA = {
    "x": [1, 2, 3, 4],
    "y": [2, 4, 6, 8],
}
pn.extension("altair")


def dataframe():
    return pd.DataFrame(DATA)


def chart():
    return (
        alt.Chart(dataframe().reset_index())
        .mark_line()
        .encode(alt.Y("y", scale=alt.Scale(zero=False)), x="x")
    )


def chart_fixed():
    return chart().properties(width=800, height=300,)


def chart_responsive_width():
    return chart().properties(width="container", height=300,)


def chart_responsive():
    return chart().properties(width="container", height="container",)


def view():
    return pn.Column(
        chart(),
        chart_fixed(),
        chart_responsive_width(),
        pn.Row(chart_responsive(), sizing_mode="stretch_width", height=400, background="pink"),
        sizing_mode="stretch_width",
        background="gray",
    )


view().servable()
```

#### Additional Context

**Panel is novel in that it supports nearly all plotting libraries**.

It just works out of the box in Streamlit which makes it so easy to use.

![image](https://user-images.githubusercontent.com/42288570/72495427-f7787200-3826-11ea-8b88-751f4e9147af.png)

https://altair-viz.github.io/user_guide/generated/core/altair.TopLevelLayerSpec.html

![image](https://user-images.githubusercontent.com/42288570/72495648-98672d00-3827-11ea-9894-eaa8e8309626.png)

**Comment by philippjfr** [comment]
So this is what I see on master, not responsive but also not the mess you are seeing:

![Screen Shot 2020-01-16 at 3 11 10 PM](https://user-images.githubusercontent.com/1550771/72531781-7ba41700-3872-11ea-9673-903dadabe73f.png)

**Comment by philippjfr** [comment]
Also if I correctly set the sizing modes on the Vega panes I do get responsive behavior:

![Screen Shot 2020-01-16 at 3 13 28 PM](https://user-images.githubusercontent.com/1550771/72531951-cd4ca180-3872-11ea-80ca-425f48f2e1a1.png)

I can probably automate that.

**Comment by MarcSkovMadsen** [comment]
I can confirm this works in the latest release candidate for Panel v.0.8.0. 

- Full width. Check.
- Responsive. Check.

It's so awesome and important for the use of Panel. And the charts load so increadibly fast. The look and feel of a Panel app using Altair just improved dramatically.

![altair_responsive](https://user-images.githubusercontent.com/42288570/73420268-3d9efc80-4322-11ea-99e1-81963a777e6d.gif)

I will have to test some day if they are actually faster than the bokeh/ holoviews charts.

![image](https://user-images.githubusercontent.com/42288570/73420074-acc82100-4321-11ea-82ce-75b58045a8a5.png)
