### ISSUE TITLE
Parameter not updating when updated

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#974]
#### System Info

- Panel: 0.7.0
- Bokeh: 1.4.0
- Tornado 5.1.11
- Python: 3.7.4
- OS: Windows 8.1
- Browser: Chrome

#### Description of expected behavior and the observed behavior

When setting a parameter dynamically via code I would expect the value of the parameter shown to be updated. But it does not.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import param
import panel as pn
class Test(param.Parameterized):
    window_size = param.Integer(default=6, bounds=(1, 21))
    test = param.Integer()
    
    @param.depends('window_size', watch=True)
    def update(self):
        self.test=self.window_size

    @param.depends("test")
    def view(self):
        return "Test: " + str(self.test)
    
test = Test(name='Test')
pn.Column(test.param, test.view).servable()
```

![param_not_updating](https://user-images.githubusercontent.com/42288570/72777770-1146fa00-3c17-11ea-83c8-f3431a28dd7b.gif)

![image](https://user-images.githubusercontent.com/42288570/72777796-24f26080-3c17-11ea-8fc5-b9b066b9c7f7.png)

**Comment by philippjfr** [comment]
Can't reproduce on master, so unless you can I'll probably close.

**Comment by MarcSkovMadsen** [comment]
Great. 

I have a few more bugs I consider posting. But I have a feeling that the release of 0.8 will solve a lot of things. So I will wait for now.
