### ISSUE TITLE
MultiFileSelector/File browser widget using FileInput widget

### ISSUE THREAD

**Issue by scolobs** [holoviz/panel#975]
I would like to display a MultiFileSelector/File browser widget. I should be able to browse to a folder containing files, choose multiple files, do something with the contents of the files, and display results. Kind of like FileInput widget, but for multiple files
I have tried MultiFileSelector, but it doesn’t allow browsing into a folder to choose multiple files.

**Comment by DancingQuanta** [comment]
How about recently added [FileSelector](https://github.com/holoviz/panel/pull/909) widget which is not yet available in a released version but you can use it from the master of this repo.

**Comment by philippjfr** [comment]
>Is there any way to enable Double Click on the File Browser list to automatically Enter the folder (instead of navigating to the arrow on the right of the path)?

I'm really hoping we can make that happen somehow.

**Comment by thoth291** [comment]
One more issue with FileSelector (in addition to the one mentioned [above](https://github.com/holoviz/panel/issues/975#issuecomment-580377161)) is order in which one selects multiple files.

**Reproducer**: Assume that there are 2 files in your folder: `A.txt` and `B.txt`.
1. If you choose `A.txt` first and `B.txt` second - then the value of your widget will be `['A.txt','B.txt']`. And visually on the selected list of files to the right hand side you will see `A.txt` at the top of `B.txt`.
2. But when you choose `B.txt` first and `A.txt` second - then selected files on the right hand side will be automatically sorted to `A.txt` on the top of `B.txt`, while widget value is `['B.txt','A.txt']`

Is there any way to control this inconsistency of the visual representation of selection of multiple files and what will be returned by widget value?

**Comment by dwsideriusNIST** [comment]
Selection of multiple files is supported in bokeh (https://github.com/bokeh/bokeh/issues/9727), but the interface in panel is not present.

**Comment by philippjfr** [comment]
@dwsideriusNIST Thanks for pointing that out.

**Comment by philippjfr** [comment]
The `multiple` argument to the `FileInput` widget was added in https://github.com/holoviz/panel/pull/1911
