### ISSUE TITLE
VtkJS extension of 3D data viewer

### ISSUE THREAD

**Issue by thoth291** [holoviz/panel#976]
Panel is AMAZING project!
All the ideas behind are so great!
Especially this concept of **develope -> embed -> serve** - truly remarkable modernization of R&D web-python interface!

Recent development with Kitware on VTK support is really amazing.
Especially 3D viewer!

But there are few caveats:

- [ ] I love the fact that it embeds data inside HTML - but is there anyway to **pass an optional save/load parameters**
* where to store the dump of the embedded data
* url/file prefix to load dump back in HTML javascript
* sort of like `save_path` and `load_path` in `panel.embed` function here: https://panel.holoviz.org/user_guide/Deploy_and_Export.html#Embedding

- [x] Visualizing 3D data using VolumeViewer is really awesome - but is there anyway to implement this **3D slicing example (MultiSliceImageMapper)**
* https://kitware.github.io/vtk-js/examples/MultiSliceImageMapper.html
* in some cases it's way more preferable way to visualize data

- [ ] **Integration with `ipyparaview` widget**
* https://github.com/NickLeaf/ipyparaview
* maybe this belongs to `intake` instead of panel - but I'm not sure

Any thoughts, @philippjfr, @jbednar, @jlstevens ?

**Comment by philippjfr** [comment]
>I love the fact that it embeds data inside HTML - but is there anyway to pass an optional save/load parameters

In principle, sure, should be a separate feature request though.

>Visualizing 3D data using VolumeViewer is really awesome - but is there anyway to implement this 3D slicing example (MultiSliceImageMapper)

A good question for @xavArtley.

> Integration with ipyparaview widget

Once bokeh 2.0 is released ipywidgets can be used from within Panel using the ipywidget_bokeh package.

**Comment by xavArtley** [comment]
Hello, `MultiSliceImageMapper` should not be difficult to implement as a separate panel.

**Comment by xavArtley** [comment]
Could look like this
![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/18531147/73011597-d7434700-3e14-11ea-87eb-318ed81b8849.gif)

**Comment by philippjfr** [comment]
@xavArtley You rock!

**Comment by thoth291** [comment]
@xavArtley , this is simply brilliant! Wow!
Two questions:
- where can I get it to try on my data
- will it work on 3D Numpy arrays or it requires something special for that?

**Comment by xavArtley** [comment]
For the moment it's in this branch https://github.com/holoviz/panel/tree/xav/multi_slice_image_mapper
And yes it works like the vtkvolume panel on numpy array and vtkImageData

**Comment by thoth291** [comment]
@xavArtley , I just tested it and it looks beautiful. One thing I noticed is that I cannot embed the widgets actions in HTML - it basically doesn't react when I browse it in the HTML and not within notebook.
For example, VTKVolume works even in HTML embedded mode.

**Comment by philippjfr** [comment]
>One thing I noticed is that I cannot embed the widgets actions in HTML - it basically doesn't react when I browse it in the HTML and not within notebook.

I've just opened https://github.com/holoviz/panel/issues/1003 because this is a prime candidate for that. If the Python based slider -> slice link were converted to JS it would work even in the static export.

**Comment by xavArtley** [comment]
Without changing panel code this should do the trick:
```python
import param
import numpy as np
import panel as pn
import pyvista as pv
from pyvista import examples
pn.extension('vtk')
# Download a volumetric dataset
vol = examples.download_head()
p = pn.pane.vtk.VTKSlicer(vol, origin=(-5,-5,-5), spacing=(3,2,1), sizing_mode='stretch_both')
class SlicerController:
    parameters=[('slice_I', pn.widgets.IntSlider),
                ('slice_J', pn.widgets.IntSlider),
                ('slice_K', pn.widgets.IntSlider),
                ('color_level', pn.widgets.FloatSlider),
                ('color_window', pn.widgets.FloatSlider),]
    
    def __init__(self, slicer):
        for item in self.parameters:
            param_name = item[0]
            param_value = getattr(slicer, param_name)
            param_bounds = slicer.param[param_name].bounds
            widget_type = item[1]
            widget = widget_type(value=param_value,
                                 start=param_bounds[0],
                                 end=param_bounds[1])
            widget.jslink(target=slicer, value=param_name)
            setattr(self, param_name, widget)
            
    def panel(self):
        return pn.Column(*[getattr(self,item[0]) for item in self.parameters])
pn.Row(SlicerController(p).panel(), p, sizing_mode='stretch_both').save('test.html')
```
https://xavartley.github.io/#panel/vtk_examples/vtkSlicer.html

**Comment by thoth291** [comment]
Thank you, @xavArtley! This looks beautiful! Really good example of powerful holoviz infrastructure. As far as I understood it is expected this to show at 0.8. Or will it come earlier?

**Comment by philippjfr** [comment]
Almost certainly later, I'm still trying to get 0.8 out asap. Although I've trying to get in one last major PR (specifically https://github.com/holoviz/panel/issues/1003), which aims to make jslinks more powerful by default and automatically enable them on embed.

**Comment by philippjfr** [comment]
I'll close the save/load has it's own issue and ipywidget integration is on the roadmap (and will just work once we release a version compatible with bokeh 2.0).
