### ISSUE TITLE
Width of the tabs names are being trimmed

### ISSUE THREAD

**Issue by thoth291** [holoviz/panel#983]
Here is the reproducer:
```python
import panel as pn
pn.extension()
import panel.widgets as pnw

def create_tab(fix='',name_list=['A','BBBBB','CCCCCCCCC']):
    m = max(len(e) for e in name_list)
    nameList = [((m-len(e))//2)*fix+e+fix*(m-len(e)-(m-len(e))//2) for e in name_list]
    tab_contents = name_list
    buttons = [pnw.Button(name="Do "+name) for name in name_list]
    return pn.Tabs(*((tab_name,form) for tab_name,form in zip(nameList,buttons)))
def create_tabs():
    return pn.Column(
        pn.Row(create_tab()),     #this is default
        pn.Row(create_tab('_')),  #this is what size I need
        pn.Row(create_tab(' '))   #this is unfortunate `trimming` of the spaces
    )

create_tabs()
```

Here is the image (**second tab is what I'm trying to build in terms of width of the tabs**):
![image](https://user-images.githubusercontent.com/2971670/72920512-112a2580-3d0f-11ea-8b13-b92925d6bb1c.png)

I guess adding spaces to extend the width is not what I should do - but I couldn't figure out a workaround from documentation...

Please help.

**Comment by philippjfr** [comment]
So this is a bokeh issue and should be filed there. In the meantime you can use an [em-space](https://www.compart.com/en/unicode/U+2003).

**Comment by thoth291** [comment]
Just for the future reference I used these spaces:`u'\x85'` and `'\u3000'`
