### ISSUE TITLE
VTK pane not playing well with PanelHTMLBoxView

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#987]
As an example we can notice vtkvolume panels are not well displayed in the developer documentation
https://pyviz-dev.github.io/panel/reference/panes/VTKVolume.html#panes-gallery-vtkvolume
I suppose it is due to the way the PanelHTMLBoxView compute the size of the panel content.
As the vtk panels are filled after the computation of the layout they do not behave like other panes.

**Comment by xavArtley** [comment]
Sorry to reopen but I don't think the issue is solved:
```
import panel as pn
pn.extension('vtk')
dragon = pn.pane.VTK('https://raw.githubusercontent.com/Kitware/vtk-js/master/Data/StanfordDragon.vtkjs',
                     sizing_mode='stretch_both', height=400, enable_keybindings=True, orientation_widget=True,
                     serialize_on_instantiation=True)
dragon
```

result:
- notebook
![image](https://user-images.githubusercontent.com/18531147/72967312-5c047580-3dc1-11ea-8636-5002be48d9b1.png)
- served 
![image](https://user-images.githubusercontent.com/18531147/72967361-78081700-3dc1-11ea-84ed-9b13cd3f1ae3.png)

**Comment by philippjfr** [comment]
I can't reproduce:

![Screen Shot 2020-01-23 at 11 58 48 AM](https://user-images.githubusercontent.com/1550771/72979056-ccb68c80-3dd7-11ea-98d0-50da8a766c76.png)

![Screen Shot 2020-01-23 at 11 57 38 AM](https://user-images.githubusercontent.com/1550771/72978938-96790d00-3dd7-11ea-861e-63c0eba4b467.png)

**Comment by philippjfr** [comment]
Hmm, I see, you're using 'stretch_both', missed that sorry.
